### ISSUE TITLE
elektraKeyGetRelativeName

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1002]
Behavior of elektraKeyGetRelativeName if cur == parentKey:
- document
- add unit tests

**Comment by markus2330** [comment]
tests/shell/shell/*.simpleini need also to be fixed (to be relative)

**Comment by markus2330** [comment]
in the case of simpleini, the parentKey is written as the namespace.

An empty string or a special character might be good solutions?

**Comment by markus2330** [comment]
Is hopefully a very easy testing+docu issue

**Comment by e1528532** [comment]
fixed in #1508

**Comment by markus2330** [comment]
> tests/shell/shell/*.simpleini need also to be fixed (to be relative)

Seems like there are still subtasks left open.
You can also open a new issue if you want.

**Comment by e1528532** [comment]
seems to be fixed in the latest commit
