### ISSUE TITLE
multi-enum

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1005]
I need a multi-enum, i.e. that in a list of words for every word it should be checked if it is an enum (with some specified separator, at the moment I only need space).

I also would prefer a simplified syntax for specifying enum entries for the case when I know that no space will occur within enum entries (not possible anyway because it is the separator for multi-enum).

E.g.:

```
# the * says its a multi-enum
kdb setmeta user/example/enum/value check/enum "* low middle high"
# the old syntax should still work:
kdb setmeta user/example/enum/value check/enum "* 'low', 'middle',  'high'"
kdb set user/example/enum/value low middle # success
kdb set user/example/enum/value high wrong # fail (wrong not part of enum)
```

**Comment by tom-wa** [comment]
i think some restrictions are needed here
there would be too many possible combinations to test with `value = 'low middle'`, `check/enum = "* low 'low middle' high"` or `value = low middle` + `check/enum = "* low 'low middle' middle"`, etc allowed

**Comment by markus2330** [comment]
I am also okay with only the new syntax (space seperated enums). What purpose has the `'`(In one syntax you need to escape `'`, in the other ` `)?

Or we switch to arrays, then we do not have any escaping problem...

**Comment by tom-wa** [comment]
is there anything left to do ?

**Comment by markus2330** [comment]
The multi-enum option for the traditional ("list")-syntax is missing. Btw. I changed the `validateWithArray` so that it rejects duplicate entries. If you think duplicate entries might be useful, that would be another config option.

**Comment by markus2330** [comment]
Thanks for fixing this!
