### ISSUE TITLE
Document dependencies via CONTRACT

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1016]
@Namoshek wrote:

> What I personally would like to see is some collection of all packages you need to get a full installation running.

Currently, most plugins print a warning when they are excluded which dependency was missing. This solution seems to be not satisfactory (see #1015).

## Should replace

- [ ] info in doc/COMPILE.md
- [ ] lists in .travis.yml
- [ ] list in doc/docker/Dockerfile
- [ ] list in doc/vagrant/provision.sh
- [ ] list in puppet hiera
- [ ] the output some plugins provide when they are excluded because of missing deps (see #1889)

## Should support

- [ ] Debian-based systems
- [ ] MacOSX-based systems
- [ ] Others? (Fedora-based systems, Arch-linux-based systems)

## Open questions

Implement it as CMake or Shell script? (Advantage of CMake: already implements logic for interpreting PLUGINS variable, Disadvantage: adds additional step during installation if cmake not available)

I would propose that we describe deps similar to  #1012: in a way that they are written down decentral but we can collect them easily. The main problem is that packages are called differently across distros and versions. So how can we specify them?

What are your requirements and expectations for documentations of the dependencies?

**Comment by Namoshek** [comment]
The most important distros should be documented (debian, ubuntu, redhat, ...). Ideally you could somehow generate package manager commands (`apt-get install ...`) from the enumeration.

If enumerating all possible variations gets too much (quite likely considering how many distros there are), we should maybe limit supported distros for this specific part of documentation? For technical implementation, I think a space separated list of deps for each supported distro(+version) should be enough.

**Comment by markus2330** [comment]
Result of last discussion:

Let us add dependencies information via the contract. First we have to add the dependencies for some package systems (contributors?). Later we can also add functionality in `kdb info` to output all deps of all plugins.

@reox can you add deps for debian/cent os (rpm)?

**Comment by reox** [comment]
Dependecies for CentOS 7 (got from rpm's spec file):
```
boost-devel cmake3 db4-devel docbook-style-xsl doxygen gawk GConf2-devel gettext-devel libxml2-devel libxslt yajl-devel
```

**Comment by reox** [comment]
Found out, there are more dependencies. This is my current list (using CentOS 7.2 and EPEL Repos):

```
gcc-c++ boost-devel cmake3 libdb-devel docbook-style-xsl doxygen GConf2-devel gettext-devel libxml2-devel libxslt yajl-devel libcurl-devel augeas-devel libgit2-devel lua-devel swig python34-devel python-devel graphviz
```

**Comment by markus2330** [comment]
Thanks! How did you find out about gettext-devel? We do not directly search for it neither use it. Which error comes without it?

libxslt seems strange? What is the error there?

**Comment by reox** [comment]
You are right. I removed them and got no problem configuring everything. I did not build the project completly, maybe they are used later on? I think they where already in the old specfile, so I did not removed them.

**Comment by markus2330** [comment]
libxslt might have been necessary for Elektra 0.7 (for building docu), gettext was used a "for the autoconf ICONV macro only" (see 3af69722869be54c56fd7488c2772dea5017e583 "remove old unmaintained rpmspecs"). Thus we do not use autoconf anymore, gettext is not needed anymore.

**Comment by reox** [comment]
but there are some more dependencies, when using `BINDINGS=ALL`:
`java-1.8.0-openjdk-devel jna ruby-devel`

by the way, there is no `ronn` on CentOS, so I used `BUILD_DOCUMENTATION=false` to get rid of the warning.

**Comment by markus2330** [comment]
Thanks for reporting the dependencies!

Yes, ronn is hardly available outside of debian. `BUILD_DOCUMENTATION=false` disables more than the man pages.

**Comment by reox** [comment]
By the way, this is the bare minimum for building on centos 7.2:
```
# Install EPEL for RHEL 7
curl -o epel-release-7-8.noarch.rpm http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm
sudo rpm -ivh epel-release-7-8.noarch.rpm
sudo yum update    
# Bare minimum build tools
sudo yum install -y rpm-build rpmdevtools

# Dependencies of elektra
sudo yum install -y gcc-c++ boost-devel cmake3 libdb-devel docbook-style-xsl doxygen GConf2-devel libxml2-devel yajl-devel libcurl-devel augeas-devel libgit2-devel lua-devel swig python34-devel python-devel graphviz java-1.8.0-openjdk-devel jna ruby-devel byacc
mkdir -p /home/vagrant/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
chown vagrant.vagrant /home/vagrant/rpmbuild -R
# ronn is used for manpages
gem install ronn

```

**Comment by markus2330** [comment]
I added this info in doc/COMPILE.md 97fdbbb635a9681f7b82a1e492cca1be5e17df34

What is the reason for libdb-devel and byacc?

**Comment by reox** [comment]
`libdb` was in the specfile from before... did not checked that. maybe berkeley-db isnt used anymore?

`byacc` was added by @krit0n - dunno what that is for.

**Comment by markus2330** [comment]
> berkeley-db isnt used anymore?

Yes, it isn't used anymore. (Was never used in Elektra 0.8)

> byacc

@krit0n can you explain?

> And here are some more information about dependencies:

Thank you, I added the swig3 in 5c235c80f0f75530d1af773fbc044aec3e4f19b9
The ronn information was already added yesterday.

> EPEL Section

Whats that? What exactly should I write? (How to enable it?)

> I can check for the new CentOS 7.3 now.

Thank you, that would be great!

**Comment by reox** [comment]
EPEL https://fedoraproject.org/wiki/EPEL
it's another package source basically.

Idk, maybe centos/RHEL/fedora users are aware of those repos...

How to enable them on centos:
```
# Install EPEL for RHEL 7
curl -o epel-release-7-8.noarch.rpm http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm
sudo rpm -ivh epel-release-7-8.noarch.rpm
sudo yum update    
```

**Comment by markus2330** [comment]
Thanks, I added the information!

1c26994c2279c5fed3b8fa121605a52e39488c5f

**Comment by ingwinlu** [comment]
there is also https://github.com/ElektraInitiative/libelektra/blob/master/cmake/PrintDependencies.cmake

**Comment by markus2330** [comment]
Yes, cmake/PrintDependencies.cmake was a feasibility study by me if it is possible to do everything within CMake. While it is possible it might be too much (unnecessary) effort. The only advantage of CMake is the better portability.

A simple shell script similar to tests/shell/check_meta.sh which concatenates all dependencies within the contracts of the plugins would be much easier to write.

The main work would be to decide how the entries in the contract should be named (With decisions like: Can all rpm distributions be put into one clause?) and then collect how these dependencies are called in the rpm, deb, and homebrew world.
