### ISSUE TITLE
foreach hooks

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1017]
For the foreach hooks, it would be necessary to inform the plugin how often it gets called and in which state it currently is.

Metadata might work fine for doing so but some performance improvements might be necessary. I suggest to use keyCopyMeta instead of keySetMeta. The idea is as follows: you have Keys that have every metadata already prepared and do a lookup and copy the metadata from them to the parentKeys.

Then we would have only KeySet operations but no creations of keys during kdbGet()/kdbSet().

Furthermore we should document how the parent keys flow through all plugins and hooks.
(The flow is relevant if plugins want to communicate with each other via metadata)

**Comment by mpranj** [comment]
Thanks for the input, I'll keep this in mind when I get to the foreach hooks.
