### ISSUE TITLE
website: object Object  to  object Object 

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1036]
When creating an github issue, the title of the github issue says: "object Object  to  object Object"

**Comment by Namoshek** [comment]
Already fixed locally, but not worth a push yet. :+1:

**Comment by markus2330** [comment]
Ok ;)

**Comment by markus2330** [comment]
Btw. usually issues are only closed if the fix is merged to master.

But that should be easier to follow after the merge+going online in November.

**Comment by Namoshek** [comment]
Ok, sorry. I found it so minor that I fixed it already while we were talking during the meeting and because the whole application is still in progress, it seemed odd to have full tracking of a simple bug like this.
