### ISSUE TITLE
Separate namespace with key path

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1037]
Separate namespaces with `:`.
Grammar:
`[ <namespace> ’:’ ] ’/’ <relative key name>`

 E.g. for an absolute key name `/something` in the namespace `user` we have `user:/something`.

**Comment by markus2330** [comment]
It sounds quite reasonable to do this for 1.0. Within the specs needed by @tom-wa always writing the full name does not work. And clearly visible namespaces are a prerequisite to have a way to reliably distinguish key names and relative key names.

So we would have colon `:` also as something with needs to be escaped (but only if it is directly before slashes).

@sanssecours @domhof What do you think, do you agree to do this for 1.0?

**Comment by sanssecours** [comment]
Separating the namespace part with a colon sounds like a good idea.

> Separate namespaces with `:`, e.g. `user:/something`.

Why do you prefix `something` with a slash here? Would `user:something` be the same as `user:/something`?

**Comment by markus2330** [comment]
Thanks for supporting it!

> Why do you prefix something with a slash here?

Because in the example I used an absolute key name.

The grammar for absolute key names would be:
`[ <namespace> ’:’ ] ’/’ <relative key name>`

Of course we also could allow relative key names with namespaces, which would be `user:something`. But this was not needed up to now, thus I am against introducing it. (It would need colon to be escaped everywhere or make the escaping rules even more complex.)

I updated the proposal above.

**Comment by sanssecours** [comment]
I do not think prefixing a relative key name with a namespace makes much sense. For example, if we use the command:

```sh
kdb set user:relative/to/what value
``` 

, then which key name would this command set to `value`? What about the command

```sh
kdb mv user:relative/to/what system:where/am/i
```

? In my opinion it would make more sense to always require a leading namespace (such as `dir`, `user`, `system`)  in absolute key names and consequently drop the leading slash (e.g. `user:absolute/path`, `spec:ab/so/lute`). Everything else (e.g. `relative/key`, `/relative/key`, `../yet/another/relative/key`) would then be interpreted as relative/cascading key name.

**Comment by markus2330** [comment]
> I do not think prefixing a relative key name with a namespace makes much sense.

I agree! I am against introducing them.

> What about the command

Actually for `kdb mv` relative keys (but without namespace) *could* be used (the second key could use the first key as starting point), e.g.:

`kdb mv user:/absolute/key relative # renames user:/absolute/key to user:/absolute/relative`

I do not recommend to introduce such feature, it is non-standard and will confuse people expecting `mv` semantics.

> In my opinion it would make more sense to always require a leading namespace

Always having absolute names (which I would be in favor!) creates huge inconveniences for @tom-wa validation plugins. You want to write

```
kdb setmeta user:/examples/mathcheck/k check/math "== + a b"
# and not
kdb setmeta user:examples/mathcheck/k check/math "== + user:examples/mathcheck/k/a user:examples/mathcheck/k/b"
```

> Everything else would then be interpreted as relative/cascading key name.

Can you elaborate please? Relative and cascading key names are completely separate concepts, how can you distinguish them in your proposal?

In my current proposal it is:
```
/this/is/a/cascading/key # for lookup in any namespace
user:/this/is/a/user/key # absolute names to uniquely identify keys on disk
this/is/a/relative/key # cannot be alone, needs key it refers to
# namespace then will be as in key it refers to
```

And if we really want to stick to it (I am not sure if we should have it and I am not happy with the syntax):
```
@/this/is/relative/to/parent/key
```

**Comment by sanssecours** [comment]
> Always having absolute names (which I would be in favor!) creates huge inconveniences for @tom-wa validation plugins.

I do not like the idea of always requiring absolute key names. As you already pointed out always using absolute names is quite cumbersome.

> Can you elaborate please? Relative and cascading key names are completely separate concepts…?

Relative key names and cascading key names are not that different in my opinion. The difference between a relative and an absolute value in the most general sense is that an **absolute value** specifies the **whole information** you want, while a **relative value** only specifies **part of that information**.

Similar, an absolute key name specifies the exact position of a value in the key value database, while a relative key only specifies the exact position, if we add additional information in form of a prefix. The difference between a cascading key name and relative key name is that in the first case we need only the namespace prefix (`user`, `system`, …), while in the second case we need both a namespace prefix and a key name prefix.

> …, how can you distinguish them in your proposal?

You can not. I did not think about that issue.

> In my current proposal it is…

Looks good to me.

> And if we really want to stick to it (I am not sure if we should have it and I am not happy with the syntax):
> ```
> @/this/is/relative/to/parent/key
> ```

Why would you not use `this/is/relative/to/parent/key` in this case? What is the semantic of the `@` sign here?

**Comment by markus2330** [comment]
> Relative key names and cascading key names are not that different in my opinion.

From configuration point of view they are very different, because with cascading keys you have a specified way to find the corresponding key. Relative keys alone are  useless, you have no glue where they are, or which one is meant.

Of course it would be possible to avoid this difference, but then Elektra would be a key-value framework barely related to configuration anymore. Multiple sources for the same configuration setting are an essential functionality for a configuration setting framework.

> absolute value specifies the whole information you want,

Yes, but there are two different viewpoints of what "whole information" is, so we have three possibilities:

1. namespace+absolute key (e.g. user:/key): we exactly (physically) know which key is meant
2. cascading key (e.g. /key): we refer to exactly zero or one key, but we need other keys to  know which one  (namespaces and spec influence the lookup)
3. relative key (e.g. key): might refer to many keys. Even if you have an export of all keys on a system it might still be ambiguous which key is meant.

> Why would you not use this/is/relative/to/parent/key in this case?

@tom-wa said it would be handy, even though in a quite large specification partly written by @tom-wa  it is not used once. I do not know a good reason.

We really should consider removing it.

> What is the semantic of the @ sign here?

It refers to the mountpoint. From my point of view it is even dangerous, because submountpoints change the semantics of the specification in possibly unexpected ways. (Granted that introducing submountpoints always has the potential to break specifications: if keys refer to keys outside of the submountpoint they would not be found.)

**Comment by sanssecours** [comment]
> @tom-wa said it would be handy, even though in a quite large specification partly written by @tom-wa it is not used once. I do not know a good reason.

Thank you for the information.

> We really should consider removing it.

I think so too.
