### ISSUE TITLE
libs: add READMEs

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1039]
Add a readme for libs

**Comment by Namoshek** [comment]
I'd like to also have readmes for all individual bindings enumerated in `src/bindings/README.md`, because several bindings are in sub-sub-folders and therefore I think parsing the readme is a nicer solution that listing directories.

**Comment by markus2330** [comment]
@BernhardDenner Can you provide a README.md for all three swig bindings?

**Comment by markus2330** [comment]
Done, all bindings are listed in the README.
