### ISSUE TITLE
ELEKTRA_PLUGIN_NAME

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1042]
Build system should provide:
- a string that contains the plugin/module name
- a non-string variant of the plugin/module name

Then ELEKTRA_PLUGIN_EXPORT, ELEKTRA_PLUGIN_FUNCTION, ELEKTRA_README would have one paramter less.

**Comment by markus2330** [comment]
@petermax2 Do you maybe want to implement this?

**Comment by petermax2** [comment]
Yes, you can assign me if the implementation is not time critical. At the moment I have not so much spare time.

**Comment by markus2330** [comment]
Thank you for working on this!

The actual reason to do this, is that every plugin has something like CRYPTO_PLUGIN_FUNCTION available and that CRYPTO_PLUGIN_FUNCTION is not needed anymore.

Btw. ARG_COMPILE_DEFINITIONS cannot be modified (due to restore_variable), so simply add further definitions in cmake/Modules/LibAddPlugin.cmake line 155 (where COMPILE_DEFINITIONS are defined).

**Comment by markus2330** [comment]
Great that you have progress!

**Comment by petermax2** [comment]
@markus2330  the build server reported

    Caught the following exception: null

Is this a know bug?

**Comment by petermax2** [comment]
### Progress so far

#2360 : The CMake module `add_plugin` provides the following compiler definitions for every plugin:

- **ELEKTRA_PLUGIN_NAME**: the plugin name (including the variant if any) as string
- **ELEKTRA_PLUGIN_NAME_C**: the plugin name without quotes, so it can be used to construct function names, that depend on the plugin name/variant.

The removal of unnecessary parameters of `ELEKTRA_PLUGIN_FUNCTION` and `CRYPTO_PLUGIN_FUNCTION` will be implemented in another PR.

**Comment by markus2330** [comment]
So ELEKTRA_PLUGIN_EXPORT and ELEKTRA_README are the last left-overs?

**Comment by petermax2** [comment]
> So ELEKTRA_PLUGIN_EXPORT and ELEKTRA_README are the last left-overs?

Yes, should be very easy and straight-forward now that `ELEKTRA_PLUGIN_FUNCTION` works.

**Comment by markus2330** [comment]
We finally did it!
