### ISSUE TITLE
csvstorage improvements

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1045]
csvstorage could be enhanced with other features as described in https://tools.ietf.org/html/rfc4180

**Comment by tom-wa** [comment]
>   7.  If double-quotes are used to enclose fields, then a double-quote
       appearing inside a field must be escaped by preceding it with
       another double quote.  For example:

>      "aaa","b""bb","ccc"

how should happen in case of `"aaa","b"bb","ccc"` ? i'd say a warning is enough since i can parse it just fine, what do you think ?

**Comment by markus2330** [comment]
In the long term we need a "strict" mode. But as our current main goal is to work with the files that are lying around in `/etc`, you are right: we should accept it with a warning.
