### ISSUE TITLE
Implement file plugin

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1047]
Hello newcomer,

Sometimes it is useful to have the content of the whole file to be the value of a single key. (e.g. in combination with the blockresolver or with some trivial configuration files such as `/etc/motd`)

To achieve this, you have to create a new plugin (see https://github.com/ElektraInitiative/libelektra/blob/master/doc/tutorials/plugins.md ). You only have to implement kdbGet and kdbSet:
- in kdbGet you create a new key with the name of the parentKey, then read the whole content of the file (file name given by string in parentKey) and set as value of the key you just created. Then append it to returned.
- in kdbSet you do the opposite: you lookup the key with the name of the parentKey and rewrite the whole file with its value

To complete the task, please:
- [ ] implement as described above
- [ ] fully fill out README.md. For tricky parts (provides, placements) you can peek into the READMEs of other storage plugins.
- [ ] handle all errors (also peek in other storage plugins what to do on I/O errors)
- [ ] add unit tests demonstrating that a file read and written again stays the same (you guessed it, other storage plugins do the same)
- [ ] remove not needed parts of template (open, close, error)

Please write something below before starting the task. You can always ask here for help.

**Comment by tom-wa** [comment]
would you mind if i do this one ? together with the multifile resolver many parts of /sys could be mounted/used

**Comment by markus2330** [comment]
I would suggest @e1528532 could do it (if he has time in the next days?) He needs to get into dev of plugins and this one certainly is easier than the xml one.

**Comment by tom-wa** [comment]
should the plugin detect automatically if the file (and key) contains binary data and create a binary key, or default to string and allow to configure it to read/write binary data ?

**Comment by markus2330** [comment]
You cannot reliably detect if its binary from the content: binary does not have to contain null bytes.

What about abusing the executable bit to tell if its binary?

Btw. as future extension all file meta data could be mapped as meta data. See "Old stuff inherited from filesys plugin" for meta data description. We should use some prefix before this names, though. Maybe `file/*`?

**Comment by tom-wa** [comment]
>What about abusing the executable bit to tell if its binary?

i think most binary files that we would like to mount aren't executeable. currently i default to string if the plugin configuration doesn't specify otherwise

**Comment by tom-wa** [comment]
can we close this one or is there still something left ?

**Comment by markus2330** [comment]
Thanks for reminding!
