### ISSUE TITLE
Crypto: Utilize libinvoke

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#1049]
# Problem

The ~~latest~~ compile error ( #1043 ) revealed a design flaw in shared code from the plugins:
- crypto
- fcrypt
- base64

These plugins share two common functionalities:
- GPG interface (`crypto/gpg.c`)
- Base64 encoding / decoding (`base64/base64_functions.c`)

Statically linked builds caused troubles with function name resolution, as the shared code is compiled per plugin.

Utilizing `libinvoke` solves the problem, if the `base64` plugin exports its encoding functions properly.

~~Moving these features to a library (or maybe two libraries) would reduce compile time and lead towards a cleaner API. Also readability in affected `CMakeLists.txt` files would increase, because instead of~~
- ~~including the source files from other plugins~~
- ~~adding the plugin source folder to the include path~~

~~a single line to the call of `add_plugin` is required instead: `LINK_ELETRA elektra-libname`.~~

# Proposal

- The `base64` plugin exports its encoding functions.
- The `crypto` plugin utilizes `libinvoke` to encode/decode Base64 strings.
- The `crypto` plugin no longer compiles the source files of the `base64` plugin into its code, thus eliminating the need for complicated `ELEKTRA_PLUGIN_FUNCTION` macro uses.

EDIT: update proposal, edit problem statement

**Comment by markus2330** [comment]
Some quick thoughts:

- What about a library that does not only execute gpg, but can be used to invoke any process? (gpg only as convenience wrapper)
- I am not conviced that encoding functionality should be moved to a library, but we should rather fix the plugin system by either:
  1. allow plugin configuration to be encoded (this seems the reason why crypto depends on base64). A quite easy way to do so would be to add an encoding and the boolean plugin in `elektraBackendOpenDefault`.
  2. Load plugins from other plugins: Actually you could easily introduce a soft dependency from crypto to base64 which only uses base64 if it was found at runtime (keep binary key, otherwise).

**Comment by petermax2** [comment]
> What about a library that does not only execute gpg, but can be used to invoke any process? 

Sounds good. Especially if we want to support OS that do not provide `fork` (thinking about Windows).

> Load plugins from other plugins: Actually you could easily introduce a soft dependency from crypto to base64 which only uses base64 if it was found at runtime (keep binary key, otherwise).

That would be great. Although I see a way how the crypto plugin could live without any base64 encoding at all. Nevertheless I think having the possibility to use other plugins code is generally a good thing. However, I would like to have access not only to the kdb functions (`get`, `set`, etc.) but also to the encoding functions itself (for the base64 plugin).

**Comment by markus2330** [comment]
> Sounds good. Especially if we want to support OS that do not provide fork (thinking about Windows).

Yes, and a spawning functionality is also used across other parts in Elektra, e.g. `kdb editor`, `kdb external`, and `shell plugin`.

> Although I see a way how the crypto plugin could live without any base64 encoding at all.

Tell me more!

> Nevertheless I think having the possibility to use other plugins code is generally a good thing. However, I would like to have access not only to the kdb functions (get, set, etc.) but also to the encoding functions itself (for the base64 plugin). 

Isn't this  #922?
