### ISSUE TITLE
fcrypt: conflict on set

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1050]
# Describe what you wanted to do

Change encrypted file again.
# Describe what you expected

```
kdb set /t/a "hello world"
kdb set /t/a "hello world2" #-> should update value
```
# Describe what actually happened

An error occurred:

```
Using name user/t/a
Set string to hello world
The command set failed while accessing the key database with the info:
Error (#30) occurred!
Description: A conflict occurred: Another KDB instance modified the key database.
Ingroup: plugin
Module: resolver
At: /home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/resolver/resolver.c:742
Reason: conflict, file modification time stamp 1477249556.813719088 is different than our time stamp 1477249522.621116829, config file name is "/home/markus/.config/crypt.ecf", our identity is uid: 500, euid: 500, gid: 100, egid: 100
Mountpoint: user/t
Configfile: /home/markus/.config/crypt.ecf.4852:1477249556.781814.tmp
```

Seems like the time stamp is updated after the resolver took the timestamp for conflict detection.

You might need to restore previous timestamps via futimens. The bug report is low priority (it is enough if it is within the release), try first if the /proc/fd trick works.

Thanks!
# System Information
- Elektra Version: master
# Notes
# Further Log Files and Output

**Comment by markus2330** [comment]
Any solution in sight? Can we fix this for 0.8.19?

**Comment by petermax2** [comment]
> Any solution in sight? Can we fix this for 0.8.19?

I will try to have it fixed until the weekend.

**Comment by markus2330** [comment]
Thank you! Would be great to release with a usable fcrypt!

**Comment by petermax2** [comment]
How do I determine the right timestamp to recover? I get an odd `mtime` in `fcrypt / set`. See listing below:

    $ kdb set user/t/a "hi3"
         resolver updates handle value at kdb set to ts 1479393909.236515253
         resolver updates handle value at kdb set to ts 1479393909.236515253
         resolver updates handle value at kdb set to ts 1479387838.577156737
         resolver updates handle value at kdb set to ts 1479387837.473203413
         resolver updates handle value at kdb set to ts 1479394756.944976325
         fcrypt reads timestamp using stat(): 1479394855.173913482
    Set string to hi3
         fcrypt reads timestamp using stat(): 1479394855.180913193
    The command set failed while accessing the key database with the info:
    Error (#30) occurred!
    Description: A conflict occurred: Another KDB instance modified the key database.
    Ingroup: plugin
    Module: resolver
    At: /home/pnirschl/Projekte/libelektra/src/plugins/resolver/resolver.c:732
    Reason: conflict, file modification time stamp 1479394855.179913234 is different than our time stamp 1479394756.944976325, config file name is "/home/pnirschl/.config/./t.ecf", our identity is uid: 1000, euid: 1000, gid: 1000, egid: 1000
    Mountpoint: user/t
    Configfile: /home/pnirschl/.config/./t.ecf.26720:1479394854.245524.tmp

The resolver expects `1479394756.944976325` but on `keyString(parentKey)` the value `1479394855.180913193` is actually read by `stat()`.

**Comment by markus2330** [comment]
You need to get the timestamp using stat and restore it with futimens.

**Comment by petermax2** [comment]
But `stat()` does **not** return the timestamp that the resolver expects.

**Comment by markus2330** [comment]
The resolver assumes that it is the only plugin that modifies the original config file. (All others should only write to the temporary file as given by the resolver.) So you need to fake that you did not touch it at all.

in which system does stat+modify+futimens not leave the timestamp of the file as if it was never modified?

**Comment by petermax2** [comment]
I was measuring at the wrong point.

Fcrypt has to save the timestamp in `kdb get` when in `PREGETSTORAGE` mode. The timestamp will be written to the plugin handle (mainly like the resolver does). In `kdb set` fcrypt restores the timestamp from the plugin handle.

**Comment by markus2330** [comment]
Another strange (related?) error: testmod_fcrypt fails if you run it with `kdb run_all` (I tried it 3x). It does not fail when you run it separately (`kdb testmod_fcrypt`, I tried it several hundret times).

```
--- running testmod_fcrypt ---


FCRYPT       TESTS
==================

/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/fcrypt/testmod_fcrypt.c:50: error in writeTestFile: can not write to temporary file
/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/fcrypt/testmod_fcrypt.c:156: error in test_file_operations: kdb set failed
/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/fcrypt/testmod_fcrypt.c:68: error in isTestFileCorrect: can not read from temporary file
/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/fcrypt/testmod_fcrypt.c:160: error in test_file_operations: kdb get (pregetstorage) failed
/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/fcrypt/testmod_fcrypt.c:68: error in isTestFileCorrect: can not read from temporary file
/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/fcrypt/testmod_fcrypt.c:161: error in test_file_operations: file content could not be restored during decryption
/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/fcrypt/testmod_fcrypt.c:164: error in test_file_operations: kdb get (postgetstorage) failed
/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/fcrypt/testmod_fcrypt.c:68: error in isTestFileCorrect: can not read from temporary file

fcrypt RESULTS: 23 test(s) done. 8 error(s).
error: testmod_fcrypt

....


+ exit 0
Following test cases failed:
testmod_fcrypt
run_all RESULTS: 667 test(s) done 1 error(s).
```

Any ideas? Hopefully it gets fixed anyway when you fix the known fcrypt bug.

**Comment by petermax2** [comment]
> Any ideas?

Not yet but at least I fixed the bug above. The timestamp also has to be restored in `kdb get / postgetstorage`.
