### ISSUE TITLE
Tutorial doesn't work

### ISSUE THREAD

**Issue by eschnett** [ElektraInitiative/libelektra#1055]
I'm following the tutorial on `https://github.com/ElektraInitiative/libelektra`. I'm using macOS Sierra. I downloaded, configured, built, and installed libelektra without problems.

This is what I typed, and the responses I received:

```
$ kdb export user/hello ini
eschnett@Redshift:~ (15:53:24)
$ kdb export user/hello simpleini
The command export terminated unsuccessfully with the info:
Was not able to load such a plugin!

Maybe you misspelled it, there is no such plugin or the loader has problems.
You might want to try to set LD_LIBRARY_PATH, use kdb-full or kdb-static.
Errors/Warnings during loading were:
1 Warning was issued:
 Warning number: 1
    Description: could not load module, dlopen failed
    Ingroup: modules
    Module: dl
    At: /Users/eschnett/src/libelektra/src/libs/loader/dl.c:86
    Reason: of module: libelektra-simpleini.so, because: dlopen(libelektra-simpleini.so, 2): image not found
    Mountpoint:
    Configfile:
```
- Note that my first command didn't lead to any output. The tutorial shows output `hello_world = ...`.
- The second command fails.
- The error suggests running `kdb-full` or `kdb-static` instead, but no such file was built or installed.

**Comment by markus2330** [comment]
Thanks for trying the tutorial! The second problem you encountered is that `simpleini` is not portable and does not work with Mac OS X. Thus it is disabled during compilation on your computer and not available at run-time. We plan to implement #701 to have a plugin with identical features on Mac OS X, too.

For the first problem the tutorial seems to be incomplete, can you point me to which tutorial you followed? To get the expected output you would need a `kdb set user/hello/hello_world ...` before.

**Comment by eschnett** [comment]
On the page I mentioned, look for the text `Here a small demo:`. I typed the text visible in the screen shot there.

**Comment by markus2330** [comment]
Ahh, now I understand! That is an automatic preview of the ascii screencast. The screenshot is not self-contained but needs the already mentioned `kdb set user/hello/hello_world ...` before. (As shown in the ascii screencast [when you click on play](https://asciinema.org/a/cantr04assr4jkv8v34uz9b8r).)

For the next video I will try to get a preview that shows something self-contained. The software asciicast seems to pick a screenshot from somewhere in the middle...

**Comment by eschnett** [comment]
I am looking at the demo, and tried to follow along. This doesn't work for me:
- The first command in the movie doesn't output anything. For me, I get a long list of error messages, ending with
`
IMPORTANT: Make sure you can write to system namespace
           Usually you need to be root for that!
`
- At about second 28, the command `kdb file user/hello/hello_world` outputs a file name. This is a file `hello.ini` in the demo. For me, this is a file `default.ecf`.

I've also looked for actual tutorials that would be easier to follow along than a movie. I've found a link `tutorial` on the main readme. However, this only leads to the page `https://github.com/ElektraInitiative/libelektra/tree/master/doc/tutorials` which holds a list of tutorials without further explanation. None of these seem to do something similar to the demo. I then looked at `validation.md`, but this seems to be an advanced tutorial that expects some background. The commands shown there don't work when I just type them in.

By way of explanation: I'm looking for a "follow-along" tutorial where I can read some text and type in some commands to explore the features offered by Elektra. The tutorials you're offering seem to be different; they probably assume some familiarity with Elektra, and then teach how to perform a particular task.

**Comment by markus2330** [comment]
> IMPORTANT: Make sure you can write to system namespace Usually you need to be root for that! 

Yes, mounting writes to `/etc/kdb/elektra.ecf` (or whatever `kdb file system/elektra/mountpoints` outputs) and thus you need to be root or follow the instructions given [here](git.libelektra.org/blob/master/doc/TESTING.md). I tried to improve the error message in 42d786f63078fe6294ee02fb18f6addc369224a8.

> At about second 28, the command kdb file user/hello/hello_world outputs a file name. This is a file hello.ini in the demo. For me, this is a file default.ecf.

This is expected because the mounting did not work. `default.ecf` is used when there is no mountpoint.

> which holds a list of tutorials without further explanation

I added a [explanation](https://github.com/ElektraInitiative/libelektra/tree/master/doc/tutorials/README.md).

> they probably assume some familiarity with Elektra

Yes, unfortunately they currently do. We will inform you when we fixed it.

**Comment by markus2330** [comment]
Thanks for your great feedback! We improved the tutorials, now we have tutorials suitable without prior familiarity, in particular: http://tree.libelektra.org/doc/tutorials/mount.md
