### ISSUE TITLE
Compile error on FreeBSD11

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#1058]
# Describe what you wanted to do

Compile `fcrypt` on FreeBSD 11 with clang 3.8.
# Describe what you expected

A successful build.
# Describe what actually happened

```
/usr/home/pnirschl/Projekte/libelektra/src/plugins/fcrypt/fcrypt.c:181:12: error: static
      declaration of 'encrypt' follows non-static declaration
static int encrypt (KeySet * pluginConfig, Key * parentKey)
       ^
/usr/include/unistd.h:452:6: note: previous declaration is here
int      encrypt(char *, int);
     ^
```
# System Information
- Elektra Version: master
- Versions of other relevant software?
  
  $ freebsd-version
  11.0-RELEASE-p2
  $ clang --version
  FreeBSD clang version 3.8.0 (tags/RELEASE_380/final 262564) (based on LLVM 3.8.0)
# Further Log Files and Output

**Comment by markus2330** [comment]
Thank you for reporting! Strange that no other compiler said something about this.
