### ISSUE TITLE
Compile error w/o swig installed

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1065]
```
-- Command "/usr/bin/swig3.0 -swiglib" failed with output:

CMake Error at src/bindings/swig/python2/CMakeLists.txt:1 (include):
  include called with wrong number of arguments.  include() only takes one
  file.


-- Include Binding swig_python2
CMake Error at src/bindings/swig/python2/CMakeLists.txt:35 (swig_add_module):
  Unknown CMake command "swig_add_module".
```

**Comment by mayankBIL** [comment]
I am also getting the same error while building RDKit using 'Cmake'.  please help.

**Comment by markus2330** [comment]
Hi! Thanks for conforming the issue! Which system do you use?

There are two, hopefully easy, ways to workaround this issue:

- exclude swig bindings from `BINDINGS`, e.g. you can call `cmake -DBINDINGS=cpp .` (or with path to elektra source instead of `.` if calling cmake for the first time)
- install swig3.0 and/or pass the correct swig executable, e.g. `-DSWIG_EXECUTABLE=/usr/bin/swig3.0`

**Comment by mayankBIL** [comment]
Hey! Thanks for quick reply. I figured it out, there was problem in my SWIG installation. After correctly re-installing SWIG, error disappeared.

**Comment by Stonesjtu** [comment]
I followed the FAQ page of cmake and found an additional `include` may solve this problem on UBUNTU 16.04
>How do I use CMake to generate SWIG wrapper libraries?
CMake version 2 includes a module that supports the generation of SWIG wrapper libraries. The SWIG package defines the following macros: SWIG_ADD_MODULE and SWIG_LINK_LIBRARIES.
```cmake
# This example shows how to use python
# Currently these languages have been tested:
#  perl tcl ruby php4 pike

FIND_PACKAGE(SWIG REQUIRED)
INCLUDE(${SWIG_USE_FILE})

FIND_PACKAGE(PythonLibs)
INCLUDE_DIRECTORIES(${PYTHON_INCLUDE_PATH})

INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR})

SET(CMAKE_SWIG_FLAGS "")

SET_SOURCE_FILES_PROPERTIES(example.i PROPERTIES CPLUSPLUS ON)
SET_SOURCE_FILES_PROPERTIES(example.i PROPERTIES SWIG_FLAGS "-includeall")
SWIG_ADD_MODULE(example python
  example.i example.cxx)
SWIG_LINK_LIBRARIES(example ${PYTHON_LIBRARIES})
```

**Comment by markus2330** [comment]
Thank you for your comment.

Which additional `include` do you mean? We already use `include (${SWIG_USE_FILE}`, `swig_add_module`, and `swig_link_libraries`.

**Comment by Stonesjtu** [comment]
The `INCLUDE(${SWIG_USE_FILE})` exactly.

**Comment by smartboy666** [comment]
Thanks to **Stonesjtu**. The `FIND_PACKAGE(SWIG REQUIRED)` can solve this problem.

**Comment by markus2330** [comment]
Thank you for this info! Is there also a change within Elektra needed?
