### ISSUE TITLE
Untested used internal function

### ISSUE THREAD

**Issue by KurtMi** [ElektraInitiative/libelektra#1067]
Here a list of untested internal functions:

- [ ] splitUpdateFileName 
- [ ] backendOpenMissing
- [ ] backendOpenDefault
- [ ] backendOpenMissing
- [ ] backendOpenModules
- [ ] backendOpenVersion
- [ ] backendUpdateSize
- [ ] mountGlobals
- [ ] mountVersion

maybe we should write test cases for those.

**Comment by markus2330** [comment]
Thanks for opening the issue, we definitely should test them more!
