### ISSUE TITLE
3 way merge: conflict_meta deletes key content

### ISSUE THREAD

**Issue by fberlakovich** [ElektraInitiative/libelektra#107]
The merge framework contains some TODOs and some parts need more extensive testing

**Comment by markus2330** [comment]
The next release contains an ABI/API break in libtools, so its a good time for some cleanup now.

**Comment by fberlakovich** [comment]
> Additionally I propose that we split libtools to libtools and libmerge, what do you think?

Sounds reasonable. I was hoping that the merge framework would be extended anyway. However, it still contains some parts I am not really happy with, but I couldn't come up with a better solution yet.

**Comment by markus2330** [comment]
I am afraid the splitup is already very difficult (more than a year passed in the meantime, some tool code already uses merge code and the other way round).

But there are useful cleanups/improvements nevertheless.

**Comment by markus2330** [comment]
See TODO in src/merging/metamergestrategy.cpp line 83

**Comment by markus2330** [comment]
@Chemin1 is this relevant or already fixed with your new merging framework?

**Comment by Chemin1** [comment]
From a quick look I'm not really sure how the [todo](https://github.com/ElektraInitiative/libelektra/blob/e82b55f0d3ea4c77f3a4c04fa217084021bd8e4b/src/libs/tools/src/merging/metamergestrategy.cpp#L83) from metamergestrategy.cpp relates to what I wrote. Based on what we thought about meta data we made handling it (including when it is overwritten) very much dependent on the not-meta data.

**Comment by markus2330** [comment]
Let us close it if it only confuses. I hope your new merging framework is used everywhere soon, then the bug will truly be closed.
