### ISSUE TITLE
cmake: changes README.md do not trigger rebuild

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1075]
Cmake is not called automatically when README.md are changed

**Comment by kodebach** [comment]
Pretty sure this link is solved by line 629 in LibAddMacros.cmake (at least for those README.md files that use generate_readme):

https://github.com/ElektraInitiative/libelektra/blob/ab01f77af560dd98c424e2e3df2ffeed4f3d2730/scripts/cmake/Modules/LibAddMacros.cmake#L628-L629

**Comment by markus2330** [comment]
Jup, worked for me in the dbus plugin.
