### ISSUE TITLE
Mounting in dir namespace doesn't work for same path

### ISSUE THREAD

**Issue by krit0n** [ElektraInitiative/libelektra#1080]
# Describe what you wanted to do
I tried to mount a configuration into the dir namespace that was already mounted in another directory under the same path.

# Describe what you expected
I expected this to succeed.

# Describe what actually happened
        $ mkdir x && cd $_
        $ sudo kdb mount x.ini dir/myconfig ini
        $ cd .. && mkdir y && cd $_
        $ sudo kdb mount y.ini dir/myconfig ini
        The command mount terminated unsuccessfully with the info:
        Mountpoint dir/myconfig is one of the already used names: dir/myconfig 
# System Information

- Elektra Version: 0.8.18

**Comment by krit0n** [comment]
When you use Elektra for development, you have multiple projects in multiple directories. I think in this scenario its a common usecase, that you mount configuration in the same path.
Maybe it is possible to add an option to `kdb mount` to use another name instead of the mountpoint?

**Comment by Namoshek** [comment]
As far as I know, if you mount something like `kdb mount git.dump dir/git dump`, it will be used for every directory. You can easily check by mounting something like that, setting a key in two directories and looking for the file in the `.dir` directory (in both folders).

**Comment by markus2330** [comment]
Yes, mounting is a static information, whereas resolving is happening dynamically.

**Comment by krit0n** [comment]
Ok, I understand... so I cannot use different configuration file paths in different directories if I want to mount it to the same mountpoint.

**Comment by markus2330** [comment]
I think your expectations are valid, there should be a way for user and dir specific mountpoints.

In #1074 we discuss to support what you suggested here (not only for dir, but also for user). I linked this issue from there.
