### ISSUE TITLE
Improve  CONTRIBUTING.md

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1082]
We should explain how a developer can create PRs, e.g.,  similar to https://opencomparison.readthedocs.io/en/latest/contributing.html

It should also have many pointers to our documentation.

**Comment by Namoshek** [comment]
We currently already have the [CONTRIBUTING.md](.github/CONTRIBUTING.md), which is linked when creating a new PR (where you can write text for the PR). Maybe we can use this as basis?

**Comment by markus2330** [comment]
Thanks for the input! Yes, it is a good idea.

Which information do you think would help in getting started developing with Elektra? Should we also cover IDE issues? Is there a "how to use github" guide we can simply link to without replicating too much content?

**Comment by Namoshek** [comment]
I think it depends quite a lot on what someone wants to change or develop. A link to the current API docs could definitely be useful. If we had the website ready, we could also link there (to the developer "getting started" section maybe)?

About github: We can give a hint that there is a [comprehensive help](https://help.github.com/), but I wouldn't give too much other input on this topic.

**Comment by markus2330** [comment]
> I think it depends quite a lot on what someone wants to change or develop.

In which ways? How would the guide differ if you want to write an application or plugin? Isn't it necessary to first understand the application view, before you can develop a plugin?

> About github

So you mean somethink like: "We use the fork and pull model, you can read about forking our repo here https://help.github.com/articles/fork-a-repo/"?

**Comment by Namoshek** [comment]
> In which ways? How would the guide differ if you want to write an application or plugin? Isn't it necessary to first understand the application view, before you can develop a plugin?

Of course you first need to understand the application view, but each topic (libs, plugins, tools, ...) has different aspects as well. For example "we would want to keep the core library small with no dependencies" or "we want plugins to be based on existing libraries to reduce maintenance responsibilities". That are quite contrary statements, but both are important and depend on the goal.

But in order for someone to know what he wants to develop (lib, tool or plugin), he has to know the project (quite) a bit already. So I would only give a very general hint at the top like "before you start thinking about code contributions, you should have read the 'getting started guide' to make yourself familiar with Elektra". Then only talk about more specific topics like plugins, tools, etc.

> So you mean somethink like: "We use the fork and pull model, you can read about forking our repo here https://help.github.com/articles/fork-a-repo/"?

Small hints like that sound good, yes!

**Comment by markus2330** [comment]
Thanks for your feedback, do you think doc/BIGPICTURE.md resolved this issue?

Or do you think we should also cover libs more? I left them out because it seems to be that extending libs is not really a beginners problem. And defining APIs is not always obvious, even for experts (remember our discussion about the "heuristics of which syntax a configuration file" has? Actually not the heuristics themselves were important, but an API and a single place that could be extended with all tools profiting from it). Of course there is always the risk of having an API with a single user, which sometimes is a waste of effort.

**Comment by Namoshek** [comment]
I think that document helps a lot in understanding how Elektra works, yes. I'm not yet sure if it gives enough info about the possibilities of plugins and tools in detail, but a lot has been written in linked files already, so I guess it is fine.

Some textual remarks:

At the very top

> ...why such an solution...

should probably be "a solution".

In the middle

> In the same way that there is not one file system satisfying everybody's needs, different configuration file format parsers have different advantages and disadvantages. To have multiple file systems present at the same time. A virtual file system is able to mount concrete file systems and thus give applications a way to uniformly access them. Elektra in its core exactly implements this. A contract specifies the interface between plugins and the core.

reads strange. The second sentence feels somehow misplaced.

The rest reads good, but I think you should use links to README files instead of directories (for the website).

**Comment by markus2330** [comment]
Thanks for the feedback! I fixed your points and extended the document. Please reopen if you find something else!

> links to README files

I fixed it for this file, but I think there are many more places where this is not yet done. I opened #1095 to discuss this issue!
