### ISSUE TITLE
ini plugin creates ghost keys

### ISSUE THREAD

**Issue by krit0n** [ElektraInitiative/libelektra#1088]
First I thought that `kdb ls` lists all paths that contain keys, but than I noticed that this only happens with the ini plugin. I think its not a big issue, but just to let you know. 

# Describe what you wanted to do
    $ mkdir a && cd $_
    $ cat << EOF > a.ini
    $ [b]
    $ c = 42
    $ EOF
    $ sudo kdb mount /a.ini dir/a ini
    $ kdb ls dir/a
    dir/a/b   <--- is this really a key?
    dir/a/b/c

If I would have mounted the config file as *dump*, dir/a/b wouldn't have been a key.
It seems that [b] is recognized as a key. I don't know if this is intended.

# Describe what you expected
I didn't expect dir/a/b to be a key

# Describe what actually happened
dir/a/b is a key with no value

# System Information

- Elektra Version: 0.8.18

**Comment by markus2330** [comment]
What you describe here is actually arguable (you wrote down a section b in the ini file). The problem you actually describe is:

```
kdb mount /empty.ini dir/empty ini
kdb set dir/empty/a/b ab
kdb get dir/empty/a       # <-- key is suddenly here
```

But this can be changed via the `section` option:

```
kdb mount /empty.ini dir/empty ini section=NULL
```

I'll update the docu. Please reopen if there are further issues.
