### ISSUE TITLE
kdb mount manpage - invalid example

### ISSUE THREAD

**Issue by krit0n** [ElektraInitiative/libelektra#1089]
The kdb mount manpage contains the following example:

> ## Examples
> ...
> To recode and rename a configuration file using Elektra:
> **kdb mount s.ini recode.txt ni rename cut=path iconv recode=utf8..latin1**

When I try this example I get the following error message:

> Invalid arguments passed: recode.txt is not an valid keyname

If this is indeed incorrect we should remove this example from
**src/tools/kdb/mount.hpp:75** and **doc/help/kdb-mount.md:114**
otherwise we have to adapt the synopsis of kdb mount in the manpage.

**Comment by krit0n** [comment]
...and the error message should be:
Invalid arguments passed: recode.txt is not **a** valid keyname

**Comment by markus2330** [comment]
Very good catch! Thank you for reporting!
