### ISSUE TITLE
ini plugin - replacing comment metadata breaks config file

### ISSUE THREAD

**Issue by krit0n** [ElektraInitiative/libelektra#1091]
The ini plugin does support comments as metadata. Replacing these comments can break things.

# Describe what actually happened
    $ sudo kdb mount /a.ini dir/a ini
    $ cat << EOF > a.ini
    $ [b]
    $ # this is a comment
    $ c = 42
    $ EOF

When comment metadata is displayed the '#' seems to be part of the comment:

    $ kdb getmeta dir/a/b/c  comments/#0
    # this is a comment

Now we can replace the '#' away:

    $ kdb setmeta dir/a/b/c comments/#0 "new = value"
    $ kdb get dir/a/b/new
    value
    
# System Information

- Elektra Version: 0.8.18

**Comment by markus2330** [comment]
Thanks for reporting this issue! Seems like there is no default character for comments.
