### ISSUE TITLE
mathcheck plugin is not working correctly

### ISSUE THREAD

**Issue by krit0n** [ElektraInitiative/libelektra#1094]
This issue seems to pop up when I reference keys in `check/math` that are one level up in the path-hierarchy (keys that are referenced with `../../`)

# Describe what actually happened

    $ sudo kdb mount /example.ni user/example ni mathcheck
    $ cat << EOF > example.ni
    a/b/u = 1
    a/v = 2
    a/b/w = 3
    a/b/x =

    [a/b/x]
     check/math = := + ../u + ../../v ../w

    $ kdb set user/example/a/b/w 10
    $ kdb get user/example/a/b/x
    0.1 <-- should be 13

# System Information

- Elektra Version: 0.8.18

**Comment by markus2330** [comment]
Thanks for reporting this issue!

@tom-wa Is "mathcheck does not work with icc 14.0.2 20140120, and some gcc versions when using debug. Additionally, it fails to run on OpenBSD" still true?
