### ISSUE TITLE
links to directories

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1095]
Should the link checker reject links to directories or can we extend the homepage to automatically append README.md for directories?

**Comment by Namoshek** [comment]
I think it should be possible to extend the frontend, I'll have a look later the day.

**Comment by Namoshek** [comment]
It was actually already implemented (hard-coded for `README.md` as filename), but a list can now be used, allowing for fallbacks. If no target file was found, a link to github will be generated.

If links to directories are no problem for other tools, etc., this issue may be closed from my side.

**Comment by markus2330** [comment]
Yes, github and doxygen seem to work with directory links as well. We never had a problem with them.

Is it important to have a slash at the end or will it also work without?

I added all 3 variants at end of doc/BIGPICTURES.md for testing.

**Comment by Namoshek** [comment]
It should work without as it does a filesystem check whether it is a file or not.

**Comment by markus2330** [comment]
There seems to be a problem with directories in doxygen (http://doc.libelektra.org/api/latest/html/doc_BIGPICTURE_md.html). In github there is also a difference: a link to the directory shows the content of the folder first, which sometimes hides the README's content (especially on the plugin page https://github.com/ElektraInitiative/libelektra/tree/master/src/plugins) So it might be best after all to rewrite all links to have README.md.

@Namoshek Can you add BIGPICTURE at namoshek:9000?

@KurtMi Is it possible to rewrite (change) the links automatically by your tool? Or simply reject them and we add /README.md at all places (directory links)?

Additionally, it seems like some README.md(s) are not included in doc/Doxyfile. We should find them all using cmake and append them in doc/Doxyfile.

**Comment by Namoshek** [comment]
Where to add the BIGPICTURE.md? To the getting started section for users or for developers?

**Comment by markus2330** [comment]
"Documentation" seems to be the point for everybody (user+developers), so what about adding it there? It is also linked tightly with WHY, which is also at "Documentation".

**Comment by Namoshek** [comment]
I added it to the Getting Started section of Documentation. If I add it with our current tools as single file, we would have a whole docu section only for this file (looks weird).

There are some link errors in the BIGPICTURE.md though, e.g. `[iconv plugin](src/plugins/iconv/README.md)` should start with a leading slash as it should be read from the directory root. Shall I fix this errors together with the frontend or do you want to change it separately?

**Comment by markus2330** [comment]
Please do not add unrelated stuff to such a already-too-big PR (hopefully we can merge it soon?). I fixed the places I saw.

**Comment by Namoshek** [comment]
I thought so, thank you! Because of the change I could find a small bug in one of the scripts that is fixed now, all links should look beautiful now. :grin:

**Comment by markus2330** [comment]
Thank you both for fixing this!

Links to directories now work fine! (both front-end and doxygen append README.md)
