### ISSUE TITLE
cc: error: unrecognized argument to -fsanitize= option: ‘integer’

### ISSUE THREAD

**Issue by tom-wa** [ElektraInitiative/libelektra#1097]
# Describe what you wanted to do
compile elektra

# Describe what you expected
no error

# Describe what actually happened
building failed with error: unrecognized argument to -fsanitize= option: ‘integer’

# System Information

- Elektra Version: master
- Versions of other relevant software?
debian jessie with gcc 4.9.2

# Further Log Files and Output

[  1%] Building CXX object gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
c++: error: unrecognized argument to -fsanitize= option: ‘integer’
gtest/CMakeFiles/gtest.dir/build.make:54: recipe for target 'gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o' failed
make[2]: *** [gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 1
CMakeFiles/Makefile2:1083: recipe for target 'gtest/CMakeFiles/gtest.dir/all' failed
make[1]: *** [gtest/CMakeFiles/gtest.dir/all] Error 2
Makefile:147: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by markus2330** [comment]
What are your cmake options?

Does #803 fix this problem?

**Comment by tom-wa** [comment]
not really sure what the exact options were, but it seems like it was some cmake issue. i've tried deleting the build folder and got the same error. after deleting it a second time the issue was gone, no idea what exactly happened 
does cmake cache things outside of the build folder ?

**Comment by markus2330** [comment]
No, afaik cmake only works within the build folder. Usually it should be enough to remove CMakeCache.txt.

But other tools might use files external to the build folder, do you use ccache?

**Comment by tom-wa** [comment]
no ccache.
usually removing the build folder solves all cmake issues. seems to work fine now.

**Comment by markus2330** [comment]
Please reopen if it occurrs again.
