### ISSUE TITLE
testkdb_error: fails

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#1102]
Just documenting this. Might be specific to my machine since I didn't see the unit tests fail neither on travis nor jenkins.

# Describe what you wanted to do
Build project, run the tests.

# Describe what you expected
Expected the tests not to fail.

# Describe what actually happened
The test "testkdb_error" failed. See attached log.

# System Information

- Elektra Version: master @ 4b7f0b0177086bda26560e40f3f2216ae0a3e296
- Versions of other relevant software?
- macOS 10.12.1

# Further Log Files and Output
[testkdb_error.txt](https://github.com/ElektraInitiative/libelektra/files/596129/testkdb_error.txt)

**Comment by markus2330** [comment]
Thanks for reporting! The build server agrees with you!
