### ISSUE TITLE
global plugins

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#1103]
Nothing to see here yet. Just internal tracking for myself.

TODO:
- [ ] @kodebach: At least some errors returned from global plugins are suppressed by kdbGet.

Old, possibly obsolete TODO:
- [ ] init could be even earlier directly in kdbGet? @ 450
- [ ] I think we missed at the meeting that for [foreach] a pre/post might be useful. (Post execute after line 465) @ 461
- [ ] won't work here, return -1 would bypass it. @ 490
- [ ] Would be executed even if no backend->getplugins[p] exists. @ 576
- [ ] Seems like we need to split the loop to have presetstorage and setstorage separated. setresolver would be the COMMIT_PLUGIN, its not within this loop. @ 854
- [ ] Would not be needed if loop is split. @ 870
- [ ] again, a split in the loop within elektraSetRollback would be required (prerollback and rollback). The foreach must be within the loop of elektraSetRollback. @ 1219
- [ ] It would be good if you have a helper function/macro for executing the hooks so that the hooks are better visible/readable.
- [ ] sporadically not executed presetstorage MAXONCE

**Comment by mpranj** [comment]
@markus2330 you mentioned in #874:
> sporadically not executed presetstorage MAXONCE

I'm sorry but I can not see why the hook would not be called. The code is the same for every hook and it doesn't do anything fancy. The hook is called after namespace and sanity checks (handle or ks is NULL).

The only thing I could do is place it before the namespace check.

**Comment by markus2330** [comment]
@kodebach I don't think it is needed to remove stale flags of internal trackings.

**Comment by kodebach** [comment]
Oh... Seems I confused the issue with another one
