### ISSUE TITLE
Color Theme for asciinema

### ISSUE THREAD

**Issue by Namoshek** [ElektraInitiative/libelektra#1108]
Please add to the list what needs to be changed for the front-page. If texts should be changed, add them in a separate comment.

+ [x] increase spacing between selling points
+ [x] add buttons at top for 'getting started' and others (what else to link here? e.g. examples?)
+ [x] remove API description from developer-gettingstarted section (it is externally linked already)
+ [x] add short introductory description to news list items (how to recognize them in the post items?)
+ [x] add short links to specific docu pages at the bottom (what exactly?)
+ [ ] color schema for asciinema

**Comment by markus2330** [comment]
Is there some more efficient way to change/review the text? What about having a PR with only containing the front page? Or do you think you will be ready with the front end PR anyway soon?

**Comment by Namoshek** [comment]
I think the PR is pretty much ready, I only have to look at the cmake integration once again. We can change the 'home' page later too (texts are part of the language file, icons and other stuff is not).

**Comment by markus2330** [comment]
Ok, then only fix the obvious stuff we discussed and I will review the PR directly after the release (if "work in progress" is removed by then). When the PR is under review, please only change review comments, otherwise the review gets tedious and long.

**Comment by Namoshek** [comment]
I implemented everything listed above (and news posts are now split into the year they were created when you look at the menu in the news section). I also fixed one or two minor glitches. Again, the new three points on the bottom are only placeholders... we can change them later pretty easily.

**Comment by markus2330** [comment]
Thank you, that are great news!

@waht @Namoshek Maybe we should use a different color schema for the asciinema?
https://asciinema.org/a/cantr04assr4jkv8v34uz9b8r?theme=white-black
or solarized-dark?

@Namoshek is it okay if I write 0.8.19 release notes in the old format? Can you convert it afterwards for the homepage release?

**Comment by Namoshek** [comment]
>  different color schema ... or solarized-dark?

I think the white one is not good. You should be able to see that there is a video in my opinion. The other one would be ok, but personally I like the current one the most (`tango` is pretty good as well).

> is it okay if I write 0.8.19 release notes in the old format? Can you convert it afterwards for the homepage release?

Absolutely! I'll rebase afterwards and split the last news post in a new file, it should be no problem.

**Comment by Namoshek** [comment]
I still like the default one most... tried all of them, the other ones are hard to read or don't match with our colors. An individual style would be best though.

**Comment by markus2330** [comment]
Yes, good idea. I will unassign you. Maybe @waht can come up with a nice color theme for asciinema, too.

**Comment by Namoshek** [comment]
Are custom styles even possible? Didn't find this option when doing a quick manual check..

**Comment by markus2330** [comment]
I will close the issue: We are happy with the current look of the webpage.
