### ISSUE TITLE
Improve update-info-status

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1110]
- [ ] nodoc: With 40 vs. 41 lines it seems a bit arbitrary. In this case maybe something like <30 add nodoc >80 remove nodoc.
For example base64 could be considered as documented (34 lines, @petermax2 what do you think?), but desktop is rather poorly documented (48 lines, many of them empty, empty lines might be be useful to consider, too).
src/plugins/uname/README.md is also a corner case: what it does is trivial (32 lines)
- [ ] unittest: should also have some metric, at least the tests as copied from template should not lead to `unittest`
- [ ] plugins doc and template should not be touched
- [x] resolver should have nodep. It has LINK_LIBRARIES, but only of pthreads, which is part of libc.

Issues we can live with:

- [ ] configurable: keytometa gets `configurable` removed wrongly (configuration via. metadata)
- [ ] timeofday and tracer get configure added wrongly (they use elektraPluginGetConfig, but only for `/module`, which is not really configuration).

**Comment by petermax2** [comment]
Everything base64 does is documented in `README.md` essentially. I think in-code documentation and comments are important as well.

**Comment by petermax2** [comment]
desktop's documentation does not really tell me what desktop is supposed to do: 

> The plugin is informational and mainly be used to provide context for
> other configuration. See [elektrify-getenv](/src/libs/getenv/README.md).

**Comment by markus2330** [comment]
> desktop's documentation does not really tell me what desktop is supposed to do

That was my point ;)

**Comment by markus2330** [comment]
These problems seem to be resolved now. #666 is about adding new infos/status.
