### ISSUE TITLE
glib test broken

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1111]
src/bindings/glib/tests/testglib_key.c line 222:

```
libelektra/src/bindings/glib/tests/testglib_key.c:222:22: warning: variable 'key' is uninitialized when used here [-Wuninitialized]
                succeed_if (meta > key == curmeta > key, "meta iterators returned different keys");
                                   ^~~
```

**Comment by manuelm** [comment]
The test doesn't make any sense to me so I looked into the history. Looks like this is on you :-)
https://github.com/ElektraInitiative/libelektra/commit/adbe117c8b88b75769ef0c760ef72858d1de2876#diff-4e50148c8b9bba331ce8cdd95228681e

**Comment by markus2330** [comment]
Thanks, will fix it ;)
