### ISSUE TITLE
fcrypt: failing test case if current directory is not writable

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1113]
# Describe what you wanted to do

Run `kdb run_all` with installed Elektra on my machine.

Seems to *not* occur on http://build.libelektra.org:8080/job/elektra-local-installation/
neither on a fresh installation:

- Install jessie (e.g. `deboostrap jessie jessie`).
- add `deb     [trusted=yes] http://debian-stable.libelektra.org/elektra-stable/ jessie main` to /etc/apt/sources.list
- `apt-get update`
- `apt-get install libelektra4-bin libelektra-test`
- `kdb run_all`

But it is always reproducable on my machine, even when wiping out all keys of kdb or when running tests with `env -i`. Same behavior with `KDB=kdb-static kdb-static run_all` and `KDB=kdb-full kdb-full run_all`.

@petermax2 Can you reproduce it?

# Describe what you expected

That all test cases run successfully.

# Describe what actually happened

`error: testmod_fcrypt fails` if you run it with `kdb run_all` (I tried it several times).

It does not fail when you run it separately (`kdb testmod_fcrypt`, I tried it several hundret times).

# System Information

- Elektra Version: master
- gpg (GnuPG) 2.0.26
- libgcrypt 1.6.3

# Further Log Files and Output
```
--- running testmod_fcrypt ---


FCRYPT       TESTS
==================

/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/fcrypt/testmod_fcrypt.c:50: error in writeTestFile: can not write to temporary file
/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/fcrypt/testmod_fcrypt.c:156: error in test_file_operations: kdb set failed
/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/fcrypt/testmod_fcrypt.c:68: error in isTestFileCorrect: can not read from temporary file
/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/fcrypt/testmod_fcrypt.c:160: error in test_file_operations: kdb get (pregetstorage) failed
/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/fcrypt/testmod_fcrypt.c:68: error in isTestFileCorrect: can not read from temporary file
/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/fcrypt/testmod_fcrypt.c:161: error in test_file_operations: file content could not be restored during decryption
/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/fcrypt/testmod_fcrypt.c:164: error in test_file_operations: kdb get (postgetstorage) failed
/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/fcrypt/testmod_fcrypt.c:68: error in isTestFileCorrect: can not read from temporary file

fcrypt RESULTS: 23 test(s) done. 8 error(s).
error: testmod_fcrypt

....


+ exit 0
Following test cases failed:
testmod_fcrypt
run_all RESULTS: 667 test(s) done 1 error(s).
```

**Comment by markus2330** [comment]
I can reproduce it on a different machine. It has my home directory shared, though. Do you have any idea what this could be? Maybe a broken gpg setup?

**Comment by petermax2** [comment]
I set up a fresh Debian 8 VM and installed elektra as described above. I could *not* reproduce the error.

Running (as root):

    kdb run_all

results in:

    fcrypt RESULTS: 27 test(s) done. 0 error(s).

Very strange though. Maybe there is something wrong with your environment? Does gpg2 "see" the test key? What happens if you manually add the test key to your key chain?

**Comment by petermax2** [comment]
The test key is located at: `src/plugins/crypto/test_key.asc` .

**Comment by markus2330** [comment]
Yes, seems like there is something weird/wrong in my environment. I think the only way to find out is adding more sanity checks within fcrypt or the tests. How to I find out if  gpg2 "see" the test key? Can you add such checks?

**Comment by petermax2** [comment]
There is already a unit test for that in `testmod_fcrypt` .

We could add a check if the specified keys exist in the keychain at `checkconf` .

**Comment by markus2330** [comment]
The earlier the user gets an error, the better. But maybe I misunderstand what the check does. Would be good if you think through what kind of environmental changes are possible and which error would be helpful for users in such cases.

Btw. I found out it is not about that all test cases run together, but it seems like one of the environmental manipulation within run_all is the problem. (If I *only* run testmod_fcrypt within run_all by changing the shell script, I still get the error).

And that lead to that the problem simply is: you need to be in a writable directory. So when I `cd /usr`, then `kdb testmod_fcrypt` fails, If I am at I directory where I can write to, it works.

Is also obvious when doing a strace, the test does: `open("fcrypt_testfile7a0Nbn", O_RDONLY) = 4`.

Can you fix this?

**Comment by petermax2** [comment]
> Can you fix this?

Yes, assuming we agree on a directory that is writable. But I don't want to over-engineer the test cases. How about putting the test files to `/tmp` . It _should_ be writable on most systems.

**Comment by markus2330** [comment]
Yes, of course. Most of the other test cases also use mktemp, simply do it in the same way. Please do not invent something new ;)

**Comment by markus2330** [comment]
Seems to be broken on OpenSuse 42.1, too.

```
sh-4.2# kdb testmod_fcrypt
FCRYPT       TESTS
==================

/libelektra/src/plugins/fcrypt/testmod_fcrypt.c:162: error in test_file_operations: kdb set failed
/libelektra/src/plugins/fcrypt/testmod_fcrypt.c:163: error in test_file_operations: file content did not change during encryption
/libelektra/src/plugins/fcrypt/testmod_fcrypt.c:166: error in test_file_operations: kdb get (pregetstorage) failed
/libelektra/src/plugins/fcrypt/testmod_fcrypt.c:170: error in test_file_operations: kdb get (postgetstorage) failed
/libelektra/src/plugins/fcrypt/testmod_fcrypt.c:171: error in test_file_operations: postgetstorage did not encrypt the file again

fcrypt RESULTS: 27 test(s) done. 5 error(s).
sh-4.2# mkdir /tmp
mkdir: cannot create directory '/tmp': File exists
```

**Comment by markus2330** [comment]
`TMPDIR=/tmp kdb testmod_fcrypt` same error.

**Comment by petermax2** [comment]
`getTemporaryFileName()` in fcrypt.c needs the same fix.

**Comment by petermax2** [comment]
> getTemporaryFileName() in fcrypt.c needs the same fix.

Well that should not be the problem. In fcrypt.c `getTemporaryFileName()` is called like:

    getTemporaryFileName (keyString (parentKey), &tmpFileFd)

so it has the `/tmp/file...` path within `keyString(parentKey)`.

**Comment by markus2330** [comment]
Btw. there is a `elektraFilename ()` used by many other testcases which works nicely.

**Comment by markus2330** [comment]
See `tests/cframework/tests.[hc]` for other useful functions.
