### ISSUE TITLE
Build problems on CentOS 7

### ISSUE THREAD

**Issue by reox** [ElektraInitiative/libelektra#1114]
extending from #1071 

there is more:
```
-- Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is at least version "3")
-- Could NOT find SWIG: Found unsuitable version "2.0.10", but required is at least "3" (found /usr/bin/swig)
-- Search for swig2 instead
-- Exclude Plugin python because python 3 libs not found
-- Could NOT find Python2Libs (missing:  PYTHON2_LIBRARIES PYTHON2_INCLUDE_DIRS) (Required is at least version "2.7")
-- Could NOT find SWIG: Found unsuitable version "2.0.10", but required is at least "3" (found /usr/bin/swig)
-- Search for swig2 instead
-- Exclude Plugin python2 because python 2 libs not found
CMake Deprecation Warning at src/plugins/python2/CMakeLists.txt:40 (message):
  Python 2.7 plugin has been deprecated
```

I installed `python` and `python34` and also `python-libs` and `python34-libs`:
```
[vagrant@localhost ~]$ python3 --version
Python 3.4.5
[vagrant@localhost ~]$ python --version
Python 2.7.5
```

Also LUA has some misleading messages:
What about this error:
```
Lua library: .
Lua executable: 5.1
-- Could NOT find Lua (missing:  LUA_INCLUDE_DIR) (Required is at least version "5.1")
-- Could NOT find SWIG (missing:  SWIG_EXECUTABLE SWIG_DIR) (Required is at least version "3")
-- Search for swig2 instead
-- Exclude Plugin lua because Lua libs >= 5.2 not found
```

First it wants LUA 5.1, then 5.2? In CentOS EPEL there is lua-devel 5.1.4
If installing `lua-devel` it works:
`-- Found Lua: /usr/lib64/liblua-5.1.so;/usr/lib64/libm.so (found suitable version "5.1.4", minimum required is "5.1") 
`

**Comment by reox** [comment]
Next one:
```
[vagrant@localhost ~]$ sudo rpm -i rpmbuild/RPMS/x86_64/elektra-0.8.18-1.el7.centoszkk1intercept.x86_64.rpm 
error: Failed dependencies:
	libelektra-resolver.so()(64bit) is needed by elektra-0.8.18-1.el7.centoszkk1intercept.x86_64

```

The lib is in the rpm at `/usr/lib64/elektra/libelektra-resolver.so` but seems to be wanted at `/usr/lib64/libelektra-resolver.so`?

**Comment by markus2330** [comment]
Thanks for reporting all these issues!

python: It seems to be a swig problem, so either swig3 is not installed or `-DSWIG_EXECUTABLE=/usr/bin/swig3.0` is not specified correctly.
You also need python*-dev.

Lua should be fixed with 4c52ab2073b58a08304f2b4d5b12cf01b4154462

I do not understand the rpm error: nothing should link directly to libelektra-resolver.so or any other plugin.

**Comment by reox** [comment]
I have no clue how rpmbuild determined which libs are required and which are provided. If someone can hint me with the commands to check where this comes from, I can do it. 
Otherwise the requires_exclude works fine.

**Comment by markus2330** [comment]
> Otherwise the requires_exclude works fine.

Ok, thanks for finding out.

Are the messages now fine? Do the python bindings work now?

**Comment by reox** [comment]
swig output looks now like this:
```
-- Could NOT find SWIG: Found unsuitable version "2.0.10", but required is at least "3" (found /usr/bin/swig)
-- Search for swig2 instead
-- Found SWIG: /usr/bin/swig (found suitable version "2.0.10", minimum required is "2") 

```

On master I get now, i think this is correct due to a version change?
```
-- Found LibGit2: /usr/lib64/libgit2.so  
-- Exclude Plugin gitresolver because libgit2 >= 0.24.1 required
```

For the python stuff: I definitely get some warnings and notes but it builds...

The `doc/COPYING` file seems to be missing in master:
```
cp: cannot stat 'doc/COPYING': No such file or directory
```
was this file moved? It is at least referenced a lot in the Code...

Also now i do not have `libelektragetenv.so`, `libgelektra-*.so` and `libelektrasettings.so` anymore. Arn't they build by default?

**Comment by markus2330** [comment]
> swig output looks now like this

Not ideal, but it should be fine?

> [gitresolver] version change?

No, it has been 0.24.1 all along. Debian jessie version is also too old.

> get some warnings

Compiler warnings are not easy to fix (swig generates it this way). Or do you mean other warnings?

> doc/COPYING

Yes, it is now called doc/LICENSE.md. If you have selected INSTALL_DOCUMENTATION it should be installed.

> doc/COPYING is at least referenced a lot in the Code...

Thank you! Should be fixed in 6c8cfac6b427ce720cca49a3ce3db6d82adc7718

> libelektragetenv.so.0

symlink was reintroduced today for compatibility reasons, see 0a2622b6e827f42324e19ad5f617ab51b37bfb6b

> libelektragetenv.so.0.8.19 

No, this one never existed. Where is it needed? `libelektraintercept-env.so*` are the new names. And there should now be a 0.8.19 version of it, too.

> libelektrasettings.so Aren't they build by default?

They never were and as long as we cannot clarify  #1071 I think we better leave it this way.

**Comment by reox** [comment]
> No, it has been 0.24.1 all along. Debian jessie version is also too old.
interessting, because from the 0.8.18 tarball it build

> Compiler warnings are not easy to fix (swig generates it this way). Or do you mean other warnings?
compiler warnings

> No, this one never existed. 
Oh okay, for me those two files were generated using 0.8.18 tarball...

**Comment by markus2330** [comment]
> interessting, because from the 0.8.18 tarball it build

`git diff master..0.8.18 -- src/plugins/gitresolver` only shows docu changes.

> Oh okay, for me those two files were generated using 0.8.18 tarball... 

You get libelektragetenv.so.0.8.19  files from the 0.8.18 tarball?

> I can import kdb in python and do stuff like

Ok, looks very good.

> Where should it crash or are there any tests i can perform?

`kdb run_all` or `make run_all` in the build directory. Has to be done as root (or see doc/TESTING.md for other options).

**Comment by markus2330** [comment]
Thanks for reporting these issues! Please (re)open if something still does not work.
