### ISSUE TITLE
kdb list returns lib.so names

### ISSUE THREAD

**Issue by beku** [ElektraInitiative/libelektra#1119]
Should there be the logical plug in name instead of the on disk name?

# Describe what you wanted to do
kdb list

# Describe what you expected
show the plug in names like dump, yajl ...

# Describe what actually happened
dump.so
rename.so
resolver.so
resolver_fm_hpu_b.so
storage.so
struct.so
yajl.so

# System Information

- Elektra Version: master

**Comment by beku** [comment]
[CMakeCache.txt](https://github.com/ElektraInitiative/libelektra/files/602278/CMakeCache.txt)

**Comment by markus2330** [comment]
Hi @beku,

Thanks for reporting!

> Should there be the logical plug in name instead of the on disk name?

Yes, it definitely should be!

Are you sure your CMakeCache.txt was properly purged? There are some strange variables, e.g. `_PLUGINS:UNINITIALIZED` or `KDB_DB_DIR:PATH=.dir` (should be `KDB_DB_DIR:STRING=.dir`). Can you also post the cmake command line you used?

On which operating system does this problem occur?

**Comment by beku** [comment]
@markus2330 

$ cmake "$cmake_target" -DCMAKE_INSTALL_PREFIX="$prefix" -DLIB_SUFFIX=$BARCH -DCMAKE_BUILD_TYPE=Debug -DINSTALL_SYSTEM_FILES=false -DBUILD_TESTING=false -DENABLE_TESTING=OFF -DTOOLS=DEFAULT -DPLUGINS="ALL;dump;resolver;yajl;rename;struct;-passwd" ..
$ cmake "$cmake_target" -DCMAKE_C_FLAGS="$CFLAGS $OSX_ARCH_LIBRARY" -DCMAKE_CXX_FLAGS="$CXXFLAGS $OSX_ARCH_LIBRARY" -DCMAKE_LD_FLAGS="$LDFLAGS $OSX_ARCH_LIBRARY" ..

openSUSE-42.1

**Comment by markus2330** [comment]
> -DTOOLS=DEFAULT 

Here I get the cmake error `CMake Error at src/tools/CMakeLists.txt:3 (add_subdirectory):
  add_subdirectory given source "DEFAULT" which is not an existing directory.`

Are you sure you use master?

Why are there two cmake invocations?

> openSUSE-42.1

I'll try to install it with zypper in a chroot, takes some time...

**Comment by beku** [comment]
Trying with -DTOOLS=""

**Comment by beku** [comment]
The result is still not as expected:
$ kdb list
base64.so
blockresolver.so
boolean.so
c.so
cachefilter.so
ccode.so
conditionals.so
constants.so
...

**Comment by beku** [comment]
my master is #61308ac6

**Comment by markus2330** [comment]
> my master is #61308ac6

Looks good ;)

> Trying with -DTOOLS=""

Are you sure you execute what you compile? `-DTOOLS=""` should provide no `kdb` at all. You can simply leave it away or use `-DTOOLS="kdb"`

And why are there two cmake commands?

I used: `cmake -DCMAKE_INSTALL_PREFIX="/usr" -DLIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=Debug -DINSTALL_SYSTEM_FILES=false -DBUILD_TESTING=false -DENABLE_TESTING=OFF -DTOOLS="kdb" -DPLUGINS="ALL;dump;resolver;yajl;rename;struct;-passwd" ../libelektra`

And then it works on OpenSuse 42.1 without issues:
```
kdb list
doc
semlock
template
fcrypt
```

**Comment by beku** [comment]
I tried your cmake line with not success.
The following patch appears to fix the issue with kdb list:
[fix_kdb_list.txt](https://github.com/ElektraInitiative/libelektra/files/602374/fix_kdb_list.txt)

**Comment by markus2330** [comment]
Thanks! Do you also want the change openicc-devices.json -> openicc.json be applied?

**Comment by beku** [comment]
Yes. 

(I am about verifying/testing the JSON DB access :)

**Comment by markus2330** [comment]
Seems like the problem was that the shared objects have some postfix. Strange that I could not reproduce it, maybe I got some of your cmake parameters wrong.

**Comment by markus2330** [comment]
Ok, I applied both fixes! Thanks a lot for them!

Please check if all issues are gone now!

**Comment by beku** [comment]
Looks fine. @markus2330 thanks for taking the time and applying the patch.

**Comment by markus2330** [comment]
Thanks for reporting and fixing it! Do not hesitate to (re)open issues for any questions!
