### ISSUE TITLE
shellrecorder: return state, multiple protocols

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1124]
The exit state of shell_recorder/markdown_wrapper seems to be wrong:

```
124: Test command: /home/markus/Projekte/Elektra/current/tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh "/home/markus/Projekte/Elektra/current/doc/tutorials/mount.md"
124: Test timeout computed to be: 1500
124: protocol file: /tmp/elektraenv.CQweyHo2v
124: mount /etc/hosts system/hosts hosts
124: shell_recorder /tmp/tmp.nnUhIgKFNZ RESULTS: 1 test(s) done
124:  0 error(s).
124: protocol file: /tmp/elektraenv.EekFRy6Qm
124: $ kdb file system/hosts
124: 
124: ERROR - STDOUT:
124: /etc/kdb/default.ecf
124: doesn't match /etc/hosts
124: 
124: shell_recorder /tmp/tmp.OQH781BNNV RESULTS: 2 test(s) done
124:  1 error(s).
124: protocol file: /tmp/elektraenv.dZSifC2nq
124: rm system/hosts/ipv4/mylocalhost
124: Return value 1 doesn't match 0
124: umount system/hosts
124: Return value 1 doesn't match 0
124: shell_recorder /tmp/tmp.03Udhjg8Y9 RESULTS: 2 test(s) done
124:  2 error(s).
1/1 Test #124: testshell_tutorial_mount .........   Passed    0.32 sec
```

@tom-wa Are there multiple shell_recorder started for one tutorial? (Why does it mention protocol file multiple times?)

Expected Behavior:

- return should only be successful, if it passed.
- only one shell_recorder/protocol file per tutorial/README.

**Comment by markus2330** [comment]
And while the output is checked for
```
$ kdb file system/hosts
/etc/hosts
```

It does not seem to be checked for

```
kdb file system/hosts
# /etc/hosts
```

But without any syntax explanation it is impossible to know what it should do.

**Comment by tom-wa** [comment]
>only one shell_recorder/protocol file per tutorial/README.

currently i run every example as a separate testcase
should all of them run as a single testcase or should i just merge the protocols ?

**Comment by markus2330** [comment]
Yes, run them together, they typically build on each other.

**Comment by tom-wa** [comment]
should the examples be selfcontained, or is it enough it the first example does the mounting, etc and the last example the cleanup ?

**Comment by markus2330** [comment]
There is no such thing as examples, within a file there are small snippets with some commands but you cannot assume that these snippets are self contained examples. They are tutorial style: the snippets end when an explanation is needed, not when something is "finished".

Why not execute everything with one shell_recorder? Btw. is it also possible to replay what was executed earlier? (With checks that the effects on KDB are the same)
