### ISSUE TITLE
strict mode for parsing

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1129]
For `kdb editor` or other tools where configuration files are actually manually edited and then validated, it would be good to have an option for stricter parsing.

Questions around this topic:

- also fail when it can be parsed unambiguous?
- fail on duplicate entries?

**Comment by sanssecours** [comment]
Sorry for the late response. 

> Questions around this topic:
> 
> - also fail when it can be parsed unambiguous?

Could you please elaborate why `kdb editor` should fail if a file can be parsed unambiguously?

> - fail on duplicate entries?

I think that makes sense, since duplicate keys can cause hard to find bugs.

**Comment by markus2330** [comment]
Thanks for answering!

> Could you please elaborate why kdb editor should fail if a file can be parsed unambiguously?

For example INI has a feature, which allows us to write a key without a value in different ways:

```
key
key=
```

The first form might easily be a typo (think of a longer string where the `=` was removed by mistake).

While it makes a lot of sense not to fail on such issues when parsing (especially for Elektra's mountpoints: failing parsing this file would make all mountpoints disappear), it also makes sense that we fail on newly edited files files where the user types in such likely-to-be-wrong synax.

> I think that makes sense, since duplicate keys can cause hard to find bugs.

Yes, a missing `=` can also cause hard-to-find bugs.

An alternative solution would be that we have an extra plugin which is designed to be robust (like INI is now) and other plugins that fail on likely-to-be-wrong synax.

**Comment by sanssecours** [comment]
While I think such a feature would make sense, it would also just mask problems with the configuration format itself. In your example, it would make sense to require the `=` in the first place.

In general, the more ambiguous the specification of a configuration language is, the more likely is it that the user unintentionally produces  a “correct” file. I think the proper solution here is to fix the file format specification or just use another file format, instead of making the parsing code more complicated.

**Comment by markus2330** [comment]
Yes, so let us separate the strictness of parsing to different plugins then.

For example, the `key` feature (without `=`) is something found in the wild, the ConfigParser from python uses it. It is a nice idea if you are keen on reading any garbage (e.g. for core config files where the whole system would stop working, e.g. think of /etc/passwd), but it might be not a good idea for 0815 applications.

Of course it would be better if users only use safe interfaces to edit config files, then we could always be strict and have more safety.

We somehow need a way to communicate to users what they will get if they choose among the different plugins.

**Comment by markus2330** [comment]
This should be irrelevant for YAML.
