### ISSUE TITLE
shellrecorder: properly clean up

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1132]
All changes to KDB should be cleaned up afterwards.

Including, but not limited to:

- [x] mountpoints
- [ ] globalplugins

But it should also yield an error in the case that something is not cleaned up in the tutorial, see #1189

The shell recorder is getting really great! We will advertise it with the next release!

**Comment by tom-wa** [comment]
afaik there is currently no way to umount a global plugin ? i can do the cleanup in the MSR without it, but should exist anyway.

**Comment by tom-wa** [comment]
would it be enough to umount everything that wasn't mounted before running the MSR and mount everything that isn't present afterwards ?

**Comment by markus2330** [comment]
> afaik there is currently no way to umount a global plugin ?

Yes, there is some other essential functionality missing too, see #1290. I assigned it to  @e1528532, should be an easy job.

> would it be enough to umount everything that wasn't mounted before running the MSR and mount everything that isn't present afterwards ?

Yes, it would be nice if everything wrong is reverted but the unit test should nevertheless fail thus the unit test clearly does wrong things and needs to be fixed. Please do not make cleanup logic too complicated, otherwise it might do more harm than good.

**Comment by markus2330** [comment]
To allow further temporary files (cleaned up by shell recorder, see #1613 for a use case), the shell recorder should set some TMPDIR variable which can be used within the scripts.
