### ISSUE TITLE
homepage: dynamic text

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1138]
Hi, is it easily possible to choose some random text on the main page?

The idea is to dynamically change the last word of the slogan, so rotate through slogans like:

- Configure everything, correctly
- Configure everything, fast
- Configure everything, validated
- Configure everything, simply

**Comment by Namoshek** [comment]
Easy :+1:

**Comment by markus2330** [comment]
Thank you! The next question is which words we should choose. Everybody is welcomed to throw in some words (that fit as last part after "Configure everything, _").

**Comment by Namoshek** [comment]
Just to make sure I'm right: You mean changing the word every x seconds? Or only on page refresh?

- efficiently
- globally
- remotely (maybe wait with this one until @omnidan is done)

**Comment by markus2330** [comment]
> You mean changing the word every x seconds? Or only on page refresh?

Not really important from my side. Something that is easy and does not involve a new REST API ;) If done via time-change, maybe a different word per day is fun?

Btw. I like globally.

Some more words:

- Configure everything, finally (was already suggested)
- Configure everything, specified
- Configure everything, sharable
- Configure everything, now

**Comment by Namoshek** [comment]
Well, it is pretty easy to change the word every x seconds, so I'll do that. All other suggestions are fine too, but then you need to visit the page quiet often until you saw all words.

**Comment by Namoshek** [comment]
Example how I imagine it to look like is online.

**Comment by markus2330** [comment]
Nice! Two micro issues: I think it goes too fast (3secs?), and it the jumping around annoys a bit.

**Comment by Namoshek** [comment]
Yes, I also think it goes too fast, I'll add a configuration option for it. The jumping is hardly avoidable though, as the slogan is centered... not sure if this is fixable.

**Comment by markus2330** [comment]
> Yes, I also think it goes too fast, I'll add a configuration option for it.

Good idea, I think it is still to fast. Maybe 10 sec?

> as the slogan is centered

Why not left-align it in a centered box or left-align with the subtitle "Elektra - the configuration framework for everyone"?

> which could be change to [sort list]

Yes, that is a nice improvement. Btw. you could go up and down instead of cycling, then sorting by length would work.

And some words to discuss (in their current form they would be flawed):

- notified
- desktop-neutral
- incorruptible

**Comment by Namoshek** [comment]
> Good idea, I think it is still to fast. Maybe 10 sec?

I think that is too long to realize that something changes. And if someone sees that it switches the adjective, they maybe want to see all of them (and then they don't want to wait an eternity). So I would not go too high with the interval.

> Why not left-align it in a centered box or left-align with the subtitle "Elektra - the configuration framework for everyone"?

I think that looks weird, because it isn't really centered for most adjectives then. Going up and down in the list seems a good compromise though.

> And some words to discuss

- "desktop-neutral" seems a bit very long, but something that reflects "cross-platform" sounds important to me ("cross-platform" is also too long).
- "notified" sounds important as well, but I can't think of anything (short) else.
- "incorruptible" could be replaced by "robust"?

**Comment by markus2330** [comment]
- [ ] Add effect when changing slogan
- [ ] responsiveness (small screen)
- [ ] 3.2 MB application.js?
- [ ] external links always in new tabs
- [ ] avoid useless README https://community.libelektra.org/libraries/readme
- [ ] does not work w/o javascript
- [ ] Links from all "big points"
- [ ] search is annoying
- [ ] not really clear that you can upload snippets (why is there a login?)

**Comment by Namoshek** [comment]
Points added to #1151

**Comment by markus2330** [comment]
thanks, shareable seems to have a typo

**Comment by markus2330** [comment]
Thanks, everything here works perfectly now! (or moved to #1151)

The animation is great ;)
