### ISSUE TITLE
shell-recorder: prefix files

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1139]
when doing `kdb mount /etc/hosts` we actually do not want the shell recorder to modify /etc/hosts when running the test case.

Expected behavior:
Use some temporary absolute path instead.

**Comment by tom-wa** [comment]
does that only apply to `kdb mount` or all operations on files ? (the first one would be complicated enough, the latter probably impossible without some really ugly hacks)

if we do `kdb mount /etc/hosts` what should happen instead ? i'd do something like
```
tmp=$(mktemp -d)
mkdir -p $tmp/etc
cp /etc/hosts $tmp/etc/hosts
kdb mount $tmp/etc/hosts
```

**Comment by markus2330** [comment]
Only for the case `kdb mount /...` it should be changed to `kdb mount /tmp/...`. No other action is needed, we always assume to start with empty files.

At the end the `/tmp/...` should be cleaned up.

**Comment by markus2330** [comment]
I added it to #944 or is it fixed already?
