### ISSUE TITLE
Tutorial rest-backend/frontend

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1140]
Could you please write a tutorial how to run backend+frontend? (can be a part of doc/INSTALL.md)

Ideally with paths that work in debian jessie.

Btw. we have now 2.0% JavaScript in Elektra!

**Comment by markus2330** [comment]
Please also integrate some checks in the tutorial if everything is running properly, e.g. curl queries against rest-backend. Please also mention maintenance tasks (where user data and snippets are written to, where logs are,..)

I am looking forward to get this running soon!

**Comment by markus2330** [comment]
Please also add how to run  Drafter and how to generate a HTML documentation with the Apairy CLI.

**Comment by Namoshek** [comment]
This issue should be resolved.

**Comment by markus2330** [comment]
Yes, thank you, nicely done!
