### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1150]
While running `make install`:

```
npm WARN package.json rest-frontend@1.0.0 No repository field.
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'iamadamjowett/angular-logger-max' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'rest-frontend'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--unsafe-perm"
npm ERR! cwd /home/markus/Projekte/Elektra/installation/share/elektra/tool_data/rest-frontend
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/markus/Projekte/Elektra/installation/share/elektra/tool_data/rest-frontend/npm-debug.log
npm ERR! not ok code 0

```

**Comment by Namoshek** [comment]
That is weird, because it is [listed in the npm registry](https://www.npmjs.com/package/@iamadamjowett/angular-logger-max).

How did you install npm? Directly as apt-package (`apt-get install npm`) or as part of nodejs (`apt-get install nodejs`)?

**Comment by markus2330** [comment]
Yes, npm 1.4.21+ds-2 and nodejs 0.10.29~dfsg-2 (from Debian Jessie).

**Comment by Namoshek** [comment]
I think if you install npm directly, it causes trouble; I had the same issue when I first installed it on my server. Can you try to remove npm and if it still not works re-install nodejs?

**Comment by markus2330** [comment]
So npm gets automatically installed using nodejs? And who should install grunt? `/home/markus/Projekte/Elektra/installation/lib/elektra/tool_exec/run-rest-frontend: 2: /home/markus/Projekte/Elektra/installation/lib/elektra/tool_exec/run-rest-frontend: ./node_modules/grunt-cli/bin/grunt: not found`

Btw. `kdb mount` during installation is a nice idea, but I am afraid we cannot assume `kdb` to be installed. These things need to be done via tutorial. (As least as long as it is not a separate project).

**Comment by Namoshek** [comment]
> So npm gets automatically installed using nodejs?

Yes!

> And who should install grunt? 

Grunt is installed as npm package, as you can see by the path (`node_modules` dir).

> Btw. kdb mount during installation is a nice idea, but I am afraid we cannot assume kdb to be installed. These things need to be done via tutorial. (As least as long as it is not a separate project).

Noticed it today when I got the "kdb: error while loading shared libraries: libelektra-core.so.4: cannot open shared object file: No such file or directory" error. I'll move it into a script.

**Comment by markus2330** [comment]
>So npm gets automatically installed using nodejs?

Unfortunately I get `-- Exclude tool rest-frontend because dependency manager 'npm' not found`. Also reinstalling nodejs does not help. Also removing `~/.npm` did not work. I always get the same error. Can you reproduce it with debian jessie?

> Grunt is installed as npm package

I got `grunt not found`, but that is likely to be related with the npm error.

> I'll move it into a script.

Thanks good idea.

**Comment by Namoshek** [comment]
The grunt issue is because of npm, but it looks strange. Have you tried `find / -iname npm` to locate it? Maybe it helps us understanding the issue.

**Comment by markus2330** [comment]
> find / -iname npm

The npm binaries are only part of the npm package (not of nodejs package):

npm: /usr/bin/npm
npm: /usr/lib/nodejs/npm

So if there is no other way nodejs can bootstrap npm it is clear that it cannot work ;)
But even if it could bootstrap, the frontend directly searches for the npm binary without any nodejs bootstrapping? What exactly did you mean with

> Can you try to remove npm and if it still not works re-install nodejs?

**Comment by Namoshek** [comment]
Interesting, maybe I installed it from the website and cannot remember. Anyhow, I'll have a look...

**Comment by Namoshek** [comment]
After installing nodejs + npm like explained on the [nodejs website](https://nodejs.org/en/download/package-manager/), it seems to work. npm is now on version 3.10.8 instead of 1.4.21.

Used commands:
```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by markus2330** [comment]
Can you confirm that 1.4.21 is broken? The script seems to be ok (at least now, it really is not a secure way to install packages)

For tutorial updates I created an extra issue: #1160

A check in cmake would be nice too, but I am afraid it is difficult to find out which npm versions will work.

I also created an issue about rest-frontend installation: #1161

Btw. I think @omnidan will also be happy that we depend on a much newer version than 1.4.21 ;)

**Comment by Namoshek** [comment]
I don't really know where the version difference comes from, but I guess the nodejs version of npm uses a different registry or something like that.

PS: Yes, I would not install *random* software like that, but I trust the nodejs crew. They got a lot to lose.

**Comment by markus2330** [comment]
> I don't really know where the version difference comes from, but I guess the nodejs version of npm uses a different registry or something like that.

What do you mean? 1.4.21 is what is in Debian Jessie.

Forgot to mention (in this ticket) I also use npm 3.10.8 and nodejs v6.9.1 now.

> I trust the nodejs crew

It is a remote executed script without any chain of trust, there are much more parties to trust here in the delivery process, e.g. DNS. But adding some random URL in sources.list is not much better, too.

**Comment by Namoshek** [comment]
> What do you mean? 1.4.21 is what is in Debian Jessie.

Sure, I don't question this. But the difference between 1.4.12 and 3.10.8 is quite huge, so I wonder where **this** difference comes from. In other words, why the official npm package in debian jessie seems to be ages back in the history. The last 1.4 release (1.4.28) was on 2014-09-14 according to [their github tags](https://github.com/npm/npm/tags?after=v2.0.2), so it is really old and not just configured differently.

**Comment by markus2330** [comment]
That is the different perception of time regarding different technologies! In C++ 2011 is recent, 2014 brand-new. In C, 1999 is too new for some (e.g. msvc++).

If you think it is not feasible to add a cmake check about which npm/nodejs works, we can close the issue.

**Comment by Namoshek** [comment]
Then we close it. I'll add a more emphasized hint in the tutorial.
