### ISSUE TITLE
RSS functionality

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1155]
I do not find the RSS link on the website nor does the "subscribe" button work?

**Comment by Namoshek** [comment]
You never mentioned anything like that so far, I need more info what exactly you want/need.

**Comment by markus2330** [comment]
I thought it is implemented in `src/tools/rest-frontend/resources/grunt-tasks/grunt-create-website-news-rss.js`?

It is enough to generate RSS entries as done in http://doc.libelektra.org/news/feed.rss

The old RSS generator is now broken  because the NEWS.md is now split up. I thought this is obvious, sorry if it was not.

**Comment by Namoshek** [comment]
I only knew of files like http://doc.libelektra.org/news/190576e0-9fef-486e-b8da-c4e75be08329.html, not about the feed.rss. (To be honest, I've never used RSS feeds in my life, for me its antique technique...)

**Comment by markus2330** [comment]
> I've never used RSS feeds in my life, for me its antique technique

I am open to something else (people need to change anyway thus the old feed will stop displaying new news), is there another technology where people can subscribe to news without us being dependent on external servers/companies (such as twitter, facebook and so on)? What do you use?

Newsletter would be a way, but it seems to be like much more effort (for us) with less usability.

> What button on the website btw?

For RSS/Atom there are standard buttons used everywhere (we should use, too). But by having some information in the html header, browsers also show a "subscribe" button (we do not have control over).

**Comment by Namoshek** [comment]
> What do you use?

Does "nothing" count as answer? :wink:

> For RSS/Atom there are standard buttons used everywhere (we should use, too). But by having some information in the html header, browsers also show a "subscribe" button (we do not have control over).

Then I'll look up this information, ty.
