### ISSUE TITLE
rest-frontend installation

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1161]
- [x] add auto-restart for rest-backend
- [x] make build script kill the rest-backend after install (force restart)
- [x] make build script recompile rest-frontend
- [x] https certificate

- [x] the rest-frontend@1.0.0 postinstall is verbose.

## Not so important
- Using npm 3.10.8 and nodejs v6.9.1 I get some warnings:
```
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.0.5: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global jshint@0.9.1 should be installed with -g
... (a lot of output)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN rest-frontend@1.0.0 No repository field.
npm WARN rest-frontend@1.0.0 license should be a valid SPDX license expression
```

**Comment by Namoshek** [comment]
As far as I can see, above dependencies are no direct dependencies, i.e. I've no control over the version that is used by a vendor package. The global hints are ok, but I'm not sure if I can change it and it does also not make sense (we don't want to pollute systems with our packages).

The installed packages (the hierarchy that gives a huge output) could be surpressed with `--silent`, but should we really do that in an installation? If I compare the output of npm to the rest of the Elektra installation, it is not "that much" tbh...

**Comment by Namoshek** [comment]
By the way, frontend is installed at [community.markus-raab.org](http://community.markus-raab.org/home). It is, however, not installed via the built script yet. I first want it to work before I adapt the built script.

**Comment by markus2330** [comment]
> dependencies are no direct dependencies

Ok, then it is low priority for now.

> If I compare the output of npm to the rest of the Elektra installation, it is not "that much" tbh...

What do you mean? I think there is no other output from Elektra? Otherwise it is only the list of files (standard CMake output).

If `--silent` still outputs errors and write log files it might be a good option?

> By the way, frontend is installed at community.markus-raab.org

Great!

**Comment by Namoshek** [comment]
> (standard CMake output).

That's what I mean.

I think `--silent` can still output errors and warnings or if not, there is another option.

**Comment by Namoshek** [comment]
The website should now be fully functional, I added the API on port 8088 for the moment.

**Comment by markus2330** [comment]
Thank you! Should we change www.libelektra.org (is there already a restart feature if the rest-backend crashes/is updated?)

>  I added the API on port 8088 for the moment.

I see no reason to change it?

Is the frontend/backend already build by the build server? Can you give some details about the installation? (Web Server,...)

**Comment by Namoshek** [comment]
> (is there already a restart feature if the rest-backend crashes/is updated?)

No and the installation is also done by hand, not by the build script yet. Just needed to get the setup working before I can do that.

> I see no reason to change it?

Well, if we want to expose the API as stand-alone feature, we should use a subdomain for it. But we can add this routing also internally, additionally.

> Is the frontend/backend already build by the build server? Can you give some details about the installation? (Web Server,...)

About build see above. I cloned the repo manually in the jenkins home dir, built it (similar to the build script), copied the rest-frontend and rest-backend into a special working directory (/home/jenkins/website) and set everything up in there. Both applications are using an apache2 installation. For the frontend the webroot is in /home/jenkins/website/rest-frontend/public and for the backend I'm using an scgi proxy (or however this is called) as described on the cppcms website.

Todos are:
- [ ] add service for backend (auto-restart)
- [ ] make build script copy rest-frontend and rest-backend from build directory to /home/jenkins/website
- [ ] make build script set the LD_LIBRARY_PATH for the rest-backend
- [ ] make build script restart the rest-backend after copy
- [ ] make build script recompile frontend (+ backup config, it should not get overwritten)

**Comment by markus2330** [comment]
> Well, if we want to expose the API as stand-alone feature, we should use a subdomain for it. But we can add this routing also internally, additionally.

Yes, we have to route it internally, there is no additional ipv4 address. I added restapi.libelektra.org (same IP as community).

> Both applications are using an apache2 installation.

Good!

> scgi proxy (or however this is called)

Which module did you use? If you use the fcgi you can also automatically start up the backend if needed. Hopefully we do not need a systemd service for starting the backend then. (I do not know what it does on crashes? So maybe we need the service anyway.)

> Todos are

I added them in the top post.

> LD_LIBRARY_PATH

Better if we can avoid that. Simply change the installation folder.

>  make build script restart the rest-backend after copy

Please prefer reloading.

> frontend backup config

That is ugly. Can you read two files and merge them (custom files wins)? Then manual changes could be done in a file that is not installed.

**Comment by Namoshek** [comment]
> Better if we can avoid that. Simply change the installation folder.

Can I install everything into its default paths, i.e. /usr/local? That would make it a lot easier. It would also prevent the frontend configuration from being overwritten, for example. I just thought you want to have everything installed in the working directory, as the build script was written this way.

> Which module did you use? If you use the fcgi you can also automatically start up the backend if needed. Hopefully we do not need a systemd service for starting the backend then. (I do not know what it does on crashes? So maybe we need the service anyway.)

It is not fast-cgi, but scgi ... I'm using mod_scgi (I think it basically does exactly the same as fast-cgi, but configuration is simpler). Yes, it does not allow for auto-start of the backend, but I think we should manage this separately anyway. A service to restart the backend seems best to me.

> Please prefer reloading.

What do you mean by that? The restbackend only knows on and off.

**Comment by markus2330** [comment]
> Can I install everything into its default paths, i.e. /usr/local? That would

Of course, the container is dedicated for the homepage only.

> make it a lot easier. It would also prevent the frontend configuration from
> being overwritten, for example.

Why is this connected? The frontend configuration would be overwritten with 
installation, too?

> I just thought you want to have everything installed in the working 
> directory, as the build script was written this way.

It is the "jenkins way" to only operate within $WORKSPACE. But for this case 
it seems we have good reasons to do otherwise.

> It is not fast-cgi, but scgi ... I'm using mod_scgi (I think it basically
> does exactly the same as fast-cgi, but configuration is simpler). Yes, it
> does not allow for auto-start of the backend, but I think we should manage
> this separately anyway. A service to restart the backend seems best to me.

It has different pros and cons. A service might handle restarts better, but..

> > Please prefer reloading.
> 
> What do you mean by that? The restbackend only knows on and off.

..reloading can only work with fcgi support from the server. Reload would be 
that both processes run next to each other and no user would get failures. But 
I am not sure how well this is handled and if it is worth the effort.

**Comment by Namoshek** [comment]
> Of course, the container is dedicated for the homepage only.

Is jenkins (and his user) even able to install the files globally? I guess for /usr/local he needs more privilegues than he has?

**Comment by markus2330** [comment]
You can either prepare some scripts that the jenkins user can trigger with sudo (without password) or you can chown /usr/local to jenkins.

**Comment by Namoshek** [comment]
It seems that systemd is not the current service manager (`ps -p 1 -o comm=` returns `init`). The package that enables the symlinks (`systemd-sysv`) is installed, so I guess a reboot should do it. But unfortunately it seems I'm not able to issue one:
```
Failed to read /proc/cmdline. Ignoring: No such file or directory
Failed to open initctl FIFO: No such device or address
Failed to talk to init daemon.
```

**Comment by markus2330** [comment]
There is no service manager/systemd currently running, it is a chroot within a container (which does not have systemd). There is no way to reboot a chroot. If you cannot start/use systemd, then simply write a shell loop respawning the process, so something like:

```
until kdb run-rest-backend; do
    logger "Server crashed with exit code $?.  Respawning.."
done
```

Within the jenkins job you simply kill the currently running process via the pid file, and the loop will respawn the rest-backend.

**Comment by markus2330** [comment]
(Btw. within the loop we should also collect core dumps and so on, so it might be useful to have the loop in any case)

**Comment by Namoshek** [comment]
Then I probably need to rewrite the run script, because it seems to save the pid even if the process couldn't be started.

**Comment by markus2330** [comment]
I think both scripts are useful (and should be separate), one that starts it up a single time and one that keeps it running forever (and collects core dumps+logs problems).

**Comment by Namoshek** [comment]
I got that, don't worry. But if the loop calls `kdb run-rest-backend` and this script overrides the pid file for every attempt, I can't force a stop anymore. But when thinking about this, I can't do it by pid anyway, because it will always "start" and just fail on using the port. Only option would be doing it via the process name therefore.

**Comment by Namoshek** [comment]
For some reason I can't connect to the server anymore, getting `ssh_exchange_identification: read: Connection reset by peer`. Yesterday when I closed the connection, everything was fine...

**Comment by markus2330** [comment]
Fixed, the issue was that `/var/run/sshd` was owned by jenkins.

**Comment by Namoshek** [comment]
Thank you!

**Comment by Namoshek** [comment]
For some reason the backend doesn't seem to recognize the configuration for the api description (although it is set in three namespaces + spec); the rest should work though. I added a script in the jenkins home directory that checks every 10 seconds if the PID is still up - otherwise it launches the start script (`kdb run-rest-backend`).

How can I collect core dumps?

**Comment by markus2330** [comment]
> For some reason the backend doesn't seem to recognize the configuration for the api description (although it is set in three namespaces + spec); the rest should work though.

Is there anything you do different internally? Does `kdb get` work? Is the issue for raw or html?

> I added a script in the jenkins home directory that checks every 10 seconds if the PID is still up - otherwise it launches the start script (kdb run-rest-backend).

That is not a good idea (polling), its better if the script starting the process also respawns when the process terminates (e.g. crashes).

> How can I collect core dumps?

Not so important, let us do this later.

**Comment by Namoshek** [comment]
> Is there anything you do different internally? Does kdb get work? Is the issue for raw or html?

No, I'm using the same method than for the other config values and kdb get works fine. The issue applies to both, raw and html.

> That is not a good idea (polling), its better if the script starting the process also respawns when the process terminates (e.g. crashes).

This should be the case actually, with a max delay of 10s.

**Comment by markus2330** [comment]
> No, I'm using the same method than for the other config values and kdb get works fine. The issue applies to both, raw and html.

Strange, there is even a unit tests that it works?

> This should be the case actually, with a max delay of 10s.

The main issue is that many things can go wrong with the pid files, too.

**Comment by markus2330** [comment]
Sorry, "https certificate" is still open

**Comment by Namoshek** [comment]
> Strange, there is even a unit tests that it works?

It passes the validation stage, so it should be in the config, yes...

> The main issue is that many things can go wrong with the pid files, too.

The worst case scenario is that the script tries to start the backend every 10 seconds and fails.

> Sorry, "https certificate" is still open

Would be nice if you could help me with that, I haven't set something like that up yet.

**Comment by Namoshek** [comment]
I found the error. The API description is dispatched from the application root, which does not start with a slash. When mounting the backend through SCGI, it will always send the trailing slash, which leads to a 404. Will make a PR for it.

**Comment by markus2330** [comment]
> The worst case scenario is that the script tries to start the backend every 10 seconds and fails.

Unfortunately that is not true. The worst case is that it spawns up a new process every 10 seconds until the machine is out of memory.

>  Would be nice if you could help me with that, I haven't set something like that up yet.

I did it for https://restapi.libelektra.org/, letsencrypt repo is in /root/letsencrypt

> Will make a PR for it.

Thanks!

**Comment by Namoshek** [comment]
>Unfortunately that is not true. The worst case is that it spawns up a new process every 10 seconds until the machine is out of memory.
>> That is not a good idea (polling), its better if the script starting the process also respawns when the process terminates (e.g. crashes).

It could also be done via `await kdb run-rest-backend` probably and with `pkill rest-backend` in the build script, does this sound better to you?

> I did it for https://restapi.libelektra.org/, letsencrypt repo is in /root/letsencrypt

And how does this work? From their docu I'm not really getting anywhere...

**Comment by markus2330** [comment]
> It could also be done via await kdb run-rest-backend probably and with pkill rest-backend in the build script, does this sound better to you?

This does not really change much, it needs to be started in a blocking way (not setting it in the background). But we do not really need to solve the problem in case of crashes, cppcms already did it for us: service.worker_processes

Btw. cppcms can write pid files itself via daemon.lock, that would be better than your current approach for run/stop.

For security reasons daemon.user should be set, too.

> And how does this work? From their docu I'm not really getting anywhere...

www.libelektra.org cannot be added at the moment because the DNS entry does not exist.

For some reason community.libelektra.org cannot be selected, did you enable this site in the same way as restapi? Can you add an entry for snippets.libelektra.org and web.libelektra.org, maybe it will work then for snippets/web.

Did you make sure that only https://restapi.libelektra.org is used (even when the page is visited via http?).

**Comment by Namoshek** [comment]
> For some reason community.libelektra.org cannot be selected, did you enable this site in the same way as restapi? Can you add an entry for snippets.libelektra.org and web.libelektra.org, maybe it will work then for snippets/web.

Until now I haven't explicitely given the community site a `ServerName`, but now it has one. I added `web.libelektra.org` with a redirect to community, please try again.

> Did you make sure that only https://restapi.libelektra.org is used (even when the page is visited via http?).

Now it has a permanent redirect to the https variant!

> [ CppCMS stuff ]

Sounds like good ideas, I'll try some of it.

**Comment by markus2330** [comment]
> https://web.libelektra.org

done! https://community.libelektra.org/home works now too.

> Now it has a permanent redirect to the https variant!

Thank you!

Looks great, we should be finished soon!

**Comment by Namoshek** [comment]
> cppcms already did it for us: service.worker_processes

This seems like a good thing, but the setting I want to use (1 because of caching) does not work. The reason is that 1 is parsed as boolean... so either I drop boolean support for the convertion from keyset to json::value or I don't know. Can I enfore that `get<bool> ()` fails with help of specification (e.g. `check/type = int`)?

**Comment by markus2330** [comment]
> with help of specification `check/type`

Yes, exactly: you already have the type meta-data in the keys (copied by `spec` plugin, which now does not need `kdb global-mount` anymore, btw.). You should do so for the other types, too. Note that `check/type` uses CORBA types (see doc/METADATA.ini and src/plugins/type/), so it should be long or long_long (not int) and boolean.

> Btw. with the current cache two workers should be no problem, but if we introduce the cachefilter somewhen, this could be an issue I guess.

The guesswork based on the content of the string is not a very good idea anyway. But I do not really see a relation between cachefilter and two processes? The question is if your code works with external modifications of KDB (can scope with that someone else modifies the snippets/user KDB while running). If it does, multiple processes should be no issue.

**Comment by Namoshek** [comment]
> Yes, exactly: you already have the type meta-data in the keys 

But I need to check the type by hand, right?

> The question is if your code works with external modifications of KDB (can scope with that someone else modifies the snippets/user KDB while running). If it does, multiple processes should be no issue.

With two worker processes we would also have two caches or later two open KDB connections. I'm pretty sure this could lead to issues, e.g.
- Process A makes kdbGet on x
- Process B makes kdbGet on y
- Process A deletes x and executes kdbSet
- Process B makes an update on y and executes kdbSet

In the last step, the cache would append the deleted x resource again, if I'm not wrong.

**Comment by markus2330** [comment]
> But I need to check the type by hand, right?

The type checking is done in the type plugin, so when it says `check/type = long` you can assume it is `long`.

Or do you ask for something like `ks.get<any>()` where you automatically get the correct type returned? Sounds interesting, but is not yet available. So yes, you have to check by hand for which conversion/cast you need.

> In the last step, the cache would append the deleted x resource again, if I'm not wrong.

Not necessarily. Process B would get a conflict. You could use 3-way merging then (see ~libtools/include/merging/mergingkdb.hpp) which handles such situations easily (as long as not exactly the same snippet was edited).

**Comment by Namoshek** [comment]
> Or do you ask for something like ks.get<any>() where you automatically get the correct type returned? Sounds interesting, but is not yet available. So yes, you have to check by hand for which conversion/cast you need.

That was my idea. Or at least let the `get<int> ()` fail if it is a string, for example. This way the type logic could be in the library (tools) and the lookups could be written easier (although I think you don't like this style).

**Comment by markus2330** [comment]
You are right that `ks.get<int>` should throw if it is a different type (even if the content of the string would be convertible to a number). Consider this as a bug, see #1092.

And yes, I do not like the style to guess which type a string has based on its content ;)

In C++17 we could have a `get<variant<list of allowed types>>`.

For now the best way is query the meta data and then use a switch. (default is string). 

Just to be sure that you know: spec is not the only way to store meta data. Some storage plugins (dump, tcl) can store arbitrary meta data next to keys. And some storage plugins (yajl) have implicit knowledge of their types. But for applications `spec` is the best way, then you also have a place where to put the description and the user can query which configuration options are availabe.

**Comment by Namoshek** [comment]
> You are right that ks.get<int> should throw if it is a different type (even if the content of the string would be convertible to a number). Consider this as a bug, see #1092.

But it is only a bug in case the meta data for the type is available, which was not the case until now for cppcms options.

**Comment by Namoshek** [comment]
The backend does now run with a worker process and should restart in case of a crash; ofc I'll monitor it.

**Comment by Namoshek** [comment]
Is this ticket done?

**Comment by markus2330** [comment]
Yes, I made a follow-up: #1179
