### ISSUE TITLE
zsh completion requirements: better kdb ls

### ISSUE THREAD

**Issue by reox** [ElektraInitiative/libelektra#1167]
for a better zsh completion a tool would be nice, that gives more information than `kdb ls`.
It would be nice to have information if a key is leaf or a node and if it is a node, if subkeys (nodes or leafes) exists.
each item can be null seperated or seperated by newlines.

maybe such a command can be useful for someone else as well, so maybe null seperated values can be triggered using a cmdline option?

the output could look like this:
```
kdb super-ls /
system/foo node 1
system/foo/bla node 1
system/foo/bla/something node 4
system/foo/bla/something/a leaf
system/foo/bla/something/b leaf
system/foo/bla/something/c leaf
system/foo/bla/something/d leaf
system/bla node 1
system/bla/xx node 0
```

**Comment by markus2330** [comment]
@e1528532 maybe this is an easy first step? Please use null-separation, otherwise keys with news-lines will make trouble.

And we need a better name than super-ls ;)

**Comment by markus2330** [comment]
One more not-so-obvious note: the list should also contain mountpoints which are leaf. This is because after mounting you often do not have keys (non-existing file) in the mountpoint but want nevertheless get completion to the mountpoint.
