### ISSUE TITLE
Tools section on homepage

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1175]
To better advertise the tools around Elektra we should extend the homepage with

- [x] snippet sharing + how snippet upload looks like? or showing a curl interaction in asciinema?
- [x] qtgui + screenshot or showing a short gif?
- [x] webgui + screenshot of @omnidan or showing a short gif?
- [x] elektrify your apps with link to application-integration tutorial

**Comment by Namoshek** [comment]
Images are no problem, but then please give them to me, I don't want o make them on my own.

Curl interaction for snippet sharing is probably too complicated (possible, but complicated). Not sure if a picture is a good replacement, as it should be clear what you have to fill out for an upload when you look at existing snippets. We should definitely explain/mention the snippet sharing on the home page, but not sure how detailed.

**Comment by markus2330** [comment]
> but then please give them to me

Ok, np, I will do a screenshot for qt-gui.

For "other applications", maybe  @beku has a screenshot which shows some oyranos application interacting with Elektra.

@omnidan can you point to some screenshots for the GUI?

> Curl interaction for snippet sharing is probably too complicated (possible, but complicated)

Yes, we obviously need a script that does that. The credentials can be stored encrypted in KDB.

**Comment by beku** [comment]
@Namoshek here a screenshot of a Oyranos color device view:

![screenshot_20161208_112347](https://cloud.githubusercontent.com/assets/497823/21006374/f033801e-bd38-11e6-9067-e0e4debb6e0a.png)
KDE KolorManager with d-bus updated device list. The device messages come from oyranos-monitor-daemon, which manages device setup.

**Comment by beku** [comment]
@Namoshek in case you need a logo, here comes the one for KM/Oyranos
![Oyranos Logo](https://camo.githubusercontent.com/bd4d8a460dd6cc974b833880761527d43da97216/687474703a2f2f7777772e6f7972616e6f732e6f72672f696d616765732f6f7972616e6f735f6c6f676f2e737667)

**Comment by markus2330** [comment]
@beku Thank you! Can we add them to our repo (BSD licenced)?

I added tree.libelektra.org/doc/images/qtgui.png

![screenshot qtgui](https://github.com/ElektraInitiative/libelektra/raw/master/doc/images/qtgui.png)

**Comment by beku** [comment]
@markus2330 yes please do, BSD is fine for the pictures

**Comment by Namoshek** [comment]
> Yes, we obviously need a script that does that. The credentials can be stored encrypted in KDB.

I think we should keep this as improvement for the future with an own tool / kdb command, not only a script.

**Comment by markus2330** [comment]
> I think we should keep this as improvement for the future with an own tool / kdb command, not only a script.

I think it really is critical for the success of the snippet service as I do not really see a way to upload all the configuration files lying around via the web interface. Do not get me wrong: the web interface is really nice, but it is not suitable for mass-up/downloads.

Furthermore I think the script is quite trivial: If written in bash it is some kdb, curl and jshon calls (@tom-wa can help you here, he has written dozens of such scripts, often using "APIs" not documented at all), if written in pyton you do not need any external lib (@reox can help you there).

In the long term, the same script should communicate with your API and also with @omnidan's API, this was also the reason for the coordination meeting of how the API should look like.

> Shouldn't we wait with this until a proper version was released?

We can comment out the part in html before homepage release until webgui release, but I would like to see the whole website as it should be.

**Comment by omnidan** [comment]
@Namoshek you can find screenshots on my presentation: http://slides.com/omnidan/remote-configuration-management#/3

**Comment by Namoshek** [comment]
I think it would look better if we would use wide-screen images for the website, i.e. something around the 2:1 ratio. The resolution itself is not so important, but should be above 600px in the width.

**Comment by markus2330** [comment]
Thanks for the hint! I updated qtgui.png to 1161 x 480 and triggered the homepage rebuild.
Some links in the text next to the screenshots would be nice. Is it possible that the screenshots themselves are links? Or is it possible to show them larger when clicking on them?

**Comment by markus2330** [comment]
The new image is used now but it is very small. Can you resize it or do you need another resolution?

**Comment by markus2330** [comment]
I also updated http://asciinema.org/a/0z7byvhbyljcnfx89qwd8wxrb

**Comment by markus2330** [comment]
Thank you, looks great now!

Thanks to all who supplied us with logos/images!
