### ISSUE TITLE
kdb export/import/editor should support provides

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1178]
# Describe what you wanted to do

`kdb export /hello json`

# Describe what you expected

That it is exported as json like it does with `kdb mount`.

# Describe what actually happened

Plugin is not found.

# System Information

- Elektra Version: master

# Getting started

`pluginDatabase->lookupProvides (plugin.getName ());`

**Comment by MasterToney** [comment]
Implemented with PR #3191
@markus2330 can we close this issue?

**Comment by markus2330** [comment]
Thank you for fixing it! :sparkling_heart:
