### ISSUE TITLE
homepage installation

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1179]
- [x] add keep-alive-rest-backend.sh to scripts
- [ ] user of rest-backend should have minimal rights (not jenkins)
- [x] describe setup of homepage server
- [x] snippets should be in git repo, accessible only from rest-backend user

**Comment by Namoshek** [comment]
> add keep-alive-rest-backend.sh to scripts

It is not even used anymore thanks to the cppcms worker_processes configuration.

> user of rest-backend should have minimal rights (not jenkins)

I'm not the right one to do this. My knowledge about unix permissions is terrible and I don't want to be responsible for anything. If you think we need a change here, please go ahead.

> snippets should be in git repo, accessible only from rest-backend user

Is the git plugin sufficient for that?

**Comment by markus2330** [comment]
>  It is not even used anymore thanks to the cppcms worker_processes configuration.

That is good, but it is still running `jenkins  11250  0.0  0.0   4324   244 ?        S    Dec06   0:13 sh keep-alive-rest-backend.sh` and still lies around at /var/lib/jenkins/keep-alive-rest-backend.sh. Can you clean this up?

>  I'm not the right one to do this. My knowledge about unix permissions is terrible and I don't want to be responsible for anything. If you think we need a change here, please go ahead.

Ok, then please describe the rest of the setup, I will do this tweak.

> Is the git plugin sufficient for that?

It would be, but it needs a very recent libgit not available in jessie and thus it is easier to write a script which does the git commit. I think it would be also useful to have everything exported in multiple formats (dump is not so friendly to be read or written).

So the script would do something like:
```
kdb export /snippets ini > snippets.ini
git commit -a -m "autocommit"
```

**Comment by Namoshek** [comment]
> Ok, then please describe the rest of the setup, I will do this tweak.

Where? It doesn't really fit in the tutorial because too much custom stuff of us is involved.

**Comment by markus2330** [comment]
> Where?

Good question. Maybe the tutorial is not so bad after all, you can write it in a way "example for how you could configure the snippet service, here we describe how we did it for www.libelektra.org" in an extra section at the end?

**Comment by Namoshek** [comment]
Can you create a new repo for the snippets?

**Comment by markus2330** [comment]
> Can you create a new repo for the snippets?

I created https://github.com/ElektraInitiative/snippets

> And what user do we use to push them?

I think we need to create a new github user. How should we call it? elektrabot?

**Comment by Namoshek** [comment]
Sure, why not.

**Comment by Namoshek** [comment]
Do you want to create it or should I? I think it is better if you keep the access to yourself and add an ssh key...?

**Comment by markus2330** [comment]
@elektrabot exists and is ready to serve you.

(ssh keys are in /var/lib/jenkins/.ssh, snippet repo is in /var/lib/jenkins/snippets, pushing the initial commit worked)

**Comment by Namoshek** [comment]
And the script works as well, first auto-commit done!

It delays the insert/update of snippets quite significantly though. Can I also run the shell script in the background to not block the service?

**Comment by markus2330** [comment]
> And the script works as well, first auto-commit done!

Perfect!

> It delays the insert/update of snippets quite significantly though. Can I also run the shell script in the background to not block the service?

I would say that is advisable. Also make sure they run guarded with `flock` so that we do not have a bad surprise once people actually upload a snippet at the same time.

What would be great is if you can also change the commiter name/e-mail to the person that actually did something. Maybe you can pass the information via environment when doing `kdb set`?

> Btw. which plugin should we use? For the moment I've chosen ni, but personally I think yajl would be nicer.

The snippet database itself might be best to stay in dump (but should be also in the snippet repo). But then we can export every snippet into multiple formats, I think ni, ini, xmltool, and yajl should be included! Furthermore it would be great if the initial format would be available, too. Maybe you can pass this information also via environment variables.

Please add the script to scripts.

Btw. I am currently doing jenkins upgrades...

**Comment by Namoshek** [comment]
> What would be great is if you can also change the commiter name/e-mail to the person that actually did something. Maybe you can pass the information via environment when doing kdb set?

Can you elaborate on that? I know what you mean, but I've no idea how to do it. But if it involves adding additional logic to the rest-backend, then I'm against it. I don't want to add stuff that is only very specific for our needs.

> Furthermore it would be great if the initial format would be available, too. Maybe you can pass this information also via environment variables.

Initial format? You mean what we use internally to store the snippets?

**Comment by markus2330** [comment]
> Can you elaborate on that?

Before calling `kdb.set` you simply do `setenv("REST_USER", theusername, 1);...` and within the shellscript you use `$REST_USER`. Should be very simply, no logic needed.

>  Initial format? You mean what we use internally to store the snippets?

Yeah, I mean what is actually mounted and snippets are stored to. The place I can modify to upload my own snippets without using the GUI ;)

**Comment by Namoshek** [comment]
> Before calling kdb.set you simply do setenv("REST_USER", theusername, 1);... and within the shellscript you use $REST_USER. Should be very simply, no logic needed.

That might be no logic, but still it is too heavily bound to our use case in my opinion...

> Yeah, I mean what is actually mounted and snippets are stored to. The place I can modify to upload my own snippets without using the GUI ;)

Don't get this. If you speak of `system/configs`, then it's irrelevant, because the path is removed during `kdb export`. So you can import the snippets repo wherever you want (except for dump, but I would only see it as backup anyway).

**Comment by markus2330** [comment]
> That might be no logic, but still it is too heavily bound to our use case in my opinion...

Such information is usually available when calling `kdb`. Then the shell sets `PWD` and so on. So it would be nice if the rest service can do it instead of the shell. It is not really specific to our script.

It is enough if you pass information that you have readily available. name, e-mail and format should be enough.

> So you can import the snippets repo wherever you want (except for dump, but I would only see it as backup anyway).

I do not mean importing it. I mean that I modify the repo, push the content, and then I restart the rest-backend (on the homepage agent) so that the new snippets are available. We already discussed this.
