### ISSUE TITLE
build.libelektra.org not reachable (SSL)

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1181]
- [x] please fix issue
- [ ] please find out why the backend went down
- [x] please change the contact address webmaster@localhost to webmaster@libelektra.org
- [x] where does the lock file go? (might be the cause for leaky fd)
- [ ] is Elektra uninstalled before installing it? (or how are files removed that are no more needed?) Hint: install_manifest.txt in build directory contains all installed files. See https://tree.libelektra.org/doc/INSTALL.md for how to uninstall
- [x] letsencrypt has issues with `git*.libelektra.org` (can you configure apache differently?).

```
> curl https://restapi.libelektra.org/version
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 webmaster@localhost to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at restapi.libelektra.org Port 443</address>
</body></html>
```

**Comment by Namoshek** [comment]
Hm, can't really tell why it happened. But the website doesn't look up-to-date, so I triggered another build. Let's see if the problem occurs again.

**Comment by markus2330** [comment]
> Hm, can't really tell why it happened.

Was it still running? Any core dump?

Could you please add build date to web site (maybe even build id somewhere hidden).

**Comment by Namoshek** [comment]
> Was it still running? Any core dump?

Nope and I think jenkins is the issue. It restarts properly during the build but dies after the build with the message
> Process leaked file descriptors. See http://wiki.jenkins-ci.org/display/JENKINS/Spawning+processes+from+build for more information

I also encountered that apache is not serving the updated frontend files even though they are definitely on the hard drive.

> Could you please add build date to web site (maybe even build id somewhere hidden).

I add it to the tasks...

**Comment by markus2330** [comment]
> Process leaked file descriptors.

Maybe you do not have the `daemon.enable` option activated?

Btw. security.csrf.enable is irrelevant for us, isn't it?

> I add it to the tasks...

Thanks!

**Comment by Namoshek** [comment]
> Maybe you do not have the daemon.enable option activated?

Wasn't enabled, but still the same happens...

> Btw. security.csrf.enable is irrelevant for us, isn't it?

That's why it is not part of the specification, yes.

**Comment by markus2330** [comment]
> Wasn't enabled, but still the same happens...

Maybe its necessary to get rid of all `&`, you do not need to put something in the background if it daemonizes anyway (maybe it even causes the issue).

> That's why it is not part of the specification, yes.

Good to know that not being part of the specification is not arbitrary. You always surprise with careful work!

**Comment by Namoshek** [comment]
You are right, removing the `&` solves the leaking file descriptor issue, but the rest-backend still goes down at the end of the build for whatever reason...

**Comment by markus2330** [comment]
So the rest-backend goes down after building the web page? Or does it also goes down on other occasions?

**Comment by Namoshek** [comment]
As far as I can say, it only goes down because the build somehow terminates it at the end (after it was already restarted).

**Comment by markus2330** [comment]
Can you add some logs so that we can see why it goes down? Maybe its enough to configure `logging` in the cppcms config.

**Comment by Namoshek** [comment]
I configured the cppcms logger but it behaves strange. If I run the backend manually, the log is written properly, but if the jenkins build starts the backend, the log doesn't seem to be used. I configured the logger in the system namespace, so it should work I guess?

**Comment by markus2330** [comment]
I added `kdb export` to see and restarted the job. What is the scripts/build-homepage-test?

**Comment by Namoshek** [comment]
The script calls a copy of `kdb run-rest-backend-daemon` with removed `&`; I wanted to try it before making anything in the source.

**Comment by Namoshek** [comment]
> 2016-12-11 13:10:03; cppcms, info: Catched signal 17 (service.cpp:655)
2016-12-11 13:10:03; cppcms, info: Catched signal 15 (service.cpp:655)
2016-12-11 13:10:03; cppcms, info: Shutting down (service.cpp:702)
2016-12-11 13:10:03; cppcms, debug: Killing Children (service.cpp:704)
2016-12-11 13:10:03; cppcms, debug: Children are dead (service.cpp:717)


Obviously jenkins is killing the process...

**Comment by markus2330** [comment]
> I wanted to try it before making anything in the source.

It is more transparent what you try if you create a PR and trigger the job from there.

What was the reason that the logging did not work at first?

> Obviously jenkins is killing the process...

Maybe the combination of worker_processes and daemon.enable is causing troubles? 

I added pstree at the end of the script and retriggered.

Btw. is configure-rest-frontend a good name? Shouldn't it be recompile-rest-frontend?

**Comment by Namoshek** [comment]
> It is more transparent what you try if you create a PR and trigger the job from there.

Okay, I'll do so next time.

> What was the reason that the logging did not work at first?

I'm not really sure. I tried it two times myself before you triggered the build, both times nothing seemed to happen. And I had `tail -f /home/jenkins/rest-backend-cppcms.log` running all the time, so I can see if something changes (`tail: rest-backend-cppcms.log: file truncated`).

> Maybe the combination of worker_processes and daemon.enable is causing troubles?

I hope not.

But interestingly the rest-backend seems to be still up after the last build; I've not started it manually since then.

> Btw. is configure-rest-frontend a good name? Shouldn't it be recompile-rest-frontend?

Both names are not really fitting because the script does quite a lot of stuff, starting from bundling the JS stuff, via creating a structure file to copying everything. But if I think about it, nothing is "compiled" at all... maybe (re)build would be better.

**Comment by markus2330** [comment]
> Okay, I'll do so next time.

Btw. please always retrigger the homepage build on PRs (even if you do not need it). Its easier for me to validate when I see the site.

> maybe (re)build would be better.

Yes, build is a nice word for this!

**Comment by markus2330** [comment]
Two things are not yet documented:

- where does the lock file of the rest backend go? (might be the cause for leaky fd) We should use an absolute path here (outside the working space)
- is Elektra uninstalled before installing it? (or how are files removed that are no more needed?) Hint: install_manifest.txt in build directory contains all installed files. See https://tree.libelektra.org/doc/INSTALL.md for how to uninstall

Btw. letsencrypt has issues with `git*.libelektra.org`. Can you reconfigure apache without this character?

Successful updated were following SSL certificates:
https://www.ssllabs.com/ssltest/analyze.html?d=master.libelektra.org
https://www.ssllabs.com/ssltest/analyze.html?d=raw.libelektra.org
https://www.ssllabs.com/ssltest/analyze.html?d=community.libelektra.org
https://www.ssllabs.com/ssltest/analyze.html?d=bugs.libelektra.org     
https://www.ssllabs.com/ssltest/analyze.html?d=github.libelektra.org        
https://www.ssllabs.com/ssltest/analyze.html?d=blob.libelektra.org        
https://www.ssllabs.com/ssltest/analyze.html?d=tree.libelektra.org      
https://www.ssllabs.com/ssltest/analyze.html?d=web.libelektra.org    
https://www.ssllabs.com/ssltest/analyze.html?d=build.libelektra.org     
https://www.ssllabs.com/ssltest/analyze.html?d=restapi.libelektra.org 


I updated the ticket above.

**Comment by Namoshek** [comment]
> where does the lock file of the rest backend go? (might be the cause for leaky fd) We should use an absolute path here (outside the working space)

Good idea, I will try this.

> is Elektra uninstalled before installing it?

No, and I'm afraid this would lead to unavailability (of the frontend).

> Btw. letsencrypt has issues with git*.libelektra.org. Can you reconfigure apache without this character?

Saved one file, but ok, I'll change it. :+1:

**Comment by Namoshek** [comment]
Can you add a certificate for git.libelektra.org (only if it is necessary, we redirect anyway).

**Comment by markus2330** [comment]
Done, git and github were added. Thanks for splitting.

https://www.ssllabs.com/ssltest/analyze.html?d=git.libelektra.org
https://www.ssllabs.com/ssltest/analyze.html?d=github.libelektra.org

www.libelektra.org is the only one missing from the config. libelektra.org is not yet part of the config.

**Comment by Namoshek** [comment]
What do you mean? www.libelektra.org exists already (points to community.libelektra.org) and I just added libelektra.org itself.

**Comment by markus2330** [comment]
I mean that no SSL certificate can be created: letsencrypt requires the domain setup for verification.

So the last two SSL certificates will be done when we are finished with #1033 and domains are redirected.

**Comment by markus2330** [comment]
I also switched www.libelektra.org (because someone typed in https://www.libelektra.org which did not work). So the only remaining not switched Domain is https://libelektra.org  (still forwards to github)

https://www.ssllabs.com/ssltest/analyze.html?d=www.libelektra.org

**Comment by markus2330** [comment]
@sanssecours Oops, seems like our new www setup destroyed Elektra downloads:

https://bot.brew.sh/job/Homebrew%20Core/13297/version=yosemite/testReport/junit/brew-test-bot/yosemite/fetch_elektra/

@Namoshek can you fix that http://www.libelektra.org/ftp/elektra/releases/elektra-0.8.19.tar.gz points to the releases?

I copied the folder containing the releases to /srv/elektra

**Comment by markus2330** [comment]
@sanssecours a workaround would be to use https://github.com/ElektraInitiative/libelektra/releases/download/0.8.19/elektra-0.8.19.tar.gz

**Comment by Namoshek** [comment]
What do you think about introducing ftp.libelektra.org @markus2330 (+ the legacy fallback if necessary)?

**Comment by markus2330** [comment]
ftp.libelektra.org exists and is a CNAME to www.libelektra.org

Changing the domains now does not really help: we do not know when the DNS caches are updated for our users. (And cannot safely say to the brew people that they should trigger the build)

In longer term some redundancy would be nice, though.

**Comment by markus2330** [comment]
@Namoshek Is it a problem to redirect everything below /ftp/ to apache directly delivering the files? Would be good if we had a quick fix, the brew people might reject the PR if we cannot get this right on time.

**Comment by sanssecours** [comment]
> @sanssecours Oops, seems like our new www setup destroyed Elektra downloads…

Yeah, I already saw the problem. Currently I am working on defining the build and run-time dependencies of the formula. I will update the URL if the problem persists after I am finished with working on the dependencies.

**Comment by Namoshek** [comment]
On my system www.libelektra.org still redirects me to github; is it really changed to the homepage server already? I can't really test what I'm doing if I can't connect to the right server...

**Comment by markus2330** [comment]
Yes, http://www.libelektra.org seems to redirect, but https://www.libelektra.org/ftp/elektra/releases/elektra-0.8.19.tar.gz seems to work now. Something in the setup seems to be faulty ;)

> I can't really test what I'm doing if I can't connect to the right server...

Are you sure that this this is the problem?

If it is, kdb to the rescue:
```
sudo kdb mount --with-recommends /etc/hosts system/hosts hosts
sudo kdb set system/hosts/ipv4/www.libelektra.org 88.198.134.180
```

**Comment by Namoshek** [comment]
www.libelektra.org should now also serve the frontend + /srv for /ftp... the redirect script to github is not from me and also not linked anywhere in the configs.

**Comment by markus2330** [comment]
Both http+https access attempts are logged by apache2: `[16/Dec/2016:14:43:08 +0000] "GET /ftp/elektra/releases/elektra-0.8.19.tar.gz HTTP/1.1" 301 642 "-" "curl/7.38.0"`. So it has to be a configuration error somewhere within apache?

Maybe it is caused by a misconfiguration in HSTS?

**Comment by Namoshek** [comment]
The ftp works now on my machine too, but not the main page itself. The redirect is caused by a html file (like before), it can't be an apache config error.

**Comment by markus2330** [comment]
> The ftp works now on my machine too, but not the main page itself. The redirect is caused by a html file (like before), it can't be an apache config error.

Why do you think there is a html file involved? I do not think that a html file with the content
```
<p>The document has moved <a href="https://community.libelektra.org/ftp/elektra/releases/elektra-0.8.19.tar.gz">here</a>.</p>
```
exists.

www.libelektra.org should go to your homepage, except www.libelektra.org/ftp should go to the files in /srv. And this should happen with http and https in the same way. Currently, http and https do differently.

**Comment by markus2330** [comment]
So either we do the https upgrade differently, or also handle community.libelektra.org/ftp correctly.

**Comment by markus2330** [comment]
Btw. shouldn't we redirect to www.libelektra.org as canonical source (instead of community.libelektra.org). This might solve the problem..

**Comment by Namoshek** [comment]
It was a browser cache issue and yes, there was a html file like you mentioned above. I'll change the config to www.libelektra.org now. The setup will be so that all http:// urls redirect to the corresponding https:// url and only they will redirect to www.libelektra.org; then we have a clean setup!

**Comment by markus2330** [comment]
Thank you, good idea!

**Comment by Namoshek** [comment]
Everything should work now as expected. :+1:

**Comment by markus2330** [comment]
I also changed libelektra.org itself.

The only missing domains are:
```
dl                       IN A       88.198.134.177
doc                      IN A       88.198.134.177
download                 IN A       88.198.134.177
```

Can we prepare to update them, too?

**Comment by Namoshek** [comment]
What do you need for them?

**Comment by markus2330** [comment]
I copied the data to /srv/libelektra. The domains should provide the data to download.

I think mostly used was doc.libelektra.org/api, doc.libelektra.org/coverage and doc.libelektra.org/news.

doc.libelektra.org/news could also point to your new webpage, if it provides the same files (in a more pretty way).

dl and download are only aliases to doc.

**Comment by Namoshek** [comment]
Everything should be prepared:
```
http://dl.libelektra.org -> https://dl.libelektra.org
https://dl.libelektra.org ->https://download.libelektra.org

http://download.libelektra.org -> https://download.libelektra.org
https://download.libelektra.org -> /srv/libelektra

http://doc.libelektra.org -> https://doc.libelektra.org
https://doc.libelektra.org -> {
     "/" -> "/srv/libelektra"
     "/news" -> "/usr/local/share/elektra/tool_data/rest-frontend/public/news"
}
```

**Comment by markus2330** [comment]
Thanks! DNS and certificates are updated.

> Is it still correct that www.libelektra.org/ftp points to /srv?

Was this the case before? Would be good if we do not produce dead links.

**Comment by Namoshek** [comment]
It is not dead, it just has directory listing not enabled at the moment (e.g. see www.libelektra.org/ftp/elektra/releases/elektra-0.8.19.tar.gz). I'm asking this because it has to point to /srv instead of /srv/elektra for old links to work.

**Comment by markus2330** [comment]
> I'm asking this because it has to point to /srv instead of /srv/elektra for old links to work.

Ahh, thank you, then please fix it.

**Comment by markus2330** [comment]
And the link from the website to the build server is broken. Can you create a redirect from build.libelektra.org (port 80) to jenkins so that we have https links for the build server?

**Comment by markus2330** [comment]
https://doc.libelektra.org/api/ seems to be broken, too.

**Comment by markus2330** [comment]
http://build.libelektra.org redirects to https://build.libelektra.org:8080, but it gives the error SSL_ERROR_RX_RECORD_TOO_LONG. Do we need to fix jenkins or can we use apache to terminate the encryption there?

**Comment by Namoshek** [comment]
Weird. It should just be non ssl right?

**Comment by markus2330** [comment]
Ideally, http://build.libelektra.org should be SSL to the apache, hiding the jenkins. But yes, before it was non ssl.

**Comment by Namoshek** [comment]
Done

**Comment by markus2330** [comment]
Thank you, both work wonderful!

Actually we could now make jenkins listen to localhost?

Strangely DNS does not yet resolve doc.libelektra.org correctly for me.

**Comment by Namoshek** [comment]
I had the same issue, but after visiting https://doc.libelektra.org it worked. I think it is because of the cached index.html the browser still expects.

**Comment by markus2330** [comment]
There seems to be a regression in the redirection of https://doc.libelektra.org/news/ (it points to the "archive", not to the fancy pages).

**Comment by markus2330** [comment]
And I get an internal server error when visiting https://restapi.libelektra.org/

**Comment by markus2330** [comment]
building restapi docu and have it available is also an open issue?

**Comment by Namoshek** [comment]
> There seems to be a regression in the redirection of https://doc.libelektra.org/news/ (it points to the "archive", not to the fancy pages).

Impossible, there is no link/symlink/whatever that could cause this behavior. If you look at the https://doc.libelektra.org/news/feed.rss, you will also see that the generator is node, i.e. it is the correct one. The RSS pages were never pretty (RSS just isn't pretty).

> And I get an internal server error when visiting https://restapi.libelektra.org/
> building restapi docu and have it available is also an open issue?

That is the issue, it couldn't be done before we added doc.libelektra.org to the community server. I'll write a script for it.

**Comment by markus2330** [comment]
> you will also see that the generator is node

You are right, no regression, the redirection seems to work.

> The RSS pages were never pretty (RSS just isn't pretty).

I think we have a misunderstanding here. My question was why https://www.libelektra.org/news/0.8.15-release and https://www.libelektra.org/news/1ab4a560-c286-46d2-a058-1a8e7e208fe8.html are different pages. (the first one is the pretty one :smile:)

> That is the issue, it couldn't be done before we added doc.libelektra.org to the community server. I'll write a script for it.

Perfect, except for the apiary.io dep its nice (added to #1151)

**Comment by Namoshek** [comment]
> I think we have a misunderstanding here. My question was why https://www.libelektra.org/news/0.8.15-release and https://www.libelektra.org/news/1ab4a560-c286-46d2-a058-1a8e7e208fe8.html are different pages. (the first one is the pretty one :smile:)

Oh, lol. Well the first one is on the web page and the second one belongs to the rss feed. That's actually everything I can say about it..? ^^

**Comment by markus2330** [comment]
The rss feed is only a xml document that contains news entries. The other htmls are static pages that are linked from the rss feed, but otherwise have nothing to do with the rss feed.

In future we do not really need the long names anymore (we could also link to the short names). If you find an easy way it would be nice if the old perma links link to the pretty pages.

**Comment by Namoshek** [comment]
That's not gonna work, the website is not aware of the guids.

**Comment by markus2330** [comment]
Ok, thanks for the very nice apache setup! Let us close this issue.

**Comment by markus2330** [comment]
I also added https://www.ssllabs.com/ssltest/analyze.html?d=ftp.libelektra.org seems like we forgot it.
