### ISSUE TITLE
`kdb fstab` command is confusing

### ISSUE THREAD

**Issue by eschnett** [ElektraInitiative/libelektra#1188]
In my mind, in terms of Unix administration, `fstab` and `mount` are closely related concepts. It seems that `kdb fstab` creates Unix fstab entries, i.e. it changes the Unix installation. `kdb mount` on the other hand only performs actions internal to libelektra, i.e. it does not affect the Unix system.

When I first read about `kdb fstab`, I assume that this would also only change how `kdb mount` would work, maybe setting certain mount options automatically, so that one can e.g. use only a single argument to `kdb mount` instead of having to enter three arguments.

**Comment by markus2330** [comment]
Thanks for reporting!

Yes, you are right, we need to get rid of the `fstab` command. It basically only solves the issue that partial fstab settings are invalid (you can only set a full line within `/etc/fstab`, not parts of it). But the necessity to set many keys at once is a recurring one, so we need a template-based generic solution here (and not one that is specific to modifying `fstab` files).

> `kdb mount` on the other hand only performs actions internal to libelektra, i.e. it does not affect the Unix system.

In some way it does: it writes into `/etc/kdb` and all applications or tools using Elektra will honor the new mountpoint.

Maybe I elaborate a bit what `kdb mount` does: In analogy to fstab+mount in UNIX systems: `kdb mount` writes into Elektra's "fstab" (`/etc/kdb/elektra.ecf`) to set up a "automount". Every following `kdb get/set` command will then automatically honor the mountpoint, but also every other application using Elektra. (Hopefully this analogy was not confusing, too)

Btw. https://web.libelektra.org/ will be ready soon.

**Comment by markus2330** [comment]
As discussed in #265 we will remove the fstab command because it is confusing.

**Comment by markus2330** [comment]
We removed the fstab command. Now we only have `kdb mount`. I also improved the docu of `kdb mount` so that it is more clear that it persistently mounts files.
