### ISSUE TITLE
failing installation due to missing NEWS.md

### ISSUE THREAD

**Issue by Namoshek** [ElektraInitiative/libelektra#1208]
# Describe what you wanted to do

The removal of the NEWS.md in c821a6fccfe06808a961d8232e1955f363cf5edf causes make to fail during the installation.

```
CMake Error at doc/cmake_install.cmake:76 (file):
  file INSTALL cannot find
  "/home/marvin/Schreibtisch/libelektra-code/doc/NEWS.md".
Call Stack (most recent call first):
  cmake_install.cmake:38 (include)
```

# System Information

- Elektra Version: master

# Note

Instead of only removing the installation of the NEWS.md in the [CMakeLists.txt](https://tree.libelektra.org/doc/CMakeLists.txt), we could also add the new news files in the `doc/news` folder to the docu. This should be done in the `doc/CMakeLists.txt` though, as it would cause a constant warning in the news script of the rest-frontend if it was in an own CMakeLists in the `doc/news` dir.

**Comment by Namoshek** [comment]
Do we really need the news in the doxygen docu?

**Comment by markus2330** [comment]
Thanks for reporting the issue!

I do not think we need it in the doxygen docu (but could do so easily). For the file to be installed I simply merge all files in the news folder.
