### ISSUE TITLE
plugin simpleini has issue with empty keys

### ISSUE THREAD

**Issue by Namoshek** [ElektraInitiative/libelektra#1212]
## Describe what you wanted to do

While I moved users and snippets on the homepage server from one file to different mount points, I came across an issue with the simpleini plugin. I exported and reimported with the plugin and lost some keys, which I found later elsewhere.

(It was only one snippet used for tests, so nothing got lost)

## Describe what you expected

I expected the exported configuration (which is written correctly into the output file) to be re-imported correctly.

## Describe what actually happened

I created a minimal, complete and verifiable test example:
```
// create keys
$> kdb set dir/test/empty
Create a new key dir/test/empty with null value
$> kdb set dir/test/empty/a a
Create a new key dir/test/empty/a with string a
$> kdb set dir/test/empty/b b
Create a new key dir/test/empty/b with string b
$> kdb ls dir/test
dir/test/empty
dir/test/empty/a
dir/test/empty/b

// export
$> kdb export dir/test simpleini > test.ini
$> cat test.ini
empty =
empty/a = a
empty/b = b

// reimport
$> kdb import dir/test2 simpleini < test.ini
$> kdb ls dir/test2
dir/test2/empty
dir/test2/empty/b

// let's find the missing key
$> kdb export dir/test2 ni | cat
;Ni1
; Generated by Nickel Plugin using Elektra (see libelektra.org).

empty = empty/a = a
empty/b = b
```

## System Information

- Elektra Version: master

**Comment by markus2330** [comment]
Thanks for reporting the issue! I will look at it later.

Please prefer the shell recorder tutorial syntax the next time, then we can use it for regressions tests.

**Comment by Namoshek** [comment]
I still did not really get behind the shell recorder, but I'll remember for the next time.

**Comment by markus2330** [comment]
Basically it is only the reverse way, commands are as is, output as comment, for example:

```
kdb ls dir/test2
#> dir/test2/empty
#> dir/test2/empty/b
```

See tests/shell/shell_recorder/tutorial_wrapper/README.md
