### ISSUE TITLE
Convert with plugin augeas lens=Hosts.lns to simpleini

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1215]
I tried to convert a snippet on the website, but it seems like augeas adds the parent key with the temporary file to the keyset, but should not do that.

## Used plugins
```
Input:
- Plugin: augeas lens=Hosts.lns
- Format: none
- Additional config: 
Output:
- Plugin: simpleini
- Format: ini
- Additional config: % : %
```

## Input configuration
```
128.0.0.1 localhost
```

## Last output configuration
```
system = /tmp/2158-4829-518d-49b2
1 = 
1/canonical = localhost
1/ipaddr = 128.0.0.1

```

**Comment by Namoshek** [comment]
I noticed this also during testing, but as it does not happen for all lenses, I thought it might be lens-dependend.

**Comment by markus2330** [comment]
If the parent key itself is actually used the issue might be not visible.

But the file name should never show up in the keyset (for non-debug plugins).

**Comment by Namoshek** [comment]
Sorry, that was not intentional. Misclicked while still being half asleep. :)

**Comment by markus2330** [comment]
I think we can actually close it unless someone wants to continue to work on the snippet converter...
