### ISSUE TITLE
line plugin cuts of first line at export

### ISSUE THREAD

**Issue by Namoshek** [ElektraInitiative/libelektra#1227]
# Description

When comparing what I uploaded on the snippet sharing service and what I receive to download, the first line is always missing when I use the line plugin. This does not happen for other plugins like the hosts plugin for example.

It does by the way also happen when using the converter and line as in- and output format.

# System Information

- Elektra Version: master
- Snippet Sharing Version: master

# Ideas

Could it be that the line plugin currently needs the root key to be part of the key set (e.g. it just skips the first key on purpose)?
```
this/is/some/root/key       <-- probably skipped on purpose?
this/is/some/root/key/#0
this/is/some/root/key/#1
this/is/some/root/key/#2
```

**Comment by markus2330** [comment]
Thanks for reporting the issue!

The parentKey is skipped on purpose, because it actually should not contain content. (It is only there to correctly form an array).

**Comment by Namoshek** [comment]
Well that seems reasonable, but why does it skip the first line (i.e. `#0`)? Is the skip maybe implemented the wrong way?

**Comment by markus2330** [comment]
It is possible, but I cannot reproduce it with kdb:

```
kdb mount file.line /example/line line
cat /home/markus/.config/file.line
#> here
#> huhu
#> something
kdb ls /example/line
#> user/example/line
#> user/example/line/#0
#> user/example/line/#1
#> user/example/line/#2
 kdb export /example/line simpleini
#> user = 
#> #0 = here
#> #1 = is
#> #2 = something
kdb set /example/line/#1 huhu
#> Using name user/example/line/#1
#> Set string to huhu
kdb export /example/line simpleini 
#> user = 
#> #0 = here
#> #1 = huhu
#> #2 = something
kdb export /example/line line
#> here
#> huhu
#> something
```

**Comment by Namoshek** [comment]
I can try if the behavior changes if I add the parent key (an empty copy) to the keyset to export.

**Comment by markus2330** [comment]
I changed the line's behavior that *only* the parentKey is ignored. Maybe this works better?

**Comment by Namoshek** [comment]
I triggered a rebuild, let's see. It looks like it could do what I want it to, yes.

**Comment by Namoshek** [comment]
It seems to work, thank you for the quick fix!
