### ISSUE TITLE
website: Next Steps for Snippet Sharing

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1228]
From feedback:

- [ ] improve performance!
- [ ] make use case more clear!
- [ ] make formats more clear (what to do on any file)
- [ ] Simplify login
- [ ] Improve ways to give feedback

Here are some ideas how we can improve snippet sharing:

- [ ] upload more snippets!
- [ ] better description when to use `line`
- [ ] github auth/register
- [ ] markdown for description field
- [ ] allow curl put (curlget plugin) to upload snippets
- [ ] command-line tool to upload/download snippets
- [ ] introduce rating system
- [ ] commenting on snippets
- [ ] allow to upload snippets from the snippet converter
- [ ] upload format as column in search and "Raw" uses upload format
- [ ] combine multiple plugins, e.g. validation, transformations (see #1229)
- [ ] allow code to be inserted for transformation plugins
- [ ] "rename" snippets key (e.g. when changing organization, frontend creates a new snippet and removes the old one)

### Frontend Fixes

- [ ] github link if js does not work
- [ ] when creating snippets: clicking on "?" does not do anything (for hover you need patience, please show it immediately)
- [ ] support for compilation variants, see [HTML version of the crypto documentation](https://www.libelektra.org/plugins/crypto) (ifdefs should be removed)

### Setup Improvements

- [ ] make sure backend does not go down
- [ ] enable core dumps
- [ ] backup into private repo
- [ ] install apache log analyzer
- [ ] user of rest-backend should have minimal rights (not jenkins)

### Backend

- [ ] automated API Testing #931

###

Which of them do you find useful?

**Comment by e1528532** [comment]
I encountered two issues:
* You cannot change organization after you created a snippet and want to edit it because you forgot to specify the organization
* XML plugin needs improvements, wasn't able to recognize my maven configuration snippets

**Comment by markus2330** [comment]
Thanks for your feedback! I think the changing of organization would require some "rename" functionality, I added it in the list above.

The XML plugin would be a new completely new plugin. It might be not too hard to write, though (when using a XML parser with a nice API, e.g. look at `ni` plugin). xmltool is very old code, I can not recommend to base a new plugin on that code. Please open a new issue if you see an easy (~3h) way to do it.

@e1528532 I also added the other "better description when to use `line`" you mentioned at the meeting. From the docu it should be clear that `line` is the way to go if no other plugin fits. The file plugin #1047 would be a good alternative to line,though.

**Comment by Namoshek** [comment]
> I think the changing of organization would require some "rename" functionality, I added it in the list above.

I think it cannot or shouldn't be done in the rest-backend because it violates the REST scheme (`organization` is part of the identifier, one shouldn't change the identifier). But it could be done in the frontend by creating a new entry and deleting the old one.

**Comment by markus2330** [comment]
superseded by #3396
