### ISSUE TITLE
gpg test cases fail

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1230]
https://build.libelektra.org/job/elektra-gcc-configure-debian/lastFailedBuild/consoleFull

on debian-unstable-mm ( @manuelm any relevant changes there?)

```
 54/158 Test  #54: testmod_crypto_openssl .............***Failed    0.62 sec
CYPTO        TESTS
==================

/home/jenkins/workspace/workspace/elektra-gcc-configure-debian/src/plugins/crypto/test_internals.h:263: error in test_gpg: failed to install the GPG test key

crypto_openssl RESULTS: 66 test(s) done. 1 error(s).

        Start  55: testmod_crypto_gcrypt
 55/158 Test  #55: testmod_crypto_gcrypt ..............***Failed    0.39 sec
CYPTO        TESTS
==================

/home/jenkins/workspace/workspace/elektra-gcc-configure-debian/src/plugins/crypto/test_internals.h:263: error in test_gpg: failed to install the GPG test key

crypto_gcrypt RESULTS: 66 test(s) done. 1 error(s).

        Start  56: testmod_crypto_botan
 56/158 Test  #56: testmod_crypto_botan ...............***Failed    1.13 sec
CYPTO        TESTS
==================

/home/jenkins/workspace/workspace/elektra-gcc-configure-debian/src/plugins/crypto/test_internals.h:263: error in test_gpg: failed to install the GPG test key

crypto_botan RESULTS: 66 test(s) done. 1 error(s).

        Start  57: testmod_csvstorage
 57/158 Test  #57: testmod_csvstorage .................   Passed    0.01 sec
        Start  58: testmod_curlget
 58/158 Test  #58: testmod_curlget ....................   Passed    0.02 sec
        Start  59: testmod_dbus
 59/158 Test  #59: testmod_dbus .......................   Passed    0.00 sec
        Start  60: testmod_dpkg
 60/158 Test  #60: testmod_dpkg .......................   Passed    0.00 sec
        Start  61: testmod_dump
 61/158 Test  #61: testmod_dump .......................   Passed    0.00 sec
        Start  62: testmod_enum
 62/158 Test  #62: testmod_enum .......................   Passed    0.00 sec
        Start  63: testmod_fcrypt
 63/158 Test  #63: testmod_fcrypt .....................***Failed    0.04 sec
FCRYPT       TESTS
==================

/home/jenkins/workspace/workspace/elektra-gcc-configure-debian/src/plugins/fcrypt/testmod_fcrypt.c:114: error in test_gpg: failed to install the GPG test key
/home/jenkins/workspace/workspace/elektra-gcc-configure-debian/src/plugins/fcrypt/testmod_fcrypt.c:146: error in test_file_operations: kdb get (pregetstorage) failed
/home/jenkins/workspace/workspace/elektra-gcc-configure-debian/src/plugins/fcrypt/testmod_fcrypt.c:147: error in test_file_operations: file content could not be restored during decryption

fcrypt RESULTS: 27 test(s) done. 3 error(s).

        Start  64: testmod_filecheck
 64/158 Test  #64: testmod_filecheck ..................   Passed    0.00 sec


...



The following tests FAILED:
	 54 - testmod_crypto_openssl (Failed)
	 55 - testmod_crypto_gcrypt (Failed)
	 56 - testmod_crypto_botan (Failed)
	 63 - testmod_fcrypt (Failed)
Errors while running CTest
```

It would be great if the plugin/unit tests did more self-checks on run-time environments (gpg), maybe it is something simple (gpg2 not installed, wrong version or similar).

**Comment by manuelm** [comment]
On December 24, 2016 8:12:08 AM GMT+01:00, markus2330 <notifications@github.com> wrote:
>on debian-unstable-mm ( @manuelm any relevant changes there?)

Nope. No changes. Not even regular updates. In fact I haven't logged in in a while.

**Comment by petermax2** [comment]
The output of gpg is:

    GPG error: GPG failed with return value 512. gpg: directory '/tmp/elektra-test.Bx2Xil/.gnupg' created
    gpg: can't open '/usr/share/gnupg/dirmngr-conf.skel': No such file or directory
    gpg: new configuration file '/tmp/elektra-test.Bx2Xil/.gnupg/gpg.conf' created
    gpg: keybox '/tmp/elektra-test.Bx2Xil/.gnupg/pubring.kbx' created
    gpg: /tmp/elektra-test.Bx2Xil/.gnupg/trustdb.gpg: trustdb created
    gpg: key DAF635B17F230E8D: public key "Elektra Unit Tests (DO NOT USE IN PRODUCTION)  <unit-tests@libelektra.org>" imported
    gpg: WARNING: server 'gpg-agent' is older��@

@manuelm  or @markus2330  can you please kill the `gpg-agent` process.

**Comment by petermax2** [comment]
Maybe we need a cronjob that kills the gpg-agent daily/weekly? GPG seems to have a problem if the agent is running for too long.

**Comment by markus2330** [comment]
> new configuration file '/tmp/elektra-test.Bx2Xil/.gnupg/gpg.conf' created

It seems to me that we force gpg to create a new config file in some temporary directory? Is this as it should be?

> WARNING: server 'gpg-agent' is older��@

It seems like the string is concatenated incorrectly?

>  can you please kill the gpg-agent process.

There is one running only on debian-stretch-mr and debian-unstable-mm -- e.g. debian-stable-mm and debian-stretch-mr do not have them running.

I killed following processes on the two agents that had them running:
```
jenkins  14380  0.0  0.0 237396  1644 ?        Ss    2016  30:29 gpg-agent --homedir /tmp/elektra-test.FU8oQ3/.gnupg --use-standard-socket --daemon
jenkins  16824  0.0  0.0  89912    40 ?        SNs   2016   0:00 gpg-agent --homedir /tmp/elektra-test.hf9MT3/.gnupg --use-standard-socket --daemon
```

> Maybe we need a cronjob that kills the gpg-agent daily/weekly?

We can kill it at the beginning of the build jobs, but why did this problem not occur earlier? And I somehow doubt that gpg has issues with running some month.

Maybe it is the resource leak issue we had with the homepage, too? (It could be an issue introduced with an jenkins upgrade). "Process leaked file descriptors. See http://wiki.jenkins-ci.org/display/JENKINS/Spawning+processes+from+build for more information" see discussion in #1181
