### ISSUE TITLE
upload/review snippets

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1232]
This ticket is to encourage more uploads and to give information which snippets were reviewed.

- [x] review https://www.libelektra.org/entries/details/mozilla~2Ffirefox~2Fv45~2Fprivacy

**Comment by markus2330** [comment]
@reox ping

**Comment by reox** [comment]
what exactly should be reviewed? the content of the snippet?

**Comment by markus2330** [comment]
Yes, maybe you have some further suggestions.

You are also very welcome to upload further snippets!

**Comment by reox** [comment]
So i looked at the preferences, and I do not think there is something else to mention.
I think all other stuff, like disable weak ciphers, use https all the time, ... need an addon installed.
