### ISSUE TITLE
global plugins: invalid read

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#1241]
@markus2330 you mentioned a memleak in #874.

Did you mean this: https://build.libelektra.org/job/elektra-mergerequests-stable/811/artifact/build/Testing/20161227-2311/DynamicAnalysis.xml/*view*/

**Comment by markus2330** [comment]
There are plenty of issues with the current implementation. Let us fix the memleaks in your reimplementation (if necessary), but do not waste time with the current implementation.

**Comment by mpranj** [comment]
I won't waste time with the old implementation. The log above is very current (cachefilter branch rebased from master yesterday).
I thought maybe you had seen a concrete memleak.

**Comment by markus2330** [comment]
Ahh, ok, from the DynamicAnalysis.xml file alone it is not clear which branch was build and github did not inform me about your update/rebase on #874.

The memleak I saw was something obvious, so you will definitely find it during testing.

**Comment by mpranj** [comment]
Ok, thanks very much!

**Comment by mpranj** [comment]
The memleaks above are "fixed" with 8d9927a30491c1398b76f98042b221192f4b4990, and only memleaks from cachefilter itself remain.

It seems that the problem is that the strings returned from `keyBaseName` are not null-terminated. Any ideas why?

**Comment by markus2330** [comment]
`keyBaseName` only returns a pointer to `key->key` and it would be an serious issue if `key->key` is not null-terminated. Can you reduce the issue to a test case?

**Comment by mpranj** [comment]
In general I don't think we can write a test case that checks whether a string is not null-terminated (except if we knew some kind of a maximum size, in which case null-termination wouldn't be required anyway).

I would just solve the initial problem. It seems that the "spec as default" global-hook configuration triggers the memproblems. I have fixed some mistakes in the config but I haven't been able to fix the problem just yet.

**Comment by markus2330** [comment]
> In general I don't think we can write a test case that checks whether a string is not null-terminated

I mean to write a test case where valgrind reports some out-of-bounds access because something was not properly null-terminated.

> I would just solve the initial problem. It seems that the "spec as default" global-hook configuration triggers the memproblems. I have fixed some mistakes in the config but I haven't been able to fix the problem just yet.

Yes, but would be great to have a very reduced test case. It will also help to triage the problem.
