### ISSUE TITLE
Curlget Plugin: OpenSSL Check Does Not Work Properly on macOS

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1242]
# Steps to Reproduce

1. Clone the repository
2. Configure the build system:

    ```sh
    mkdir -p build &&						\
    cd build &&							\
    cmake ..							\
          -GNinja							\
          -DENABLE_TESTING=ON					\
          -DENABLE_DEBUG=ON						\
          -DENABLE_LOGGER=OFF					\
          -DBUILD_PDF=ON						\
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON			\
          -DPDFLATEX_COMPILER=`which latexmk`			\
          -DPDFLATEX_COMPILER_OPTIONS='-pdf;-f;-quiet'		\
          -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5			\
          -DTOOLS=ALL						\
          -DBINDINGS="ALL;-swig_python;-swig_python2;-swig_ruby"	\
          -DPLUGINS="ALL;-fcrypt"					\
    ```

3. Build Elektra

    ```sh
    ninja -C build
    ```

# Expected Result

The build finishes without problems using one of these two options:
  - CMake includes the Curlget plugin, or
  - CMake excludes the Curlget plugin, since it only found an incompatible version of OpenSSL or did nor find OpenSSL at all.

# Describe what actually happened

CMake includes the Curlget plugin:

```
-- Found CURL: /usr/lib/libcurl.dylib (found version "7.51.0")
-- Found OpenSSL: /usr/lib/libssl.dylib;/usr/lib/libcrypto.dylib (found version "0.9.8zh")
-- Include Plugin curlget
```

, but `ninja` is not able to build Elektra:

```
[8/742] Building C object src/plugins/curlget/CMakeFiles/elektra-curlget-objects.dir/curlget.c.o
FAILED: src/plugins/curlget/CMakeFiles/elektra-curlget-objects.dir/curlget.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -DELEKTRA_STATIC -DHAVE_KDBCONFIG_H -DPLUGIN_SHORT_NAME=curlget -DREADME=readme_curlget.c -Isrc/include -I../src/include -I../src/plugins/base64 -Isrc/plugins/curlget -std=gnu99  -Wno-deprecated-declarations  -Wno-long-long -pedantic -Wno-variadic-macros -Wall -Wextra -Wno-overlength-strings -Wsign-compare -Wfloat-equal -Wformat-security -Wshadow -Wcomments -Wtrigraphs -Wundef -Wuninitialized -Winit-self -Wsign-compare -Wfloat-equal -Wformat-security -O2 -g -DNDEBUG   -fPIC -MD -MT src/plugins/curlget/CMakeFiles/elektra-curlget-objects.dir/curlget.c.o -MF src/plugins/curlget/CMakeFiles/elektra-curlget-objects.dir/curlget.c.o.d -o src/plugins/curlget/CMakeFiles/elektra-curlget-objects.dir/curlget.c.o   -c "Elektra/src/plugins/curlget/curlget.c"
Elektra/src/plugins/curlget/curlget.c:18:10: fatal error: 'openssl/md5.h' file not found
#include <openssl/md5.h>
         ^
1 error generated.
```

. As far as I can tell the Crypto plugin [handles this situation](https://github.com/ElektraInitiative/libelektra/blob/master/src/plugins/crypto/CMakeLists.txt) correctly.  

# System Information

- Elektra Version: master

## Other Relevant Software

I also installed OpenSSL via Homebrew. The text below shows the output of `brew info openssl` on my machine.

```
openssl: stable 1.0.2j (bottled) [keg-only]
SSL/TLS cryptography library
https://openssl.org/
/usr/local/Cellar/openssl/1.0.2j (1,695 files, 12M)
  Poured from bottle on 2016-09-27 at 09:14:34
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/openssl.rb
==> Dependencies
Build: makedepend ✔
==> Options
--universal
	Build a universal binary
--without-test
	Skip build-time tests (not recommended)
==> Caveats
A CA file has been bootstrapped using certificates from the SystemRoots
keychain. To add additional certificates (e.g. the certificates added in
the System keychain), place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include
    PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig
```

**Comment by markus2330** [comment]
Thanks for the detailed description!

Does the issue occur in ninja only? We really should set up a ninja build agent (I increased the priority in #160)

Maybe #1235 is related. (for non-ninja)

> I also installed OpenSSL via Homebrew.

Does it only happen with OpenSSL, only without, or in both situations?

**Comment by sanssecours** [comment]
> Does the issue occur in ninja only?

Nope, `make` reports the same error:

```
Scanning dependencies of target elektra-curlget
[ 18%] Building C object src/plugins/curlget/CMakeFiles/elektra-curlget.dir/curlget.c.o
Elektra/src/plugins/curlget/curlget.c:18:10: fatal error: 'openssl/md5.h' file not found
#include <openssl/md5.h>
         ^
1 error generated.
make[2]: *** [src/plugins/curlget/CMakeFiles/elektra-curlget.dir/curlget.c.o] Error 1
make[1]: *** [src/plugins/curlget/CMakeFiles/elektra-curlget.dir/all] Error 2
make: *** [all] Error 2
```

.

> Maybe #1235 is related.

I guess not, since creating the build system with `cmake -DPLUGINS=ALL ..` in a clean build directory works on my machine:

```
…
-- Checking for one of the modules 'openssl'
-- Exclude Plugin crypto_openssl because OpenSSL compilation test failed
-- Found libgcrypt: -L/usr/local/opt/libgcrypt/lib -lgcrypt -L/usr/local/opt/libgpg-error/lib -lgpg-error
-- Checking for one of the modules 'botan-1.10;botan-1.9;botan-1.8;botan'
-- Exclude Plugin crypto_botan because botan development files not found
-- Include Plugin crypto_gcrypt
-- Include Plugin csvstorage
-- Found CURL: /usr/lib/libcurl.dylib (found version "7.51.0")
-- Found OpenSSL: /usr/lib/libssl.dylib;/usr/lib/libcrypto.dylib (found version "0.9.8zh")
-- Include Plugin curlget
-- Found D-Bus: /usr/local/lib/libdbus-1.dylib
-- Include Plugin dbus
-- Include Plugin desktop
-- Include Plugin doc
-- Include Plugin dpkg
-- Include Plugin dump
-- Include Plugin enum
-- Include Plugin error
-- Include Plugin fcrypt
…
```

 . After that building fails, because of the bug described in this issue and some issues with the `fcrypt` plugin:

```
Scanning dependencies of target elektra-fcrypt
[ 21%] Building C object src/plugins/fcrypt/CMakeFiles/elektra-fcrypt.dir/__/crypto/gpg.c.o
[ 21%] Building C object src/plugins/fcrypt/CMakeFiles/elektra-fcrypt.dir/fcrypt.c.o
Elektra/src/plugins/fcrypt/fcrypt.c:174:20: error: use of undeclared identifier 'UTIME_OMIT'
        times[0].tv_sec = UTIME_OMIT;
                          ^
Elektra/src/plugins/fcrypt/fcrypt.c:175:21: error: use of undeclared identifier 'UTIME_OMIT'
        times[0].tv_nsec = UTIME_OMIT;
                           ^
Elektra/src/plugins/fcrypt/fcrypt.c:183:6: warning: implicit declaration of function 'utimensat' is invalid in C99
      [-Wimplicit-function-declaration]
        if (utimensat (AT_FDCWD, keyString (parentKey), times, 0))
            ^
1 warning and 2 errors generated.
make[2]: *** [src/plugins/fcrypt/CMakeFiles/elektra-fcrypt.dir/fcrypt.c.o] Error 1
make[1]: *** [src/plugins/fcrypt/CMakeFiles/elektra-fcrypt.dir/all] Error 2
make: *** [all] Error 2
```
.

>> I also installed OpenSSL via Homebrew.

> Does it only happen with OpenSSL, only without, or in both situations?

The detected version of OpenSSL seems to be the one provided by Apple. Uninstalling the Homebrew version of OpenSSL with

```sh
brew uninstall --ignore-dependencies openssl
``` 

does not change the output of CMake or Ninja, at least as far as I can tell.

**Comment by markus2330** [comment]
Can you post the relevant parts of the compile log with `VERBOSE=1`. In particular I am interested if the include paths of openssl are added in crypto, fcrypt, and curlget in the same way.

**Comment by petermax2** [comment]
I had the same problem with my crypto plugin. In curlget's `CMakeLists.txt` you only use

    find_package(OpenSSL)

which is not sufficient on Mac OS. Please refer to `src/plugins/crypto/CMakeLists.txt` for a somewhat working OpenSSL detection.

**Comment by markus2330** [comment]
Thanks for your tip! Can you move your OpenSSL detection to some shared CMake file? Then we could reuse it in curlget and other places.

There are two implementation techniques, either as module (see `cmake/Modules/Find*`) or like `find_swig` in `cmake/Modules/LibAddMacros.cmake`.

**Comment by petermax2** [comment]
I think I might have done that already.

**Comment by petermax2** [comment]
Nope it's not a module. Just using `pkg-config`. This method requires that pkg-config is installed on the system. It is available via Homebrew on Mac OS.

**Comment by markus2330** [comment]
Can you put the code above in a macro/module and call it from `crypto` and `curlget`? Then we could also avoid repeated `try_compile`/OpenSSL detection if we put a guard within the macro.

Btw. we also have a workaround to have `pkg_get_variable` for older cmakes in cmake/Modules/LibFindMacros.cmake. You simply need to make sure that `LibFindMacros` is included before using `pkg_get_variable`.

**Comment by markus2330** [comment]
Does this issue still occur?

**Comment by sanssecours** [comment]
> Does this issue still occur?

Yes.

**Comment by petermax2** [comment]
Sorry I forgot about the issue. I'll try to provide a CMake file for OpenSSL detection by the weekend. Working full-time consumes pretty much all of the day.
