### ISSUE TITLE
Installing Elektra on macOS via brew after manual installation

### ISSUE THREAD

**Issue by e1528532** [ElektraInitiative/libelektra#1243]
# Describe what you wanted to do
I wanted to install elektra via homebrew following the instructions on the homepage.

# Describe what you expected
I expected that everything will work out of the box.

# Describe what actually happened
It failed the brew link step due to insufficient access rights (see attached log for details), apparently there are still some leftovers from a previous elektra installation which i compiled and installed manually (and also removed via sudo make uninstall).

Since you install it manually by using sudo make install, it creates elektra-api/html/ folder with root as the owner. Therefore, brew cannot write in that folder now.

The solution is simply to correct the access rights, and i guess that in normal environments without a previous manual elektra installation it works.

# System Information

- Elektra Version: master
- Versions of other relevant software? (dont think the others are relevant)

# Further Log Files and Output
mbp-armin:elektra-api admin$ brew install elektra
==> Installing elektra from elektrainitiative/elektra
==> Downloading https://github.com/ElektraInitiative/homebrew-elektra/releases/d
Already downloaded: /Users/admin/Library/Caches/Homebrew/elektra-0.8.19.sierra.bottle.tar.gz
==> Pouring elektra-0.8.19.sierra.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink share/doc/elektra-api/html/FreeSans.ttf
/usr/local/share/doc/elektra-api/html is not writable.

You can try again using:
  brew link elektra
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/elektra/0.8.19: 2,600 files, 51.8M

**Comment by sanssecours** [comment]
Thank you for the bug report.

> I expected that everything will work out of the box.

Does installing Elektra work if you follow the instructions in the [“Troubleshooting”](https://github.com/ElektraInitiative/homebrew-elektra#troubleshooting) section of the ReadMe:

> - If you have any problems using this formula, then please run `brew doctor` and remove all fragments of previous Elektra versions that the command reports.

?

**Comment by e1528532** [comment]
just noticed that someone else also reported this in #531 already. 

Running brew doctor and removing the fragments manually (using sudo rm if necessary) does work though. But some additional folders are also required which are not listed by brew doctor, those it tells you while trying to link:
mbp-armin:build admin$ brew link elektra

Linking /usr/local/Cellar/elektra/0.8.19... 
Error: Could not symlink include/elektra/backend.hpp
/usr/local/include/elektra is not writable.

and the latter directory is not directly suggested by brew doctor, which only complains about some files inside of it:

Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/lib/elektra/libelektra-resolver.so
  /usr/local/lib/elektra/libelektra-storage.so
mbp-armin:build admin$ brew prune
Error: Permission denied - /usr/local/lib/elektra/libelektra-resolver.so

Calling brew prune with sudo is prevent by homebrew so i ended up manually removing the troubling paths then it works again.

I guess theres not much we can do about it from the homebrew perspective? I'd rather see the issue by calling sudo make uninstall not actually uninstalling everything.

**Comment by markus2330** [comment]
> I'd rather see the issue by calling sudo make uninstall not actually uninstalling everything.

Yes, that is definitely an issue, thanks for reporting. Please open new issues if you find new ones.

I opened #1244

**Comment by sanssecours** [comment]
> I guess theres not much we can do about it from the homebrew perspective?

Since we only provide the formula (and not the package system), I think you are right. I made the part about `brew doctor` more prominent in the latest version of the [ReadMe](https://github.com/ElektraInitiative/homebrew-elektra#preparation). Hopefully this will help other users to avoid this issue.

> I'd rather see the issue by calling sudo make uninstall not actually uninstalling everything.

Looks like Markus thinks so [too](https://github.com/ElektraInitiative/libelektra/issues/1244) 😀.

**Comment by markus2330** [comment]
Thus we have #1244 we can close this issue.
