### ISSUE TITLE
PDF Manual: Incorrect Entries in Table of Contents

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1245]
# Steps to Reproduce

1. Clone the repository

    ```sh
    git clone https://github.com/ElektraInitiative/libelektra.git
    ```

2. Build Elektra and the PDF manual

    ```sh
    	mkdir -p build &&						\
    	cd build &&							\
    	cmake ..							\
    	      -GNinja							\
    	      -DENABLE_TESTING=ON					\
    	      -DENABLE_DEBUG=ON						\
    	      -DENABLE_LOGGER=OFF					\
    	      -DBUILD_PDF=ON						\
    	      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON			\
    	      -DPDFLATEX_COMPILER=`which latexmk`			\
    	      -DPDFLATEX_COMPILER_OPTIONS='-pdf;-f;-quiet'		\
    	      -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5			\
    	      -DTOOLS=ALL						\
    	      -DBINDINGS="ALL;-swig_python;-swig_python2;-swig_ruby"	\
    	      -DPLUGINS="ALL;-fcrypt;-curlget"				\
    ```

3. Open the PDF manual

    ```sh
    open build/doc/latex/refman.pdf
    ```

# Expected Result

The entries in the table of contents show the title of the included (Markdown) documents.

# Actual Result

The entry for `elektra-sync-flag.md` displays the filename instead of the title “elektra-sync-flag(7) – detection for writing”. 

![Original](https://cloud.githubusercontent.com/assets/691989/21577306/93c9031e-cf56-11e6-9575-89c1d9c1afac.png)

I tried changing the title of the document, but the entry stays the same. If I change the filename, then the TOC entry uses the new name of the file.

![Changed](https://cloud.githubusercontent.com/assets/691989/21577307/99c49a94-cf56-11e6-9ea9-63456de122ea.png)

Seems like the same issue happens when Doxygen includes `elektra-granularity.md`.

# System Information

- Elektra Version: master

**Comment by markus2330** [comment]
Thank you for reporting! Can you elaborate on the expected result a bit more? Is “elektra-sync-flag(7) – detection for writing” really what we want as title?

**Comment by sanssecours** [comment]
>  Is “elektra-sync-flag(7) – detection for writing” really what we want as title?

I would say that depends, on someone’s preference. I would prefer something like “Detection for Writing”, but do not care that much, as long as the naming scheme is consistent.
