### ISSUE TITLE
Website: Loading shows wrong text

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1251]
# Describe what you wanted to do

Search for all snippets.

# Describe what you expected

That it first loads, and then show all snippets.

# Describe what actually happened

It immediately showed "No snippets found matching the given search criteria." while loading. Loading took quite long (might be a connection issue).

# System Information

- Elektra Version: master
- Website last update: 1.1.2017, 12:11:11 (+1h UTC)

**Comment by markus2330** [comment]
It seems like a quite straight-forward job to fix this. Maybe it is a good starting point for @e1528532?

**Comment by Namoshek** [comment]
Yeah it's pretty simple, an `isLoaded` flag to determine the text should be enough.
