### ISSUE TITLE
Markdown Shell Recorder — Problems

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1253]
# Description

The text below mentions some of the problems I found while trying the Markdown Shell Recorder (MSR). While Markus already opened an [issue](https://github.com/ElektraInitiative/libelektra/issues/944) mentioning problems with the more general Shell Recorder, I think describing problems with MSR separately makes sense.   

# Overview

- [x] MSR fails silently if a system uses the BSD version of `grep`
- [x] MSR does not execute tests
- [x] MSR fails because of substring expression error
- [x] MSR syntax should support leading whitespace

# System Information

- Elektra Version: `master`
- OS: `macOS 10.12.2`

# MSR Fails Silently (BSD grep)

## Steps to Reproduce

1. Build Elektra in the directory `build`
2. Change into the directory `build`
3. Run one of the Markdown Shell Recorder Test (e.g. `testshell_conditionals`):

    ```sh
    ctest -VV -R testshell_conditionals
    ```

## Expected Result

Markdown Shell Recorder executes the tests specified in the ReadMe of  the conditionals plugin and succeeds.

## Actual Result

MSR calls `grep` and fails, because BSD’s grep does not support certain flags, such as `-P`, used in `markdown_shell_recorder.sh`.

The text below shows the output of  `testshell_conditionals`:

```
UpdateCTestConfiguration  from :Elektra/build/DartConfiguration.tcl
Parse Config file:Elektra/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :Elektra/build/DartConfiguration.tcl
Parse Config file:Elektra/build/DartConfiguration.tcl
Test project Elektra/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 102
    Start 102: testshell_conditionals

102: Test command: Elektra/tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh "Elektra/src/plugins/conditionals/README.md"
102: Test timeout computed to be: 1500
102: usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
102: 	[-e pattern] [-f file] [--binary-files=value] [--color=when]
102: 	[--context[=num]] [--directories=action] [--label] [--line-buffered]
102: 	[--null] [pattern] [file ...]
102: usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
102: 	[-e pattern] [-f file] [--binary-files=value] [--color=when]
102: 	[--context[=num]] [--directories=action] [--label] [--line-buffered]
102: 	[--null] [pattern] [file ...]
102: protocol file: /var/folders/hx/flbncdhj4fs87095gzxvnj3h0000gn/T/elektraenv.XXXXXXXXX.5Aj46mjn
102: shell_recorder /var/folders/hx/flbncdhj4fs87095gzxvnj3h0000gn/T/tmp.mYbAeCdZ RESULTS: 0 test(s) done
102:  0 error(s).
1/1 Test #102: testshell_conditionals ...........   Passed    0.10 sec

The following tests passed:
	testshell_conditionals

100% tests passed, 0 tests failed out of 1

Label Time Summary:
kdbtests    =   0.10 sec (1 test)
memleak     =   0.10 sec (1 test)

Total Test time (real) =   0.11 sec
```

# MSR Does Not Execute Tests

For this test I installed the GNU version of `grep` via `brew install grep --with-default-names`.

## Steps to Reproduce

1. Build Elektra in the directory `build`
2. Change into the directory `build`
3. Run one of the Markdown Shell Recorder Test (e.g. `testshell_mathcheck`):

    ```sh
    ctest -VV -R testshell_mathcheck
    ```

## Expected Result

Markdown Shell Recorder executes the tests specified in the ReadMe of  the mathcheck plugin and succeeds.

## Actual Result

It looks like MSR does not execute any tests:

```
…
105: Test command: Elektra/tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh "Elektra/src/plugins/mathcheck/README.md"
105: Test timeout computed to be: 1500
105: protocol file: /var/folders/hx/flbncdhj4fs87095gzxvnj3h0000gn/T/elektraenv.XXXXXXXXX.uUWFG4tC
105: shell_recorder /var/folders/hx/flbncdhj4fs87095gzxvnj3h0000gn/T/tmp.OBVilzoK RESULTS: 0 test(s) done
105:  0 error(s).
2/2 Test #105: testshell_mathcheck ..............   Passed    1.86 sec

The following tests passed:
	testshell_mathcheck
	testshell_mathcheck

100% tests passed, 0 tests failed out of 2

Label Time Summary:
kdbtests    =   3.24 sec (3 tests)
memleak     =   3.24 sec (3 tests)

Total Test time (real) =   2.57 sec
```

. At least the protocol is empty.  The Shell Recorder file seems to be correct. If I change the output in `src/plugins/mathcheck/README.md` from 

```sh
# should fail
kdb set /examples/mathcheck/k 7.7
# RET:5
```

to 

```sh
# should fail
kdb set /examples/mathcheck/k 7.7
# RET:1337
```

, then the test still does not fail.

# MSR Fails Because of Substring Expression Error

For this test I installed the GNU version of `grep` via `brew install grep --with-default-names`.

## Steps to Reproduce

1. Build Elektra in the directory `build`
2. Change into the directory `build`
3. Run one of the Markdown Shell Recorder Test (e.g. `testshell_blockresolver`):

    ```sh
    ctest -VV -R testshell_blockresolver
    ```

## Expected Result

Markdown Shell Recorder executes the tests specified in the ReadMe of the blockresolver plugin and succeeds.

## Actual Result

Markdown Shell Recorder fails, because of a substring expression error:

```
    Start 101: testshell_blockresolver

101: Test command: Elektra/tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh "Elektra/src/plugins/blockresolver/README.md"
101: Test timeout computed to be: 1500
101: Elektra/tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh: line 168: -1: substring expression < 0
1/1 Test #101: testshell_blockresolver ..........***Failed    0.63 sec

0% tests passed, 1 tests failed out of 1

Label Time Summary:
kdbtests    =   0.63 sec (1 test)
memleak     =   0.63 sec (1 test)

Total Test time (real) =   0.65 sec

The following tests FAILED:
	101 - testshell_blockresolver (Failed)
Errors while running CTest
```

.

# MSR Syntax Should Support Leading Whitespace

This is a feature request. Could we please 🙏  ignore leading whitespace in the values that Markdown Shell Recorder checks? That would be really awesome 😘.

I would rather write something like this:

```sh
kdb set /overrides/test "hello user"
# STDOUT: Using name user/overrides/test⏎
#         Create a new key user/overrides/test with string hello user
kdb get /sw/tutorial/cascading/#0/current/test
# STDOUT: hello user
```

instead of this:

```sh
kdb set /overrides/test "hello user"
# STDOUT:Using name user/overrides/test⏎
# Create a new key user/overrides/test with string hello user
kdb get /sw/tutorial/cascading/#0/current/test
# STDOUT:hello user
```

. Especially since the second version does not play nicely with the integrated spell checker (of macOS):

<img width="444" alt="msr - example" src="https://cloud.githubusercontent.com/assets/691989/21641126/232989cc-d27a-11e6-9a72-b1c3461bc8e5.png">

.

**Update:** Looks like I totally missed the part

> * Checks
> 
>   * `#> STRING`
>
>     `STRING` is matched 1:1 against the command output. multiple `#> ` will be concatenated automatically using `⏎`

in the [ReadMe](https://github.com/ElektraInitiative/libelektra/blob/master/tests/shell/shell_recorder/tutorial_wrapper/README.md) of the Markdown Shell Recorder 😳. I would still like to see support for leading whitespace for all the other checks, though.

**Comment by markus2330** [comment]
Thanks for your detailed analysis of the issues! I hope it helps @tom-wa to progress more quickly.

Btw. if you know solutions to (some) of this problems, do not hesitate to fix them. Especially Mac OS X specific issues: It would be difficult for @tom-wa to debug them.

**Comment by tom-wa** [comment]
@sanssecours can you test if #1301 fixes the first 3 issues ?

**Comment by sanssecours** [comment]
> @sanssecours can you test if #1301 fixes the first 3 issues?

Since MSR does not fail silently anymore, I would say #1301 addresses the first issue. However, now `testshell_conditionals` fails because of the substring expression error described in the third issue:

```
UpdateCTestConfiguration  from :build/DartConfiguration.tcl
Parse Config file:build/DartConfiguration.tcl
UpdateCTestConfiguration  from :build/DartConfiguration.tcl
Parse Config file:build/DartConfiguration.tcl
Test project build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 102
    Start 102: testshell_conditionals

102: Test command: tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh "src/plugins/conditionals/README.md"
102: Test timeout computed to be: 1500
102: tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh: line 168: -1: substring expression < 0
1/1 Test #102: testshell_conditionals ...........***Failed    1.12 sec

0% tests passed, 1 tests failed out of 1

Label Time Summary:
kdbtests    =   1.12 sec (1 test)
memleak     =   1.12 sec (1 test)

Total Test time (real) =   1.13 sec

The following tests FAILED:
	102 - testshell_conditionals (Failed)
Errors while running CTest
```

. Travis also reports [the same error](https://travis-ci.org/ElektraInitiative/libelektra/jobs/196490553#L2458).

The second issue not fixed as far as I can tell. The tests `testshell_mathcheck` still does not fail if I change the reference output in `src/plugins/mathcheck/README.md`.

The third issue seems to be still there too. The test `testshell_blockresolver` still fails because of a substring expression error.

**Comment by tom-wa** [comment]
thanks for checking!
seems like the bash version on os x doesn't support string manipulation

**Comment by sanssecours** [comment]
> seems like the bash version on os x doesn't support string manipulation

I tried some string manipulation examples on this [web page](http://tldp.org/LDP/abs/html/string-manipulation.html). All of them worked as far as I can tell. Since the version of Bash in macOS is ancient:

```
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.
```

, I would expect that some of the newer features of Bash do not work at all. The problematic command seems to be

```sh
COMMAND="${COMMAND::-1}"
```

. If I enter the following commands:

```sh
COMMAND=test
echo "${COMMAND::-1}"
```

, then `bash` prints the following error message:

```
bash: -1: substring expression < 0
```

.

**Comment by tom-wa** [comment]
ok, thanks. negative indices wer added in 4.2, but it seems like `%?` did the trick. at least the travis buildjob works fine now.

oh, and i'll add leading whitespace support for the 0.8.20
