### ISSUE TITLE
Documentation link (doc.libelektra.org) weird behaviour

### ISSUE THREAD

**Issue by KurtMi** [ElektraInitiative/libelektra#1268]
> curl http://doc.libelektra.org
> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>301 Moved Permanently</title>
> </head><body>
> <h1>Moved Permanently</h1>
> <p>The document has moved <a href="https://github.com/ElektraInitiative/libelektra/blob/master/">here</a>.</p>
> <hr>
> <address>Apache/2.4.10 (Debian) Server at doc.libelektra.org Port 80</address>
> </body></html>

Does not work

> curl https://doc.libelektra.org
> <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
> <html>
> <head>
 > <title>Index of /</title>
> </head>
> <body>
> <h1>Index of /</h1>
>...

It works

Another suggestion: the link should go directly to the latest doxygen

**Comment by markus2330** [comment]
Thanks for reporting!

The apache site for http://doc.libelektra.org was not enabled, should be fixed now.
