### ISSUE TITLE
Introduce symbol versioning

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1271]
API breaks are much less painful if old software continues to work (ABI stays compatible). Symbol versioning provides that. See `doc/todo/FUTURE` for planned changes that require introduction of symbol versioning.

It would be better to also always stay API compatible, but the proposal #600 was rejected as being too ambitious.

**Comment by kodebach** [comment]
If anybody wants to tackle this, the solution that FreeBSD uses is quite neat. It is described [here](https://people.freebsd.org/~deischen/symver/library_versioning.txt). The "magical awk script" that is mentioned is [this one](https://github.com/freebsd/freebsd/blob/1d6e4247415d264485ee94b59fdbc12e0c566fd0/share/mk/version_gen.awk), as far as I can tell. The script is invoked [here](https://github.com/freebsd/freebsd/blob/1d6e4247415d264485ee94b59fdbc12e0c566fd0/share/mk/bsd.symver.mk). The master version script would be `libelektra-symbols.map` in our case.

The biggest hurdle for this issue IMO is testing. We would need separate tests for each of the symbol versions to make sure we don't accidentally break something.

**Comment by markus2330** [comment]
Thank you so much for your input here!

> The biggest hurdle for this issue IMO is testing. We would need separate tests for each of the symbol versions to make sure we don't accidentally break something.

This is already done by me manually. I run the latest elektra libraries against the unit tests of the previous release (which were compiled with Elektra of the previous version).

To automate this would of course be very nice, then we would be very near to continuous releases (releasing a new version of Elektra by pressing a button) because the ABI tests are currently the point which eat up the most time during releases.

**Comment by markus2330** [comment]
Finished thanks to @kodebach
