### ISSUE TITLE
Document specification language

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1273]
@Piankero and @kodebach will improve the specification language which allows global validation and calculation of default values.

E.g. if you are not behind a firewall (and the firewall settings are known to Elektra), a daemon can be bound to `127.0.0.1` for security reasons.

First demonstrations for these features will be for:

- lcdproc #1266
- machinekit #388
- openicc #1137

**Comment by markus2330** [comment]
@tom-wa just found an example of default value calculation:
The default speed of CFontzPacket depends on the Model.

**Comment by kodebach** [comment]
possible duplicate of #2231

**Comment by markus2330** [comment]
Yes, this is basically only a 1.0 milestone. I updated the names who is working on it.

**Comment by markus2330** [comment]
@Piankero we need a good tutorial of how the specification language works.

**Comment by Piankero** [comment]
I started a tutorial in https://github.com/ElektraInitiative/libelektra/tree/specification-language-tutorial and will make a PR in the next days

**Comment by markus2330** [comment]
Thank you, but please prefer to use branches in your own repo.

**Comment by Piankero** [comment]
That was accidental, I moved it to my repo
