### ISSUE TITLE
Improve Plugin Framework

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1274]
- Global Plugins #1103
- backend = plugin (make plugins lazy + get rid of limitations of number of plugins, i.e., have internal list implementation)
- get rid of state in kdbSet (have function kdbCommit)
- get rid of limitations in the number of plugins  #2133

Proposals:
- #1249

**Comment by mpranj** [comment]
Parts of this are still WIP.

**Comment by kodebach** [comment]
Should #3693 also move from the generic global plugin mechanism to specialised "hooks" for each of the currently existing global plugins? I think would make the implementation easier. For users it would also be better to do it in one go, since that means only one migration.

**Comment by markus2330** [comment]
#3693 should be as small as possible. Only if the hooks get broken in #3693 such things can be done, otherwise a separate PR is much more preferred.

> For users it would also be better to do it in one go, since that means only one migration.

As we clearly communicate that 0.9 is development for 1.0 the only relevant migration is 0.8 -> 1.0.

**Comment by kodebach** [comment]
Okay let me clarify that... Of course smaller PRs are better. The question was more, if the move to specialised hooks should be made ASAP as well (in a follow-up PR).

The current code in #3693 removes some of the existing global plugin positions already and only calls those that correspond to useful global plugins (`cache`, `spec`, `gopts`, notifications). My plan was to keep it this way and not add the other positions. In a future PR the whole global plugin positions and mounting system would be replace by a specialised system with new positions corresponding to the purpose of the plugin (`cache`, `spec`, `gopts`, `notifications`).


> the only relevant migration is 0.8 -> 1.0.

To clarify that as well: With "users" I also included people working on Elektra. But now that I think about it, there is probably (almost) no one who actually used a custom global plugins config, so there won't be much migration.

**Comment by markus2330** [comment]
@kodebach can we close this now? Or what is left over?

**Comment by kodebach** [comment]
The stuff that is mentioned here is done.
