### ISSUE TITLE
kdb-full fails on macOS

### ISSUE THREAD

**Issue by e1528532** [ElektraInitiative/libelektra#1276]
# Describe what you wanted to do

Execute kdb-full on macOS in order to test the JNI plugin.

# Describe what you expected

After fixing a java-related library bug, i expected kdb-full will work now.

# Describe what actually happened

It gave me the following error instead:
e251-086:build admin$ kdb-full 
dyld: Library not loaded: @rpath/libelektratools-full.2.dylib
  Referenced from: /usr/local/bin/kdb-full
  Reason: image not found
Abort trap: 6

Apparently, this library gets built successfully, as it is contained in <elektra_build_dir>/lib. But upon installation, it doesn't seem to work. I haven't located the dylib file on the system yet, its at least not in /usr/local/lib/elektra/.

As described here https://www.libelektra.org/docgettingstarted/compiling , i also tried setting the BUILD_SHARED flag to off, but this did not help.

After manually setting the dyld path to include the <elektra_build_dir>/lib directory via environment variable, it works successfully. However, this doesn't seem to be an option for production use. Anyway heres the command (already also includes the java paths for jni plugin):

export DYLD_FALLBACK_LIBRARY_PATH="/Users/admin/git/libelektra/build/lib/"

And i guess this could be related to #1233 and #1275 ?

# System Information

- Elektra Version: master
- macOS Sierra

**Comment by markus2330** [comment]
Thanks for reporting!

libelektratools should be installed in the same folder as libelektra (see `src/libs/tools/src/CMakeLists.txt`). Maybe the installed Elektra and the build directory are mixed up?

**Comment by markus2330** [comment]
This was most likely an installation problem. Please reopen if it appears again.
