### ISSUE TITLE
jni plugin fails on macOS

### ISSUE THREAD

**Issue by e1528532** [ElektraInitiative/libelektra#1277]
# Describe what you wanted to do

I wanted to install the jni plugin. I have opened a pull request regarding updated documentation about installing jni on macOS. Then i wanted to execute kdb-full as suggested in the jni README to see if it actually works.

# Describe what you expected

I expected that everything will work.

# Describe what actually happened

After having solved some dylib related issues, which you see in my pull request, when opening kdb-full as suggested in the jni readme to test it, it fails as it tells me to install the legacy java 6 from apple. Which is weird as i had quite some effort to get jni to use the java 8 headers.

I did a quick research and found this https://bugs.openjdk.java.net/browse/JDK-7131356 which indicates this might be related to a jdk bug? The fix seems to be targeted for the jdk9, which will be released in a few months. However i'm not sure if its really related to that bug, but i wonder if its worth spending more time trying to make it run or simply wait for jdk9 and hope it will fix the issue?

# System Information

- Elektra Version: master
- jdk 1.8.112

**Comment by markus2330** [comment]
Yes, sounds sensible to not use even more time for your java setup. Such an effort is unacceptable for potential users anyway.
