### ISSUE TITLE
kdb rm fails silently when key was not removed

### ISSUE THREAD

**Issue by krit0n** [ElektraInitiative/libelektra#1287]
I just noted, that `kdb rm` fails silently when failing to remove keys.

# Describe what you wanted to do
```sh
sudo kdb set system/a b
#> Create a new key system/a with string b
kdb get system/a
#> b

# can't remove key, because not superuser ...
kdb rm system/a
# ... but no error message

kdb get system/a
#> b
```

# Describe what you expected
I expected to be informed when a key is not removed, like `rm` does:
`rm: cannot remove 'x': Permission denied`
or like `kdb set` does.

# System Information

- Elektra Version: master

**Comment by markus2330** [comment]
Thank you for reporting! Very good catch! The issue seems to be related to the logic of removing configuration files, so it only failed silently when removing the last key. Should be fixed now, please reopen if you have issues.
