### ISSUE TITLE
global-mount / gmount help message issues

### ISSUE THREAD

**Issue by tom-wa** [ElektraInitiative/libelektra#1302]
```
 % kdb global-mount --help 
No manual entry for kdb-global-mount

 % kdb global-mount -h                                                                                                            [16]
kdb: invalid option -- 'h'
Invalid option given

Usage: kdb global-mount [mountpoint] [plugin [config] [..]]

Globally mount given plugins.

-H --help                Show the man page.
-p --profile <name>      Use a different profile for kdb configuration
-V --version             Print version info.
-W --with-recommends     Add recommended plugins.
-C --color[=WHEN]        Print never/auto(default)/always colored output.
```

`mountpoint` isn't a valid argument for `global-mount`
there should be a way to get the help message without specifying an invalid option

**Comment by markus2330** [comment]
Currently you need to install `ronn`, then you would get man pages when using `-H` and `--help`. But we want to improve here by already pre-compiling the man pages (see  #1211).

We are trying to remove the duplicated information (like `Globally mount given plugins.`)

**Comment by tom-wa** [comment]
i'd still say there needs to be a way to get a quick help too like the one when you enter a invalid argument. and i think that's what people would expect when running `kdb <command> --help` because most of the time that would enough when i just want to lookup the syntax or the name of a option. and something like `--full-help` or `--long-help` for the man page.

**Comment by markus2330** [comment]
The short help is basically exclusively for showing which options exist, so only showing it on wrong options makes sense. We now have the same behaviour as git, having slight differences (like short+long help) would confuse people.
