### ISSUE TITLE
make mount not fail if mp exists

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1306]
If someone tries to mount something that is mounted already, we should not fail. (If it would do exactly the same action)

Affected:

- [ ] `mount` (the script `elektra-mount` is basically already a workaround for it)
- [ ] `global-mount` see  #1301 src/plugins/conditionals/README.md 
- [ ] `elektra-mount`can be removed then

Unclear:

- [ ] do we need an option to disable this behavior?

**Comment by markus2330** [comment]
I have set the milestone to 0.8.21 because it should be part of LCDproc release.

We also need this feature for #1374 and #1663

**Comment by markus2330** [comment]
A simple way to implement that feature would be to have a `-f` option which cuts the mountpoint's config before doing the mount.

If this is not a good way, we should rather move this feature to 0.8.22.

**Comment by markus2330** [comment]
With `--strategy preserve` this works now for normal mounts.

**Comment by markus2330** [comment]
@Chemin1 It would be great to have a fully working preserve strategy, so that this finally correctly works for mount and global-mount.

**Comment by markus2330** [comment]
Sorry, actually we need "--strategy unchanged". And this should also be default for mounting.

The strategy is actually very simple: It only succeeds if ours, theirs and base is the same.

**Comment by Chemin1** [comment]
I'll have to take a closer look at how that works, as I did not even know that mounting has strategies until now.

Looking at `our`, `their` and `base`: Is this related to the install-config-file script that we talked about? I mount a file and get the `base` and `our` version. I mount the same file again (this is now `their`) with strategy unchanged and the mount succeeds?

**Comment by markus2330** [comment]
> I'll have to take a closer look at how that works, as I did not even know that mounting has strategies until now.

Basically every tool that writes more than a single key (in this case merging is trivial) different strategies are useful. So also `kdb shell` would profit from having 3-way merging integrated.

**Comment by markus2330** [comment]
Project would be together with #1322.
