### ISSUE TITLE
libelektra.org login not possible

### ISSUE THREAD

**Issue by BernhardDenner** [ElektraInitiative/libelektra#1307]
I've tried to login at https://www.libelektra.org/auth/login

but always get the following error message:

> Connection issues
> It seems as if the service is not reachable. This may be either due to a downtime of the service or because of your internet connection.

To be sure, my internet connection has no downtime ;)

**Comment by markus2330** [comment]
Thank you for reporting! It seems like the backend was down. I restarted it. In #1267 we are looking for a more robust solution, hopefully the new server will not contain this issue anymore.

Please reopen the issue if it is down again.
