### ISSUE TITLE
Better security for libelektra.org login error messages

### ISSUE THREAD

**Issue by BernhardDenner** [ElektraInitiative/libelektra#1309]
currently the authentication process at libelektra.org is issuing different error messages if user or password combinations do not match.

Messages such as "unknown username" or "wrong password for username" are considered to be a bad practice: see https://www.owasp.org/index.php/Authentication_Cheat_Sheet#Authentication_and_Error_Messages for details.

In both cases (invalid username or password) the SAME error message should be given "invalid username or password".

**Comment by markus2330** [comment]
Thank you for reporting!

I fully agree that it would be better from security point of view! Unfortunately it reduces the usability if someone actually mistypes the user (and thinks he/she mistyped the password). In the current state with nearly no snippets and/or users it might be not the best way to reduce usability?

I would suggest we postpone it until we support github logins, which would make standard sign in less important anyway.
