### ISSUE TITLE
date: test cases fail

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1313]
```
        Start  67: testmod_date
 67/169 Test  #67: testmod_date .......................***Failed    0.00 sec
DATE     TESTS
==================

src/plugins/date/testmod_date.c:26: error in testFmt: validation failed
src/plugins/date/testmod_date.c:55: error in testRfc2822: validation failed

testmod_date RESULTS: 72 test(s) done. 2 error(s).
```

**Comment by markus2330** [comment]
Please fix, it is very annoying if test cases fail, then we might overlook further regressions in PRs.

Also fails at Mac OS X:

```
 49/143 Test  #49: testmod_date .......................***Failed    0.03 sec

DATE     TESTS

==================

/Users/travis/build/ElektraInitiative/libelektra/src/plugins/date/testmod_date.c:26: error in testFmt: validation failed

/Users/travis/build/ElektraInitiative/libelektra/src/plugins/date/testmod_date.c:41: error in testIso: validation failed

/Users/travis/build/ElektraInitiative/libelektra/src/plugins/date/testmod_date.c:41: error in testIso: validation failed

/Users/travis/build/ElektraInitiative/libelektra/src/plugins/date/testmod_date.c:41: error in testIso: validation failed

/Users/travis/build/ElektraInitiative/libelektra/src/plugins/date/testmod_date.c:41: error in testIso: validation failed

/Users/travis/build/ElektraInitiative/libelektra/src/plugins/date/testmod_date.c:41: error in testIso: validation failed

/Users/travis/build/ElektraInitiative/libelektra/src/plugins/date/testmod_date.c:41: error in testIso: validation failed

testmod_date RESULTS: 72 test(s) done. 7 error(s).
```

**Comment by tom-wa** [comment]
```
       For reasons of symmetry, glibc tries to support for strptime() the same format characters as for strftime(3). 
```

i've used some of them for my implementation because they are the same format characters as used in ISO 8601, i'll try to find a workaround for them

**Comment by tom-wa** [comment]
Seems like the issues are related to the `%z` and `%Z` format character which validates the timezone designators

the seem to work fine on jessie and stretch, but not on wheezy and OS X. 

i'm not going to reimplement %z/%Z. would it be enough to drop unittests for tomezone designators and mention them as restriction in the README.md ?

**Comment by markus2330** [comment]
Yes, limitations are okay! Enough other standards are supported. Only please make sure that the default works everywhere.

Btw. the initially reported error also happens on jessie:
```
68: /home/markus/Projekte/Elektra/current/src/plugins/date/testmod_date.c:26: error in testFmt: validation failed
68: /home/markus/Projekte/Elektra/current/src/plugins/date/testmod_date.c:55: error in testRfc2822: validation failed
```

**Comment by tom-wa** [comment]
i'm not really sure what the actual limitations for %z/%Z are and i've got some mixed results testing it. i'll setup a clean jessie vm and do some additional testing, on stretch and sid it seems to work fine.

**Comment by markus2330** [comment]
> i'll setup a clean jessie vm

You can save yourself the effort. It is a locale problem. The unit test runs fine with `LC_ALL=C`.

So either we set `LC_ALL=C` for the unit tests (and add further limitations), or (preferred) we find a solution that the plugin has stable results.

**Comment by tom-wa** [comment]
i already had that suspicion , the gnu manpage is really lacking some informations.
i guess setting and resetting the locale in the unittest is the best solution.

**Comment by markus2330** [comment]
> i guess setting and resetting the locale in the unittest is the best solution.

Yes, likely so.

Its quite often impossible to use the APIs in a thread-safe and locale-independent way.
