### ISSUE TITLE
kdb complete: complete a completed key?

### ISSUE THREAD

**Issue by reox** [ElektraInitiative/libelektra#1329]
So i tried the new feature (very nice btw!) now and found this:

# Describe what you wanted to do
```
$ kdb set user/foo/bar/bla/foo xyz
$ kdb complete user/foo/bar/bla/foo
```

# Describe what you expected
I think this should output
```
user/foo/bar/bla/foo
```
like `kdb ls` does:
```
$ kdb ls user/foo/bar/bla/foo 
user/foo/bar/bla/foo
```

# Describe what actually happened
The output is empyt

# System Information
```
$ kdb --version
KDB_VERSION: 0.8.19
SO_VERSION: 4
```
using 0.8.19-1.5381

I think the behaviour of `ls` and `complete` should be similar, or was this build on purpose?
By the way: I think it should return the value with trailing `/` and without (like `ls` does).

**Comment by markus2330** [comment]
I assume this is not relevant anymore. Thank you for the question and the answer!
