### ISSUE TITLE
kdb complete: flag for hiding extra information

### ISSUE THREAD

**Issue by reox** [ElektraInitiative/libelektra#1330]
I noticed now, that i need for the completions the pure keys at some parts, so i use sed to remove the leaf and node number information.
Would it be possible to have a flag to hide them if needed?

**Comment by markus2330** [comment]
What exactly do you want to hide?

The node number information is now hidden anyway?

**Comment by reox** [comment]
Oh, i should install the latest snapshots then.

Hide the node/leaf output if wanted. Or is this also not shown anymore?

**Comment by markus2330** [comment]
Also not shown anymore, you really should get the latest version :smile:

**Comment by reox** [comment]
too lazy to build myself, I used the debian packages :D
