### ISSUE TITLE
Typed getters and setters in kdb.h?

### ISSUE THREAD

**Issue by domhof** [ElektraInitiative/libelektra#1333]
Here is a list of typed getters/setters we could add to kdb.h. What's your opinion about that? Do we want to support short/long/unsigned types too? Can this naive approach of getters and setters for the basic C-types lead to problems on different platforms?

- ssize_t keyGetInt (const Key * key, int * returnedInt)
ssize_t keySetInt (Key * key, int newIntValue)

- ssize_t keyGetChar (const Key * key, char * returnedChar)
ssize_t keySetChar (Key * key, const char * newCharValue)

- ssize_t keyGetFloat (const Key * key, float * returnedFloat)
ssize_t keySetFloat (Key * key, float newFloatValue)

- ssize_t keyGetDouble (const Key * key, double * returnedDouble)
ssize_t keySetDouble (Key * key, double newDoubleValue)

**Comment by tom-wa** [comment]
any reason why the getters don't return the result values ? 

>ssize_t keySetChar (Key * key, const char * newCharValue)

shouldn't that be `keySetString` or the 2 argument `const char newCharValue` ?

**Comment by markus2330** [comment]
Thank you for starting the discussion!

> Here is a list of typed getters/setters we could add to kdb.h.

The core is reserved for operations directly accessing internal structures, so we can and should have this in an extra header file and library. (Maybe together with the high level API?)

> What's your opinion about that?

Looks nice for lower level get/set of the types!

> Do we want to support short/long/unsigned types too?

We should at least have support every data type we support in meta data (see #1324).

> Can this naive approach of getters and setters for the basic C-types lead to problems on different platforms?

Yes, but only issues C people already know (`sizeof(int)`, `CHAR_BIT!=8`, char can be signed/unsigned and so on)

Alternatively, or additionally, we could use the types defined in src/include/kdbtypes.h which already abstracts over some of these issues.

**Comment by domhof** [comment]
@tom-wa The idea for not returning the values directly was that the return value is used for error handling in the existing Value, String and Binary getters/setters and I tried to be consistent with them.

> shouldn't that be keySetString or the 2 argument const char newCharValue ?

Right, it actually wasn't meant to be a pointer. :-)

@markus2330 

> The core is reserved for operations directly accessing internal structures, so we can and should have this in an extra header file and library. (Maybe together with the high level API?)

Do you mean that the Core API shouldn't handle any types at all (except for string and binary)?

**Comment by markus2330** [comment]
> Do you mean that the Core API shouldn't handle any types at all (except for string and binary)?

Exactly! Maybe not even strings/binary but only a single interface for non-null-terminated chars (keeping it absolutely minimal). And directly above it we have a convenience layers with all the types.

Obviously every C programmer would use the convenience layer (it is still very low level), but for many plugins and bindings this convenience is not needed.

**Comment by markus2330** [comment]
This feature was implemented in the high-level API.
