### ISSUE TITLE
debian: Build python3 bindings and rename packages

### ISSUE THREAD

**Issue by reox** [ElektraInitiative/libelektra#1343]
Currently I use the builds from here: https://build.libelektra.org/job/elektra-git-buildpackage-jessie/

But there are no python3 bindings.

Also the names of the packages should probably be python3-libelektra and not libelektra-python?
The current debian package name is libelektra4-python, which is a python3 version... Or is the name libelektra-python because it is not a python module but rather a plugin for elektra itself that also has the python bindings?

**Comment by markus2330** [comment]
Thank you for creating the issue!

We will have to drop the broken debian wheezy builds anyway which are the cause of most of these troubles. Removing the support for wheezy, we can use the upstream debian source files, which includes `python3-elektra`. Unfortunately the todo list in #160 is long..

There are both python bindings and a python plugin (which allows to write Elektra plugins using python); each of them for python2+3. The plugin needs the binding to work.

Where did you find libelektra4-python? Do you mean the official debian package? Yes, it has the python3 plugin. python3-elektra has the bindings.

In our jessie repo there is only libelektra-python4 which contains python 2 binding (/usr/lib/python2.7/dist-packages/kdb.py+so)+python 2 plugin (/usr/lib/elektra4/libelektra-python2.so).

**Comment by reox** [comment]
https://packages.debian.org/sid/libelektra4-python

okay, I'm not 100% sure but if the package does not only contain the python bindings, the name should be fine

**Comment by markus2330** [comment]
We now have python3 and python2 packages build on our build server.
