### ISSUE TITLE
Start reference counting with 1 and remove keyDel()

### ISSUE THREAD

**Issue by domhof** [ElektraInitiative/libelektra#1344]
In the following proposal Key can be interchanged with KeySet, so it actually is a proposal for reference counting of Key AND KeySet.

## Current situation:

- keyNew creates a Key with a reference count of 0.
- keyDup creates a Key with a reference count of 0.
- The user can increment the reference counter if he needs to.
- When the Key is not needed anymore by the user, he has to delete it with keyDel(). If he previously increased the reference count, he must decrease it before calling keyDel(), otherwise memory is leaked.
- The user still has to call keyDel() when he doesn't use the Key anymore.
- If he passes the key to a function that takes ownership he doesn't have to call keyDel() and if he does it's a no-op (in fact not really, because it has the overhead of the function call and the check for the reference counter being 0)

#### API version compatibility:
Suppose that in the first version of a high level API we have foo() and bar(). foo returns a Key. 
The user must call keyDel() on this Key when he is done with using it. 
Let's assume for the next version of the API we want to introduce a context/state and we have to store a reference to the returned Key internally (the function still serves the same purpose for the user but is internally implemented differently). By doing so we would break API compatibility and the user of our API would have to adapt his code to call keyDecRef() instead of keyDel() when he updates to the new API version. Moreover, he can easily forget to adapt it, and would not even notice it, because keyDel() does nothing if the reference count is greater than zero.

The following example illustrates this (notice that API 2 not even increases the reference count directly by using keyIncRef but only implicitly by storing the Key in a KeySet for later use).

#### API 1

```c

// API 1

Key * foo() 
{
  Key *key = keyNew("..."); // reference count is 0

  return key;
}

void bar() 
{
  // ...
}

// Application code

int main (int argc, char ** argv) {
    Key * key = foo (); // Reference count is 1.

    // Use key...

    keyDel (key); // In API 1 this will free the memory.

    bar ();
}

```

#### API 2

```c

// API 2

KeySet * ks = NULL;

Key * foo ()
{
    if (ks == NULL)
    {
        ks = ksNew (0, KS_END);
    }

    Key * key = keyNew ("..."); // Reference count is 0.
    ksAppendKey (ks, key); // Reference count is 1.

    return key;
}

void bar ()
{
    // ...

    ksDel (ks);
    ks = NULL;
}

// Application code

int main (int argc, char ** argv) {
    Key * key = foo (); // Reference count is 2.

    // Use key...

    keyDel (key); // In API 2 this will result in a no-op.

    bar ();

    // At this point the memory is not freed, since the reference counter is still 1.
}

```

#### Risk of dangling pointers
Suppose the user creates a Key and stores a reference to it. Then he adds the Key to a KeySet, does something with the KeySet and then calls ksDel() on that KeySet. Since ksDel() calls keyDel() on each Key stored in the KeySet, the reference to the users key now points to a deallocated location - we have a dangling pointer. If the user subsequently uses the stored reference he will see undefined behavior of our API.

```c

int main (int argc, char ** argv) {
    Key * key = foo (); // Reference count is 0.

    KeySet * ks = ksNew (0, KS_END);

    ksAppendKey (ks, key); // Reference count is 1.

    // Use ks...

    ksDel (ks); // ksDel calls keyDel() on key too.

    // Now the user has a dangling pointer within his scope.
}

```

While this can of course be prevented by the user by calling keyIncRef(key) before adding the Key to the KeySet, this can be easily forgotten and can lead to bugs that can be hidden due to possibly deactivated compiler optimization in debug builds and as such might only occur in release builds.

## Proposed solution
- Newly created Keys start with a reference count of 1.
- Rename keyIncRef to "keyRetain" and keyDecRef to "keyRelease" because it expresses semantically better what it does (we hide the implementation detail that a reference counter is increased/decreased).
- Remove ksDel(Key *key)
- keyRelease(Key *key) deletes the key if reference count is 0 after decreasing it.
- If an API function creates a new Key, the user must keyRelease it when he doesn't need it anymore.
- API functions that create and return a Key must either state this explicitly in the documentation or better follow a naming convention (e.g.: The name of a function that returns a newly created key must start with new, create or copy).

```c
Key * keyNew (const char * name, ...); // Reference count is 1.
void keyRetain (Key * key);
void keyRelease (Key * key);
```

### Advantages of the proposed solution
- Consistent handling of ownership. A function takes ownership by calling ksRetain and subsequently ksRelease when it doesn't need it anymore. 
- We can remove the function ksDel().
- Freeing memory is implicitly handled by ksRelease.
- No unintentional ksDel/ksDecRef no-ops can be made anymore.
- Better version-compatibility of high level APIs that build upon the core API.
- No risk of introducing a dangling pointer.

### Downside of the proposed solution
- The calling function must store a reference to a newly created Key. This is required to be able to call keyRelease() on the before created Key. This means a Key cannot be created "on-the-fly" as an argument to a function anymore. However, in my opinion this outweighs the risk of introducing a dangling pointer in the users application space. Still, by forgetting to call keyRelease on the Key, the user can potentially leak memory.

**Comment by markus2330** [comment]
Thanks for creating the proposal!

It is a consequent result from also removing the vaargs functionality. Admittedly, they cause a lot of issues, in particular for bindings.

We could also use a hybrid solution (having an flag for the key constructor which decides if a Key lives within a KeySet or is owned by the creator).

Maybe we find even a low-level solution which our current API can be build on? (And bindings would use the lower-level solution without vaargs troubles)

Btw. do not forget to make suggestions regarding the higher-level APIs, they are much more urgent. The kdb.h changes cannot be done before 0.9/1.0 anyway.

**Comment by markus2330** [comment]
I like this proposal but I am afraid there is nobody to work on it. I'll close it for now.
