### ISSUE TITLE
Java Detection on Debian Jessie

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1349]
On Debian jessie there seems to be something wrong with the java detection:

```
-- Found Java: /usr/bin/java (found version "1.8.0.51") 
-- Exclude Binding jna because Java not found, but required to build the jna bindings
```

Better error messages would be helpful.

CMakeCache.txt:
```
//Path to java command, used by the Dart server to create html.
JAVACOMMAND:FILEPATH=/usr/bin/java

//Path to a file.
JAVA_AWT_INCLUDE_PATH:PATH=/usr/lib/jvm/default-java/include

//Path to a library.
JAVA_AWT_LIBRARY:FILEPATH=/usr/lib/jvm/default-java/jre/lib/amd64/libjawt.so

//Path to a file.
JAVA_INCLUDE_PATH:PATH=/usr/lib/jvm/default-java/include

//Path to a file.
JAVA_INCLUDE_PATH2:PATH=/usr/lib/jvm/default-java/include/linux

//Path to a library.
JAVA_JVM_LIBRARY:FILEPATH=/usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so

//Path to a program.
Java_JAR_EXECUTABLE:FILEPATH=/usr/bin/jar

//Path to a program.
Java_JAVAC_EXECUTABLE:FILEPATH=/usr/bin/javac

//Path to a program.
Java_JAVADOC_EXECUTABLE:FILEPATH=/usr/bin/javadoc

//Path to a program.
Java_JAVAH_EXECUTABLE:FILEPATH=/usr/bin/javah

//Path to a program.
Java_JAVA_EXECUTABLE:FILEPATH=/usr/bin/java
```

Are you sure that Java detection is needed?
If I only remove the java detection and the `if` everything works fine. I do not see any place where you would refer to `java` (only to maven).

So why not:
```
diff --git a/src/bindings/jna/CMakeLists.txt b/src/bindings/jna/CMakeLists.txt
index 3812d69..356c1ea 100644
--- a/src/bindings/jna/CMakeLists.txt
+++ b/src/bindings/jna/CMakeLists.txt
@@ -1,8 +1,5 @@
-find_package (Java)
 find_program (MAVEN_EXECUTABLE mvn)
 
-if (Java_FOUND) # set by find_package
-if (Java_VERSION_MAJOR GREATER 0 AND Java_VERSION_MINOR GREATER 7)
 if (MAVEN_EXECUTABLE) # set by find_program
        file (
                MAKE_DIRECTORY libelektra4j
@@ -52,9 +49,3 @@ if (MAVEN_EXECUTABLE) # set by find_program
 else (MAVEN_EXECUTABLE)
        remove_binding (jna "Maven Executable not found, but required to build the jna bindings")
 endif (MAVEN_EXECUTABLE)
-else (Java_VERSION_MAJOR GREATER 0 AND Java_VERSION_MINOR GREATER 7)
-       remove_binding (jna "Java is not greater version 8, but ${Java_VERSION} was found")
-endif (Java_VERSION_MAJOR GREATER 0 AND Java_VERSION_MINOR GREATER 7)
-else (Java_FOUND)
-       remove_binding (jna "Java not found, but required to build the jna bindings")
-endif (Java_FOUND)
```

**Comment by e1528532** [comment]
According to https://cmake.org/cmake/help/v3.8/module/FindJava.html?highlight=findjava there should be the Java_FOUND flag. But it gets only set if all java components are found, which might be the issue there.

But i agree, the best solution is probably really to just remove the java check. I mean without java maven will not work and then fail at build time, as also Bernhard argued, since maven itself is programmed in java. Thats why i initially left the check in the code. But i guess its save enough to assume that everyone who has installed maven and plans to use it, has also installed java. So i think your suggestion should be fine to future problems with the cmake FindJava module.

**Comment by markus2330** [comment]
> I mean without java maven will not work and then fail at build time, as also Bernhard argued, since maven itself is programmed in java

If cmake finds a java has little to do with if maven finds a java.
