### ISSUE TITLE
consistency of METADATA.ini

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1355]
As discussed in #1320 

Please provide a consistency checker between plugin's contract and metadata.ini. It should be a small script that parses infos/metadata out of src/plugins/*/README.md; and also parses all usedby/plugin of doc/METADATA.ini and check if they have exactly the same information.

On error it should output which metadata in plugins and METADATA.ini is missing, ideally with printing where it should be added.

The script should be in the style of the README.md check in tests/shell/check_plugins.sh.
It should run during `make check`, thus also on the build server. bash as dep is okay.

**Comment by markus2330** [comment]
implemented by #1368

**Comment by mpranj** [comment]
Why not close the issue if it is already implemented? What is missing?

**Comment by markus2330** [comment]
@mpranj Do you know if the CI already executes it? If yes, please close.

**Comment by mpranj** [comment]
Yes the CI already executes it.
