### ISSUE TITLE
OpenSSL detection in OS X is still not working

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#1357]
# Describe what you wanted to do

Generate the build scripts using

    cmake -DCMAKE_INSTALL_PREFIX=${PWD}/ -DKDB_DB_SYSTEM=${PWD}/bin/ -DPLUGINS="sync;dump;resolver_fm_hpu_b;crypto_gcrypt;crypto_botan;crypto_openssl;fcrypt;base64" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DBUILD_DOCUMENTATION=OFF -DENABLE_DEBUG=OFF -DELEKTRA_ENABLE_OPTIMIZATIONS=ON ..

under Mac OS Sierra 10.12.3 (16D32)

# Describe what you expected

Working detection of OpenSSL.

# Describe what actually happened

CMake output:

    -- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.1") 
    -- OpenSSL compile/linker test failed
    -- Exclude Plugin crypto_openssl because OpenSSL development files not found

# System Information

- Elektra Version: master
- OpenSSL 0.9.8zh 14 Jan 2016
- cmake version 3.7.2 

# Further Log Files and Output

**Comment by markus2330** [comment]
Thanks for reporting and self-assigning!

Seems like "OpenSSL compile/linker test failed". There should be a detailed information in the build directory's file `CMakeFiles/CMakeError.log`.
