### ISSUE TITLE
Fcrypt compile error on OS X

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#1358]
# Describe what you wanted to do

Compile the fcrypt plugin on Mac OS Sierra 10.12.3 (16D32)

# Describe what you expected

Working compilation.

# Describe what actually happened

    /Users/pnirschl/Projects/libelektra/src/plugins/fcrypt/fcrypt.c:174:20: error: use of undeclared identifier 'UTIME_OMIT'
            times[0].tv_sec = UTIME_OMIT;
                              ^
    /Users/pnirschl/Projects/libelektra/src/plugins/fcrypt/fcrypt.c:175:21: error: use of undeclared identifier 'UTIME_OMIT'
            times[0].tv_nsec = UTIME_OMIT;
                               ^

# System Information

- Elektra Version: master
- Apple LLVM version 8.0.0 (clang-800.0.42.1)
- cmake version 3.7.2
- Mac OS Sierra 10.12.3 (16D32)

# Further Log Files and Output

**Comment by markus2330** [comment]
Thanks for reporting and self-assigning! Maybe it is useful to extend the abstractions of time stamps via macros in `src/include/kdbmacros.h`.

**Comment by petermax2** [comment]
> Maybe it is useful to extend the abstractions of time stamps via macros in src/include/kdbmacros.h.

I found out that FreeBSD and OpenBSD both provide `UTIME_OMIT` and `UTIME_NEW`. Mac OS seems to be the only exception. Do you think it is worth the effort for one OS?

**Comment by petermax2** [comment]
0873b42f807cde8b8fffc1e212c287963a47645d works on Mac OS Sierra. I also successfully tested on FreeBSD 11, where it works fine too.
