### ISSUE TITLE
static code checkers

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1362]
http://www.catb.org/gpsd/reliability.html

see also:

http://www.aosabook.org/en/gpsd.html

**Comment by e1528532** [comment]
https://scan.coverity.com/ also seems to be a possibility for us

**Comment by e1528532** [comment]
I've tried out cppcheck now. Its quite easy to use as it supports cmake. 

First you run cmake with the parameter -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
this makes it create a json file in the same folder which contains the compilation configuration.

Then you simply run cppcheck with the parameters you want, e.g. i've tried it with
`cppcheck --project=compile_commands.json --enable=all -j 8 --xml-version=2 2> cppcheck_result.xml`

then you can create a fancy html report out of it, i've attached mine. It shows mostly style and performance issues, but also reports some errors we might want to look at.
`cppcheck-htmlreport --file=cppcheck_result.xml --report-dir=cppcheck_report --source-dir=.` (. if you are already in the build directory)

[cppcheck_report.zip](https://github.com/ElektraInitiative/libelektra/files/1081249/cppcheck_report.zip)

I guess we can automate this procedure and add it to the build server too if we want to

**Comment by e1528532** [comment]
Next i check scan-build. It is a tool for the use with clang, doesn't work with gcc.
Basically its fairly easy to use too, instead of `make `you just do `scan-build make`, parallelization via -j is supported.
Then it hooks into the compilation calls and generates a report out of it, which it then allows you to view.
Example call: `scan-build -o ./scanbuild_result make -j 32`

Again, I've attached a sample report of my local build.

[scanbuild_result.zip](https://github.com/ElektraInitiative/libelektra/files/1081324/scanbuild_result.zip)

**Comment by markus2330** [comment]
> First you run cmake with the parameter...
> scan-build

Could you please add the docu how to use these two tools to `doc/TESTING.md`?

> I guess we can automate this procedure and add it to the build server too if we want to

Sounds useful if we can fail the builds on warnings/errors of the checker. But first we would need to fix the warnings/errors. They should be fairly easy to fix?

**Comment by e1528532** [comment]
basically a lot has been done on that matter. a few fixes were reverted because otherwise it breaks abi incompatibility. how do we want to proceed on that issue?

**Comment by markus2330** [comment]
> basically a lot has been done on that matter. a few fixes were reverted
> because otherwise it breaks abi incompatibility. how do we want to
> proceed on that issue?

The reverted ABIs got their own issue #1668 (to be reverted again later)

An open topic is integration in the build server and trying out further static checkers. Thus this issue can stay open.
