### ISSUE TITLE
Storage plugins: provide additional "info" metadata

### ISSUE THREAD

**Issue by tom-wa** [ElektraInitiative/libelektra#1365]
while writing the `file` plugin i thought it would be convenient to provide informations like: filesize, atime, ctime, mtime, filetype, owner, mode, etc as metadata since i have to `stat` the file anyway.
for other storage plugins additional infos like number of entries, version/specification/standard/extensions/... if supported, etc might also come in handy for some users

**Comment by markus2330** [comment]
Seems like we had the same idea!

`doc/METADATA.md` contains a specification for it in section `Old stuff inherited from filesys plugin`.

> filesize

Does this differ to the size of the value?

> for other storage plugins additional infos like number of entries,

Does this differ to `ksGetSize`?

> version/specification/standard/extensions/... if supported, etc might also come in handy for some users

Yes, actually it would be a nice idea to have an optional header that states which plugin settings are needed to mount the file. It would be an important step to automatically detect the configuration file format. I am not sure if @vanessaNWK wants to work on this topic, too. If not, we rather keep it simple and avoid too much info that might be wrong.

**Comment by tom-wa** [comment]
>>filesize
>
>Does this differ to the size of the value?

probably never but it would be nice for shell scripting

>>for other storage plugins additional infos like number of entries,
>
>Does this differ to ksGetSize?

maybe if post-get transformations happen + same reason as above

**Comment by markus2330** [comment]
>  probably never but it would be nice for shell scripting

But then let us directly have a way to enquiry the size of a key value. (Extend the kdb tool.) Having redundant meta data doesn't seem like a good idea.

> maybe if post-get transformations happen

Why would you need the original number of keys a storage plugin added? The purpose of e.g. `hidden` is to hide keys someone is not interested in. If someone is interested, `hidden` would not be added.

**Comment by tom-wa** [comment]
>doc/METADATA.md contains a specification for it in section Old stuff inherited from filesys plugin.

i'd say we should prefix those with something like `fileinfo`, `file`, ... ?

**Comment by markus2330** [comment]
Yes, should be prefixed, file is okay. Can you please update the file plugin and METADATA.ini?
