### ISSUE TITLE
race tests broken

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#137]
the test running the "race" utility has some problems, strangely even if it skips the test.

**Comment by markus2330** [comment]
reopen: the program race might hang if some resource is exhaustet. Additionally, it should print some logs to better see whats going on

**Comment by markus2330** [comment]
Depends on global plugins.

**Comment by markus2330** [comment]
To solve the issue we need to implement a global lock plugin, can be done now

**Comment by markus2330** [comment]
See  #613, which might be solved with the global lock plugin, too.

**Comment by KurtMi** [comment]
@markus2330 I went from testing the semlock, to the race tool/test and now have some questions.

Why is there a consistency check with the timestamp in the resolver?
At an kdb get the time is stored and at kdb set compared. If they do not match kdb set fails.
I ask because I tried the semlock with the race tool/test and now get this:
```
src/plugins/resolver/resolver.c:1041:libelektra_resolver_fm_hpu_b_LTX_elektraPluginset: entering resolver::set -1 "/home/jenkins/.config/default.ecf"
src/plugins/resolver/resolver.c:795:elektraCheckConflict: Add Error 30 : conflict, file modification time stamp 1550576761.295271045 is different than our time stamp 1550576749.932126933, config file name is "/home/jenkins/.config/default.ecf", our identity is uid: 1000, euid: 1000, gid: 1000, egid: 1000
src/plugins/resolver/resolver.c:1100:libelektra_resolver_fm_hpu_b_LTX_elektraPluginset: leaving resolver::set -1 "/home/jenkins/.config/default.ecf"
```
What is your plan about the kdb serialization #2024?

**Comment by markus2330** [comment]
> Why is there a consistency check with the timestamp in the resolver?

Which consistency check do you mean?

The conflict is necessary because otherwise data of other KDBs is lost.

> What is your plan about the kdb serialization #2024?

If semlock works reliable and the speedup is considerable, we can run the tests in parallel.

By default I would not make the semlock plugin having long-term locks, though. The current implementation of the race tests are maybe too strict, they might find problems even if there are none. Conflicts are not a problem per se. Only non-atomic kdbGet/kdbSet are a problem.

**Comment by KurtMi** [comment]
> Which consistency check do you mean?

I mean this check:
```
if (ELEKTRA_STAT_SECONDS (buf) != pk->mtime.tv_sec || ELEKTRA_STAT_NANO_SECONDS (buf) != pk->mtime.tv_nsec)
```
in the `elektraCheckConflict (...)` function. This function is invoked in `elektraSetPrepare (...)` and this one in the resolver set of the `/src/plugins/resolver/resolver.c`.

> The conflict is necessary because otherwise data of other KDBs is lost.

But is there not a merge? and does the resolver not read the file just before the set and also at the kdbGet?

**Comment by markus2330** [comment]
> I mean this check:

Yes, exactly this check is to verify that nobody else changed the data. It is needed to not overwrite data of others.

> But is there not a merge?

It is the application's responsibility to merge properly. E.g. the high-level API automatically merges.

> and does the resolver not read the file just before the set and also at the kdbGet?

No, Elektra only reads the file if `kdbGet` is invoked. So in between `kdbGet` and `kdbSet` someone else could use `kdbSet`.
