### ISSUE TITLE
METADATA.ini for tools

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1374]
We need info from METADATA.ini for some tools, at least:

- [ ] type dispatcher
- [ ] spec reader: `src/libs/tools/src/specreader.cpp`
- [ ] spec plugin?
- [ ] speccheck plugin, see #2382

## For type dispatcher

We could require METADATA.ini to be mounted (would only work if the type dispatcher is mounted globally though).

The issue with using it at compile time is that it won't be aware of newly added/installed plugins (neither of not installed plugins?). But its certainly better as duplicating the information.

It is also a question of overhead. While reading METADATA.ini during mounting does not really matter, the type dispatcher would do so on every KDB access, which might be an issue.

Maybe we find a solution where METADATA.ini parsing and type -> plugin names happens during mounting? Maybe in checkconf of the type dispatchers plugin?

**Comment by markus2330** [comment]
From the current behavior of Elektra it might be best to move these decisions at mount-time. There we can assume `METADATA.ini` to be mounted and do not have to care about performance too much.

Also pro mount-time: It might also be confusing for a user if suddenly some applications use different plugins (but previously started ones not, thus it would be hard to detect at run-time when new plugins are installed).

**Comment by tom-wa** [comment]
so you mean something like a dummy plugin that mounts METADATA.ini and typedispatcher states int `info/needs` that it requires that dummy plugin ?

**Comment by markus2330** [comment]
We can implement that logic directly in `kdb mount`, no need for a dummy plugin. We can even automatically mount `METADATA.ini` if it is not there.

The out-of-the-box experience would be much nicer if such basics plugins are all mounted by default.

**Comment by markus2330** [comment]
I prosopse to mount it at:

`spec/elektra/meta`
