### ISSUE TITLE
Linker error for a plugin using CPP bindings

### ISSUE THREAD

**Issue by e1528532** [ElektraInitiative/libelektra#1379]
# Describe what you wanted to do

I wanted to write a plugin in cpp which makes use of the cpp bindings.

# Describe what you expected

I expected that this is possible and build will succeed

# Describe what actually happened

It worked fine as long as i didn't make use of the CPP bindings, but only of CPP itself (for experimenting with xerces). Until that moment my cmake file looked like this:

```
add_plugin (xerces
	SOURCES
		xerces.hpp xerces.cpp
		deserializer.hpp deserializer.cpp
	INCLUDE_DIRECTORIES
		${XercesC_INCLUDE_DIRS}
	LINK_LIBRARIES
		${XercesC_LIBRARIES}
	ADD_TEST
)
```

But since i included the header files <keyset.hpp> and <key.hpp>, it doesn't compile anymore, i have to add a CPP to the add_plugin in the CMakeFile. Thats also how the lua and python plugins seem to do it:

```
add_plugin (xerces
	CPP
	SOURCES
		// ... rest is the same
```

Now it doesn't complain about unknown header files anymore, but fails in the last linking step:

```
ld: library not found for -lCPP
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/plugins_tests/CMakeFiles/testmod_xerces.dir/build.make:105: bin/testmod_xerces] Error 1
make[1]: *** [CMakeFiles/Makefile2:10662: src/plugins_tests/CMakeFiles/testmod_xerces.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

What do i miss? I've cross compared with lua and python which also seem to use the CPP bindings as a plugin but i don't see the issue.

# System Information

- Elektra Version: master
- Apple LLVM version 8.0.0 (clang-800.0.42.1)

# Further Log Files and Output
You can find the whole plugin a branch in my fork: https://github.com/e1528532/libelektra/tree/xerces-plugin/src/plugins/xerces , its too early for a PR imo, i want to have it compile at least.

**Comment by markus2330** [comment]
> I expected that this is possible and build will succeed

Yes, it is possible, type and struct do it this way.
Only dump is using c++, but not the c++ bindings.

Your error might be related to some cmake cache issues. Try to remove the build directory.

> too early for a PR

You can and should always create a PR, then the build server would have checked for you if the issue is on your computer.

**Comment by e1528532** [comment]
Finally i spotted the issue.

It looks like when i add the CPP flag to add_plugin, it passes this to the linkage of the test for this plugin. our cmake add_plugin macro seems to be able to only add c based tests though, but tries to pass the CPP argument somehow and then fails to link the plugin test. 

I add the test manually now and don't use the ADD_TEST argument of add_plugin (too bad, that would be very convenient though), so it doesn't pass the CPP linker argument. Works fine but you have to know that.

**Comment by markus2330** [comment]
Could you please add a CMake check that gives a clear error when someone tries to pass CPP (indirectly) to tests?
