### ISSUE TITLE
check_meta buggy?

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1381]
check_meta claims that `ni` needs an `order` metakey although this is not specified. Does it get confused with `ini`?

Fix should also remove `order` from `src/plugins/ni/README.md` which is wrong and was only added to satisfy the unit tests.

**Comment by sanssecours** [comment]
> Does it get confused with `ini`?

As far as I can tell, yes. I opened a pull request, which hopefully fixes the problem [here](https://github.com/ElektraInitiative/libelektra/pull/1382).
