### ISSUE TITLE
Names for "Core" API and "High level" API

### ISSUE THREAD

**Issue by domhof** [ElektraInitiative/libelektra#1385]
Currently we use KDBHL as name for the high level C-API. As @markus2330 already mentioned we should define a better name before we get too much used to it.

Since the API defined in kdb.h handles only the most basic getter/setter methods and reference counting of Keys and KeySet, I think we could call it KDBCore. Probably people don't want to care about things like reference counting, Keys and KeySets when they start with Elektra and will want to work with a higher level API (KDBHL) when they start with Elektra. I think this API, for simplicity, should just be called KDB, such that it is clear for a beginner where to start.

What is your opinion on that?
An alternative (besides other names) would also be that there is only one API, called KDB which provides both low and high level functionality.

**Comment by markus2330** [comment]
KDB is quite prone to name clashes, did you check if it is safe?

An alternative would be that the high-level API simply starts with `elektra` or even everything starts with `elektra`?

**Comment by domhof** [comment]
> An alternative would be that the high-level API simply starts with elektra or even everything starts with elektra

👍 

I suggested KDB only because the existing APIs use that already. I would even prefer ```elektra``` as prefix (for everything) since I think this would be easier to understand for new users (I believe for them Elektra is the same as KDB anyway).

**Comment by markus2330** [comment]
We also need a name for `KDBHL`. Any suggestions?

`ElektraHandle`? `Elektra`?

**Comment by domhof** [comment]
> ```ElektraHandle```? ```Elektra```?

I would vote for ```Elektra```.

**Comment by markus2330** [comment]
Another idea: What about inventing some similar names to Elektra to give everything a proper name? E.g. also in mythology surrounding Elektra?

We need names for:

- the API
- the specification language
- ...

Btw. I really like your idea that we provide both the high level API and supplementing code generation. Will comment more on it soon.
