### ISSUE TITLE
crypto_openssl is broken

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#1389]
# Describe what you wanted to do

	kdb mount a.ecf user/a crypto_openssl "gpg/key=B815F1334CF4F830187A784256CFA3A5C54DF8E4"
	kdb set user/a/a
	kdb setmeta user/a/a crypto/encrypt 1
	kdb set user/a/a "ahoi"
	kdb get user/a/a

# Describe what you expected

Receiving "ahoi" as output of `kdb get`.

# Describe what actually happened

An empty line is returned by `kdb get`.

# System Information

- Elektra Version: master

# Further Log Files and Output

Thanks for @sanssecours for reporting it in #1384 .

**Comment by markus2330** [comment]
Thanks for creating the issue! Is it related to the `dlopen failed` errors? If it isn't can you also create an issue for the `dlopen` errors. (If you are sure it wasn't an installation problem as suggested by @sanssecours)

**Comment by petermax2** [comment]
There seems to be a problem in the OpenSSL BIO_ interface. I am writing 16 bytes to the BIO but it tells me 37 bytes are available.

    pnirschl@elektra-build-vm:~/libelektra/build$ ./bin/kdb set user/a/a "ahoi"
    written 16
    output data 37   key length 37
    Set string to ahoi

**Comment by petermax2** [comment]
The warnings only occur if I build a subset of the plugins. Maybe something is required but missing?

If I compile with `-DPLUGINS="sync;dump;resolver_fm_hpu_b;crypto_gcrypt;crypto_botan;crypto_openssl;base64"` the warnings occur.

If I compilte with `-DPLUGINS=ALL` everything is fine.
