### ISSUE TITLE
what's the desired behavior of the spec plugin?

### ISSUE THREAD

**Issue by BernhardDenner** [ElektraInitiative/libelektra#1390]
I currently wondering how the spec plugin is designed to work?
I know, it copies meta keys from the spec namespace to other namespaces. But should the copied metakeys remain at the target keys "forever", persisting through a storage plugin?

Example (suppose the battery example):
```sh
$> kdb setmeta spec/example/battery/age check/enum "'young', 'old'"
$> kdb set /example/battery/age old
Using name user/example/battery/age
Create a new key user/example/battery/age with string old
```
results in
```ini
#@META check/enum = 'young', 'old'
age = old
#@META check/enum = 'critical', 'low', 'high', 'full'
level = low
```
now I rethink my enum and want to add an additional value
```sh
$> kdb setmeta spec/example/battery/age check/enum "'young', 'avg', 'old'"
$> kdb set /example/battery/age avg                                       
Using name user/example/battery/age
Set string to avg
```
now the resulting ini looks something like
```ini
#@META check/enum = 'young', 'avg', 'old'
#@META conflict/check/enum = 'young', 'old'
#@META conflict/collision/#0 = check/enum
age = avg
#@META check/enum = 'critical', 'low', 'high', 'full'
level = low
```

Is this the intended behaviour? (just wondering)

I mean, I have the validation information already in the database (in spec namespace), but afterwards I have it in my "normal" namespace too, duplicated. After updating the specification in one place I get a conflict, of course.
Should the metakeys copied from the spec namespace be removed directly before passing them to the storage plugin?

**Comment by BernhardDenner** [comment]
Ahh, just found #670 so the copied metavalues should be removed then?

**Comment by tom-wa** [comment]
>So the copied metavalues should be removed then?

they should be removed before writing the keyset back to the file.. but the placements weren't documented (postgetcleanup and postsetcleanup) because all placements for global plugins were to be rewritten anyway.

if you mount the spec  plugin a second time (last postgetstorage and last presetstorage slot) it will remove all copied metadata from the keyset again before writing them to the configuration file

**Comment by BernhardDenner** [comment]
Ah ok, thanks for clarification
