### ISSUE TITLE
Plugin Functions: Return Value on Success

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1393]
👋 Hi,

the [documentation](https://github.com/ElektraInitiative/libelektra/blob/master/doc/tutorials/plugins.md#coding) states that `elektraPluginGet` should return `0` on success, yet the [template suggests](https://github.com/ElektraInitiative/libelektra/blob/master/src/plugins/template/template.c#L49) – since commit 📜 062e017e – that plugin functions should return `1` on success. 

[Other](https://github.com/ElektraInitiative/libelektra/blob/master/src/plugins/null/null.c#L57) [plugins](https://github.com/ElektraInitiative/libelektra/blob/master/src/plugins/date/date.c#L474) also use `1` to show that functions were successful, as far as I can tell. The `tcl` plugin on the other hand [returns `0` on success](https://github.com/ElektraInitiative/libelektra/blob/master/src/plugins/tcl/tcl.cpp#L59). Which return value is the correct one?

**Comment by tom-wa** [comment]
both are correct
1 for success + keyset updated
0 for success but nothing changed
-1 for error

**Comment by sanssecours** [comment]
> both are correct…

Thank you for the quick response. I will update the documentation accordingly.

**Comment by Namoshek** [comment]
I suggest to also add a note to the template:
```
//  1 for success + keyset updated
//  0 for success without changes
// -1 for error
return 1;
```

**Comment by sanssecours** [comment]
> I suggest to also add a note to the template, because it is trivial enough to not require to dive into a huge documentation…

Good idea. I just added the information to `elektraTemplateGet` in my local branch of the repo.
