### ISSUE TITLE
units-of-measurements plugin

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1398]
A plugin that gives numbers a more human-friendly syntax would be great.

I am thinking of following features, as specified in meta data:

- prefixing it with 0b and 0x to get binary or hexadecimal base
- postfixing it with a [Metric prefix](https://en.wikipedia.org/wiki/Metric_prefix) such as 20k to get 20000. Or for floats a [normalized number](https://en.wikipedia.org/wiki/Normalized_number), i.e. 2.0e4 (if we decide to support that for floats, see #1388)
- some e-notation or scientific notation, such as 20e3
- postfixing it with arbitrary strings (or SI-units) that are checked for presence. For example, "s" demands that it is 20ks or 20s, but 20 would be invalid then.

For writing out, it restores the same pre and postfix as it was when getting the value. For new values it uses the specified default.

The plugin either transforms to a value, or yields an error if the value cannot be transformed with the given specification.

For example:

```
[key]
type = long
unit/base/#0 = decimal
unit/base/#1 = hexadecimal
unit/notation/#0 = metric
unit/notation/#1 = e
unit/measurement = s
```

decimal and metric would be default, as they are first in the specifications. hexadecimal and e-notation would be allowed (and are also kept this way if it was so before). In any case, the key must be postfixed with s to be valid.

As first step, `0x` support for lcdproc would be enough. @tom-wa Do you think `0b` is needed for lcdproc?

What do you think?

**Comment by tom-wa** [comment]
i haven't seen any binary literals in the configs, and if they'd be needed somewhere i'm not sure if and how they should be interpreted. so let's avoid them for now.

about the rest: seems fine to me.

**Comment by markus2330** [comment]
Then lets start with hex-only and add later more if needed.

Do you also need escaping of strings for INI?

Do we need a transform dispatcher to have the hex and size plugin #1395 present without hassle?

**Comment by tom-wa** [comment]
>Do you also need escaping of strings for INI?

unescaping

>Do we need a transform dispatcher to have the hex and size plugin #1395 present without hassle?

i'm not really sure if we need it for now, but i'd prefer to have it. it's easier to specify the order of operations, you don't need to remount everything it you want to add another plugin, ....

**Comment by markus2330** [comment]
> unescaping

details? For `=`? Only for values or also for names? And metanames, too?

> but i'd prefer to have it. it's easier to specify the order of operations, you don't need to remount everything it you want to add another plugin, ....

Yes, it is definitely easier and much more flexible. With transformation and type dispatcher present, changing of storage and resolver is basically the only reason to remount. And this sounds quite sensible.

If it works really well, we might not have the need to fix the limitation of number of plugins, too.

**Comment by markus2330** [comment]
@tom-wa already used "hex" as "type" in the range plugin. But I would prefer to use a separate meta data for hex because many different numerical types can be denoted in hex. We do not want to lose information (if it was long, unsigned long, and so on...).

To specify a list of bases to be allowed might be over engineered. Simpler proposal (without arrays):

```
[unit/base]
type = enum dec bin hex any
default = dec
description = allows values to be written in other bases.
```


For example:

```
[key]
type = long
unit/base = any
unit/notation = metric
unit/measurement = s
```

Here 0x20Aks would be valid, representing 522000s, transformed to 522000. I have to admit that metric prefixes in non-decimal numbers is also a quite bizarre feature. Further simplifications are welcomed.

**Comment by markus2330** [comment]
We now have a units plugin.
