### ISSUE TITLE
escaping in (meta)keynames

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1400]
Issue: some storage plugins are not able to write every keyname (or metakeyname).

(Only brain storming at the moment)

Writte in #1380 by @e1528532:
> The only issue that remains is that xerces doesn't handle illegal element & attribute names. I haven't really found a lot about that, only microsoft seems to offer something for that case: https://msdn.microsoft.com/en-us/library/35577sxd(v=vs.80).aspx
I think their approach should be fine basically, and if we can extend the rename plugin so it changes key names (also of metakeys) to this escaped version (and vice versa) we can also handle forbidden characters in xml element names. The only problem i can think of is that if someone calls a key like _x00010000_ for a reason (seems to be rather unlikely for me, but everything is possible ;) ) as it would also be unescaped then.

We also have this issue for JSON and other plugins. There is already the hexcode plugin which could be configured to use `_` as escaping character, but it only applies to values. The rename plugin supports renaming of key names, but has no escaping strategies.

TODO: Design general strategy for how to handle renaming in (meta)keynames.

Should we group together by escaping algorithm or by what is renamed (key, value, metakey)?

**Comment by e1528532** [comment]
Regarding the grouping:

For simplicity, we might just specify we want to escape for xml and then it escapes the key and metakey names automatically, leaving the rest like it is. But this kind of escaping is only useful for the xerces plugin which uses keynames as element names, it wouldn't be necessary for the old xmltool plugin which also maps keynames as attributes. So i don't know if its a good idea to call the escaping algorithmn "xml" then as its only required if we serialize keysets to xml with the xerces plugin.

If we group both by escape algorithmn and what is renamed we would get the most flexible startegy. For instance, we can say something like escape key names as xml and escape metakey names as xml too. Now imagine another plugin or use case which maybe also works with xml where you want to use key values as element names for whatsoever reason. If we offer both grouping possibilities in those cases you could still use the rename plugin and tell it to escape key values as xml now. 

So i guess its rather a question of simplicity (fixed xml escaping algorithm always only escaping key names and metakey names) vs flexibility (both grouping options possible).

**Comment by markus2330** [comment]
Yes, having an extra plugin that is only useful for xerces does not make much sense.

The ccode plugin allows you to specify which character to use for escaping and what to escape. simpleini makes use of this escaping by stating in the contract which characters should be escaped.

We are only lacking for a plugin that does the same, but for (meta)keynames. Then we could configure it to use `_` for escaping, and it should work for xerces, too.

**Comment by markus2330** [comment]
Making the grouping question more precise:

The question is

1.) if we should extend hexcode, ccode and base64 plugins to also work on (meta) keynames or

2.) if we should extend the rename plugin to also have hexcode, ccode and base64 functionality, and add a `metarename` plugin, with the same algorithms, too.

For option (1) we would need a library to share renaming logic, for (2) we would need a library to share the algorithms. (1) might be better here, because renaming of keys is something better suited for Elektra's libraries than escaping algorithms.

The usability, would be quite similar:

```
(1) kdb mount file.xml xerces hexcode rename=,metarename=
(2) kdb mount file.xml xerces rename algorithm=hexcode metarename algorithm=hexcode
```

(Of course once xerces has the dependency in the contract, the user only needs to specify the renaming if she wishes another renaming algorithm).

**Comment by sanssecours** [comment]
I prefer option (1) since this way the code of a single plugin should stay relatively simple. The rename plugin already does two jobs at once (renaming/cutting) as it currently stands.
