### ISSUE TITLE
Code generation: ImportError: cannot import name util

### ISSUE THREAD

**Issue by domhof** [ElektraInitiative/libelektra#1413]
When executing `./gen path/to/specification.ini template/genopt.h` I keep getting the following error (Ubuntu 16.04, libelektra master):

```
Traceback (most recent call last):
  File "./gen", line 101, in <module>
    main()
  File "./gen", line 65, in main
    searchList=[parameterSpecification])
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1259, in __init__
    self._compile(source, file, compilerSettings=compilerSettings)
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1553, in _compile
    keepRefToGeneratedCode=True)
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 788, in compile
    exec(co, mod.__dict__)
  File "_home_parallels_Projects_Elektra_libelektra_src_tools_gen_template_genopt_h.py", line 27, in <module>
ImportError: cannot import name util
```

Any ideas?

**Comment by markus2330** [comment]
Do you use python2.7 and cheetah for exactly this version?

Does `make` work in this folder?

If it does, you might invoke the tool incorrectly:
Maybe the -c --classname does not fit (it has util has default)

**Comment by domhof** [comment]
I reconfigured and compiled libelektra to include the static lib. Then I ran make for gen, which failed (without running make I still get the same error). Somehow gen is working now, although I'm not sure if it's output is correct (doesn't currently generate much code for wc).

**Comment by markus2330** [comment]
Does it work now? What did you change? (The error message does not look like it has to do something with static libs)

**Comment by domhof** [comment]
Yes, gen is working now. Maybe just running make for gen fixed it already, I honestly don't know what's going on but I'm glad it works... ;-) Btw. I had the same problem on OS X.

**Comment by markus2330** [comment]
If you can reproduce the issue, please reopen with details.
