### ISSUE TITLE
enum plugin case problems

### ISSUE THREAD

**Issue by omnidan** [ElektraInitiative/libelektra#1414]
I have a `gender` proprety with the following metakey: `check/enum = ['male','female','NA']`

However, when I try to set the value `NA` via `kdb set /pk/1600000/student/gender "NA"`, I get an error:

```
Using name user/pk/1600000/student/gender
The command kdb set failed while accessing the key database with the info:
Sorry, the error (#121) occurred ;(
Description: validation failed
Ingroup: plugin
Module: enum
At: enum.c:203
Reason: Validation of key "user/pk/1600000/student/gender" with string "NA" failed.
Mountpoint: user/pk/1600000
```

However, the other possible values (`male` and `female`) work fine.

**Comment by tom-wa** [comment]
it should be `'male','female','NA'`

**Comment by tom-wa** [comment]
oh, just saw that i updated the code to allow `]` at the end too, but never the documentation.. 
your example works for me though

```
% kdb setmeta user/pk/1600000/student/gender check/enum "['male','female','NA']"
% kdb set user/pk/1600000/student/gender male              [0]
Set string to male
% kdb set user/pk/1600000/student/gender female            [0]
Set string to female
% kdb set user/pk/1600000/student/gender NA                [0]
Set string to NA
% kdb set user/pk/1600000/student/gender blubb             [0]
The command kdb set failed while accessing the key database with the info:
Sorry, the error (#121) occurred ;(
Description: validation failed
Ingroup: plugin
Module: enum
At: /home/thomas/Dev/libelektra/src/plugins/enum/enum.c:203
Reason: Validation of key "user/pk/1600000/student/gender" with string "blubb" failed.
Mountpoint: user/pk/1600000
Configfile: /home/thomas/.config/student.dump.6648:1489598851.635107.tmp
```

**Comment by omnidan** [comment]
@tom-wa that's strange - executing exactly the same commands fails for `NA` for me. with `'male','female','NA'` (without the brackets `[` and `]`) it works fine, though. seems like the brackets were the problem and this is fixed now :+1:

**Comment by markus2330** [comment]
Thanks for reporting!

Yes, I think nothing is to do then, we only support the syntax without brackets (as documented)!
