### ISSUE TITLE
ruby kdbtools: compilation fails

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1421]
Possibly since #1346 the ruby bindings do not compile anymore:

```
[ 71%] Swig source
/home/markus/Projekte/Elektra/current/src/bindings/swig/ruby/kdbtools.i:42: Error: Unable to find 'std_shared_ptr.i'
src/bindings/swig/ruby/CMakeFiles/swig-ruby-tools.dir/build.make:53: recipe for target 'src/bindings/swig/ruby/kdbtoolsRUBY_wrap.cxx' failed
make[2]: *** [src/bindings/swig/ruby/kdbtoolsRUBY_wrap.cxx] Error 1
CMakeFiles/Makefile2:14664: recipe for target 'src/bindings/swig/ruby/CMakeFiles/swig-ruby-tools.dir/all' failed
make[1]: *** [src/bindings/swig/ruby/CMakeFiles/swig-ruby-tools.dir/all] Error 2
Makefile:147: recipe for target 'all' failed
make: *** [all] Error 2
```

Workaround: exclude swig_ruby from BINDINGS.

Btw. Does it make sense to split ruby and rubytools bindings?

## System

- Debian Jessie
- ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
- SWIG Version 3.0.2

**Comment by BernhardDenner** [comment]
Seems to be a too old swig Version. I'll check the minimal version again

**Comment by markus2330** [comment]
Thanks, would be great if you can support the Jessie version.

**Comment by BernhardDenner** [comment]
Oh, shared pointer support for Ruby was added with 3.0.8. I think this is the minimum version we can support. So for Debian we sill need to build Swig from source before building the Ruby bindings.
I'll add a check in the CMakeLists.txt for that later.

**Comment by markus2330** [comment]
Thanks! Okay, so let us add the check (please also put a comment why it is needed).

Can you separate the libtools and the other part? (Only libtools needs 3.0.8?)

Maybe we can backport swig and libgit2 for jessie. (libgit2 is also too old in Jessie for gitresolver to work.)

**Comment by BernhardDenner** [comment]
was fixed by https://github.com/ElektraInitiative/libelektra/commit/fc56af6dc53aee1163ef4cf0d2906d306d82d381 and https://github.com/ElektraInitiative/libelektra/commit/9bb035bc1678c556f5c2f8aa639a866d11b106aa

So closing this issue.
