### ISSUE TITLE
multiresolver fixes

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1425]
- [x] update infos/status
- [x] globbing for user
- [x] file name of nearest file should stay in parent key (for `kdb file`)

**Comment by tom-wa** [comment]
can we also allow absolute paths for user mounts ? 
the real problem is that (after glob) the multiresolver ends up with absolute pathnames for every file and i have to check what namespace, home paths (xdg, normal, etc..) are used and remove that part of the path, only to have `resolver` doing the same checks and assemble the path together again.

**Comment by markus2330** [comment]
> can we also allow absolute paths for user mounts ?

They are allowed. But they are nevertheless relative to the home directory. Why not simply adding your path to what you get from the root-resolver, then you have working paths you can pass to glob?

Btw. it was your suggestion to make namespaces even more strict than they currently are ;)

> [..] only to have resolver doing the same checks and assemble the path together again.

Yes, sounds awkward. Isn't it enough to remember a dirNameSkip, i.e. how many characters to ignore from the root name?

**Comment by tom-wa** [comment]
> root-resolver

i think thats my issue, i didn't use the `resolver` to resolve the root path, just all child-backends. i'll try to adapt the functions from `resolver/filename.c`

>Btw. it was your suggestion to make namespaces even more strict than they currently are ;)

i didn't want to make them less strict, i just wanted to have absolute paths with the same restrictions, but you are right, it's a bad idea

**Comment by markus2330** [comment]
>  i'll try to adapt the functions from resolver/filename.c

What do you mean with adapt? Please do not copy functions from there. Why not call `kdbGet`?

**Comment by tom-wa** [comment]
>file name of nearest file should stay in parent key (for kdb file)

wouldn't mounted directory be an better option ? 
the nearest file could be several directories deeper and for glob it seems to be locale (`LC_COLLATE`) dependent

**Comment by markus2330** [comment]
> wouldn't mounted directory be an better option?

Yes, much better option. I think this is what I meant (thinking of directories are files, too).

So if you have a multifile mount in `/m`:
```
kdb file /m # returns directory of multifile mount
kdb file /m/k # returns the file which `k` is responsible for
```

**Comment by tom-wa** [comment]
>`kdb file /m/k # returns the file which `k` is responsible for`

doesn't the resolver plugin only see `/m` even if it's called with `/m/k` ? or am i missing something ? i'd like to use the `/k` part for optimizations anyway (ignore all other child-backends) but couldn't figure out how the get the key it's called with.

**Comment by markus2330** [comment]
You are right, the parent key name is set to the mountpoint before being passed to the plugins. Sorry for not pointing that out from the beginning. Implementing the special case to pass the full parentKey would break storage plugins but we could store the original key name as meta data. But let us do this in separate PRs, for a first version getting the directory is okay.
