### ISSUE TITLE
WebUI: FirefoxESR

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1427]
For both @tom-wa and me, the Web UI does not allow login using the nginx auth. Which chromium it works (but #1424 applies).

Affected seems to be Mozilla FirefoxESR  45.7.0

**Comment by reox** [comment]
I have installed a real certificate - maybe that helps?

**Comment by markus2330** [comment]
Thank you, the certificate is working great, you can deactivate http!

But the login still does not work on FirefoxESR.
In the network tab it simply shows that it issued an request, without answer. (It says it took 0ms)

In the Browser Console it says:
```
1490090956898	addons.productaddons	ERROR	Request failed certificate checks: [Exception... "SSL is required and URI scheme is not https."  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 145"  data: no] Log.jsm:751:0
1490090956899	Toolkit.GMP	ERROR	GMPInstallManager.simpleCheckAndInstall Could not check for addons: [Exception... "SSL is required and URI scheme is not https."  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 145"  data: no] Stack trace: checkCert()@resource://gre/modules/CertUtils.jsm:145 < downloadXML/</success()@resource://gre/modules/addons/ProductAddonChecker.jsm:113 Log.jsm:751:0
```

But this might be unrelated. (Most likely it is unrelated)

**Comment by markus2330** [comment]
On other pages such as reox.at I get the challenge without any issues.

Btw. I even tried to remove the cache, the issue still prevails.

Did you try to reproduce with Firefox ESR?

**Comment by reox** [comment]
firefox-esr seems to do real crazy stuff... i see the SSL handshake in wireshark but it never reaches the nginx log.
I restricted the ciphers and used only tls1.2 and it seems to work now...

**Comment by markus2330** [comment]
Thank you!
