### ISSUE TITLE
Improve performance of config conversion

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1462]
Performance-wise it seems like we did something wrong in the setup and the restbackend writes to local disc when converting snippets (instead of only writing into tmpfs).

At which places do we need to mount tmpfs to avoid this problem?

**Comment by markus2330** [comment]
The relevant part is: `boost::filesystem::path tmpPath = boost::filesystem::temp_directory_path () / boost::filesystem::unique_path ();`

**Comment by Namoshek** [comment]
It should be enough to mount a `tmpfs` for the `/tmp` directory, but I'm don't feel confident enough to do this on my own (and it probably needs a reboot anyway).

Explanation:
`boost::filesystem::temp_directory_path()` will actually take the first path it finds in one of the following environment variables: `TMPDIR`, `TMP`, `TEMP`, `TEMPDIR`. If none is present, it falls back to `/tmp`.

**Comment by markus2330** [comment]
Yes, clearly the folder /tmp is used:  35754 files are lying there. Seems like the tmpfiles from the build spammed the folder. In a directory with such many files it is not a surprise that it gets so slow, a simple `ls` takes 12sec (cached), which is about the time the snippet conversion takes.

I mounted a tmpfs. It now works much faster.

I will also prepare a patch to clean the /tmp folder after every build.
