### ISSUE TITLE
Error severity level "normal"

### ISSUE THREAD

**Issue by domhof** [ElektraInitiative/libelektra#1473]
In src/error/specification several severity level are used: fatal, error, normal, warning.

What is the difference between error and normal?

**Comment by markus2330** [comment]
Thanks for asking the question!

Currently everything which is not a warning, is an error. So if you clean up, you can fix fatal and normal to be an error.

**Comment by domhof** [comment]
Thanks for the info! I fixed "normal" to be an "error". However I'm not sure if we should do the same to "fatal". In the API we have now "warning", "error" and "fatal" so we can map them 1:1 this way.

**Comment by markus2330** [comment]
I think we should have very little user-visible errors and map all our internal errors to these few.

Basically the user is only interested in:

- validation errors (meaning that the user needs to change the value to succeed)
- conflicts (retrying might be useful, but might also be harmful and cause emergent misbehavior)
- temporary errors (retrying might be useful, e.g. out of disk space, NFS timeouts,..)
- permanent errors (installation broken, admin needs to fix something to make it work again)
- (did I miss something?)

**Comment by domhof** [comment]
I like the idea of having a limited amount of user-visible errors. I could imagine, however, that a mapping can easily get cumbersome. Can you elaborate on how this mapping could be done?

**Comment by markus2330** [comment]
The field `class` and `extends` already were introduced to achieve something like that. I think we can even remove the `extends` and only have 3-4 classes.

To avoid missing classes in future we can change `exporterrors` to abort if `class` is missing.

**Comment by domhof** [comment]
Currently the specification contains the following classes:

FailedLoadModuleError (2 occurrences in specification with similar description: "could not load module...")
FailedResolveSymbolError (2 occurrences in specification with similar description: "could not get pointer to factory...")
NoDefaultBackendError (1 occurrence with description "failed to open default backend")

Is this really all we need and how can we map them (all "permanent errors")? At least for number:30 (conflict) we would need another class.

Who introduced `class` and what was it meant to represent exactly?

**Comment by markus2330** [comment]
You can remove these 3 classes that occur in the files, they were never used.

Instead introduce the errors as mentioned above:
- **validation** errors (meaning that the user needs to change the value to succeed)
- **conflict**s (retrying might be useful, but might also be harmful and cause emergent misbehavior)
- **temporary** errors (retrying might be useful, e.g. out of disk space, NFS timeouts,..)
- **permanent** errors (installation broken, admin needs to fix something to make it work again)

(I marked a word in bold for its potential class name).

> Who introduced class and what was it meant to represent exactly?

I introduced it to have code-generation with inheritance. It was only an idea, and was never realized. The concept we discuss in this issue is barely related, but the name `class` fits well.

**Comment by markus2330** [comment]
For clarification: The classes do *not* make the severity obsolete. The severity stays as is, and only the errors (which is one of the two severities) get assigned to a class.

**Comment by domhof** [comment]
> For clarification: The classes do not make the severity obsolete. The severity stays as is, and only the errors (which is one of the two severities) get assigned to a class.

In other words, we only need an extra attribute "class" in ElektraError together with a getter "elektraErrorClass(ElektraError * error).

**Comment by markus2330** [comment]
I was talking about the specification. In the user API "warning" might be actually one enum among the errors. Separating severity and class in two getters might be overkill here. They are something which can safely be ignored (if it is not possible to display them to the user).

**Comment by domhof** [comment]
So should the user of the API be able to see which class an error is in or not? From what you write it is not clear to me what you actually want to archive and how this should influence the API.

**Comment by markus2330** [comment]
Yes, of course the user should see which class an error has.

Changes to make:
- add class (validation, conflict, temporary, permanent) to every error in the specification
- give user an getter for an enum {validation, conflict, temporary, permanent, warning}

However, it is not so important to have getters for all other details of the error message, maybe a short+long error text is an easier-to-use interface? (having getters for ElektraErrorCode  elektraErrorDescription ElektraErrorSeverity ElektraErrorGroup ElektraErrorModule sounds like overkill for me.)

**Comment by markus2330** [comment]
@Piankero here are some discussions about the error concept.

**Comment by Piankero** [comment]
Should I add it to `doc/decisions/error_codes.md` in the `# Decision` section or does it deserve its own design decision?

**Comment by markus2330** [comment]
It would be best if we had some entry point for reading about errors (ideally a tutorial). From this tutorial you can link the design decisions at the appropriate times. (Or even move some text from the design decisions to the tutorial.)

So it depends on the structure of this tutorial if a separated decision is better. In case of doubt, make it separate. Too long decisions are not easy to read.

**Comment by Piankero** [comment]
This issue is unrelated to visible error messages.
As discussed in the Elektra meeting I may unassign myself.

**Comment by markus2330** [comment]
@Piankero this would be a quite simple Java task.
