### ISSUE TITLE
mount with recommended plugins error

### ISSUE THREAD

**Issue by BernhardDenner** [ElektraInitiative/libelektra#1480]
When mounting with recommended plugins while explicitly specifying one of the recommended plugins may lead to an plugin placement error.

E.g:
```sh
kdb mount -W /etc/hosts system/network/hosts hosts network
#> The command kdb mount terminated unsuccessfully with the info:
#> Ordering Violation!
#> You tried to add a plugin which requests another plugin to be positioned first.
#> Please position the other plugin first and try again.Please report the issue at https://issues.libelektra.org/
```
expected behaviour:
Since I already specified the 'network' plugin, the recommended plugin feature shouldn't add it again. Thus mounting is done only with one 'network' plugin instance.

**Comment by markus2330** [comment]
Thank you for reporting the issue!

I can confirm the problem.

For needed plugins the BackendBuilder::removeProvided (line 253) takes care of removing plugins already explicit listed, we need something similar for recommended plugins.

Do you need further help for this issue?

**Comment by BernhardDenner** [comment]
From the 'puppet-libelektra' module point of view, the issue is now solved. I'm now checking which plugins would actually be added by other plugins and therefore do only explicitly use a minimal set of plugins. This avoids this problem. 
The reason why I've chosen to solve the problem in kdbmount itself, is that I require a similar logic for checking if the currently mounted plugins are actually used because of dependencies or because they were added explicetly. Otherwise, my kdmount plugin detects "too many" mounted plugins (if add_recommenden_plugins = true), and does a remount. Now with the latest kdbmount fix, this remounting is avoided. 

I'll have a look later, if there is more time for it ;)
