### ISSUE TITLE
Split source location of elektra libs

### ISSUE THREAD

**Issue by domhof** [ElektraInitiative/libelektra#1484]
Currently the KDB source is located in libs/elektra and the high level API is in libs/highlevel. Since we discussed in another issue that we could name the high level API simply "Elektra", there is a conflict regarding the location. Can we move libs/elektra (KDB) to libs/kdb and libs/highlevel to libs/elektra?

There are also some other functions with the prefix "elektra" (e.g. in "ease"). Should we rename them?

**Comment by domhof** [comment]
libelektra-elektra (if we name the HL API "Elektra") might be a bit confusing. How about if we name it "Elektra API" and use `libelektra-api` for the compiled lib and `libs/api` for the source code. We still can split up elektra into core, kdb, etc. at a later point.

**Comment by markus2330** [comment]
For me a library called `api` is even more confusing, every library has an api.

libelektra-kdb if you work with `KDB` and libelektra-elektra if you want the high-level `Elektra` isn't too bad?

Btw. this and the error changes please in a separate PR. For #1412 please only add a tutorial and change whatever the review reveals (I hope I can do it today).

**Comment by domhof** [comment]
> libelektra-kdb if you work with KDB and libelektra-elektra if you want the high-level Elektra isn't too bad?

No, as long as the directory structure reflects the names (`libs/core`, `libs/kdb`, `libs/elektra`, ...) it's not bad at all. ;-)

**Comment by markus2330** [comment]
Okay, then lets reopen the issue for splitting up the elektra folder.
