### ISSUE TITLE
The Order Preserving Minimal Perfect Hash Map Build Integration

### ISSUE THREAD

**Issue by KurtMi** [ElektraInitiative/libelektra#1487]
The Order Preserving Minimal Perfect Hash Map (OPMPHM) is a very special kind of hash map. In Order to make a KeySet ready for lookups a build process is need. This build process in mainly divided in two steps. This Issue describes the needed tasks to Integrate the OPMPHM build process in Elektra.

### Init
- [x] add ratio param
- [x] add ksLookup flag for explicit hash build
- [x] add random function
- [x] add hash function
- [x] add graph debug tool graphviz as soft dept
- [x] test cases
- [x] try to find a more platform independent seed init function
- [x] fix  endian at hashfunction

### Build
- [x] add points here!

**Comment by KurtMi** [comment]
@mpranj the final OPMPHM will look like:
```
#define OPMPHMTUPLE 5
typedef struct
{
	size_t * transsitions[OPMPHMTUPLE];
	size_t size[OPMPHMTUPLE];
	uint32_t opmphmHashFunctionSeeds[OPMPHMTUPLE]; 
} Opmphm;
```
The constant OPMPHMTUPLE is fixed after compiling.
The types of the first two members will maybe change.

**Comment by mpranj** [comment]
@KurtMi thanks! I will definitely have to adapt the mmapstorage/cache once your implementation is merged, but it shouldn't be a problem.
In fact, as long as the size is known it will be fine, no matter what we have to store.

**Comment by KurtMi** [comment]
> In fact, as long as the size is known it will be fine, no matter what we have to store.

The:
```
size_t size[OPMPHMTUPLE];
```
is not the size in bytes and after having a closer look the size is not necessarily needed in the struct. Is there a way to get the size of a malloced pointer without saving it? When not I could change it to the actual size in bytes.

**Comment by mpranj** [comment]
>  Is there a way to get the size of a malloced pointer without saving it?

No. Usually you need remember the size somehow, like in Key and KeySet.

If you have the number of elements and the size of one element, then you know the size of the allocation anyway.

**Comment by KurtMi** [comment]
#1730 closes this issue.
