### ISSUE TITLE
Crypto: improve plugin performance

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#1493]
I discovered a design flaw in the crypto plugin while debugging the benchmark  `src/libs/tools/benchmarks/benchmark_crypto_comparison.cpp`.

We fork into the gpg process for every key in a keyset in both methods: kdb get and kdb set. This makes the plugin unusable for larger keysets. Encrypting 100 keys takes between 3 and 7 seconds!

Instead we should derive the cryptographic key and the initialization vector only once for every keyset that is encrypted/decrypted.

**Comment by markus2330** [comment]
Thank you for reporting the issue!

Is there no simple way to keep the process open and keep sending data to it?

**Comment by petermax2** [comment]
> Is there no simple way to keep the process open and keep sending data to it?

As far as I can remember gpg quits after the request has been processed, but I will look into it anyway.

**Comment by petermax2** [comment]
> Is there no simple way to keep the process open and keep sending data to it?

Luckily this is not necessary. It is enough to pull the `fork()` into GPG a level up. Now only one GPG call takes place for the whole `KeySet` during `kdb get` and `kdb set`.

**Comment by markus2330** [comment]
I do not think we should over-optimize it: The idea of this feature is to encrypt single keys, not everything. (For everything, `fcrypt` is the better solution.)  Security and usability is more important, let us better concentrate on that. Thus a case study where you also discuss the other aspects would be a really important addition to the benchmarks.

Of course, if you find a simple and secure solution to make it faster, go for it. But avoiding  PBKDF2 sounds like a redesign where security would be traded with performance.

**Comment by petermax2** [comment]
> avoiding PBKDF2 sounds like a redesign where security would be traded with performance.

I agree on that and do not have a secure alternative. Let's close the issue.
