### ISSUE TITLE
make install doesn't install kdb-gen

### ISSUE THREAD

**Issue by tom-wa** [ElektraInitiative/libelektra#1500]
as the title states no matter what, i can't get make/cmake to install kdb-gen. 
i don't get any cmake warnings, cmake states `-- Include Tool gen`, but make install ignores kdb-gen 
kdb-gen works fine after copying the files manually though

**Comment by markus2330** [comment]
Thank you for reporting the problem!

Is there no error during `make install`? You need to have python2+cheetah installed.

Is your problem maybe related to #692?

**Comment by tom-wa** [comment]
i have python2 and cheetah installed and don't get any errors during `make install`. and since kdb-gen works fine after manually copying everything i don't think i'm missing any dependencies.

**Comment by markus2330** [comment]
Have you included `gen` in `TOOLS`? Is the manpage of `kdb-gen` installed?

@domhof Can you reproduce this issue?

**Comment by markus2330** [comment]
Obsolete because of #1562
