### ISSUE TITLE
errors in kdbGet

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1511]
(this proposal is a draft)

Currently, kdbGet passes through wrong configuration settings in order to give the application any chance to correct the config. This also means that applications start up with wrong conf, which is an unwanted situation. Possible solutions:

1. Remove offending keys (and add warning)
2. Hide offending keys (and add warning)
3. Make higher-level API responsible to quit application on such problematic warnings

see also #1291

**Comment by markus2330** [comment]
https://github.com/ElektraInitiative/libelektra/blob/ecd4c997d90ad595ca36ba709da2df07e6f50282/src/plugins/ni/ni.c#L54

> @kodebach wrote: In this case [failing] is the correct option. If the file contains invalid key names, you either edited the file manually (in which case you can do that again to fix the problem) or the plugin is completely broken and actually produced the invalid key name (in which case there is no chance of fixing the key name anyway).

It could be also a corruption of some other kind, e.g. some script did a wrong change or even a hard disc failure. I wouldn't go for more than a warning, as not starting the application for a maybe irrelevant option can be a very severe problem.

Applications can always decide to exit on warnings (and normal applications probably should do that) but in some situations there might be no way to let applications start with a present error, e.g. if the error is already within `kdbOpen`, applications would not not even get the `KDB` handle.

**Comment by kodebach** [comment]
But the question is, what would the `ni` plugin return, if it encouters an invalid key name? In any case, at least this one key will be lost.

To me a warning is something that "should ideally be fixed", but "can also be safely ignored". So IMO ignoring a warning should **never** lead to data loss.

That is actually, why we need a mode were errors are ignored. Then we can properly return errors, when something really bad happend.

**Comment by markus2330** [comment]
Yes, this would basically mean we need critical and non-critical errors.

Or: we treat such things as corruption of the database and build some other tools (post 1.0) to fix such corruptions. Something like `fsck`? These tools obviously would not be able to use the API but they could use the plugin if the plugin would continue processing the configuration file even in the case of errors.

Or: we make it internally as warning, and the spec plugin turns it to an error if the warning is related to a specified key. If the name is invalid, it is not such a case anyway. This could be very problematic if the erroneous key is actually a typo from a name of a specified key. And this approach is probably also a too big burden for the spec plugin.

Anyway: We definitely need a consistent error concept. See also #2726.
