### ISSUE TITLE
transient error in testcpp_contextual_thread

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1519]
@sanssecours wrote in #1516:
> Looks like there was a [transient error](https://travis-ci.org/ElektraInitiative/libelektra/jobs/244306508#L960-L972) in `testcpp_contextual_thread`.

`valgrind --tool=helgrind bin/testcpp_contextual_thread`

**Comment by sanssecours** [comment]
It seems the test failed [once again](https://travis-ci.org/ElektraInitiative/libelektra/jobs/251448312#L2256-L2267) 😢.

**Comment by markus2330** [comment]
Surprising that this is possible, the difference in waiting time is huge. I could not reproduce it even if I have the same waiting time for both threads. Only when I give the thread which should be faster more waiting time, the test case fails (as expected):

```
diff --git a/src/bindings/cpp/tests/testcpp_contextual_thread.cpp b/src/bindings/cpp/tests/testcpp_contextual_thread.cpp
index 3244653..9fe3c93 100644
--- a/src/bindings/cpp/tests/testcpp_contextual_thread.cpp
+++ b/src/bindings/cpp/tests/testcpp_contextual_thread.cpp
@@ -136,7 +136,7 @@ void activate1 (Coordinator & gc, KeySet & ks)
        c1.activate<Activate> ();
        ASSERT_TRUE (g_toggle);
        ASSERT_EQ (v1, 22);
-       std::this_thread::sleep_for (std::chrono::milliseconds (100));
+       std::this_thread::sleep_for (std::chrono::milliseconds (1));
        ASSERT_EQ (v1, 22);
        c1.deactivate<Activate> ();
        ASSERT_FALSE (g_toggle);
@@ -161,7 +161,7 @@ TEST (test_contextual_thread, activate)
 
        std::thread t1 (activate1, std::ref (gc), std::ref (ks));
        ASSERT_EQ (v, 10);
-       std::this_thread::sleep_for (std::chrono::milliseconds (50));
+       std::this_thread::sleep_for (std::chrono::milliseconds (2));
        ASSERT_TRUE (g_toggle);
        c.syncLayers ();
        ASSERT_EQ (v, 22);
```

Rewriting the test case to mutexes does not make much sense (there are already tests which test sequential execution). I'll increase the waiting times + disable the test for apple.

**Comment by mpranj** [comment]
I've just experienced this with a current PR.

```

 28/232 Test  #22: testcpp_contextual_thread .....................Child aborted***Exception:   1.26 sec

Running main() from /opt/gtest/googletest/src/gtest_main.cc

[==========] Running 8 tests from 1 test case.

[----------] Global test environment set-up.

[----------] 8 tests from test_contextual_thread

[ RUN      ] test_contextual_thread.instanciation

[       OK ] test_contextual_thread.instanciation (172 ms)

[ RUN      ] test_contextual_thread.activate

/home/jenkins/workspace/libelektra_PR-3291@2/src/bindings/cpp/tests/testcpp_contextual_thread.cpp:170: Failure

Value of: g_toggle

  Actual: false

Expected: true

terminate called without an active exception
```

:confused:

**Comment by markus2330** [comment]
Thank you for reporting. Yes, this transient error, together with many others (#2439) are still not fixed. Our current fix is to run failing tests again.

Can you check if this test really failed twice in a row? We could retry 2 times (3 in total).

**Comment by mpranj** [comment]
> Can you check if this test really failed twice in a row?

No. It seems that the Jenkinsfile calls `ctest` directly instead of the workarount in `run_all`.
https://github.com/ElektraInitiative/libelektra/blob/0eb2a81e333b8aca6e54431557e7ee6cb8fd86c1/scripts/jenkins/Jenkinsfile#L1312-L1314

Maybe we add the same workaround to the Jenkinsfile so we don't waste too much time on this problem.

**Comment by markus2330** [comment]
I think we can simply change the Jenkinsfile to run `make tests` as all the logic for test exclusion is only about temporary errors (as far as I see).

**Comment by markus2330** [comment]
Doesn't fail anymore and the error itself is not very important.
