### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1523]
For example: https://www.libelektra.org/ftp/papers/kps2015sharing.pdf

**Comment by BernhardDenner** [comment]
Sorry, but I can't find the mentioned file any where on the old server. Are you sure it was really hosted on this site?

**Comment by markus2330** [comment]
No, I am not sure, maybe it was a redirect to the files on http://markus-raab.org/ftp/papers/? Should I change the links or can you do a redirect?

Btw. `pulls.libelektra.org` would be great, too ;) (see #1526)
