### ISSUE TITLE
Crypto: Switch from CBC to GCM mode of operation

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#1524]
# Intention

Exchange the CBC mode of operation with the Galois Counter Mode (GCM) which is supported in all of our libraries:

- OpenSSL
- Botan
- gcrypt

I propose this change because GCM integrates an integrity check of the data during encryption and decryption. The integrated HMAC eliminates the need for explicitly signing values in the plugin.

Since the plugin status contains `experimental unfinished discouraged` (see README.md) we can safely break the encryption schema, right? Because switching mode of operation makes it impossible to retrieve existing data, which has been encrypted by the plugin.

It should not take long to switch the mode. I estimate a very low effort with a high benefit for Elektra.

What do you think about this change? 

EDIT: Of course I would implement the switch by myself, if it is ok for everyone.

**Comment by markus2330** [comment]
From the plugin status point of view I do not see any barrier for any breaking change.

But I do not know how it fits in the big picture: signing is not only about integrity (but also identity of who signed). So maybe it is better to have some real-world use case (case study) first and then decide if GCM makes sense in this context. Is there a real danger that a bit flip can lead to valid configuration setting an attacker wants?

And another question to consider: Would GCM be interesting performance wise (to compare it with the current implementation)?

In any case: If the change is easy and brings benefits for users, please do it. But if it is time consuming (and reading 3x docu about security sensitive material sounds time consuming), please first consider the big picture (ideally write something up).

**Comment by petermax2** [comment]
This proposal is not very promising and I don't want to follow up on this idea.
