### ISSUE TITLE
leftovers libelektra.org migration

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1526]
- [x] #1525 (convert) snippet service down 
- [ ] #1523 missing files
- [ ] ssh copy artifacts does not work (see #1502, maybe also for build-doc?)
- [x] homepage build agent down?
- [ ] make jenkins build jobs config part of puppet config
- [ ] docu for how to deploy puppet from scratch and on updates
- [x] #1541
- [ ] letsencrypt automation
- [ ] icc compiler missing: https://build.libelektra.org/jenkins/job/elektra-icc/946/console

**Comment by tr37ion** [comment]
Unfortunately, I'm not using Apache webserver. Though, from reading Apache sources, it should be something like this

```config
Header set X-XSS-Protection “1; mode=block”
Header always append X-Frame-Options DENY
Header set X-Content-Type-Options nosniff
```
## CSR Policy

If the previous three header work (verify with the scanner I listed in #1505) you can add a CSR policy, to prevent cross-site-attacks. AFAIK the website is not using any external CDN content, then this should be a good working policy. 

To test it first, use

`Header set Content-Security-Policy-Report-Only "default-src 'self';"`

If that works fine, replace that line with

`Header set Content-Security-Policy "default-src 'self';"`

In short, this header ensures that browsers are only allowed to load content form the website's default URL itself.

## HSTS

Additionally, you can add a HSTS header if you like. Adding this means that you have to redirect all HTTP requests to HTTPS by default! If you don't want this, just skip this section. It only tells the visitor's browser that your site will only allow HTTPS connections for the coming 31536000 seconds from the first time visiting your page.

```note
Prior to implementing this header, you must ensure all your website page is accessible over HTTPS else your browser blocks your site from loading for max31536000 seconds. If unsure, you can start with a small `max_Age=300` (5 minutes) and then increase the number if scans are working.*
```

```config
Header set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
```

In conclusion, if you add the first four headers + HSTS the website should be fine. Later you can always be more restrictive with your CSR policy, but for now this should be fine :ok_hand:

I hope this helps a bit.

## :fire: HPKP
**Optionally, you can add a HPKP header, but attention, this is a tricky task and in case of misconfiguration all your won't be able to access your website anymore. I wouldn't recommend adding it for *libelektra.org* now. If you are risk-conscious you could do it, but please read into the topic before! --- I warned you :stuck_out_tongue_winking_eye:**

**Comment by markus2330** [comment]
@BernhardDenner I added a request for a redirection of puppet.libelektra.org (to your project). Ideally, the tutorial/docu you are writing should contain how to create such aliases.

**Comment by markus2330** [comment]
@BernhardDenner I added a request for one more redirection, a tutorial would be great :-)
