### ISSUE TITLE
kdb-gen: fail if no default supplied

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1529]
Applications are only guaranteed to get a key if they either require the key or provide an default.

The code generator should emit a warning if settings are neither, and do not emit a tag then. (Later we could provide some ways for `optional` keys, but we do not need it now.)

We should however test the specification with users.

**Comment by markus2330** [comment]
I simplified the task: We should always have a default. The reason for this is that the guarantee for `require` is misleading. While it can check for all required keys at startup, we would need to recheck required keys also for every configuration change. This means that the application might fail at run-time, which is something we definitely do not want.

The problem occurs because of different contexts. For example, a user might have a key present in `dir:/required/key`. Then she can easily remove `user:/required/key` and everything would still validate nicely because the required key is there (in dir:). If an application was started in a different folder, where `dir:/required/key` never was present and `user:/required/key` suddenly is missing, we would have a run-time fault when the application tries to reread the configuration settings. The same argumentation also applies for system vs. user, so you are never safe. Even requiring every key to be present in system is only partial: then a user cannot install an application, and `namespace` might exclude system.

Thus lcdproc has defaults for every key anyway the decision will not effect the lcdproc migration.

I know that there are not always sensible defaults (e.g. the language of an application). Nevertheless, it is better to have a value that is somehow arguable (and can be introspected, so it is no surprise that it is there) than a run-time crash.

I do not propose to remove `require`, but we have to admit that the `require` (we have) has nothing to do with guarantees for applications at run-time.

**Comment by kodebach** [comment]
The new `kdb gen` requires that each key either has a `default` or is marked `require`.
