### ISSUE TITLE
Create Build Job with ENABLE_OPTIMIZATIONS set to ON

### ISSUE THREAD

**Issue by KurtMi** [ElektraInitiative/libelektra#1535]
In order to integrate the OPMPHM in elektra the cmake flag `ENABLE_OPTIMIZATIONS` will be turned off, thus a build job where `ENABLE_OPTIMIZATIONS` is set to on is needed.

**Comment by markus2330** [comment]
I forgot to give you account data today, please remind me next meeting.

**Comment by markus2330** [comment]
Done! See https://build.libelektra.org/jenkins/job/elektra-gcc-configure-debian-optimizations/

**Comment by markus2330** [comment]
Done! See https://build.libelektra.org/jenkins/job/elektra-gcc-configure-debian-optimizations/
