### ISSUE TITLE
Wrong redirect

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1541]
# Describe what you wanted to do

Visit the page https://libelektra.org/plugins/ni

# Describe what you expected

That I see https://www.libelektra.org/plugins/ni

# Describe what actually happened

Got a "Server not found" http://www.libelektra.orgplugins/ni

**Comment by Namoshek** [comment]
From the redirect speed, this is most likely an issue with the apache configuration.

**Comment by markus2330** [comment]
Thanks for the hint! Yes, @BernhardDenner reapplied your apache configs using Puppet. Might be a copy&paste or something...

**Comment by BernhardDenner** [comment]
fixed by https://github.com/ElektraInitiative/buildserver/commit/cf2081e160a02446a86bab1de49ee35e43371cd1.
