### ISSUE TITLE
fcrypt: improvements

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#1543]
Improve error handling for the following calls:

- [x] `close()`
- [x] `unlink()`

Other improvements

- [x] textmode - in textmode fcrypt uses `--armor` and `--clearsign`. In non-textmode the regular binary output is used as usual.

**Comment by markus2330** [comment]
Thank you for reporting! I tagged it as low-priority. Its more a reminder to do a code review: Maybe there are some more important places where error handling was forgotten.

As discussed your focus should be benchmarks+case study+writing.

Btw. wouldn't it be nicer to use `--clearsign --armor` so that the content of the config file is visible as clear text?

**Comment by petermax2** [comment]
> Btw. wouldn't it be nicer to use --clearsign --armor so that the content of the config file is visible as clear text?

absolutely!

**Comment by petermax2** [comment]
Just as a note: using --clearsign` is quite difficult because `gpg -d` suppresses the output of `\0` when processing "clear-signed" files. This leads to length mismatches in the dump plugin and corrupted key sets (the new-line "\n" is then part of the key value and "keyEnd" is ommited, so the key is not appended to the key set).

I will post my solution to this problem here, just in case anyone else stumbles upon this problem.

**Comment by petermax2** [comment]
So far I found `--no-textmode` which leaves `0x00` characters in the output during the clear-sign process. However `-d` still does not write `0x00`.

**Comment by markus2330** [comment]
Thank you for looking into it! What about having a plugin configuration to choose if it is text mode. (Text by default.) In dump we could add the plugin configuration (using its contract, as for example, done in the hosts plugin) to let fcrypt automatically switch to non-text.

**Comment by petermax2** [comment]
> What about having a plugin configuration to choose if it is text mode

Sounds good to me and should not be too much effort.
