### ISSUE TITLE
C functions with no paramter

### ISSUE THREAD

**Issue by KurtMi** [ElektraInitiative/libelektra#1545]
It is possible to compile and run the following code without any warning and error:
```
void foo ()
{

}
int main ()
{
    foo (3);
}
```
Changing the whole C code is not so nice, a compiler flag would be perfect.

**Comment by markus2330** [comment]
Thank you for reporting the problem!

The API seems to be not affected.

We likely need to fix these cases, I am afraid there is no way to redefine the C-standard for us. But it seems like with `-Wmissing-declarations` and `-Wmissing-prototypes` the compiler will tell us all cases where it is needed. Unfortunately, it also means that we need to add a prototype everywhere. I could not find an option which does exactly what we need (only warning these cases) without forcing to write prototypes everywhere.

Btw. `-fno-allow-parameterless-variadic-functions` seems to be default and not fix the problem.

**Comment by markus2330** [comment]
Just found the answer: `-Wstrict-prototypes`.

@KurtMi can you fix the violations of your code?
@e1528532 can you fix the leftovers after Kurt?

Just comment in the line added in 1b9577ca56ab63cd93dd9e1cc9355981330dc9db to get the warnings.

**Comment by KurtMi** [comment]
#1549 should fix my code.

**Comment by markus2330** [comment]
@e1528532 can you fix all occurrences of `()` with `(void)`? Uncommenting 4e5c57c should point you to them.

**Comment by e1528532** [comment]
should be done in #1552
