### ISSUE TITLE
CMake: Fix Deprecated Code and Warnings

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1555]
# Steps to Reproduce the Problem

1. Clone the repository
2. Run CMake (Version `3.9.0` or later)

# Expected Result

CMake creates the build system without any warnings.

# Actual Result

CMake prints a warning about policy CMP0026,

```
CMake Deprecation Warning at CMakeLists.txt:16 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
```

about [policy CMP0053](https://travis-ci.org/ElektraInitiative/libelektra/jobs/257825569#L1410-L1455), if we include the Qt GUI:

```
-- Include Tool qt-gui
CMake Warning (dev) at /usr/local/opt/qt5/lib/cmake/Qt5/Qt5ModuleLocation.cmake:4 (set):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
  For input:
    '${_qt5_install_prefix}/Qt5@module@/Qt5@module@Config.cmake'
  the old evaluation rules produce:
    '/usr/local/opt/qt5/lib/cmake/Qt5/Qt5Config.cmake'
  but the new evaluation rules produce:
    '/usr/local/opt/qt5/lib/cmake/Qt5@module@/Qt5@module@Config.cmake'
  Using the old result for compatibility since the policy is not set.
Call Stack (most recent call first):
  /usr/local/opt/qt5/lib/cmake/Qt5/Qt5Config.cmake:25 (include)
  src/tools/qt-gui/CMakeLists.txt:7 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
CMake Warning (dev) at /usr/local/opt/qt5/lib/cmake/Qt5/Qt5ModuleLocation.cmake:4 (set):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
  For input:
    '${_qt5_install_prefix}/Qt5@module@/Qt5@module@Config.cmake'
  the old evaluation rules produce:
    '/usr/local/opt/qt5/lib/cmake/Qt5/Qt5Config.cmake'
  but the new evaluation rules produce:
    '/usr/local/opt/qt5/lib/cmake/Qt5@module@/Qt5@module@Config.cmake'
  Using the old result for compatibility since the policy is not set.
Call Stack (most recent call first):
  /usr/local/opt/qt5/lib/cmake/Qt5/Qt5Config.cmake:25 (include)
  src/tools/qt-gui/CMakeLists.txt:8 (find_package)
```

, and about `SWIG_ADD_MODULE` in the CMake code of the [Python 2 bindings](https://travis-ci.org/ElektraInitiative/libelektra/jobs/257825569#L1364-L1368):

```
CMake Deprecation Warning at /usr/local/Cellar/cmake/3.8.2/share/cmake/Modules/UseSWIG.cmake:226 (message):
  SWIG_ADD_MODULE is deprecated.  Use SWIG_ADD_LIBRARY instead.
Call Stack (most recent call first):
  src/bindings/swig/python2/CMakeLists.txt:34 (swig_add_module)
```

. CMake also prints the last warning if we include the [Python 3](https://travis-ci.org/ElektraInitiative/libelektra/jobs/257825569#L1371-L1376), [Lua](https://travis-ci.org/ElektraInitiative/libelektra/jobs/257825569#L1379-L1383) or [Ruby](https://travis-ci.org/ElektraInitiative/libelektra/jobs/257825569#L1386-L1397) bindings.

# System Information

- Elektra Version: master
- CMake: 3.9.0
- OS: macOS 10.12.6

**Comment by markus2330** [comment]
Thank you for reporting! Seems like you have a newer version of CMake.

Is setting the policies to the OLD behavior viable or did it unveil bugs we have?

**Comment by sanssecours** [comment]
> Is setting the policies to the OLD behavior viable…?

I think the first warning above already answers that question properly:

>  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  **Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.**

. By the way: It Looks like the problem with Policy CMP0053 will be fixed [upstream](https://codereview.qt-project.org/#/c/185173).

**Comment by sanssecours** [comment]
PR #1559 fixes the warnings about `SWIG_ADD_MODULE`. Unfortunately updating the code for the new behavior of CMP0026 seems to be more complicated.

**Comment by sanssecours** [comment]
As far as I can tell, after commit c12ae15 there is only [one line of code](https://github.com/ElektraInitiative/libelektra/blob/master/cmake/Modules/LibAddMacros.cmake#L189) left, where we use the `LOCATION` target property. After we fix this line we can remove the setting for CMake policy 0026.

**Comment by markus2330** [comment]
> Projects should be ported to the NEW behavior and not rely on setting a policy to OLD.

Yes, of course it is always the long term goal but it also means we have to drop support for older cmake versions.

> SWIG_ADD_MODULE. Unfortunately updating the code for the new behavior of CMP0026 seems to be more complicated.

Is it done now?

> LOCATION target property

Wasn't it possible to set `${util}_EXE_LOC` to `"$<TARGET_FILE:..>"` as you fixed the other occurrences?

**Comment by sanssecours** [comment]
> Is it done now?

Yes.

> Wasn't it possible to set `${util}_EXE_LOC` to `"$<TARGET_FILE:..>"` as you fixed the other occurrences?

Yes, that worked. I had to slightly adjust the [CMake code for the Markdown Link Converter](https://github.com/sanssecours/libelektra/blob/c393b830a9d72c5f6542cdef406bc9c26d1e7300/doc/CMakeLists.txt#L66-L69) though, since this part of the code did not support generator expressions directly.
