### ISSUE TITLE
Fcrypt: store decrypted temporary files to tmpfs

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#1567]
# Proposal

## Idea

Fcrypt provides another configuration option `fcrypt/tmpdir=<path>`.
The plugin stores the temporarily decrypted GPG output to the specified path.

If no path is provided within the configuration, fcrypt will automatically mount and unmount a `tmpfs` as required.

## Implications

1. The risk of leaking decrypted data is reduced.
2. Thus it would be reasonable to remove the tags: `experimental unfinished discouraged`

## Estimated amount of work

Reasonable.

## Downsides

- Does not work on Windows

## Notes

- An example of mounting `tmpfs` can be found [here](https://gist.github.com/gcmurphy/c4c5222075d8e501d7d1).
- Mounting `tmpfs` is required at `kdb get` / `pregetstorage`
- Unmounting `tmpfs` is required at `kdb get` / `postgetstorage`

**Comment by markus2330** [comment]
Thanks for the proposal! Using mount(2) is not a good idea thus it needs root privileges (there are some alternatives like using the mount executable and changing `/etc/fstab`, but at least once you need to be root, thus I see no portable way how to fulfill it in a user-friendly way).

I would instead suggest that we should mention such risks in the docu and propose counter-measures. (Like mounting /tmp on tmpfs, using /dev/shm, or using /run/shm (latter two are usually already mounted tmpfs and world-writeable, but are currently not standardized by FHS.)

You could avoid that other users can see the file if you create the file within a directory with the permissions 700, shell pseudocode:
```
mkdir -m 700 /dev/shm/<username>
touch /dev/shm/<username>/unencrypted-file
```

Another idea is to use [statfs](https://stackoverflow.com/questions/26635846/how-to-tell-if-a-file-is-on-tmpfs-given-its-path-on-linux) to check if tmpdir is used (in some standard locations) to have better chances to actually use a tmpdir. If there is no user-writable or world-writeable tmpdir available, you obviously have to either fail or use a insecure location. (such decisions are tough, I think we can use an insecure location if the docu mentions it, we could add a warning though)

> Thus it would be reasonable to remove the tags

Good idea! If you can use it in "real-world scenarios", it should be okay!

**Comment by petermax2** [comment]
As discussed in our meeting today, we add a `fcrypt/tmpdir` plugin configuration option to `fcrypt`. Furthermore we explain how to use it properly in `README.md` .

I am using this task as an implementation task.

**Comment by markus2330** [comment]
A minor implementation note: It would be great if a user can introspect which values a plugin uses by default by returning relevant information via the contract. (Similar to the resolver, e.g. `system/elektra/modules/crypto` ELEKTRA_PLUGIN_NAME `/constants/TMPDIR`)

You should also consider returning the payload version, so something like (`system/elektra/modules/crypto` ELEKTRA_PLUGIN_NAME `/constants/PAYLOAD_VERSION`). Then users can easily introspect which payload version their plugin is able to handle.

Obviously you can also return any other information relevant to the user, such as the used crypto algorithm, password length and so on...

**Comment by petermax2** [comment]
@markus2330 OK I will fix that, but this is the wrong ticket. I will open a new ticket.

**Comment by petermax2** [comment]
@markus2330  Is it better to use `constant` or `default` in the contract? I would have used something like this for `fcrypt`:

    keyNew ("system/elektra/modules/" ELEKTRA_PLUGIN_NAME "/config/default/fcrypt/tmpdir", KEY_VALUE, "/tmp", KEY_END),
