### ISSUE TITLE
Provide alternative methods for keyNew/ksNew for bindings

### ISSUE THREAD

**Issue by manuelm** [ElektraInitiative/libelektra#157]
The use of va_list in keyNew/ksNew is troublesome for all bindings as variable arguments are a compile time feature of the c compiler. It relies on knowing the number and types of arguments passed to the function. That's something the c compiler knows, but bindings don't.

One possible solution to this is manipulation of the stack frame using libffi. libffi + swig are known to work. However gobject introspection probably won't. No idea about java.

Another solution, which is implemented right now, is duplicating the code in the native language of the corresponding binding. However as with every code duplication this increases maintenance effort. Additional it's not possible to call all methods elektra provides. e.g. elektraKeySetName from kdbproposal is not wrapped, so providing support for KEY_{CASCADING, META, EMPTY}_NAME in any bindings is not possible right now.

A possible workaround is to only support up to X (e.g, 20) arguments and generate the needed function signatures during compile time. That's the way JNI currently support this.

The aim of this enhancement is to search, discuss and provide alternative methods the bindings can use directly.

**Comment by markus2330** [comment]
I think we can close that now. Issue resolved and merged.
