### ISSUE TITLE
crypto: add magic number in front of the crypto payload

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#1575]
As discussed in our meeting today, `crypto_*` should put a magic number in front of the actual crypto header. This will help us avoiding version conflicts in the future.

The arbitrarily chosen magic number is: `2321 6372 7970 746f 3030` which is the ASCII representation for "#!crypto00".

If you would prefer another magic number as prefix, let me know.

**Comment by petermax2** [comment]
If the magic number does not match during decryption, the key will be ignored by the `crypto` plugin, assuming that another version of the plugin will take care of it.

**Comment by markus2330** [comment]
I like `#!crypto00`! Is `00` the version? (maybe describe magic code+version as different fields)

> If the magic number does not match during decryption, the key will be ignored by the crypto plugin, assuming that another version of the plugin will take care of it.

You should give a warning if you ignore the metadata your plugin is responsible for. And the warning message should be different if:

1. the first 8 bytes are wrong (something unknown has gone wrong)
2.  the other 2 bytes `00` are wrong (which indicates that the plugin version is too old to handle this header/message)

**Comment by petermax2** [comment]
`00` is the version. OK, I will solve it like this

    #define ELEKTRA_CRYPTO_PAYLOAD_VERSION "00"
    #define ELEKTRA_CRYPTO_MAGIC_NUMBER "#!crypto" ELEKTRA_CRYPTO_PAYLOAD_VERSION
    #define ELEKTRA_CRYPTO_MAGIC_NUMBER_LEN (10)

**Comment by markus2330** [comment]
With "describe ... as different fields" I mainly refer to your thesis (and hopefully you also copy this table somewhere within the repo, or have a struct with all fields documented) and not the macros.

Btw. `ELEKTRA_CRYPTO_MAGIC_NUMBER_LEN` could easily be calculated using `sizeof (ELEKTRA_CRYPTO_MAGIC_NUMBER)`.

**Comment by petermax2** [comment]
At the moment the table only exists in the thesis. Is `README.md` the right place to put it?

**Comment by markus2330** [comment]
Its maybe too specific to be in the end user docu (or do you expect users to look at the encrypted binaries?), so better put it somewhere as source code comment(s). If you do not have a struct, the macros might be a good place after all.

**Comment by petermax2** [comment]
There is no struct, because that did not work out.

I will put the message format into a comment in `crypto.h`.
