### ISSUE TITLE
Crypto: Detection of Botan Does not Work on macOS

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1576]
# Steps to Reproduce the Problem

Build Elektra according to the steps given in [`tavis.yml`](https://github.com/ElektraInitiative/libelektra/blob/master/.travis.yml)

# Expected Result

The build system includes the plugin `crypto_botan`, since we installed `botan` via `brew install botan`.

# Actual Result

CMake [excludes the plugin](https://travis-ci.org/ElektraInitiative/libelektra/jobs/265046758#L1522) printing the following message:

```
-- Exclude Plugin crypto_botan because botan development files not found
```

. As far as I can remember the detection process for `crypto_botan` used to work on macOS in [February](https://github.com/ElektraInitiative/libelektra/pull/1384#pullrequestreview-23880661). Seems like the detection broke somewhere before we [enabled experimental](https://travis-ci.org/ElektraInitiative/libelektra/builds/220655967) plugins in the Travis build.

# System Information

- Elektra Version: master
- OS: macOS

**Comment by markus2330** [comment]
Thank you for reporting the problem!

I removed the "1.0.0" milestone to keep the number of tasks for the milestone smaller.
