### ISSUE TITLE
Setting `CMAKE_INSTALL_PREFIX` Breaks `kdb`

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1577]
# Steps to Reproduce

1. Clone the repository
2. Build and install Elektra

   ```sh
   mkdir build
   cd build
   cmake -GNinja -DCMAKE_INSTALL_PREFIX=/tmp/Elektra ..
   ninja install
   ```

3. Add the binary directory of Elektra to `PATH`

   ```sh
   set -x PATH $PATH /tmp/Elektra/bin
   ```

4. Run `kdb`

   ```sh
   kdb run_all
   ```

# Expected Result

The command `kdb` executes various tests

# Actual Result

The command prints the error messages below.

## Linux

```
kdb: error while loading shared libraries: libelektratools.so.2: cannot open shared object file: No such file or directory
```

## macOS

```
dyld: Library not loaded: @rpath/libelektratools.2.dylib
  Referenced from: /tmp/Elektra/bin/kdb
  Reason: image not found
fish: 'kdb run_all' terminated by signal SIGABRT (Abort)
```

# System Information

- Elektra Version: master

# Log Files

- [Travis – Linux](https://travis-ci.org/sanssecours/libelektra/jobs/265851610#L2205)
- [Travis – macOS](https://travis-ci.org/sanssecours/libelektra/jobs/265851607#L2744-L2747)

**Comment by markus2330** [comment]
Thank you for reporting the problem!

Seems like a regular library location problem. (libelektratools has no special treatment, it is linked against kdb in the regular way. See `ldd`.) Libraries use `LD_LIBRARY_PATH` (might be different on Mac OS X) and not `PATH`. Please try to set this variable additionally.

Alternatively, you can try to follow the Troubleshooting guide in `doc/INSTALL.md` for a permanent fix.

Please report if this did not help.

**Comment by sanssecours** [comment]
Setting `LD_LIBRARY_PATH` seems to [solve the problem](https://travis-ci.org/sanssecours/libelektra/jobs/266110587). Thank you!
