### ISSUE TITLE
crypto: put payload version information in the contract

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#1582]
I relocated @markus2330  's message from #1567 to here:

A minor implementation note: It would be great if a user can introspect which values a plugin uses by default by returning relevant information via the contract. (Similar to the resolver, e.g. `system/elektra/modules/crypto` ELEKTRA_PLUGIN_NAME `/constants/TMPDIR`)

You should also consider returning the payload version, so something like (`system/elektra/modules/crypto` ELEKTRA_PLUGIN_NAME `/constants/PAYLOAD_VERSION`). Then users can easily introspect which payload version their plugin is able to handle.

Obviously you can also return any other information relevant to the user, such as the used crypto algorithm, password length and so on...

**Comment by petermax2** [comment]
@markus2330 OK, I will put a constant in the contract of `crypto`.

**Comment by markus2330** [comment]
Sorry for not opening a new issue right away!

I thought that there would also be a constant necessary for the path resolving, too. The idea was that you can be more efficient with a single PR ;)
