### ISSUE TITLE
Linking Plugin Crypto Botan with GCC Fails on macOS

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1592]
# Steps to Reproduce

1. Install Botan and GCC via Homebrew

```sh
brew install botan
brew install gcc
brew link --overwrite gcc
```

2. Build Elektra using GCC

```sh
export CC=gcc-7
export CXX=g++-7
mkdir -p build
cd build
cmake .. -GNinja -DBINDINGS=ALL
ninja
```
# Expected Result

Building Elektra works without any problems

# Actual Result

Linking the plugin produces the following [error message](https://travis-ci.org/sanssecours/libelektra/jobs/269100889#L2338):

```
Undefined symbols for architecture x86_64:
  "Botan::get_cipher(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Botan::OctetString const&, Botan::OctetString const&, Botan::Cipher_Dir)", referenced from:
      _elektraCryptoBotanDecrypt in botan_operations.cpp.o
      _elektraCryptoBotanEncrypt in botan_operations.cpp.o
  "Botan::Pipe::read_all_as_string[abi:cxx11](unsigned long)", referenced from:
      _elektraCryptoBotanDecrypt in botan_operations.cpp.o
  "Botan::Pipe::write(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      _elektraCryptoBotanEncrypt in botan_operations.cpp.o
  "Botan::PBKDF::create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      _elektraCryptoBotanDecrypt in botan_operations.cpp.o
      _elektraCryptoBotanEncrypt in botan_operations.cpp.o
  "Botan::PBKDF::pbkdf_iterations(unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char const*, unsigned long, unsigned long) const", referenced from:
      _elektraCryptoBotanDecrypt in botan_operations.cpp.o
      _elektraCryptoBotanEncrypt in botan_operations.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
```

.

# System Information

- Elektra Version: master
- OS: macOS 10.12

**Comment by sanssecours** [comment]
I think we can fix this problem by installing Botan from source. At least installing `yaml-cpp` from source using GCC:

```sh
brew install --cc=gcc-7 --c++11 yaml-cpp
```

solved a similar issue for the YAML CPP plugin.

**Comment by markus2330** [comment]
Strange, did you have a header/library inconsistency? Or was the version you used actually broken with symbols missing?

Anyway, good that it is working now.

**Comment by sanssecours** [comment]
The following comment only applies to `yaml-cpp`.

> Strange, did you have a header/library inconsistency?

If you mean something like “Did you have two incompatible versions of the same library installed?” with your question, then my answer is “Probably Not“.

> Or was the version you used actually broken with symbols missing?

As far as I can tell Clang and GCC seem to produce slightly different symbols for `std::basic_string`.

I created a small sample project for `yaml-cpp`. Clang compiles this project without problems, if I use the bottled (binary) version of yaml-cpp. If I compile my sample project using `g++-7`, then the linker reports the following problem:

```
Undefined symbols for architecture x86_64:
  "YAML::LoadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      _main in main.cpp.o
  "YAML::operator<<(std::basic_ostream<char, std::char_traits<char> >&, YAML::Node const&)", referenced from:
      print(YAML::Node&)     in main.cpp.o
      _main in main.cpp.o
```

. After that I searched for `YAML::LoadFile` in the symbol table of `yaml-cpp`:

```sh
symbols (pkg-config yaml-cpp --variable=libdir)/libyaml-cpp.dylib | grep YAML::LoadFile
```

. The command above showed the following definition:

```
YAML::LoadFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
```

. I assumed this means that yaml-cpp was translated using a different C++ standard. But even if I install `yaml-cpp` using the flag `--c++11`:

```sh
brew install --c++11 yaml-cpp 
```

,  the definition of the function stays the same. Only if I I also use `g++-7` to compile `yaml-cpp`:

```sh
brew install --cc=gcc-7 --c++11 yaml-cpp
```

, then the library contains the symbols GCC 7 expects:

```
YAML::LoadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
```

. After that change however, Clang is unable to link to the library since it searches for `std::__1::basic_string` instead of `std::__cxx11::basic_string`:

 ```
 Undefined symbols for architecture x86_64:
   "YAML::LoadFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
       _main in main.cpp.o
   "YAML::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, YAML::Node const&)", referenced from:
       print(YAML::Node&) in main.cpp.o
       _main in main.cpp.o
 ```

 . I also tried `gcc-4.9` which expects the following symbol definition for `YAML::LoadFile`:

 ```
 YAML::LoadFile(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
 ```

 , which makes the most sense in my opinion, but is again incompatible with both `g++-7` and Clang. If anybody knows how I can fix these linking problems, without recompiling the library with a compatible compiler, then please just comment below.
