### ISSUE TITLE
Fcrypt: KDB Get Succeeded on Faulty Non-Verifiable File

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1593]
# Description

Seems like part of `testmod_fcrypt` failed in one of the [latest Travis builds](https://travis-ci.org/sanssecours/libelektra/jobs/269210137#L2747):

```
FCRYPT       TESTS
==================
/Users/travis/build/sanssecours/libelektra/src/plugins/fcrypt/testmod_fcrypt.c:228: error in test_file_signature_operations: kdb get succeeded on faulty non-verifiable file
fcrypt RESULTS: 39 test(s) done. 1 error(s).
```

. I do not think that this is an OS or compiler-specific bug, since I saw the same issue using both 

- GCC on macOS and 
- Clang on Linux

.

# System Information

- Elektra Version: `master`

**Comment by markus2330** [comment]
Thank you for reporting the problem!

**Comment by petermax2** [comment]
> Clang on Linux

What distro have you been using? Do you possibly remember which cmake options you used?

The test cases are running fine on my OS X, Debian 9 and FreeBSD instances. I can't reproduce the error locally.

**Comment by petermax2** [comment]
But the test case needs some love anyway. I will re-design it.

**Comment by sanssecours** [comment]
> What distro have you been using?

[Ubuntu Trusty Tahr](https://docs.travis-ci.com/user/reference/trusty)

> Do you possibly remember which cmake options you used?

```sh
-GNinja
-DBUILD_STATIC=OFF
-DPLUGINS="ALL;-jni"
-DBINDINGS=ALL
-DTOOLS=ALL
-DINSTALL_SYSTEM_FILES=OFF
-DCMAKE_INSTALL_PREFIX="$INSTALL_DIR"
-DKDB_DB_SYSTEM="$SYSTEM_DIR"
${CMAKE_OPT[@]}
```

You can find the other options specified in `CMAKE_OPT` in [`.travis.yml`](https://github.com/ElektraInitiative/libelektra/blob/master/.travis.yml).

> The test cases are running fine on my OS X, Debian 9 and FreeBSD instances. I can't reproduce the error locally.

Unfortunately this seems to be a transient error. For now I saw two instances when this problem happened:

1. on macOS using GCC while running `ninja run_all`, and
2. on Ubuntu using Clang while running `kdb run_all`

.

**Comment by petermax2** [comment]
Thank you for the details. I will investigate.

**Comment by petermax2** [comment]
I still can't reproduce the error even when sticking strictly to the travis build instructions. Nevertheless I redesigned the unit-test (it wasn't good anyway). The behavior should be more stable now.

See ba9b48571eb9ca25e354843f464fcad4b81ea81e .
