### ISSUE TITLE
Documentation: HTTPS Links to Documentation Point to Folder Structure

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1607]
# Step to Reproduce

Open one of the following links:

  - https://doc.libelektra.org
  - https://doc.libelektra.org/
  - https://doc.libelektra.org/api
  - https://doc.libelektra.org/news/

in your favorite browser.

# Expected Result

The browser redirects you to a page, where you can learn more about Elektra

# Actual Result

The pages displays the folder structure on the server. For example, below is the HTML output of `curl https://doc.libelektra.org`:

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
 <head>
  <title>Index of /</title>
 </head>
 <body>
<h1>Index of /</h1>
  <table>
   <tr><th valign="top"><img src="/icons/blank.gif" alt="[ICO]"></th><th><a href="?C=N;O=D">Name</a></th><th><a href="?C=M;O=A">Last modified</a></th><th><a href="?C=S;O=A">Size</a></th><th><a href="?C=D;O=A">Description</a></th></tr>
   <tr><th colspan="5"><hr></th></tr>
<tr><td valign="top"><img src="/icons/folder.gif" alt="[DIR]"></td><td><a href="api/">api/</a></td><td align="right">2016-11-22 21:33  </td><td align="right">  - </td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="/icons/folder.gif" alt="[DIR]"></td><td><a href="archive/">archive/</a></td><td align="right">2016-12-20 10:08  </td><td align="right">  - </td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="/icons/folder.gif" alt="[DIR]"></td><td><a href="coverage/">coverage/</a></td><td align="right">2014-09-22 16:04  </td><td align="right">  - </td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="/icons/folder.gif" alt="[DIR]"></td><td><a href="help/">help/</a></td><td align="right">2015-11-15 09:55  </td><td align="right">  - </td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="/icons/folder.gif" alt="[DIR]"></td><td><a href="news/">news/</a></td><td align="right">2017-03-20 16:24  </td><td align="right">  - </td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="/icons/folder.gif" alt="[DIR]"></td><td><a href="restapi/">restapi/</a></td><td align="right">2017-04-08 21:41  </td><td align="right">  - </td><td>&nbsp;</td></tr>
   <tr><th colspan="5"><hr></th></tr>
</table>
<address>Apache/2.4.10 (Debian) Server at doc.libelektra.org Port 443</address>
</body></html>
```

.

**Comment by sanssecours** [comment]
> Do you want the directory listing beautified or should it be part of the web site?

I do not think the directory listing is very useful in the case of https://doc.libelektra.org. The bigger problem here is the non-uniform behavior of HTTP and HTTPS links however. For example:

-  https://doc.libelektra.org: shows a directory listing, while
-  http://doc.libelektra.org redirects to  https://www.libelektra.org/.

In my opinion both links should point to the same introductory page of the documentation, like

- https://www.libelektra.org/docgettingstarted/ ,
- https://www.libelektra.org/devgettingstarted/ , or maybe even more useful
- https://doc.libelektra.org/api/current/html/

. If the folder structure is intentional, then I think the pages for 

- https://doc.libelektra.org/api
- https://doc.libelektra.org/news

look okay, since most people wont enter these addresses manually anyway.

**Comment by markus2330** [comment]
Thank you again for reporting! The inconsistency should be fixed now.
