### ISSUE TITLE
KDB Does Not List YAJL Plugin

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1612]
# Steps to Reproduce

1. Build Elektra including support for YAJL
2. Enter the following command

   ```sh
   kdb list | sort
   ```

# Expected Output

The output of the command above should include an entry `yajl`. 

# Actual Output

```
base64
blockresolver
boolean
c
cachefilter
ccode
conditionals
constants
counter
csvstorage
desktop
doc
dpkg
dump
enum
error
glob
hexcode
hidden
hosts
ini
iterate
keytometa
line
lineendings
list
logchange
mathcheck
mozprefs
network
ni
noresolver
null
passwd
path
profile
regexstore
rename
required
resolver
resolver_fm_b_b
resolver_fm_hb_b
resolver_fm_hp_b
resolver_fm_hpu_b
resolver_fm_pb_b
resolver_fm_ub_x
resolver_fm_uhb_xb
resolver_fm_xb_x
resolver_fm_xhp_x
resolver_fm_xp_x
shell
simplespeclang
spec
storage
struct
sync
syslog
template
timeofday
tracer
type
uname
validation
wresolver
```

# Other Information

The plugin is available since mounting with 

```sh
kdb mount config.json user/json yajl
```

and writing via `kdb set user/json/key value` seems to work correctly. At least 

```sh
kdb file user/json | xargs cat
```

prints

```
{
    "key": "value"
}
```

.

# System Information

- Elektra Version: master
- OS: macOS 10.13

**Comment by markus2330** [comment]
Sorry, cannot reproduce: `kdb list | grep yajl` finds yajl as expected for me.

**Comment by sanssecours** [comment]
Thank you for testing. Looks like `kdb list` always checks the installed version of Elektra, even if I invoke `build/bin/kdb`. Uninstalling Elektra via `brew remove elektra` solved the issue.

**Comment by markus2330** [comment]
Yes, if HAVE_GLOB is true, the installed plugins are checked.

You can see the implementation in src/libs/tools/src/plugindatabase.cpp line 51, function ModulesPluginDatabase::listAllPlugins

We could fix your problem for non-installed versions by considering the RPATH, but we should decide on #1275 first.

So let us keep it closed for now, if we keep using RPATH, we should fix it.
