### ISSUE TITLE
KDB Command to Set Binary Values

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1614]
# Proposal

Sometimes it would be nice to have a tool that stores binary data in the key data base. We could either integrate this functionality directly into `kdb set` or create a new tool with the name `kdb setbinary`, `kdb setbin` or a similar name. Since binary data can also contain NULL bytes I think we should probably support escape sequences to save arbitrary data. For example the command

```sh
kdb setbin user/test/binary/key '\x48\x69\x00'
```

or the equivalent command

```sh
kdb setbin user/test/binary/key 'Hi\x00'
```

could save the C ASCII string `Hi`(the numbers 72, 105, and 0) in the key `user/test/binary/key`.

**Comment by markus2330** [comment]
Thank you, good proposal! I would prefer the longer name `set-binary` (see #302)
