### ISSUE TITLE
[FLOSS H1] build server check: only allow a-z, 0-9 and _ for file names

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1615]
We have inconsistent use of characters in file names, which always requires one to think which kind of separator is used in specific cases.

```
~e> find . -name '*-*' | wc -l
386
~e> find . -name '*_*' | wc -l
491
~e> find . -name '* *' | wc -l
0
```

As short time goal we should not introduce new variants (such as spaces, see #1613), as 1.0 goal I propose to unify it to a single variant.

**Comment by markus2330** [comment]
Latest results:

```
~e> find . -name '*-*' | grep -v "^./.git/" | wc -l                                                                                                                                                                                          
416
~e> find . -name '*_*' | grep -v "^./.git/" | wc -l                                                                                                                                                                                          
538
```

Ideally we would have a script that automatically renames everything based on conventions, in the same way we have it with clang-format. I'd prefer not to have to discuss about such conventions :wink:

**Comment by markus2330** [comment]
The guideline now is `find . -not -regex '[/.a-zA-Z0-9_-]*'` should not find your file names. We should add a build server task to check this, #160.

**Comment by markus2330** [comment]
@muskater it is easier to do such verification in a clean clone.

I also tried the command, and `./.idea/fileTemplates/includes/C File Header.h` seems to be an actual violation. Can you check if this name is required by idea? If yes, it is probably best to simply allow this file and add an exception to the check. (Ideally in a separated whitelist file tests/filenames.whitelist, like tests/linkchecker.whitelist.)

**Comment by muskater** [comment]
CLion requires the template name to be `C File Header.h`. I have tried many different ways to rename and or re-add the file. However, all of them failed and CLion complaint not being able to find the template.

Having a template for header files is definitely a nice addition. I agree, the best solution would be to have a separate allow list for these kind of corner cases.
