### ISSUE TITLE
yamlcpp: Internally inconsistency

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1619]
yamlcpp's add_plugin does not protect its arguments against inconsistencies.

```
 CMake Error at cmake/Modules/LibAddPlugin.cmake:185 (message):
   Internally inconsistency, plugin elektra-yamlcpp got different values for
   variable ARG_INCLUDE_DIRECTORIES: '/usr/include;/usr/include' !=
   '/usr/include'
 Call Stack (most recent call first):
   cmake/Modules/LibAddPlugin.cmake:244 (restore_variable)
   src/plugins/yamlcpp/CMakeLists.txt:22 (add_plugin)
```

**Comment by sanssecours** [comment]
Could you please add steps to reproduce this problem. All of the Travis instances worked without any problems after all…

**Comment by markus2330** [comment]
The issue is already fixed. It is an easy fix: You only need to make sure to never pass more than one argument in add_plugin. Reproducing might be difficult, you need a Distro with cmake  where:

- both yamlcpp and boost have an include path
- only one of them caches the path
