### ISSUE TITLE
KDB Export: Support Multiple Plugins

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1625]
# Description

Currently plugins that require other plugins might crash on export. The issue is that `kdb export` only supports a single plugin. The commands below show steps to [reproduce a crash](https://github.com/ElektraInitiative/libelektra/issues/1019).

```sh
cd src/plugins/xmltool/xmltool
kdb import user/tests/dump xmltool < dump.xml
kdb export user/tests/dump tcl
#> {
#>        {
# STDERR: *** Error in `kdb': munmap_chunk(): invalid pointer: 0x000000000119c490 ***
#                 zsh: abort (core dumped)  noglob kdb export user/tests/dump tcl
```

This issue should be fixed after we implement #1229.

**Comment by markus2330** [comment]
I think this issue is actually a problem of the tcl plugin (I was also able to reproduce a crash), #3491 should solve the problem.
