### ISSUE TITLE
old web sites lead to 404

### ISSUE THREAD

**Issue by the-Arioch** [ElektraInitiative/libelektra#1628]
Google for KDE xml registry - > get 2004 presentation "Linux Registry Project" -> get URL for that project

The first redirect works ( http://registry.sf.net -> http://elektra.sf.net )

But the next redirect leads to 404, as if the project is dead and abandoned long ago

**Comment by markus2330** [comment]
Thank you for reporting the issue! We have left sourceforge a long time ago, I will check if it is possible to fix the redirect.

For new references to elektra, please use https://www.libelektra.org

**Comment by markus2330** [comment]
Thanks again for reporting, I fixed the redirect.
