### ISSUE TITLE
Build Scripts

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1641]
@BernhardDenner Could you please tell me where I can find the scripts (`run-make`, …) for the Jenkins build jobs?

**Comment by markus2330** [comment]
/etc/puppet/buildserver/modules/buildslave/files/scripts

**Comment by markus2330** [comment]
The scripts are part of the (currently private) repo https://github.com/ElektraInitiative/buildserver in the folder `modules/buildslave/files/scripts`.

You have access to it now, unfortunately we lack a good description how to apply puppet configs, you might have to ping @BernhardDenner to actually apply it.

Afaik the scripts do not cause a current problem (they could be optimized though to use a higher `-j` on some of the build agents).
