### ISSUE TITLE
boolean values in specification

### ISSUE THREAD

**Issue by BernhardDenner** [ElektraInitiative/libelektra#1659]
See #1657 

The rest-backend specification file uses some boolean typed keys (meta key `check/type = boolean`) with default values set to `true` or `false`. However, these default values are in the current version of elektra incorrect, since the `boolean` plugin will not convert them since it is triggered on meta key `type = boolean` instead of `check/type = boolean`. As a result of this, the rest-backed application will crash if these defaults get applied because the `kdb::get<bool>` throws an exception:

```
terminate called after throwing an instance of 'kdb::KeyTypeConversion'
  what():  Could not convert data to requested type. Use get(Meta)<std::string> respectively get(Meta)<const Key> for more generic access or specialize the template methods with your type.
```

Question: did the rest-backend spec file with the `true/false` defaults for boolean keys ever work as desired? 
If yes, now it does not.

I think this should be fixed, since using `true` or `false` for boolean values is quite convenient and makes a specification more readable.

**Comment by markus2330** [comment]
Thank you for reporting this! It seems like the boolean plugin is severely broken (thanks for also reporting #1646 and #1645). It was hardly changed till 0.8.18, so there are good chances it never worked correctly.

If we do not find the issues, we make it experimental again.

This specific issue should be trivial to fix, I will do it right now.
