### ISSUE TITLE
shell recorder: leftovers

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1660]
- [x] src/plugins/mini/README.md creates the file stderr.txt and does not clean it up. Isn't it possible with an stderr-regex to avoid this file? (fixed in #1640)
- [x] empty folder `kdbtutorial`
- [x] folder `.dir`

**Comment by sanssecours** [comment]
Pull request #1640 already [fixes this problem](https://github.com/ElektraInitiative/libelektra/pull/1640/commits/4f81ce11b38f4ec35e508d4160e4d48683f2de65).

**Comment by markus2330** [comment]
Ohh, I even commented this line. I completely forgot about it.

Using a temporary directory for shell recorder execution and not writing files unless required would be preferable. It is low priority, though.

**Comment by markus2330** [comment]
It seems like we additionally have an empty folder `kdbtutorial` as leftover.
