### ISSUE TITLE
Homepage: Broken URLs

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1662]
# Steps to Reproduce

1. Open a web browser
2. Open a URL for a plugin like https://www.libelektra.org/plugins/multifile

# Expected Result

The web browser displays some information about the `multifile` plugin.

# Actual Result

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /plugins/multifile was not found on this server.</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at www.libelektra.org Port 443</address>
</body></html>
```

# Other Information

The strange thing is that the browser displays the correct result if I follow the steps below.

1. Enter the URL https://www.libelektra.org
2. Select “Documentation“→“Plugins”
3. Select “Multifile“
4. The browser shows the correct page content and displays the URL https://www.libelektra.org/plugins/multifile

If I now press enter in the URL input field, then the browser displays the 404 page mentioned above.

**Comment by markus2330** [comment]
Thank you for reporting this!

Seems like there is still some misconfiguration in the website setup, I am quite sure it worked before reinstallation.

@BernhardDenner Can you take a look at it?

**Comment by markus2330** [comment]
It seems like an URL rewrite is missing, see https://stackoverflow.com/questions/20459047/angular-routing-doesnt-work-when-url-is-directly-visited-in-browser-but-works-w

@Namoshek Do you know what exactly we forgot to do in the apache setup?

**Comment by Namoshek** [comment]
I don't remember our exact rewrite rules, but the rules should basically do two things:
- Look if a resource with the given URL is available (e.g. [the logo](https://www.libelektra.org/assets/img/logo.svg)). If this is the case, the resource should be returned (i.e. no rewrite necessary).
- If no resource was found for the given URL, the index.html should be served instead (but the URL should not be changed, i.e. no `Location` header needs to be sent or so).

The link of you provides proper rewrite conditions, I think. Just give them a try!

**Comment by BernhardDenner** [comment]
Found and fixed. 
The corresponding `Directory` directive was pointing to the wrong path, therefore the `FallbackResource` was not active for the homepage. Now refreshs and direct links work as expected.

**Comment by markus2330** [comment]
Thank you, that is great!

@BernhardDenner Now only the website build is missing.
