### ISSUE TITLE
Website: yamlcpp not included

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1665]
Seems like the regex that parses all plugin names from `src/plugins/README.md` stumbles over yamlcpp. After following change:

```
-- [yamlcpp](yamlcpp/) reads and writes data in the [YAML][] format using [yaml-cpp](https://github.com/jbeder/yaml-cpp)
+- [yamlcpp](yamlcpp/) reads and writes data
```

yamlcpp is successfully included, otherwise it is missing.

Steps to reproduce:   Add `rest-frontend` to tools, install Elektra run `installation/lib/elektra/tool_exec/run-rest-frontend `, and visit `http://localhost:9000/plugins/yamlcpp`.

We can either fix the regex, or the yamlcpp entry.

The regex is in `src/tools/rest-frontend/resources/structure.json.in` line 93.

**Comment by sanssecours** [comment]
I would say we rather fix the regular expression, since the entry is not broken. I think

```js
"entry_regex": "^- \\[([^\\]]+)\\]\\(([^)]+)\\)(.*)"
```

should work. At least it does in the JavaScript console of my browser. Can you please try if it works in the REST frontend too?
