### ISSUE TITLE
example how to use merge API

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#167]
Could you please create an example what is the currently best way to use the merge API. Please add the file to src/libtools/examples/.

**Comment by markus2330** [comment]
an example in keytometa/README.md would be brilliant, too.

**Comment by fberlakovich** [comment]
> an example in keytometa/README.md would be brilliant, too.

What kind of example are you thinking of here? Each subsection in the README already contains one ore more examples. Do you mean an example making use of all the different options at once?

**Comment by markus2330** [comment]
Hello,

you wrote:
> What kind of example are you thinking of here? Each subsection in the
> README already contains one ore more examples. Do you mean an example
> making use of all the different options at once?

I am thinking about realworld examples, e.g. like you worked with it with 
augeas. It should be clear how to mount the plugin and how to configure glob 
(or other ways of doing metadata tagging). You can add them to the README.md.

The examples currently in the README.md also need some cleanup, e.g. in 
section "PARENT STRATEGY" there is no child3 in the example.

best regards
