### ISSUE TITLE
Markdown Shell Recorder: Documentation Improvements

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1675]
# Description

Currently the documentation of the Markdown Shell Recorder is quite limited.

# Checklist

We should consider the following points mentioned by Markus in pull request #1640:

- [x] “General info should be earlier, specific infos later.”
- [x] “Should we mention `⏎` at all or is this only an implementation detail?“
- [x] “Isn't it better if the concatenation feature is consistent used everywhere?”

.

**Comment by markus2330** [comment]
Thank you for reporting this issue and collecting the left overs in such a careful way!
