### ISSUE TITLE
qt-gui: many shadow parameters

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#168]
Names are often reused in different scopes which can be confusing, e.g.

GUIBackend::mountPoints uses the variable

    QStringList mountPoints;

Please turn on -Wshadow to get a warning for these situations. Ideally, you should fix all warnings of cmake/ElektraCompiling.cmake

**Comment by 0003088** [comment]
fixed in 79c2626627

**Comment by markus2330** [comment]
Thanks, all warnings gone now.
