### ISSUE TITLE
Website: More plugins?

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1680]
- [ ] xerces
- [ ] yamlcpp

and less important:

- [ ] camel
- [ ] mini
- [ ] others?

**Comment by BernhardDenner** [comment]
the homepage build currently excludes all EXPERIMENTAL plugins

**Comment by markus2330** [comment]
I added `camel;xerces;yamlcpp` f986a66f7766605fd9822163280b9810446e61bf and installed libyaml-cpp-dev on the homepage node. I could not find the place in the yaml file referring to the installed packages for the homepage node?
