### ISSUE TITLE
Xerces: Problems with INI as Default Storage

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1686]
# Steps to Reproduce the Problem

1. Configure Elektra with INI as default storage

   ```sh
   mkdir build
   cd build
   cmake .. -GNinja -DPLUGINS='ALL' -DKDB_DB_FILE='default.ini' -DKDB_DB_INIT='elektra.ini' -DKDB_DEFAULT_STORAGE=ini
   ```

2. Build Elektra  

   ```sh
   ninja
   ```

3. Run the following commands:

   ```sh
   sudo kdb mount xerces.xml /examples/xercesfile xerces
   
   kdb set /examples/xercesfile foo
   kdb setmeta /examples/xercesfile xerces/rootname xerces
   kdb set /examples/xercesfile/bar bar
   kdb setmeta /examples/xercesfile/bar meta "da_ta"
   
   kdb getmeta /examples/xercesfile xerces/rootname
   #> xerces
   
   kdb get /examples/xercesfile/bar
   #> bar
   
   kdb export /examples/xercesfile xerces
   ``` 

# Expected Result

```sh
#> <?xml version="1.0" encoding="UTF-8" standalone="no" ?>
#> <xerces>
#>
#>   <bar meta="da_ta">bar</bar>foo
#>
#> </xerces>
```

# Actual Result

```sh
# ERROR: 174
```

## Error Message

```
Sorry, the error (#174) occurred ;(
Description: general xml error
Reason: invalid or illegal XML character
Ingroup: plugin
Module: xerces
At: ../src/plugins/xerces/xerces.cpp:114
Mountpoint: /examples/xercesfile
Configfile: /dev/stdout
```

# System Information

- Elektra Version: master

**Comment by markus2330** [comment]
Thank you for reporting! Good that we did not switch to INI as default in this release.

I used 0.8.21 as milestone: for the lcdproc release INI as default is desirable. In general you do not have to tag bugs as "1.0.0", it is clear that we want to release non-experimental parts of 1.0.0 without known bugs. Having too many issues for "1.0.0" makes the goal less clear. We could add another milestone for your purpose?

**Comment by sanssecours** [comment]
> We could add another milestone for your purpose?

How about `0.9`? I think `1.0` should only fix minor issues of an almost stable `0.9.x` release.

**Comment by markus2330** [comment]
Good suggestion, I created 0.9.0.

INI-specific bugs, however, are 0.8.21, unless you plan to create a new INI plugin which can we use as default?

**Comment by sanssecours** [comment]
> INI-specific bugs, however, are 0.8.21, unless you plan to create a new INI plugin which we can use as default?

Nope 😊. I think it makes more sense to fix the already existing INI plugin, instead of creating a new one, containing new additional bugs.

**Comment by markus2330** [comment]
This is now low-priority thus we do not have INI as default.
