### ISSUE TITLE
yamlcpp/xerces: ASAN tests fail

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1691]
When enabling yamlcpp/xerces for the homepage f986a66f7766605fd9822163280b9810446e61bf the test cases fail:

```
 75/101 Test  #77: testmod_yamlcpp ..................***Failed    0.64 sec
/usr/include/boost/smart_ptr/detail/shared_count.hpp:484:41: runtime error: member call on address 0x60300000ecb0 which does not point to an object of type 'sp_counted_base'
0x60300000ecb0: note: object is of type 'boost::detail::sp_counted_impl_p<YAML::detail::memory_holder>'
 02 00 00 70  98 96 c5 0d e5 7f 00 00  01 00 00 00 01 00 00 00  70 e7 00 00 20 60 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
...
/home/jenkins/workspace/workspace/elektra-homepage/src/plugins/xerces/deserializer.cpp:202:57: runtime error: member call on address 0x613000003d90 which does not point to an object of type 'DOMDocument'
0x613000003d88: note: object is base class subobject at offset 8 within object of type 'xercesc_3_1::DOMDocumentImpl'
 20 60 00 00  a8 81 ec a3 71 7f 00 00  b8 84 ec a3 71 7f 00 00  00 86 ec a3 71 7f 00 00  38 86 ec a3
              ^                        ~~~~~~~~~~~~~~~~~~~~~~~
                                       vptr for 'xercesc_3_1::DOMDocument' base class of 'xercesc_3_1::DOMDocumentImpl'
```

See https://build.libelektra.org/jenkins/job/elektra-homepage/235/consoleFull for full log.

Any idea why the suppressions (tests/sanitizer.blacklist) are not working?

Do we need a new script for every combination? (asan_nokdbtests?) If possible I would rather avoid that.

**Comment by sanssecours** [comment]
> Any idea why the suppressions (tests/sanitizer.blacklist) are not working?

I assume that is the case since the homepage build uses GCC:

```cmake
	if (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
		set (EXTRA_FLAGS "${EXTRA_FLAGS} -fsanitize=integer")
		set (EXTRA_FLAGS "${EXTRA_FLAGS} -fsanitize-blacklist=\"${CMAKE_SOURCE_DIR}/tests/sanitizer.blacklist\"")
	endif ()
```

.

**Comment by markus2330** [comment]
Thank you for looking into it. I removed these two plugins for now until also a solution for gcc is found.

**Comment by e1528532** [comment]
Yes gcc doesn't support the blacklist. There seems to be the possibility to use a [macro](https://stackoverflow.com/questions/27966082/gcc-address-sanitizer-blacklisting-library-functions-specifically-boosttest) though but since some of the blacklisted things happen inside an external library, this doesn't seem to be a good solution for us.

**Comment by markus2330** [comment]
The advantage of the macro is that it is supported by both llvm and gcc. Does it work recursive? Then we could mark the functions calling the problematic code.

Is not ideal, though, we would also exclude our code to be instrumented 😕
