### ISSUE TITLE
dini: new default storage plugin

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1693]
## To be done

- [ ] add binary plugin as dep
- [x] #1713 ASAN
- [x] testshell_markdown_dini fails
- [x] cannot write new dini files (conflict)

## Specification

For the migration from dump to ini, we need a new plugin dini (for "default ini" or "dump ini"), which is capable of:

- reading (but not writing!) dump files with the dump plugin, if it fails reading a dump file it falls back to:
- reading and writing ini files with the ini plugin
- instantiate plugins the ini plugin needs (null, binary, dir2leaf  #106, others?)

*Every* error that happens during reading with dump is ignored, including the absence of the dump plugin. This allows the dump plugin to be dropped as hard dependency. (e.g. people not caring about migration but caring about the plugins ini needs). People might even remove the dump plugin on purpose because it obviously causes some overhead.

The goals of the plugin are:

- to be completely compatible with Elektra installations that currently use dump
- safely migrate such installations to use INI
- to be able to represent every KeySet, like dump did (thus null, binary, dir2leaf, etc. plugins might be needed)

When we have dini, we can make the plugin dump obsolete. dump then only is used in the context of dini: to migrate legacy Elektra installations.

What do you think?

**Comment by sanssecours** [comment]
> What do you think?

Sounds good to me (as long as I do not have to implement the `dini` plugin ☺️).

**Comment by markus2330** [comment]
Are there any further leftovers for dini except merging #1722?

To everyone: Please use and test the dini plugin.

**Comment by sanssecours** [comment]
> Are there any further leftovers for dini except merging #1722?

I do not think so. I already pulled the relevant changes from #1722 into the master branch yesterday.

> To everyone: Please use and test the dini plugin.

I currently use `dini` as default storage. As far as I can tell everything works fine 🙌.

**Comment by markus2330** [comment]
In particular we should test if partly-done-migrations (like /etc/kdb/default.ecf is already INI but /etc/kdb/elektra.ecf is not) causes any problems.

Do we need (or can we) add other plugins to be used within INI? (null, binary, directoryvalue?)

**Comment by sanssecours** [comment]
> Do we need (or can we) add other plugins to be used within INI? (null, binary, directoryvalue?)

- Adding `directoryvalue` to INI does not work, as already stated [here](https://github.com/ElektraInitiative/libelektra/pull/1722#issue-280811266).

- Fortunately using Base64 (`binary`) together with INI seems to work. I already added a Markdown Shell Recorder test for this situation in one of the branches of my repo.

- I do not think it makes much sense to also use the `null` plugin together with INI, since INI already supports empty values. If we use Base64, then INI can also save empty binary values.

**Comment by markus2330** [comment]
Thank you, thats great, let us add binary/base64. (I added it in the top post)
