### ISSUE TITLE
INI: Merging Does not Work

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1696]
# Description

It seems like `kdb merge` does not work correctly if we use INI as default storage.

# Steps to Reproduce the Problem

1. Configure Elektra with INI as default storage:

   ```sh
   mkdir build
   cd build
   cmake .. -GNinja -DPLUGINS='ALL' -DKDB_DB_FILE='default.ini' -DKDB_DB_INIT='elektra.ini' -DKDB_DEFAULT_STORAGE=ini
   ```

2. Build Elektra:

   ```sh
   ninja
   ```

3. Run the following commands:

   ```sh
   kdb set user/tests/script/mergetest/ours/key   init
   kdb set user/tests/script/mergetest/theirs/key init
   kdb set user/tests/script/mergetest/base/key   init
   
   kdb merge                            \
     user/tests/script/mergetest/ours   \
     user/tests/script/mergetest/theirs \
     user/tests/script/mergetest/base   \
     user/tests/script/mergetest/merged
   ```

# Expected Result

The tool `kdb merge` should produce a new key `user/tests/script/mergetest/merged` with the value `init`.

# Describe what actually happened

```
1 conflicts were detected that could not be resolved automatically:
user/tests/script/mergetest/merged/key
ours: CONFLICT_META, theirs: CONFLICT_META

Merge unsuccessful.
```

# Additional Information

- Elektra Version: master
- Jenkins Build Job: [elektra-ini-mergerequests](https://build.libelektra.org/jenkins/job/elektra-ini-mergerequests)

**Comment by markus2330** [comment]
Thank you for reporting this issue! It might be simply caused by the internal metadata, then it is yet-another-instance of #1695.

Seems like we need debug info in src/merging/metamergestrategy.cpp or even better a debug merger strategy to find out.

**Comment by alexsaber** [comment]
Hi! Can you please assign me to this issue? I have picked 3 more ini related problems.
