### ISSUE TITLE
INI: Mathcheck Plugin Does not Work 

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1697]
# Description

It looks like the `mathcheck` does not work correctly if we use INI as storage plugin.

# Steps to Reproduce the Problem

```sh
kdb mount mathcheck.esr user/tmount/mathcheck mathcheck ini

kdb set user/tmount/mathcheck/check/test0/points 5.9
kdb set user/tmount/mathcheck/check/test1/points 4.5

kdb set user/tmount/mathcheck/check/gp
kdb setmeta user/tmount/mathcheck/check/gp check/math ":= + ../test0/points ../test1/points"

kdb get user/tmount/mathcheck/check/gp
# STDOUT: 10.4
```

# Expected Result

The command `kdb get` prints `10.4`.

# Actual Result

The command `kdb get` prints nothing.

# Additional Information

Everything works fine if we use the `ni` plugin instead of `ini`:

```sh
kdb mount mathcheck.esr user/tmount/mathcheck mathcheck ni
```

.

- Elektra Version: master

**Comment by markus2330** [comment]
Thank you for reporting! Can you please also post the resulting ini file? Is the meta data properly stored in the file?

**Comment by sanssecours** [comment]
> Can you please also post the resulting ini file?

```ini
[check/test0]
points = 5.9
[check/test1]
points = 4.5
#@META check/math = := + ../test0/points ../test1/points
[check/gp]
```

> Is the meta data properly stored in the file?

Yes, as far as I can tell. The command `kdb getmeta user/tmount/mathcheck/check/gp check/math` returns

```
:= + ../test0/points ../test1/points
```

.
