### ISSUE TITLE
qt-gui: creates config style with state

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1707]
# Steps to Reproduce the Problem

Not yet reproduced.

# Expected Result

no files are written to disc

# Actual Result

.config/ElektraInitiative/org.libelektra.elektra-qt-editor.conf

gets written to disc with content like:

```
[QQControlsFileDialog]
favoriteFolders=@Variant(\0\0\0\x7f\0\0\0\tQJSValue\0\0\0\0\0\0\0\0\t\0\0\0\0)
height=0
sidebarSplit=111.60000000000001
sidebarVisible=true
sidebarWidth=80
width=0

```

# System Information

- Elektra Version: master

**Comment by markus2330** [comment]
@0003088 Is it maybe possible to not write this file?

**Comment by 0003088** [comment]
I don't know? I never intentionally created this file. It looks to me like the file the OS creates to remember the window settings?

**Comment by markus2330** [comment]
Yes, seems like qt has some build-in feature doing this. Maybe it is possible to turn the feature off.
