### ISSUE TITLE
jenkins: build all job

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1711]
As proposed by @sanssecours we could add the "jenkins build all please" phrase to every build job.

This way we could avoid merging PRs that break some build job.

Maybe we should exclude the build jobs that are already triggered immediately anyway?
Any suggestions for a better name than "jenkins build all please"?

(see also #160)

**Comment by sanssecours** [comment]
> Maybe we should exclude the build jobs that are already triggered immediately anyway?

Makes sense.

> Any suggestions for a better name than "jenkins build all please"?

Nope. The phrase sounds good to me.

**Comment by markus2330** [comment]
If we also want to exclude the build jobs that were executed by default, we might better have two phrases:

- "jenkins build all please"
- "jenkins build others please"

("build all" is still relevant if master is changed because this wont trigger the default build jobs for the PRs)

**Comment by sanssecours** [comment]
> If we also want to exclude the build jobs that were executed by default, we might better have two phrases…

You are right. In that case I am for including the PR build jobs too. The simplification (only one special build phrase) should make up for the overhead of building the PR jobs twice.

**Comment by sanssecours** [comment]
I just added the new build phrase to the triggers of almost all jobs. I did not incorporate the phrase in the build jobs

- `elektra-git-buildpackage-jessie`,
- `elektra-git-buildpackage-stretch`, and
- `elektra-git-buildpackage-wheezy`

, since I am not sure that building the packages makes much sense in the case of a pull request. I also did not attach the phrase to

- `PR-checks`, and
- `elektra-todo`

. Do you think we should add some of the build jobs above to `jenkins build all please` too?

**Comment by markus2330** [comment]
Thank you so much, its great to have `jenkins build all please` available. Can you document it in `doc/GIT.md` (if not done so already)?

Yes, the buildpackage jobs do not work for PRs.

I do not know what PR-checks is for, afaik it was created by @BernhardDenner

The `elektra-todo` is not really relevant (currently it is not used at all) but it also does not harm to add it? (One exception less.)

**Comment by sanssecours** [comment]
> Thank you so much, its great to have `jenkins build all please` available. Can you document it in `doc/GIT.md` (if not done so already)?

I am already working on it.

> The `elektra-todo` is not really relevant (currently it is not used at all) but it also does not harm to add it? (One exception less.)

Okay. I just added the phrase to the job.
