### ISSUE TITLE
docu: accidental removal of files

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1717]
@waht You mentioned a tutorial that might remove files of the user if the argument does not evaluate as expected. I could not find it with `grep -rH "\<rm\>" doc`. Can you tell me where you found this problem?

**Comment by waht** [comment]
It was in doc/TESTING.md, but instead of `rm` it was `chown`. I created PR #1737

**Comment by markus2330** [comment]
> but instead of rm it was chown

Ahh, that explains why I did not find it.

Thank you for the PR!
