### ISSUE TITLE
bugs in storage plugins

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1718]
This issue tracks bugs in storage plugins.

- [ ] `hosts` see #1719 
- [ ] `ini` see #1720

@BernhardDenner please do not forget to report the bugs of the storage plugins you found.

**Comment by BernhardDenner** [comment]
was this some sort of "miind transfer" ;)
I just wanted to add the bug reports ... and now I found this issue.
I'll keep it as a summary/parent issue.

**Comment by markus2330** [comment]
Thank you for the quick and detailed bug reports!

**Comment by markus2330** [comment]
All referenced bugs were closed.
