### ISSUE TITLE
glib: Building with clang fails

### ISSUE THREAD

**Issue by waht** [ElektraInitiative/libelektra#1739]
## Steps to Reproduce the Problem

Building the `glib` binding with `clang` fails with the following error:
```
[...]/libelektra/src/bindings/glib/gelektra-key.h:113:33: error: this function declaration is not a prototype [-Werror,-Wstrict-prototypes]

typedef void (*gelektra_func_t) ();
```
See failed build log: https://travis-ci.org/ElektraInitiative/libelektra/jobs/316925817#L1489

## System Information

- Elektra Version: master (was on different branch but line is same in master)
- Pesent in clang versions 5.0 (not reported with clang-3.8)

**Comment by markus2330** [comment]
Thank you, this is a good catch!

**Comment by waht** [comment]
Turns out it is a warning that gets promoted to an error on Travis because we're using `-Werror`
