### ISSUE TITLE
Remove Unused KeySet Flag

### ISSUE THREAD

**Issue by KurtMi** [ElektraInitiative/libelektra#1740]
During the integration of the OPMPHM I found a unused flag, it shall be removed!

- [ ] `KS_FLAG_SYNC` in kdbprivate.h:136 and
- [ ] the function `int ksNeedSync (const KeySet * ks)`.

Nevermind the conversation :)

@markus2330 I told you that I need a Flag but I found another way. Whats about the second one? It also dose some weird stuff.
@mpranj could you use the first one?

**Comment by mpranj** [comment]
I'm not sure what you mean. I haven't used `KS_FLAG_SYNC ` for anything. I had to introduce  `KS_FLAG_MMAP` and `KEY_FLAG_MMAP` so I can track what's inside a mmap region (and therefore should not be free()'d).

**Comment by markus2330** [comment]
Yes, one information is about who allocated the memory, the other information (@KurtMi is interested in) is about if there were changes in the KeySet.

@KurtMi Please reuse the unused KS_FLAG_SYNC (or rename it if you do not like the name). But we should definitely get rid of obsolete/historical stuff.

**Comment by KurtMi** [comment]
@markus2330 I apologize for causing confusion! The point is that I do NOT need the `KS_FLAG_SYNC` flag and I thought @mpranj could use it. But since nobody has usage for that flag, this issue will be transformed into the task to remove the flag.

**Comment by mpranj** [comment]
In that case I can reuse/rename it instead of my additional flag.

**Comment by KurtMi** [comment]
I found out that removing that flag appears to be non trivial since the function `ksNeedSync (...)`, that reads out that flag is also present in the bindings:
```
src/bindings/haskell/src/Elektra/KeySet.chs:12:  ksGetSize, ksNeedSync,
src/bindings/haskell/src/Elektra/KeySet.chs:55:{#fun unsafe ksNeedSync {`KeySet'} -> `Int' #}
src/bindings/jna/libelektra4j/src/main/java/org/libelektra/Elektra.java:143:    int ksNeedSync(Pointer ks);
src/bindings/jna/libelektra4j/src/main/java/org/libelektra/KeySet.java:175:             return Elektra.INSTANCE.ksNeedSync(get());
```

**Comment by markus2330** [comment]
Yes, additionally it would be an ABI/API break in the core library. So it needs to wait to 1.0 anyway.

doc/todo/FUTURE already lists ksNeedSync to be removed.

**Comment by kodebach** [comment]
@mpranj Do you see it correctly, that `KS_FLAG_SYNC` and `ksNeedSync` can still be removed?
AFAICT `KS_FLAG_SYNC` is set by `mmapstorage` and `ksPop`, but only read by `ksNeedSync` which in turn is never called (outside of test cases).

**Comment by mpranj** [comment]
Afair `mmapstorage` does not need this flag but it is currently used in its magic data. I could remove it from mmap while doing the other fixes.

**Comment by markus2330** [comment]
@mpranj Thank you for looking into this! Then let us simply keep this (internal) flag and let us only remove ksNeedSync. Can you remove it or create a separate issue for its removal?

**Comment by mpranj** [comment]
Ok I'll remove `ksNeedSync()` and _maybe_ keep the flag. No need for a separate issue as this issue is exactly what that is about ...
