### ISSUE TITLE
release-critical parts of community infrastructure

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1742]
Thanks to @BernhardDenner we quickly recovered from the breach at libelektra.org. Unfortunately, some release-critical parts are not yet fixed:

- [x] git repos for ftp+docu: Before the breach it was possible to directly push the release tarballs and docu to the server. It seems these parts are now plain files and not git repos anymore?
- [x] stretch debian packages not provided: the [stretch build job](https://build.libelektra.org/jenkins/job/elektra-git-buildpackage-stretch/) happily builds debian packages but currently there is no way to download them (No webserver reachable at https://unstable.libelektra.org/elektra-stable/).

And small new wishes for the release notes:

- [x] book.libelektra.org to redirect to https://github.com/ElektraInitiative/book
- [x] pulls.libelektra.org to redirect to "Pull requests" (https://github.com/ElektraInitiative/libelektra/pulls/)
- [x] puppet.libelektra.org to redirect to https://github.com/ElektraInitiative/puppet-libelektra

And:

- [x] fix feed URL #1684

**Comment by BernhardDenner** [comment]
@git for docu: I do not find any Apache related configuration that allows pulling/pushing to doc.liblektra.org using http protocol. Maybe it was configured somewhere else I not aware of.

Should this be usable by other users too, e.g. pulling from anonymous? If not, I prefer to use SSH for the transport layer, as this supports key based authentication and works out of the box by just creating a local user.

**Comment by markus2330** [comment]
@BernhardDenner Thank you for looking into it!

>  I do not find any Apache related configuration that allows pulling/pushing to doc.liblektra.org using http protocol.

It was done using ssh but the repos were configured in a way that they automatically check out when something is pushed into them.

> as this supports key based authentication and works out of the box by just creating a local user.

Yes, I would also prefer that. Can you create a user with correct permissions and add my public key?

**Comment by BernhardDenner** [comment]
Git repo for releases/downloads now up2date again. See mail for instructions.

**Comment by BernhardDenner** [comment]
New subdomain redirects added, Letsencrypt setup will be done in right now.
However, you still have to update the liblektra.org domain, because these subdomains are not registered right now

**Comment by BernhardDenner** [comment]
SSL certificate is now updated too, thus includes the now subdomains.

**Comment by markus2330** [comment]
Thank you! Subdomains are added.

(I also wrote you an email.)

**Comment by markus2330** [comment]
Stretch repos are the only missing item. The git repos for ftp/doc work wonderful!

**Comment by markus2330** [comment]
Automatic checkout of doc does not seem to work. Is it a problem if non-git files are lying around? (They are periodically copied from the build server).

**Comment by markus2330** [comment]
@BernhardDenner Any update here?

**Comment by markus2330** [comment]
Seems like we have an additional problem: The mailman Web interface is broken: I cannot subscribe/unsubscribe (seems to do a redirect to http when submitting form data)

**Comment by markus2330** [comment]
It would be great to have this running for 0.8.23. @ingwinlu what is the current status?

**Comment by ingwinlu** [comment]
I tried to get it to build debian packages in docker containers but did not get very far, mostly because I needed to revamp the current images (we need huge images to build all the debian packages because of all the dependencies).

Additionally the feedback on #1866 kept me busy and all the other 'urgent' stuff that I am assigned to.

**Comment by ingwinlu** [comment]
#1866 in itself might not be urgent. but whenever I need to add something like the homepage build or the debian packaging I have to test it locally. And this takes forever as my pc takes 15min+ to build elektra.

Having it merged would mean I could open new PR's for both of those tasks where we could discuss the problems that occur during them as well as have the ci system display the logs in an easily acceptable manner. This would make my life considerable easier.

**Comment by markus2330** [comment]
Yes, I am for merging it soon, too.

From my point of view only docu is misssing.

**Comment by markus2330** [comment]
Closing, because it is a duplicate from #1752. Other issue was migrated.
