### ISSUE TITLE
Stretch Debian Packages

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1752]
Elektra should provide Debian Packages for Stretch. Missing tasks:

- [ ] currently there is no way to download built packages. No webserver reachable at https://unstable.libelektra.org/elektra-stable/.
- [ ] stretch debian packages not provided: the [stretch build job](https://build.libelektra.org/jenkins/job/elektra-git-buildpackage-stretch/) fails. (see details below)

https://build.libelektra.org/jenkins/job/elektra-git-buildpackage-stretch/60/consoleFull was the last working build:

```
Now signing changes and any dsc files...
 signfile dsc elektra_0.8.20-1.601.dsc Autobuilder <autobuilder@libelektra.org>

 fixup_buildinfo elektra_0.8.20-1.601.dsc elektra_0.8.20-1.601_amd64.buildinfo
 signfile buildinfo elektra_0.8.20-1.601_amd64.buildinfo Autobuilder <autobuilder@libelektra.org>

 fixup_changes dsc elektra_0.8.20-1.601.dsc elektra_0.8.20-1.601_amd64.changes
 fixup_changes buildinfo elektra_0.8.20-1.601_amd64.buildinfo elektra_0.8.20-1.601_amd64.changes
 signfile changes elektra_0.8.20-1.601_amd64.changes Autobuilder <autobuilder@libelektra.org>

Successfully signed dsc, buildinfo, changes files
```

Since then the builds fail with the error (for example in https://build.libelektra.org/jenkins/job/elektra-git-buildpackage-stretch/61/consoleFull):

```
Now signing changes and any dsc files...
 signfile dsc elektra_0.8.20-1.611.dsc Autobuilder <autobuilder@libelektra.org>
gpg: skipped "Autobuilder <autobuilder@libelektra.org>": No secret key
gpg: /tmp/debsign.G9D2mEED/elektra_0.8.20-1.611.dsc: clear-sign failed: No secret key
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1045:
running debsign failed
gbp:error: 'debuild -i -I -sa' failed: it exited with 29
```

Was the key somehow removed?

**Comment by markus2330** [comment]
0.8.22 is a pseudo-milestone, it would be great to have the fix earlier.

**Comment by markus2330** [comment]
@BernhardDenner Any update here?

**Comment by markus2330** [comment]
basically a duplicate of #1742

**Comment by markus2330** [comment]
@ingwinlu Could you please write about the new Jenkinsfile in the release notes (as highlight 3). Please also write about that Debian Packages are again available and how to get them. (the main README.md needs to be updated, too) That would help a lot for the release!

**Comment by markus2330** [comment]
see also #1974

**Comment by ingwinlu** [comment]
What do you want changed in the main README.md? @markus2330

**Comment by markus2330** [comment]
I forgot that we moved the lines to doc/INSTALL.md.
