### ISSUE TITLE
multifile plugin depends on fts.h not available everywhere

### ISSUE THREAD

**Issue by haraldg** [ElektraInitiative/libelektra#1757]
## Steps to Reproduce the Problem

try compiling libelektra with musl libc - like crosscompiling for OpenWRT:  
The file `fts.h` is not found

It seems some people have a grudge against the fts* interface:
https://wiki.musl-libc.org/faq.html

## System Information

- Elektra Version: 0.8.21
- Versions of other relevant software?

## log output
```
[ 42%] Building C object src/plugins/multifile/CMakeFiles/elektra-multifile-objects.dir/multifile.c.o
/home/lambda/olinuxino/openwrt/build_dir/target-arm_arm926ej-s_musl-1.1.15_eabi/elektra-0.8.21/src/plugins/multifile/multifile.c:15:17: fatal error: fts.h: No such file or directory
compilation terminated.
src/plugins/multifile/CMakeFiles/elektra-multifile-objects.dir/build.make:62: recipe for target 'src/plugins/multifile/CMakeFiles/elektra-multifile-objects.dir/multifile.c.o' failed
make[5]: *** [src/plugins/multifile/CMakeFiles/elektra-multifile-objects.dir/multifile.c.o] Error 1
```

**Comment by markus2330** [comment]
Thank you for reporting!

As temporary fix you can add `-multifile` to `PLUGINS` in cmake (to exclude the plugin which does not compile).

For the next release, we will add a check for this header file and remove the plugin multifile automatically on absence of the header file. Or do you think that the functionality of the multifile plugin is needed for musl targets?

**Comment by haraldg** [comment]
I don't know of any usecase for this plugin ATM - so probably not. OTOH almost any software can run on musl targets, so if applications start using elektra and start using this plugin it might become an issue in the future. I wouldn't bother about this for now, but maybe it makes sense to look into why peope dislike this API before deciding how to proceed.
