### ISSUE TITLE
Elektra-web 1.2 tasks

### ISSUE THREAD

**Issue by omnidan** [ElektraInitiative/libelektra#1759]
- [x] search works like a filter of already expanded/loaded items right now, it doesn't search through the whole configuration tree - this is performance expensive as we'd have to `kdb get` on every key... might make more sense once elektrad is replaced with an actual api -> https://github.com/elbywan/bosket/issues/20
- [x] setting validation regex and message when editing metadata
- [x] setting negative numbers does not work. in the kdb command, this translates to `kdb set key "-6"`, but even with the `"` kdb still picks `6` up as an option, not the value.
- [x] implement read-only/disabled keys (+ configuration via metadata)
- [x] always display `description` (where?), display `example` as placeholder for text fields
- [x] debounce requests when editing metadata and data (e.g. description field, etc), reduces load on the server/API
- [x] move api to /api/ to fix routing issues
- [x] implement css fallback for firefox esr
- [x] fix anchors for icon buttons
- [x] show "loading..." instead of "no results found" when no data is available yet

@markus2330 reported:

- [x] fix and test Firefox+FirefoxESR
- [x] it is not possible to mark text (in value)
- [x] some way to copy&paste the full key name/value missing?
- [ ] custom field to create ranges (instead of putting them in as a string)
- [ ] please avoid special syntax to specify enums (please add some interface where new valid enum entries can be added). Please also use new syntax (check/enum/#). And make sure to change `check/type` accordingly when enum is set.
- [x] not possible to add further arbitrary metadata
- [x] support for some more metadata such as check/range (to specify integer ranges)
- [x] values might be invalid after the type has been changed (warning? especially irritating when changing to checkbox because then the actual value is not visible anymore)
- [x] no hints when hoovering the symbols
- [x] how to reload config from disk? And better feedback if everything was already written out?

Fosdem:

-  [x] The webUI seems to have several problems with keys that were removed earlier (outside the WebUI). Refreshing does not work as expected.
- [x] Firefox rendering is quite broken.
- [x] Subkeys (parentkeys) containing values are not rendered properly. (e.g. /parent = 1, and /parent/key = 2, the 1 is not displayed correctly).

**Comment by markus2330** [comment]
Thank you for reporting the issues! I'll add further issues here if I find them and if this is okay for you.

> elektrad is replaced with an actual api

As long as you need to requests for every key individually it might be quite expensive. You need some way to export a whole tree with a single API call. Didn't we discuss such export capabilities?

> setting negative numbers does not work. in the kdb command, this translates to kdb set key "-6", but even with the " kdb still picks 6 up as an option, not the value.

This should be a trivial fix: Add `--` as parameter to indicate that no flags follow. And you should use single quotes `'` to avoid escaping problems of `!~$` and so on.

>  always display description (where?)

As hover text sounds reasonable. Maybe also add a ? icon to indicate that a hover text exists?

**Comment by markus2330** [comment]
As discussed, please test with Firefox+FirefoxESR. (I added the point above)

**Comment by markus2330** [comment]
I quickly tested the webUI a bit with chromium and reported some problems I found (also see above):

- [ ] fix and test Firefox+FirefoxESR
- [ ] it is not possible to mark text (in value)
- [ ] some way to copy&paste the full key name/value missing?
- [ ] please avoid special syntax to specify enums (please add some interface where new valid enum entries can be added). Please also use new syntax (check/enum/#). And make sure to change `check/type` accordingly when enum is set.
- [ ] not possible to add further arbitrary metadata
- [ ] support for some more metadata such as check/range (to specify integer ranges)
- [ ] values might be invalid after the type has been changed (warning? especially irritating when changing to checkbox because then the actual value is not visible anymore)
- [ ] no hints when hoovering the symbols
- [ ] how to reload config from disk? And better feedback if everything was already written out?

It would be great if it works with Firefox so that I can also do some testing there.

**Comment by markus2330** [comment]
We tried to do preparations for the FOSDEM presentation.

-  [ ] The webUI seems to have several problems with keys that were removed earlier (outside the WebUI). Refreshing does not work as expected.
- [ ] Firefox rendering is quite broken.
- [ ] Subkeys (parentkeys) containing values are not rendered properly. (e.g. /parent = 1, and /parent/key = 2, the 1 is not displayed correctly).

Can you fix this?

**Comment by omnidan** [comment]
Firefox 53+ works fine. Unfortunately, css masks are only supported from firefox 53 (and ESR is 52), which is why ESR only renders black bars. Furthermore, ESR renders quite slow compared to the newer firefox versions. I will look into ESR support again later. However, it is not a priority right now.

**Comment by markus2330** [comment]
Thank you for looking into it. For me Firefox ESR is the standard browser thus I always check with it first. Would be great to get it fixed.

I thought such problems are only of the past. I am looking forward to read about the details how the rendering works and how this can cause problems in any browser.

**Comment by omnidan** [comment]
@markus2330 I added a workaround for all browsers that do not support css `mask`, which fixes the issue on Firefox ESR. I also finished almost all the tasks, so elektra-web is ready for the usability test now. I will create a MR with all the changes tomorrow.

**Comment by markus2330** [comment]
Great! I'll look at it asap, so that you can start the usability test soon.

**Comment by omnidan** [comment]
@markus2330 you can check out the latest version on https://github.com/omnidan/libelektra/tree/elektra-web1.2

**Comment by markus2330** [comment]
Please create a PR, it is easier for discussions.

**Comment by omnidan** [comment]
@markus2330 -> #1839

**Comment by markus2330** [comment]
moved tasks to #1845
