### ISSUE TITLE
keyIsDirectBelow fails for escaped keys

### ISSUE THREAD

**Issue by fberlakovich** [ElektraInitiative/libelektra#176]
During the implementation of an ini feature I encountered a bug in `keyIsDirectBelow`. The following testcase fails
```
succeed_if (keyIsDirectBelow(
		keyNew("user/tests/ini-section-write", KEY_END),
		keyNew("user/tests/ini-section-write/akey\\/looking\\/like\\/sections", KEY_END)),
		"keyIsDirectBelow does not work correctly");
```
This is because `keyisDirectBelow` uses strchr. My first idea to fix this would be to use something like this:
Instead of
```
if (!keyIsBelow(key, check)) return 0;
if (strchr(checkname + keysize, '/')) return 0;
```
I would use
```
if (!keyIsBelow(key, check)) return 0;
Key *temp = keyDup(check);
keySetBaseName(temp, 0);
int ret = 0;
ret = keyIsBelow(key, temp) ? 0 : 1;
keyDel(temp);
return ret;
```
However, this implementation is rather ineffecient. Can you come up with a better solution?

**Comment by markus2330** [comment]
Hello,

you wrote:
> During the implementation of an ini feature I encountered a bug in
> `keyIsDirectBelow`.

thank you! Basically every occurence of strchr and x[i] == '/' in Elektra is a 
bug. I have a branch where most of them are already fixed, but as discussed 
its not in a release state and the new mounting names are not backwards-
compatible and some test cases are still broken.

But if you are interested, I can push the branch to github. I am afraid I wont 
have time for it in January.

best regards,
Markus

**Comment by fberlakovich** [comment]
> But if you are interested, I can push the branch to github. I am afraid I wont have time for it in January.

No hurry. The ini tests pass with only `keyIsDirectBelow` fixed and this should be sufficient for the ini changeset. In the long term an efficient implementation is definitely the way to go. I close the issue as you are already aware of it and I assume your version is cleaner.

**Comment by markus2330** [comment]
I will reopen it so that I can recheck it for the release
