### ISSUE TITLE
Reduce number of default build jobs

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1763]
With "jenkins build all please" (a big thanks to @sanssecours for that) it seems to be overkill to build ~10 jobs per default (which are repeated on every push and when saying "jenkins build all please"). I propose to reduce these default jobs to 2-3 jobs:

- jenkins build fast please
- jenkins build stable please
- jenkins build unstable please

Maybe we can even get rid of "fast". Is this job useful? (The idea was to give some quick feedback.)

We should also document which jobs are built by default.

**Comment by sanssecours** [comment]
I am definitely in favor of adding less Jenkins build jobs by default. Two to three jobs sounds like a good idea. I would vote for

- `elektra-mergerequests-fast`,
- `elektra-gcc-configure-debian-log`, and
- `elektra-ini-mergerequests`

. 

# Rationale

- The build job `elektra-mergerequests-fast` should finish fast and therefore immediately tell us if there is a bigger problem with the pull request. 
- Both `elektra-gcc-configure-debian-log` and `elektra-ini-mergerequests` use configurations that are not that common. These jobs should help us to discover problems that the Travis build jobs did not already uncover.

**Comment by markus2330** [comment]
I fully agree to use build configurations that are more diverse and thus more likely to fail.
- `elektra-gcc-configure-debian-log` or even `elektra-gcc-configure-debian-debug` are definitely important in order to get more developers to use these build configurations.
-  `elektra-ini-mergerequests`, however, gets obsolete after we have #1755 merged. We might want a multi-configuration build job with different default storage plugins as replacement but it seems to me to be heavyweight to be always used.

What `jenkins build (un)stable please` has is:

- code coverage analysis (https://doc.libelektra.org/coverage/mergerequest/)
- valgrind memcheck

Are these features we need for every PR change?

**Comment by sanssecours** [comment]
> Are these features we need for every PR change?

I think the code coverage analysis is not that important. The Valgrind memory checks are interesting, although the ASAN enabled Travis build should find most memory related problems already. Anyway, it seems `elektra-gcc-configure-debian-log` already uses Valgrind. I therefore vote we use

- `elektra-mergerequests-fast` and
- `elektra-gcc-configure-debian-log` 

as default build jobs.

**Comment by markus2330** [comment]
Yes, sounds perfect. If you find some time, would you please deactivate the other jobs so that they are not build without explicit command?

**Comment by markus2330** [comment]
Btw. when you are changing jobs please also add yourself as admin so that you are also able to confirm by saying "add to whitelist".
