### ISSUE TITLE
Header files of libtool installed incorrectly

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#177]
The header files related to merging are located in a subfolder "merging". However, they are not installed in such a subdirectory. So trying to include them fails when Elektra is installed.

I would propose to not add them in the public API at all, but instead only provide the simple new high-level API we discussed.

Additionally, files should ideally be prefixed with kdb, because elektra enforces the user to put /usr/include/elektra into the include path (otherwise recursive inclusion fails). So I would suggest kdbmerge.h as new name for the high level merge API.

**Comment by fberlakovich** [comment]
Should the private headers (e.g. automergestrategy.hpp) also be renamed (e.g. kdbautomergestrategy.hpp)? Am I right that making those headers private simply means not installing them via CMake?

In addition I would be glad to make them public again somewhere in the future when the merge API is more mature. The whole framewwork was designed from ground up to be highly flexible and modular and removing this flexibility by hiding the building blocks hurts. However, I totally understand that the framework is currently hard to use and the headers won't be of any use at the moment.

**Comment by markus2330** [comment]
Hello,

you wrote:
> Should the private headers (e.g. automergestrategy.hpp) also be renamed
> (e.g. kdbautomergestrategy.hpp)? Am I right that making those headers
> private simply means not installing them via CMake?

Not installing it is the most private way. kdbprivate.h is only installed, 
because the data structures are needed by debuggers.

> In addition I would be glad to make them public again somewhere in the
> future when the merge API is more mature. The whole framewwork was
> designed from ground up to be highly flexible and modular and removing
> this flexibility by hiding the building blocks hurts. However, I totally
> understand that the framework is currently hard to use and the headers
> won't be of any use at the moment.

I would be glad to have that API with more flexibility once the issues are 
resolved. Having two different APIs for the same thing is also not ideal, thus 
hiding the other is the best thing at the moment (also considering that hiding 
is the least effort). Do you agree?

best regards, Markus

**Comment by fberlakovich** [comment]
> Having two different APIs for the same thing is also not ideal, thus hiding the other is the best thing at the moment (also considering that hiding is the least effort). Do you agree?

Yes, absolutely.

**Comment by markus2330** [comment]
I installed all files because kdb.h is the only file that guarantees compatibility anyway.
