### ISSUE TITLE
Plugin ruby: testscr_check_kdb_internal_check fails

### ISSUE THREAD

**Issue by waht** [ElektraInitiative/libelektra#1771]
## Steps to Reproduce the Problem

When compiling Elektra with `ENABLE_LOGGER=ON` and `PLUGINS=ALL` (including the ruby plugin) the test `testscr_check_kdb_internal_check` fails with the following message:

```
        Start 112: testscr_check_kdb_internal_check
112/192 Test #112: testscr_check_kdb_internal_check .........***Failed    1.06 sec

ELEKTRA KDB INTERNAL TEST SUITE

Check if script tests the correct version
error: check of plugin ruby produced: "src/plugins/ruby/ruby.cpp:475:libelektra_Ruby_LTX_elektraPluginOpen: could not init ruby environment"
testscr_check_kdb_internal_check.sh RESULTS: 182 test(s) done 1 error(s).
```

Upon investigation it seems like the error was masked by `ELEKTRA_LOG_WARNING` (located in ruby.cpp at line 475) because when I replace the line with `exit (-1)` the test fails without `ENABLE_LOGGER`.

## System Information

- Elektra Version: master
- Reproducable on Debian stretch and Docker
- ruby 2.3.3

## Further Log Files and Output
- https://build.libelektra.org/jenkins/job/elektra-gcc-configure-debian-log/1109/consoleFull

**Comment by markus2330** [comment]
Thank you for looking into it. Doesn't reducing the severity of the log output (to DEBUG) solve the issue?

**Comment by waht** [comment]
I did some testing and found out that the ruby plugin requires the swig_ruby bindings. I would suggest adding this to the readme and build script.
I would include this in my current PR since I would need to change build script afterwards anyway.

**Comment by markus2330** [comment]
Thank you, it is indeed a strange error for a missing binding. I expected that the initialization of the ruby environment has nothing to do with the binding. Thanks for fixing it!

**Comment by waht** [comment]
It makes sense because the `kdb` module provided by the `swig_ruby` binding is used by plugins written in Ruby to access the key database.

The line in `init_ruby_environment()` actually was: 
```C
ELEKTRA_ADD_WARNING (ELEKTRA_WARNING_RUBY_GEN_WARN, warningsKey, "could not load Ruby module 'kdb'");
```
But the warning was not printed.

I updated README and build script in #1515.
