### ISSUE TITLE
Use libelektra as branding name on website

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1778]
# Proposal

Since this repository does not only contain `libelektra` but also SpecElektra and other tools it would make sense to rename it to `elektra`. This should be easily doable via the settings tab.

## Advantages

- Three letters less to type
- The name of the repository matches with the assumptions stated in the [glossary](https://github.com/ElektraInitiative/libelektra/blob/master/doc/help/elektra-glossary.md)

## Disadvantages

- Possibly broken links

Most of the links should be fine though, since we used `master.libelektra.org` in large parts of the documentation. I think the most used and afterwards possibly broken link would be the one of the [git repo](https://github.com/ElektraInitiative/libelektra.git). However, I renamed [my copy of the repo](https://github.com/sanssecours/elektra) to `elektra` and cloning using the [old repo address](https://github.com/sanssecours/libelektra.git) still works. The link to the [old GitHub page of my repo](https://github.com/sanssecours/libelektra) works fine too.

**Comment by markus2330** [comment]
Thank you! I like the proposal! Maybe we can combine this rename together with a new website URL. (Where we also should drop the *lib*.)

I still did not find any nice and affordable top-level domain where we could get the name ".elektra".

Another suggestion would be to take the name ".elektra-initiative" (available for most top-level domains like ".org") but this has several drawbacks:

- for two words you never know how they are separated
- it is much longer
- initiative can easily be misspelled

**Comment by sanssecours** [comment]
> I still did not find any nice and affordable top-level domain where we could get the name ".elektra".

I just checked Google Domains. Below are some of the available domains I found. I am not really sure if I like any of those though:

![domains](https://user-images.githubusercontent.com/691989/34906387-004593be-f86d-11e7-9824-507411506b65.png)

. I think `elektra.dev` might be a good domain name, however `.dev` is [not yet available](https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains#D_2).

**Comment by markus2330** [comment]
I am also not really sure about any of these. "elektra.rocks" has the best price 😄

> I think `elektra.dev` might be a good domain name, however `.dev` is [not yet available](https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains#D_2). 

Google is the operator, so let us see if it will be available for public at all.

**Comment by markus2330** [comment]
elektra.software and elektra.community would be other options

**Comment by markus2330** [comment]
@mpranj what is your thought on this? Now is a quiet time, we could do it (if wanted).

**Comment by mpranj** [comment]
I also like the proposal and agree that it's a great time to implement it. If/when we do it I would still keep "libelektra.org" as well. There's probably tons of links and it makes no sense to let somebody else do something malevolent with the domain.

**Comment by markus2330** [comment]
Yes, we can keep the libelektra.org domain for some time. Unfortunately, hetzner domain registration only allows .de, .com, .net, .org, .info, .biz, .eu, .at, .co.at, .or.at; which are afaik taken. Which domain do we want and where can we register it?

**Comment by mpranj** [comment]
Hetzner has two services: domain registration robot and KonsoleH. In KonsoleH (separate account needed afaik) you can register many more domains. I'll take a look until the next meeting if I find some name suggestions. Of the mentioned I like elektra.dev the most.

**Comment by markus2330** [comment]
Ahh, I didn't know that. Will everything go to the same bill nevertheless?

**Comment by mpranj** [comment]
> Will everything go to the same bill nevertheless?

I think they count it as separate customers so the bill is separate for me. Not sure if that can be unified.

**Comment by markus2330** [comment]
@mpranj ping, did you have time to look?

At the moment I like most (in this order):

- elektra.software
- elektra.community
- elektra.systems
- elektra.dev
- elektra.works

Alternatively, we could use "libelektra" on our website as the name for our software. (And not only the libraries but the whole framework, including tools, code generation, ....) At the moment there is no occurrence of the string "libelektra" on the homepage of the Website.

Switching to "libelektra" might be the better idea anyway as:

- it fixes #1778
- no troubles with trademarks/companies of the same name (http://see-ip.patentamt.at and http://tmsearch.uspto.gov do not find anything about libelektra)

**Comment by mpranj** [comment]
I did take a look months ago, but I did not like anything else really.

> Switching to "libelektra" might be the better idea anyway as:

Over time I got so used to libelektra.org so I am likely biased, but I actually like the current domain.
