### ISSUE TITLE
setup.hs compilation error

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1782]
Seems like I merged the PRs too early.

On Debian Stretch the compilation failed:
```
dist/setup/setup.hs:141:11: error: parse error on input ‘->’
src/bindings/haskell/CMakeFiles/c2hs_haskell.dir/build.make:71: for „src/bindings/haskell/libHSlibelektra-haskell-ghc8.0.1.so“ failed
make[2]: *** [src/bindings/haskell/libHSlibelektra-haskell-ghc8.0.1.so] Error 1
```

And there is also a new warning:
```
CMakeFiles/elektra-pluginprocess.dir/pluginprocess.c.o: In function `getPipename':
/home/markus/Projekte/Elektra/current/src/libs/pluginprocess/pluginprocess.c:272: warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
[ 82%] Built target elektra-pluginprocess
```

**Comment by e1528532** [comment]
could you please state your ghc and cabal versions? Most likely that is some version difference. We should probably also introduce a haskell test to be executed on the debian platforms, currently its only really tested on mac like i use for developing. I think i should set up a debian vm additionally.

The latter issue can be avoided by creating a temporary directory instead and placing the pipe files into there. i'll take care about that.

**Comment by markus2330** [comment]
Thank you for the quick response. I use the versions from Debian Stretch.

```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1

$ cabal --version
cabal-install version 1.24.0.1
compiled using version 1.24.1.0 of the Cabal library
```

> I think i should set up a debian vm additionally.

This should be easily done with the docker builds. But I am also okay to install ghc and cabal on every agent (or at least on these where we plan to support it. Maybe Jessie is already too old. We should support stretch, though.).

**Comment by e1528532** [comment]
that should be covered by #1787 and checked via the new haskell build job on v2. closing.

**Comment by markus2330** [comment]
very good that so many bugs are being closed right now :-)
