### ISSUE TITLE
security: vulnerable dependency

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1786]
Hello Marvin,

Can you easily update the version number for jquery?

src/tools/rest-frontend/package.json

Known  moderate severity security vulnerability detected in jquery < 3.0.0 defined in package.json. 

best regards,

**Comment by markus2330** [comment]
Thank you for the fast reply.

The warning was generated from GitHub, I gave you also the access to these security messages (should be in "Inights"). I also forwarded you the email I got from GitHub.

**Comment by Namoshek** [comment]
Nope, not seeing the vulnerabilities, only the dependency graph. However, I have a concrete clue about updating jQuery now. I will have a look at it but I cannot promise anything as I cannot check the stuff easily as I still couldn't get back my dev VM.

**Comment by Namoshek** [comment]
Couldn't get anything working yesterday, so I figured it might be worth trying to just increment the version on it's own. If it doesn't work, we can just go ahead and undo the changes.
