### ISSUE TITLE
reduce error information for common errors

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1789]

**Comment by Piankero** [comment]
What exactly should I do here? You referenced this issue in #2333 but with a checkmark on the task

**Comment by markus2330** [comment]
This is actually already implemented with the `-d` and `-v` options.

@kodebach once said that it would be much better if we only have `-v`. For me open is a tutorial/docu/guide about how tools should provide `-d` and `-v`. (When to output which parts of warnings/errors).

**Comment by Piankero** [comment]
This issue is unrelated to visible error messages.
As discussed in the Elektra meeting I may unassign myself.

**Comment by markus2330** [comment]
This is very much related to visible error messages but it is already implemented (by you)
