### ISSUE TITLE
building with cmake 3.10 on macOS breaks elektra

### ISSUE THREAD

**Issue by e1528532** [ElektraInitiative/libelektra#1790]
## Steps to Reproduce the Problem

Compile Elektra in any configuration using cmake 3.10 on macOS. Then install elektra and try running the kdb tool.

## Expected Result

I expect everything to work fine.

## Actual Result

KDB is unable to load any plugins, not even the resolver, thus nothing works. The rpaths seemed fine on a first glance though when i checked them with `otool -l`.

Then i tried it in a new build directory and had the same result (before i just ran cmake again in my exiting build). At some point i noticed that i've recently upgraded cmake and that this might be the cause, so i went back to cmake 3.9.6. Then everything worked again.

## System Information

- Elektra Version: master
- cmake 3.10.2 (latest on homebrew)
- macOS 10.12.6 (I haven't tried it on linux, maybe its the same there)

## Further Log Files and Output

Please request if required, however i feel like one has to try this out yourself.

**Comment by sanssecours** [comment]
Thank you for the bug report. Looks like everything works fine on my machine:

- macOS 10.13.2
- CMake 3.10.2

. Did you by any chance [enable ASAN](https://github.com/ElektraInitiative/libelektra/issues/1569)?

**Comment by e1528532** [comment]
hmm, today i tried it again and i cannot reproduce it anymore. Restarted my laptop in between though, which i haven't done yesterday so maybe its because of that? I can confirm that with asan it does not work but i am pretty sure i made a brand new build to ensure its not a misconfiguration. Anyway, closing this for now. I'll reopen it if i manage to reproduce it again.
