### ISSUE TITLE
invoke error messages

### ISSUE THREAD

**Issue by e1528532** [ElektraInitiative/libelektra#1795]
Currently i have the issue that there is [one build](https://travis-ci.org/ElektraInitiative/libelektra/jobs/334161623) where apparently opening the dump plugin with kdbinvokefor the process plugin fails and returns null. The exact line that causes this behavior is line 334 of pluginprocess.c in that PR's branch, and its called like `pp->dump = elektraInvokeOpen ("dump", 0);` that returns 0 there.

However, i can't reproduce this locally neither in my debian vm nor on mac, on other builds it seems to work as well. So i wondered if there is some way to get a more detailled output why invokeOpen fails on the build server?

**Comment by e1528532** [comment]
> From which PR did you trigger the build?

Sorry i thought its clear from the context by my link. It happens in the process branch/PR.

> Seems you improved that already in your PR.

Yes, the process plugin is a very good example to mature the pluginprocess library further.

> Seems like we need to modify the elektraInvokeOpen interface so that we can get these error/warnings.

Should i go forward with a proposal for that? I think its useful in general, if elektraInvokeOpen fails you'd probably want to see the error messages.

**Comment by markus2330** [comment]
>  Sorry i thought its clear from the context by my link. It happens in the process plugin branch/PR.

Ahh, I did not see that the PR number is written within the build job page.

>   Should i go forward with a proposal for that? I think its useful in general, if elektraInvokeOpen fails you'd probably want to see the error messages.

Yes, that would be great. To not have a key with the error messages is an oversight, there should be definitely a way to pass this information to the caller.

**Comment by e1528532** [comment]
closed in #1801
