### ISSUE TITLE
Multiple builds fail due to race condition in one test

### ISSUE THREAD

**Issue by e1528532** [ElektraInitiative/libelektra#1805]
## Steps to Reproduce the Problem

On the build server we have a new node which can basically execute several builds in parallel. Basically just launch a multiconfig-gcc47-cmake-options build.

## Expected Result

I expect that all builds pass.

## Actual Result

The subbuilds of the multiconfig build sometimes fail due to a race condition in `testscr_check_distribution` as it creates a file in /tmp, so multiple builds can't run the tests at the same time due to this.

```
Check if script tests the correct version
Testing sibling
  Check distribution of system/tests/script/distribution/a1 and system/tests/script/distribution/b2
fatal (no cleanup necessary): /tmp/file1 already exists
```

Maybe it is possible do create a temporary directory with mktemp and do the tests inside there to avoid this race condition?

In any way I've limited the number of builds back to 1 for the new node in the meanwhile, though its capable of more which we should utilize if possible.

**Comment by markus2330** [comment]
Thank you for reporting this problem!

It was never noticed before and we already have parallel builds since quite a long time so it might be a quite rare situation. (multiple testscr_check_distribution need to start concurrently).

> Maybe it is possible do create a temporary directory with mktemp and do the tests inside there to avoid this race condition?

Yes, that is a good suggestion!
