### ISSUE TITLE
Fails to build on aarch64: test_meta.c:345:2: error: impossible constraint in 'asm'

### ISSUE THREAD

**Issue by jirutka** [ElektraInitiative/libelektra#1811]
## Steps to Reproduce the Problem

```
CFLAGS="-Os -fomit-frame-pointer"
CXXFLAGS="-Os -fomit-frame-pointer"
LDFLAGS="-Wl,--as-needed"

mkdir build
cd build
cmake .. \
    -DCMAKE_BUILD_TYPE=MinSizeRel \
    -DCMAKE_C_FLAGS_MINSIZEREL_INIT="$CFLAGS" \
    -DCMAKE_CXX_FLAGS_MINSIZEREL_INIT="$CXXFLAGS" \
    -DCMAKE_EXE_LINKER_FLAGS_MINSIZEREL_INIT="$LDFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_RPATH=/usr/lib/elektra \
    -DTARGET_PLUGIN_FOLDER=elektra \
    -DCMAKE_VERBOSE_MAKEFILE=OFF \
    -DBUILD_DOCUMENTATION=OFF \
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_STATIC=OFF \
    \
    -DENABLE_DEBUG=OFF \
    -DENABLE_LOGGER=OFF \
    -DINSTALL_TESTING=OFF \
    -DBINDINGS='cpp;glib;swig_lua;swig_python;swig_ruby' \
    -DPLUGINS='ALL;-EXPERIMENTAL;-journald;-wresolver;-xerces;-yamlcpp' \
    -DTOOLS='kdb;qt-gui'
make
```

## Expected Result

Elektra should be successfully built without errors (as on x86_64 and x86).

## Actual Result

```
[ 92%] Building CXX object src/libs/tools/tests/CMakeFiles/testtool_umount.dir/testtool_umount.cpp.o
[ 92%] Building CXX object src/libs/tools/tests/CMakeFiles/testtool_comparison.dir/testtool_comparison.cpp.o
[ 92%] Linking CXX executable ../../bin/test_plugin
/home/buildozer/aports/testing/elektra/src/libelektra-0.8.21/tests/ctest/test_meta.c: In function 'rdtsc':
/home/buildozer/aports/testing/elektra/src/libelektra-0.8.21/tests/ctest/test_meta.c:345:2: error: impossible constraint in 'asm'
  __asm__ __volatile__("rdtsc" : "=a"(lo), "=d"(hi));
  ^~~~~~~
```

## System Information

- Elektra Version: 0.8.21 (with patch #1761 and [cmake-allow-override-rpath.patch](https://github.com/alpinelinux/aports/blob/master/testing/elektra/cmake-allow-override-rpath.patch))
- compiler: gcc 6.4.0 (with PaX)
- libc: musl 1.1.18
- OS: Alpine Linux Edge
- Arch: aarch64

## Resources

- Alpine abuild for Elektra: [testing/elektra/APKBUILD](https://github.com/alpinelinux/aports/blob/master/testing/elektra/APKBUILD).

**Comment by markus2330** [comment]
Thank you, that is great that a variety of architectures are tested! And the bug report is flawless, thank you for that, too.

Elektra was already built successfully on all architectures Debian supports but we added a hash map recently (#1730) which might have problems on non-x86 platforms. If you run into troubles with this code, you can disable ENABLE_OPTIMIZATIONS. We would love to get feedback if the new hash map works on aarch64 (and other architectures).

For this concrete build error it seems that @tom-wa forgot to remove some benchmark code. I removed the offending code in 63150f65b7aaee160e4615a127c2eff21c36e75e

As workaround you also could have set BUILD_TESTING to OFF. 

Please report if now everything compiles.

**Comment by jirutka** [comment]
My colleague has meanwhile fixed the build by removing offended assembly, see [patch](https://github.com/alpinelinux/aports/blob/32c3ea7c918f4083be4b5e27cbed8e28fdf5929e/testing/elektra/remove-unneeded-assembly.patch).

> I removed the offending code in 63150f65b7aaee160e4615a127c2eff21c36e75e

Commit with such hash does not exist.

> Please report if now everything compiles.

After applying the mentioned patch, it builds successfully on x86, x86_64, aarch64 and ppc64le (armhf is in queue). However, some tests currently fail (on all architectures) – I’ll investigate them later.

Alpine package [elektra](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/elektra) is currently available in the testing branch. I’ve packaged each plugin and binding in a separate subpackage (except cpp). I also reused `infos/provides`, so user can install e.g. `elektra-storage-ini` and apk will pull `elektra-dini` (subpackage providing storage-ini with the highest priority; priorities are set statically in APKBUILD).
So, I kept my promise from FOSDEM to create Alpine package for Elektra ASAP. 😸

**Comment by markus2330** [comment]
>  Commit with such hash does not exist.

Sorry, origin had changed and thus the push did not work (and I was in a rush). I now applied the patch in a20d8a0226f87265d3e8219da92afffe75b09047 (and pushed successfully 😄). I also added Timo Teräs in the release notes (see 5114e72b529735a850ff01eba09c6e8aab851a77).

>  it builds successfully on x86, x86_64, aarch64 and ppc64le (armhf is in queue)

Great to hear that.

> However, some tests currently fail (on all architectures) – I’ll investigate them later.

Most likely the kdb tests do not work as they need to write into the system (and need root privileges). If you want to avoid that, you can use `make run_nokdbtests` or see [TESTING.md](http://master.libelektra.org/doc/TESTING.md) for other methods.

> Alpine package elektra is currently available in the testing branch. I’ve packaged each plugin and binding in a separate subpackage (except cpp). I also reused infos/provides, so user can install e.g. elektra-storage-ini and apk will pull elektra-dini (subpackage providing storage-ini with the highest priority; priorities are set statically in APKBUILD).

That modularity and clever use of infos/provides is great! I added the link about the package in 6f4cd7d72da0b85b60fbd0761fe937686bbcc694

> So, I kept my promise from FOSDEM to create Alpine package for Elektra ASAP. 😸

Thank you so much. Please tell us when it hits the stable repo, so that we can update the link.

**Comment by markus2330** [comment]
@jirutka Is there any progress with the Alpine packages? Our build server now also tests on Alpine, so we hopefully will not have any regressions on your distro.

I'll close this issue as the initial problem is now fixed.
