### ISSUE TITLE
Arrays should contain last index

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#182]
For arrays, the metakey "array" of the "root key" of the array should contain the last index.

```
#@META array = #2
user/array
user/array/#0 = some value
user/array/#1 = other value
user/array/#2 = last entry
```

See also https://www.libelektra.org/decisions/array

This allows:

- robust detection of what an array is
- easier iterating
- easier appending of elements
- empty arrays (having metadata "array" without content")

Affected components:

- [ ] yajl
- [ ] API (elektraArrayIncName, elektraArrayGetNextKey)
- [ ] elektraMetaArrayToKS (see #2316)
- [ ] high-level API #1605 
- [ ] Web UI #2037 
- [ ] spec plugin (to automatically add array keys when something is validated as array)

Long term goal:

Drop the `#` syntax for arrays (only encode using `#` internally, but not for users).

**Comment by markus2330** [comment]
Alternative: metadata `array` to contain `#2`.

**Comment by markus2330** [comment]
The `array` metadata entry has following advantages:

- one can distuinigish an array with keys that are called by chance `#0`
- the metadata can also be used in the spec to validate that something really is an array (maybe also with cardinality/array size checks)
- empty arrays are easily possible, it would avoid hacks such as `###empty_array` used in yajl

**Comment by fberlakovich** [comment]
I prefer the metadata version. However, I would also like to shield as much code as possible from the array handling with a capable array library.

**Comment by markus2330** [comment]
To model the structure of hosts files nicely we would need arrays with a value, thus only metadata array would work. E.g.

```
ipv4/localhost = 127.0.0.1
ipv4/localhost/#0 = local # alias
```

**Comment by markus2330** [comment]
As already discussed shortly, we could also extend the escaping logic for key names and avoid the `_` prefixes. So it would be `#10`, and the (internally) unescaped version (see `keyUnescapedName`) would be `#_10` for correct sorting.

**Comment by markus2330** [comment]
As discussed in #2388 it would be even better if we escape `10` -> `#_10` (or maybe even completely without `#`) so that arrays cannot be interpreted as comment by the shell. Then we would have a variant of natural sorting, but efficient because internally we would only work with memcmp.
