### ISSUE TITLE
document enums

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1843]
Since #1836 enums unfortunately get collapsed by clang-format unless there is some documentation written for any enum member. So I hope we use this as motivation to write some documentation for all enums.

Especially there are some completely undocumented enums I did not know what they are for in src/plugins/crypto/crypto.h and src/plugins/crypto/gpg.c and  src/plugins/fcrypt/fcrypt.c

@petermax2 could you please fix this?

**Comment by petermax2** [comment]
> @petermax2 could you please fix this?

Of course! I'll fix it later today.

**Comment by petermax2** [comment]
Do you want to keep this issue open for other undocumented enums?

**Comment by markus2330** [comment]
No, afaik now all important ones are fixed. Thank you for reminding.
