### ISSUE TITLE
kdb ls -0: regression test missing

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1844]
kdb ls -0 and lsmeta -0 need to be used because (meta) keyname may contain a newline.

## Example

```
kdb setmeta user/metanew "m2                                                                                                                                                                                     
m3" "a  key with newline"
> kdb lsmeta user/metanew
#> m2
#> m3
```
`kdb lsmeta -0 user/metanew`

works as expected.

## System Information

- Elektra Version: master

**Comment by omnidan** [comment]
@markus2330 `kdb lsmeta -0` seems to work. however, `kdb ls -0` still returns keys separated by newlines (on Elektra 0.8.21).

I fixed metakeys with newlines by using `kdb lsmeta -0`.

**Comment by markus2330** [comment]
Thank you for reporting! This is a regression from @e1528532. I'll fix it in a minute.

@e1528532 Can you add a unit test for `kdb ls -0`?

**Comment by markus2330** [comment]
Should be fixed in 17ba5e3a343aeec9d408cfbe2607a4518580528c!

A trivial unittest would be to call something like `kdb ls -0 / | xargs -0n 1 echo "NL:"` in a shell recorder test.

**Comment by omnidan** [comment]
@markus2330 should I wait until the next release to change this from `kdb ls` to `kdb ls -0` in elektra-web? or should I change it right now (would break elektra-web if you're not using the latest elektra version)

**Comment by markus2330** [comment]
You can change this right now. We do not have any guarantee that software from master works together with older releases.

But please keep this issue open so that we do not forget to add the shell recorder test.

**Comment by omnidan** [comment]
I changed it in elektra-web 1.2!
