### ISSUE TITLE
Web UI: Ideas

### ISSUE THREAD

**Issue by omnidan** [ElektraInitiative/libelektra#1849]
Further ideas for improvements of Elektra Web:

## elektrad

- [x] avoid using CLI in elektrad (rewrite elektrad in C/C++?)
- [ ] if there is a spec key, its meta data should also apply to the keys with the same name in other name spaces
- [ ] listen to configuration changes

## webd&elektrad

- [ ] configuration of client within elektra-web
- [ ] show cascading key hierarchy
- [ ] import/export functionality
- [ ] mounting functionality
- [ ] support for changing binary keys
- [ ] apikey or other means of securing connection between webd&elektrad
- [ ] if keys in subtrees change for already visited subtrees, the subtrees are not updated
- [ ] undo of multiple items in "configure metadata" still does not work if "type" flags are changed?
- [ ] meta-data arrays are not supported
- [ ] this is particularly annoying when editing comments. It should be easy to add a new comment line (e.g. in hosts files)
- [ ] support concurrent editing
- [ ] how to input a newline in value or metadata?
- [ ] improved keyboard support (arrow keys)

**Comment by markus2330** [comment]
I updated this a bit and split tasks between elektrad and webd&elektrad

**Comment by markus2330** [comment]
I also added "support for binary keys" here because the feature is not really important as configuration usually is plain text.

**Comment by markus2330** [comment]
I added "if keys in subtrees change for already visited subtrees, the subtrees are not updated".

I changed the title to contain "web ui", otherwise the issue was hard to find.

**Comment by markus2330** [comment]
Let us go back to use cases and not simply implement random ideas.
