### ISSUE TITLE
creating key in spec namespace crashes

### ISSUE THREAD

**Issue by omnidan** [ElektraInitiative/libelektra#1852]
on latest elektra (master)

I tried adding a key to the spec namespace:

```
> kdb set spec/test
Create a new key spec/test with null value
```

but then I got the following error:

```
> kdb ls /

Sorry, I crashed by the signal SIGSEGV
This should not have happened!

Please report the issue at https://issues.libelektra.org/
fish: 'kdb ls /' terminated by signal SIGABRT (Abort)
```

This error happens on all further commands. It is also not possible to recover from this error via `kdb` anymore.

The solution is deleting the created spec key by deleting the `.../elektra/specification/default.ecf` file.

**Comment by omnidan** [comment]
duplicate of #1821?

**Comment by markus2330** [comment]
Sorry, I cannot reproduce:

```
kdb stash
kdb set spec/test
kdb ls /
#> spec/test
```

Are you sure that there are not some additional keys lying around?

**Comment by markus2330** [comment]
Could you please check if #1863 fixes the problem?
