### ISSUE TITLE
bug: list plugin & nested plugin configuration

### ISSUE THREAD

**Issue by waht** [ElektraInitiative/libelektra#1855]
I believe there is a bug in list plugin which which prevents configuration for globally mounted plugins.
I could reproduce the steps on 0.8.22.

## Steps to Reproduce the Problem

Step by step guide on how to reproduce the problem:

```sh
kdb gmount dbus announce=once

# monitor system bus in another shell
dbus-monitor --system

kdb set sytem/foo/bar 123
#> Create a new key system/foo/bar with string "123"
```

When using the plugin at a mountpoint everything works well.

## Expected Result

The dbus monitor should report "Commit" events since "announce=once" configured it to do so.

## Actual Result

The dbus monitor reports "KeyAdded" or "KeyChanged" events.
I was able to reproduce this with other plugins (zeromqsend & zeromqrecv from PR #1835) as well.

## System Information

- Elektra Version: master, 0.8.22

**Comment by waht** [comment]
The configuration is passed to the dbus plugin:
```
 user/config = 
 user/config/announce = once
```

Which should be afaik:
```
 user = 
 user/announce = once
```

**Comment by markus2330** [comment]
Thank you for reporting!

Yes, it looks a lot like #1783, was the problem in the process plugin also related to the list plugin?

We really should add plugin tests that check if passing arguments and so on works properly.

**Comment by markus2330** [comment]
Thank you for #1856.

It might be possible that I messed up and misunderstood where the list plugin reads its configuration from. This would require a change in backend.cpp:586.

@tom-wa Can you comment?

**Comment by waht** [comment]
Hm. The plugin documentation says that plugins are configured using `plugins/#/config/` so backend.cpp should be correct. I changed the line 586 so that plugin configurations are stored below `plugins/#` and it worked, but `plugins/#/config/` is better to avoid naming conflicts.

**Comment by waht** [comment]
I'm not sure if the problems in #1783 are related to this. As far as I can see there are no globally mounted plugins and the list plugin is not used.

**Comment by tom-wa** [comment]
>@tom-wa Can you comment?

i think the documentation is correct but i messed up the parsing.
