### ISSUE TITLE
COMPILE.md outdated

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#1859]
https://github.com/ElektraInitiative/libelektra/blob/master/doc/COMPILE.md#preparation seems to be outdated as cmake 3.0 is now the minimum requirement to prepare the build.

```
# grep -nrw -e "cmake_minimum_required" .
./src/bindings/gsettings/CMakeLists.txt:6:cmake_minimum_required (VERSION 3.0)
./doc/tutorials/hello-elektra.md:10:   cmake_minimum_required(VERSION 3.0)
./tests/gtest-1.7.0/CMakeLists.txt:1:cmake_minimum_required(VERSION 2.6.2)
./CMakeLists.txt:1:cmake_minimum_required (VERSION 3.0)
./examples/external/cmake/CMakeLists.txt:1:cmake_minimum_required(VERSION 2.6)
```

**Comment by markus2330** [comment]
Thank you for reporting!

There seem to be at least two problems:

- [ ] outdated COMPILE.md
- [ ] external/cmake/CMakeLists.txt advocating a cmake version, which might be too low

I created  #1860 to fix both problems.

Btw. some entries in COMPILE.md complier matrix are outdated, too. Please update them once the build server is cleaned up.
