### ISSUE TITLE
OS X build fixes

### ISSUE THREAD

**Issue by beku** [ElektraInitiative/libelektra#186]
The osx-01 branch contains some fixes. The state is not final. Build stops at around 60%. The commit format is not always best.

Here the current issue:
Linking CXX executable ../../../bin/kdb-static
cd /Users/kuwe/programme/oyranos/libelektra/build3/src/tools/kdb &&
/opt/local/bin/cmake -E cmake_link_script
CMakeFiles/kdb-static.dir/link.txt --verbose=1
/usr/bin/c++    -std=c++98  -Wno-deprecated-declarations
-Wstrict-null-sentinel -Wno-missing-field-initializers -Wold-style-cast
-Woverloaded-virtual  -Wsign-promo  -pedantic -Wno-variadic-macros -Wall
-Wextra -Wno-overlength-strings -Wsign-compare -Wfloat-equal
-Wformat-security -Wshadow -Wcomments -Wtrigraphs -Wundef
-Wuninitialized -O2 -g -DNDEBUG -Wl,-search_paths_first
-Wl,-headerpad_max_install_names   CMakeFiles/kdb-static.dir/check.cpp.o
CMakeFiles/kdb-static.dir/cmdline.cpp.o
CMakeFiles/kdb-static.dir/command.cpp.o
CMakeFiles/kdb-static.dir/convert.cpp.o
CMakeFiles/kdb-static.dir/cp.cpp.o
CMakeFiles/kdb-static.dir/export.cpp.o
CMakeFiles/kdb-static.dir/external.cpp.o
CMakeFiles/kdb-static.dir/file.cpp.o
CMakeFiles/kdb-static.dir/fstab.cpp.o
CMakeFiles/kdb-static.dir/get.cpp.o
CMakeFiles/kdb-static.dir/import.cpp.o
CMakeFiles/kdb-static.dir/info.cpp.o
CMakeFiles/kdb-static.dir/list.cpp.o CMakeFiles/kdb-static.dir/ls.cpp.o
CMakeFiles/kdb-static.dir/main.cpp.o
CMakeFiles/kdb-static.dir/merge.cpp.o
CMakeFiles/kdb-static.dir/mergehelper.cpp.o
CMakeFiles/kdb-static.dir/metaget.cpp.o
CMakeFiles/kdb-static.dir/metals.cpp.o
CMakeFiles/kdb-static.dir/metaset.cpp.o
CMakeFiles/kdb-static.dir/mount.cpp.o
CMakeFiles/kdb-static.dir/mountbase.cpp.o
CMakeFiles/kdb-static.dir/mv.cpp.o
CMakeFiles/kdb-static.dir/remount.cpp.o
CMakeFiles/kdb-static.dir/rm.cpp.o CMakeFiles/kdb-static.dir/set.cpp.o
CMakeFiles/kdb-static.dir/sget.cpp.o
CMakeFiles/kdb-static.dir/shell.cpp.o
CMakeFiles/kdb-static.dir/test.cpp.o
CMakeFiles/kdb-static.dir/umount.cpp.o
CMakeFiles/kdb-static.dir/validation.cpp.o  -o ../../../bin/kdb-static
../../../lib/libelektra-static.a ../../../lib/libelektratools-static.a
../../../lib/libelektra-static.a
Undefined symbols:
  "_elektra_resolver_mutex", referenced from:
      _elektraUnlockMutex in libelektra-static.a(resolver.c.o)
      _resolverInit in libelektra-static.a(resolver.c.o)
      _elektraSetPrepare in libelektra-static.a(resolver.c.o)
ld: symbol(s) not found
collect2: ld returned 1 exit status
make[2]: *** [bin/kdb-static] Error 1
make[1]: *** [src/tools/kdb/CMakeFiles/kdb-static.dir/all] Error 2
make: *** [all] Error 2

My guess is that ../../../lib/libelektra-static.a  linking needs mutex.c.o after resolver.c.o . But you are likely much faster than me in fixing that.

**Comment by markus2330** [comment]
Hello,

you wrote:
> The osx-01 branch contains some fixes. The state is not final. Build stops
> at around 60%. The commit format is not always best.

Can you create a merge request for all issues except resolver (one can use 
wresolver instead). Btw. the mutex is a compile time option and can be avoided 
in resolver, too. Except of the resolvers and libloader everything should be 
portable C99.

best regards, Markus

**Comment by markus2330** [comment]
@beku: can you please confirm that master works on OS X?

**Comment by markus2330** [comment]
I will close it, please reopen if you find a build issue.
