### ISSUE TITLE
Hindering Factors of Elektra Adoption

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1880]
@haraldg wrote in #1873
> I asked:
> > Is this really an obstacle for the adoption of Elektra?
> This is very difficult to answer.

Thank you for the answer. Your answer maps very much with the feedback we got at the survey but with some new interesting details.

>  For your target audience I would guess the main obstacles are:
> 1) Almost nobody else is using it

Here I should continue stating that Elektra is actually used *a lot* but unfortunately not in FLOSS. And it is not only universities, but e.g. Broadcom, Toshiba, insurance companies, ..

> 2) No high level API is provided yet

Yes, the initial idea was: "we give you the building blocks, please write your own API" (which then is perfectly suitable for your needs). Either this was poorly communicated (companies understood it, though) or it simply did not work. In any way, the high-level APIs got one of our mayor 1.0 goals #1270 :wink: 

See also the full  [list of 1.0 goals](https://github.com/ElektraInitiative/libelektra/milestone/12)

> 3) It is a bit scary with all the many features and few people look into it in enough detail to realize it is modular enough to not cause too many problems.

Yes, especially the combination of the belief "nobody uses it" and "has many features" is very scary.

But we also see a need for action and will remove some stuff for 1.0: #1327

> 4) Many programmers like to think of configuration issues (like merging on upgrades) as the maintainers problem and don't care as much about 3-way-merge ability as they IMO should.

I fully agree! Although 3-way merge is minor compared with missing validation, no programmatic ways to change settings and so on and so on...

But it seems like there is a bit of a mind-shift is happening. For example, my talk about this topic got [accepted in FOSDEM main track](https://fosdem.org/2018/schedule/event/elektra/), which only happens if some people find the topic indeed very important.

> 5) Many people think of configuration as some kind of script rather then a set of key-value-pairs, so elektra seems alien to them.

Yes, definitely.

**Comment by haraldg** [comment]
markus2330 writes:
> >  For your target audience I would guess the main obstacles are:
> > 1) Almost nobody else is using it
> 
> Here I should continue stating that Elektra is actually used *a lot* but unfortunately not in FLOSS. And it is not only universities, but e.g. Broadcom, Toshiba, insurance companies, ..

It would have been more precise for me to write: There is no community of
users around elektra. Some company using elektra behind closed doors isn't
going to help most people.

> > 2) No high level API is provided yet
> 
> Yes, the initial idea was: "we give you the building blocks, please write your own API" (which then is perfectly suitable for your needs). Either this was poorly communicated (companies understood it, though) or it simply did not work. In any way, the high-level APIs got one of our mayor 1.0 goals #1270 :wink: 

I wasn't aware of this philosophy myself, but I doubt it was a communication
problem. It wouldn't have been a problem if the high level APIs were in
different projects - maybe it still does make sense to go that route,
if the high level API has less requirements/assumptions then the current
one. Ie if the high level API could be implemented as a wrapper around
windows registry or on very limited systems without virtual memory. (Of
course with much less features supported.)

But if there is no high level API available anywhere, then at least for
me this marks the system pretty much as immature, as in: Looks like
nobody has yet figured out how to reasonably expose these features to
user code. At least for me designing a good API is really hard and already
getting one for free is a huge bonus: When starting to work on a new topic
I usually don't know what ideas are important and which ones are dead ends.
A good API should automatically nudge me away from most mistakes by twisting
my thinking in the right direction. When I'm writing an application then I
look for an API embodying years of experience in the topic - not a set of
bricks, that tempt me to build crazy magical castles.

> > 4) Many programmers like to think of configuration issues (like merging on upgrades) as the maintainers problem and don't care as much about 3-way-merge ability as they IMO should.
> 
> I fully agree! Although 3-way merge is minor compared with missing validation, no programmatic ways to change settings and so on and so on...

Depends on whom you ask I guess. For me (and I'm pretty sure most debian
users will agree) merging configuration on package upgrades is the only
real issue I experience. (Can somebody please elektrify rsyslogd?)

**Comment by markus2330** [comment]
> I wasn't aware of this philosophy myself, but I doubt it was a communication problem.

It was an implicit assumption from the very beginning. Initially "elektrifying" basically meant to reimplement some internal APIs of the applications. (@avibrazil :wave:). This was also the first suggestion of how to elektrify LCDproc: reimplement `config_get_*`. The low-level API would be perfectly suitable for this task.

In the last years I extended what elektrify could mean:

1. Reimplementing internal APIs or transforming a KeySet to the application's internal data structure.
2. Reimplementing official APIs (like getenv). This can be even used to dynamically intercept configuration access of applications.
3. Using high-level APIs with code-generation to write new software with Elektra with many guarantees you could not get otherwise.

All 3 methods use the low-level KeySet internally but the users might not be exposed to it.

> It wouldn't have been a problem if the high level APIs were in different projects - maybe it still does make sense to go that route, if the high level API has less requirements/assumptions then the current one. Ie if the high level API could be implemented as a wrapper around windows registry

We are currently working on Windows Registry support (again). The higher-level API is not needed to support that. As a matter of fact I would prefer to use the lower-level API if possible because then *any* higher-level API automatically gets supported, too (like the internalnotification-API, which is also high-level but completely different).

>  or on very limited systems without virtual memory. (Of course with much less features supported.)

Yes, here a higher abstraction actually would make sense.

>  But if there is no high level API available anywhere, then at least for me this marks the system pretty much as immature, as in: Looks like nobody has yet figured out how to reasonably expose these features to user code.

There *are* two high-level API since some years:

1. One using code generation, see [here](https://master.libelektra.org/src/tools/gen/) It is C++ only but it has *many* guarantees (like reading always successful, thread safety, ..)
2. Reimplementation of getenv, see [here](https://www.libelektra.org/bindings/intercept_env) (read-only)

> Depends on whom you ask I guess. For me (and I'm pretty sure most debian users will agree) merging configuration on package upgrades is the only real issue I experience.

You never needed to write some ad-hoc sed script that modifies parts in configuration files? You never mistyped something in the configuration file and the application refused to start with a weird (or none) error message? Lucky you!

> (Can somebody please elektrify rsyslogd?)

:smile:

**Comment by haraldg** [comment]
>> I wasn't aware of this philosophy myself, but I doubt it was a 
>> communication problem.
>
> It was an implicit assumption from the very beginning. Initially
> "elektrifying" basically meant to reimplement some internal APIs of
> the applications.

I can see that this is a convenient way to elektrify existing 
applications
quickly. But I don't see why anybody would like to use that approach
for new applications.

> This was also the first suggestion of how to elektrify LCDproc:
> reimplement `config_get_*`.

In the case of LCDproc config_get_* was never really designed, but
mostly happend accidentally, so I think trying to get rid of it is 
reasonable.

If I was only after 3-way-merge on upgrade but didn't care about 
switching
to a clean and easy to use API, then probably we wouldn't strictly need 
to
link against elektra at all (for a moment ignoring the bugs in our
implementation). We (or rather the distribution) could just use
some tool based on elektra for merging and parsing could still be done 
by
our custom code and save a lot of memory footprint. A distribution 
could
switch its entire configuration management to elektra without a single
application actually being elektrified.

With that in mind your focus on plugins for any configuration format 
out
there instead of high level APIs suddenly makes a lot more sense. You 
want
to be able to read any configuration in its legacy format, because you
aren't sure that all (or even most) access to it happens through 
elektra.
OTOH lcdproc probably would readily switch from ini to some other human
readable configuration format, if necessary, so long as we get a nice 
and
easy to use API, that was designed by people with years of experience 
in
the field. If I'm right, then we had there quite a big misunderstanding 
...

> You never needed to write some ad-hoc sed script that modifies parts
> in configuration files?

No, I don't remember ever doing such a thing.

> You never mistyped something in the configuration file and the
> application refused to start with a weird (or none) error message?

The first part happens occasionally of course, but I rarely have a 
problem
finding and fixing the error. And quite often it is mistyping some 
number,
that wouldn't be detected by validation anyway.

OTOH rsyslogd bothers me on almost any upgrade, since the default
configuration is neither suitable for linux containers nor embedded 
systems
and I have quite a few of both but don't dare stick with an old 
configuration
forever.

**Comment by markus2330** [comment]
> But I don't see why anybody would like to use that approach for new applications.

Apparently the FLOSS community didn't like it for old applications, either. Also @beku (oyranos) was a bit disappointed when we did not have a high-level API available. So going for specialized but much easier to use APIs is certainly a good and necessary thing.

If no API we provide fits, you still can reinvent your own.

> In the case of LCDproc config_get_* was never really designed, but
mostly happend accidentally, so I think trying to get rid of it is
reasonable.

Yes.

> A distribution could switch its entire configuration management to elektra without a single application actually being elektrified.

You can go to a certain degree but not all of configuration management would work as expected: e.g.

1. Default values also belong to configuration management. And without elektrifying your  applications, you cannot specify (or not even query!) the default values.
2. The parser in Elektra might interpret some things differently than the parser in the applications.
3. You are tied to all limitations the configuration file format might have.

See also [discussion here](https://www.libelektra.org/tutorials/integration-of-your-application). So there are good reasons for *configuration management* to elektrify the applications, even if Elektra implements the configuration file format of the application.

> We (or rather the distribution) could just use some tool based on elektra for merging and parsing could still be done by our custom code and save a lot of memory footprint.

This is subject for investigation in LCDproc. Elektra's `_Key` is a bit clumsier than LCDproc's `_config_key` (e.g. sizes and a pointer to metadata) but with Elektra the parsing code gets to be removed from the executable which might save some memory (assuming that the library is shared with other processes).

> to be able to read any configuration in its legacy format, because you aren't sure that all (or even most) access to it happens through elektra.

It is not about not being unsure which technique will succeed: Having support for nice configuration file formats is also often needed even if applications want to be elektrified.

For example: Elektra can only be a drop-in replacement if we implement the application's configuration file format.

> OTOH lcdproc probably would readily switch from ini to some other human readable configuration format, if necessary, so long as we get a nice and easy to use API, that was designed by people with years of experience in the field.

One of the main points of elektrifying is that it gets irrelevant which configuration file format you use. So people preferring YAML, XML, JSON, ... can go for YAML, XML, JSON, respectively.

Without implementing these formats, the advantage would be theoretical. Now it is real, you can actually choose between these formats.


> If I'm right, then we had there quite a big misunderstanding

I am not sure if there is a misunderstanding, the situation simply is a bit more complicated and we might not have discussed all possibilities in detail. It is not like we can simply exchange APIs (elektrify) and all problems of configuration management are gone. More is needed, and Elektra is a full solution to make people caring about configuration management happy. (Like also specifying which values are allowed and introspect these specifications.)

> > You never needed to write some ad-hoc sed script that modifies parts in configuration files?

> No, I don't remember ever doing such a thing.

I can only say again: Lucky you :smile: 

> > You never mistyped something in the configuration file and the
 application refused to start with a weird (or none) error message?

> The first part happens occasionally of course, but I rarely have a problem finding and fixing the error. And quite often it is mistyping some number, that wouldn't be detected by validation anyway.

There is quite a lot what you could do, e.g., also add units, metric prefixes (see #1398) or you can often also turn numbers into enums (because most of the configuration space is not needed anyway and with text you cannot easily catch typos). These things are configuration settings design, where Elektra gives you much more possibilities.

**Comment by haraldg** [comment]
> Apparently the FLOSS community didn't like it for old applications,
> either.

Yes, most people active in FLOSS deveopment do it as some kind of 
hobby/dedication
with money being a secondary concern. They tend to have a lot higher 
standard
about their code then companies and somewhat look down on quit and 
dirty solutions.

As Linus Torvalds once said: One of the good things of open source 
software is
that you can always make fun of people writing bad code - it prevents 
so much bad
software from being written. (I don't quite agree with him about making 
fun of
people, but I'm pretty sure we have much better code then most 
companies.)

> If no API we provide fits, you still can reinvent your own.

I'm pretty sure if you come up with a set of *good* APIs, then a lot of 
people
will be reworking their code to fit one of it instead of trying to 
support their
quirks.

**Comment by markus2330** [comment]
The highlevel API is now progressing again. #2293
