### ISSUE TITLE
example_notification_async not async?

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1883]
## Steps to Reproduce the Problem

Please provide a step by step guide on how to reproduce the problem here. If possible, please use
[Markdown Shell Recorder](https://master.libelektra.org/tests/shell/shell_recorder/tutorial_wrapper)
syntax:

```sh
kdb global-mount dbus dbusrecv
bin/example_notification_async &
kdb set /sw/tests/example_notification/#0/current/value 5
```

## Expected Result

I expect that:

- the value 5 is immediately printed
- when pressing ctrl+c, that the program immediately terminates

## Actual Result

- the value is printed with timer delay (periodically)
- the program terminates after timer expires

It is not wrong to have an example like this but one with immediate reactions would be nicer.

## System Information

- Elektra Version: master

**Comment by waht** [comment]
I updated the example to print immediately. 

I also figured out how to immediately close the loop. However it is not very obvious: A call to `uv_stop ()` only updates [an internal flag](https://github.com/libuv/libuv/blob/v1.x/src/uv-common.c#L424) while the loop is sleeping until the next timer interval has passed. So removing the timer was not enough. An "async" handle (`uv_async_t`) which wakes up the loop after removing the timer and closing the loop did the trick.
