### ISSUE TITLE
[Documentation] Make sure all plugins/bindings have their dependencies documented

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#1886]
Currently not all plugins/bindings have their dependencies documented:
For example `binding/glib` or `plugin/gitresolver`

**Comment by markus2330** [comment]
Thank you for reporting!

Yes, that is part of a bigger problem:  #1016

We would be thrilled if you can take care of that problem, and use the dependency information from one central place (within the contract of the plugins) instead of yet-another duplication.
