### ISSUE TITLE
HASKELL Binding requirements (base)

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#1891]
## Steps to Reproduce the Problem

currently building elektra with haskell bindings and an insufficient version of ghc leads to
```
conflict: libelektra-haskell =>base>=4.7 && <5)
```
during compilation

## Expected Result
Cmake does exclude haskell binding if ghc version is not high enough

## Actual Result
Build fails during compilation

## System Information
- debian jessie
- ghc 7.6.3

## Further Log Files and Output
[Full Log](https://build.libelektra.org/jenkins/job/elektra-jenkinsfile/62/execution/node/105/log/)
[Haskell Base Package](https://wiki.haskell.org/Base_package)

**Comment by markus2330** [comment]
Thank you for reporting!

I think we need to exclude Haskell for jessie. It should work on stretch, though.

@e1528532 Or do you have an idea how to resolve this?

**Comment by e1528532** [comment]
Maybe an older version would be sufficient as well but I think the easiest thing is to expect 8.0.1 as bundled with stretch as the minimum version. For some type checking things it won't work with earlier versions anyway.

**Comment by markus2330** [comment]
> Maybe an older version would be sufficient as well but I think the easiest thing is to expect 8.0.1 as bundled with stretch as the minimum version. For some type checking things it won't work with earlier versions anyway.

We should fix the version we are supporting. Let us take the 8.0.1 as bundled with stretch.

@e1528532 Can you please add a CMake check so that the build will not fail?

**Comment by ingwinlu** [comment]
https://github.com/domdere/haskellSkeleton/blob/master/cmakemodules/FindHaskell.cmake shows how we could 'find' the ghc version required to build the binding.
