### ISSUE TITLE
integrate link checker in the build server

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#1898]
## Steps to Reproduce the Problem

* configure with cmake so html target is included
* `make html`

## Expected Result

When there are warnings because of, for example, invalid links the build should fail.

## Actual Result

```
root@939367aae911:/tmp/workspace/build# make html
Built target markdownlinkconverter
Generating html/index.html, man/man3elektra/kdb.3elektra
/tmp/workspace/doc/help/elektra-faq.md|95 col 0| warning: invalid link '/.github/CONTRIBUTING.md'
/tmp/workspace/doc/IDEAS.md|40 col 0| warning: invalid link '/.github/CONTRIBUTING.md'
Built target html

```

## System Information

- Elektra Version: master

**Comment by markus2330** [comment]
Thank you! Yes, it would be great if the link checker would tell doxygen that something is wrong.

@KurtMi Is this easily possible?

In general I do not think it is useful to have a warning-free doxygen. Doxygen simply is too verbose and warns about many irrelevant things (and iirc not all of them can be configured to not emit a warning). I tried it once in a project and it was immense effort with little benefit.

But once Doxygen introduces warning levels or similar (or did they already?) it might be a good idea to keep an eye on the warnings. But in the current situation the warnings are nearly worthless.

**Comment by markus2330** [comment]
I renamed this issue. @KurtMi any update if it is possible to make the internal link checker fail on wrong links?

I also briefly considered if we should include the external link checker in the build server but it seems like there are always spurious problems and it takes to long, so it makes little sense.

**Comment by ingwinlu** [comment]
Closed as wontfix as there are no easy solutions as far as I can see.

**Comment by markus2330** [comment]
I added the task to #160. The static part of the link checker should be not too difficult to integrate. It does not have false positives.
