### ISSUE TITLE
ctest: support parallelism

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1900]
It seems like ctest supports `-j`. This should work for all build jobs except those tagged with kdbtests.

It would be interesting if the speedup is interesting also for the build server. For local runs it certainly is.

Following cleanup is needed:

- [ ] Set LD_LIBRARY_PATH via CTEST_ENVIRONMENT
- [ ]  get rid of our scripts calling ctest: run_all, run_memcheck, run_nokdbtests (use cmake targets instead)
- [ ] make exclusion of memleak tests properly with CTEST_CUSTOM_MEMCHECK_IGNORE
- [ ] Mark the kdbtests to lock the same resource (so that they are not executed in parallel)

**Comment by ingwinlu** [comment]
This is currently very ugly to implement as we use shell scripts to run the tests (i.e. we would need to set it there but it should be moddable from the outside).

The proper way to handle this is to remove the scripts (run_all, run_memcheck, ....) and move all the configuration into cmake.

* [handle libs](https://cmake.org/Wiki/CMake_RPATH_handling)
* [handle args](https://stackoverflow.com/questions/36726545/replace-ctest-command-with-ctest-output-on-failure-permanently-for-a-specifi)

Afterwards users should be able to just run make with -j same as during the build process

**Comment by markus2330** [comment]
Yes, you are right. The script was basically only there for the exit status but this was now removed anyway (thanks to you). So currently the scripts only set the LD_LIBRARY_PATH, which should be doable from within CMake, too. (Using CTEST_ENVIRONMENT)

> run_all

Beware that there are two run_all, the second one is tests/shell/run_all.sh which is needed to run test cases within an installed Elektra. It does not use ctest and we still need it :wink: 

> RPATH

Unfortunately, RPATH does not work in a number of situations, so LD_LIBRARY_PATH was needed. For example, if an interpreter (like lua or python) loads Elektra RPATH is not considered on some systems. You can browse in old issues if you are interested but be assured: we tried hard to not need LD_LIBRARY_PATH but it is actually necessary in some situations (for the test runs but not when Elektra is installed).

> handle args

If we do this like in the accepted answer, we again lose the `-j`, arguments, don't we?

I updated the top post for things to be done.

**Comment by ingwinlu** [comment]
> If we do this like in the accepted answer, we again lose the -j, arguments, don't we?
`make test ARGS=-j4` or something like that. will have to take a closer look

**Comment by ingwinlu** [comment]
`CTEST_CUSTOM_MEMCHECK_IGNORE` requires cmake 3.4
`CTEST_ENVIRONMENT` is not for cmake but only ctest scripts, an alternative would be to add en ENVIRONMENT property toall add_test commands
https://cmake.org/cmake/help/v2.8.12/cmake.html#prop_test:RUN_SERIAL could be used to limit parallel memcheck runs.

**Comment by ingwinlu** [comment]
@markus2330 I need a decicion regarding `CTEST_CUSTOM_MEMCHECK_IGNORE`. Should we require cmake 3.4 and use it or require people to manually specify -LE memleak for memchecks?
