### ISSUE TITLE
docs: resolve warnings

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#1904]
current documentation generation produces [lots of warnings](https://gist.githubusercontent.com/ingwinlu/c22432e138ce5c385a0bf2ea2d73d9c5/raw/7b2f9a62ed20ea9a6802e9c5eea82eb39f6b8aa6/doxygen.log)

A cleanup would be appreciated.

**Comment by markus2330** [comment]
Thank you for creating that gist.

There are much less warnings than I expected. Seems like we are not documenting enough :smile: 

Btw. It would be helpful if we get rid of random prefixes like "/home/jenkins/workspace/elektra-jenkinsfile@4/" in warnings. If this is easily possible (on the build server, not in the gist), please do it.

**Comment by ingwinlu** [comment]
An up2date list can always be found [here](https://build.libelektra.org/jenkins/job/elektra-jenkinsfile/warnings17).

**Comment by markus2330** [comment]
The link with the updated list does not work anymore.
