### ISSUE TITLE
have maintainable list of build server admins

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1905]
Feature request: it would be great to have an easy-to-maintain list of admins shared between all build jobs. Admins then can say "add to whitelist" so that collaborators are allowed to trigger jobs.

@ingwinlu wrote in #160:
> I tried to add `allowMembersOfWhitelistedOrgsAsAdmin` to all build jobs today but seems like I can still not trigger a build all (see #1863) properly and only some jobs get executed

I do not have any idea why you cannot trigger jobs. Seems like misconfiguration in most of the jobs? Maybe the "add to whitelist" did not work properly in your case?

> @markus2330 https://github.com/janinko/ghprb/issues/416#issuecomment-266254688

As I understood it, building jobs only needs the "add to whitelist" by an admin. And this always worked, you are the first case where it did not.

**Comment by ingwinlu** [comment]
our Jenkinsfile job does this automatically by determining if the github user has write access to the repo
