### ISSUE TITLE
kdb: swallowing env variables

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#1906]
A Problem for example when trying to provide a dbus session or a custom `LUA_PATH`:

## Steps to Reproduce the Problem

```bash
  #startup dbus and export address
 DBUS=(`dbus-daemon --session --fork --print-pid --print-address`)
 export DBUS_SESSION_BUS_ADDRESS=${DBUS[0]}
 echo $DBUS_SESSION_BUS_ADDRESS
 # try to see if it works
 dbus-monitor --session
 # monitor should start up, abort with ctrl + c

 # but the address is not picked up during kdb testruns:
 # you can ignore the all environment variables, just kdb testmod_dbus should produce the desired result
 LD_LIBRARY_PATH=$WORKSPACE/system/lib:$LD_LIBRARY_PATH \
   PATH=$WORKSPACE/system/bin:$PATH \
   LUA_PATH=$WORKSPACE/system/lib:$LUA_PATH \
   DBUS_SESSION_BUS_ADDRESS=${DBUS[0]} \
   kdb testmod_dbus
 kill ${DBUS[1]}
```
## Expected Result

environment variables should be available in tests

## Actual Result

environment variables seem to not get picked up by tests i.e. 'vanish'

## System Information

- Elektra Version: master

**Comment by ingwinlu** [comment]
i did getenv in test_dbus and indeed it is `null`.

If i put senenv directly in the test with my dbus session address as value it works as expected and tests run + pass so it indeed is just a problem of kdb swallowing the values along the way.

**Comment by ingwinlu** [comment]
one thing that seems to work is `kdb elektrify-getenv`:
```sh
LD_LIBRARY_PATH=$WORKSPACE/system/lib:$LD_LIBRARY_PATH \
  PATH=$WORKSPACE/system/bin:$PATH \
  LUA_PATH=$WORKSPACE/system/lib:$LUA_PATH \
  kdb set user/elektra/intercept/getenv/override/DBUS_SESSION_BUS_ADDRESS `echo $DBUS_SESSION_BUS_ADDRESS`
kdb elektrify-getenv kdb testmod_dbus
```

I am however not sure if I want to have the hard requirement to have the intercept binding included in there

**Comment by markus2330** [comment]
Thank you for reporting the bug!

Can you try to directly invoke bin/testmod_dbus?

I this works, external.cpp line 125 might be the problem, maybe _WIN32 is set?

**Comment by ingwinlu** [comment]
i did try it directly and the issue persisted. I don't know about _WIN32 but can have a look on Monday

**Comment by markus2330** [comment]
If the direct execution failed, my idea about external.cpp is irrelevant.

The problem most likely is tests/cframework/tests.c line 54, seems like we clear the environment there.
I created #1909 which should fix this problem.

**Comment by markus2330** [comment]
If the LUA_PATH problem is not fixed, please open a separate issue about lua. (test cases seem to still fail)
