### ISSUE TITLE
build: Set up reference repos

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#1907]
To safe io (network + disc) we should use reference git repos on all jobs.
https://support.cloudbees.com/hc/en-us/articles/115001728812-Using-a-Git-reference-repository

Additionally a 'daily' job to update it could be introduced (`Jenkinsfile.daily` #1908 ).

**Comment by ingwinlu** [comment]
Created https://build.libelektra.org/jenkins/job/elektra-jenkinsfile-daily/, can add to existing jobs via reference repo: `${HOME}/git_mirrors/libelektra`

**Comment by markus2330** [comment]
Thank you!
