### ISSUE TITLE
build:elektra-git-buildpackage-stretch failing

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#1911]
[elektra-git-buildpackage-stretch](https://build.libelektra.org/jenkins/job/elektra-git-buildpackage-stretch) has been failing for a long time due to an gpg signing error.

@markus2330: Since I have no experience with debian package management please look into it.

PS: It is also one of the build jobs that we should move to the docker container on v2 if possible.

**Comment by markus2330** [comment]
Thank you for reminding. This is actually a high-priority problem  #1752 which we were unfortunately not able to fix for a long time. (Several people asked if there are stretch debian repos and I had to disappoint them all.)

Basically, only a gpg key needs to be created and maybe ` -k` passed to gbp buildpackage (but I think if there is only a single secret key, it will use that one without any config).

The question is how to deploy the same gpg key into all docker images where the build might run?

The second problem is where to deploy the resulting reprepro. If setting up a new web server is too complicated we can also use an existing one like https://www.libelektra.org/ftp/repos/ 

Maybe @BernhardDenner can help with the second problem?

**Comment by ingwinlu** [comment]
I suggest providing the gpg keys (private + public I think?) as jenkins credentials. It allows to inject files into any build process.

https://jenkins.io/doc/book/using/using-credentials/
https://support.cloudbees.com/hc/en-us/articles/203802500-Injecting-Secrets-into-Jenkins-Build-Jobs

**Comment by ingwinlu** [comment]
We can deploy the repo on a7 behind the reverse proxy.

**Comment by markus2330** [comment]
The public key can even be in the repo. We can also put the private key into a private repo. It might be a good idea to put as little info into Jenkins as possible.

**Comment by ingwinlu** [comment]
I am not sure if it is worth the additional hassle as we would need a way to authenticate jenkins against the private repo.
