### ISSUE TITLE
elektra-clang-asan: failing "testlib_notification" test

### ISSUE THREAD

**Issue by waht** [ElektraInitiative/libelektra#1919]
I would like to collect information in this issue to resolve the [failing "testlib_notification" test](https://build.libelektra.org/jenkins/job/elektra-clang-asan/423/console).

The reason for the failing test is the same as in [#1824](https://github.com/ElektraInitiative/libelektra/issues/1824#issuecomment-369689156): 
The "dump" storage plugin fails to load due to the missing `__ubsan_vptr_type_cache` symbol, added by enabling the [UndefinedBehaviorSanitizer](http://releases.llvm.org/3.8.0/tools/clang/docs/UndefinedBehaviorSanitizer.html) (included by ASAN). 

## Steps to Reproduce the Problem

Step-by-step guide:

1. open src/libs/elektra/log.c and uncomment line 19 (`#define NO_FILTER`) to enable all logging messages

2. compile with ASAN, logging and debugging enabled and install
```sh
cmake -DPLUGINS=ALL  -DENABLE_ASAN=ON -DBUILD_DOCUMENTATION=OFF -DENABLE_DEBUG=ON -DENABLE_LOGGER=ON ..
make -j 3
make -j 5 install && ldconfig
```

3. run the testlib_notification test
```sh
ASAN_OPTIONS=symbolize=1 ASAN_SYMBOLIZER_PATH=$(which llvm-symbolizer) ./bin/testlib_notification
```

## Expected Result

The "testlib_notifcation" test should pass.

## Actual Result

The test fails (the output below can only be seen when running the test directly)
```
test open & close
src/libs/elektra/kdb.c:260:kdbOpen: called with system/sw/tests/testlib_notification
src/libs/elektra/plugin.c:300:elektraPluginOpen: Finished loading plugin resolver
src/libs/loader/dl.c:89:elektraModulesLoad: Add Warning 1 : of module: libelektra-storage.so, because: /mnt/share/build_docker/lib/libelektra-storage.so: undefined symbol: __ubsan_vptr_type_cache
```

## System Information

- Elektra Version: master
- Docker Container: [doc/dockder/debian/stretch](https://github.com/ElektraInitiative/libelektra/pull/1866/files#diff-41c79795703816113cf05be55c35b516)
- Clang 5.0 and 3.8

**Comment by waht** [comment]
Alternatively we can [disable the "vptr" checks](https://github.com/ElektraInitiative/libelektra/pull/1825/commits/a1944f1ad1e3b469a192576e279e02bee0603bb5).

**Comment by markus2330** [comment]
Thank you for looking into the problem!

Disabling vptr checks for the dump plugin sounds reasonable.
