### ISSUE TITLE
Missing constants in constants plugin

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#1921]
https://github.com/ElektraInitiative/libelektra/blob/master/src/plugins/constants/constants.c.in is missing at least the following constants:
* MEMORYCHECK_COMMAND_OPTIONS
* MEMORYCHECK_SUPPRESSIONS_FILE

**Comment by markus2330** [comment]
Thank you for reporting potentially missing constants!

Why would these two CMake Cache variables be useful for the run-time system? Afaik the MEMORYCHECK_ options only influence ctest within the build directory but have no influence whatsoever on the installation, binaries or the build process.

ENABLE_ASAN, however, might be something of interest. I added it in 1eb73b5d8db18bafcd6b8d4bbac6ccfab217b5c4

CMAKE_SKIP_BUILD_RPATH might be relevant, too. (Is the warning generated for "CMAKE_SKIP_BUILD_RPATH AND BUILD_TESTING" still relevant?)

Btw. does your LUA environment influence the TARGET_LUA_CMOD_FOLDER? This constant, however, is only relevant if there are lua bindings.

**Comment by sanssecours** [comment]
> ENABLE_ASAN, however, might be something of interest. I added it in 1eb73b5

Please [test](https://build.libelektra.org/jenkins/blue/organizations/jenkins/elektra-gcc-configure-debian-log/detail/elektra-gcc-configure-debian-log/1615/pipeline#log-524) your changes before you push them. I fixed the broken MSR test for the Constants plugin in commit a12362a0.

**Comment by markus2330** [comment]
Sorry and thank you for the fix!
