### ISSUE TITLE
Jenkins: MinGW Build Fails

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1922]
# Steps to Reproduce the Problem

Execute the build job [elektra-gcc-configure-mingw-w64](https://build.libelektra.org/jenkins/blue/organizations/jenkins/elektra-gcc-configure-mingw-w64) on Jenkins.

## Expected Result

The build job succeeds.

## Actual Result

The build job [fails](https://build.libelektra.org/jenkins/blue/organizations/jenkins/elektra-gcc-configure-mingw-w64/detail/elektra-gcc-configure-mingw-w64/1434/pipeline/) printing the following error message:

```
it looks like multiarch needs to be enabled.  as root, please
execute "dpkg --add-architecture i386 && apt-get update &&
apt-get install wine32"
wine: chdir to /home/jenkins/workspace/workspace/.wine
 : No such file or directory
src/error/CMakeFiles/kdberrors_generated.dir/build.make:52: recipe for target 'src/include/kdberrors.h' failed
```

.

# System Information

- Elektra Version: `master`

**Comment by ingwinlu** [comment]
My bad I moved the workingdir yesterday, did not expect to have relative references in the build job.

**Comment by ingwinlu** [comment]
**Error:** `wine: chdir to /home/jenkins/workspace/workspace/.wine`
**Solution** changing WINEPREFIX relative to $HOME and making sure the directory exists before the build:
```
export WINEPREFIX=$HOME/workspace/.wine
mkdir -p $WINEPREFIX
```
ping #160

**Comment by markus2330** [comment]
Thank you for reporting and fixing this!
