### ISSUE TITLE
elektra-gcc-configure-debian-log failing, lua

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#1931]
Hi since yesterday builds for elektra-gcc-configure-debian-log are failing due to a locale issue. Since I did not touch `debian-mm-unstable` (no login) I hoped somebody could clarify what is going on.
```
-- Include Plugin counter
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = "",
	LC_MESSAGES = "",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
"getters" is not defined in %Dpkg::Arch::EXPORT_TAGS at /usr/bin/dpkg-architecture line 29.
	main::BEGIN() called at /usr/bin/dpkg-architecture line 29
	eval {...} called at /usr/bin/dpkg-architecture line 29
"mappers" is not defined in %Dpkg::Arch::EXPORT_TAGS at /usr/bin/dpkg-architecture line 29.
	main::BEGIN() called at /usr/bin/dpkg-architecture line 29
	eval {...} called at /usr/bin/dpkg-architecture line 29
Can't continue after import errors at /usr/bin/dpkg-architecture line 29.
BEGIN failed--compilation aborted at /usr/bin/dpkg-architecture line 29.
-- Include Plugin crypto_gcrypt
```

[Broken Since](https://build.libelektra.org/jenkins/job/elektra-gcc-configure-debian-log/1631/console)

**Comment by markus2330** [comment]
Thank you for reporting this issue!

I might have fixed it by running "apt-get dist-upgrade" (there were broken packages, e.g. dpkg-dev, which might have caused the output).

I do not remember that I changed anything yesterday, though.

**Comment by ingwinlu** [comment]
https://build.libelektra.org/jenkins/job/elektra-gcc-configure-debian-log/1636/consoleFull

while locale looks okay now, some tests are affected

**Comment by markus2330** [comment]
Which tests do you mean? It is not new that the lua tests fail :wink:

**Comment by ingwinlu** [comment]
new on this system though:
https://build.libelektra.org/jenkins/job/elektra-gcc-configure-debian-log/1630/consoleFull
vs
https://build.libelektra.org/jenkins/job/elektra-gcc-configure-debian-log/1636/consoleFull

**Comment by ingwinlu** [comment]
@markus2330 I just noticed that apparently the upgrade was not successfull, maybe we are in an inconsistant state https://gist.github.com/ingwinlu/9348dc57318577d1d00cb3d65e75c388.

Can you rerun the upgrade process and maybe reboot the machine?

**Comment by markus2330** [comment]
Maybe we only triggered something at debian-unstable-mm at the same time.

I updated now lua from 5.2.4-1.1+b1 to 5.2.4-1.1+b2

**Comment by ingwinlu** [comment]
@markus2330 that was not the problem, we need lua-lgi 0.9.2-2

**Comment by markus2330** [comment]
Yes, lua-lgi is also upgraded from 0.9.1-1 -> 0.9.2-2

**Comment by ingwinlu** [comment]
Seems to be working again. Thank you.
