### ISSUE TITLE
tests: use provided add_test macros everywhere

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#1934]
For tests to work correctly a simple add_test is not enough. Some tests require LD_LIBRARY_PATH to be set, some require the memleak or kdbtests labels to be set.

Elektra already provides macros to help you add those tests with the correct settings. However some places still don't use them. Those should be replaced with the macro calls to remove clutter.

ref #1933

**Comment by markus2330** [comment]
Please reopen if any further occurrences are found.
