### ISSUE TITLE
shell_recorder.sh: Also print stderr if there is a testerror

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#1936]
If a shell_recorder test fails it will always be helpful to also get stderr.

I just had a problem with a missing dependency for a README test that required ruby. Instead of just seeing the 'ruby command not found' in the build server output I had to recreate the environment locally to get to the error message.

**Comment by markus2330** [comment]
Thank you for reporting the problem!

@sanssecours @tom-wa Do you know how to fix this behavior of the shell recorder?

**Comment by sanssecours** [comment]
> Instead of just seeing the 'ruby command not found' in the build server output I had to recreate the environment locally to get to the error message.

Another option would be to add the [directive](https://github.com/ElektraInitiative/libelektra/tree/master/tests/shell/shell_recorder/tutorial_wrapper#checks) `STDERR: ` **followed by some text** to the test:

```sh
shinyShinyProgrammingLanguage -c 'printf \x68\x69'
# STDERR: Error
#> hi
```

, then the test would also print the text sent to `stderr`:

```
ERROR - RET:
Return value “127” does not match “0”


ERROR - STDERR:
“sh: shinyShinyProgrammingLanguage: command not found”
does not match
“Error”


ERROR - STDOUT:
“”
does not match
“hi”
```

. By the way, while certainly not human readable, the return value of the command (`127`) also [indicates the problem](https://stackoverflow.com/questions/1763156/127-return-code-from).
