### ISSUE TITLE
Add Unescaped methods to API

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#194]
const void *keyUnescapedName(const Key *key);
    ssize_t keyGetUnescapedNameSize(const Key *key);

are the only sane way to iterate over a key name in Elektra. Unforunately they are not in the API yet.

Is there anything to consider in respect to the bindings before adding them? Is there any iteration over names in the bindings available yet?

**Comment by manuelm** [comment]
This returns the key with `\0` instead of `/` as delimiter? Because `key.name.split("/")` won't work on escaped with names (e.g. `user/some\/foo/bar`), right?

Doubt that will work out of the box in bindings. Python3 is easy. Python2 is ignored by me. Lua is troublesome.
Can take a look later.

**Comment by markus2330** [comment]
manuel wrote:
> This returns the key with `\0` instead of `/` as delimiter?

Yes.

> Because
> `key.name.split("/")` won't work on escaped with names (e.g.
> `user/some\/foo/bar`), right?

Right! Sorting by the escaped names also leads to wrong results, but for that 
keyCmp already exists.
 
> Doubt that will work out of the box in bindings. Python3 is easy. Python2
> is ignored by me. Lua is troublesome. Can take a look later.

So maybe its better to leave it for a later release. Its in proposal and can 
be used anyway.

best regards

**Comment by manuelm** [comment]
I've just added support for this:
```
# python3 -c 'import kdb; k=kdb.Key("user/foo\/bar/mimimi"); [ print(x) for x in k ];'
user
foo/bar
mimimi
```

API integration is ok?

**Comment by markus2330** [comment]
Thank you! In ea3d690447f47eb2cf2a3b6d8e11f26bcfe4d3a6 I moved the two lines from kdbproposal.h to kdb.h. The python API is very nice. Do you think the C API is ok?

I will add Java bindings later (so please keep issue open, but you can unassign yourself).

**Comment by manuelm** [comment]
C API is ok, yes.

I'm still working on the Lua iterator. Already took me a few hours but no end in sight.

How will you name the method/interface on Java? Lua doesn't have generic forward iterators like Python. My current (not-yet-working) method is called `key.name_iterator()`. Any better idea?

**Comment by markus2330** [comment]
> I'm still working on the Lua iterator. Already took me a few hours but no
> end in sight.
> 
> How will you name the method/interface on Java? Lua doesn't have generic
> forward iterators like Python. My current (not-yet-working) method is
> called `key.name_iterator()`. Any better idea?

I think I will only return some container holding strings. Isn't this possible 
in Lua, too?

**Comment by manuelm** [comment]
Any container would require pre-allocating all contained elements on the heap.

My current WIP is:
```
# lua -e 'require("kdb"); k = kdb.Key("user/foo\\/bar/mimimi"); for x in k:name_iterator() do print(x) end'
user
foo/bar
mimimi
```

But I kind of don't like the method names.

An alternative is `for x in NameIterator(kdb.Key("user/foo")) do print(x) end`

**Comment by manuelm** [comment]
Do we need support in gobject/gi as well?

**Comment by markus2330** [comment]
When your comparision reveals that SWIG is superior, then
only gobject should be kept up-to-date.

**Comment by markus2330** [comment]
released, thanks for help
