### ISSUE TITLE
rest frontend: configurable pid file location

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#1949]
Currently the location of the pid file when starting the rest frontend via `kdb run-rest-frontend` is hardcoded in the script.

Since normal users tend to not have write privileges in /run it would be great if it could be set similarly to the pid of the backend.

**Comment by ingwinlu** [comment]
and while we are on it I would love to have it respect the debug switch so it actually prints the enabled loggging output and an option to not start it in the background

**Comment by markus2330** [comment]
Thank you for reporting! I added a config setting for the PID file in #1950. Not starting in background should be fairly simple to add but I think not using the script in this case sounds simpler.

For logging I do not know how to add it.

**Comment by ingwinlu** [comment]
For logging grunt needs to be started with the -d flag.

For non daemonized runs: can we just do what you did in #1950 and query a daemon flag, adding & to the grunt command if it is set to true and vice versa?

**Comment by ingwinlu** [comment]
i want to use it in a docker container that runs the back + frontend.

While running grunt manually is an option it of course does not look as nice as a `kdb run-rest-frontend` + it is dependent on the install path

**Comment by markus2330** [comment]
> i want to use it in a docker container that runs the back + frontend.

Yes, that is clear.

> While running grunt manually is an option it of course does not look as nice as a kdb run-rest-frontend + it is dependent on the install path

I fully agree.

But why would you want the process running in foreground and with debug info? If it is in foreground, the build job will never terminate?

**Comment by ingwinlu** [comment]
the image is already built (remember there can be no running processes in an image).
when the image is then started I need to both start the backend and the frontend and I would like them to print to stdout as this is where docker expects the logs of the commands to be.

**Comment by markus2330** [comment]
So the idea is to run two docker images, one for front and one for backend? And everything should be non-detached printing to foreground? Makes sense.

You can simply add the two ifs in #1950.

Ideally, we should add a `kdb bget` which directly can be used within shell-`if`s but I would prefer not to add too many features shortly before the release.

Are these things necessary for #1866? I would like to merge #1866 and do the release asap.

**Comment by ingwinlu** [comment]
not critical, i created a wrapper script that does what I need it to do

**Comment by ingwinlu** [comment]
quite similar: https://github.com/ElektraInitiative/libelektra/blob/master/src/tools/rest-backend/stop.sh#L3
hardcoded path even though it is configurable.

**Comment by markus2330** [comment]
Yes, seems like nobody ever used this script with non-default configuration.

Thus the backend gets replaced we should not put too much effort into it.

The frontend, however, will still be used. It would be great if you can fix the scripts and configs, you would help @vanessaNWK with her work. It is not so ideal if new wrapper scripts get created instead of fixing the original scripts.

**Comment by markus2330** [comment]
fixed with #1950
