### ISSUE TITLE
gi possible cmake errors

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#1954]
## Steps to Reproduce the Problem

Build elektra with all plugins + bindings on a system with all listed requirements (cmake does not complain about anything missing).

Trying to run tests afterwards will let gi bindings fail because neither lua or python can find required packages.

## Expected Result

Tests should pass or bindings should not be included when requirements not met

## Actual Result

Bindings get built and tests fail

## System Information

- Elektra Version: master
- Docker container from #1866 - stretch

## Further Log Files and Output
https://build.libelektra.org/jenkins/blue/organizations/jenkins/elektra-jenkinsfile/detail/elektra-jenkinsfile/182/pipeline

**Comment by ingwinlu** [comment]
@markus2330 I think this was why I disabled deprecated bindings in #1866.

**Comment by ingwinlu** [comment]
might just need paths set for tests similar to https://github.com/ElektraInitiative/libelektra/blob/master/src/bindings/swig/lua/tests/CMakeLists.txt#L13

**Comment by ingwinlu** [comment]
Remove https://github.com/ElektraInitiative/libelektra/blob/master/scripts/jenkins/Jenkinsfile#L74 when resolved.

**Comment by markus2330** [comment]
I am closing the issue: GI are deprecated.
