### ISSUE TITLE
qt-gui: creation from keys in root

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#196]
Following situation: given that no key in user exists, "user" is still shown on the side (makes sense, because otherwise there would be no way to create user keys).

When I click on user and say New ->Key (Besides that Key Value is auto-focused, but this should be easy to fix) and put a/b/c as name, I get:

(- for the green arrow, _ for the black)

    - user
     - user
      - a
       b _

So it seems like an additional user key is added.

Expected behaviour:

    - user
      - a
       b _

**Comment by 0003088** [comment]
I could not recreate that, works like expected (also keyname is autofocused and not keyvalue). That's strange.

**Comment by markus2330** [comment]
I did not find a way to reproduce the focus issue every time. It does not occur the first time, but it happens sometimes. Maybe its a xinerama focus problem and beyond what can be done in qml. More problematic, however, is the focus in the tree view. On right clicks no new entry is selected but the action is done on whatever was selected before.

In current master I also cannot reproduce the above "double-user" issue, its really strange. It may have something to do with the mountpoints but I do not know how they were when I could reproduce it.

There are other "user" related issues, though:
1.) one can remove the user key and cannot recreate it (w/o restarting gui)
2.) one cannot change the value or meta data of the (consider that as low priority feature request, there is not really much usecase why one should do that. But maybe its an easy fix)

So consider the removal of "user" as new #196 and the others just as question.

**Comment by 0003088** [comment]
The user node cannot be edited because  name, value and metadata will be set when a node is edited and trying to setBaseName() on user throws a keyinvalidname exception.
