### ISSUE TITLE
Check for common errors in build server

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1966]
There are two kinds of errors that sometimes slip through:

1. Release notes were forgotten. This produces a huge effort for the release: all commits need to be checked. The check is trivial:
```
git diff --exit-code doc/news/_preparation_next_release.md || echo "You must edit release notes for every commit"
```
2. Sometimes PRs were not rebased after releases and thus their parents/children cross the release tag. This might only be an inconvenience when browsing through the history but maybe there is an easy way to check for this and automatically ask for rebases in such situations.

Can we add -fast checks for such situations?

**Comment by markus2330** [comment]
> sure, but shouldn't you be able to PR that on your own now that we have documentation in the Jenkinsfile :P?

Yes, I already considered this :smile: If I write it, it has the advantage that you won't be the bad guy who lets the build jobs of all PRs fail :+1: 

> should be possible equally simple

Thanks for looking that up but help for the script would be highly appreciated.

**Comment by markus2330** [comment]
@ingwinlu Would git diff master produce correct results? (Is "master" set to the master as on github, or does Jenkins merges the PR into master?)

**Comment by ingwinlu** [comment]
currently the tests run of a merge of the pr + master, but the refspec used to check it out includes origin/master hence you can use this to make a diff.

**Comment by markus2330** [comment]
Thank you, so git "diff origin/master ..." should work?

Could you please document that, too?
