### ISSUE TITLE
EVP_EncryptFinal

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1969]
As shown in linker warnings in  #1760, are we sure we do not misuse EVP_EncryptFinal?

```
CMakeFiles/elektra-crypto_openssl.dir/openssl_operations.c.o: In function `elektraCryptoOpenSSLEncrypt':
openssl_operations.c:(.text+0x3a5c): warning: warning: EVP_EncryptFinal is often misused, please use EVP_EncryptFinal_ex and EVP_CIPHER_CTX_cleanup
CMakeFiles/elektra-crypto_openssl.dir/openssl_operations.c.o: In function `elektraCryptoOpenSSLDecrypt':
openssl_operations.c:(.text+0x462b): warning: warning: EVP_DecryptFinal is often misused, please use EVP_DecryptFinal_ex and EVP_CIPHER_CTX_cleanup
```

**Comment by petermax2** [comment]
`EVP_CIPHER_CTX_cleanup` is invoked in `elektraCryptoOpenSSLHandleDestroy`.

The man page says:

    EVP_EncryptFinal(), EVP_DecryptFinal() and EVP_CipherFinal() are identical to EVP_EncryptFinal_ex(),
       EVP_DecryptFinal_ex() and EVP_CipherFinal_ex(). In previous releases they also cleaned up the ctx, but this is no longer
       done and EVP_CIPHER_CTX_clean() must be called to free any context resources.

Since we invoke `EVP_CIPHER_CTX_cleanup` at the end, everything should be fine.

**Comment by petermax2** [comment]
I was sticking primarily to the OpenSSL documentation and the O'Reilly book[1] during development.

[1]  Jon Viega, Pravir Chandra, and Matt Messier. 2002. Network Security with Openssl (1st ed.). O'Reilly & Associates, Inc., Sebastopol, CA, USA.

**Comment by petermax2** [comment]
But it would be interesting what kind of "misuse" the linker spots here. It is very vague.
