### ISSUE TITLE
qt-gui: QML Type Error

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#197]
When changes are present one will be asked to save. When saying yes it will be properly saved, but also a qml error is printed in the console:

    qrc:/qml/main.qml:760: TypeError: Cannot call method 'get' of undefined

**Comment by 0003088** [comment]
Seems to only occur after certain actions, since a first test did not result in the message. Will keep an eye on it.

**Comment by markus2330** [comment]
It was rather a pinpoint to that line of code. I thought there is an obvious, but unimportant thing missing.
