### ISSUE TITLE
jessie repo

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#1976]
The jessie debian package repo is currently available via https://debian-stable.libelektra.org/ and should be updated to reflect that is no longer stable.

**Comment by markus2330** [comment]
What do you mean by "update repo". Do you mean to update the DNS entry?

What about removing these aliases altogether and only use:

- debian-jessie-repo
- debian-stretch-repo
- debian-buster-repo

**Comment by markus2330** [comment]
Isn't it better to have all repos on one server? (a7?)

Can you update the Apache configs then?

**Comment by markus2330** [comment]
The jessie repo is not really important, the stretch repo is.

**Comment by ingwinlu** [comment]
well then I have some good news for you:
https://debian-stretch-repo.libelektra.org/pool/main/e/elektra/
