### ISSUE TITLE
qt-gui: renaming keys in the middle leads to wrong list view

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#198]
Given the keys:

```
user/guitest
user/guitest/A
user/guitest/B
user/guitest/C
```

When user/guitest is renamed to user/Guitest first user/guitest disappears.

When synchronization is pressed, user/guitest is there again, but in gray (which is correct).
But the right side list view wrongly displays A, B, C for both guitest and Guitest. Only Guitest has the black arrow (wrongly)

The keys in the database are correct:
```
user/Guitest
user/guitest/A
user/guitest/B
user/guitest/C
```
 so after restarting everything is as it should be.

Expected outcome: directly display in the way its displayed after restart.

**Comment by 0003088** [comment]
confirmed. I'll look into it.
