### ISSUE TITLE
shell recorder: safe working directory

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1982]
It might be a good idea to create a temporary directory below TMPDIR and set HOME and PWD to this path. Potential leftovers and programming errors would only affect this directory.

This is already done for the cframework test cases and works there quite well.

EDIT:

Furthermore, we need variables, that:

- point to the Markdown file executed
- point to the top-level source dir

see also #1955 and #1981 for rationale

**Comment by markus2330** [comment]
This way we would also get rid of the leftovers files "stderr" and stdout" which are left in the source repo from time to time.

**Comment by markus2330** [comment]
@sanssecours wrote:

>  That is certainly a must have, if we execute tests in a random location. This behavior sounds also very similar to the way Cram handles this: Cram sets the variable TESTDIR to the location of the file under test.

Could you please elaborate? TEST**DIR** points to a file?

**Comment by sanssecours** [comment]
> Could you please elaborate? TEST**DIR** points to a file?

The variable saves the directory of the file under test. For example, if your file under test is `foo/bar/test.t`, then the variable contains the value `foo/bar`.
