### ISSUE TITLE
tagging of master debian packages

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#1986]
We currently build debian packages and only tag them with the 'upcoming' version tag.

Would it make more sense to use the git description as a version tag?

**Comment by markus2330** [comment]
`-v` please. Which advantage does it have to use the git description?

**Comment by ingwinlu** [comment]
we generate a package and tag it with 0.8.23.
Then we generate a new package, delete the old one and name the new one 0.8.23.

For me as an outsider to debian packaging this does not seem rational to have two different versions named the same.

git description produces 'names' for current commits that are more readable than just the commit hash. The default is <lasttag>-<commits since tag>-<shorthash>. In our case it would look like `0.8.22-622-gfbe50a336'.

So the next time when something gets merged into master this obviously changes and we would get a new unique version identification for the packages.

**Comment by markus2330** [comment]
> For me as an outsider to debian packaging this does not seem rational to have two different versions named the same.

It is not the same across builds, we append the build ID (or we did it previously, isn't it done now?)

> git description produces 'names' for current commits that are more readable than just the commit hash.

You mean "git describe", okay now its clear :wink: 

Yes, also okay from my side. I think both "git describe" and appending the build ID is somewhat unusual for Debian packages.

**Comment by ingwinlu** [comment]
we use dch -l to append that string, I don't think that actually modifies the version correctly. The reason why I believe this (and why i want to move to another scheme) is that currently I have to remove the existing package from the repository before adding the new one. reprepro complains about the missmatching checksums and so on.

but then again i know nothing about debian packaging and best practises and I did find very little useful information on the matter.

**Comment by markus2330** [comment]
Maybe only the source package has the same version/name.

Afaik there are little rules, except how to compare version numbers, see https://manpages.debian.org/wheezy/dpkg-dev/deb-version.5.en.html

Most packages with many updates simply use the date (20180513).

Sometimes you see `+svn<svnid>`, sometimes `~svn<svnid>` but this is not as common in git. E.g. libcrystalhd3 has version `1:0.0~git20110715.fdd2f19-12` or  libfreerdp-cache1.1 has version `1.1.0~git20140921.1.440916e+dfsg1-13+deb9u2` but I doubt that this is best practice :wink:
