### ISSUE TITLE
website: rename application-config.json.tpl to application-config.json

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1987]
## Steps to Reproduce the Problem

Install Elektra and call `kdb rest-frontend`

## Expected Result

A website at `http://localhost:9000`

## Actual Result

```
Loading "Gruntfile.js" tasks...ERROR
>> Error: Unable to read "application-config.json" file (Error code: ENOENT).
Warning: Task "server" not found. Use --force to continue.

Aborted due to warnings.
```

## Workaround

`mv application-config.json.tpl application-config.json` and install Elektra again (to retrigger node install).

## System Information

- Elektra Version: master

**Comment by ingwinlu** [comment]
see here: https://github.com/ElektraInitiative/libelektra/tree/master/src/tools/rest-frontend#application-configjson

you are supposed to mount the config and handle it with kdb in the current setup.

I thought about removing kdb from the whole process as well so we would not need to build it for the website deployment but then again, it is probably good to have some kind of 'real world application' in our tests.

**Comment by markus2330** [comment]
Yes, but in this case I did not want to change the config, the default would have worked for me.

In retrospective I find it more intuitive if "kdb mount-rest-frontend-config" only mounts (and not copies a template).

I also think there is little use of "fail-by-default" if it could as well listen to localhost and do what most people doing a local installation expect (and I expected and hence created this issue).
