### ISSUE TITLE
bashisms: error but does not fail

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#1994]
## Steps to Reproduce the Problem

Run bashism as currently done on the build server during kdb run_all

## Expected Result

If test is finding problems it should report it as an error.

## Actual Result

```
--- running check_bashisms ---



ELEKTRA SCRIPTS BASHISMS TEST

find: unknown predicate `-E'
Try 'find --help' for more information.
/home/jenkins/workspace/libelektra_PR-1991-I6WB67JAHEJ43V4YFB2VEFGWV2OINNBNLLWTUAKWXVNIIW35FWKQ/system/lib/elektra/tool_exec/check_bashisms: 1015: /home/jenkins/workspace/libelektra_PR-1991-I6WB67JAHEJ43V4YFB2VEFGWV2OINNBNLLWTUAKWXVNIIW35FWKQ/system/lib/elektra/tool_exec/check_bashisms: .+(/docker/.+|check-env-dep|Jenkinsfile(.daily)?|kdb_zsh_completion|sed|\.(cmake|fish|in|md|txt))$: not found
check_bashisms RESULTS: 1 test(s) done 0 error(s).
```

## System Information
- Elektra Version: master

## Further Log Files and Output

https://build.libelektra.org/jenkins/job/libelektra/job/PR-1991/2/execution/node/617/log/

**Comment by sanssecours** [comment]
Thank you for reporting the bug. I think the problem here is is that the GNU version of `find` does not support the `-E` flag.

**Comment by markus2330** [comment]
Thank you for reporting and fixing!
