### ISSUE TITLE
cmake: binding need plugin like removal behaviour

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#2007]
src/libs/notification seems to not get disabled when io_uv is removed
```
[ 71%] Linking C executable ../../../../bin/example_notification_async
/usr/bin/ld.gold: error: cannot find -lelektra-io-uv
/home/jenkins/workspace/libelektra_PR-1963-UY7VIGJMXZ2D2SSXYCECW7I6XLHKVOJM6XQS67PEYRQNRNHU5NRA/src/libs/notification/example/example_notification_async.c:60: error: undefined reference to 'uv_default_loop'
/home/jenkins/workspace/libelektra_PR-1963-UY7VIGJMXZ2D2SSXYCECW7I6XLHKVOJM6XQS67PEYRQNRNHU5NRA/src/libs/notification/example/example_notification_async.c:60: error: undefined reference to 'uv_stop'
/home/jenkins/workspace/libelektra_PR-1963-UY7VIGJMXZ2D2SSXYCECW7I6XLHKVOJM6XQS67PEYRQNRNHU5NRA/src/libs/notification/example/example_notification_async.c:86: error: undefined reference to 'uv_default_loop'
/home/jenkins/workspace/libelektra_PR-1963-UY7VIGJMXZ2D2SSXYCECW7I6XLHKVOJM6XQS67PEYRQNRNHU5NRA/src/libs/notification/example/example_notification_async.c:87: error: undefined reference to 'elektraIoUvNew'
/home/jenkins/workspace/libelektra_PR-1963-UY7VIGJMXZ2D2SSXYCECW7I6XLHKVOJM6XQS67PEYRQNRNHU5NRA/src/libs/notification/example/example_notification_async.c:125: error: undefined reference to 'uv_run'
/home/jenkins/workspace/libelektra_PR-1963-UY7VIGJMXZ2D2SSXYCECW7I6XLHKVOJM6XQS67PEYRQNRNHU5NRA/src/libs/notification/example/example_notification_async.c:135: error: undefined reference to 'uv_run'
/home/jenkins/workspace/libelektra_PR-1963-UY7VIGJMXZ2D2SSXYCECW7I6XLHKVOJM6XQS67PEYRQNRNHU5NRA/src/libs/notification/example/example_notification_async.c:137: error: undefined reference to 'uv_default_loop'
/home/jenkins/workspace/libelektra_PR-1963-UY7VIGJMXZ2D2SSXYCECW7I6XLHKVOJM6XQS67PEYRQNRNHU5NRA/src/libs/notification/example/example_notification_async.c:137: error: undefined reference to 'uv_loop_close'
collect2: error: ld returned 1 exit status
src/libs/notification/example/CMakeFiles/example_notification_async.dir/build.make:99: recipe for target 'bin/example_notification_async' failed
make[2]: *** [bin/example_notification_async] Error 1
CMakeFiles/Makefile2:12515: recipe for target 'src/libs/notification/example/CMakeFiles/example_notification_async.dir/all' failed
make[1]: *** [src/libs/notification/example/CMakeFiles/example_notification_async.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by ingwinlu** [comment]
on closer inspection io_uv does not check if io has been disabled.

**Comment by ingwinlu** [comment]
@waht any idea why the existing https://github.com/ElektraInitiative/libelektra/blob/master/src/libs/notification/example/CMakeLists.txt#L19 does not do the trick?

**Comment by ingwinlu** [comment]
It seems that the check is called before it is excluded.

**Comment by ingwinlu** [comment]
@markus2330 can I move the notification example into the example folder? Or should I delay the add otherwise?

**Comment by ingwinlu** [comment]
Just to recap: There is a circular dependency going on with the notification library async example requiring io_uv before it can be excluded by conventional means.

**Comment by markus2330** [comment]
Thank you for creating the issue!

For me, moving the example to some later-included directory sounds fair (and examples in particular makes a lot of sense).

But because @waht is still working on this topic, he should be included in the decision.

**Comment by waht** [comment]
The `check_binding_included` function operates on the `BINDINGS` variable and as @ingwinlu said it cannot know exclusion due to missing dependencies in advance before bindings were processed (`check_binding_was_added` can be used for this). To deal with such cases the example's cmake-code additionally checks for the libuv library.
Seems like I missed some condition or something.
Can you link a log from a build server? Maybe this will provide more insight.

Generally, moving the example to the examples folder is a great idea - I was not aware of the folder (nor did I search for it). I would move the example in PR #1850 if thats ok.

**Comment by ingwinlu** [comment]
> To deal with such cases the example's cmake-code additionally checks for the libuv library.

Right, but sadly when cmake is processing the lib dir it has not been removed yet, which in turn lets https://github.com/ElektraInitiative/libelektra/blob/master/src/libs/notification/example/CMakeLists.txt#L19 return Yes.

> check_binding_was_added 

Same problem, hence it also can not be used in this case.

> moving the example to the examples folder 

Other libs would also be affected as they also provide their examples in src/lib/bla/examples. The difference is that they are not using 'external' dependencies.

> Can you link a log from a build server? Maybe this will provide more insight.

it is all part of #1963. The following commit is what I try to do for io: https://github.com/ElektraInitiative/libelektra/pull/1963/commits/79b8d467818a0b077b13f275171268923c0ec5d3.
https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-1963/29/pipeline/274/ is the matching testrun.

The minimal change to make it pass is to just check for ENABLE_ASAN in the async example as well, but I feel like this is not the way to go. Replicating the plugin behaviour for add + removal would be much more futureproof.

**Comment by ingwinlu** [comment]
I will manually disable the example for asan builds for now and mention this issue for tracking in the commit.

Changing the cmake behaviour here is out of scope of the original issue and is not a trivial addition.

**Comment by ingwinlu** [comment]
Reopened with different title as we only implemented a workaround.
