### ISSUE TITLE
Web UI: communication issue

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2014]
@0003088 Could you please report the bug you told me about where Web UI does not compile?

In #1901 we are thinking about creating a live demo, so that people do not have to install it. Nevertheless, failed attempts are crucial for improvement.

Btw. I am afraid we do not have a t-shirt in the requested size anymore (see #667) but do not worry, we will order new ones.

**Comment by markus2330** [comment]
@0003088 Did it work for you now?

**Comment by 0003088** [comment]
Sry, I did not test it again yet. But 'does not compile' is not an accurate description of what happened, it compiled fine, there just seemed to be a problem regarding the communication of server and client when I remember correctly.

**Comment by markus2330** [comment]
Thank you! I'll keep the issue open. It would be great to get some feedback.

**Comment by 0003088** [comment]
Sorry for the late reply, I was a little busy during the last few days. So today I tested the web gui again. I cloned the latest version and built it. Then I entered `kdb run-elektrad` which led to the following output
```

> @elektra-web/elektrad@1.3.0 start:prod /usr/local/share/elektra/tool_data/web/elektrad
> cross-env NODE_ENV=production DEBUG=elektrad:*,-*debug,-*log node build/

  elektrad:info @elektra-web/elektrad v1.3.0 starting +0ms
  elektrad:info |- using default kdb command +13ms
  elektrad:info |- versions: { api: 1, elektra: { version: '0.8.23', major: 0, minor: 8, micro: 23 } } +0ms
  elektrad:info `-> running on http://localhost:33333 +7ms
```
which looks fine to me. In a new terminal I entered `kdb run-web` which led to

```
> @elektra-web/webd@1.3.0 start:prod /usr/local/share/elektra/tool_data/web/webd
> cross-env NODE_ENV=production DEBUG=webd:*,-*debug,-*log node build/

  webd:info @elektra-web/webd v1.3.0 starting +0ms
  webd:info |- using default kdb command +80ms
  webd:info |- versions: { api: 1, elektra: { version: '0.8.23', major: 0, minor: 8, micro: 23 } } +0ms
  webd:client:info prod mode: serving client static assets +7ms
  webd:info `-> running on http://localhost:33334 +3ms
```
which also looks fine? But when I open a webbrowser and enter a hostname (pc) and url ("http://127.0.0.1:33333") on the config screen I get 

![screenshot_20180626_202548](https://user-images.githubusercontent.com/2543279/41931814-76a39dce-797f-11e8-88e2-8669f5d5f450.png)

I did not debug this any further maybe the reason why it's not working is obvious to you, it just does not seem to work out of the box on my machine (Manjaro Linux)

Best

**Comment by markus2330** [comment]
Thank you for looking into it!

Did you also *install* the latest Elektra version? (Web UI uses the installed `kdb`.)

@omnidan Do you have an idea where the problem could be?

**Comment by omnidan** [comment]
@markus2330 I'm not sure, but he is running an old version of the Web UI ("Done" button is still there, version not in header).

`Did not find key '/'` should not be considered an error, and I get the same thing when running `kdb get /` on my machine (although the Web UI works fine for me). Maybe the check fails on your machine for some reason? https://github.com/ElektraInitiative/libelektra/blob/master/src/tools/web/kdb.js#L101

**Comment by markus2330** [comment]
Thank you for looking into it!

We are looking forward to more feedback :smile:
