### ISSUE TITLE
rebuilding Debian packages

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2027]
I just updated the debian branch e37ea2f8478dba73b7a5e73b90b6a87031b4efb9 and would like to rebuild the Debian packages now (by the build server, so that they are available in our repo).

Is there some way to retrigger the building of Debian packages? Does every push to the debian branch also retrigger the build jobs?

Some clarification in the docu when the build jobs are started would be great!

**Comment by ingwinlu** [comment]
> Is there some way to retrigger the building of Debian packages? 

https://build.libelektra.org/jenkins/job/libelektra/job/master/ and 'Build Now'

> Does every push to the debian branch also retrigger the build jobs?

No the debian branch is blacklisted for the 'normal' build as it is not 'buildable' on its own atm.

You could create a job that monitors 'debian' though and trigger a build of master after changes if you want.

**Comment by markus2330** [comment]
Thank you, I can live with manual triggering, debian isn't updated too often. Of course it would be convenient if debian packages are rebuilt automatically (describing the packages is the whole purpose of the debian branch).

I moved the docu request to #1974, thus you unassigned yourself from here.

**Comment by markus2330** [comment]
Manually retriggering worked perfectly. The Debian packages are already available, and the testcases of the hexnumber plugin work now. (lua still fails)

A small drawback is that people need a login in Jenkins to be able to do that. But we had the same problem also before.
