### ISSUE TITLE
Meaning of green in build server

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2043]
I think we should be very careful not to make anything "green" if it was not successful.

- [ ] Several people (iirc @mpranj and @kodebach) reported that sometimes the GitHub build status is green, although it is actually still running.
- [ ] In PRs the "Deploy Homepage" stage is green, although actually: "Stage skipped: Deploy Homepage"

**Comment by ingwinlu** [comment]
>  Several people (iirc @mpranj and @kodebach) reported that sometimes the GitHub build status is green, although it is actually still running.

bug upstream. already fixed in https://github.com/jenkinsci/github-branch-source-plugin/pull/175, not released though

>  In PRs the "Deploy Homepage" stage is green, although actually: "Stage skipped: Deploy Homepage"

I can only mark it as unstable, which would be translated to a failed build on github though.

**Comment by ingwinlu** [comment]
I issued the update for the github source plugin. I would have closed after the restart.

But I don't plan to do anything else for this issue so I unassigned myself.

**Comment by markus2330** [comment]
> I would have closed after the restart.

Thank you! Nothing else is to do.

**Comment by ingwinlu** [comment]
as far as i can tell the issue with to early reporting success has been resolved.

to implement better behaviour for the 'skipped' stages stuff we would need support for 'status per stage' which is en open jenkins pipelien feature and is supposed to be implemented sometime in the future.

**Comment by ingwinlu** [comment]
issue still persists

**Comment by ingwinlu** [comment]
issue is fixed
