### ISSUE TITLE
Travis: Haskell Build Job Always Fails on Fork

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2050]
# Steps to Reproduce the Problem

1. Fork the Elektra repository at GitHub
2. Activate Travis for the newly created clone
3. Run the Travis tests suite

# Expected Result

Every build jobs completes successfully.

# Actual Result

The Haskell build job always fails, printing the following output:

```
[190/390] Generating sandbox/cabal.sandbox.config
FAILED: src/plugins/typechecker/sandbox/cabal.sandbox.config 
cd /Users/travis/build/sanssecours/build/src/plugins/typechecker/sandbox && /usr/local/bin/cabal sandbox delete -v0 && /usr/local/bin/cabal sandbox init -v0 && /usr/local/bin/cabal sandbox add-source -v0 /Users/travis/build/sanssecours/build/src/libs/typesystem/libfa && /usr/local/bin/cabal sandbox add-source -v0 /Users/travis/build/sanssecours/build/src/libs/typesystem/specelektra && /usr/local/bin/cabal install --only-dependencies --avoid-reinstalls --offline -v0
cabal: Error: some packages failed to install:
libfa-1.0.8.23-ZfhKuK3orHDHB6gQt3Gon failed during the building phase. The
exception was:
ExitFailure 1
specelektra-1.0.8.23-IReNAIDscgT7DKprOslWT2 depends on specelektra-1.0.8.23
which failed to install.
[192/390] Generating libHShaskell-ghc8.2.2.dylib
ninja: build stopped: subcommand failed.
```

# Examples

- [Example 1](https://travis-ci.org/sanssecours/elektra/builds/388443197)
- [Example 2](https://travis-ci.org/sanssecours/elektra/builds/388443939)
- [Example 3](https://travis-ci.org/sanssecours/elektra/builds/388607913)
- [Example 4](https://travis-ci.org/sanssecours/elektra/builds/388638435)

**Comment by markus2330** [comment]
Thank you for reporting this problem. Even the sporadic failures were quite annoying. (as discussed in #2045)

**Comment by e1528532** [comment]
have you tried cleaning the travis caches if there are any? i think they got corrupted at some point due to constant changes, as it was the case for my own fork. Or do you really mean a newly created fork?

**Comment by sanssecours** [comment]
> have you tried cleaning the travis caches if there are any?

Thank you for the helpful response. I did not know that clearing the cache was possible. I removed the cache in my own copy of the repo now. Hopefully this procedure fixes the build problems.

**Comment by e1528532** [comment]
I am not sure if this is really the root issue, the above PR might help though

**Comment by sanssecours** [comment]
Unfortunately, clearing the cache did not solve the issue.

**Comment by e1528532** [comment]
i think now it should work now, as language-c got updated so c2hs will use 0.8.1 now instead if 0.8 is not hidden in some cache. I've cleared the caches on this repo's travis to avoid that issue.
