### ISSUE TITLE
manpages - wrong content

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#2059]
https://www.libelektra.org/manpages/kdb-change-storage-symlink
`kdb-change-resolver-symlink -- Changes the default resolver symlink`

https://www.libelektra.org/manpages/kdb-change-resolver-symlink
`kdb-change-storage-symlink -- Changes the default storage symlink`

**Comment by markus2330** [comment]
@ingwinlu  Thank you for reporting!

I thought that I could use my "git-swap" command (it does a git mv and adds the temporary file), but @sanssecours was faster :wink:
