### ISSUE TITLE
pluginprocess.c is not C99

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2061]
In the discussions in #2056 we found that pluginprocess.c contains non-C99 code.

- src/libs/pluginprocess/pluginprocess.c:275:6: warning: implicit declaration of function ‘mkdtemp’ [-Wimplicit-function-declaration
- src/libs/pluginprocess/pluginprocess.c:275:30: warning: comparison between pointer and integer

EDIT: The second warning seems to be only a aftereffect of the first warning.

**Comment by e1528532** [comment]
mkdtemp is probably the best way to create a temporary directory though and i think i had a warning when using mktemp (though i don't remember exactly). It should be defined in stdlib.h present in pluginprocess.c according to https://linux.die.net/man/3/mkdtemp , though its probably newer than C99 i guess. How do we generally deal with such issues?

**Comment by markus2330** [comment]
Looking at it more closely, the problem seems to be trivial. Just add a mkdtemp detection in cmake/Modules/FindPluginprocess.cmake (like you already did with mkfifo and fork).

Btw. "FindPluginprocess.cmake" is a very confusing name, and PLUGINPROCESS_FOUND even more so. I expected it searches for a plugin named "process", not that it searches for the *dependences* of a library called pluginprocess.

Other options are:

- Move the lib to the plugin processplugin (#1783) or to a binding. Plugin/Bindings can be simply excluded if some dep is not present.
- We also thought about creating a LIBS CMake variable, that does the same as PLUGINS for libraries.
- have an alternative implementation for mkdtemp if it is not available.

**Comment by ingwinlu** [comment]
@e1528532 you need the whole man page you linked.
```
Feature Test Macro Requirements for glibc (see feature_test_macros(7)):
_BSD_SOURCE
|| /* Since glibc 2.10: */
(_POSIX_C_SOURCE >= 200809L || _XOPEN_SOURCE >= 700)
```
So yes it is in the header, but not made available unless you fulfill those flags.
In a35813d5d0f898743bb5d07ed06c03494baeab0d i implemented those checks for our cframework.

**NOTE**.: Those are only compatibilities for glibc, though most libc implementations should have 200809 POSIX compatibility they might have other requirements to enable them or enable it automatically.
