### ISSUE TITLE
XDG config envs do not accept quoted paths

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#2062]
## Steps to Reproduce the Problem

```sh
The command /home/jenkins/workspace/libelektra_PR-2060-UC533EJXFEGIMCPXROAS5K3DQGSNDLWE3TI7WV4NENQDLGK2UB4A@3/build/bin/kdb get failed while accessing the key database with the info:
 Sorry, 8 warnings were issued ;(
 Warning (#100):
	Description: environment variable is not absolute and cannot be used
	Ingroup: plugin
	Module: resolver
	At: /home/jenkins/workspace/libelektra_PR-2060-UC533EJXFEGIMCPXROAS5K3DQGSNDLWE3TI7WV4NENQDLGK2UB4A@3/src/plugins/resolver/filename.c:194
	Reason: XDG_CONFIG_HOME contains a path that is not absolute (violates XDG specification) and thus it was skipped: '/home/jenkins/workspace/libelektra_PR-2060-UC533EJXFEGIMCPXROAS5K3DQGSNDLWE3TI7WV4NENQDLGK2UB4A@3/xdg/user'
```

Modifying the path from
`'/home/jenkins/workspace/libelektra_PR-2060-UC533EJXFEGIMCPXROAS5K3DQGSNDLWE3TI7WV4NENQDLGK2UB4A@3/xdg/user'`
to
`/home/jenkins/workspace/libelektra_PR-2060-UC533EJXFEGIMCPXROAS5K3DQGSNDLWE3TI7WV4NENQDLGK2UB4A@3/xdg/user`
allows all tests to pass.

## Expected Result

quotes should be stripped before testing for an absolute path

## Actual Result

quotes are treated as part of the path and hence resolver.c treats it as relative path (which in turn violates XDG specs).

## System Information

- Elektra Version: master

## Further Log Files and Output
https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2060/5/pipeline/340/

**Comment by markus2330** [comment]
Thank you for reporting the problem! Could you please point me to the place where the quoting is explained? Is it in https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html?

**Comment by ingwinlu** [comment]
Nowhere. But assume you want a path for xdg with spaces, then you would need quotes around it.

The current resolver.c implementation only checks the first char of the path to determine if it is an absolute path which might not be an `/` in case the path is quoted.

**Comment by markus2330** [comment]
> Nowhere. But assume you want a path for xdg with spaces, then you would need quotes around it.

Why? Only colons would need to be escaped. But I cannot find any reference that paths with colons should be possible.

**Comment by markus2330** [comment]
Of course you always need to quote paths to make the shell happy (to allow newlines and avoid the problems mentioned in the link). But the shell removes these quotes, so they never end up in the environment and are never seen by Elektra.

If you put quotes literally in the string, they are interpreted as file path. The only non-file path character in the *PATH variables is colon (`:`). But afaik there is no escaping so it is simply not possible to have colon in the file paths.

**Comment by ingwinlu** [comment]
Closed as a wontfix
