### ISSUE TITLE
INI: support not having spaces around =

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2065]
INI currently creates a space around =. This behavior breaks some software, e.g. shell files but also courier config files:

```
sudo kdb mount /etc/courier/imapd system/courier/imapd ini
sudo kdb set system/courier/imapd/MAILDIRPATH Mail
sudo /etc/init.d/courier-imap restart
#> Restarting Courier IMAP server: imapd failed!
```

(The error message clearly indicates the problem.)

Is there a good reason to have these spaces? Otherwise I would suggest we simply remove them by default. And if people want them, they can choose their delimiter to be `" = "`?

**Comment by alexsaber** [comment]
Hi! Can you please assign me to this issue? I have picked 3 more ini related problems.

**Comment by markus2330** [comment]
Thank you, I assigned you these issues.

I think this issue is a good starting point to get to know the parser.

**Comment by markus2330** [comment]
Finally done!
