### ISSUE TITLE
cmake haskell

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#2067]
## Steps to Reproduce the Problem

Build Elektra with haskell enabled, same as our build jobs.
Cmake issues the following error multiple times:
`ls: cannot access '/home/jenkins/.cabal/lib': No such file or directory`.

## Expected Result

When the directory does not exist it should not be queried for installed packages.

## Actual Result

The warning gets issues multiple times during cmake.

## System Information

- Elektra Version: master

## Further Log Files and Output
https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/84/pipeline/173

**Comment by e1528532** [comment]
I've seen that as well but i have no idea what queries that directory. As it doesn't seem to matter apart from the unnecessary output i agree with the low priority for now

**Comment by ingwinlu** [comment]
Further the following just happened on master:
```
[ 96%] Built target testtool_pluginspec
/home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@2/build/src/bindings/haskell/dist/setup/setup:
runProcess: runInteractiveProcess: exec: resource busy (Text file busy)
src/bindings/haskell/CMakeFiles/c2hs_haskell_tests.dir/build.make:78: recipe for target 'src/bindings/haskell/dist/build/testhaskell_basic/testhaskell_basic' failed
make[2]: *** [src/bindings/haskell/dist/build/testhaskell_basic/testhaskell_basic] Error 1
CMakeFiles/Makefile2:15103: recipe for target 'src/bindings/haskell/CMakeFiles/c2hs_haskell_tests.dir/all' failed
make[1]: *** [src/bindings/haskell/CMakeFiles/c2hs_haskell_tests.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 96%] Linking CXX executable ../../../../bin/testtool_samemountpoint
[ 96%] Built target testtool_samemountpoint
[ 96%] Built target regexdispatcher
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
script returned exit code 2
```

**Comment by ingwinlu** [comment]
Issues in here are widely resolved

**Comment by markus2330** [comment]
It is an duplicate, I reported the same problem in #2139

Afaik, it is not resolved, though.
