### ISSUE TITLE
markdown shell recorder + spaces in directory fails

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#2068]
## Steps to Reproduce the Problem

Have a space in your build directory + run ctest

## Expected Result

tests should pass same as with 'normal' dir

## Actual Result

ALL testshell_markdown_ tests fail (shortened log):
```
        Start 187: testshell_markdown_tutorial_cascading
215/224 Test #187: testshell_markdown_tutorial_cascading ....***Failed    1.11 sec
Input: /home/jenkins/workspace/libelektra_PR-2063-LIVOSPL6L4UH5CAHYVKB57ZOFL2KYPEWGRHMTO5TDKMLMP5JUIOQ/doc/tutorials/cascading.md
/home/jenkins/workspace/libelektra_PR-2063-LIVOSPL6L4UH5CAHYVKB57ZOFL2KYPEWGRHMTO5TDKMLMP5JUIOQ/build directory/tests/shell/shell_recorder/shell_recorder.sh: 1001: export: directory/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin: bad variable name

        Start 188: testshell_markdown_kdb_complete
216/224 Test #188: testshell_markdown_kdb_complete ..........***Failed    0.68 sec
Input: /home/jenkins/workspace/libelektra_PR-2063-LIVOSPL6L4UH5CAHYVKB57ZOFL2KYPEWGRHMTO5TDKMLMP5JUIOQ/doc/help/kdb-complete.md
/home/jenkins/workspace/libelektra_PR-2063-LIVOSPL6L4UH5CAHYVKB57ZOFL2KYPEWGRHMTO5TDKMLMP5JUIOQ/build directory/tests/shell/shell_recorder/shell_recorder.sh: 1001: export: directory/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin: bad variable name
        Start 189: testshell_markdown_kdb_ls

217/224 Test #189: testshell_markdown_kdb_ls ................***Failed    0.80 sec
Input: /home/jenkins/workspace/libelektra_PR-2063-LIVOSPL6L4UH5CAHYVKB57ZOFL2KYPEWGRHMTO5TDKMLMP5JUIOQ/doc/help/kdb-ls.md
/home/jenkins/workspace/libelektra_PR-2063-LIVOSPL6L4UH5CAHYVKB57ZOFL2KYPEWGRHMTO5TDKMLMP5JUIOQ/build directory/tests/shell/shell_recorder/shell_recorder.sh: 1001: export: directory/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin: bad variable name

        Start 190: testshell_markdown_kdb_find
218/224 Test #190: testshell_markdown_kdb_find ..............***Failed    0.44 sec
Input: /home/jenkins/workspace/libelektra_PR-2063-LIVOSPL6L4UH5CAHYVKB57ZOFL2KYPEWGRHMTO5TDKMLMP5JUIOQ/doc/help/kdb-find.md
/home/jenkins/workspace/libelektra_PR-2063-LIVOSPL6L4UH5CAHYVKB57ZOFL2KYPEWGRHMTO5TDKMLMP5JUIOQ/build directory/tests/shell/shell_recorder/shell_recorder.sh: 1001: export: directory/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin: bad variable name

        Start 191: testshell_markdown_tutorial_validation
219/224 Test #191: testshell_markdown_tutorial_validation ...***Failed    2.22 sec
Input: /home/jenkins/workspace/libelektra_PR-2063-LIVOSPL6L4UH5CAHYVKB57ZOFL2KYPEWGRHMTO5TDKMLMP5JUIOQ/doc/tutorials/validation.md
/home/jenkins/workspace/libelektra_PR-2063-LIVOSPL6L4UH5CAHYVKB57ZOFL2KYPEWGRHMTO5TDKMLMP5JUIOQ/build directory/tests/shell/shell_recorder/shell_recorder.sh: 1001: export: directory/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin: bad variable name

< snipped >
```

## System Information

- Elektra Version: master

## Further Log Files and Output
https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2063/21/pipeline

**Comment by markus2330** [comment]
@sanssecours Did you stop using spaces in the build directory? Seems like it currently does not work. I am afraid I broke it with my commit 5d331cf7e8daf71ffd3f56cce7ab0a04a2de8133. Then maybe 0066dfeecef95e6248438cba0027e4b1c615f022 solves the problem? (But I am afraid it does not,   CMAKE_BINARY_DIR was already quoted)

Any idea what the line 1001 refers to? Is it the line we append in 
tests/shell/shell_recorder/CMakeLists.txt line 43/45?

**Comment by sanssecours** [comment]
> Did you stop using spaces in the build directory?

Nope. My build directory does look something like this: `/stuff/foo/bar/sp ac es/moar spaces/Elektra/build` though. The build directory on the build server looks a little bit different: `/stuff/foo/bar/build directory`. Anyway, I tried

```sh
mkdir 'Build Dir'
cmake .. -DBUILD_TESTING=ON -DBUILD_DOCUMENTATION=OFF -DTOOLS='kdb' -DBINDINGS='' -DPLUGINS='resolver_fm_hpu_b;dump;spec;list'
make test
```

which also worked on my machine, except for `testshell_markdown_kdb_find`, which failed because the `sync` plugin was not available.

> I am afraid I broke it with my commit 5d331cf.

I do not see a problem with this commit. The line produced by the CMake command looks fine on my machine too:

```sh
export KDB="kdb" PATH="…/Elektra/build/bin":$PATH
```

.

> Then maybe 0066dfe solves the problem?

Both the current code in `master` and the one from the commit above look fine to me.

> Any idea what the line 1001 refers to? Is it the line we append in
tests/shell/shell_recorder/CMakeLists.txt line 43/45?

As far as I can tell, yes.

**Comment by ingwinlu** [comment]
With the current master the issue is resolved.
