### ISSUE TITLE
cmake: Should we check if paths are writeable?

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#2070]
### new issue
Should cmake check if paths we use are actually usable?

### old issue
On our new build machine master can not be build. 

```
-- Include Plugin type

ls: cannot access '.'$'\n''.'$'\n''.'$'\n''.'$'\n''.'$'\n''.'$'\n''.'$'\n''.'$'\n''.'$'\n''.'$'\n''.'$'\n''./lib': No such file or directory

ls: cannot access '.'$'\n''.'$'\n''.'$'\n''.'$'\n''.'$'\n''.'$'\n''.'$'\n''.'$'\n''.'$'\n''.'$'\n''.'$'\n''./lib': No such file or directory

/.cabal: createDirectory: permission denied (Permission denied)

cabal: The package environment file

'/home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@3/build/src/plugins/typechecker/cabal.sandbox.config'

doesn't exist

cabal: The package environment file

'/home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@3/build/src/plugins/typechecker/cabal.sandbox.config'

doesn't exist

cabal: The package environment file

'/home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@3/build/src/plugins/typechecker/cabal.sandbox.config'

doesn't exist
```

https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/85/pipeline

**Comment by ingwinlu** [comment]
The new host did not have correct userid/groupid set for the jenkins user.

**Comment by ingwinlu** [comment]
Updated op + title to reflect that the original issue is resolved.
Now I would like to know if we can have some checks regarding paths passed to cmake.

**Comment by markus2330** [comment]
Which path? I am a bit confused about this issue.

If you mean the build path: cmake itself should introduce such checks and give proper error messages. It seems overkill to check if the build dir exists and has correct permissions. (We already have checks, however, if the build dir == source dir. The "FORCE_IN_SOURCE_BUILD" was needed because cmake at OpenWRT only supported in-source-builds. Maybe that is not true anymore, I am all for removing this legacy code.)

**Comment by ingwinlu** [comment]
We are not only needing the build directory for builds though.
For example the haskell cabal process needs write access to the HOME directory.

But yes it probably is overkill.

**Comment by markus2330** [comment]
> For example the haskell cabal process needs write access to the HOME directory.

Yes, that is a different matter then. But if cabal does not emit a useful error it is a bug of cabal.

But please document here which error message you got and what you needed to do to fix it.
