### ISSUE TITLE
testshell_markdown should be disabled if `bash` is not available

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#2077]
## Steps to Reproduce the Problem

build and run ctest on a system without bash.

## Expected Result

bash dependent tests are not executed

## Actual Result

```
138/172 Test #134: testshell_markdown_issue_template ........***Failed    0.00 sec
env: can't execute 'bash': No such file or directory
```

## System Information

- Elektra Version: master
- Operating System or Docker Container?
- Versions of other relevant software?

## Further Log Files and Output
https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2063/52/pipeline/444

**Comment by markus2330** [comment]
Thank you for reporting the problem!

As long term goal we want to get rid of bash, see #1938.

But excluding tests that need bash on a system without bash seems to be useful and not too much work. Greping for "env bash" it looks like the shell recorder is the only part which needs bash. So a check and if in `add_msr_test` should be enough.

**Comment by ingwinlu** [comment]
I tried implementing it via find_program but that produced more exclusion messages as I liked (I wanted to print exactly 1 if bash could not be found)

**Comment by ingwinlu** [comment]
I will probably just rewrite the shell recorder wo work with sh...

**Comment by ingwinlu** [comment]
@sanssecours I am getting close now. But can you explain to me what happens [here](https://github.com/ElektraInitiative/libelektra/blob/master/tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh#L139)?

That part isn't even parsing for me on bash :X
