### ISSUE TITLE
Show correct build status

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2087]
On the front page https://build.libelektra.org/jenkins/ the libelektra job is blue but with thunderstorm clouds.

As discussed this might only be an outdated aggregation. It would be enough for me to fix that but maybe there are even better solutions. In many projects you see little badges that show very short infos of the current builds. Can we add such badges to the website and the main README.md?

Btw.  libelektra-daily is red and I do not understand the errors. Is it maybe caused by recent tests/changes?

**Comment by ingwinlu** [comment]
> libelektra-daily is red and I do not understand the errors. Is it maybe caused by recent tests/changes?
Resolved via e1afbe55d3bb3897e1bd774cd5e71dd7bc1abc86.

As for the build status: there is nothing configurable there yet that would allow to specify which job should represent the folder AFAIK. You are welcome to look for existing tickets or create a new one.

It is already displayed for [brances](https://github.com/ElektraInitiative/libelektra/branches) and [commits](https://github.com/ElektraInitiative/libelektra/commits/master) on github.

**Comment by markus2330** [comment]
Thank you, the status in GitHub also resolves the problem. Could you please write about that in the documentation.

**Comment by ingwinlu** [comment]
> Could you please write about that in the documentation.

No as it is not controlled by us (github API) and thus can change at any minute. It is also not dependent on Jenkins as it is the same as with travis (or any other took using github api).

**Comment by markus2330** [comment]
Yes, gaining some control over the git interface is something we will discuss in the next meeting.
