### ISSUE TITLE
Have automatic plugin exclusion in add_plugin

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2088]
@tom-wa (understandably) complains that it is too difficult to write plugins that compile everywhere.

To make it much easier to write unportable plugins I propose to have something like:

`infos/portability = <specifier>`

where `<specifier>` is something like "Linux Musl", "POSIX 2008" or similar.

`add_plugin` reads this specifier and automatically removes the plugin if the condition is not fulfilled.

What do you think?

**Comment by ingwinlu** [comment]
> too difficult to write plugins that compile everywhere.

You don't need to write plugins that compile everywhere.
What you need to do is check if your requirements are available and disable your plugin/binding/... if not met.

Currently some parts of Elektra just assumes that their requirements are met. Even the cframework (which I assume is pretty core-y) silently assumes _GNU_SOURCE to be available and set.
Just coming up with some kind of magic for add_plugin would not be enough for this use case.

**Comment by markus2330** [comment]
> What you need to do is check if your requirements are available and disable your plugin/binding/... if not met.

Yes, but also this can be quite hard as we see for the date plugin #2080.

> Currently some parts of Elektra just assumes that their requirements are met. Even the cframework (which I assume is pretty core-y) silently assumes _GNU_SOURCE to be available and set.

Yes, such dependencies easily creep in. Thus I am in favour for C99 tests (#2092). cframework is not part of the core: it can be deactivated easily (BUILD_TESTING=OFF).

> Just coming up with some kind of magic for add_plugin would not be enough for this use case.

This proposal is only about plugins and the standards/systems we often have to do with.

**Comment by ingwinlu** [comment]
>  it can be deactivated easily (BUILD_TESTING=OFF).

Offtopic but: yes it can be deactivated that way, but would that also work for automatic disabling if requirements are not met? When I tried to check for it's required functions to be available and disable it later I ran into issues where other parts of Elektras cmake configuration tried to link to cframework targets anyway.

**Comment by markus2330** [comment]
@ingwinlu suggested that we specify which symbols a plugin needs.

There are some problems with this approach:

- not everything is a symbol, sometimes you e.g. need some macros
- symbols might be present but do not behave according the standard or we might need more than standards provide (e.g. #2080)
- it is quite some effort to enumerate all symbols

> Offtopic but: yes it can be deactivated that way, but would that also work for automatic disabling if requirements are not met? When I tried to check for it's required functions to be available and disable it later I ran into issues where other parts of Elektras cmake configuration tried to link to cframework targets anyway.

Automatic deactivation is only for plugins. To disable testing I prefer if people must manually select BUILD_TESTING=OFF.

**Comment by ingwinlu** [comment]
> not everything is a symbol, sometimes you e.g. need some macros

not an issue https://cmake.org/cmake/help/v3.0/module/CheckSymbolExists.html

> symbols might be present but do not behave according the standard or we might need more than standards provide

not an issue, they will be not found as they are not exported when the standard is not available

> it is quite some effort to enumerate all symbols

only the ones that are not in the c standard the core follows. the rest should be checked as it currently is.

**Comment by markus2330** [comment]
> not everything is a symbol, sometimes you e.g. need some macros

"need some macros" means: it must be a macro and not a symbol (or reverse). I have to admit that such requirements rarely happen.

>   not an issue, they will be not found as they are not exported when the standard is not available

see #2080: the symbol is found and only the unit tests told us that an modifier is missing. We have the same problem in `simpleini`: it uses printf (C99) but with modifiers only available in glibc.

So it is an practical problem that already occurred several times.

> only the ones that are not in the c standard the core follows. the rest should be checked as it currently is.

E.g. look at the resolver variants. It is unfeasible to check all symbols (in every variant) there. And it obviously cannot work with mingw.

**Comment by markus2330** [comment]
We need to have CMake detection code.
