### ISSUE TITLE
removal of added GNU_SOURCE before search

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#2091]
Should https://github.com/ElektraInitiative/libelektra/blob/master/src/include/CMakeLists.txt#L11
be removed?

if you add a definition to list that is not used during compilation you will get segfaults. It probably only works on systems that default export anything.

**Comment by markus2330** [comment]
I think @KurtMi added this for benchmarks.

Yes, we could move this to a bit less public place. (Where it is needed, i.e., in the benchmarks.)

**Comment by ingwinlu** [comment]
Ah I see his approach now. It is fine as it is working correctly in all cases.
