### ISSUE TITLE
c99 build

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#2092]
After #2063 is in I would like to add a new build job with the following properties:

- [ ] set -std=c99
- [x] add -Werror

It should check if Elektra properly disables plugins/bindings/... when standards are not met.

I started work on the patches in https://github.com/ingwinlu/libelektra/tree/fix_non_c99_errors

**Comment by markus2330** [comment]
@sanssecours Is this already fixed?

**Comment by sanssecours** [comment]
> Is this already fixed?

Not as far as I can know. I do not think we have a build job that uses `-std=c99` yet.

**Comment by markus2330** [comment]
And the -Werror?

**Comment by sanssecours** [comment]
> And the -Werror?

The only build job that does **not** use `-Werror` is `debian-oldstable-full`.

**Comment by markus2330** [comment]
I think we went already quite far with this.
