### ISSUE TITLE
ini: remove strcasecmp

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#2093]
https://github.com/ElektraInitiative/libelektra/blob/master/src/plugins/ini/ini.c#L572 replace with https://github.com/ElektraInitiative/libelektra/blob/36f2a2a0fd8b961ad5989a8a8a1fa05006a8ba2a/src/libs/elektra/internal.c#L159

**Comment by ingwinlu** [comment]
if you search for strcasecmp other offenders are visible as well.

**Comment by markus2330** [comment]
Yes, for other functions you are completely right.

But I am consider to remove elektraStrCaseCmp from the core (see doc/todo/FUTURE), the benefit of case-insensitive searches are marginal. It is more historic that we have it.

So it is okay if plugins do not use it.

**Comment by ingwinlu** [comment]
Actually a lot of plugins are not c99 conformant because they rely on strdup and similar. So if Elektra would provide an alternative implementation (if not provided by libc) they would easily be made c99.

**Comment by markus2330** [comment]
Which plugins are you referring to?

Elektra provides elektraStrDup and if we hit a system that does not have strdup we would reimplement it  (but even mingw seems to have it).

strdup and strcasecmp are, however, quite different things. strdup is about memory management, which is centralized in Elektra. Somewhere needs the line to be drawn. I do not think it is useful to wrap libc.

**Comment by ingwinlu** [comment]
> Which plugins are you referring to?

pick one from https://github.com/ElektraInitiative/libelektra/pull/2095/commits
for example glob.

> Elektra provides elektraStrDup 

then a lot of plugins do not use it

> and if we hit a system that does not have strdup we would reimplement it

That is not the current behaviour, seems to be always implemented.

> (but even mingw seems to have it).

It might not get exported as soon as you use c99 (as it is not c99 anymore).
