### ISSUE TITLE
qt-gui: whats this only works on active buttons

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#210]
Is there a special reason why "Whats this" is disabled for buttons currently not clickable?

Otherwise: great feature!

**Comment by 0003088** [comment]
This was not a conscious decision, it's  a technical limitation. The "Whats this" mode is realized with a MouseArea, these are obviously disabled when the button is not pushable.

**Comment by markus2330** [comment]
you wrote:
> This was not a conscious decision, it's  a technical limitation. The "Whats
> this" mode is realized with a MouseArea, these are obviously disabled when
> the button is not pushable.

Ok, it isn't a major thing, its quite obvious how to get the buttons pushable 
(just click on a key)
