### ISSUE TITLE
assign/condition does not create wildcard key

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2104]
## Steps to Reproduce the Problem

Given the specification (ni format):

```
[tests/test?/positiv]
assign/condition = (../points < '50') ? ('0') : ('1')
```

and the configuration (ini format):

```
[tests]
[tests/test1]
points = 100
```

then run `kdb global-mount conditionals`
and then run `kdb get /tests/test1/positiv`

## Expected Result

"1" because points is `>= 50`.

## Actual Result

`Did not find key`

Workaround: create an empty key, then it works as expected.

## System Information

- Elektra Version: master
- Operating System or Docker Container?
- Versions of other relevant software?

## Related Issues

Might be related to #1499?

**Comment by tom-wa** [comment]
the `spec` plugin checks if `tests/test?/positive` matches any key, and if not, creates a key named `tests/test?/positive` (literally "test?") in this case. 
so `assign/conditional` doesn't currently work with whitespaces.
it could be implemented, but i'm not sure how multiple not-existing levels below a wildcard key should be handled.  e.g. `tests/test?/sub/positive` - should the spec plugin stop trying if `tests/test?/sub` is not found, or remove the basename until a matching key is found ?

**Comment by markus2330** [comment]
I see. Yes, I think we can assume the basename to be present for now and fill out the wildcards as they are for the basenames. It would at least fix the problems I have.

**Comment by markus2330** [comment]
Seems like the creation of default keys is also effected by this bug.
