### ISSUE TITLE
Web UI Firefox problems

### ISSUE THREAD

**Issue by omnidan** [ElektraInitiative/libelektra#2105]
Firefox seems to have some problems when an input field is `draggable`. It is not possible to select text or click at a certain position. This does not happen with Chrome or Safari.

- [ ] not possible to click somewhere in the text (of values)
- [ ] not possible to select text (of values)

**Comment by markus2330** [comment]
Is it maybe possible to make it not draggable but have some anchor next to it? (at least for Firefox) E.g. Tuwel is implementing it that way.

**Comment by omnidan** [comment]
Unfortunately I did not find a way to do this with the current version of the tree view library. However, I created an issue on their github page: https://github.com/elbywan/bosket/issues/43
