### ISSUE TITLE
system/elektra/version|modules should have restrict/write, restrict/remove

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2109]
## Steps to Reproduce the Problem

Try to change or remove "system/elektra/version/constants/KDB_VERSION" in the Web UI.

## Expected Result

There should be no way to change or remove it (because of metadata restrict/write, restrict/remove).

## Actual Result

You get the typical errors you get in the command-line interface.

## System Information

- Elektra Version: master

## Implementation Hints

The meta data `restrict/write` and `restrict/remove` (both with value "1") need to be added using `keyCopyAllMeta` in elektraVersionGet (src/libs/elektra/plugin.c line 411) and somewhere around src/libs/elektra/backend.c line 350.

(Adding it using `src/include/kdbversion.h.in` would need more memory)

**Comment by Chemin1** [comment]
I don't really know where to look for a solution to the following problems for my first commit

1. At the moment I constantly compile and install elektra on my system to see the changes. This is quite tedious. Which is the common way to do this? Virtual machine? Execute the files in `build/bin` and perform `npm install` for `elektrad` and `client`? Something different?

2. I want to find out why I cannot add metadata in `system/elektra/version/constants/`
This 
`kdb setmeta system/elektra/version/constants/KDB_VERSION test testvalue`
`kdb getmeta system/elektra/version/constants/KDB_VERSION test`
gives me nothing while this
`kdb setmeta user/test test testvalue`
`kdb getmeta user/test test`
works. What keyword am I looking for here?

**Comment by markus2330** [comment]
Hello! Thank you for writing here.

> Which is the common way to do this? Virtual machine? Execute the files in build/bin and perform npm install for elektrad and client? Something different?

You can use "kdb" from the build directory. scripts/run_dev_env should setup all paths properly.

@omnidan How did you develop the WebUI?

> I want to find out why I cannot add metadata in `system/elektra/version`

`system/elektra/version` is generated by  src/libs/elektra/plugin.c line 411 and read-only (see line 419, there is no persistent storage behind this data).

So to fix this bug you basically only need to modify src/include/kdbversion.h.in to have the necessary meta-data so that the Web-UI knows that this is read-only.

**Comment by omnidan** [comment]
@markus2330 I compiled and installed elektra and kdb and then used `npm run start:dev` to start elektrad/webd in development mode (which automatically recompiles the app when you make changes).

**Comment by markus2330** [comment]
Thanks for the response! Sounds good.

So if you change Elektra itself, you only need to take care that the correct kdb binary is executed (the one from the build directory).

**Comment by Chemin1** [comment]
Thank you both! Especially the part with `scripts/run_dev_env` was really helpful.

> and somewhere around src/libs/elektra/backend.c line 350.
I did not change that, but it seemed to be working nonetheless.

**Comment by Chemin1** [comment]
> and somewhere around src/libs/elektra/backend.c line 350.

I wanted to ask how sure you are about that line 350. Trying to find all the necessary keys, I read a lot of source code and documentation about e.g. how plugins are loaded and how they work together with backends. Slowly I'm beginning to ask myself if I'm overlooking something or if it simply needs some more understanding of the code base.

**Comment by markus2330** [comment]
This task is actually not so easy as the one with version.

> I wanted to ask how sure you are about that line 350.

Seems like the line number changed, I marked it for you:

https://github.com/ElektraInitiative/libelektra/blob/d1d1ae5bf63b29b9cb0a96ac133156384e6f327e/src/libs/elektra/backend.c#L360

Obviously you cannot directly add the metadata there. Instead you need a proxy function, which calls "plugin" and then adds the metadata.
