### ISSUE TITLE
new memory leaks detected

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#2113]
Builds on master started to fail on unstable + valgrind combinations due to a new memory leak.

It seems to be related to the semlock plugin and the testkdb_allplugins test.

https://build.libelektra.org/jenkins/job/libelektra/job/master/138/artifact/artifacts/debian-unstable-full/DynamicAnalysis.xml

**Comment by sanssecours** [comment]
@KurtMi Can you please have a look?

This seems to be a rather strange issue, since the tests for commit 1c4a21be already [ran successfully](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/136/pipeline). I disabled the test for the `semlock` plugin in PR #2114. It would be nice if we could fix the underlying problem though.

**Comment by ingwinlu** [comment]
right. i failed to mention: the docker image changed because it was a new month and hence a fresh build was issued. Since unstable does not really 'pin' versions something probably changed upstream.

**Comment by ingwinlu** [comment]
14c14
< bash/now 4.4.18-2 amd64 [installed,local]
---
> bash/now 4.4.18-3 amd64 [installed,local]
16,18c16,18
< binutils/now 2.30-21 amd64 [installed,local]
< binutils-common/now 2.30-21 amd64 [installed,local]
< binutils-x86-64-linux-gnu/now 2.30-21 amd64 [installed,local]
---
> binutils/now 2.30.90.20180627-1 amd64 [installed,local]
> binutils-common/now 2.30.90.20180627-1 amd64 [installed,local]
> binutils-x86-64-linux-gnu/now 2.30.90.20180627-1 amd64 [installed,local]
21c21
< bsdutils/now 1:2.31.1-0.5 amd64 [installed,local]
---
> bsdutils/now 1:2.32-0.1 amd64 [installed,local]
36c36
< cpp-7/now 7.3.0-20 amd64 [installed,local]
---
> cpp-7/now 7.3.0-24 amd64 [installed,local]
39,40c39,40
< dbus/now 1.12.8-2 amd64 [installed,local]
< dbus-user-session/now 1.12.8-2 amd64 [installed,local]
---
> dbus/now 1.12.8-3 amd64 [installed,local]
> dbus-user-session/now 1.12.8-3 amd64 [installed,local]
44,45c44,45
< debconf/now 1.5.66 all [installed,local]
< debhelper/now 11.3.2 all [installed,local]
---
> debconf/now 1.5.67 all [installed,local]
> debhelper/now 11.3.5 all [installed,local]
47,48c47,48
< debianutils/now 4.8.4 amd64 [installed,local]
< default-jre-headless/now 2:1.10-66 amd64 [installed,local]
---
> debianutils/now 4.8.6 amd64 [installed,local]
> default-jre-headless/now 2:1.10-67 amd64 [installed,local]
52c52
< dh-strip-nondeterminism/now 0.041-1 all [installed,local]
---
> dh-strip-nondeterminism/now 0.042-1 all [installed,local]
54c54
< dirmngr/now 2.2.7-1 amd64 [installed,local]
---
> dirmngr/now 2.2.8-3 amd64 [installed,local]
56c56
< dpkg/now 1.19.0.5 amd64 [installed,local]
---
> dpkg/now 1.19.0.5+b1 amd64 [installed,local]
59c59
< e2fsprogs/now 1.44.1-2 amd64 [installed,local]
---
> e2fsprogs/now 1.44.2-1 amd64 [installed,local]
61,62c61,62
< fdisk/now 2.31.1-0.5 amd64 [installed,local]
< file/now 1:5.33-2 amd64 [installed,local]
---
> fdisk/now 2.32-0.1 amd64 [installed,local]
> file/now 1:5.33-3 amd64 [installed,local]
70c70
< g++-7/now 7.3.0-20 amd64 [installed,local]
---
> g++-7/now 7.3.0-24 amd64 [installed,local]
73,75c73,75
< gcc-7/now 7.3.0-20 amd64 [installed,local]
< gcc-7-base/now 7.3.0-20 amd64 [installed,local]
< gcc-8-base/now 8.1.0-4 amd64 [installed,local]
---
> gcc-7/now 7.3.0-24 amd64 [installed,local]
> gcc-7-base/now 7.3.0-24 amd64 [installed,local]
> gcc-8-base/now 8.1.0-9 amd64 [installed,local]
79c79
< ghc/now 8.2.2-3+b1 amd64 [installed,local]
---
> ghc/now 8.2.2-4 amd64 [installed,local]
82,84c82,84
< gir1.2-harfbuzz-0.0/now 1.7.6-1+b1 amd64 [installed,local]
< git/now 1:2.17.1-1 amd64 [installed,local]
< git-man/now 1:2.17.1-1 all [installed,local]
---
> gir1.2-harfbuzz-0.0/now 1.8.1-1 amd64 [installed,local]
> git/now 1:2.18.0-1 amd64 [installed,local]
> git-man/now 1:2.18.0-1 all [installed,local]
88,90c88,90
< gnupg/now 2.2.7-1 amd64 [installed,local]
< gnupg-l10n/now 2.2.7-1 all [installed,local]
< gnupg-utils/now 2.2.7-1 amd64 [installed,local]
---
> gnupg/now 2.2.8-3 all [installed,local]
> gnupg-l10n/now 2.2.8-3 all [installed,local]
> gnupg-utils/now 2.2.8-3 amd64 [installed,local]
92,98c92,98
< gpg/now 2.2.7-1 amd64 [installed,local]
< gpg-agent/now 2.2.7-1 amd64 [installed,local]
< gpg-wks-client/now 2.2.7-1 amd64 [installed,local]
< gpg-wks-server/now 2.2.7-1 amd64 [installed,local]
< gpgconf/now 2.2.7-1 amd64 [installed,local]
< gpgsm/now 2.2.7-1 amd64 [installed,local]
< gpgv/now 2.2.7-1 amd64 [installed,local]
---
> gpg/now 2.2.8-3 amd64 [installed,local]
> gpg-agent/now 2.2.8-3 amd64 [installed,local]
> gpg-wks-client/now 2.2.8-3 amd64 [installed,local]
> gpg-wks-server/now 2.2.8-3 amd64 [installed,local]
> gpgconf/now 2.2.8-3 amd64 [installed,local]
> gpgsm/now 2.2.8-3 amd64 [installed,local]
> gpgv/now 2.2.8-3 amd64 [installed,local]
102c102
< gtk-update-icon-cache/now 3.22.30-1 amd64 [installed,local]
---
> gtk-update-icon-cache/now 3.22.30-2 amd64 [installed,local]
107c107
< ibverbs-providers/now 18.0-1 amd64 [installed,local]
---
> ibverbs-providers/now 19.0-1 amd64 [installed,local]
112c112
< iproute2/now 4.15.0-3 amd64 [installed,local]
---
> iproute2/now 4.16.0-4 amd64 [installed,local]
114c114
< java-common/now 0.66 all [installed,local]
---
> java-common/now 0.67 all [installed,local]
119,120c119,120
< lib32gcc1/now 1:8.1.0-4 amd64 [installed,local]
< lib32stdc++6/now 8.1.0-4 amd64 [installed,local]
---
> lib32gcc1/now 1:8.1.0-9 amd64 [installed,local]
> lib32stdc++6/now 8.1.0-9 amd64 [installed,local]
127c127
< libapparmor1/now 2.12-4 amd64 [installed,local]
---
> libapparmor1/now 2.12-4+b1 amd64 [installed,local]
132,133c132,134
< libargon2-0/now 0~20161029-2 amd64 [installed,local]
< libasan4/now 7.3.0-20 amd64 [installed,local]
---
> libargon2-0/now 0~20171227-0.1 amd64 [installed,local]
> libargon2-1/now 0~20171227-0.1 amd64 [installed,local]
> libasan4/now 7.3.0-24 amd64 [installed,local]
144c145
< libatomic1/now 8.1.0-4 amd64 [installed,local]
---
> libatomic1/now 8.1.0-9 amd64 [installed,local]
147,148c148,149
< libaudit-common/now 1:2.8.2-1 all [installed,local]
< libaudit1/now 1:2.8.2-1 amd64 [installed,local]
---
> libaudit-common/now 1:2.8.3-1 all [installed,local]
> libaudit1/now 1:2.8.3-1 amd64 [installed,local]
154,155c155,156
< libbabeltrace1/now 1.5.5-1 amd64 [installed,local]
< libbinutils/now 2.30-21 amd64 [installed,local]
---
> libbabeltrace1/now 1.5.5-1+b1 amd64 [installed,local]
> libbinutils/now 2.30.90.20180627-1 amd64 [installed,local]
157c158
< libblkid1/now 2.31.1-0.5 amd64 [installed,local]
---
> libblkid1/now 2.32-0.1 amd64 [installed,local]
262c263,264
< libcc1-0/now 8.1.0-4 amd64 [installed,local]
---
> libcap2-bin/now 1:2.25-1.2 amd64 [installed,local]
> libcc1-0/now 8.1.0-9 amd64 [installed,local]
264c266
< libcilkrts5/now 7.3.0-20 amd64 [installed,local]
---
> libcilkrts5/now 7.3.0-24 amd64 [installed,local]
268c270
< libcom-err2/now 1.44.1-2 amd64 [installed,local]
---
> libcom-err2/now 1.44.2-1 amd64 [installed,local]
274,275c276,277
< libcryptsetup12/now 2:2.0.2-1 amd64 [installed,local]
< libcups2/now 2.2.7-5 amd64 [installed,local]
---
> libcryptsetup12/now 2:2.0.3-4 amd64 [installed,local]
> libcups2/now 2.2.8-3 amd64 [installed,local]
279c281
< libdatrie1/now 0.2.11-1 amd64 [installed,local]
---
> libdatrie1/now 0.2.12-1 amd64 [installed,local]
281,282c283,284
< libdbus-1-3/now 1.12.8-2 amd64 [installed,local]
< libdbus-1-dev/now 1.12.8-2 amd64 [installed,local]
---
> libdbus-1-3/now 1.12.8-3 amd64 [installed,local]
> libdbus-1-dev/now 1.12.8-3 amd64 [installed,local]
293c295
< libdw1/now 0.170-0.4 amd64 [installed,local]
---
> libdw1/now 0.170-0.5 amd64 [installed,local]
295,297c297
< libegl-mesa0/now 18.0.4-1 amd64 [installed,local]
< libegl1/now 1.0.0+git20180308-3 amd64 [installed,local]
< libelf1/now 0.170-0.4 amd64 [installed,local]
---
> libelf1/now 0.170-0.5 amd64 [installed,local]
299c299
< liberror-perl/now 0.17025-1 all [installed,local]
---
> liberror-perl/now 0.17026-1 all [installed,local]
305,306c305,306
< libext2fs2/now 1.44.1-2 amd64 [installed,local]
< libfabric1/now 1.5.3-1 amd64 [installed,local]
---
> libext2fs2/now 1.44.2-1 amd64 [installed,local]
> libfabric1/now 1.6.1-5 amd64 [installed,local]
308c308
< libfdisk1/now 2.31.1-0.5 amd64 [installed,local]
---
> libfdisk1/now 2.32-0.1 amd64 [installed,local]
313c313
< libfile-stripnondeterminism-perl/now 0.041-1 all [installed,local]
---
> libfile-stripnondeterminism-perl/now 0.042-1 all [installed,local]
318,321c318,320
< libfribidi0/now 0.19.7-2 amd64 [installed,local]
< libgail-common/now 2.24.32-1 amd64 [installed,local]
< libgail18/now 2.24.32-1 amd64 [installed,local]
< libgbm1/now 18.0.4-1 amd64 [installed,local]
---
> libfribidi0/now 0.19.7-3 amd64 [installed,local]
> libgail-common/now 2.24.32-2 amd64 [installed,local]
> libgail18/now 2.24.32-2 amd64 [installed,local]
323,326c322,325
< libgcc-7-dev/now 7.3.0-20 amd64 [installed,local]
< libgcc1/now 1:8.1.0-4 amd64 [installed,local]
< libgcrypt20/now 1.8.2-2 amd64 [installed,local]
< libgcrypt20-dev/now 1.8.2-2 amd64 [installed,local]
---
> libgcc-7-dev/now 7.3.0-24 amd64 [installed,local]
> libgcc1/now 1:8.1.0-9 amd64 [installed,local]
> libgcrypt20/now 1.8.3-1 amd64 [installed,local]
> libgcrypt20-dev/now 1.8.3-1 amd64 [installed,local]
336,337c335,336
< libgfortran4/now 7.3.0-20 amd64 [installed,local]
< libgif7/now 5.1.4-2 amd64 [installed,local]
---
> libgfortran4/now 7.3.0-24 amd64 [installed,local]
> libgif7/now 5.1.4-3 amd64 [installed,local]
343,345c342,344
< libgl1-mesa-dri/now 18.0.4-1 amd64 [installed,local]
< libgl1-mesa-glx/now 18.0.4-1 amd64 [installed,local]
< libglapi-mesa/now 18.0.4-1 amd64 [installed,local]
---
> libgl1-mesa-dri/now 18.1.2-1 amd64 [installed,local]
> libgl1-mesa-glx/now 18.1.2-1 amd64 [installed,local]
> libglapi-mesa/now 18.1.2-1 amd64 [installed,local]
352c351
< libglx-mesa0/now 18.0.4-1 amd64 [installed,local]
---
> libglx-mesa0/now 18.1.2-1 amd64 [installed,local]
359c358
< libgomp1/now 8.1.0-4 amd64 [installed,local]
---
> libgomp1/now 8.1.0-9 amd64 [installed,local]
366,371c365,370
< libgtk-3-0/now 3.22.30-1 amd64 [installed,local]
< libgtk-3-bin/now 3.22.30-1 amd64 [installed,local]
< libgtk-3-common/now 3.22.30-1 all [installed,local]
< libgtk2.0-0/now 2.24.32-1 amd64 [installed,local]
< libgtk2.0-bin/now 2.24.32-1 amd64 [installed,local]
< libgtk2.0-common/now 2.24.32-1 all [installed,local]
---
> libgtk-3-0/now 3.22.30-2 amd64 [installed,local]
> libgtk-3-bin/now 3.22.30-2 amd64 [installed,local]
> libgtk-3-common/now 3.22.30-2 all [installed,local]
> libgtk2.0-0/now 2.24.32-2 amd64 [installed,local]
> libgtk2.0-bin/now 2.24.32-2 amd64 [installed,local]
> libgtk2.0-common/now 2.24.32-2 all [installed,local]
374,377c373,376
< libharfbuzz-dev/now 1.7.6-1+b1 amd64 [installed,local]
< libharfbuzz-gobject0/now 1.7.6-1+b1 amd64 [installed,local]
< libharfbuzz-icu0/now 1.7.6-1+b1 amd64 [installed,local]
< libharfbuzz0b/now 1.7.6-1+b1 amd64 [installed,local]
---
> libharfbuzz-dev/now 1.8.1-1 amd64 [installed,local]
> libharfbuzz-gobject0/now 1.8.1-1 amd64 [installed,local]
> libharfbuzz-icu0/now 1.8.1-1 amd64 [installed,local]
> libharfbuzz0b/now 1.8.1-1 amd64 [installed,local]
382,386c381,385
< libhwloc-dev/now 1.11.10-1+b1 amd64 [installed,local]
< libhwloc-plugins/now 1.11.10-1+b1 amd64 [installed,local]
< libhwloc5/now 1.11.10-1+b1 amd64 [installed,local]
< libibverbs-dev/now 18.0-1 amd64 [installed,local]
< libibverbs1/now 18.0-1 amd64 [installed,local]
---
> libhwloc-dev/now 1.11.10-2 amd64 [installed,local]
> libhwloc-plugins/now 1.11.10-2 amd64 [installed,local]
> libhwloc5/now 1.11.10-2 amd64 [installed,local]
> libibverbs-dev/now 19.0-1 amd64 [installed,local]
> libibverbs1/now 19.0-1 amd64 [installed,local]
399c398
< libitm1/now 8.1.0-4 amd64 [installed,local]
---
> libitm1/now 8.1.0-9 amd64 [installed,local]
405c404
< libjs-sphinxdoc/now 1.7.4-1 all [installed,local]
---
> libjs-sphinxdoc/now 1.7.5-3 all [installed,local]
418c417
< liblcms2-2/now 2.9-1 amd64 [installed,local]
---
> liblcms2-2/now 2.9-2 amd64 [installed,local]
423c422
< libllvm6.0/now 1:6.0-3+b1 amd64 [installed,local]
---
> libllvm6.0/now 1:6.0.1-2 amd64 [installed,local]
425c424
< liblsan0/now 8.1.0-4 amd64 [installed,local]
---
> liblsan0/now 8.1.0-9 amd64 [installed,local]
434c433
< liblz4-1/now 1.8.1.2-1 amd64 [installed,local]
---
> liblz4-1/now 1.8.2-1 amd64 [installed,local]
437,438c436,437
< libmagic-mgc/now 1:5.33-2 amd64 [installed,local]
< libmagic1/now 1:5.33-2 amd64 [installed,local]
---
> libmagic-mgc/now 1:5.33-3 amd64 [installed,local]
> libmagic1/now 1:5.33-3 amd64 [installed,local]
440,443c439,442
< libmaven-parent-java/now 27-2 all [installed,local]
< libmaven-resolver-java/now 1.1.0-3 all [installed,local]
< libmaven-shared-utils-java/now 3.1.0-2 all [installed,local]
< libmaven3-core-java/now 3.5.2-2 all [installed,local]
---
> libmaven-parent-java/now 31-2 all [installed,local]
> libmaven-resolver-java/now 1.1.1-1 all [installed,local]
> libmaven-shared-utils-java/now 3.2.1-1 all [installed,local]
> libmaven3-core-java/now 3.5.3-1 all [installed,local]
445c444
< libmount1/now 2.31.1-0.5 amd64 [installed,local]
---
> libmount1/now 2.32-0.1 amd64 [installed,local]
449c448
< libmpx2/now 8.1.0-4 amd64 [installed,local]
---
> libmpx2/now 8.1.0-9 amd64 [installed,local]
453d451
< libncursesw5/now 6.1-1 amd64 [installed,local]
459c457
< libnpth0/now 1.5-3 amd64 [installed,local]
---
> libnpth0/now 1.5-4 amd64 [installed,local]
461,462c459,460
< libnss-systemd/now 238-5 amd64 [installed,local]
< libnss3/now 2:3.37.1-1 amd64 [installed,local]
---
> libnss-systemd/now 239-3 amd64 [installed,local]
> libnss3/now 2:3.38-1 amd64 [installed,local]
466,467c464,465
< libobjc-7-dev/now 7.3.0-20 amd64 [installed,local]
< libobjc4/now 8.1.0-4 amd64 [installed,local]
---
> libobjc-7-dev/now 7.3.0-24 amd64 [installed,local]
> libobjc4/now 8.1.0-9 amd64 [installed,local]
471,473c469,471
< libopenmpi-dev/now 3.1.0-6 amd64 [installed,local]
< libopenmpi3/now 3.1.0-6 amd64 [installed,local]
< libp11-kit0/now 0.23.10-2 amd64 [installed,local]
---
> libopenmpi-dev/now 3.1.0-8 amd64 [installed,local]
> libopenmpi3/now 3.1.0-8 amd64 [installed,local]
> libp11-kit0/now 0.23.12-2 amd64 [installed,local]
477c475
< libpam-systemd/now 238-5 amd64 [installed,local]
---
> libpam-systemd/now 239-3 amd64 [installed,local]
479,481c477,479
< libpango-1.0-0/now 1.42.1-1 amd64 [installed,local]
< libpangocairo-1.0-0/now 1.42.1-1 amd64 [installed,local]
< libpangoft2-1.0-0/now 1.42.1-1 amd64 [installed,local]
---
> libpango-1.0-0/now 1.42.1-2 amd64 [installed,local]
> libpangocairo-1.0-0/now 1.42.1-2 amd64 [installed,local]
> libpangoft2-1.0-0/now 1.42.1-2 amd64 [installed,local]
492c490
< libperl5.26/now 5.26.2-5 amd64 [installed,local]
---
> libperl5.26/now 5.26.2-6 amd64 [installed,local]
504c502
< libprocps7/now 2:3.3.15-1 amd64 [installed,local]
---
> libprocps7/now 2:3.3.15-2 amd64 [installed,local]
506c504
< libpsl5/now 0.20.1-1 amd64 [installed,local]
---
> libpsl5/now 0.20.2-1 amd64 [installed,local]
507a506
> libpsm2-2/now 10.3.58-1 amd64 [installed,local]
509,512c508,513
< libpulse0/now 11.1-5 amd64 [installed,local]
< libpython-all-dev/now 2.7.15~rc1-1 amd64 [installed,local]
< libpython-dev/now 2.7.15~rc1-1 amd64 [installed,local]
< libpython-stdlib/now 2.7.15~rc1-1 amd64 [installed,local]
---
> libpulse0/now 12.0-1 amd64 [installed,local]
> libpython-all-dev/now 2.7.15-3 amd64 [installed,local]
> libpython-dev/now 2.7.15-3 amd64 [installed,local]
> libpython-stdlib/now 2.7.15-3 amd64 [installed,local]
> libpython2-dev/now 2.7.15-3 amd64 [installed,local]
> libpython2-stdlib/now 2.7.15-3 amd64 [installed,local]
517,524c518,525
< libpython3-dev/now 3.6.5-3 amd64 [installed,local]
< libpython3-stdlib/now 3.6.5-3 amd64 [installed,local]
< libpython3.6/now 3.6.5-9 amd64 [installed,local]
< libpython3.6-dev/now 3.6.5-9 amd64 [installed,local]
< libpython3.6-minimal/now 3.6.5-9 amd64 [installed,local]
< libpython3.6-stdlib/now 3.6.5-9 amd64 [installed,local]
< libquadmath0/now 8.1.0-4 amd64 [installed,local]
< librdmacm1/now 18.0-1 amd64 [installed,local]
---
> libpython3-dev/now 3.6.6-1 amd64 [installed,local]
> libpython3-stdlib/now 3.6.6-1 amd64 [installed,local]
> libpython3.6/now 3.6.6-1 amd64 [installed,local]
> libpython3.6-dev/now 3.6.6-1 amd64 [installed,local]
> libpython3.6-minimal/now 3.6.6-1 amd64 [installed,local]
> libpython3.6-stdlib/now 3.6.6-1 amd64 [installed,local]
> libquadmath0/now 8.1.0-9 amd64 [installed,local]
> librdmacm1/now 19.0-1 amd64 [installed,local]
532c533
< libruby2.5/now 2.5.1-1+b1 amd64 [installed,local]
---
> libruby2.5/now 2.5.1-3 amd64 [installed,local]
536,540c537,541
< libseccomp2/now 2.3.3-1 amd64 [installed,local]
< libselinux1/now 2.8-1 amd64 [installed,local]
< libselinux1-dev/now 2.8-1 amd64 [installed,local]
< libsemanage-common/now 2.7-2 all [installed,local]
< libsemanage1/now 2.7-2+b2 amd64 [installed,local]
---
> libseccomp2/now 2.3.3-2 amd64 [installed,local]
> libselinux1/now 2.8-1+b1 amd64 [installed,local]
> libselinux1-dev/now 2.8-1+b1 amd64 [installed,local]
> libsemanage-common/now 2.8-1 all [installed,local]
> libsemanage1/now 2.8-1 amd64 [installed,local]
550c551
< libsmartcols1/now 2.31.1-0.5 amd64 [installed,local]
---
> libsmartcols1/now 2.32-0.1 amd64 [installed,local]
552,555c553,556
< libsoup-gnome2.4-1/now 2.62.2-1 amd64 [installed,local]
< libsoup2.4-1/now 2.62.2-1 amd64 [installed,local]
< libsqlite3-0/now 3.23.1-1 amd64 [installed,local]
< libss2/now 1.44.1-2 amd64 [installed,local]
---
> libsoup-gnome2.4-1/now 2.62.2-2 amd64 [installed,local]
> libsoup2.4-1/now 2.62.2-2 amd64 [installed,local]
> libsqlite3-0/now 3.24.0-1 amd64 [installed,local]
> libss2/now 1.44.2-1 amd64 [installed,local]
561,562c562,563
< libstdc++-7-dev/now 7.3.0-20 amd64 [installed,local]
< libstdc++6/now 8.1.0-4 amd64 [installed,local]
---
> libstdc++-7-dev/now 7.3.0-24 amd64 [installed,local]
> libstdc++6/now 8.1.0-9 amd64 [installed,local]
564,566c565,567
< libsystemd-dev/now 238-5 amd64 [installed,local]
< libsystemd0/now 238-5 amd64 [installed,local]
< libtasn1-6/now 4.13-2 amd64 [installed,local]
---
> libsystemd-dev/now 239-3 amd64 [installed,local]
> libsystemd0/now 239-3 amd64 [installed,local]
> libtasn1-6/now 4.13-3 amd64 [installed,local]
575d575
< libtinfo5/now 6.1-1 amd64 [installed,local]
579,581c579,581
< libtsan0/now 8.1.0-4 amd64 [installed,local]
< libubsan0/now 7.3.0-20 amd64 [installed,local]
< libudev1/now 238-4 amd64 [installed,local]
---
> libtsan0/now 8.1.0-9 amd64 [installed,local]
> libubsan0/now 7.3.0-24 amd64 [installed,local]
> libudev1/now 239-1 amd64 [installed,local]
583,585c583,585
< libuuid1/now 2.31.1-0.5 amd64 [installed,local]
< libuv1/now 1.20.3-1 amd64 [installed,local]
< libuv1-dev/now 1.20.3-1 amd64 [installed,local]
---
> libuuid1/now 2.32-0.1 amd64 [installed,local]
> libuv1/now 1.20.3-2 amd64 [installed,local]
> libuv1-dev/now 1.20.3-2 amd64 [installed,local]
594,595d593
< libwayland-egl1-mesa/now 18.0.4-1 amd64 [installed,local]
< libwayland-server0/now 1.15.0-2 amd64 [installed,local]
629,631c627,629
< libxkbcommon0/now 0.8.0-1 amd64 [installed,local]
< libxml2/now 2.9.4+dfsg1-7 amd64 [installed,local]
< libxml2-dev/now 2.9.4+dfsg1-7 amd64 [installed,local]
---
> libxkbcommon0/now 0.8.0-2 amd64 [installed,local]
> libxml2/now 2.9.4+dfsg1-7+b1 amd64 [installed,local]
> libxml2-dev/now 2.9.4+dfsg1-7+b1 amd64 [installed,local]
646c644
< libyaml-0-2/now 0.1.7-2 amd64 [installed,local]
---
> libyaml-0-2/now 0.2.1-1 amd64 [installed,local]
649,650c647,648
< libzstd1/now 1.3.3+dfsg-2 amd64 [installed,local]
< linux-libc-dev/now 4.16.12-1 amd64 [installed,local]
---
> libzstd1/now 1.3.4+dfsg-3 amd64 [installed,local]
> linux-libc-dev/now 4.16.16-2 amd64 [installed,local]
669c667
< maven/now 3.5.2-2 all [installed,local]
---
> maven/now 3.5.3-1 all [installed,local]
671c669
< mime-support/now 3.60 all [installed,local]
---
> mime-support/now 3.61 all [installed,local]
673c671
< mount/now 2.31.1-0.5 amd64 [installed,local]
---
> mount/now 2.32-0.1 amd64 [installed,local]
676,677c674,675
< ncurses-base/now 6.1-1 all [installed,local]
< ncurses-bin/now 6.1-1 amd64 [installed,local]
---
> ncurses-base/now 6.1+20180210-4 all [installed,local]
> ncurses-bin/now 6.1+20180210-4 amd64 [installed,local]
685,686c683,684
< openmpi-bin/now 3.1.0-6 amd64 [installed,local]
< openmpi-common/now 3.1.0-6 all [installed,local]
---
> openmpi-bin/now 3.1.0-8 amd64 [installed,local]
> openmpi-common/now 3.1.0-8 all [installed,local]
691,693c689,691
< perl/now 5.26.2-5 amd64 [installed,local]
< perl-base/now 5.26.2-5 amd64 [installed,local]
< perl-modules-5.26/now 5.26.2-5 all [installed,local]
---
> perl/now 5.26.2-6 amd64 [installed,local]
> perl-base/now 5.26.2-6 amd64 [installed,local]
> perl-modules-5.26/now 5.26.2-6 all [installed,local]
697c695
< procps/now 2:3.3.15-1 amd64 [installed,local]
---
> procps/now 2:3.3.15-2 amd64 [installed,local]
699,702c697,700
< publicsuffix/now 20180328.1055-1 all [installed,local]
< python/now 2.7.15~rc1-1 amd64 [installed,local]
< python-all/now 2.7.15~rc1-1 amd64 [installed,local]
< python-all-dev/now 2.7.15~rc1-1 amd64 [installed,local]
---
> publicsuffix/now 20180523.2326-2 all [installed,local]
> python/now 2.7.15-3 amd64 [installed,local]
> python-all/now 2.7.15-3 amd64 [installed,local]
> python-all-dev/now 2.7.15-3 amd64 [installed,local]
704c702
< python-cffi-backend/now 1.11.5-1 amd64 [installed,local]
---
> python-cffi-backend/now 1.11.5-1+b1 amd64 [installed,local]
706,709c704,707
< python-crypto/now 2.6.1-9 amd64 [installed,local]
< python-cryptography/now 2.1.4-1 amd64 [installed,local]
< python-dbus/now 1.2.8-2 amd64 [installed,local]
< python-dev/now 2.7.15~rc1-1 amd64 [installed,local]
---
> python-crypto/now 2.6.1-9+b1 amd64 [installed,local]
> python-cryptography/now 2.2.2-1 amd64 [installed,local]
> python-dbus/now 1.2.8-2+b1 amd64 [installed,local]
> python-dev/now 2.7.15-3 amd64 [installed,local]
712c710
< python-gi/now 3.28.2-1 amd64 [installed,local]
---
> python-gi/now 3.28.2-1+b1 amd64 [installed,local]
715c713
< python-keyring/now 12.2.1-1 all [installed,local]
---
> python-keyring/now 13.1.0-1 all [installed,local]
717c715
< python-minimal/now 2.7.15~rc1-1 amd64 [installed,local]
---
> python-minimal/now 2.7.15-3 amd64 [installed,local]
720c718
< python-pkg-resources/now 39.1.0-1 all [installed,local]
---
> python-pkg-resources/now 39.2.0-1 all [installed,local]
722c720
< python-setuptools/now 39.1.0-1 all [installed,local]
---
> python-setuptools/now 39.2.0-1 all [installed,local]
725a724,726
> python2/now 2.7.15-3 amd64 [installed,local]
> python2-dev/now 2.7.15-3 amd64 [installed,local]
> python2-minimal/now 2.7.15-3 amd64 [installed,local]
729,732c730,733
< python3/now 3.6.5-3 amd64 [installed,local]
< python3-dev/now 3.6.5-3 amd64 [installed,local]
< python3-distutils/now 3.6.5-3 all [installed,local]
< python3-lib2to3/now 3.6.5-3 all [installed,local]
---
> python3/now 3.6.6-1 amd64 [installed,local]
> python3-dev/now 3.6.6-1 amd64 [installed,local]
> python3-distutils/now 3.6.6-1 all [installed,local]
> python3-lib2to3/now 3.6.6-1 all [installed,local]
734,738c735,739
< python3-markupsafe/now 1.0-1+b1 amd64 [installed,local]
< python3-minimal/now 3.6.5-3 amd64 [installed,local]
< python3.6/now 3.6.5-9 amd64 [installed,local]
< python3.6-dev/now 3.6.5-9 amd64 [installed,local]
< python3.6-minimal/now 3.6.5-9 amd64 [installed,local]
---
> python3-markupsafe/now 1.0-1+b2 amd64 [installed,local]
> python3-minimal/now 3.6.6-1 amd64 [installed,local]
> python3.6/now 3.6.6-1 amd64 [installed,local]
> python3.6-dev/now 3.6.6-1 amd64 [installed,local]
> python3.6-minimal/now 3.6.6-1 amd64 [installed,local]
748,750c749,752
< ruby2.5/now 2.5.1-1+b1 amd64 [installed,local]
< ruby2.5-dev/now 2.5.1-1+b1 amd64 [installed,local]
< ruby2.5-doc/now 2.5.1-1 all [installed,local]
---
> ruby-xmlrpc/now 0.3.0-1 all [installed,local]
> ruby2.5/now 2.5.1-3 amd64 [installed,local]
> ruby2.5-dev/now 2.5.1-3 amd64 [installed,local]
> ruby2.5-doc/now 2.5.1-3 all [installed,local]
756,758c758,760
< swig3.0/now 3.0.12-1 amd64 [installed,local]
< systemd/now 238-5 amd64 [installed,local]
< systemd-sysv/now 238-5 amd64 [installed,local]
---
> swig3.0/now 3.0.12-1.1 amd64 [installed,local]
> systemd/now 239-3 amd64 [installed,local]
> systemd-sysv/now 239-3 amd64 [installed,local]
760c762
< tar/now 1.29b-2 amd64 [installed,local]
---
> tar/now 1.30+dfsg-2 amd64 [installed,local]
762c764
< tzdata/now 2018d-1 all [installed,local]
---
> tzdata/now 2018e-1 all [installed,local]
765c767
< util-linux/now 2.31.1-0.5 amd64 [installed,local]
---
> util-linux/now 2.32-0.1 amd64 [installed,local]

**Comment by KurtMi** [comment]
> @KurtMi Can you please have a look?

The semlock tests should be disabled, why are they enabled?
I added a line in [TESTING](https://github.com/ElektraInitiative/libelektra/blob/master/doc/todo/TESTING) (line 9), because the semlock caused problems #1260.

**Comment by sanssecours** [comment]
> The semlock tests should be disabled, why are they enabled?

The plugin test (`testmod_semlock`) is already disabled. However, the memory leak is caused by [`testkdb_allplugins`](https://github.com/ElektraInitiative/libelektra/blob/master/tests/kdb/testkdb_allplugins.cpp), which tests every plugin that is [not explicitly excluded](https://github.com/ElektraInitiative/libelektra/blob/master/tests/kdb/testkdb_allplugins.cpp#L32-L38). I excluded the test for the `semlock` plugin in commit b13d34a9. Do you think that is the proper solution for the problem, or should we investigate further?

**Comment by KurtMi** [comment]
> Do you think that is the proper solution for the problem, or should we investigate further?

I think for now it is ok. In my opinion the problem is not semlock, it is the test suite that has no uniform way to exclude stuff.

**Comment by ingwinlu** [comment]
closed via #2117
