### ISSUE TITLE
ASAN: Some Tests Fail on macOS with Enabled Leak Detection

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2118]
# Steps to Reproduce the Problem

Enter the commands below at the root directory of the repository.

```sh
brew install llvm
export CC=/usr/local/opt/llvm/bin/clang
export CXX=/usr/local/opt/llvm/bin/clang++
export ASAN_OPTIONS=detect_leaks=1
export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig

mkdir build
cd build
cmake .. -GNinja -DENABLE_ASAN=ON -DBUILD_TESTING=ON -DTOOLS='kdb' -DBINDINGS='cpp' -DPLUGINS='ALL'
ninja
ninja test
```

# Expected Result

All tests finish successfully.

# Actual Result

The following tests fail:

 - `testtool_backendbuilder`
 - `testtool_plugindatabase`
 - `testmod_augeas`
 - `testmod_dbus`
 - `testmod_type`
 - `testscr_check_kdb_internal_check`
 - `testkdb_allplugins`

.

# System Information

- Elektra Version: master
- Operating System: macOS 10.13.6

# Further Log Files and Output

Travis: [Build with Enabled Leak Detection](https://travis-ci.org/sanssecours/elektra/jobs/407094416)
Log Files:
- [`testkdb_allplugins.log.txt`](https://github.com/ElektraInitiative/libelektra/files/2219402/testkdb_allplugins.log.txt)
- [`testmod_augeas.log.txt`](https://github.com/ElektraInitiative/libelektra/files/2219403/testmod_augeas.log.txt)
- [`testmod_dbus.log.txt`](https://github.com/ElektraInitiative/libelektra/files/2219404/testmod_dbus.log.txt)
- [`testmod_type.log.txt`](https://github.com/ElektraInitiative/libelektra/files/2219405/testmod_type.log.txt)
- [`testscr_check_kdb_internal_check.log.txt`](https://github.com/ElektraInitiative/libelektra/files/2219406/testscr_check_kdb_internal_check.log.txt)
- [`testtool_backendbuilder.log.txt`](https://github.com/ElektraInitiative/libelektra/files/2219407/testtool_backendbuilder.log.txt)
- [`testtool_plugindatabase.log.txt`](https://github.com/ElektraInitiative/libelektra/files/2219408/testtool_plugindatabase.log.txt)

**Comment by markus2330** [comment]
Thank you for reporting this problem! What did change so that these errors occurred? Or were they always present and simply never reported before?

**Comment by sanssecours** [comment]
> What did change so that these errors occurred?

The environment variable `ASAN_OPTIONS`.

> Or were they always present and simply never reported before?

The tests failed before too. I was just to lazy to report the issue. Since the build system now excludes all problematic tests on Linux, I thought it would make sense to do the same on macOS.

**Comment by markus2330** [comment]
Yes, it makes sense to automatically exclude tests that cannot work because of the platform/compiler/...

Let us discuss this tomorrow.

**Comment by markus2330** [comment]
Is now augeas the only test case that fails or do still all of them fail?

**Comment by sanssecours** [comment]
All of them fail. The tests `testscr_check_kdb_internal_check`, `testkdb_allplugins`, and `testtool_plugindatabase` do fail because of the `augeas` plugin though.

**Comment by sanssecours** [comment]
The reason why `testmod_dbus` failed on my machine was that I did not start `dbus` beforehand:

```sh
brew services start dbus
```

. I still think it would make sense to handle this situation more gracefully, if it does not require that much work.

**Comment by markus2330** [comment]
@waht Can you maybe take a look at the dbus issue?

**Comment by waht** [comment]
I'm on it. IMHO testmod_dbus is handling the unavailable dbus daemon rather gracefully (i.e. the test prints a warning and returns 0 errors) but dbus is producing a memory leak at least on macOS.
On Linux (stretch container) there is no leak without a dbus daemon.
API use seems fine (i.e. the error is freed before return) but I'll check if a call to `dbus_shutdown()` will fix this.

**Comment by waht** [comment]
It seems like `dbus_shutdown()` does the job: [https://travis-ci.org/waht/libelektra/jobs/418867511#L5133](Travis Build Log).
@sanssecours Do you want add the  [https://github.com/waht/libelektra/commit/d1a1cc1dbcf9cbe709c456632ee5e1299d2964bd](quite trivial fix) to a PR of yours of should I create one?

**Comment by sanssecours** [comment]
> @sanssecours Do you want add the quite trivial fix to a PR of yours of should I create one?

Thanks for taking care of the problem. I cherry-picked your commit in PR #2201.
