### ISSUE TITLE
cmake output: cannot access .cabal

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2139]
## Steps to Reproduce the Problem

```sh
docker build -t buildelektra-stretch-full --build-arg JENKINS_USERID=`id -u` --build-arg JENKINS_GROUPID=`id -g` -f scripts/docker/debian/stretch/Dockerfile scripts/docker/debian/stretch/ 

docker run -it --rm -v `pwd`:/home/jenkins/workspace -w /home/jenkins/workspace buildelektra-stretch-full

mkdir build && cd build

cmake -DSITE=debian-stable-full -DKDB_DB_SYSTEM=`pwd`/config/kdb/system -DKDB_DB_SPEC=`pwd`/config/kdb/spec -DKDB_DB_HOME=`pwd`/config/kdb/home -DCMAKE_INSTALL_PREFIX=`pwd`/system -DINSTALL_SYSTEM_FILES=OFF -DBUILD_DOCUMENTATION=OFF -DBINDINGS="ALL;-DEPRECATED" -DPLUGINS="ALL;-DEPRECATED" -DTOOLS=ALL -DBUILD_FULL=ON -DBUILD_STATIC=ON -DENABLE_COVERAGE=ON ..
```

## Expected Result

Run without warnings.

## Actual Result

```
ls: cannot access '/home/jenkins/.cabal/lib': No such file or directory
```

gets printed several times (~6x).

## System Information

- Elektra Version: master

**Comment by e1528532** [comment]
Yes i've seen this as well but wasn't really able to resolve yet. I think it gets outputted internally by cabal somewhere, so i fear there is not much i can do about it. A workaround could be creating that directory? ;)

Assigning low priority as it doesn't threat the build as far as i've experienced.

**Comment by markus2330** [comment]
Yes, creating the directory seems like a valid solution. Can you please do that for our build server in scripts/jenkins/Jenkinsfile
