### ISSUE TITLE
pluginprocess: transfer of parentKey

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2142]
It seems like some arguments are not transfered correctly.

@e1528532 Do you have time for a quick fix? It would be highly appreciated. It should be quite easy to fix and if the problem is like I think it is you will also trap into it with your plugins. It might, however, only a misuse in #2135.

## Steps to Reproduce the Problem

Debug python plugin of PR #2135 and print the name of parentKey.

## Expected Result

That parentKey is fully transmitted to the other process.

## Actual Result

parentKey is missing its name.

## System Information

- Elektra Version: master or PR #2135 to reproduce

## Further Info

Shortly looking at src/libs/pluginprocess/pluginprocess.c line 199 there seems to be the assumption that no key with the name of the parentKey exists in the originalKeySet. This assumption is not valid, it is easily possible that the key also exists in the keyset. /pluginprocess/original only transfers the name, but not the other information of the parentKey.

**Comment by markus2330** [comment]
@e1528532 Do you have time to look at it? A (partial?) fix is done in the python PR #2135

**Comment by e1528532** [comment]
fixed in #2149
