### ISSUE TITLE
Document Possible Exceptions ThreeWayMerge

### ISSUE THREAD

**Issue by 0003088** [ElektraInitiative/libelektra#215]
When executing merger.mergeKeySet() its unknown which exceptions can occur. However, the error message shown to the user is based on the kind of the exception, so it would be great if it could be documented somewhere.

**Comment by markus2330** [comment]
Is this a documentation issue? Can it be closed?

**Comment by fberlakovich** [comment]
It is a mix of a documentation issue and an error handling issue. There is not much error handling at the moment, but even the bits of error handling (exceptions) are not documented properly. You can close this issue, but if you do please create another issue for improving the error handling in the merging framework

**Comment by markus2330** [comment]
I changed the title to reflect the new scope of the issue.

**Comment by markus2330** [comment]
I close the issue as it is not very clear what needs to be done here.
