### ISSUE TITLE
Too Many Plugins Error reappears even after reducing the number of plugins again

### ISSUE THREAD

**Issue by Piankero** [ElektraInitiative/libelektra#2152]
## Steps to Reproduce the Problem

I wrote a specification for a configuration and run into your [too many plugins error](https://github.com/ElektraInitiative/libelektra/issues/2133) after having too many plugins loaded.

I thought that reducing the number of plugins again would solve the problem but I receive the same error, even when having two plugins only loaded.

I attached my file here:
[bug.zip](https://github.com/ElektraInitiative/libelektra/files/2257465/bug.zip)

First load the specfile with line 4 active and 3 inactive.
You will receive the error.
Then load the specfile with line 3 active and 4 inactive.
You still receive the same error.

```sh
kdb mount LCDd.conf spec/lcdd dump
kdb import spec/lcdd ni < specfile_bug.ini  #Line 4 active
kdb spec-mount /lcdd

#Receive Error

kdb rm -r spec/lcdd
kdb import spec/lcdd ni < specfile_bug.ini  #Line 3 active
kdb spec-mount /lcdd

#Still the same bug
```
## Expected Result

The specfile gets mounted correctly.

## Actual Result

It still complains that there are too many plugins loaded

## System Information

- Elektra Version: 
KDB_VERSION: 0.8.23
SO_VERSION: 4
- Operating System: Linux Mint

## Further Questions

Why is there no spec-umount command?
`kdb stash` is not available in my latest built version so I cannot even have a clean db again.

**Comment by markus2330** [comment]
`kdb spec-mount` always adds all plugins necessary for all metadata within the specification, there is no way to reduce the number of plugins via command-line (there cannot be, it is the purpose of the tool to select all plugins as needed by the specification). So I am not quite sure what you mean by "when having two plugins only loaded". I think this bug does not differ from #2133. It shows the same problem with another tool.

> Why is there no spec-umount command?

Because spec-mount does a normal mount except that it automatically selects the plugins.

> kdb stash is not available in my latest built version so I cannot even have a clean db again.

Did you install Elektra? If you did, please open a separate issue describing what you did.

**Comment by Piankero** [comment]
> `kdb spec-mount` always adds all plugins necessary for all metadata within the specification,...

Alright, after commenting out some specification it works again. I thought that the mounted plugins come from this line `infos/plugins = dump validation` and not some sort of "automounting".
I did not find any documentation that `kdb spec-mount` behaves like this. It is not very intuitive that you have to mount all needed plugins youself, but `spec-mount` magically does it itself without some documentation for it.

I would suggest that you write this behavior in [here](https://github.com/ElektraInitiative/libelektra/blob/master/doc/tutorials/validation.md#specfiles) so it is clear?

Nontheless thanks for your help :)

**Comment by markus2330** [comment]
Yes, it is a great idea to update the documentation, including the tutorial and the man page! Can you please add these two sentences? ("automounting" and umount)

**Comment by Piankero** [comment]
Done in [here](https://github.com/ElektraInitiative/libelektra/pull/2164).
