### ISSUE TITLE
csvstorage: invalid number of columns check too strict?

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2155]
@tom-wa Is this wanted behavior or a bug?

## Steps to Reproduce the Problem

```sh
kdb set /tests/csv/#0
kdb set /tests/csv/#0/a a1
kdb set /tests/csv/#0/b b
kdb set /tests/csv/#1
kdb set /tests/csv/#1/a a2

kdb export /tests/csv csvstorage -c export=,export/a= 
#> a
#> a2
```

## Expected Result

No error because "b" is not exported. Output see above.

I would only expect errors if I try to output a column that is not present in every record.

I would even argue that `kdb set /tests/csv/#0` and `kdb set /tests/csv/#1` are not strictly necessary.

## Actual Result

```
a
a2
Sorry, the error (#117) occurred ;(
Description: invalid number of columns
Reason: illegal number of columns (1 - 2) in line 1
Ingroup: plugin
Module: csvstorage
At: /home/markus/Projekte/Elektra/x/libelektra-build-debian-package/src/plugins/csvstorage/csvstorage.c:724
Mountpoint: /tests/csv
Configfile: /dev/stdout
```

## System Information

- Elektra Version: master

## Workaround

```
kdb set /tests/csv/#1/b
```

For every key, which can be cumbersome if there are many.

**Comment by tom-wa** [comment]
According to RFC 4180 each line should have the same number of fields. Your example would produce an invalid CSV file. 
Possible solutions/workarounds:
 * a plugin to normalize the data (e.g. add required keys)
 * a standalone csvexport plugin
 * _maybe_ some export options for the csvstorage plugin (gotta look into it if is a viable solution)

**Comment by markus2330** [comment]
Each line has the same number of fields: exactly 1. The `/b` key is not exported, so imho its presence should not matter.

**Comment by markus2330** [comment]
Thank you for the quick reply.

As you wrote by email the problem is that the check happens to early. So essentially, we only need to move the check at a later stage for exports?

**Comment by markus2330** [comment]
@tom-wa any progress? It would be great to have a working export!
