### ISSUE TITLE
USE_NFTW not available on build server?

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2157]
## Steps to Reproduce the Problem

See https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2135/26/pipeline

```sh

CYPTO        TESTS

==================



crypto_botan Results: 65 Tests done — 0 errors.

/home/jenkins/workspace/libelektra_PR-2135-KT7KVB3R7BMZPN4PF55YDXXT6WIH7TO44W3NZXZZ7PPZJAFP7MOA/tests/cframework/tests.c:542: error in clean_temp_home: Could not delete TMPHOME manually

--- running testmod_crypto_gcrypt ---



CYPTO        TESTS

==================



crypto_gcrypt Results: 65 Tests done — 0 errors.

/home/jenkins/workspace/libelektra_PR-2135-KT7KVB3R7BMZPN4PF55YDXXT6WIH7TO44W3NZXZZ7PPZJAFP7MOA/tests/cframework/tests.c:542: error in clean_temp_home: Could not delete TMPHOME manually

--- running testmod_crypto_openssl ---



CYPTO        TESTS

==================



crypto_openssl Results: 65 Tests done — 0 errors.

/home/jenkins/workspace/libelektra_PR-2135-KT7KVB3R7BMZPN4PF55YDXXT6WIH7TO44W3NZXZZ7PPZJAFP7MOA/tests/cframework/tests.c:542: error in clean_temp_home: Could not delete TMPHOME manually
```

## Expected Result

That Line 526 of tests.c is executed successfully.

## Actual Result

Line 542 is executed and fails.

## System Information

- Elektra Version: master

**Comment by ingwinlu** [comment]
It obviously is available else there would be problems with master. 

You must have somehow set a feature macro manually which might have disabled the functionality. 
As long as no feature macro is set glibc automatically enables EVERYTHING (same for libc from apple). As soon as you set some flag manually this automatic enable all thing is switched off and hence the function is no longer exported.

Somewhat related to #2095 .

**Comment by markus2330** [comment]
Why did you unassign yourself? You implemented this feature and it does not work.

**Comment by ingwinlu** [comment]
It does work on master. Your PR breaks it.

**Comment by markus2330** [comment]
Yes, unifying feature macros is of course a nice-to-have and I understand it is out of scope for you.

That the build system does not leak files, however, is an important property for a build system. It is like memleaks in source-code.

So to permanently fix this issue, we should have a build server check that verifies that the build process leaks no files. With such a check we would have immediately caught this issue. Now we (you?) need to search which commit introduced the problem.
