### ISSUE TITLE
running unit tests is much slower

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2168]
Seems like one of the current changes (maybe the pluginprocessification of Python?) drastically increased the time needed to execute all tests. First I thought this is only locally but also the build server seems to suffer from the same problem:

2min https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/174/pipeline/220
7min https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/181/pipeline/220

Might be related to #2160

Any idea?

**Comment by e1528532** [comment]
In case its related to pluginprocess, shouldn't such tests be much slower as well locally? 2 to 7 minutes really sounds like a huge regression, the pluginprocess tests always executed almost instantly on my machine

**Comment by markus2330** [comment]
Yes, for me it is also slower locally. Isn't it for you?

**Comment by ingwinlu** [comment]
There should be artifacts in XML Format Form the Tests with time used per
test case. You can compare those to determine what takes longer

e1528532 <notifications@github.com> schrieb am Mi., 8. Aug. 2018, 16:32:

**Comment by e1528532** [comment]
i checked the build server log and the test execution time for both testlib_pluginprocess and testmod_python is stated as <1s. Locally these tests don't take much time either.

**Comment by markus2330** [comment]
I am afraid the reason for this is that my local KDB is now too big. Hopefully the mmap storage will improve this.
