### ISSUE TITLE
Electra dasn't compile with debug & verbose flag

### ISSUE THREAD

**Issue by KurtMi** [ElektraInitiative/libelektra#218]
There are warnings and errors:
/data/elektra_src/src/libelektra/backend.c:385:2: warning: format '%d' expects argument of type 'int', but argument 2 has type 'ssize_t' [-Wformat=]
  printf ("user: %d\n", backend->usersize);
  ^
/data/elektra_src/src/libelektra/backend.c:386:2: warning: format '%d' expects argument of type 'int', but argument 2 has type 'ssize_t' [-Wformat=]
  printf ("system: %d\n", backend->systemsize);
  ^
/data/elektra_src/src/libelektra/split.c: In function 'elektraSplitBuildup':
/data/elektra_src/src/libelektra/split.c:341:3: warning: format '%d' expects argument of type 'int', but argument 2 has type 'size_t' [-Wformat=]
   printf ("  %d with parent %s\n", i, keyName(kdb->split->parents[i]));
   ^
/data/elektra_src/src/libelektra/keyhelpers.c: In function 'keyVInit':
/data/elektra_src/src/libelektra/keyhelpers.c:416:15: error: 'unsigned_long_long_t' undeclared (first use in this function)
        "\n", (unsigned_long_long_t)action);
               ^
/data/elektra_src/src/libelektra/keyhelpers.c:416:15: note: each undeclared identifier is reported only once for each function it appears in
/data/elektra_src/src/libelektra/keyhelpers.c:416:36: error: expected ')' before 'action'
        "\n", (unsigned_long_long_t)action);
                                    ^

**Comment by manuelm** [comment]
Seems nobody compiles with debug enabled ;-)

**Comment by beku** [comment]
@manuelm hehe. I use just CMAKE_C/CXX_FLAGS. So I might not see all stuff supported by cmake Debug targets.
