### ISSUE TITLE
C++ binding: "delBaseName" missing

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2182]
See #2181#discussion_r210214397 it is not possible to pass 0 to setBaseName so we should add a separate delBaseName to provide this functionality.

**Comment by sanssecours** [comment]
> …it is not possible to pass 0 to setBaseName…

Since you merged commit 7af5fab7, this should now be possible. However, adding a function called `delBaseName` or `removeBaseName` definitely makes sense in my opinion.

**Comment by markus2330** [comment]
I did not look at the latest fixes by you, so I did not notice. I did not expect that you will extend the API :smile:  I really wonder that all bindings happily accept overloading the function in this way. How do they know which method to call?

I tend to rather have only setBaseName(char*) or a delBaseName, not both. And shouldn't it be del* to be consistent with other methods?

**Comment by sanssecours** [comment]
> I tend to rather have only setBaseName(char*) or a delBaseName, not both.

That makes sense. I would prefer `delBaseName`. However, since calling `key.setBaseName(0)` before commit 7af5fab would cause a segmentation fault, I am not that sure that we should remove `Key::setBaseName (char const * baseName)`.

**Comment by markus2330** [comment]
For C++ programmers it is obvious that this will segfault, you cannot initialize a std::string with 0. I wonder why you did not get any warning?

So we could have a delBaseName which internally simply calls keySetBaseName (key, 0). Then we do not need the setBaseName (char const * baseName), if you change your code.

**Comment by sanssecours** [comment]
> For C++ programmers it is obvious that this will segfault, you cannot initialize a std::string with 0.

I would have expected 

- to not be able to compile the code at all, or 
- for the compiler to print a warning message

😒.

> So we could have a delBaseName which internally simply calls keySetBaseName (key, 0). Then we do not need the setBaseName (char const * baseName), if you change your code.

Sounds good to me. I opened pull request #2183 for that purpose.
