### ISSUE TITLE
Test cases may fail if config files already exist

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2190]
For example:

- testshell_markdown_ccode and testshell_markdown_tcl fail if ~/.config/config.tcl is a non-TCL file
- testshell_markdown_tutorial_validation fails if ~/.config/tutorial.dump contains user/tests/tutorial/spec/should_not_be_here
- testshell_markdown_toml fails if ~/.config/test.toml exists

Furthermore, the situation, that our tests simply start modifying already existing config files, is not ideal.

Two ways to resolve this:

- the shell recorder moves and restores config files if they were already present (but not created by earlier lines of the shell recorder test)
- the shell recorder prefixes the names of the config files

**Comment by sanssecours** [comment]
I think the most simple solution would be to reserve a certain prefix for MSR config file names. For example, we could just require that every config file name we use in (Markdown) Shell Recorder tests has to start with the text `tests_`.

**Comment by markus2330** [comment]
A constant prefix might reduce the likelihood but in my case it would not have been helpful: all the cases I had up to now where leftovers from unsuccessful or aborted previous test runs.

Shellrecorder is the only place where we can give guarantees about files not being there and being cleaned up in the end.

**Comment by sanssecours** [comment]
> …all the cases I had up to now where leftovers from unsuccessful or aborted previous test runs.

In that case the second solution you proposed above:

> - the shell recorder prefixes the names of the config files

does not fix the problem either.

**Comment by markus2330** [comment]
Depends on the prefix: mktemp or uuid should suffice for any practical purpose.

**Comment by markus2330** [comment]
I had again this problem (~/.config/tutorial.dump) was present. It would be great if shell recorder could have better support to deal with this problem.

**Comment by markus2330** [comment]
We simply should make `kdb stash` or some clean docker/chroot a precondition in doc/TESTING.md.  Then such left-overs bugs would not matter.

What do you think? How do you execute the tests without running into these problems?

**Comment by mpranj** [comment]
> How do you execute the tests without running into these problems?

I usually use a clean docker environment to avoid any left-over files.

> the shell recorder moves and restores config files if they were already present 

The best would be that the tests do not touch user config files at all ... (so no backup&restore either).

To me the `mktemp` approach seems best, because it is quite clear that the files should not persist in a users `.conf` folder. I've had many annoying leftover files from tests there.

**Comment by markus2330** [comment]
Would be fixed with #4482
