### ISSUE TITLE
anatomy of WORKSPACE

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2192]
Currently error messages contain source code locations like:

At: /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@2/libelektra/obj-x86_64-linux-gnu/src/include/kdberrors.h:23334

Where does Q2... come from? Is this reproducible?

**Comment by ingwinlu** [comment]
as jenkins requires a workspace it might be autogenerated per build.

**Comment by markus2330** [comment]
So you never changed anything and just use the $WORKSPACE you get?

**Comment by ingwinlu** [comment]
yes. if something changed maybe it was due to updates to any of the plugins we use?

**Comment by markus2330** [comment]
Thank you.
