### ISSUE TITLE
Plugin questions/suggestions

### ISSUE THREAD

**Issue by Piankero** [ElektraInitiative/libelektra#2200]
I have a few questions and improvement ideas which I want to discuss before doing a PR.

# Questions

## range plugin
Does it support floats eg "0.0005 - 10"? Didn't work for me.

# Improvement questions

## network plugin

Alot of configuration options which I have seen just give "localhost" on some configurations.
The `check/ipaddr` only allows valid IP's. I would make an exception for `localhost` though
which should be allowed too as it is very common.

## path plugin

The idea of the path plugin is great but requiring absolute path limits deploy-ability quite a bit.
I would at least suggest to allow `~` which is resolved then to the home path of the current user when setting it.

## conditionals plugin

It now happened quite alot that a value depends on another one. Eg. if user sets "model = some_model1", then the value of another setting is change, eg "driver = some_model1_driver".
The conditionals plugin does not really support this kind of behavior, especially not with arbitrary much conditionals (like a switch statement). I would also suggest incorporating that

**Comment by markus2330** [comment]
> Does it support floats eg "0.0005 - 10"? Didn't work for me.

I do not think it does but I agree that the docu is fuzzy about that.

> The check/ipaddr only allows valid IP's.

For check/ipaddr there are two different implementations, "network" allows everything the operating system supports. For the other implementation, which is regex based, only IP addresses are allowed.

> I would make an exception for localhost though which should be allowed too as it is very common.

I do not think we can allow this. Actually, you pointed to a problem: maybe the "network" behavior is always right because applications might use different APIs, that do not support names (but only IP addresses).

> would at least suggest to allow ~ which is resolved then to the home path of the current user when setting it.

Good suggestion but supporting "~" is a Pandora's box. We should only do it when we share the implementation with the resolver.

> It now happened quite alot that a value depends on another one. Eg. if user sets "model = some_model1", then the value of another setting is change, eg "driver = some_model1_driver".

This sounds like string concatenation unrelated to conditionals, doesn't it?

**Comment by markus2330** [comment]
Btw. I think you slowly see the main problems:

- it is hard to precisely define behavior of meta data (especially with multiple implementations)
- it is difficult to combine different things (conditionals, string concatenation, ...)
- it is hard to define order between meta data (#907 is a partial solution but it does not work across different meta data)

Progress on these topics are definitely worth a master thesis :+1:

**Comment by Piankero** [comment]
> For check/ipaddr there are two different implementations, "network" allows everything the operating system supports.

I included the network plugin to check for the ipaddr as localhost. Did not work for me.

> Good suggestion but supporting "~" is a Pandora's box. We should only do it when we share the implementation with the resolver.

I see, for LCDproc I think I wont be able to use the checks then for a few settings :/

> This sounds like string concatenation unrelated to conditionals, doesn't it?

I really meant that one value depends on another. Or imagine other default display sizes, depending on the monitor which a user provided via a configuration. LCDproc uses it for example here:
https://github.com/lcdproc/lcdproc/blob/master/LCDd.conf#L266 (the model is defined a few lines above)

**Comment by markus2330** [comment]
>  I included the network plugin to check for the ipaddr as localhost. Did not work for me.

Are you sure you included it? (kdb mountpoint-info) If you can ping "localhost" and the value is rejected, please open a bug report.

> I see, for LCDproc I think I wont be able to use the checks then for a few settings :/

If it is necessary we can do it. We already reuse these resolver parts in other plugins.

> Or imagine other default display sizes, depending on the monitor which a user provided via a configuration.

Ahh, yes. Default value calculation is actually missing and would be important to have.

**Comment by Piankero** [comment]
> Are you sure you included it? (kdb mountpoint-info) If you can ping "localhost" and the value is rejected, please open a bug report.

[#2203](https://github.com/ElektraInitiative/libelektra/issues/2203)

> Ahh, yes. Default value calculation is actually missing and would be important to have.

I will submit a new PR with a README.md in the near future for this purpose.

**Comment by markus2330** [comment]
Maybe it would be good if you create some meta-issue where you have TODOs for things like default value calculation. Or do you use the LCDproc project for that?

**Comment by Piankero** [comment]
I can do that but especially for the default value calculation I assume that this project is very huge. More about that tomorrow in our meeting. For now I will create a meta Issue though :)
