### ISSUE TITLE
On check_symbol_exists and werror

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#2218]
https://cmake.org/Bug/view.php?id=13208

A generated c file that checks for availability of fork:

```
[winlu@virtualArch libelektra]$ cat build/CMakeFiles/CMakeTmp/CheckSymbolExists.c 
/* */
#include <sys/types.h>
#include <unistd.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef fork
  return ((int*)(&fork))[argc];
#else
  (void)argc;
  return 0;
#endif
}
```

The error when compiling (with our flags as defined in ElektraCompiling) :
```
build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:9:11: error: ISO C forbids conversion of function pointer to object po
inter type [-Werror=pedantic]
   return ((int*)(&fork))[argc];
           ^
cc1: all warnings being treated as errors
[winlu@virtualArch libelektra]$
```

Hence adding -Werror is not as easy as thought (breaks out cmake). and explaining why https://github.com/ElektraInitiative/libelektra/commit/5b800ceaddcd59b4711e776e256ed8277f906508 had an effect on the detection of functions.
I already argued in https://github.com/ElektraInitiative/libelektra/pull/2159 that the commit is basically snake oil and only hides issues instead of fixing the real issue.
However I could not confirm my original assumption that without -Werror present check_symbol_exists might pass on invalid code since the function might be implicitly declared.

I am unsure on how to best approach on how to reliable determine which symbols/functions are available now across the whole codebase.
I am also not hopeful on an upstream fix as the issue is known for several years now.

One option would be to provide our own implementation which would disable -Wpedantic for all checks.

This blocks efforts that rely on detecting exported symbols such as #2078 or the recently opened #2217 that tries to add -Werror to builds.

**Comment by markus2330** [comment]
Disabling -Werror for CheckSymbolExists and our own checker programs is a pragmatic solution. Of course it is snake oil, as it might hide some run-time errors (e.g. differences in parameters that only emit warnings). But it seems like there is no viable alternative which would fit in the time budget you have. And if there are tests that check functionality, only people not running the tests would actually hit such bugs at run-time.
