### ISSUE TITLE
testkdb_allplugins SEGFAULT master

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#2220]
`testkdb_allplugins` seems to be segfaulting sporadically with the current master.
This is not limited to a specific machine (happened on i7 and v2) nor is it limited to ctest vs ctest memcheck.

**Comment by markus2330** [comment]
Thank you for reporting the problem! Do you have some stack trace?

Was there also an occurrence of a segfault with valgrind? Then we would maybe get even more information.

I never got this segfault locally up to now. Did you try to run testkdb_allplugins in a loop?

**Comment by markus2330** [comment]
I executed it several thousand times now with `while ctest -R testkdb_allplugins; do i=$((i+1)); echo $i; done`.

Which docker image can I use to reproduce it?
