### ISSUE TITLE
Boolean plugin has random behavior

### ISSUE THREAD

**Issue by Piankero** [ElektraInitiative/libelektra#2222]
I tried to use the boolean plugin. After changing a value from a previously set value the plugin rejects it with a nonsense error.

```sh
sudo kdb mount bool.conf /bool dump boolean
kdb setmeta /bool/b type boolean
#>Using keyname spec/bool/b
kdb set /bool/b true
#>Using name system/bool/b
#>Create a new key system/bool/b with string "true"
kdb get /bool/b
#>1
kdb set /bool/b false
#>Using name system/bool/b
#>The command kdb set failed while accessing the key database with the info:
#>Sorry, the error (#153) occurred ;(
#>Description: not a valid boolean value
#>Reason: true is not a valid boolean value
#>Ingroup: plugin
#>Module: boolean
#>At: /media/wespe/extended/repository/piankero-libelektra/src/plugins/boolean/boolean.c:345
#>Mountpoint: system/bool
#>Configfile: /etc/kdb/bool.conf.16220:1535989849.48285.tmp
```

What did I do wrong?

**Comment by markus2330** [comment]
Thank you for reporting the issue!

"random" is a bit misleading here, it means that sometimes it does what it should and after executing the same commands, it sometimes does not.

And are you sure you used the commands exactly as mentioned above? You did not even add the boolean plugin?

To avoid such problems, why not simply creating a PR modifying the Example in the boolean plugin and let the build server check that the problem you want to show actually occurs.

I am not sure what you tried and can not reproduce the problem.

What I did see, however, that the documentation is lacking to mention "check/type" next to "type" and infos/metadata is completely empty. The docu also hides which values are "true/false" by default (only shown on the very bottom).

**Comment by Piankero** [comment]
![proof](https://user-images.githubusercontent.com/12346621/45345861-e0c56980-b5a7-11e8-813d-fa2d93b1ce69.png)

This is an actual screenshot from my system.

> And are you sure you used the commands exactly as mentioned above? You did not even add the boolean plugin?

I typed in the commands manually, looks like i did a mistake there when taking over the commands from the console. But the problem remains.

**Comment by markus2330** [comment]
Sorry, seems like we had a misunderstanding: I had no doubt that you have this problem, it is only that I could not reproduce it. The goal is to improve Elektra, not to demonstrate who is right. And if I type the text from the screenshot, this won't increase the chance that I'll be able to reproduce (I might mistype something, something that happened before might be relevant, ...). With a PR and reproducibility on the buildserver there is no possibility of misunderstanding/typing errors/... on both sides.

And in this case the PR is useful anyway because the boolean docu is not very good.

**Comment by markus2330** [comment]
Yes, simply extend the example in the readme. Or add one more example.

**Comment by markus2330** [comment]
Were you able to reproduce the issue?
