### ISSUE TITLE
document cmake -DBINDINGS=ALL in doc/COMPILE.md

### ISSUE THREAD

**Issue by beku** [ElektraInitiative/libelektra#223]
looks like it is only in NEWS.md . Just as reminder: would be good to have in doc/COMPILE.md

**Comment by markus2330** [comment]
Hello, thank you!

Does 48964fe help you?

I am not happy with the cmake variable situation. I would like to have a self-documented system which disallows invalid configuration. Unfortunately, CMake seems to make that hard. (e.g. only one line of CMake variable documentation is displayed in ccmake)

**Comment by beku** [comment]
thanks, for the docu
