### ISSUE TITLE
gtest with static linking off

### ISSUE THREAD

**Issue by beku** [ElektraInitiative/libelektra#224]
From OBS Debian_8.0 build of elektra git master:

[  382s] cd /usr/src/packages/BUILD/obj-x86_64-linux-gnu/src/tools/race && /usr/bin/cc   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -std=gnu99  -Wno-deprecated-declarations  -Wno-long-long -pedantic -Wno-variadic-macros -Wall -Wextra -Wno-overlength-strings -Wsign-compare -Wfloat-equal -Wformat-security -Wshadow -Wcomments -Wtrigraphs -Wundef -Wuninitialized -Winit-self -Wmaybe-uninitialized -Wsign-compare -Wfloat-equal -Wformat-security -I/usr/src/packages/BUILD/obj-x86_64-linux-gnu/src/include -I/usr/src/packages/BUILD/src/include    -o CMakeFiles/race.dir/race.c.o   -c /usr/src/packages/BUILD/src/tools/race/race.c
[  382s] Linking C executable ../../../bin/race
[  382s] cd /usr/src/packages/BUILD/obj-x86_64-linux-gnu/src/tools/race && /usr/bin/cmake -E cmake_link_script CMakeFiles/race.dir/link.txt --verbose=1
[  382s] /usr/bin/cc  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -std=gnu99  -Wno-deprecated-declarations  -Wno-long-long -pedantic -Wno-variadic-macros -Wall -Wextra -Wno-overlength-strings -Wsign-compare -Wfloat-equal -Wformat-security -Wshadow -Wcomments -Wtrigraphs -Wundef -Wuninitialized -Winit-self -Wmaybe-uninitialized -Wsign-compare -Wfloat-equal -Wformat-security   -Wl,-z,relro CMakeFiles/race.dir/race.c.o  -o ../../../bin/race -rdynamic -lpthread -lelektra-static 
[  382s] /usr/bin/ld: cannot find -lelektra-static
[  382s] collect2: error: ld returned 1 exit status
[  382s] src/tools/race/CMakeFiles/race.dir/build.make:88: recipe for target 'bin/race' failed
[  382s] make[3]: *** [bin/race] Error 1
[  382s] make[3]: Leaving directory '/usr/src/packages/BUILD/obj-x86_64-linux-gnu'
[  382s] CMakeFiles/Makefile2:7982: recipe for target 'src/tools/race/CMakeFiles/race.dir/all' failed
[  382s] make[2]: *** [src/tools/race/CMakeFiles/race.dir/all] Error 2
[  382s] make[2]: *** Waiting for unfinished jobs....

debian/rules says:
CMAKE_ARGS = -DLIB_SUFFIX="/$(DEB_HOST_MULTIARCH)" \
  -DTARGET_PLUGIN_FOLDER="elektra4" \
  -DPLUGINS="ALL" \
  -DTOOLS="ALL" \
  -DBUILD_STATIC=OFF \
  -DBUILD_SWIG=ON -DSWIG_EXECUTABLE="/usr/bin/swig3.0" \
  -DBUILD_SWIG_LUA=ON \
  -DBUILD_SWIG_PYTHON3=ON -DPython_ADDITIONAL_VERSIONS="$(PY3VER)" \
  -DGTEST_ROOT="/usr/src/gtest" \
  -DTARGET_DOCUMENTATION_HTML_FOLDER="share/doc/elektra-doc/html"

**Comment by markus2330** [comment]
the problem is fixed with db20051
Is there any specific reason why the static build is disabled?

Maybe it would be good to have a usecase discussion which BUILD_* flags are needed when + if all combinations are needed + how to choose which binaries are linked against which kind of elektra?

**Comment by markus2330** [comment]
Btw. is BUILD_TESTING and ENABLE_TESTING needed? Would be good to reduce some options, if possible.

**Comment by beku** [comment]
thanks for the fix. The mentioned options came from the debian/rules. Will try to omit those.

**Comment by markus2330** [comment]
For reference: BUILD_TESTING is actually needed for mingw, where not all testing code compiles.
ENABLE_TESTING might be expected by CMake users, even though I still wonder if there really is a build system that cannot disable running of tests by itself (just omit "make test").

**Comment by beku** [comment]
BUILD_TESTING and ENABLE_TESTING is removed from the OBS spec file. (You might want cc Pino about the Debian side?)

**Comment by beku** [comment]
... and confirmed on MinGW we use -DBUILD_TESTING=OFF
