### ISSUE TITLE
half way python3 detection

### ISSUE THREAD

**Issue by beku** [ElektraInitiative/libelektra#226]
OBS says:

[   47s] -- Include Binding swig
[   47s] -- Found SWIG: /usr/bin/swig (found suitable version "3.0.5", minimum required is "3")
[   47s] -- Found Python2Interp: /usr/bin/python2.7 (found suitable version "2.7.9", minimum required is "2.7")
[   47s] -- Found Python2Libs: /usr/lib64/libpython2.7.so (found suitable version "2.7.9", minimum required is "2.7")
[   47s] -- Include Binding swig_python2
[   47s] -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.4.3", minimum required is "3")
[   47s] -- Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is at least version "3")
[   47s] -- Exclude Binding swig_python3 because python3 libs not found

.. only python2.7 is swigged. Any idea?

**Comment by markus2330** [comment]
Hello,

Kai-Uwe Behrmann wrote:
> "3.4.3", minimum required is "3") [   47s] -- Could NOT find PythonLibs
> (missing:  PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is at least
> version "3") [   47s] -- Exclude Binding swig_python3 because python3 libs
> not found

As CMake suggests PYTHON_LIBRARIES and PYTHON_INCLUDE_DIRS need to be set.

E.g. see scripts/configure-debian-wheezy-local how python2 and python3 at the 
same time work for me. Relevant excerpt from there (its for wheezy, pathes 
must be adapted accordingly):

cmake -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 \
	-DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.2 \
	-DPYTHON_LIBRARY:FILEPATH=/usr/lib/libpython3.2mu.so \	
	-DTOOLS=ALL -DBINDINGS="cpp;swig_python2;swig_python3;jna"

best regards,
Markus

**Comment by beku** [comment]
PYTHON_INCLUDE_DIR would be too cryptic for guessing in order to be practical -  on oS-13.2 /usr/include/python3.4m/

**Comment by markus2330** [comment]
Hello,

You wrote:
> PYTHON_INCLUDE_DIR would be too cryptic for guessing in order to be
> practical -  on oS-13.2 /usr/include/python3.4m/

The guessing happens in the systems FindPythonLibs.cmake and I do not know why 
most distributions were unable to put the pathes they use inside there. On 
Debian the cmake file contains code to look into the windows registry, but is 
lacking the simple hint /usr/lib/python3.2/. Seems like your distro has the 
same problem.

So maybe such pathes should be stored in Elektra ;)

best regards,
Markus

**Comment by markus2330** [comment]
Ok, I think I found the problem. the search for python2 libs overwrote an internal variable needed by python3 searching.

CMake really isn't the best language. But its a great build system.

Could you check if it also solves your problem and close the issue?
