### ISSUE TITLE
cache: transient plugins

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2269]
@mpranj we forgot that the global cache will not work at all if a single resolver is always out-of-date.

For example, if someone has mounted the "noresolver" plugin (e.g. to work with the "uname" plugin), we would always throw away the cache.

Possible solutions:

1. Also store the transient data into the global cache (where the timestamps are) and let the resolver check if the data is unchanged. The comparison could be implemented in "noresolver" but somehow plugins would need to be invoked to get the data.
2. have a functionality that transient data can be added to the KeySet also after cache hits. This would need changes in the "split" logic of KDB. The advantage is that this would also allow the user the exclude encrypted backends.

**Comment by mpranj** [comment]
Thank you for reporting and providing solutions!
I was aware of the problem in general, but not that this could be a "typical" scenario.

**Comment by markus2330** [comment]
Yes, for example the "constants" plugin actually should be even part of the default backends. So we need a solution for the "noresolver".

Of course we do not need a solution for every possible backend. For example, we might be able to live without backends returning random numbers or a timestamp (if having this conflicts heavily with a good mmap solution). At the moment we do not have such backends anyway. But of course we would need to document such limitations even if they do not limit any of the current plugins.
