### ISSUE TITLE
gir installation

### ISSUE THREAD

**Issue by beku** [ElektraInitiative/libelektra#227]
Independent from the OBS link issue #225, on a development machine the local install fails due to 
INTROSPECTION_GIRDIR and INTROSPECTION_TYPELIBDIR want /usr/lib64, which requires root rights. Please see src/bindings/gi/CMakeLists.txt:54

**Comment by markus2330** [comment]
Hello,

Kai-Uwe Behrmann wrote:
> on a development machine the
> local install fails due to  INTROSPECTION_GIRDIR and
> INTROSPECTION_TYPELIBDIR want /usr/lib64, which requires root rights.
> Please see src/bindings/gi/CMakeLists.txt:54

Does ee32187ae8032e6c1c4da39f264c07a49760b3d8 look like a solution?

@manuelm The alternative, installing somewhere else (e.g. prefixed with 
CMAKE_INSTALL_PREFIX) does not really make sense, does it?

**Comment by markus2330** [comment]
please reopen if ee32187 did not solve the issue.
