### ISSUE TITLE
coveralls: make jobs not fail on master

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2289]
## Steps to Reproduce the Problem

Push commits to master.

## Expected Result

That it is successful if the PR was successful.

## Actual Result

The build job might fail if the coverage decreased, e.g.:

https://coveralls.io/builds/19804348

I am not even sure if the result is correct, it does not seem that this PR changed so much that this could reduce 8.2% of coverage.

**Comment by sanssecours** [comment]
I changed

- the “Coverage Threshold for Failure” to 60 %, and
- the “Coverage Decrease Threshold for Failure“ to 10%

at https://coveralls.io/github/ElektraInitiative/libelektra/settings. If you want you can increase/decrease these values even further.
