### ISSUE TITLE
libglobbing does not support escaped slashes

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#2297]
# Problem
Currently the new libglobbing does not support escaped slashes. This is because the library relies on, `fnmatch(3)` with the flags `FNM_NOESCAPE` and `FNM_PATHNAME` enabled.

# Possible Solution
Instead of `fnmatch` we could use `regex.h`. This would require translating the globbing expressions into regular expressions. Additionally we would need to escape any of the regex special characters.

The regular expression `([^\\/]|(\\\\)*\\/|\\\\)+` should match a single key name part.
I tested the regex with this script (an additional `\` has to be added because of the way sed expressions work):
```
cat <<'EOF' |
test/
other test/
more/test/123
adv\/anced/t\\\/est
another\\\\/test
EOF
sed -E 's/([^\\/]|(\\\\)*\\\/|(\\\\))+/{{\0}}/g'
```
Which prints:
```
{{test}}/
{{other test}}/
{{more}}/{{test}}/{{123}}
{{adv\/anced}}/{{t\\\/est}}
{{another\\\\}}/{{test}}
```

# Alternative Solution

A better solution may be to create a Key with the globbing expression and then use the unescaped name to match part by part. This pseudo code for this would look like this:

```
bool globMatches (Key * key, const char * glob)
{
    create Key from glob
    // simultaneously iterate over keyname parts using keyUnescapedName
    foreach keyPart in key, globPart in glob do
        if globPart == "#" and keyPart is not arrayElement
            return not_matching
        if globPart == "_" and keyPart is arrayElement
            return not_matching
        if globPart == "__" and keyPart is last part in key
            return matching
        if not fnmatch (globPart, keyPart) // without FNM_PATHNAME
            return not_matching
    end
    return matching
}
```

Performance might be improved, by first checking, if the globbing expression contains a `\`. If there is no backslash, we can use the current implementation safely. Whether this is actually an improvement would have to be benchmarked however. My guess is that it would improve performance, because creating a key is not a cheap operation, because it uses malloc extensively.

**Comment by markus2330** [comment]
Thank you! Yes, I like the regex idea. It also has advantages for other tools (like a "mmv"-like functionality). And it is in general very useful for external tools if we can specify a regex.

The regex does not seem to be complete, though. Single backslashes are generally allowed (to be used literally) but in some situations they are used for escaping (., %), see also src/libs/elektra/keyname.c

```
cat <<'EOF' |
level1/\./level3
level1/\../level3
level1/\%/level3
level1/\x/level3
level1/x\x/level3
EOF
sed -E 's/([^\\/]|(\\\\)*\\\/|(\\\\))+/{{\0}}/g'
```
commented output:

```
{{level1}}/\{{.}}/{{level3}}  # ok
{{level1}}/\{{..}}/{{level3}}  # ok
{{level1}}/\{{%}}/{{level3}}  # ok
{{level1}}/\{{x}}/{{level3}}  # backslash should be part of key name part in level2
{{level1}}/{{x}}\{{x}}/{{level3}}  # should not introduce a new level
```

**Comment by kodebach** [comment]
> compilation of regex for every key

Yes the regex would be compiled for every call of `elektraKeyGlob`. But if you want to match against many keys you should really call `elektraKsGlob`, which could internally be optimised to only compile the regex pattern once.

> I assume fnmatch is already highly optimized

According to [this](https://www.boost.org/doc/libs/1_54_0/libs/regex/doc/vc71-performance.html) its more that POSIX `regex.h` is badly optimized.

Which is why I now think, using regex without allowing regex input from the user might not be a good idea. However, for mmv-like functionality which needs back references, using PCRE might be worth thinking about. PCRE with its many extensions, would also allow direct translation of `_` and `#` into regex (using recursion and negative lookahead), although this would require extensive testing.

> With larger specifications, most of the execution time is already spent within the spec plugin matching key names

We could always provide a second version `elektraKeyGlobFast`, which restricts the usage of `*`. Use of `*` would only be allowed in one of three ways:
* as a whole key part, i.e. key part can be anything
* ONCE anywhere inside a key part, i.e. key part must have prefix, suffix or both
* at the start AND end of a key part, i.e. key part must contain substring
This behaviour would a simple hand-written implementation possible, it would also allow further optimisations for KeySet.

For the spec plugin, this would not be a problem because `*` is an undocumented feature anyway.

Additionally `elektraKsGlobFast` could use a trie-like structure on the basis of key name parts, which would be compiled first (for reuse with different patterns). This way not every key in the KeySet has to be checked.

For example when the KeySet contains `abc/def`, `abc/jkl` and `test/k?y`. The trie structure would be:
```
                  +
                  |
          +--------------+
          +              +
         abc            test
          +              +
     +----+----+         |
     +         +         +
    def       jkl       key

```

When matching against the pattern `test/*` we do:
1. search `test` in sorted of children list `{ abc, test}`
2. go to sub-tree of `test`, ignore everything else
3. recursively call on every child of `test`, because of `*`
4. `k?y` find sub-keys matching pattern and call recursively
4. add the Key `test/key` to the result (because it is a leaf)

Here the restriction of `*` provides significant advantages, because it makes matching easier.
If the whole key part is `*` every child matches (`_` and `#` are similar if we store separate child lists at construction). And as long as a prefix of the key part is known, we can perform a binary search for the first child matching that prefix and the check the following children. Only if no prefix is known, we need to look at every child.

**Comment by kodebach** [comment]
I added an alternative solution that doesn't rely on regex and would be quite easy to implement. If we go for that solution, we may want to mark this issue as a "good first issue".
