### ISSUE TITLE
qt-gui build fails in openSUSE_Factory

### ISSUE THREAD

**Issue by beku** [ElektraInitiative/libelektra#230]
Qt5 requires building position independent. But in elektras qt-gui CMAKE_CXX_FLAGS are ignored. Building stops therefore.

spec file says:
%cmake -DTARGET_PLUGIN_FOLDER="elektra%{api}" \
  -DPLUGINS="ALL" \
  -DTOOLS="ALL" \
  -DBINDINGS="ALL" \
  -DPYTHON_INCLUDE_DIR=`python3  -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())"` \
  -DPYTHON_LIBRARY=/usr/%{_lib}/libpython3.so \
  -DTARGET_DOCUMENTATION_HTML_FOLDER="share/doc/elektra-doc/html" \
  -DBUILD_DOCUMENTATION=ON \
  -DTARGET_CMAKE_FOLDER=%{_libdir}/cmake/elektra \
  -DCMAKE_C_FLAGS="-fPIC $CFLAGS" \
  -DCMAKE_CXX_FLAGS="-fPIC $CXXFLAGS"

Message:
[  423s] cd /home/abuild/rpmbuild/BUILD/elektra-150629.180742gite39f439b/build/src/tools/qt-gui && /usr/bin/c++   -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_QML_LIB -DQT_QUICK_LIB -DQT_TESTLIB_LIB -DQT_WIDGETS_LIB -fPIC -fomit-frame-pointer -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -std=c++98  -Wno-deprecated-declarations  -Wstrict-null-sentinel -Wno-missing-field-initializers -Wold-style-cast -Woverloaded-virtual  -Wsign-promo  -Wno-long-long -pedantic -Wno-variadic-macros -Wall -Wextra -Wno-overlength-strings -Wsign-compare -Wfloat-equal -Wformat-security -Wshadow -Wcomments -Wtrigraphs -Wundef -Wuninitialized -Winit-self -Wmaybe-uninitialized -O3 -DNDEBUG -fPIE -I/home/abuild/rpmbuild/BUILD/elektra-150629.180742gite39f439b/build/src/tools/qt-gui -I/home/abuild/rpmbuild/BUILD/elektra-150629.180742gite39f439b/src/tools/qt-gui -I/home/abuild/rpmbuild/BUILD/elektra-150629.180742gite39f439b/build/src/include -I/home/abuild/rpmbuild/BUILD/elektra-150629.180742gite39f439b -I/home/abuild/rpmbuild/BUILD/elektra-150629.180742gite39f439b/src/tools/qt-gui/../../libtools/include -I/home/abuild/rpmbuild/BUILD/elektra-150629.180742gite39f439b/src/tools/qt-gui/../../libtools/include/merging -I/home/abuild/rpmbuild/BUILD/elektra-150629.180742gite39f439b/src/tools/qt-gui/../../libtools/include/helper -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -isystem /usr/lib/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtTest -isystem /home/abuild/rpmbuild/BUILD/elektra-150629.180742gite39f439b/src/tools/qt-gui/src/markdownconverter -I/home/abuild/rpmbuild/BUILD/elektra-150629.180742gite39f439b/src/include -I/home/abuild/rpmbuild/BUILD/elektra-150629.180742gite39f439b/build/src/bindings/cpp/include -I/home/abuild/rpmbuild/BUILD/elektra-150629.180742gite39f439b/src/bindings/cpp/include -I/home/abuild/rpmbuild/BUILD/elektra-150629.180742gite39f439b/build/src/libtools/include -I/home/abuild/rpmbuild/BUILD/elektra-150629.180742gite39f439b/src/libtools/include    -o CMakeFiles/qt-gui.dir/src/guibackend.cpp.o -c /home/abuild/rpmbuild/BUILD/elektra-150629.180742gite39f439b/src/tools/qt-gui/src/guibackend.cpp
[  423s] In file included from /usr/include/qt5/QtCore/qnamespace.h:37:0,
[  423s]                  from /usr/include/qt5/QtCore/qobjectdefs.h:41,
[  423s]                  from /usr/include/qt5/QtCore/qobject.h:40,
[  423s]                  from /usr/include/qt5/QtCore/QObject:1,
[  423s]                  from /home/abuild/rpmbuild/BUILD/elektra-150629.180742gite39f439b/src/tools/qt-gui/src/guibackend.hpp:4,
[  423s]                  from /home/abuild/rpmbuild/BUILD/elektra-150629.180742gite39f439b/src/tools/qt-gui/src/guibackend.cpp:1:
[  423s] /usr/include/qt5/QtCore/qglobal.h:1052:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC (-fPIE is not enough)."
[  423s]  #  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\
[  423s]     ^

Solutions:
let CMAKE_CXX_FLAGS pass through. IMO, it is always a good solution to let users/distributors decide, what they think is good for their system. Or look at:
https://forum.qt.io/topic/28359/qt5-compilation-catastrophic-error/6
https://github.com/Cockatrice/Cockatrice/commit/9cfb09cd5b25a01fb142d425ba70b77b89f65a09

**Comment by markus2330** [comment]
Hello,

Kai-Uwe Behrmann wrote:
> [  423s] .. /usr/bin/c++   -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB
> -DQT_NO_DEBUG -DQT_QML_LIB -DQT_QUICK_LIB -DQT_TESTLIB_LIB -DQT_WIDGETS_LIB
> -fPIC

I do not see any reason why CMAKE_CXX_FLAGS should not be passed trough.
And it worked for me locally, also for qt-gui. In your output it seems like 
they are passed through, too.

Maybe the error comes from some C Code which would have needed -fPIC, too?

ca511024f394a56b86a861e6029585ec1448f789 hopefully makes such -fPIC hacks 
unnecessary.

Please do not hesitate to reopen when the problem is not fixed!

best regards,
Markus

**Comment by beku** [comment]
This particular point appears here too:
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1341159.html
/usr/include/qt5/QtCore/qglobal.h +1052 says:
(defined(__PIE__) && defined(Q_CC_GNU) && Q_CC_GNU >= 500
#  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\
         "Compile your code with -fPIC (-fPIE is not enough)."
Not sure where -fPIE comes from.

**Comment by markus2330** [comment]
Every application using qt5 built with -reduce-relocations not using -fPIC should be affected.

But ca51102 should correctly add -fPIC for qt-gui in Elektra.

Can you point me to a build log where the problem persists?

**Comment by beku** [comment]
Confirmed that -fPIC is there. But qglobal.h +1052 has this by me not yet understood \_\_PIE__ macro set.

Here the log:
https://build.opensuse.org/build/home:bekun:devel/openSUSE_Factory/i586/elektra/_log

**Comment by markus2330** [comment]
The errors in the log (Tue Aug 18 08:40:59 UTC 2015):
```
CMake Error: install(EXPORT "ElektraTargetsLibelektra") given absolute DESTINATION "/usr/lib/cmake/elektra" but the export references an installation of target "elektra" which has relative DESTINATION "lib".
```
seem to be unrelated to this issue?

It uses the _INSTALL_DIR options wrongly (absolute instead of relative), instead of -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DINCLUDE_INSTALL_DIR:PATH=include should be correct. More specifically, -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib seems to cause that problem.

Btw. The `find . -name CMakeLists.txt..` looks really strange, what is it for? Is it needed for Elektra?

**Comment by beku** [comment]
Your are right the actual build has a new issue. Thanks for your comment.

Here a link to the old log from June:
http://www.oyranos.org/temp/elektra-150629.180742gite39f439b-PIE-log.txt

**Comment by beku** [comment]
ping: the spec file is repaired and the obs log from git master shows the same issue.

**Comment by beku** [comment]
> Btw. The find . -name CMakeLists.txt.. looks really strange, what is it for? Is it needed for Elektra?
That comes likely from RPM macros.

**Comment by markus2330** [comment]
I think I found the problem: the macro checks for defined(__PIE__), that means that -fPIE is not allowed to be present, CMAKE_POSITION_INDEPENDENT_CODE is likely to be the cause.

So maybe ca51102 introduces another problem and it can only be solved by adding -fPIC globally (as you did). I reverted it in 934df1c5a48dfcb07b432952b6b04a4bebb168fb could you please check if it works now?

**Comment by markus2330** [comment]
To really solve it, there should be a cmake check for qt version >5.4.2 (since then -fPIE is not allowed anymore, see [here](http://code.qt.io/cgit/qt/qtbase.git/plain/dist/changes-5.4.2)).

**Comment by beku** [comment]
-fPIE occurs only in src/tools/qt-gui

find /var/tmp/build-root/openSUSE_Factory-x86_64/home/abuild/rpmbuild/BUILD/elektra-150819.004342git4133dc02/ | xargs grep PIE 2>/dev/null
/var/tmp/build-root/openSUSE_Factory-x86_64/home/abuild/rpmbuild/BUILD/elektra-150819.004342git4133dc02/build/src/tools/qt-gui/CMakeFiles/qt-gui.dir/flags.make:CXX_FLAGS = -fPIC -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -std=c++98  -Wno-deprecated-declarations  -Wstrict-null-sentinel -Wno-missing-field-initializers -Wold-style-cast -Woverloaded-virtual  -Wsign-promo  -Wno-long-long -pedantic -Wno-variadic-macros -Wall -Wextra -Wno-overlength-strings -Wsign-compare -Wfloat-equal -Wformat-security -Wshadow -Wcomments -Wtrigraphs -Wundef -Wuninitialized -Winit-self -Wmaybe-uninitialized -O3 -DNDEBUG -fPIE -I/home/abuild/rpmbuild/BUILD/elektra-150819.004342git4133dc02/build/src/tools/qt-gui -I/home/abuild/rpmbuild/BUILD/elektra-150819.004342git4133dc02/src/tools/qt-gui -I/home/abuild/rpmbuild/BUILD/elektra-150819.004342git4133dc02/build/src/include -I/home/abuild/rpmbuild/BUILD/elektra-150819.004342git4133dc02 -I/home/abuild/rpmbuild/BUILD/elektra-150819.004342git4133dc02/src/tools/qt-gui/../../libtools/include -I/home/abuild/rpmbuild/BUILD/elektra-150819.004342git4133dc02/src/tools/qt-gui/../../libtools/include/merging -I/home/abuild/rpmbuild/BUILD/elektra-150819.004342git4133dc02/src/tools/qt-gui/../../libtools/include/helper -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtTest -isystem /home/abuild/rpmbuild/BUILD/elektra-150819.004342git4133dc02/src/tools/qt-gui/src/markdownconverter -I/home/abuild/rpmbuild/BUILD/elektra-150819.004342git4133dc02/src/include -I/home/abuild/rpmbuild/BUILD/elektra-150819.004342git4133dc02/build/src/bindings/cpp/include -I/home/abuild/rpmbuild/BUILD/elektra-150819.004342git4133dc02/src/bindings/cpp/include -I/home/abuild/rpmbuild/BUILD/elektra-150819.004342git4133dc02/build/src/libtools/include -I/home/abuild/rpmbuild/BUILD/elektra-150819.004342git4133dc02/src/libtools/include   
Übereinstimmungen in Binärdatei /var/tmp/build-root/openSUSE_Factory-x86_64/home/abuild/rpmbuild/BUILD/elektra-150819.004342git4133dc02/build/bin/testkdb_nested.

**Comment by beku** [comment]
using cmake-3.3.0 appears to solve the gcc5 -fPIE / Qt5  issue.

Thanks for the cmake hint.
