### ISSUE TITLE
[CM T0] remove VERBOSE

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2313]
The macro VERBOSE and defined(HAVE_STDIO_H) does not make sense with the new logger anymore. These parts should be removed. (If there are printf inside, they should be ported to the new logger.)

**Comment by kerschy** [comment]
I would like to do this as my first issue.

**Comment by markus2330** [comment]
Thank you for working on this!

**Comment by flo91** [comment]
Ok, thanks for clarifying that!
If `stdio.h` is needed, e.g. for `snprintf`, should it just be included without checking if it's defined?

For example in `src/libs/elektra/keyset.c` there is the code:
```c
#if defined(HAVE_STDIO_H)
#include <stdio.h>
#endif
```

Should the first and last line get removed, so that just the `#include` statement remains?
```c
#include <stdio.h>
```

**Comment by markus2330** [comment]
> If stdio.h is needed, e.g. for snprintf or file-operations like fopen, should it just be included without checking if it's defined?

Yes.

> Should the first and last line get removed, so that just the #include statement remains?

Exactly!

**Comment by markus2330** [comment]
There are still a few leftovers:

```
src/bindings/cpp/include/kdbcontext.hpp:#if DEBUG && VERBOSE
src/bindings/cpp/include/kdbcontext.hpp:#if DEBUG && VERBOSE
src/bindings/cpp/include/kdbcontext.hpp:#if DEBUG && VERBOSE
src/bindings/cpp/include/kdbcontext.hpp:#if DEBUG && VERBOSE
src/bindings/cpp/include/kdbcontext.hpp:#if DEBUG && VERBOSE
src/bindings/intercept/env/tests/test_fork.cpp:#if VERBOSE
src/bindings/intercept/env/tests/test_fork.cpp:#if VERBOSE
src/libs/elektra/mount.c:#if DEBUG && VERBOSE
src/libs/elektra/split.c:#if VERBOSE && defined(HAVE_STDIO_H)
src/libs/elektra/split.c:#if DEBUG && VERBOSE
src/libs/elektra/split.c:#if DEBUG && VERBOSE
src/libs/elektra/split.c:#if DEBUG && VERBOSE
src/libs/elektra/split.c:#if DEBUG && VERBOSE
src/libs/elektra/split.c:#if DEBUG && VERBOSE
src/libs/elektra/split.c:#if DEBUG && VERBOSE
src/libs/elektra/split.c:#if DEBUG && VERBOSE
src/libs/elektra/kdb.c:#if VERBOSE && DEBUG
src/libs/elektra/kdb.c:#if DEBUG && VERBOSE
src/libs/elektra/trie.c:#if VERBOSE && defined(HAVE_STDIO_H)
src/include/kdbconfig.h.in:#define VERBOSE 0
src/bindings/cpp/include/kdbvalue.hpp:#define VERBOSE 0
src/bindings/cpp/include/kdbvalue.hpp:#if DEBUG && VERBOSE
src/bindings/cpp/include/kdbvalue.hpp:#if DEBUG && VERBOSE
src/bindings/cpp/include/kdbvalue.hpp:#if DEBUG && VERBOSE
src/bindings/cpp/include/kdbvalue.hpp:#if DEBUG && VERBOSE
src/plugins/curlget/curlget.c:#if VERBOSE
src/plugins/curlget/curlget.c:#if VERBOSE
src/tools/qt-gui/src/treeviewmodel.cpp:#include <kdbconfig.h> // for DEBUG and VERBOSE
src/tools/qt-gui/src/treeviewmodel.cpp:#if DEBUG && VERBOSE
src/tools/qt-gui/src/treeviewmodel.cpp:#if DEBUG && VERBOSE
src/tools/qt-gui/src/treeviewmodel.cpp:#if DEBUG && VERBOSE
```

**Comment by mandoway** [comment]
[CM T0]
My colleague @Gratla and I want to work on this issue.

I found the following occurrences in the source code:  
```
Targets
    Occurrences of '#if.*(VERBOSE|defined\(HAVE_STDIO_H\))' in Directory \\wsl$\Ubuntu\home\markus\libelektra\src
Found Occurrences in Directory \\wsl$\Ubuntu\home\markus\libelektra\src  (33 usages found)
    Unclassified  (33 usages found)
        libelektra  (33 usages found)
            src\bindings\cpp\include  (9 usages found)
                kdbcontext.hpp  (5 usages found)
                    107 #if DEBUG && VERBOSE
                    357 #if DEBUG && VERBOSE
                    378 #if DEBUG && VERBOSE
                    431 #if DEBUG && VERBOSE
                    440 #if DEBUG && VERBOSE
                kdbvalue.hpp  (4 usages found)
                    682 #if DEBUG && VERBOSE
                    704 #if DEBUG && VERBOSE
                    721 #if DEBUG && VERBOSE
                    757 #if DEBUG && VERBOSE
            src\bindings\intercept\env\tests  (2 usages found)
                test_fork.cpp  (2 usages found)
                    26 #if VERBOSE
                    36 #if VERBOSE
            src\libs\elektra  (17 usages found)
                kdb.c  (3 usages found)
                    14 #if DEBUG && defined(HAVE_STDIO_H)
                    1573 #if VERBOSE && DEBUG
                    1651 #if DEBUG && VERBOSE
                keyset.c  (1 usage found)
                    15 #if defined(HAVE_STDIO_H)
                keyvalue.c  (1 usage found)
                    26 #if DEBUG && defined(HAVE_STDIO_H)
                mount.c  (2 usages found)
                    13 #if DEBUG && defined(HAVE_STDIO_H)
                    395 #if DEBUG && VERBOSE
                plugin.c  (1 usage found)
                    13 #if DEBUG && defined(HAVE_STDIO_H)
                split.c  (8 usages found)
                    13 #if VERBOSE && defined(HAVE_STDIO_H)
                    316 #if DEBUG && VERBOSE
                    321 #if DEBUG && VERBOSE
                    326 #if DEBUG && VERBOSE
                    335 #if DEBUG && VERBOSE
                    343 #if DEBUG && VERBOSE
                    422 #if DEBUG && VERBOSE
                    603 #if DEBUG && VERBOSE
                trie.c  (1 usage found)
                    13 #if VERBOSE && defined(HAVE_STDIO_H)
            src\plugins\curlget  (2 usages found)
                curlget.c  (2 usages found)
                    493 #if VERBOSE
                    777 #if VERBOSE
            src\tools\qt-gui\src  (3 usages found)
                treeviewmodel.cpp  (3 usages found)
                    568 #if DEBUG && VERBOSE
                    632 #if DEBUG && VERBOSE
                    644 #if DEBUG && VERBOSE

```

There are different types of occurrences:
1. In a condition additionally to DEBUG:
    - I assume VERBOSE or defined(..) should be simply removed
2. A condition with only VERBOSE and/or defined(..)
    - Should the condition be removed with the statement remaining?
    - Should the condition and the statement be removed?
    - Should the condition change to a new value? (should this be the port to the new logger mentioned in the original issue?)

How exactly should we port the `printf` statements to the new logger?
e.g. from src/libs/elektra/split.c
```
#if DEBUG && VERBOSE
	printf (" with parent %s\n", keyName (parentKey));
#endif
```
Should we replace the `printf` with a kdblogger call?

**Comment by kodebach** [comment]
> How exactly should we port the `printf` statements to the new logger? e.g. from src/libs/elektra/split.c
> 
> ```
> #if DEBUG && VERBOSE
> 	printf (" with parent %s\n", keyName (parentKey));
> #endif
> ```
> 
> Should we replace the `printf` with a kdblogger call?

I would replace it like this.

```c
ELEKTRA_LOG_DEBUG (" with parent %s\n", keyName (parentKey));
```

Notice, that a `#if DEBUG` around a log statement (like these `printf`) is also nonsensical. `ELEKTRA_LOG_DEBUG` is enabled if `DEBUG` is active and does nothing otherwise.

https://github.com/ElektraInitiative/libelektra/blob/ac45b8b11e0915e5d47d3420b9a2766d1b831ba7/src/include/kdblogger.h#L69-L79

> In a condition additionally to DEBUG:
> * I assume VERBOSE or defined(..) should be simply removed

Correct. Also if the remaining `#if DEBUG` contains only a `printf` it should be replaced by a `ELEKTRA_LOG_DEBUG` like above. In fact `printf` statements should exist almost only in tests, examples, etc., but not library or plugin code. In any case `printf` should never be used for logging.

> A condition with only VERBOSE and/or defined(..)
> * Should the condition be removed with the statement remaining?
> * Should the condition and the statement be removed?
> * Should the condition change to a new value? (should this be the port to the new logger mentioned in the original issue?)

That depends on what is contained within the `#if`.

- If the `#if` contains only `printf` then the whole `#if` should be replaced by a logger statement like in the example above.
- If there is other code its more difficult to say and we need to consider each case separately. Possibly replacing `VERBOSE` with `DEBUG` is an option, but I can't say for sure.

**Comment by Gratla** [comment]
Ok, thank you for the information!
How do we know, what we need to do with the remaining VERBOSE statements which do not contain printf?
Are there any rules or do we need to contact you for every occurence?

**Comment by kodebach** [comment]
When you create the PR, just fix what you know. Where you are unsure, either include a change in the PR and we will review it, or if you don't know what to do at all, just ask.
