### ISSUE TITLE
Test Elektra on BSD Based OS

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2318]
# Issue Description

It would make sense to compile and test Elektra on one or more [BSD based operating system](https://en.wikipedia.org/wiki/Comparison_of_BSD_operating_systems).

# Possible Options

The following CI services provide at least support for FreeBSD:

- [Cirrus CI](https://cirrus-ci.org)
- [builds.sr.ht](https://builds.sr.ht)

. Both of these CI services are free (for open source projects).

**Comment by kodebach** [comment]
Cirrus CI also allows Windows builds, which would be useful once #2303 is completed.
It also uses the new [Github Checks API](https://developer.github.com/changes/2018-05-07-new-checks-api-public-beta/) which can produce much more detailed results. Though I am not sure how much of that is already supported.

**Comment by sanssecours** [comment]
Yep, I also think that Cirrus CI seems to be an interesting option for an additional CI system. I already created a basic [configuration file for Cirrus CI](https://github.com/sanssecours/elektra/blob/🌤/.cirrus.yml) in my fork of Elektra. The first builds of the configuration already show [promising results](https://cirrus-ci.com/github/sanssecours/elektra).

**Comment by markus2330** [comment]
Thank you both for investigating new CI options!

Windows builds can already successfully be done with mingw, so #2303 is not a blocker for this.

**Comment by markus2330** [comment]
Trying out https://builds.sr.ht/ would also be interesting.
