### ISSUE TITLE
MemCheck: fix valgrind tests for ENABLE_DEBUG=OFF

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#2320]
As mentioned in #2309, we are currently running memory checks with valgrind only for targets with the CMake option `ENABLE_DEBUG=ON`.

It might be desirable to make it work with `ENABLE_DEBUG=OFF`. It _might_ be enough to just fix the valgrind suppressions.

**Comment by markus2330** [comment]
Thank you for reporting!

**Comment by markus2330** [comment]
In 51734a5cca0f83f44457887508bc8f4d27dcd6cf I check if the problem still occurs in buster.
