### ISSUE TITLE
KDB: Installed Version of KDB Tool Fails to Load Resolver on FreeBSD

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2321]
# Steps to Reproduce the Problem

1. Install Elektra on FreeBSD:

   ```sh
   mkdir build && cd build
   cmake -GNinja ..
   ninja
   ninja install
   ```

2. Run the KDB tool:

   ```sh
   kdb
   ``` 

# Expected Result

The tool prints a short usage message and a list of available commands.

# Actual Result

The command prints the following output:

```
Usage: kdb <command> [args]
kdb is a program to manage Elektra's key database.
Please run a command with -H or --help as args to show a help text for
a specific command.
Known commands are:
Sorry, I have a severe problem, it seems like I am not installed correctly!
kdbOpen() failed with the info:
 Sorry, 1 warning was issued ;(
 Warning (#1):
	Description: 
could not load module, dlopen failed
	Ingroup: 
modules
	Module: 
dl
	At: 
../src/libs/loader/dl.c:89
	Reason: 
of module: libelektra-resolver.so, because: Shared object "libelektra-resolver.so" not found, required by "kdb"
	Mountpoint: 
	Configfile: 
Sorry, the error (#40) occurred ;(
Description: 
failed to open default backend (see warnings for more information)
Reason: 
could not open default backend
Ingroup: 
kdb
Module: 
At: 
../src/libs/elektra/kdb.c:287
Mountpoint: 
Configfile: 
Please report the issue at https://issues.libelektra.org/
Exit status: 8
```

.

# System Information

- Elektra Version: `master`
- FreeBSD 11.2

# Further Log Files and Output

- [Cirrus CI Build](https://cirrus-ci.com/task/5644957793648640)

**Comment by markus2330** [comment]
Thank you for reporting the problem!

Most likely it is a RPATH problem (see doc/COMPILE.md). Passing `-DTARGET_PLUGIN_FOLDER="" -DCMAKE_SKIP_INSTALL_RPATH=ON` to cmake should be enough. Then `kdb run_all` should hopefully work.

**Comment by sanssecours** [comment]
Thank you for the quick response. The additional CMake options did indeed solve the problem.
