### ISSUE TITLE
Network Plugin: Unit Test Fails on FreeBSD

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2322]
# Steps to Reproduce the Problem

1. Build Elektra
2. Run `testmod_network`

# Expected Result

The test `testmod_network` runs without any problems.

# Actual Result

The test prints the following error message:

```
NETWORK   TESTS
===============
../src/plugins/network/../ipaddr/test_ipaddr.h:45: error in testIP: validation of IP address “localhost” returned -1 instead of 1
../src/plugins/network/../ipaddr/test_ipaddr.h:45: error in testIP: validation of IP address “localhost” returned -1 instead of 1
testmod_network Results: 2100 Tests done — 2 errors.
error: testmod_network
```

# System Information

- Elektra Version: `master`
- FreeBSD 11.2

# Further Log Files and Output

- [Cirrus Ci build](https://cirrus-ci.com/task/5666837867003904)

**Comment by markus2330** [comment]
Thank you for reporting this problem!

Is "localhost" in /etc/hosts? Maybe we should remove this test?

**Comment by sanssecours** [comment]
> Is "localhost" in /etc/hosts?

According to [this Cirrus build](https://cirrus-ci.com/task/5722080373899264): Nope.

> Maybe we should remove this test?

That sounds reasonable. Maybe we could include a Markdown Shell Recorder test that checks `/etc/hosts` before it tries to resolve `localhost` instead.

**Comment by markus2330** [comment]
Thank you, I like your suggestion.

**Comment by markus2330** [comment]
@sanssecours thank you for fixing! Is anything else left over here?

**Comment by sanssecours** [comment]
I do not think so.
