### ISSUE TITLE
IO GLIB: Binding Fails to Compile on macOS

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2328]
# Steps to Reproduce the Problem

1. Install GLIB: 

   ```sh
   brew install glib
   ```

2. Generate the build system:

   ```sh
   mkdir build
   cd build
   cmake -GNinja -DBINDINGS=ALL ..
   ```

3. Build Elektra:

   ```sh
   ninja
   ```

# Expected Result

The last command should build Elektra without any problems.

# Actual Result

The linking step of `libelektra-io-glib` fails:

```
FAILED: lib/libelektra-io-glib.dylib
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -std=gnu99  -Wno-deprecated-declarations  -Wstrict-prototypes  -Wno-long-long -Wpedantic -Wno-variadic-macros -Wall -Wextra -Wno-overlength-strings -Wsign-compare -Wfloat-equal -Wformat -Wformat-security -Wshadow -Wcomments -Wtrigraphs -Wundef -Wuninitialized -Winit-self -Wsign-compare -Wfloat-equal -O2 -g -DNDEBUG  -dynamiclib -Wl,-headerpad_max_install_names  -o lib/libelektra-io-glib.dylib -install_name @rpath/libelektra-io-glib.dylib src/bindings/io/glib/CMakeFiles/elektra-io-glib.dir/io_glib.c.o  -Wl,-rpath,"/Users/rene/Documents/University/Master Thesis/Configuration Parsing/Source/Elektra/build/lib" lib/libelektra-io.0.8.25.dylib -lglib-2.0 -lintl lib/libelektra-kdb.0.8.25.dylib lib/libelektra-invoke.0.8.25.dylib lib/libelektra-core.0.8.25.dylib lib/libelektra.0.8.25.dylib && :
ld: library not found for -lintl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[601/892] Building CXX object src/bindings/cpp...xtual_basic.dir/testcpp_contextual_basic.cpp.o
warning: unknown warning option '-Wno-self-assign-overloaded'; did you mean '-Wno-self-assign-field'? [-Wunknown-warning-option]
1 warning generated.
```

.

# System Information

- Elektra Version: `master`
- macOS `10.14.2`

# Further Log Files and Output

- [Travis build job](https://travis-ci.org/ElektraInitiative/libelektra/jobs/482933203)

**Comment by markus2330** [comment]
Thank you for reporting this problem!

Does maybe "brew install gettext" fix the problem?

https://stackoverflow.com/questions/21370363/link-error-installing-rcpp-library-not-found-for-lintl

**Comment by sanssecours** [comment]
> Does maybe "brew install gettext" fix the problem?

Not as far as I can tell. I already installed `gettext` (via Homebrew) before I opened this issue:

```sh
brew install gettext
#> Warning: gettext 0.19.8.1 is already installed and up-to-date
#> To reinstall 0.19.8.1, run `brew reinstall gettext` 
```

.

**Comment by sanssecours** [comment]
> Do you know which packages were upgraded since it does not work anymore?

Nope. To me it looks like the base macOS images just contain more packages out of the box. For example, until very recently [Xerces and GLIB were not part of the base systems](https://travis-ci.org/ElektraInitiative/libelektra/jobs/482933196).

**Comment by markus2330** [comment]
So the problem is only caused because now glib adds a binding which before was not built and tested?

@waht Do you have an idea?

Otherwise we maybe simply disable the binding for Mac OS X?

**Comment by sanssecours** [comment]
> So the problem is only caused because now glib adds a binding which before was not built and tested?

As far as I can tell, yes.
