### ISSUE TITLE
Create Tutorial for End Users

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2332]
The tutorial should explain, based on the example of LCDproc, how an application (LCDproc) can be configured with Elektra. Following ways should be part of the tutorial:

- [ ] "kdb editor"
- [ ] "kdb set"
- [ ] "kdb qt-gui" (as embedded video?)
- [ ] "kdb run-web" (as embedded video?)

What the tutorial describes should be useful (LCDproc users might actually want to reconfigure as described). Ideally, all changes together make some sense. Quirks should not be described, but instead issues should be opened describing what did not work.

Target Audience: People that never heard of Elektra.

The tutorial should also explain how to introspect the specification (e.g. to find out of which type a configuration setting is).

Please use terminology from ./doc/help/elektra-glossary.md

Note: https://www.libelektra.org/news/elektrify-lcdproc is basically the list of promises we made.

Further input of what the tutorial should contain is very much welcomed.

@Piankero If anything is unclear, please ask here.

**Comment by markus2330** [comment]
Any progress here?

**Comment by Piankero** [comment]
Will be done from Sunday to Tuesday :)

**Comment by Piankero** [comment]
As of now I can only write a useful tutorial for `kdb set` and `kdb editor` as both available guis do not integrate with specifications very well and would just confuse users when they use it in my opinion. 
I linked all issues above.
I will write the first version tomorrow for you to have a review on.

**Comment by Piankero** [comment]
The first version is available in the PR: https://github.com/ElektraInitiative/lcdproc/pull/5

Unfortunately the `kdb editor` is also not useable because it cannot update any configuration setting without failing or even breaking the configuration

**Comment by Piankero** [comment]
This was implemented and is finished
