### ISSUE TITLE
Improve Error Messages

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2333]
Currently, error messages are not always consistent and not always user friendly. The error framework and messages should be reworked to reach better usability.

Goals:

- [ ] Tutorial of how to use Elektra's error messages.
- [X] Error message guidelines
- [X] API users should get clear information what to do with an error (try kdbSet() again, conflict: do kdbGet() again, try kdbSet() after fixing data, ...)
- [x] End users should not be confused by wrong/misleading/too much information #1789
- [x] Modularity of error messages (not everything in one file?)
- [X] Plugins checking the same things, should yield the same errors (consistency)
- [x] also allow Java plugins to yield error messages
- [x] Rust error messages

**Comment by Piankero** [comment]
I think we can close this ticket?

**Comment by markus2330** [comment]
Not all the goals have been reached yet, especially docu is missing.

**Comment by Piankero** [comment]
This issue is unrelated to visible error messages and is primarily focused towards docu or developer specific tasks.
As discussed in the Elektra meeting I may unassign myself.

**Comment by markus2330** [comment]
@Piankero this is the meta-issue for your whole work. Open is only a tutorial how to use error messages. This should be definitely written to complete your work.

**Comment by markus2330** [comment]
Error message system was improved, unfortunately Tutorial is still missing.
