### ISSUE TITLE
Make reformating easier

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2336]
The jenkins buildserver runs tests/shell/check_formatting.sh at an early stage but:

- [ ] it might not run all of the formatting checks (cmake-format or shfmt might not be installed)
- [ ] it does not give help how to apply this patch locally
- [ ] it does not give help how to run the checks locally

**Comment by kodebach** [comment]
We could set up a [Probot instance](https://probot.github.io/) on our own server. Probot could react to pull requests similarly to our CI systems. However, Probot would just run our formatting check and in case something is wrong report that using the Checks API. It should also be possible to create a button for automatically reformatting the code in the details tab of the check run.

Alternatively we could use [Github Actions](https://developer.github.com/actions/) which is currently in beta. They are basically Github's native replacement for Probot. I didn't find an example, but at least in theory it should be possible to automatically reformat all commits pushed to the repository. In future, it should also be possible to use the Checks API like described above, however, currently only `push` events are supported for public repositories.

Both solutions would also eliminate any possible version mismatches of our formatting tools. They would however introduce additional commits, every time something has to be reformatted, so developers should still try to format everything correctly.

Both Github Actions and Probot could be used for many other things. e.g. enforcing the changes to the release notes, automatically labeling PRs or Issues, enforcing certain rules for PR names and commit message, etc.

**Comment by markus2330** [comment]
Thank you for looking into it!
