### ISSUE TITLE
highlevel: header file names

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2344]
Currently, we install the following files:
```
usr/include/elektra/elektra.h
usr/include/elektra/errors.h
usr/include/elektra/types.h
usr/include/elektra/errorcodes.h
usr/include/elektra/conversion.h
```

Thus we usually recommend to put usr/include/elektra into the include path, errors.h might clash with other header files.

We should either:

- implement #817, or
- move them to usr/include/elektra/elektra/errors.h

**Comment by kodebach** [comment]
> usr/include/elektra/elektra/errors.h

That was the intended path. I will fix the CMake configuration.

**Comment by markus2330** [comment]
Thank you!

Please

- also move the header files in the source repo in a subdir, like done with kdbio.
- also fix the installation of the files in the debian branch (otherwise master will fail to build).
- build and run examples/highlevel on the buildserver, so that we can be sure it actually works*.

*I currently get 
```
/usr/include/elektra/elektra.h:12:27: fatal error: elektra/error.h: No such file or directory
 #include <elektra/error.h>
```

**Comment by markus2330** [comment]
Any progress here? I would need the fix in able to test the high-level API.

**Comment by kodebach** [comment]
> Any progress here? I would need the fix to be able to test the high-level API.

I just created the PR.
