### ISSUE TITLE
Small change to elektraGetOpts

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#2361]
Currently the primary function of libopts has this signature:
```c
int elektraGetOpts (KeySet * ks, int argc, const char ** argv, const char ** envp, Key * errorKey)
```
Also currently `errorKey` can be any Key whatsoever, because it is only used for error reporting (and the `posixly` metadata). If we instead also used it as a parent key, i.e. we ignore any key in `ks` which is not below `errorKey`, we could get rid of the requirement to pass only the specification for the currently running application. Which is why we currently recommend using `ksCut`. We should probably also rename the parameter to `parentKey`.

Additionally I propose accept `parentKey`s in any namespace and turn the Key into a spec-Key internally for filtering automatically.

The current example (without error/help handling):
```c
Key * parentKey = keyNew ("/sw/org/example/#0/current", KEY_END);
KDB * kdb = kdbOpen (parentKey);
KeySet * ks = ksNew (0, KS_END);
kdbGet (kdb, ks, parentKey);
KeySet * spec = ksCut (ks, parentKey);
int result = elektraGetOpts (spec, argc, argv, (const char **) environ, parentKey);
ksAppend (ks, spec);
ksDel (spec);
```
would simply turn into:
```c
Key * parentKey = keyNew ("/sw/org/example/#0/current", KEY_END);
KDB * kdb = kdbOpen (parentKey);
KeySet * ks = ksNew (0, KS_END);
kdbGet (kdb, ks, parentKey);
int result = elektraGetOpts (spec, argc, argv, (const char **) environ, parentKey);
```

Although this isn't much shorter, it would be probably be much quicker in most cases, because `ksAppend` is not very well optimized at the moment.

@markus2330 If we do implement this, we should probably do it before the next release.

**Comment by markus2330** [comment]
Thank you, I like the proposal very much! As it is only an extension, and not an incompatible API change, it is not absolutely necessary to have it before the release.

> it would be probably be much quicker in most cases

The important thing is that we can optimize it internally, without bothering users of Elektra. To see if "ksAppend" or "ksCut" is an actual bottleneck, we would need a benchmark, though. But it is good if we do the "ksCut" within the API and do not require Elektra's users to do it.
