### ISSUE TITLE
python3: dup() for Key and KeySet returns wrong type

### ISSUE THREAD

**Issue by pinotree** [ElektraInitiative/libelektra#237]
The `dup()` implementations for `Key` and `KeySet` in the python3 binding returns the raw Swig type, so it is a different type than the object they are duplicating, and thus not comparable.

See for example for `Key`:
```
$ python3
Python 3.4.3+ (default, Jun  2 2015, 14:09:35) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kdb
>>> key1 = kdb.Key("user/key1", kdb.KEY_VALUE, "some_value")
>>> key1
<kdb.Key; proxy of <Swig Object of type 'kdb::Key *' at 0x7fbcc3224c00> >
>>> key2 = key1.dup()
>>> key2
<Swig Object of type 'ckdb::Key *' at 0x7fbcc3224e40>
```
and for `KeySet`:
```
$ python3
Python 3.4.3+ (default, Jun  2 2015, 14:09:35) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kdb
>>> ks1 = kdb.KeySet(100, kdb.Key("user/key1"), kdb.Key("user/key2"), kdb.Key("user/key3"))
>>> ks1
<kdb.KeySet; proxy of <Swig Object of type 'kdb::KeySet *' at 0x7fe145eb5de0> >
>>> ks2 = ks1.dup()
>>> ks2
<Swig Object of type 'ckdb::KeySet *' at 0x7fe145eb5d50>
```

This also causes the `example_key.py` example to fail:
```
$ python3 example_key.py
Key1 name="user/key1" value="some_value"

Every Key has properties. Some are read only, some are read+write.
Properties of Key1:
  key1.name     = "user/key1"
  key1.value    = "some_value"
  key1.basename = "key1"
  key1.fullname = "user/key1"

Key1 is now binary: True

Traceback (most recent call last):
  File "example_key.py", line 19, in <module>
    key2 = kdb.Key(key1.dup())
  File "/usr/lib/python3/dist-packages/kdb.py", line 830, in __init__
    _kdb.Key_swiginit(self,_kdb.new_Key(*args))
TypeError: in method 'new_Key', argument 1 of type 'char const *'
```

**Comment by pinotree** [comment]
Forgot to add: this happens with elektra 0.8.12.

**Comment by manuelm** [comment]
Which SWIG version?

**Comment by pinotree** [comment]
> Which SWIG version?

3.0.2.

**Comment by markus2330** [comment]
I also could reproduce it with python 2.7.9 (SWIG Version 3.0.2)

**Comment by manuelm** [comment]
Took a quick look. dup() is from the c-api and shouldn't be used at all. Just use constructor syntax.

#244 removes the dup call from examples and adds support for pythons copy module for the sake of completeness.

**Comment by markus2330** [comment]
there are two ways of copying: a new reference and a new duplicate

Could you please mark both scenarios in the example?

**Comment by manuelm** [comment]
My origin comment 20 days ago and the pull request is wrong. So please ignore all my comments up to now.

This bug has been introduced with the KEY_FLAGS constructor rewrite and I'll add a test case for it.

There are two ways to solve this:
1) adding ckdb::Key* as SWIG output parameter and convert everything to kdb::Key. This means SWIG will add glue code to all methods returning ckdb::Key* to instead return kdb::Key. This will make the copy constructor work again. However the API will diverge from the C++ API.
 e.g.
```
# python3 -c 'import kdb; k=kdb.Key("user/foo"); print(type(k)); print(type(k.dup()));'
[old] <class 'kdb.Key'>
[old] <class 'SwigPyObject'>
[new] <class 'kdb.Key'>
[new] <class 'kdb.Key'>
```

2) fixing the copy constructor. Making a copy of a key will still be the same as with the C++ API: `kdb.Key(k.dup())`

Right now I'm in favor of 2 so APIs are in sync. But 1 also makes sense to a certain degree.

Adding support for pythons copy module will be added anyway.
