### ISSUE TITLE
yaypeg test fails

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2371]
## Steps to Reproduce the Problem

Install Elektra and run:

```sh
kdb stash
kdb testmod_yaypeg
```

## Expected Result

Success

## Actual Result

```
Running testmod_yaypeg

[==========] Running 5 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 5 tests from yaypeg
[ RUN      ] yaypeg.basics
/home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA/libelektra/src/plugins/yaypeg/testmod_yaypeg.cpp:73: Failure
Value of: plugin != __null
  Actual: false
Expected: true
Could not open yaypeg plugin
error: testmod_yaypeg
```

## System Information

- Elektra Version: master
- Debian Stretch

**Comment by sanssecours** [comment]
I can not reproduce this bug on [macOS](https://travis-ci.org/ElektraInitiative/libelektra/jobs/489420151#L2851). On [Ubuntu](https://travis-ci.org/sanssecours/elektra/jobs/488906348#L2124) everything seems to be fine too. I tried the following, using the [Docker image for Debian Stretch](https://github.com/ElektraInitiative/libelektra/blob/master/scripts/docker/debian/stretch/Dockerfile), which also worked:

```sh
mkdir build
cd build
cmake -GNinja                                                  \
      -DPLUGINS=ALL                                            \
      -DBINDINGS=cpp                                           \
      -DCMAKE_INSTALL_PREFIX="/home/jenkins/workspace/install" \
      -DINSTALL_SYSTEM_FILES=OFF                               \
      ..
ninja install
cd /home/jenkins/workspace/install/bin
./kdb testmod_yaypeg
#> [==========] Running 5 tests from 1 test case.
#> [----------] Global test environment set-up.
#> [----------] 5 tests from yaypeg
#> [ RUN      ] yaypeg.basics
#> [       OK ] yaypeg.basics (6 ms)
#> [ RUN      ] yaypeg.empty
#> [       OK ] yaypeg.empty (10 ms)
#> [ RUN      ] yaypeg.scalar
#> [       OK ] yaypeg.scalar (22 ms)
#> [ RUN      ] yaypeg.list
#> [       OK ] yaypeg.list (14 ms)
#> [ RUN      ] yaypeg.map
#> [       OK ] yaypeg.map (27 ms)
#> [----------] 5 tests from yaypeg (80 ms total)
#> 
#> [----------] Global test environment tear-down
#> [==========] 5 tests from 1 test case ran. (80 ms total)
#> [  PASSED  ] 5 tests.
```

.

**Comment by markus2330** [comment]
Is it possible that the plugin simply is not installed? (#2353)

**Comment by sanssecours** [comment]
That might be possible. At least a [message in a recent build of PR #2369](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2369/5/pipeline/#step-1508-log-808) indicates that there might be problems in the package build step concerning the YAy PEG plugin:

```
dh_install: usr/lib/x86_64-linux-gnu/elektra4/libelektra-yaypeg.so exists in debian/tmp but is not installed to anywhere
```

. Jenkins also reports the [same message for the `master` branch](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/389/pipeline/#step-1479-log-423).

**Comment by markus2330** [comment]
Thank you, the test case passes now!
