### ISSUE TITLE
kdb run_all does not execute external tests

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2372]
## Steps to Reproduce the Problem

Install Elektra and run:

```sh
kdb stash
kdb run_all
```

## Expected Result

It runs all test cases.

## Actual Result

```
Running check_spec
Running external_check*

The command kdb-full external_check* is not known
[...]
error: external_check*


Following test cases failed: 
testmod_lua
testmod_network
testmod_yaypeg
external_check*

run_all RESULTS: 146 test(s) done 4 error(s).
```

## System Information

- Elektra Version: master
- Debian Stretch

## Further Log Files and Output

`kdb list-tools | grep external`

has no output, so it seems like the external_check is not installed (is not part of the Debian package).

So there are actually two problems:

- [ ] that the external test case is not installed
- [ ] the failures in the case if external test cases are not installed

Why not simply naming it also check_external_... Then e63db7da06154094130dd0c33a56715ceb4f0122 would not have been necessary, which would avoid the second problem.

**Comment by kodebach** [comment]
Is there any reason we aren't using CPack for building the debian package? That way `make install` would always use the same files as the debian package.

**Comment by markus2330** [comment]
We used CPack a long time ago. It might still work, the code is still there: cmake/ElektraPackaging.cmake

Afaik CPack cannot produce modular packages (everything is put into one package) and this package would be huge with a ridiculous amount of dependencies. E.g. elektra-dbg alone is > 70 MB, which is enormous compared to the ~100k base libraries.

I already have many installations where only parts of Elektra is installed. Actually, I only have few places where everything is installed.

**Comment by kodebach** [comment]
It should be possible to use [CPack components](https://cmake.org/cmake/help/latest/module/CPackComponent.html) to produce multiple packages. Might be worth investigating for #2353.
