### ISSUE TITLE
Add file + line numbers on failures

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2373]
## Steps to Reproduce the Problem

Run an application that uses the high-level API but there is some specification mismatch.

## Expected Result

Output of where the error occurred.

## Actual Result

```sh
./application
ERROR: The key '/sw/example/highlevel/#0/current/mystring' has the wrong type (expected 'string' but got '(null)').
```

## System Information

- Elektra Version: master

## Implementation details

As most of the API (in particular elektraGet*) are macros, it should be easy to get file + line number information.

Maybe we should always turn on our logger (silent per default) and use our logger to output these errors.

**Comment by kodebach** [comment]
> As most of the API (in particular elektraGet*) are macros

Actually only `elektraGet` and `elektraSet` which are used together with the code generated tags are exposed to the user as macros. The typed versions (`elektraGetLong` etc.) are normal functions.

Personally I think file+line number is debug information that shouldn't concern the user. The current error message tells the user everything they need to know to fix the error. Developers can simply debug an application, if an error occurs. Alternatively they can log the file and line numbers themselves by using their own macro.

**Comment by markus2330** [comment]
Thank you for the quick response. If they are not macros, it is not feasible anyway.

> Alternatively they can log the file and line numbers themselves by using their own macro.

This approach usually brings a lot of inconsistencies between applications. Something like "etrace", a tool that logs all elektraGet/elektraSet invocations would be handy for end-users to find out about which configuration settings are accessed by an application.
