### ISSUE TITLE
KBD Mount: Command Prints Mountpoints Twice

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2380]
# Steps to Reproduce the Problem

Enter the following commands:

```sh
kdb mount config.ecf user/tests/dump dump
kdb mount config.yaml user/tests/yaml yamlcpp
kdb mount
#> config.ecf on user/tests/dump with name user/tests/dump
#> config.yaml on user/tests/yaml with name user/tests/yaml
kdb mount -1
```

.

# Expected Result

The last command prints the following output:

```
user/tests/dump
user/tests/yaml
```

.

# Actual Result

The command `kdb mount -1` prints the following:

```
user/tests/dump
user/tests/dump
user/tests/yaml
user/tests/yaml
```

.

# System Information

- Elektra Version: master
- macOS `10.14.3`

**Comment by markus2330** [comment]
As written in #1844, we also need regression tests for the `-0` (and `-1`) feature. Or we remove the feature.
