### ISSUE TITLE
kdb stash: does not remove errornous config files

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2386]
# Issue Description

Currently we offer the tool [`kdb stash`](https://www.libelektra.org/manpages/kdb-stash) that, at least  in theory, should backup the current configuration and after that remove all custom configuration values. However, the tool does not remove “broken” configuration data:

```sh
# Add erroneous data
printf 'Error' > "$(kdb file user/tests/error)"
kdb ls user/tests/error
# RET: 5

# Try to remove all configuration data
kdb stash
# RET: 1

# The configuration data still exists
kdb ls user/tests/error
# RET: 5
```

. A command `kdb reset` could get rid of this problem, for example, by removing all mounted configuration files. We have to take proper care to not remove any configuration data used by other configuration tools, such as `/etc/hosts` though.

**Comment by markus2330** [comment]
Thank you for the suggestion!

Why not extend `kdb stash` with this behavior?

**Comment by sanssecours** [comment]
> Why not extend `kdb stash` with this behavior?

That is of course another valid option. The advantage of a new command would be that `kdb reset` does not have to care about a backup at all. We could also just call `kdb reset` in `kdb stash`, just like we do now with `kdb backup`. Anyway, I just want a tool that reverts to the default configuration. If it is called `kdb stash`, `kdb reset` (in my opinion, a better name for the task described above) or `kdb napalm-death`, I do not care.

**Comment by kodebach** [comment]
This would be very useful for testing.

> in my opinion, a better name for the task described above

Yes, `reset` immediately tells me that all my data is gone afterwards.

**Comment by markus2330** [comment]
> Anyway, I just want a tool that reverts to the default configuration.

This is exactly what `kdb stash` should do.

> This would be very useful for testing.

Yes, this was the idea of `kdb stash`.

>  Yes, reset immediately tells me that all my data is gone afterwards.

Which is not a very nice behavior if you are actually also using Elektra on that system. And of course it is the goal that Elektra devs also use Elektra. Thus we should fix `kdb stash`. If there are any other problems in kdb stash, please report them.

To fix the bug described here, I think it would be enough if `kdb stash` removes the files using `rm` instead of `kdb rm -r`. The files are backed-up using `cp` anyway.

**Comment by sanssecours** [comment]
> This is exactly what `kdb stash` should do.

That might be the case. However, I still think the name “stash” does not make that very clear:

> stash1 | staʃ | informal
> verb [with object and adverbial of place]
> **store (something) safely** in a hidden or secret place: their wealth had been stashed away in Swiss 
> banks.

(Source: New Oxford American Dictionary).

>>  Yes, reset immediately tells me that all my data is gone afterwards.

> Which is not a very nice behavior if you are actually also using Elektra on that system.

I do not think that providing a way to get rid of all custom configuration is bad behavior. A lot of tools even show such options quite prominently. For example, the preferences window of Docker Desktop contains a tab “Reset”:

<img width="612" alt="docker" src="https://user-images.githubusercontent.com/691989/52519420-69315e80-2c5b-11e9-9244-8a0793a6d6e2.png">

.

**Comment by kodebach** [comment]
> Thus we should fix `kdb stash`

Like  @sanssecours suggested, I think we should implement `kdb reset` and then change `kdb stash` to basically be `kdb backup && kdb reset`. That fixes `kdb stash` and provides the `kdb reset` option for anyone who doesn't care about a backup.

**Comment by markus2330** [comment]
> store (something) safely in a hidden or secret place

This describes it quite well, doesn't it? The only problem is that it is not "something" but "everything". And that "store" only implies "move" on real objects. The name is taken from git terminology.

Better suggestions are always welcomed.

> I do not think that providing a way to get rid of all custom configuration is bad behavior.

It is not "bad", it is only very against usability. Everything that you remove, format, clear, reset, ... without any way of undo requires a good backup and restore strategy which typical end users often do not have. So if you take usability serious, you try to avoid such functionality (see #898 for how harmful a simple `kdb umount` can be).

**Comment by markus2330** [comment]
I now added `kdb reset` as wished. It needs to be called with `-f` to actually do something to avoid accidental removal of important files.

kdb stash is now essentially kdb backup && kdb reset

If you have some time to test it, now would be a good time.
