### ISSUE TITLE
Documentation: asciinema Recording in ReadMe Unavailable

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2397]
# Issue Description

It seems the asciinema recording in the [main ReadMe file](https://github.com/ElektraInitiative/libelektra#usage) was “archived” (aka. removed). It would make sense to either remove the broken recording:

[![asciicast](https://asciinema.org/a/cantr04assr4jkv8v34uz9b8r.png)](https://asciinema.org/a/cantr04assr4jkv8v34uz9b8r)

or even better, add a new video.

**Comment by markus2330** [comment]
Thank you, I removed it for now. (ca82f499ff99dbdaa536c95770e1f3c9ccc688c7)

It would be great to have a new asciinema recording for the upcoming release.
