### ISSUE TITLE
QT-GUI requires additional packages on linux mint (ubuntu xenial)

### ISSUE THREAD

**Issue by Piankero** [ElektraInitiative/libelektra#2400]
After installing all required modules for the qt-gui and compiling the project, I got the following error message:
```
> kdb qt-gui 
QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:182 Type ExportDialog unavailable
qrc:/qml/ExportDialog.qml:4 Type FileDialog unavailable
qrc:/QtQuick/Dialogs/DefaultFileDialog.qml:45 module "Qt.labs.settings" is not installed
qrc:/QtQuick/Dialogs/DefaultFileDialog.qml:44 module "Qt.labs.folderlistmodel" is not installed
qrc:/QtQuick/Dialogs/DefaultFileDialog.qml:45 module "Qt.labs.settings" is not installed
qrc:/QtQuick/Dialogs/DefaultFileDialog.qml:44 module "Qt.labs.folderlistmodel" is not installed
```
I expected that after compiling and installing all required dependencies, I could immediately start the gui.
To solve the problem I had to execute the following commands:
```
sudo apt-get install qml-module-qt-labs-folderlistmodel
sudo apt-get install qml-module-qt-labs-settings
```
Maybe there could be further checks done in the cmakelists to prevent such additional effort and confusing the user?

I installed qt via 
```
sudo apt-get install qtdeclarative5-dev
sudo apt-get install libqt5svg5-dev
sudo apt-get install discount
```

**System info**

KDB_VERSION: 0.8.25
SO_VERSION: 4

NAME="Linux Mint"
VERSION="18.2 (Sonya)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.2"
VERSION_CODENAME=sonya
UBUNTU_CODENAME=xenial
kernel: 4.15.0-43-generic
This issue was a result of #2332

**Comment by markus2330** [comment]
Thank you for reporting!

The discount should actually be checked by CMake?

The modules are only run-time deps and are not required to be present during compilation. But you are right, it would be nice to also have this information is available via #1016.

I partially fixed the docu in 92768924178120cd61f0a97b6eced29ca103325d but please also make a PR describing  which OS you used (and similar).

**Comment by Piankero** [comment]
> The discount should actually be checked by CMake?
Thats right, I just posted my install process for reproduceablility.

**Comment by markus2330** [comment]
But for reproducibility also OS/versions/... are required.

**Comment by Piankero** [comment]
I updated the description
