### ISSUE TITLE
QT-GUI does not support multiline metadata correctly

### ISSUE THREAD

**Issue by ghost** [ElektraInitiative/libelektra#2405]
Metadata with much text simply gets printed over multiple lines, which results in overlapping text if additional metadata is present below.

![qt-gui-multiline-description](https://user-images.githubusercontent.com/12346621/52593277-d3f3bd00-2e48-11e9-9204-852057c4e022.jpg)

System:

```
qmake --version
#> QMake version 3.0
#> Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu

cat /etc/os-release
#> NAME="Linux Mint"
#> VERSION="18.2 (Sonya)"
#> ID=linuxmint
#> ID_LIKE=ubuntu
#> PRETTY_NAME="Linux Mint 18.2"
#> VERSION_ID="18.2"
#> HOME_URL="http://www.linuxmint.com/"
#> SUPPORT_URL="http://forums.linuxmint.com/"
#> BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
#> VERSION_CODENAME=sonya
#> UBUNTU_CODENAME=xenial
```

#2332

**Comment by markus2330** [comment]
Thank you for reporting!

@0003088 Do you maybe have time to fix this?

**Comment by 0003088** [comment]
This issue looks vaguely familiar, I think I tried to fix this already back in the day (to no avail obviously). I can make a few tests but as far as I see there have been no additions to the QT TableViewColumn type since 2015 https://doc.qt.io/qt-5/qml-qtquick-controls-tableviewcolumn.html

To me it looks like an rendering error in the qt engine itself.

**Comment by markus2330** [comment]
Thank you for looking into it! Is this problem reported in the QT issue tracker?

**Comment by 0003088** [comment]
Doesn't look like it, guess I could file one during the next days. Has this happened with the latest version of QT? Should be 5.12.1.

**Comment by markus2330** [comment]
@Piankero Please tell us the OS and version of QT.

**Comment by Piankero** [comment]
> Please tell us the OS and version of QT.

Updated the description

**Comment by 0003088** [comment]
I looked into this again and it's in fact not a problem with the TableViewColumn, but with the Text delegate. The problem are obviously the newlines, by default Qt just renders them as they are

![qt_gui_overlapping](https://user-images.githubusercontent.com/2543279/52915871-6842a180-32d9-11e9-893a-653709b764f8.png)

There is the possibility to 'elide' them, so only the first line is shown and dots indicate, that something has been left out

![qt_gui_elide](https://user-images.githubusercontent.com/2543279/52915870-6842a180-32d9-11e9-991f-bc834c70b849.png)

Obviously not ideal. It is however supported to check if elide mode is in effect so maybe a solution would be to create a mouse field that is only active if elide is on and displays the whole text on hover? 

BTW I would recommend to update Qt,  5.5 is _very_ old.

**Comment by markus2330** [comment]
@0003088 thank you for looking into it!

>Obviously not ideal. It is however supported to check if elide mode is in effect so maybe a solution would be to create a mouse field that is only active if elide is on and displays the whole text on hover?

Sounds like a good plan! Maybe the text can be done a bit longer before being elided? Or do already two lines create an overlap?

**Comment by 0003088** [comment]
I just realized that I cannot save changes in the metakeys? Is this a known issue? It works if I create a new key, assign it a metakey and synchronize. But if I want to change an existing metakey, the changes are gone after sync/restart.

**Comment by markus2330** [comment]
Thank you for spotting and reporting this problem! No, it is not a known issue, setting meta-data on the commandline works without problems:

```
kdb setmeta user/something abc def
kdb getmeta user/something abc
#> def
kdb setmeta user/something abc def2
kdb getmeta user/something abc
#> def2
```

Maybe the problem is in the 3-way merge, which is currently being reimplemented because of many known problems.

**Comment by markus2330** [comment]
@darddan ping
