### ISSUE TITLE
QT-GUI gives bad error messages if spec plugins reports an error

### ISSUE THREAD

**Issue by Piankero** [ElektraInitiative/libelektra#2406]
When trying to set a key to an invalid value (eg. wrong enum) and pressing the synchronize button in the gui, the error message is not helpful.

Here how it looks in the commandline
```
kdb set '/sw/lcdproc/lcdd/#0/current/curses/background' greeeeen 
#> Using name user/sw/lcdproc/lcdd/#0/current/curses/background
#> The command kdb set failed while accessing the key database with the info:
#> Sorry, the error (#121) occurred ;(
#> Description: validation failed
#> Reason: Validation of key "user/sw/lcdproc/lcdd/#0/current/curses/background" with string "greeeeen" failed.
#> Ingroup: plugin
#> Module: enum
#> At: ....../src/plugins/enum/enum.c:218
#> Mountpoint: user/sw/lcdproc/lcdd/#0/current
#> Configfile: ...../LCDd.conf.25676:1549919217.284067.tmp
```

Here is the error message I receive in the GUI:
![qt-gui-spec-error-message](https://user-images.githubusercontent.com/12346621/52593655-c854c600-2e49-11e9-90a4-3cb60d0c2cb7.png)

#2332

**Comment by markus2330** [comment]
Thank you for finding this tricky problem! I did not know about it.

In which order do you do the `kdb set` and pressing of the synchronization button?

We will improve (rewrite) the 3-way merging soon (), the problem will hopefully fixed with this.
