### ISSUE TITLE
QT-GUI does not correctly update from empty namespaces

### ISSUE THREAD

**Issue by Piankero** [ElektraInitiative/libelektra#2407]
When my spec namespace is empty in the QT-gui and I mount something into the spec namespace, nothing is updated in the gui (even after pressing the refresh button)

**Steps to reproduce:**
Have an empty spec namepsace:
![spec-first](https://user-images.githubusercontent.com/12346621/52594088-e7078c80-2e4a-11e9-988a-7a226efe0995.png)

Mount some specification:
```
sudo kdb mount ..../server/specification/LCDd-spec.ini 'spec/sw/lcdproc/lcdd/#0/current' ni
sudo kdb spec-mount '/sw/lcdproc/lcdd/#0/current
```

Press the refresh button.
There is still no expandable button.

**Expected result:**
![second](https://user-images.githubusercontent.com/12346621/52594207-33eb6300-2e4b-11e9-8fa3-9d55bf2d072d.png)

I only receive the expected result after completely restarting the gui.

#2332

**Comment by markus2330** [comment]
Thank you for reporting this problem!

A notification on /elektra is needed. In this case `KDB` needs to be reopened.

@waht already did this for another application. Maybe you want to help out here?
