### ISSUE TITLE
kdb showmeta

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#2412]
Currently it is quite difficult to list all meta data values of a given key using the `kdb` tool. The best way currently is:

```sh
kdb lsmeta '/some/key' | xargs -I% -n1 sh -c 'printf "% = " && kdb getmeta "/some/key" "%"'
```

I propose we either add a new command `kdb showmeta` or add an option to `kdb lsmeta`, that not only lists the names of the meta keys but also their values.

A good example where this is very useful is the `check/enum` metadata. The comma-separated list version is much nicer to view with `kdb getmeta`, but isn't really how arrays/lists should be done in Elektra. The array version with `check/enum/#` meanwhile is horrible to view using `kdb`.

**Comment by Piankero** [comment]
This is an awesome idea. Usability is not the best with the array notation.

I would suggest that `kdb lsmeta` prints out all values whereas `kdb showmeta` is the current `lsmeta`.
Alternatively maybe something like `kdb lsmeta --values` would also be a possibility

**Comment by markus2330** [comment]
Yes, I agree that a `showmeta` would improve usability.

Although it is actually only an alias for `kdb export <something> ni` (or the command given above)?

**Comment by kodebach** [comment]
> alias for `kdb export <something> ni`

Not quite `kdb export` will also output all keys below `<something>` and their metadata, so there could be quite a lot of unwanted information.

> or the command given above

Of course we could just add the one-liner as an external script, like we do for `kdb stash` and `kdb umount-all`. Although it woudn't be a lot of C++ code either, so it doesn't really matter.

**Comment by markus2330** [comment]
Yes, I am fine with the script or also a new C++ command. Let @Piankero decide what he wants to do.
