### ISSUE TITLE
Highlevel API and enums

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#2413]
Currently the highlevel API has the function `elektraGetEnumInt` and `elektraSetEnumInt`. These functions are essentially equivalent to `elektraGetLong` and `elektraSetLong`, but use `int` instead of `kdb_long_t`.

This means that we either need a plugin that converts the values of keys marked with `type=enum` into integers using the values from `check/enum/#`, or we remove the enum functions from the highlevel API and support enums only through code-generation. 
The code-generation would generate a function that just uses `strcmp` and `if`s to find the integer value from the string.

The plugin seems like the better solution since it could be used without code generation. We could also add a `check/enum/convert` option to disable the conversion, in case somebody needs the string values.

**Comment by kodebach** [comment]
I think the plugin solution wouldn't work, since there is a weird edge case that would make the reverse conversion in `kdbSet` impossible:

```
[some/key]
type = enum
check/enum/convert = 1
check/enum = #1
check/enum/#0 = 1
check/enum/#1 = 0
```

When first setting `some/key` there is no problem. The key wasn't there in the `kdbGet` call, so we won't to any conversion in `kdbSet`. 

But as soon as the key has a value (e.g. `some/key = 1`)  the plugin will convert the string to the integer version in `kdbGet` (now `some/key = 0`). That means in `kdbSet` the plugin should do a reverse conversion (back to `some/key = 1`). But what if we call `kdb set some/key 0`? Should the plugin now do the reverse conversion or not? In other words, did we provide the string or the integer version of the enum to `kdb set`? There is no way for the plugin to know that.

If we only convert back keys that the plugin converted in the first place and that are unchanged,  we have to provide the string version of the enum in `kdbSet` calls and therefore the highlevel API doesn't work.

If we convert back all keys, we have to provide the integer version to `kdbSet` and `kdb set` and only ever see the string versions of the enum values in the mounted files.

---
So unless someone has a solution for this, I will implement it via code generation and remove `elektraGetEnumInt` and `elektraSetEnumInt` from the highlevel API.

**Comment by markus2330** [comment]
Yes, I also think we can remove these functions from the high-level API.

**Comment by kodebach** [comment]
The functions have been removed in #2399.
