### ISSUE TITLE
kdb editor: cannot use dump storage plugin

### ISSUE THREAD

**Issue by Piankero** [ElektraInitiative/libelektra#2416]
## Steps to Reproduce the Problem

Checkout https://github.com/ElektraInitiative/lcdproc/tree/elektra_tutorial
Mount the specification:
```sh
sudo kdb mount '<path_to_repo>/lcdproc-elektra/server/specification/LCDd-spec.ini' 'spec/sw/lcdproc/lcdd/#0/current' ni
sudo kdb spec-mount '/sw/lcdproc/lcdd/#0/current'
```

Set a value and call the editor with the `dump` plugin
```sh
kdb set '/sw/lcdproc/lcdd/#0/current/curses/background' green
kdb editor '/sw/lcdproc/lcdd/#0/current/curses/background
```
Change any value (eg. user/sw/lcdproc/lcdd/#0/current/curses/background^@red^@)

Save the configuration
## Expected Result

The configuration merges correctly.

## Actual Result

```
Sorry, the error (#49) occurred ;(
Description: unknown command detected in dumpfile
Reason: check/enum/#0
Ingroup: plugin
Module: dump
At: .../src/plugins/dump/dump.cpp:191
Mountpoint: /sw/lcdproc/lcdd/#0/current/curses/background
Configfile: /tmp/elektra-test.Dh4bLh
```

#2332

**Comment by markus2330** [comment]
The dump plugin is not suitable for being edited by hand. You need to update the sizes correctly if you change any length.
