### ISSUE TITLE
Improve 3-way merge

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2417]
- [ ] semantic merging
   - [ ] types: if type=float then 0.0 == 0.00
   - [ ] comments
   - [ ] other metadata
- [ ] support for proper merging of arrays and meta-arrays (with line-based merging algorithms)
- [ ] #107 
- [ ] #2406

**Comment by Chemin1** [comment]
I do not have the rights to do so, but I think opening a project for this issue might be a good idea. This way, discussions about various topics like arrays, whitespace and tutorials could be separated and keeping track of the different subtasks were possible in form of different issues.

We have talked about that the merge tool would not profit much from existing diffutils. However, it seems to me that building up on `diff`might be a good starting point. This would quickly solve issues like that inserting a line at the top of the file is recognized as single edit and not edits in all of the following lines. Am I missing something here?

**Comment by markus2330** [comment]
> I do not have the rights to do so

You should have the rights now.

> I think opening a project for this issue might be a good idea

Yes, this is a good idea.

> Am I missing something here?

Of course you can use the diff algorithm for arrays. But to always work on line-based structures (what you automatically would achieve using the line plugin) would be very weak as simple reordering or changes of spaces would already create conflicts.

**Comment by Chemin1** [comment]
In my head everything was about merging files so far. The existing merge tool, however, operates on KeySets (and on their representation in a file only as a consequence) and avoids struggles with different file formats in doing so.
@markus2330 Were you thinking about files aswell or did we have a misunderstanding here?

**Comment by markus2330** [comment]
No, it should always operate on KeySets as this already solves many problems. E.g.:

```ini
key =    value
key2     =   other value
```

```ini

key2     = "other value"

key =  value
```

has identical KeySets.

**Comment by markus2330** [comment]
(Except of meta-data but this would need clever handling by your semantic merge)

**Comment by markus2330** [comment]
@Chemin1 Any progress here? Would be great to see your 3-way merge throughout.

**Comment by Chemin1** [comment]
Unfortunately, not yet. I currently have to spend my evenings with two courses that stretch the semester until middle of September.

**Comment by markus2330** [comment]
I think we can close this for now. #3131 is the only crucial leftover.
