### ISSUE TITLE
type plugin causes failure for specifications

### ISSUE THREAD

**Issue by Piankero** [ElektraInitiative/libelektra#2425]
## Steps to Reproduce the Problem

The following code should work but does not
```sh
sudo kdb mount test.spec spec/tests dump
sudo kdb mount test.conf /tests dump enum type

sudo kdb setmeta spec/tests/abc type enum
sudo kdb setmeta spec/tests/abc check/type enum
sudo kdb setmeta spec/tests/abc 'check/enum/#0' red
sudo kdb setmeta spec/tests/abc 'check/enum/#1' black
sudo kdb setmeta spec/tests/abc 'check/enum/#2' green
sudo kdb setmeta spec/tests/abc 'check/enum/#3' yellow
sudo kdb setmeta spec/tests/abc 'check/enum/#4' blue
sudo kdb setmeta spec/tests/abc 'check/enum/#5' magenta
sudo kdb setmeta spec/tests/abc 'check/enum/#6' cyan
sudo kdb setmeta spec/tests/abc 'check/enum/#7' white

kdb set /tests/abc red
#RET: 0

sudo kdb umount spec/tests
```

## Expected Result

kdb set commands work

## Actual Result

```
sudo kdb set /tests/abc red
#> Sorry, the error (#52) occurred ;(
#> Description: could not type check value of key
#> Reason: The type enum failed to match for system/tests/abc with string: red
#> Ingroup: plugin
#> Module: type
#> At: /media/wespe/extended/repository/myFork-libelektra/src/plugins/type/type.cpp:31
#> Mountpoint: system/tests
#> Configfile: /etc/kdb/test.conf.29332:1550422238.372919.tmp

```

## System Information

KDB_VERSION: 0.8.25
SO_VERSION: 4

NAME="Linux Mint"
VERSION="18.2 (Sonya)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.2"
VERSION_ID="18.2"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sonya
UBUNTU_CODENAME=xenial
kernel = 4.15.0-43-generic

**Comment by markus2330** [comment]
You are mounting enum type to the spec namespace (where they are not needed) but not to the other namespaces (where they would be needed).

So try to use:
```
sudo kdb mount test.spec spec/tests dump
sudo kdb mount test.conf /tests dump enum type
```

Or try spec-mount.

**Comment by Piankero** [comment]
Thank you for the clarification, nontheless the type plugin causes a failure. I updated the example

**Comment by markus2330** [comment]
Ahh, I see what you mean.

Yes, there is no type "enum" known to the "typecheck" plugin.

The typecheck plugin needs to be fixed: It would be enough if it checks for the presence of "enum" meta-data when "type" is "enum".

**Comment by Piankero** [comment]
It was working a few days ago though, was there any code change until then?

**Comment by markus2330** [comment]
What do you mean? git shows you all the code changes.

**Comment by Piankero** [comment]
The same code above worked 2 weeks ago I think, suddenly it does not. Maybe you knew the reason why because I remember that you have worked on something concerning the type plugin. It doesn't matter though for now.

Thanks for the help

**Comment by markus2330** [comment]
As far as I know this never worked.
