### ISSUE TITLE
Highlevel API tests

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#2430]
The highlevel API currently only does some basic tests for each of the supported types.

It would be nice, if we added more tests to `testkdb_highlevel.cpp` (especially for border cases).
For example adding a test that checks that we accept `0` and `65535`, but not `-1` and `65536` for the type `unsigned_short`.

**Comment by markus2330** [comment]
Thank you for creating the issue! It would be great to have the tests for the upcoming release.
