### ISSUE TITLE
Flexible size types in va_list

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#2437]
`keyVInit` and therefore `keyVNew` and `keyNew` (and maybe others) currently use `size_t` for the value size of a key. The C standard doesn't define a fixed size for `size_t`, only that it should be at least 16 bits. This can lead to problems, if a bigger type (e.g. `kdb_unsigned_long_long_t`) is passed without casting, because of the way that some compilers implement `va_list`.

We should change all `va_list` usages to only use our fixed size integer types declared in `kdbtypes.h`.

**Comment by markus2330** [comment]
Thank you for creating the issue!

Yes, other methods are affected, too: e.g. ksNew

**Comment by kodebach** [comment]
`ksNew` is not as big a problem. We do use `size_t`, so the maximum size of a KeySet is implementation/architecture dependent, but it cannot lead to the same kind of bug, because die parameter is declared as `size_t` and not part of a `va_list`.
