### ISSUE TITLE
CMake Sanitizers

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#2444]
On my wild google adventure to find the cause of the current bug in #2344, I stumbled upon https://github.com/arsenm/sanitizers-cmake. This might be a better solution than what we currently use for ASAN.

**Comment by markus2330** [comment]
Thank you for bringing this up!

Does it also solve the LD_LIBRARY_PATH problem you have in #2433?

**Comment by kodebach** [comment]
I doubt it. The problem was that `LD_LIBRARY_PATH` was required because the tests are executed before installing, but it simply wasn't set. That wasn't immediately obvious, however, because it worked in some cases. No idea why...
