### ISSUE TITLE
kdb get -v should also display default values.

### ISSUE THREAD

**Issue by Piankero** [ElektraInitiative/libelektra#2474]
It is beneficial for users to see where a value from `kdb get` actually comes from. This is especially useful when `default` values are taken. 

Unforuntately `kdb get -v` does not indicate anything like that:
```sh
kdb get -v '/sw/lcdproc/lcdd/#0/current/curses/foreground'
#> got 660 keys
#> searching spec/sw/lcdproc/lcdd/#0/current/curses/foreground, found: 
#> spec/sw/lcdproc/lcdd/#0/current/curses/foreground, options: KDB_O_CALLBACK
#> The resulting keyname is /sw/lcdproc/lcdd/#0/current/curses/foreground
#> The resulting value size is 5
#> blue
```

Proposal:
```sh
kdb get -v '/sw/lcdproc/lcdd/#0/current/curses/foreground'
#> got 660 keys
#> searching spec/sw/lcdproc/lcdd/#0/current/curses/foreground, found: 
#> spec/sw/lcdproc/lcdd/#0/current/curses/foreground, options: KDB_O_CALLBACK
#> The key was not found in any other namespace, taking the default from the metadata
#> The resulting keyname is /sw/lcdproc/lcdd/#0/current/curses/foreground
#> The resulting value size is 5
#> blue
```

**Comment by markus2330** [comment]
Thank you for reporting this problem and for propose a solution.

A make a minor adaption in the output (swap sentence).

This should be a quite easy fix, a check if the resulting key starts with / is enough to know if a default is used.

**Comment by e01306821** [comment]
I'd take this issue to get a bit familiar with the codebase (CM)

**Comment by markus2330** [comment]
Thank you for taking this issue!

The relevant source is in src/tools/kdb/get.cpp method printTrace
