### ISSUE TITLE
conditional: check if key is empty

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2489]
I need to express that "if isempty(a) then istrue(b)".

Is this possible with conditionals?

How to say "isempty"? ("isempty" refers to if it contains a string with length 0)

Does "istrue" also work if the keys are yes/no? (Together with the boolean plugin. Maybe we need another ordering here?)

**Comment by kodebach** [comment]
> I need to express that "if isempty(a) then istrue(b)".

If you mean that if a is empty b must be true, I guess (haven't tried it) setting this on key a should work 
`( ./ == '' ) ? ( ./relative/path/to/b == '1' )`, as long as `boolean` is mounted first.

But I think the whole `conditionals` plugin is quite broken, and if nothing else, we should at least remove the `maintained` status.

---

Also `infos/ordering` is not really a good solution. You need to know about all other plugins to specify it correctly. If you write a new plugin, you also have to update any existing plugin, if your plugin has to be executed first.

**Comment by markus2330** [comment]
> should work

Yes, it may work but I never tried it, thus I ask.

> But I think the whole conditionals plugin is quite broken, and if nothing else, we should at least remove the maintained status.

Yes, I agree.

> Also infos/ordering is not really a good solution.

It is only for one situation: If two plugins of the same type (like it is the case here: boolean and conditionals are both validation plugins) have requirements that one must be before the other. Otherwise a different placement should be chosen.
