### ISSUE TITLE
allow customization of error messages

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2490]
The error messages of the some plugins are often hard to read (the syntax is not very intuitive).

A custom error message text similar to validation would be very helpful.

**Comment by markus2330** [comment]
Some specifier to refer to other parts of the specification would be very helpful.

E.g. the "example" or the "description":

```
[_/term]
description=The current term of this lecture.
example=2019s
default=2019s
check/validation=[0-9]{4}[sw]
check/validation/message=%description% Should be 4 digits and then s or w (match to %check/validation%), e.g. %example%.
```

**Comment by markus2330** [comment]
It would be useful to also have specifiers for the regex and the key name, see #2660

**Comment by kodebach** [comment]
> also have specifiers for the regex

Wouldn't that just be the value of `check/validation` (so `%check/validation%` in your example)?

**Comment by markus2330** [comment]
You are of course right. We only need for key-name and key-value special specifiers.

The question is if we should misuse the parentKey to pass all this information (including meta-data) or we should add another parameter to ELEKTA_SET_ERROR.

@Piankero what are your thoughts on this issue?

**Comment by Piankero** [comment]
> It would already help if the key can be printed, then one could do the lookup in the spec.

So why don't we statically add it to the error message itself (`The key %s does not confirm to %s.`) rather than giving the user a complicated and easy to fail possibility? I would not let the user add arbitrary keys (such as the description) to the message because the consistency of error messages suffers. E.g., like in cassandra one decides to expand the description with more detail (even with multiple lines and sentences) the actual `Reason` will get lost in much text or does not conform with the `check/validation/message` anymore that it forms a sensible sentence.

**Comment by markus2330** [comment]
For the regex compilation error and the failed regex I agree with @Piankero: It makes more sense to have some static text, and the message is simply added (if available and only for regex does not match errors). This way the messages are more consistent and obviously the placeholders cannot be used wrongly. (It is less flexible but the flexibility most likely is not needed as it is very unlikely that specification writers will invest a lot of time to make their error messages perfect.)

>   We could in theory completely get rid of all *_ERRORF macros.

Yes, you are right. It would be more elegant to have no _*F macros but this would be a quite big change. So I would say it is rather low priority.

> We could even detect the "%s" argument, not do the printf stuff and just use the second argument as the message.

This is most likely not needed as compilers already do such things. https://developers.redhat.com/blog/2019/08/12/efficient-string-copying-and-concatenation-in-c/

**Comment by Piankero** [comment]
Ok, so what exactly is the solution here for this issue? Should I statically add the message which key failed on which regex once a validation fails? And for any other case we wait if there is actually a need to make such customizations?

**Comment by markus2330** [comment]
Yes, seems like the most simple fix is the best.

You simply add the relevant information to the error messages.

The key (names) might not be needed in the messages, however, due to #2955. As we would of course render the cause in the error messages.

**Comment by Piankero** [comment]
Are you fine with this solution?
https://github.com/ElektraInitiative/libelektra/pull/2950/commits/8bf1943011838e1a7a0c9c4fb839dcc4975e7934

**Comment by markus2330** [comment]
The value is missing there.

**Comment by Piankero** [comment]
Value was added in https://github.com/ElektraInitiative/libelektra/pull/2950/commits/2e075baa7a53c40f88b2d8cf18b7045461de1d47

**Comment by Piankero** [comment]
Could we possibly close this issue? The root problem for the validation plugin was fixed.

**Comment by markus2330** [comment]
Yes, we can close it.
