### ISSUE TITLE
Drop wheezy support?

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#250]
Since I have now upgraded most my machines to jessie, I am wondering if I have to leave one wheezy machine to still compile and test Elektra there?

Is there anyone using Elektra 0.8.* on wheezy or sees some reason to support the old libraries or g++-4.4 as only available in wheezy?

Btw. most parts are Ansi C99, they will continue to work anyway...

@manuelm: What do you think is the best way to migrate the build-server agents?

**Comment by mhaberler** [comment]
yes, please do not drop wheezy yet.

Sometimes there are reasons not to upgrade just yet which go beyond the availability of packages in a particular debian stream, for example https://github.com/machinekit/machinekit/issues/598

**Comment by manuelm** [comment]
I've no problem with dropping the automated tests on jessie. Wiping the agent and re-installing with debian testing is probably the easiest way.

@mhaberler because we don't do automated tests any more doesn't mean libelektra will suddenly stop working.

**Comment by markus2330** [comment]
@manuelm Is it also possible to create a new agent and leave the wheezy agents as is? I thinks its better to not have all agents duplicated, but instead to cover a wider range of versions+distros. We should rename the agents to debian-wheezy, debian-jessie, debian-stretch and debian-sid (with possible -mm postfix).

E.g. you leave the agents as is (just rename them to debian-wheezy-mm and debian-sid-mm), and I will create the new jessie and stretch agents?

**Comment by manuelm** [comment]
Is this really necessary? More vms means more maintenance work and even longer build times.

In my comment above I've mixed the debian release names. In short I'm in favor of upgrading the "stable" vm to debians current stable and leaving unstable as is. I see no point in supporting+testing old debian release in new elektra releases.

Regarding testing more distributions: Testing libelektra with the distribution specific packages should be done by the package maintainer of the distribution.

But ofc it's your time and your decision :-)

**Comment by markus2330** [comment]
Running Elektra's test suite has some complications because they write to system+user pathes.
So distributions often disable these tests, if they run them at all. On our build-server we already have solutions for these issues.

Additionally, distributions only report bugs after releases. So less testing on our build-server might result to less quality in releases.

But thanks to your two existing agents I think we can cover all four debian versions with acceptable work load. For me its ok if you leave your agents names unchanged (track stable+unstable) and I up/downgrade them accordingly.

So we we would have:
debian-stable-mm  .. needs upgrade to jessie
debian-unstable-mm .. needs regular upgrades to latest sid
debian-stable -> debian-wheezy (as long there is support for it)
debian-unstable -> debian-stretch

Is this ok for you?

**Comment by manuelm** [comment]
both vms done (stable-mm -> jessi, unstable-mm -> latest updates)

**Comment by markus2330** [comment]
Thank you! For some packages to be installed, see #160.

Lets keep this issue for wheezy issues.
