### ISSUE TITLE
csvstorage: support dos newlines

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2508]
## Steps to Reproduce the Problem

Mount a CSV file which has dos newlines:

```sh
unix2dos config.csv
kdb mount config.csv system/tests csvstorage
kdb get "system/tests/lastrow/lastcolumn"
#> did not find key
kdb get "system/tests/lastrow/lastcolumn^M"
#> entry
```

## Expected Result

That the last column works.

## Actual Result

In the last column the keys have a `^M` appended.

## System Information

- Elektra Version: master

**Comment by vbalan92** [comment]
I would like to take over this task. Can you please assign it to me? Tanks in advance!

**Comment by markus2330** [comment]
@vbalan92 Thank you for taking this issue! It is quite important as https://tools.ietf.org/html/rfc4180 actually defines CSV to have CRLF as record delimiter.

You will find the source code in src/plugins/csvstorage.

I quickly tried if the following patch fixes the problem: d2803229154a35e4e4ddd3e94da531f314393878 but it does not, see https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/492/pipeline

Please also add test cases (CSV files with different file endings).

If you see some opportunities to refactor to code, it is highly appreciated (maybe as separate issue+PR).

**Comment by vbalan92** [comment]
Can you please point me to the documentation that reveals how to compile and test the compiled plugin? Thanks in advance

**Comment by markus2330** [comment]
All plugins are automatically compiled together with Elektra, you simply have to follow doc/COMPILE.md

To run only the specific tests, you can do something like:

```
ctest -V -R csvstorage
```

To directly run executables from the build directory, use (assuming "build" is the build dir within the elektra folder):

```
cd build
. ../scripts/run_dev_env
```

See also doc/TESTING.md

**Comment by markus2330** [comment]
#2553 works like a charm! Both UNIX and dos line endings now work correctly for me.
