### ISSUE TITLE
tag issues by languages

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2509]
I propose to tag issues by languages.

I would add the following tags:

- Java
- C++
- JavaScript
- Python
- (Ruby) (not sure if there is a bug in the moment)
- Groovy
- CMake

The Groovy and CMake are actually specializations of what we currently tag as "build".

What do you think about this proposal?

Any ideas or improvements?

**Comment by usamamorad** [comment]
Good Idea

**Comment by markus2330** [comment]
As discussed we will use `lang/<lang>`, e.g., `lang/cpp` for C++.

We will only create the labels we will actually need.

For the build issues we will keep build, so lang/groovy is not needed. The only exception is lang/cmake (for CMake related tasks).

**Comment by markus2330** [comment]
@usamamorad will you work on this? Many labels are already created and quite a few issues are already labeled.

**Comment by usamamorad** [comment]
@markus2330 yes i will start tagging on friday :)

**Comment by markus2330** [comment]
I am looking forward to it!

**Comment by usamamorad** [comment]
@markus2330 unfortunately i cannot add any labels to other contributors issues, as far as i know i would need write access to be able to do that. can you identify the needed permissions? :) BR Usama

**Comment by markus2330** [comment]
@usamamorad I invited you!

**Comment by markus2330** [comment]
@usamamorad are you still working on this? I assigned you now.

If anything is unclear, simply directly ask in the issues.

**Comment by markus2330** [comment]
Is already done!
