### ISSUE TITLE
JNI: Write Tutorial for Java Plugin Development

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2515]
There are already some examples of Java Plugins (src/bindings/jna/libelektra4j/src/main/java/org/libelektra/plugin/) but there is no tutorial of how to do it.

Please write a tutorial of how to get started with plugin development in Java.

**Comment by mirunix** [comment]
Thank you for the assignment. Sorry for asking, but I suppose this is one of the minor bug/tasks and not the homework, right?

**Comment by mirunix** [comment]
Thank you for the assignment, will do.

**Comment by markus2330** [comment]
This issue is again open. First work was done in #2552 which only needs to be reformatted.
