### ISSUE TITLE
python+cpp: delBaseName misleading exception

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2526]
## Steps to Reproduce the Problem

```python
with kdb.KDB() as db:
	ks = kdb.KeySet()
	db.get(ks, "system")

	for k in ks:
		if k.isDirectBelow(kdb.Key("system/somewhere")):
			if k.name.endswith("else"):
				k.delBaseName()
```

## Expected Result

Get an exception that clearly says that "k" is read-only because it is in ks (and not also many other reasons).

## Actual Result

```
Traceback (most recent call last):
  File "./script.py", line 72, in <module>
    calculate (ks)
  File "./script.py", line 62, in calculate
    k.delBaseName()
kdb.KeyInvalidName: Invalid Keyname: keyname needs to start with /, spec/, proc/, dir/, user/ or system/ or maybe you tried to change a key that is already in a KeySet.
```

## System Information

- Elektra Version: master

**Comment by markus2330** [comment]
This is related to #3029

**Comment by manuelm** [comment]
This will automatically resolve as soon as #3029 gets implemented and the cpp bindings adapted. Imho this can be closed.

**Comment by markus2330** [comment]
Thank you! As it is very easy to reproduce I keep it open and will test it once #3029 is implemented.
