### ISSUE TITLE
license issues

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2528]
update doc/THIRD-PARTY-LICENSES

- [x]  `src/tools/rest-frontend` should be renamed to `src/tools/website`.
- [x] `Files: src/tools/kdb/gen/mustache.hpp:` remove `: ` at end
- [x] cmake was renamed to `scripts/cmake`
- [x] cmake/Modules/FindLua.cmake: "To distribute this file outside of CMake, substitute the full License text for the above reference."

(Extracted from #2353)

**Comment by nastiaulian** [comment]
Will add license for asciinema.

**Comment by markus2330** [comment]
Thank you, I assigned you for this issue.

**Comment by markus2330** [comment]
The current situation is:

```sh
for i in `grep Files doc/THIRD-PARTY-LICENSES | cut -f 2 -d " "`
do
echo -n "$i " 
eval ls -d "$i" 2> /dev/null | wc -l
done
```

```
* 12
cmake/Modules/DownloadProject* 1
cmake/Modules/FindAugeas.cmake 0
cmake/Modules/FindDiscount.cmake 0
cmake/Modules/FindLua52.cmake 0
cmake/Modules/FindGLib.cmake 0
src/plugins/ini/inih-r29/* 1
src/plugins/ni/nickel-1.1.0/* 7
src/plugins/ni/nickel-1.1.0/src/hash.c 1
src/tools/rest-frontend/resources/assets/skin/base/util/space.less 0
src/tools/rest-frontend/public/assets/fonts/lato/* 1
src/tools/rest-frontend/public/assets/fonts/libre-franklin/* 1
src/tools/rest-frontend/public/assets/fonts/font-awesome/* 1
src/tools/rest-frontend/public/vendor/asciinema/asciinema-player.* 1
src/tools/rest-frontend/resources/assets/skin/base/fonts/font-awesome/* 1
src/tools/qt-gui/src/markdownconverter/* 5
scripts/realpath 0
src/tools/web/client/public/Roboto-Light.ttf 0
src/tools/kdb/gen/mustache.hpp: 0
```

**Comment by a-kraschitzer** [comment]
I'm not completely sure what is needed here.
As far as I understand, `doc/THIRD-PARTY-LICENSES` should contain all licenses that are mentioned in libelektra project that are on third parties?
Is the information currently incomplete? Or wrong?
Are only the 4 changes mentioned on top needed?

**Comment by markus2330** [comment]
Yes, at least these 4 points above are currently wrong in doc/THIRD-PARTY-LICENSES. It would be best if all entries in doc/THIRD-PARTY-LICENSES are checked, ideally with a script that you also add (that checks if the specified `Files` still exist). Such a script/CI integration is of course for additional points.

There are also scripts that extract licensing information from the source. You could run such a script and manually verify if doc/THIRD-PARTY-LICENSES is up-to-date. These scripts are, afaik, not complete or correct, so they cannot be used to generate doc/THIRD-PARTY-LICENSES. But if you find some way to generate or at least check this file, we would be very interested.

**Comment by a-kraschitzer** [comment]
> cmake/Modules/FindLua.cmake: "To distribute this file outside of CMake, substitute the full License text for the above reference."

what exactly needs to be done here?

This is the block in scripts/cmake/Modules/FindLua.cmake
```
# ~~~
# =============================================================================
# Copyright 2007-2009 Kitware, Inc.
# Copyright 2013 Rolf Eike Beer <eike@sf-mail.de>
#
# Distributed under the OSI-approved BSD License (the "License");
# see accompanying file Copyright.txt for details.
#
# This software is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the License for more information.
# =============================================================================
# (To distribute this file outside of CMake, substitute the full
#  License text for the above reference.)
# ~~~
```
Should I copy? move? everything between the `====` to `doc/THIRD-PARTY-LICENSES` ?

**Comment by markus2330** [comment]
I am also not a lawyer, but I think we need to replace the text the text between `~~~` with the text from Copyright.txt (from the other repo).

**Comment by markus2330** [comment]
@a-kraschitzer did you start this work?

**Comment by a-kraschitzer** [comment]
Yes
