### ISSUE TITLE
formatting job fails if no tools installed?

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2529]
https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/515/pipeline

**Comment by markus2330** [comment]
https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/550/pipeline/

**Comment by sanssecours** [comment]
I tried to reproduce the bug using the Alpine Linux Docker image. However, the command 

```sh
for repetition in $(seq 100); do
	printf 'Repetition %s\n' "$repetition"
	ctest -R testscr_check_formatting || exit 1
done
```

did not show any failing test. Judging from the log of the build server the first `git diff --quiet` in

https://github.com/ElektraInitiative/libelektra/blob/1046a31da67c7632fd3814474c0162ebf829cf8a/tests/shell/check_formatting.sh#L69-L76

seems to fail, while the second `git diff --quiet` succeeds, which I find quite strange.

**Comment by markus2330** [comment]
Thank you for looking into it!

Is maybe installing the tools in Alpine Linux a solution?

**Comment by sanssecours** [comment]
> Is maybe installing the tools in Alpine Linux a solution?

I do not think that would solve the underlying problem.

**Comment by markus2330** [comment]
What is the underlying problem? Is it because of the shell?

**Comment by sanssecours** [comment]
> What is the underlying problem?

If I knew that I would probably fix the issue 😊.

> Is it because of the shell?

I do not think so. The other shell tests work just fine.
