### ISSUE TITLE
Old build types in documentation

### ISSUE THREAD

**Issue by Chemin1** [ElektraInitiative/libelektra#2535]
The documentation for compiling (https://www.libelektra.org/docgettingstarted/compiling) mentions 

> ELEKTRA_DEBUG_BUILD and ELEKTRA_VERBOSE_BUILD

for. However, from what I've seen this is outdatet since 0.8.17 (https://www.libelektra.org/news/0.8.17-release) and should therefore not be in the official guide anymore?

**Comment by markus2330** [comment]
Thank you, you are completely right! I'll fix the problem.
