### ISSUE TITLE
list plugin confusion

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#2536]
While working on #868 I stumbled across a lot of weirdness inside the `list` plugin and the config for global plugins...

The one thing that is kind of problematic for `kdbEnsure`:

The `list` plugin, provides the functions `elektraListAddPlugin` and `elektraListEditPlugin`. The names make it seem like the are useful functions, with which one can add a plugin or edit its config.

However, the code inside the function highly confusing and probably even wrong (see below). The way these functions work also makes it highly impractical to use them. This is probably why they aren't used anywhere, even though at least the `notification` library could make use of them.

Why these functions are IMHO broken/implemented wrong:
https://github.com/ElektraInitiative/libelektra/blob/a59ba0853b1d4d61b5642e047224d398ebff35a5/src/plugins/list/list.c#L465-L477

This code simply checks the basename of the second key in the KeySet without validating anything else about the KeySet... 

The question now is: Can I simply change these functions completely (signature and all)?

Technically this would be a breaking change, but they aren't used anywhere and I doubt they are used anywhere in the wild, because they are basically useless (if not completely useless, because you cannot get the necessary plugin handle).

**Comment by markus2330** [comment]
> The question now is: Can I simply change these functions completely (signature and all)?

Yes.

But please make it in a way so that we can reuse this API also with the new plugin system developed by Vid. The list plugin will hopefully get retired soon.
