### ISSUE TITLE
mounting/accessing a remote elektra instance: possible?

### ISSUE THREAD

**Issue by mhaberler** [ElektraInitiative/libelektra#254]
is there any provision for integrating elektra namespaces beyond a single host, excluding networked file systems?

IOW: can I mount a remote elektra namespace into a local keyspace?

**Comment by markus2330** [comment]
No, the semantics of Elektra namespaces are defined to be local to the system, user, dir(ectory) or proc(ess). Nevertheless, if you want to pull a new config every time (and assume that a central node is always up) a curl-plugin could fulfil that task easily. Alternatively, can pull/push changes with the myriad of configuration management tools available. (Which can use Elektra to have key/value access)

What architecture do you have in mind?

**Comment by mhaberler** [comment]
well that is a pretty fundamental design decision, maybe this should be spelled out in a non-goals section in https://github.com/ElektraInitiative/libelektra/blob/master/doc/GOALS.md ?

the use case is: remote access to configuration data of clients which do not/can not store permanent configuration state

example: the machinekit UI's running on tablets/phones etc get all their setup, including UI layout, and intra-UI code at connect time (QML/js in the Qt5 case), and using local files would make an exception to this pattern (besides being a support problem)

**Comment by markus2330** [comment]
Even if "system" is defined to be local to the system, nobody says that it needs to be persistently stored on that system.

Limitations only exist for what a KeySet is able to represent (e.g. having two keys with the same name would be a non-goal). There is no limitation for what plugins are allowed to implement.

Its perfectly fine if a plugin downloads configuration from somewhere and operates completely in-memory.

**Comment by markus2330** [comment]
@tom-wa said that he also plan to implement a distribution protocol directly based on sockets

**Comment by markus2330** [comment]
I will close the issue, the `curlget` plugin can be used to access configurations of remote  instances.  Please write to  #388 if you need something else.
