### ISSUE TITLE
KDB Set Meta: Command Stores Empty String Instead of Nothing in New Keys

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2540]
# Steps to Reproduce the Problem

```sh
kdb setmeta user/tests/empty array ''
```

# Expected Result

The command above should create an empty key:

```sh
kdb lsmeta user/tests/empty
#> array
#> binary
```

.

# Actual Result

The command creates a key that stores an empty string:

```sh
# The following command would also show the meta key `binary` for an 
# empty key, since “nothing” can not be represented as string.
kdb lsmeta user/tests/empty
#> array

# The command `keyNew 17 1` shows that 
# `kdb setmeta` did produce a key that stores an empty string instead of nothing
kdb export user/tests/empty dump
#> kdbOpen 1
#> ksNew 1
#> keyNew 17 1
#> user/tests/empty
#> keyMeta 6 1
#> array
#> keyEnd
#> ksEnd
```

# Additional Information

I think that the commands

```sh
kdb set user/tests/empty
kdb setmeta user/tests/empty array ''
```

, and

```sh
kdb setmeta user/tests/empty array '' # No `kdb set` before
```

should produce the same key database. This is currently not the case.

If I remove the comment from

https://github.com/ElektraInitiative/libelektra/blob/0ea118c630f8de98efae4f89df88375aefec9737/src/tools/kdb/metaset.cpp#L51

, then at least the following tests:

- `testshell_markdown_enum`
- `testshell_markdown_ipaddr`
- `testshell_markdown_mathcheck`
- `testshell_markdown_ni`
- `testshell_markdown_range`
- `testscr_check_spec`
- `testshell_markdown_tutorial_validation`

[fail](https://github.com/sanssecours/elektra/runs/85163675).

# System Information

- Elektra Version: `master`
- macOS 10.14.3

**Comment by markus2330** [comment]
Thank you for reporting this usability problem!

As the code-comment already says, I wanted to avoid following problem:

```
kdb setmeta user/tests/empty array ''
kdb getmeta user/tests/empty binary
# Why is binary set here? I wanted to set array ;(
```

What about improving the output of `kdb setmeta user/tests/empty array ''`? E.g. it could say "Created new key user/tests/empty with empty value and meta-data array"?

**Comment by sanssecours** [comment]
> E.g. it could say "Created new key user/tests/empty with empty **value** and meta-data array"?

If you replace “value” with “string” in the message above, then I think it would improve the situation slightly. However, I still prefer that `kdb setmeta` just creates an empty key, if the key does not exist yet.

**Comment by markus2330** [comment]
> If you replace “value” with “string” in the message above, then I think it would improve the situation slightly.

Ok, then let us do this for now.

> I still prefer that kdb setmeta just creates an empty key, if the key does not exist yet.

Yes, it makes sense if you already know Elektra's basics. But if someone does not know about that keys can be empty, it will be confusing for the person why "binary" is set.

What about completely rejecting `kdb setmeta` if the key does not exist?

**Comment by sanssecours** [comment]
> Yes, it makes sense if you already know Elektra's basics. But if someone does not know about that keys can be empty, it will be confusing for the person why "binary" is set.

I agree that we should make it more obvious in the documentation that empty keys exist, and that they store the meta key `binary`.

> What about completely rejecting `kdb setmeta` if the key does not exist?

That sound inconvenient. I would even prefer the current current behavior over that.

**Comment by markus2330** [comment]
> I agree that we should make it more obvious in the documentation that empty keys exist

I think the docu already overcharges users with special nuances of problems normal users never thought of. Most users should be able to use Elektra without knowing what an "null value" or an "empty base name" is. Of course you need to know it if you want to write a parser. But for normal usage it should be irrelevant.

We should put the attention on things they really should care about: E.g. that meta data exists and that they can use it to describe their application's configuration.

Btw. "empty base name" (%) is not explained in doc/help/elektra-glossary.md

**Comment by kodebach** [comment]
Isn't the easiest solution here to remove this functionality `kdb set user/tests/empty`?

AFAIK it is currently the only way `kdb set` creates a binary key, any other `kdb set` call creates a string key.

**Comment by markus2330** [comment]
Yes, very good idea. Let us simply remove this functionality. And after 1.0 we properly implement binary support in `kdb` #1614.
