### ISSUE TITLE
authentication model: what is the idea here?

### ISSUE THREAD

**Issue by mhaberler** [ElektraInitiative/libelektra#255]
`grep -ri authenticat elektra ` turns up zero matches.

Is there an authentication model for libelektra?
 
If so, is it the unix user credentials being assumed or anything else?

In a possible remote scenario, what would be the authentication model?

**Comment by markus2330** [comment]
Thus the file access happens directly with the process requesting configuration, the security model is completely left to the operating system. You can and should design your application to not have write access to configuration it should not be able to change. (E.g. directly requesting system/ configuration and denying write-access to /etc). Obviously, also ACLs can be used.

On plugin-level further restrictions could be implemented, but of course they would *not* improve security in any way. More useful would be to implement authentication+restrictions in the GUI and disable local access for untrusted users completely.

What are your thoughts on that?

**Comment by mhaberler** [comment]
well your answer and the fact that remote access is out of scope for elektra settles it

as far as I can see the only option would be to confine elektra to a server instance and wrap remote access/authentication around that in an extra layer along the lines of webdis/etcd/ZooKeeper ff

that is something we tried to avoid but it seems elektra will not help here

in such a case change detection in the server becomes essential, what is the story on that?

**Comment by markus2330** [comment]
I see generic GUIs as part of Elektra and I think its ok to have access control features (e.g. with roles and visibility) together with the authentication there.

Isn't the change detection discussed in #253?

**Comment by markus2330** [comment]
I think the definitive answer here is: authentication is an issue for every plugin and bridge that opens a connection to the outside world. libelektra in its default setup will not open anything except configuration files.

Thus some protocols demand specific authentication models to use, we cannot enforce a single authentication model.

Of course everyone is welcome to build network configuration protocols (such as SNMP) or distributed configuration synchronization mechanism on top of Elektra. We also accept such tools and plugins here in upstream.
