### ISSUE TITLE
JNA-bindings: test_keySetCut_shouldPass failes

### ISSUE THREAD

**Issue by mirunix** [ElektraInitiative/libelektra#2551]
## Steps to Reproduce the Problem

Run the java unit tests in the KeySetTest.java

## Expected Result

The test test_keySetCut_shouldPass is expected to pass.

## Actual Result

The test failes with an assertation error.

**Comment by mirunix** [comment]
@markus2330 Please assign the issue to me so I can take a closer look at the test. Thank you!

**Comment by markus2330** [comment]
Thank you for creating the issue! I assigned you.

**Comment by mirunix** [comment]
I found the problem with this one, but I have a question regarding the expected functionality:

The method public KeySet cut(final Key cutpoint) in KeySet.java calls the constructor new KeySet with the result of the cutted KeySet. But according to the contructor protected KeySet(final Pointer p), the result will still be the actual, initial KeySet, which is now shortened through the cut method.

So the test fails because the cut Method actually changed the initial KeySet ks, and not the second one, ks2. 

My question is, is this the expected behavior and the test should be updated to check the length of the initial KeySet ks, or is the constructor in the KeySet class wrong and it should actually build another identical KeySet with the one on which the Pointer shows at?

**Comment by markus2330** [comment]
Thank you for looking into it in more detail. The docu seems to be misleading/wrong. The keyset itself (this) is modified (keys are cutted out) and the cutted-out keys will be returned.

Both the Java and C++ binding behave this way but the docu in Java does not mention this.

So please fix the docu and the testcase.

**Comment by mirunix** [comment]
Testcase should be correct, the implementation has to be fixed according to https://github.com/ElektraInitiative/libelektra/pull/2557#discussion_r271499985 .

**Comment by markus2330** [comment]
Yes, then your task is only to update the docu. Many examples were given already, so it should be easy to write a good docu.
