### ISSUE TITLE
CMake: kdb dependencies

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#2555]
There might already be an issue for this, but I will post it anyway...

In order for `kdb` (the C++ tool, not the `elektra-kdb` library) to function properly, at least the default storage and resolver plugin have to be available. Therefore there should be a CMake dependency between `kdb` and those plugins.

Currently we do not have this dependency so the following (quite reasonable) sequence of commands will not work:
```sh
mkdir build && cd build
cmake ..
make kdb
bin/kdb
```
Instead there will be a pretty long and complicated message about `kdbOpen()` failing...

**Comment by markus2330** [comment]
Thank you for reporting this problem!

**Comment by mpranj** [comment]
This sounds like we should at least take a look at it.

**Comment by kodebach** [comment]
I just tried this again and I think some changes to the error message would be an alternative solution. Currently I get:

```
Usage: bin/kdb <command> [args]

bin/kdb is a program to manage Elektra's key database.
Please run a command with -H or --help as args to show a help text for
a specific command.

Known commands are:
Sorry, I have a severe problem, it seems like I am not installed correctly!
kdbOpen() failed with the info:
 Sorry, 1 warning was issued ;(
	Sorry, module kdb issued the warning C01200:
	Installation: Dlopen failed. Could not load module libelektra-resolver.so. Reason: /home/klemens/libelektra/build/lib/libelektra-resolver.so: file too short
	Mountpoint: 
	Configfile: 
	At: /home/klemens/libelektra/src/libs/loader/dl.c:90
Sorry, module kdb issued the error C01200:
Installation: Could not open default backend. See other warning or error messages for concrete details
Mountpoint: 
Configfile: 
At: /home/klemens/libelektra/src/libs/elektra/kdb.c:329

Please report the issue at https://issues.libelektra.org/                                                                                                                                                                                                                                 
```


I see two problems here:
1. `kdb` starts to print the help message, but then switches to an error message, without any real indication where the switch happens.
The easiest change here would be to print one or two empty lines before the "Sorry, I have  [...]" so it is more obvious where the error starts. Coloring the "Sorry, I have [...]" could also help.
2. Some part of the build process creates the `libelektra-resolver.so` symlink as well as its target (in my case `libelektra-resolver_fm_hpu_b.so`) even though the resolver is not being built. This results in an accurate but confusing error about the file being to short. If the error said something simple like "The resolver plugin wasn't found/couldn't be loaded". The correct course of action would be much clearer.

**Comment by markus2330** [comment]
Thank you for looking into it again and the very constructive suggestion :sparkling_heart: 

I totally agree that this "error message" is confusing. Could it also happen on regular systems when the libelektra-resolver.so symlink is missing/wrong?

**Comment by markus2330** [comment]
One more thought: From my point of view it is enough if the build system has knowledge about all build dependency. What this issue (and also others) propose is to add run-time dependencies.

I agree that it is a nice thing (for developers) but imho simply not worth the effort to code all these deps in CMake.

An imho more important issue in our build system is #1075 (a changed file does not retrigger builds). But also here I think we can leave it as is because the main use case is: create new build directory, run cmake, run make. That anything else works is only nice to have and, unfortunately, often quite an effort with CMake. But it is now up to @mpranj to define to which level of developer convenience the build system should work.

**Comment by kodebach** [comment]
> Could it also happen on regular systems when the libelektra-resolver.so symlink is missing/wrong?

I didn't test it, but I don't see why it would make any difference what caused the symlink to be missing/broken.

I think the problem here is that `kdb` starts printing stuff and at some point it tries to read the KDB to get some information. That fails and causes the error message.

Maybe a good solution would be to have `kdb` call a `checkSetup()` function at the start of `main()` that tries to load the KDB and maybe does some rudimentary checks.

> What this issue (and also others) propose is to add run-time dependencies.

Not really. The CMake variables `KDB_DEFAULT_STORAGE` and `KDB_DEFAULT_RESOLVER` already exist. If the `kdb` target had dependencies on the targets the values of these variables correspond to, the original issue would be solved.

> a changed file does not retrigger builds

You can use `set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS <filename>)` to add files that should trigger CMake to reconfigure.

If you just want to trigger a build step, for compile targets CMake should take care of that for custom commands you need to add the files to the `DEPENDS` part of [`add_custom_command`](https://cmake.org/cmake/help/latest/command/add_custom_command.html).

I know that works, because that is how I got CMake to regenerate `templates.hpp` file that `kdb gen` uses, whenever one of the `.mustache` files is changed. (see [here](https://github.com/ElektraInitiative/libelektra/blob/dfca6204964769ce35ee42318578b0b27d5ff532/src/tools/kdb/gen/templates/CMakeLists.txt))
Adding new files doesn't trigger a regenerate, but that is expected because CMake has no way of knowing about these files.
