### ISSUE TITLE
High-Level API: Test Seems to Stall Sometimes

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2558]
# Problem Description

It looks like the tests [`testkdb_highlevel`](https://github.com/ElektraInitiative/libelektra/blob/master/tests/kdb/testkdb_highlevel.cpp) stalls sometimes on the Jenkins build server, since it might fail with exit code `143`. As far as I can tell from the [Jenkins documentation](https://wiki.jenkins.io/display/JENKINS/Job+Exit+Status), exit code 143 means the process was terminated with signal [`SIGTERM`](https://www.tutorialspoint.com/unix/unix-signals-traps.htm) (143-128=**15**), which usually happens if `ctest` kills a test that hit the timeout limit. 
 
# System Information

- Elektra Version: `master`

# Build Server Logs

- [`master`](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2545/6/pipeline/460)
- [PR #2545](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2553/4/pipeline/223/)

**Comment by kodebach** [comment]
I don't think it stalls, `testkdb_highlevel` is just inherently a very slow test. Every `elektraSet*` call (of which a good test has many) includes a call to `kdbSet` and `kdbGet` and is therefore a bit slow. In combination with `valgrind` and high server load this results in pretty long test durations.

For example in the [PR #2545 build](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2545/5/pipeline/460#step-1429-log-7) just before the one you linked, it took nearly 4 minutes to complete the test in `BUILD_FULL` "optimizations off"-mode.

**Comment by sanssecours** [comment]
Thank you for the quick update. If the test really takes that long to execute, then it might make sense to just increase the test timeout?

**Comment by kodebach** [comment]
> then it might make sense to just increase the test timeout?

Seems like the easiest solution, yes.

**Comment by sanssecours** [comment]
According to this [Stackflow article](https://stackoverflow.com/questions/45009595/how-to-overwrite-ctest-default-timeout-1500-in-cmakelists-txt) and the [source code of CMake](https://github.com/Kitware/CMake/blob/master/Tests/CMakeLists.txt#L327) the default CTest timeout should be 1500s (25 min). Do we limit this test timeout somewhere in the CMake code or does `testkdb_highlevel` really take that long to execute?

**Comment by kodebach** [comment]
I highly doubt it takes that long...

Also I looked at some of the problematic Jenkins jobs, and they all took a lot less than 25 min before they stopped. [Here](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2545/6/pipeline/460/) the build step in question aborted after only 5m 9s...

So the SIGTERM must come from something other than a timeout.

**Comment by markus2330** [comment]
Thank you for looking into this and fixing the problem!
