### ISSUE TITLE
kdb cp should not fail if keys are identical

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2560]
## Steps to Reproduce the Problem

```sh
kdb set user/tests/hello world
kdb set user/tests/copy world

kdb cp user/tests/hello user/tests/copy
```

## Expected Result

That nothing happens (and no error message).

## Actual Result

```
The command kdb cp terminated unsuccessfully with the info:
Copy will not be done, because user/tests/copy already exists, use -f to force copy
```

## System Information

- Elektra Version: master

## Implementation Hint

also must work for -r (in this case it is even more important)

**Comment by e01306821** [comment]
I'd like to take this issue.

**Comment by markus2330** [comment]
Thank you! I assigned you.
