### ISSUE TITLE
JNA: No Rebuild After Changes to Unit Test

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2574]
# Steps to Reproduce the Problem

1. Build Elektra

   ```sh
   mkdir build
   cd build
   cmake -GNinja -DBINDINGS="jna" ..
   ninja
   ```

2. Insert a syntax error into `KeySetTest.java`

   ```sh
   printf 'Choose Go!' >> \
     ../src/bindings/jna/libelektra4j/src/test/java/org/libelektra/KeySetTest.java
   ```

3. Rebuild Elektra

   ```sh
   ninja
   ```

# Expected Result

The last command should rebuild Elektra (including the file `KeySetTest.java`).

# Actual Result

Ninja reports that the build system is up to date:

```
ninja: no work to do.
```

. The test for the JNA binding:

```sh
ctest --output-on-failure -R jna
# RET: 0
```

still works, even though `KeySetTest.java` is broken.

# Additional Information

As far as I can tell, the problem is, that the Maven commands in the [CMake code of the JNA binding](https://master.libelektra.org/src/bindings/jna/CMakeLists.txt) do not depend on the source files of the JNA binding.

## System Information

- Elektra Version: `master`
- macOS `10.14.4`

**Comment by markus2330** [comment]
Thank you for creating this bug report!

Btw: #1075 is a similar problem.
