### ISSUE TITLE
cpp: malformed key names not rejected

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2583]
## Steps to Reproduce the Problem

```python
import kdb
k = kdb.Key("abc")
k.name="abc"
```

## Expected Result

That for both ways to assign the key's name an exception is raised that "abc" is not a valid keyname.

## Actual Result

```
k = kdb.Key("abc")
#> <kdb.Key; proxy of <Swig Object of type 'kdb::Key *' at 0x7f9ec38b2c90> >
k.name
#> ''
k.name="abc"
#> segfault
```

## System Information

- Elektra Version: master

**Comment by manuelm** [comment]
I've modified the subject as this is no python nor swig issue. A possible fix, feel free to commit this:
```patch
--- a/src/bindings/cpp/include/key.hpp
+++ b/src/bindings/cpp/include/key.hpp
@@ -604,6 +604,7 @@ inline Key::Key (const char * keyName, ...)
        va_end (ap);
 
        if (!key) throw std::bad_alloc ();
+       if (ckdb::keyGetUnescapedNameSize (key) <= 0) throw KeyInvalidName ();
 
        operator++ ();
 }
@@ -628,6 +629,7 @@ inline Key::Key (const std::string keyName, ...)
        va_end (ap);
 
        if (!key) throw std::bad_alloc ();
+       if (ckdb::keyGetUnescapedNameSize (key) <= 0) throw KeyInvalidName ();
 
        operator++ ();
 }
@@ -645,6 +647,7 @@ inline Key::Key (const char * keyName, va_list ap)
        key = ckdb::keyVNew (keyName, ap);
 
        if (!key) throw std::bad_alloc ();
+       if (ckdb::keyGetUnescapedNameSize (key) <= 0) throw KeyInvalidName ();
 
        operator++ ();
 }
```

**Comment by markus2330** [comment]
Thank you! Can you please add this commit to your PR?

**Comment by manuelm** [comment]
@markus2330 As expected changing the ctor to throw on invalid names makes tests fail on other places. Can you or someone else please take over https://github.com/ElektraInitiative/libelektra/pull/3133/commits/ea8a01e4918544ccb860666478f2e87b27ae9f37. I've already invested enough time in this.

**Comment by markus2330** [comment]
Actually this problem will solve itself once #3115 is merged. Because then keyNew will fail with malformed key names.
