### ISSUE TITLE
python: Install bindings

### ISSUE THREAD

**Issue by PhilippGackstatter** [ElektraInitiative/libelektra#2593]
I am trying to use the python-bindings in a Docker container running alpine (edge in this case).  The documentation for the python binding only speaks of compilation, so I assumed the following steps would be all that I need.

## Steps to Reproduce the Problem

```sh
docker run -it alpine:edge /bin/sh
```

Then inside the container
```sh
# The elektra package is only available in testing (I think)
echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
# Install elektra and the python bindings
apk update && apk add elektra elektra-python
# Start python
python3
Python 3.6.8 (default, Mar 13 2019, 17:23:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'kdb'
```

## Expected Result
I expect the import of the kdb module to suceed.

## Actual Result

`ModuleNotFoundError: No module named 'kdb'`

## System Information

- Elektra Version: elektra (0.8.21-r5)
- Docker `alpine:edge` (Image ID `7da711226313`).

**Comment by markus2330** [comment]
Thank you for creating this issue! It seems like that elektra-python only contains the python plugin but not the python binding. You are searching for apk add py3-elektra, then the `import kdb` works.

**Comment by PhilippGackstatter** [comment]
Thanks, that worked! I think there should be documentation on this either on the [python-bindings](https://www.libelektra.org/tutorials/python-bindings) tutorial or on the [swig-python](https://www.libelektra.org/bindings/swig_python) bindings page on libelektra.

**Comment by markus2330** [comment]
Feel free to add this information with a PR in the python-bindings tutorial. The Alpine docker image seems to be an easy way to try out Elektra, see also  #2585

**Comment by PhilippGackstatter** [comment]
I'll make a PR shortly. Regarding #2585, I was running a plain alpine image, not the one built with the script in this repo since I want to add elektra to an extisting application that is running in an alpine container.

**Comment by markus2330** [comment]
In the PR you can describe both variants (plain alpine and alpine image from our repo).

**Comment by PhilippGackstatter** [comment]
On a new `alpine:edge` container, just installing `elektra` and `py3-elektra` lets me use `kdb` just fine, but in python it fails.

```sh
kdb set user/test hello
#> Create a new key user/test with string "hello"
kdb get user/test
#> hello
```

```sh
Python 3.7.3 (default, Apr 17 2019, 11:48:37) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kdb
>>> kdb.KDB()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/kdb.py", line 1672, in __init__
    _kdb.KDB_swiginit(self, _kdb.new_KDB(*args))
kdb.KDBException: 1 Warning was issued:
 Warning number: 1
	Description: could not load module, dlopen failed
	Ingroup: modules
	Module: dl
	At: /home/buildozer/aports/testing/elektra/src/libelektra-0.8.21/src/libs/loader/dl.c:88
	Reason: of module: libelektra-resolver.so, because: Error loading shared library libelektra-resolver.so: No such file or directory
	Mountpoint: 
	Configfile: 
Sorry, the error (#40) occurred!
Description: failed to open default backend (see warnings for more information)
Ingroup: kdb
Module: 
At: /home/buildozer/aports/testing/elektra/src/libelektra-0.8.21/src/libs/elektra/kdb.c:287
Reason: could not open default backend
Mountpoint: 
Configfile: 
```

Any idea why that is? If the resolver was actually missing, wouldn't `kdb` fail as well?

**Comment by markus2330** [comment]
This can happen if e.g. the python binary does not support RPATH. Can you try to add Elektra's plugin directory (where libelektra-resolver.so is) to /etc/ld.so.conf and run ldconfig?

If this helps we should report this upstream in Alpine Linux so that they can fix it.

**Comment by PhilippGackstatter** [comment]
That doesn't work for me unfortunately.
```sh
/etc # find / -name libelektra-resolver*
/usr/lib/elektra/libelektra-resolver.so
/usr/lib/elektra/libelektra-resolver_fm_hpu_b.so
/etc # echo "/usr/lib/elektra" >> /etc/ld.so.conf
/etc # ldconfig
/etc # python3
Python 3.6.8 (default, Mar 13 2019, 17:23:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kdb
>>> kdb.KDB()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/kdb.py", line 1672, in __init__
    _kdb.KDB_swiginit(self, _kdb.new_KDB(*args))
kdb.KDBException: 1 Warning was issued:
 Warning number: 1
	Description: could not load module, dlopen failed
	Ingroup: modules
	Module: dl
	At: /home/buildozer/aports/testing/elektra/src/libelektra-0.8.21/src/libs/loader/dl.c:88
	Reason: of module: libelektra-resolver.so, because: Error loading shared library libelektra-resolver.so: No such file or directory
	Mountpoint: 
	Configfile: 
Sorry, the error (#40) occurred!
Description: failed to open default backend (see warnings for more information)
Ingroup: kdb
Module: 
At: /home/buildozer/aports/testing/elektra/src/libelektra-0.8.21/src/libs/elektra/kdb.c:287
Reason: could not open default backend
Mountpoint: 
Configfile: 

```

**Comment by markus2330** [comment]
Sorry, in Alpine Linux the file is called differently (not /etc/ld.so.conf), see https://stackoverflow.com/questions/36990951/ldconfig-seems-no-functional-under-alpine-3-3

We should also mention this in doc/INSTALL.md

**Comment by PhilippGackstatter** [comment]
Cool, that worked!
I added
```
/lib
/usr/local/lib
/usr/lib
/usr/lib/elektra/
```
to `/etc/ld-musl-x86_64.path`.
Then
```sh
/ # ldconfig
/ # python3
Python 3.6.8 (default, Mar 13 2019, 17:23:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kdb
>>> with kdb.KDB() as k:
...     ks = kdb.KeySet()
...     k.get(ks, 'user')
...     for e in ks:
...             print(e)
... 
1
user/test
```
I will add this to the installation instructions for the python-bindings under Alpine.

**Comment by markus2330** [comment]
Thank you! As mentioned in #1275 we will most likely change the default in the next release so that this should not be necessary anymore.
