### ISSUE TITLE
cache: resolver support

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2598]
Are all resolvers already supported by the cache plugin? I tried to umount all noresolver but the cache plugin still did not yield any performance advantage. I have some multiresolver mounted (and also some INI files, see #2592).

**Comment by mpranj** [comment]
Only the default resolver is currently supported (tracked informally in #2270).

Whenever the ini plugin is encountered in the current split backends, nothing is cached.

**Comment by markus2330** [comment]
Ok, unfortunately, I currently use multiresolver and ini in my setup and cannot avoid it. I hope @tom-wa will find a solution for #2592 (or at least describe how it should be).
