### ISSUE TITLE
The JNI version is not correct when JNI plugin is included with cmake

### ISSUE THREAD

**Issue by dmoisej** [ElektraInitiative/libelektra#2616]
## Steps to Reproduce the Problem

Please provide a step by step guide on how to reproduce the problem here. If possible, please use
[Markdown Shell Recorder](https://master.libelektra.org/tests/shell/shell_recorder/tutorial_wrapper)
syntax:

1. Specify JAVA_HOME environmental variable.
```sh
JAVA_HOME=/usr/lib/jvm/java-11-oracle
```
2. Compile the libelektra with the jni plugin:
```sh
git clone https://github.com/ElektraInitiative/libelektra.git
cd libelektra
mkdir build
cd build
cmake -DPLUGINS="ALL;-EXPERIMENTAL;jni" ..
```

## Expected Result

The jni plugin is successfully included into the list of available plugins.

## Actual Result

The jni plugin is not included because JNI_VERSION_1_8 is not defined.

## System Information

- Elektra Version: master

## Solution. The fix is provided in the pull request 2615.

**Comment by markus2330** [comment]
Thank you for reporting this problem!

Maybe we can also improve the jni plugin to allow other Java versions?
