### ISSUE TITLE
Enable C++11 support by default

### ISSUE THREAD

**Issue by manuelm** [ElektraInitiative/libelektra#262]
Enable C++11 support by default and remove the configuration setting.

:+1: ? :-)

**Comment by markus2330** [comment]
I am completely for it, but I don't know if the used mingw compiler already support that flag.

@beku any thoughts on this?

**Comment by markus2330** [comment]
Kai-Uwe also has no objections. So its good to go, but I think its better to apply the necessary changes directly after the release of 0.8.13.

**Comment by markus2330** [comment]
0.8.14 released, it only supports C++11, no problems up to now. Please reopen if you have one.
