### ISSUE TITLE
How to compile/use python2-binding?

### ISSUE THREAD

**Issue by e01306821** [ElektraInitiative/libelektra#2620]
Hi, I'm trying to use the python2-binding on arch-linux. Since it seems to not be available in its package-repositories (unlike in alpinelinux as mentioned in #2593), I've tried to manually build and install it using the [swig_python2-documentation](https://www.libelektra.org/bindings/swig_python2) and [COMPILATION.md](https://github.com/ElektraInitiative/libelektra/tree/master/doc/COMPILE.md#bindings).

Inside libelektra/build

- cmake .. -DBINDINGS="ALL;-EXPERIMENTAL;-DEPRECATED" -DPYTHON2_EXECUTABLE:FILEPATH="/usr/bin/python2.7" -DPYTHON2_INCLUDE_DIR:PATH="/usr/include/python2.7" -DPYTHON2_LIBRARY:FILEPATH="/usr/lib/libpython2.7.so"
- make -j 5
- sudo make install & sudo ldconfig

If I now try to import kdb, the module can still not be found. Am i missing something? These paths for DPYTHON2 seem to be correct.

**Comment by markus2330** [comment]
There is an up-to-date AUR package https://aur.archlinux.org/packages/elektra/ which optionally includes python2 bindings.

Otherwise, if it does not help, please post the relevant parts of your cmake log. Maybe the python2 binding was removed because of some missing dependency.

**Comment by e01306821** [comment]
Thanks! It is automatically compiled and added by installing this package
