### ISSUE TITLE
Tutorial about how to work on this project using CLion

### ISSUE THREAD

**Issue by e01306821** [ElektraInitiative/libelektra#2623]
I'd like to write a tutorial about how to work on this project using CLion (import project, run tests, debugging, ...) if that's ok for you.

**Comment by markus2330** [comment]
Yes, this is an excellent idea! We are very much looking forward to it. I assigned you.

**Comment by kodebach** [comment]
If you have any problems with CLion or generally want to know what works best, just tag me. I have been using CLion for working on Elektra for a few months now...
