### ISSUE TITLE
cache: fails to validate cached file names

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#2624]
The `cache` plugin fails to validate resolved file names. False cache hits can be produced in a somewhat rare scenario, where the number of splits is the same but a filename has changed while the cache has not been invalidated by another reason.

Currently the check is placed before filenames are resolved and thus fails to check for the correct file name. The check needs to be done after the resolver has run.

**Comment by markus2330** [comment]
Thank you for reporting and fixing the bug!
