### ISSUE TITLE
link warning in libelektra-journald.so

### ISSUE THREAD

**Issue by sl1pkn07** [ElektraInitiative/libelektra#264]
when build the project:

    [ 54%] Linking C shared module ../../../lib/libelektra-journald.so
    CMakeFiles/elektra-journald.dir/journald.c.o: In the function `elektraJournaldSet':
    journald.c:(.text+0x2e1): warning: sd_journal_send_with_location was moved to libsystemd. Do not use libsystemd-journal.
    [ 54%] Built target elektra-journald

systemd 224

**Comment by markus2330** [comment]
Thanks for reporting!

**Comment by fberlakovich** [comment]
I am afraid you have to either reassign this issue to someone with a newer development environment (mine is Debian 7.8) or give me access to a suitable test machine. This warning does not occurr on my machine.

**Comment by sl1pkn07** [comment]
same with systemd 227 (Archlinux)

**Comment by markus2330** [comment]
@sl1pkn07 Which distribution? Is the issue still present with more recent versions?

@fberlakovich Where did you get FindSystemdJournal.cmake from? Maybe there is a more recent version available?

**Comment by sl1pkn07** [comment]
Archlinux. And still happen with systemd 227

**Comment by markus2330** [comment]
@sl1pkn07 Can you provide an Archlinux login for @fberlakovich somewhere?

To understand the bug we need much more information: What is in CMakeCache.txt, what is the gcc command directly after `Linking C shared module` (VERBOSE=1),... To fix it, we most likely need an Archlinux installation anyway.

**Comment by sl1pkn07** [comment]
[ 62%] Linking C shared module ../../../lib/libelektra-journald.so
    cd /tmp/makepkg/elektra-git/src/build/src/plugins/journald && /usr/bin/cmake -E cmake_link_script CMakeFiles/elektra-journald.dir/link.txt --verbose=1
    /usr/bin/cc  -fPIC -march=native -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4  -std=gnu99  -Wno-deprecated-declarations  -Wno-long-long -pedantic -Wno-variadic-macros -Wall -Wextra -Wno-overlength-strings -Wsign-compare -Wfloat-equal -Wformat-security -Wshadow -Wcomments -Wtrigraphs -Wundef -Wuninitialized -Winit-self -Wmaybe-uninitialized -Wsign-compare -Wfloat-equal -Wformat-security -O3 -DNDEBUG  -Wl,-O1,--sort-common,--as-needed,-z,relro -shared -Wl,-soname,libelektra-journald.so -o ../../../lib/libelektra-journald.so CMakeFiles/elektra-journald.dir/journald.c.o ../../../lib/libelektra.so.0.8.13 -lsystemd-journal -ldl -Wl,-rpath,/tmp/makepkg/elektra-git/src/build/lib: 
    CMakeFiles/elektra-journald.dir/journald.c.o: En la función `elektraJournaldSet':
    journald.c:(.text+0x2e1): aviso: sd_journal_send_with_location was moved to libsystemd. Do not use libsystemd-journal.
    make[2]: se sale del directorio '/tmp/makepkg/elektra-git/src/build'

CMakeCache.txt: http://sl1pkn07.wtf/paste/view/b2a10551

**Comment by markus2330** [comment]
So `LIBSYSTEMD_JOURNAL_LIBRARIES:FILEPATH=/usr/lib64/libsystemd-journal.so` is wrong and `LIBSYSTEMD_JOURNAL_LIBRARIES:FILEPATH=/usr/lib64/libsystemd.so` is expected?

Is this specific to Arch-Linux? Is there some hint when not to use `libsystemd-journal.so` (except of that warning)? Why is `libsystemd-journal.so` installed anyway?

**Comment by sl1pkn07** [comment]
https://github.com/systemd/systemd/blob/master/src/compat-libs/linkwarning.h

sounds sd_journal_send_with_location in libsystemd-journal.so is deprecated

see http://forums.debian.net/viewtopic.php?f=20&t=118617

**Comment by sl1pkn07** [comment]
the message now gone (testing with commit c5dd537ba7511230d9514665d24c32d3c9763ef0  and systemd 229)

greetings
