### ISSUE TITLE
core: disable global plugins for cache hit and no update

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#2644]
As discussed in #2270 we want to disable all plugins (including global positions) when we have a cache hit. The idea is to store the completely processed KeySet, and then only load it. The change makes a significant performance improvement.

I would like to disable the same plugins for the no update scenario too. It makes no sense that a cache hit is faster (which it is) than an already loaded KeySet with no updates to do.

The obvious drawback is that this prevents us from using certain things like logging, tracer, ... in those positions.

It looks like only one test case fails when we implement this change:

```
261/276 Test #275: testkdb_ensure ................................***Failed    0.27 sec
Running main() from /opt/gtest/googletest/src/gtest_main.cc
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from Ensure
[ RUN      ] Ensure.GlobalUnmount
[       OK ] Ensure.GlobalUnmount (94 ms)
[ RUN      ] Ensure.Unmount
[       OK ] Ensure.Unmount (86 ms)
[ RUN      ] Ensure.GlobalMount
tracer: open(0x55db6b824780, spec/tests/kdb/ensure = ): 0
/home/jenkins/workspace/libelektra/tests/kdb/testkdb_ensure.cpp:129: Failure
Value of: capture.empty ()
  Actual: true
Expected: false
tracer plugin not run
Google Test trace:
/home/jenkins/workspace/libelektra/tests/kdb/testkdb_ensure.cpp:170: first ensure
/home/jenkins/workspace/libelektra/tests/kdb/testkdb_ensure.cpp:129: Failure
Value of: capture.empty ()
  Actual: true
Expected: false
tracer plugin not run
Google Test trace:
/home/jenkins/workspace/libelektra/tests/kdb/testkdb_ensure.cpp:180: second ensure
tracer: close(0x55db6b824780,  = )
[  FAILED  ] Ensure.GlobalMount (88 ms)
[----------] 3 tests from Ensure (268 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test case ran. (268 ms total)
[  PASSED  ] 2 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Ensure.GlobalMount

 1 FAILED TEST
```

I think it would make sense to disable the cache only for the test case such that it can run properly.

**Comment by kodebach** [comment]
If I understand the problem correctly, the cache behaviour is wrong IMO. `testkdb_ensure` verifies that mounting a global plugin via `kdbEnsure` works correctly. There shouldn't be a cache hit after mounting a global plugin.

**Comment by mpranj** [comment]
Can you specify why it is wrong?

The cache should store keysets from previous kdbGets. This means that tracer will not be executed on the next get for instance.

Your test checks for some tracer output after the keyset is already cached, but in that case we don’t want to execute tracer (or plugin) again.

**Comment by kodebach** [comment]
The tracer plugin is just used by cause it can be easily checked that it was executed.

What I am talking about, is basically this scenario:
1. The state of the KDB doesn't matter, except that "global plugin X" is not mounted. 
2. `kdbEnsure` is called and "global plugin X" is mounted.
3. There cannot be a cache hit for the next kdbGet() call, because "global plugin X" might influence the result of kdbGet().

If you have some logic that detects whether a newly mounted global plugin would change the result of a kdbGet() call (not sure how that would work though), then we can just rewrite the test case, so that the newly mounted plugin actually has an effect on kdbGet().

**Comment by mpranj** [comment]
**Thank you**, now I understand!

The scenario that I was thinking of: you can never know when something is cached, as we do not specify that. So it is not guaranteed that a global plugin will really be executed when you call kdbGet(), because it might have been cached earlier (even kdbOpen calls kdbGet ...).

What you are saying though, is a scenario that I didn't really think of. I think the cache can not detect that, at least not easily. Even if we know what was mounted before, we do not know the behaviour of the plugin. This means: if "global plugin X" changes behaviour with a future revision, we would have to know this and invalidate the cache. It would not be enough to invalidate all caches when a new plugin is (un)/mounted somewhere. I think this is out of scope for my thesis (@markus2330 ??).

On another note: I think that same problem exists without the cache, since the resolver would report `NO_UPDATE` for the same backends as the cache does. The cache is just always tricky because it persists that same behaviour/error.

**Comment by kodebach** [comment]
> if "global plugin X" changes behaviour with a future revision

Since we don't have proper versioning for plugins, I think solving this is impossible. For now it will probably be enough to invalidate the cache when `kdbEnsure()` is called.

**Comment by markus2330** [comment]
@kodebach thank you for helping out here!
