### ISSUE TITLE
Documentation: Pipeline Syntax URL Only Works for Authenticated Users

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2674]
# Steps to Reproduce the Problem

Execute the following command:

```sh
wget --spider 'https://build.libelektra.org/jenkins/job/libelektra/pipeline-syntax'
```

.

## Expected Result

The document located at https://build.libelektra.org/jenkins/job/libelektra/pipeline-syntax should redirect to the [Jenkins login page](https://build.libelektra.org/jenkins/login), if the current user is not logged in.

## Actual Result

The `wget` command above returns the status “404 Not Found”.

**Comment by markus2330** [comment]
Thank you for reporting! Is this is a bug of Jenkins?

**Comment by sanssecours** [comment]
> Is this is a bug of Jenkins?

I do not know. Maybe it is a security feature. Anyway, the [link checker](https://master.libelektra.org/scripts/link-checker) will report that 

```
https://build.libelektra.org/jenkins/job/libelektra/pipeline-syntax 
```

is a broken link.

**Comment by markus2330** [comment]
I think it is weird that it requires authorization at all. In any case, I do not think there is much we can do about it except of writing a white list for the link checker.
