### ISSUE TITLE
kdb: Support -F for all tools

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2677]
In #2498 the `-F` option was introduced to load config from files. This is basically useful for (nearly) all kdb tools, e.g.:

kdb get -F ini:myfile.ini get /some/key

could get the key /some/key from the file myfile.ini without mounting the file.

**Comment by markus2330** [comment]
I agree with the priority but, as you know, you cannot always choose what gets done first in a free software initiative. And `-F` is very useful for some use cases.

**Comment by markus2330** [comment]
GitHub shows for me my answer before the one of @kodebach?

**Comment by kodebach** [comment]
> GitHub shows for me my answer before the one of @kodebach?

Same here, it seems there is an issue. A similar issue is happening in #2498, there I see my comments before yours...
