### ISSUE TITLE
Memory Checker not set

### ISSUE THREAD

**Issue by Piankero** [ElektraInitiative/libelektra#2692]
When I call `make run_memcheck` I receive the following error message:

```
   Site: wespe-Serval-WS
   Build name: Linux-c++
Memory check project /media/wespe/extended/repository/libelektra/build
Memory checker (MemoryCheckCommand) not set, or cannot find the specified program.
Errors while running CTest
```

I use the latest build of elektra on linux mint 18.2.

Any idea how to fix this?

**Comment by sanssecours** [comment]
> Any idea how to fix this?

Did you maybe forget to install [Valgrind](http://valgrind.org)?

**Comment by Piankero** [comment]
I installed it but still receive the same error message

**Comment by sanssecours** [comment]
> I installed it but still receive the same error message

Did you start with a clean build directory? If that does not help, you can check the value of the variable `MemoryCheckCommand` in the file `DartConfiguration.tcl` inside the build folder:

```sh
grep MemoryCheckCommand DartConfiguration.tcl
#> MemoryCheckCommand: /usr/bin/valgrind
#> MemoryCheckCommandOptions: --trace-children=yes --leak-check=full --gen-suppressions=all --error-exitcode=1
```

.

**Comment by Piankero** [comment]
It was indeed that I needed to install valgrind and to purge the build directory. Thank you @sanssecours !
