### ISSUE TITLE
cache: slowdown on export

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2696]
## Steps to Reproduce the Problem

I have a large multiresolver configuration, from which exports into 24 CSV files are done. (Using `kdb export`)

## Expected Result

That with cache, the previous generation time of 358s will be improved.

## Actual Result

With cache, the exports take longer: 559s

## System Information

- Elektra Version: master

**Comment by mpranj** [comment]
I can not confirm this.

Here's what I did:

```
# Create some large CSVs in current dir
for j in `seq 1 100`; do echo "user/test/$j/name;user/test/$j/other;user/test/$j/something" > $j.csv; for i in `seq 1 1000`; echo "$i:$i;$i" >> $j.csv; done

# Mount the CSVs using multifile and csvstorage
kdb mount -R multifile -c storage="csvstorage",pattern="*.csv",resolver="resolver" `pwd` system/test/

# Clear caches and run some exports
kdb cache clear

time kdb ls system/test > /dev/null
# kdb ls system/test > /dev/null  0.69s user 0.15s system 97% cpu 0.870 total
time kdb ls system/test > /dev/null
# kdb ls system/test > /dev/null  0.24s user 0.12s system 99% cpu 0.360 total
time kdb ls system/test > /dev/null
# kdb ls system/test > /dev/null  0.24s user 0.12s system 99% cpu 0.365 total
```

I do get a speedup by using the cache. Is it possible you used "/" or "system/" when exporting? Maybe something in there can't be cached (#2454).

**Comment by markus2330** [comment]
1. I compared with an Elektra where the cache plugin was not available at all not the first with the second execution (e.g. by not having it mounted or remove the plugin).
2. (Maybe not relevant but) I copied it the other way round: multiresolver+INI is mounted and the export uses `csvstorage`.

**Comment by mpranj** [comment]
Then I think you used a version of Elektra where INI caching was disabled. Caching for ini was enabled in #2604 much later than this issue was opened.

**Comment by markus2330** [comment]
So you think that the way the disabling was implemented caused the slowdown?

**Comment by mpranj** [comment]
I think so, but I'll verify it. The disabling always caused a cache miss and a rebuild of the cache.

**Comment by markus2330** [comment]
This is very plausible.
