### ISSUE TITLE
unify error messages via templates

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2697]
At the moment very similar error/warnings have irrelevant differences or are missing important information (e.g. #2660).

I propose that we get templates (macros with predefined text) for some of the error categories. E.g. for validation errors, in nearly all cases, the error message template could look like:

```
Sorry, the validation of the key '<key>' failed because the value '<value>' is not one of the allowed values '<allowed values>'.
E.g. for the range plugin:
Sorry, the validation of the key '/somewhere' failed because the value '5' is not one of the allowed values '7-9'.
In the code one would use:
ELEKTRA_SET_VALIDATION_ERROR_T(key, value, allowed_values)
```

Of course it would not work with every error message but it would be helpful in common cases.

**Comment by kodebach** [comment]
It is a nice idea, but the use of this macro would be complicated. The `allowed_values` probably has to be constructed out of other parts. Without the macro you can use something like `ELEKTRA_SET_VALIDATION_SEMANTIC_ERRORF(key, "[...] of the allowed values '%d-%d'", min, max)`. With the macro that would require additional malloc/free.

Also I think your template is to restrictive. Many validation plugins just have a condition that the value has to meet (reference to existing key, must be integer, match regex, etc.). Something like this may work better:

```
Sorry, the validation of key `<key>` with value '<value>' failed, because <reason>.
```

Where `<reason>` could be "it doesn't reference an existing key", "the value is not an integer" or "the value didn't match the regex [...]". But this still has the problem of complicated use in many cases.

**Comment by markus2330** [comment]
> The allowed_values probably has to be constructed out of other parts.

As said: not in every situation it is best to use the macro. If you have exactly these arguments, they will help. If one argument is missing, you will hopefully rewrite the code so that you deliver the needed information. (Which is the main purpose of these templates: to give a guideline which information should be present.)

We already have such macros, e.g. ELEKTRA_MALLOC_ERROR and ELEKTRA_SET_ERROR_READ_ONLY, see src/include/kdbmacros.h
They were introduced to make the error handling more consistent.

My proposal here is to unify them and to match them with the categories we have.

> Also I think your template is to restrictive. [...] , because <reason>

We decided to drop the separation of "description" and "reason". Furthermore, "reason" would be typically constructed out of other parts.

**Comment by markus2330** [comment]
For resource errors, it might make sense to have something like:

`ELEKTRA_SET_SYSCALL_ERROR (errno, resource, msg, ..`

With a unified text that prints which resource lead to which errno. (And takes away all the troubles of strerror.)

We could even not have errno as argument, as it is a global (thread-local) variable anyway.

**Comment by Piankero** [comment]
This has already be done for out of memory messages.
An idea has been given in https://github.com/ElektraInitiative/libelektra/pull/3263
This issue though is too big to do for all categories and therefore out of scope as discussed.

**Comment by markus2330** [comment]
It was not discussed that you can leave this out. I said I will look at the text if you already got enough insight.

**Comment by Piankero** [comment]
Sorry for the misunderstanding. I have not meant that this will be "left out" but actually as you said I will work on that to gain insight but I will not finish it for each and every error category

**Comment by markus2330** [comment]
Moved after 1.0.
