### ISSUE TITLE
cascading keys in shell recorder

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2715]
@kodebach wrote:     

> Try using the user namespace for all keys (i.e. user/tests/mac instead of /tests/mac), there are certain problems with cascading keys in shellrecorder tests.

Can you elaborate?

I think validation tests should definitely use cascading keys. We should fix the problems with shell recorder.

(For #2621 we should leave it as-is, though.)

**Comment by kodebach** [comment]
I definite problem is the use of cascading keys with `setmeta`. The cascading key gets resolved to a spec key. Setting this key in the default setup requires root permissions, but AFAIK the shell recorder strips `sudo` from commands.

**Comment by markus2330** [comment]
> AFAIK the shell recorder strips sudo from commands.

Yes, it strips sudo but on the build server setting to all namespaces (also spec) works.

@sanssecours can you remember when cascading keys made problems? Is there some way to fix the shell-recorder to avoid this problem?

**Comment by kodebach** [comment]
> Yes, it strips sudo but on the build server setting to all namespaces (also spec) works.

True, but the tests should work on all machines not just the build server.

**Comment by markus2330** [comment]
Unfortunately, there are always some limitations: either on realism (everything is tested as it would work in real systems) or scope (parts that modify the system are not tested). Elektra's purpose is to modify the system.

Btw. also `kdb mount` modifies `system`, so writing to `spec` is not so much different.

**Comment by sanssecours** [comment]
> can you remember when cascading keys made problems?

One problem is the different output from commands such as `kdb set` and `kdb ls`.

>  Is there some way to fix the shell-recorder to avoid this problem?

An option to fix the issue above would be to add regex support to the `#> ` directive.
