### ISSUE TITLE
Improve qt-gui error message popup

### ISSUE THREAD

**Issue by Piankero** [ElektraInitiative/libelektra#2717]
Currently if an error happens in the QT-GUI it looks as follows:
![qt-gui-error](https://user-images.githubusercontent.com/12346621/58271500-7696d280-7d8c-11e9-9e39-e0b83ffd4e26.png)

Unfortunately the message is not very useful or even misleading as synchronization actually has nothing to do with the underlying error.

The error message should be similar to the WEB-GUI (see [here](https://github.com/ElektraInitiative/libelektra/pull/2704#issuecomment-493793789) as an example).

The `Synchronizing failed, ...` message should be replaced by the first two lines of the error message whereas the details expansion should show the `At`, `Configfile` and `Mountpoint`.

Simply [this line](https://github.com/ElektraInitiative/libelektra/blob/4f66fe62cb38cd7f30df9cf5d5d1de01bf408218/src/tools/qt-gui/src/treeviewmodel.cpp#L665) should be changed accordingly.

**Comment by markus2330** [comment]
@0003088 are you interested in tackling this issue?

**Comment by 0003088** [comment]
Yes I will look into it this week.

**Comment by markus2330** [comment]
Thank you **very much**!

**Comment by markus2330** [comment]
@0003088 is this resolved? Is everything you did merged now? Any further work planned by you?

**Comment by 0003088** [comment]
As far as I can remember this problem was solved. I thought somebody else is
rewriting the gui for KDE?

**Comment by markus2330** [comment]
Yes, @darddan is updating the qt-gui for the latest widgets. But this does not mean that your collaborations are not welcomed :wink:
