### ISSUE TITLE
Debugging testcases on specialized distributions

### ISSUE THREAD

**Issue by Piankero** [ElektraInitiative/libelektra#2718]
I am having a problem with a testcase on a the "Haskell" run on Travis 
(see [here](https://travis-ci.org/ElektraInitiative/libelektra/jobs/532370865)).

On every other distribution and system the testcase `CharTestSet` works fine but on the specific system it causes a SegFault.

Since I am not having a mac I cannot easily debug this testcase. How would you proceed in such a case? Is there a special docker image which can be used?

Any help would be appreciated!

**Comment by sanssecours** [comment]
> How would you proceed in such a case?

1. Sign up for a [Travis](https://travis-ci.com) account, if you have not done so already. This allows you to test commits on your own clone of the repository.
2. Remove all build jobs that you do not need from the list `matrix/include` in [`.travis.yml`](https://master.libelektra.org/.travis.yml). After that the interesting build job `🍏 Haskell` should more or less start instantly.
3. Check which commit introduces the problem:
   1. Clone the base of the branch that contains the problematic code
   2. Cherry pick commits, or rebase on a certain commit that you think introduces the problem
   3. Push your changes and check if Travis reports errors or not
4. After you found the problematic commit you can check (for example via logging), which statements cause the segfault.

All of this will probably take quite some time though. I would recommend you work on something different while you wait for a certain Travis build job to finish.

> Is there a special docker image which can be used?

Nope. As far as I know, Docker only supports Linux as “guest” OS.

**Comment by Piankero** [comment]
Thank you very much for the suggestion. It helped me to speed up debugging a lot despite you did the major work here :)
