### ISSUE TITLE
have clear responsibility, who sets errors

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2726]
For plugins we have a well-defined interface (plugins must set an error if they return -1) but for functions from libs this responsibility currently is not so clear:

- [ ] elektraModulesLoad sets warnings but no errors
- [ ] elektraPluginOpen sets warnings but no errors
- [ ] elektraInvokeOpen might set warnings but no errors, even though it has documented that "errorKey a key where error messages will be stored"
- [X] elektraGetOpts sets errors

as we now can transform every error to a warning easily, we could let the function set an error (normal case) and *if* the caller has some workaround, the caller can transform the error to a warning. This seems to be more robust than trusting that the callee sets the errors (which often does not happen, e.g. elektraSpecloadOpen if elektraInvokeOpen failed).

The docu of these functions and doc/CODING.md also needs to be updated to reflect the new error concept.

**Comment by Piankero** [comment]
Not related to visible error messages.
As discussed in the Elektra meeting I may unassign myself.
