### ISSUE TITLE
multifile: swallows keys not belonging to a file

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#2741]
The `multifile` plugin swallows keys which do not belong to a real backend. This happens for instance, when we have a multifile mountpoint at `system/test/x` with a file mounted at `system/test/x/a` but want to write a key `system/test/x/b`.

## Expected Result

Error messsage or key written to default mountpoint.

## Actual Result

No error and key is lost.

**Comment by markus2330** [comment]
Thank you reporting the problem!

Wouldn't it be better if the multifile plugin would simply create files?

Also a `kdb -r` in multifile does not what you would expect: it simply does nothing.

**Comment by mpranj** [comment]
> Wouldn't it be better if the multifile plugin would simply create files?

That's much better and it is what I would expect without reading any documentation.
