### ISSUE TITLE
kdb export: no -vd

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2743]
## Steps to Reproduce the Problem

I execute an export that does not work:

```sh
kdb export -vd ...
```

## Expected Result

That I get an detailed error message.

## Actual Result

```sh
Sorry, module csvstorage issued the error 117:
invalid number of columns: illegal number of columns (8 - 9) in line 6
```

which does not contain the additional error information, or:

```sh
kdb: invalid option -- 'v'
kdb: invalid option -- 'd'
Sorry, I could not process the given options (see errors above)
```

Please check for all tools if they actually accept -v and -d and work.

## System Information

- Elektra Version: master

**Comment by Piankero** [comment]
This to be honest looks like a bug in the cmdline.pp ad `export.cpp` correctly uses the command line args.

I debugged it to [this](https://github.com/ElektraInitiative/libelektra/blob/2c6f1263b9a8801118c4ca4a8daf82bf5833b476/src/tools/kdb/cmdline.cpp#L483-L485) section where `d` and `v` are treated as illegal option despite explicitly be checked in the case statement.

When I add the following line: 
```
cerr << "Opt:" << opt << endl;
```
i always receive the following output when taking `v` or `d`:
```
Opt:63
```

Do you have a hint for me? This seems to be a C related error?

**Comment by markus2330** [comment]
It is simply about that not all command-line tools accept -v or -d, although it is now essential with the new error concept.

To add a command-line option to every tool, it must be added in cmdline.cpp line 59 (allOptions).

Then individual vd can be removed from the header files (getShortOptions).

**Comment by Piankero** [comment]
This was fixed with the merge
