### ISSUE TITLE
rename rest-front/backend to website

### ISSUE THREAD

**Issue by dmoisej** [ElektraInitiative/libelektra#2747]
Related to the documentation:
https://www.libelektra.org/tutorials/snippet-sharing-rest-service

As it is said

> The backend requires the most dependencies and unfortunately some of them need to be installed manually because no APT packages are available.
The required dependencies with their own dependencies are:
CppCMS >= v1.0.0
Zlib library
PCRE library
Python >= v2.4 (but not v3)
ICU library >= v3.6
gcrypt or OpenSSL library
Boost >= v1.45
OpenSSL
LibJWT >= v1.5
Jansson
OpenSSL

I am using Ubuntu 16.06 by myself.  The problem appears while installing CppCMS. I tried to install it manually, so to download from the repository, untar, execute cmake and make in the build folder. 

As a result I couldn't install CppCMS becuase I had errors during make command. After investigating I figured it out, that it is recommended to have gcc and g++ compilers of version up to 4.3 but Ubuntu 16.06 doesn't support this version and I couldn't install the older versions of gcc and g++, so the minimal version, that I could install was 4.7. Anyway, the cppcms package didn't want to compile and as a result I can not start  compile the libelektra with the following command:

`cmake -DTOOLS="ALL;rest-backend;rest-frontend" -DPLUGINS="yajl" ..` 

It reported me, that the CppCMS package does not exist.

So as a result, I suppose it is not possible to install all those dependencies for the Shared Snippets on the latest Ubuntu versions.

**Comment by sanssecours** [comment]
Thank you for the bug report. As far as I can tell from the [nightly build report of CppCMS](http://cppcms.com/files/nightly-build-report.html), it looks like building the framework with

- Clang 3.8,
- Clang 4.0,
- GCC 5.4, and
- GCC 5.4/C++11

on Ubuntu `16.04` should work. Can you please also add the error messages reported by `make` to the issue?

**Comment by dmoisej** [comment]
I have installed clang 3.8 and gcc 5.5. After I execute the make I get the following problems:
![cppcms_error](https://user-images.githubusercontent.com/32390104/58870197-052a1e80-86c0-11e9-854e-f22a15e0f9f9.png)

And as a result there is long list of errors like the specific symbol or variable _was not declared in this scope_

**Comment by markus2330** [comment]
Thank you for reporting this problem! Cppcms is an external tool, this bug should be reported to 
https://github.com/artyom-beilis/cppcms/issues

But as already written by EMail, I think you actually want [elektrad](https://github.com/ElektraInitiative/libelektra/blob/master/doc/api_blueprints/elektrad.apib) and not the snippet sharing. Elektrad "only" needs nodejs/npm, so it should be easy to run it.

I updated the docu to clarify the differences in 9c3ba9829dd17108020a7c00e2cebee642732146

What we actually should do is to move "rest-backend" and "rest-frontend" to a folder "website". Then people might be less likely to confuse it as a REST service that provides a get/set interface of configuration (which it is *not*, it is to share snippets).

@Namoshek do you think we can simply move these folders? Or do you remember potential problems we will face then?

**Comment by dmoisej** [comment]
@markus2330, yes, you are right, I just need [elektrad](https://github.com/ElektraInitiative/libelektra/blob/master/doc/api_blueprints/elektrad.apib) and no shared snippets. I just wanted to describe the issue, that I faced.

**Comment by markus2330** [comment]
Ok, thank you for the report! I wrote about it in https://github.com/artyom-beilis/cppcms/issues/60

**Comment by Namoshek** [comment]
> @Namoshek do you think we can simply move these folders? Or do you remember potential problems we will face then?

Not sure. I think we designed the CMake build in a way that will survive a folder move. The grunt tasks are based on a configuration that is generated from CMake.

**Comment by markus2330** [comment]
Thank you for the quick reply!

Then we'll leave the ticket open for this move (at least to try if the move causes any troubles).

**Comment by artyom-beilis** [comment]
You are building an old CppCMS 1.0.4. You need to use 1.2.1 - it is the stable and well tested release.
