### ISSUE TITLE
cabal legacy build

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#2749]
There has been an update to Haskell build system `cabal`. The Travis build log notes:

>Warning: The update command is a part of the legacy v1 style of cabal usage.
Please switch to using either the new project style and the new-update command
or the legacy v1-update alias as new-style projects will become the default in
the next version of cabal-install. Please file a bug if you cannot replicate a
working v1- use case with the new-style commands.
For more information, see: https://wiki.haskell.org/Cabal/NewBuild

(there are a lot more warnings for all the other commands)

See for example: https://travis-ci.org/ElektraInitiative/libelektra/jobs/539281372

**Comment by markus2330** [comment]
Thank you for reporting this problem!

@e1528532 can you take a look?
