### ISSUE TITLE
Weird issues on Travis Xcode10.1

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#2751]
There is some weird issue that appears only on Travis, when using the Xcode10.1 image.
It is not related to Haskell. @Piankero also tried builds with `HASKELL=OFF` and the same problems occurred.

Examples:
- https://travis-ci.org/ElektraInitiative/libelektra/jobs/541493536
- https://travis-ci.org/ElektraInitiative/libelektra/jobs/538852056

After fixing #2749 the Haskell builds might work on macOS 10.14, which would probably fix the issues.

**Comment by markus2330** [comment]
As @e1528532 seems to not respond, I think we need to remove the haskell build jobs (and discourage the plugins using Haskell)

**Comment by kodebach** [comment]
I already disabled the haskell build job in #2707.

**Comment by markus2330** [comment]
> I already disabled the haskell build job in #2707.

I wrote an email to @e1528532.

> It is not related to Haskell.

Please elaborate: How can this be if it is related to #2749?

**Comment by kodebach** [comment]
> Please elaborate: How can this be if it is related to #2749?

The weird issues also occur, if Haskell is disabled. However, if all the Haskell stuff gets an update, it might be possible to build the Haskell plugins with macOS 10.14. Under macOS 10.14 the issues don't seem to exist.

**Comment by markus2330** [comment]
I hope this gets fixed with #3017?

**Comment by markus2330** [comment]
Haskell was removed.
