### ISSUE TITLE
wrong storage plugins might lead to very poor error messages

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2753]
## Steps to Reproduce the Problem

I accidentally mounted a quickdump file as dump file:

```sh
kdb mount `pwd`/file.qd /tests # quickdump
kdb ls /tests
```

I think something like this can easily happen, it is a rather typical error. (Especially as long as "dump" is default).

## Expected Result

That I get a nice error message that this is maybe a wrong file format. Ideally it should even say that a solution might be to remount the file with a different plugin.

## Actual Result

```
Sorry, module dump issued the error 49:
unknown command detected in dumpfile: EKDB
```

## System Information

- Elektra Version: master

**Comment by Piankero** [comment]
I changed the error message as following:
https://github.com/Piankero/libelektra/blob/1984018672a0fc0ca62ffbfd73213025fd4289ce/src/plugins/dump/dump.cpp#L191-L195

If you think this is enough feel free to close the ticket

**Comment by markus2330** [comment]
Yes, the text is okay but I keep it open as these needs to be changed again when the SOLUTION macro exists.

To give "dump" as example does not make sense: dump is the plugin that failed.

**Comment by Piankero** [comment]
If the user mounts with `ini` but it is a dump file then probably this is the correct format.

**Comment by markus2330** [comment]
I was refering to

https://github.com/Piankero/libelektra/blob/1984018672a0fc0ca62ffbfd73213025fd4289ce/src/plugins/dump/dump.cpp#L191-L195

here we know that the user tried dump and dump is wrong.

**Comment by Piankero** [comment]
Since "Solution" will not be implemented because of controversy in scientific literature this ticket does not need to stay open anymore
