### ISSUE TITLE
Cirrus Link Checker

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#2758]
The Cirrus link checker task should be run on the merged version of a PR. I.e. it should checkout `master`, merge the PR branch into master and then run the check. This currently not the case and therefore PRs that are based on a commit of `master` that contains a broken link (whether originally broken, or only recently) has to be rebased in order for the check to succeed.

For an example of a failing check see #2707. There the link checker complains about the link https://www.fishshell.com, which should be https://fishshell.com. This has been fixed on `master`, but the link checker will keep complaining, until the PR is rebased, even though in a merge the fixed link from `master` would be unchanged.

Alternatively, we could run the link checker only on changed lines, but that would probably be more complicated.

**Comment by markus2330** [comment]
Thank you very much for reporting this problem!

Is there someone who has time to fix this?
