### ISSUE TITLE
kdbconfig.h macro conflicts

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#2759]
The `DEBUG` macro (used to indicate debug mode) should not be defined in `kdbconfig.h`. Instead it should injected by the compiler via CMake.

This is because `kdbconfig.h` is a public header that will be included in applications using Elektra. However, in such a case the `DEBUG` macro might conflict without an application's `DEBUG` macro (see for example LCDproc).

This also means `DEBUG` should not be used in any other headers that are `install`ed via CMake. Currently this is already the case AFAIK.

**Comment by kodebach** [comment]
The same is actually true for all of the `HAVE_*` macros as well as the `VERBOSE` macro.

The `SIZEOF_*` macros have the same problem, but they are needed in `kdbtypes.h`, so we probably have to rename or modify `kdbtypes.h`.

**Comment by markus2330** [comment]
Thank you for reporting the problem!

kdbconfig.h was always intended to be a **private internal** header file, it should not be included in user code.

Why do you include it there?

**Comment by kodebach** [comment]
I am not including it directly, but it is included by some of our public headers. Including `kdbtypes.h`.

**Comment by markus2330** [comment]
I see. kdbtypes.h was initially also not meant for public use. But as we have it now in the API it obviously needs to be exposed. I think the best way forward here is to split kdbconfig.h to:

- an internal kdbconfig.h with everything that we query via cmake
- a public kdbconfig.h (with different name) that has the former SIZEOF_ macros (and maybe some other things externally needed) but always prefixes all macros with ELEKTRA_

**Comment by kodebach** [comment]
I think we should also move all the internal (i.e. not installed) headers in `src/include` into `src/include/internal` so it is more obvious which headers are installed and which aren't without looking at the CMakeLists file. Then this problem shouldn't arise in future, or at least we would notice it beforehand.

**Comment by markus2330** [comment]
I totally agree!
