### ISSUE TITLE
Choosing the right crypto library

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#276]
As @markus2330 pointed out to me, the same plugin can be instanciated several times, which makes global initialization and teardown impossible.

Libgcrypt requires global initialization calls like ```gcry_check_version(GCRYPT_VERSION)``` and ```gcry_control(GCRYCTL_INITIALIZATION_FINISHED, 0)```. The gcrypt manual suggests to **NOT place this initialization code within a library** as it does some internal thread setup and other stuff, but rather put it in the application that is using the library. [0] This would mean that Elektrifikation is becoming a pain in the... if you want to use the crypto plugin.

I suggest dropping libgcrypt completely and use **libcrypto** provided by the OpenSSL project instead. It has a much nicer API anyway and does not need initialization at all. All handles can be created within the encryption and decryption functions and no global implications are to be expected. The only disadvantage is that libcrypto is not FIPS-140 validated by default. [1] On the other hand, many other applicatins rely on libcrypto and I think applications with higher security demands are being reviewed anyway.

Do you folks have any thoughts on that topic? Every input is appreciated!

[[0](https://www.gnupg.org/documentation/manuals/gcrypt/Initializing-the-library.html#Initializing-the-library)] https://www.gnupg.org/documentation/manuals/gcrypt/Initializing-the-library.html#Initializing-the-library
[[1](https://www.openssl.org/docs/fipsnotes.html)] https://www.openssl.org/docs/fipsnotes.html

**Comment by markus2330** [comment]
Not having the need for global initialization is important, especially within libraries (and *especially* those with plugin systems). Unfortunately, many APIs are not designed properly.

libgcrypt is not be the first library in Elektra with this problem. The other is the java plugin, and later the python plugin. E.g. Python's C API is quite broken, but they have at least the workaround that calling Py_Initialize() again will only lead to nops. (Obviously this does not fix everything: Its still prone to race conditions and python might be initialized with wrong arguments.) Java supports attaching to an already running VM.

Maybe the best thing is, especially considering that your libgcrypt plugin looks quite finished, to have both. You already have the API in place to additional provide libcrypto. Of course, if you find one to be vastly superior, we should get slowly get rid of the other one. (Similar to GI-bindings)

@manuelm Maybe we have to think about your proposal again. @manuelm said that we should have a kdbInit() that needs to be called once at top-level of an application. In it, callbacks of plugins which use libraries with such limitations, are executed. This kdbInit(), however might not solve the problem if the application needs java/python/libgcrypt itself. And it obviously is unable to work within other plugins which never know if kdbInit() was already called earlier. Basically, it is only a workaround.

**Comment by markus2330** [comment]
Btw. you could (and should) select pros and cons, if you like in the format of `doc/decisions/` (choose requirements, search for everything that could be used,... ). We can discuss this topic in the next meeting, but I am afraid you won't learn much, you are likely to be the most experienced in these libraries.

**Comment by markus2330** [comment]
You mentioned that `libcrypto` has a a global mutex-initializer. Is it really required or is it only a way to use an alternative mutex? (Such a feature is often available for alternative malloc implementations)

**Comment by petermax2** [comment]
In version 1.0.2 of OpenSSL `libcrypto` still requires two callbacks to be set to be thread-safe:

    CRYPTO_THREADID_set_callback(pthreads_thread_id);
    CRYPTO_set_locking_callback(pthreads_locking_callback);

The signature of `pthreads_locking_callback` looks like this:

    void pthreads_locking_callback(int mode, int type, const char *file, int line)

where `type` is a number between 0 and `CRYPTO_num_locks() - 1` and `mode` is either lock or unlock. 
`file` and `line` are hints for debugging.

The `pthreads_thread_id` callback sets the ID of the current thread (as the name suggests) and its signature looks like this:

    void pthreads_thread_id(CRYPTO_THREADID *tid)

The implementation of this function is not a problem. However, locking and unlocking the right mutex across multiple crypto-plugin instances could be tricky.

Altough I used pthread as example here, the callbacks are independant of the thread implementation.

There is also a dynamic locking facility in OpenSSL but it is not used by now.

You can read the full story of OpenSSL and thread-safety [here](https://www.openssl.org/docs/man1.0.2/crypto/CRYPTO_set_locking_callback.html).

@markus2330 where is the right place to put the setup of the mutexes and where do we put the initialization of the callbacks for `libcrypto`?

**Comment by markus2330** [comment]
@petermax2 Is it possible to check if the setup already occurred? Then its easy, just check it in `cryptoPluginOpen()` and only setup if not done before. Then applications simply have to do the setup before the first kdbOpen() or not at all. (Which is not ideal, but a limitation we can live with).

In any case: its best if you ask in the mailinglists if their library is intended to be used within a library where you do not know if someone else is using the library, too. Make sure to mention that the usage is within a plugin.

Because maybe a resetup does not hurt anyway? Then we dont have to worry at all. The developers should know these details.

**Comment by petermax2** [comment]
I had a look into `libcrypto`'s source code. `CRYPTO_set_locking_callback` really just sets the function pointer internally BUT it also calls `OPENSSL_init()` which by now is only relevant if OpenSSL is compiled FIPS-compliant mode.

We could also check if the callbacks have been initialized. `CRYPTO_get_locking_callback` is not documented but declared in `crypto.h`, so it should be safe to call it and compare its result against NULL. Any objections? :)

**Comment by markus2330** [comment]
You should ask, they might have plans to remove it in the future, especially if it is not documented.

**Comment by petermax2** [comment]
@markus2330 not neccessary, I found the answer in the OpenSSL wiki [[1]](https://wiki.openssl.org/index.php/Libcrypto_API#Thread_Safety):

> Currently the only moderately safe way for libraries using OpenSSL to handle thread safety is to do the following as early as possible, possible in .init or DllMain:
> - Check if the locking callback has been set, then set it if not;
> - CRYPTO_w_lock(CRYPTO_LOCK_DYNLOCK), set the remaining callbacks (threadid, dynlock, and add_lock) if not already set, then CRYPTO_w_unlock(CRYPTO_LOCK_DYNLOCK);

The earliest point for initialization is still `ELEKTRA_PLUGIN_OPEN`, right? Some sort of global initialization in Elektra would be really nice.

[[1] https://wiki.openssl.org/index.php/Libcrypto_API#Thread_Safety](https://wiki.openssl.org/index.php/Libcrypto_API#Thread_Safety)

**Comment by markus2330** [comment]
Global initialization is only nice for us, but not for the users. (Which would have the problems we have with OpenSSL.) Yes, PluginOpen would be the place to do it.

**Comment by petermax2** [comment]
see PR #427
