### ISSUE TITLE
kdb rm /..: removes spec key

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2761]
## Steps to Reproduce the Problem

Assume that `spec.ini` is in pwd and contains:
```ini
[]
mountpoint = mymountpoint.ini

[mykey]
type = long
```

```sh
sudo kdb mount `pwd`/spec.ini spec/tests/hello ni
sudo kdb spec-mount /tests/hello

kdb set /tests/hello/mykey 123
kdb rm /tests/hello/mykey
```

## Expected Result

That I removed what I've set just before.

## Actual Result

The spec key is removed, `spec.ini` then contains:
```ini
;Ni1
; Generated by Nickel Plugin using Elektra (see libelektra.org).

 = 

[]
 mountpoint = mymountpoint.ini
```

Interestingly, the validation then still fails and `kdb meta-get /tests/hello/mykey type` still returns `long`.  But this might be a different mmap-related bug (#2760).

## System Information

- Elektra Version: master

**Comment by kodebach** [comment]
> kdb getmeta /tests/hello/mykey type still returns long

That may be because of #2700.  It may also be related to #2456.

**Comment by markus2330** [comment]
Thank you for making the connections.

**Comment by markus2330** [comment]
As this bug might lead to accidental removal of wrong data, we should fix it. I updated the initial description to use meta-get.

Also the to-be-believed-mmap-related bug still can be reproduced with Elektra 0.9.2.

**Comment by kodebach** [comment]
@markus2330 Does this bug still exist? Should we reopen the issue?

**Comment by markus2330** [comment]
#3742 should fix it.
