### ISSUE TITLE
integrate kdbEnsure into kdbOpen

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2764]
see #868 for previous discussions.

**Comment by kodebach** [comment]
see #3549

**Comment by markus2330** [comment]
Is something more to discuss or is it clear how to integrate kdbEnsure into kdbOpen?

Anyway, #2963 should be merged first.

**Comment by kodebach** [comment]
I don't think there is anything to discuss, but it's still to be implemented. I switched the issue from `proposal` to `enhancement`.
