### ISSUE TITLE
highlevel: guarantee that elektraGet succeeds

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2765]
As written in  #2382 we want to guarantee that elektraGet always succeeds.

There are different point of times when type checking can take place:

1. during kdbSet: Of course it is always better to never make configuration mistakes persistent. But Elektra cannot guarantee that in some way or another the type checking is circumvented.
2. during elektraOpen: here we can guarantee that type checking is not circumvented by:
    - use built-in spec if no spec is provided
    - fail if type plugin is not available
    - fail if the type plugin reports warnings/errors

**Comment by kodebach** [comment]
Before we can discuss this issue we need to clarify one thing: Are we talking about the highlevel API by itself or are we talking about the highlevel API in combination with code-generation? The ideal and also the possible solutions are very different for the two cases...

**Comment by markus2330** [comment]
Actually, the guarantees should be nearly the same except that the one without code generation fails if spec is missing (and, of course, cannot provide type safety).

If there are further differences: let us concentrate on the one with code generation as it is the recommended way to use the highlevel API.
