### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by omnidan** [ElektraInitiative/libelektra#278]
* https://github.com/ElektraInitiative/libelektra/tree/master/src/tools/gen#commandline-arguments - `here` is a broken link

 * https://github.com/ElektraInitiative/libelektra/tree/master/src/tools/qt-gui#installing - `install documentation` is a broken link

 * all links in the `qt-gui` README seem to be broken too

**Comment by markus2330** [comment]
Can you send me a pull request with fixes?

**Comment by omnidan** [comment]
* I couldn't find the file for the first link: https://github.com/ElektraInitiative/libelektra/search?utf8=%E2%9C%93&q=visit_context.cpp

 * seems like the `qt-gui/doc` folder moved

 * `COMPILE.md` in the `qt-gui` folder and other files seem to have moved too

**Comment by markus2330** [comment]
Thank you for reporting! I have fixed the 3 broken links. Please report if there are more..
