### ISSUE TITLE
resolver: solution on non-permission errors wrong

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#2780]
Segmentation fault when file descriptor limit is exceeded.

**Comment by mpranj** [comment]
@markus2330 I fixed a different bug (multifile+cache), and now I *sometimes* get the following error:

```
[... lots of single resolver errors (multifile loop), then: ...]
Sorry, module resolver issued the error 26:
could not open configuration file. You might want to try as root (use sudo !!).: Could not reopen configuration file "/home/mpranj/workspace/libelektra/build/multi/124" for writing because "Too many open files"
```

It then started to do some undefined behaviour stuff. I **found the real problem** to be a wrong resolver handle. The multifile resolver calls the resolver with the multifile handle, and not the resolver handle. Of course it's going to fail. :man_facepalming: 

Now it consistently fails with the more helpful "too many open files" error message.

**Comment by markus2330** [comment]
Perfect, thank you so much!

@Piankero the solution suggested here is completely wrong. The solution "You might want to try as root" only make sense if errno says it was a permission error.

For this concrete error, the correct solution would be to increase the maximum allowed file handles. To get this solution is luxury but we definitely should not give wrong solutions.

**Comment by Piankero** [comment]
I removed the solution with #2686
