### ISSUE TITLE
Writing Java Plugin

### ISSUE THREAD

**Issue by dmoisej** [ElektraInitiative/libelektra#2785]
Right now, I am trying to follow the steps here: https://www.libelektra.org/plugins/jni, in order to enable Java plugins into Elektra. The problem is, that executing the following command:

`
kdb info -c classname=elektra/plugin/PropertiesStorage,classpath=.:/usr/share/java/jna.jar:/usr/lib/java:/path/to/libelektra/src/bindings/jna,print= jni`

I get the error:

> Module does not seem to be loaded.
> Now in fallback code. Will directly load config from plugin.
> The command kdb info terminated unsuccessfully with the info:
> You entered a bad name (classname=src/bindings/jna/libelektra4j/src/main/java/org/libelektra/plugin/Echo,classpath=/usr/share/java/jna.jar:/usr/lib/java:/home/dmoisej/Projects/dmoisej/libelektra/src/bindings/jna,print=jni) for a plugin!
> A valid name of a plugin is either
> modulename or modulename#refname
> where both modulename and refname must start with a-z
> and then a-z, 0-9 and underscore (_) only
> Please report the issue at https://issues.libelektra.org/

In my case I am trying to execute the command from the libelektra folder and my command is:

``` sh kdb info classname=src/bindings/jna/libelektra4j/src/main/java/org/libelektra/plugin/Echo,classpath=/usr/share/java/jna.jar:/usr/lib/java:/home/dmoisej/Projects/dmoisej/libelektra/src/bindings/jna,print=jni```

If I use -c after the ```info```, then the error is:

> Sorry, I could not process the arguments: Need 1 or 2 argument(s)
> 
> Usage: kdb info <plugin name> [<clause name>]
> 
> Print information about a plugin.
> Print out the information of a specific plugin's contract.
> 
> E.g.
> Print out all information about dump plugin:
>  kdb info dump
> 
> Print out the licence of the resolver plugin:
>  kdb info resolver licence
> 
>

**Comment by markus2330** [comment]
Thank you for creating the issue!

It should be irrelevant where you put the -c, but you cannot invoke it with `sh kdb` because `kdb` is not a shellscript.

What happens if you simply type `kdb info jni`?

@Piankero did you have a similar problem or know where the problem is here?

**Comment by dmoisej** [comment]
@markus2330 by running 
`kdb info jni` 
I get normal output
![image](https://user-images.githubusercontent.com/32390104/59535375-13164580-8ef1-11e9-9556-dc0dc9be8d39.png)

I will try to investigate this issue more

**Comment by markus2330** [comment]
Seems like you somehow have wrong quoting or similar when you use `-c`.
