### ISSUE TITLE
Improving Java Binding

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2786]
As suggested, some improvements for the Java Bindings:

- [x] implements toString
- ~~[ ] implements Serializable~~
~~- [ ] implements Map<K,V> or similar~~
- ~~[ ] implements Cloneable~~
- [x] and others to make Key/KeySet/KDB more Java-like
~~- [ ] integrate new error message concept (specific exceptions where possible and sensible)~~
- [x] create new issue for evaluating to integrate notification for Java bindings, see 4441
- [X] bindings for gopts
- [x] Java Tutorial should also be improved, see #2778
- [x] improve API docu #3754
- [x] improve tutorials #1083

**Comment by markus2330** [comment]
@Piankero I added two points above:

- upload to maven central
- integrate new error message concept

uploading to maven central is debatable but it would be a really big gain for Elektra.

**Comment by Piankero** [comment]
Not related to visible error messages.
As discussed in the Elektra meeting I may unassign myself.

**Comment by markus2330** [comment]
I moved
- [ ] upload to maven central
to #3519

to keep this issue only related to improving the Java binding.

**Comment by tucek** [comment]
> Can you please check which parts are already done?

yes! i'm not sure whether we really need this ticket anyways, since all java related tickets should be assigned to the "Java bindings overhaul" project

**Comment by markus2330** [comment]
> i would close this ticket if all open tasks have a corresponding issue. Would that be ok with you?

Yes, this is perfectly okay, too!

**Comment by kodebach** [comment]
> Should we consider to implement `Map<String, Key>` for `KeySet`?

If we do, we should implement `SortedMap` or `NavigableMap`. But I think implementing `Set` and `Map` could be confusing. We should decide on one of them.

> Do we really need this? 

I don't think we need `Cloneable`. We have `keyDup`/`ksDup` whose semantics might be slightly different. Adding `Cloneable` could cause confusion.

> bindings for notification

I have no idea, what this entails exactly. But I think the `process` protocol is not related here. AFAIK the notification stuff uses plugins, but the receiving side just uses a library.

> I would create a new issue for that

I would agree. This is probably much more work than anybody expects. AFAIK the notification stuff was only tested with C/C++ code.

**Comment by tucek** [comment]
Closing this issue, since all valiid tasks have been completed.
