### ISSUE TITLE
https://restapi.libelektra.org/ empty

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2789]
It seems like after restart of the build server https://restapi.libelektra.org/ is down. The link checker fails because of this.

Hopefully rebuilding elektra-homepage fixes this problem. I triggered the build now.

**Comment by markus2330** [comment]
Building elektra-homepage fixed the problem. https://doc.libelektra.org/restapi/0.8.26/snippet-sharing.html is, however, blank in my browser. Did apiary.io change something?

**Comment by kodebach** [comment]
> Building elektra-homepage fixed the problem. https://doc.libelektra.org/restapi/0.8.26/snippet-sharing.html is, however, blank in my browser. Did apiary.io change something?

It works for me. Do you have Javascript enabled?
