### ISSUE TITLE
kdb qt-gui: command not found

### ISSUE THREAD

**Issue by omnidan** [ElektraInitiative/libelektra#279]
*Running `kdb qt-gui` does not seem to work.*

 * First of all, I tried compiling elektra with `-DTOOLS=ALL` and then executing `./kdb qt-gui` - that didn't work though.

 * Then I ran `sudo make install`, which installs `kdb` globally. Running `kdb qt-gui` still doesn't seem to work, it just prints `The command qt-gui is not known` and the help page.

 * What I ended up doing is compile `qt-gui` separately with QT Creator. I was missing `libmarkdown2-dev` though (not part of the dependency list). After installing that the gui compiles and runs fine, though.

Make sure running `kdb qt-gui` works in the release. If we're putting the `qt-gui` in a separate package, please let me know so I can add the package name to the new Quickstart section.

**Comment by markus2330** [comment]
Thanks, it would be useful to describe external tools in a tutorial, too.

```sh
kdb list-tools
```
prints as first line where the tools are searched. It only will work when Elektra is installed on the system.

So only if qt-gui is installed in the above path, `kdb qt-gui` will work.

Can you check if this was the case? Maybe there is a bug with a some ressources not correctly installed?

**Comment by omnidan** [comment]
The directory was `/usr/local/lib/elektra/tool_exec`, I checked and `qt-gui` wasn't there. After manually copying the `qt-gui` executable there, running `kdb qt-gui` works fine.

**Comment by markus2330** [comment]
Any idea why `sudo make install` did not copy qt-gui?

**Comment by omnidan** [comment]
I'll try it again. `cd build; cmake -DTOOLS=ALL ..; make; sudo make install` should be fine, right?

I had a problem while uninstalling, by the way. I just manually removed `qt-gui` from the directory to test it.

```
CMake Error: Error processing file: /home/dan/libelektra/cmake/cmake/ElektraUninstall.cmake
cmake/CMakeFiles/uninstall.dir/build.make:49: recipe for target 'cmake/CMakeFiles/uninstall' failed
make[3]: *** [cmake/CMakeFiles/uninstall] Error 1
CMakeFiles/Makefile2:943: recipe for target 'cmake/CMakeFiles/uninstall.dir/all' failed
make[2]: *** [cmake/CMakeFiles/uninstall.dir/all] Error 2
CMakeFiles/Makefile2:951: recipe for target 'cmake/CMakeFiles/uninstall.dir/rule' failed
make[1]: *** [cmake/CMakeFiles/uninstall.dir/rule] Error 2
Makefile:545: recipe for target 'uninstall' failed
make: *** [uninstall] Error 2
```

**Comment by markus2330** [comment]
What is the content of /home/dan/libelektra/cmake/cmake/ElektraUninstall.cmake?

You also can install somewhere else using DESTDIR, e.g.

    DESTDIR=x make install

**Comment by omnidan** [comment]
After rebuilding it like that it seems to work fine. It was probably that I didn't have some dependencies yet and I installed them in the process of compiling `qt-gui` manually.

`/home/dan/libelektra/cmake/cmake/ElektraUninstall.cmake` does not exist, the correct path is `/home/dan/libelektra/cmake/ElektraUninstall.cmake`

**Comment by markus2330** [comment]
Did you check the cmake output? Maybe the qt-gui was excluded from build? (e.g. because of libmarkdown missing)

**Comment by omnidan** [comment]
@markus2330 I did not check it and I don't have the logs anymore now - but it must've been one of the dependencies (probably `libmarkdown`)

What about `make uninstall` though? why is it checking in `cmake/cmake/` when it's just `cmake/`?

**Comment by markus2330** [comment]
@omnidan `make uninstall` had bugs, I fixed it in 86473bedb658b2bad055e463de707c09ca6518fe

Can you please install libmarkdown and try again? (`kdb qt-gui` and `make uninstall`)

Btw. a workaround for `make uninstall` is `xargs rm < install_manifest.txt` (its faster but does not honor DESTDIR)

**Comment by markus2330** [comment]
I would recommend a package manager or at least `checkinstall` though.

**Comment by markus2330** [comment]
@omnidan Please give me as status report about Mac OSX,  kdb qt-gui and make uninstall

**Comment by omnidan** [comment]
`make uninstall` works fine now :+1:

I uninstalled and reinstalled elektra and `kdb qt-gui` works now too. The missing `libmarkdown` seems to have been the issue (I tried installing all required dependencies with `apt-get build-dep`, seems like `libmarkdown` is not part of that?)

**Comment by markus2330** [comment]
Thanks for report! qt-gui is not part of the current debian packages. This will hopefully change with 0.8.13.
