### ISSUE TITLE
avoid strerror

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2794]
From #2686:
> We should not recommend to call strerror(errno) as it is not thread-safe. strerror_r should be used instead. It would be better if we can embed the strerror in a generic way, so that not every caller needs to worry about that.

@Piankero wrote:
> Always allocating and freeing memory just for an error message seems very cumbersome.

Exactly, this is why our error system should take care of this. Then we only implement it once, and everyone can safely report errno.

> So why now introduce thread safety just for error messages?

Thread safety is always supported with Elektra. The current uses of strerror are simply a bug.

It is okay if your implementation uses strerror for now (if you find the other strerror APIs too difficult). But it is important that we have a single place where we can fix the problem.

**Comment by markus2330** [comment]
Btw. this issue is already listed in #2572, so it is not new. And if you use mustache for the template, it should be very easy to fix strerror at the one place.

This issue is also related to #2697.

**Comment by kodebach** [comment]
> Always allocating and freeing memory just for an error message seems very cumbersome.

I don't think that is needed. The following is safe to use and message longer than 2048 characters (if they even exist anywhere) wouldn't be read by the user anyway, so IMO its fine to truncate them. A smaller limit would probably, be fine as well.

```c
char buf[2048];
strerror_r (errno, buf, sizeof(buf));
```

**Comment by Piankero** [comment]
Not related to visible error messages.
As discussed in the Elektra meeting I may unassign myself.
