### ISSUE TITLE
Web UI for LCDproc?

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2795]
@haraldg: as now someone will again work on the Web-UI and reimplement the service on the device with Go: Is it a relevant use case that people want to configure their device with a Web-UI?

**Comment by haraldg** [comment]
I don't really know. I think your Web-UI is probably not really useful for OpenWRT systems (though there are some fairly powerful systems running with OpenWRT these days, so who knows?) and on non-embedded systems there probably is some way to edit configuration, that is prefered over Web-UIs. OTOH lot's of people seem to use LCDproc on headless BSD servers. Maybe they would like it?

Does there actually depend something on the answer to the question?

**Comment by markus2330** [comment]
Thank you for the quick answer!

> Does there actually depend something on the answer to the question?

Yes, if the student should actually try it out (if the Web-UI works with LCDproc) as case study.

**Comment by haraldg** [comment]
Then feel free to ask on the ML whether there is interest.

**Comment by kodebach** [comment]
I don't know what this person is interested in, but maybe a proper terminal UI would also be an option.
There seems to be [good library support for go](https://github.com/gdamore/tcell) there is even some [high level stuff](https://github.com/rivo/tview).

**Comment by markus2330** [comment]
> Then feel free to ask on the ML whether there is interest.

I would like to avoid to ask such questions as long as the basics are not working properly.

> I don't know what this person is interested in, but maybe a proper terminal UI would also be an option.

I do not know if @raphi011 is interested in this but this would be a separate work. I do not see how the Web-UI could be reused there.

But in general a terminal UI would be definitely nice for some tasks. But compared to Web-UI and `kdb editor` I think there is a rather limited group of people who are interested. Which does not mean we shouldn't implement it in the long term.

@kodebach for LCDproc a minimal `ckdb` which uses the high-level API could be also more interesting (if someone wants to run Elektra completely without C++).

**Comment by kodebach** [comment]
> I do not see how the Web-UI could be reused there

No of course it couldn't, it just occurred to me because of the connection to Go.

**Comment by kodebach** [comment]
> minimal ckdb which uses the high-level API could be also more interesting

The high-level API is absolutely not suited for such a tool. Where would the defaults and the `type` metadata come from? Would it only work for the parts of the KDB that have a spec mounted? How would you mount that spec? Mounting right now relies heavily on C++ so we could get avoid having `kdb` anyway.

**Comment by markus2330** [comment]
It should work for the config of LCDproc?

**Comment by kodebach** [comment]
A tool exclusively for LCDproc seems like a bad idea. Also you would still need C++ for mounting, unless somebody rewrites the code for that.
