### ISSUE TITLE
kdbCommit

### ISSUE THREAD

**Issue by vLesk** [ElektraInitiative/libelektra#2798]
When `kdbSet()` is called, plugins implementing the `commit` role need to track their state to distinguish between carrying out that role and carrying out potential other roles (`commit` and `setresolver` for the `resolver` plugin, for example). 

To make plugins more modular and to achieve greater flexibility and reusability of plugins, I would like to separate committing into its own function, `kdbCommit()`. 

Implementing this function would require the following:

- [x] Modifying KDB to call the commit function instead of the set function during the commit step
- [x] Adding a pointer for `kdbCommit()` to `kdbprivate.h`
- [x] Adding support for `kdbCommit()` to `elektraPluginExport`
- [x] Modifying all plugins which carry out the `commit` role to implement `kdbCommit` (for existing plugins this could simply be a function which calls the set function again)
- [x] Modifying `pluginprocess` to support `kdbCommit`

Implementing this function has already been proposed in #1274.

**Comment by markus2330** [comment]
Great description and very good to see activity from you again!

**Comment by vLesk** [comment]
Closing this issue, the remaining work on kdbCommit will be covered by #2918.
