### ISSUE TITLE
Setting up default backend

### ISSUE THREAD

**Issue by jozeffdo** [ElektraInitiative/libelektra#2804]
Hello ,

I am new to Elektra. I have setup my environment with CLion with WSL (Windows subsystem for Linux). 
When I run the example "helloElektra" I get the following output, (as there is no check built for the result of kdbOpen) 
![image](https://user-images.githubusercontent.com/1162768/59976094-1c25a780-95c0-11e9-9c25-4204394355e2.png)

while debugging the example "helloElektra" and other examples which calls kdbOpen(xxx), elektraOpenBootstrap (handle, keys, errorKey) switches to
" **ELEKTRA_SET_ERROR (40, errorKey, "could not open default backend**");

As mentioned in issue "**CLion: running kdb in debug mode #2766**" I have tried with setting the environment variable in CLion
![image](https://user-images.githubusercontent.com/1162768/59975885-bafcd480-95bd-11e9-9650-1fac4b873b9c.png)
as well as in /etc/environemnt
![image](https://user-images.githubusercontent.com/1162768/59975950-a1a85800-95be-11e9-8d48-6d92b6f2e2f7.png)

I would appreciate if someone can help me to fix this issue.

**Comment by markus2330** [comment]
Hello,

thank you for creating the issue!

Did you already see the tutorial doc/tutorials/contributing-clion.md? (It is not yet on the website because a link was forgotten, I added it just now in 2734034e287fd6d657ce08b5257a6e7836569cf1)

Can you try to run the `kdb` command as it is more verbose (it also outputs the warning, which might contain the essential information here.).

Also try to run the tests and see which fail. (see doc/TESTING.md).

As workaround, you could try to build the full or static variant, then no plugins need to be loaded.

**Comment by jozeffdo** [comment]
I have run the kdb and got the following 
**OutPut:**

/mnt/d/libelektra/cmake-build-debug/bin/kdb
Usage: /mnt/d/libelektra/cmake-build-debug/bin/kdb <command> [args]

/mnt/d/libelektra/cmake-build-debug/bin/kdb is a program to manage Elektra's key database.
Please run a command with -H or --help as args to show a help text for
a specific command.

Known commands are:
Sorry, I have a severe problem, it seems like I am not installed correctly!
kdbOpen() failed with the info:
 Sorry, 1 warning was issued ;(
	Sorry, module dl issued the warning 1:
	could not load module, dlopen failed: of module: libelektra-resolver.so, because: (null)
	Mountpoint: 
	Configfile: 
	At: /mnt/d/libelektra/src/libs/loader/dl.c:89
Sorry, module  issued the error 40:
failed to open default backend (see warnings for more information): could not open default backend
Mountpoint: 
Configfile: 
At: /mnt/d/libelektra/src/libs/elektra/kdb.c:293

Please report the issue at https://issues.libelektra.org/
Process finished with exit code 8

**Also ran "run_all" with exeutable "kdb" and many test threw the same exception. I have copied one below**

 Start  45: testshell_markdown_conditionals
Unable to find executable: /mnt/d/libelektra/cmake-build-debug/bin/testmod_conditionals
 45/196 Test  #45: testshell_markdown_conditionals .............***Failed   15.10 sec
Input: /mnt/d/libelektra/src/plugins/conditionals/README.md
terminate called after throwing an instance of 'kdb::KDBException'
  what():   Sorry, 1 warning was issued ;(
	Sorry, module dl issued the warning 1:
	could not load module, dlopen failed: of module: libelektra-resolver.so, because: (null)
	Mountpoint: 
	Configfile: 
	At: /mnt/d/libelektra/src/libs/loader/dl.c:89
Sorry, module  issued the error 40:
failed to open default backend (see warnings for more information): could not open default backend
Mountpoint: 
Configfile: 
At: /mnt/d/libelektra/src/libs/elektra/kdb.c:293


Sorry, I crashed by the signal SIGABRT
This should not have happened!

Please report the issue at https://issues.libelektra.org/
Aborted (core dumped)
fatal: Could not export spec config

**Comment by markus2330** [comment]
Very weird, so it is definitely that dlopen fails but it is very weird that `dlerror` is not set.

Did you also try `../scripts/run_dev_env` described in doc/TESTING.md?

As alternative, use a full/static build or use a different virtualization environment.

**Comment by jozeffdo** [comment]
With the new virtualized environment it works .

![image](https://user-images.githubusercontent.com/1162768/60144234-e7813e00-97c1-11e9-897e-f5ead2f95dcf.png)

Thank you for you contribution.
