### ISSUE TITLE
behavior of kdbGet() if nothing is to do initially

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2810]
@kodebach wrote:
>As far as I can tell, the NO_UPDATE case is used in two cases:

> None of the requested mountpoints have any existing data (i.e. file/block/commit etc doesn't exist). This means the storage plugin call can be replaced by ksNew(0, KS_END).

Here it makes sense to nevertheless call procgetstorage. So maybe we should avoid that this case is NO_UPDATE at all.

**Comment by kodebach** [comment]
> Here it makes sense to nevertheless call procgetstorage. 

Depends on the semantics of `procgetstorage`. Like I said, if we define that it must return an empty KeySet whenever it is called with an empty KeySet, not calling would be fine.

I don't really see a use case for plugins that lookup some process specific data and store it in the KDB without any dependency on other KDB data. In that case a separate library function returning the data directly makes much more sense and would probably be easier to use.
Such plugins could of course make sense, if their data is then processed further by `postgetstorage` plugins, but that is currently not possible anyway.

**Comment by markus2330** [comment]
Yes, it is easily possible that it is useless. I was thinking about applications that only want command-line options but no config files. But currently they would at least need a spec, so the KeySet would not be empty.
