### ISSUE TITLE
Cache: GCC ASAN Build Warnings

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2820]
# Steps to Reproduce the Problem

1. Download the file [Dockerfile.txt](https://github.com/ElektraInitiative/libelektra/files/3386130/Dockerfile.txt) and store it as `scripts/docker/debian/buster/Dockerfile`

2. Build the Docker image

   ```sh
   docker build \
          -t elektra-buster \
          --build-arg JENKINS_USERID=$(id -u) \
          --build-arg JENKINS_GROUPID=$(id -g) \
          -f scripts/docker/debian/buster/Dockerfile \
          scripts/docker/debian/buster/
   ```

3. Run the Docker image

   ```sh
   docker run \
          -it --rm --cap-add SYS_PTRACE \
          -v "$PWD:/home/jenkins/workspace" \
          -w /home/jenkins/workspace \
          elektra-buster
   ```

4. Create the build system

   ```sh
   mkdir build
   cd build
   cmake \
         -DBUILD_DOCUMENTATION=OFF \
         -DCOMMON_FLAGS=-Werror \
         -DENABLE_ASAN=ON \
         -DBINDINGS='ALL;-DEPRECATED' \
         -DPLUGINS='ALL;-DEPRECATED ' \
         -DTOOLS='ALL;-qt-gui' \
         -DENABLE_DEBUG=ON \
         -DKDB_DB_FILE=default.mmap \
         -DKDB_DB_INIT=elektra.mmap \
         -DKDB_DEFAULT_STORAGE=mmapstorage \
         ..
   ```

5. Compile Elektra

   ```sh
   cmake --build .
   ```

# Expected Result

The build system is able to translate Elektra without any warnings.

# Actual Result

GCC `8.3` reports a warning about a null destination pointer:

```
src/plugins/cache/cache.c: In function ‘elektraCacheSet’:
src/plugins/cache/cache.c:154:8: error: null destination pointer [-Werror=format-overflow=]
  len = sprintf (tmpFile, "%s", cacheFileName);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

.

# System Information

- Elektra `master`
- Docker `2.0.0.3`

# Further Log Files and Output

- [Jenkins Build Job](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2819/11/pipeline/458)

**Comment by mpranj** [comment]
Thank you for reporting. Pretty sure I copied that code straight out of our default resolver.

https://github.com/ElektraInitiative/libelektra/blob/061ff14bea36aa17d2c20687854569b55b49cf0e/src/plugins/resolver/filename.c#L76

**Comment by markus2330** [comment]
@mpranj Do we need to fix the default resolver, too?

Multiresolver reuses some code of resolver. Maybe you can use a similar strategy to reuse code? Or did you only copy this one line?

**Comment by mpranj** [comment]
The code is the same but the error was never triggered. I only copied 3 lines, it makes no sense to reuse it.
