### ISSUE TITLE
Unable to test interpreter plugins

### ISSUE THREAD

**Issue by manuelm** [ElektraInitiative/libelektra#283]
Both python und lua plugin need to find their bindings in order to something useful. Their interpeters support extending the search path with environment variables, however cframework/tests.c is completely wiping the environment.

Since you're the one who introduced the clearenv call I suspect you know the answer how to solve this

**Comment by manuelm** [comment]
I also need a way to set compile definitions/flag for a source file for elektra-full. `set_source_files_properties` doesn't work here

**Comment by markus2330** [comment]
Tests that need some external environment to run is bad design. See java plugin how to solve the CLASSPATH issue. Basically, it should be irrelevant if information is passed by plugin config or by environment. Or is it an interpreter API issue?

Currently only the global properties elektra-full_SRCS and elektra-full_LIBRARIES exist, but it should not be hard to add elektra-full_DEFINITIONS. Do you need help there?

**Comment by manuelm** [comment]
There are no java tests. So you have solved *nothing*.

**Comment by manuelm** [comment]
> Currently only the global properties elektra-full_SRCS and elektra-full_LIBRARIES exist, but it should not be hard to add elektra-full_DEFINITIONS. Do you need help there?
Yes, but only if you can make this definitions per source file. I don't want to add global any definitions. The definition shall only be used during compilation of the specified source files. So it behaves the same as set_source_files_properties

**Comment by markus2330** [comment]
Better to open one issue per issue. About the elektra-full_DEFINITIONS: It should work when you create $<TARGET_OBJECTS:${PLUGIN_OBJS}> for the source files in question and add them to elektra-full_SRCS. At least this is done in LibAddPlugin.cmake.

**Comment by manuelm** [comment]
Did some other workarounds

**Comment by markus2330** [comment]
In c4f120272b848debcdc9176ec9b0e8eb8b9d0347 I added a plugin test for java as demonstration how it could be done. (Without any environment required to be set, even though internally a CLASSPATH is used) Test is currently only in-build, to run in from installation would be straight forward, though.

@manuelm Where exactly do you need a workaround?

**Comment by manuelm** [comment]
I've done something similar: https://github.com/manuelm/libelektra/blob/python/src/plugins/python/CMakeLists.txt#L65

**Comment by manuelm** [comment]
I hope you've received a notification about my comment here: https://github.com/ElektraInitiative/libelektra/commit/c4f120272b848debcdc9176ec9b0e8eb8b9d0347#commitcomment-13245185

**Comment by markus2330** [comment]
Yes, got the notification and you already answered that it is ok? (In e-mails there is no history)

Fine that you also got it to work. I had a 4h meeting which delayed my jni-example.
