### ISSUE TITLE
Build broken, if libuv missing

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#2845]
The commit c3d1bda breaks the `RelWithDebInfo` build on my machine.

More specifically it is this line:

https://github.com/ElektraInitiative/libelektra/blob/c3d1bda848c5e66d3e4fd941a3859a8bf8051267/examples/CMakeLists.txt#L102

As far as I can tell, it is because I have `glib` but not `libuv` installed. For some reason we add the `libuv` include directories, even if only `glib` is installed. This causes the following error when calling CMake:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
libuv_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/klemens/data/bsc/libelektra/examples
   [ ... repeated about 40 times ... ]
```

For mysterious reasons it only happens when `CMAKE_BUILD_TYPE=RelWithDebInfo`.

**Comment by markus2330** [comment]
Thank you for reporting this problem and finding the problematic commit!

@sanssecours is this maybe a MacOS specific problem? Maybe homebrew compiled glib in a way that it uses libuv and distribute a wrong GLib_INCLUDE_DIRS.

> For mysterious reasons it only happens when CMAKE_BUILD_TYPE=RelWithDebInfo.

This is really mysterious.

**Comment by sanssecours** [comment]
> is this maybe a MacOS specific problem?

I do not know. I just added the include directory, since the Cirrus macOS build jobs were complaining about a missing header file.

> Maybe homebrew compiled glib in a way that it uses libuv and distribute a wrong GLib_INCLUDE_DIRS.

That might be the case. However, as far as I remember, the Travis macOS build jobs worked fine, even before commit c3d1bda.
