### ISSUE TITLE
gopts: does not compile in buster

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2853]
```
-- gopts: no procfs and sysctl test failed with:
Change Dir: /libelektra/build/src/plugins/gopts/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_a12e0/fast"
/usr/bin/make -f CMakeFiles/cmTC_a12e0.dir/build.make CMakeFiles/cmTC_a12e0.dir/build
make[1]: Entering directory '/libelektra/build/src/plugins/gopts/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_a12e0.dir/sysctl_test.c.o
/usr/bin/cc   -std=gnu99  -Wno-deprecated-declarations  -Wstrict-prototypes  -Wno-long-long -Wpedantic -Wno-variadic-macros -Wall -Wextra -Wno-overlength-strings -Wsign-compare -Wfloat-equal -Wformat -Wformat-security -Wshadow -Wcomments -Wtrigraphs -Wundef -Wuninitialized -Winit-self -Wmaybe-uninitialized -Wsign-compare -Wfloat-equal    -o CMakeFiles/cmTC_a12e0.dir/sysctl_test.c.o   -c /libelektra/src/plugins/gopts/sysctl_test.c
/libelektra/src/plugins/gopts/sysctl_test.c:15:2: error: #error no KERN_PROC
 #error no KERN_PROC
  ^~~~~
/libelektra/src/plugins/gopts/sysctl_test.c:19:2: error: #error no KERN_PROC_ARGS
 #error no KERN_PROC_ARGS
  ^~~~~
make[1]: *** [CMakeFiles/cmTC_a12e0.dir/build.make:66: CMakeFiles/cmTC_a12e0.dir/sysctl_test.c.o] Error 1
make[1]: Leaving directory '/libelektra/build/src/plugins/gopts/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_a12e0/fast] Error 2

```

**Comment by kodebach** [comment]
On Debian the `procfs` test should succeed, i.e. this condition should be true.

https://github.com/ElektraInitiative/libelektra/blob/c1d26bc4047c8edc41b2f9ffe02da2fccd255d01/src/plugins/gopts/CMakeLists.txt#L16

Possibly `/proc/mounts` doesn't exist on Debian Buster? Try changing it to

```cmake
elseif (EXISTS "/proc/self/cmdline")
```

which is a better test anyway. Although according to the manpage both files should always exist (`/proc/mounts` might be a symlink but that shouldn't matter).

**Comment by markus2330** [comment]
Thank you for the answer. Maybe the test only failed because procfs was not mounted.

**Comment by kodebach** [comment]
`gopts` needs one of 4 things: the Win32 API, the OSX API, the `sysctl` API with support for  `KERN_PROC_ARGS` or a mounted `procfs`. If none of those are found it won't compile. AFAIK on debian procfs should be mounted by default.

**Comment by markus2330** [comment]
Maybe you can improve CMake the error message to say something like this?

And actually checking for /proc during CMake is not the right thing: Because actually we want the node where Elektra runs to have /proc, not the build server.

**Comment by kodebach** [comment]
I need to check the other APIs during CMake, because they need to be available during build time. We also check that `/proc` is available during runtime:

https://github.com/ElektraInitiative/libelektra/blob/c1d26bc4047c8edc41b2f9ffe02da2fccd255d01/src/plugins/gopts/gopts_procfs.h#L25-L36

The CMake check is just an additional check, based on the assumption that a plugin should only be compiled, if it runs on the machine it is built on. 

One thing that could be improved is the runtime error message. Currently `gopts` doesn't have any...

> Maybe you can improve CMake the error message to say something like this?

It already says "gopts: no procfs and sysctl test failed with: ...". What would you like it to say?

**Comment by markus2330** [comment]
> The CMake check is just an additional check, based on the assumption that a plugin should only be compiled, if it runs on the machine it is built on.

Yes, I think the assumption is invalid. CMake should only check if it will compile later on. In this case, however, it is not a big deal as /proc usually is available.

> One thing that could be improved is the runtime error message. Currently gopts doesn't have any (apart from the ones passed along from elektraGetOpts).

That would be great!

> It already says "gopts: no procfs and sysctl test failed with: ...". What would you like it to say?

Based on what you wrote above:

"gopts failed to find one of the supported platforms. Supported are the Win32 API, the OSX API, the sysctl API with support for KERN_PROC_ARGS or a mounted procfs."

> AFAIK on debian procfs should be mounted by default.

Yes, only in chroot or similar it might not be mounted.

**Comment by kodebach** [comment]
> Yes, I think the assumption is invalid.

I'll add an option through which the `gopts` variant that forces a variant, even if it may not compile. That way one can build the `procfs` variant, without having `procfs` mounted.

> "gopts failed to find one of the supported platforms. Supported are the Win32 API, the OSX API, the sysctl API with support for KERN_PROC_ARGS or a mounted procfs."

I'll change it.

**Comment by markus2330** [comment]
> I'll add an option through which the gopts variant that forces a variant, even if it may not compile. That way one can build the procfs variant, without having procfs mounted.

No, this only complicates the build system. With the proper error message it should be clear what the problem is. Mounting procfs would have been no problem for me.
