### ISSUE TITLE
add regression tests for external kdb commands

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2859]
In ca63b86f53cefb5e0941ec0b7a1d116f504bcb12 a hard-to-find bug was introduced: external commands did not get their arguments but instead failed with "UnknownCommand".

We should add an regression test where external commands are tested, ideally some that use gopts (similar tests already exist).

The test succeeds if the executed `kdb my-test-command` prints all cmd-line args and env successfully.

**Comment by Piankero** [comment]
Not related to visible error messages.
As discussed I may unassign myself.

Also there hasn't been found any regression again yet.

**Comment by markus2330** [comment]
Yes, I am happy that it was now only two regressions.
