### ISSUE TITLE
cache not used despite it is enabled

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2865]
## Steps to Reproduce the Problem

```sh
kdb cache enable
kdb cache clear
kdb global-mount syslog
time kdb ls / > /dev/null 
ls ~/.cache/elektra
```

## Expected Result

That there is a cache file in ~/.cache/elektra or a warning that the cache cannot be used is printed.

## Actual Result

It is not, as `kdb global-mount syslog` made the cache dysfunctional.

## System Information

- Elektra Version: master

Btw. if the cache works, it works amazing. 6,253 -> 0,483 seconds (or even 13,426 -> 0,450 seconds in a second try) for 649 config files.

Only for system and / it does not work (noresolvers). Unfortunately, also no warning there.

**Comment by mpranj** [comment]
Thank you for reporting, I forgot to add the warnings. I don't think I'll be able to fix it properly before the upcoming release.

**Comment by markus2330** [comment]
Don't worry, the release is already done (only not pushed).
