### ISSUE TITLE
'comments' metadata after importing ini

### ISSUE THREAD

**Issue by Chemin1** [ElektraInitiative/libelektra#2868]
After an .ini file

```
➜  ~ cat firefoxprofiles.ini
[Install4F96D1932A9F858E]
Default=qp0doffe.default
Locked=1

[Profile0]
Name=default
IsRelative=1
Path=qp0doffe.default
Default=1

[General]
StartWithLastProfile=1
Version=2
```

has been imported with  `➜  ~ cat firefoxprofiles.ini | kdb import system/firefox ini`
we can execute the following command

```
➜  ~ kdb getmeta system/firefox/General comments
#0
```

METADATA.ini only has [comment] but not [comments] and [comment] is deprecated. Thus, I assume that this should not happen?

**Comment by markus2330** [comment]
Thank you for creating this issue! You are right.

Unfortunately, some plugins still use the deprecated metadata `comment`, see #1375

I started a new issue to collect places where old metadata is in use:  #2870
Please feel free to add other problems with deprecated metadata, still in use, there as well.
