### ISSUE TITLE
Clean up tmp files/directories during/after building

### ISSUE THREAD

**Issue by manuelm** [ElektraInitiative/libelektra#287]
The /tmp directory of my build containers have a LOT of tmp files and directories which get created during the build process. We should either clean all of them at the end or during the build.

tmp.XXXXXXXXX files in /tmp: 1541
elektraenv.XXXXXXXXX directories in /tmp: 12
elektra-test.XXXXXX directories in /tmp: 7
getenv-XXXXXX.ii files in /tmp: 6
cpp11_benchmark_thread-XXXXXX.ii files in /tmp: 1

**Comment by markus2330** [comment]
You are right. They also should all start with elektra-.

**Comment by markus2330** [comment]
#284 is already a step in this direction.

**Comment by markus2330** [comment]
You mention some other folders and /tmp/jna--* seems also to be from Elektra

**Comment by markus2330** [comment]
shell recorder should do cleanup, too

**Comment by markus2330** [comment]
A trap for cleanup after signals would be great, too.

**Comment by markus2330** [comment]
What about changing TMPDIR and clean up the whole directory? Seems easier than to track down every single tmpfile in every test case.

**Comment by markus2330** [comment]
There are still plenty of such cases, including /tmp/elektra-test and elektraenv.XXXXXXXXX.

shellrecorder could help for cleanup, and finally fixing TMPDIR, see #1973

@ingwinlu Can the build server check which leftovers the testcases have? (So that we at least not increase the number of leaking test cases.)

**Comment by markus2330** [comment]
@sanssecours Is it a good idea to keep the Protocol File of the shell recorder? We already print it, so they could be removed, can't they?

**Comment by sanssecours** [comment]
> We already print it, so they can be removed, can't they?

Makes sense, I opened pull request #1979 which updates the behavior of the Shell Recorder accordingly.

**Comment by markus2330** [comment]
Is this now fixed with #2056? Or do we need cleanup for other test suites (like gtest), too?

Can we add a check in our build server which checks if we leave /tmp in the state as before?
