### ISSUE TITLE
Conflicting build server formatting

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#2874]
There is a weird bug in our formatting checks. All build servers use `cmake-format` version `0.5.4`  as far as I can tell.

However for this commit https://github.com/ElektraInitiative/libelektra/commit/8801d77137de808a34bd680a978a441dd10f6dd6 in #2805
- [Jenkins](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2805/29/pipeline/315) accepted the CMake files
- so did [Travis](https://travis-ci.org/ElektraInitiative/libelektra/builds/570567998)
- [Cirrus](https://cirrus-ci.com/task/6296186686799872) however detected problems

When I ran `reformat-cmake` locally (also `cmake-format` version `0.5.4`, but python3), exactly the files that Cirrus complained about where reformatted. Python 3 is not the cause, since all build servers still use Python 2.7 (see the warnings when calling `pip install`).

**Comment by markus2330** [comment]
Thank you for reporting the problem!

Can you also reproduce the other formatting locally? E.g. in different dockers?

Is it maybe related to the OS?

@sanssecours any ideas?

**Comment by kodebach** [comment]
I doubt it is related to the OS locally I used Linux and none of the Linux servers detected the problem. Also the Cirrus macOS jobs detected the problem, but the Travis macOS job did not.

Since all servers accepted the reformatted version, I guess that the script for `testscr_check_formatting` does not check all files or doesn't report all faults correctly.

**Comment by markus2330** [comment]
Ok, so it is not like that two different servers came to different formatting results?

To debug the script we could print $files

**Comment by sanssecours** [comment]
> Ok, so it is not like that two different servers came to different formatting results?

As far as I can tell, `cmake-format --version` seems to print its output on `stderr` instead of `stdout` in the Travis build jobs. The result of this behavior is that the version detection of `reformat-cmake` fails, and the script does not reformat any files at all. I already fixed the problem in my copy of the repo. If there are no unexpected problems, I will open a pull request soon.
