### ISSUE TITLE
Validation Regex Bug?

### ISSUE THREAD

**Issue by Piankero** [ElektraInitiative/libelektra#2881]
## Steps to Reproduce the Problem

Does C use a different form of regex engine?
The regex below works just fine in the browser: https://regex101.com/r/fZr9Mi/1

```sh
kdb mount test.spec spec/tests dump
kdb mount test.conf /tests dump validation
kdb rm -r /tests
kdb rm -r spec/tests
kdb rm user/tests/abc

kdb setmeta spec/tests/abc 'check/validation' '[1-9]\d{3,}'
kdb setmeta spec/tests/abc 'check/validation/match' 'LINE'
kdb setmeta spec/tests/abc 'check/validation/message' 'LircFlushThreshold must be a positive number >=1000'

kdb set /tests/abc 1000

kdb umount spec/tests
kdb umount /tests
```

## Expected Result

The upper script is executed without any error

## Actual Result

```
Sorry, module validation issued the error C03100:
Validation Syntactic: Key value failed to validate. Reason: LircFlushThreshold must be a positive number >=1000
```

## System Information

- Elektra Version: master

**Comment by markus2330** [comment]
Thank you for reporting this problem!

Checking for numbers is easier to be done by the range plugin.

But you are right, the documentation about which kind of regex is supported is poor, this should be improved. We use REG_NOSUB | REG_EXTENDED from regcomp by default but this can be modified with check/validation/type (undocumented? BRE switches to basic regular expressions).

So we should:

- document which regex can be used (link to regcomp(1) and regex(7) manual page)
- clarify the check/validation/type in the docu or remove the feature
- allow the message to contain the value and regex
- and finally also fix  #2603

To answer why the regex does not work: I would check if `\d` is supported.

**Comment by Piankero** [comment]
Thank you for your clarification.

> Checking for numbers is easier to be done by the range plugin.

I cannot do this since the range plugin needs a lower *and* upper bound whereas I only have a lower bound.

**Comment by Piankero** [comment]
Switching the regex to `[1-9][0-9]{3,}` does now work.

**Comment by markus2330** [comment]
Good! Would be great if you can improve the docu, so that it will be easier for the next person.

> I cannot do this since the range plugin needs a lower and upper bound whereas I only have a lower bound.

It is possible if you write the actual number of LLONG_MIN-1000. But your regex also does not work for numbers below 0, so you could use the range 0-1000.
