### ISSUE TITLE
cmake error with FindOpenSSL

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2900]
Is this our fault or is the problem in the system's cmake?

https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/867/pipeline
```
CMake Error at /usr/share/cmake-3.7/Modules/FindOpenSSL.cmake:327 (math):

  math cannot parse the expression: "0 + B": syntax error, unexpected $end,

  expecting exp_OPENPARENT or exp_NUMBER (5)

Call Stack (most recent call first):

  /usr/share/cmake-3.7/Modules/FindOpenSSL.cmake:358 (from_hex)

  src/tools/website-backend/CMakeLists.txt:4 (find_package)

```

**Comment by petermax2** [comment]
The cause is most likely a problem within the system's CMake modules, since all we do in our `FindLibOpenSSL.cmake` is basically:

    find_package (OpenSSL QUIET)

**Comment by markus2330** [comment]
Very weird, in the next build it succeeded successfully without any changes. Maybe the Docker image has been rebuilt in the meantime?

https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/869/

Now we have fixed all OpenSSL -> LibOpenSSL (our wrapper to include OpenSSL by @sanssecours). So I will close this issue.
