### ISSUE TITLE
Link checker limitations

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#2904]
I'm not 100% sure how our link-checker (more specifically the markdown link converter) works, but there are some limitations. It would be nice, if we could get rid of them.

For example [this run](https://github.com/ElektraInitiative/libelektra/runs/199835189) failed even though the link is technically correct.

If I understand things correctly, we need to generate `{ #header }` tags not only for the title, but also for subtitles in markdown files for this to work.

**Comment by kodebach** [comment]
> I am still not sure if it now works for all our markdown targets (ronn?, qt-gui?)

Are tutorials rendered anywhere else apart from the website? I think it would make sense to allow anchors for the files that are only displayed on the website.

**Comment by markus2330** [comment]
> Are tutorials rendered anywhere else apart from the website?

At least GitHub and Doxygen also renders them.

As we sometimes move around text, I think it is easier if we use the same syntax everywhere.
