### ISSUE TITLE
Example Web UI Instance is Down

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2913]
# Steps to Reproduce the Problem

Open the following link:

- https://webdemo.libelektra.org

.

# Expected Result

The URL above should show an example instance of the [Web UI](https://master.libelektra.org/src/tools/web/README.md).

# Actual Result

The web server reports the error “502 Bad Gateway”.

**Comment by kodebach** [comment]
The server no longer returns a 502 Error. Instead the request just times out.

Since our link-checker script didn't use a timeout and instead our build jobs timed out, I added the timeout in #2914.

**Comment by kodebach** [comment]
After further investigation it turns out the docker registry https://hub-public.libelektra.org is also down. As far as I can tell they are on the same server (at least via the same IP), so probably the whole server crashed.

**Comment by kodebach** [comment]
> the docker registry https://hub-public.libelektra.org is also down

The Jenkins server also doesn't work because of that.

**Comment by markus2330** [comment]
Thank you for reporting these problems!

I think "only" a7 is down, all the services you mentioned here are on a7. I asked our admin to restart the machine.

**Comment by kodebach** [comment]
Did the restart already happen? If so, it didn't help...

**Comment by markus2330** [comment]
The admin did not write me anything yet :cry:

**Comment by markus2330** [comment]
a7 is up again. But I can reproduce now that https://webdemo.libelektra.org/ stopped working. I am afraid I caused it by #2907 :cry: 

Luckily @Mistreated will now work on this topic again (or more precise on #2530)

@kodebach: Can you check if https://hub-public.libelektra.org/ works again for you?

**Comment by kodebach** [comment]
> Can you check if https://hub-public.libelektra.org/ works again for you?

Yes, it seems to be working again.

**Comment by kodebach** [comment]
@markus2330 The server is down again. Maybe revert #2907, since it may be the cause for the crashes.

**Comment by Chemin1** [comment]
https://hub-public.libelektra.org/ as well as https://webdemo.libelektra.org are down for me, too (connection timed out).

**Comment by markus2330** [comment]
> @markus2330 The server is down again. Maybe revert #2907, since it may be the cause for the crashes.

The server crashes because the kernel/hardware is unstable. It has nothing to do with the code it compiles and runs. It occurs since we upgraded to Buster, so maybe the Buster kernel has some regression on this hardware.

> https://hub-public.libelektra.org/ as well as https://webdemo.libelektra.org are down for me, too (connection timed out).

Yes, because a7 is down again, see #160.

This issue is only about the Web UI, please report other issues in #160 or in new issues.

**Comment by markus2330** [comment]
@lukashartl will you do this? You are currently not assigned...

**Comment by lukashartl** [comment]
@markus2330 yes, I'll do this
