### ISSUE TITLE
Get started / Entry Barrier 

### ISSUE THREAD

**Issue by d3nwp** [ElektraInitiative/libelektra#2922]
Since I am working on my thesis which is about the entry barriers of floss projects, I am also interested to contribute to elektra and highlight some issues that I faced when I tried to install elektra for the very first time. So lets make a better World (of Elektra) :D -> Error: make cmd not found!

There is already an [issue 2891](https://github.com/ElektraInitiative/libelektra/issues/2891) which points out the main problem = 'overloaded' doc pages and a nontrivial structure. 

Reproducing the 'problem': 
Just imagine, for the very first time I visited the homepage and I was interested in elektra, so I started watching the video and clicking around to find more information about the project.
The first problem I was confronted with was the navigation to the get started page.
There are three ways to "get started":

- Green button labeled with "Get Started" on the main page (which is a link to 2nd point of this list) 
- Navigation bar -> Documentation/Getting Started
- Navigation bar -> Development/Getting Started

Since I wasn't interested in any documentation, I clicked on "Development/Getting Started" and read the information on that page. However, I wasn't satisfied because this page was for developers or contributors of elektra (!?) and the short paragraph wasn't really helpful. Now I navigated back to the main page and clicked the green button. And now I thought that this page contains important content and because of that I read all of the topics and sub-topics and finally reached my goal, the "Installation section". On this page I had to skip a bunch of sub-sections to find the "OS Independent" sub-section (IMO the majority of users are interested in this sub-section) and now it said that I need to visit the Compile page to fulfill the pre-requirements.

I mean it wasn't that hard to find all of this information but I think we should re-write/edit the “Get Started” part and face some entry barriers and overcome newcomer-fear.

**Comment by markus2330** [comment]
Yes, there is certainly a lot of space for improvement. Thank you for the summarize.

Related issues are:  #280 #1054 #1189 

Improvements of documentation style:  #1053

**Comment by d3nwp** [comment]
I am trying to build the project with -DTOOLS="ALL;website-backend;website-frontend" (as described in https://www.libelektra.org/tutorials/snippet-sharing-rest-service) but I get an error and I don't know why or how to fix it:

![cmake_mit_dtools_website](https://user-images.githubusercontent.com/51342287/64644093-26fb1600-d412-11e9-9fc9-ecfc546d04cb.png)

I couldn't find the files which are mentioned in the error log.

My make options in CLion:
-DKDB_DB_SYSTEM="~/.config/kdb/hto/system"
-DKDB_DB_SPEC="~/.config/kdb/hto/spec"
-DKDB_DB_USER=".config/kdb/hto/user"
-DCMAKE_INSTALL_PREFIX=install
-DENABLE_DEBUG=ON
-DENABLE_LOGGER=ON
-DTOOLS="ALL;website-backend;website-frontend"

**Comment by sanssecours** [comment]
> I couldn't find the files which are mentioned in the error log.

As far as I can tell, these directories [exist in the `master` branch](https://github.com/ElektraInitiative/libelektra/tree/master/src/tools). Did you maybe accidentally delete them?

I executed the following commands on my machine:

```sh
git clone https://github.com/ElektraInitiative/libelektra.git
cd libelektra
mkdir build
cd build
cmake -DTOOLS="ALL;website-backend;website-frontend" ..
```

. The `cmake` command reported some (expected) warnings about missing dependencies, but seems to work fine otherwise.

**Comment by markus2330** [comment]
Maybe you read the documentation on the website (which refers to the master branch) but you checked out an older branch (the website was renamed recently).

Make sure that you always pull from the main repo into your repo.
