### ISSUE TITLE
Ubuntu Bionic Packages

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2924]
@Mistreated Similar to https://github.com/ElektraInitiative/libelektra/pull/2906 we should also create Ubuntu Bionic Packages as needed by @raphi011.

If deps are called differently, we can simply handle it similar to ac3883f7ca4fb9050ee26e026a99098bb3e05bd6

**Comment by Mistreated** [comment]
Currently testing out the Dockerfile.

**Comment by Mistreated** [comment]
Progress:  Setting up a Dockerfile and testing it locally.

**Comment by markus2330** [comment]
Thank you for testing! You can also create a PR with the Dockerfile only.

As written by email:

scripts/build-debian-package

and:

scripts/jenkins/Jenkinsfile

are the current ways how to build a Debian package. Unfortunately, there is no docu for them.

**Comment by sanssecours** [comment]
> You can also create a PR with the Dockerfile only.

I think it makes sense to only add the Dockerfile for Ubuntu Bionic in the first PR. 

One additional important piece of information about the package is that the package description is contained in the folder [`debian`](https://github.com/ElektraInitiative/libelektra/tree/debian/debian) in the [`debian` branch](https://github.com/ElektraInitiative/libelektra/tree/debian).

By the way, PR #2906 contains code that builds packages for Debian buster. I think the code for adding packages for Ubuntu Bionic should be similar.

If you have any questions, please feel free to ask here or write me an email. We can also meet, if you want to. Usually I am at the university during the week, so we could for example meet there.

**Comment by markus2330** [comment]
Note, that  #2906 only builds the Debian package (for buster) but does not publish it.

@ingwinlu can you shine some light on how we could publish Debian packages for several distributions? How does publishDebianPackages  works? (I do not see how it knows for which distribution to publish).

**Comment by Mistreated** [comment]
Dockerfile is tested locally and ready, gonna make a PR until the end of the day.

**Comment by raphi011** [comment]
Since this is merged - when will the package be available in the official repository?

**Comment by sanssecours** [comment]
> Since this is merged - when will the package be available in the official repository?

PR #3053 (and PR #2932) only included the Dockerfile for Ubuntu Bionic. Jenkins does currently not build the packages for Ubuntu Bionic:

https://github.com/ElektraInitiative/libelektra/blob/dc24c7fc23a247127b29ff7023c933b336123e17/scripts/jenkins/Jenkinsfile#L1034

. The code for publishing the packages does not exist yet, as far as I know. It requires changes to the private [build server repo](https://github.com/ElektraInitiative/buildserver/blob/master/compose/frontend/docker-compose.yml#L63r).

As far as I know Djordje (Mistreated) will take care of the Ubuntu packages, after he finishes the migration from the old to the new main (Jenkins) build server.

**Comment by markus2330** [comment]
@Mistreated any progress here? Only the publishing of the packages in different repos should be missing.

**Comment by raphi011** [comment]
any ETA on this?

**Comment by Mistreated** [comment]
Im gonna look it up over the weekend.

**Comment by markus2330** [comment]
@Mistreated ping

**Comment by markus2330** [comment]
@Mistreated what is the status?

**Comment by Mistreated** [comment]
We have Ubuntu packages now so, closed.
