### ISSUE TITLE
Copies of files between python2 and python plugins

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#293]
It seems like that the weird redirections of python source won't work when installed. The assumption that the files can be found in `/../../python` is wrong then.

Don't you think copying the source files would be reasonable? 023ead2be61bb4d94591907a5ebab70455f1245e

Btw. I would rather avoid copy README.md.

What do you think?

```
> kdb testmod_python2

PYTHON      TESTS
==================

Testing simple variable passing...
Traceback (most recent call last):
  File "/usr/share/libelektra-test/test-data/python2/python_plugin.py", line 9, in <module>
    ElektraPlugin = importlib.import_module("python.%s" % py2module).ElektraPlugin
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named python.python_plugin
There are 1 warnings
buffer is: warnings/#00
number: 11
description: open of plugin returned unsuccessfully (reason contains plugin, see other warnings for details)
ingroup: kdb
module: 
file: /home/jenkins/workspace/workspace/elektra-git-buildpackage-wheezy/libelektra/src/libelektra/plugin.c
line: 296
reason: python2
reason: 
reason: 
/home/jenkins/workspace/workspace/elektra-git-buildpackage-wheezy/libelektra/src/plugins/python2/../python/testmod_python.c:47: error in test_variable_passing: warnings in kdbOpen for plugin python2
number: 111
description: : python error
ingroup: : plugin
module: : python
at: /home/jenkins/workspace/workspace/elektra-git-buildpackage-wheezy/libelektra/src/plugins/python2/../python/python.cpp:254
reason: : Unable to import python script /usr/share/libelektra-test/test-data/python2/python_plugin.py
mountpoint: : 
configfile: : 
/home/jenkins/workspace/workspace/elektra-git-buildpackage-wheezy/libelektra/src/plugins/python2/../python/testmod_python.c:47: error in test_variable_passing: error in kdbOpen for plugin python2
/home/jenkins/workspace/workspace/elektra-git-buildpackage-wheezy/libelektra/src/plugins/python2/../python/testmod_python.c:47: fatal in test_variable_passing: could not open python2 plugin

```

**Comment by manuelm** [comment]
Well, you already copied it. No idea what this issue is about then.

The idea about this redirect was, since the plugin and the testcase itself is just a include, the python plugins should be includes too.

A better approach is to remove the python2 test folder and do the magic in pythons testmod.

re readme: there's no cmake property to overwrite the readme and all cmake functions assume the readme in CMAKE_CURRENT_SOURCE_DIR...

**Comment by markus2330** [comment]
Thanks for the info.

While writing the issue, I came to the conclusion that python3 test_data might not be installed, and a copy is needed anyway ;)

readme: what about simply including readme_python.c (and not readme_python2.c)?

Nevertheless, lets keep these things for after the release.

**Comment by manuelm** [comment]
readme_python.c is located in another folder and might not get build if only python2 is selected
