### ISSUE TITLE
debian packages

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2947]
- [ ] publish Debian packages for buster
- [x] publish Ubuntu packages
- [ ] install -merge files

**Comment by markus2330** [comment]
It seems that sometimes buster and sometimes stretch packages are published.

Currently, we again have stretch packages (which also work on buster except of the python3 packages).

**Comment by markus2330** [comment]
@Mistreated in the buildserver repo there is compose/frontend/images/repo-builder/Dockerfile

This dockerfile needs to be executed 3x, with different DISTRO set.

**Comment by markus2330** [comment]
@Mistreated the compose file is 
https://github.com/ElektraInitiative/buildserver/blob/master/compose/frontend/docker-compose.yml#L63

**Comment by Mistreated** [comment]
@markus2330 With which DISTROs should I execute docker compose?

**Comment by markus2330** [comment]
bionic, stretch and buster

**Comment by markus2330** [comment]
@Mistreated any progress here, would be great to have Debian Packages for 0.9.1

**Comment by Mistreated** [comment]
Is https://github.com/ElektraInitiative/buildserver/blob/master/compose/frontend/docker-compose.yml#L63 as a whole to be executed or just `repo-builder-stretch`?

**Comment by mpranj** [comment]
When you start it with docker compose everything is started. The relevant dockerfile is in the images subdirectory though.

**Comment by markus2330** [comment]
It would be good to have a small reminder in the docu where the composer stuff is located, how to start it and so on.

**Comment by markus2330** [comment]
But for this issue (the Debian/Ubuntu/... packages) I think we should migrate away from the current composer solution. You can simply copy the deb files to our webserver, like we do with all other artifacts.

**Comment by Mistreated** [comment]
#2924 
I do not know what is exactly to be done. 
Do you mean just publish them somwhere on the webserver?

**Comment by markus2330** [comment]
Yes, Debian just requires some specific folder structure and an index file served by an webserver. Software like reprepro can do the structure/index for you. The delivery itself does not need anything but a webserver.

**Comment by markus2330** [comment]
@Mistreated ping
