### ISSUE TITLE
3-way merge: marks every key as sync

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#295]
just a reminder, because TODO in src/tools/qt-gui/src/treeviewmodel.cpp is not very visible

**Comment by markus2330** [comment]
solution might not actually effect 3-way mering (reconstruct minimal changed keyset as additional API)

**Comment by fberlakovich** [comment]
Could you please give an example of what keys are marked as sync? The TODO in treeviewmodel does not seem to be present anymore.

**Comment by markus2330** [comment]
I think at least all of "our". Its best if you create a testcase with keys not marked sync. After merging only merged keys should be marked sync.

I think the problem is in rebaseKey, which always creates a new key. And it seems to be called for every key in "our"? (see ThreeWayMerge::detectConflicts)

**Comment by markus2330** [comment]
(or simply unsync and check for sync in the already existing test cases)

**Comment by fberlakovich** [comment]
Which API should I use to check whether a key needs sync (especially in C++)?

**Comment by markus2330** [comment]
I added Key::needSync. For changing the bit you need an internal API (kdbprivate.h), `clear_bit(k->flags, KEY_FLAG_SYNC);` should do for test cases.

**Comment by fberlakovich** [comment]
Am I right that this is mainly a problem when either ours or theirs overlaps with the merge target? Otherwise the sync flag is justified because the merged keys have a new parentKey and strictly spoken each merged key is a new one.

**Comment by markus2330** [comment]
I am not sure, its the best if you debug it with the GUI.
Even if it can be argued its a new key -- when theirs and ours is identical they should not have the sync flag set.

Rationale: sync flag is only an optimization to detect if a keyset needs to be rewritten. If we know it needs not, we should not set the flag.

The current status, that everything is rewritten in the merge case even though neither theirs nor ours changed, is unsatisfactory.

**Comment by markus2330** [comment]
Thanks for fixing the issue for this release
