### ISSUE TITLE
High-level API Error access

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#2952]
Right now the high-level API only provides very limited access to errors via the public API:

https://github.com/ElektraInitiative/libelektra/blob/e299d34ab06b519267b35d2f3195cbb1a13d9caa/src/include/elektra/error.h#L27-L30

The struct `ElektraError` meanwhile looks like this:

https://github.com/ElektraInitiative/libelektra/blob/e299d34ab06b519267b35d2f3195cbb1a13d9caa/src/include/kdbprivate.h#L638-L650

This for example means that an `ElektraError` containing only warnings, cannot be properly handled. The description will be `""` and the error code will be `NULL`.

We should add:
```c
kdb_long_t elektraErrorWarningCount(ElektraError * error);
const ElektraError * elektraErrorGetWarning(ElektraError * error, kdb_long_t index);
```

Possibly adding a `const char * elektraErrorFullDescription(ElektraError * error)` that returns a string describing the error and all its attached warnings, would also make sense. The resulting string would be something like:

```
{error->description}
    Includes warnings:
    {error->warnings[0]->description}
    {error->warnings[1]->description}
    {...}
    {error->warnings[error->warningCount - 1]->description}
```

---

We could also add these functions:

```c
const char * elektraErrorModule(ElektraError * error);
const char * elektraErrorFile(ElektraError * error);
kdb_long_t elektraErrorLine(ElektraError * error);
```

However, these are only useful, if the `ElektraError` was created via `elektraErrorFromKey`, i.e. for errors coming directly from the low-level API (most likely from `kdbGet()` or `kdbSet()`). For errors from the high-level API, they will always return `"highlevel"`, `"unknown"` and `0` respectively.

**Comment by kodebach** [comment]
Personally, I think we should add `elektraErrorWarningCount`, `elektraErrorWarningCount` and `elektraErrorFullDescription` (or some variant thereof).

**Comment by markus2330** [comment]
Thank you for the proposal!

I think the most important (and maybe only needed feature) is that we provide an API call to render the whole error&warnings message with parameter for verbose and debug. Or even better would be if gopts already provides some --elektra-debug and --elektra-verbose so that individual applications do not need to write support for this.

Everything else is only needed for very special UI requirements (where error&warnings are not in a text field).

**Comment by kodebach** [comment]
> Or even better would be if gopts already provides some --elektra-debug and --elektra-verbose so that individual applications do not need to write support for this.

Not really my preferred solution (very magic black box approach), especially, if it cannot be disabled.

> I think the most important (and maybe only needed feature) is that we provide an API call to render the whole error&warnings message with parameter for verbose and debug.

What would be the difference between debug and verbose?
In `kdb` verbose mode adds `mountpoint` and `configfile`, but in the high-level API those are known already.

I assume debug would add the module, file name and line number?
If this information is needed, it would make a lot more sense to actually debug the application. The module (i.e. which plugin caused the error) might be interesting sometimes, but it should already be obvious from the error message itself. Also, as stated above, these three are completely useless, if the error comes from the high-level API itself.

> Everything else is only needed for very special UI requirements

I disagree. A server application might want to properly log errors/warnings with various tags etc. This may be as simple as using a special output format so the log file can be parsed more easily. It would be very annoying, if errors and warnings cannot be separated into different log entries.

**Comment by markus2330** [comment]
> Not really my preferred solution (very magic black box approach), especially, if it cannot be disabled.

Alternatively, we could always print everything because unlike "when working with `kdb`" errors/warnings should rarely be displayed.

>  What would be the difference between debug and verbose?

verbose also prints the name of the config file (and others), debug prints source code line numbers of where the error was set. @Piankero can you add documentation about this?

> Also, as stated above, these three are completely useless, if the error comes from the high-level API itself.

I agree with the module but why should the file name and line number be useless? I would need it to know where to look.

>  I disagree. A server application might want to properly log errors/warnings with various tags etc. This may be as simple as using a special output format so the log file can be parsed more easily. It would be very annoying, if errors and warnings cannot be separated into different log entries.

Ok, I agree, the sentence should be "Everything else is only needed for very special requirements". Good behaving server applications would print and log all information they have if they fail to start. Warnings are sometimes essential to find out the concrete reason.

**Comment by kodebach** [comment]
I think the best compromise is to introduce:

```c
// prints error including warnings to stderr
elektraErrorPrint (ElektraError * error, kdb_boolean_t verbose, kdb_boolean_t debug);

kdb_long_t elektraErrorWarningCount(ElektraError * error);
const ElektraError * elektraErrorGetWarning(ElektraError * error, kdb_long_t index);
const char * elektraErrorModule(ElektraError * error);
const char * elektraErrorConfigfile(ElektraError * error);
const char * elektraErrorMountpoint(ElektraError * error);
const char * elektraErrorFile(ElektraError * error);
kdb_long_t elektraErrorLine(ElektraError * error);
```

The `elektraErrorPrint` would be simple to use, for new applications and the accessor functions can be used, if more granular or differently structured information is required. The only question is, whether we need both `verbose` and `debug` and what information they should include.

IMO it should be enough to have `verbose`. Enabling `verbose` would add `configfile` and possibly `mountpoint`, since those mean something to the user. (They could be useful, if someone mounted a secondary file below the applications config to replace some keys.)
The remaining information will only be useful to a developer. And in many cases it will only be useful to someone with access to the Elektra source code. If someone is willing to dig into Elektra's source, I think running `gdb` and attaching a breakpoint to `elektraErrorPrint` should also be manageable. Once you are in the debugger, inspecting the errors remaining fields is trivial.

**Comment by Piankero** [comment]
> verbose also prints the name of the config file (and others), debug prints source code line numbers of where the error was set. @Piankero can you add documentation about this?

What exactly do you want me to add here? It is already documented in the design decision about the new error message format.

**Comment by markus2330** [comment]
> elektraErrorPrint

I am not  in favor of a function that directly prints. It makes much more sense to return a string.

Otherwise your proposal of the API sounds good. I think it would be easier to discuss the details of the API in a PR.

> IMO it should be enough to have verbose.

At the moment we have verbose+debug, to change this would require several changes, including revising the decision doc/decisions/error_message_format.md


> What exactly do you want me to add here? It is already documented in the design decision about the new error message format.

It only "documents" the format but not which meta data exists. Furthermore, the decisions should only describe how we decided, how it actually is should be in separate documentation.

**Comment by kodebach** [comment]
> At the moment we have verbose+debug, to change this would require several changes, including revising the decision doc/decisions/error_message_format.md

I'm not proposing to get rid of the debug setting in the `kdb` tool. I just think we don't need it in the new high-level API function.

> It only "documents" the format but not which meta data exists. Furthermore, the decisions should only describe how we decided, how it actually is should be in separate documentation.

The spec of the `error/*` and `warning/#/*` metadata should be in a separate document anyway. They are completely unrelated to the format of the messages that `kdb` prints. IMO there should be a `doc/dev/error-metadata.md` documenting these.

**Comment by markus2330** [comment]
> I'm not proposing to get rid of the debug setting in the kdb tool. I just think we don't need it in the new high-level API function.

And include debug+verbose information together if verbose is set? Even if debug without verbose might  be needed rarely such an inconsistency in the features can disturb nevertheless. Especially we would not be able to share docu across different APIs.

> They are completely unrelated to the format of the messages that kdb prints.

They are very much related as the error messages consists of the information from the metadata. But of course it also makes sense to explain these two concepts separately.
