### ISSUE TITLE
document+fix possible error codes in kdb*

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2956]
There are some undocumented expectations of which error is possible in which kdb* function. We should document this, similar to how possible exceptions are documented in Java. And if some errors are unexpected in some situations, we should fix this.

- kdbOpen (here ideally only a few fatal errors should be possible, as nothing can be done if kdbOpen fails, see also #2955 )
  - Resource (in particular Memory Allocation)
  - Installation (would be the typical error people sometimes actually experience)
  - Logical Assertion (bugs in kdbOpen)
- kdbGet: everything but Conflicting State
- kdbSet: everything
- kdbClose: basically only Logical Assertion (bugs in Elektra)

**Comment by Piankero** [comment]
Not related to visible error messages.
As discussed in the Elektra meeting I may unassign myself.

**Comment by markus2330** [comment]
This is very much visible to API users. But I see it will be a lot of work to find out which errors might be added where.

**Comment by markus2330** [comment]
@lawli3t here is some docu of which errors might be thrown by which function.

**Comment by markus2330** [comment]
@lawli3t can you make this issue more concrete so that we can hand it over?
