### ISSUE TITLE
testshell_markdown_tutorial_crypto fails

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2957]
On my laptop, which uses buster and has several gpg keys, testshell_markdown_tutorial_crypto fails. If the test is executed with `ctest -V -R testshell_markdown_tutorial_crypto` it opens a pinentry for my key, which obviously should not be like this as the test case should have its own key.

```
Test project /home/markus/Projekte/Elektra/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 220
    Start 220: testshell_markdown_tutorial_crypto

220: Test command: /home/markus/Projekte/Elektra/build/tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh "/home/markus/Projekte/Elektra/current/doc/tutorials/crypto.md"
220: Environment variables: 
220:  LD_LIBRARY_PATH=/home/markus/Projekte/Elektra/build/lib
220: Test timeout computed to be: 1500
220: Input: /home/markus/Projekte/Elektra/current/doc/tutorials/crypto.md
220: kdb mount test.ini user/tests ini
220: kdb set user/tests/password 1234
220: kdb file user/tests/password | xargs cat
220: kdb rm user/tests/password
220: kdb umount user/tests
220: kdb mount test.ini user/tests fcrypt "encrypt/key=$(kdb gen-gpg-testkey)" ini
220: kdb set user/tests/password 1234
220: 
220: ERROR - RET:
220: Return value “5” does not match “0”
220: 
220: kdb file user/tests/password | xargs cat
220: 
220: ERROR - RET:
220: Return value “123” does not match “0”
220: 
220: kdb rm user/tests/password
220: 
220: ERROR - RET:
220: Return value “11” does not match “0”
220: 
220: kdb umount user/tests
220: kdb mount test.ini user/tests fcrypt "sign/key=$(kdb gen-gpg-testkey)" ini
220: kdb set user/tests/password 1234
220: 
220: ERROR - RET:
220: Return value “5” does not match “0”
220: 
220: kdb file user/tests/password | xargs cat
220: 
220: ERROR - RET:
220: Return value “123” does not match “0”
220: 
220: kdb rm user/tests/password
220: 
220: ERROR - RET:
220: Return value “11” does not match “0”
220: 
220: kdb umount user/tests
220: kdb mount test.ini user/tests fcrypt "sign/key=$(kdb gen-gpg-testkey),encrypt/key=$(kdb gen-gpg-testkey)" ini
220: kdb set user/tests/password 1234
220: 
220: ERROR - RET:
220: Return value “5” does not match “0”
220: 
220: kdb file user/tests/password | xargs cat
220: 
220: ERROR - RET:
220: Return value “123” does not match “0”
220: 
220: kdb rm user/tests/password
220: 
220: ERROR - RET:
220: Return value “11” does not match “0”
220: 
220: kdb umount user/tests
220: kdb mount test.ini user/tests crypto_gcrypt "crypto/key=$(kdb gen-gpg-testkey)" base64 ini
220: kdb setmeta user/tests/password crypto/encrypt 1
220: kdb set user/tests/password 1234
220: kdb set user/tests/unencrypted "I am not encrypted"
220: kdb file user/tests/password | xargs cat
220: kdb setmeta user/tests/password crypto/encrypt 0
220: kdb file user/tests/password | xargs cat
220: kdb rm user/tests/unencrypted
220: kdb rm user/tests/password
220: kdb umount user/tests
220: shell_recorder /tmp/tmp.SFkbumzoDP RESULTS: 31 test(s) done 9 error(s).
220: 
220: —— Protocol ————————————————————————————————————————————————————
220: CMD: kdb mount test.ini user/tests ini
220: RET: 0
220: 
220: CMD: kdb set user/tests/password 1234
220: RET: 0
220: STDOUT: Create a new key user/tests/password with string "1234"
220: 
220: CMD: kdb file user/tests/password | xargs cat
220: RET: 0
220: STDOUT: password=1234
220: 
220: CMD: kdb rm user/tests/password
220: RET: 0
220: 
220: CMD: kdb umount user/tests
220: RET: 0
220: 
220: CMD: kdb mount test.ini user/tests fcrypt "encrypt/key=$(kdb gen-gpg-testkey)" ini
220: RET: 0
220: 
220: CMD: kdb set user/tests/password 1234
220: RET: 5
220: === FAILED return value does not match expected pattern 0
220: STDERR: Sorry, module fcrypt issued the error C01100:
220: Resource: Renaming file /tmp/test.ini.28619:1568523969.513222.tmpiKxwWb to /home/markus/.config/test.ini.28619:1568523969.513222.tmp failed. Reason: Invalid cross-device link
220: ERROR: C01100
220: 
220: CMD: kdb file user/tests/password | xargs cat
220: RET: 123
220: === FAILED return value does not match expected pattern 0
220: STDERR: cat: /home/markus/.config/test.ini: Datei oder Verzeichnis nicht gefunden
220: 
220: CMD: kdb rm user/tests/password
220: RET: 11
220: === FAILED return value does not match expected pattern 0
220: STDERR: Did not find the key
220: 
220: CMD: kdb umount user/tests
220: RET: 0
220: 
220: CMD: kdb mount test.ini user/tests fcrypt "sign/key=$(kdb gen-gpg-testkey)" ini
220: RET: 0
220: 
220: CMD: kdb set user/tests/password 1234
220: RET: 5
220: === FAILED return value does not match expected pattern 0
220: STDERR: Sorry, module fcrypt issued the error C01100:
220: Resource: Renaming file /tmp/test.ini.28833:1568523969.829088.tmpYQyRfB to /home/markus/.config/test.ini.28833:1568523969.829088.tmp failed. Reason: Invalid cross-device link
220: ERROR: C01100
220: 
220: CMD: kdb file user/tests/password | xargs cat
220: RET: 123
220: === FAILED return value does not match expected pattern 0
220: STDERR: cat: /home/markus/.config/test.ini: Datei oder Verzeichnis nicht gefunden
220: 
220: CMD: kdb rm user/tests/password
220: RET: 11
220: === FAILED return value does not match expected pattern 0
220: STDERR: Did not find the key
220: 
220: CMD: kdb umount user/tests
220: RET: 0
220: 
220: CMD: kdb mount test.ini user/tests fcrypt "sign/key=$(kdb gen-gpg-testkey),encrypt/key=$(kdb gen-gpg-testkey)" ini
220: RET: 0
220: 
220: CMD: kdb set user/tests/password 1234
220: RET: 5
220: === FAILED return value does not match expected pattern 0
220: STDERR: Sorry, module fcrypt issued the error C01100:
220: Resource: Renaming file /tmp/test.ini.29064:1568523970.266048.tmp7T6B0X to /home/markus/.config/test.ini.29064:1568523970.266048.tmp failed. Reason: Invalid cross-device link
220: ERROR: C01100
220: 
220: CMD: kdb file user/tests/password | xargs cat
220: RET: 123
220: === FAILED return value does not match expected pattern 0
220: STDERR: cat: /home/markus/.config/test.ini: Datei oder Verzeichnis nicht gefunden
220: 
220: CMD: kdb rm user/tests/password
220: RET: 11
220: === FAILED return value does not match expected pattern 0
220: STDERR: Did not find the key
220: 
220: CMD: kdb umount user/tests
220: RET: 0
220: 
220: CMD: kdb mount test.ini user/tests crypto_gcrypt "crypto/key=$(kdb gen-gpg-testkey)" base64 ini
220: RET: 0
220: 
220: CMD: kdb setmeta user/tests/password crypto/encrypt 1
220: RET: 0
220: 
220: CMD: kdb set user/tests/password 1234
220: RET: 0
220: STDOUT: Set string to "1234"
220: 
220: CMD: kdb set user/tests/unencrypted "I am not encrypted"
220: RET: 0
220: STDOUT: Create a new key user/tests/unencrypted with string "I am not encrypted"
220: 
220: CMD: kdb file user/tests/password | xargs cat
220: RET: 0
220: STDOUT: unencrypted=I am not encrypted
220: #@META crypto/encrypt = 1
220: password=@BASE64IyFjcnlwdG8wMBEAAAAtetcvCr4QmzanFLTfM1CsHkl03scQOwm8ywpbowM7lqGFB3W3G37UCSmPr3ugIpq6
220: 
220: CMD: kdb setmeta user/tests/password crypto/encrypt 0
220: RET: 0
220: 
220: CMD: kdb file user/tests/password | xargs cat
220: RET: 0
220: STDOUT: unencrypted=I am not encrypted
220: #@META crypto/encrypt = 0
220: password=1234
220: 
220: CMD: kdb rm user/tests/unencrypted
220: RET: 0
220: 
220: CMD: kdb rm user/tests/password
220: RET: 0
220: 
220: CMD: kdb umount user/tests
220: RET: 0
220: ————————————————————————————————————————————————————————————————
1/1 Test #220: testshell_markdown_tutorial_crypto ...***Failed    4.10 sec

0% tests passed, 1 tests failed out of 1

Label Time Summary:
kdbtests    =   4.10 sec*proc (1 test)
memleak     =   4.10 sec*proc (1 test)

Total Test time (real) =   4.11 sec

The following tests FAILED:
        220 - testshell_markdown_tutorial_crypto (Failed)
Errors while running CTest
```

**Comment by markus2330** [comment]
It also fails on another computer. Again gpg prompts me for my password.

```
        Start 220: testshell_markdown_tutorial_crypto
175/267 Test #220: testshell_markdown_tutorial_crypto ............***Failed    6.59 sec
Input: /home/markus/Projekte/Elektra/current/doc/tutorials/crypto.md
kdb mount test.ini user/tests ini
kdb set user/tests/password 1234
kdb file user/tests/password | xargs cat
kdb rm user/tests/password
kdb umount user/tests
kdb mount test.ini user/tests fcrypt "encrypt/key=$(kdb gen-gpg-testkey)" ini
kdb set user/tests/password 1234

ERROR - RET:
Return value “5” does not match “0”

kdb file user/tests/password | xargs cat

ERROR - RET:
Return value “123” does not match “0”

kdb rm user/tests/password

ERROR - RET:
Return value “11” does not match “0”

kdb umount user/tests
kdb mount test.ini user/tests fcrypt "sign/key=$(kdb gen-gpg-testkey)" ini
kdb set user/tests/password 1234

ERROR - RET:
Return value “5” does not match “0”

kdb file user/tests/password | xargs cat

ERROR - RET:
Return value “123” does not match “0”

kdb rm user/tests/password

ERROR - RET:
Return value “11” does not match “0”

kdb umount user/tests
kdb mount test.ini user/tests fcrypt "sign/key=$(kdb gen-gpg-testkey),encrypt/key=$(kdb gen-gpg-testkey)" ini
kdb set user/tests/password 1234

ERROR - RET:
Return value “5” does not match “0”

kdb file user/tests/password | xargs cat

ERROR - RET:
Return value “123” does not match “0”

kdb rm user/tests/password

ERROR - RET:
Return value “11” does not match “0”

kdb umount user/tests
kdb mount test.ini user/tests crypto_gcrypt "crypto/key=$(kdb gen-gpg-testkey)" base64 ini
kdb setmeta user/tests/password crypto/encrypt 1
kdb set user/tests/password 1234
kdb set user/tests/unencrypted "I am not encrypted"
kdb file user/tests/password | xargs cat
kdb setmeta user/tests/password crypto/encrypt 0
kdb file user/tests/password | xargs cat
kdb rm user/tests/unencrypted
kdb rm user/tests/password
kdb umount user/tests
shell_recorder /tmp/tmp.lVwm5hFVVW RESULTS: 31 test(s) done 9 error(s).

—— Protocol ————————————————————————————————————————————————————
CMD: kdb mount test.ini user/tests ini
RET: 0

CMD: kdb set user/tests/password 1234
RET: 0
STDOUT: Create a new key user/tests/password with string "1234"

CMD: kdb file user/tests/password | xargs cat
RET: 0
STDOUT: password=1234

CMD: kdb rm user/tests/password
RET: 0

CMD: kdb umount user/tests
RET: 0

CMD: kdb mount test.ini user/tests fcrypt "encrypt/key=$(kdb gen-gpg-testkey)" ini
RET: 0

CMD: kdb set user/tests/password 1234
RET: 5
=== FAILED return value does not match expected pattern 0
STDERR: Sorry, module fcrypt issued the error C01100:
Resource: Renaming file /tmp/test.ini.17552:1569990332.299640.tmpUYJgsU to /home/markus/.config/test.ini.17552:1569990332.299640.tmp failed. Reason: Invalid cross-device link
ERROR: C01100

CMD: kdb file user/tests/password | xargs cat
RET: 123
=== FAILED return value does not match expected pattern 0
STDERR: cat: /home/markus/.config/test.ini: Datei oder Verzeichnis nicht gefunden

CMD: kdb rm user/tests/password
RET: 11
=== FAILED return value does not match expected pattern 0
STDERR: Did not find the key

CMD: kdb umount user/tests
RET: 0

CMD: kdb mount test.ini user/tests fcrypt "sign/key=$(kdb gen-gpg-testkey)" ini
RET: 0

CMD: kdb set user/tests/password 1234
RET: 5
=== FAILED return value does not match expected pattern 0
STDERR: Sorry, module fcrypt issued the error C01100:
Resource: Renaming file /tmp/test.ini.17766:1569990332.433638.tmpEmmql5 to /home/markus/.config/test.ini.17766:1569990332.433638.tmp failed. Reason: Invalid cross-device link
ERROR: C01100

CMD: kdb file user/tests/password | xargs cat
RET: 123
=== FAILED return value does not match expected pattern 0
STDERR: cat: /home/markus/.config/test.ini: Datei oder Verzeichnis nicht gefunden

CMD: kdb rm user/tests/password
RET: 11
=== FAILED return value does not match expected pattern 0
STDERR: Did not find the key

CMD: kdb umount user/tests
RET: 0

CMD: kdb mount test.ini user/tests fcrypt "sign/key=$(kdb gen-gpg-testkey),encrypt/key=$(kdb gen-gpg-testkey)" ini
RET: 0

CMD: kdb set user/tests/password 1234
RET: 5
=== FAILED return value does not match expected pattern 0
STDERR: Sorry, module fcrypt issued the error C01100:
Resource: Renaming file /tmp/test.ini.18007:1569990337.12097.tmp2gLKrR to /home/markus/.config/test.ini.18007:1569990337.12097.tmp failed. Reason: Invalid cross-device link
ERROR: C01100

CMD: kdb file user/tests/password | xargs cat
RET: 123
=== FAILED return value does not match expected pattern 0
STDERR: cat: /home/markus/.config/test.ini: Datei oder Verzeichnis nicht gefunden

CMD: kdb rm user/tests/password
RET: 11
=== FAILED return value does not match expected pattern 0
STDERR: Did not find the key

CMD: kdb umount user/tests
RET: 0

CMD: kdb mount test.ini user/tests crypto_gcrypt "crypto/key=$(kdb gen-gpg-testkey)" base64 ini
RET: 0

CMD: kdb setmeta user/tests/password crypto/encrypt 1
RET: 0

CMD: kdb set user/tests/password 1234
RET: 0
STDOUT: Set string to "1234"

CMD: kdb set user/tests/unencrypted "I am not encrypted"
RET: 0
STDOUT: Create a new key user/tests/unencrypted with string "I am not encrypted"

CMD: kdb file user/tests/password | xargs cat
RET: 0
STDOUT: unencrypted=I am not encrypted
#@META crypto/encrypt = 1
password=@BASE64IyFjcnlwdG8wMBEAAABol1npOAf+bYmhCxDfvCkiNywIzjDTNdOMjYOPAywwzIGPr9Fn/C3p8bJuMyXdPOd1

CMD: kdb setmeta user/tests/password crypto/encrypt 0
RET: 0

CMD: kdb file user/tests/password | xargs cat
RET: 0
STDOUT: unencrypted=I am not encrypted
#@META crypto/encrypt = 0
password=1234

CMD: kdb rm user/tests/unencrypted
RET: 0

CMD: kdb rm user/tests/password
RET: 0

CMD: kdb umount user/tests
RET: 0
————————————————————————————————————————————————————————————————
```

**Comment by markus2330** [comment]
As root (other user) this test does not fail. So it has something to do with my gpg config.

`.gnupg/gpg-agent.conf` only has `pinentry-program /usr/bin/pinentry`

.gnupg/gpg.conf has:
```
no-greeting
default-key  4C9580F50B2F0DDC
force-v3-sigs
escape-from-lines
lock-once
keyserver  hkp://pgp.mit.edu
keyserver  hkp://pgp.mit.edu
use-agent
```

Maybe the default-key is the problem? Or lock-once?

**Comment by petermax2** [comment]
> Maybe the default-key is the problem? Or lock-once?

Does `kdb mount`  require root privileges in the `user` namespace?

**Comment by markus2330** [comment]
Yes, `kdb mount` currently always needs root privilege. Feature request #1074 is still open.

**Comment by petermax2** [comment]
So actually the test script should fail at 

    kdb mount test.ini user/tests ini

which seems to succed atm. I will look into it.

**Comment by markus2330** [comment]
> which seems to succed atm.

on my PC it succeeds because my user has permission to write to system/ (and as such I can mount as user).

Don't you think it is related to my gpg config?

**Comment by petermax2** [comment]
> Don't you think it is related to my gpg config?

Maybe,.. I don't even have a `agent.conf`. With default gpg settings it seems to work fine. Maybe you are being asked for a PIN entry or a password in the background while the script is running?

**Comment by markus2330** [comment]
Yes, as already said before I am asked for a PIN entry (see top-entry). So somehow the tests or the plugin seem to use keys they should not use.

**Comment by petermax2** [comment]
I have a hard time reproducing the behavior. I set up a Debian VM and copied your config (with adapted key ID), but the test does not fail.

	root@elektra-testing:/home/pnirschl/libelektra/build# ctest -V -R testshell_markdown_tutorial_crypto
	UpdateCTestConfiguration  from :/home/pnirschl/libelektra/build/DartConfiguration.tcl
	Parse Config file:/home/pnirschl/libelektra/build/DartConfiguration.tcl
	UpdateCTestConfiguration  from :/home/pnirschl/libelektra/build/DartConfiguration.tcl
	Parse Config file:/home/pnirschl/libelektra/build/DartConfiguration.tcl
	Test project /home/pnirschl/libelektra/build
	Constructing a list of tests
	Done constructing a list of tests
	Updating test list for fixtures
	Added 0 tests to meet fixture requirements
	Checking test dependency graph...
	Checking test dependency graph end
	test 174
	    Start 174: testshell_markdown_tutorial_crypto
	    
	174: Test command: /home/pnirschl/libelektra/build/tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh "/home/pnirschl/libelektra/doc/tutorials/crypto.md"
	174: Environment variables: 
	174:  LD_LIBRARY_PATH=/home/pnirschl/libelektra/build/lib
	174: Test timeout computed to be: 1500
	174: Input: /home/pnirschl/libelektra/doc/tutorials/crypto.md
	174: kdb mount test.ini user/tests ini
	174: kdb set user/tests/password 1234
	174: kdb file user/tests/password | xargs cat
	174: kdb rm user/tests/password
	174: kdb umount user/tests
	174: kdb mount test.ini user/tests fcrypt "encrypt/key=$(kdb gen-gpg-testkey)" ini
	174: kdb set user/tests/password 1234
	174: kdb file user/tests/password | xargs cat
	174: kdb rm user/tests/password
	174: kdb umount user/tests
	174: kdb mount test.ini user/tests fcrypt "sign/key=$(kdb gen-gpg-testkey)" ini
	174: kdb set user/tests/password 1234
	174: kdb file user/tests/password | xargs cat
	174: kdb rm user/tests/password
	174: kdb umount user/tests
	174: kdb mount test.ini user/tests fcrypt "sign/key=$(kdb gen-gpg-testkey),encrypt/key=$(kdb gen-gpg-testkey)" ini
	174: kdb set user/tests/password 1234
	174: kdb file user/tests/password | xargs cat
	174: kdb rm user/tests/password
	174: kdb umount user/tests
	174: kdb mount test.ini user/tests crypto_gcrypt "crypto/key=$(kdb gen-gpg-testkey)" base64 ini
	174: kdb setmeta user/tests/password crypto/encrypt 1
	174: kdb set user/tests/password 1234
	174: kdb set user/tests/unencrypted "I am not encrypted"
	174: kdb file user/tests/password | xargs cat
	174: kdb setmeta user/tests/password crypto/encrypt 0
	174: kdb file user/tests/password | xargs cat
	174: kdb rm user/tests/unencrypted
	174: kdb rm user/tests/password
	174: kdb umount user/tests
	174: shell_recorder /tmp/tmp.eJiHztn7vc RESULTS: 31 test(s) done 0 error(s).
	1/1 Test #174: testshell_markdown_tutorial_crypto ...   Passed   12.54 sec
	
	The following tests passed:
		testshell_markdown_tutorial_crypto
		
	100% tests passed, 0 tests failed out of 1
	 
	Label Time Summary:
	kdbtests    =  12.54 sec*proc (1 test)
	memleak     =  12.54 sec*proc (1 test)
    
	Total Test time (real) =  12.86 sec
	root@elektra-testing:/home/pnirschl/libelektra/build# cat ~/.gnupg/gpg-agent.conf 
	pinentry-program /usr/bin/pinentry
	root@elektra-testing:/home/pnirschl/libelektra/build# cat ~/.gnupg/gpg.conf 
	no-greeting
	default-key  272402A0F3C244704097E8D7F5C6168A7AB0BC4A
	force-v3-sigs
	escape-from-lines
	lock-once
	keyserver  hkp://pgp.mit.edu
	keyserver  hkp://pgp.mit.edu
	use-agent
	root@elektra-testing:/home/pnirschl/libelektra/build# 

My setup:

    root@elektra-testing:/home/pnirschl/libelektra/build# gpg2 --version
    gpg (GnuPG) 2.2.12
    libgcrypt 1.8.4
    Copyright (C) 2018 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

    Home: /root/.gnupg
    Supported algorithms:
    Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
    Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
            CAMELLIA128, CAMELLIA192, CAMELLIA256
    Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
    Compression: Uncompressed, ZIP, ZLIB, BZIP2
    root@elektra-testing:/home/pnirschl/libelektra/build# neofetch 
           _,met$$$$$gg.          root@elektra-testing 
        ,g$$$$$$$$$$$$$$$P.       -------------------- 
      ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 10 (buster) x86_64 
     ,$$P'              `$$$.     Host: VirtualBox 1.2 
    ',$$P       ,ggs.     `$$b:   Kernel: 4.19.0-6-amd64 
    `d$$'     ,$P"'   .    $$$    Uptime: 15 mins 
     $$P      d$'     ,    $$P    Packages: 451 (dpkg) 
     $$:      $$.   -    ,d$$'    Shell: bash 5.0.3 
     $$;      Y$b._   _,d$P'      CPU: Intel i7-4771 (4) @ 3.418GHz 
     Y$$.    `.`"Y$$$$P"'         GPU: VMware SVGA II Adapter 
     `$$b      "-.__              Memory: 108MiB / 1994MiB 
      `Y$$
       `Y$$.                                              
         `$$b.
           `Y$$b.
              `"Y$b._
                  `"""

    root@elektra-testing:/home/pnirschl/libelektra/build#

**Comment by petermax2** [comment]
Now I can reproduce it as "regular" user (i.e. no root). The trick is to set the KDB database to a user directory.

    cmake -DENABLE_COVERAGE=OFF -DENABLE_OPTIMIZATIONS=OFF -DENABLE_DEBUG=ON -DENABLE_LOGGER=ON -DBUILD_STATIC=OFF -DCMAKE_INSTALL_PREFIX="$PWD/conf" -DKDB_DB_SYSTEM="$PWD/conf" -DINSTALL_SYSTEM_FILES=OFF -DPLUGINS="ALL" -DTOOLS="kdb;gen-gpg-testkey" ..

**Comment by markus2330** [comment]
Great! Yes, I also cannot reproduce it as root (see above: "As root (other user) this test does not fail.")

**Comment by petermax2** [comment]
I found the problem: `gen-gpg-testkey` is looking for "elektra" and I guess your e-mail address contains something with "elektra.org", so it will falsely use it as test-key which is supposed to have no password...

https://github.com/ElektraInitiative/libelektra/blob/fa6d9597dfad75ccd712a7628b404e2eee218cb0/src/tools/gen-gpg-testkey/gen-gpg-testkey.c#L36-L37

**Comment by markus2330** [comment]
Yes, that sounds very much like the problem :100: 

If possible please also improve the error message, so that the next time it is more clear that a wrong key was taken and why it failed. Maybe I simply used the wrong password for this key? Or did you also check if the encrypted binary is as expected? (which obviously is different when encrypted with another key)

**Comment by petermax2** [comment]
The error message comes from GPG. I can not interpret the output of GPG, also the return codes are not documented anywhere.

**Comment by markus2330** [comment]
```
STDERR: Sorry, module fcrypt issued the error C01100:
Resource: Renaming file /tmp/test.ini.17552:1569990332.299640.tmpUYJgsU to /home/markus/.config/test.ini.17552:1569990332.299640.tmp failed. Reason: Invalid cross-device link
ERROR: C01100
```

does not sound like it comes from gpg. Maybe this error overwrites the error of gpg?

**Comment by petermax2** [comment]
Hm I just get this one:

    174: ERROR: C01330@Plugin Misbehavior: GPG failed with return value 512. gpg: invalid radix64 character 2D skipped@gpg: invalid radix64 character 2D skipped@gpg: invalid radix64 character 2D skipped@gpg: invalid radix64 character 2D skipped@gpg: invalid radix64 character 2D skipped@gpg: invalid radix64 character 2D skipped@gpg: invalid radix64 character 2D skipped@gpg: invalid radix64 character 2D skipped@gpg: invalid radix64 character 2D skipped@gpg: invalid radix64 character 2D skipped@gpg: encrypted with 3072-bit RSA key, ID 3D700E2F2BF3A6F4, created 2019-10-06@      "Peter T�@t@V@Mountpoint: user/tests@Configfile: /home/pnirschl/.config/test.ini@At: /home/pnirschl/libelektra/src/plugins/crypto/gpg.c:777@ (in execute at src/tools/kdb/file.cpp:47)
