### ISSUE TITLE
Bachelor Thesis 00828630

### ISSUE THREAD

**Issue by raphi011** [ElektraInitiative/libelektra#2958]
- [ ] Index
- [ ] Introduction
- [ ] Background
- [ ] Methodology
- [ ] Evaluierung
- [ ] Case study, webserver benchmarks
- [ ] Conclusion

**Comment by markus2330** [comment]
Thank you for creating the issue. For completely non-code related tasks it is better if you use the issue tracker of the abgaben repo.
