### ISSUE TITLE
Go Bindings

### ISSUE THREAD

**Issue by raphi011** [ElektraInitiative/libelektra#2959]
See [this](https://github.com/ElektraInitiative/libelektra/pull/2827) pull rqeuest

  - [x] Tests
  - [x] Create a [vanity import](https://sagikazarmark.hu/blog/vanity-import-paths-in-go/), e.g.

**Comment by markus2330** [comment]
Thank you for creating this PR!

**Comment by raphi011** [comment]
@markus2330 can you take a look at the current state of the go bindings? I know you probably want more documentation :) But other than that?

**Comment by markus2330** [comment]
Yes, you are right, the docu definitely needs improvements. The first sentence of the main readme is already broken.

**Comment by raphi011** [comment]
> Yes, you are right, the docu definitely needs improvements. The first sentence of the main readme is already broken.

I'm aware that the docu is not satisfactory yet - but the rest is probably equally important :)

**Comment by markus2330** [comment]
I am aware that you are aware of the not satisfactory docu. But I cannot evaluate the rest as long as I do not know what you wanted to do and how I can use it. Hence docu is required so that I can check if the code does what the docu promises.

**Comment by raphi011** [comment]
I've improved the documentation
