### ISSUE TITLE
Jenkins: Blue Ocean Interface sometimes does not open

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2973]
https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2945/6/ does not load for me

https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2945/6/pipeline/1693 works

Is this a bug in "Blue Ocean" or is the Jenkins server too slow to deliver the page?

**Comment by sanssecours** [comment]
Both example URLs work fine for me. I assume the not loading part is just because our main Jenkins  build server runs on a toaster or something similarly powerful 😊.

**Comment by Mistreated** [comment]
> Is this a bug in "Blue Ocean" or is the Jenkins server too slow to deliver the page?

> Both example URLs work fine for me. I assume the not loading part is just because our main Jenkins build server runs on a toaster or something similarly powerful blush.

I dont think its a bug in "Blue Ocean". More likely is that Jenkins server is too slow.

**Comment by kodebach** [comment]
I agree with the toaster hypothesis. Both links work fine right now, but the Link Checker build also sometimes fails (5 second timeout) for Jenkins links. It happens mostly, when there is high load on the Jenkins server.

**Comment by markus2330** [comment]
For me they also work now, so I agree that it is most likely overload on the server.

Hopefully we can order the new server soon.
