### ISSUE TITLE
kdb mount-website-backend-config error

### ISSUE THREAD

**Issue by d3nwp** [ElektraInitiative/libelektra#2982]
I was trying to configure the (website-)backend:

```sh
kdb mount-website-backend-config
The command kdb spec-mount terminated unsuccessfully with the info:
No plugin that provides check/type/max could be found
Please report the issue at https://issues.libelektra.org/
```
According to @markus2330 its a bug and "check/type/max" and "check/type/min" should be replaced by check/range

Even if I install the plugins, I get the same error:

```sh
cmake -DPLUGINS="dump;resolver_fm_hpu_b;list;spec;newtype" -DTOOLS="ALL;website-backend;website-frontend" ..
```

**Comment by markus2330** [comment]
Thank you for reporting this bug!

This is a left-over from our migration from cpptype to type (done by @kodebach).

The change would be fairly easy. It only involves changes the check/type/min or max lines in ./src/tools/website-backend/config-specification.ini.in

**Comment by kodebach** [comment]
> `-DPLUGINS="dump;resolver_fm_hpu_b;list;spec;newtype"`

It should also be just `type` not `newtype`.

**Comment by markus2330** [comment]
@d3nwp where did you get the cmake statement from? I cannot find newtype in our repo.

**Comment by kodebach** [comment]
> I cannot find newtype in our repo.

The new `type` was called `newtype` for a short period, possibly a file was missed by a regex replace...

**Comment by d3nwp** [comment]
> 
> 
> @d3nwp where did you get the cmake statement from? I cannot find newtype in our repo.

here: [cpptype](https://www.libelektra.org/plugins/cpptype)

**Comment by markus2330** [comment]
Ahh, ok. Yes, the website is a bit out-dated because of #2897

a7.libelektra.org should contain a later version (from successful master builds)

**Comment by mpranj** [comment]
Should be obsolete since the removal of the website backend in #3469.
