### ISSUE TITLE
Jenkins: Internal Compiler Error

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2986]
# Description

Looks like `i7` sometimes fails to compile Elektra in the Docker [Web UI Base image](https://github.com/ElektraInitiative/libelektra/blob/master/scripts/docker/webui/base/Dockerfile), reporting [internal compiler errors](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/964/pipeline/):

> c++: internal compiler error: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.

. I also noticed this issue on my computer, which also contains an i7 processor. I fixed the problem on my machine by using only one simultaneous `make` job. I do not think removing the text `-j ${PARALLEL}` from the Dockerfile:

https://github.com/ElektraInitiative/libelektra/blob/f0735fd734a4dd6eb958442beeda4c08c213066b/scripts/docker/webui/base/Dockerfile#L30

is an appropriate option for the build server though.

**Comment by markus2330** [comment]
Thank you for reporting this problem and proposing a solution!

Is this an out-of-memory issue? Maybe a different compiler also solves the problem, we could upgrade the Ubuntu version for the Web UI Base image.

This fix maybe can be done together with #2913 which is the more urgent problem for now.

**Comment by sanssecours** [comment]
> Is this an out-of-memory issue?

I do not think so, at least I would expect a different error message in that case.

> Maybe a different compiler also solves the problem, we could upgrade the Ubuntu version for the Web UI Base image.

I also think that a newer compiler should probably solve the issue. It should not be that hard to use a less outdated version of Ubuntu for the image.

**Comment by markus2330** [comment]
Yes, lets try upgrading the base image.

**Comment by markus2330** [comment]
Should be solved now, please reopen if it occurs again.
