### ISSUE TITLE
Jenkins: Fetching of Docker Images Fails

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2995]
# Description

Looks like the Jenkins build now [fails in the “Pull Docker Images” stage](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/974/pipeline):

```
java.io.IOException: Unexpected EOF
	at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:99)
	at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
Also:   <cycle to java.io.IOException: Unexpected EOF>
	Caused: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on v2-debian-buster failed. The channel is closing down or has closed down
…
Also:   <cycle to java.io.IOException: Unexpected EOF>
	Caused: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on v2-debian-buster failed. The channel is closing down or has closed down
Caused: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on v2-debian-buster failed. The channel is closing down or has closed down
	at hudson.remoting.Channel.call(Channel.java:948)
	at hudson.EnvVars.getRemote(EnvVars.java:408)
	at hudson.model.Computer.getEnvironment(Computer.java:1188)
	at org.jenkinsci.plugins.workflow.support.steps.ExecutorStepExecution$PlaceholderTask$PlaceholderExecutable.run(ExecutorStepExecution.java:691)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
```

. Maybe this problem has also something to do with the recent [failures of the build job  `libelektra-daily`](https://github.com/ElektraInitiative/libelektra/issues/2994).

**Comment by markus2330** [comment]
It is very likely that this is related. Maybe the docker registry is down?

**Comment by sanssecours** [comment]
> Maybe the docker registry is down?

I do not think so. At least

```sh
docker run --rm anoxis/registry-cli -r https://hub-public.libelektra.org
```

and downloading an images via

```sh
docker pull hub-public.libelektra.org/build-elektra-alpine:201909-78555f42df1da5d02d2b9bb9c131790fcd98511c3dea33c6d1ecee06b45fae55
```

seems to work.

**Comment by sanssecours** [comment]
Looks like the problem is the [build server `v2-debian-buster`](https://build.libelektra.org/jenkins/job/libelektra/job/master/977/console):

> ERROR: Issue with creating launcher for agent v2-debian-buster. The agent is being disconnected

. I temporarily took the node offline and fetching the images now seems to work again.

**Comment by markus2330** [comment]
I upgraded Docker on v2. When I type:

`docker pull hub-public.libelektra.org/build-elektra-alpine:201909-78555f42df1da5d02d2b9bb9c131790fcd98511c3dea33c6d1ecee06b45fae55` it works (pulls the image) but when I use `docker pull hub.libelektra.org/build-elektra-debian-buster-doc:201909-75ef639fd76156c406114ce9c5ebf0c6741319a31ae5f2f6782fc9092bfbc9ae`, then following error happens:

```
Error response from daemon: Get https://hub.libelektra.org/v2/build-elektra-debian-buster-doc/manifests/201909-75ef639fd76156c406114ce9c5ebf0c6741319a31ae5f2f6782fc9092bfbc9ae: no basic auth credentials
```

@Mistreated @ingwinlu any idea?

**Comment by markus2330** [comment]
With v2 connected, the same error happen again: https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/987/pipeline/44
