### ISSUE TITLE
Remove references to obsolete "error code 30" in the documentation

### ISSUE THREAD

**Issue by raphi011** [ElektraInitiative/libelektra#2996]
There are several [references](https://github.com/ElektraInitiative/libelektra/blob/master/src/libs/elektra/kdb.c#L99) to error code 30 (conflict) in the codebase - which is outdated.

**Comment by markus2330** [comment]
Thank you for reporting this problem!

**Comment by Piankero** [comment]
I searched through all available code via regex and found some other old occurrences too. I fixed them in my general improvement branch: https://github.com/ElektraInitiative/libelektra/pull/2950/commits/1b1cc111323e4bdffbf2f4f62a4633701f81e60a

**Comment by markus2330** [comment]
Thank you! But please take care that the PR is not getting too big. It would be good to merge it soon.
