### ISSUE TITLE
Remove usage of deprecated flags from code / examples

### ISSUE THREAD

**Issue by raphi011** [ElektraInitiative/libelektra#2997]
[Code](https://github.com/ElektraInitiative/libelektra/blob/master/src/libs/elektra/kdb.c#L571) and [Examples](https://github.com/ElektraInitiative/libelektra/blob/master/examples/kdbintro.c#L14) still used deprecated keynames like `KEY_CASCADING_NAME`

**Comment by markus2330** [comment]
Thank you for reporting this problem!

**Comment by markus2330** [comment]
There is no such occurrence anymore, except of old news:

```
grep -rH KEY_CASCADING_NAME
doc/news/2014-12-02_0.8.10.md:changes in kdb.h is the addition of `KEY_CASCADING_NAME` and
doc/news/2014-12-02_0.8.10.md:Key *c = keyNew("/org/freedesktop", KEY_CASCADING_NAME, KEY_END);
doc/news/2015-04-03_0.8.11.md:Key *parentKey = keyNew("/sw/app/#0", KEY_CASCADING_NAME, KEY_END);
```
