### ISSUE TITLE
Jenkins: Unable to Connect to `i7-debian-buster`

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2999]
# Description

One of the newer Jenkins problems seem to be [connection errors to `i7-debian-buster`](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2998/2/pipeline/611/):

> ERROR: Issue with creating launcher for agent i7-debian-buster. The agent has not been fully initialized yet
> Channel "unknown": Remote call on i7-debian-buster failed. The channel is closing down or has closed down

.

**Comment by markus2330** [comment]
Maybe it was only a short connection problem? At the moment i7 is executing a build job.

**Comment by sanssecours** [comment]
> Maybe it was only a short connection problem?

That might be the case. However, I still think it makes sense to keep this issue open until we know that it wont happen again (often) in the near future.

**Comment by sanssecours** [comment]
Jenkins just reported [another error on `i7-debian-buster`](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/981/pipeline) that seems to be similar to the one described in this issue:

> remote file operation failed

.

**Comment by markus2330** [comment]
Thank you for reporting! Does restarting the job fix the problem?

**Comment by sanssecours** [comment]
> Does restarting the job fix the problem?

Probably, but the Jenkins build might fail again, because of [various other problems](https://github.com/ElektraInitiative/libelektra/issues/2967). As far as I can tell, the probability that the whole Jenkins build finishes successfully is less than 50%.

**Comment by markus2330** [comment]
That is really not good. Luckily, Djordje now starts working on it.

**Comment by markus2330** [comment]
Happened again:

https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/988/pipeline

**Comment by markus2330** [comment]
Is this fixed now? Maybe due to #2984

**Comment by sanssecours** [comment]
> Is this fixed now?

I am not sure. If I remember correctly, I did not see any similar warnings in the last two days though.
