### ISSUE TITLE
use github for proposals

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#300]
Currently [decisions](https://github.com/ElektraInitiative/libelektra/tree/master/doc/decisions) should serve as basis for discussion to achieve good solution. Unfortunately, no much contribution is happening there.

I would propose to use github for such discussions, and using [decisions](https://github.com/ElektraInitiative/libelektra/tree/master/doc/decisions) only for documenting outcome.

**Comment by mpranj** [comment]
This proposal makes sense to me.

**Comment by fberlakovich** [comment]
Good idea. It is happening already anyway ;).

**Comment by petermax2** [comment]
+1
the issue tab appears clearer to me =)

**Comment by markus2330** [comment]
Proposal accepted ;)
