### ISSUE TITLE
Tutorial for merge into Debian package

### ISSUE THREAD

**Issue by Chemin1** [ElektraInitiative/libelektra#3006]
As the tutorial elektra-merge-integration.md has been removed in [this pull request](https://github.com/ElektraInitiative/libelektra/pull/2941#event-2634456496) we should write a similar tutorial.

**Comment by Chemin1** [comment]
I wrote some lines about the plans that we have talked about so far. Writing more does not seem really useful to me at the moment, as the implementation is not ready yet.

**Comment by Chemin1** [comment]
As we postponed this in our offline-discussion yesterday, I guess we can close this issue for the time being and reopen it if necessary.

**Comment by markus2330** [comment]
Yes, it is better if we get a very good 3-way merging for `kdb import`, `kdb editor`, qt-gui and webui. There we will definitely need it. Debian did not show so much interest so far.
