### ISSUE TITLE
Jenkins: git tag sometimes fails

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#3009]
# Description

Seems like the Jenkins build now fails every time when its time to build Debian packages. According to the build server the command

```sh
git tag -a -f -m Jenkins Build #1007 jenkins-master-1007 # timeout=10
```

[does not work](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/1007), printing the error message:

> Could not apply tag jenkins-master-1007

. This failure happened at least in [build 1005](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/1005) up until [build 1009](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/1009) of the `master` branch. The last time the Debian packages were built successfully was [build 983](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/983). The last overall successful Jenkins build was [build 982](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/982) 😭.

**Comment by markus2330** [comment]
Thank you for reporting the problem!

@Mistreated any progress on Debian packaging?

Alternatively, I think it is best to disable Debian Buster packages until @Mistreated has progress.

**Comment by sanssecours** [comment]
> @Mistreated any progress on Debian packaging?

I met Djordje yesterday. As far as I know generating packages for Ubuntu Bionic [should work now](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2932/17/pipeline/363).

**Comment by sanssecours** [comment]
I think the problem lies somewhere in the following code for the [Pipeline SCM Step Plugin](https://plugins.jenkins.io/workflow-scm-step):

https://github.com/ElektraInitiative/libelektra/blob/5519cb8066a096215a3701ca3d8c02fcebe54914/scripts/jenkins/Jenkinsfile#L1050-L1059

. [Here](https://jenkins.io/doc/pipeline/steps/workflow-scm-step/) is some documentation for the plugin.

**Comment by markus2330** [comment]
@ingwinlu do you have an idea?

**Comment by markus2330** [comment]
@Mistreated can you reenable the buster packages together with the Ubuntu packages?

**Comment by sanssecours** [comment]
Seems like commit 883e0e7 [did not fix this problem](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/1017/pipeline).

**Comment by markus2330** [comment]
Master builds now: https://github.com/ElektraInitiative/libelektra/commits/master#

Did you see the problem also somewhere else or can this be closed now?

**Comment by sanssecours** [comment]
Looks like [building the packages still fails sometimes](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/1038/pipeline).

**Comment by markus2330** [comment]
Why are the `git config` commands missing there? 794cfdf7747423ed0240c82987dec69ee2065f01

**Comment by sanssecours** [comment]
> Why are the `git config` commands missing there? [794cfdf](https://github.com/ElektraInitiative/libelektra/commit/794cfdf7747423ed0240c82987dec69ee2065f01)

As far as I know that is the case, because the build step fails before these commands are executed (see also https://github.com/ElektraInitiative/libelektra/issues/3009#issuecomment-535405854)

**Comment by sanssecours** [comment]
[Build 1040](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/1040/pipeline) and [Build 1041](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/1040/pipeline) also failed, because of this issue.

**Comment by markus2330** [comment]
Is there something wrong in the Jenkins configuration? Seems like some module of Jenkins already does this `git tag`.

**Comment by markus2330** [comment]
It still happens but not so often anymore. I removed "urgent".

**Comment by markus2330** [comment]
I think it still happens from time to time. @Mistreated did you already investigate?

**Comment by mpranj** [comment]
> I think it still happens from time to time.

Happens on a regular basis. Sometimes many rebuilds do not help to the point that I gave up on this. Would be great if someone knows how to fix it.

**Comment by Mistreated** [comment]
Can you link the build that fails with this error?

**Comment by mpranj** [comment]
[Here](https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/master/135/pipeline/) is one example from master.

**Comment by Mistreated** [comment]
If this mistake happens from now on again. I would appreciate, if someone could link it if I do not see it immediately (debugging purposes).

**Comment by Mistreated** [comment]
Anyone encountered this problem last 10 days?

**Comment by Mistreated** [comment]
This error does not repeat after a default git user is set:

`[user]
        name = Jenkins
        email = Jenkins <autobuilder@libelektra.org>
`

Closed.

**Comment by markus2330** [comment]
It looks like this issue popped up again! It is some undocumented assumption of how build server agents are configured.

The error occurs on master: https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/master/793/pipeline

```
 > git tag -a -f -m Jenkins Build #793 jenkins-master-793 # timeout=10

Could not apply tag jenkins-master-793
```

@lukashartl can you please fix the Ansible scripts that the default git user will be set (see post directly above) and apply it to l1? I disabled l1 till then.

**Comment by markus2330** [comment]
@lukashartl any update here? I see l1 is enabled again?

**Comment by lukashartl** [comment]
has been fixed and documented here: https://github.com/ElektraInitiative/buildserver/issues/105

**Comment by markus2330** [comment]
Thx, so this issue can be closed!
