### ISSUE TITLE
provide internal arrays

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#301]
We already have arrays like
```
array
array/#0
array/#1
```

They serve their purpose for recursive structures, i.e. when `array/#0` has or might have subkeys.

Often it is quite clear that recursion is not needed. Then these arrays are cumbersome to use.

I propose to introduce light-weight arrays that are stored within a single `Key`.

Usage with new API:
```
const char ** keyGetArray(Key *k);
int keySetArray(Key *k, const char ** value);
```
Internally, its stored: `<first string>\0<second string>\0`. Metadata `binary` and `array` would be set, then.

New metadata:
```
[array]
type=empty
usedby/api=keyGetArray keySetArray
```

## Drawbacks/Implications

Storage plugins need support for it (they could write it as binary blob, though).

## Status

This is only a first draft. Open points are:

- better integration with current arrays
- allow to use it within metadata

**Comment by markus2330** [comment]
I think we should rather reject this proposal and get the current form of arrays more efficient.

**Comment by KurtMi** [comment]
> I think we should rather reject this proposal

me too.

**Comment by markus2330** [comment]
rejection
