### ISSUE TITLE
Codegen Tutorials: Incorrect app paths

### ISSUE THREAD

**Issue by bauhaus93** [ElektraInitiative/libelektra#3014]
It seems that in the `codegen/tree` and `codegen/econf` example READMEs, the kdb mount commands for the `cmake` and `pkgconfig` setup are executed from the build directory, while they are expected to be executed from the directory of the `README.md` (since `specload "app=$PWD/cmake/build/application"` in case of the cmake setup). 

`tree/README.md`, cmake setup, comments added:
```sh
mkdir "$PWD/cmake/build" && cd "$PWD/cmake/build"

cmake ..
cmake --build .

# Directory isn't changed, since $PWD contains current directory
cd "$PWD"

# kdb mount executed from the build directory,
sudo kdb mount -R noresolver codegen_tree_example.conf "spec/sw/example/tree/#0/current" specload "app=$PWD/cmake/build/application"
sudo kdb spec-mount "/sw/example/econf/#0/current"
```
After `kdb mount`, there is the error message:
```
The command kdb mount terminated unsuccessfully with the info:
Was not able to load such a plugin!

Maybe you misspelled it, there is no such plugin or the loader has problems.
You might want to try to set LD_LIBRARY_PATH, use kdb-full or kdb-static.
Errors/Warnings during loading were:
Sorry, module specload issued the error C01100:
Resource: App '<FULL_PATH>/libelektra/examples/codegen/tree/cmake/build/cmake/build/application' doesn't exist or is not executable
```
The same problem appears in `econf/README.md`.

The third tutorial, `menu/README.md` works, expecting `$PWD` to be the build directory, where `application` is located:
```sh
sudo kdb mount -R noresolver codegen_menu_example.conf "spec/sw/example/menu/#0/current" specload "app=$PWD/application"
```

**Comment by markus2330** [comment]
Thank you so much for reporting it!

@kodebach is this an easy fix?
