### ISSUE TITLE
rust: links against legacy library

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3015]
libelektra.so only exists for legacy purposes, the library was actually split up, see doc/decisions/library_split.md

In #3004 I now try to remove this legacy library but (among other problems) the Rust binding still seems to use -lelektra
https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-3004/4/pipeline

I do not see where the linking against elektra in the Rust binding is specified, can you help? (Ideally fix it by pushing commit(s) to #3004).

**Comment by PhilippGackstatter** [comment]
I didn't know about the decision, sorry.

I'm linking against `core`, `meta` and `kdb` now. That should fix it.

**Comment by markus2330** [comment]
Thank you, perfect!
