### ISSUE TITLE
naming conventions for KDB

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#302]
Thus Elektra is more and more used, we should start thinking about how the keynames of applications should look like. Basic convetions already [exist here](https://github.com/ElektraInitiative/libelektra/blob/master/doc/tutorials/application-integration.md), but many questions are still unanswered.

The most urgent question is about the capitalization, because it affects basically every key.
E.g. for "my app" from "fancy.org" with the key "full name"
Typical proposals are:

1. /sw/org/fancy/myapp/#0/current/name/full ... use / everywhere, reverse splitted words
2. /sw/fancy.org/my.app/#0/current/full.name ... use dots
3. /sw/fancy-org/my-app/#0/current/full-name ... use dash
4. /sw/fancy_org/my_app/#0/current/full_name ... use underscore
5. /sw/fancyOrg/myApp/#0/current/fullName ... camelCase

Obviously, mixed solutions are possible too. E.g. dot for domain names, but underscore for key names. At least, following dimensions exist (each of them could have different naming conventions)

1. top level names like `sw` (software)
2. domain names to have no conflicts for applications with same names
3. application names
4. profile names (`current`, `default`,..)
5. key names

Like for arrays, these are only conventions and nothing can stop someone from not be consistent.

**Comment by omnidan** [comment]
A variation of 1 without the `/org` part would be nice:

/sw/fancy/myapp/#0/current/name/full

**Comment by KurtMi** [comment]
In my opinion the variation of @omnidan is fine

**Comment by fberlakovich** [comment]
I vote for 1

**Comment by markus2330** [comment]
We also need a convenience layer for `kdb-tool`
either `kdb chdir` or alias ~myapp = /sw/fancy/myapp/#0/current/

**Comment by markus2330** [comment]
decided for daniel proposal

**Comment by markus2330** [comment]
~ creates some problems for the "bookmark"-feature as discussed (it is used heavily for different features in shells). So I gave + a try.

The new feature works like:
```
kdb set user/sw/elektra/kdb/#0/current/namedkeys
kdb set user/sw/elektra/kdb/#0/current/namedkeys/kdb user/sw/elektra/kdb/#0/current
kdb get +kdb/format      # will actually get user/sw/elektra/kdb/#0/current/format
```

What do you think?

**Comment by markus2330** [comment]
I reopen this issue: there is still bunch of documentation that refers back to old pathes in kdb and qtgui

**Comment by markus2330** [comment]
I think also the documentation should be updated now.

**Comment by sirblackheart** [comment]
As already mentioned at the Meeting 09.06.2016, we have a clash here with `GSettings` key names.
`GSettings` Key names are `toplevel.domain.appname` e.g. `/org/gnome/gedit` `/org/libelektra/elektra-qt-editor`
Hereby i suggest to accept those also as valid keyname.
The reason for this is that this structure is already widely used in free-desktop standards. e.g. dbus, desktop files, appdata etc.

Accepting those would seamlessly integrate the existing GSettings key name scheme with Elektra without loss of information.

For discussion regarding #version and profile support in GSettings keyname see #775

**Comment by markus2330** [comment]
We should the hierarchy into some subdirectory, otherwise it might clash with apps directly using Elektra.

Is `/sw/gnome/gsettings/#0/current` as root viable? Does your binding already has a name, maybe we can use it?

Note that users can set bookmarks to not be concerned about such a long name, e.g. `+gs/org/gnome/editor`.

If you dislike this long name, please propose a shorter name as root for keys of your bindings. (It should not be `sw`, because we already reserved it for our naming conventions)

**Comment by markus2330** [comment]
A rationale to why always using `/`: It is more flexible when keys are later added.

For example, if you have an option listener-threads or "fancy colour" you would write:
`listener/threads` or `fancy/colour`. If one day you decide to also introduce `listener/process` and `fancy/font`, you already have a suitable hierarchy.
