### ISSUE TITLE
make elektraPluginOpen/Close public

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3028]
@kodebach said in #3004:
>   It was present, but not public API. It's also still declared in kdbprivate.h, so shouldn't be public API.

De-facto it is already public API because since quite some time as all tools use it. In particular src/libs/tools/src/plugin.cpp.

The big question is if it should

1. stay in KDB, or
2. moved to core (would drop the libkdb dep for invoke).

For header file imho src/include/kdbmodule.h is best (which functions are currently in core afaik).

**Comment by kodebach** [comment]
IMO the plugin related stuff should not be in `elektra-core`. The plugin system doesn't make much sense without the other parts of `elektra-kdb`.

**Comment by markus2330** [comment]
I agree but then we should also move out the modules stuff from core. The downside is that `kdb` has two deps then.
