### ISSUE TITLE
Tutorial for standalone merge

### ISSUE THREAD

**Issue by dominicjaeger** [ElektraInitiative/libelektra#3030]
As discussed, better to leave this away. But a tutorial for the standalone merging tool would be interesting.

_Originally posted by @markus2330 in https://github.com/ElektraInitiative/libelektra/pull/3011_

**Comment by markus2330** [comment]
Thank you for making this issue!

**Comment by Chemin1** [comment]
What do we mean exactly with standalone? Calling "kdb (c)merge" or also with the little helper script that operates on files?

**Comment by markus2330** [comment]
I mean a script that works more or less than the current helper script. I already described this standalone script in the last comment of #2869:

> I was thinking of something like `elektra-install-config-files <config file> <elektra path>` which:
> 
> 1. if no such Elektra path exists, installs (copy+mount) the config file twice: once in the path, once in some origin path (so that you have origin)
> 2. if the path already contains data, you do a 3-way merge with the given config file and the orig path (you can derive).
> 
> @kodebach: How will your script for installing the specifications be named? It would be good if these scripts are consistent.

**Comment by Chemin1** [comment]
> I already described this standalone script in the last comment of #2869:

Ahh, I didn't get that the tutorial should be for this script! I'll implement the script asap :)

**Comment by markus2330** [comment]
Actually, the tutorial(s) should cover merging in general (your work) but I think the script will be the most easy way to describe it.

**Comment by Chemin1** [comment]
Draft in #3216
