### ISSUE TITLE
Vanity import for go

### ISSUE THREAD

**Issue by raphi011** [ElektraInitiative/libelektra#3037]
At the moment we have a vanity import for go.libelektra.org (which is not used yet) - but we may want to change this to `libelektra.org/go/elektra`. This looks more like a go import and allows us add different packages in the future without creating a new subdomain, e.g. `libelektra.org/go/foo`.

**Comment by markus2330** [comment]
Which different packages are you thinking of?

There is basically only plugin and tools API to do, should that be in separate packages?

And even if so, why not making new domains and or having go.libelektra.org/package?

And I thought you already have two packages? (low-level and high-level API)

**Comment by raphi011** [comment]
I've experimented with the highlevel api but it's not implemented.

But you're probably right - the subdomain should suffice

**Comment by raphi011** [comment]
I can't find the vanity `index.html` in the /doc repository anymore, have you removed it @markus2330 ? I need to update it with [this file](https://gist.github.com/raphi011/995358e145cb779a5ff198ae68923386)in order to make the documentation work again.

**Comment by markus2330** [comment]
> I can't find the vanity index.html in the /doc repository anymore, have you removed it @markus2330?

Not on purpose. Maybe it was removed because of some change in the build server.

> I need to update it with this file in order to make the documentation work again.

curl https://go.libelektra.org should now return the correct content. (Note to myself: the file lies in /srv/go)

**Comment by markus2330** [comment]
Is the vanity import working now? Can we close this?

**Comment by raphi011** [comment]
yes
