### ISSUE TITLE
Rust test case fails on master

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3045]
https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/18/pipeline reports:

```
test kdb::test::can_use_kdb ... FAILED


failures:


---- kdb::test::can_use_kdb stdout ----

thread 'kdb::test::can_use_kdb' panicked at 'internal error: entered unreachable code', elektra/src/kdb.rs:318:17

note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.



failures:

    kdb::test::can_use_kdb


test result: FAILED. 32 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out


error: test failed, to rerun pass '-p elektra --lib'

```

**Comment by PhilippGackstatter** [comment]
Some error code was given that wasn't known to the mapper. The mapping for Installation ("C01200") errors was missing and I added that in #3047.

But that doesn't really explain why there occurred an error in the first place. The test case isn't raising an error. And the latest PR #3038 you merged didn't even touch the rust bindings.
I'll try to figure it out in the PR above.

**Comment by markus2330** [comment]
Thank you for looking at it so quickly.

**Comment by sanssecours** [comment]
Seems the test [failed again](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/58/pipeline).

**Comment by PhilippGackstatter** [comment]
It's a different error this time unrelated to the error mapping.
A `Permanent(Logical(Internal(...)))` error occurred, but it wasn't printed out. So that's all the information that I have. I'll added a small fix to master for printing that as well, that's all I can do unfortunately. Next time we can see the error if the same one happens again.

**Comment by markus2330** [comment]
Thank you! It is always good to have enough output in test cases.

**Comment by sanssecours** [comment]
Looks like [`test_rust_elektra` failed](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-3126/2/pipeline) in PR #3126.

```
156/260 Test  #34: test_rust_elektra .............................***Failed   53.30 sec
   Compiling cc v1.0.40
   Compiling libc v0.2.62
   Compiling memchr v2.2.1
   Compiling version_check v0.1.5
   Compiling bitflags v1.1.0
   Compiling lazy_static v1.3.0
   Compiling byteorder v1.3.2
   Compiling proc-macro2 v0.4.30
   Compiling log v0.4.8
   Compiling glob v0.3.0
   Compiling rustc-demangle v0.1.16
   Compiling cfg-if v0.1.9
   Compiling regex-syntax v0.6.11
   Compiling quick-error v1.2.2
   Compiling unicode-width v0.1.6
   Compiling unicode-xid v0.1.0
   Compiling strsim v0.8.0
   Compiling termcolor v1.0.5
   Compiling ansi_term v0.11.0
   Compiling bindgen v0.50.0
   Compiling vec_map v0.8.1
   Compiling peeking_take_while v0.1.2
   Compiling shlex v0.1.1
   Compiling thread_local v0.3.6
   Compiling nom v4.2.3
   Compiling backtrace-sys v0.1.31
   Compiling libloading v0.5.2
   Compiling humantime v1.2.0
   Compiling textwrap v0.11.0
   Compiling clang-sys v0.28.1
   Compiling fxhash v0.2.1
   Compiling atty v0.2.13
   Compiling aho-corasick v0.7.6
   Compiling quote v0.6.13
   Compiling clap v2.33.0
   Compiling backtrace v0.3.35
   Compiling failure v0.1.5
   Compiling cexpr v0.3.5
   Compiling regex v1.2.1
   Compiling which v2.0.1
   Compiling env_logger v0.6.2
   Compiling elektra-sys v0.9.0 (/home/jenkins/workspace/libelektra_PR-3126-IPADARSP3KMTTQ7U2PEWIJVQABRCHP2XCZ3DTXEC6ASQGMF6PDAQ/build directory/src/bindings/rust/elektra-sys)
   Compiling elektra v0.9.0 (/home/jenkins/workspace/libelektra_PR-3126-IPADARSP3KMTTQ7U2PEWIJVQABRCHP2XCZ3DTXEC6ASQGMF6PDAQ/build directory/src/bindings/rust/elektra)
    Finished dev [unoptimized + debuginfo] target(s) in 48.16s
     Running target/debug/deps/elektra-4964972aba2a8495

running 33 tests
test key::tests::can_duplicate_key ... ok
test key::tests::can_cast_key_types ... ok
test key::tests::can_delete_metadata ... ok
test key::tests::can_get_fullname ... ok
test key::tests::can_iterate_key ... ok
test key::tests::can_iterate_name ... ok
test key::tests::can_reference_count ... ok
test key::tests::can_set_get_metavalue ... ok
test key::tests::can_write_read_key_value ... ok
test key::tests::can_write_read_key ... ok
test key::tests::can_write_read_binary ... ok
test key::tests::equality_is_symmetric ... ok
test key::tests::equality_is_transitive ... ok
test key::tests::keys_are_ordered ... ok
test key::tests::keys_are_ordered_with_metadata ... ok
test keybuilder::test::can_build_binary_key ... ok
test keybuilder::test::can_build_key_with_meta ... ok
test keybuilder::test::can_build_string_key ... ok
test keyset::tests::can_build_simple_keyset ... ok
test keyset::tests::can_duplicate_keyset ... ok
test keyset::tests::can_iterate_simple_keyset ... ok
test keyset::tests::can_lookup_by_name_and_duplicate_key ... ok
test keyset::tests::can_lookup_key_with_nocase_and_pop_option ... ok
test keyset::tests::can_lookup_key_with_none_option ... ok
test keyset::tests::can_lookup_key_with_pop_option ... ok
test keyset::tests::can_use_popped_key_after_keyset_freed ... ok
test keyset::tests::extend_keyset_and_append_are_equal ... ok
test keyset::tests::pop_on_empty_keyset_returns_none ... ok
test key::tests::equality_is_reflexive ... ok
test key::tests::can_write_read_empty_binary ... ok
test key::tests::equality_is_exclusive ... ok
test key::tests::error_on_missing_metaname ... ok
test kdb::test::can_use_kdb ... FAILED

failures:

---- kdb::test::can_use_kdb stdout ----
thread 'kdb::test::can_use_kdb' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: <core::option::Option<T>>::unwrap
             at /usr/src/rustc-1.34.2/src/libcore/macros.rs:11
  10: elektra::kdb::test::remove_test_keys
             at elektra/src/kdb.rs:394
  11: elektra::kdb::test::can_use_kdb
             at elektra/src/kdb.rs:386
  12: elektra::kdb::test::can_use_kdb::{{closure}}
             at elektra/src/kdb.rs:360
  13: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.34.2/src/libcore/ops/function.rs:231
  14: <F as alloc::boxed::FnBox<A>>::call_box
  15: __rust_maybe_catch_panic


failures:
    kdb::test::can_use_kdb

test result: FAILED. 32 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p elektra --lib'
```

**Comment by PhilippGackstatter** [comment]
Thanks for reporting.

This is again a different error than last time. 
A lookup in the keyset retrieved via kdbGet failed. It's particularly strange since the same code (except `KDB_O_NONE` instead of `KDB_O_POP`) succeeded a few lines earlier.
`kdbGet` must've not modified the given KeySet such that the key was present afterwards. And again, the same code ran a couple of lines earlier and succeeded.

Judging by the irregular nature that this occurs at and what I've just described, it seems like a problem external to the rust code. It's of course still interesting that it always occurs in rust code.

Was there ever any problem with kdb functions failing sometimes before? Could `kdbGet` fail or produce incomplete results on a laggy filesystem #2984?
And is it possible to enable debug logging for elektra for this test, so I can see what's going on in `kdbGet`?

**Comment by markus2330** [comment]
> succeeded a few lines earlier.

Can you point me to the lines?

> Was there ever any problem with kdb functions failing sometimes before?

Conflicts might happen with `kdb set` on an NFS filesystem. On the build server only tests with very frequent conflicts failed (see the DISABLED_ tests in tests/kdb/testkdb_conflict.cpp or the racer tests #137).

> Could kdbGet fail or produce incomplete results on a laggy filesystem #2984?

No, only kdbSet might produce unwanted conflicts (when time jumps happen or similar).

That kdbGet failed did not happen as far as I know.

Maybe you have some memory problem in the Rust binding? Did you try to run valgrind or similar?

> And is it possible to enable debug logging for elektra for this test, so I can see what's going on in kdbGet?

In a PR you could do this but I would not waste too much time on that. If it happens so infrequently, it is much too indirectly to find the bug with this method.

**Comment by PhilippGackstatter** [comment]
> Can you point me to the lines?

https://github.com/ElektraInitiative/libelektra/blob/d8978c39f5ab82c69db34b07f576d6006fc21831/src/bindings/rust/elektra/src/kdb.rs#L374-L378

That succeeded, but then in `remove_test_keys` it failed. (`Default::default()` is `KDB_O_NONE`)



> Maybe you have some memory problem in the Rust binding? Did you try to run valgrind or similar?

I've run it occasionally during development and just tried it again, with interesting results. Valgrind showed memory leaks, but even for a simple Rust program with `kdbOpen` followed by `kdbClose`.

I tried it in C, compiled the example from the [kdb doc page](https://doc.libelektra.org/api/current/html/group__kdb.html) and valgrind also showed a memory leak. Not sure if I'm testing correctly, since the build servers also run various ASAN checks.

```c
// leak.c, example from kdb docs
KeySet * myConfig = ksNew (0, KS_END);
Key * parentKey = keyNew ("/sw/MyApp", KEY_CASCADING_NAME, KEY_END);
KDB * handle = kdbOpen (parentKey);
kdbGet (handle, myConfig, parentKey); // kdbGet() must be first
// now any number of any kdbGet()/kdbSet() calls are allowed, e.g.:
kdbSet (handle, myConfig, parentKey);
ksDel (myConfig); // delete the in-memory configuration
kdbClose (handle, parentKey); // no more affairs with the key database.
keyDel (parentKey);        // working with key/ks does not need kdb
```

I built the current master. Then from the build directory
```sh
$ clang -Isrc/include/ -I../src/include/ -Llib/ leak.c -lelektra-core -lelektra-kdb
$ valgrind --leak-check=full ./a.out
==16818== Memcheck, a memory error detector
==16818== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==16818== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==16818== Command: ./a.out
==16818== 
==16818== 
==16818== HEAP SUMMARY:
==16818==     in use at exit: 84,757 bytes in 22 blocks
==16818==   total heap usage: 5,665 allocs, 5,643 frees, 494,812 bytes allocated
==16818== 
==16818== LEAK SUMMARY:
==16818==    definitely lost: 0 bytes in 0 blocks
==16818==    indirectly lost: 0 bytes in 0 blocks
==16818==      possibly lost: 0 bytes in 0 blocks
==16818==    still reachable: 84,757 bytes in 22 blocks
==16818==         suppressed: 0 bytes in 0 blocks
==16818== Reachable blocks (those to which a pointer was found) are not shown.
==16818== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==16818== 
==16818== For lists of detected and suppressed errors, rerun with: -s
==16818== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

Am I not testing correctly?

**Comment by mpranj** [comment]
If you are talking about the `still reachable` portion, it's not a big issue. It means that a pointer to the memory still exists and it could be cleaned up ([see docs](http://valgrind.org/docs/manual/mc-manual.html)).

The severity in the output is basically sorted from most severe to not so relevant: definitely lost > indirectly lost > possibly lost > still reachable > suppressed. If there are not definitely, indirectly or possibly lost bytes, you're probably fine. You can try running valgrind on any command like `ls`, it will also have still reachable bytes.

**Comment by PhilippGackstatter** [comment]
I see, thank you for the explanation!

**Comment by PhilippGackstatter** [comment]
Just to document this, I updated the tests in #3165, but the build failed. 
The test succeeds on my machine locally, but did not in [building pr 3165](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-3165/4/pipeline).

```
test kdb::test::test_kdb ... FAILED

failures:

---- kdb::test::test_kdb stdout ----
thread 'kdb::test::test_kdb' panicked at 'assertion failed: `(left == right)`
  left: `false`,
 right: `true`', elektra/src/kdb.rs:496:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: std::panicking::begin_panic_fmt
   7: elektra::kdb::test::set_kdb
             at elektra/src/kdb.rs:496
   8: elektra::kdb::test::test_kdb
             at elektra/src/kdb.rs:480
   9: elektra::kdb::test::test_kdb::{{closure}}
             at elektra/src/kdb.rs:479
  10: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.34.2/src/libcore/ops/function.rs:231
  11: <F as alloc::boxed::FnBox<A>>::call_box
  12: __rust_maybe_catch_panic
```

The responsible lines are

https://github.com/ElektraInitiative/libelektra/blob/37c5027758cef3d8bb8295a7bbc268459ad7bba8/src/bindings/rust/elektra/src/kdb.rs#L485-L496

`kdb.get(...)` should return true if the keys were retrieved successfully, but false was returned, meaning "there was no update - no changes are made to the keyset then". I don't understand why it returns false instead of true.

**Comment by mpranj** [comment]
> kdb.get(...) should return true if the keys were retrieved successfully, but false was returned, meaning "there was no update - no changes are made to the keyset then". I don't understand why it returns false instead of true.

Maybe there is no key in the backend of the used parentKey, then it also returns 0 as there is no change to the keyset.

**Comment by PhilippGackstatter** [comment]
Yes, you're totally right. I made a wrong assumption about that call. Since it's the first one and the kdb is empty, false may be returned. Thanks!

**Comment by markus2330** [comment]
Good that you found out.

What about closing this issue and opening another one if a Rust test case fails again?

**Comment by PhilippGackstatter** [comment]
> What about closing this issue and opening another one if a Rust test case fails again?

This was an error I introduced in this PR and I thought it was related to this issue. But it's actually unrelated, so unfortunately this issue is not fixed.

**Comment by markus2330** [comment]
Did not occur again.
