### ISSUE TITLE
Rust: OutOfMemory is not a subtype of a general resource error

### ISSUE THREAD

**Issue by PhilippGackstatter** [ElektraInitiative/libelektra#3059]
The error specification is defined as

- Permanent errors C01000
    - Resource C01100
        - Memory Allocation C01110

In Rust, due to lack of inheritance, the errors are implemented as nesting enums to allow for i.e. catching all types of permanent errors, as it would be with catching a PermanentErrorException in Java.

This works great as long as only the leafs of this tree are concrete errors. However, resource errors are the exception to this case, since they can also be a concrete error.

This is currently implemented like this

```rust
pub enum ResourceError {
    GeneralResourceError(KDBErrorWrapper),
    OutOfMemory(KDBErrorWrapper),
}
```

`OutOfMemory` errors have their own enum variant, but any other Resource error is wrapped in `GeneralResourceError`, which means that they are distinct variants and `OutOfMemory` is not a subtype of `GeneralResourceError` as it should be according to the spec.

I don't think this is a big problem, since you can still catch all types of resource errors with
 
```rust
if let KDBError::Permanent(PermanentError::Resource(err)) = kdb_open_result {
    // Now match which exact resource error we got
    match err {
        ResourceError::GeneralResourceError(resource_err) => { /* handle */ },
        ResourceError::OutOfMemory(oom_err) => { /* handle */ }
    }
}
 ```

@markus2330 wrote in #3047 

> OutOfMemoryError should be a subtype of the ResourceError.

From the user perspective it seems to work. Why do you think this is an issue?

**Comment by markus2330** [comment]
>  From the user perspective it seems to work. Why do you think this is an issue?

Because a user might expect that catching a ResourceError will also catch OutOfMemory.

@Piankero is this the only place where this can occur? Where is this documented?

**Comment by Piankero** [comment]
There was a long discussion about if we allow leaf-only categories and it was agreed on that it would partly just result in unnecessary splitting (e.g., exactly for the OOMException). The Resource Errors are the only category which can have errors themselves and has a subtype as of now.

> Where is this documented?

It was documented in the design decision but after restructuring it was lost/forgotten. I will add this information to the error-categorization.md file which developers should read beforehand anyway. An implicit documentation is the specification file. All errors which occur there are actually assignable.

**Comment by PhilippGackstatter** [comment]
> Because a user might expect that catching a ResourceError will also catch OutOfMemory.

Pattern matching
`if let KDBError::Permanent(PermanentError::Resource(err)) = kdb_open_result`
does exactly that. It catches both `GeneralResourceError` and `OutOfMemory`.

The other solution is to ditch the current enum implementation completely and create a wrapper around the error key. The wrapper would just match the strings.
Here is a short example [on the rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8e6fb35c6c65f346257e45ef35be2c2b).

This would actually be much simpler to implement than the current solution. From the user perspective this is is fairly similar with the now added bonus of also having OOM as subtype of Resource Error.

**Comment by markus2330** [comment]
> There was a long discussion about if we allow leaf-only categories and it was agreed on that it would partly just result in unnecessary splitting (e.g., exactly for the OOMException). The Resource Errors are the only category which can have errors themselves and has a subtype as of now.

Yes, the main point point of the discussion was to have the possibility to introduce subcategories. For example for installation errors it might be interesting to distinguish installation errors of Elektra and other software.

But code written now to catch installation errors should also catch this potential new C01210 group of ElektraInstallationErrors. @PhilippGackstatter is this guaranteed with the current Rust implementation?

> It was documented in the design decision but after restructuring it was lost/forgotten. I will add this information to the error-categorization.md file

Thank you. Please also make sure that nothing else got lost in the restructuring.

> which developers should read beforehand anyway.

I agree. Maybe you can give some input to @d3nwp (or even meet him?) about how the docu should be restructured that newcomers can enter the project more easily.

> It catches both GeneralResourceError and OutOfMemory.

Good. Will it also work with potential extensions?

> The wrapper would just match the strings.

If this is more future proof it would be good to have it. (See questions above.)

**Comment by PhilippGackstatter** [comment]
> But code written now to catch installation errors should also catch this potential new C01210 group of ElektraInstallationErrors. @PhilippGackstatter is this guaranteed with the current Rust implementation?

> Will it also work with potential extensions?

The (current) bindings need to be extended manually, as each error code is mapped to one Rust error type. If one is added to elektra, but not the bindings or they are not updated, that would panic.

In that regard, the alternative solution I proposed would still be able to catch all types of installation errors, even if a new subcategory was added. The new subcategory would of course still need to be added by hand. 

> If this is more future proof it would be good to have it.

It seems to me like this is the more future proof solution, so I can try to implement it and see if it actually works out.

**Comment by Piankero** [comment]
> I agree. Maybe you can give some input to @d3nwp (or even meet him?) about how the docu should be restructured that newcomers can enter the project more easily.

Is this meant for me or @PhilippGackstatter ?

> The (current) bindings need to be extended manually, as each error code is mapped to one Rust error type. If one is added to elektra, but not the bindings or they are not updated, that would panic.

It is acceptable that one needs to manually add the error type to Rust if Elektra gets a new error type. Error types are very stable and should not change very often. We agreed on this in a design decision (will be merged soon from #2872).

> It seems to me like this is the more future proof solution, so I can try to implement it and see if it actually works out.

The main advantage I see here is that if you forget to add it in Rust, it will not break any existing Rust code, right?

**Comment by PhilippGackstatter** [comment]
> The main advantage I see here is that if you forget to add it in Rust, it will not break any existing Rust code, right?

There's two cases. From the binding user's perspective, 
1) Elektra adds a new error type and Rust binding is updated
2) Elektra adds a new error type, but the Rust binding is not updated

| Implementation        | binding up-to-date           | binding *not* up-to-date  |
|:-------------:|:-------------:|:-----:|
| Current     | compile error if the enum is exhaustively matched, otherwise fine | panics (exits the program) |
| Proposed  | user can match new error, doesn't have to   |  the next higher category is still matched |

It's mostly about what happens if the elektra version and the binding version do not match, if that really happens.

Having the compile time error for enums is helpful if you want to match every error explicitly. But those that don't care, can use a match-all handler, and wouldn't get a compile error.

The proposed solution also works if the binding version 0.9.0 was used with, say, elektra version 0.9.2 where that version introduced a new error. So it would actually be forward compatible.

**Comment by markus2330** [comment]
>   Is this meant for me or @PhilippGackstatter ?

To @Piankero 

>  It is acceptable that one needs to manually add the error type to Rust if Elektra gets a new error type. Error types are very stable and should change infrequently. We agreed on this in a design decision (will be merged soon from #2872).

Yes, it is acceptable to adapt all the bindings. But it is not acceptable that every user of Elektra (or its bindings) need to adapt the code. If this is not clear from the decision it should be corrected.

> It's mostly about what happens if the elektra version and the binding version do not match, if that really happens.

Hopefully the binding and Elektra will be in sync (if not panic is ok). But what can easily happen is that the application was compiled against an older version of Elektra and Elektra (together with the binding) was updated. Is this something that can happen in the Rust world?

**Comment by Piankero** [comment]
> Maybe you can give some input to @d3nwp (or even meet him?) about how the docu should be restructured that newcomers can enter the project more easily.

Alright, I can help @d3nwp to restructure the docu. Can @d3nwp tell me which docu exactly is meant?

**Comment by PhilippGackstatter** [comment]
> But what can easily happen is that the application was compiled against an older version of Elektra and Elektra (together with the binding) was updated. Is this something that can happen in the Rust world?

That can only happen if the rust bindings were compiled as a shared library and updated independently from the application, unless I'm missing something. If the new binding + elektra version returns a new error code, then the current implementation panics when it tries to map the error code.

I have thought more about the proposal and instead of supplying the error code to check for, we could provide a number of methods to check. So i.e. users would call `kdb_error.is_validation()` to check if the error is a validation error.

```rust
let mut kdb = KDB::open();
if let Err(kdb_error) = kdb {
    if kdb_error.is_validation() {
        // Catches both syntactic and semantic
        // Handle somehow
    } else {
        // Propagate other errors up
        return Err(kdb_error);
    }
}
```

In the above scenario, but with the proposed solution, here the unknown error would be propagated up and _probably_ lead to a graceful application failure by printing the error message. So this solution would handle this specific scenario better. In general, the proposed solution would not panic.

But I think that the bindings would mostly be compiled into the application, (certainly when using it through crates.io) but would use elektra as a shared library. Then the binding version and elektra version mismatch is the more likely scenario. But here the proposed solution would also work better, similiar to the given example.

**Comment by markus2330** [comment]
Yes, these `is_?` also sound good to me. I do not know about best-practices of error handling Rust, though.

**Comment by Piankero** [comment]
Since I added the documentation I can unassign myself

**Comment by markus2330** [comment]
@PhilippGackstatter will you implement the proposed implementation or can we close this? I do no think it has high priority but as we already more or less know what can be done it might be not so much effort anymore?
