### ISSUE TITLE
Order output of kdb list command

### ISSUE THREAD

**Issue by MasterToney** [ElektraInitiative/libelektra#3060]
Currently the output of kdb list is the same as how the commands in the [Factory](https://github.com/ElektraInitiative/libelektra/blob/dc24c7fc23a247127b29ff7023c933b336123e17/src/tools/kdb/factory.hpp#L86) are registered.
Since there are currently more than 80 commands registered I would suggest to sort them in alphabetical order to make it easier to find available or missing commands.

There are two paces where such an ordering could take place:
1. in the get methods of the [Factory](https://github.com/ElektraInitiative/libelektra/blob/dc24c7fc23a247127b29ff7023c933b336123e17/src/tools/kdb/factory.hpp#L130-L161)
2. in the [kdb list](https://github.com/ElektraInitiative/libelektra/blob/83d1a1962bdafff8d0dd79f6c8de99e66e1fe7c1/src/tools/kdb/listcommands.cpp#L23-L65) command directly

Option 1 would have the advantage that all tools which use the factory as source would have the same order.

I would take care of the implementation next week if this change is desired and rated as useful.

Ps: Same goes for the Plugins README since it is used to construct the navigation sidebar on the website if I'm not mistaken?

**Comment by markus2330** [comment]
Thank you for making this proposal! I think it is very useful to not output in a random order.

Yes, the get methods are the perfect place for this, `sort(ret.begin(), ret.end())` should do what you need.

**Comment by MasterToney** [comment]
Implemented by #3070 and therefore closed.
