### ISSUE TITLE
build server reports formatting error in binary quickdump file

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3061]
In #3011 @Chemin1 run into a strange problem: The [build server reports](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-3011/21/pipeline/):

```
diff --git a/src/plugins/specload/specload/remove.quickdump b/src/plugins/specload/specload/remove.quickdump

index ccedf5000..e69de29bb 100644

Binary files a/src/plugins/specload/specload/remove.quickdump and b/src/plugins/specload/specload/remove.quickdump differ
```

@kodebach @sanssecours any idea what went wrong here?

**Comment by Chemin1** [comment]
[full log here](https://github.com/ElektraInitiative/libelektra/files/3721545/dockerFormat.txt)

I saw this only a single time, but maybe some else has had the same problem or will run into it in the future.

**Comment by sanssecours** [comment]
> @sanssecours any idea what went wrong here?

I have no idea. These transient error are usually also quite hard to reproduce.

**Comment by markus2330** [comment]
Thank you for adding the log.

> but maybe some else has had the same problem or will run into it in the future.

exactly.

**Comment by markus2330** [comment]
Did not occur again.

**Comment by mpranj** [comment]
[Happened again](https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/master/263/pipeline/684), but it's not worth investigating if it goes away for 6 months again. 😄
