### ISSUE TITLE
Priority of FreeBSD

### ISSUE THREAD

**Issue by Chemin1** [ElektraInitiative/libelektra#3067]
How much of a priority is FreeBSD for us at the moment?

I just installed Elektra for the first time on FreeBSD 11.3. Compiling went relatively straightforward but the memory tests take forever at `Start 18: testlib_pluginprocess`. Should we put time into getting this to work or (especially if there is an easy solution that I currently don't see) documenting this?

**Comment by sanssecours** [comment]
> How much of a priority is FreeBSD for us at the moment?

I do not think adding FreeBSD support for Jenkins has a high priority, as we already build Elektra on FreeBSD `11` and FreeBSD `12`:

https://github.com/ElektraInitiative/libelektra/blob/62897f3708d886396c262e2965b611ba1f3fe3b3/.cirrus.yml#L4-L10

.

**Comment by Chemin1** [comment]
I didn't think of Jenkins actually but rather something like extending the [getting started with compiling](https://www.libelektra.org/docgettingstarted/compiling) with more hints for BSD.

Because this
>  memory tests take forever at

was really meant as forever. It didn't fail or succeed after quite some time. Or which steps have to be taken to install LibGit2. I just installed the package on BSD but couldn't use it yet with Elektra.

**Comment by sanssecours** [comment]
> It didn't fail or succeed after quite some time. 

This is also the case on macOS. I can remember that executing all tests with Valgrind took over 10 hours on my computer. I would recommend you use [AddressSanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer) (`ENABLE_ASAN=ON`), if you want to debug memory related problems.

>  I just installed the package on BSD but couldn't use it yet with Elektra.

Does [`FindLibGit2.cmake`](https://github.com/ElektraInitiative/libelektra/blob/master/scripts/cmake/Modules/FindLibGit2.cmake) not detect the library? Maybe you need to regenerate the build system with `cmake` again?

**Comment by Chemin1** [comment]
> This is also the case on macOS. I can remember that executing all tests with Valgrind took over 10 hours on my computer

Ok, I didn't expect it to take that long. In this case I'll leave it running while sleeping.

> Does FindLibGit2.cmake not detect the library? Maybe you need to regenerate the build system with cmake again?

I'll try to find this out.

**Comment by markus2330** [comment]
Being portable is important for Elektra, so FreeBSD is important, too. Furthermore @llukask uses FreeBSD.

But to have tests running fast is not important. It is also very limited what we can do about it. (E.g. valgrind is only optimized on Linux.)

> I didn't think of Jenkins actually but rather something like extending the getting started with compiling with more hints for BSD.

This is definitely a good idea! Maybe you can also coordinate with @d3nwp who is currently working on getting started (#3002)

**Comment by Chemin1** [comment]
> Does [`FindLibGit2.cmake`](https://github.com/ElektraInitiative/libelektra/blob/master/scripts/cmake/Modules/FindLibGit2.cmake) not detect the library?

I have quite a chaos at the moment, but at some point I got the log message that libgit2 was found on FreeBSD :)

**Comment by markus2330** [comment]
I think question is answered. If there are any concrete troubles with FreeBSD, please reopen new issues.
