### ISSUE TITLE
Jenkins password protected

### ISSUE THREAD

**Issue by Chemin1** [ElektraInitiative/libelektra#3068]
I assume this is due to the migration. Currently looking why any Jenkins check is unsuccessful is impossible as the "Details" link in a PR redirects to a login portal.

For example #3011 has had all checks successfull two hours ago and not anymore now. Is this planned?

@Mistreated Do you know what's going on?

**Comment by Mistreated** [comment]
Yeah, it is due to the migration. It "should" be working now.

**Comment by Chemin1** [comment]
After restarting the browser and Ctrl+F5 refreshing there is still the login portal.

**Comment by Mistreated** [comment]
It wants to login on the new server. I wanted to force new server today. Hopefully this will be resolved tomorow.

**Comment by markus2330** [comment]
@Mistreated please resolve as fast as possible. Having a working infrastructure has the highest priority.

**Comment by Chemin1** [comment]
New PRs don't have the login prompt anymore. Also, after `jenkins restart libelektra please` the old PR's Jenkins is available again.

**Comment by markus2330** [comment]
@Chemin1 does now again everything works as expected?

**Comment by Chemin1** [comment]
> @Chemin1 does now again everything works as expected?

Yes
