### ISSUE TITLE
Inheritance and Errno in warnings/error

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#307]
It should be possible to check if validation (or something else) failed.

Additionally, it would be good to capture the errno automatically at the place where ELEKTRA_SET_ERROR was used.

**Comment by fberlakovich** [comment]
Sounds good. My experiments to simplify this with macros didn't really work out.

**Comment by markus2330** [comment]
To give more details:
1.) We actually only have to care about that every error gets a correct `class` attribute. Then one can check if the error is of a error-class and does not have to check for a concrete number.
2.) Then we can (dynamically) add `errno` which contains the current errno. When printing the error message, one should use strerror to print the text.

**Comment by markus2330** [comment]
This seems to complicate the error system without too much benefits:

- the errno can easily appended with macros that take a format string
- the inheritance can be avoided by using the same error for the same errors (which is also done currently)
