### ISSUE TITLE
improve the documentation of ksAppendKey

### ISSUE THREAD

**Issue by raphi011** [ElektraInitiative/libelektra#3072]
## Steps to Reproduce the Problem

1. Create a new key
1. increment the ref counter with `keyIncRef`
1. Add it to a keyset with `ksAppendKey`
1. call `ksClose` on the keyset
1. call `keyDel` on the key

## Expected Result

The deletion of the key is successfull since the keyset should not have deleted it as described in the documentation of `ksAppendKey`: 

```
 * Appends a Key to the end of @p ks.
 *
 * Hands the ownership of the key @p toAppend to the KeySet @p ks.
 * That means ksDel(ks) will remove the key unless
 * the key:
 * - got its refcount incremented by keyIncRef() before appending
 * - was also inserted into another keyset with ksAppendKey()
 ...
```

## Actual Result

Crashes with `invalid pointer` because `ksClose` ignores the keys ref counter.

## System Information

- Elektra Version: master

**Comment by markus2330** [comment]
Thank you for reporting this problem! As written in  #3073 this testcase should also be part of the test suite (for regression tests).

**Comment by raphi011** [comment]
Going to add the test tomorrow

**Comment by raphi011** [comment]
What is the easiest way to a run a single test in the tests/ctests folder? @markus2330

**Comment by markus2330** [comment]
`ctest -V -R ...`, I added it in 69400481b699c068dba595ae334f353da9706f8c

**Comment by raphi011** [comment]
Seems like I was wrong - the logic of not deleting the key if it still has references is implemented in `keyDel` not `ksDel`, so everthing should be fine. Closing this

**Comment by markus2330** [comment]
Maybe you can update the docu so that the next person is not confused about the logic of keyClose/ksClose?

**Comment by raphi011** [comment]
> Maybe you can update the docu so that the next person is not confused about the logic of keyClose/ksClose?

Done

**Comment by markus2330** [comment]
Can you reference to the commits/PRs where this happened? Ideally, you write "see/close #3072" within the commits, then the referencing happens automatically.

**Comment by raphi011** [comment]
Good question, I can remember changing the documentation but can't find the commit anymore. Will take another look tonight

**Comment by markus2330** [comment]
Implementation is in #3073
