### ISSUE TITLE
FreeBSD: run_dev_env not working

### ISSUE THREAD

**Issue by Chemin1** [ElektraInitiative/libelektra#3077]
The `run_dev_env` scripts doesn't seem to work on FreeBSD. Using `sh` as explained in #3076 makes that only an error message that I am used to (`cannot open...`) gets thrown.

```sh
sh
cd build
. ../scripts/run_dev_env
#.: cannot open /root/rene/scripts/include-common: No such file or directory
echo $?
#2
kdb ls /
#sh: kdb: not found
ls bin | grep "^kdb"
#kdb
#kdb-full
#kdbget
#kdbget_error
#kdbintro
#kdbopen
#kdbset
```

@llukask Markus mentioned that you use FreeBSD [here](https://github.com/ElektraInitiative/libelektra/issues/3067#issuecomment-542097209). Do you know what's going on?

**Comment by markus2330** [comment]
Thank you for reporting this problem!

Can you check what $SCRIPTS_DIR and $PATH contains? Furthermore, `grep "^Elektra_SOURCE_DIR" CMakeCache.txt` might be of interest. Maybe grep needs `-e` to support the `^` on FreeBSD?

In any case it seems like SCRIPTS_DIR is already wrong on your system and thus the rest of the script cannot do anything useful.

**Comment by Chemin1** [comment]
>
```sh
echo $0
#-csh
echo $SCRIPTS_DIR
#SCRIPTS_DIR: Undefined variable
echo $PATH
#/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
sh
echo $0
#sh
echo $SCRIPTS_DIR
#
echo $?
#0
echo $PATH
#/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
cd build
. ../scripts/run_dev_env
#.: cannot open /root/rene/scripts/include-common: No such file or directory
echo $SCRIPTS_DIR
#/root/libelektra/scripts
echo $PATH
#/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
Ctrl+D

[Now in Elektra repository root]
grep "^Elektra_SOURCE_DIR" CMakeCache.txt
cd build
grep "^Elektra_SOURCE_DIR" CMakeCache.txt
#Elektra_SOURCE_DIR:STATIC=/root/libelektra

**Comment by markus2330** [comment]
I see,  #3087 hopefully fixes the problem.
