### ISSUE TITLE
FreeBSD: run_asan not working

### ISSUE THREAD

**Issue by Chemin1** [ElektraInitiative/libelektra#3078]
`run_asan` doesn't seem to work on FreeBSD. Related to #3077?

```sh
sh
cd build
. ../scripts/run_dev_env
#.: cannot open /root/rene/scripts/include-common: No such file or directory
echo $?
#2
run_asan
#sh: run_asan: not found
```

Our [testing documentation](https://www.libelektra.org/devgettingstarted/testing) mentions
> Then, to use ASAN, run run_asan in the build directory, which simply does:
> ```
> ASAN_OPTIONS=symbolize=1 ASAN_SYMBOLIZER_PATH=$(shell which llvm-symbolizer) make run_all
> ```

At least one part of this command does not work on FreeBSD
```csh
shell which llvm-symbolizer
#sh: shell: not found
```

@llukask Do you know what's going on?

**Comment by markus2330** [comment]
Thank you for reporting this problem!

This seems to be a duplicate of #3077, as long as run_dev_env does not work, the other scripts obviously also cannot be found.

**Comment by Chemin1** [comment]
Let's assume `run_dev_env` was working. Then `run_asan` would fail if `llvm-symbolizer` is not installed?
```csh
find / -name llvm-symbolizer && echo $?
0
```
I cannot find llvm-symbolizer on my FreeBSD. If this is true then we could make a list of necessary packages for FreeBSD.

Additionally, I just noticed that the description of run_asan in TESTING.md contains an invalid string `shell`. I fixed it locally and plan to make a PR if I find some more little problems.

**Comment by markus2330** [comment]
The question is what "necessary" is. If FreeBSD does not have everything for ASAN packaged, maybe we should drop the idea to have ASAN test cases on FreeBSD?

The foremost goal should always be to have Elektra itself successfully running.

> Additionally, I just noticed that the description of run_asan in TESTING.md contains an invalid string shell. I fixed it locally and plan to make a PR if I find some more little problems.

Thank you very much!
