### ISSUE TITLE
Definition of bool

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#308]
There are various definitions of when bool evaluates to true, and when to false:

1. @manuelm only used `1` as true recently.
2. In python it is implemented by having `true`, `1` and `on` as true, everything else as false.
3. `check/type` uses C++ streams to decide (so its `1` is true)
4. In a PR recently: everything that starts with `1` is true.

I would suggest that we are strict and only accept `0` as false and `1` as true and have a convenience plugin which converts everything that could be interpreted as true to `1`.

What do you think?

**Comment by markus2330** [comment]
@manuelm: is it ok to rename "/shutdown" to "/noshutdown" to be consistent?

**Comment by manuelm** [comment]
`/noshutdown` only make sense if shutdown is the default behavior. And we had this discussion before :smile:

**Comment by markus2330** [comment]
Any suggestion how to get consistent behaviour for every bool?

**Comment by manuelm** [comment]
What's the problem with the current flag?

**Comment by manuelm** [comment]
`- 0 is false, everything else is true`
imho that's already true for `/shutdown`

`- rename options to "noOPTION" to avoid different default behavior`
I think this definition is somewhat limiting. It should rather be `no<OPTION>` where `<OPTION>` itself can already be negated. And `<OPTION>` should describe the default behavior.
In other words: An enabled boolean flag should always change the default behavior.

**Comment by markus2330** [comment]
> `- 0 is false, everything else is true`
> imho that's already true for `/shutdown`

The non-presence would be false, too.
 
> `- rename options to "noOPTION" to avoid different default behavior`
> I think this definition is somewhat limiting. It should rather be
> `no<OPTION>` where `<OPTION>` itself can already be negated. And `<OPTION>`
> should describe the default behavior. In other words: An enabled boolean
> flag should always change the default behavior.

I changed the wording so that two different defaults are allowed.

What do you think?

**Comment by manuelm** [comment]
>> `- 0 is false, everything else is true`
>> imho that's already true for `/shutdown`

> The non-presence would be false, too.

I'm sorry, but no. Non-presence is by definition no value, not defined or default.

> I changed the wording so that two different defaults are allowed.
> What do you think?

I'm not sure you changed it to something better. How about just doing: `0` is false, `1` is true. everyhing else is undefined and MAY throw an error.

**Comment by markus2330** [comment]
> > The non-presence would be false, too.
> 
> I'm sorry, but no. Non-presence is by definition no value, not defined or
> default.

If default is false the statements do not contradict.

> > I changed the wording so that two different defaults are allowed.
> > What do you think?
> 
> I'm not sure you changed it to something better. How about just doing: `0`
> is false, `1` is true. everyhing else is undefined and MAY throw an error.

This definition is nearly status-quo. The problem is, that everyone does 
something different in the "undefined" case. Thats nice for the implementor, but 
very troublesome for users.

I think, with validation enabled, there MUST be an error if its not `0` or `1` 
and thats obviously the preferred case.

But also without validation there should be a predictable, documented and 
defined behavior. I know that you currently are a fan of undefined behavior, but 
maybe you should think of SWIG with its undefined behaviour and if writing 
bindings would have been easier without it :)

**Comment by markus2330** [comment]
There is an issue with the idea regarding a boolean convenience plugin: It won't work for plugin configuration unless it is already encoded within the default plugin, because the plugin configuration is already fetched in the early bootstrap phase. We could however define some essential plugins (e.g. also sync) which are hardwired in the default backend when Elektra was compiled with them. See also #423.

**Comment by sirblackheart** [comment]
My question regarding this handling of boolean is the following:
There are many variations of booleans in configuration. If we convert them all to `0` or `1` we are not able to reproduce the correct string form from it. For example for importing and exporting configuration files from Elektra.
Or am i misunderstanding the proposed behavior of the convenience plugin?
From my point of view on a call of get<`bool`> on a string we should check for variations of `false` (`0`, `off`, `false` etc.) and return `FALSE` in that case. Everything else should be `TRUE`.

**Comment by markus2330** [comment]
The bool-plugin would hide the actual value in the configuration file for you and will canonicalize it to 0 and 1.

E.g. if you have an INI file:
a = true
b = TRUE
c = on

you would receive the keyset:

a = 1
b = 1
c = 1

when writing back, the old names would be preserved.

I do not think everything else should be false, e.g. if you have

d = is true
e = wahr
f = onn

you want an error when writing it out and it should not be considered as "false".
But we can add an configuration option for the bool-plugin if we do not have consensius here.

**Comment by sirblackheart** [comment]
> you want an error when writing it out and it should not be considered as "false".
I was saying true, but your point is valid for both and makes sense.

So does this mean we would need metadata for the convenience plugin?
How we decide when we check for boolean? For every key write? Only for spec values? Only for APIs that support it?

**Comment by markus2330** [comment]
Like other recoding plugins (e.g. null, ccode, ..) it would be in every set/get. And yes, it would need some type annotation (e.g. in the specification).

**Comment by markus2330** [comment]
@tom-wa: Can write such a boolean plugin?

**Comment by tom-wa** [comment]
should the plugin check/convert every value, or only keys tagged with `type/boolean` ?

**Comment by markus2330** [comment]
Only tagged ones, we do not plan to reimplement infamous spreadsheet programs that shredder data ;)

**Comment by markus2330** [comment]
Thank you for all your participation!
