### ISSUE TITLE
Idea: Combine namespaces in KeySet

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3080]
This is not really a proposal, but more an idea I had. It is completely untested. It is also a **very big** change, probably version 2.0 rather than 1.0.

We are currently working towards all keys having a proper namespaces. This gave me an idea.

## Current situation

Right now we use the full key name as the sort key and the hash map key in a KeySet. This means that a cascading lookup requires multiple lookups and that the array stored in the KeySet can get big quickly.

## Idea

When inserting a Key into a KeySet ignore the namespace for sorting and hash map purposes. Both `user/key` and `system/key` would be stored under `key`. This of course requires a *new structure* to contain the keys for the different namespaces.

## Benefits

- A cascading lookup is a single hash map or sorted array lookup. After that we just select the correct namespace from the new structure.
- If the spec plugin is given access to this new structure, it could be simplified quite a bit. As long as no `_` wildcards are involved. 
- Less memory footprint. If we swap the keyname at the appropriate moments, we could avoid storing the `key` part for `user/key` and `system/key` twice.

## Problems

- This change would affect KeySet order.
- Very high effort.

## Alternatives

- Don't use a new structure inside KeySets. Change `Key` to contain values for all namespaces in one instance. This would have implications outside of KeySets. It would also change the semantics of `ksAppendKey`. On the other hand it would not require swapping key names to reduce memory footprint.

**Comment by markus2330** [comment]
Thank you very much for the idea! The big question with more complex data structures is how we can maintain the easy and fast O(1) iteration we have now.

I agree that this is out-of-scope for 1.0.0. I'll close issues for 2.0.0 so that it is easier to find 1.0.0 issues.
