### ISSUE TITLE
remove ksLookup features not related to looking up keys

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3083]
Elektra used to have ksLookup features that were simply iterating over all keys and checking values. This functionality is not very useful.

Thus following functions should be removed:

- [ ] ksLookupByString (which is also buggy, see a9e2aab7cc933995e99b48c0fa6c4deb75e11755)
- [ ] ksLookupByBinary
- [ ] elektraLookupLinearSearch
- [ ] KDB_O_NODIR and so on, are already marked to be removed, until
 - [ ] KDB_O_NOALL

**Comment by PhilippGackstatter** [comment]
In the [keyvalue documentation](https://doc.libelektra.org/api/current/html/group__keyvalue.html#ga6f29609c5da53c6dc26a98678d5752af) under the Binary Data Handling heading, in the example, there is a reference to `KDB_O_SORT`. How should that be changed/handled if these are removed?
