### ISSUE TITLE
run_dev_env in csh

### ISSUE THREAD

**Issue by Chemin1** [ElektraInitiative/libelektra#3085]
As mentioned in [this comment](https://github.com/ElektraInitiative/libelektra/pull/3076#issuecomment-543037905). FreeBSD has `csh` as default shell. The syntax of run_dev_env is invalid in csh.

```csh
source ../scripts/run_dev_env
# if: Expression Syntax.
echo $?
#1
```

I added documentation on how to avoid this problem in #3076 but we could improve user experience by having scripts work with `csh` too.

I don't  know if there is one syntax that fits many shells including `csh`. We could detect which shell a user is running and forward to different scripts if not.

**Comment by markus2330** [comment]
Thank you for reporting this problem!
