### ISSUE TITLE
test_service_convertengine fails on website build

### ISSUE THREAD

**Issue by Chemin1** [ElektraInitiative/libelektra#3086]
`test_service_convertengine` fails during `Starting build/hub.libelektra.org/build-elektra-website-backend`. [logfile here](https://github.com/ElektraInitiative/libelektra/files/3738796/log.1.txt).

According to https://github.com/ElektraInitiative/libelektra/issues/2967#issuecomment-543039772 we can disable the test to fix this.

**Comment by markus2330** [comment]
Thank you for reporting the problem!
