### ISSUE TITLE
CMake Error With `man` Target

### ISSUE THREAD

**Issue by iandonnelly** [ElektraInitiative/libelektra#309]
I am getting this error when trying to build Elektra. It appears to be related to adding the dependency for man into [src/libgetenv/CMakeLists.txt](src/libgetenv/CMakeLists.txt) which was done in commit 941aebcd5f3023d4adc5e1b6a4b812ade6b4c972.

    CMake Error at src/libgetenv/CMakeLists.txt:35 (add_dependencies):
      Cannot add target-level dependencies to non-existent target "man".

      The add_dependencies works for top-level logical targets created by the
      add_executable, add_library, or add_custom_target commands.  If you want to
      add file-level dependencies see the DEPENDS option of the add_custom_target
      and add_custom_command commands.

    -- Configuring incomplete, errors occurred!

**Comment by iandonnelly** [comment]
This happened after when trying to build from scratch (after deleting the contents of the build dir).

**Comment by markus2330** [comment]
Seems like you have disabled BUILD_DOCUMENTATION, but with ronn installed.

Thanks for reporting!

**Comment by iandonnelly** [comment]
Still have the same error. I installed doxygen and it went away...

**Comment by markus2330** [comment]
Did you get the warning "Doxygen not found, Reference Manual can't be created even though requested with BUILD_DOCUMENTATION."

**Comment by markus2330** [comment]
I will try to improve that together with the BUILD_PDF issue.

**Comment by iandonnelly** [comment]
Yes, I did actually get that warning looking back at my bash history.
