### ISSUE TITLE
Remove src/include/kdbobsolete.h

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3091]
As it only contains one function, we can remove the file (ideally also the function).

**Comment by kodebach** [comment]
It might take some time because AFAIK either elektraKeySetName or elektraUnescapeKeyName uses keyGetNameOneLevel, so they have to be changed before keyGetNameOneLevel can use the unescaped name.

**Comment by markus2330** [comment]
> I will change keyGetNameOneLevel. The simple solution would be to extract one level from the unescaped name and then escape it. 

keyBaseName currently returns from the unescaped name but you are right, it makes sense to always get the escaped form. See d8bd4f37626170dcf31033ef728e208aa53397f8

We should definitely improve the docu on these details and in this case maybe even the behavior (I think it was already confusing for someone that keyBaseName returns the unescaped form, e.g.  #176). Thank you for taking a look at it!

**Comment by PhilippGackstatter** [comment]
> I will change keyGetNameOneLevel.

Okay, then imo it makes more sense for you to remove `kdbobsolete.h` when you get around to change `keyGetNameOneLevel`. Otherwise I'm just moving functions around.

**Comment by markus2330** [comment]
Ok, I reassigned @kodebach for now as he is currently working in this area. (@kodebach you can assign back if the function cannot be removed and should be moved.)
