### ISSUE TITLE
src/libs/highlevel/elektra_error.c

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3092]
https://github.com/ElektraInitiative/libelektra/blob/e000710a83fe3a7ae019a12d7efd37676ee6b59f/src/libs/highlevel/elektra_error.c#L124-L129

@kodebach what is wrong there?

@Piankero please document how to get number of warnings.

**Comment by markus2330** [comment]
Thank you for making the bug request more pretty and helpful.

I agree warnings should be a proper array. Thank you for adding the TODO.

@Piankero any further questions?

**Comment by Piankero** [comment]
I want to change the way warnings are stored after the merge of #2976.

**Comment by Piankero** [comment]
Not related to visible error messages.
As discussed in the Elektra meeting I may unassign myself.
