### ISSUE TITLE
Fix TODOs

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3093]
Important TODOs to be fixed:

- [ ] kdb.c
- [ ] src/libs/elektra/split.c
- [ ] src/plugins/cache/cache.c (@mpranj)
- [ ] src/plugins/mmapstorage/mmapstorage.c (@mpranj)

**Comment by markus2330** [comment]
@kodebach are these TODOs still there/relevant after new-backend?

**Comment by kodebach** [comment]
There are TODOs in `kdb.c` but they are all from new-backend, `split.c` is completely gone, `cache.c` needs to be updated anyway (the TODOs may still be relevant), `mmapstorage.c` was almost if not completely untouched by new-backend.
