### ISSUE TITLE
elektraStrNDup should be elektraMemDup

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3110]
The function name `elektraStrNDup` could be confusing. In the standard library `strn*` functions use the length as a maximum, but stop if a `\0` is encountered first. `elektraStrNDup` meanwhile ignores any `\0` it encounters. In the standard library such functions are called `mem*`.

It is especially confusing, since there is a `strndup` function [in the POSIX standard](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html) already.

**Comment by markus2330** [comment]
Yes, I fully agree, it should be renamed.

**Comment by a-kraschitzer** [comment]
I could do a quick search and replace for this aswell.
`elektraStrNDup` -> `elektraMemDup` ?

**Comment by kodebach** [comment]
Sure, go ahead. But please use a separate PR for this issue, so we can merge it separately when it has the least impact on other ongoing PRs.
