### ISSUE TITLE
newlines in meta data with ini

### ISSUE THREAD

**Issue by Chemin1** [ElektraInitiative/libelektra#3114]
The ini plugin does not seem to handle newlines in meta data correctly.

## Steps to Reproduce the Problem
```
echo "127.0.0.1       localhost

127.0.1.1       computer

# BASE The following lines are desirable for IPv6 capable hosts

::1     ip6-localhost ip6-loopback

fe00::0 ip6-localnet

ff00::0 ip6-mcastprefix

ff02::1 ip6-allnodes

ff02::2 ip6-allrouters" | kdb import user/tests/hosts/base hosts

echo "127.0.0.1       localhost

127.0.1.1       computer

# OUR The following lines are desirable for IPv6 capable hosts

::1     ip6-localhost ip6-loopback

fe00::0 ip6-localnet

ff00::0 ip6-mcastprefix

ff02::1 ip6-allnodes

ff02::2 ip6-allrouters" | kdb import user/tests/hosts/our hosts

echo "127.0.0.1       localhost

127.0.1.1       computer

# THEIR The following lines are desirable for IPv6 capable hosts

::2     ip6-localhost ip6-loopback

fe00::0 ip6-localnet

ff00::0 ip6-mcastprefix

ff02::1 ip6-allnodes

ff02::2 ip6-allrouters" | kdb import user/tests/hosts/their hosts

kdb cmerge user/tests/hosts/our user/tests/hosts/their user/tests/hosts/base user/tests/hosts/result

kdb get user/tests/hosts/result/ipv6/ip6-localhost

kdb meta-get user/tests/hosts/result/ipv6/ip6-localhost comment/#1


ERROR - RET:

Return value “2” does not match “0”



ERROR - STDOUT:

“”

does not match

“ THEIR The following lines are desirable for IPv6 capable hosts”
```

## System Information

- Elektra Version: some version of PR #3106
- This happens only in jenkins build debian-stretch-full-ini

**Comment by Chemin1** [comment]
This does not only affect multiline input but meta arrays in general.
```
kdb cmerge user/tests/hosts/our user/tests/hosts/their user/tests/hosts/base user/tests/hosts/result
kdb get user/tests/hosts/result/ipv6/ip6-localhost
kdb set user/tests/meta/base equal
kdb meta-set user/tests/meta/base comment/#0 "This is the original inline comment"
kdb meta-set user/tests/meta/base comment/#1 "This is the first line of the original comment above the key"
kdb meta-set user/tests/meta/base comment/#2 "This is the second line of the original comment above the key"
kdb set user/tests/meta/their equal
kdb meta-set user/tests/meta/their comment/#0 "This is their inline comment"
kdb meta-set user/tests/meta/their comment/#1 "This is the first line of their comment above the key"
kdb meta-set user/tests/meta/their comment/#2 "This is the second line of their comment above the key"
kdb set user/tests/meta/our equal
kdb meta-set user/tests/meta/our comment/#0 "This is your custom inline comment"
kdb meta-set user/tests/meta/our comment/#1 "This is the first line of your custom comment above the key"
kdb meta-set user/tests/meta/our comment/#2 "This is the second line of your custom comment above the key"
kdb cmerge user/tests/meta/our user/tests/meta/their user/tests/meta/base user/tests/meta/metaFromOur
kdb meta-get user/tests/meta/metaFromOur comment/#0
ERROR - RET:
Return value “2” does not match “0”

ERROR - STDOUT:
“”
does not match
“This is your custom inline comment”

kdb meta-get user/tests/meta/metaFromOur comment/#1
ERROR - RET:
Return value “2” does not match “0”

ERROR - STDOUT:
“”
does not match
“This is the first line of your custom comment above the key”

kdb meta-get user/tests/meta/metaFromOur comment/#2
ERROR - RET:
Return value “2” does not match “0”

ERROR - STDOUT:
“”
does not match
“This is the second line of your custom comment above the key”
```

**Comment by markus2330** [comment]
Thank you for reporting this problem!

In general you should not expect too much from the INI plugin, I updated its status in #3116. Hopefully it will soon be superseded (in most cases) by @bauhaus93's TOML plugin.

Why are you trying to mount a hosts file with the INI plugin? And is this report different from  #2467?

I think best for your evaluation will be if you compare some plugins (like host plugin, but also ini/TOML if it is an INI/TOML file) with the line plugin. The line plugin will then only make a pure array merge (with your libgit2 implementation). This will be a fair comparison and you do not need two different setups (but everything will be done with Elektra).

**Comment by Chemin1** [comment]
> Why are you trying to mount a hosts file with the INI plugin?

I always used  `... | kdb import ... hosts` is this doing mounts with ini in the background?

> And is this report different from #2467?

I did not see that. He used `kdb mount` there but I think it's basically the same problem.

> compare some plugins

Thank you! I will take a look at how this works and do that!

**Comment by markus2330** [comment]
`kdb import X hosts` will use the hosts plugin to convert the input to the KeySet and whatsoever is mounted at X (in your case INI?) will be used to transform the KeySet to a persistent file.

Did you maybe use ini as default storage plugin?

>  Thank you! I will take a look at how this works and do that!

Good. The advantage will be that all the conflicts are then counted the same way (with your implementation).

**Comment by Chemin1** [comment]
> Did you maybe use ini as default storage plugin?

This only happens in the jenkins build `debian-stretch-full-ini` for which the comment in the Jenkinsfile says
> Build Elektra with the ini backend instead of the default

**Comment by markus2330** [comment]
Yes, in this build job everything is written to INI files and any limitation of the ini plugin applies.

You can disable the build debian-stretch-full-ini (in scripts/jenkins/Jenkinsfile). @bauhaus93 will later create a debian-stretch-full-toml which will hopefully not have this problem.

**Comment by Chemin1** [comment]
> You can disable the build debian-stretch-full-ini

I have already changed my examples so that they can pass the full-ini build some days ago, so we could also leave the build running for the moment.

**Comment by markus2330** [comment]
Ok.
