### ISSUE TITLE
Append library dependencies to elektra-full

### ISSUE THREAD

**Issue by dominicjaeger** [ElektraInitiative/libelektra#3119]
As discussed [here](https://github.com/ElektraInitiative/libelektra/commit/1dd52cd0dd3b75a6e66ff96838636dc1aa46f106#commitcomment-35680046) we should add something like this line from LibAddPlugin.cmake

```
set_property (GLOBAL APPEND PROPERTY "elektra-full_LIBRARIES" ${REQUIRED_LIBRARY_DIRS})
```

to LibAddLib.cmake as well. This way we will not have to set this property manually every time we create a new library.

**Comment by markus2330** [comment]
Thank you for reporting this problem! Also make sure to remove this line from the merge lib afterwards.
