### ISSUE TITLE
provide API to get/set errors in cpp/python

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3129]
We now have a much simplified error system. It would be nice if these errors/warnings are better integrated in python/lua, e.g. by providing exception classes that can be thrown from plugins and/or can be caught from failing kdbGet/kdbSet.

See also doc/tutorials/language-bindings.md

Maybe make first a proposal how to do it before implementing something.

**Comment by manuelm** [comment]
If python plugins should be able to throw errors the cpp bindings need exception classes. So someone (def. not me) needs to generate these C++ exception classes during build time. And we definitely need to intergrate the generated helpers which fills the exception payload (the error key) into the exception classes.

After this is done the python plugin can be extended to catch the exception and extract the errorkey payload.

Regarding kdb open/get/set/close: Should be implemented in the cpp bindings. After step 1. python will automatically pick it up.

Lua doesn't support any kind of exceptions at all.

**Comment by Piankero** [comment]
This issue is unrelated to visible error messages.
As discussed in the Elektra meeting I may unassign myself.
