### ISSUE TITLE
Semantics in merge

### ISSUE THREAD

**Issue by Chemin1** [ElektraInitiative/libelektra#3132]
Merging should take into account semantics like the following.

- [ ] floats  0.00 == 0.0000 == 0.0000000
- [x] booleans yes == true == 1

To do so the type plugin must be improved.

**Comment by markus2330** [comment]
Thank you for creating this issue!

Btw. it is good if we can get rid of the name "cmerge" as fast as possible (and use "merge" everywhere).

It should be enough if you fix the semantic equality once in the type plugin. Then it should not be needed to have several fixes in json/toml/ini.

**Comment by markus2330** [comment]
Yes, of course. I was referring to the title of the issue.
