### ISSUE TITLE
Permission error on hetzner

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3138]
In https://build.libelektra.org/jenkins/blue/rest/organizations/jenkins/pipelines/libelektra/branches/PR-3125/runs/5/nodes/638/steps/1315/log/?start=0 I now got a full log of the errors on the hetzner node. The essential information is:

```
id: unknown ID 47000
id: unknown ID 47000
```

So somehow the ID used in Docker is not connected to the jenkins ID with the correct home directory. That is why user is written to /.config instead of /home/jenkins/.config

Please fix and document in doc/BUILDSERVER.md how to setup Docker correctly (with correct ID).

**Comment by Mistreated** [comment]
The User ID should not be 47000, it should be 47110.

**Comment by markus2330** [comment]
Good that you found out, please also fix the docu.

**Comment by markus2330** [comment]
Ahh, you already did, great :+1:
