### ISSUE TITLE
Jenkins: retry problematic stages

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3146]
According to the [pipeline documentation](https://jenkins.io/doc/book/pipeline/running-pipelines/#restarting-from-the-blue-ocean-ui), we should be able to restart individual jobs from stages by clicking a button.

The feature should have been introduced by Pipeline: Declarative version 1.3. We are running 1.3.1 but the feature seems to be missing. Some other plugins are also slightly outdated. Are there any issues blocking us from upgrading everything?

**Comment by markus2330** [comment]
@mpranj thank you for making us aware of this.

@ingwinlu @Mistreated do you know something about this?

**Comment by sanssecours** [comment]
> do you know something about this?

As far as I know we do not use the “declarative pipeline syntax”, but the older [“scripted pipeline syntax”](https://jenkins.io/doc/book/pipeline/syntax/#scripted-pipeline). This means we most probably will never be able to restart stages, unless we switch to the more modern (but also more limited) declarative pipeline style.

See also: https://github.com/ElektraInitiative/libelektra/pull/2927#issuecomment-528885991

**Comment by markus2330** [comment]
Yes, https://issues.jenkins-ci.org/browse/JENKINS-45455 says it is only declarative pipeline.

According to https://stackoverflow.com/questions/38129745/jenkins-build-pipeline-restart-at-stage the "retry" might be better suited than https://wiki.jenkins.io/display/JENKINS/Naginator+Plugin (which restarts the whole job, not only parts).

@Mistreated Can you please add some retry at the hot-spots? I think this could fix most of #2967

**Comment by markus2330** [comment]
Seems to be a wontfix
