### ISSUE TITLE
mmapstorage: filter empty meta keysets

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3147]
Filter out empty meta keysets in `mmapstorage` to minimize disk and memory space used. ([See discussion](https://github.com/ElektraInitiative/libelektra/pull/3142#discussion_r341816840).)

**Comment by markus2330** [comment]
Thank you for creating this issue! If you have more spaces to fill: it would be interesting which parts use how much of the disk space.

**Comment by mpranj** [comment]
I added it to my notes. I have written quite a bit this week, but it might fit in somewhere, so thanks for the hint!

**Comment by markus2330** [comment]
As discussed, this is a research question on its own and might not be needed for this thesis.
