### ISSUE TITLE
testmod_gopts: sporadic timeouts

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3148]
Seems like `testmod_gopts` sometimes has timeouts. I thought this is was introduced by my PR but we have seen different PRs now with this issue.

## Steps to Reproduce the Problem

Open a PR and let the builds and tests run.

## Expected Result

Test suite runs fine.

## Actual Result

Sometimes the tests time out:

```

 76/134 MemCheck  #85: testmod_gopts ....................***Timeout 120.05 sec

```

## System Information

- Elektra Version: master
- Operating System or Docker Container?
- Versions of other relevant software?

**Comment by markus2330** [comment]
Thank you for creating this issue!

@kodebach do you have ideas why this occurs?

**Comment by kodebach** [comment]
I assume this only happens for the `MemCheck` tests? If so, `testmod_gopts` uses `fork`/`exec` which is quite slow with valgrind. We could either increase the timeout or exclude the test.

**Comment by markus2330** [comment]
Lets try to increase the timeout.
