### ISSUE TITLE
Jenkins: build timeouts

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3157]
The following build message occurred in multiple PRs I have seen (e.g. #3150):
```
Sending interrupt signal to process

Terminated
```

It seems that we are increasingly hitting the 10 minute Jenkins limit (when a build has no log output for 10 minutes). https://github.com/ElektraInitiative/libelektra/blob/6aea503521a35cbeef3a719f8c73c2fe40830c1d/scripts/jenkins/Jenkinsfile#L1271

I'm not sure it will help to increase the limit, as some of the killed jobs show that they are running for 5+ hours. We can try to increase the limit and see whether we are only exceeding it by very little. Otherwise I think we will need to evaluate what's causing the builds to take forever and work on a better solution.

The fact that many builds are currently failing (and being re-built) because of problems with our Jenkins ironically puts even more load on the systems, so the effect seems to amplify.

**Comment by markus2330** [comment]
Thank you for creating this issue!

@Mistreated can you try to change the timeout?

**Comment by mpranj** [comment]
I took the liberty to test/increase the timeout in my PR, as it keeps hitting this limit. Seems like it is usually a build on a7 (which is slower) and I have not yet seen it on v2 (which is presumably faster).

**Comment by markus2330** [comment]
Problems seem to be gone.
