### ISSUE TITLE
PKG_CONFIG_PATH in go bindings

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3159]
```sh
> dpkg -L libelektra-dev | grep pc                                                                                                                                                  /usr/lib/x86_64-linux-gnu/pkgconfig/elektra-codegen.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/elektra-highlevel.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/elektra-io.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/elektra-notification.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/elektra.pc
> PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig go test -run "^(TestKeySetMemory)\$"   
 can't load package: package github.com/ElektraInitiative/go-elektra: unknown import path "github.com/ElektraInitiative/go-elektra": cannot find module providing package github.com/ElektraInitiative/go-elektra
```

**Comment by markus2330** [comment]
Why do I need this PKG_CONFIG_PATH at all? IIRC I did not provide it the last time.

**Comment by raphi011** [comment]
You may not need this env var if the package config path is already set.

Seems like you have to enable go mod with `GO111MODULE=on`

**Comment by markus2330** [comment]
No, I was not in the kdb subdirectory. Then I get:

```
# go.libelektra.org/kdb_test [go.libelektra.org/kdb.test]
./kdb_test.go:128:13: undefined: errors.Is
FAIL    go.libelektra.org/kdb [build failed]
```

Can you add in README.md about how to execute TestKeySetMemory? Is it disabled by default?

**Comment by raphi011** [comment]
You need go v1.13

**Comment by markus2330** [comment]
In Debian stable (buster) is only golang 1.11~1. Which features require a newer go?

**Comment by raphi011** [comment]
The `errors` package

**Comment by markus2330** [comment]
What exactly does the errors package provide that it is worth this limitation? In general it is good if the bindings have as little deps as possible.

**Comment by raphi011** [comment]
That's why I upgraded to go 1.13 - because I wanted no external dependencies and the new version added a useful errors package.

**Comment by markus2330** [comment]
Ok, sounds like a good idea then. How can I get go 1.13 in Debian Buster (and also for our Docker images)?

**Comment by raphi011** [comment]
here's a handy guide: https://tecadmin.net/install-go-on-debian/
