### ISSUE TITLE
kdb::tools::Backend::getName not implemented

### ISSUE THREAD

**Issue by manuelm** [ElektraInitiative/libelektra#316]
![cheering up](https://38.media.tumblr.com/203c4fd85b4c643567dacc81fdd27df3/tumblr_inline_mi0do1EEXN1qz4rgp.jpg)

**Comment by markus2330** [comment]
Thanks for reporting! I removed kdb::tools::Backend::getName in 70f16807f1a9a41231c8cadfbf9d3614132743e4 because backends do not have a "name" anymore. (They are unique by where they are mounted to)
