### ISSUE TITLE
libelektra-daily build job fails

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3160]
https://build.libelektra.org/jenkins/job/libelektra-daily/639/console

**Comment by markus2330** [comment]
It seems like the disc space goes full very fast if this is not fixed, I tag it as urgent.

**Comment by markus2330** [comment]
```
[git/hetzner-jenkins1/libelektra] [git_mirrors] Running shell script
[git/hetzner-jenkins1/libelektra] + git clone --mirror https://github.com/ElektraInitiative/libelektra.git libelektra
[git/hetzner-jenkins1/libelektra] Cloning into bare repository 'libelektra'...
[git/hetzner-jenkins1/libelektra] /home/jenkins/git_mirrors/libelektra: Permission denied
```

**Comment by Mistreated** [comment]
@markus2330 Fixed. Can be closed now.

**Comment by markus2330** [comment]
Thank you!

**Comment by markus2330** [comment]
@Mistreated the same error again on Jenkins3: https://build.libelektra.org/jenkins/job/libelektra-daily/659/console

I resized the disc from 200 to 300GB as it was full.

**Comment by Mistreated** [comment]
Fixed.

https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra-daily/detail/libelektra-daily/660/pipeline

**Comment by markus2330** [comment]
daily is broken again: https://build.libelektra.org/job/libelektra-daily/21/console

Please test your agents when you add them! Also document what is to do and go over these checklists.

**Comment by Mistreated** [comment]
Fixed. 

The problem is that the folder `git_mirror` is made from the user `root`. That triggers the error when user `jenkins` tries to do something with it.

**Comment by markus2330** [comment]
Thank you for fixing it!
