### ISSUE TITLE
build jobs for master unstable

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3161]
See https://github.com/ElektraInitiative/libelektra/commits/master# Jenkins stopped building for master.

**Comment by markus2330** [comment]
Seems like it only took quite a time as several commits happened during a short time.

Still the master Jobs are quite unstable (now Travis seems to have failed).

**Comment by sanssecours** [comment]
> Still the master Jobs are quite unstable (now Travis seems to have failed).

The Travis builds for the master build were just auto-canceled: If there are new commits on a branch and none of the build jobs for an “old” commit on the same branch started, the whole build for the “old” commit will be canceled. Canceled builds will shows up as “failed” (`❌`) on the GitHub page for a certain branch. I now turned off that option.

<img width="952" alt="Auto Cancel" src="https://user-images.githubusercontent.com/691989/68194568-8c542900-ffb5-11e9-8de7-405595cdced8.png">

> Seems like it only took quite a time as several commits happened during a short time.

That was always the case. The main Jenkins build server is just not fast enough to react to “fast“ updates.

**Comment by markus2330** [comment]
Thank you for the explanation!
