### ISSUE TITLE
Plugin docu: link checker fail

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3181]
Commit 2ce0dbbd905f36eb2af7eb792453bde2416b51bd removed a linked file.

```
Broken Links:
—————————————
doc/tutorials/plugins.md:368:0 https://github.com/ElektraInitiative/libelektra/blob/master/src/error/specification
—————————————
```

@Piankero I was not sure if the docu in `doc/tutorials/plugins.md:368` maybe needs a general update after your PR was merged?

**Comment by markus2330** [comment]
Thank you for reporting the problem, seems like @Piankero forgot to update this part.

I removed the sentence to make master build again in cac326cb6292f216ea05b1f8bb8dd0cba6b24bd3 but the text needs to be adapted to the new errors.

**Comment by Piankero** [comment]
Already merged
