### ISSUE TITLE
rename binding swig_python to python

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3186]
Currently, `cmake` (without setting PLUGINS or BINDINGS) outputs:

```
-- Exclude Plugin python because swig_python binding is required
-- Exclude Plugin python2 because swig_python2 binding is required
[...]
-- Include Binding cpp
-- Exclude Binding jna because javac (java compiler) not found, which is only included in a jdk
-- Exclude Binding rust because excluded by category EXPERIMENTAL
-- Exclude Binding swig_ruby because explicitly excluded
-- Exclude Binding gsettings because excluded by category EXPERIMENTAL
-- Exclude Binding intercept_fs because excluded by category EXPERIMENTAL
-- Include Binding intercept_env
-- Exclude Binding io_uv because excluded by category EXPERIMENTAL
-- Exclude Binding io_ev because excluded by category EXPERIMENTAL
-- Exclude Binding io_glib because excluded by category EXPERIMENTAL
```

It does not write anything about the python binding. (info about swig_ruby is also wrong).

To include the python binding, currently it is needed to call (see also #3185 for the confusion):

```
cmake -DSWIG_EXECUTABLE=/usr/bin/swig3.0 -DBINDINGS="cpp;swig_python" ../workspace
```

I propose following changes:

- [x] rename the swig_python and swig_lua bindings to simply python and lua
- [x] remove the python2 binding and plugin (as python2 days are counted anyway)
- [x] fix the output, that "Exclude Binding" is also printed correctly for python/lua/ruby
- [x] that the python binding is included by default, as it is well tested and in productive use

@manuelm what do you think?

**Comment by manuelm** [comment]
Sure. Go ahead.

**Comment by markus2330** [comment]
Removing python2 support was your suggestion. Will you do at that part? The other things should be very minor.
