### ISSUE TITLE
print error if python3 module is imported in python2

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3187]
A low-priority usability issue but maybe it is easy to fix.

If I run `python` with an PYTHONPATH to the python3 kdb module and type `import kdb` I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3/dist-packages/kdb.py", line 190
    def what(self) -> "char const *":
                   ^
SyntaxError: invalid syntax
```

I would expect an output like:

```
Error: You tried to import the python3 kdb module in python2. You need at least python version 3.X to use kdb.
```

(X replaced with our minimum version we support, please support at least 3.6)

**Comment by manuelm** [comment]
The SyntaxError is thrown during compile time. No single statement of the module has been executed at this time. So that's not possible. You can catch SyntaxErrors in the code that it is importing the module though.

**Comment by markus2330** [comment]
Thank you for the quick answer!
