### ISSUE TITLE
remove cursor API

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3189]
I propose:

- [ ] ksGetCursor/ksSetCursor to be removed (due to #3171)
- [ ] `Key *ksAtCursor(KeySet *ks, cursor_t cursor);` to be changed to `Key *ksAt(KeySet *ks, ssize_t index);`
- [ ] `Key * elektraKsPopAtCursor (KeySet * ks, cursor_t pos)` to be changed to `Key * ksPop (KeySet *ks, ssize_t index);` (and to remove current `ksPop`, as it is simply `ksPop(ks, -1)`).
- [ ] `ssize_t ksIndex (KeySet * ks, Key * key)` (see below)
- [ ] to remove cursor_t

Negative index represent index from the end.

- [ ] Then the Java API (remove in src/bindings/jna/libelektra4j/src/main/java/org/libelektra/KeySetIterator.java) can be fixed to use ksPop instead of looking up the key we already found

What do you think?

**Comment by PhilippGackstatter** [comment]
I like these changes. Since we move away from internal iterators, I think it makes sense to also implement 
- indexing in languages that support it. E.g. `let first_elem = keyset[0]`, which is just nicer than `keyset.at(0)`.
- indexing by ranges, to get a slice of a keyset like `let first_3_elems = keyset[0..3]`.

**Comment by markus2330** [comment]
Thank you for the feedback, yes I agree!

In Python we have currently indexing by key name (string). I am not sure if it is possible to provide both at once (indexing by string and number)? @manuelm?

**Comment by manuelm** [comment]
SWIG doesn't use the C functions

**Comment by markus2330** [comment]
> SWIG doesn't use the C functions

Why is this implementation issue relevant here? Also the C function does not exist yet.

In this case (for []) the operator overloading happens directly in the Python binding, not in C++.

**Comment by manuelm** [comment]
Sorry. Didn't look at your actual question. So this:  https://github.com/ElektraInitiative/libelektra/blob/9a3413f7dee83e8d7d628056092781b4088f1269/src/bindings/swig/python/tests/test_keyset.py#L36 ?

**Comment by markus2330** [comment]
Exactly, so we have this already :sparkle:. And it is even mentioned in the tutorial :sparkling_heart: (with slicing).

@PhilippGackstatter so @manuelm already implemented what you proposed :stuck_out_tongue_winking_eye:

**Comment by kodebach** [comment]
We also need a way to lookup the index of a key in a KeySet. This is needed as a replacement for:

```c
ksLookup (ks, k, 0);
cursor_t cursor = ksGetCursor (ks);
```

**Comment by markus2330** [comment]
Yes, I forgot about that. A quite elegant solution would be that `ksLookup` returns a pair of index and the key, unfortunately this is not possible in C (it supports only struct (which is a disaster for binary compatibility) or union (which is an ugly hack as the options would decide what part of the union is valid)).

So we would need a `ksIndex (KeySet *, Key * lookupKey)`. But isn't this quite unrelated to the above proposal? I could not find any code that actually needs this. So we can add this after 1.0.

**Comment by kodebach** [comment]
> But isn't this quite unrelated to the above proposal?

It is related because you want to remove `ksGetCursor`.

> I could not find any code that actually needs this.

It might be used externally. Its also the best way of checking, if a key has other keys below (in a certain KeySet):

```c
 // precond: key is not cascading and definitely part of ks
ksLookup (ks, key, 0);
cursor_t c = ksGetCursor (ks);
Key * k1 = ksAtCursor (ks, c + 1);
if (keyIsBelow (key, k1) == 1) {
   // key has subkeys
} else {
  // key is leaf
}
```

> So we can add this after 1.0.

Why not now? We aren't removing `ksNext`, so the internal cursor is still set correctly in `ksLookup`. The implementation could basically be:

```c
ssize_t ksIndex (KeySet * ks, Key * key)
{
    ksLookup (ks, key);
    return ks->cursor;
}
```

Adding this is basically no effort compare to the rest of this issue.

**Comment by markus2330** [comment]
Ok, I added it in the top post and removed the "proposal" tag.

> Why not now?

It easily happens in quickly introduced APIs that you find in retrospective that a different API would have been better.

**Comment by markus2330** [comment]
We should at least move ksGetCursor/ksSetCursor to a private header file.

**Comment by kodebach** [comment]
As part of #3651 I added `ksFindHierarchy`. It is only part of `kdbprivate.h` (could be changed), but it basically does what the proposed change for `ksLookup` / the proposed `ksIndex` would do (and a bit more). It doesn't rely on the internal cursor at all, so it should be the perfect candidate here.

**Comment by markus2330** [comment]
The iterators need more thought, I do not think it is suitable for CM.

**Comment by kodebach** [comment]
ping

**Comment by markus2330** [comment]
> ping

Simply removing the stale label should work as well.

Can you put this to a decision?

**Comment by kodebach** [comment]
> Can you put this to a decision?

We already have one: https://github.com/ElektraInitiative/libelektra/blob/master/doc/decisions/iterators.md

**Comment by markus2330** [comment]
ksIndex/ksHierarchy etc. is not mentioned there?

**Comment by kodebach** [comment]
AFAICT `ksIndex` is basically what we now have with `ksSearch`. Except that the behaviour is slightly different for keys that are not in the keyset. The return value is still negative (i.e. shows the key is not present), but `ksSearch` also indicates where the key would be. Therefore, I think `ksSearch` is superior to the originally proposed `ksIndex`.

I assume `ksHierarchy` was supposed to be `ksFindHierarchy`. We could put it into the `iterators.md` decision. But I think, it would probably be better in one of the new decisions (`simplify_api.md` etc.). The function already exists (I needed it somewhere), but is currently part of `kdbprivate.h`. I think it is not used in the core and I don't think the function can be considered minimal API. So we should probably just move to one of the new extra libraries (#4245).
