### ISSUE TITLE
Mounting with no sudo leads to an error with no error messages

### ISSUE THREAD

**Issue by darddan** [ElektraInitiative/libelektra#3197]
## Precondition

You have no rights to change the system envivironment keys from the user environment

## Steps to Reproduce the Problem
```sh
echo "{\"key\":\"value\"}" > test.json
kdb mount ${pwd}/test.json /test_json json
```

## Expected Result

An error message showing whats wrong or how to properly mount the file

## Actual Result

Stops with error code `5` but there's no output in the terminal.

## System Information

- Elektra Version: master
- Arch Linux & Ubuntu

## Further Log Files and Output
with the `-vd` flags it doesn't print out any error (last log line is: `Now writing the mountpoint configuration` which makes you assume everything worked correctly).

**Comment by markus2330** [comment]
Thank you very much for reporting this problem!

It is very severe and embarrassing problem because as it is a quite usual for beginners to expect that non-root can mount something (unfortunately #1074 is still open this may be the case also for 1.0). I.e. we always wrote in the error message, that you need to be root.

I could reproduce the issue also on Debian Stretch.

@Piankero Can you please fix this regression and test the tools better that they always show errors/warnings.

**Comment by markus2330** [comment]
@darddan (here is the issue)

**Comment by markus2330** [comment]
Works for me with Elektra 0.91.

`kdb umount` however, does not output the `IMPORTANT` disclaimer.

And the error message is quite verbose:
```
 Sorry, 1 warning was issued ;(
        Sorry, module resolver_fm_hpu_b issued the warning C01100:
        Resource: Could not unlink the file '/etc/kdb/elektra.ecf.30403:1574844361.910521.tmp'. Reason: No such file or directory
        Mountpoint: system/elektra
        Configfile: /etc/kdb/elektra.ecf.30403:1574844361.910521.tmp
        At: /home/markus/tmp/elektra-0.9.1/src/plugins/resolver/resolver.c:1154
Sorry, module dump issued the error C01100:
Resource: Insufficient permissions to open configuration file /etc/kdb/elektra.ecf.30403:1574844361.910521.tmp for writing. You might want to retry as root. Reason: Permission denied
Mountpoint: system/elektra
Configfile: /etc/kdb/elektra.ecf.30403:1574844361.910521.tmp
At: /home/markus/tmp/elektra-0.9.1/src/plugins/dump/dump.cpp:287


IMPORTANT: Sorry, I am unable to write your requested mountpoint to system/elektra/mountpoints.
           You can get the problematic file name by reading the elektra system file (kdb file system/elektra/mountpoints).
           Usually you need to be root for this operation (try `sudo !!`).
```
