### ISSUE TITLE
Create standalone documentation for merge strategies

### ISSUE THREAD

**Issue by Chemin1** [ElektraInitiative/libelektra#3203]
Documentation for the merge strategies currently exists in different PRs, for example #3106. As mentioned [here](https://github.com/ElektraInitiative/libelektra/pull/3106#discussion_r342699414) it should be documented as standalone document as the strategies will be used be by various tools.

**Comment by markus2330** [comment]
Thank you for creating this issue!

**Comment by Chemin1** [comment]
Draft in #3216

**Comment by Chemin1** [comment]
Closed because #3216 is merged.

**Comment by markus2330** [comment]
Of course the strategies and their docu can be improved in #3260
