### ISSUE TITLE
Merge tutorial: Use printf instead of echo

### ISSUE THREAD

**Issue by Chemin1** [ElektraInitiative/libelektra#3204]
This is not relevant for `master` yet. In #3106 and dependents like #3141 we have tutorials using echo. While this passes the tests we should replace them with `printf`calls sooner or later as it is more portable.

Thanks to @sanssecours for pointing it out [here](https://github.com/ElektraInitiative/libelektra/pull/3141#discussion_r343043572).

**Comment by markus2330** [comment]
Thank you for creating this reminder!
