### ISSUE TITLE
asciicast on www.libelektra.org

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3207]
Mounting is done without sudo (which worked on the computer because of chmod /etc/kdb). Maybe we can simply add "sudo" to every "kdb mount" to the file ./src/tools/website-frontend/public/vendor/asciinema/asciinema-demo.json?

**Comment by markus2330** [comment]
@Piankero can you the asciicast for the upcoming release? (Tomorrow before noon?)

**Comment by Piankero** [comment]
I was already looking into this, I try to get the asciicast running. I will try to fix it today or tomorrow morning

**Comment by markus2330** [comment]
Thank you very much :sparkling_heart:

**Comment by markus2330** [comment]
We (@Mistreated @mpranj) will verify during the release if the asciicast is fine now and report potential problems to  #2742 (so that the newly recorded one will not have these problems).

**Comment by Piankero** [comment]
Could you verify that sudo is correctly added? If yes we can close this ticket

**Comment by markus2330** [comment]
We will do this before the release.

**Comment by Piankero** [comment]
> We will do this before the release.

The release is done actually

**Comment by markus2330** [comment]
Yes, but after the release is before the release. How is your recording going?

**Comment by Piankero** [comment]
I am working on the tutorial for the errors currently.

So the task for this here is to simply rerecord everything exactly the same so the error message is shown correctly? How does this relate to https://github.com/ElektraInitiative/libelektra/issues/2742 then? Is this here a duplicate?

**Comment by markus2330** [comment]
This task is done (it is about cutting out sudo). #2742 I already gave an answer.
