### ISSUE TITLE
Remove spaces in Jenkins build path

### ISSUE THREAD

**Issue by Chemin1** [ElektraInitiative/libelektra#3210]
Suggestion: We should remove the spaces from our Jenkins build path.

On stdout we see where `command` from POSIX located `kdb`. However, when I I use the result to call it, it is not found due to the space. I can use `command` differently, but such troubles could be easily avoided.

## Real-world example
```sh
=== FAILED return value does not match expected pattern 0
STDERR: /home/jenkins/workspace/libelektra_PR-3209-6HCFMUCA42NSQRXUUFJL2YO3IVQHWSIO2GSOEHE5MLMAJOJKUTVA@2/scripts/kdb/install-config-file: 47: /home/jenkins/workspace/libelektra_PR-3209-6HCFMUCA42NSQRXUUFJL2YO3IVQHWSIO2GSOEHE5MLMAJOJKUTVA@2/scripts/kdb/install-config-file: /home/jenkins/workspace/libelektra_PR-3209-6HCFMUCA42NSQRXUUFJL2YO3IVQHWSIO2GSOEHE5MLMAJOJKUTVA@2/build: not found
ERROR: Could not use kdb ls on system/tests/installing.
STDOUT: /home/jenkins/workspace/libelektra_PR-3209-6HCFMUCA42NSQRXUUFJL2YO3IVQHWSIO2GSOEHE5MLMAJOJKUTVA@2/build directory/bin/kdb
```

## Steps to reproduce the problem
```zsh
mkdir some\ test
cd some\ test 
export PATH="$PATH:$PWD" 
echo "echo hello" > hello.sh
chmod +x hello.sh
command -v hello.sh
#> /home/dominic/some test/hello.sh
$(command -v hello.sh)
#> zsh: no such file or directory: /home/dominic/some
```

**Comment by sanssecours** [comment]
Usually you should be able to use double (or single) quotes to fix this problem. For example, in the code below the shell assumes that you want to call the command some `some` with the argument `test/hello.sh`:

```sh
some test/hello.sh
#STDERR: some test/hello: No such file or directory
```

. To call the command `hello.sh` in the folder `some test` you can use the following command instead:

```sh
"some test/hello.sh"
#> hello
```

.

**Comment by Chemin1** [comment]
Thank you! That's exactly what I did in e6ec60e :)

I think ideally we should have a build path without spaces and other "special" characters and maybe one test specifically for "special" paths. Then we could go even further with this idea and test things like newlines in paths, too.

**Comment by markus2330** [comment]
@Chemin1 thank you for asking the question!

@sanssecours thank you for helping out!

> I think ideally we should have a build path without spaces and other "special" characters and maybe one test specifically for "special" paths.

This is more or less the situation, not every test uses special path. Or did all the tests fail for you?

> Then we could go even further with this idea and test things like newlines in paths, too.

Yes, it is always possible to extend tests. But with spaces in build paths we are already quite advanced, so I do not think we should put even more effort into this.

**Comment by Chemin1** [comment]
> not every test uses special path.

But all tests _are_ in a special path I think.


If you look at the build logs you see this
```sh
-- Build files have been written to: /home/jenkins/workspace/libelektra_PR-3208-7EXBIWZNKPRWP2G5DR73AQBCU35FNWVKNTPBRIJN4ZIAL2T2UT5A/build directory
```
or
```sh
Test project /home/jenkins/workspace/libelektra_PR-3208-7EXBIWZNKPRWP2G5DR73AQBCU35FNWVKNTPBRIJN4ZIAL2T2UT5A/build directory
        Start   1: testtool_automergestrategy
        Start   2: testtool_backend
        Start   3: testtool_backendbuilder
        Start   4: testtool_backendparser
```

**Comment by markus2330** [comment]
We could add an `if` in line 933 to make the space only for one job. But I somehow doubt that this would actually help anyone. If you are aware of these problems, you will immediately see that it is an escaping problem of shell vars. If you do not know of this problem, the name of the build job alone will not be so helpful, as we usually look at the errors and not which job was the problem.

**Comment by Chemin1** [comment]
> the name of the build job alone will not be so helpful

Having one build with special paths or tests would not make the error message go away, no information is lost. One more hint is only added. But at the moment this is low priority anyways.
