### ISSUE TITLE
Merge: Move LibGit to standalone

### ISSUE THREAD

**Issue by dominicjaeger** [ElektraInitiative/libelektra#3217]
Replace all `ifdef LIBGITFOUND` with a new file in `kdbmerge.c` as explained [here](https://github.com/ElektraInitiative/libelektra/pull/3209#discussion_r346691778).

**Comment by markus2330** [comment]
Thank you for creating this issue!

> with a new file in kdbmerge.c

the file(s) should be next to kdbmerge.c
