### ISSUE TITLE
Tutorial: Failing kdbSet

### ISSUE THREAD

**Issue by Chemin1** [ElektraInitiative/libelektra#3218]
As mentioned [here](https://github.com/ElektraInitiative/libelektra/pull/3209#discussion_r346674106) we should have a tutorial about applications where kdbSet failed.

@markus2330 You do not mean using the tool `kdb set`?

**Comment by markus2330** [comment]
No, with the tool `kdb set` you cannot produce such conflicts. (At least not deterministic.)

With `kdb shell` it would be possible but the shell recorder does not support to send input to two different processes at the same time.

So your tutorial will be more focused on the code. After you patched the first tools, you will know what is relevant :smile:
