### ISSUE TITLE
Add make as dependecy for compilation steps

### ISSUE THREAD

**Issue by Chemin1** [ElektraInitiative/libelektra#3225]
## Steps to Reproduce the Problem

Create a Fedora 31 VM. 
Do the installs from COMPILE.md
`
sudo dnf install -y cmake3 git gcc-c++
`

(Note `yum` => `dnf`)

## Expected Result

Compiling works.

## Actual Result

ERROR: Fixing CMake was unable to find a build program corresponding to "Unix Makefiles"

## Solution

`sudo dnf install make`

Update: That means it would be enough to add `make` to the required dependencies in COMPILE.md

## System Information

- Elektra Version: master
- Fedora 31

**Comment by markus2330** [comment]
Thank you for reporting this problem!
