### ISSUE TITLE
Build Agents: add cleanup cronjobs

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3242]
Note to self.

**Comment by mpranj** [comment]
Daily docker system prune and weekly btrfs data rebalance implemented via classic system cronjob on a7 and v2 like below, but at slightly different times:
```
17 3 * * * root docker system prune -f > /dev/null 2>&1
18 4 * * 0 root btrfs balance start -dusage=80 / > /dev/null 2>&1
```

**Comment by markus2330** [comment]
Thank you very much! The docker prune would be good for i7, too.

**Comment by mpranj** [comment]
I did not know I have access on i7?

**Comment by markus2330** [comment]
Now you have :smile:

**Comment by mpranj** [comment]
Cronjob added on `i7` too.
