### ISSUE TITLE
Improve directoryvalue

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3256]
In #3223 I proposed a change to directoryvalue, that would avoid the possible collisions that the base name `__directoryvalue` could cause. The proposed version would probably work fine, but I had a better idea.

Storage plugins have to have some mechanism to store metadata. So why not move the problematic key's value into metadata?

This might seem like we are just moving the problem, but we are not. There is already precedence for metakeys having special semantics. For example, the way `origvalue` works, means that it can never occur in a stored config file.

Now, we could either abuse the `origvalue` name to avoid conflicts, or we could just define that e.g. `dirvalue` must not be used for actual metadata. Then the `directoryvalue` plugin could store the problematic keys' values into `dirvalue` metakeys.

---

I also still think, that `directoryvalue` should be a library not a plugin. Libraries are more flexible. If the library just provides a function `elektraIsDirectoryKeyWithValue (Key * k, KeySet * ks)`, then plugins could do whatever suits them best with these keys. Some plugins might not need to move the value, but instead just need to store it differently.
A library would also avoid the overhead related to creating/reading mountpoints.

**Comment by markus2330** [comment]
I do not see how metadata can help here. The purpose of directoryvalue is circumvent  limitations of configuration file formats, so it needs to encode data within key names and key values, as no other place is available to store the additional information.

The only "problem" directoryvalue has is that it would not work if someone actually would like to store `__directoryvalue`. As this is quite unlikely, I accepted the plugin.

> I also still think, that directoryvalue should be a library not a plugin.

This makes writing of storage plugins even harder as it already is. The advantage of directoryvalue as plugin is that it works completely transparent. The storage plugin gets the guarantee that the directories will not have values and do not need to do anything to handle these situations.

**Comment by markus2330** [comment]
Thinking about it again, I agree more and more with having storage support functionality (like escaping and transforming) as library and not as plugins. As plugins there are too many interactions and as default storage plugin you cannot have additional plugins anyway (without over-complicating the whole plugin system).
