### ISSUE TITLE
Update during jenkins builds proposal.

### ISSUE THREAD

**Issue by Mistreated** [ElektraInitiative/libelektra#3258]
Is it worth considering to set "Cancel build on update" in Jenkins?

An update would cancel the running build and start the updated one.

**Comment by markus2330** [comment]
Thank you for your proposal! I think this is a good idea but isn't this already done in the Jenkinsfile here?

https://github.com/ElektraInitiative/libelektra/blob/c44f308565fd05f65eebfd0bea3b1b1020ece3b0/scripts/jenkins/Jenkinsfile#L1497-L1512

The code is needed to distinguish between master and other PRs.

**Comment by Mistreated** [comment]
Actually yes. I missed this line:

> We never want to abort builds of the master branch
