### ISSUE TITLE
Test: Formatting Check Always Finishes Successfully on Second Invocation

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#3281]
# Steps to Reproduce the Problem

- Add some incorrectly formatted C or C++ code to the repository

# Expected Result

Either Cirrus or Travis should report the incorrectly formatted code. The build jobs that test formatting should finish unsuccessfully.

# Actual Result

All build jobs finish successfully.

# Additional Information

The script `testscr_check_formatting` fails in the CI builds as expected. However, since we use `ctest $ARGS --rerun-failed`:

https://github.com/ElektraInitiative/libelektra/blob/8d9dba123e662a011a69d04ce8535831d39f0543/scripts/dev/run_all.in#L17

the test `testscr_check_formatting` is executed again. This time the test does not fail, since the source was modified:

https://github.com/ElektraInitiative/libelektra/blob/8d9dba123e662a011a69d04ce8535831d39f0543/tests/shell/check_formatting.sh#L14-L17

. 

# Possible Fix

One option to solve this problem would be to `stash` the current changes at the end of the `check_formatting.sh`. I do not know if doing that has other unintended consequences though.

**Comment by markus2330** [comment]
Thank you so much for this detailed issue. I think this is a good first issue?
