### ISSUE TITLE
Release: debian

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3282]
@markus2330 for the debian related release tasks: am I right here that you usually skipt this step? I dont see any commit for unreleased versions.

**Comment by markus2330** [comment]
In the branch "debian" there should be plenty of tags for the released versions. For the unreleased versions there are only commits, no tags.

**Comment by mpranj** [comment]
You're right. Seems like I overlooked something here.

A general note: maybe I overlooked something but not everything works in order of the document `doc/todo/RELEASE`. The correct/working steps are different than the order in the doc. Maybe we should update it a bit (after the release, low priority).

**Comment by markus2330** [comment]
Yes, quite often I changed doc/todo/RELEASE while I was doing the release. Then after the release I pushed the changes to the file.

The ownership of this file is now yours, so feel free to adapt it how you need it.
