### ISSUE TITLE
Release 0.9.1

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3284]
Internal tracking and questions.

**Comment by mpranj** [comment]
@markus2330 do I add notes about KDE in 0.9.1 already or did you mean the next release?

**Comment by markus2330** [comment]
Yes already now. And also next release, I think there is nothing which interests people more than this. You can write about what you heard in the last meeting.

@FelixResch @darddan or do you have time to provide a paragraph about the current status?

**Comment by mpranj** [comment]
@markus2330 I'm having a hard time to reproduce all steps from `doc/todo/RELEASE` without errors on my machine. Especially for the stuff in the releases repo (the artifacts of kdb run_all, strace,...).

Do you want to go through what's really important, or do I just ignore all that and proceed with the essential parts: tag, bump debian package, make source package, publish API/docs and try to get the website working?

If the other artifacts are important it will take a little bit longer.

**Comment by markus2330** [comment]
All these steps (except strace) you mentioned are done on the buildserver anyway, so do not bother too long trying to reproduce it on your machine. Maybe you can take a look in the build logs if they were really executed?

The strace logs I actually never compared with older versions, so it seems like they are not very important :wink:

> bump debian package

Also the Debian packages are optional. You could also do Fedora Packages instead.

Quite nice would be if you do some manual smoke tests with the release. Manually you sometimes see different things. If you verify that  #3197 is gone, it is nearly enough (some get/set and umount would also not harm).

> tag, make source package, publish API/docs and try to get the website working?

Yes, this is what really matters.

**Comment by mpranj** [comment]
Thank you! Then I'll do the essential stuff and ping you when I think it's ready so you can at least glance over it.

**Comment by markus2330** [comment]
Don't worry, if it is not ok, we will simply release 0.9.2.

**Comment by mpranj** [comment]
@markus2330 

Permission to ElektraInitiative/**ftp**.git denied to mpranj.
ERROR: Permission to ElektraInitiative/**doc**.git denied to mpranj.

**Comment by markus2330** [comment]
I added you to be a core member: https://github.com/orgs/ElektraInitiative/teams/core/members
Pushing to ftp and doc should work now, and you can add other members.

**Comment by mpranj** [comment]
Thank you, api docs and tarballs are up. I'm working on the release notes, tag will be pushed soon.

**Comment by markus2330** [comment]
https://doc.libelektra.org/api/current/html/ works for me. I am off for today but it seems like you already finished the most important parts anyway.

**Comment by mpranj** [comment]
Thank you for all the answers!
