### ISSUE TITLE
website deployment

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3289]
- [x]  Website deployment is broken
- [x]  manual deployment makes rss links refer to localhost:9000/
- [x] fix directories where webpage is served from

**Comment by markus2330** [comment]
> @markus2330 side note: www.libelektra on port 80 and 443 serve two completely different directories. I'll probably clean that up too if there was no reason to do that. To me this just complicates deployment.

Yes, please. This was my fault, I forgot to update the apache config at one point.

**Comment by mpranj** [comment]
This basically works now. Do we actually want to auto-publish the website built from master to www.libelektra.org? This is comfortable but could inevitably break the website at some times.

An alternative would be to auto-publish to www-new.libelektra.org and to manually push to the production site on releases.

Both approaches have pros and cons. I'm open to suggestions.

**Comment by markus2330** [comment]
The auto-publishing was used for a very long time and rarely caused troubles. When auto-publishing failed there sometimes was confusion why the latest changes are not reflected in the webpage.

In some point of time, however, most people will use releases and not master anymore. From that moment, it makes more sense if www.libelektra.org reflects released software. If you think this time has already come, then only publish the web page on releases and let us have something like www-new or www-master.

**Comment by mpranj** [comment]
In that case we can publish master until around 1.0, where I would switch to publishing only released versions.
