### ISSUE TITLE
[Website] Validation page issues

### ISSUE THREAD

**Issue by MasterToney** [ElektraInitiative/libelektra#3293]
The tutorial page for the validation has the info header box for author and description not well formatted as well as a big review pending after that.
This is the case on both sites, libelektra.org and on a7.

https://www.libelektra.org/tutorials/validate-configuration#validation
http://a7.libelektra.org/tutorials/validate-configuration

On a first quick look I could not find any other tutorial that have the info header on top so I think we could remove that, as to the review pending I'm not sure if it also should be removed or not.

**Comment by markus2330** [comment]
Yes, I agree, you can remove this header.
