### ISSUE TITLE
[plugin type] not supported as global plugin

### ISSUE THREAD

**Issue by MasterToney** [ElektraInitiative/libelektra#3298]
## Steps to Reproduce the Problem

```sh
sudo kdb global-mount type
#> The command kdb global-mount terminated unsuccessfully with the info:
#> The plugin "type" is not suitable to be mounted as global plugin!
#> Please report the issue at https://issues.libelektra.org/
```

## Expected Result

The plugin type should be mounted globally.

## Actual Result

I got the error as stated above.

## System Information

- Elektra Version: master
-  macOS 10.15.1
- installed via homebrew

Looking at https://www.libelektra.org/plugins/type I do not see anything that would hint that the type plugin is not suitable to be mounted globally.
Also https://www.libelektra.org/manpages/kdb-global-mount#kdb-global-mount-1-globally-mount-plugins does not state any requirement for a plugin to be global mount-able.

**Comment by MasterToney** [comment]
Same behavior with `sudo kdb global-mount validation` so there needs to be some criteria when a plugin can be mounted globally.
Curiously the following happens:
```sh
sudo kdb gmount
# no output so no plugins are globally mounted

sudo kdb gmount check
# no output again

sudo kdb gmount
#> spec
#> spec
```
So `check` is as far as I can tell from `kdb plugin-list` not a name for any plugin but will be interpreted as the `spec` plugin but two times?
From my intuition this should not be happen as calling `sudo gmount spec` twice returns an error the second time `It is not allowed to insert the same plugin (spec#spec) again!` which makes sense to me.

**Comment by markus2330** [comment]
Why do you try to mount them globally? What did you expect?

> what are the criteria for a plugin to be global mountable?

Practically only notification plugins, mmap and spec are really suitable.

> which plugins fulfill these criteria (so we can document this behavior)

That `global` is in the contract.

> what is the check plugin

That is not a real plugin, only a provider like `json`.

**Comment by MasterToney** [comment]
> Why do you try to mount them globally? What did you expect (if it would have been mounted globally)?

I'm trying to get validation to work and my thought was if I mount the plugins that do so globally then all my interactions with `kdb` should be validated.
Also I don't want to simply `mount` a new backend because for that I need to mount it to a file which I want to avoid.

> That `global` is in the contract.
I guess that we could adjust the exception message accordingly to state that and mention it in `global-mount` docs too. Will do so over the weekend.

**Comment by markus2330** [comment]
> Also I don't want to simply mount a new backend because for that I need to mount it to a file which I want to avoid.

It is always mapped to some file (you can check with `kdb file`). You can also mount to the root (/) which should do what you want.

>  I guess that we could adjust the exception message accordingly to state that and mention it in global-mount docs too. Will do so over the weekend.

Thank you. In the mounting tutorial it should be mentioned that there are global mountpoints (only for notifications) and that it is possible to mount to /.
