### ISSUE TITLE
cache: fix tool synopsis

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3301]
Synopsis was not updated, `kdb cache default` is missing here but available in the man page.

https://github.com/ElektraInitiative/libelektra/blob/b04c7f85a902fd247b628d88d752370d33dd034a/src/tools/kdb/cache.hpp#L26-L33

**Comment by markus2330** [comment]
Thank you for reporting and fixing the problem :sparkling_heart:

**Comment by mpranj** [comment]
I only reported it. :smile:

**Comment by markus2330** [comment]
And you assigned yourself :stuck_out_tongue:
