### ISSUE TITLE
coveralls: stopped updating

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3309]
According to https://coveralls.io/github/ElektraInitiative/libelektra the last master build was on 03 Aug 2019.

@sanssecours is this thing mismatching because we now have debian-buster-full and debian-stretch-full?
https://github.com/ElektraInitiative/libelektra/blob/3b00685cc3906d11bf19f3fed476c093e3a08bb8/scripts/jenkins/Jenkinsfile#L921

**Comment by sanssecours** [comment]
> @sanssecours is this thing mismatching because we now have debian-buster-full and debian-stretch-full?

Yes,  I think you are correct. Thanks for the detailed report and the fast fix 💖.
