### ISSUE TITLE
kdb export with `yaml` plugin does not add newline

### ISSUE THREAD

**Issue by Piankero** [ElektraInitiative/libelektra#3311]
## Steps to Reproduce the Problem

I tried to do the asciinema recording with yaml but the missing newline makes it weird

```sh
kdb set user/hello/hello/world "Hello World"
kdb export user/hello yaml
```

## Expected Result

Note that `elektra $` is the user and $ the delimiter (shell configured that way in docker image)
```
elektra $ kdb export user/hello yaml
hello:
  world: Hello World!
elektra $ 
```

## Actual Result

```
elektra $ kdb export user/hello yaml
hello:
  world: Hello Worldelektra $ 
```

## System Information

docker run -it elektra/elektra

**Comment by mpranj** [comment]
Thank you for reporting! I can reproduce it also without the docker image.

@sanssecours can you take a look please?

**Comment by sanssecours** [comment]
> @sanssecours can you take a look please?

Sorry, I do not think I have time for that at the moment.

**Comment by markus2330** [comment]
workaround is something like:

```
echo `kdb export user/hello yaml`
```

**Comment by Piankero** [comment]
Doing this in the asciinema recording would be really weird...

**Comment by sanssecours** [comment]
If you want a quick “workaround”, then just replace the line:

https://github.com/ElektraInitiative/libelektra/blob/3c53b19a51b41e9588284a1943d8c25211748a42/src/plugins/yamlcpp/write.cpp#L536

with the code

```cpp
output << data << endl;
```

.

**Comment by mpranj** [comment]
@sanssecours thank you!

I applied this patch only to the docker image. It's basically only a playground anyway.

Maybe we can fix this properly before the next release.
