### ISSUE TITLE
merge: getConflicts name too general

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3318]
The API getConflicts needs to be renamed to begin with elektraMerge. E.g. elektraMergeGetConflicts.

**Comment by mpranj** [comment]
Is the elektra prefix not "reserved" for internal usage, or is getConflicts only used internally?

**Comment by markus2330** [comment]
The elektra prefix is normal for all the libs except of the core. But also in the core we have quite some public symbols starting with elektra, e.g. for plugin loading (elektraPluginOpen, ...) Adding the elektra prefix to all functions in the core would be nice but it would be at least as much effort as #3115, so way beyond our capacity.

**Comment by markus2330** [comment]
But for the extra libs (like libmerge) we should take care that everything starts with elektra. Thus this issue.

**Comment by Chemin1** [comment]
Makes sense. I'll get to that as soon as I'm not in bed with fever anymore.

**Comment by markus2330** [comment]
@Chemin1 this looks like a very simple task, maybe you have some time for this?

**Comment by atmaxinger** [comment]
I'll rename it to elektraMergeGetConflicts

**Comment by atmaxinger** [comment]
We can close that, it is already done.
