### ISSUE TITLE
list-commands not bold

### ISSUE THREAD

**Issue by Chemin1** [ElektraInitiative/libelektra#3325]
In the [Docker container for running all tests](https://github.com/ElektraInitiative/libelektra/blob/master/doc/tutorials/run_all_tests_with_docker.md).

Elektra compiled from ad0ac3d1689211c1b8656cd838cb4cf2863624ae.
GNOME Terminal 3.28.2.

## Does not work

`doc/help/kdb-list-commands.md` says there should be bold output but either I get an error or no bold output.

<pre>jenkins@0d2b25b79bdb:~/workspace/elektra-build-docker$ kdb -C always list-commands
The command <b>kdb -C</b> is <font color="#CC0000">not known</font>
Usage: kdb &lt;command&gt; [args]

kdb is a program to manage Elektra&apos;s key database.
Please run a command with -H or --help as args to show a help text for
a specific command.

Known commands are:
<b>cache</b>	Enable, disable or clear the cache.
<b>complete</b>	Show suggestions how to complete key names.
<b>convert</b>	Convert configuration.
<b>cp</b>	Copy keys within the key database.
(...)
<b>rm</b>	Remove key(s) from key database.
<b>set</b>	Set the value of an individual key.
<b>sget</b>	Get the value of an individual key within a shell script.
<b>shell</b>	Start a kdb shell.
<b>smount</b>	Mount a new backend by specification. All necessary plugins will be loaded automatically, depending on the metadata.
<b>spec-mount</b>	Mount a new backend by specification. All necessary plugins will be loaded automatically, depending on the metadata.
<b>test</b>	Run key database test suite.
<b>umount</b>	Unmount backend from key database.
jenkins@0d2b25b79bdb:~/workspace/elektra-build-docker$ kdb list-commands -C always
cache
complete
convert
cp
editor
(...)
test
umount
</pre>

**Comment by markus2330** [comment]
Thank you for reporting this bug!

> says there should be bold output

Can you say what you read and what you expected?

I only see one occurrence of "bold" and it is next to the command-line option `-v`. For me the commands are bold if I add this option.

See: `src/tools/kdb/listcommands.cpp`

> kdb -C always list-commands

The command must always be the first after `kdb`. I agree this could be more clear in the `kdb` man page.

**Comment by Chemin1** [comment]
After reading your answer I don't think that this is a bug anymore. I think my problem was that I thought that specifying`-C` (also when default)  would turn the list bold every time. Now it is clear to me, that this is only true if `-v` is specified.

Even though this makes sense to distinguish it from the description coming from `-v`, I think it's also a bit strange that the color changes depending on other options than `-C`.

I rewrote the man page a bit to address for example my problem with the synopsis.

**Comment by markus2330** [comment]
I reopen as it not yet merged. Furthermore the second point "The command must always be the first after kdb." is not yet dealt with.
