### ISSUE TITLE
Python: Upgrade CMake Code for CMake Policy 78

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#3330]
# Steps to Reproduce the Problem

1. Set the new behavior for CMake Policy `0078` in [`src/bindings/swig/python/CMakeLists.txt`](https://github.com/ElektraInitiative/libelektra/blob/master/src/bindings/swig/python/CMakeLists.txt):

   ```cmake
   cmake_policy (SET CMP0078 NEW)
   ````

2. Create the build system:

   ```sh
   cmake -DBINDINGS='python' -Bbuild
   ```

# Expected Result

CMake should be able to create the build system successfully.

# Actual Result

CMake fails and prints the following error message:

```
CMake Error at src/bindings/swig/python/CMakeLists.txt:61 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  _swig-python


CMake Error at src/bindings/swig/python/CMakeLists.txt:79 (install):
  install TARGETS given target "_swig-python" which does not exist.
```

# System Information

- Elektra Version: `master`
- macOS `10.15.1` 
- CMake `3.15.5`

**Comment by markus2330** [comment]
Thank you for reporting this problem!

**Comment by kodebach** [comment]
Semi-related: There are also a few other CMake Policy Updates and Deprecation Warnings that need to be fixed.

A found at least these:

```
CMake Deprecation Warning at CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```

```
CMake Warning (dev) at /usr/share/cmake-3.19/Modules/UseSWIG.cmake:513 (message):
  Policy CMP0086 is not set: UseSWIG honors SWIG_MODULE_NAME via -module
  flag.  Run "cmake --help-policy CMP0086" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
```

**Comment by kodebach** [comment]
I think this issue should be solved by just using `swig-python` instead of `_swig-python` after activating the policy. If I understand the docs for the policy change correctly, we should have never used `_swig-python` directly and instead used a variable generated by the CMake swig module which contained this internal name. With the policy change, the target should use the name that was given to `swig_add_library`, which is `swig-python` in our case.
