### ISSUE TITLE
Augeas: Improve Handling of Large Files

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#3332]
# Description

Currently the Augeas plugin uses the function `ftell` to retrieve the size of a file:

https://github.com/ElektraInitiative/libelektra/blob/9e98a62c395f495d28a019dee9681dcfec2451cd/src/plugins/augeas/augeas.c#L321

. Afterwards the plugin uses `elektraMalloc` to allocate memory for the file content:

https://github.com/ElektraInitiative/libelektra/blob/9e98a62c395f495d28a019dee9681dcfec2451cd/src/plugins/augeas/augeas.c#L326

. The problem with this approach is that the maximum value of the type `long` returned by `ftell` (`LONG_MAX`) might be larger than the maximum possible `size_t` value (`SIZE_MAX`). In this case the plugin code might not store the whole content of the file and hence not work correctly.

For more information about this problem, please take a look [here](https://github.com/ElektraInitiative/libelektra/pull/3328#discussion_r355978633).

**Comment by markus2330** [comment]
Thank you for reporting the potential problem.
