### ISSUE TITLE
Merge: Show conflicting keys

### ISSUE THREAD

**Issue by dominicjaeger** [ElektraInitiative/libelektra#3338]
Mentioned by @markus2330 [here](https://github.com/ElektraInitiative/libelektra/pull/3260#discussion_r355181496).

Currently the merge library counts the number of conflict but does not keep track of which keys produced the conflicts. However, UIs are interested in this information.

The C++ merge tool used an additional KeySet to collect those keys. We could also mark keys using metadata instead. Any other ideas for this?

**Comment by mpranj** [comment]
Thank you for looking into this!

Depending on the original KeySet size it _might_ be cheaper to have the additional KeySet instead of marking them with metadata and then iterating again and collecting the correct Keys. It would depend on the rest of the logic.

**Comment by markus2330** [comment]
Yes, I also think this is up to you. It should be as easy for the client as possible to inform the user about the conflicts. And it should also be hard to use it wrong, so it should be as unlikely as possible that someone confuses conflicts from an earlier merge attempt with the conflicts that occurred by the last invocation.

**Comment by markus2330** [comment]
@Chemin1 it would be good if you could ping issues which get stale and are not yet obsolete. Hope to see a PR from you soon :sparkling_heart:
