### ISSUE TITLE
[WIP] opts: Specification for sub-commands

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3341]
**This proposal is still a work in progress. The specification is not final, but comments are welcome**

Currently `libopts` can be used to implement an application with multiple sub-commands (e.g. `kdb`), but it is a bit tedious and has to be done manually. This is a proposal for a specification that would allow `elektraGetOpts` to parse sub-commands.

The main idea is the following:

_If a key is marked with the `opt/command` (name not final) metakey, `elektraGetOpts` will **not** immediately process keys below it._

The keys are only processed, when the `elektraGetOpts` determines that the command was actually invoked. The example below illustrates this main rule.

When `elektraGetOpts` processes such a command-key `ck` one of three things can happen:
- A sub-command of the `ck` was invoked. The value of `ck` will be `/[subcmd]`, where `subcmd` is the basename of the sub-command's command-key.
- `ck` was invoked but none of its sub-commands (this would be `get` in `kdb get`). We call it the terminal sub-command. Here `ck`'s value will simply be `/`.
- `ck` was not invoked at all (e.g. the `set` command-key when `kdb get` is called). `ck` will be set to an empty string.

Here is an example specification:

```ini
[kdb]
opt/command = kdb

[kdb/printversion]
type = boolean
opt = v
opt/long = version
opt/arg = none

[kdb/get]
opt/command = get

[kdb/get/verbose]
type = boolean
opt = v
opt/long = verbose
opt/arg = none

[kdb/get/keyname]
type = string
args = single

[kdb/set]
opt/command = get

[kdb/set/verbose]
type = boolean
opt = v
opt/long = verbose
opt/arg = none
```

To illustrate the behaviour we will look at a few sample invocations:

- `kdb -v`: Keys below `kdb/get` and `kdb/set` are not touched. The result is:
  - `kdb = /`
  - `kdb/printversion = 1`
  - `kdb/get = ""`
  - `kdb/set = ""`
- `kdb get -v name`: Keys below `kdb/set` are not touched. The result is:
  - `kdb = /get`
  - `kdb/get = /`
  - `kdb/get/verbose = 1`
  - `kdb/get/keyname = name`
  - `kdb/set = ""`
- `kdb -v set -v`: Keys below `kdb/get` are not touched. The result is:
  - `kdb = /set`
  - `kdb/printversion = 1`
  - `kdb/set = /`
  - `kdb/set/verbose = 1`
  - `kdb/get = ""`

---

Additional rules:

- Sub-command processing only happens when the parent key has the `opt/command` metakey.
- Sub-command processing implies the `posixly` version of `elektraGetOpts`, i.e. **all** options must be specified before non-options.
- If sub-command processing is not active, **no key**  below the parent (no matter how deep) may have the `opt/command` metakey.
- Sub-command may be arbitrarily deep below there parent command. They don't have to be directly below. e.g. `kdb/commands/get` can be a sub-command of `kdb` (if `kdb/commands` is not a command itself).
- Below any given key `k` (no matter how deep) there may only be either keys with `args` or with `opt/command` metadata never both. Because of the main rule above, this doesn't apply for keys below sub-commands. e.g. in the example above `kdb/get/keyname` is allowed, because `kdb/get` has no sub-commands, but a similar `kdb/keyname` would not be allowed.

**Comment by kodebach** [comment]
@markus2330 please take a look.

**Comment by kodebach** [comment]
I also had an idea for integrating this with the code-generation. Basically, we would generate a header with a function for each of the terminal sub-commands (function names would be given in the specification). The implementation of these functions would be supplied by the user. Another generated function `int runCommand (Elektra * elektra)` that invokes the correct command-function would then be used.

**Comment by mpranj** [comment]
I won't interfere with the design decisions, but it would be great to have this and thank you for working on it. The main idea sounds good to me.

**Comment by markus2330** [comment]
@mpranj if you can and want to contribute something to the discussion, please do it.

I hope I will have tomorrow time to look at it.

@ulrikeschaefer said she is already working on the topic again.

**Comment by markus2330** [comment]
@kodebach in general, I think such discussions are easier as PR, adding a file in design decisions then it is possible to comment on individual lines. And after we agree on something, we also have it permanently documented.

**Comment by markus2330** [comment]
@kodebach thank you so much for the proposal! I really like it!

> This is a proposal for a specification that would allow elektraGetOpts to parse sub-commands.

We also want the same specification to be used for auto-completion.

> If a key is marked with the opt/command (name not final) metakey, elektraGetOpts will not immediately process keys below it.

Do I understand correctly: Such keys will actually not be options (neither in KDB nor for elektraGetOpts). Maybe the metakey name `command` (or the already proposed `application/name`) is better, as the effects are not limited to `opt`.

> A sub-command of the ck was invoked. The value of ck will be /[subcmd], where subcmd is the basename of the sub-command's command-key.

Do I understand correctly: The slash means, it is the command itself, emptiness means the command was not invoked. Why do we need to add command-keys that were not invoked at all? (Then we could also leave away the leading slash?)

> Additional rules:

Some specification checker would be nice, it is getting more and more difficult to write correct specifications. Maybe @ulrikeschaefer can write a small tool that checks if the specification is consistent?
