### ISSUE TITLE
FreeBSD 12.1: ccode / tcl shelltests fail

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3353]
With cirrus FreeBSD images 12.1 updated from 12.0 the clang version notably changed from 6.0.1 to 8.0.1. For some reason boost is now found and the `tcl` plugin is automatically included, resulting in test failures.

## Expected Result

Tests succeed.

## Actual Result

The following tests FAILED:
	 38 - testshell_markdown_ccode (Failed)
	108 - testshell_markdown_tcl (Failed)

## System Information

- Elektra Version: master
- FreeBSD 12.1 on cirrus

## Further Log Files and Output
Full log:
[tests.log](https://github.com/ElektraInitiative/libelektra/files/4249633/tests.log)

**Comment by mpranj** [comment]
@sanssecours thank you so much for working on this!  When you make the PR, please enable tcl in cirrus again.

**Comment by markus2330** [comment]
Thank you for fixing the build server. I am okay with the tcl tests not running, tcl is a low-priority plugin. We were already discussing if we might remove it, together with xmltool. But we thought maybe we keep it, as xmltool could be useful for migration from ancient Elektra versions and tcl is a quite small plugin.
