### ISSUE TITLE
elektrad: improve management of kdb handles

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3360]
KDB handles are currently held by `elektrad` for 60 minutes of inactivity before being closed.

Depending on the scenario this might have to be improved. One possibility is having a `MAX_SESSIONS` limit and removing the oldest sessions to mitigate e.g. denial of service. Other suggestions are welcome.

**Comment by markus2330** [comment]
elektrad is not designed to be directly used from the outside world but instead being proxied by webd. And webd is expected to be protected by some authentication, again done by a proxy. Maybe this should be clarified in the docu.

So DOS should be no problem. @mpranj  Or where you also thinking of other scenarios?

**Comment by mpranj** [comment]
> And webd is expected to be protected by some authentication

I was missing this premise. Authentication in front of the webd would mitigate the problem regarding public access.  We can close it or leave it open as a docu issue.

**Comment by markus2330** [comment]
If this information cannot be found somewhere we have a documentation problem.

@raphi011 can you take this issue over and describe how a full elektrad/webd setup would look like?
