### ISSUE TITLE
[FLOSS H1] CSV Storage: Plugin Should Add Array Metadata

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#3369]
# Problem Description

Currently the [`csvstorage` plugin](https://www.libelektra.org/plugins/csvstorage) does not add the [`array` meta key](https://github.com/ElektraInitiative/libelektra/blob/master/doc/tutorials/arrays.md) to array parents. As a consequence of this behavior other plugins, such as [Directory Value](https://www.libelektra.org/plugins/directoryvalue), [will not work as expected](https://github.com/ElektraInitiative/libelektra/pull/3357#discussion_r386127533). 

# Steps to Reproduce the Problem

```sh
kdb mount config.csv user:/tests/csvstorage csvstorage
printf 'one,two,three\nfour,five,six\n' > `kdb file user:/tests/csvstorage`
kdb ls user:/tests/csvstorage
#> user/tests/csvstorage/#0
#> user/tests/csvstorage/#0/#0
#> user/tests/csvstorage/#0/#1
#> user/tests/csvstorage/#0/#2
#> user/tests/csvstorage/#1
#> user/tests/csvstorage/#1/#0
#> user/tests/csvstorage/#1/#1
#> user/tests/csvstorage/#1/#2

# The plugin should add the array meta key to array parents, but does not.
kdb meta-get user:/tests/csvstorage/#0 array
# RET: 2
```

# Expected Result

The command `meta-get` should print the value `#2` (the [index of the last array element](https://github.com/ElektraInitiative/libelektra/blob/master/doc/decisions/array.md#decision)) and finish successfully (return code `0`).

# Actual Result

The command `meta-get` prints nothing and returns the unsuccessfully (return code `2`).

**Comment by markus2330** [comment]
Thank you very much for creating this issue! Is this a good first issue?

**Comment by sanssecours** [comment]
> Is this a good first issue?

I am not sure. Ideally you only have to add one `keySetMeta` statement to the code. However, you have to find the ideal position for that statement first.

**Comment by muskater** [comment]
When trying to reproduce the bug I had to slightly change the steps and got a similar result.
The steps I used:

```
kdb mount config.csv user:/tests/csvstorage csvstorage
printf 'one,two,three\nfour,five,six\n' > `kdb file user:/tests/csvstorage`
kdb ls user:/tests/csvstorage
kdb meta-get user:/tests/csvstorage/#0 array
```
The difference is that I had to write `user:/` instead of `user/`

Also I get the return value `1`, not `2`.
