### ISSUE TITLE
Update used compiler list

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3384]
The list of used compilers in `doc/COMPILE.md` is outdated. The list should be updated to reflect the current state of compilers used and point to our CI (travis, cirrus, jenkins), where the list of compilers can be seen.

**Comment by markus2330** [comment]
Thank you for reporting!

I would suggest to remove all compilers related to CI from doc/COMPILE.md; so to only list the ones you use manually; and instead link from the table to our CI systems (ideally some place where it can be seen which compilers they use).

**Comment by mpranj** [comment]
I updated it for this release.

**Comment by markus2330** [comment]
Thank you very much! :sparkling_heart:
