### ISSUE TITLE
Crypto: drop support for Botan and OpenSSL variants

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#3391]
The crypto plugin(s) consist(s) in variants with the following crypto libraries in use:

- libgcrypt,
- OpenSSL, and
- Botan.

The variants have been introduced for academic research, which was finished in 2018. There is no other benefit of supporting several crypto libraries.

On the downside the maintenance effort of supporting the libraries mentioned above is increasing (e.g. #3385 ).

I think **libgcrypt** is the crypto library that best fits our needs (and has the nicest code-base). Also I do not expect the crypto library to cause increased maintenance effort.

Therefore I propose to drop the support of:

- OpenSSL, and
- Botan

and remove their corresponding compilation variants from the crypto plugin.

**Comment by markus2330** [comment]
I agree with the proposal!

**Comment by petermax2** [comment]
The implementation of this issue closes #3385 .

**Comment by petermax2** [comment]
I'll start with the implementation so we get a feeling if the clean-up improves the situation.

Please feel free to discuss the proposal above in the meantime.

**Comment by markus2330** [comment]
Btw. there was also a maintenance issue with OpenSSL https://github.com/openwrt/packages/pull/8998

So keeping only libgcrypt seems to be the perfect choice from maintenance point of view.

@haraldg: is this also ok for you? It seems like the openwrt package currently only uses OpenSSL?

Is it possible to build curl also with gcrypt so that the whole Elektra depends only on libgcrypt (and not OpenSSL)?

**Comment by mpranj** [comment]
If there are no major functional differences I **fully agree** with maintaining only the best plugin variant. It's also great to drop some dependencies. I think you are in the best position to make the decision which plugin to keep @petermax2, but libgcrypt seems to be a good decision according to your work.

**Comment by petermax2** [comment]
> Is it possible to build curl also with gcrypt so that the whole Elektra depends only on libgcrypt (and not OpenSSL)?

Libgcrypt does not provide any TLS/SSL functions. I'm afraid you won't be able to build curl with gcrypt.
