### ISSUE TITLE
remove login from www.libelektra.org

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3396]
as snippet sharing is not used anymore

**Comment by markus2330** [comment]
Wow, cool that you resolved this so fast! The website now looks much cleaner!

@d3nwp continuation of this work is highly appreciated :wink:

**Comment by mpranj** [comment]
> continuation of this work is highly appreciated

I agree! Improving the website is always a good way to improve the experience for users. I expect most users to read the docs from there and not from the folder structure of our git repo.
