### ISSUE TITLE
qt-gui: some bugs when building against Qt5.5

### ISSUE THREAD

**Issue by 0003088** [ElektraInitiative/libelektra#341]
When deleting a key in the keyAreaWindow and then closing the gui, the app will crash. The problem starts in TreeViewModel::data line 58 and ends in qSharedPointer_impl.h line 189 (void execute() { delete ptr; }). It seems that the same pointer is deleted more than once.

Sometimes an error will occur: QML ListView: Binding loop detected for property "model". The debugger marks the line 391 in file BasicTableView.qml as the culprit.

**Comment by 0003088** [comment]
I fixed the most annoying problem, but these two not that severe issues are still unresolved.

**Comment by markus2330** [comment]
Are there still open problems?

**Comment by markus2330** [comment]
Please reopen if there are still problems.
