### ISSUE TITLE
use same targets for tests on all CIs

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3414]
> afaik our jenkins does not re-run tests as it does not use the run_all script

shouldn't we make this consistent across our continuous integration?

- [ ] jenkins: calls ctest itself, excludes some test cases

**Comment by mpranj** [comment]
Thank you for reporting! I would guess one reason to call it manually was to exclude some tests only on specific (problematic) test systems.

I agree that more consistency would be beneficial. During my last PRs I noticed the inconsistency causes further problems. The exclusion of some tests via e.g. Jenkinsfile may still leave broken default builds on developer systems.

Still, it might not pay off to invest too much time for each edge  case, especially if it only occurs on *our* build servers.

**Comment by markus2330** [comment]
> I would guess one reason to call it manually was to exclude some tests only on specific (problematic) test systems.

Yes, probably. But the reason does not exist anymore and thus the exclusions are not needed: the 3 excluded tests work (with rerunning of failed tests).

> Still, it might not pay off to invest too much time for each edge case, especially if it only occurs on our build servers.

I agree we should be careful of not using too much time for this.
