### ISSUE TITLE
cirrus: Timed out!

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3422]
I am increasingly seeing `Timed out!` errors on cirrus. The errors occur sporadically and are usually fixed by re-running.

The timeout can be increased but it is most definitely not the cause of the problems, as we are not even close to the default 60 minute timeout.

The problem seems similar to travis-ci where it says "no output received for the last x minutes, aborting". The errors quite frequently cause build failures. Ideas how to improve this are welcome.

**Comment by markus2330** [comment]
I cannot really help (as I do not know the reason) but nevertheless one idea: You could try to make more verbose compilation to exclude the "no output received for the last x minutes, aborting" possibility. 

Additionally or alternatively we can reduce what cirrus does, especially the parts that are identical to what Jenkins is already doing.

**Comment by mpranj** [comment]
It often simply hangs during cmake afair, so I would not assume that it's during some truly longer operation. It's still worth a shot to be more verbose.

**Comment by markus2330** [comment]
Please reopen if it occurs again.
