### ISSUE TITLE
debian buster builds broken

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3435]
## Steps to Reproduce the Problem

Install Debian buster, add one of these lines (lead to same result) in /etc/apt/sources.list

```
deb [trusted=yes] https://debian-stretch-repo.libelektra.org/ stretch main
deb [trusted=yes] https://debian-buster-repo.libelektra.org/ buster main
```

run:

```sh
apt-get update
apt-get install libelektra4
```

## Expected Result

That libelektra gets installed.

## Actual Result

```
The following packages have unmet dependencies:
 libelektra4 : Depends: libc6 (>= 2.27) but 2.24-11+deb9u4 is to be installed
E: Unable to correct problems, you have held broken packages
```

## System Information

- Elektra Version: master

**Comment by mpranj** [comment]
Thank you for testing and reporting!

**Comment by Mistreated** [comment]
Where are these packages hosted?

**Comment by Mistreated** [comment]
`deb [trusted=yes] https://debian-buster-repo.libelektra.org/ buster main`

After I run this with `apt-get update` I get:

`W: Failed to fetch https://debian-buster-repo.libelektra.org/dists/buster/InRelease  Could not connect to debian-buster-repo.libelektra.org:443 (88.198.134.179). - connect (111: Connection refused)
`

**Comment by markus2330** [comment]
It is the packages we host, a7 or community server.

I also got failed connection, seems debian-buster-repo.libelektra.org is now down?

**Comment by mpranj** [comment]
Come to think of it, did the buster repo ever exist? We had a stretch repo and @Mistreated created the ubuntu bionic repo. I think we never had a buster repo and the A record is pointing to an IP which we don't own.

**Comment by markus2330** [comment]
The current Jenkinsfile pretends it builds buster images:

https://github.com/ElektraInitiative/libelektra/blob/9cd0170f2630631696e711a5a1f08c553ce010e6/scripts/jenkins/Jenkinsfile#L1079

**Comment by mpranj** [comment]
In that case I think we publish buster packages to the stretch repo.

**Comment by markus2330** [comment]
I updated the DNS record of debian-buster-repo.libelektra.org, both now point to 128.130.173.73. Now the situation is like:

- debian-buster-repo.libelektra.org leads to: │W: Herunterladen von https://debian-buster-repo.libelektra.org/dists/buster/main/binary-amd64/Packages fehlgeschlagen: Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification. [IP: 128.130.173.73 443]
- debian-stretch-repo.libelektra.org has libelektra4 version 0.9.1-1.1761 and 0.9.1-2 build for libc6 (>= 2.27), that means, as also @mpranj suggested, probably buster?

I think we do not need to solve the "stretch" problem, let us simply remove this repo and instead fix the certificate of debian-buster-repo.libelektra.org

**Comment by mpranj** [comment]
I've created the apache config and tried to acquire a letsencrypt cert, but the old DNS is still cached. Will try again later.

**Comment by mpranj** [comment]
The stretch repo is now migrated to buster. If we intend to drop stretch support we should remove the obsolete A record.

Unfortunately master builds are broken so no packages can be built.

**Comment by markus2330** [comment]
doc/INSTALL.md also still mentions debian-stretch-repo

**Comment by mpranj** [comment]
Docs are updated and automated publishing of master packages should now work. Can you check whether the packages from the repo work now?

**Comment by markus2330** [comment]
For some reason I have 0.9.1-2 installed, which is preferred to 0.9.1-1.1861, which is probably the new one from the buildserver? Can we pump the number or do I need to downgrade? Something like `dch --newversion 0.9.1-2 "Bump version."` should be enough.

**Comment by mpranj** [comment]
Thank you for testing again. Yes you can bump the version number.

**Comment by mpranj** [comment]
Thank you for bumping the version. I triggered a rebuild of master to get new packages and it seems to work now. I tested the packages from our repo using a clean debian buster docker image.

**Comment by markus2330** [comment]
Yes, works perfectly, thanks for triggering! I upgraded now to 0.9.1-2.1881 :fireworks:

**Comment by mpranj** [comment]
Afaik we fixed everything mentioned here. Please reopen if I am mistaken or the problem reoccurs.

**Comment by markus2330** [comment]
Thank you! I am already running with Elektra 0.9.2 on Buster! Everything is working flawlessly :sparkle:
