### ISSUE TITLE
remove "Convert snippet" button

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3440]
The website-backend can not be [built any more](https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/master/183/pipeline), which also causes failed master builds.

Afaik this only serves the snippet sharing service which has not been working for quite some time. Should we simply disable the builds? This takes up considerable build agent cycles and currently serves no purpose.

**Comment by markus2330** [comment]
It seems like only the download fails (or is incomplete). Strange, for me the same command succeeds.

The proper fix would be to remove src/tools/website-backend/ and then remove the login part in the frontend (and other parts that interact with the backend).

But as quick fix for master, simply taking out the backend build from the Jenkinsfile might be the fastest way.

**Comment by mpranj** [comment]
Yes but it makes no sense to fix the Dockerfile if it will never be needed again. Or are there plans to work on the service again?

**Comment by markus2330** [comment]
No, only plans to remove the backend to simplify the website. Unfortunately, nobody works on this.

**Comment by mpranj** [comment]
Ok, I will quickly disable the broken build so master builds are green. We can clean up the rest later.

**Comment by mpranj** [comment]
Disabling the broken build made Jenkins builds green again.

The proper cleanup from the website frontend still needs to be done.

**Comment by markus2330** [comment]
Thank you for fixing the CI!

I think we actually only need to remove the "Convert snippet" button, as it immediately brings an error and is very visible.

Because nobody tried to sign up in the last years, I do not think that too many people will try to do the registration now.

@d3nwp can you maybe take over this issue and remove the "Convert snippet" button?
