### ISSUE TITLE
CMakeCache searched wrongly

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#345]
`CMakeCache.txt` is only searched in `bin` folder.

`fopen Error: file /home/markus/Projekte/Elektra/build/bin/CMakeCache.txt not found`

**Comment by KurtMi** [comment]
what distribution are you using?

**Comment by markus2330** [comment]
Its the same as build server: debian jessie

Can you please document the logic how CMakeCache.txt is searched for. In manual invocations there is some "strange" behavior:
```
cd ~build
bin/markdownlinkconverter ~e/README.md
fopen Error: file bin/markdownlinkconverterCMakeCache.txt not found
./markdownlinkconverter ~e/README.md
fopen Error: file ./markdownlinkconverterCMakeCache.txt not found
```
why not use the current working directory (so simply fopen "CMakeCache.txt")? What is the rationale of the concatination of executablename and CMAKE_CACHE_FILENAME?

Please also give one example (in the README) of how to execute the tool manually.

**Comment by KurtMi** [comment]
The markdown link converter was not designed for manual invocations.
I will have a look at this, asap.

**Comment by markus2330** [comment]
I could not find a way to debug doxygen's filters? Is there any reason not to support manual invocation?

**Comment by KurtMi** [comment]
I debugged it via printf in the html output.
The markdown link converter (mlc) needs the path of the markdown file in the elektra project folder (called here intern path), to convert relative links.

Example:
...elektra/doc/CODING.md has the following content:
...
[Design document](DESIGN.md)
...

so the mlc needs to know the intern path, in this example doc/CODING.md. To convert "DESIGN.md" to "doc_DESIGN_md".

Since doxygen calls the input filter always with an absolute path, finding the "intern path" is easy. But if the mlc will be called with relative paths there is some logic needed to determine the intern path.

**Comment by markus2330** [comment]
Ok, got it working now (for manual invocation). Just write in the README.md that full path must be given: `~build/bin/markdownlinkconverter ~e/README.md` works fine.

Btw. what is about the ```bash, does Doxygen knows these github specific markdown addons?

**Comment by markus2330** [comment]
strangely, in my installation the executablename is `/home/markus/Projekte/Elektra/build/bin/`, thus the `fopen Error: file /home/markus/Projekte/Elektra/build/bin/CMakeCache.txt not found`.

Seems to be that argv[0] is not very portable when `popen` is used.

**Comment by markus2330** [comment]
Btw. `getcwd` is /home/markus/Projekte/Elektra/build/doc and you can easily influence it with `add_custom_command`.

**Comment by KurtMi** [comment]
> Btw. what is about the ```bash, does Doxygen knows these github specific markdown addons?

I think not, in the documentation of doxygen is nothing mentioned.
(https://www.stack.nl/~dimitri/doxygen/manual/markdown.html#markdown_extra)

> Seems to be that argv[0] is not very portable when popen is used.

The usage of argv[0] will be removed and the CMakeCache.txt will be assumed in the current working directory, additionally there could be a second parameter for the CMakeCache.txt path.

**Comment by markus2330** [comment]
As mentioned already, on my system `getcwd` would not contain CMakeCache.txt unless you pass the proper WORKING_DIRECTORY to add_custom_command

**Comment by KurtMi** [comment]
> Btw. what is about the ```bash, does Doxygen knows these github specific markdown addons?

doxygen supports this, but only in version 1.8.10

**Comment by markus2330** [comment]
Ok, perfect, then we can allow to use this feature in the guidelines.
