### ISSUE TITLE
Travis builds broken

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3463]
## Steps to Reproduce the Problem

Issue a CI build.

## Expected Result

Success for #3462

## Actual Result

```
$ cmake ${CMAKE_OPT[@]}
901CMake Error at /usr/local/Cellar/cmake/3.17.2/share/cmake/Modules/CMakeDetermineCCompiler.cmake:49 (message):
902  Could not find compiler set in environment variable CC:
903
904  gcc-9.
905Call Stack (most recent call first):
906  CMakeLists.txt:23 (project)
```

https://travis-ci.org/github/ElektraInitiative/libelektra/jobs/712141684

## System Information

- Elektra Version: master

**Comment by mpranj** [comment]
Thank you for reporting this. Should be resolved quickly if everything goes well.
