### ISSUE TITLE
website-frontend: all links do not work

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3467]
## Steps to Reproduce the Problem

```sh
~e/scripts/dev/configure-debian -DCMAKE_INSTALL_PREFIX=/srv -DTOOLS="ALL;website frontend" ~e
make -j 5 install
/srv/lib/elektra/tool_exec/mount-website-frontend-config
/srv/lib/elektra/tool_exec/run-website-frontend
#> Running "connect:server" (connect) task
#> Waiting forever...
#> Started connect web server on http://localhost:9000
```

## Expected Result

That I can visit http://localhost:9000 and see something like https://www.libelektra.org

## Actual Result

For every `<page>`, I get an error `Cannot GET /<page>`, the html source for root is:

```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /</pre>
</body>
</html>

```

## System Information

- Elektra Version: master
- npm --version: 5.8.0

**Comment by markus2330** [comment]
Upgrading to npm 6.14.6 (in backports.org) resolved the issue.

**Comment by markus2330** [comment]
Closed too early, while the main page shows now properly a different problem occurred: clicking on the links does not follow links.

I also tried installing nodejs 14 as described in https://github.com/nodesource/distributions/blob/master/README.md
```
curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
sudo apt-get install -y nodejs
```

and still clicking on the links does not follow links. When directly entering a link in the URL, e.g. `http://localhost:9000/libraries/` only a white page is shown.

When completely removing /srv and reinstalling again, I get the initial error `Cannot GET /<page>`, so all these problems seem to be unrelated to the npm/nodejs version.

Instead above error seems to be fixable with `kdb set system/sw/elektra/websitefrontend/#0/current/website/content_root /` and then installing Elektra again. But I do not know about the second issue, i.e., links/buttons without reaction.

@Namoshek do you maybe have an idea what I did wrong here?

Is it possible that the non-availability of the backend causes this problem (I do not have the deps for the backend installed here).

**Comment by mpranj** [comment]
> Is it possible that the non-availability of the backend causes this problem (I do not have the deps for the backend installed here).

Building and deploying the website works without the backend. We have not been building the backend for a while at all.

Maybe there is a problem with the run command which we are not using at all. The script uses `grunt server` and grunt even reports some [problems](https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/master/214/pipeline/2002) when installing in the frontend docker image:

```
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! website-frontend@1.0.0 postinstall: `./node_modules/grunt-cli/bin/grunt install`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the website-frontend@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-03T10_25_45_178Z-debug.log
```

**Comment by Namoshek** [comment]
> @Namoshek do you maybe have an idea what I did wrong here?

I can only guess, but I think that surfing to full URLs doesn't work with the built-in webserver of gruntjs because apache/nginx is doing the required rewrites in production (before they hit said webserver). That doesn't mean it is not working as intended though, it's just not the same setup locally as in production.

From what I can see in the configuration file, grunt starts a webserver on port 9000. Maybe you forgot about the port in the URL or the port is not written into links properly?

**Comment by markus2330** [comment]
> I can only guess, but I think that surfing to full URLs doesn't work with the built-in webserver

Thank you both for your replies! Probably it is better if we avoid using the built-in webserver in the future?

Is it somehow possible to show the static pages without any webserver?

When I visit `file:///srv/share/elektra/tool_data/website-frontend/public/` I only get a directory listing.

> From what I can see in the configuration file, grunt starts a webserver on port 9000. Maybe you forgot about the port in the URL or the port is not written into links properly?

The URL looks correct to me (e.g. http://localhost:9000/plugins/yajl) but only a white page is shown. I am also quite sure it worked that way some time ago.

>  Building and deploying the website works without the backend. We have not been building the backend for a while at all.

Good to know, so then this is not the problem. We should remove website-backend and rename website-frontend. I updated #2987

> Maybe there is a problem with the run command which we are not using at all.

Maybe we should stop recommending this way and remove this script. Unfortunately, `cd /srv/share/elektra/tool_data/website-frontend && ./node_modules/grunt-cli/bin/grunt full` also fails without `--force`:

```
Warning: connect ECONNREFUSED 127.0.0.1:8080 Use --force to continue.

Aborted due to warnings.
```

This warning we should also get rid of. @Namoshek do you maybe have some idea how to do that?

**Comment by markus2330** [comment]
I have the same problem (not working links) also when the pages are delivered via apache after a `grunt full --force`. (`ln -s /srv/share/elektra/tool_data/website-frontend/public/ /var/www/html`)

So the problem seems to be unrelated to the internal webserver of grunt.

**Comment by Namoshek** [comment]
> Is it somehow possible to show the static pages without any webserver?

Web browsers typically do not allow scripts to be run from local files, which is essential for a SPA though. So it simply won't work.

> We should remove website-backend and rename website-frontend. I updated #2987

When looking through the cmake script, I noticed some variables were not renamed the last time the tool was renamed. Just for consideration, you may want to have a look at them this time.

> This warning we should also get rid of. @Namoshek do you maybe have some idea how to do that?

Just remove the `create-website-sitemap` script from the `Gruntfile.js` (especially in the task registration on the bottom).

> So the problem seems to be unrelated to the internal webserver of grunt.

Interesting. Can you give me a directory listing of the folder you tried to publish using apache/grunt?

**Comment by markus2330** [comment]
> When looking through the cmake script, I noticed some variables were not renamed the last time the tool was renamed. Just for consideration, you may want to have a look at them this time.

Which CMake script? From the frontend?

>  Just remove the create-website-sitemap script from the Gruntfile.js (especially in the task registration on the bottom).

Thank you, done in 481817032db0b584d46b90597a45491d5c687805

>    Interesting. Can you give me a directory listing of the folder you tried to publish using apache/grunt?

```
/srv/lib/elektra/tool_exec/mount-website-config
/srv/lib/elektra/tool_exec/build-website
ls /srv/share/elektra/tool_data/website/public                                                                                                                                                                                       
#> assets  index.html  news  pages  templates  vendor  website
```

**Comment by Namoshek** [comment]
> Which CMake script? From the frontend?

Yes, this one here:
https://github.com/ElektraInitiative/libelektra/blob/399856a673b25858e02b117f5787fb902e6485ad/src/tools/website-frontend/CMakeLists.txt#L18

But be careful, the variable is used in other files of the frontend as well.

---

> ```
> /srv/lib/elektra/tool_exec/mount-website-config
> /srv/lib/elektra/tool_exec/build-website
> ls /srv/share/elektra/tool_data/website/public                                                                                                                                                                                       
> #> assets  index.html  news  pages  templates  vendor  website
> ```

I've installed it in a different path (using Debian Buster in WSL 2), but when I use the built-in PHP webserver to test it, it works perfectly fine for me.
```sh
$> cd /usr/local/share/elektra/tool_data/website-frontend/public
$> php -S localhost:9000
```
Opening `http://localhost:9000` in the browser yields the expected home page with working internal and external links. Entering `http://localhost:9000/something/not/existing` will redirect me to the `/error/404` page of the SPA and entering `http://localhost:9000/news/0.8.17-release` yields a 404 error of the webserver, but that must have to do with the routing I guess (as explained earlier).

**Comment by markus2330** [comment]
Thank you very much for testing! So it is some local problem here. `php -S localhost:9000` also showed the same problem but gives at least some useful hint:

```
[Sun Aug  9 19:31:51 2020] [::1]:36940 [200]: /
[Sun Aug  9 19:31:51 2020] [::1]:36942 [200]: /vendor/docsearch.min.js
[Sun Aug  9 19:31:51 2020] [::1]:36944 [200]: /vendor/docsearch.min.css
[Sun Aug  9 19:31:51 2020] [::1]:36946 [200]: /vendor/pace.min.css
[Sun Aug  9 19:31:51 2020] [::1]:36948 [200]: /vendor/pace.min.js
[Sun Aug  9 19:31:51 2020] [::1]:36950 [200]: /assets/skin/default/css/theme.min.css
[Sun Aug  9 19:31:51 2020] [::1]:36952 [200]: /assets/skin/vendor.css
[Sun Aug  9 19:31:51 2020] [::1]:36954 [200]: /vendor/asciinema/asciinema-player.css
[Sun Aug  9 19:31:51 2020] [::1]:36956 [200]: /vendor/asciinema/asciinema-player.js
[Sun Aug  9 19:31:51 2020] [::1]:36958 [200]: /assets/js/application.js
[Sun Aug  9 19:31:52 2020] [::1]:36960 [200]: /assets/img/logo.ico
[Sun Aug  9 19:31:52 2020] [::1]:36962 [200]: /assets/translations/en.json
[Sun Aug  9 19:31:52 2020] [::1]:36964 [200]: /pages/main/template.html
[Sun Aug  9 19:31:52 2020] [::1]:36966 [200]: /pages/main/website/home.html
[Sun Aug  9 19:31:52 2020] [::1]:36968 [200]: /assets/img/logo.svg
[Sun Aug  9 19:31:52 2020] [::1]:36970 [200]: /website/img/qtgui.png
[Sun Aug  9 19:31:52 2020] [::1]:36972 [200]: /website/img/oyranos-km-logo.svg
[Sun Aug  9 19:31:52 2020] [::1]:36974 [200]: /website/img/oyranos-kolor-manager.png
[Sun Aug  9 19:31:52 2020] [::1]:36976 [200]: /website/img/web-gui-kdb.png
[Sun Aug  9 19:31:52 2020] [::1]:36978 [200]: /templates/breadcrumbs.html
[Sun Aug  9 19:31:52 2020] [::1]:36986 [200]: /assets/fonts/lato/lato-regular-webfont.woff2
[Sun Aug  9 19:31:52 2020] [::1]:36988 [200]: /assets/fonts/libre-franklin/librefranklin-regular-webfont.woff2
[Sun Aug  9 19:31:52 2020] [::1]:36990 [200]: /assets/fonts/font-awesome/fontawesome-webfont.woff2?v=4.7.0
[Sun Aug  9 19:31:52 2020] [::1]:36992 [200]: /assets/fonts/lato/lato-bold-webfont.woff2
[Sun Aug  9 19:31:52 2020] [::1]:36994 [200]: /vendor/asciinema/asciinema-demo.json
[Sun Aug  9 19:31:54 2020] [::1]:37000 [404]: /doc/help/kdb-export.md - No such file or directory
[Sun Aug  9 19:31:57 2020] [::1]:37002 [404]: /src/plugins/hosts/README.md - No such file or directory
```

So it looks like some files are not copied to the public folder.

> http://localhost:9000/something/not/existing will redirect me to the /error/404

This also works for me. Only correct links do not work.

**Comment by markus2330** [comment]
Btw. here the listing of all files: [listing.txt](https://github.com/ElektraInitiative/libelektra/files/5048134/listing.txt)

**Comment by markus2330** [comment]
Is it possible that the problem is that `kdb set system/sw/elektra/websitefrontend/#0/current/website/content_root /`? Does this change on which URL pages are delivered or does this change from where source files are looked up?

**Comment by Namoshek** [comment]
> Is it possible that the problem is that kdb set system/sw/elektra/websitefrontend/#0/current/website/content_root /? Does this change on which URL pages are delivered or does this change from where source files are looked up?

Yes, I think so. The `content_root` defines the directory where dynamic contents are stored, which is `/srv/share/elektra/tool_data/website/public/website` in your case. Since the script which uses this path is executed in the `public/` directory, it needs to prefix lookups with the `website/` sub path.

**Comment by markus2330** [comment]
I found out how to fix the first bug about `Cannot GET /<page>`: a `/srv/lib/elektra/tool_exec/build-website` is needed also when running the grunt webserver.

> but it makes no sense to do so I think

:+1: 

Setting `kdb set system/sw/elektra/websitefrontend/#0/current/website/content_root /srv/share/elektra/tool_data/website/public/website` did not help.

**Comment by Namoshek** [comment]
I think you got me wrong. Don't set it to the full path, only to `website/` (the default). It is actually a public content root, not the internal one. So it's basically an URL prefix for requested pages.

**Comment by markus2330** [comment]
Ok, so any other value than `website/` seems to lead to break the links of the page :wink: I reverted the commit and fixed the local setup, it works now.
