### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3468]
## Steps to Reproduce the Problem

1. go to https://www.libelektra.org/libraries/readme
2. click on the first external notification link

The relevant link in Markdown is `**[notification](notification/)**`, so it is an internal link, as other links in the same document (the other seem to work, at least the loader link directly below works for me, it looks like `**[loader](loader/)**`.

## Expected Result

That I will go to https://github.com/ElektraInitiative/libelektra/tree/master/src/libs/notification/

## Actual Result

I was sent to https://github.com/ElektraInitiative/libelektra/tree/master/notification/ which is a 404.

## System Information

- Elektra Version: master

**Comment by markus2330** [comment]
Thank you for helping out with the "all links broken", there is also an issue with one link broken :wink:

@Namoshek do you have any ideas about that?

**Comment by Namoshek** [comment]
> That I will go to https://github.com/ElektraInitiative/libelektra/tree/master/src/libs/notification/

If you want to be sent to an external page, then make the link an absolute URL. Relative and absolute file paths only work with displayable documents (markdown, c-files, images, etc). It's also important that the target of the link exists and is not just a directory.

**Comment by kodebach** [comment]
Is this issue still relevant? I recently made a change to some of link translation code, since it previously only allowed one link per line of markdown. Did that change fix this issue as well?

**Comment by markus2330** [comment]
loader and notification now both point to the GitHub repo. I think we can close this.
