### ISSUE TITLE
qtgui: meta data conflicts

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#347]
constants and uname get conflicts on meta data,
```
system/info/constants
Ours: CONFLICT_META, Theirs CONFLICT_META
...
system/info/uname
Ours: CONFLICT_META, Theirs CONFLICT_META
...
```
even though they do not have meta data set:
```
kdb lsmeta system/info/constants
kdb lsmeta system/info/uname
```

steps to reproduce:
```
kdb mount-info 
```

Then cause two merges in the qt-gui (e.g. setting `user/guitest/inside` from within the qt-gui and `user/guitest/outside` from outside twice and press sync in between).

**Comment by fberlakovich** [comment]
I will have a look at this as soon as I can use the gui on my machine.

**Comment by markus2330** [comment]
@fberlakovich GUI is fixed, it should work nicely now.

**Comment by markus2330** [comment]
ok, you might have problems in a virtual box without any graphics acceleration, but thats an issue inherent to qml

**Comment by fberlakovich** [comment]
Could it be that is is fixed already? I cannot reproduce this issue

**Comment by markus2330** [comment]
Nice that qt-gui works for you again!

It seems like that `populateModel` (#348) fixes the problem. So somehow wrong meta data is added to the keys, which cause a merge conflict.

When using `populateModel`, all meta data is wiped out (because keys are reread), avoiding this problem.

So I think there is nothing to do in merging code, but only in the qtgui.

**Comment by 0003088** [comment]
I do not get how I can trigger the problem? Just for clarification: I am supposed to edit a key from inside the gui and one from outside the gui and then hit sync? And then a conflict should occur? And the whole thing twice?

**Comment by markus2330** [comment]
@0003088 exactly! Do not forget to run `kdb mount-info` first.

**Comment by 0003088** [comment]
Am I supposed to run kdb mount-info as root? Because when I don't it fails and when I do I cannot write to my config anymore.

**Comment by markus2330** [comment]
You can chown /etc/kdb afterwards or before:
```
chown -R `whoami` /etc/kdb
kdb mount-info
```

**Comment by markus2330** [comment]
Cannot reproduce the initial issue anymore. #299 might improve the performance on reloading.
