### ISSUE TITLE
Lua plugin doesn't compile

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3479]
## Steps to Reproduce the Problem

Try to compile the Lua plugin.

## Expected Result

Compilation should be sucessful.

## Actual Result

```
/usr/bin/ld: ../plugins/lua/CMakeFiles/elektra-lua-objects.dir/lua.cpp.o: in function `SWIG_Lua_NewPointerObj':
~/libelektra/cmake-build-debug/src/plugins/lua/runtime.h:2470: undefined reference to `lua_newuserdatauv'
/usr/bin/ld: ../plugins/lua/CMakeFiles/elektra-lua-objects.dir/lua.cpp.o: in function `SWIG_Lua_NewPackedObj':
~/libelektra/cmake-build-debug/src/plugins/lua/runtime.h:2535: undefined reference to `lua_newuserdatauv'
```

## System Information

- Elektra Version: master
- Operating System: Manjaro Stable Version, up-to-date as of 2020-09-05
- Lua Version: 5.4.0 (specifically 5.4.0-2 from the Manjaro extra repo)

**Comment by mpranj** [comment]
A fix for this will be provided in #3532. (already fixed, needs git push from another machine)
