### ISSUE TITLE
qt-gui: populateModel slow

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#348]
createNewNodes does not update existing keys properly Steps to reproduce:
```
kdb set user/guitest/oldkey oldvalue
kdb qt-gui
kdb set user/guitest/oldkey newvalue
kdb set user/guitest/newkey newvalue
```

After pressing refresh, I see `user/guitest/oldkey oldvalue` even though the keyset internally already had `newvalue`, but `createNewNodes` seems to not update the key.

Solution: make `populateModel` faster and use it

**Comment by markus2330** [comment]
`populateModel` does not have the problem

**Comment by markus2330** [comment]
Actually, I think that using `populateModel` is correct. `createNewNodes` would need to handle all cases of new and removed keys on both sides correctly (actually that would be a merging).

`populateModel` has two problems:
1. the tree view collapses. Also `createNewNodes` closes the right window. So both do not work perfectly. I think we can live with it. Better to have a small navigation obstacle than to have wrong values.
2. memory consumption/speed. This is really a problem. @fberlakovich could not even start qt-gui. But thus it is also a startup problem, we should fix it.

The problem is that for every TreeViewModel node during populateModel Elektra is (re)opened. When I tried to press sync once, 48.22% of the CPU time was spent in elektraPluginOpen, (45.21% in elektraAugeasOpen, which seems to be the slowest plugin).

So we need to move KDB out of TreeViewModel and share it once for the whole tree. What do you think is the best place to move KDB to?

**Comment by 0003088** [comment]
I was a little suprised when I read here in this issue about slow populating since I was sure that I had moved m_kdb out of TreeViewModel due to my optimizations because we faced the problem earlier (if you remember there was a time when the gui was dead slow). So I looked it up and it was indeed you yourself who moved m_kdb into TreeViewModel (see d88d384e640ebb448959dcf235a3f477ef65c232). I do not know the exact motivation, but can't we move it back to main.cpp? Or put it in GUIBasickeySet maybe?

**Comment by markus2330** [comment]
The kdb objects store the state which configuration files are already fetched. So if you create a new kdb object for every sync, everything is refeteched every time (d88d384e640ebb448959dcf235a3f477ef65c232 fixed that).

We could do:
1. have kdb outside of TreeViewModel and only have a reference within
2. only have a kdb in the outmost TreeViewModel (and not in the inners)
3. split TreeViewModel to have a outmost component and another for hierarchical nesting

I can fix the problem, I just wanted to ask for your opinion which solution might be the best. 3. might be the nicest solution, but it needs some refactoring and I am not sure about the constraints QML and QAbstractListModel gives us.

**Comment by 0003088** [comment]
Well, I think that 1. would be the simplest and least painful solution? At least for the moment. 

About the update problem: the keyset that is parameter of createNewNodes() is the latest and  most actual configuration, right? And the gui does not know that something has changed in the config, so it does not delete the old node and creates a new one. So it only checks if the node exists and if so, the gui does nothing.  So what about if we add in sink() a check for the value if a existing node is found and it contains a key? Shouldn't that work? Or am I missing something?

**Comment by markus2330** [comment]
Yes, the parameter of `createNewNodes()` had the latest configuration, but it was not propagated to the tree view.

I think there are more scenarios then the one with changed value, especially scenarios with changed meta data. If you can fix all of them, we can use `createNewNodes` again. Do you want to do that?

**Comment by 0003088** [comment]
Actually it wouldn't even be necessary to check if the values & metadata are the same, it's enough to set them since we know that the new data is the latest. So I will just call setValue() and setMetadata() for each existing node that contains a key. Right? And you will fix the kdb problem?

**Comment by markus2330** [comment]
Yes, if everything is set again and every leftover key is removed it should be fine.

**Comment by 0003088** [comment]
I wrote a fix but cannot test it:

Error (#84) occurred!
Description: Read only plugin, kdbSet not supported
Ingroup: kdb
Module: 
At: /home/raf/qtprojects/libelektra/src/libelektra/plugin.c:384
Reason: the key system/elektra/version/constants/KDB_VERSION (expected system/elektra/version) was modified to 0.8.13 (expected Below are version information of the Elektra Library you are currently using)
Mountpoint: system/elektra/version
Configfile: 

Do you know what's that about?

**Comment by markus2330** [comment]
Strange, actually there is code that checks if the keyset is unchanged. The error you got should only be issued if you actually tried to modify the value "0.8.13".

**Comment by markus2330** [comment]
In your case it seems as if the key `system/elektra/version` vanished?

**Comment by 0003088** [comment]
No, the key is there and it says 0.8.13. This error even appears when I open the gui and do nothing else than pushing sync.

**Comment by markus2330** [comment]
Please execute: `kdb ls system/elektra/version`
`kdb export system/elektra/version simpleini`
`kdb set system/elektra/version a` (should fail)
`kdb set system/elektra/version/constants/KDB_VERSION 0.8.13` (should succeed)

**Comment by 0003088** [comment]
I did all that but it didn't change anything.

raf@netbook:~/qtprojects/libelektra/build$ kdb ls system/elektra/version
system/elektra/version
system/elektra/version/constants
system/elektra/version/constants/KDB_VERSION
system/elektra/version/constants/KDB_VERSION_MAJOR
system/elektra/version/constants/KDB_VERSION_MICRO
system/elektra/version/constants/KDB_VERSION_MINOR
system/elektra/version/constants/SO_VERSION
system/elektra/version/infos
system/elektra/version/infos/author
system/elektra/version/infos/description
system/elektra/version/infos/licence
system/elektra/version/infos/version

raf@netbook:~/qtprojects/libelektra/build$ kdb export system/elektra/version simpleini
system/elektra/version = Below are version information of the Elektra Library you are currently using
system/elektra/version/constants = 
system/elektra/version/constants/KDB_VERSION = 0.8.13
system/elektra/version/constants/KDB_VERSION_MAJOR = 0
system/elektra/version/constants/KDB_VERSION_MICRO = 13
system/elektra/version/constants/KDB_VERSION_MINOR = 8
system/elektra/version/constants/SO_VERSION = 4
system/elektra/version/infos = All information you want to know
system/elektra/version/infos/author = Markus Raab <elektra@markus-raab.org>
system/elektra/version/infos/description = Information of your Elektra Installation
system/elektra/version/infos/licence = BSD
system/elektra/version/infos/version = 1

raf@netbook:~/qtprojects/libelektra/build$ kdb set system/elektra/version a
Set string to a
The command set failed while accessing the key database with the info:
Error (#84) occurred!
Description: Read only plugin, kdbSet not supported
Ingroup: kdb
Module: 
At: /home/raf/qtprojects/libelektra/src/libelektra/plugin.c:384
Reason: the key system/elektra/version (expected system/elektra/version) was modified to a (expected Below are version information of the Elektra Library you are currently using)
Mountpoint: system/elektra/version
Configfile: 

raf@netbook:~/qtprojects/libelektra/build$ kdb set system/elektra/version/constants/KDB_VERSION 0.8.13
Set string to 0.8.13

**Comment by markus2330** [comment]
The commands are only debug info to track down the problem. Unfortunately, I am still without clue why you get this error. Your Elektra installation seems ok.


I cannot reproduce it yet. Somehow your qtgui (but not mine) seems to swallow the keys `system/elektra/version` and `system/elektra/version/constants`.

Btw. I implemented 1. to avoid the regression I introduced. qtgui is now fast again.

**Comment by 0003088** [comment]
Do you want me to push the fix so you can try it? Or should I wait?

**Comment by markus2330** [comment]
Would be good if you can test it too. Try to make the keyset in `src/include/kdbversion.h.in` empty (change it to `return ksNew (20, KS_END);`.

Make sure you have the latest version (6fb3b3bc98fc36c2b9961494396f49c72fd48c4f).

**Comment by fberlakovich** [comment]
Perfect! Btw: the gui works fine now.
