### ISSUE TITLE
tcl plugin test fails

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3481]
## Steps to Reproduce the Problem

Compile and run `make run_all`. (Specifically `testshell_markdown_tcl`)

## Expected Result

Compilation and tests should be sucessful.

## Actual Result

```
Sorry, I crashed by the signal SIGSEGV
This should not have happened!

Please report the issue at https://issues.libelektra.org/
~/libelektra/cmake-build-debug/tests/shell/shell_recorder/shell_recorder.sh: line 267: 2999324 Aborted                 (core dumped) "$KDB" export spec dump > "$SPECEXPORT"
fatal: Could not export spec config
```

Upon closer inspection, it turns out that the error is caused by the `€`-symbol (and any other special characters) in the testdata.
Specifically somewhere in the Boost Qi library (`boost::spirit::qi`) an assert fails, because the special character is decoded as a negative integer which is not in the range of an `unsigned char`.

## System Information

- Elektra Version: master
- Operating System: Manjaro Stable Version, up-to-date as of 2020-09-05
- Boost Version: 1.72.0 (specifically 1.72.0-2 from the Manjaro extra repo)

**Comment by markus2330** [comment]
Thank you very much for reporting! Looks to me like an upstream problem. As the tcl plugin is not so important, I mark this issue as low priority.
