### ISSUE TITLE
remove null plugin

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3483]
In order to simplify Elektra we want to get rid of trivial plugins, which have unintended side effects (like modifying unmodified keys). One candidate is the "null" plugin:

- its functionality is trivial
- it modifies keys (which is the main source of trouble)
- there are not many plugins using the plugins, it is only:
 - [ ] line (I can fix this)
 - [ ] simpleini (plugin can be removed)
 - [ ] tcl (plugin can be removed)
 - [ ] toml

@bauhaus93 can you remove the dependency of the null plugin and implement its functionality directly in the escaping/unescaping code? Doing so also has the advantage, that null values/empty strings will also work when toml is the default plugin. (binary values are probably no problem anyway as we do not write binary data to /elektra). If you can fix this in a separate PR (or together with other escaping fixes but not together with making toml the default storage plugin) this week, we could remove the null plugin already in the upcoming release.

**Comment by bauhaus93** [comment]
Yeah, I can do that. So this would mean, for the NULL case: On writing I need to check for NULL values and write `'@@NULL'` to the file instead. On reading I'd have to check for `"@@NULL"` values and replace them with NULL.
I've already created a separated branch for minor `toml` fixes, I will add this change to that branch and create a PR for it.

**Comment by markus2330** [comment]
Thank you very much! :sparkling_heart:

You do not need to mimic the exact behavior of the null plugin. You can use any escaping which feels natural for TOML.
