### ISSUE TITLE
csvstorage: usage of columns/names, quiet failure

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#349]
@tom-wa Can you provide an example of the columns/names usage in the README?

```
$ cat ~/.config/test.csv
a;b
c;d
$ kdb mount test.csv /csv csvstorage "delimiter=;,columns=2,columns/names=,columns/names/#0=col0Name,columns/names/#1=col1Name"
$ kdb export system/elektra/mountpoints simpleini
system/elektra/mountpoints/\/csv/getplugins/#5#csvstorage#csvstorage#/config/columns = 2
system/elektra/mountpoints/\/csv/getplugins/#5#csvstorage#csvstorage#/config/columns/names = 
system/elektra/mountpoints/\/csv/getplugins/#5#csvstorage#csvstorage#/config/columns/names/#0 = col0Name
system/elektra/mountpoints/\/csv/getplugins/#5#csvstorage#csvstorage#/config/columns/names/#1 = col1Name
$ kdb ls /csv
The command ls failed while accessing the key database with the info:

5
```
(exit code 5, but no other output)

**Comment by tom-wa** [comment]
Thanks for reporting, shouldn't have happened. 
the plugin handles the combination of the (missing/default) header flag in combination with the column names wrong. for some reason i've always had the header=colnames option activated while testing. 
I'll submit a patch this evening.

**Comment by tom-wa** [comment]
@markus2330 
seems like i forgot to reference the bug in the in the commit, this one has already been fixed
