### ISSUE TITLE
Cask 'java ' is unavailable

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3494]
Currently all (at least in #3447, #3493, #3491) macOS build jobs on CirrusCI fail with the message:

```
Error: Cask 'java' is unavailable: No Cask with this name exists. Did you mean one of these?
eclipse-java
eclipse-javascript
netbeans-java-ee
netbeans-java-se
oracle-jdk-javadoc
```

e.g. https://github.com/ElektraInitiative/libelektra/pull/3447/checks?check_run_id=1141161973

I am not a macOS user, but a quick google search [reveals that `brew cask` is for GUI apps](https://apple.stackexchange.com/questions/125468/what-is-the-difference-between-brew-and-brew-cask), so why are we using in a CI job?

I think we need `brew install openjdk` instead of `brew cask install java`.

**Comment by markus2330** [comment]
Thank you very much for reporting! :sparkling_heart: 

Let's hope #3495 fixes the issue.
