### ISSUE TITLE
Jenkins server config issue

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3499]
It seems the Jenkins server is not configured quite right...

The [latest run](https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-3447/29/pipeline) from #3447 is falsely reported as successful.

AFAICT `debian-stretch-full` was aborted for unknown reasons, which caused the build to stop after the "Full Builds" stage. But for some reason the build is now reported as successful, even though the "Build artifacts" stage did not run at all.

**Comment by markus2330** [comment]
@Mistreated can you take a look?

**Comment by Mistreated** [comment]
I checked it right away.
This must have been some odd termination, because:

> Caught the following exception: null

Since it did not catch any exception it went on, although the process was terminated.
If something like this happens again, please link it here.

**Comment by markus2330** [comment]
Is there maybe some other way to get more information about the current state beside from the Exception? The null exception is unfortunately not very rare.

**Comment by mpranj** [comment]
This problem has been reoccurring since the new build server setup. I just did some maintenance on the build system, but this will likely not fix the issue. A fix would be great but I also don't know how to debug this. 🤷

**Comment by Mistreated** [comment]
The last time I remember something like this happened was when there was a bug in publishing.
But if this happens again, just post the build here.. I will see what can I do about this.
