### ISSUE TITLE
fix dates for man pages

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3505]
As git does not remember times for files but the man pages use this time stamp, generated man pages get different results.

The easiest solution: We could pass `--date=<date>` to ronn. The date simply gets updated on releases.

More complicated solution: We somehow save&restore the correct dates for each file, e.g. `etckeeper` has such a feature.

**Comment by mpranj** [comment]
I think it should be enough to pass `--date=<date>` to ronn. It makes sense for releases. Is there any scenario why we would need to save&restore the correct dates?

**Comment by markus2330** [comment]
IMHO it is more honest when we would give the modification date and not
the release date. E.g. if a man page rots since many years but we say it
is "October 2020".

It is actually quite easy, we can get the date via:

```sh
git log -1 --format="%ad" --date=short -- $filename
```

**Comment by markus2330** [comment]
On a second thought there is a complication 🤔

When someone compiles from a tar ball we need to avoid that the man
pages are regenerated, even if ronn is available. (Otherwise the git
command would fail.)

**Comment by mpranj** [comment]
I agree. We can use your git suggestion when possible, and simply not rebuild otherwise. I think this tradeoff is fully acceptable.

**Comment by a-kraschitzer** [comment]
What kind of change does this entail?
Changing the make files to use the `git log` date instead?
Or can this be achieved in another way? (I still don't have a working build system and wouldn't mind not having to get it to work :) )

**Comment by markus2330** [comment]
> What kind of change does this entail?

The goal is that the man pages in `doc/man` reliably get regenerated with dates in their header from when their source in `doc/help` was actually modified (as seen in `git log`).

> Changing the make files to use the git log date instead?

It is about scripts/cmake/Modules/LibAddMacros.cmake that invokes scripts/cmake/ElektraManPage.cmake which invokes ronn. `git` needs to be additionally invoked and the date passed to the ronn invocation. The situation when `git` fails must be accounted for (e.g. when a tar ball gets extracted).

> Or can this be achieved in another way? (I still don't have a working build system and wouldn't mind not having to get it to work :) )

No. It is a very minor change which is only tricky because of the CMake integration. Even if you would write an extra script reimplementing what above mentioned files do, you still would need to integrate this script into CMake: so it wouldn't bring any benefit and poses portability problems (the script would need to run on every operating system).

**Comment by kodebach** [comment]
Is it intentional, that we now have a Cirrus Job that enforces that all man page files contain the current month?

See for example: https://cirrus-ci.com/task/6194364968861696
One man page file was changed, but the unmodified files should be accepted with the original date IMO.

**Comment by markus2330** [comment]
> Is it intentional, that we now have a Cirrus Job that enforces that all man page files contain the current month?

No, we actually want the month where the file was modified: #3505

**Comment by kodebach** [comment]
Then we should probably disable the Cirrus Job, since it obviously isn't working correctly.

**Comment by mpranj** [comment]
Closed via #3923 thanks to @kodebach. 🚀
