### ISSUE TITLE
New version dump plugin

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3506]
Merging of #3447 will actually break **every** file stored with `dump`, since it (incorrectly) stores absolute key names. The fix would be easy for most files (just add the new `:`). But it's almost impossible for the fix to cover all cases.

This might be the ideal moment to create a new version of `dump`. My goals for this new version would be:
- Store relative key names, so it behaves correctly for exports. (simple fix)
- Get rid of some of the useless parts of the file structure. (remove the `ksNew` and `ksEnd` lines)
- Ensure the files are printable, as long as all key values are printable. (very easy fix)

This would also make `dump` a very good candidate for most of the `testshell_markdown_` tests. It is a very simple format, but still stores all the information a `KeySet` contains. The only problem with the current version is that it store the null-terminator bytes of key names and key values, which makes the markdown tests hard.

**Comment by mpranj** [comment]
> This might be the ideal moment to create a new version of dump.

To my knowledge there is not much interest in further supporting `dump`. The decision was to move to `toml` asap. The only reason to keep dump would be to import old configs / provide an upgrade path. A new incompatible dump format would contradict that.

Of course, if we break every config by merging #3447, this idea might be obsolete anyway.

**Comment by kodebach** [comment]
> Of course, if we break every config by merging #3447, this idea might be obsolete anyway.

I could add a fix to #3447, so that at least most files could be read. I would just insert a `:` after the namespace if it is missing.

> The decision was to move to toml asap. 

It is still not clear to me that `toml` will 100% be able to store every possible KeySet in a lossless way.

It might also be beneficial in general to have a text-based format that is designed to mirror the structure of a KeySet. If nothing else, it can be used for demo purposes (if you ignore the zero-bytes and open a `dump` file in a text editor it actually shows very well how KeySets are structured) and of course for markdown tests.

But this was just suggestion, so it's also totally fine, if we just deprecate/remove `dump` before 1.0.

**Comment by mpranj** [comment]
From a maintenance perspective it makes sense. The `dump` plugin has a simple structure, is used heavily and has caused basically no problems.

**Comment by kodebach** [comment]
>  A new incompatible dump format would contradict that.

The new version doesn't even have to be (fully) incompatible.

All current dump files actually start with `kdbOpen 1`, where `1` is decoded as a version number.

https://github.com/ElektraInitiative/libelektra/blob/0486d043d70ada5ed7ff48cb2ff93619033282b3/src/plugins/dump/dump.cpp#L112-L121

The version check has existed for at least 10 years, so even if a very old Elektra version encounters an updated dump file, there would be a nice error message:

https://github.com/ElektraInitiative/libelektra/blob/6f1d7d75916626288e4317e40b3debf8ad38d19e/src/plugins/dump/dump.cpp#L112-L121

We could just write the plugin such that it can read version 1 and version 2, but only writes version 2. Then we'd have a seamless update procedure as well. If we decide to do, that we should do it before merging #3447 (even though that means another rebase for me).

**Comment by mpranj** [comment]
> We could just write the plugin such that it can read version 1 and version 2, but only writes version 2.

This sounds pretty nice to me. 👍
