### ISSUE TITLE
website: pages do not render properly (SHOWONGITHUB)

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3508]
E.g. https://www.libelektra.org/plugins/readme shows on a otherwise empty page (with Firefox ESR+Chromium):

```
{{ 'APP.WEBSITE.LISTFILES.BUTTON.SHOWONGITHUB' | translate }}
```

Did we introduce a syntax error somewhere on this page?

@Namoshek any ideas?

**Comment by mpranj** [comment]
I think [this](https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/master/241/pipeline/2439) is the build which resulted in the error.

I triggered a rebuild in case it was a temporary error, but I have seen nothing **new** and suspicious in the logs.

**Comment by Namoshek** [comment]
Looks weird to me; neither updates to the affected code nor related packages were made, as far as I can see.

**Comment by mpranj** [comment]
The rebuild did not help.

The [news page](https://www.libelektra.org/news/0.9.2-release) is broken as well. Actually it seems most pages except the landing page are broken.

**Comment by markus2330** [comment]
I can also reproduce locally. Unfortunately, not even the very old 47394dfd17a6132c2e5fd29e1dc28b9bff2575b6 commit builds correctly, so the problem is most likely unrelated to our changes. And it also seems to me that actually all pages are broken.

Maybe it is the nodejs version? (I use now v14.13.1; there was a recent update from 14.12.0 on 1st of October which might be the cause) Or is it some npm package?

@Namoshek any idea what we could do?

**Comment by markus2330** [comment]
With nodejs v10.21.0 I get the same results.

@Namoshek Is it possible that some change of GitHub introduced the problem? Or is it just by chance that the source of `SHOWONGITHUB` is shown?

Btw. the build log looks very innocent:

```
Running "less:build" (less) task
>> 2 stylesheets created.

Running "cssmin:build" (cssmin) task
>> 2 files created. 239.29 kB → 189.66 kB

Running "concat:vendor" (concat) task

Running "concat:docsearchcss" (concat) task

Running "concat:docsearchjs" (concat) task

Running "concat:pacejs" (concat) task

Running "concat:pacecss" (concat) task

Running "create-website-news:build" (create-website-news) task
>> Found file `.gitattributes`, which has an inappropriate filename, in the news folder.
>> Found file `_preparation_next_release.md`, which has an inappropriate filename, in the news folder.
>> News post 2014-10-22_augeas.md has no short description matching the configured regex!
>> Website news file generated successfully!

Running "create-website-news-rss:build" (create-website-news-rss) task
>> News post undefined has no guid that can be used to generate an RSS post!
>> News post undefined has no guid that can be used to generate an RSS post!
>> Website RSS news generated successfully!

Running "create-website-structure:build" (create-website-structure) task
>> Website structure file generated successfully!

Running "copy-website-content:build" (copy-website-content) task
>> Website content copied to target directory successfully!

Running "copy:build" (copy) task
Copied 4 files

Running "preprocess:config" (preprocess) task

Running "preprocess:index" (preprocess) task

Running "browserify:build" (browserify) task
>> Bundle resources/application.js.tmp created.

Running "uglify:build" (uglify) task
>> 1 sourcemap created.
>> 1 file created 3.98 MB → 1.82 MB

Done.
```
