### ISSUE TITLE
Update for pluginprocess

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3509]
As noted in #3507, the `pluginprocess` library should be updated.

1. It should not try to send keys that are about eh `parentKey` it uses for the storage plugin.
2. It should work with a storage plugin that (correctly) uses relative key names.
3. It should probably use a storage plugin that is faster the `dump`, e.g. `quickdump`.

Maybe an approach entirely without a storage plugin by writing/reading Keys in the library would be better.
Alternatively, using `mmapstorage` and shared memory might work and should be faster than encoding and decoding KeySets for transmission.

**Comment by markus2330** [comment]
I like the idea with mmapstorage best! As pluginprocess only works on POSIX anyway, an mmap approach is perfect.

**Comment by mpranj** [comment]
> Alternatively, using mmapstorage and shared memory [...] should be faster

I have been thinking about this as well. I also suspect it could be faster, but only if not implemented as a plugin (i.e. we can't just use mmapstorage as is). I think the key would be not to use the mmap kdbSet() and kdbGet() functions, but to do everything in one step.

One drawback is that the encoding process basically does all the work in advance and the receiving process cannot start digesting the keyset already. I discussed this with @markus2330 once. So unfortunately it does not seem guaranteed that it would be effectively faster than say quickdump.

**Comment by markus2330** [comment]
> receiving process cannot start digesting the keyset already

I doubt that happens in the current implementation except of the construction of the KeySet which would not be needed with mmapstorage in the first place.

Would be interesting how it performs, especially in memory overhead (which might be the main benefit, especially for plugins that do not consume all keys). Some scripting plugin (with pluginprocess) fits very nice in a real-world benchmark anyway.

@kodebach thank you for bringing up the topic :sparkling_heart:

**Comment by kodebach** [comment]
> I also suspect it could be faster, but only if not implemented as a plugin (i.e. we can't just use mmapstorage as is). I think the key would be not to use the mmap kdbSet() and kdbGet() functions, but to do everything in one step.

Yes, we would probably have to extract the actual `mmap` part into a separate library.

> One drawback is that the encoding process basically does all the work in advance and the receiving process cannot start digesting the keyset already.

Using pipes is also an easy way to notify the reading process, when the writing process is ready. AFAIK with a shared memory solution that would require some extra work, e.g. semaphores.

> Would be interesting how it performs, especially in memory overhead (which might be the main benefit, especially for plugins that do not consume all keys).

Depending on the actual implementation (and use case), memory overhead might actually be a lot higher with mmapstorage. It might require that we duplicate the entire KeySet (on both sides) to avoid unwanted writes.
