### ISSUE TITLE
Jenkins: build timeouts

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3510]
We have had timeouts on travis-ci for a while. [This](https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/master/247/pipeline/647) is the first time that I see build timeouts on Jenkins:

```
212/258 Test #175: testscr_check_get_set .........................   Passed    6.20 sec
        Start 176: testscr_check_import
213/258 Test #176: testscr_check_import ..........................   Passed  105.42 sec
        Start 177: testscr_check_kdb_internal_check
214/258 Test #177: testscr_check_kdb_internal_check ..............   Passed    1.68 sec
        Start 178: testscr_check_kdb_internal_suite
Sending interrupt signal to process
Terminated
script returned exit code 143
Caught the following exception: null
Start archivation
```

A similar situation happens when a different build fails so other builds get terminated. Here, no other builds are failing.

Our Jenkinsfile does specify a timeout after 15 minutes of no output, but this should still not happen.

[full_log.txt](https://github.com/ElektraInitiative/libelektra/files/5357237/full_log.txt)

**Comment by markus2330** [comment]
The internal suite runs quite intensive read/write tests on all storage plugins. We already needed to reduce the number of tests (for dump plugin), as it might take hours when all tests are executed on all plugins (btw. mmapstorage would also pass all tests?). So probably we should reduce the tests even more for regular builds and only for releases we run the extensive suite. Robert will work on this in future.

Did you try to increase the Jenkins timeout, did it help?

**Comment by mpranj** [comment]
I did not increase the timeout. It seemed unlikely to me that there would be no output at all for 15 minutes. We can try increasing if you think that is the reason. I mean, the old hard drives and btrfs are quite slow, that is true.

I don't know whether mmapstorage passes these tests, but we can test it. I did not even know what the internal_suite does tbh.

**Comment by markus2330** [comment]
> We can try increasing

It is worth a shot. In Jenkins we at least have this possibility.

./tests/shell/check_kdb_internal_suite.sh calls `kdb test` on all rw storage plugins. `kdb test` writes and reads many different KeySets and sees if they round-trip correctly.

**Comment by mpranj** [comment]
```
215/258 Test #178: testscr_check_kdb_internal_suite ..............***Timeout 1500.00 sec
```

Now it timeouts because of the ctest timeout of 25 minutes. I'll try increasing that in a PR.

**Comment by mpranj** [comment]
This specific test does not finish in 30 minutes either. It seems that it only fails on `a7` though.

**Comment by markus2330** [comment]
a7 is the only one without SSD. 30 minutes is quite long nevertheless. Would be interesting which of the plugins take so long. Only toml was added, wasn't it?

**Comment by mpranj** [comment]
Seems like merging #3511 finally improved things, it ran through even on `a7`. 

```
        Start 181: testscr_check_kdb_internal_suite
218/262 Test #181: testscr_check_kdb_internal_suite ..............   Passed  1804.16 sec
```

> Would be interesting which of the plugins take so long.

I don't really know, I opened #3512 for further investigation.
