### ISSUE TITLE
My fundamental problems with Elektra

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3517]
**NOTE** _This issue is intended for discussion in the meeting on Monday 2020-10-19. If you will attend the meeting, please don't comment and instead add your input during the meeting._

---

I don't have a problem with Elektra's key names themselves. However, I do have some issues with Elektra that could be solved through changes to key names.

### Problem

Currently the semantics of key **cannot** be determined from just the `Key` instance. The consequences range from mildly annoying to catastrophic. A few examples, just based on `array` the metadata:

- To lookup an array element I can't just do `ksLookupByName (ks, "/myarray/#0", 0)`. Instead, I also have to do `ksLookupByName (ks, "/myarray", 0)` and check that it has `array` metadata with value of at least `#0`.

  This is mildly annoying. While we do need to do all this in the general case. Often iterate over the array and therefore have to lookup the array size from the `array` metadata anyway. In applications with a good specification, we can also do a simple lookup of the array element, if the specification ensures that the array element always exists and always is an array element.
- The `spec` plugin has to do immense amounts of work to correctly handle arrays.

   This is catastrophic. If we have the key `spec:/polygons/#/points/#/x` the `spec` plugin has to do:
   - a lookup for `/polygons` to find outer the array size
   - for each of possible outer array elements do a lookup `/polygons/#XYZ/points`, to find the inner array sizes
   - now we finally know the matching keys
   Written like this, this may seem not that hard, but a significant challenge here is to finding/constructing the key names that have to be looked up.

### Solution

Ensure all key semantics are self-contained in the `Key` structure. This could for example be achieved through changes to the key name. A solution specific to arrays, is discussed below.

### Problem

Elektra's memory consumption is very high.

### Solution

There are many solutions. Here are a few that involve changes related to key names:

- Encoding some of the semantics into the key name, instead of using metakeys.
- Using the escaped key name only for construction of keys and for printing.
  Reducing the use of escaped key names to a minimum would make it possible to only store the unescaped name (or only store escaped parts that differ from the unescaped ones) and reconstructing the escaped name every time it is needed.
- Store a parent key in a `KeySet` and use relative names for all contained `Key`s. This would significantly reduce memory use, since we would cut down on the number of duplicated string segments.

### Problem

Currently there is no good way for storage plugins to work around limitations of the storage format.

Most formats struggle with metadata and non-leaf keys with values. The reason is that most formats are designed to store a single tree structure with values at the leaves. Elektra's KDB, however, is a tree in which every node may have a value and a link to a separate tree (metadata).

### Solution without key name change

There is no real solution. The best we can do is say: A storage plugin may limit what Elektra is capable of, if some of Elektras features conflict with the limitations of the storage format.

### Solution with key name change

We could prohibit certain key names. Then a storage plugin could take advantage of these key names and use them to encode information that could otherwise not be distinguished from another key.

Non-leaf values and metadata could be moved into special child nodes in the tree structure. These special child nodes would correspond to key names that are prohibited. Therefore we know that these nodes should be read as metadata/non-leaf values and not as actual child keys.

Such a solution could be accomplished without prohibiting key names. But that would require escaping mechanisms and further complicate both the storage format and the code of the storage plugin. Additionally, prohibiting key names and using those also makes it easier to define a standard way to implement this work around and thereby make the whole thing more user-friendly.

Note: the minimum change required here is, to prohibit certain key names from appearing in `KeySet` that are passed to/from storage plugins. Everywhere else key names could still be unrestricted and the storage plugin interface could be guarded by an encoder/decoder plugin that translates the prohibited keys into a non-prohibited encoding.

### Problem

Arrays are incredibly cumbersome to use in Elektra. This very bad. Arrays are an integral part for writing good configurations.

There are already a few examples above that show how cumbersome array handling can be in Elektra. It is especially bad in libraries and plugins that do not have prior knowledge indicating whether a key is an array element or not.

Currently, you need to check 3 things to make absolutely sure, a `Key * k` is an array element:
1. `keyBaseName (k)` is a valid array index.
2. The parent key of `k`, has the `array` metadata and its value is at least `keyBaseName (k)`.
3. The escaped base name (incredibly hard to obtain) does not start with a backslash `\`.

### Solution without key name change

Add lots and lots of helper functions and hope everybody finds and uses them. This will be a lot of effort for us in terms of development and maintenance. Designing this set of helper functions in the first place will already be a challenge.

### Solution with key name change

Once and for all define that all key name parts starting with `#` must be a valid array index and that all such parts are always elements of an array.

First of all, this ensures self-contained key semantics and thereby avoids having to lookup the parent key. It also avoids the complicated check of the escaped base name and instead of checking all of `keyBaseName (k)` (probably via a helper function), we only need `keyBaseName (k)[0] == '#'`.

It also saves us having to develop and maintain a whole ecosystem of array helper functions. Most array handling will be quite simple and wouldn't require helper functions. The remaining helper functions would be much simpler and easier to maintain.

### Problem

Currently, contextual values are a bit weird and applications have to use a different (C++) API to utilise them. But maybe one day the high-level API supports a variant of contextual values, or there is a plugin that does something similar, but at `kdbGet`-time not at lookup-time.

The problem is, that currently no plugin can do any such processing of key names. Even a very basic plugin `uid` that replaces `/$uid/` with the UID of the current user doesn't work. The UID cannot change between `kdbGet` and `ksLookup`, so implementing this subset of contextual values as a plugin should be no problem. The UID also doesn't depend on the mountpoint so you would expect it to work as a global plugin.

However, what if an application uses user supplied values e.g. WiFi SSIDs as a key name part. If a user now mounts the `uid` plugin globally and also uses this application with the SSID `$uid`, there is a problem.

Now, I know this a very contrived example. The `uid` plugin alone is not a very good idea to begin with. But the whole thing is a very easy to understand example. There may be some useful more complex ideas, that run into similar problems.

### Solution without key name change

None, AFAIK.

The current idea of key names basically means an unescaped key name can never convey any meaning beyond which key of the KDB it refers to. 

### Solution with key name change

There are two solution, I know of. They can be used together or separately.

1. Add a kind of escape syntax to the unescaped key name. It's a bit weird to have escapes in the unescaped name, but whatever. Basically there would be some way to encode a key name part, if an application wants to ensure the key name part is never interpreted in any way that would change the keys semantics. For example, if the application uses user supplied values (WiFi SSID), it would encode the user supplied value before adding it to the key name. That way every part of Elektra knows to ignore this part of the key name.
2. Add more syntax/semantics to key names. Just like the `#` for arrays above, one or more characters could be reserved. There wouldn't have to be any change in the core. A convention could be enough. For example, the convention could be key name parts starting with `@` always have special meaning and might change the keys semantics. Applications using user supplied values (WiFi SSID), would have to ensure they don't accidentally use such a key.

  A single character like `@` would be enough, because we could introduce a convention. For example `@plug@dat`, means this key name part will be interpreted by the plugin `plug` and the plugin will use `dat` as an argument. In this case we could also use `@@dat` as the encoding for `@dat`.

---

### Re: making the API more difficult to use

These changes, mostly affect applications that use user supplied values in key names. IMHO this is not a big problem. It is very common that user supplied values have to be sanitized/escaped before they can be used. As long as there is a ready-made function that takes care of this, I don't think anybody will complain.

To me it also seems that while it will make Elektra slightly more difficult to use in some cases. It will make Elektra easier to use in many many other cases.

Lastly, additional changes to the API might help as well. For example:

There is the constraint "`keySetBaseName (k, keyBaseName (k))` should be a NOP". This constraint, however, only exists because of the current names of these functions and the assumptions that most programmers make based on this names.
If we the names were `keyLastPart` and `keySetBaseName` (or even `keySetLastUnescapedPart`), I think most programmers wouldn't make any assumptions. It might make the API a tiny bit more confusing at first, but it is not that uncommon to have asymmetric getters and setters in an API.

Most of the constraints for `key*BaseName` actually arise purely from expectations based on the names. So if we completely redesign the naming scheme, the result might be an easier to use and more powerful API. That would of course take some time, but I don't think 1.0 will be released any time soon.

A way to avoid another huge PR that touches everything would be to implement the new API and keep the existing one. Then we could migrate everything to the new API piece by piece. This would of course require a new name for every function in the core that is affected by the change, so it might be impossible because of transitive uses.

**Comment by kodebach** [comment]
Currently, I tend towards the following changes to key names:

- Key name parts starting with `#` must be a valid array element. Anything else just causes confusion and doesn't have any clear benefits IMO. So things like `/#abc/`, `/#__10/` and `/#_123/` are **never** allowed.
- The `spec` plugin automatically generates/validates the correct `array` metadata. `array` metadata should **never** be stored explicitly. That way the `array` metadata cannot be out of sync with the elements. The `array` metadata is generated, even if no `spec:/` key with `array` is present. `#` key name parts are **always** array elements.
- At least one key name part (e.g. `@elektra`), but ideally a whole set of parts (e.g. starting with `@elektra@`) is reserved. This means a `Key` with such a name _can_ be constructed, but applications **must not** use them for their configuration. Such keys could be used by plugins to provide information that doesn't really fit into metadata.
- Rename most or all of the `key*Name` functions to avoid conflicts with existing assumptions.
- Introduce a function that appends to the end of the last key name part. The function **does not** add a new key name part. This makes it easier for applications to create prefixed key name parts and avoid reserved/illegal names.

**Comment by markus2330** [comment]
Again, answers in #3514 are highly appreciated (especially which already contain wording or suggestions that can be easily put into the decisions). I tried to capture the essence of this discussion in 26ab29f880ccab140f3ce8728f58d4e0bc0ed118 but as it is highly subjective what arguments are important, please give feedback in #3514.

> The spec plugin has to do immense amounts of work to correctly handle arrays. This is catastrophic.

Yes, I agree. But I think that the amounts of work is not getting much less if you do not have the `array` metadata. The heavy lifting is to detect misstructured nested arrays (`#` intermixed with non `#` keys) which is a possibility either way.

> Ensure all key semantics are self-contained in the Key structure.

Why wouldn't that be the case with the array.md decision?

> Elektra's memory consumption is very high.

I agree there is much to be improved and hope @mpranj will work on this. Currently this is probably more important than CPU optimizations. But there is not much to be decided with one exception: if we should provide both `keyName` and `keyUnescapedName`. Did you take a look of how many call-sites of `keyName` are there? Will it be feasible to get rid of that function and then rename `keyUnescapedName` to  `keyName`? To get the escaped keyName you then would need something like `elektraEncodeKeyName(buffer, keyName(...)`. This should be okay for printing the keyname? The impact for storage plugins might be not so much, as mainly elektraKeyGetRelativeName would need to be fixed.

>  Encoding some of the semantics into the key name, instead of using metakeys.

Did you think of anything except the array? It seems to me this alone does not save noticeable memory...

> Store a parent key in a KeySet and use relative names for all contained Keys. This would significantly reduce memory use, since we would cut down on the number of duplicated string segments.

Doesn't work if we want to provide `keyName` and also would slow down comparison a lot.

> Currently there is no good way for storage plugins to work around limitations of the storage format.

The big question is if this is a goal. I do not think so. As you say for yourself, it only can be a "work around" anyway.

> is a tree in which every node may have a value and a link to a separate tree (metadata).

Yes, the KeySet is designed to hold anything that any configuration file format can hold. It does not mean that any storage plugin should also implement this. Limitations in storage plugins are necessary and not a problem.

> We could prohibit certain key names. Then a storage plugin could take advantage of these key names and use them to encode information that could otherwise not be distinguished from another key.

Storage plugins **already** can prohibit any key names as they see fit. They are allowed to reject KeySets. What we need are classifications of classes of KeySets to be rejected #3504.

Only for the special case "storage plugins that try to please" everyone, you can try to extend the storage format to do everything.

> Non-leaf values and metadata could be moved into special child nodes in the tree structure.

Non-leaf values and metadata are already supported by the KeySet, why would a storage plugin to move it at places where it should not be.

So we are actually only talking about the problem that storage plugins need to reserve special syntax which is completely internal, i.e., never in a KeySet that leaves the storage plugin.

> Additionally, prohibiting key names and using those also makes it easier to define a standard way to implement this work around and thereby make the whole thing more user-friendly.

I agree that it makes sense to have a standard way. But if it is somehow possible, we should make these workarounds local to the plugins that need them, and not globally visible for everyone using the KeySet.

> Note: the minimum change required here is, to prohibit certain key names from appearing in KeySet that are passed to/from storage plugins. Everywhere else key names could still be unrestricted and the storage plugin interface could be guarded by an encoder/decoder plugin that translates the prohibited keys into a non-prohibited encoding.

Sounds reasonable. But why does it need to be a guarding plugin and cannot be done in the plugin itself if it always stays internal?

> The escaped base name (incredibly hard to obtain) does not start with a backslash \.

This problem gets introduced in #3447, so probably we should simply get rid of it by not introducing it.

> Once and for all define that all key name parts starting with # must be a valid array index and that all such parts are always elements of an array.

This does not really change the problem that `#` keys might be intermixed with non-`#` keys. Somehow we need to deal with this problem in any case.

> First of all, this ensures self-contained key semantics and thereby avoids having to lookup the parent key.

If an application has specified that it is an array, it does not need to look it up. But probably it wants, because then it knows how far to iterate.

> It also saves us having to develop and maintain a whole ecosystem of array helper functions.

At least the conversion from Elektra's arrays to the programming language's arrays we need to implement anyway.

> Now, I know this a very contrived example.

A better example would be what the profile plugin is doing. The profile plugin avoids the problem, by using a hard-coded position where the profile is supposed to be. This works because we have specified how key names for applications should look like. So no placeholder is actually needed. If you do not know where it should be, you could also specify it in `spec`.

> The current idea of key names basically means an unescaped key name can never convey any meaning beyond which key of the KDB it refers to.

The metadata can give any meaning.

> Add a kind of escape syntax to the unescaped key name.

Actually every storage plugin can already do things like this.

> For example @plug@dat

I think this is quite obscure.

> As long as there is a ready-made function that takes care of this, I don't think anybody will complain.

Yes, in the end mostly the user interface matters (both the API and tooling).

> There is the constraint "keySetBaseName (k, keyBaseName (k)) should be a NOP". This constraint, however, only exists because of the current names of these functions and the assumptions that most programmers make based on this names.

No, it also exists that storage plugins round-trip.

> Most of the constraints for key*BaseName actually arise purely from expectations based on the names.

Yes, and it also a very good thing that names give many expectations. Names that do not give expectations are useless (e.g. foo, bar).

> A way to avoid another huge PR that touches everything would be to implement the new API and keep the existing one.

This is definitely a no-go. Such things can **only** be done after 1.0 and only if we made an API totally wrong. We should do anything in our power that such a thing does not happen. Having a minimal non-redudant API is basically the most important characteristic to have simplicity, which is our highest goal (directly after compatibility). And the statement "we will clean up before 1.0" is totally unrealistic, we already have way to much to clean up.

**Comment by mpranj** [comment]
> Elektra's memory consumption is very high.

Is there any analysis available what exactly consumes lots of memory? I know that the KDB handle and all structures are quite heavy, but usually you will have more KeySets and Keys than KDB handles. KeySets and Keys are much lighter afair.

The first idea that comes to mind is using relative Key names as already suggested by @kodebach. The optimization also has no effect if even one Key is not within that parentKey of the KeySet (when the common prefix is the empty string..).

I also suspect that changing the memory layout of Key names might break the OPMPHM, and I wouldn't know how to fix that.

**Comment by markus2330** [comment]
No proper analysis for larger applications has been done yet. This would be the first step before we start talking about solutions. Statistics about mmap files might actually be a quite good way to get a first impression. Would it be feasible to have some `kdb cache statistics` tool?

And we should take this topic somewhere else, as it is barely related to key names.

**Comment by kodebach** [comment]
> Is there any analysis available what exactly consumes lots of memory?

Not sure the analysis would reveal anything we don't already know. A big reason for the memory consumption is certainly that all `Key`s contain their full key names, but also that both escaped and unescaped key names are store.

`KeySet` probably cannot be optimized much (without loosing runtime performance) and `KDB` exists only once or twice per application so that's not really relevant.

> No proper analysis for larger applications has been done yet. This would be the first step before we start talking about solutions.

Are there any large applications using the latest Elektra that could be used for analysis? Implementing an application just to analyze it and then change everything is a bit silly.

---

> And we should take this topic somewhere else, as it is barely related to key names. (Everything else in the discussion is about key names)

Well, it was never my intention to discuss anything in this issue. Like the description says, it's intended as input for our meeting. The discussions should probably take place in separate smaller issues. Otherwise we get one huge comment after another again.

Nonetheless, I will look at your comment later.

**Comment by markus2330** [comment]
> Not sure the analysis would reveal anything we don't already know. A big reason for the memory consumption is certainly that all Keys contain their full key names, but also that both escaped and unescaped key names are store.

Pure speculation. sizeof(Key) is also large and also metadata can be large.

> Are there any large applications using the latest Elektra that could be used for analysis?

Yes, KDE and GNOME would be perfect :1st_place_medal: 

>  Well, it was never my intention to discuss anything in this issue. Like the description says, it's intended as input for our meeting. The discussions should probably take place in separate smaller issues. Otherwise we get one huge comment after another again.

My hope is that we get the discussion to #3514.

**Comment by kodebach** [comment]
First of all: **PLEASE** only post further comments, if you really think it is necessary and can't wait until the meeting. That way can give you more detailed explanations, _before_ you write comments based on some misunderstanding.

> My hope is that we get the discussion to #3514.

No, sorry. I will also keep my responses over there to an absolute minimum until we had our meeting. The meeting will be much quicker than writing one comment after another...

In that spirit, will also only clarify misunderstandings here. But will not further explain my opinions until the meeting. But first two exceptions:

> But I think that the amounts of work is not getting much less if you do not have the `array` metadata. The heavy lifting is to detect misstructured nested arrays (`#` intermixed with non `#` keys) which is a possibility either way.

Please, do not speculate about what is and isn't a lot of work in `spec`. I wrote the current implementation and I _know_ there are some areas where the code could be significantly simpler, if key names worked differently.

> Pure speculation. sizeof(Key) is also large and also metadata can be large.

**Not** "pure speculation". `sizeof (Key)` IIRC is about 64 bytes. `sizeof("system:/elektra/mountpoints/version") == 36` in #3447 the corresponding unescaped name is 30 bytes. That makes 64 bytes for the structure and 66 bytes for the key names. And that is just for `"system:/elektra/mountpoints/version"`, which is not a particularly long key name. In the spec of LCDproc for example every key name starts with `spec:/sw/lcdproc/lcdexec/#0/current` which is a 35 character prefix (and 31 bytes in unescaped name). If you remember, I did try to address the significant memory increase in the LCDproc with Elektra version. I didn't really succeed, because **most of the increase was key names**.

I wouldn't use the word "certainly", if I just made a wild guess...

Now back to the misunderstandings...

----

In general you took everything I wrote very literal and as concrete proposal. Many of the things in the description are just rough ideas that have to be evaluated first. The issue is just supposed to be notes for discussion not a proposal.

Please, also ask if you are unsure what something is supposed to mean or if you are not sure you understood my point, instead of making assumptions. I often read your responses and then have to re-read my own comments to see, where your interpretation comes from...

> But there is not much to be decided with one exception: if we should provide both `keyName` and `keyUnescapedName`. Did you take a look of how many call-sites of `keyName` are there? Will it be feasible to get rid of that function and then rename `keyUnescapedName` to `keyName`?

It was never my intention to remove `keyName`. My intention was to remove `char * key` from the `struct _Key`. Removing `keyName` or replacing it with `keyUnescapedName` might be nice, but it could also be very confusing so I didn't suggest it.

> It does not mean that any storage plugin should also implement this.

Also not my intention. But if Elektra wants to give the choice of config forma to the user, we need to support a at least a few popular formats (INI, JSON, YAML, XML) _in most/all possible cases_.

> But why does it need to be a guarding plugin and cannot be done in the plugin itself if it always stays internal?

It was just a possible solution, not necessarily the best or my preferred one. You always said my proposal would be too much work for storage plugin developers, so I suggested a solution with less code in storage plugins.

> This does not really change the problem that `#` keys might be intermixed with non-`#` keys. Somehow we need to deal with this problem in any case.

I did not address this because I don't see it as a problem. It's an odd quirk of Elektra, but it can be made to work. (Please don't ask how, I have ideas, but explaining them will just cause unnecessary discussions)

> > Now, I know this a very contrived example.
> 
> A better example would be what the profile plugin is doing.

You misunderstood, what the example was for. The example should not be useful or show what is possible. The example was explicitly designed to be simple and show a limitation. Whether another solution for the same problem exists, didn't matter because there may be another problem that encounters this limitation, but has no other solution. It was intended to be similar to the WiFi SSID example. There may be a million other ways to achieve it, but somebody may think this one is the best.

> No, it also exists that storage plugins round-trip.

You took my words too far. Of course other constraints still exist. But the constraints for storage plugins are completely separate from those for the API. The only exception is that storage plugins must be able to use the API to deconstruct and reconstruct the key name. But that was always a given.

The only thing I wanted to say is that the names `keySetBaseName` and `keyBaseName` imply "`keySetBaseName (key, keyBaseName (key))` is not a NOP" to many people. Other names, might not do that. I also didn't want to say that there shouldn't be a way to achieve this NOP, but maybe you need 3 functions or you have to call them differently, etc.

> Yes, and it also a very good thing that names give many expectations. Names that do not give expectations are useless (e.g. foo, bar).

Again, you took it too literal. I didn't want to imply that we create an API with function `foo1()`, `foo2()`, `foo3()`, ..., `fooN()`, `bar1()`, `bar2()`, ... `barN()`. Of course the API should use meaningful names. However, `keyLastPart` would be meaningful just as meaningful as `keyBaseName`. But because it is a new name, nobody should expect it to work like `keyBaseName`, even if its main purpose is the same.

> > A way to avoid another huge PR that touches everything would be to implement the new API and keep the existing one.
>
> This is definitely a **no-go**. Such things can only be done after 1.0 and only if we made an API totally wrong.

You also **completely** misunderstood what I wanted to say here. I absolutely **do not** want to make a release with both the new and the old API. I just wanted to avoid a single huge PR that is hard to review and (almost) breaks GitHub's UI.

The idea was this:
1. Last release before all of this is done
2. Implement new API, including tests and first few use-cases (e.g. update all of `libs/elektra`) in PR-1. Also mark the old API as deprecated in this PR.
3. Stop merging any PRs that use the old API.
4. Update all the components to use the new API, in PR-2 through PR-N (e.g. one PR per plugin/binding/library/tool).
5. Remove the old API in PR-N+1.
6. Now we can make releases again.

The only goals to have smaller more manageable PRs, nothing else.

> > Are there any large applications using the latest Elektra that could be used for analysis?
> 
> Yes, KDE and GNOME would be perfect

Ok, this time I should have been more precise ;)

I meant applications that are non-experimental and are in real-world use. Unless I missed some huge news, the default versions of KDE and GNOME still don't use Elektra.

I would also prefer and application that was written with Elektra in mind from the start. Otherwise the application may use Elektra in an unusual way to fulfil some pre-existing constraint or to make the update more seamless. Such setups could mess with the results. For example, my LCDproc version copies the whole config into the existing config `struct`s to reduce the code changes needed.
