### ISSUE TITLE
0.9.3 Release Coordination

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3528]
Can we do the release 0.9.3 today? What is still open?

**Comment by robaerd** [comment]
The docker image for ubuntu focal as well as building ubuntu images in the release script are still open. I will try to finish it today.
Sorry it took me longer than expected to finish the script, I had some issues that the debian package couldn't be built with the initial version.

**Comment by markus2330** [comment]
It would be also okay to finish today the essentials (everything mentioned release notes like tar.gz) and create the Ubuntu packages later.

It would be only a not-so-ideal situation if we find out that it is impossible to build the Ubuntu packages because of something in the source #3522, but actually it is also not a big deal: as we automated the release, we simply make 0.9.4.

@robaerd is there anything still open in the #3524? Did you already test it with Jenkins?

@mpranj do you have time today for the release?

**Comment by markus2330** [comment]
@mpranj did you look through https://github.com/ElektraInitiative/libelektra/milestone/24?

**Comment by mpranj** [comment]
@markus2330 as soon as #3524 is merged @robaerd will need to add the pipeline to Jenkins and test it on the actual infrastructure. I think a release today would be a bit rushed. We could release tomorrow in the evening, if @robaerd can get the basics working until then.

**Comment by markus2330** [comment]
Will today be the day?

**Comment by mpranj** [comment]
From the [Jenkins logs](https://build.libelektra.org/job/libelektra-release/) it seems that quite some work is being done to automate the release.

@robaerd it looks like the tests are failing because of no permission to write to `/etc/kdb`.

**Comment by robaerd** [comment]
I ran into some issues while testing on jenkins. Currently the pipeline is configured to use my fork of the repos since a few fixes needed to be made.
The release script currently requires root priveledges to run because of `make install` and the `dpgk -i *.deb` command. For `make install` I could simply set the CMAKE_INSTALL_PREFIX flag, but I'm not really sure how to  install the .deb package without root permissions.

**Comment by markus2330** [comment]
> Currently the pipeline is configured to use my fork of the repos since a few fixes needed to be made.

Which repo do you mean? https://github.com/robaerd/libelektra/commits/master seems to not contain any fixes the master does not contain.

If there are any other important fixes, we need to get this fixes into our master, otherwise we cannot make the release. Can you create a PR?

> The release script currently requires root priveledges to run because of make install

Please always write the error messages. I think for this release it will be okay to use root. The build is only triggered manually anyway?

At a later point, we probably want to create a new docker image where Elektra is installed with a test user who can write to system configuration.

> @robaerd it looks like the tests are failing because of no permission to write to /etc/kdb.

See doc/TESTING.md

For now: simply give the user access to /etc/kdb and the spec folder or run as root.

> and the dpgk -i *.deb command.

Packaging stuff can be moved after the release. For now simply use sudo or similar.

The proper solution (after the release) would be to create a new docker image where the debs are installed during image creation (`apt-get` or similar commands in the Dockerfile).

**Comment by mpranj** [comment]
> The proper solution (after the release) would be to create a new docker image where the debs are installed during image creation (apt-get or similar commands in the Dockerfile).

Sounds good to me!

> @mpranj did you look through https://github.com/ElektraInitiative/libelektra/milestone/24?

Yes. I will see if anything can be fixed quickly before the release, but I think that might interfere with the release automation testing. (New PRs will slow down the CI infrastructure...)
If we want to do the 0.9.3 release today we will have to postpone most leftover issues to the next release.

**Comment by robaerd** [comment]
> If there are any other important fixes, we need to get this fixes into our master, otherwise we cannot make the release. Can you create a PR?

Forgot to mention the branch. https://github.com/robaerd/libelektra/commits/release_automation

> Can you create a PR?

Yes

> The build is only triggered manually anyway?

Yes

>  ...or run as root...
> ... For now simply use sudo or similar.

Since the pipeline for the release currently uses the debian buster image and the jenkins user inside the image is not authorized to call sudo, I think this is not possible. It would probably be necessary to either modify the buster Dockerfile or create a separate one for release which can execute sudo without authentication.

**Comment by mpranj** [comment]
> It would probably be necessary to either modify the buster Dockerfile or create a separate one for release which can execute sudo without authentication.

@markus2330 what if we postpone the debian package tests until the next release?

@robaerd yes, it would probably be better to set up a separate Docker image to test the packages. It could be a minimalistic Debian image where the packages are installed during the image ceration as @markus2330 suggested.

It is possible to run sudo in a container, but I think we should not do this with our standard buster docker image.

**Comment by markus2330** [comment]
> what if we postpone the debian package tests until the next release?

Yes, no problem for me. 0.9.* is an unstable series anyway, so which tests are executed is actually not so important. Without release automation we probably also would not have run them. And now we at least document (via the logs) which tests are run, so we are more transparent than we were before.

What is more important is that we get Ubuntu Focal #3522 packages, ideally also tested (okay if manual this time), as @dev2718 is waiting for them.

> It could be a minimalistic Debian image where the packages are installed

Exactly, it would be actually more clean if the dev packages are *not* installed.

**Comment by markus2330** [comment]
Btw. and it is also totally okay if we release 0.9.4 soon (maybe with release automation as highlight). We should not stress us too much to get 0.9.3 "perfect". The normal build pipeline covers already so much, so a build that run through that has already a quite high standard.

**Comment by mpranj** [comment]
Ok, then @robaerd let's do a release with whatever is working right now. Don't start working on any new problems like the docker image.

> What is more urgent is that we get Ubuntu Focal #3522 packages, ideally also tested (okay if manual this time), as @dev2718 is waiting for them.

They are built anyway, I can manually import them to the repo. This should not be a showstopper.

**Comment by markus2330** [comment]
Ubuntu packages work now :1st_place_medal: (#3522)

I agree as you said in #3530, let us get this release on the road and fix the remaining small things later.

I am today probably not on the computer, if at all quite late in the evening. But that shouldn't be a problem for the release.

**Comment by mpranj** [comment]
I will prepare parts of the release right now and finish up also late in the evening or tomorrow morning.

**Comment by mpranj** [comment]
The release is basically done, based on [this](https://build.libelektra.org/blue/organizations/jenkins/libelektra-release/detail/libelektra-release/76/pipeline) jenkins run. I will wait for the builds to finish (website as well) before announcing on github and elsewhere.

Thanks to @robaerd for making this so easy. **Great** job! I think I am also leaning towards full automation now.

The Alpine release image is already pushed.

**Comment by markus2330** [comment]
Thank you both :sparkling_heart: 

Please tell us in #676 when we can announce (and where you already did).

**Comment by markus2330** [comment]
I am making minor fixes in the release notes, PR will come soon.

**Comment by mpranj** [comment]
Thank you to all Elektra developers for making this release possible! I'm already looking forward to the next one. 😃
