### ISSUE TITLE
CMake Release Parameters.

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3531]
In #3530 @robaerd noted that `scripts/dev/configure-debian` is not suitable for our release automation.

We should decide on some sane CMake parameters to be used for release builds. If there are any opinions, please do not hesitate to contribute here.

@robaerd please adapt the release scripts later to whatever is decided here.

**Comment by markus2330** [comment]
Testing the manual installation should rather have low priority. It is basically the same as the packages anyway, and the packages solve many problems a `make install` in Docker image creation time would have. It is a nice-to-have at best. We should rather focus on packages.

Btw. in doc/todo/RELEASE the builds done with scripts/dev/configure-debian are actually never installed.

Btw2. that ~e/scripts/configure-debian (the wrong path) still is in doc/todo/RELEASE, is a quite clear indication that these things were actually not really done the last releases :wink:
