### ISSUE TITLE
macOS: python bindings segfault

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3539]
Homebrew revently updated the python packages with a seemingly minor update.
Around this time the python bindings tests started to fail with a segfault. The update may or may not be relevant.

It fails on my machine as well as Cirrus and Travis CI.

## Actual Result

```
97% tests passed, 9 tests failed out of 267
Label Time Summary:
bindings    =   8.05 sec*proc (25 tests)
kdbtests    = 414.74 sec*proc (112 tests)
memleak     = 413.33 sec*proc (132 tests)
Total Test time (real) = 402.48 sec
The following tests FAILED:
	 34 - test_kdb.py (SEGFAULT)
	 35 - test_key.py (SEGFAULT)
	 36 - test_keyset.py (SEGFAULT)
	 37 - test_tools_backendbuilder.py (SEGFAULT)
	 38 - test_tools_backendparser.py (SEGFAULT)
	 39 - test_tools_modules.py (SEGFAULT)
	 40 - test_tools_plugindatabase.py (SEGFAULT)
	 41 - test_tools_pluginspec.py (SEGFAULT)
	 42 - test_tools_specreader.py (SEGFAULT)
```

## System Information

- Elektra Version: master
- macOS, Cirrus-CI, Travis-CI
- Versions of other relevant software:
  - python@3.8 3.8.6 (cirrus)
  - python@3.8 3.8.6_1 (my machine)

**Comment by mpranj** [comment]
I think I found one problem: the homebrew python version is not used at all. I'll try to fix this ..

**Comment by markus2330** [comment]
Thank you so much for reporting and looking into it!
