### ISSUE TITLE
ini: removes parts of names

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#354]
there is a critical bug that destroys names in the ini files.

```
> kdb rm -r user/inibug
> kdb set user/inibug/MyApp/mykey new_value
> kdb set user/inibug/binarytest
> kdb set user/inibug/debienna/test value
> kdb export user/inibug ini
MyApp/mykey = new_value
[binarytest]
st = value
```
@tom-wa I am not sure when it was introduced, but I think its better if you debug/fix it because you worked with ini recently.

**Comment by fberlakovich** [comment]
Some info I could gather: the bug is rooted in `getIniName`. The bug happens when the previously written key is a section (in this case `user/inibug/binarytest`), but the next key is not below this section (in this case `user/inibug/debienna/test`). `getIniName` then incorrectly treats the key as below the section key and the expression `(char *)keyName(key)+strlen(keyName(section))+1` starts at a wrong position.

**Comment by markus2330** [comment]
@tom-wa please also provide a testcase for regressions.

**Comment by markus2330** [comment]
Build server still has not built it (see #160)

@manuelm if you find time, would be good if you can install ruby-ronn

**Comment by omnidan** [comment]
This still isn't fixed, running those commands with the latest elektra build results in:

```
MyApp/mykey = new_value
[binarytest]
debienna/test = value
```

`debienna/test` shouldn't be under the `[binarytest]` section.

**Comment by tom-wa** [comment]
this particular case should work using the autosections flag.
the problem can't really be fixed in the current version because the plugin has ne concept of ordering, but i've already found a solution for it in the newer version that should be ready in about a week.

**Comment by fberlakovich** [comment]
@markus2330: since this bug is rooted in the new implementation of ini, could you please assign @tom-wa. For some reason I cannot assign him.

**Comment by markus2330** [comment]
@fberlakovich thanks for the hint. Could you please also comment on #377?

**Comment by markus2330** [comment]
Seems to work nicely now, new output:
```
[MyApp]
mykey = new_value
[binarytest]
[debienna]
test = value
```

**Comment by omnidan** [comment]
Yep, works for me too.
