### ISSUE TITLE
improve logs for release

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3541]
- [x]  readelf: only of core available. Better make a subdir where all readelf outputs of all libs are
- [x] installed_files: please cut the common prefix (./home/jenkins/workspace/libelektra-release@2/system)
- [x] size: also here please cut the common prefix (simply `cd` to the directory to make the ls from there, do not forget to change back)
- [x] verbosity of test running: only run_all shows all output (wanted behavior) but not run_all_full or run_all_static
- [x] MemoryChecker: can we give them better names? Or some index which number is which test?
- [x] the version sub-dir in debian is not needed (as it is always $VERSION-1). The Debian version, however, might be useful (buster, ...)

**Comment by robaerd** [comment]
> MemoryChecker: can we give them better names? Or some index which number is which test?

I don't think I understand this question. Currently we do not store logs from the MemoryChecker. The MemoryChecker already prints to stdout in following format [NR]/135 MemCheck #[TEST_NR]: [TEST_NAME]

**Comment by markus2330** [comment]
I am referring to: https://build.libelektra.org/job/libelektra-release/65/execution/node/108/ws/0.9.2/memcheck/ but probably we do not need them in the logs of ~elektra-ftp anyway?

**Comment by robaerd** [comment]
Since you mentioned in #3530 that the MemoryCheck tests should be removed from the release pipeline, storing them in ~elektra-ftp wouldn't be necessary anymore.
I previously only archived them so @mpranj could take a look at them.
