### ISSUE TITLE
website: rss urls point to localhost and broken links

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3543]
Somehow for each release there is a new reason why the RSS feed is broken and points to localhost.

https://github.com/ElektraInitiative/libelektra/blob/aace28621939164542a9dd4a710968783ae4cd02/src/tools/website/application-config.json.tpl#L6

Can we change this to default to the real website @markus2330?

- [x] Fix URL in rss feed.
- [ ] Remove backend references
- [x] RSS entries (the title) are broken links. "0.9.3 Release" links to broken link: `https://www.libelektra.org/undefined9b9e8889-0c77-45ce-8441-8bdf26a110ac.html`

**Comment by markus2330** [comment]
Of course, and you can remove the "backend" section if you already on it :wink:

**Comment by mpranj** [comment]
Seems that my changes broke the website.. I will try to fix it quickly by building only the website until it is resolved. Sorry for the inconvenience.

**Comment by markus2330** [comment]
Good that you found out before sending out to everyone :+1:

**Comment by mpranj** [comment]
Yes, it's fixed again. Do you have any additions (news/website)? Otherwise I'll reactivate the full pipeline for a last rebuild before we send the news out.

**Comment by markus2330** [comment]
> Do you have any additions (news/website)?

No, everything looks amazing :fireworks: 

> Otherwise I'll reactivate the full pipeline for a last rebuild before we send the news out.

Is this needed? There were already successful builds after the release tags.

Maybe you can retrigger the jobs of the commit with the tag 0cb41ac378c782b5741692fd01c70f66e8c77503, it looks like it had failed to build

**Comment by mpranj** [comment]
> Is this needed? 

No, but it makes the CI badges on the website and github appear green, which looks nice to me. 😄 

> Maybe you can retrigger the jobs of the commit with the release tag

Great idea, done!

**Comment by mpranj** [comment]
I just found another problem with RSS links:

RSS entries (the title) are broken links. "0.9.3 Release" links to broken link: `https://www.libelektra.org/undefined9b9e8889-0c77-45ce-8441-8bdf26a110ac.html`

**Comment by markus2330** [comment]
Thank you for pointing out! My RSS reader (thunderbird) does not even show this link (nor subject nor title is a link), so I never noticed.

A validator, however, confirms your problem and also shows others (e.g. a duplicated guid): https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.libelektra.org%2Fnews%2Ffeed.rss
