### ISSUE TITLE
ini: allow repeated entries

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#355]
automatically build up arrays on repeated entries:
```
[sec]
a=1
a=2
```
(when parameter array is given), see also #182 

So above would result in the following keyset:
```
sec/a   with metadata array="#1"
sec/a/#0=1
sec/a/#1=2
```

The keyset without the metadata `array`, the ini file would be written to:
```
[sec]
a=
a/#0=1
a/#1=2
```

@strahlex any opinions on that?

**Comment by strahlex** [comment]
Looks fine for me. Context is representing a array in an INI file e.g.:
````ini
[DISPLAY]
program = .ngc GCode file
program = .py Python file
````
resulting in list like
````python
program = ['.ngc GCode file', '.py Python file']
````

**Comment by markus2330** [comment]
Yes, exactly, an array is conceived to be transformed to container datastructures, such as a list in python.

**Comment by markus2330** [comment]
Should work now (needs mount option "array"), e.g.:
```
$ kdb mount example.ini /example ini array=
$ cat `kdb file user/example`
key = value1
key = value2
key = value3
$ kdb export user/example ini
key = 
key/#0 = value1
key/#1 = value2
key/#2 = value3
```

**Comment by markus2330** [comment]
Seems to work now with option "array"
```
[sec]
a=1
a=2
```
in Elektra with:
```
$ kdb mount  $(realpath test.ini) system/ini/array ini array=
$ kdb ls system/ini/array
system/ini/array
system/ini/array/sec
system/ini/array/sec/a
system/ini/array/sec/a/#0
system/ini/array/sec/a/#1
$ kdb set system/ini/array/sec/a/#1 x
```

Questionable, however is:
```
kdb set system/ini/array/sec/a/#2 new 
```
leads to the file:
```
[sec]
a = 1
a = x
a/#2 = new
```

**Comment by strahlex** [comment]
It would be preferable if writing works too. However, read-only should be sufficient right now.

**Comment by markus2330** [comment]
Of course, writing configuration is an equally important goal for Elektra. I add the missing features in the issue  #388.

**Comment by markus2330** [comment]
Seems to work now in both directions!
