### ISSUE TITLE
Failing tests after installing deb package and dependency problem on Ubuntu Focal

### ISSUE THREAD

**Issue by robaerd** [ElektraInitiative/libelektra#3556]
## Ubuntu Focal (20.04)

There is a problem with the dependencies for the elektra-qt-gui package.

The binary dependency (qml-module-qtquick-controls-styles-breeze) is not available for Ubuntu Focal, therefore the installation for libelektra4-all fails.

```
dpkg: dependency problems prevent configuration of elektra-qt-gui:
 elektra-qt-gui depends on qml-module-qtquick-controls-styles-breeze; however:
  Package qml-module-qtquick-controls-styles-breeze is not installed.

dpkg: error processing package elektra-qt-gui (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libelektra4-all:
 libelektra4-all depends on elektra-qt-gui; however:
  Package elektra-qt-gui is not configured yet.

dpkg: error processing package libelektra4-all (--install):
 dependency problems - leaving unconfigured
```

After the (forced) installation following tests fail: dump, testmod_gopts, testmod_kconfig, testmod_lua, testmod_specload. I tested this with the 0.9.3 package on Ubuntu Focal and with the 0.9.2 package from our repo ubuntu-bionic-repo.libelektra.org on Ubuntu Bionic and in both cases the same tests fail. 

The results for dump, gopts and scpecload are the same as in #2856.

```
LUA         TESTS
==================

Testing simple variable passing...
There are 1 warnings
buffer is: warnings/#00
number: C01330
description: Plugin Misbehavior
module: kdb
file: /home/jenkins/workspace/libelektra-release/libelektra/src/libs/elektra/plugin.c
line: 300
reason: Open of plugin returned unsuccessfully: lua. Reason contains plugin, see other warnings for details
reason: 
reason: 
/home/jenkins/workspace/libelektra-release/libelektra/src/plugins/lua/testmod_lua.c:24: error in test_variable_passing: warnings in kdbOpen for plugin lua
number: C01200
description: : Installation
module: : lua
at: /home/jenkins/workspace/libelektra-release/libelektra/src/plugins/lua/lua.cpp:170
reason: : module 'kdb' not found:
	no field package.preload['kdb']
	no file '/usr/local/share/lua/5.3/kdb.lua'
	no file '/usr/local/share/lua/5.3/kdb/init.lua'
	no file '/usr/local/lib/lua/5.3/kdb.lua'
	no file '/usr/local/lib/lua/5.3/kdb/init.lua'
	no file '/usr/share/lua/5.3/kdb.lua'
	no file '/usr/share/lua/5.3/kdb/init.lua'
	no file './kdb.lua'
	no file './kdb/init.lua'
	no file '/usr/local/lib/lua/5.3/kdb.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.3/kdb.so'
	no file '/usr/lib/lua/5.3/kdb.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './kdb.so'
mountpoint: : 
configfile: : 
/home/jenkins/workspace/libelektra-release/libelektra/src/plugins/lua/testmod_lua.c:24: error in test_variable_passing: error in kdbOpen for plugin lua
/home/jenkins/workspace/libelektra-release/libelektra/src/plugins/lua/testmod_lua.c:24: fatal in test_variable_passing: could not open lua plugin
error: testmod_lua
```

```
Running testmod_kconfig

[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from kconfig
[ RUN      ] kconfig.read_and_write_test
/home/jenkins/workspace/libelektra-release/libelektra/src/plugins/kconfig/testmod_kconfig.cpp:45: Failure
Expected equality of these values:
  true
  fileA.is_open ()
    Which is: false
Could not open /usr/share/libelektra-test/test-data/kconfig/test_validrc
error: testmod_kconfig
```

**Comment by markus2330** [comment]
Thank you very much for reporting this problem! I split up the Debian problem to #3557 as it looks unrelated, maybe we need even more issues for the individual failing tests.

> qml-module-qtquick-controls-styles-breeze

This particular problem doesn't look serious enough that demands an action now. We can again simply remove this dep. As this is already the second problem of this kind I started a discussion how we can really deal with the problem in #3558.

> testmod_specload

This is a packaging problem you can actually fix: the file bin/elektra-specload-testapp is missing in the installation (see #2856). In general, there are plenty of warnings when building a debian/ubuntu packages, including many not installed files. I think its best if you first fix these reported problems, and then we look into failing test cases again.

**Comment by robaerd** [comment]
> I think its best if you look at the reported problems before we look into failing test cases.

Will do.

> @robaerd when did the tests fail? With make run_all or kdb run_all?

The tests fail with `kdb run_all`. With `make run_all` all tests succeed.
