### ISSUE TITLE
conditionals: error messages absolute/relative keys

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#356]
How to distinguish absolute/relative keys? Or are there only relative keys? What if it is used as global plugin? (Please update docu)

What is the difference of string/double value? Why is the grammar `('String' | '1234.56' | Key | '')`? (Please update docu)

The errors are sometimes misleading, e.g.:

    kdb mount conditionals.dump /tmount/conditionals conditionals dump
    kdb set user/tmount/conditionals/fkey 3.0
    kdb set user/tmount/conditionals/hkey hello
    kdb setmeta user/tmount/conditionals/key check/condition "(hkey == 'hello') ? (fkey == '3.0')" # success
    kdb setmeta user/tmount/conditionals/key check/condition "(hkey == 'hello') ? (fkey == '5.0')" # fail

Fails with the error:
```
The command setmeta failed while accessing the key database with the info:
Error (#135) occurred!
Description: Validation failed
Ingroup: plugin
Module: conditionals
At: /home/jenkins/workspace/workspace/elektra-git-buildpackage-wheezy/libelektra/src/plugins/conditionals/conditionals.c:427
Reason: Validation failed for key user/tmount/conditionals/key: Value: 
Mountpoint: user/tmount/conditionals
Configfile: /home/markus/.config/conditionals.dump.16045:1447259812.164148.tmp
```

Expected error should include that `fkey` is not `3.0`.

**Comment by markus2330** [comment]
This is still open, the error message is not so good. If it isn't an easy fix we can delay it.

**Comment by tom-wa** [comment]
didn't consider it to be used as a global plugin when i wrote it, currently the keys are all relative to the parent key. 
not really sure how to differentiate between a relative and an absolute name, but i think using "./" as a prefix for relative keynames would work, any suggestions ? 
 
the error messages should all be fixed with #503

**Comment by markus2330** [comment]
Thank you! The error messages were the important part! Most plugins are disabled for global-plugins (including conditionals) for the release anyway.

The absolute vs. relative is not so easy if you want to specify namespaces.

**Comment by markus2330** [comment]
Proposal: relative keys start with `./`

**Comment by markus2330** [comment]
Error message is now much better! Thank you!

```
The command setmeta failed while accessing the key database with the info:
Error (#135) occurred!
Description: Validation failed
Ingroup: plugin
Module: conditionals
At: /home/jenkins/workspace/workspace/elektra-git-buildpackage-wheezy/libelektra/src/plugins/conditionals/conditionals.c:645
Reason: Validation of (hkey == 'hello') ? (fkey == '5.0') failed. ((fkey == '5.0') failed)
Mountpoint: user/tmount/conditionals
Configfile: /home/markus/.config/conditionals.dump.12049:1461764276.353011.tmp
```
