### ISSUE TITLE
yamlcpp: tests fail on macOS

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3564]
`yamlcpp` tests are failing on macOS (see [cirrus](https://cirrus-ci.com/task/6007215985262592)).

Happened after Keyname overhaul, but unsure if it is related. The tests are not failing on Linux.

Full log: [tests.log](https://github.com/ElektraInitiative/libelektra/files/5588551/tests.log)

**Comment by sanssecours** [comment]
As far as I can tell this issue is describes the same problem as issue #3561. At least in my tests the code does not crash anymore, as soon as I [remove the call to `node.as<bool> ()`](https://github.com/ElektraInitiative/libelektra/issues/3561#issuecomment-728286492).

**Comment by mpranj** [comment]
Thank you for looking into it, you're absolutely right.
I thought it only failed on ASAN builds there.

Closed as duplicate of #3561.
