### ISSUE TITLE
keyname overhaul regressions

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3570]
- [ ] go bindings renames in test cases, comments and main readme: problems found, see #3458
- [x] qt gui broken, only shows namespaces without :
- [x] have a look at code coverage
- [ ] WebUI (low prior, not for 0.9.4)
- [X] external applications
  - [X] dq

**Comment by markus2330** [comment]
@kodebach I couldn't find many problems, the main problems that still exist are listed above.

kconfig+lcdproc are not tested but with grep I could not find any user/ or system/ key.

**Comment by kodebach** [comment]
`lcdproc` should not have problems, it uses `kdb gen` and that is fully tested, so a recompile might be needed (if anybody is using the Elektra version already), but then it should work.

I did a quick check of the Qt GUI, but I didn't find any obvious problems, so I'll have to look more closely at the code. Since I have no experience at all with Qt this might take sometime...

What exactly do you mean by "have a look at code coverage"?
[Our coveralls](https://coveralls.io/builds/35310402/source?filename=src/libs/elektra/keyname.c) reports that `keyname.c` is almost completely covered except for `keyGetUnescapedName` and some `mmap` paths, plus some minor things.

**Comment by kodebach** [comment]
For the Go stuff see ElektraInitiative/go-elektra#10

**Comment by kodebach** [comment]
Sidenote: If we setup a build job that builds `ubuntu-bionic` packages from master, we could add a setup Travis job in  [ElektraInitiative/go-elektra](https://github.com/ElektraInitiative/go-elektra) that tests the go binding against that package. Then we can fix go bindings before releases. (We could also build and install Elektra directly from master, but that's just unnecessary CI time for the go project.)

**Comment by kodebach** [comment]
For the elektrad fixes see #3588

**Comment by markus2330** [comment]
Thank you so much for these fixes :sparkling_heart: 

> I did a quick check of the Qt GUI, but I didn't find any obvious problems, so I'll have to look more closely at the code. Since I have no experience at all with Qt this might take sometime...

So it shows you all the keys you have? For me all hierarchies are empty...

> What exactly do you mean by "have a look at code coverage"?

You did what I meant. So it is done.

> If we setup a build job [...] go-elektra

Something like this is planned. And we also want to run the go tests in the main pipeline to not break master in future.

> For the elektrad fixes see #3588

:rocket:

**Comment by kodebach** [comment]
> So it shows you all the keys you have? For me all hierarchies are empty...

No, I see the same thing as you in the UI. I just didn't find obvious problems in the code

> Something like this is planned. And we also want to run the go tests in the main pipeline to not break master in future.

It might also be possible to move all of go-elektra into the main repository. AFAICT the only reason it is separate is that `cgo` uses `pkg-config`, which normally requires Elektra to be installed to find the libraries. But it may be possible to write a "local dev" `elektra.pc` file and point the `PKG_CONFIG_PATH` for `go build` to it's location. But it would certainly require some CMake magic to make it work properly...

**Comment by markus2330** [comment]
I have always been very much in favor of integrating the go repo into the main repo, it was never done because:

1. too much effort or not enough CMake skills of the person doing it
2. go clones the repo during compilation, with separate repos it can clone only the smaller repo

Especially 2. is actually a good reason to keep it separated, so we only integrate it in the main pipeline: #3458

**Comment by kodebach** [comment]
> 2. go clones the repo during compilation, with separate repos it can clone only the smaller repo

That is actually true... A git submodule might be a solution. Then you could clone just the go repo or everything.

**Comment by markus2330** [comment]
I've heard that if you have a problem and want to solve it with git submodule then you have two problems. If it is not like this anymore and we can maybe even integrate kconfig, gsettings-tests (which need to be a separate repo because of license issues) it could be worth a consideration.

**Comment by kodebach** [comment]
> I've heard that if you have a problem and want to solve it with git submodule then you have two problems

I have actually no experience with git submodules... I just remember seeing a few Github projects that use them.

> we can maybe even integrate kconfig, gsettings-tests

I don't think this is a good idea. These are clearly separate projects, while the Go bindings are much more a part of libelektra like all the other bindings. There is also a difference in versioning schemes. IMO there should be a new release of the Go bindings, whenever there is a new release of libelektra (even, if the go bindings are unchanged). For kconfig and gesettings this should not be the case. If we add the Go bindings as a submodule each release of libelektra will automatically link to the appropriate version of the Go bindings.

**Comment by markus2330** [comment]
We are going very OT here: gsettings is currently completely integrated in the main repo (src/bindings/gsettings), only the tests are not. Of course it would be ideal if kconfig gets accepted upstream but till then it is actually also a binding like the others.

Nevertheless, I doubt git submodules will help us, as they will not make the CMake logic easier. So just plumbing everything together in the CI is probably the more reasonable choice.

**Comment by markus2330** [comment]
@kodebach can you update the top post? What is still missing? Is there anything but #3618 missing for 0.9.4?

**Comment by kodebach** [comment]
Updated

Not sure about the state of #3588. I also don't know whether the WebUI itself works (but that is marked as low prio anyway).
I also have no idea what you wanted for the go bindings and what the state of #3458 is. The PR to fix the go binding is still open (https://github.com/ElektraInitiative/go-elektra/pull/10), but AFAIAC it is done.

**Comment by markus2330** [comment]
Ok, sounds like we are ready to go then as WebUI was probably already broken before.

**Comment by markus2330** [comment]
I close this issue, as the problems now have individual issues. The only important left-over is #3896
