### ISSUE TITLE
kdb ls `invalid key`: Bad error message

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3593]
## Steps to Reproduce the Problem

Try either:

```sh
kdb ls user 
kdb ls user:
```

## Expected Result

That I get an error message like:

```
"user" is not a valid key name. A key name consists of [<namespace>:]/<path>.
```

## Actual Result

```
The command kdb ls terminated unsuccessfully with the info:
std::bad_alloc
Please report the issue at https://issues.libelektra.org/
```

## System Information

- Elektra Version: master

**Comment by mpranj** [comment]
Thank you for reporting. I agree that the proposed error message is better. 👍
