### ISSUE TITLE
Use __attribute__((nonnull))

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3594]
It probably would make sense to add [`__attribute__((nonnull))`](https://clang.llvm.org/docs/AttributeReference.html#id18) (see also [gcc](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#Common-Function-Attributes)) to many of our functions.

@markus2330  AFAIK there is (or will be) someone working on the API surface of Elektra. Please assign this issue appropriately.

**Comment by markus2330** [comment]
This can also be done after 1.0.
