### ISSUE TITLE
Remove cascading key from cascading lookup order

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3597]
Currently, `ksLookup` when given a cascading name (e.g. `/abc`) will lookup the cascading name itself as a final step (see code below).

Since we now have the `default:/` namespace, this  doesn't make sense anymore and should be removed.

https://github.com/ElektraInitiative/libelektra/blob/d9a8478478b0009971a070d2990af0b310abfd7e/src/libs/elektra/keyset.c#L1830-L1846

**Comment by markus2330** [comment]
Thank you for creating the issue! Can you also point to the code where the change needs to be done?

**Comment by kodebach** [comment]
Could be combined with #3598, #4477 and/or #4478. In fact #4478 may be required to implement this.
