### ISSUE TITLE
Types of KeySets

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3598]
The different types of KeySets should be made explicit. The types are:

1) "Normal" data: Keys of the namespaces `proc:/`, `dir:/`, `user:/`, `system:/` and `default:/` are allowed to be added to the KeySet. This is the default and what will be created by a simple `ksNew`.

2) Metdata: Only keys of namespace `meta:/` are allowed. This type cannot be created via the public API. It is only created internally in a `keyVNew` call.

3) Cascading keys: Only cascading keys are allowed in these KeySets. This will be needed after #3597 to still allow the use of KeySets as a general map-like data structure. This type of KeySet will be created via `ksNewData` (name open to suggestions).

---

Internally the type of KeySet will be determined by a flag in the `struct _KeySet`.

The public API could be made more intuitive by adding two `typedef`s: `typedef KeySet MetaKeySet` and `typedef KeySet DataKeySet`. These would be used for the return types of `keyMeta` and `ksNewData` respectively.

`ksAppend`, `ksAppendKey` and all other functions that modify the KeySet need to be updated to respect the new flag.

In addition to #3597 `ksLookup` has to modified to ignore the normal cascading lookup in Type 3 KeySets and instead lookup the cascading name directly.

**Comment by markus2330** [comment]
Thank you for creating the issue!

> The public API could be made more intuitive by adding two typedefs: typedef KeySet MetaKeySet and typedef KeySet DataKeySet

DataKeySet sounds contradictory to its purpose as it is about Config, which can be defined as input of applications which is not domain-specific data. What about ConfigKeySet?

**Comment by kodebach** [comment]
> DataKeySet sounds contradictory to its purpose as it is about Config, which can be defined as input of applications which is not domain-specific data. What about ConfigKeySet?

`DataKeySet` would be the one for general data that only allows cascading keys. The KeySets for config data (user:/, system:/ etc) would still just be `KeySet`.

**Comment by markus2330** [comment]
This type of KeySet is not used in the API anyway, so we also do not need to make this typedef.

**Comment by kodebach** [comment]
It would be the return type of the function proposed in point 3 above.

The basic idea would be that these work:

```c
KeySet * ks = ksNew (1, keyNew ("user:/test", KEY_END), KS_END);
assert(ks != NULL);

DataKeySet * dks = ksNewData (1, keyNew ("/test", KEY_END), KS_END);
assert(dks != NULL);
```

But these will fail (= return `NULL`):
```c
KeySet * ks = ksNew (2, keyNew ("/test", KEY_END), KS_END);
assert(ks == NULL);

DataKeySet * dks = ksNewData (1, keyNew ("user:/test", KEY_END), KS_END);
assert(dks == NULL);
```

The use of `DataKeySet` is just for clarity, what makes or breaks the code is `ksNew` vs `ksNewData`

**Comment by kodebach** [comment]
See also #4478
