### ISSUE TITLE
Need to replace Travis CI

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3603]
As far as I understand [this blog post](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), once Elektra is migrated to travis-ci.com (which will happen automatically at some point), Travis CI will basically be useless for us. It seems you only get 10.000 Credits (= 16.67 hours on Linux, or 3.33 hours on macOS) **once**. OSS projects can apply for more, but it seems you need to re-apply every time you need more. AFAIK the credits **do not** replenish monthly.

Other Projects seem to have the same issue: zopefoundation/meta#38

AFAIK everything the Travis CI builds do should be covered by Cirrus CI anyway, but we could also switch from Travis CI to Github Actions. It seems to be completely free for public repositories, according to [the docs](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions). There is also a [migration guide](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions) and Github Actions allows [self-hosting runners](https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners) although that is not recommended for public repos because of security implications.

## Features only in Travis CI

- [X] Mac builds also in Cirrus CI
- [x] macOS+GCC 10
- [ ] Whitespaces in build dir

**Comment by markus2330** [comment]
Thank you for reporting this! I can do the registration but we can also drop Travis. Everything essential should be on our own Jenkins server, exactly for reasons like this.

As @sanssecours started everything about Travis CI and is also doing a lot of its maintenance work, he should be included in any decision. @sanssecours are you maybe today coming to our meeting?

**Comment by kodebach** [comment]
Our Jenkins server doesn't support macOS builds. But the macOS builds on Travis CI were always a problem.
Personally, I dislike how slow the Travis builds are. Cirrus CI seems to be much faster across the board. I have no experience with Github Actions, but a quick search suggests, it is faster than Travis and of course much better integrated into Github.

**Comment by markus2330** [comment]
I started to collect things which are only on Travis CI or were the reasons to have Travis CI (top post, please extend). If we can port some of these things to Jenkins it would be good anyway, even if we decide to keep Travis CI.

**Comment by mpranj** [comment]
Our infrastructure also does not have unlimited resources. At the time it was nice to distribute some of the workload to Travis and Cirrus.

@sanssecours already said that the Travis macOS build job is the only one, where macOS+GCC 10 are tested. We could try to migrate this to Cirrus. Note that Cirrus also has a concurrency limit (especially for macOS), so it would likely increase build times.

Regarding the Travis migration: we can try, but I do not think that we will somehow get more resources than before. We can discuss it quickly in the meeting, if anyone understands the new terms.

**Comment by sanssecours** [comment]
> @sanssecours are you maybe today coming to our meeting?

Most probably not 😊. I think I will work at 17:00. 

I would recommend to switch to GitHub Actions (for the macOS build job) as proposed by Klemens. Its [free for public repositories](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions#about-billing-for-github-actions) and it seems to work reasonably well. I only created workflows for small projects until now though. The experience for larger projects like Elektra might be different.

**Comment by kodebach** [comment]
> Our infrastructure also does not have unlimited resources. At the time it was nice to distribute some of the workload to Travis and Cirrus.

Agreed, I think migrating stuff to Jenkins is not a good idea, unless we expand our infrastructure. When there are many PRs Jenkins already takes quite long to work through the queue. 

> Note that Cirrus also has a concurrency limit (especially for macOS)

IIRC the limits on Cirrus are per User not per Repository. So two PRs by different people don't affect each other.
We also only have 1 full Linux build plus the Link Check and Documentation build on Cirrus right now. So there should be room for more Linux builds as well.

**Comment by mpranj** [comment]
Thank you both for the input! I just started the migration of the travis macOS build to Github Actions.

It's looking very promising.

**Comment by mpranj** [comment]
So we are just missing a build with whitespaces in the path? Good first issue?

**Comment by kodebach** [comment]
AFAICT this is the only thing that is missing, yes.

We could combine this with moving macOS jobs from Cirrus to GitHub actions to increase build speeds (because of better concurrency).

There might also be a simple way to improve the concurrency on Cirrus. It seems our macOS jobs currently use 12 CPU cores (the maximum amount allowed per user). Maybe if we limit each job to 4 Cores Cirrus runs 3 task concurrently?

**Comment by mpranj** [comment]
> Maybe if we limit each job to 4 Cores Cirrus runs 3 task concurrently?

Definitely worth a shot

**Comment by mpranj** [comment]
> Maybe if we limit each job to 4 Cores Cirrus runs 3 task concurrently?

The current [cirrus docu](https://cirrus-ci.org/faq/#are-there-any-limits) suggests we are limited to 1 macOS VM, regardless of CPU count. Thus I think we are limited to the current situation.

**Comment by kodebach** [comment]
Yes, it seems the docs were updated. So the only option to speed up macOS builds would be moving some to GitHub Actions (which currently has a limit of [5 concurrent macOS jobs](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration)).

**Comment by markus2330** [comment]
I asked our admin if we can have some macOS hardware.

**Comment by kodebach** [comment]
How would we use that hardware? Our Jenkins Setup is based on Docker so AFAIK that wouldn't work on macOS. We could use our own hardware as runners for GitHub Actions. But don't even use all of the free GitHub-hosted runners, so why bother?

**Comment by mpranj** [comment]
>  But don't even use all of the free GitHub-hosted runners, so why bother?

In case we stay at GitHub: It would be great to move all current macOS jobs to Actions, to improve build times. 

In case we move to GitLab: GitLab Runner supports macOS build agents, so it does make sense.

Regarding Jenkins: it should also be possible to add a macOS agent and adapt the Jenkinsfile.

I have to say I am a bit hesitant to run our own macOS agent. We would have to implement some virtualization and snapshots to be able to run clean builds. Running "directly" on the hardware would probably lead to lots of maintenance work after failures (since everything is persistent).

**Comment by markus2330** [comment]
I was also thinking about having a machine to log in for debugging purposes. But let's see if we get anything we want to work with.

**Comment by kodebach** [comment]
A machine for debugging purposes might be helpful. But there is similar problem to creating our own macOS build agent. How would we avoid conflicts, if two people log in at the same time? Or would this be a single-user thing?

**Comment by markus2330** [comment]
Afaik is macOS a multi-user operating system. Anyway, such discussions are way too early now, as we do not even know if we get a machine.

**Comment by kodebach** [comment]
> Afaik is macOS a multi-user operating system.

Yes, but Elektra is a global system. Even ignoring that, libraries, compilers and other dependencies are (normally) installed system-wide, so one user can still influence another. If users where completely isolated we wouldn't need containers.

**Comment by mpranj** [comment]
> Yes, it seems the docs were updated. So the only option to speed up macOS builds would be moving some to GitHub Actions (which currently has a limit of 5 concurrent macOS jobs).

I would like to subsequently move some jobs from cirrus to github actions to improve concurrency of macOS builds. I think this could help quite a lot regarding macOS builds which are the slowest on cirrus. The best would likely be to have only one macOS job on cirrus and the rest on GitHub Actions.

Most other jobs are running reasonably fast and it seems Jenkins will be the next bottleneck.

**Comment by kodebach** [comment]
> The best would likely be to have only one macOS job on cirrus and the rest on GitHub Actions.

AFAICT the bottleneck for macOS jobs is the `install` phase. If we could speed up the homebrew installs during the translation of the scripts, it might also help a lot. Even without parallel jobs.

Maybe using a single 
```
brew install A B C ...
```
instead of
```
brew install A
brew install B
brew install C
...
```
could help? I don't know how homebrew works, but maybe this way installs (or a least downloads) happen in parallel. The machine has 12 Threads after all, so we should probably try to use them.

**Comment by mpranj** [comment]
>  I don't know how homebrew works, but maybe this way installs (or a least downloads) happen in parallel.

I have not done any analysis of this, but:
Installs and downloads seem very sequential on my machine. That said, calling install less often should result in some marginal time benefit (only checking dependencies once), but I fear it will not have the huge effect you expect.

I would suggest we do both of these things.

**Comment by kodebach** [comment]
> only checking dependencies once

This may actually be an improvement. IIRC many of the build failures (that aren't actual failed tests) for macOS jobs happen because of connection problems during dependency checks.

**Comment by mpranj** [comment]
Seems like travis-ci.org was finally shut down. We could apply (via support) to receive free open source credits, but I do not think it is worth the hassle.

The remaining task here would be to migrate some/all of the travis linux builds to github actions.

**Comment by markus2330** [comment]
I don't think it is a good idea to migrate to github actions: then we might have the same problem in a few years when github action limits its free use. Hopefully @robaerd can migrate at least one job to our new Mac.

**Comment by mpranj** [comment]
> migrate at least one job to our new Mac.

Ok, but there were only Linux jobs remaining on travis.

> I don't think it is a good idea to migrate to github actions

When multiple builds are running our own infrastructure on Jenkins is still the bottleneck. GitHub would offer much more computing power, even if we have to migrate the jobs again in a few years (which is all hypothetical).
We have definitely spent much less time migrating and maintaining jobs on travis and cirrus than we have spent on Jenkins. We periodically have either no disk space left or some other problem.

**Comment by markus2330** [comment]
>  When multiple builds are running our own infrastructure on Jenkins is still the bottleneck.

There is plenty of additional hardware, I hope we come around to add them as build agents in August.

> GitHub would offer much more computing power, even if we have to migrate the jobs again in a few years (which is all hypothetical). We have definitely spent much less time migrating and maintaining jobs on travis and cirrus than we have spent on Jenkins. We periodically have either no disk space left or some other problem.

There are not only hypothetical reasons (to be independent of companies which need at some point profit to continue doing something) but: Supporting several CIs is definitely the worst option in terms of how much time we need to spend. Jenkins covers more than 90% of our tests. I was never in favor of adding any other CI. It just happened because Elektra is a community project and everyone has the right to add any CI they want (as long as they maintain it).

**Comment by kodebach** [comment]
> The remaining task here would be to migrate some/all of the travis linux builds to github actions.

AFAIK the only remaining part that isn't cover yet are build directories with spaces in the path.

> There is plenty of additional hardware, I hope we come around to add them as build agents in August.

More hardware only helps, if it is fast as well. Especially the IO, which is the bottleneck for many of our tests.

> to be independent of companies which need at some point profit to continue doing something

Then we shouldn't use GitHub at all and self-host everything. However, we already decided that this not a good idea (bad discoverability, high effort and cost).

> Supporting several CIs is definitely the worst option in terms of how much time we need to spend.

I totally disagree. Maintaining the scripts for Cirrus and GitHub Actions is pretty easy, for a pretty big reward. You get multiple independent systems reporting results. This not only results in faster results, but also in more reliability in case of them doesn't work.

If you actually want to minimize time spent on maintaining CI, self-hosted Jenkins is actually the worst option. Using GitHub Actions exclusively would be the least effort. (I'm not saying that would be a good idea either).

> Jenkins covers more than 90% of our tests.

I'm not sure 90% is true. For example, there is not macOS build right now. Also the Jenkins jobs (and our CI in general) has a lot of redundant jobs. For example, building the same configs on different versions of Debian or building configs that are subsets of each other. That actually results in lots of load that could be avoided.

Of course, building e.g. all plugins vs. just a subset has some benefit (e.g. if there are hidden dependencies between plugins). But maybe we should reduce what we build for every PR and do more stuff in a nightly pipeline.

Also while 90% of tests might be covered by Jenkins, I'm also pretty sure that at least 90% of build server maintenance time is spent on Jenkins. At the same time I suspect the majority of bugs is detected not because of Jenkins, but because of another CI, because most of the time Jenkins takes longer to run.

> I was never in favor of adding any other CI. It just happened because Elektra is a community and everyone in the community has the right to add any CI they want (as long as they maintain it).

IMHO other CIs were added, because Jenkins is dreadfully slow and breaks a lot (often for intransparent reasons). Also adding Cirrus CI jobs or GitHub Actions builds is much easier than adding stuff to Jenkins.

---

It might sound like I'm against using Jenkins. That's not the case. Using Jenkins is fine, but I think we should use GitHub Actions more. I don't really see a reason why we shouldn't, as long as it is not our main CI system non of your worries about future limits/cost make much sense. Basically "Einem geschenkten Gaul schaut man nicht ins Maul".

Also the runner for GitHub Actions is open source an can be self-hosted (see https://github.com/actions/runner). So even if we create complicated scripts that can't be migrated easily in the future, there would be a way to keep using them.

**Comment by mpranj** [comment]
I migrated all but one macOS job to GitHub Actions to speed up build times (see #3945). The PR should be done soon.

I think it is best if we leverage the available resources as long as we can. The migration was quite easy after all. It is still possible and quite easy to migrate back and forth between cirrus and github actions.

I also think we should keep Jenkins (or some self-hosted CI) so we are never fully dependent on others.

> For example, building the same configs on different versions of Debian or building configs that are subsets of each other.

Yes, I also think there is quite a bit of redundancy in the tests which should be analyzed and reduced.

**Comment by markus2330** [comment]
Thank you for doing this migration, great job! Lets not put too many jobs on external services, so that we do not have to do such a migration again.
