### ISSUE TITLE
inject argc, argv, environ

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3607]
For the FUSE binding we need some way to inject argc, argv, environ to be used by gopts.

Ideally, this would be fixed together with #2764, so that it is also ensured that gopts is present for FUSE.

**Comment by kodebach** [comment]
In created a quick hacky workaround solution in #3608. This won't be the final solution for various reasons, but it should allow @dev2718 to keep working on their FUSE implementation.

In the end the goal is to integrate the functionality into a new version of `kdbOpen` (together with `kdbEnsure`). But I don't know when I will find time to do that, or how long it will take to get it done (could be weeks). So I created this hacky solution for. 

@dev2718 You should probably just merge #3608 into a branch of your fork and use it until the permanent solution is done. This is how you use it:
https://github.com/ElektraInitiative/libelektra/blob/dad3f19640657bd13ffe8bcd5166d2a1d5c4de2e/src/bindings/swig/python/tests/test_gopts.py#L86-L89
