### ISSUE TITLE
ksDeepDup doesn't deep dup metadata

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3609]
The current `ksDeepDup` **does not** create a deep copy of metadata. So the new KeySet is not fully independent of the old one.

Deep copies of metadata were not needed before we had `keyMeta`, because `keySetMeta` always uses `ksAppendKey`. But since now `keyMeta` exists the user could do:

```c
Key * k = keyDup (orig);
Key * m = ksLookupByName (keyMeta (k), "meta:/type", 0);
keySetString (m, "long");
```

Now of course `keyString (keyGetMeta (k, "type"))` is `"long"`. But if I'm not mistaken, the fact that we used a shallow copy of the metakeys means `orig` was also modified and `keyString (keyGetMeta (orig, "type"))` is `"long"`.

This is even worse, if `orig` has `KEY_FLAG_RO_META` set.

**Comment by markus2330** [comment]
Thank you for reporting the problem!

I think we should make the metakeys completely readonly, then a ksDeepDup is not necessary. Making them readonly force the users to always duplicate on any change, realizing a COW.

**Comment by kodebach** [comment]
Obsolete. See #3610
