### ISSUE TITLE
No documentation how to build specific Python bindings

### ISSUE THREAD

**Issue by strahlex** [ElektraInitiative/libelektra#361]
https://github.com/ElektraInitiative/libelektra/tree/9ff195d5f5a7777b83f19f7ca6a43dd61b966bbb/src/bindings/swig

and

    https://github.com/ElektraInitiative/libelektra/blob/master/doc/COMPILE.md

provide some help on building the Python bindings. However, nothing mentions how to explicitly the Python2 or Python3 bindings.

**Comment by markus2330** [comment]
@manuelm can you enlist all plugin names in the docu? (with short description)

**Comment by markus2330** [comment]
It seems like that swig_python2 and swig_python are only enlisted in:

- cmake/ElektraCache.cmake
- scripts/configure-debian-wheezy
- and obviously their usage in src/bindings (and src/plugins)

Btw. there seem to be some leftovers of swig_python3 in cmake/ElektraCache.cmake (with a TODO marker :camel:)
