### ISSUE TITLE
doc.libelektra.org/api/master/ outdated

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3627]
The docu on https://doc.libelektra.org/api/master/ does not reference current master at all.

Edit: the `latest` symlink at least seems to be working.

**Comment by markus2330** [comment]
Thank you for reporting!

**Comment by markus2330** [comment]
The names of the symlink should also be in-sync with the terms (master latest) as used in #3623

**Comment by robaerd** [comment]
Could it be that **/api/master doesn't actually belong here? In the docu (doc/API.md) only `current` and `latest` are described, where **/latest should contain the current master docu.

Regarding docu in #3623, currently in the Release pipeline the docu is only pushed to the `doc` git repo and doesn't update doc.libelektra.org/api/. How was this updated in the previous releases? I could see that the **/api folder is actually the [doc git repo](https://github.com/ElektraInitiative/doc/tree/master/api) but `git remote -v` doesn't return anything.

**Comment by mpranj** [comment]
> **/api folder is actually the doc git repo but git remote -v doesn't return anything

This is the doc repo where we push to publish the docs. I think the https://github.com/ElektraInitiative/doc repo is just a mirror.

Maybe `master` was added manually once and it is undocumented.

**Comment by robaerd** [comment]
So a push to https://github.com/ElektraInitiative/doc is enough to update  https://doc.libelektra.org/api ?

> The names of the symlink should also be in-sync with the terms (master latest) as used in #3623

This would require renaming `latest` to `master` and  renaming `current` to `latest`. In the end only `latest` and `master` would exists, where `latest` would be a symlink to a release e.g. 0.9.4/ and `master` would just be a folder containing the docu built of the master branch. Did I understand this correctly?

**Comment by mpranj** [comment]
> So a push to https://github.com/ElektraInitiative/doc is enough to update https://doc.libelektra.org/api ?

No, you need to add the community server as a remote and push there too. So you push to github and then to community too, there is no automation.

**Comment by robaerd** [comment]
Thank you for the clarification! I will add this to the release pipeline.

**Comment by robaerd** [comment]
I changed the api docu terms in #3623. After this PR is merged, the only thing left to do would be to also change these terms in the [doc repo](https://github.com/ElektraInitiative/doc) and its git mirror on the community server.

**Comment by robaerd** [comment]
https://doc.libelektra.org/api/master/ now references current master and  https://doc.libelektra.org/api/latest references latest released version.
