### ISSUE TITLE
kdb upgrade

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3633]
Not sure, if we really want this for 0.9.4 (seems we want to release it sooner rather than later). But I mentioned a new `kdb upgrade` tool in the release notes to handle upgrading mountpoints to the new keyname scheme.

I can implement the tool this week (probably tomorrow), but such a tool should probably be tested quite a bit. I won't have time for that.

---
@markus2330 @mpranj

**Comment by markus2330** [comment]
Yes, it would be amazing to have but probably the migration 0.8 -> 1.0 is actually the more important migration. So it is okay to release 0.9.4 without the migration tool. If there are some delays in the release, we can of course already ship 0.9.4 with the tool, potentially also with little testing as the tool is not immediately mission critical. (If there is a problem, people will be able to wait for 0.9.5 or even later).

**Comment by kodebach** [comment]
The least we should do is package this https://github.com/ElektraInitiative/libelektra/issues/3575#issuecomment-735446701 into a script and ship it as a kdb tool. Then there is at least something, even if it isn't well tested.

**Comment by markus2330** [comment]
Thank you for reminding. If we provide such a hack, it is imho better if we are transparently about it and paste the script into the release notes. Then the people have some idea about which limitations the script might have.

**Comment by kodebach** [comment]
> if we are transparently about it and paste the script into the release notes

Yes that might be better. Ideally with an link to the issue, in so that there is a common location to report problems.

**Comment by mpranj** [comment]
The script was added to the release notes. I will close the issue for now. If there are any plans to improve the upgrade procedure (e.g. shipping a tool) please reopen.
