### ISSUE TITLE
delete debian branch

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3643]
@robaerd can we already safely remove the debian branch?

**Comment by robaerd** [comment]
Yes, the debian branch can be safely removed.

The only things that are in the debian branch and are **not** adopted with CPack are the *.examples and *.lintian-overrides files. But you already stated in https://github.com/ElektraInitiative/libelektra/pull/3583#issuecomment-740413642 that they are not necessary anymore.
> *examples: I do not see much benefit in installing parts of the source. But I am also okay if it is done as part of the normal documentation installation.
> *.lintian-overrides: As we were not lintian clean anyway, forget about this.

**Comment by markus2330** [comment]
Perfect! I deleted the debian branch now.
