### ISSUE TITLE
Plist? Passwords?

### ISSUE THREAD

**Issue by magnusviri** [ElektraInitiative/libelektra#3660]
I can't find any statements in the documentation about plist support or storing secrets like passwords. I realize this isn't a password manager but do you have any intention of working with them to retrieve secrets?

**Comment by kodebach** [comment]
I don't think we currently have a plugin that supports plist files.

For password and secret storage, you may take a look at the `crypto`, `fcrpyt` and `gpgme` plugin written by @petermax2.
