### ISSUE TITLE
Array specifications (in TOML and others)

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3671]
**Note:** I used the `toml` plugin as an example, but the problem also occurs with other plugins that don't support metadata.

If there is some specification for an array mounted at `spec:/mountpoint`, e.g.

```ini
[]
mountpoint = test.toml
infos/plugins = toml

[myarray]
array =

[myarray/#]
type = long
```

We can produce a similar thing with:

```sh
sudo kdb meta-set "spec:/mountpoint" mountpoint test.toml
sudo kdb meta-set "spec:/mountpoint" infos/plugins toml
sudo kdb meta-set "spec:/mountpoint/myarray" array ""
sudo kdb meta-set "spec:/mountpoint/myarray/#" type long

sudo kdb spec-mount /mountpoint
```

The correct way to add entries is to first increase the size of the array and then add entries. Otherwise, the `spec` plugin will not correctly copy the metakeys needed for validation.

```sh
kdb meta-set "user:/mountpoint/myarray" array "#0"
kdb set -N user "/mountpoint/myarray/#0" 42

kdb meta-get "user:/mountpoint/myarray" array
#> #0

kdb get /mountpoint/myarray/#0
#> 42

cat $(kdb file /mountpoint/myarray/#0)
#> Using name user:/mountpoint/myarray/#0
#> myarray = [42]
```

This seems to work, but this is only because `42` was a valid `long` value. In fact, this doesn't work with the `toml` plugin (and many others), since it doesn't really support metadata. Therefore the `kdb meta-set` call will do nothing. We can see this, if we remove the TOML file and try to set the `array` metakey again.

```sh
rm $(kdb file /mountpoint/myarray)
kdb meta-set "user:/mountpoint/myarray" array "#0"

kdb meta-get "user:/mountpoint/myarray" array
#> 

cat $(kdb file /mountpoint/myarray/#0)
#> Using name user:/mountpoint/myarray/#0
#> myarray = []
```

Interestingly, the `toml` plugins does recognize that `myarray` is supposed to be an array, but it doesn't know how to create an array with max index `#0` that doesn't have an element `#0`.

During the following `kdb set` call, the `spec` plugin will only find the `array` metakey of the `spec:/` namespace. Since that one only defines an empty array (as a default), it won't add the `type = long` metakey to the array element key, which technically is not an array element as it is beyond the bounds of the `array` metakey.

If we had used an invalid value for the array `/mountpoint/myarray/#0`, this wouldn't be detected.

```sh
kdb meta-set "user:/mountpoint/myarray" array "#0"
kdb set -N user "/mountpoint/myarray/#0" "not a long value"

cat (kdb file /mountpoint/myarray)
#> Using name user:/mountpoint/myarray
#> myarray = ["not a long value"]
```

This is not the whole story, however. The following makes the whole situation much worse:

```sh
kdb get /mountpoint/myarray/#0
#> not a long value
```

Something is clearly wrong here. This doesn't fit our specification so we should get an error. If we take a closer look, we see that the `toml` plugin correctly produces `array` metadata and therefore `spec` should copy the `type` meta key.

```sh
kdb meta-show /mountpoint/myarray
#> array: #0
#> internal/spec/array/validated:
#> order: 0
```

So what happens?

```sh
kdb meta-show /mountpoint/myarray/#0
#> conflict: 00100
#> conflict/collision: #0
#> conflict/collision/#0: meta:/type
#> conflict/meta:/type: string
#> type: string
```

Per default, the `spec` plugin doesn't produce an error, if there is conflicting metadata. The `toml` plugin doesn't know about the `spec:/` keys and produces a `type = string` metakey. This results in a conflict in, but this is only logged via the metadata and otherwise ignored. The `type` plugin only sees the `type = string` from `toml` and so we never get an error for our invalid configuration.

---

I'm not entirely sure, how to solve this one. One part is clearly to make errors the default in `spec`. Then we at least get an error in `kdbGet`. But we really should get an error during `kdbSet` as well.

One solution would be for the `toml` plugin to support metadata, but that is not a complete solution. If you look closely, you will notice that calling e.g. `kdb meta-set "user:/mountpoint/myarray" array "#0"` could create an invalid configuration (e.g. if `spec:/mountpoint/myarray/#` had the `required` metakey).

A more complete solution would be to create a `kdb array-add` command that adds an element to the array. It would update the `array` metakey and add the element in a single `kdbSet()` call, thereby eliminating the problem. However, this breaks again, if we have something like `spec:/mountpoint/myarray/#/property` or more complex specifications.

AFAICT the only general solution to this is modifying the configuration as a whole instead of bit by bit. `kdb editor` should be a way to do this, but the last time I tried it, there were some problems. It is also hard to impossible to automate `kdb editor`. For automated scripts one should use `kdb import`, but that doesn't do any spec validation.

**Comment by markus2330** [comment]
> One part is clearly to make errors the default in spec.

Yes, I agree.

> One solution would be for the toml plugin to support metadata

Please clarify which kind of metadata it should support. Afaik it already supports `array`, which additional metadata should it store to make it work as you expect?
