### ISSUE TITLE
spec tutorial examples not working

### ISSUE THREAD

**Issue by robaerd** [ElektraInitiative/libelektra#3676]
## Steps to Reproduce the Problem

Do as instructed in src/plugins/spec/README.md

```sh
cp battery.ini $(dirname $(kdb file spec:/))
kdb mount battery.ini spec:/example/battery ni
kdb spec-mount /example/battery
kdb set /example/battery/level low
#> Using name system:/example/battery/level
#> Set string to "low" 
```

and then try to set an invalid value:

```sh
kdb set /example/battery/level x  
#> Using name system:/example/battery/level
#> Set string to "x"
```

## Expected Result

Should fail with error.

## Actual Result

It succeeds.

## System Information

- Elektra Version: master
- Ubuntu Focal Docker Container

**Comment by markus2330** [comment]
Thank you for reporting this problem!

The type plugin changed its syntax, it should now read:

```
[]
mountpoint = battery.ini

[level]
type = enum
check/enum = #3
check/enum/#0 = critical
check/enum/#1 = low
check/enum/#2 = high
check/enum/#3 = full
```

I created a PR  #3678

**Comment by robaerd** [comment]
I'm not sure if I'm doing something wrong, but the tutorial is still not working for me:

```sh
sudo cp battery.ini $(dirname $(kdb file spec:/))
sudo kdb mount battery.ini spec:/example/battery ni
sudo kdb spec-mount /example/battery
#> No metadata "mountpoint" found below spec/example/battery
kdb meta-ls /example/battery/level
#> Did not find key
kdb meta-get /example/battery/level check/enum
#> Key not found
kdb set /example/battery/level low
#> Using name system:/example/battery/level
#> Create a new key system:/example/battery/level with string "low"
kdb set /example/battery/level x
#> Using name system:/example/battery/level
#> Set string to "x"
```

**Comment by kodebach** [comment]
I couldn't reproduce the issue with the commands you posted.

Are you sure that the initial `cp` command was successful? If so, please post the `battery.ini` file you used, because it probably has an error.

`kdb meta-ls /example/battery/level` and `kdb meta-get /example/battery/level check/enum` don't work for me either, but with an `spec:/` namespace (e.g. `kdb meta-get spec:/example/battery/level check/enum`) it works.

**Comment by robaerd** [comment]
Aaaah I just found the error. Thank you for the hint regarding the `cp` command! 
`sudo cp battery.ini $(dirname $(kdb file spec:/))` copied the `battery.ini` file into the file `/usr/share/elektra/specification`. 
The command should actually be `sudo cp battery.ini $(dirname $(kdb file spec:/))/` so `battery.ini` is copied into `/usr/share/elektra/specification/battery.ini`
