### ISSUE TITLE
"kdb meta-get /... array" not working with xerces

### ISSUE THREAD

**Issue by robaerd** [ElektraInitiative/libelektra#3677]
## Steps to Reproduce the Problem

```sh
sudo kdb mount `pwd`/test.xml system:/test xml

kdb meta-get system:/test/sequence array
#>Key not found
```

```sh
kdb ls system:/test
# system:/test
# system:/test/sequence/#0
# system:/test/sequence/#1
```

test.xml:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<test>
  <sequence>11</sequence>
  <sequence>22</sequence>
</test>
```

## Expected Result

Index of last array element should be returned.

## Actual Result

Key not found.

## System Information

- Elektra Version: master

**Comment by markus2330** [comment]
Thank you so much for reporting this problem! I was able to reproduce it!

Seems like that xerces does not yet implement doc/decisions/array.md

**Comment by robaerd** [comment]
I assigned myself to this issue as I would like to work on this for CM H2.
