### ISSUE TITLE
applications link to the exact version of Elektra

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3680]
## Steps to Reproduce the Problem

A CMakeLists.txt:

```
find_package (Elektra REQUIRED)

include_directories (${ELEKTRA_INCLUDE_DIR})
target_link_libraries (... ${ELEKTRA_LIBRARY})
```

and a debian/control of:
```
Depends: ${shlibs:Depends}, ${misc:Depends}
```

## Expected Result

That the application works with the installed version of Elektra or newer.

## Actual Result

```
apt-cache show ...
Depends: llibelektra5 (= 0.9.4-1.3461)
```

So on any upgrade the dependency is not fulfilled.

Afaik this was not the case some time ago.

@robaerd is it possible that the libelektra5 Debian package now returns a different version number than some time ago?

From 1.0 we should link to (> 1.x.y), as we guarantee that applications will continue to work after upgrades.

## System Information

- Elektra Version: master

**Comment by robaerd** [comment]
> @robaerd is it possible that the libelektra5 Debian package now returns a different version number than some time ago?

I think old packages also returned the same package version. See https://ubuntu-bionic-repo.libelektra.org/pool/main/e/elektra/libelektra4-yajl_0.9.3-1.2951_amd64.deb for an example package before CPack was used.

> From 1.0 we should link to (> 1.x.y), as we guarantee that applications will continue to work after upgrades.

For this we would only need to set the variable `CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS_POLICY` to `>=`.

**Comment by markus2330** [comment]
>  For this we would only need to set the variable CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS_POLICY to >=.

Sounds good, let us do it. It is too impractical if someone (I) need to rebuild all Debian packages on any upgrade. And for 1.0.0 we want `>=` anyway.

**Comment by markus2330** [comment]
So the current situation actually forces to recompile applications on every update from the build server, which is really not feasible.

Can you please set CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS_POLICY to >=?

Is there something similar also for RPMs?

**Comment by robaerd** [comment]
Changing `CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS_POLICY` seems to have fixed this issue.

> Is there something similar also for RPMs?

AFAIK when using the `AUTOREQ` tag (equivalent to shlibs autodiscovery), only the individual files/SO without a version are autodiscovered and not the whole package. The corresponding package is selected during the installation by searching what packages can provide these files. Therefore no version restriction is present for the RPMs.
I will however verify if this is really the case in the next days.

**Comment by markus2330** [comment]
I can confirm that the issue is resolved now, in the recent updates no recompilation/reinstallation was necessary anymore.
