### ISSUE TITLE
remove keyCompareByOwner and keyCompareByNameOwner

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3685]
in file src/libs/elektra/keyset.c

keyCompareByOwner has to be removed, keyCompareByNameOwner has to be removed and calls have to be replaced with keyCompareByName.

**Comment by a-kraschitzer** [comment]
I would like to take this over

**Comment by mpranj** [comment]
Closed via #3790 (origin: #3775) thanks to @a-kraschitzer!
