### ISSUE TITLE
elektraCalloc is non-standard

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3686]
`elektraCalloc` uses a different API than the standard `calloc`. IMO we should fix that.

Concretely, we should change

https://github.com/ElektraInitiative/libelektra/blob/758d002d44764dabc8cdce4635de8285a5f99e00/src/libs/elektra/internal.c#L289-L295

into 

```c
 void * elektraCalloc (size_t count, size_t size) 
 { 
// ...
 	void * ret = calloc (count, size);
// ...
 } 
```

and then update all existing `elektraCalloc (...)` to `elektraCalloc (1, ...)`.

**Comment by markus2330** [comment]
The elektra* functions were never designed to have POSIX signatures. As a matter of fact e.g. elektraRealloc was specifically designed to be not like POSIX, as the author of elektraRealloc (Avi) found the realloc API to be bad in usability.

Btw. the label "usability" is about usability for customers, not for internal stuff.

**Comment by kodebach** [comment]
Maybe I should have phrased that differently. POSIX compatibility is of course nice, but definitely not a must. You are absolutely right, `elektraRealloc` is much harder to misuse than `realloc`.

The main reason POSIX interface is better in this case is, that you quite often need an array of things. In that case I find `calloc (arraySize, sizeof(element))` nicer to use than multiplying manually (especially if the array size is something like `x + 1`). At the same time, adding the `1`, if you don't need an array of things is not that much effort.

> Btw. the label "usability" is about usability for customers, not for internal stuff.

While it might not be used externally very often, `elektraCalloc` (and everything else from `kdbhelper.h`) is part of the public API. So it was partly about external usability.

**Comment by mpranj** [comment]
The proposal sounds reasonable to me. Having a wrapper is not a bad idea as we can easily add things like assertions (as is already done).

Other than that I think it would be better if we provide e.g. a working XML parser, than to focus on improving well known POSIX APIs.
