### ISSUE TITLE
document global keyset

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3687]
as discussed in #3651

**Comment by kodebach** [comment]
There is already some documentation. See https://github.com/ElektraInitiative/libelektra/pull/3651#issuecomment-781539532

I already added some information about the caching of the global Keyset.

What else should we document and where?

**Comment by mpranj** [comment]
Places where usage and decisions of global keyset are documented:

1. https://github.com/ElektraInitiative/libelektra/blob/master/doc/decisions/global_keyset.md
2. https://github.com/ElektraInitiative/libelektra/blob/master/doc/tutorials/plugins.md#elektraplugingetglobalkeyset
3. https://github.com/ElektraInitiative/libelektra/blob/a80240f20c735514d9ba4f7a98a1306f11eab12d/src/plugins/doc/doc.c#L150-L163
4. https://github.com/ElektraInitiative/libelektra/blob/a80240f20c735514d9ba4f7a98a1306f11eab12d/src/libs/plugin/plugin.c#L152-L170

Personally I think points 3 and 4 are most important to a user of the global keyset. Maybe we could document which part of the global keyset is cached.

@markus2330 where can we improve this docu?

**Comment by markus2330** [comment]
I don't see much information about the structure of the global keyset. Also where/when/how plugins are supposed to write/cleanup. (I.e. convention to avoid clashes between different plugins.)

libelektra/src/plugins/doc/doc.c and the plugin tutorials would be good places. In general it is often helpful if the different places link to each other.

**Comment by mpranj** [comment]
> I don't see much information about the structure of the global keyset.

Not sure what is meant here, it is just a keyset.

> Also where/when/how plugins are supposed to write/cleanup.

This docu could be improved, but: there are no limitations. A plugin can use it at any time and should probably clean up unused keys asap, such that the keyset remains small.

> In general it is often helpful if the different places link to each other.

I agree, the docu should ideally be in one place, or at least linked together. Currently it is hard to find information (and this applies to other parts of the docu as well).

**Comment by markus2330** [comment]
> [structure of the global keyset]

I mean the semantics of the hierarchy, e.g. if `/elektra` keys are reserved or similar.

> there are no limitations

There should be limitations: if any plugin can change any part as they want it clearly cannot work as they might remove each others keys.

> I agree, the docu should ideally be in one place, or at least linked together.

:sparkling_heart:
