### ISSUE TITLE
Possible bug in kdbSet

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3691]
I noticed that in `testkdb_simple` there is a test that expects an empty KeySet from `kdbSet`:

https://github.com/ElektraInitiative/libelektra/blob/a80240f20c735514d9ba4f7a98a1306f11eab12d/tests/kdb/testkdb_simple.cpp#L42-L51

The test obviously succeeds, but isn't the test wrong? I would at least expect some keys in `system:/elektra/mountpoints`, since the `testkdb_*` tests create some mountpoints?

**Comment by markus2330** [comment]
Thank you for reviewing and asking questions.

In the SetUp the test mounts a non-existing file at testRoot. As we get keys exactly at testRoot, the current implementation of Elektra guarantees that nothing will be returned (and the file will not appear).

Of course, if you would get all keys, you would get keys in `system:/elektra/mountpoints` and so on. But the test is not about that.

**Comment by kodebach** [comment]
Ah yes, somehow missed that we don't get the whole KDB here
