### ISSUE TITLE
Possible bug in resolver

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3692]
If an empty KeySet is passed to the resolver, it checks whether the storage file can be deleted during the first phase. Specifically, it checks whether the directory that contains the file can be modified.

https://github.com/ElektraInitiative/libelektra/blob/a80240f20c735514d9ba4f7a98a1306f11eab12d/src/plugins/resolver/resolver.c#L1091-L1097

But wouldn't that check fail, if the directory doesn't exist? Since there is no error, I assume the resolver is somehow not called in such a case, but we should probably fix it regardless.

**Comment by markus2330** [comment]
There are bugs related to empty files in the resolver, e.g. #1470. Unfortunately they are quite complicated to fix and we do not have tests for the many situations (so it is easy to break something that worked before). I do not see these issues as 1.0 critical, as most problems are related to non-cooperative processes. Improvements very much welcomed nevertheless.

**Comment by kodebach** [comment]
Yes, fixing all the bugs in the resolver is quite complicated, but this one should be solved by adding a `access(pk->dirname, F_OK)`
