### ISSUE TITLE
qt-gui: metadata name not shown

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3696]
Probably since keyname overhaul (which added the `meta:` namespace to metadata) the metadata name is now shown (the value still works). E.g. I use:

```sh
kdb meta-set /sw/app/current/#0/server/port type short
kdb qt-gui
```

then I navigate to `spec: -> sw app -> current -> #0 -> server -> port` and in the metadata window "Metakey Value" with short is shown but "Metakey Name" is blank. It should read `type` (or meta:/type).

![grafik](https://user-images.githubusercontent.com/7949075/110461838-412db700-80d0-11eb-925c-e549a64ce279.png)

@0003088 do you have time to look at it?

Btw. is there some way to change the font size of the qt-gui?

**Comment by kodebach** [comment]
The namespace for metadata is called `meta:/` not `metadata:/`

**Comment by 0003088** [comment]
I could not check it out in detail yet, but does this still work? 

`m_key.currentMeta ().getName ()`

**Comment by markus2330** [comment]
Thank you for the quick response. Yes, afaik it should still work but it now returns `meta:/metakey`.

**Comment by 0003088** [comment]
I found the reason why it's not working. The question is, should the key be shown in the gui with or without the prefix?

**Comment by markus2330** [comment]
Thank you so much, great :1st_place_medal: 

I would not show it when editing metakeys as it is only a source of errors (any other namespace is not allowed anyway). When showing it in the main window we can consider showing `meta:/` as imho it is not immediately obvious that meta-data is shown in the bottom split window and the "Metakey Name" title is quite small.

**Comment by markus2330** [comment]
Btw. I get two messages when using qt-gui, the first one seemingly related to metadata:

```
qrc:/qml/NewMetaKey.qml:58: ReferenceError: user is not defined
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 803, resource id: 10823870, major code: 40 (TranslateCoords), minor code: 0
```

**Comment by 0003088** [comment]
I'm sorry for the delay. As I said earlier, I found the reason for the bug and corrected it. But when I tested the fix I noticed that I could not edit the metakeys, they are always overwritten in the threeway merge. I do not think this has anything to do with the display bug. Do you have any idea why the merger behaves like that?

**Comment by markus2330** [comment]
I don't think we changed the old C++ merger in any way, so probably the merging you tested also did not work before. Maybe this is now a good opportunity to use @dominicjaeger's new 3 way merger instead? @dominicjaeger do you have time to do the migration or to help with it?

**Comment by dominicjaeger** [comment]
I think we started introducting the C merge in the qt-gui already? But I'll have to look up how far we came...

**Comment by markus2330** [comment]
@dominicjaeger thank you for the quick response! If we already use your implementation consider https://github.com/ElektraInitiative/libelektra/issues/3696#issuecomment-841030473 as first bug report :wink:

**Comment by markus2330** [comment]
Bug still present for me.
