### ISSUE TITLE
qt-gui: search broken

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#370]
When typing text in the search field and press enter, the search dialog is shown, but no results in it.

**Comment by 0003088** [comment]
works for me? search behaves as expected.

**Comment by markus2330** [comment]
It still does not work for me with Version: 5.3.2+dfsg-4+deb8u1 (Debian Jessie), even with #406 applied. Are you also testing with qt 5.3?

But if it works with newer versions, its ok. You shouldn't waste too much effort on old versions.

**Comment by 0003088** [comment]
No, I use 5.4.2 mostly and sometimes 5.5 for testing

**Comment by markus2330** [comment]
only present at older qt versions
