### ISSUE TITLE
Mounting augeas with glob and keytometa

### ISSUE THREAD

**Issue by fberlakovich** [ElektraInitiative/libelektra#371]
I would like to mount configurations with the augeas storage plugin together with glob and keytometa for comment treatment. The augeas plugin contract provides a default configuration for glob that should work for most configuration files. I am pretty sure that this already worked once. However, the call

```kdb mount path/to/file system/test augeas glob keytometa```

does not create the appropriate glob configuration. In addition, glob seems to be mounted at the wrong position (after keytometa):

```
ountpoints/system\/test/getplugins/#0#resolver
system/elektra/mountpoints/system\/test/getplugins/#5#augeas#augeas#
system/elektra/mountpoints/system\/test/getplugins/#8#keytometa#keytometa#
system/elektra/mountpoints/system\/test/getplugins/#9#glob#glob#
```

@markus2330 could you help me getting this right? My knowledge of the contract checking is rather limited.

**Comment by markus2330** [comment]
When I use
`kdb mount path/to/file system/test augeas glob keytometa`
I get
```
system/elektra/mountpoints/system\/test/getplugins/#8#keytometa#keytometa#
system/elektra/mountpoints/system\/test/getplugins/#9#glob#glob#
system/elektra/mountpoints/system\/test/setplugins/#1#glob
system/elektra/mountpoints/system\/test/setplugins/#2#keytometa
system/elektra/mountpoints/system\/test/setplugins/#5#augeas
```
which is wrong in the get-path: glob is applied after keytometa.
The problem is the stacking feature which turns around the processing chain in one direction. So stacking needs to be disabled for glob. (Because glob always must be first to work properly)

The second problem in the contract is that:
`kdb mount path/to/file system/test augeas keytometa glob`
would lead to a wrongly mounted backend (in both get+set path).

To avoid that the ordering feature should be used. So glob needs to know that keytometa is never to be mounted afterwards, hence glob gets `ordering = keytometa`. Then the mounting of `keytometa glob` leads to an ordering violation (and not to an non-functional backend).

I hope this clarifies how the contract works.

**Comment by markus2330** [comment]
Thanks for answering the question, please reopen if you need further clarifications. Your mount command in your question should now (after d60119edd59da87d5fcaa0b672da10c5508ee9bd) work again.

**Comment by fberlakovich** [comment]
Thanks for the fast response! The ordering issue is fixed now. However, in my question I tried to describe two issues. The second issue is that the default configuration for glob provided by the augeas plugin contract is not reflected anywhere:

```
keyNew ("system/elektra/modules/augeas/config", KEY_END),
keyNew ("system/elektra/modules/augeas/config/needs", KEY_END),
keyNew ("system/elektra/modules/augeas/config/needs/glob/get/#1",
	        KEY_VALUE, "*#comment*",
	        KEY_META, "convert/metaname", "comment", /* comment keys are converted to comments */
	        KEY_META, "convert/append", "next", /* usually comments belong to the following key */
        KEY_END),
keyNew ("system/elektra/modules/augeas/config/needs/glob/get/#1/flags",
	        KEY_VALUE, "0", /* disable the path matching mode */
	KEY_END),
```

What has to be done in order for this default configuration to be present for glob whenever glob is mounted together with augeas?

Should I rename this issue and create a second question for the configuration part?

**Comment by markus2330** [comment]
Thanks! It actually was a regression from the change of keyAdd*Name() semantics. Now (after fd2c94cd85630dfbb2875ed7ae5fa79fbd669d0d) the config is appended. Please reopen if there are still any issues. Please give an example in augeas README how to use it together with keytometa.

About renaming: not needed, the topic still seems to fit. Creating a second question is not needed for follow-up issues, only if we see that there are actually two unresolved issues at once. In case of doubt, however, open new issues.

**Comment by fberlakovich** [comment]
The configuration is now added, but with a wrong path:

```
system/elektra/mountpoints/system\/test/config/elektra/modules/augeas/config/needs
system/elektra/mountpoints/system\/test/config/elektra/modules/augeas/config/needs/glob/get/#1
system/elektra/mountpoints/system\/test/config/elektra/modules/augeas/config/needs/glob/get/#1/flags
```

The issue seems to be in ```serializeBackend``` where the keys in the ```config``` KeySet are rebased.

**Comment by markus2330** [comment]
Was the behavior of rebaseKey changed, too? Didn't you changed it recently because of the sync issue? I think we need more unit tests in these parts. This issue should be tackled together with the specification mounting.

**Comment by markus2330** [comment]
Sorry for ping pong. Seems like there were a bunch of unrelated issues involved. Please reopen if you find one more.

Please document the keytometa, glob and augeas interconnections, so that I can actually test your intended behaviour.
