### ISSUE TITLE
Invalid key name log message when executing some JNA tests

### ISSUE THREAD

**Issue by tucek** [ElektraInitiative/libelektra#3710]
## Steps to Reproduce the Problem

I've built Elektra with `ENABLE_LOGGER` = `ON`. When executing the JNA binding tests, multiple `Invalid name:  (in keyVNew at src/libs/elektra/key.c:238)` messages are being logged by Elektra.

```sh
cd src/bindings/jna/libelektra5j/
cp pom.xml.in pom.xml
mvn test
```

## Expected Result

No log messages issued by Elektra regarding invalid names.

## Actual Result

```
#> ...
#> -------------------------------------------------------
#>  T E S T S
#> -------------------------------------------------------
#> Running org.libelektra.exception.model.WarningEntryTest
#> Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.494 sec
#> Running org.libelektra.ExceptionMapperTest
#> Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.111 sec
#> Running org.libelektra.GOptsTest
#> Invalid name:  (in keyVNew at src/libs/elektra/key.c:238)
#> Invalid name:  (in keyVNew at src/libs/elektra/key.c:238)
#> Invalid name:  (in keyVNew at src/libs/elektra/key.c:238)
#> Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.091 sec
#> Running org.libelektra.KDBExceptionTest
#> Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
#> Running org.libelektra.KDBTest
#> Invalid name:  (in keyVNew at src/libs/elektra/key.c:238)
#> Invalid name:  (in keyVNew at src/libs/elektra/key.c:238)
#> Invalid name:  (in keyVNew at src/libs/elektra/key.c:238)
#> Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
#> Running org.libelektra.KeySetTest
#> Tests run: 17, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
#> Running org.libelektra.KeyTest
#> Tests run: 30, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
#> 
#> Results :
#> 
#> Tests run: 54, Failures: 0, Errors: 0, Skipped: 0
#> 
#> [INFO] ------------------------------------------------------------------------
#> [INFO] BUILD SUCCESS
#> [INFO] ------------------------------------------------------------------------
#> ...
```

## System Information

- Elektra Version: master (8f2eec2e2002e9748c102da799cafe144d0fbf48)
- Ubuntu 20.04 on WSL2

## Further Information

- In spite of the log messages being dispensed, it does not seem to has any adverse effect on the tests
- see @kodebach comments on the suspected origin in https://github.com/ElektraInitiative/libelektra/issues/3171#issuecomment-799789807
- I've debugged the tests and the log messages seems to be dispensed after `kdb.set` is called in `GOptsTest.java:55` and `KDBTest.java:44`

**Comment by markus2330** [comment]
Thank you for trying it with logging enabled and reporting this problem! It might be that this is actually an indicator of a problem in the binding (except if the tests actually test invalid key names). I think the binding should refuse to create a key where the underlying C-Key object could not be created. Is this the case?

**Comment by tucek** [comment]
@markus2330 i do not think the jna binding tests try to create any empty keys... my superficial analysis suggests it not to be a binding problem... i maybe could get back to this, doing a more thorough analysis, if i have time...

**Comment by markus2330** [comment]
The plugin loader tries to create keys with an empty name:

```
libelektra5j/src/main/java/org/libelektra/PluginLoader.java:            this.errorKey = Key.create ("");
libelektra5j/src/main/java/org/libelektra/PluginLoader.java:            Key error = Key.create ("")
```

**Comment by tucek** [comment]
Thanks for having a look. As far as I remember, the PluginLoader was not involved in the Tests in question, but i may be wrong. I will have a look at it.
