### ISSUE TITLE
[CM H2] Migrate Java (JNA) binding to gradle

### ISSUE THREAD

**Issue by tucek** [ElektraInitiative/libelektra#3713]
- [x] Register at sonartype to enable maven central artifact publishing
- [x] Migrate the existing Maven project to Gradle (`/src/bindings/jna`)
- [x] Integrate Gradle build into cmake build
- [x] Remove Maven from and add Gradle to build images
- [x] Provide Gradle task to (manually) publish artifact to maven central
- [x] Update all JNA/Maven specific docs and tutorials (add quick tutorial for Gradle project depending on Elektra)

**Comment by tucek** [comment]
I'll now begin to figure out how to remove maven and replace it with the proper version of gradle in the build images and the cmake build.
If someone can provide some short hints, it would surely safe me some time ;)

**Comment by tucek** [comment]
@markus2330 It appears to me that pinning the native library to the Elektra version the JNA bindings were built with only works if

- either specifying `Native.loadLibrary("libelektra-kdb.so.0.9.4", Elektra.class)` instead of `Native.loadLibrary("libelektra-kdb", Elektra.class)` which breaks when native libraries do not have `so` as extension
- or providing an additional symlink like libelektra-kdb.0.9.4.so -> libelektra-kdb.so.0.9.4

should i proceed in any of this directions, preferably the second one, or should i drop this issue for now?

**Comment by tucek** [comment]
@robaerd I've modified all Dockerfiles previously supporting Maven to support Gradle instead. Could you please have a look, whether i made some grave oversight? I've build all images and tested whether Gradle works within.

**Comment by tucek** [comment]
@markus2330 Can i assume macOS GCC action failing because of
```
The following tests FAILED:
	 41 - test_tools_plugindatabase.py (Failed)
	 55 - testruby_tools_plugindatabase.rb (Failed)
	176 - testscr_check_gen (Failed)
	212 - testshell_markdown_tutorial_validation (Failed)
	213 - testshell_markdown_tutorial_crypto (Failed)
FAILED: tests/CMakeFiles/run_all
```
is currently completely normal and not related to my changes?

**Comment by markus2330** [comment]
> instead of Native.loadLibrary("libelektra-kdb", Elektra.class) and provide an additional symlink like libelektra-kdb.0.9.4.so -> libelektra-kdb.so.0.9.4

This symlink basically already exists: /usr/lib/libelektra-core.so -> libelektra-core.so.5 and this "5" tells you the compatibility of the native interface.

> should i proceed in any of this directions, preferably the second one, or should i drop this issue for now?

The native pinning on the exact version will not be needed in future as with 1.0 we remain compatible with our own versions. A run-time check might be useful though, e.g. you could provide a small version check API which compares with the keys below system:/elektra/version/constants/KDB_VERSION_*? During 0.9. this is not ideal as there are some potential API changes where even this version check could fail. I think, however, if people get an exception that the native installation is somewhat broken might be enough indication?

> is currently completely normal and not related to my changes?

I don't know. They were not failing a few days ago. Can you open an issue?

**Comment by tucek** [comment]
> > Could you please have a look, whether i made some grave oversight?
> 
> Is it really necessary to change sh to bash in all Dockerfiles? I refer to following line:
> 
> ```dockerfile
> RUN rm /bin/sh && ln -s /bin/bash /bin/sh
> ```
> 
> Does gradle not work with dash? If this is the case this could probably be a problem since a lot of scripts have the shebang `#!/bin/sh` which forces to mimic POSIX-conform sh behavior.
> Btw, on Fedora /bin/sh already points to /bin/bash.
> 
> > At least Fedora (https://cirrus-ci.com/task/5945902897561600?logs=main#L189) seems not to fing Gradle yet
> 
> Paths on fedora are a bit different, maybe it works by setting PATHS in CMake:
> 
> ```shell
> find_program(GRADLE_EXECUTABLE NAMES gradle PATHS $ENV{GRADLE_HOME}/bin)
> ```

@robaerd Thank you very much for your quick review! 

- Bash was a requirement for using sdkman to install gradle. I've removed this dependency. 
- I've also set thge PATH for root and the occasional jenkins user which seems to now work for fedora as well (without modifying the cmake build as you suggested.)

Maybe you could have another quick look, if you have time...

**Comment by tucek** [comment]
Some build checks still fail because of missing java doc and the now more strict validation of it. I will address this issue later today.

**Comment by tucek** [comment]
> > instead of Native.loadLibrary("libelektra-kdb", Elektra.class) and provide an additional symlink like libelektra-kdb.0.9.4.so -> libelektra-kdb.so.0.9.4
> 
> This symlink basically already exists: /usr/lib/libelektra-core.so -> libelektra-core.so.5 and this "5" tells you the compatibility of the native interface.
> 
> > should i proceed in any of this directions, preferably the second one, or should i drop this issue for now?
> 
> The native pinning on the exact version will not be needed in future as with 1.0 we remain compatible with our own versions. A run-time check might be useful though, e.g. you could provide a small version check API which compares with the keys below system:/elektra/version/constants/KDB_VERSION_*? During 0.9. this is not ideal as there are some potential API changes where even this version check could fail. I think, however, if people get an exception that the native installation is somewhat broken might be enough indication?
> 

I will create a new issue regarding the version check API and will not implement any library version pinning.

> > is currently completely normal and not related to my changes?
> 
> I don't know. They were not failing a few days ago. Can you open an issue?

I will attend to this issue when i am switching to rdy for review

**Comment by markus2330** [comment]
> I will create a new issue regarding the version check API.

Something very simple should be enough.

> I will attend to this issue when i am switching to rdy for review

It can be very beneficial to look at the buildserver from the beginning, as the pass-through time (not the time spent to actually fix the issue) can be quite high.

**Comment by markus2330** [comment]
Btw. to pin to version .5 would be useful (if you already found out how it works).

**Comment by tucek** [comment]
@markus2330 Adding proper java doc to the JNA bindings is quite time-consuming, but IMHO essential to provide acceptable developer support. The one thing bothering me a little is the amount of C API documentation i have to duplicate for documenting the native library proxy. Therefore i wanted to get you opinion on this, before finishing it up.

**Comment by markus2330** [comment]
Where exactly do you want me to look? Did you try to link to the C docu?

But I have to admit that completely without any duplication it will be hardly possible to be beginner friendly (start with Java bindings without knowing C API).

**Comment by tucek** [comment]
> Where exactly do you want me to look? Did you try to link to the C docu?
I just wanted your opinion on this topic. What would be the best way to link to the C API docs? (e.g. online URL to API docs / offline relative path to API docs - but docs would not necessarily be built / offline relative path to the .c file containing the API doc)

> But I have to admit that completely without any duplication it will be hardly possible to be beginner friendly (start with Java bindings without knowing C API).
i concur.

**Comment by tucek** [comment]
> Btw. to pin to version .5 would be useful (if you already found out how it works).

Analogous to the explanation above, since the symlink name is `libelektra.so.5`, i would break loading the library for platforms with other library extension names... I don't see a solution beside introduction of a symlink with patter `libelektra.5.<ext>`
Am i overlooking something here?

**Comment by markus2330** [comment]
>   I just wanted your opinion on this topic.

I personally would try to integrate the Java Documentation into Doxygen and then use [@copydoc](https://www.star.bnl.gov/public/comp/sofi/doxygen/commands.html#cmdcopydoc) to copy docu from the C binding to the Java binding. This is how I did it for the C++ binding. E.g. see https://doc.libelektra.org/api/master/html/classkdb_1_1KDB.html for the C++ KDB class.

Java seems to be supported by Doxygen but I never tried it in a mixed C/C++ project. Doxygen might be similar enough to Javadoc that Java devs like it, but I might be wrong here.

If you want it separated (as Javadoc) you probably should look at similar projects (Java bindings for native libraries).

The Rust bindings that a quite good job: https://crates.io/crates/elektra

> What would be the best way to link to the C API docs? (e.g. online URL to API docs / offline relative path to API docs - but docs would not necessarily be built / offline relative path to the .c file containing the API doc)

While it possible to link to functions (e.g. https://doc.libelektra.org/api/0.9.2/html/group__kdb.html#ga6808defe5870f328dd17910aacbdc6ca) it is also a bit problematic, as the links stop working on signature changes. (kdbOpen added a KeySet later, so if you increase the version number, at some point you will not jump to kdbOpen in the docu anymore)

So probably a link per class is the only reasonable thing to do, e.g. to KDB: https://doc.libelektra.org/api/master/html/group__kdb.html

> @markus2330 Analogous to the explanation above, since the symlink name is libelektra.so.5, i would break loading the library for platforms with other library extension names... I don't see a solution beside introduction of a symlink with patter libelektra.5.<ext>
Am i overlooking something here?

My mistake, I thought for the .5 link it is the other way round. But strange that this mechanism is done in a way that it is not portable. What are other projects using JNA doing?
