### ISSUE TITLE
Future plans for Docker images

### ISSUE THREAD

**Issue by robaerd** [ElektraInitiative/libelektra#3716]
## Root privileges on Docker images
There are currently 3 types of Docker images:

1. Images used for testing and/or packaging.
   These images do not have any root privileges.
2. Images where local Elektra packages are installed.
   Packages are installed during the Image build process, tests are run
   without root privileges with the jenkins user.
   These images do not have any root privileges.
3. Alpine Release image.
   Builds and installs latest released version of Elektra.
   Has permissions to call sudo.

As long as we do not give the `2. Images` sudo permissions, they will probably not be really useful for normal users. Even if we give the jenkins user access to all directories Elektra needs access to. 

### Options
- [ ] Give the `2. Images` sudo permissions.
On these images only the `kdb run_all` command is executed.
- [ ] Create for each `2. Images` a corresponding release image like `3. Alpine Release image`.
These images are only built and never run on Jenkins, however the ctests are executed during the Docker image build process.

@markus2330 @mpranj  what do you think would be best?

### Images
- **CentOS**
CentOS recently switched its focus to CentOS Stream - a rolling release distribution based on CentOS. 
In my opinion, it would make sense to create Docker images for CentOS 7, as it is supported until 2024 and also for CentOS Stream. We could also create packages for these distributions.
- **openSuse**
Since openSuse also uses the RPM package format, it should be quite easy to also build packages for it.
- **Arch**
Since there is currently no support by CPack to create Arch packages and we already have a Docker image with Arch, I do not think it is necessary to create more Arch based Docker images.
It would however make sense to integrate the Arch Docker images into Jenkins. Currently it is only used in Cirrus CI.

### Release pipeline
To automatically verify that all packages are uploaded to our package repositories, it would be necessary to install and test them from our repositories. For this we would need new Docker images for each distribution we create packages for.

**Comment by mpranj** [comment]
The main question for me is: what is the purpose of the images? Would these images be useful for users beyond trying out the release image?

As a new user I would probably first try the release image and play around with `kdb`. If it seemed useful, I would go ahead and install the debs or rpms.

Regarding `3. Alpine Release image`:
Afair sudo was only added as a convenience for beginners, to make it consistent with a typical installed version. This way users can try out what is displayed in the introductory video _"Want to see how it works?"_ on [https://www.libelektra.org/home](https://www.libelektra.org/home). I would not copy any ideas of this image. The single purpose is to easily try out Elektra, without compiling and other hassles. 

In general it is quite discouraged by Docker to run anything except the image setup as a privileged user.

**Comment by robaerd** [comment]
> The main question for me is: what is the purpose of the images? Would these images be useful for users beyond trying out the release image?

If I recall correctly, @markus2330 mentioned in the last meeting that it would be nice if the release images had the same functionality as the Alpine release image. I probably have then misinterpreted it and thought that we should start providing release images with sudo permissions.

> As a new user I would probably first try the release image and play around with kdb. If it seemed useful, I would go ahead and install the debs or rpms.

I actually did not intend the release images with installed packages to be used by actual users at all and only added them to be kept in the repositories because of a request in #3698. 
To make them really usable for other users a few basic packages are still missing. For example the `kdb editor` command is not working as no editor is installed. I think a few plugins are also not working when using `kdb` as the /etc/kdb is not writable, although it is owned by the user jenkins - probably a simple `chmod` is necessary. 

> In general it is quite discouraged by Docker to run anything except the image setup as a privileged user.

We could also run the kdb tests during the docker build stage, therefore removing the need to ever run the image in jenkins and could provide the image with sudo permissions.

**Comment by markus2330** [comment]
> If I recall correctly, @markus2330 mentioned in the last meeting that it would be nice if the release images had the same functionality as the Alpine release image. I probably have then misinterpreted it and thought that we should start providing release images with sudo permissions.

I also did not think of sudo. Maybe it actually makes sense to keep these 3 types of Docker images separated. @robaerd can you document which Docker images have which purpose?

Alternative would be to make a "safe" sudo which does not give root permissons but of some other user (e.g. admin) who can write to /etc, /usr/.../specification etc. I am not sure if this is:

1. easy to do
2. if we could run the tests with this "admin"

> I actually did not intend the release images with installed packages to be used by actual users at all and only added them to be kept in the repositories because of a request in #3698.

This request was in the direction of having more "release Docker images".

> For example the kdb editor command is not working as no editor is installed.

I like that you do such investigations :heart:  Yes, for a "release image" it makes sense if such things work. import/export e.g. also need /dev mounted and similar.

> We could also run the kdb tests during the docker build stage, therefore removing the need to ever run the image in jenkins and could provide the image with sudo permissions.

Sounds interesting. Would this solve the issue of having an Jenkins user?

**Comment by robaerd** [comment]
>  @robaerd can you document which Docker images have which purpose?

Document as in create documentation in the repository or simply describe it here?


> Sounds interesting. Would this solve the issue of having an Jenkins user?

Yes, at least for the images where Elektra packages get installed and tested and also for release images. This would however not eliminate the Jenkins user for the Docker images of our main test stages.

**Comment by markus2330** [comment]
>  Document as in create documentation in the repository or simply describe it here?

Ideally in a short README.md in scripts/docker
