### ISSUE TITLE
I cannot use Xerces plugin

### ISSUE THREAD

**Issue by GerbenAbbink** [ElektraInitiative/libelektra#3729]
I do the following:

> sudo kdb mount /etc/samba/smb.conf system:/samba xerces
The command kdb mount terminated unsuccessfully with the info:
No plugin that provides xerces could be found
Please report the issue at https://issues.libelektra.org/

To install xerces i do:
> sudo apt-get install libxerces-c-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libxerces-c-dev is already the newest version (3.2.2+debian-1build3).

Which means that xerces is already installed.

What am i doing wrong? I am new to Elektra, so maybe it's something trivial.

**Comment by markus2330** [comment]
Thank you for reporting the problem!

The xerces plugin is for XML files, so it might be unsuitable for your smb.conf.

> No plugin that provides xerces could be found

This means that the xerces plugin is not installed. Maybe installing libelektra5-xerces is enough to fix your problem. Can you please confirm if it helped you?

I agree that we should mention this in the README.md of xerces. We can keep the issue open to fix this.

> libxerces-c-dev

This is the dependency which allows you to compile the xerces plugin, it does not install the xerces plugin itself.

**Comment by GerbenAbbink** [comment]
I did this:

sudo apt-get install libelektra5-xerces
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libelektra5-xerces

**Comment by markus2330** [comment]
Did you add the package repository as described in https://www.libelektra.org/installation/installation? (Make sure to uninstall older versions of Elektra you might have installed.) Otherwise, please give more information what you did and which distribution you have.

**Comment by GerbenAbbink** [comment]
It's still not working.

I am running Ubuntu under Windows 10 on VMWare 16.

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 20.04.2 LTS
Release: 20.04
Codename: focal

Following ElektraInitiative (libelektra.org)
<https://www.libelektra.org/installation/installation> i do this:
> sudo apt-get install software-properties-common apt-transport-https
OK.
> sudo echo "deb https://debs.libelektra.org/focal focal main" | sudo tee
/etc/apt/sources.list.d/elektra.list
OK.
> sudo apt-get install libelektra5-all
sudo apt-get install libelektra5-all
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libelektra5-all

Now I am stuck.

**Comment by markus2330** [comment]
Are you sure you executed `apt-get update` before trying to install?

We should add this in the docu, too. (Next to mentioning the package names in the respective plugins).

**Comment by GerbenAbbink** [comment]
Yes, that's it!

I ran

> sudo apt-get update

Everything is working now. I can use the xerces plugin.

Thank you for helping me.
