### ISSUE TITLE
Replace keyClear with an alias to keyCopy?

### ISSUE THREAD

**Issue by lawli3t** [ElektraInitiative/libelektra#3730]
With the new functionality added to `keyCopy()`, keyClear could be replaced / aliased by a call to `keyCopy(dest, source, NULL)`. This would improve maintainability and remove duplication of functionality. If not, should `keyCopy()` be able to perform the function of `keyClear()`? Are there any differences of how `keyClear()` and `keyCopy()` clear keys, that I am not aware of?

**Comment by markus2330** [comment]
> This would improve maintainability and remove duplication of functionality.

I am not yet so sure if the whole "aliases" approach is a good idea. I agree though that sometimes trivial functions are necessary. The API's discoverability is not as good as it could be.

Can you do an analysis if:

- The benefits we hope for are really there (e.g. smaller binary size of Elektra's libraries and no blow-up of binary size of applications).
- The aliases will not make problems for Elektra's reimplementations like in Rust.
-  I am quite sure it will make maintainability more difficult, as aliases basically cannot be changed at all (no symbol versioning and as the code is embedded in the applications we cannot even fix bugs via library updates).
- It might leak implementation details or will require recompilation of applications for some optimizations.

I think this analysis will fit well in your second research question.

> Are there any differences of how keyClear() and keyCopy() clear keys, that I am not aware of?

If there are, we should select the more useful behavior and get rid of the other one.

I do not like the idea to have several ways of the same functionality with subtle differences hidden in remarks of the docu.

**Comment by lawli3t** [comment]
> Probably the best way forward is to keep `keyClear`, but only in `kdbprivate.h`. It does serve a purpose, but only in a very limited fashion and not in any way to would be very useful to an external user.

Sounds like a good idea to me.

**Comment by markus2330** [comment]
See also my comment in #3733

**Comment by lawli3t** [comment]
keyClear will be wholly removed as per #3839
