### ISSUE TITLE
Change parameter names of functions taking a KeySet as parameter

### ISSUE THREAD

**Issue by lawli3t** [ElektraInitiative/libelektra#3732]
Currently all functions taking a KeySet as an argument use `ks` as a variable name. This could be renamed to `keySet`, making source code more readable and the API more expressive. Functionality would be untouched, but this would be a slight improvement to readability / discoverability of the API. The function parameter itself has the type `KeySet`, so opponents may argue this is already sufficient - but would it hurt to change it anyway? It might bring some upsides, while having barely any downsides (line length).

Examples
Almost all functions in the [KeySet module](https://doc.libelektra.org/api/master/html/group__keyset.html)

**Comment by markus2330** [comment]
Yes, I agree. As `ks` is not listed anywhere as abbreviation, we should also avoid using it.

**Comment by kodebach** [comment]
Are we sure we want to go through all the effort of renaming all these parameters? Wouldn't it be simpler to add `ks` as an "official" abbreviation for KeySet?

BTW I think `ns` is also commonly used as an abbreviation for namespace paramters/variables. Should we rename those too? In this case I think the reason is sometimes that in C++ `namespace` is a reserved keyword and that can cause problems in some places.

**Comment by markus2330** [comment]
I am also fine with "ks" as abbreviation (as it is currently used consistently).

ns is only a single occurrence in the API, which was recently introduced by @kodebach :wink:

**Comment by kodebach** [comment]
> ns is only a single occurrence in the API, which was recently introduced

To be fair, I did check how much it is actually used in the public API. I just know it is is used quite a bit as a variable name (possible just in plugins or internally) and that I did have problems with the C++ `namespace` keyword at some point.

**Comment by lawli3t** [comment]
It seems to be that going forward with just adding ks to the glossary would be the easier solution. Do you really think that renaming all this parameters with an IDE would be too cumbersome?

I guess considering all the different bindings where this would need to be renamed it might prove quite an effort, even with IDEs.

**Comment by markus2330** [comment]
Yes, such huge renamings can be a big task. You can try to rename *every* occurrence of `ks` and see if it still compiles. IDE's/refactoring tools will not help so much here, as we also need to fix the occurrences in the text files.

But as said: simply add it to the glossary and the job is also done :wink:

**Comment by kodebach** [comment]
I think this only happens inside functions and not at an API level, but there may also be cases where `Ks` is used as a suffix. For example `specKs` for a KeySet containing a spec. It would be pretty hard to find all of those occurrences. IMO we should just `ks` to the glossary.

**Comment by lawli3t** [comment]
deemed too much work for too little gain
