### ISSUE TITLE
Is keyVNew still needed in the public API

### ISSUE THREAD

**Issue by lawli3t** [ElektraInitiative/libelektra#3735]
`keyVNew` is part of kdb.h.in [1], but doesnt appear in the documentation [2]. `keyNew` seems to be a wrapper function for `keyVNew()` that performs necessary actions before calling [3]. Could `keyVNew` be removed from the public API, as users would need to perform the actions `keyNew()` performs anyway? Are there any use cases where `keyVNew()` is applicable but `keyNew()` isn't? If yes, then `keyVNew()` should get added documentation where those use cases are explicitly explained, so users can understand the differences between `keyVNew()` and `keyNew()`.

[1] https://github.com/ElektraInitiative/libelektra/blob/master/src/include/kdb.h.in#L139
[2] https://doc.libelektra.org/api/master/html/group__key.html
[3] https://github.com/ElektraInitiative/libelektra/blob/master/src/libs/elektra/key.c#L149

**Comment by markus2330** [comment]
keyVNew has basically the same reason as vprintf. It has C specific reasons why it exists and is only needed for bindings/wrappers. I agree it should be in the docu. If keyNew could be an alias is up for investigation (it basically only calls keyVNew).

**Comment by lawli3t** [comment]
Okay, so the way forward will be adding the documentation for `keyVNew` via a new PR from me.
