### ISSUE TITLE
Replace keySetMeta / keyGetMeta with aliases to ksAppendKey / ksLookupByName

### ISSUE THREAD

**Issue by lawli3t** [ElektraInitiative/libelektra#3736]
During the API review, Klemens had the idea of replacing the implementation of `keySetMeta()` / `keyGetMeta()` with aliases to `ksAppendKey` / `ksLookupByName` (see below for example calls). This would reduce duplication of functionality and increase maintainability. `keySetMeta()` currently has a convenience functionality, where if `newMetaString` is `0` the meta-information gets removed. This should also be achievable via this change. Is there any other functionality, that could not be easily replaced by wrapping KeySet functions?

### keyGetMeta
`ksLookupByName (keyMeta (key), metaName, 0)`

### keySetMeta
`ksAppendKey (keyMeta (key), keyNew (metaName, KEY_VALUE, metaString, KEY_END))`

**Comment by markus2330** [comment]
See also #3730.

> Is there any other functionality, that could not be easily replaced by wrapping KeySet functions?

I do not understand the question, nearly all functions cannot be easily replaced. If you mean if I know other cases where aliases could be useful:

Removing keys via `ksLookup (..., KDB_O_POP)` is a major problem in the API's discoverability.

**Comment by lawli3t** [comment]
Similarly to my answer [here](https://github.com/ElektraInitiative/libelektra/issues/3730#issuecomment-811455082), aliases might have been the wrong term. Although I see good counterpoints, that if the behaviour of either function needs to change slightly, it might break the implementation of the other function and then in turn we would need to implement it separately anyway.

**Comment by kodebach** [comment]
I think aliases would be a good idea here, because they provide a migration path. The idea behind all this is that with the introduction of `keyMeta()` the other `key*Meta` functions are not needed anymore. To keep the API minimal they should be removed. But to make migration easier we could provide a new header (or as part of `kdb.h`) which defines these one-line `static inline` helpers. I would call them "helper aliases" or maybe even "migration helper aliases" to indicate they don't provide their own functionality and are basically just shortcuts.

If we do keep the `key*Meta` functions as real functions they should still be simplified. This includes that before 1.0 the functionality that e.g. `keyGetMeta (key, "type")` behaves like `keyGetMeta (key, "meta:/type")` should be removed. (This is a requirement for switching to the one-liner aliases from above anyway).

**Comment by markus2330** [comment]
I don't think that a migration path is burden we should have for 1.0. It is easier and more helpful for the initiatives (basically only Oyranos as kconfig, go-bindings etc. are maintained by us anyway) using Elektra if we directly help them to get 1.0 compatible.

I would not miss the key*Meta functions, I think the `keyMeta` design with locked keys in a meta-keyset would be more elegant. Unfortunately, it is not yet complete (run-time checks of write functionality not available).

The question is: how do we move forward to get everything decided and complete. We cannot ask @lawli3t to do all of it. I think the best way would be that we finish the decisions https://www.libelektra.org/decisions/readme together with @lawli3t and then break up who does what.

@lawli3t would you be interested to create a PR about the remaining API decisions? (Basically as documentation of what we discuss here together with the results of your analysis.)

**Comment by kodebach** [comment]
The first big step will always be going through all the `key*Meta` calls and adding the `meta:/` prefix, where it isn't used yet.

After that the best way forward might be to remove the `key*Meta` functions from the public API, but keep them for internal use inside our repo. This way we can slowly migrate away from the separate functions to standard KeySet functions and `keyMeta()`. Whether we keep the current implementation or use `static inline` one-liners for the new internal `key*Meta` versions is up for debate, but doesn't really matter with this approach.

**Comment by lawli3t** [comment]
> I don't think that a migration path is burden we should have for 1.0. It is easier and more helpful for the initiatives (basically only Oyranos as kconfig, go-bindings etc. are maintained by us anyway) using Elektra if we directly help them to get 1.0 compatible.
> 
> I would not miss the key*Meta functions, I think the `keyMeta` design with locked keys in a meta-keyset would be more elegant. Unfortunately, it is not yet complete (run-time checks of write functionality not available).
> 
> The question is: how do we move forward to get everything decided and complete. We cannot ask @lawli3t to do all of it. I think the best way would be that we finish the decisions https://www.libelektra.org/decisions/readme together with @lawli3t and then break up who does what.
> 
> @lawli3t would you be interested to create a PR about the remaining API decisions? (Basically as documentation of what we discuss here together with the results of your analysis.)

Yes i certainly can, do you mean only for this issues - or in general?

**Comment by markus2330** [comment]
In general, but there is not much more (I know of) than the issues you opened. (Of course we could discuss about everything forever but that is what decisions are for: to also stop discussing at some point.)

**Comment by lawli3t** [comment]
further discussions in #3980
