### ISSUE TITLE
python: ksLookup KDB_O_POP not available

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3749]
It looks like there is an oversight in the python binding: `ks.lookup` only takes one argument, so it is not possible to pass KDB_O_POP which makes it impossible to remove one item as discussed in https://github.com/ElektraInitiative/libelektra/pull/3657#discussion_r595952403

```python
>>> import kdb
>>> ks=kdb.KeySet()

>>> ks.lookup("user:/abc", kdb.KDB_O_POP)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: lookup() takes 2 positional arguments but 3 were given

>>> ks.pop("user:/abc")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: KeySet_pop() takes exactly one argument (2 given)

>>> ks.remove("user:/abc")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'KeySet' object has no attribute 'remove'

>>> del ks["user:/abc"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'KeySet' object does not support item deletion
```

@manuelm Is there something I did not see?

Workaround: cut the keyset so that to-be-removed key is last, pop the last element and put KeySet together again. (not very attractive for a seemingly simple thing.)

**Comment by manuelm** [comment]
Is adding `remove` fine? Otherwise I would have to prevent from passing `KDB_O_DEL`

**Comment by markus2330** [comment]
Thank you so much for the quick reply! Basically all the variants I tried I would be fine with, so yes `remove` is perfect :sparkling_heart: 

It would be good if it is mentioned in the Python tutorial, so that people know about it.

> Otherwise I would have to prevent from passing KDB_O_DEL

Yes, you are right, that would be dangerous.
