### ISSUE TITLE
rename: does not work in two directions

### ISSUE THREAD

**Issue by strahlex** [ElektraInitiative/libelektra#375]
My expected behavior of adding keys to an elektra database is:
````
kdb set system/machinekit/FOO/BAR 1.0
````
whereas `system/machinekit` is a mountpoint of an ini file resulting in a ini key
````ini
[FOO]
BAR = 1.0
````
However it looks like the key in the ini file not created at all.

Workaround is creating the section manually:
````
kdb set system/machinekit/FOO
kdb set system/machinekit/FOO/BAR 1.0 
kdb get system/machinekit/FOO/BAR
````

**Comment by markus2330** [comment]
Thanks for reporting the bug. Could you please more specific about what means that the ini file is not created? Which error do you get? Are you sure its not a permission problem?

Here the file is created, but a later `kdb get system/machinekit/FOO/BAR` does not work. It seems to be a problem in escaping.


Did you try to use the option `autosections` when mounting the INI file? Then the needed null keys should be created automatically.


What is your intended behaviour if you use more then one hierarchy depth?

E.g. kdb set system/machinekit/FOO/BAR/EVEN/DEEPER 1.0

@tom-wa Do you have an opinion about deeper nesting?

**Comment by tom-wa** [comment]
i have some ideas here. the best approach imho would be turning every level except the last (key) into a section.
so `system/machinekit/FOO/BAR/EVEN/DEEPER 1.0`
would become 
```
[FOO]
[FOO/BAR]
[FOO/BAR/EVEN]
DEEPER = 1.0
```
i'd turn the whole keyset into a tree before writing it, and then apply all optional flags. that way you could easily add things like sorting, reordering, merging, etc and, if you want to, 
turn `system/machinekit/FOO/BAR/EVEN/DEEPER 1.0` into 
```
[FOO/BAR/EVEN]
DEEPER = 1.0
```
or 
```
[FOO]
BAR/EVEN/DEEPER = 1.0
```
by adding a flag

**Comment by fberlakovich** [comment]
regarding the topic of the issue: @markus2330 is right, the ```autosection``` option should yield the desired behavior.

**Comment by markus2330** [comment]
I am afraid there at least 4 different ways someone would expect from a INI-plugin:

1.) Turning everything except the outmost into a section

The file basically would be flat. The section would have no information and basically would not need a key for representation.

2.) Turning only the first level into a section

e.g. `system/machinekit/FOO/BAR/EVEN/DEEPER 1.0`

would be
```
[FOO]
BAR/EVEN/DEEPER = 1.0
```

Again, the file basically would be flat. And again, the section would have no information and basically would not need a key for representation.

3.) Null keys are sections

Now we are not flat anymore. We need a hierarchical understanding. Sections have a meaning.

At the moment we seem to have mixture, thus the different understandings.

@fberlakovich What was the idea of the `autosection`, should it represent 1. or 2.?

4.) Every part between a `/` forms a section

Thats basically what @tom-wa proposed. Then sections have no meaning (they are always present), the structure will be as in XML. Hierarchical understanding is needed.

I think @strahlex would be fine with both 1. and 2., if you only have 2 levels, it does not really matter.

The remaining questions are:

- should this INI plugin be the place to actually implement 3. or 4. (and thus go to a proper tree)?
- Or should we have a different plugin for that?

**Comment by tom-wa** [comment]
we could move that to a different plugin (plugin turns keyset into tree, back into keyset with arrays and subarrays). 
that way the storage plugins would only need to follow the array indexes and know some metadata it uses (aka section metakey, etc ..) and it could be used for every storage plugin (they would have to add some metakeys to tell the tree-plugin what to do though)

**Comment by fberlakovich** [comment]
@markus2330 As far as I can remember (I currently cannot verify it) the idea of autosections is the one you described in 1. The whole hiearchy goes into the section name and only the basename is used for the nonsection key.

**Comment by tom-wa** [comment]
`akey/looking/like/sections`
get turned into 
```
[akey]
looking/like/sections = ...
```
too ?
works with #376, but the testcase doesn't like it. (compares against ini/sectionini there it's still `akey/looking/like/sections` )

**Comment by strahlex** [comment]
And is there a way to automatically convert the key names to lowercase when importing into elektra? The uppercase names are legacy it does not make a lot of sense to import them in elektra. But it can not expected that all user files will be converted to lowercase naming.

**Comment by markus2330** [comment]
Yes, you can do that soon. (Or immediately if you write the plugin). @tom-wa has plans to improve the `rename` plugin to do lower-uppercase renames. It won't happen in the INI plugin, however, so please open a new issue if you want to discuss details.

**Comment by markus2330** [comment]
See #485
