### ISSUE TITLE
Upgrade to jdk11 [JNA bindings]

### ISSUE THREAD

**Issue by tucek** [ElektraInitiative/libelektra#3753]
- [x] Ensure all build images use jdk 11 (currently some buildenvironments are still using jdk 1.8)
- [x] Update Gradle project jave language level
- [x] Update JNA cmake java versioncheck
- [ ] Update language feature usage where appropriate

**Comment by markus2330** [comment]
Thank you for reporting the issue! I agree it is time to finally switch to jdk 11 :rocket:

**Comment by markus2330** [comment]
> Update language feature usage where appropriate

Is this still open?

**Comment by tucek** [comment]
no, marked task as done
