### ISSUE TITLE
Migrate to usage of Java specific formatter [JNA bindings]

### ISSUE THREAD

**Issue by tucek** [ElektraInitiative/libelektra#3756]
Currently clang is used to enforce Java code formatting. Since the resulting formatting is rather unusual for Java code, we should change the formatter.

Proposed candidate for evaluation: prettier java community extension. (since prettier i already in use and ide support seems quite ok)

**Comment by markus2330** [comment]
As said, such changes usually take much longer then one might expect and they introduce maintenance effort (one more tool to regularly update). So if you can somehow life with the style or maybe fix the problem by dropping another .clang-format in a sub-directory (I do not know if this works, though) we would have more time&energy for important stuff :wink:

**Comment by tucek** [comment]
Closed accidentally via PR.

**Comment by tucek** [comment]
Is it a known issue, that javascript formatting is broken?

**Comment by tucek** [comment]
https://github.com/google/google-java-format is now being used
