### ISSUE TITLE
Add external Grade test [JNA bindings]

### ISSUE THREAD

**Issue by tucek** [ElektraInitiative/libelektra#3759]
tests\shell\external\maven.sh has to be replaced by an appropriate Gradle variant due to Maven no longer being available in build images.

**Comment by markus2330** [comment]
Thank you for reporting this problem! Actually it would be good to also keep a maven project, and **add** a gradle project.

Iirc these external tests do not run on the build server anyway. It would be nice to integrate them.

**Comment by tucek** [comment]
> Thank you for reporting this problem! Actually it would be good to also keep a maven project, and **add** a gradle project.

I concur. I've already had added a gradle sample project (actually the same sources and locations as the maven sample project).
The test script is still to be added.

**Comment by tucek** [comment]
Since we are now publishing artifacts, does anyone really needs this test scripts? There is exhaustive information how to use the JNA binding with either gradle or maven (https://github.com/ElektraInitiative/libelektra/blob/master/src/bindings/jna/README.md) also referencing the provided example project...

**Comment by tucek** [comment]
@markus2330 my suggestion is to simply delete `tests/shell/external/maven.sh`

**Comment by markus2330** [comment]
I agree it is a bit over the top but automatically tested (and thus working) examples are very valuable, so it is always a pity if they get removed.

**Comment by tucek** [comment]
> Iirc these external tests do not run on the build server anyway. It would be nice to integrate them.
...
> I agree it is a bit over the top but automatically tested (and thus working) examples are very valuable, so it is always a pity if they get removed.

As i understood it was not an automatically run test anyways...

**Comment by markus2330** [comment]
Ok, then let us remove the maven test and let us automate the gradle test.

**Comment by tucek** [comment]
> Ok, then let us remove the maven test and let us automate the gradle test.

Gradle test are already automated (testjna_gradle and testmod_jni)
