### ISSUE TITLE
Spell checker should be included in reformatting

### ISSUE THREAD

**Issue by tucek** [ElektraInitiative/libelektra#3760]
The spell checker broke my CI build, because i spelled `Unix` as `unix`. To prevent unnecessary waiting for the CI to fail on such a trivial issue, i propose to include instructions on how to run the spell checker locally in `doc/tutorials/run_reformatting_script_with_docker.md`

**Comment by markus2330** [comment]
Yes, I agree, this is a good idea!

@robaerd can you maybe take a look at it?

**Comment by robaerd** [comment]
I will include this in #3739.
