### ISSUE TITLE
Boost: remove dependency

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3766]
Boost is not needed any more as all dependent plugins are gone.

Remove all boost references (except Boost license) from 

- [x] Docker images
- [x] `scripts/cmake/ElektraCache.cmake`
- [x] Cirrus
- [x] `scripts/cmake/Modules/PackagingFedora.cmake`
- [x] Find remaining occurences

The license is still needed due to `src/tools/kdb/gen/mustache.hpp`.

**Comment by markus2330** [comment]
Great maintenance job! One dependency less :rocket:
