### ISSUE TITLE
A specific Gradle version should be installed via macOS_gcc10.yml

### ISSUE THREAD

**Issue by tucek** [ElektraInitiative/libelektra#3770]
This would currently be 6.8.3.
I do not consider this ticket very important, since upgrade to Gradle 7.0 will be done shortly and the probability of breaking change affecting our simple Gradle project in then more recent Gradle versions is low IMHO.

**Comment by markus2330** [comment]
Can we close the ticket?

**Comment by mpranj** [comment]
Gradle is not installed there, afaik.

**Comment by tucek** [comment]
Gradle comes with the base image (7.0 at the time of writing). When i tried to install gradle via brew (6.8.3), i got the error that 7.0 is already installed.

**Comment by mpranj** [comment]
> Gradle comes with the base image 

You're right, it is included. Sorry for the wrong information before.

Thank you so much for checking it!

**Comment by tucek** [comment]
@mpranj The subject of this issue was to ensure that the same version of gradle as with the other ci images is installed. This still is not the case. This issue is definitely not urgent, but if we want to keep gradle versions the same between all ci images, we should keep this issue open...

**Comment by markus2330** [comment]
Actually, it is not a goal to have the same version of some software across the build infrastructure. Instead it has advantages to have diversity to test a broad range of possibilities. Of course some minimum version can be specified.

**Comment by tucek** [comment]
Then we can close this issue.
