### ISSUE TITLE
Use case: default and per config parameters

### ISSUE THREAD

**Issue by strahlex** [ElektraInitiative/libelektra#378]
To use libelektra for Machinekit configurations following scenario has to be considered:

We have global default parameters mounted into e.g. `system/machinekit/cnc`. This global default config also has meta values specifying the type of the parameter.

Each Machinekit configuration has its own per machine settings stored in an ini file. The ini file is located in the machine configuration directory. A typical configuration looks like this https://github.com/strahlex/mkwrapper-sim and is located somewhere in the users home directory. `mkwrapper.ini` is the file containing the per machine parameters. These parameters should be mounted on top of the global default parameters e.g. into `user/machinekit/cnc`.

Inside the Machinekit application I wan to be able to use a setting by accessing for example the key `/machinekit/cnc/AXIS_0/MAX_VELOCITY`. In case the key exists in the user parameters this value should be used, if not the value from the system configuration should be used.

Following problems:
- I cannot mount ini files as user - can be circumvented by giving the user access rights
- The ini plug-in only accepts relative paths from the `~/.config` directory, but my ini file is located somewhere else.
- How can I add meta keys to the global parameters?

**Comment by markus2330** [comment]
Default and other meta values should be mounted to `spec/machinekit/cnc`. How does this file look like or can you invent a new one?

Are the `.hal` files also considered as configuration files?

I think the `mkwrapper.ini` should be mounted to system then (if it contains per-machine parameters).

User-specific overwrites then should be mounted to user.

If you use `/machinekit/cnc/AXIS_0/MAX_VELOCITY` (its a cascading key), following will happen: https://github.com/ElektraInitiative/libelektra/blob/master/doc/help/elektra-cascading.md

Problems:
Why do you need to mount files later on? Once you have done a cascading mount, for every user and even for every directory the files are correctly used.
E.g.: `kdb mount mkwrapper.ini /machinekit/cnc ini` then when user `hugo` does a `kdb get user/machinekit/cnc` he will use `/home/hugo/.config/mkwrapper.ini`. In /etc/passwd you can define a different home directories. Or you can even use current directories with the `dir`-namespace.

You do not have to use relative pathes. Absolute pathes are possible, too and mean, depending on the namespace, something different. For spec and system absolute names are interpreted as-is. See https://github.com/ElektraInitiative/libelektra/tree/master/src/plugins/resolver

`kdb setmeta` with the dump plugin is the easiest, most robust way currently.
If you want meta data for many keys, you currently can use the `glob` plugin.
For next release, there hopefully will be a `spec` plugin which copies meta data from the `spec` namespace to the other namespaces.

**Comment by strahlex** [comment]
No meta files exist yet. They can be invented from scratch

`.hal` files are part of the configuration but not of the parameters. There is no need to load them into elektra.

I see the term configuration in the Machinekit context causes confusion:
*Machinekit configuration*: A set of configuration files that create a launch-able entity.
*Machinekit instance*: A running Machinekit configuration.

Machinekit has system default parameters that should be overwritten by the values contained in a Machinekit configuration. e.g. there might be a system `machinekit/cnc/DISPLAY/DISPLAY` containing the default display program. This value should be overwritten by the value contained in the Machinekit configuration file (`mkwrapper.ini`). 

Mounting at system startup or login is not an option since Machinekit instances are launched inside a login session and multiple Machinekit instances can co-exist on a single computer. The configuration parameters should be contained within the configuration directory to make portability as easy as possible. 

Machinekit configuration parameters are therefore no user settings and should not be stored in the `~/.config` directory. A user that executes Machinekit instance is also very likely to have admin access to the computer. Mounting in `system/` makes sense. However, how does aliasing of default parameters work when default parameters and configuration parameters are both store in `system/`? Or is this what `spec/` is for?

However, a Machinekit instance might also have a set of user parameters containing e.g. values set in a user interfaces. These should not be stored in the Machinekit configuration and storing them in `~/.config` is feasible.

**Comment by markus2330** [comment]
> No meta files exist yet. They can be invented from scratch

Thats good, then we can create a really nice specification!

> Machinekit has system default parameters that should be overwritten by the values..

So there are different levels how you can specify which values get overwritten.

1.) The "built-in-defaults" for a system where /etc was wiped out have to be in `spec` as `default` meta-data. Lets call it spec/machinekit/cnc/. They have the least priority, any present configuration file will overrule them.
2.) Then you could mount ini to /machinekit/cnc. This gives you a system **and** user configuration file **and** dir configuration file. You do not need any mounting at startup/login, mounting is permanent. This setup already covers the typical demans.
3.) In your case, however, you want an additional configuration file also in system (/etc) that should take presence. This can be done by mounting another file to, lets say to /machinekit/cnc/mkwrapper. Then you have to define in spec/machinekit/cnc/ which overwrites you want. E.g. `kdb setmeta spec/machinekit/cnc/DISPLAY/DISPLAY override/#0 /machinekit/cnc/mkwrapper/DISPLAY/DISPLAY`.

Its best if you just try it out and see with `kdb get -v` what happens when you request some values.

Portability: Elektra also gives you `kdb export`. But actually you can keep your approach with having everything in system for typical usage. The `spec` is done by you and the user should not mess around with it anyway. I would not store the `spec` file next to the other config files. (Even though its possible). But rather somewhere hidden in `/usr`.

The `~/.config` storage is for free when using cascading mountpoints. They will automatically be preferred to system configuration. If you do not want it, mount to `system` only.

**Comment by strahlex** [comment]
So from `spec/` only metadata is used? Is there a way to enforce storing keys in `system/` rather than in user when using the `/` prefix, e.g. by a metadata key?

**Comment by markus2330** [comment]
Yes, spec specifies the semantics of the other namespaces. While you could store values there, it usually only contains meta data.

>  Is there a way to enforce storing keys in system/ rather than in user when using the / prefix, e.g. by a metadata key?

Yes, with the metadata `namespace/#0 system`.

**Comment by strahlex** [comment]
Soo I would go for mounting the parameter files as follows:
- metadata  in `spec/`
- default parameters in `system/machinekit/default`
- per configuration parameters in `system/machinekit/mkwrapper-sim`
- user parameters in `user/machinekit/mkwrapper-sim`

Is there way to specify that `system/machinekit/default` should overwrite `system/machinekit/*`?

And does it make sense to handle resolving instance names on the parameter service level. E.g. on parameter service client I would change the key `cnc/DISPLAY/DISPLAY` instead of `/machinekit/<name of config>/cnc/DISPLAY/DISPLAY`?

**Comment by markus2330** [comment]
I extended https://github.com/ElektraInitiative/libelektra/blob/master/doc/tutorials/application-integration.md

**Comment by strahlex** [comment]
Okay, so actually resolving the instance name or number has to be done on application level (in my case parameter service). The idea is to be able to access the keys very easy inside the application itself. If the parameter service or Machinekit specific parameter library handles instance resolving, there is no reason to not use the uuid of the instance for this purpose. This way there will not be any collisions with other instances using their own set of parameter files.

I am still not sure how I can configure elektra to return the value from `default` for any lookup in `system/machinekit/*`. Expecting a single instance at a time would be easy, but in the future there might be support for multiple instances on a single system.

**Comment by markus2330** [comment]
@strahlex Currently the specification only works on per-key level, so every key in `spec/machinekit/default` needs to specify `override/#0`. So every `spec` key must exist. Using globbing, however, you can easily copy meta-data to every key matching to a glob. `spec/machinekit/*` would be the glob expression, then.

For such dynamic resolving, you can use contextual-lookups. They also can handle multi-instance lookups. But I would get the basics right, first.

**Comment by strahlex** [comment]
I tried following:
defaults.ini
````
DISPLAY/DISPLAY = mkwrapper
[DISPLAY/DISPLAY]
 check/type = string
 namespace/#0 = system
````
Executed following commands:
````
$ kdb mount `pwd`/defaults.ini spec/machinekit/cnc ni
$ kdb mount `pwd`/mkwrapper.ini system/machinekit/cnc ini dbus
$ kdb getmeta /machinekit/cnc/DISPLAY/DISPLAY namespace/#0
Metakey not found
$ kdb get /machinekit/cnc/DISPLAY/DISPLAY
mkwrapper
$ kdb set /machinekit/cnc/DISPLAY/DISPLAY axis
Using name user/machinekit/cnc/DISPLAY/DISPLAY
Set string to axis
````
However, I would expect this to be stored in `system/`. Is there something required to apply the metakeys from spec to the system keys?

**Comment by markus2330** [comment]
Yes, its the missing `spec`-plugin required which won't make it to the upcoming release (hopefully today).

The `getmeta` above would have worked, if a spec-plugin would distribute the meta-data accordingly, but thats not the case at the moment. So you should use: `kdb getmeta spec/machinekit/cnc/DISPLAY/DISPLAY "namespace/#0"` to get `system`.

For the last `kdb set` it obviously does not make sense that it defaults to `user`, so you should consider to use:
`kdb set system/sw/kdb/current/namespace system` then every cascading set goes to `system` as default.

For the features described above, however, you do not need the `spec`-plugin. But you need the INI fix #376 I merged today. On my system, after your procedure, everything works as expected. Even though in `user` we have stored `axis`:

    kdb get -v user/machinekit/cnc/DISPLAY/DISPLAY 
    axis

For the cascading lookup only `system` gets considers:

    kdb get -v /machinekit/cnc/DISPLAY/DISPLAY
    mkwrapper

**Comment by markus2330** [comment]
Btw.: its not needed that defaults.ini contains values, I think you wanted:
```
[DISPLAY/DISPLAY]
  check/type = string
  namespace/#0 = system
  default = from_spec_default
```
Then you still get the system key, if available, but from_spec_default if no system key exists.

**Comment by strahlex** [comment]
After the update to latest version of elektra and removing the `user/` key:
```
$ kdb get -v /machinekit/cnc/DISPLAY/DISPLAY
got 37 keys
searching spec/machinekit/cnc/DISPLAY/DISPLAY, found: <nothing>, options: KDB_O_CALLBACK
    searching proc/machinekit/cnc/DISPLAY/DISPLAY, found: <nothing>, options: 
    searching dir/machinekit/cnc/DISPLAY/DISPLAY, found: <nothing>, options: 
    searching user/machinekit/cnc/DISPLAY/DISPLAY, found: <nothing>, options: 
    searching system/machinekit/cnc/DISPLAY/DISPLAY, found: <nothing>, options: 
    searching default of spec/machinekit/cnc/DISPLAY/DISPLAY, found: <nothing>, options: KDB_O_NOCASCADING 
Did not find key
```
What does `options: KDB_O_NOCASCADING` mean?

**Comment by markus2330** [comment]
It seems like you removed your spec/machinekit/cnc/DISPLAY/DISPLAY key.

KDB_O_NOCASCADING means that the spec key will not be used for cascading (would be an endless-loop in the example above)

**Comment by strahlex** [comment]
Thanks, that was the case indeed.

**Comment by markus2330** [comment]
@tom-wa This should also be resolved when we have a profile plugin that allows defaults for every key within the same namespace.

**Comment by markus2330** [comment]
@strahlex Such behaviour with default/fallback values can now easily be obtained with the [profile plugin](https://github.com/ElektraInitiative/libelektra/tree/master/src/plugins/profile). You mount the configuration file with local preferences, e.g. `/etc/preferences.ini` to `/sw/machinekit/cnc/#0/current` (preferences there will always win). Then you can have multiple profiles that can be switched as you want. And finally you mount a `/etc/default.ini` to `/sw/machinekit/cnc/#0/%` which would be used if a key was not found in neither current nor the active profile.

Please open a issue if you something does not work for you as expected.
