### ISSUE TITLE
Pre / Postconditions and Invariants in API docs

### ISSUE THREAD

**Issue by lawli3t** [ElektraInitiative/libelektra#3798]
When creating the guidelines for my API reviews Markus and I decided to include the existence of `@pre` / `@post` / `@invariant` to the checklist. When conducting the review for all the core functions, almost none had any of those 3 annotations, and if they did not all 3.

When I implemented the changes from the API review I decided to temporarily skip the inclusion of those annotations for several reasons:

- A lot of them would be duplicated over many functions and / or really trivial like `key != NULL`
- Including a long list of those repeated and trivial Pre / Postconditions would significantly extend the length of the API documentation as the Preconditions all take up a separate line that is specially highlighted with extra margins. Is this special emphasis really warranted for such (mostly) trivial Pre / Postconditions?
- Many of the less trivial Annotations would be accompanied by longer explanations that are currently already included into the function's body. In my opinion those annotations should be kept rather short or they just devolve into an extended description of the function that would fit better into the real description of the function. Good examples for this would be valid Key names or Namespaces [1]. In this case this could be solved by linking to a general description of names. This would probably be the case for a lot of non-trivial preconditions.
- Some postconditions heavily depend on the passed parameters and are situational [2] [3]. Here the exact behaviour could be described and the function body and referenced in the Postcondition. But this would make the Postcondition somewhat superfluous.

What is your stance on including Pre / Postconditions and Invariants for every functions in the API documentation? There are several open questions:

- Is it really needed and practical?
- If yes, what kind of conditions would be included there? How trivial is too trivial? Or should every Condition without any exception be included?
- Should Conditions that apply to many functions be duplicated for every function?
- Should we move extended description from the function body into the Conditions and then remove them from the function body? Or should the Conditions just reference the detailed description of the function body?

[1] https://doc.libelektra.org/api/master/html/group__keyname.html#ga7699091610e7f3f43d2949514a4b35d9
[2] https://doc.libelektra.org/api/master/html/group__keyname.html#gae22037aad3f76f4454de4e6400637b39
[3] https://doc.libelektra.org/api/master/html/group__key.html#ga505575ebef060066984fe0f590081e37

**Comment by markus2330** [comment]
> Including a long list of those repeated and trivial Pre / Postconditions would significantly extend the length of the API documentation as the Preconditions all take up a separate line that is specially highlighted with extra margins. Is this special emphasis really warranted for such (mostly) trivial Pre / Postconditions?

No, for the trivial ones it is not. Furthermore, the error conditions already describe what happens if you pass a null pointer.

At one place, however, we should say that wherever a `Key` is expected, something created from `keyNew` must be passed. This can be directly in the introduction of `Key`. Also the invariant that key always must have a valid name can be documented there.

> In this case this could be solved by linking to a general description of names. This would probably be the case for a lot of non-trivial preconditions.

Exactly, I agree.

>  Is it really needed and practical?

It is needed that it is documented at one place. Copying it everywhere is (for the trival things) too much.

> Should Conditions that apply to many functions be duplicated for every function?

I think you need to find a solution for every individual condition, there cannot be a general rule for that.

The invariants are ensured by the objects themselves anyway, so to duplicate this information is imho useless. (Except to mention them in the error conditions.)

> Should we move extended description from the function body into the Conditions and then remove them from the function body? Or should the Conditions just reference the detailed description of the function body?

I don't think that links from conditions to function body make sense? If you link, then rather from all function to one common place like descriptions of key names or other invariants of `Key`/`KeySet`.

**Comment by lawli3t** [comment]
So, it seems the way going forward is to add pre / postconditions and invariants for every function in the public API. Depending on how often a specific condition / invariant occurs or its scope (for instance invariants for Key's) those will either be documented directly at the function or a respective module header.

I am currently working on adding them, but got stuck cause of other university responsibilites, I will be adding PRs for this where further discussion can take place.

**Comment by markus2330** [comment]
:+1: 

Invariants can be documented only at one place for Key/KeySet/KDB, they should not be specific to functions. If a specific invariant is very relevant for a function, it is better to link from the functions to the invariant.

**Comment by markus2330** [comment]
@lawli3t is there something still open here?
