### ISSUE TITLE
ansible localhost -m elektrafacts

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3804]
## Steps to Reproduce the Problem

```sh
ansible localhost -m elektrafacts
```

## Expected Result

Prints system: keys.

## Actual Result

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named kdb
localhost | FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/markus/.ansible/tmp/ansible-tmp-1619106747.63-13976-252114012508709/AnsiballZ_elektrafacts.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/markus/.ansible/tmp/ansible-tmp-1619106747.63-13976-252114012508709/AnsiballZ_elektrafacts.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/markus/.ansible/tmp/ansible-tmp-1619106747.63-13976-252114012508709/AnsiballZ_elektrafacts.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.elektrafacts', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_elektrafacts_payload_TjZHQo/ansible_elektrafacts_payload.zip/ansible/modules/elektrafacts.py\", line 6, in <module>\nImportError: No module named kdb\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
```

## System Information

- Elektra Version: master
- Ansible 2.9.20-1ppa~trusty

## Further Log Files and Output

`import kdb` works from python3 shells but not from python2

**Comment by kodebach** [comment]
> Ansible 2.9.20-1ppa~**trusty**

Ubuntu Trusty Tahr? That's pretty old (it's still got 1 year until EoL, but still)

> `import kdb` works from python3 shells but not from python2

Yes, Python2 is EoL and no longer supported. That's why Elektra doesn't support it.

Take a look at [this](https://docs.ansible.com/ansible/latest/reference_appendices/python_3_support.html) to find out how you can configure Ansible to use Python 3.

**Comment by markus2330** [comment]
> Ubuntu Trusty Tahr?

It was the recommended package for Debian.

> Take a look at this to find out how you can configure Ansible to use Python 3.

I didn't find a way to configure Ansible to use Python 3, your link describes to install Ansible with pip. We should mention in the docu that the python3 version of Ansible is required.

**Comment by kodebach** [comment]
> Ansible will automatically detect and use Python 3 on many platforms that ship with it. To explicitly configure a Python 3 interpreter, set the ansible_python_interpreter inventory variable at a group or host level to the location of a Python 3 interpreter, such as /usr/bin/python3. The default interpreter path may also be set in ansible.cfg.

https://docs.ansible.com/ansible/latest/reference_appendices/python_3_support.html#using-python-3-on-the-managed-machines-with-commands-and-playbooks

**Comment by markus2330** [comment]
Is the paragraph you quoted also relevant for the controller side?

**Comment by kodebach** [comment]
Sorry, I missed that. For the Controller side it seems the only way is to install via `pip3` instead of the System package. In a perfect world, the Elektra module would work with Python2 and Python3. However, IMO it is not worth the effort to add support for the deprecated Python2.

**Comment by markus2330** [comment]
Actually, it would mostly* be a revert of the commit which removed the python2 support. We even had support to compile python2+python3 bindings+plugins at once.

* cpack and other stuff was not done, though

It was actually surprising for me that ansible is still compiled with python2 as default.

With the 1.0 release Elektra python2 will hopefully be completely irrelevant? At least this was the hope when we removed python2 support.

**Comment by kodebach** [comment]
> Actually, it would mostly* be a revert of the commit which removed the python2 support.

No, the actual code of the Ansible Module only works with Python 3. The original version worked only with Python 2. There is probably a way to make work with both, but like I said, I don't think it is worth the effort.

> It was actually surprising for me that ansible is still compiled with python2 as default.

Ansible itself is written to work with both Python 2 and Python 3. Which version is used depends on the System you install it on. They want to support as many system as possible, so I suspect Ansible will still support Python 2 for many years. For example, Debian 11 was the first with Python 3 as a default, but Debian still has LTS support until 2022 (and Debian 8 has ELTS until 2022). More importantly RHEL 7 (which is made by the same company as Ansible) has support until 2024 (?) and uses Python 2 as the default.

All of this is no reason for Elektra to support Python 2, whose support fully stopped over a year ago.

**Comment by markus2330** [comment]
Yeah, hopefully Ansible also accept pure python3 modules. For now, we simply tell people a python3 version of Ansible is required, this should be clearly stated in https://galaxy.ansible.com/elektra_initiative/libelektra

Also urgent would be #3812

**Comment by markus2330** [comment]
I updated the README in 0.2.1

**Comment by kodebach** [comment]
> Yeah, hopefully Ansible also accept pure python3 modules.

They might not accept it for their official collection (https://github.com/ansible-collections). But for Galaxy it should be fine. Especially since not just Ansible module, but Elektra itself requires Python 3. So the only thing a Python 2 version of the module could do, would be printing an error stating that Python 3 is needed.

Should we keep this issue open? If so, we should rename it to "Python 2 support for Ansible".

**Comment by markus2330** [comment]
> but Elektra itself requires Python 3

As already said: Elektra's support for Python 2 is fully implemented, we could revert the commit removing it.

> Should we keep this issue open?

No, let us close it. I don't want @tom-wa to waste time on Python 2 support just because of a "they might not accept it". If it really creates troubles, we can reconsider, also post-1.0.

**Comment by kodebach** [comment]
> Elektra's support for Python 2 is fully implemented

This assumes that everything still works, after all the big changes recently (most importantly the key name change).

**Comment by markus2330** [comment]
Of course, there is always something to do (e.g. updating packages). The code itself is not even 100 lines long, see src/bindings/swig/python2/kdb.i 546150efe68729629e682a4db9a3d4b8fe1d974c
