### ISSUE TITLE
open decisions

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3839]
Decide about:

- [ ] Error Handling (e.g. adding thread-local var) #3797  #3737  #3029
- [ ] Memory Management (elektraMalloc etc.) #3750 #3731

Analysis needed first:

- [ ] aliases #3740 #3736 #3730
- [ ] iterators #3171 #2991 #3189
- [ ] refcounting #3869

**Comment by lawli3t** [comment]
# Decision Meeting

- date: tbd
- participants: tbd

## Agenda

### Error Handling

#### Return Codes are inconsistent across public API
https://github.com/ElektraInitiative/libelektra/issues/3029
https://github.com/ElektraInitiative/libelektra/issues/3737

##### Proposed Solutions
- Add documentation for errorKey to Doxygen
- Add thread-local error handling for getting information about errors

##### Open Questions
- Which functions could benefit from a thread-local error variable for getting different error codes?
- How can we streamline and implement such a global error-handling function


#### Error Handling for keyString()
https://github.com/ElektraInitiative/libelektra/issues/3797

##### Proposed Solutions
- Introduce thread-local error variable

##### Open Questions
- Which other functions would benefit from a thread-local error variable (all errorkey functions?)



### Memory Management

#### elektraMalloc()
https://github.com/ElektraInitiative/libelektra/issues/3750

##### Proposed Solutions
- Completely replace `elektraMalloc` with simple calls to `malloc`


#### Functions copying into a buffer
https://github.com/ElektraInitiative/libelektra/issues/3731

##### Proposed Solutions
- Completely remove functions copying into a buffer instead use `strdup (keyName (k))` for copying values



### Aliases

#### keySetMeta and keyGetMeta

https://github.com/ElektraInitiative/libelektra/issues/3736
https://github.com/ElektraInitiative/libelektra/issues/3730

##### Proposed Solutions
- remove dedicated `key*Meta` functions from the public API and replace them with standard KeySet functions

##### Proposed Solutions
- How can above solution be documented properly?


#### keyClear
https://github.com/ElektraInitiative/libelektra/issues/3730

##### Proposed Solutions
- remove `keyClear` from public API

##### Open Questions
- Is there any way we can remove `keyClear` altogether by merging its leftover functionality into another function?



### Iterators

https://github.com/ElektraInitiative/libelektra/issues/3171
https://github.com/ElektraInitiative/libelektra/issues/2991
https://github.com/ElektraInitiative/libelektra/issues/3189

##### Proposed Solutions


### Refcounting (?)

**Comment by kodebach** [comment]
> * Completely remove functions copying into a buffer instead use `strdup (keyName (k))` for copying values

Slight correction: The replacement for the general case is actually `strncpy(..., keyName (k), ...)` or in case of binary values `memcpy(..., keyValue (k), ...)`.

**Comment by lawli3t** [comment]
### Return Codes are sometimes insufficient
- Zweiten Kanal fuer Fehlermeldungen einfuehren
- Bei Funktionen mit erwarteten Fehlern, Fehlermeldungen via zweiten Kanal zurueck geben
- Return Codes je nach Typ vereinheitlichen und bei Bedarf kann der zweite Kanal fuer Fehlerinfos gecheckt werden

### Error Handling for keyString()
- Bei key == NULL 0 returnen, error code via zweiten kanal
- Bei key->value == NULL 0 returnen, error code via zweiten kanal
- Bei binary Value 0 returnen, error code via zweiten Kanal
- Ansonsten wie gehabt

### elektraMalloc()
- Ist-Stand behalten
- Plugin Developern freistellen die base Funktionen oder die Elektra Funktionen zu verwenden (insofern nur plugin-interner code betroffen)
- Stellen wo momentan nicht-elektra Funktionen verwendet werden fixen
- elektraMalloc / elektraCalloc / elektraRealloc aus public API entfernen

### Functions copying into a buffer
- Remove Functions
    keyGetName()
    keyGetUnescapedName()
    keyGetBaseName()
    keyGetString()
    keyGetBinary()
- use strncpy() / memcpy() instead

### keySetMeta and keyGetMeta
- replace function with static inline function
- add keyRemoveMeta

### better names
- ksAppendKey -> ksInsert

### aliases
- ksLookup (POP) -> ksRemoveKey

### keyClear
- remove from public API

### Iterators
-  remove functions related to internal iterator
ksRewind  
ksNext  
ksCurrent  
ksGetCursor  
ksSetCursor  
ksHead  
ksTail  
- change ksAtCursor -> ksAt
- implement external iterator


### Refcounting
