### ISSUE TITLE
JNA segfaults

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3868]
While testing #3846 I manged to produce a JNA segfault locally. Not in `testmod_jni`, but in `testjna_gradle`.

Here is the interesting part of the log:
```
Current thread (0x00007ff34c1392a0):  JavaThread "Cleaner-0" daemon [_thread_in_native, id=1211701, stack(0x00007ff391d5f000,0x00007ff391e60000)]

Stack: [0x00007ff391d5f000,0x00007ff391e60000],  sp=0x00007ff391e5d660,  free space=1017k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x8bc69]  cfree+0x29
C  [libelektra-core.so.5+0xf254]  ksClose+0x94
C  [libelektra-core.so.5+0xef3c]  ksDel+0x2c
C  [jna10044404941010663452.tmp+0x13574]  ffi_call_unix64+0x4c

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 1300  com.sun.jna.Native.invokeInt(Lcom/sun/jna/Function;JI[Ljava/lang/Object;)I (0 bytes) @ 0x00007ff3b478e989 [0x00007ff3b478e920+0x0000000000000069]
J 1287 c1 com.sun.jna.Function.invoke([Ljava/lang/Object;Ljava/lang/Class;ZI)Ljava/lang/Object; (769 bytes) @ 0x00007ff3ad54021c [0x00007ff3ad53fb60+0x00000000000006bc]
J 1176 c1 com.sun.jna.Function.invoke(Ljava/lang/reflect/Method;[Ljava/lang/Class;Ljava/lang/Class;[Ljava/lang/Object;Ljava/util/Map;)Ljava/lang/Object; (548 bytes) @ 0x00007ff3ad50fe8c [0x00007ff3ad50e900+0x000000000000158c]
J 1175 c1 com.sun.jna.Library$Handler.invoke(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object; (348 bytes) @ 0x00007ff3ad51bb2c [0x00007ff3ad519620+0x000000000000250c]
j  com.sun.proxy.$Proxy12.ksDel(Lcom/sun/jna/Pointer;)I+16
j  org.libelektra.ReferenceCleaner$KeySetCleanupTask.releaseKeySet()Z+7
j  org.libelektra.ReferenceCleaner$KeySetCleanupTask.run()V+31
J 847 c1 jdk.internal.ref.CleanerImpl$PhantomCleanableRef.performCleanup()V java.base@15.0.2 (10 bytes) @ 0x00007ff3ad451c1c [0x00007ff3ad451b20+0x00000000000000fc]
J 846 c1 jdk.internal.ref.PhantomCleanable.clean()V java.base@15.0.2 (16 bytes) @ 0x00007ff3ad4520ec [0x00007ff3ad451f40+0x00000000000001ac]
j  jdk.internal.ref.CleanerImpl.run()V+77 java.base@15.0.2
j  java.lang.Thread.run()V+11 java.base@15.0.2
j  jdk.internal.misc.InnocuousThread.run()V+20 java.base@15.0.2
v  ~StubRoutines::call_stub

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x00007ff4b32cbd40
```

This shows a few important things:
1. The JVM uses a separate thread for the Cleaner. This means race conditions with the `keyDel`/`ksDel` calls from native Elektra code are easily possible.
2. As expected, the segfault comes from `ksDel`, which confirms that we will need a reference counter KeySets.
3. There is no `keyDel` call on the stack, we segfault during a `free` directly in `ksClose`. This means the reference counter for `Key`s seems to work and avoids segfaults during the `keyDel` calls that happen in `ksClose`. Note: this is not 100% certain, since the first `ksDel` would have set `ks->size = 0`. If this part of memory is still unchanged, `ksClose` won't attempt to call `keyDel`.
4. The Cleaner implementation works, calls `ksDel` and should avoid memory leaks (but of course we need a reference counter to avoid other memory problems)

Full log: [hs_err_pid1211667.log](https://github.com/ElektraInitiative/libelektra/files/6566275/hs_err_pid1211667.log)

---

@markus2330 @tucek @mpranj

**Comment by tucek** [comment]
@markus2330 I'm not sure how i can help here from the Java side of things... If we want to introduce a ref counter for key sets it might be better if someone with a deeper knowledge of Elektra's C source would do that.

**Comment by tucek** [comment]
see #3869

**Comment by markus2330** [comment]
@kodebach can you please check if this problem is now gone with master?

**Comment by kodebach** [comment]
Both `testmod_jni` and `testjna_gradle` now run without segfaults.
