### ISSUE TITLE
Rename plugins needs an option for case conversion

### ISSUE THREAD

**Issue by strahlex** [ElektraInitiative/libelektra#387]
Has been already proposed in the README of the plugin: `"case: upper/lowercase the name (that are not part of parentKey!)"`

**Comment by markus2330** [comment]
Do you need more than simply ascii renaming? What about `-_` or umlauts?

**Comment by strahlex** [comment]
Just converting uppercase to lowercase conversion.

**Comment by strahlex** [comment]
https://github.com/ElektraInitiative/libelektra/pull/390

**Comment by markus2330** [comment]
Thanks, fixed by #390
