### ISSUE TITLE
KeySet might implement (Sorted)Set [JNA bindings]

### ISSUE THREAD

**Issue by tucek** [ElektraInitiative/libelektra#3870]
We should also consider implementing Key's hashcode/equals. What should define the identity?

- Just `getName`?
- Or since Keys are merely wrapper for native keys `getPointer`?

For SortedSet implementation

- Implementing `Comparable<Key>` for Key using `keyCmp` and letting `KeySet::comparator` return null should be the correct implementation

**Comment by markus2330** [comment]
> What should define the identity? Just getName?

Exactly, the (unescaped) key name.

> using keyCmp

Exactly.
