### ISSUE TITLE
Key/KeySet should implement AutoClosable [JNA bindings]

### ISSUE THREAD

**Issue by tucek** [ElektraInitiative/libelektra#3872]
Even provided the Cleaner works flawlessly, it might be an advantage to use try-with-resources with Keys and KeySets. Therefore implementing AutoClosable for these two classes might be worthwhile. The documentation should continue to clearly state that it is not a necessity to close Keys or KeySets.

`Key/KeySet::release` will be renamed to `*::close` and documentation will be updated accordingly.

**Comment by markus2330** [comment]
Why would this be needed? There are no resources connected to Key and KeySet, so the normal garbage collector should be enough. KDB is AutoClosable because it has (or might have) actual resources attached to it (like file handles).

**Comment by tucek** [comment]
The idea came up while discussing the Cleaner problems to enable try with resources syntax for manual clean-up. I agree, if the Cleaner works, we should not add Closable support to keep the API more clear.
From a Java perspective, the native key and key set resources could be seen as external resources to be closed IMHO.

**Comment by markus2330** [comment]
Ideally it should be completely transparent that this even is a binding and native parts are involved. It would be best if the whole Java API feels like native-Java.
