### ISSUE TITLE
Local error keys and usage of these in the Java bindings

### ISSUE THREAD

**Issue by tucek** [ElektraInitiative/libelektra#3873]
The C API uses Key's meta data to return error information. Functions requiring a parent key as input will use this key to return warnings and error information. Functions not having access to such a key often require an explicit error key to be passed for returning such information. (e.g.: `kdbClose`)
Creating such temporary keys currently requires a valid name (e.g. "/") in contrary to the documentation of `keyNew`:
https://github.com/ElektraInitiative/libelektra/blob/9471062a048e77024e3b3b934bc3a944bb4b5ab7/src/libs/elektra/key.c#L140-L152

1. Either we should be able to create such temporary keys with a NULL name or there should be a convention regarding the name
2. The Java binding should not publish this mechanism for error conveyance, because errors should always be mapped to exceptions anyways

**Comment by markus2330** [comment]
Take a look at the c++ binding: src/bindings/cpp/include/kdb.hpp

It basically makes the errorKey something internal, which is thrown along with the exception (to also have the original information and not only the rendered text).

And the default constructor of Key simply makes a Key with the name `/`, so there is no need for Key.KEY_LOCAL_NAME (which I still do not like; the tutorial doc/tutorials/java-kdb.md still refers to it, I fixed it in#3890).
