### ISSUE TITLE
remove Key::get*AndRelease methods [JNA bindings]

### ISSUE THREAD

**Issue by tucek** [ElektraInitiative/libelektra#3874]
Once the`Cleaner` works flawlessly, Java key representations `Key::get*AndRelease` convenience methods should be removed because they are of questionable value. If we can find a real use-case and benchmark it to confirm sensible performance advantage, they should be retained.

see https://github.com/ElektraInitiative/libelektra/pull/3863#discussion_r644391540

**Comment by markus2330** [comment]
I agree, the "release" methods can be removed.

**Comment by tucek** [comment]
Since `ENABLE_AUTO_NATIVE_REF_CLEANUP = false` currently effective renders `Key::release()` to a NOOP, we can remove the `Key::get*AndRelease`.
