### ISSUE TITLE
Enable Cleaner [JNA bindings]

### ISSUE THREAD

**Issue by tucek** [ElektraInitiative/libelektra#3875]
As soon as `Cleaner` works flawlessly, remove ENABLE_AUTO_NATIVE_REF_CLEANUP and enable automate clean-up.

see #3869, #4348

**Comment by tucek** [comment]
@kodebach I think `Cleaner` implementation should be re-enabled due to mounting java plugins via the process plugin. Do you concur?

**Comment by kodebach** [comment]
Yes, we should at least open a PR and to see if it works.

**Comment by tucek** [comment]
I tend to do this together with #4038 in the same PR, because the topics are quite connected. ok?

**Comment by tucek** [comment]
Merged implicitly via https://github.com/ElektraInitiative/libelektra/pull/4439 https://github.com/ElektraInitiative/libelektra/pull/4440

**Comment by tucek** [comment]
done
