### ISSUE TITLE
Support MSVC compiler

### ISSUE THREAD

**Issue by IngwiePhoenix** [ElektraInitiative/libelektra#3886]
# Steps to Reproduce the Problem

* Open a Visual Studio 2019 developer prompt
* `git clone` the repo

```sh
cd libelektra
mkdir out
cd out
cmake -G Ninja ..
# Fails to configure.
```

## Expected Result

A successful build configuration.

## Actual Result

Confusion... The log file is attatched.

## System Information

- Elektra Version: master
- OS: Windows 10, 64bit
- CMake `3.20.2`
- Ninja `1.10.2`
- MSVC (`cl.exe`): `19.28.29915 for x64`

## Further Log Files and Output
[CMakeError.log](https://github.com/ElektraInitiative/libelektra/files/6611606/CMakeError.log)
[CMakeOutput.log](https://github.com/ElektraInitiative/libelektra/files/6611607/CMakeOutput.log)

**Comment by markus2330** [comment]
Thank you for opening the issue!

Mingw is currently the only supported compiler for Windows (executables can be downloaded [here](https://build.libelektra.org/job/libelektra/job/master/lastSuccessfulBuild/artifact/artifacts/debian-buster-mingw-w64/elektra.zip)), others are work-in-progress, help is very much appreciated.

According the logs we pass some command-line flags to MSVC, which are not understood by MSVC, so new ifs in scripts/cmake/ElektraCompiling.cmake would be needed. But I doubt that this will be the only problem.

For your first steps with Elektra Linux, Mac OS or WSL(2) is recommended, e.g. see: https://www.libelektra.org/tutorials/contributing-with-visual-studio-windows

Btw.: I would be interested which project you intend to use Elektra for! :rocket:  Please do not hesitate to ask any questions here:exclamation:

**Comment by IngwiePhoenix** [comment]
> According the logs we pass some command-line flags to MSVC, which are not understood by MSVC

I'll take a quick look at it in a little. Maybe I can do something there. No guarantees though - MSVC is a clusterf*k... ;)

> Btw.: I would be interested which project you intend to use Elektra for! 

Well to be blunt: I am considering working towards my own linux distro with it's own desktop environment, focused on people with visual - and other - impairments. GNOME and KDE Plasma were surprisingly underwhelming. Whilst Plasma had desktop zoom that could be controlled with keyboard shotctus _and_ keyboard+mouse wheel, GNOME only had the first of the two. Only Cinnamon really had both out of the box. And desktop color inversion is a different topic alltogether; I had to make a custom script for GNOME and unbury the option in KDE's "Behaviours" settings.

So, yeah... Right now, Linux for visually impaired people is messy and I would like to change that. So I am learning SDL2, LVGL, Wayland and other such topics. One central part missing was a neat and well thought-out way of configuring the various parts - which is where I would like to use Elektra in. It feels like it would fit in nicely.

Another project is a webapp I am considering to work on where I would use elektra as a k/v storage for settings of the app itself (port, hostname, enabled services, ...).

**Comment by markus2330** [comment]
> I'll take a quick look at it in a little.

Thank you! Although this issue does not seem to be important for your Linux distro?

> Well to be blunt: I am considering working towards my own linux distro...

These are amazing news! It would be great to see a whole Linux distro configured with Elektra. We are currently working on following pieces, which could be of relevance for you:

- elektrify gsettings+kconfig by @mpranj 
- elektrify redshift by @qwepoizt 

"linux distro for visually impaired people" is actually a topic where other students might be interested. Do you already have code/website/...? How does your distro differ to Knoppix Adriane?

> One central part missing was a neat and well thought-out way of configuring the various parts - which is where I would like to use Elektra in. It feels like it would fit in nicely.

:+1: :fireworks: 

> Another project is a webapp...

Which programming language?

**Comment by IngwiePhoenix** [comment]
> Do you already have code/website/...?

Nope, just random concepts. ^^;

> How does your distro differ to Knoppix Adriane?

Hard to say, but I'd wager the following statement: I want to make a linux distro where visually impaired people - or other impaired people - would not have to forfeit on the "modern-ness" of the platform just to have it accessible. For instance: Cinnamon, albeit being able to be themed, still lacks modern features and graphical enhancements that GNOME 40 (and even 3.x) has. So it'd be great if there was software that didn't look ugly but was still very accessible even for the impaired. I am not a native speaker to be fair, but basically: A pretty linux distro for people with impairments. The other distros that went that route looked either very plain or even ugly; which is quite subjective, obviously. But, I don't see why a friend of mine, who is visually impaired and needs screen magnification, shouldn't be able to use a modern, wel looking linux distro just because of his impairment and lackluster accessibility support in common desktop environments.

This is kind of what I am targeting.

> Which programming language?

V. https://github.com/vlang/v
It compiles to C, so writing a libelektra binding for that is quite easy. Currently I am working with the devs to make binding/wrapper generation from C to V easier, and might even be able to introduce source-to-source translation from C to V. :)

**Comment by kodebach** [comment]
> > According the logs we pass some command-line flags to MSVC, which are not understood by MSVC
> 
> I'll take a quick look at it in a little. Maybe I can do something there. No guarantees though - MSVC is a clusterf*k... ;)

You may have more luck by using [Clang on Windows](https://docs.microsoft.com/en-us/cpp/build/clang-support-msbuild). I don't have much experience with Windows programming, but AFAIK it is a bit closer to the Unix ecosystem than MSVC.

Using WSL2 (if that is an option for you) should also [work out of the box](https://github.com/ElektraInitiative/libelektra/blob/master/doc/tutorials/contributing-windows.md)
