### ISSUE TITLE
mark status of plugins

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#389]
@tom-wa made a good proposal: We should somehow make it clear which plugins are more experimental and to try out things and which are production ready.

Ways to do it:

1. Experimental flag in contract which warns when mounting the plugin
2. Give good, bad, ugly or other tags to the plugins in the contract
3. Create subfolders in `plugins`, one of them contains experimental stuff
4. Only write it as text in the description of the contract (status-quo)

**Comment by manuelm** [comment]
3 is a bad idea.
1 isn't that good either. I don't care about stderr and I'm sure I would just ignore any contract flag.

I'd vote for removing experimental plugins from the ALL-compile time target. This way they hopefully don't end up in distro packages or at least get split into a separate unstable package.

**Comment by markus2330** [comment]
We could make 1. more strict by requiring the user of `kdb mount` to use .e.g `-i` `--ignore-warnings` or even `-f` `--force`.

We could reduce ALL, but that name is then somewhat self-contradicting. What about increasing the default set of plugins by everything except the experimental stuff?

**Comment by KurtMi** [comment]
Since every plugin has a CMakeLists.txt, the state of experimental or not could be marked there. When a experimental plugin gets added with cmake to the build process, we could throw a message.

**Comment by markus2330** [comment]
The question was split up in #415 and  #416.
