### ISSUE TITLE
put JNI plugins in their own processes

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3891]
As the attaching to existing JVMs has problems on its own (teardown maybe leads to crashes and we could not modify the classpath or other JVM arguments) @kodebach suggests we will instead put each JNI plugin in its own process, as it is currently done in the python plugin. I agree.

As @kodebach wrote in https://github.com/ElektraInitiative/libelektra/pull/3884#issuecomment-858146418
>  If we send the class name as well as the operation (open, get, etc.) to the Java process, you could also use a single process that dispatches to multiple plugin classes. Of course that requires a more advanced IPC method than a simple pipe, because the Java process would essentially act as a server and there would be multiple client instance on the native side.

I don't think this is a good idea, as it has similar drawbacks to attaching to JVMs: plugins would not be able to have their own JVM classpath+arguments. Furthermore, it is not a good idea to optimize without knowing what the bottleneck will be. Furthermore, I would prefer if we optimize libprocess, as then also the Python plugin could benefit from it. As we have many other important issues to attend to, I prefer not to do any optimizations at this point.

**Comment by kodebach** [comment]
> Furthermore, I would prefer if we optimize libprocess, as then also the Python plugin could benefit from it. 

The dispatching could work for Python as well. But I agree, one process per plugin would be much easier and I don't think it should be performance or resource problem since e.g. browsers also use loads of processes.

**Comment by markus2330** [comment]
Implementation seemingly started in #4239
