### ISSUE TITLE
Change unescaped form of root keys

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3902]
Currently, keys always have this form (`[...]` means `...` is optional, `·` is a zero byte):
- Escaped:
  ```
  [<namespace> <namespace-end>] <keyname-start> [<keyname>] <keyname-end>
    user        :                /                foo/bar    ·            = user:/foo/bar·
                                 /                foo/bar    ·            = /foo/bar·
    user        :                /                           ·            = user:/·
                                 /                           ·            = /·
  ```
- Unscaped:
  ```
  <namespace> <keyname-start> [<keyname>] <keyname-end>
   \x06        ·                foo·bar    ·            = \x06·foo·bar·
   \x01        ·                foo·bar    ·            = \x01·foo·bar
   \x06        ·                           ·            = \x06··
   \x01        ·                           ·            = \x01··
  ```

In this structure, root-level keys appear different. This is fine for escaped names, because they are meant only as a human-readable version and not for direct and easy manipulation. In the unescaped form, however, we want something that is nice for computers and programs. The current version is problematic, because it complicates code like this:

```c
// only works if parent is not root key
const char * relativeName = keyUnescapedName (key) + keyGetUnescapedNameSize (parent);
```

I am not yet sure how much work this would be, but we should probably change the structure of unescaped key names to be:
  ```
  <namespace> [<keyname-start> <keyname>] <keyname-end>
   \x06        ·                foo·bar    ·            = \x06·foo·bar·
   \x01        ·                foo·bar    ·            = \x01·foo·bar
   \x06                                    ·            = \x06·
   \x01                                    ·            = \x01·
  ```

This will make internal handling of unescaped names and conversion between escaped and unescaped form slightly more complicated, but it should make the majority of external code easier to write.

**Comment by markus2330** [comment]
I like the proposal :fireworks:

**Comment by markus2330** [comment]
@kodebach is anything open here?

**Comment by kodebach** [comment]
@markus2330 This might actually be an issue for FLOSS. Making the change could be pretty hard (the keyname code is pretty dense), but maybe someone (with good C knowledge) wants a challenge.

Fixing this should also solve the problem with `user:/%` which should map to `\x06··`, but that clashes with the root key `user:/`.

**Comment by markus2330** [comment]
Ok, lets try. Can you give some indications where the code in question is?

**Comment by kodebach** [comment]
All relevant code should be in `src/libs/elektra/keyname.c`, specifically `elektraKeyNameValidate`, `elektraKeyNameCanonicalize` and `elektraKeyNameUnescape` implement the keyname handling.
The tests for these are in `tests/ctest/test_keyname.c`.

- `elektraKeyNameValidate`: Nothing should need to change here. There are already tests in `test_keyname` that show `user:/%` is accepted.
- `elektraKeyNameCanonicalize`: Probably the hardest part. This needs to be changed to calculate the correct `usize` value. For root keys like `user:/` and `/` the `usize` should be 2 (namespace byte plus terminator). For keys with only a single empty part like `user:/%` and `/%` the `usize` should be 3 (namespace byte, separator and terminator).
- `elektraKeyNameUnescape`: This actually write the unescaped name. Should be easy to change once `elektraKeyNameCanonicalize` calculates the correct size.

There are some commented out tests in `test_keyname` that refer to this issue (`FIXME: broken, see #3902`). These should be uncommented and updated.

In addition to the C code, we also need to update `doc/KEYNAMES.md` and `scripts/keynames.py`.
