### ISSUE TITLE
Add root-level tests to `check_kdb_internal_suite`

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3903]
Currently, the unescaped form of root-level keys appears to be different (*). We should therefore introduce a version `check_kdb_internal_suite` that uses a root-level parent key in case plugins behave differently in such cases.

This issue may become somewhat obsolete with #3902, but additional tests can never hurt.

---

(*) They only appear different. There is still a regular structure behind all key names, but it is not the necessarily what one would expect and not the easiest structure to work with. See also #3902.

**Comment by markus2330** [comment]
@kodebach can you clarify which tests you mean?
