### ISSUE TITLE
ni as default plugin

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3905]
@kodebach can you test, similar to #3478 if ni would work as default plugin?

(Needed as fallback if toml is creating further problems.)

I am thinking that we could make ni and toml similar in behavior by giving them both a "meta" option so that they are able to store arbitrary metadata in sections for `spec:` and hierarchical configs in sections for the other namespaces.

**Comment by kodebach** [comment]
The `ni` format is better than `dump`, but I still wouldn't call it human-friendly. Also, I think `ni` is currently limited to a maximum key size (relative to the parent key) of 128:

https://github.com/ElektraInitiative/libelektra/blob/9bedbec071621e03e0607c04bfec6b31fc7800d3/src/plugins/ni/nickel-1.1.0/src/nickel.c#L36-L49

(Line 41 is important)

https://github.com/ElektraInitiative/libelektra/blob/28b58987caae1a2e56c11cb2c34687c990946f6a/src/plugins/ni/nickel-1.1.0/include/bohr/ni.h#L299

We could increase the limit, but the current code needs a fixed size I think.

https://github.com/ElektraInitiative/libelektra/blob/28b58987caae1a2e56c11cb2c34687c990946f6a/src/plugins/ni/nickel-1.1.0/include/bohr/ni.h#L23-L25

---

> if toml is creating further problems

I don't think `ni` would have fewer problems than `toml`. The only real difference is that the TOML spec mandates that files must be valid UTF-8, while `ni` can deal with arbitrary bytes. However, IMHO this is a point in favor of TOML.

> I am thinking that we could make ni and toml similar in behavior by giving them both a "meta" option

See https://github.com/ElektraInitiative/libelektra/pull/3478#issuecomment-871404740

**Comment by markus2330** [comment]
This restriction is probably irrelevant but the question is if there are problems in practice, e.g., mounting does not work or similar.

Can you create a PR where ni is used as default plugin and analyze which problems come up?

**Comment by kodebach** [comment]
> This restriction is probably irrelevant

You mean the key length? It is very much possible that there is a longer key, especially in the `system:/elektra/mountpoints` part of the KDB.

> Can you create a PR where ni is used as default plugin and analyze which problems come up?

I can create one later today, but IMO `ni` is not suitable as a default plugin anyway.

**Comment by markus2330** [comment]
Agreed, let us concentrate on TOML.
