### ISSUE TITLE
TOML: Arbitrary metadata without using comments

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3911]
This `ni` file
```ini
[]
mountpoint = mymountpoint.data

mykey/foo/bar = 123
mykey/foo/baz/bar = abc
mykey/foo/baz/boo = true

[mykey/foo/bar]
type = long_long
check/min = 100
check/max = 150

[mykey/foo/baz/bar]
type = string
check/minlength = 2

[mykey/foo/baz/boo]
type = boolean
default = 0
```

could be written as this `toml` file:

```toml
"/meta".mountpoint = "mymountpoint.data"

[mykey.foo]
bar = 123
baz.bar = "abc"
baz.boo = true
baz."boo/meta".default = false

[mykey.foo."bar/meta".check]
min = 100
max = 150

[mykey.foo.baz."bar/meta"]
check.minlength = 2
```

The key here is that `.` is TOML's separator for nested levels. So `mykey.foo` means `foo` within `mykey`. In Elektra we normally use `/` for that. In TOML `/` has no special meaning, so other parsers will just treat it as any old character. In the `toml` plugin however, we could give it special meaning.

The idea is that we use `/meta.` within a TOML key to separate the Elektra keyname from the metaname. So `baz.boo/meta.default` stands for the `default` metakey on the key `baz/boo`. To a standard TOML parser it would mean the `default` field within the `boo/meta` table within the `baz` table.

The `[mykey.foo.baz.bar/meta]` example shows that we actually wouldn't use `/meta.` as a separator, but instead would give a special meaning to all TOML keys/fields that have `/meta` at the end.

I haven't tested this idea yet, but I think this may be a solution. We would of course need a way to escape the `/` in cases where the Elektra key actually contains a `/`, but that shouldn't be too hard. TOML has a Unicode escape mechanism that would allow writing `/` as `\u002F`, but other tools might translate this back into a `/`, which would cause confusion. A simple way to fix this would be to use one of Unicode's Private-Use code points e.g. `\uEABC` to represent an actual `/`.

If it actually works, this would be a good solution IMO, because normally you wouldn't use a `/` within a key name part anyway (because of the need for escaping within Elektra), so this would minimize the collisions and therefore the need for escaping within TOML files.

_Originally posted by @kodebach in https://github.com/ElektraInitiative/libelektra/issues/3478#issuecomment-871404740_

**Comment by markus2330** [comment]
As said, I like the idea :rocket: 

Probably we should use `/@elektra.meta` as in FUSE?

**Comment by kodebach** [comment]
> Probably we should use `/@elektra.meta` as in FUSE?

That would be unnecessarily verbose IMO.

**Comment by markus2330** [comment]
About syntax: I think we should choose one way to express metadata (in the general sense) in TOML, either by `/` or by PUA (private-use) Unicode codepoint (see #3912).

>  That would be unnecessarily verbose IMO.

If it is still possible to have keys with base name `/meta` then it is unnecessary. With `/@elektra.meta` no escaping of such base names is needed (as it is reserved).

> `baz."boo/meta".default = false`

I cannot find this metadata in the original `ni` file? And the `type` seems to be missing?

> `[mykey.foo."bar/meta".check]`

I don't think this is a good idea. If we also allow meta-data to be put in sections there are too many variants of how it could be rendered. Please let us keep it simple: Only key names as section names, like in ni.

**Comment by kodebach** [comment]
> If it is still possible to have keys with base name `/meta` then it is unnecessary. With `/@elektra.meta` no escaping of such base names is needed (as it is reserved).

That is not correct.

1. Currently `®` is still used for reserved names, although that can be changed.
2. It is not about keys having the base name `/meta`, but about keys having a base name that **ends** with `/meta`.
2. We reserve names based on a keyname part prefix. I.e. key names that have a part starting with `@elektra` are reserved. But in the TOML case, we are talking about suffixes.

> I cannot find this metadata in the original `ni` file?

Fixed that. (Note: in `ni` we need `0`, because there is no type system, in TOML `false` is converted to `0`)

> And the `type` seems to be missing?

`type` metadata should only present in TOML files, if it cannot be inferred from the TOML type. In this case `false` is always a boolean. An example where a `type` is needed would be `type = short`, since integer values in TOML are inferred to be `long_long` (or `unsigned_long_long` for non-decimal values).

> I don't think this is a good idea. If we also allow meta-data to be put in sections there are too many variants of how it could be rendered. Please let us keep it simple: Only key names as section names, like in ni.

I disagree entirely. The whole point of doing it this way and not like `ni` is to give control to the user. Also in TOML this

```toml
[foo.bar]
baz = 123
```

and this

```toml
foo.bar.baz = 123
```

always have the same meaning. If we only allow one way, an external tool that knows TOML, but doesn't know Elektra restrictions could mess things up.

---

> I think we should choose one way to express metadata (in the general sense) in TOML

I thought about non-leaf values after thinking about this. Now that I though about both, I actually prefer to solution from #3912, because it requires no escaping. We could do something like this:

```toml
foo.bar = 123

# sets the value of foo
foo."\uECCC".value = "abcdef"

# sets check/minlength metakey on foo
foo."\uECCC".meta.check.minlength = 3
```

Or equivalently:
```toml
[foo]
"\uECCC".value = "abcdef"
bar = 123

[foo."\uECCC".meta]
check.minlength = 3
```

**Comment by markus2330** [comment]
> Now that I though about both, I actually prefer to solution from #3912

Thank you for your examples! It actually convinced me from the opposite. Even though the PUA (private-use) Unicode codepoint might be technically superior, similar to ®, in practice it looks to me totally annoying to actually write this. Using `/` looks to me much more convenient.

> because it requires no escaping.

We need escaping either way: applications are free to use PUA (private-use) Unicode codepoint within their key names for their (= the applications) private use.

> The whole point of doing it this way and not like ni is to give control to the user. 

If we learned anything from INI, then it is to avoid such complexities¹. If someone is not satisfied with the syntax he/she is free to write a new TOML dialect with a different or more flexible grammar.

¹ The problem is not to parse it but to remember what you parsed and then restore what the user wrote and what to do with new keys (which syntax should be preferred in which situations). If you cannot restore what the user wrote, it is always problematic for some users, even with the smallest details like indentation.

So please let us keep it simple and make one syntax. I would prefer:

```toml
[foo]
bar=123
"/value"="abc"
"/meta:check.minlength" = "3"
```
But I am fine with another syntax, too. What I am not fine with is with introducing complexities without a very clear need and a very strong commitment to maintain it. What is, however, very good about your approach is that "a part of the key name" distinguishes what metadata is (which is better than just to abuse sections for metadata). So this we should definitely keep, even if we only support one syntax.

**Comment by kodebach** [comment]
> in practice it looks to me totally annoying to actually write this

Yes, this is why I originally went with `/meta`. Although, I find `\uECCC` not that much worse to write than `/meta` (assuming the actual hex digits we'd use, are easy to remember). However, readability is much much worse with the PUA solution. `/meta` and `/value` would be pretty self-explanatory.

> We need escaping either way

There are a total of 137468 Unicode private-use codepoints. If we were fine with reserving `®elektra` without an escape mechanism, then reserving a private-use codepoint should be fine too.

> If we learned anything from INI, then it is to avoid such complexities¹.

Again a completely disagree. Is the `toml` plugin supposed to be a plugin for TOML or a plugin for TOML* "the Elektra TOML dialect".

> If someone is not satisfied with the syntax he/she is free to write a new TOML dialect with a different or more flexible grammar.

Actually you are suggesting we create a new TOML dialect now, not the other way around. TOML has a finished spec. If we actually want to support real TOML, we should adhere to it.

> ¹ The problem is not to parse it but to remember what you parsed and then restore what the user wrote and what to do with new keys (which syntax should be preferred in which situations). If you cannot restore what the user wrote, it is always problematic for some users, even with the smallest details like indentation.

The `toml` plugin is already pretty good at remembering what a file looked like. Even adding new keys in a specific way is pretty well supported. You just need to add the metadata that the `toml` plugin would generate. This works, because TOML has an actual type system with a concept of tables (which are different from INI sections) and a spec that defines names for concepts like "basic string" and "inline table", which can be used to describe the structure of a TOML file.

If people do need a guarantee that the results of writing TOML files are super predictable, then we could provide a separate mode for that. In this "strict mode", we would use the same parser (i.e. still support reading all valid TOML files). But the writer would produce a very simple format. I would suggest something very simple similar to `ni`:

```toml
# just list all key-value pairs as dotted keys, use /value suffix where needed
foo."bar/value" = "non-leaf value"
foo.bar.baz = "leaf value"

# for every key with metadata create a table with a dotted name and /meta suffix
[foo."bar/meta"]
mymeta = 123

[foo.bar."baz/meta"]
check.minlength = 3
```

Plus some additional rules, like "keys are written in keyset order", exactly where an how whitespace occurs, what happens to comments, etc.

> So please let us keep it simple and make one syntax.

We will support only one syntax. It is called TOML and is defined here: https://toml.io/en/v1.0.0 The syntax specifically is formally defined here: https://github.com/toml-lang/toml/blob/1.0.0/toml.abnf

---

Using a full TOML key to delimit metakeys (i.e. `"/meta"` in `foo."/meta".default`) is actually not the best idea. Using a suffix works better, because otherwise leaf keys with metadata have to be treated like non-leaf keys. This would apply to the PUA solution as well, so this actually another against using the Unicode PUA stuff.

```toml
foo.bar."/meta".default = 123
foo.bar = 456
```

The above wouldn't work, because it is not valid TOML. The first line defines `foo.bar` as an (implicit) table, but the second line then wants to define `foo.bar` as an integer. Similarly, these are also invalid TOML for exactly the same reason:

```toml
foo.bar."/meta/default" = 123
foo.bar = 456
```

```toml
foo.bar."/default" = 123
foo.bar = 456
```

```toml
foo.bar."\uECCC".default = 123
foo.bar = 456
```

To make this work you'd need to do:

```toml
foo.bar."/meta".default = 123
foo.bar."/value" = 456
```

With the suffix approach we don't have this problem:

```toml
foo."bar/meta".default = 123
foo.bar = 456
```

This is completely valid, because one line defines `foo."bar/meta"` as an (implicit) table and the other defines `foo.bar` as an integer.

**Comment by kodebach** [comment]
> _from https://github.com/ElektraInitiative/libelektra/discussions/3941#discussioncomment-1025829_
>
> Of course it would be TOML, but interpreted differently: In the metamode key=value would always refer to meta-data and sections would refer to keys. Afaik TOML does not specify how the emitted data structure looks like, so it should be perfectly valid to do this?

No it is not TOML. There is an official specification for TOML that defines both syntax and semantics. [It clearly states] that this
```toml
fruit.apple = "red"
```
and this
```toml
[fruit]
apple = "red"
```
have the same meaning. Both define a table `fruit` which contains the key `apple` with the value `"red"`.

TOML has datatypes (like JSON). Tables, Arrays, Strings, Integer, Floats, Booleans and the various Date/Time values are all distinct types. A plugin that actually supports TOML, interprets a valid TOML file according to the spec as tables, arrays, etc. **and then** transforms the result into a `KeySet`.

If we say that the snippets above are not the same, e.g. one defines the value for `fruit/apple` the other one defines metadata on `fruit`, then we are not conforming to the TOML spec. It wouldn't be safe anymore to use other TOML tools on these files, because they might transform between the two snippets above and expect the meaning to remain the same.

A way around that would be
```toml
# Key fruit/apple has value red
"fruit/apple" = "red"

# Key fruit has metakey apple with value red
[fruit]
apple = "red"

# Key fruit als has metakey banana with value yellow
fruit.banana = "yellow"
```
But I don't see how that is better than my propose `/meta` suffix solution. Especially, since this requires a totally different parser for "meta mode" and "normal mode", while the `/meta` suffix could be integrated nicely into the existing parser.

**Comment by markus2330** [comment]
> have the same meaning.

Yes but that shouldn't be a problem, both could be metakey apple with metavalue red in the key fruit. We could do the same for `ni`, then both have a meta-mode with the meaning: last level of hierarchy, usually indicated by sections, refer to metadata.

> But I don't see how that is better than my propose /meta suffix solution. Especially, since this requires a totally different parser for "meta mode" and "normal mode", while the /meta suffix could be integrated nicely into the existing parser.

There is no need to defend any particular solution as "mine"/"yours", let us find together advantages/disadvantages of each solution. Summarized what was said so far, /meta:

```
+ can be integrated more nicely into the parser
~ supports a more complex data structure (value and metadata intermixed), so some difficulties like comments moving from metavalues to values
```

So with only these two options in mind it boils down if we *want* intermixing (if ~ is a + or -). Intermixing has following pro/cons:

```
+ one storage plugins to rule them all (namespaces)
+ one file (format) can hold the export of all parts of Elektra
- syntactical more complex, people need to remember /meta (or whatever we decide)
```

So it basically is a tradeoff of more flexibility vs. simplicity. Simpler seems to me a clear separation: spec: only containing specs, other name spaces only containing configs.

Which usecases do we have for this higher flexibility besides dump/export functionality working for all namespaces?

**Comment by kodebach** [comment]
> There is no need to defend any particular solution as "mine"/"yours"

"mine" vs. "yours" was not supposed to be part of the argument. If it seemed that way that was my mistake. I just use "mine"/"yours" because it is the simplest way to refer to the two solutions.

That being said, "mine" vs. "yours" doesn't actually matter, because neither solution really works. To retain the structure of the file we would need meta-metadata in both cases. I'm not 100% sure, if you had this in mind in your solution, but the way I understood it, these would be valid ways of saying "key `foo` has metadata `check/range = 1-10`:
```toml
# in your solution
[foo.check]
range = "1-10"

# in my solution
["fruit/meta".check]
range = "red"
```
We cannot retain this structure, because we would need to remember, that `meta:/check` on `fruit` was a table.

Because we said retaining the structure of TOML files as important, I actually propose a different solution:

1. The `toml` plugin simply does not support storing metadata.
2. We will change the rest of Elektra so that storing metadata in config files is not needed (will be good for other storage formats too). This will likely involve changes to how spec works.

The first part is of course easy. The second part I fear will need to lengthy discussions and some deep changes. If we stick with this approach, the result will probably be some new restrictions. Especially, when it comes to arrays. It might even be the case that using a namespace and the structure of `KeySet` for specification is a bad approach. If we already know that `spec:/` is different, and needs a specialised storage plugin, why not go all the way and use a totally different format.

**Comment by kodebach** [comment]
> We will change the rest of Elektra so that storing metadata in config files is not needed

I had an idea for this. See #3954

**Comment by markus2330** [comment]
In this context, src/plugins/keytometa should probably mentioned. It restructures a KeySet without metakeys to a KeySet with metakeys. It is conceptually similar to the suggested /meta approach in TOML but with various limitations resulting because it is not a storage plugin.

> If we already know that spec:/ is different, and needs a specialised storage plugin, why not go all the way and use a totally different format.

It simply is not implemented yet. I played around a bit implementing simplespeclang (removed in a3d95f07160d792fdd0f169d8543138c32a2f580) but nobody had the time to actually implement a useful spec lang.

To make a nice spec lang is quite a big thing. I also don't think it is needed for 1.0, as ni works quite well as spec: plugin.

**Comment by kodebach** [comment]
`ni` works semi-decently for `spec:/`, but writing a specification can be quite repetitive and as soon as you want to do anything even a bit conditional, it becomes a nightmare. Those problems don't come from the storage format, but some of them might be fixed by using a different format. For example, to avoid repetitiveness a template system could be devised. This could also save memory (by reusing metakeys similar to what `spec` already does). It would be nice to have, but I agree it is not needed for 1.0

**Comment by kodebach** [comment]
TOML won't support metadata. When metadata is needed (e.g. for `spec:/`), another plugin like `ni` should be used.
