### ISSUE TITLE
TOML: non-leaf values without directoryvalue

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3912]
Adding non-leaf values could be supported by using a PUA (private-use) Unicode codepoint.

For example:

```toml
foo."\uEADD" = "non-leaf value"
foo.leaf = "leaf value"
```

would mean

```
foo = non-leaf value
foo/leaf = leaf value
```

This is not a perfect solution, since there could be a collision, if someone else tries to use the same PUA codepoint. However, I think this is just as unlikely as a collision with `___dirdata`. If we want to further reduce the collision probability, we could choose a random value from PUP-A (`\u000F0000`...`\u000FFFFD`)  or PUP-B (`\u00100000`...`\u0010FFFD`) instead of the PUA. However, I would choose a value that is somewhat easy to remember for the sake of human-friendliness.

**Comment by markus2330** [comment]
Which problem do you want to solve with this proposal?

**Comment by kodebach** [comment]
I thought the issue title and description would be obvious... The problem is: You need `directoryvalue` to allow non-leaf keys with value in TOML files.

**Why are non-leaf keys with value important?**
The simple reason is a default plugin needs to support them, IMO.

**Why is `directoryvalue` bad?**
1. `directoryvalue` is written in C++
2. Having the _default_ storage plugin depend on another plugin for something that can easily be implement without the extra plugin is a bad solution IMO.

**Why this solution?**
1. Using a private-use Unicode code point makes collisions very unlikely.
2. A simpler solution would be
  ```toml
  foo."" = "non-leaf value"
  foo.leaf = "leaf value"
  ```
  but that already maps to
  ```
  foo/% = "non-leaf value"
  foo/leaf = "leaf value"
  ```
  Elektra does support empty keyname parts, so mapping empty keys in TOML to empty keyname parts makes more sense.

---

PS. I previously thought that because we need to support metadata on a mountpoint parent (for `spec-mount`), we would also need this (to have an identifier for the mountpoint parent within the file). However, it turns out metadata on the parent key works even, if we don't support non-leaf values. I marked this issue as low-priority, but I do still think that this would be a valuable future improvement. Also because doing this non-leaf value translation inside TOML should actually be simpler than what `directoryvalue` needs to do.

**Comment by kodebach** [comment]
Another reason, why this is a problem: AFAIK there is currently no mechanism to load additional plugins, if `KDB_DEFAULT_STORAGE` has dependencies.

**Comment by markus2330** [comment]
Loading works via proxy plugins, e.g. we had the dini plugin which used ini with a fallback to dump if ini is not available. Such a proxy would be needed for base64, too.

C++ is indeed a problem for #3909. But it is still unclear if directoryvalues are needed at all. Let us keep it low prior unless it turns out it will be needed.

**Comment by kodebach** [comment]
> Loading works via proxy plugins

I really don't like that approach and one of the goals of #3693 is that plugins do not load other plugins. Only `libelektra-kdb` loads plugins and then plugins can get a reference to another plugin from `libelektra-kdb`.

> Such a proxy would be needed for base64, too.

No, we don't actually need a proxy for `base64`. Instead the `toml` plugin could simply return an error, if it encounters a binary key. If the `base64` plugin is loaded, it would transform all binary keys into string keys and the `toml` works fine. Similarly, if the mountpoint can't contain binary keys, there is no need for `base64` to be loaded.

> But it is still unclear if directoryvalues are needed at all.

If you have control of the spec, non-leaf values are never needed. You can always do a transformation similar to what `directoryvalue` does on the spec. So instead of using `foo` and `foo/bar` in the spec, you use `foo/value` and `foo/bar`.

---

Also to clarify, the issue with the default plugin having required dependencies is not a technical one. It is more a matter of principle. IMO the default backend configuration should be as simple as possible. Every bit of complexity is a source of errors and the default backend configuration absolutely must work under all circumstances.

**Comment by kodebach** [comment]
Won't be implemented for now.
