### ISSUE TITLE
restructure release notes to be more useful for 1.0

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3953]
@mpranj we already talked about it but we didn't get to a conclusion yet. How do we want to assemble the 1.0 release notes? As starting writing the 1.0 release notes already now is probably unrealistic, what about having sections in every release that will be copied to the 1.0 release notes? I am mainly thinking about highlights and breaking change but maybe we can restructure the release notes to make it even more suitable for that task?

**Comment by mpranj** [comment]
Copying&rewording from the highlights should be quite easy.

The breaking changes are more problematic, as it is possible that we already did not mention some subtle breaking changes. It sounds like we could benefit from adding a breaking changes section so that it is easier to copy to 1.0 later.

**Comment by markus2330** [comment]
Yes, I agree! Let us add a "breaking changes" section to every release from now on that summarizes what will be relevant for the 1.0 release. :rocket:
