### ISSUE TITLE
Jenkins CI Stages: add basic checks to one job

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3966]
### Discussed in https://github.com/ElektraInitiative/libelektra/discussions/3926

<div type='discussions-op-text'>

<sup>Originally posted by **mpranj** July  6, 2021</sup>
Should we add an additional stage with formatting checks etc. before anything else?

It has led to confusion when parallel builds are aborted, as error messages from aborted builds are meaningless. (recently in #3657)</div>

### Proposal

Combine all the basic checks that don't need to build the code (release notes, formatting, typos, man pages, etc.) into one job. The job should always run all the checks and report all results and not abort on the first error.

**Comment by markus2330** [comment]
Thank you for creating the PR! This will hopefully greatly improve the usability for newcomers!
