### ISSUE TITLE
undefined symbols after library split

### ISSUE THREAD

**Issue by manuelm** [ElektraInitiative/libelektra#397]
The new splitted libraries aren't that independent as outlined in your shiny uml image.

`elektra-kdb` depends on `elektraRenameKeys` + `ksPrev`
`elektra-core` depends on `keyLock` + `ksPopAtCursor`

So both libraries depend on `elektra-proposal`

I'm opting for removing `elektra-proposal` and merging it back to `elektra-core`. Don't see much use in splitting.

**Comment by markus2330** [comment]
Thanks, I am also afraid that this proposal concept will not work out. Typically they are used within the core already.

**Comment by markus2330** [comment]
Reconsidering, we could have internal elektra* functions in libcore and key* or ks* functions in libproposal.

The idea for splitting of libproposal is that it is completely obvious (and can be automatically determined) if only stable functionality is used or not.

A naming schema would be possible, too. But then users will always have to rename when a proposed function is moved to the API. (that was the status quo)

**Comment by manuelm** [comment]
> Reconsidering, we could have internal elektra* functions in libcore and key* or ks* functions in libproposal.
... which would still require linking `proposal` to both `core` + `kdb`. I fail to see the use for this additional lib.

**Comment by markus2330** [comment]
The implementation would be in libcore (called elektra*) and libproposal would only have the proposed interface (doing nothing but calling elektra*).

libproposal would be only linked against libcore then.

**Comment by manuelm** [comment]
ah ok. That would work, yes
