### ISSUE TITLE
Add second channel for error messages

### ISSUE THREAD

**Issue by lawli3t** [ElektraInitiative/libelektra#3972]
- Add a second channel for providing users / binding-maintainers with error messages
- Unify return codes in the process

TBD

- Which functions exactly should make use of the second channel?

**Comment by markus2330** [comment]
> Which functions exactly should make use of the second channel?

All of them: it must be reliable that if there is no error on the second channel there is no error at all.

**Comment by tucek** [comment]
> > Which functions exactly should make use of the second channel?
> 
> All of them: it must be reliable that if there is no error on the second channel there is no error at all.

So is the intention to report exceptional state via the second channel only? I thought the second channel would primarily be used to convey the specific error. (That would be relevant to my thesis...)

**Comment by markus2330** [comment]
> I thought the second channel would primarily be used to convey the specific error.

If the channel gives you the specific error it implicitly also tells you that there was an error (like with errno). Other ways to retrieve the presence of an error are available depending on the return type (with e.g. size_t or boolean you will not know if there was an error without looking at the second channel).
