### ISSUE TITLE
Error Handling for keyString()

### ISSUE THREAD

**Issue by lawli3t** [ElektraInitiative/libelektra#3973]
- On `key == NULL` return 0, error code via second channel
- On `key->value == NULL` 0 return 0, error code via second channel
- On `binary Value` 0 return 0, error code via second channel
- every other case stays the same

**Comment by Eiskasten** [comment]
@bhampl and I want to work together on this issue. As far as I understand this relates only to the C version of `keyString()`? If so, where can we find the implementation? I was not able to locate the definition in the C sources.

**Comment by bhampl** [comment]
As far as I can tell the relevant definition and the implementation are here: https://github.com/ElektraInitiative/libelektra/blob/f2b9d555a2de6da944781bd9edb4a2a877cd3c35/src/include/kdb.h.in#L198 https://github.com/ElektraInitiative/libelektra/blob/f2b9d555a2de6da944781bd9edb4a2a877cd3c35/src/libs/elektra/keyvalue.c#L213-L228 Is this correct?

**Comment by kodebach** [comment]
Yes, that are the relevant code snippets for this issue. However, I don't think this is a good issue for CM. But if you do #3975 that would already be enough for CM, so no need to find a replacement for this issue.

**Comment by Eiskasten** [comment]
Ok, thank you for clarifying that. I suppose that we should remove us from the assignees as well?
