### ISSUE TITLE
elektraMalloc() et al.

### ISSUE THREAD

**Issue by lawli3t** [ElektraInitiative/libelektra#3974]
- keep current state with elektra* functions
- In the future plugin developers can choose whether to use the base or the Elektra functions (as long as only plugin code is affected)
- Use elektra-functions in the Elektra code where they are currently not used
- remove elektraMalloc / elektraCalloc / elektraRealloc from public API

**Comment by markus2330** [comment]
> In the future plugin developers can choose whether to use the base or the Elektra functions

If they choose to use elektraMalloc, they should mark it in infos/status, see #666
