### ISSUE TITLE
Remove functions copying into a buffer

### ISSUE THREAD

**Issue by lawli3t** [ElektraInitiative/libelektra#3975]
Remove:
- `keyGetName()`
- `keyGetUnescapedName()`
- `keyGetBaseName()`
- `keyGetString()`
- `keyGetBinary()`

Suggested alternative:
`strncpy(..., keyName (k), ...)` or in case of binary values `memcpy(..., keyValue (k), ...)`

**Comment by markus2330** [comment]
Thank you for creating the issue!

> Suggested alternative

for the migration:

**Comment by Eiskasten** [comment]
@bhampl and I want to work on this issue. As far as I can see, none of these definitions exist (anymore)? So the task would be to remove all the related documentation, am I right?

**Comment by kodebach** [comment]
At least `keyGetString` still exists

https://github.com/ElektraInitiative/libelektra/blob/f2b9d555a2de6da944781bd9edb4a2a877cd3c35/src/libs/elektra/keyvalue.c#L326-L353

and is even still declared in kdb.h

https://github.com/ElektraInitiative/libelektra/blob/f2b9d555a2de6da944781bd9edb4a2a877cd3c35/src/include/kdb.h.in#L199

**Comment by bhampl** [comment]
That is what I found:

- `keyGetName()`: [declaration](https://github.com/ElektraInitiative/libelektra/blob/f2b9d555a2de6da944781bd9edb4a2a877cd3c35/src/include/kdb.h.in#L177) and [implementation](https://github.com/ElektraInitiative/libelektra/blob/f2b9d555a2de6da944781bd9edb4a2a877cd3c35/src/libs/elektra/keyname.c#L381-L405)
- `keyGetUnescapedName()`: no declaration but [implementation](https://github.com/ElektraInitiative/libelektra/blob/f2b9d555a2de6da944781bd9edb4a2a877cd3c35/src/libs/elektra/keyname.c#L435-L454)
- `keyGetBaseName()`: [declaration](https://github.com/ElektraInitiative/libelektra/blob/f2b9d555a2de6da944781bd9edb4a2a877cd3c35/src/include/kdb.h.in#L187) and [implementation](https://github.com/ElektraInitiative/libelektra/blob/f2b9d555a2de6da944781bd9edb4a2a877cd3c35/src/libs/elektra/keyname.c#L1323-L1348)
- `keyGetString()`: [declaration](https://github.com/ElektraInitiative/libelektra/blob/f2b9d555a2de6da944781bd9edb4a2a877cd3c35/src/include/kdb.h.in#L199) and [implementation](https://github.com/ElektraInitiative/libelektra/blob/f2b9d555a2de6da944781bd9edb4a2a877cd3c35/src/libs/elektra/keyvalue.c#L326-L353)
- `keyGetBinary()`: [declaration](https://github.com/ElektraInitiative/libelektra/blob/f2b9d555a2de6da944781bd9edb4a2a877cd3c35/src/include/kdb.h.in#L202) and [implementation](https://github.com/ElektraInitiative/libelektra/blob/f2b9d555a2de6da944781bd9edb4a2a877cd3c35/src/libs/elektra/keyvalue.c#L448-L473)

**Comment by Eiskasten** [comment]
Sorry for that, I totally missed the whitespaces between the identifier and the parentheses.

**Comment by markus2330** [comment]
Tip: As these changes are probably quite large, please remove one function after the other in different PRs. Start with the one with the least occurrences.

**Comment by markus2330** [comment]
@kodebach can you do this with your tool, too?

**Comment by kodebach** [comment]
Yes, should be possible.
