### ISSUE TITLE
Remove Internal Iterator

### ISSUE THREAD

**Issue by lawli3t** [ElektraInitiative/libelektra#3976]
remove functions related to internal iterator:
- `ksRewind`
- `ksNext`
- `ksCurrent`
- `ksGetCursor`
- `ksSetCursor`
- `ksHead`
- `ksTail`

change `ksAtCursor` -> `ksAt`
document new way of iterating

**Comment by kodebach** [comment]
This list should also include the versions for the metadata keyset, e.g. `keyNextMeta` and `keyCurrentMeta`.

**Comment by markus2330** [comment]
@flo91 which parts are still open in this issue?
