### ISSUE TITLE
Rename ksAppendKey to ksInsert

### ISSUE THREAD

**Issue by lawli3t** [ElektraInitiative/libelektra#3978]

**Comment by markus2330** [comment]
How do we call ksAppend then?

**Comment by markus2330** [comment]
@lawli3t there is still an open question

**Comment by lawli3t** [comment]
I would have thought `ksAppend` just keeps its name

**Comment by markus2330** [comment]
Sounds inconsistent to me as they are basically doing the same thing (either with a Key or a KeySet)?

**Comment by kodebach** [comment]
How about `ksInsert` and `ksInsertAll`?

I think the main issue is that "append" suggests adding to the end, which is not at all what happens.

**Comment by flo91** [comment]
This issue is part of the issue #4411 which is tagged as `project2022w`.
Maybe we can also offer this issue as a separate FLOSS task.

**Comment by kodebach** [comment]
In general, people should prefer different issues over these simple rename/API change issues, because the renaming/API changes can (hopefully) be done with the tool I'm developing for my thesis.

If people still choose issues like this one, it would be nice if they could record how much time they spent. Then I could use that data as a comparison in my thesis. (I can always just run my tool on an old commit before the change to get some results.)

cc @markus2330

**Comment by markus2330** [comment]
I agree that the renaming parts are better done by the @kodebach's tool.

> it would be nice if they could record how much time they spent.

@kodebach If you really want to do that, you need to precisely clarify what they should do (how to measure the time etc. according to your methodology) I can ask in the course who wants to do that. Then we should also carefully select which renaming (in case of doubt randomly. Letting the people select is not a good idea, as they will probably bias to simple renaming tasks).

**Comment by kodebach** [comment]
I'll see if I can come up with some concrete instructions. But this comparison "manual vs. tool" (intentionally) isn't really required to answer my research questions. So I would have just added the comparison as some examples of how the tool can help make things easier, not as a rigorous scientific evaluation.

**Comment by markus2330** [comment]
Yes but even as an example (case study) it must be clear what the people did. Maybe even more important than instructions is a small questionnaire which gives insights which tooling they used (e.g. an IDE, sed, ...).

Anyway, I will tell the students that this is an option. Can you create an explicit issue for the renaming/removal you would like to be done or can it be any renaming/removal?

**Comment by kodebach** [comment]
In general any renaming should be fine. Removal functions depends on what the replacement is. If there is a straight-forward replacement then it should also be fine, e.g. `keyGetMeta` -> `ksLookupByName (keyMeta)` + add `meta:/` prefix is missing. If the replacement is more complex and requires looking at the surrounding code, then I'd need to take a look to decide whether it would be useful for my thesis.

I can provide a list, but I'm not sure when I'll find time to do this. It's probably easier and quicker, if people just ask me for a specific API change they want to do.
