### ISSUE TITLE
Move functionality of ksLookup(..., KDB_O_POP) to a new function ksRemoveKey

### ISSUE THREAD

**Issue by lawli3t** [ElektraInitiative/libelektra#3979]

**Comment by markus2330** [comment]
It doesn't need to be a move, it could be an alias.

**Comment by markus2330** [comment]
@tucek you can immediately offer something like this in the Java API, the aliases are not useful for the bindings anyway.

**Comment by tucek** [comment]
> @tucek you can immediately offer something like this in the Java API, the aliases are not useful for the bindings anyway.

@markus2330 please have a look at the newly created corresponding issue #3982 - i could include that with PR #3790
