### ISSUE TITLE
keyCopyMeta does not clear values not set in second parameter

### ISSUE THREAD

**Issue by lawli3t** [ElektraInitiative/libelektra#3981]
_Originally posted by @markus2330 in https://github.com/ElektraInitiative/libelektra/pull/3851#discussion_r632901539_

**Comment by lawli3t** [comment]
Offending test case:

```
	succeed_if (key1 = keyNew ("/", KEY_END), "could not create key");
	succeed_if (key2 = keyNew ("/", KEY_END), "could not create key");

	succeed_if (keySetMeta (key2, "mymeta", "a longer metavalue") == sizeof ("a longer metavalue"), "could not set metavalue");
	succeed_if_same_string (keyValue (keyGetMeta (key2, "mymeta")), "a longer metavalue");

	succeed_if (keyCopyMeta (key2, key1, "mymeta") == 0, "could not copy metavalue");

	succeed_if (keyGetMeta (key1, "mymeta") == 0, "value of mymeta is not NULL");
	succeed_if (keyGetMeta (key2, "mymeta") == 0, "value of mymeta has not been cleared");

	keyDel (key1);
	keyDel (key2);
```

**Comment by markus2330** [comment]
Thank you for creating this bug!

**Comment by JakobWonisch** [comment]
[FLOSS H1]

The mentioned tests are not in `testabi_meta.c` at the moment, which allows all tests there to pass. If inserted we can see, that the problem still exists.

In `keyCopyMeta` when trying to copy a nonexistent key `ksLookup` is called to find that key in the destination with `NULL` as parameter for the target key. This leads to an instant return in `ksLookup`, meaning the key is never found and cannot be deleted.
