### ISSUE TITLE
Introduce KeySet::remove(Key)

### ISSUE THREAD

**Issue by tucek** [ElektraInitiative/libelektra#3982]
Currently the Java binding API for the key set only provides `Key KeySet::remove(int)` to remove the key at a specified index from the key set while returning the removed key or throwing IndexOutOfBoundsException on illegal indices.

The following additional method is being introduced with this issue:
`boolean KeySet::remove(Key)` removes the specified key while returning true, if the key actually was contained by the key set, false otherwise. Thrown exceptions are: `KeySetReleasedException` if this key set has already been released, `KeyReleasedException` if the specified key has already been released and `IllegalArgumentException` if the specified argument is null valued.

**Comment by tucek** [comment]
Implementation done with PR #3790

**Comment by markus2330** [comment]
Thank you, good improvement. I do not understand the name "KeySetReleasedException".

**Comment by tucek** [comment]
> KeySetReleasedException

from its javadoc: "Indicates that an already released `KeySet` has been accessed"
in this case the exception is raised if the key set, where remove is being invoked on, already has been released

**Comment by markus2330** [comment]
> "Indicates that an already released KeySet has been accessed"

So it is basically an out-of-bound exception? The sentence is still not very clear to me: If you e.g. call remove(5), does it really matter if there was the 5th Key there at some point and then released¹ later or if it never was inserted?

¹ released is also not standard terminology. Do you mean the state after remove(int) or keyDel or ksDel?

**Comment by tucek** [comment]
> > "Indicates that an already released KeySet has been accessed"
> 
> So it is basically an out-of-bound exception? The sentence is still not very clear to me: If you e.g. call remove(5), does it really matter if there was the 5th Key there at some point and then released¹ later or if it never was inserted?
> 
> ¹ released is also not standard terminology. Do you mean the state after remove(int) or keyDel or ksDel?

I think there is a misunderstanding: `KeySetReleasedException` was thrown by methods of `KeySet`, if the `KeySet` has been already released (using `KeySet::release`) - has been replaced by `IllegalStateException` in the meanwhile...

**Comment by markus2330** [comment]
Yes, it seems to be unrelated, please open a new issue. KeySetReleasedException is basically a NullPointerException? Shouldn't it inherit from NullPointerException then? But the even more important question is if we should offer a release functionality?

**Comment by tucek** [comment]
> Yes, it seems to be unrelated, please open a new issue. KeySetReleasedException is basically a NullPointerException? Shouldn't it inherit from NullPointerException then? But the even more important question is if we should offer a release functionality?

I think we can remove the possibility for a manual native resource release for `Key` and `KeySet` as soon as the garbage collector based clean-up of native resources is working (see #3875). I've created #4038 to track this issue.
