### ISSUE TITLE
No validation warning when check/enum is used with type=string

### ISSUE THREAD

**Issue by qwepoizt** [ElektraInitiative/libelektra#3983]
I'd like to fix this as part of my thesis.

I am not sure if this is a user error. 

Would it make sense to improve usability by either:
1. throwing an error on mount (or spec-mount?) if a key uses `type=string` and `check/enum` (instead of `type=enum`)
2. or adding support for keys using `type=string` and `check/enum` (instead of `type=enum`)

?

## Steps to Reproduce the Problem

1. Create file `test.ini` with content: 
```
[]
mountpoint = test.ecf

[myenum]
type = string
check/enum = #1
check/enum/#0 = legalvalue1
check/enum/#1 = legalvalue2
```

2. ``sudo kdb mount -v `pwd`/test.ini spec:/tests/test ni``
3. `sudo kdb spec-mount /tests/test/`
4. `kdb set /tests/test/myenum neitherlegalvalue1nor2`

## Expected Result

kdb output for step 4 should be:
```
Using name user:/tests/test/myenum
Sorry, module type issued the error C03200:
Validation Semantic: The type 'string' failed to match for 'user:/tests/test/myenum' with string: 'neitherlegalvalue1nor2'
Allowed values: 'legalvalue1', 'legalvalue2'
```

## Actual Result
kdb output for step 4 is:
```
Using name user:/tests/redshift/provider/location
Create a new key user:/tests/redshift/provider/location with string "asdf"
```

## System Information

- Elektra Version: 0.9.7
- Operating System: Ubuntu 20.04
- Versions of other relevant software: n/a

**Comment by markus2330** [comment]
Thank you for creating this issue! I agree that this is a bug and a big usability problem!

I would prefer the 1. variant: if types contradict each other, an error should be thrown.

**Comment by qwepoizt** [comment]
Thanks @markus2330 for your input. I will get back to you after my work on other issues.

**Comment by qwepoizt** [comment]
@markus2330 I've created #4058 to fix this.

**Comment by qwepoizt** [comment]
Closing this as the specific issue was fixed and the general problem is described in #4075 .
