### ISSUE TITLE
check/range uses check/type and not type

### ISSUE THREAD

**Issue by qwepoizt** [ElektraInitiative/libelektra#3984]
I'd like to fix this as part of my thesis.

Is this a sensible improvement or is there a reason for the current behavior?

check/range does not respect the `type` of a key. It uses the value of `check/type` and if none is set it defaults to `long long` (see https://www.libelektra.org/plugins/range).

If one does not carefully read the documentation, the current behavior is irritating.

## Steps to Reproduce the Problem

1. Create file `test.ini` with content: 
```
[]
mountpoint = test.ecf

[myfloat1a]
type = float
check/range = 0-1

[myfloat1b]
type = float
check/range = 0.0-1.0

[myfloat1c]
type = float
check/type = float
check/range = 0.0-1.0
```

2. ``sudo kdb mount -v `pwd`/test.ini spec:/tests/test ni``
3. `sudo kdb spec-mount /tests/`
4. `kdb set /tests/test/myfloat1a 1.1`
5. `kdb set /tests/test/myfloat1b 1.1`
6. `kdb set /tests/test/myfloat1c 1.1`

## Expected Result

kdb output for step 4 should be:
```
Using name user:/tests/test/myfloat1a
Sorry, module range issued the error C03200:
Validation Semantic: Value '1.1' of key 'user:/tests/test/myfloat1a' not within range 0.0-1.0
```

kdb output for step 5 should be:
```
Using name user:/tests/test/myfloat1b
Sorry, module range issued the error C03200:
Validation Semantic: Value '1.1' of key 'user:/tests/test/myfloat1b' not within range 0.0-1.0
```

kdb output for step 6 is:
```
Using name user:/tests/test/myfloat1c
Sorry, module range issued the error C03200:
Validation Semantic: Value '1.1' of key 'user:/tests/test/myfloat1c' not within range 0.0-1.0
```

### kdb output for step 4 is:
```
Using name user:/tests/test/myfloat1a
Set string to "1.1"
```

**Problem**: check/range accepted `1.1` because the truncated long long `1` is <= 1.

### kdb output for step 5 is:
```
Using name user:/tests/test/myfloat1b
Sorry, module range issued the error C03100:
Validation Syntactic: Invalid syntax: 0.0-1.0
```

**Problem**: check/range reports that the range `0.0-1.0` is invalid, because `check/type` is not set, defaults to `long long` and neither `0.0` nor `1.0` is a valid `long long`.

### kdb output for step 6 is:
 correct. check/range successfully detected that `1.1 > 1.0`
```
Using name user:/tests/test/myfloat1c
Sorry, module range issued the error C03200:
Validation Semantic: Value '1.1' of key 'user:/tests/test/myfloat1c' not within range 0.0-1.0
```

## System Information

- Elektra Version: 0.9.7
- Operating System: Ubuntu 20.04
- Versions of other relevant software: n/a

**Comment by markus2330** [comment]
Thank you for the issue, the issue is again excellently written.

I agree this is a bug. The same set commands repeated should not have different outcome (should be idempotent). Probably we need to simplify the type plugin to eliminate such behavior.

**Comment by qwepoizt** [comment]
@markus2330 Did you notice that steps 4., 5. and 6. are not equal? They all set a different key: myfloat1**a**, myfloat1**b**, myfloat1**c**.
That means it is actually not "The same set commands repeated" :).

The key questions are: 

1. Is there any value in having both metadata `type` and `check/type`? I don't mean setting both, I mean having two different metadata for specifying type.
2. Can one metadata be deprecated in favour of the other?
3. If not, there should be an error/warning, whenever `type` (or the value it defaulted to) is not equal to `check/type` (or the value it defaulted to), shouldn't it?

**Comment by qwepoizt** [comment]
Thanks @kodebach and @markus2330 for your input. I will get back to you after my work on other issues.

**Comment by qwepoizt** [comment]
> So we actually have two independent bugs in this issue?

I agree with kodebach: The issue I reported is that `check/range` only uses `check/type` and not `type`. Sorry, if my first post was unclear.

I think at this point in time it would make sense to change `check/range` to fallback to `type` if `check/type` is not set. 
@markus2330 @kodebach Do you agree?

Consolidating and simplifying the different `*/type` metadata is a separate, time-intensive issue.

**Comment by kodebach** [comment]
Yes, probably for now the best course of action is to add the `type` fallback to `range` and open a separate issue for the consolidation of type metadata.

**Comment by markus2330** [comment]
> I think at this point in time it would make sense to change check/range to fallback to type if check/type is not set.
@markus2330 @kodebach Do you agree?

Yes. Please also update doc/METADATA.ini that behavior like this is required.

**Comment by qwepoizt** [comment]
@kodebach @markus2330 Okay, sounds good too me!
