### ISSUE TITLE
Feature proposal: Output error/warning if a key that isn't in spec-file is set

### ISSUE THREAD

**Issue by qwepoizt** [ElektraInitiative/libelektra#3985]
# Notes
* I'd like to fix this as part of my thesis.
* Is this a sensible improvement or is there a reason for the current behavior?
* I've searched through the existing issues but found no mention of this.
* This could be implemented as an optional feature that is disabled by default.

# Current behavior
1. Create file `test.ini` with content: 
```
[]
mountpoint = test.ecf

[mykeyfromspec]
type = boolean
check/type = boolean
```

2. ``sudo kdb mount -v `pwd`/test.ini spec:/tests/test ni``
3. `sudo kdb spec-mount /tests/`
4. `kdb set /tests/test/mykeyfromspec true`
5. `kdb set /tests/test/somekeynotinspec somevalue`
6. `kdb set /tests/test/subtree/somekeynotinspec somevalue`

# Proposed behavior
* Steps 1 to 4. as above
* Step 5 and 6 output an error/warning, that a key was set, that is not part of the specification file (or that has no spec-related metadata).

# Motivation
* If one purpose of spec files is describing what configuration options a software does (not) support, this would make sense.
* During my work on [Elektrifying redshift](https://github.com/jonls/redshift/issues/814) I often used `kdb set` on some keys that weren't part of the spec and wondered why I didn't receive a warning that they validate a `check/` rule (e.g. when I accidentally spelt the keyname wrong in my `kdb set` call).

**Comment by qwepoizt** [comment]
@markus2330 What do you think about this?

**Comment by qwepoizt** [comment]
Thanks @markus2330 for your input. I will get back to you after my work on other issues.

**Comment by kodebach** [comment]
This conflicts with #3938
