### ISSUE TITLE
Update HelloElektra [JNA binding]

### ISSUE THREAD

**Issue by tucek** [ElektraInitiative/libelektra#3988]
- [x] Convert to gradle sub-project
- [x] update README.md

**Comment by markus2330** [comment]
Thank you for creating this issue!

**Comment by tucek** [comment]
It seems the rules for valid names have been changed, since the sample application has been developed.
Whats wrong with the following key name?
`Invalid name: user:/weird\/name///\\/is/\no/_\\problem (in keyVNew at src/libs/elektra/key.c:233)`

**Comment by markus2330** [comment]
The backslash before no is tangling `\no`?

**Comment by tucek** [comment]
> tangling

Already tried that, but it's no escape character. The Java string is `"user:/weird\\/name///\\\\/is/\\no/_\\\\problem"`

**Comment by markus2330** [comment]
There are two different levels of escaping going on here: first in Java, later in Elektra. The tangling backslash occurs in Elektra.
