### ISSUE TITLE
Provide a simple API to add error and warning information to a key [JNA bindings]

### ISSUE THREAD

**Issue by tucek** [ElektraInitiative/libelektra#3995]
Existing `Key::setError` and `Key::addWarning` methods are too specific to be helpful. Use with sample whitelist plugin.

Also see https://github.com/ElektraInitiative/libelektra/pull/3889#discussion_r688649720

**Comment by markus2330** [comment]
Thank you for creating the issue! What API do you propose?

**Comment by flo91** [comment]
@markus2330 Maybe also an issue suited for the FLOSS course?
