### ISSUE TITLE
Help message does not contain all command line options

### ISSUE THREAD

**Issue by qwepoizt** [ElektraInitiative/libelektra#3999]
Forked from #3998.

@kodebach writes:
> I investigated this a bit and it turns out this is a bug in the opts library. Specifically that generateOptionsList doesn't recognise the temp/day key as an option (because of keyIsDirectlyBelow). I don't think it is a simple as using keyIsBelow, because then it probably shows to many options, when commands are used in the spec. Probably keyWithOpt needs to be generated differently in the various process* options, so that the keyIsDirectlyBelow check works.

**Comment by qwepoizt** [comment]
I tested with more than one key that has a `opt`/`opt/long` value. Some are included, some are not. I have not yet discovered what it depends upon.

**Comment by kodebach** [comment]
What exactly did you try? I would except that without sub-commands, anything directly below the parent key would be detected, but keys that are multiple levels below would not.

**Comment by qwepoizt** [comment]
@kodebach I've implemented a fix for this using your proposed solution.

Note that I did not have to implement anything special for 

> creating the keyWithOpt for a command itself
.

Can you please take a look at #4015 and let me know if you believe it is ready to be merged?

**Comment by qwepoizt** [comment]
@markus2330 I noticed I never mentioned you in this issue, I'm doing it now.
