### ISSUE TITLE
gdb looks for debug symbols in /home/jenkins/...

### ISSUE THREAD

**Issue by qwepoizt** [ElektraInitiative/libelektra#4004]
## Steps to Reproduce the Problem

1. Under Ubuntu 20.04 install the following packages (follow guide from https://www.libelektra.org/installation/installation):
```
elektra-bin
elektra-bin-dbgsym
elektra-dbg
elektra-qt-gui
elektra-qt-gui-dbgsym
elektra-tests
elektra-tests-dbgsym
glib-elektra
glib-elektra-dbgsym
io-ev-elektra
io-ev-elektra-dbgsym
io-glib-elektra
io-glib-elektra-dbgsym
io-uv-elektra
io-uv-elektra-dbgsym
java-elektra
libelektra-dev
libelektra5
libelektra5-augeas
libelektra5-augeas-dbgsym
libelektra5-crypto
libelektra5-crypto-dbgsym
libelektra5-curl
libelektra5-curl-dbgsym
libelektra5-dbgsym
libelektra5-dbus
libelektra5-dbus-dbgsym
libelektra5-experimental
libelektra5-experimental-dbgsym
libelektra5-extra
libelektra5-extra-dbgsym
libelektra5-full
libelektra5-full-dbgsym
libelektra5-gitresolver
libelektra5-gitresolver-dbgsym
libelektra5-java
libelektra5-java-dbgsym
libelektra5-journald
libelektra5-journald-dbgsym
libelektra5-lua
libelektra5-lua-dbgsym
libelektra5-python
libelektra5-python-dbgsym
libelektra5-ruby
libelektra5-ruby-dbgsym
libelektra5-xerces
libelektra5-xerces-dbgsym
libelektra5-xmltool
libelektra5-xmltool-dbgsym
libelektra5-yajl
libelektra5-yajl-dbgsym
libelektra5-yamlcpp
libelektra5-yamlcpp-dbgsym
libelektra5-zeromq
libelektra5-zeromq-dbgsym
lua-elektra
lua-elektra-dbgsym
python3-elektra
python3-elektra-dbgsym
ruby-elektra
```

2. Execute `gdb kdb`
3. Within gdb execute `start`

## Expected Result
Sources for Elektra resp. kdb should be loaded from the paths where they were copied to by installing the  *-dbgsym packages. 

## Actual Result
gdb tries to load sources for Elektra resp. kdb from `/home/jenkins/workspace/libelektra-release/libelektra/src`

![image](https://user-images.githubusercontent.com/61849663/130635903-17a2e734-6c3b-4679-ad68-ee4d4e4bcaa6.png)

## Temporary workaround
1. Quit gdb
2. Download .ZIP archive libelektra5@0.9.7 from Github
3. Extract into `/home/jenkins/workspace/libelektra-release/libelektra/`
4. Execute `gdb kdb`
5. Within gdb execute `start`

Now sources are loaded from `/home/jenkins/workspace/libelektra-release/libelektra/`

![image](https://user-images.githubusercontent.com/61849663/130636433-169e5e46-2ee3-49c1-a61e-495d15995053.png)

![image](https://user-images.githubusercontent.com/61849663/130636452-7fccf3fb-f70c-4f4d-985c-fe0188609ce8.png)

## System Information

- Elektra Version: 0.9.7-5
- Operating System: Ubuntu 20.04
- Versions of other relevant software: 
    - gdb: GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2

**Comment by qwepoizt** [comment]
@robaerd Please feel free to reassign if you are not the right assignee for this issue.

**Comment by robaerd** [comment]
Source packages are currently not part of our repos. The reason for this is that the CPack DEB generator does not support the creation of source packages (.dsc).

**Comment by markus2330** [comment]
Ok, then I suggest we use what @qwepoizt wrote in the top post (manual download of zip for the [sources in the source path](https://sourceware.org/gdb/current/onlinedocs/gdb/Source-Path.html)) to start a new debugging tutorial.

**Comment by qwepoizt** [comment]
Thanks @markus2330 for your input. I will get back to you after my work on other issues.

**Comment by markus2330** [comment]
As discussed, this is only a documentation issue: How to download the source from the build server so that it can be found during debugging.

**Comment by qwepoizt** [comment]
I think there are two ways two debug with sources:

1. Clone Git repo and make install -> Source code will match binaries
2. Download source of installed version from build server/git -> Source code will match binaries.

I could write up a quick "Debugging" tutorial! 

Would it fit in the main menu of www.libelektra.org under "Documentation" or "Development"?

![image](https://user-images.githubusercontent.com/61849663/136171777-c88ab737-00e4-4f61-9155-1d99718d4bae.png)
![image](https://user-images.githubusercontent.com/61849663/136171794-e1699333-8b2d-4d88-8edb-11090b4eab99.png)

Or would you rather put it inside the "dev getting started" menu?
![image](https://user-images.githubusercontent.com/61849663/136171962-424bfb72-25c7-47f1-a5e4-38942c9217be.png)

Or somewhere else entirely?

**Comment by markus2330** [comment]
>    Clone Git repo and make install -> Source code will match binaries
>   Download source of installed version from build server/git -> Source code will match binaries.

Exactly.

> I could write up a quick "Debugging" tutorial!

That would be amazing :sparkling_heart: 

> Would it fit in the main menu of www.libelektra.org under "Documentation" or "Development"?

If you add a markdownfile to doc/tutorials and add an entry in doc/tutorials/README.md it will be automatically added to the website.

**Comment by qwepoizt** [comment]
@markus2330 I have done this in #4111. I think it would fit great between "Compiling" and "Installation" and have thusly put references into in `doc/` resp. `doc/README.md`.

![image](https://user-images.githubusercontent.com/61849663/137974822-2f939081-41c2-4bb0-9265-67c22a0a1d1b.png)

**Comment by qwepoizt** [comment]
@markus2330 I have decided not to include the second option `Download source of installed version from build server/git -> Source code will match binaries.` in the tutorial because that also requires putting the sources into `/home/jenkins` and debugging won't work great for installed versions which have no debug symbols and are compiler-optimized. This option seems too much of a hack.
