### ISSUE TITLE
testruby_tools_plugindatabase.rb: sporadic segmentation faults

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#4011]
The `testruby_tools_plugindatabase.rb` tests are experiencing sporadic segmentation faults, it seems from Ruby 2.7 onwards.

Since the errors are occuring more often now, we'll need to somehow take care of it.

```
 90/271 Test  #56: testruby_tools_plugindatabase.rb ..............Child aborted***Exception:   0.76 sec
Loaded suite /home/jenkins/workspace/libelektra_master/src/bindings/swig/ruby/tests/testruby_tools_plugindatabase
Started
KdbtoolsPluginDatabaseTestCases: 
  test_get_int_pluginspec_map:				/home/jenkins/workspace/libelektra_master/src/bindings/swig/ruby/tests/testruby_tools_plugindatabase.rb:75: [BUG] Segmentation fault at 0x00005566c9614000
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]
```
See build logs on [Jenkins](https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/master/536/pipeline/).
Full log attached: [log_ruby.txt](https://github.com/ElektraInitiative/libelektra/files/7071197/log_ruby.txt)

**Comment by markus2330** [comment]
Thank you for reporting this problem! Does it happen on every distribution with >= Ruby 2.7? We probably need a backtrace to somehow track this down.

**Comment by mpranj** [comment]
> Does it happen on every distribution with >= Ruby 2.7?

I'm not completely sure about anything. I think I first saw it on Fedora where Ruby 2.7 was available earlier. Now it is also happening on Debian Bullseye with Ruby 2.7.

The problem occurs only sporadically so I fear it will be tricky to track down.

**Comment by qwepoizt** [comment]
It just happened to my PR #4015.

Please see

* https://build.libelektra.org/blue/rest/organizations/jenkins/pipelines/libelektra/branches/PR-4015/runs/4/nodes/792/steps/2083/log/?start=0
* https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-4015/4/pipeline/

**Comment by markus2330** [comment]
@qwepoizt thank you for pointing to the backtrace, this is very helpful.

@kodebach It looks like that the crash is related with the dump plugin serializing during invoking the function using pluginprocess. Didn't you make some changes there? You might spot something.

**Comment by mpranj** [comment]
I disabled this test on master now as it is failing too often. Please revert 87d1a4f1ec19a0cf86b877e6d2eb9e1d124d96ee when fixing the issue.

**Comment by markus2330** [comment]
@mpranj thank you for looking after stable build jobs!

Can you please also add a line in doc/todo/TESTING for the disabled test.

**Comment by lawli3t** [comment]
I could reproduce this on my system after countless runs of the test suite, not sure where it originates from though - I'll have to investigate further

**Comment by markus2330** [comment]
Better to leave the issue to someone who has a setup where the issue occurs.

**Comment by flo91** [comment]
@markus2330 Maybe an issue for the FLOSS course?

**Comment by markus2330** [comment]
It is only for low-level ruby experts, I don't think this is suitable for FLOSS. A further triage by a non-expert probably also won't reveal much.
