### ISSUE TITLE
Older mac lineendings do not work (did not find key)

### ISSUE THREAD

**Issue by omnidan** [ElektraInitiative/libelektra#402]
Steps to reproduce:

 * Create and mount an `ini` file.
 * Change line endings to older mac lineendings (in vim: `:w ++ff=mac`)
 * Try `kdb get` on a key, it doesn't find it.

**Comment by markus2330** [comment]
can you create a pull request with problematic INI files? (to src/plugins/ini/ini)

**Comment by markus2330** [comment]
@omnidan ping, can you recheck with latest ini plugin?

**Comment by omnidan** [comment]
Seems to work fine now (on `master`)!

Without mac linendings:

```
$ sudo kdb mount ~/test.ini system/test ini
$ kdb get system/test/test
hello world
```

With mac lineendings:

```
$ kdb get system/test/test
hello world
```
