### ISSUE TITLE
kdb set uses default: on cascading writes

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4028]
## Steps to Reproduce the Problem

```sh
kdb meta-set "spec:/sw/redshift/#0/current/mode" default continual
kdb set "/sw/redshift/#0/current/mode" print
kdb get "/sw/redshift/#0/current/mode"
```

## Expected Result

That the second command fails because the default: namespace is not writable.

## Actual Result

```
kdb set "/sw/redshift/#0/current/mode" print
#> Set string to "print"
#> Using name default:/sw/redshift/#0/current/mode
kdb get "/sw/redshift/#0/current/mode"
#> continual
```

## System Information

- Elektra Version: master

## Further Information

- A similar problem will probably exist for other temporary namespaces like proc:.
- meta-set, rm and other write commands are also affected.

@dev2718 do you have time to take a look? What behavior would you suggest?

**Comment by qwepoizt** [comment]
@markus2330 I also noticed this today while working on #4029 and wanted to report this. But you were faster :)!

**Comment by dev2718** [comment]
I am a bit confused as to how to reproduce this, as
``kdb set spec:/sw/redshift/#0/current/mode default continual``
raises a syntax error (too may parameters).

**Comment by markus2330** [comment]
Which shell do you use? Some shells interpret `#` also in the middle of words. I quoted the top-post so that the problem should not occur.

**Comment by dev2718** [comment]
I use fish, but this is not the problem.

``kdb set "spec:/sw/redshift/#0/current/mode" default continual``

gives me

`Sorry, I could not process the arguments: 2 arguments needed`

caused by

https://github.com/ElektraInitiative/libelektra/blob/90fb5bef6bf2c899d8b90af90d08b99140ae6666/src/tools/kdb/set.cpp#L27-L30

**Comment by markus2330** [comment]
Sorry, it should read meta-set instead of set, I updated the top description!

**Comment by markus2330** [comment]
As discussed, we will disable all cascading writes.

@dev2718 Can you do this for this release?

**Comment by markus2330** [comment]
@atmaxinger here is the question if you rewrite the tooling so that this bug get fixed.
