### ISSUE TITLE
redshift: reloading

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4030]
## Steps to Reproduce the Problem

```sh
./src/redshift-gtk/redshift-gtk &
kdb set user:/sw/redshift/#0/current/provider/location/manual/lat -- "-80"
```

## Expected Result

That the red value adjustment changes.

## Actual Result

No change.

## System Information

- Elektra Version: master

**Comment by qwepoizt** [comment]
Thanks for the report!

The cause is that notifications are currently not implemented in elektrified redshift.

**Comment by markus2330** [comment]
As discussed the use case for reloading in redshift is not really given and to make notification work together with HL-API is not trivial.
