### ISSUE TITLE
problems in mount.sh

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4031]
- [ ] TODO in line 4
- [ ] line 14: try to unmount if mounted (not needed for spec-mount, as it already overwrites previous mountpoints)
- [ ] make sure notification is working? #4030 
- [ ] add safety checks for presence of kdb, sudo and so on
- [ ]  contains some brittle code (e.g. expect certain output of `kdb mount`)
- [ ] use argument instead of APP_PATH?

**Comment by markus2330** [comment]
@qwepoizt Is this something you already looked into? Are there further improvements to be made?

**Comment by qwepoizt** [comment]
No, actually I have not looked into this issue. I'm not aware of other improvements.

Do you want me to improve the script?

**Comment by markus2330** [comment]
It is better if we get the issues, you are already working on, fully done. This issue can be easily reassigned as it is quite separate.

The main problem with the UX of the scripts is if they are executed when the mountpoints are already mounted:

```
The command kdb get terminated unsuccessfully with the info:
Invalid Keyname: keyname needs to start with /, meta:/, default:/, spec:/, proc:/, dir:/, user:/ or system:/ or maybe you tried to change a key that is already in a KeySet. Name was: '/elektra/mountpoints/spec:\/sw\/jonls\/redshift\/#0\/current/getplugins/#5#specload#specload#/config/file' 
Please report the issue at https://issues.libelektra.org/
The command kdb get terminated unsuccessfully with the info:
Invalid Keyname: keyname needs to start with /, meta:/, default:/, spec:/, proc:/, dir:/, user:/ or system:/ or maybe you tried to change a key that is already in a KeySet. Name was: '/elektra/mountpoints/spec:\/sw\/jonls\/redshift\/#0\/current/getplugins/#5#specload#specload#/config/app' 
Please report the issue at https://issues.libelektra.org/
ERROR: another mountpoint already exists on spec:/sw/jonls/redshift/#0/current. Please umount first.
```

So a lot of very misleading errors until the real problem is printed. It would be much better if the script simply umounts itself.

**Comment by qwepoizt** [comment]
> It is better if we get the issues, you are already working on, fully done. This issue can be easily reassigned as it is quite separate.

Okay, that sounds good to me!

>  It would be much better if the script simply umounts itself.

Good idea, I agree!

**Comment by kodebach** [comment]
Eventually the generated `mount.sh` should probably be replaced by some C code that uses the new mount tools.

**Comment by markus2330** [comment]
I agree that most of it should be directly in `kdb mount` but at least the sudo part is better to be a shell script.

**Comment by kodebach** [comment]
I didn't mean make it part of `kdb mount`. I meant make it part of the generated code for the application, i.e. generate a `mountConfiguration` function. So that the application can provide e.g. a `./app install` command or call the function on first start etc. Of course actually creating the mountpoints via that function will require root access in a standard installation for now, i.e. `sudo ./app install`. But with #1074 the application could create `user:/` mountpoints.

**Comment by markus2330** [comment]
Ok, let us wait for the new mount API/tool before fixing anything.
