### ISSUE TITLE
Remove manual release API [JNA bindings]

### ISSUE THREAD

**Issue by tucek** [ElektraInitiative/libelektra#4038]
As soon as the garbage collector based clean-up of native resources is working (see #3875), the API for manual releasing native resources `Key::remove` and `KeySet::remove` should be removed (=made private).

Additionally all java-doc declaring related `IllegalArgumentException`s have to be updated.

**Comment by markus2330** [comment]
Can this already be done?

**Comment by tucek** [comment]
I think so. Even if don't know yet whether the garbage collector based clean-up now works. I will remove the manuela release methods from the Java API

**Comment by tucek** [comment]
Merged implicitly via #4439 #4440
