### ISSUE TITLE
Optimize ksSearch by searching hash map first

### ISSUE THREAD

**Issue by tucek** [ElektraInitiative/libelektra#4039]
To optimize `ksSearch`, call `opmphmLookup` (if `opmphm` is enabled) first, with a fallback on `ksSearchInternal`.

**Comment by sedadas** [comment]
[FLOSS H1]

I looked into the issue and if I am not mistaken a possible implementation would be the following:

1. include `kdbhelper.h` in `src/libs/elektra/keyset.c`
2. change signature of `ksSearch` in `src/libs/elektra/keyset.c#737` to include `elektraLookupOptions options`
3. add an if that checks if we want to search with `KDB_O_OPMPHM`
4. build the OPMPHM for the keyset just in case
5. handle accordingly

As code, it should look something like this:
```c
ssize_t ksSearch (const KeySet * ks, const Key * key, elektraLookupOptions options)
{
	if (options & KDB_O_OPMPHM) {
                // build the opmphm for the keyset
		elektraLookupBuildOpmphm(ks);
		return opmphmLookup(ks->opmphm, ks -> size, key -> key);
	}
	else
		return ksSearchInternal (ks, key);
}
```

To document the change the additional parameter needs to be specified in the comment above the function.
