### ISSUE TITLE
[CM T0] KeySet may implement NavigableSet [JNA bindings]

### ISSUE THREAD

**Issue by tucek** [ElektraInitiative/libelektra#4040]
After #3870 introduced implementation of `SortedSet` by `KeySet`, also implementing `NavigableSet` should be relatively easy.

See https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/NavigableSet.html

**Comment by markus2330** [comment]
Thank you for proposing this improvement!

**Comment by bhampl** [comment]
We (@bhampl and @Eiskasten ) would like to work on this issue. The implementation should be straight forward (we "just" need to implement the missing methods in the [KeySet](https://github.com/tucek/libelektra/blob/9a14f67a9f3edb393daf41346f3d4f3b781b6b60/src/bindings/jna/libelektra/src/main/java/org/libelektra/KeySet.java#L27) class), once we understood the code and read the documentation (mainly the javadoc). Are there any specific things we need to watch out for during implementation?

**Comment by kodebach** [comment]
I think you are right, the implementation should mostly be straightforward.

The main thing to watch out for is probably that the implementation should still be efficient. That means utilising the underlying structure implemented in C as much as possible. If you find that a new C API would be useful, don't be afraid to bring this up. For example, the implementation of `SortedSet` was one of the reasons for (quickly) adding `ksSearch` to the API (see also #4026).

**Comment by Eiskasten** [comment]
As @bhampl  already mentioned, I also want to work on this issue. As I understand, we only have to touch the KeySet class, am I right?

**Comment by kodebach** [comment]
Yes, the changes should (mostly) be contained to the `KeySet` class. It might also be necessary to modify the private inner class `KeySetView` (or add another similar class). AFAICT the C API (with the addition of `ksSearch`) should be sufficient to fully implement `NavigableSet`. If this is not the case, please report the issue and I will implement what you need on the C side.

**Comment by tucek** [comment]
merged via #4364
