### ISSUE TITLE
redshift: CLI arguments not working

### ISSUE THREAD

**Issue by qwepoizt** [ElektraInitiative/libelektra#4041]
reported by @markus2330 at https://github.com/jonls/redshift/pull/837#discussion_r706243781

# Expected behavior
`src/redshift -V` does not print the version.

# Actual behavior
`src/redshift -V` should print version and exit

**Comment by qwepoizt** [comment]
@markus2330 I'm reposting my questions here, looking forward to your response!

------------------------------------------------------------------------------------------------

Unfortunately, I'm having trouble reproducing that when specification is properly mounted. Could you please provide more information?

1. Does `src/redshift -v` (lower-case v -> verbose) and other CLI options like `--fade` work?

2. What is the output of ... 

* `src/redshift --elektra-spec` 
* `src/redshift --help` 
* `kdb ls spec:/sw/redshift/#0/current/` 
* `kdb meta-show spec:/sw/redshift/#0/current/version` 
* `kdb meta-show /sw/redshift/#0/current/version` 
* `kdb get /sw/redshift/#0/current/version` 
?

3. Maybe your build contains a broken specification (see https://github.com/jonls/redshift/pull/837#discussion_r706612067).
Could you please pull my latest changes with the fix and then unmount both mointpoints, `make distclean`, bootstrap, configure, make, execute redshift-conf.mount.sh (and optionally make install) and finally `src/redshift -v`.

**Comment by markus2330** [comment]
To get an "installed" Elektra, the easiest option is probably with our docker builds (to list them run `docker run --rm anoxis/registry-cli -r https://hub-public.libelektra.org`), see e.g. https://www.libelektra.org/tutorials/run-all-tests-with-docker

**Comment by qwepoizt** [comment]
Thanks for the hint, I've done some experimenting with docker for testing previously, I'll take a look!

**Comment by qwepoizt** [comment]
@markus2330 I believe this was caused by missing dependencies on your system! To make such issues easier to debug, I have:

* improved the usability of redshift to provide more helpful info messages during execution and more details about problems.
* extended `CONTRIBUTING.md` to make clearer, that without installing the dependencies, redshift will only work in a very limited manner.

I'll get back to you on this issue (and ask you to retest) once #3998 is closed!

**Comment by markus2330** [comment]
> To make such issues easier to debug

:sparkling_heart: 

> redshift will only work in a very limited manner.

Maybe we should even fail. I don't think anyone wants to have software where CLI arguments do not work.

**Comment by markus2330** [comment]
I just tried with several location providers, it did not make the CLI arguments work:

```
> ./src/redshift --help
You have not configured a location provider. Redshift will try to automatically choose a suitable one.
Trying location provider `geoclue2'...
`geoclue2' works and will be used.
You have not configured an adjustment method. Redshift will try to automatically choose a suitable one.
Trying adjustment method `randr'...
`randr' works and will be used.
Waiting for initial location to become available...
Location is now available! Latitude: 47.27, longitude: 11.40
```

**Comment by qwepoizt** [comment]
Thanks for trying! 

Let me clarify: We are discussing 2 issues here:

## CLI arguments not working
* This is still unsolved in this PR
* It will be solved or easier to debug once #3998 is closed.
* If you want to, you could try installing libelektra @ a4be8d468549ef52b5678e13fedfa8112b7a1e79 (latest commit in #4047) and check if the issue goes away.
* Otherwise, I'll reach out to you once it's merged into master :)

## redshift's output if no adjustment method works
* In our last call, the output was  ```"No more methods to try``` on your system. 
* After my usability improvements, it's now:
`Redshift was unable to adjust your screen temperature. Reason: None of the temperature adjustment methods of this build work on your system. Execute "redshift --method list" to see which methods are supported in this build. Exiting now.`
* You installed the `randr` dependency, redshift finds a working adjustment method and is functional.
* (I've also improved the behavior for location providers.)

**Comment by qwepoizt** [comment]
> Maybe we should even fail. 

Sorry, I think I was too unspecific. Actually, redshift was designed to work without some of those dependencies. The problem was just, that it's info/error messages were too unclear. 

Currently: 

* If Elektra dependency is missing, redshift won't compile.
* If no adjustment method dependency was installed, redshift will execute in dummy mode and print to stderr, that dummy mode has no effect on screen temperature. That's how it also was in redshift before my changes.

Therefore, I'd argue that the UX is good now - even with non-essential dependencies missing.

**Comment by markus2330** [comment]
As the title suggested, I was talking about the issue that the CLI arguments are not working. So this issue is a specific occurrence of #3998 (when using redshift).

> Otherwise, I'll reach out to you once it's merged into master :)

Yes, perfect! Let us look into the CLI arguments afterwards.

**Comment by qwepoizt** [comment]
@markus2330 tested on his system again today with Elektra 0.9.7 (which doesn't yet include #4047):

* `kdb gmount` returned:
`spec`
* after `kdb gumount spec`, **the CLI arguments worked**!
  e.g.: `./redshift -V` prints version, `./redshift -v` enables verbose mode, `./redshift --help` prints generated help text.

## Reproducing the bug
* I've tried to reproduce this on my system, but `kdb global-mount spec` yields:

```
$ sudo kdb global-mount -d -v spec
The command kdb global-mount terminated unsuccessfully with the info:
It is not allowed to insert the same plugin (spec#spec) again!
Try to add other plugins or other refnames (part after #) instead.
Please report the issue at https://issues.libelektra.org/
```

* After kdb-unmounting all my mountpoints and then executing `$ sudo rm -r /etc/kdb/elektra.ecf /etc/kdb/default.ecf /tmp/elektra*`, I still can't `gmount spec`.

## Conclusion
* `gumount`ing the spec plugin solved the problem on @markus2330 system.

* I assume there might be some conflict with the globally mounted spec and the contract in elektra.c:

https://github.com/ElektraInitiative/libelektra/blob/06940c84560172f4fc0e297b9819b78ee303ba3b/src/libs/highlevel/elektra.c#L78-L84

* As global mounting is not required anymore ever since contracts were implemented, we expect that hardly anyone will run into this problem.
* But, out of interest: 
* @markus2330 Do you have an idea how I can globally mount the spec plug-in to reproduce the bug?
* @kodebach Do you maybe have any related information about this topic?

**Comment by kodebach** [comment]
> Do you have an idea how I can globally mount the spec plug-in to reproduce the bug?

The `spec` plugin should already be globally mounted by default. You shouldn't need `kdb global-mount spec`.

The problem that is happening here is that markus2330 at some point called `kdb global-mount` for some other reason. This made the config explicit and stored it in his KDB. For that point on the default global mount config wasn't used anymore on his system and he need to update it manually.

This is a general problem with the way global plugins work. AFAIK calling `kdb global-mount` also breaks the cache, but in this case the problem seems to be that after calling `kdb global-mount` once the key `system:/elektra/globalplugins/postcommit/user/placements/get` doesn't include `procgetstorage`.

For @markus2330 the fix should just be:

```
kdb set system:/elektra/globalplugins/postcommit/user/placements/get pregetstorage procgetstorage postgetstorage
```

However, this is a bug and should be fixed properly. If we haven't fixed it before then, it should be fixed via #3693. But I think the issue is actually just that we forgot to add `procgetstorage` here:

https://github.com/ElektraInitiative/libelektra/blob/06940c84560172f4fc0e297b9819b78ee303ba3b/src/libs/tools/src/backend.cpp#L570-L570

**Comment by markus2330** [comment]
> after kdb gumount spec, the CLI arguments worked!

I actually fixed it with `kdb rm -rf system:/elektra/globalplugins`.

> @markus2330 Do you have an idea how I can globally mount the spec plug-in to reproduce the bug?

If simply mounting spec does not trigger the issue it is probably not important trying to reproduce it.

> However, this is a bug and should be fixed properly.

Exactly! We should make sure is that contracts actually ensure that a plugin gets mounted, irrelevant of the content in `system:/elektra/globalplugins`.

**Comment by kodebach** [comment]
> We should make sure is that contracts actually ensure that a plugin gets mounted, irrelevant of the content in `system:/elektra/globalplugins`.

This not really possible with the current setup without a lot of effort. That's why contracts currently rely on the `list` plugin. With #3693 it will hopefully become easier.

**Comment by qwepoizt** [comment]
Thank you both for your input! I propose to move the discussion to a new issue!

**Comment by qwepoizt** [comment]
Closing this as the issue was fixed, if required, please open a new issue for further discussion of "We should make sure is that contracts actually ensure that a plugin gets mounted, irrelevant of the content in system:/elektra/globalplugins".
