### ISSUE TITLE
gopts: Wrong type detected too late

### ISSUE THREAD

**Issue by qwepoizt** [ElektraInitiative/libelektra#4043]
Forked from #4029.

This is "Class 2: wrong type".

## Steps to Reproduce the Problem
see #4029

## Expected Result
see #4029

## Actual Result
see #4029

## System Information
see #4029

**Comment by qwepoizt** [comment]
@kodebach wrote in #4029:

> I thought that at least type also does its validation during kdbGet.

It does. But: The opts library seems to not copy the meta-keys from the keys within spec:/ to the keys within proc: .

When `elektraTypeGet()` is called, the keys in the KeySet have no meta data.

E.g. for `./myapp --mb notabool` using the spec given in #4029:

![image](https://user-images.githubusercontent.com/61849663/133226211-c70b8317-a352-43b9-b083-b113070cf669.png)

@kodebach Do you remember if the meta-keys are not copied from spec:/ to proc:/ on purpose? Would the fix be to 

1. copy the metadata 
2. or to lookup the metadata from `spec:/` within `elektraTypeGet()` ?

**Comment by qwepoizt** [comment]
(mentioning @markus2330 as discussed.)

**Comment by qwepoizt** [comment]
Addendum: 
Because they have no metadata `getTypeName(cur)` returns NULL and their type is not validated within `elektraTypeGet()` - these keys are simply skipped:

https://github.com/ElektraInitiative/libelektra/blob/6701d9ea627a7fb6df7276c4d6fe69fa9a6b8ae4/src/plugins/type/type.c#L305-L312

The wrong type is then noticed later, when the exact key is retrieved using the `elektraGetMyboolean()` function generated by `kdb gen`, as explained [here](https://github.com/ElektraInitiative/libelektra/issues/4029#issuecomment-917378424)

**Comment by kodebach** [comment]
> But: The opts library seems to not copy the meta-keys from the keys within spec:/ to the keys within proc: .

The `spec` plugin should do that. First all plugins up to and including the `getstorage` position should run. Then `gopts` should run (in the `procgetstorage` global position), then `spec` should run (`postgetstorage` global position) and finally all the plugins in `postgetstorage` position should run.

Can you verify whether `gopts`, `spec` and `type` are executed in this order? If they are, this is probably a bug in the `spec` plugin.

**Comment by qwepoizt** [comment]
No, the order is gopts, type, spec!

`gopts` is run in `procgetstorage` and `spec` is run in `postgetstorage`. I'm not sure in which position `type` is run, but it's call stack shows that it is not executed via the `list` plugin as `gopts` and `spec`.

## Call stacks
### gopts
1st call
![image](https://user-images.githubusercontent.com/61849663/133232732-064e79db-46a9-4fc4-be18-a7f6504be7b6.png)
2nd call
![image](https://user-images.githubusercontent.com/61849663/133232818-1f8abc45-ca4a-442e-8397-c4ab05374f8b.png)

### type
1st call
![image](https://user-images.githubusercontent.com/61849663/133232891-d41fd938-5622-445c-8f47-34a68770b64e.png)
2nd call
![image](https://user-images.githubusercontent.com/61849663/133232916-4d35befe-db1f-4ad5-974f-82d3df6a87f6.png)
3rd call
![image](https://user-images.githubusercontent.com/61849663/133232938-05c837c4-85be-4e2d-965b-9ab6f20b872e.png)

### spec
1st call
![image](https://user-images.githubusercontent.com/61849663/133232968-77224a91-27a3-4ba6-ad77-137486c6072f.png)

**Comment by qwepoizt** [comment]
Yes, after this change, the order is now `gopts`, `spec`, `type`!

@kodebach Can you please make sure that this is indeed a good fix for the problem and create a PR for it?  
Are you the right person for that task?  
Unfortunately, I don't know how kdbGet() works and what side-effects such a change could have, so I am quite at a loss here :).

**Comment by qwepoizt** [comment]
@markus2330 I've discovered another problem in `kdb.c` that might be related #4044.

**Comment by kodebach** [comment]
Yes, I will look into fixing this and #4044. Since #3693 will change a lot of this code anyway, I'd say as long as the change doesn't cause test failures it is good enough for now.
