### ISSUE TITLE
error/success return values ignored in elektraGetDoUpdateWithGlobalHooks()

### ISSUE THREAD

**Issue by qwepoizt** [ElektraInitiative/libelektra#4044]
## Problem
In several places of `kdb.c` return values from plugins' `kdbGet()` are ignored.

This leads to errors in these plugins from being ignored and not reported back to the initial caller of `kdbGet()`.

## Examples of ignored return values (list might be incomplete)
https://github.com/ElektraInitiative/libelektra/blob/6701d9ea627a7fb6df7276c4d6fe69fa9a6b8ae4/src/libs/elektra/kdb.c#L795-L805

https://github.com/ElektraInitiative/libelektra/blob/6701d9ea627a7fb6df7276c4d6fe69fa9a6b8ae4/src/libs/elektra/kdb.c#L837

https://github.com/ElektraInitiative/libelektra/blob/6701d9ea627a7fb6df7276c4d6fe69fa9a6b8ae4/src/libs/elektra/kdb.c#L845

https://github.com/ElektraInitiative/libelektra/blob/6701d9ea627a7fb6df7276c4d6fe69fa9a6b8ae4/src/libs/elektra/kdb.c#L853

https://github.com/ElektraInitiative/libelektra/blob/6701d9ea627a7fb6df7276c4d6fe69fa9a6b8ae4/src/libs/elektra/kdb.c#L894

## Concrete example
One concrete example for the impact of the first example 
https://github.com/ElektraInitiative/libelektra/blob/6701d9ea627a7fb6df7276c4d6fe69fa9a6b8ae4/src/libs/elektra/kdb.c#L795-L805
is that errors detected within `elektraGoptsGet()` are "swallowed".

E.g. `opts.c` detects a missing argument for a long option and returns false.
https://github.com/ElektraInitiative/libelektra/blob/6701d9ea627a7fb6df7276c4d6fe69fa9a6b8ae4/src/libs/opts/opts.c#L1789-L1792

This leads to the call to `elektraGlobalGet (handle, ks, parentKey, PROCGETSTORAGE, MAXONCE);` at:
https://github.com/ElektraInitiative/libelektra/blob/6701d9ea627a7fb6df7276c4d6fe69fa9a6b8ae4/src/libs/elektra/kdb.c#L803
to fail.

However, the return value is ignored and thusly the error is ignored.

**Comment by qwepoizt** [comment]
@markus2330 I've discovered this and am not sure if it is a bug or intended. What do you think?

**Comment by kodebach** [comment]
Yes, this is a bug. All errors should be reported, at the very least as a warning (e.g. if there was already another error).
