### ISSUE TITLE
installing fuse writes to source directory

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#4048]
Running `make install`, when the `fuse` tool is built, creates files inside the source directory. At the very least these files should be part of `.gitignore`, but ideally the shouldn't be there at all. If we really need to write some temporary files, the should be in the build directory. However, since `make install` may be run as root to allow actually installing into the system, it probably shouldn't write to the build folder either. It is quite annoying, when `sudo make install` creates files owned by root inside the build directory.

**Comment by markus2330** [comment]
Thank you for reporting this bug! We should not release like this or at least write it in the release notes about fuse.

**Comment by kodebach** [comment]
If we release like this, the files should also be added to `.gitignore` until there is a proper fix. Then you at least don't have to be careful to not commit this stuff.
