### ISSUE TITLE
Replace `type=int` with appropriate alternative

### ISSUE THREAD

**Issue by qwepoizt** [ElektraInitiative/libelektra#4060]
There are some places, where the deprecated `type=int` is still used.

@markus2330 wrote in #4058 that

> this is probably some relic from before we started to use the CORBA type system.

and

> these places need to be fixed!

## List of usages (maybe not exhaustive)

https://github.com/ElektraInitiative/libelektra/blob/90fb5bef6bf2c899d8b90af90d08b99140ae6666/doc/METADATA.ini#L356-L357

https://github.com/ElektraInitiative/libelektra/blob/90fb5bef6bf2c899d8b90af90d08b99140ae6666/doc/METADATA.ini#L77-L80

https://github.com/ElektraInitiative/libelektra/blob/90fb5bef6bf2c899d8b90af90d08b99140ae6666/doc/METADATA.ini#L1191-L1195

**Comment by markus2330** [comment]
Thank you for creating the issue!

**Comment by markus2330** [comment]
Triage needed: are there further places where int is used?

**Comment by markus2330** [comment]
There are a few other spots with wrong types:

```
doc/CONTRACT.ini:type = vector<int enum>
examples/spec/cassandra.ini:;type = unsigned_int
examples/spec/cassandra.ini:check/type = unsigned_int
examples/spec/cassandra.ini:;type = unsigned_int
examples/spec/cassandra.ini:check/type = unsigned_int
```
