### ISSUE TITLE
Implement warnings in HL API's ElektraError

### ISSUE THREAD

**Issue by qwepoizt** [ElektraInitiative/libelektra#4066]
@markus2330: The HL API's error handling file [elektra_error.c](https://github.com/ElektraInitiative/libelektra/blob/7650d17b9e866a03156943a0633c882f67144bf9/src/libs/highlevel/elektra_error.c) did not support warnings. There was some code for it, but it did not work.

I'll implement support for warnings, because this is required to fix #4049 #4053 #4059

**Comment by markus2330** [comment]
Thank you very much!

**Comment by qwepoizt** [comment]
Fixed via #4063
