### ISSUE TITLE
proposal: Merge errors.c and elektra_error.c

### ISSUE THREAD

**Issue by qwepoizt** [ElektraInitiative/libelektra#4073]
Currently, there are 2 module dealing with errors in Elektra:

1. src/libs/elektra/errors.c: Used in the whole codebase. In-code documentation says: "Used for writing the error/warning information into a key to be used for emitting messages to the user"
2. src/libs/highlevel/elektra_error.c: Used in the HL API. Can be used to create errors from scratch or from errors that were written into a key using errors.c

A big disadvantage of two files is: if the interface/behavior/... of one file is changed it is easy to miss updating the other.

Would it make sense to merge these into 1 file?

**Comment by markus2330** [comment]
These files have different purposes: the highlevel error API is for easier access to errors by end-users (i.e. not internally or plugins).

> A big disadvantage of two files is: if the interface/behavior/... of one file is changed it is easy to miss updating the other.

This shouldn't be a problem in the future as we now fixed the error categories. So no update should be needed anymore. Did you find an inconsistency we have at the moment?

**Comment by markus2330** [comment]
Thank you! Then let us close the issue.
