### ISSUE TITLE
Improve detection of problems in specification

### ISSUE THREAD

**Issue by qwepoizt** [ElektraInitiative/libelektra#4075]
Any problems in specification files should be detected as soon as possible:

* on `kdb mount` or `kdb spec-mount`
* during `kdb meta-set`

Right now they are either detected too late or not at all!

## Examples for problems

* ~conflicting type and check/type~ -> fixed for `kdb spec-mount` via #4058

```[myfloat]
type = float
# Note that here the user error is not specifying `check/type = float`. It will default to `check/type = long long` which doesn't     match the syntax of `check/range = -1.0-1.0`and therefore results in an error message once kdb set is called: `Validation Syntactic: Invalid syntax: -1.0-1.0`
check/range = -1.0-1.0
```

* ~specifying an illegal type~ -> fixed for `kdb spec-mount` via #4058

      [myfloat]
      type = sometypethatdoesntexist

* Conflicting type and default -> not detected
```
[myfloat]
type = float
default = astring
```
* An elaborate analysis might yield more examples.

# Motivation
* It makes sense to report errors in spec files as soon as possible and not only when the specified rules are applied.
* During my work on [Elektrifying redshift](https://github.com/jonls/redshift/issues/814) I often found myself wondering why e.g. a check isn't preventing me from `kdb set`ing illegal values, until I finally found I had a typo or forgot something (see examples above)

**Comment by markus2330** [comment]
Thank you for reporting the problem! Yes, I agree that more checks would improve usability. As it is unfortunately difficult to do it in a generic and correct way (for all checkers), I tag it as "low priority".
