### ISSUE TITLE
[FLOSS H0] web-ui and qt-gui feature parity

### ISSUE THREAD

**Issue by marvin-the-parrot** [ElektraInitiative/libelektra#4087]
- Does the web-ui currently have feature parity with the qt-gui?
- Is this something this iniatative is looking to achieve?
- Why was the decision taken to maintain two different types of gui?
- Would working on any two of the gui be an option for the FLOSS course?

**Comment by markus2330** [comment]
>  Does the web-ui currently have feature parity with the qt-gui?

No, the web-ui and the qt-gui has a different set of features. The web-ui has better usability (e.g. only allows to type in values which are allowed) but is also lacking some features qt-gui has, e.g. mounting and showing information about plugins.

> Is this something this iniatative is looking to achieve?

Yes, it would be great if any of Elektra's tools has the full feature set although in general we prefer that the tools get more stable and easier to use than to add all features.

> Why was the decision taken to maintain two different types of gui?

Qt-gui was first and the web-ui is better for multi-node setups.

 > Would working on any two of the gui be an option for the FLOSS course?

Absolutely.
