### ISSUE TITLE
[FLOSS H0] Target-Demographic Admin or Single User

### ISSUE THREAD

**Issue by JakobWonisch** [ElektraInitiative/libelektra#4096]
What is the intended usage scenario of Elektra? Does a program supporting it have any impact on a casual, day to day user of the system or does it only impact the person in charge of managing the machine?

**Comment by markus2330** [comment]
Thank you for asking the question and participating in the FLOSS course!

> What is the intended usage scenario of Elektra?

The main use cases are:

1. for developers to have a library where they can easily get+set configs
2. for system administrators to have better+easier configuration management: https://www.libelektra.org/docgettingstarted/vision
3. for users to have better tools to edit configs, e.g. via Web-UI as shown at the bottom of https://www.libelektra.org/home

See also Users in https://www.libelektra.org/docgettingstarted/goals

> Does a program supporting it have any impact on a casual, day to day user of the system or does it only impact the person in charge of managing the machine?

As in FLOSS users are unfortunately still very much confronted with editing config files, Elektra has a huge impact even on casual, day to day FLOSS users. With Elektra they could use much better UIs then editing config files.
