### ISSUE TITLE
[FLOSS H0] CI Infrastructure

### ISSUE THREAD

**Issue by belthazors** [ElektraInitiative/libelektra#4097]
Which tools have been used for the continuous integration part of the project? What do the builds look like and how often do they run?

**Comment by markus2330** [comment]
Thank you for asking the question and participating in the FLOSS course!

> Which tools have been used for the continuous integration part of the project?

The main tools are: Jenkins and Docker. See also https://master.libelektra.org/doc/BUILDSERVER.md

> What do the builds look like and

See https://build.libelektra.org/blue/organizations/jenkins/libelektra/activity

> how often do they run?

On every new commit in every branch or PR.
