### ISSUE TITLE
integrate pages into website

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4098]
We have a few documents which are not yet integrated in the website, e.g.:

- [x] doc/CODING.md
- [ ] doc/README.md could be added to Documentation -> Index
- [x] doc/GIT.md
- [x] doc/BUILDSERVER.md
- [x] tests/shell/shell_recorder/tutorial_wrapper/README.md
- [x] doc/todo/RELEASE.md

These files should be added in the structure src/tools/website/resources/structure.json.in

For triage the pages which are missing are to be found.

Ideally we would also have a tool that can check if there are files floating in doc not integrated there.

**Comment by sedadas** [comment]
I was successful with reproducing the issue to some extent by running the following commands and comparing the outputs:

```
# find markdown file references in structure file
$ grep -o "doc/.*.md" src/tools/website/resources/structure.json.in
doc/GOALS.md
doc/WHO.md
doc/WHY.md
doc/VISION.md
doc/BIGPICTURE.md
doc/help/elektra-faq.md
doc/GETSTARTED.md
doc/KEYNAMES.md
doc/COMPILE.md
doc/INSTALL.md
doc/TESTING.md
doc/tutorials/README.md
doc/IDEAS.md
doc/CODING.md
doc/DESIGN.md
doc/SECURITY.md
doc/TESTING.md
doc/VERSION.md
doc/decisions/README.md
doc/dev/README.md
doc/BUILDSERVER.md
doc/AUTHORS.md

# find markdown files in docs, excluding some paths that are included in json dynamically
$ find doc/ -type f -name "*.md" -not -path "doc/api_*" -not -path "doc/tutorials/*" -not -path "doc/news/*" -not -path "doc/todo/*" -not -path "doc/usecases/*" -not -path "doc/tutorials/[a-z]*.md" -not -path "doc/decisions/[a-z]*.md" -not -path "doc/help/[a-z]*.md" -not -path "doc/dev/[a-z]*.md"

doc/WHO.md
doc/GOALS.md
doc/README.md                                            # not found by grep
doc/images/README.md                               # not found by grep, not sure if needed
doc/WHY.md
doc/GIT.md  # not found
doc/COMPILE.md
doc/VISION.md
doc/CODING.md
doc/decisions/README.md
doc/BIGPICTURE.md
doc/KEYNAMES.md
doc/markdownlinkconverter/README.md       # not found by grep, not sure if needed
doc/IDEAS.md
doc/GETSTARTED.md
doc/INSTALL.md
doc/DESIGN.md
doc/paper/README.md                                   # not found by grep
doc/paper/paper.md                                         # not found by grep
doc/dev/README.md
doc/AUTHORS.md
doc/TESTING.md
doc/BUILDSERVER.md
doc/VERSION.md
doc/API.md                                                       # not found by grep
doc/SECURITY.md
```
Interestingly enough, `doc/BUILDSERVER.md` and `doc/CODING.md` seem to be present in the structure file, but not visible on the website.

The commands from above can be used for developing a bash script that checks this automatically.

**Comment by markus2330** [comment]
Very good triage! I am also interested what the problem with doc/BUILDSERVER.md and doc/CODING.md could be.

**Comment by sedadas** [comment]
@markus2330 I created a new PR #4179 
I handled all of the files there, excluding:

* tests/shell/shell_recorder/tutorial_wrapper/README.md
* doc/paper/*.md
* doc/API.md

I was not sure where to add them :sweat_smile:

**Comment by markus2330** [comment]
> tests/shell/shell_recorder/tutorial_wrapper/README.md

Development -> Testing of Tutorials

> doc/paper/README.md

Documentation -> Citations

(doc/paper/paper.md not needed)

> doc/API.md

Not needed, as "API documentation" is already linked.

**Comment by markus2330** [comment]
- doc/CODING.md seems to be still missing (was always at top post of #4098)
- doc/README.md could be added to Documentation -> Index (I added it in top-post)

**Comment by stefnotch** [comment]
doc/CODING.md is already available on the website at https://www.libelektra.org/devgettingstarted/coding

**Comment by stefnotch** [comment]
doc/README.md is also on the website under https://www.libelektra.org/docgettingstarted/github-main-page

**Comment by stefnotch** [comment]
I think this issue can be closed

**Comment by markus2330** [comment]
> doc/CODING.md is already available on the website at https://www.libelektra.org/devgettingstarted/coding

:+1: I updated the top-post.

> doc/README.md is also on the website under https://www.libelektra.org/docgettingstarted/github-main-page

I think this is /README.md, not doc/README.md? So  "doc/README.md could be added to Documentation -> Index" is the last missing?
