### ISSUE TITLE
Broken links to Linux packages on website

### ISSUE THREAD

**Issue by flo91** [ElektraInitiative/libelektra#4099]
## Steps to Reproduce the Problem

On the website of the initiative (https://www.libelektra.org) in the middle of the page there is a point named **Availability** with links to various Elektra-packages for Linux distributions.

The links to the packages for the following distributions lead to error-pages with the following contents:

- [ ] [Fedora](https://admin.fedoraproject.org/pkgdb/package/elektra/): 404 - not found
- [ ] [Gentoo](http://packages.gentoo.org/package/app-admin/elektra): 404 - not found
- [ ] [Debian](https://packages.debian.org/de/jessie/libelektra4): Error - two or more packages specified (libelektra4 jessie)
- [ ] [PLDLinux](http://sophie.zarb.org/rpms/763d9e52beefaa15b1363d11d836b65c): This page does not exists
- [ ] (if ready add Alpine Linux #4247)

## Expected Result

The links should lead to useful pages about the distribution specific Elektra-packages.
If Elektra-packages are not available anymore for some distributions, I think the affected links should be removed.

My investigations lead to the following results:

**1. Fedora**
I only found an entry for an unmaintained orphaned package at https://src.fedoraproject.org/rpms/elektra.
If no other package is available, I think the link should get removed.

**2. Gentoo**
I could not find a package containing "elektra" in its title.
```
flo@floPCVn ~ $ emerge -s elektra
  
[ Results for search key : elektra ]
Searching...

*  app-crypt/elettra [ Masked ]
      Latest version available: 1.0
      Latest version installed: [ Not Installed ]
      Size of files: 16 KiB
      Homepage:      https://www.winstonsmith.info/julia/elettra/
      Description:   Plausible deniable file cryptography
      License:       WTFPL-2

[ Applications found : 1 ]
```
The repository was synced today:
```
flo@floPCVn ~ $ date -r /var/db/repos/gentoo/metadata/timestamp
Wed Oct 13 11:09:48 CEST 2021
```

I also could not find an Elektra-related package in the unofficial portage overlay search: 
https://gpo.zugaina.org/Search?search=elektra
Therefore, I think that the link to the Gentoo package should get removed.

**3. Debian**
For debian I found some Elektra-related packages at https://packages.debian.org/search?keywords=elektra&searchon=names&suite=all&section=all.

I think that the link should get updated to point to a valid page, e.g.
elektra-bin: https://packages.debian.org/sid/elektra-bin
libelektra4: https://packages.debian.org/sid/libelektra4

**4. PLD Linux**
I could find some Elektra-related packages at http://sophie.zarb.org/search?search=elektra&type=fuzzyname&deptype=P&distribution=PLD&release=th&arch=x86_64.
elektra: http://sophie.zarb.org/rpms/567b680f47229535203d9963cf8ea869

I think that link should also get updated to point to a valid package page.

## Actual Result

The four mentioned links lead to error pages.

## System Information

- OS: Gentoo Linux (custom kernel 5.14.11)
- Browser: I tried with Firefox 93.0 and Vivaldi 4.1.2369.21

**Comment by markus2330** [comment]
Excellent investigations and thank you for joining the FLOSS course!

These links are in src/tools/website/public/assets/translations/en.json which is not part of our dead-link checker. So I think it is best to remove all these links from there and put links only to installation instructions, which is currently also a wrong link (it should go to https://www.libelektra.org/installation/installation but it links to https://www.libelektra.org/docgettingstarted/installation).

> If no other package is available, I think the link should get removed.

There is another package, created by us, see https://www.libelektra.org/installation/installation
So let us simply link there.

> Therefore, I think that the link to the Gentoo package should get removed.

Not only the link but also the word "Gentoo". Hopefully they will find a new maintainer.

> Debian

As in Fedora, we provide packages.

**Comment by markus2330** [comment]
Maybe Alpine (#4247) can also be added once done. I updated the top post.
