### ISSUE TITLE
cmake variables that should be marked as advanced

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4100]
Following variables can be marked as advanced:

- [ ] DISCOUNT_DIR
- [ ] DREDD_EXECUTABLE
- [ ] GO_EXECUTABLE
- [ ] Qt5QmlModels_DIR
- [ ] TARGET_LUA_CMOD_FOLDER
- [ ] TARGET_LUA_LMOD_FOLDER

to be added in scripts/cmake/ElektraCache.cmake (in the first part "might be relevant to users")
It would be even better to have two (or even more) separate mark_as_advanced, for the different groups (as rationale why we marked them as advanced).

**Comment by flackojr** [comment]
i'd love to try this out if i may
