### ISSUE TITLE
Look into Github Checks API for Jenkins

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#4107]
Currently, our Jenkins Server doesn't integrate with the Github Checks API. I saw that there is a [Jenkins plugin](https://plugins.jenkins.io/github-checks/) for this integration. We should look into using it.

I don't know, if it would actually show any logs directly on Github, like the other CIs. However, it seems that at least a "Re-run" button would be shown, which would be better UX than the "jenkins build libelektra please" solution we have right now.

cc @robaerd @mpranj

**Comment by markus2330** [comment]
Btw. if you are logged in in Jenkins you get a rerun button within Jenkins. If you want an account, please drop me an e-mail (markus@libelektra.org)

**Comment by mpranj** [comment]
I think @kodebach should have an account just in case, but I also think the Github Checks API would be beneficial for other contributors. This should be easier to manage from Github, instead of manually creating accounts for everyone.

**Comment by kodebach** [comment]
Agreed, a Jenkins account might help me (although I've not needed it so far). But unless we can restrict the access to "read-only + re-run" and integrate some sort of GitHub OAuth, I don't think this solution can be compared to the benefits of the Checks plugin.

**Comment by flo91** [comment]
@markus2330 Maybe also an issue for the FLOSS course?

**Comment by kodebach** [comment]
cc @lukashartl

**Comment by markus2330** [comment]
No, this issue needs admin access to Jenkins.
