### ISSUE TITLE
[FLOSS H1] First steps with Elektra

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/libelektra#4116]
# First impression

I build elektra from source following the docker container guide (https://www.libelektra.org/tutorials/run-all-tests-with-docker). I really enjoyed the tutorial section which adresses many problems someone could have. I could maybe wish for a workshop to discover what elektra has to offer in a playful way. Similar to (https://github.com/openfaas/workshop).

I did not really enjoy testing. I think it takes too long and having 2 split test suits which kinda depend on different things made me wonder. Maybe there is a possibility to test only certain modules/plugins and I just did not know, so sorry in advance.

**Comment by markus2330** [comment]
> I could maybe wish for a workshop to discover what elektra has to offer in a playful way. Similar to (https://github.com/openfaas/workshop).

Thank you, very good suggestion. This could be a task for T3.

> I did not really enjoy testing. I think it takes too long and having 2 split test suits which kinda depend on different things made me wonder.

Which 2 test suites do you mean?

> Maybe there is a possibility to test only certain modules/plugins and I just did not know, so sorry in advance.

Very good hint! Maybe you were searching for `-R` of `ctest`? Whatever you were searching for, this could be made more clear in doc/TESTING.md.
