### ISSUE TITLE
[FLOSS H1] Link in Web-UI documentation leads to 404

### ISSUE THREAD

**Issue by marvin-the-parrot** [ElektraInitiative/libelektra#4117]
## Steps to Reproduce the Problem

Go to [Web-UI](https://github.com/ElektraInitiative/libelektra/tree/master/src/tools/webui) page in GitHub and click on the link named [yajl plugin](https://github.com/ElektraInitiative/snippets/src/plugins/yajl/).
## Expected Result

The link should take me to the [yajl plugin page](https://github.com/ElektraInitiative/libelektra/tree/master/src/plugins/yajl) inside the elektra repository. From there I can further follow the instructions and read about the plugin.

## Actual Result

The link leads to an (old?) link and ends in a 404 by GitHub.

## System Information

Browsers tested on: Chrome, Opera

**Comment by markus2330** [comment]
We removed this text.
