### ISSUE TITLE
[FLOSS H1] Elektra First steps

### ISSUE THREAD

**Issue by marvin-the-parrot** [ElektraInitiative/libelektra#4118]
### Building/Installing Elektra
I started out following the steps outlined in [Getting started] (https://github.com/ElektraInitiative/libelektra/blob/master/doc/GETSTARTED.md) The documentation there provides an easy to follow step-by-step guide towards installing and building your first elektra application.

Afterwards i built a small testbuild using the [Hello, Elektra](https://github.com/ElektraInitiative/libelektra/blob/master/doc/tutorials/hello-elektra.md) page. Again the instructions were easy to follow and provided me with every detail I needed in order to get elektra up and running.

Afterwards i tried installing the yajl plugin to use the web-ui but encountered problems in the documentation. (#4117)

**Comment by markus2330** [comment]
Thank you for the small report!

> [Getting started

The markdown link is broken (no space between ] and ( allowed).
