### ISSUE TITLE
[FLOSS H1] Elektra First Steps

### ISSUE THREAD

**Issue by lawli3t** [ElektraInitiative/libelektra#4120]
I started by cloning the repository, and building the whole project from scratch. After installing some additional dependencies, as per the https://github.com/ElektraInitiative/libelektra/blob/master/doc/GETSTARTED.md guide. After getting everything set up, I first built Elektra and the tests afterwards. The tests ran through successfully, indicating that my build seems to be working properly.

Afterwards I explored the Elektra Core API, which constitutes the central part of Elektra. I made myself familiar with the available functions in the API and this branched into some further learning about the core concepts mentioned in the API documentation.

(since I started working on Elektra already before, I tried to describe my past experience of starting working on Elektra)

**Comment by markus2330** [comment]
Thank you for the report! :sparkle:
