### ISSUE TITLE
[FLOSS H1] Elektra first steps

### ISSUE THREAD

**Issue by Nirnberger** [ElektraInitiative/libelektra#4121]
I cloned the repository and built it following this helpful [guide](https://github.com/ElektraInitiative/libelektra/blob/master/doc/GETSTARTED.md). After a few missing dependency errors, I managed to get Electra running. I wasted too much time on figuring out why the test didn't work at all. It turned out that I missed one single sudo. :sob: 
Afterwards I followed the [hello world tutorial](https://github.com/ElektraInitiative/libelektra/blob/master/doc/tutorials/hello-elektra.md). 

I got stuck again after installing the [webui](https://github.com/ElektraInitiative/libelektra/blob/master/doc/tutorials/install-webui.md). I'm still stuck here but I'll try to get it to work tomorrow.

**Comment by markus2330** [comment]
> I got stuck again after installing the webui. I'm still stuck here but I'll try to get it to work tomorrow.

Did you have some progress? Note that the webui is known to be broken at the moment, see #2913 

> Also notice that i am not a contributor yet, thus unable to assign labels.

This should be fixed.
