### ISSUE TITLE
[FLOSS H1] Elektra first steps

### ISSUE THREAD

**Issue by flo91** [ElektraInitiative/libelektra#4122]
My first experiences with Elektra were quite good.
I forked the master branch in my GitHub repository and cloned the repository to my local PC with [Gentoo Linux](https://www.gentoo.org).
Then I tried a bit of building, testing and debugging like shown in the documentation and in the video [L01-4 Demo](https://tuwel.tuwien.ac.at/mod/lti/view.php?id=1366980) in the TUWEL course.
I also tried to follow the testing tutorial (https://www.libelektra.org/testing/testing), which also worked like a charm.

The next step was to install and setup the [CLion IDE](https://www.jetbrains.com/clion/) and import the project there.
To accomplish that, I followed the tutorial at https://www.libelektra.org/tutorials/contributing-with-clion.
I could not find the `run_all` target that was mentoined in the section _Testing_ of that tutorial and was a bit overwhelmed by the huge number of different targets.
It also worked to run all tests at once within the IDE, but when I wanted to run some single tests (e.g. `testcpp_kdb`) I got an error message:

```
unknown file: Failure
C++ exception with description "10 Warnings were issued:
	Sorry, module kdb issued the warning C01200:
	Installation: Dlopen failed. Could not load module libelektra-resolver.so. Reason: (null)
	Mountpoint: /
	Configfile: 
	At: /home/flo/tu/libelektra/src/libs/loader/dl.c:90
Sorry, module kdb issued the error C01200:
Installation: Could not open default backend. See other warning or error messages for concrete details
Mountpoint: /
Configfile: 
```

The solution was to add an environment variable to the `testcpp_kdb` configuration:
`LD_LIBRARY_PATH=/home/flo/tu/libelektra/cmake-build-debug/lib`

For developing and debugging such a comprehensive project that includes multiple programming languages, I think a good and powerful IDE like CLion is an important tool. After some setup and configuration of the IDE at first, I really liked working with it on the Elektra-initiative.

**Comment by markus2330** [comment]
Thank you very much for this excellent experience report! I am looking forward to see an update in the CLion tutorial. Ideally you could somehow tell the IDE that it calls scripts/dev/run_env, which also fixes other important env vars next to LD_LIBRARY_PATH.
