### ISSUE TITLE
KeySet ref counter in bindings

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#4129]
The new reference counting for KeySets that was implemented in #3949 still needs to be implemented in the bindings:

- [ ] C++
- [ ] Python (should be automatic via Swig from C++)
- [ ] Ruby (should be automatic via Swig from C++)
- [ ] Lua (should be automatic via Swig from C++)
- [ ] Rust
- [ ] Java (#4348)
- [ ] GLib

**Comment by markus2330** [comment]
Thank you for reporting!

**Comment by markus2330** [comment]
This is either a project (to update all the ref counters) or a single task in T3 for each language.

**Comment by mandoway** [comment]
[CM T0]

My colleague @Gratla and I want to work on this issue.
Specifically, we want to implement the Java part, and possibly the C++ part if we need it to reach the appropriate scope for the team tasks. 

AFAIK, ref counters are used to keep track of Elektra key references.  
They are needed to communicate when it is safe to clear a Key object.
So the implementation plan would be:
- Increment a ref counter in KeySet class on creation
- Decrement the counter on deconstruction
- Clear object references when the ref counter drops to 0

The Java KeySet ref counter will be implemented in this file:
https://github.com/ElektraInitiative/libelektra/blob/431888f2d4d229dfee159bf93ce55601b694ecae/src/bindings/jna/libelektra/src/main/java/org/libelektra/KeySet.java

For the [C++ binding](https://github.com/ElektraInitiative/libelektra/tree/master/src/bindings/cpp), I've only found header files in the directory, so I'm not sure where this should actually be implemented.
I'd be thankful for a hint on that! :)

**Comment by kodebach** [comment]
Yes, the C++ binding is a header-only library. The reference counting for `Key` is implemented via `operator++` and `operator--`.

For example:

https://github.com/ElektraInitiative/libelektra/blob/431888f2d4d229dfee159bf93ce55601b694ecae/src/bindings/cpp/include/key.hpp#L671-L679

which is called in all constructors, e.g.

https://github.com/ElektraInitiative/libelektra/blob/431888f2d4d229dfee159bf93ce55601b694ecae/src/bindings/cpp/include/key.hpp#L651-L658

**Comment by Gratla** [comment]
I think the corresponding implementation for the Key-Class is here:

https://github.com/ElektraInitiative/libelektra/blob/431888f2d4d229dfee159bf93ce55601b694ecae/src/bindings/jna/libelektra/src/main/java/org/libelektra/ReadableKey.java#L79-L115

**Comment by tucek** [comment]
@markus2330 I would spawn an issues dealing with updating teh Kava bindings only, ok? (or is there already an issue, i did not find?)

**Comment by markus2330** [comment]
Yes, please open new issues as needed. Simply link in the list above to the issue.

**Comment by Gratla** [comment]
@tucek as stated above by @mandoway, him and I want to do the java binding within the CM course.

**Comment by tucek** [comment]
@Gratla @mandoway I've added #4348 to track the changes for the Java bindings.
