### ISSUE TITLE
warning when mounting experimental plugins?

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#416]
In #389 the end-user is left out. What can we do to make it more clear for the end user that a plugin might not work as good as another?

The current situation is that one has to read the whole text in `kdb info <name>`. I propose:
1. Adding a contract information that an plugin is experimental
2. `kdb mount` should refuse mounting such plugins unless `-i --ignore-warnings` is given
3. `kdb list` does not list experimental plugins by default

Notes:
1. `kdb check` would still say nothing, otherwise internal tests would fail

**Comment by markus2330** [comment]
output warning and add quiet mode (also using KDB)

**Comment by markus2330** [comment]
To cover some more use-cases, I would extend the proposal to not only have the tag/status `experimental`, but also:

1.  popular
1.  productive .. means it is known to be in productive use
1.  specific .. means that the plugin is non-portable in order to gain some specific advantages for the user (i.e. in a positive sense specific/non-portable).
1.  unittest
1.  tested .. manually, thus not as "good" as unittest
1.  preview
1.  memleak
1.  experimental
1.  unfinished
1.  concept

Any of these tags can be added as space separted list in `infos/status`.

Any concerns, comments or wishes (e.g. for other tags)?

The idea is not to only give the user a info/warning, but also to use these tags for automatic calculation for which plugins should be preferred.

**Comment by petermax2** [comment]
> 1. Adding a contract information that an plugin is experimental
> 2. kdb mount should refuse mounting such plugins unless -i --ignore-warnings is given

agreed! :+1: 

> 3. kdb list does not list experimental plugins by default

it could also mark them as experimental. What about users who refuse to read manuals?

**Comment by markus2330** [comment]
@tom-wa also proposed to have a tag "undocumented" for some plugins that only have a minimal README.md. I agree that the documentation status of a plugin should be considered, too.

**Comment by fberlakovich** [comment]
I like both ideas, the proposed list of tags as well as the tag for the documentation status.

**Comment by markus2330** [comment]
popular is subjective

**Comment by markus2330** [comment]
@fberlakovich @petermax2 @manuelm if you want you can create PRs for your infos/status in the plugin, or simply suggest how you want it here.

**Comment by manuelm** [comment]
lua: unittest
python: unittest; maybe memleak, but that's because of python itself

**Comment by petermax2** [comment]
I will create a PR.

**Comment by markus2330** [comment]
Instead of popular we could use recommended? (Still subjective, but better tells what is meant).

Please write here if you have further ideas for tags. There should be many because every plugin should have a different status, so that we never have to rely on alphabetical or another order.

Some further ideas:

- compatible (to indiciate it will be compatible with later versions)
- conformant (to indicate that e.g. a storage plugin fulfils all requirements of a storage plugin)
- configureable
- final (no further extensions, configure options or features are desireable)
- maintained (actively used and fixed by someone)
- nodep (no external dependency, except language core deps)
- libc (only uses libc, so no libstdc++, rust-runtime,.. or the like)

**Comment by markus2330** [comment]
Hi, I added a status to all plugins in 82d24e0685cbb10f74bee8502d47f50dedfd9c6e

The current rating of all plugins is:
```
$ kdb list -v
number of all plugins: 64
doc -1032000
template -988200
error -15000
tcl -4000
iterate -3500
struct -3000
regexstore -2000
crypto -1500
crypto_gcrypt -1500
fstab -500
hidden -450
glob 50
noresolver 500
simpleini 2000
wresolver 2000
constants 2500
logchange 3000
type 3000
jni 3050
syslog 3500
python 3750
python2 3750
lua 4000
uname 4000
xmltool 4000
lineendings 4050
counter 4100
journald 4250
network 4250
ni 4250
null 4500
path 4500
timeofday 4500
tracer 4500
validation 4500
mathcheck 5000
filecheck 5050
dbus 5250
augeas 5300
iconv 5300
conditionals 5450
hosts 5500
list 5500
ccode 5550
hexcode 5550
line 5550
rename 5550
keytometa 6050
ini 6550
yajl 7000
enum 12000
csvstorage 13550
dump 14750
resolver 14800
resolver_fm_b_b 14800
resolver_fm_hb_b 14800
resolver_fm_hp_b 14800
resolver_fm_pb_b 14800
resolver_fm_ub_x 14800
resolver_fm_uhb_xb 14800
resolver_fm_xb_x 14800
resolver_fm_xhp_x 14800
resolver_fm_xp_x 14800
sync 45050
```

If you think some [tags or its value](https://github.com/ElektraInitiative/libelektra/blob/master/doc/CONTRACT.ini) should be changed; or in general that the ranking above is not like you would expect, please tell here or create a PR for concrete changes.

Thank you!

**Comment by markus2330** [comment]
I think the positive approach fits better: If users are not sure they can simply specify a provider (e.g. resolver or storage) and let `kdb` select the correct plugin for them. So no warning when mounting experimental plugins. (which are disabled to be build by default anyway)
