### ISSUE TITLE
Provide global initialization and destruction

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#418]
As initially proposed by @manuelm and now by @petermax2  in #276 we could add global initialization and destruction.

Use case: Some plugins need libraries (or interpreters) which need to be initialized exactly once. (currently: crypto, syslog, python)

Ways to resolve it:
1. (Current way) when plugin is opened (+ will only be done when plugin is used, + users do not have to care about it, - need reference counting library facilities to work correctly with other libraries doing the same thing, as workaround a `noinit` plugin configuration can be provided)
2. provide some form of `kdbInit()` and `kdbFini()` that callback what plugins want them to do (- API for user gets more difficult and gets more state, - setup might happen for non-used plugins, - Cannot be used in within-plugin context)
3. global __constructors__ (- also needs ref counting for libraries, - not portable)
4. @manuelm mentioned something about apache?

If we agree to (1) we should also agree to a convention how the `noinit` plugin configuration should be named.

**Comment by petermax2** [comment]
As for the crypto plugin number 1 would be great. I just want to know if I'm the first plugin of my kind. Some global destruction mechanism could be useful in the future (like cleaning up secure memory ares and stuff like that)

**Comment by markus2330** [comment]
Do you really mean 1.? (thats status quo)

Knowing that you are the first plugin still gives no information if the application or other libraries have already initialized libssl before.

I am afraid that there is no solution for the general problem: You cannot fix every broken API design by an additional layer. But I am looking forward that someone can convince me otherwise and we find a nice solution for python+libssl+syslog init and especially cleanup!

I think the best solution is to avoid global state all together (current approach in Elektra) and the second best solution is a reference-counted atomic "give me the handle if it already exists or create one otherwise" similar to the JNI API. Its only the second best because 1. forces some multi-thread decisions to the application and/or 2. fail if you need (different) configuration for the initialization.

Nevertheless, I think the discussion is necessary because it is a recurring problem with many APIs.

**Comment by manuelm** [comment]
What about moving the decision about initializing and final destruction to the end-user/application developer (API consumer)? As said many times we - as a library - are not able to fix this, just so some workarounds.

**Comment by petermax2** [comment]
@markus2330 do we have some reference counting facility in Elektra right now? Because knowing at `OPEN` that this is instance 1 and knowing at `CLOSE` that 0 instances are remaining after this plugin, would be sufficient for my needs. I don't know about python tough.

**Comment by manuelm** [comment]
Just use some static variable. I'm doing the same in `src/plugins/python/python.cpp` (search for `open_cnt`). However this is still no general solution.

**Comment by petermax2** [comment]
@manuelm thx! I was planning on doing the same but I wasn't sure if Elektra provided this information in some other way.

Besides not having the nicest API in the world, what's wrong with mutex + ref count?

**Comment by manuelm** [comment]
We as a library can't know what other libraries an application might be using. e.g. an application might already have python/openssl/whatever initialized and libelektra will mess with that.

**Comment by markus2330** [comment]
I think the issue is now clear to everyone and it seems that there is no perfect solution: We need to take care that libraries we integrate do not have such issues.
