### ISSUE TITLE
[CM T0] remove fullname from example_key.py

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/libelektra#4183]
Just stumbled accross this python error while trying out the python binding. Did I miss some installation steps?

## Steps to Reproduce the Problem

```sh
docker run -it debian:buster
apt-get update
apt-get install ca-certificates
apt-get install vim
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F26BBE02F3C315A19BF1F791A9A25CC1CC83E839
vim /etc/apt/sources.list
```
added "deb https://debs.libelektra.org/buster buster main" to sources.list

```sh
apt-get update
apt-get install python3-elektra
vim test.py
```

```python
import kdb

key1 = kdb.Key("user:/key1", kdb.KEY_VALUE, "some_value")
print("Key1 name=\"{0}\" value=\"{1}\"".format(key1.name, key1.value))
print("")

print("Every Key has properties. Some are read only, some are read+write.")
print("Properties of Key1:")
print("  key1.name     = \"{0}\"".format(key1.name))
print("  key1.value    = \"{0}\"".format(key1.value))
print("  key1.basename = \"{0}\"".format(key1.basename))
print("  key1.fullname = \"{0}\"".format(key1.fullname))
print("")
```

```sh
python3 test.py
```

## Expected Result

key.fullname should return the fullname of the key

## Actual Result

AttributeError: 'Key' object has no attribute 'fullname'

## System Information

- Elektra Version: master
- Docker container debian:buster
- python 3.7.3

## Further Log Files and Output

```python
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    print("  key1.fullname = \"{0}\"".format(key1.fullname))
AttributeError: 'Key' object has no attribute 'fullname'
```

**Comment by markus2330** [comment]
You found a bug in the docu/example, fullname was actually removed in d9a8478478b0009971a070d2990af0b310abfd7e

So the proper fix is to remove all references of fullname, as this concept does not exist anymore (name would be always identical to fullname).

**Comment by mandoway** [comment]
[CM T0]
My colleague @Gratla and I would like to work on this ticket.

I reproduced the issue with (I already had elektra and the according keys installed):
Installing the package: 
```sh
sudo apt update
sudo apt install python3-elektra
```

test.py:
```python
import kdb

key = kdb.Key("user:/key1", kdb.KEY_VALUE, "some_value")

print(key.fullname)
```

And executing: `python3 test.py` results in:
```sh
Traceback (most recent call last):
  File "/home/markus/test.py", line 5, in <module>
    print(key.fullname)
AttributeError: 'Key' object has no attribute 'fullname'
```

I found references to `.fullname` in the examples and tests of the python binding.

**Comment by Gratla** [comment]
The code/doc which needs to be changed is in the following lines:

https://github.com/ElektraInitiative/libelektra/blob/431888f2d4d229dfee159bf93ce55601b694ecae/src/bindings/swig/python/examples/example_key.py#L7-L13

Do we need to remove the occurences in the following tests/files as well?

https://github.com/ElektraInitiative/libelektra/blob/master/src/bindings/swig/python/tests_tools/test_tools_plugindatabase.py
https://github.com/ElektraInitiative/libelektra/blob/master/src/bindings/swig/python/tests_tools/test_tools_pluginspec.py

**Comment by kodebach** [comment]
Yes, every use of `key.fullname` in Python should be removed or replaced by `key.name`. Which one is appropriate depends on the context. In most cases it should be fairly obvious what to do. Just try to avoid duplicate tests/output/etc. and try not to remove anything that could be important.
