### ISSUE TITLE
Documentation for "kdb list" is wrong

### ISSUE THREAD

**Issue by nikonthethird** [ElektraInitiative/libelektra#420]
Running `kdb list --help` says:

    kdb-list - List keys in the key database

In reality it lists the Elektra plugins that are available. KDB version used: 0.8.14

**Comment by nikonthethird** [comment]
I also think the name "list" is too generic and totally sounds like it lists all keys in the database.

Compared to `kdb list-tools`, the command `kdb list` should in my opinion be renamed to `kdb list-plugins`.

**Comment by markus2330** [comment]
Yes, some names are too generic, a new naming schema is discussed at #265

**Comment by nikonthethird** [comment]
I didn't notice the issue about the naming schema. Closing this because it is superfluous.
