### ISSUE TITLE
Enable all shell recorder plugins

### ISSUE THREAD

**Issue by muskater** [ElektraInitiative/libelektra#4200]
This issue is related to my PR #4190 where I try to enable the shell recorder for all the plugins. This are my findings so far

I have looked into a lot of the failed test cases. Here are my findings so far:

- [x]  Some tests like for the `base64` plugin fail, if the logger is enabled as build option, because it changes the standard output. Therefore, this option should be disabled when running the tests. 
- [ ] gitresolver: The shell recorder is not applicable for this plugin 
- [ ] crypto*: I removed the shell recorder for the `brew` command. However, something is still not working right. 
- [x] augeas: Some umount and return values were missing . I tried to add them. It should now work now but the standard output dose not match at the moment. (This should be easily fixable)
- [ ] error* : I added a missing return value. However the line, `kdb mount error.dump /error error on_open/error=C03100 dump` doew not work properly 
- [ ] desktop: not really testable in a command line environment 
- [ ] fstab* :  There seems to be a problem with mounting 
- [ ] iterate: Dose not currently have an example that is working/applicable with the shell recorder 
- [ ] jini: I unfortunately could not test this plugin. 
- [x] logchange: added missing umount. This should work now.
- [ ] lua: Dose not currently have an example that is working/applicable with the shell recorder
- [ ] python: Dose not currently have an example that is working/applicable with the shell recorder 
- [x] passwd: Fixed a missing umount,  and removed standard out verification, because it is different for every user and testable in an standardized way. 
- [ ] profile: uses a non existing file

**Comment by markus2330** [comment]
Great job, thank you for creating the issue!

**Comment by markus2330** [comment]
Even for the tasks ticked above there is still "TEST_README" missing in the CMakeLists.txt.
