### ISSUE TITLE
https://doc.libelektra.org/ should hide plain email addresses

### ISSUE THREAD

**Issue by cicku** [ElektraInitiative/libelektra#4202]
https://doc.libelektra.org/api/0.9.3/latex/doc_AUTHORS_md.tex directly lists all email address without obfuscation.

**Comment by markus2330** [comment]
Thank you for contacting us! :sparkle: 

Also affected is https://www.libelektra.org/developers/authors

In general authors can decide themselves

1. if they want to be listed in AUTHORS.md
2. if they want to have their email address  in AUTHORS.md
3. if it should be obfuscated

So if you want to be listed in AUTHORS.md but want your email address to be obfuscated, I think the easiest way is to simply obfuscate it within the source file of AUTHORS.md

Is this okay for you?

**Comment by cicku** [comment]
Yes
