### ISSUE TITLE
[FLOSS] JSON spelling

### ISSUE THREAD

**Issue by muskater** [ElektraInitiative/libelektra#4212]
While finishing up #4190, I noticed that the spell checker script does not allow `JSON` to be spelled as `json` and the build failed.
This means that commands like
```
kdb export system:/tests/passwd/root json
```
get flagged as wrong spelling.
The easiest solution would be to allow `JSON` to be spelled as `json`. 
@markus2330 also pointed out that it would be also possible to have the spell checker ignore the _case_  for commands like `kdb mount/export`.

**Comment by markus2330** [comment]
> The easiest solution would be to allow JSON to be spelled as json.

Probably also the best solution.

> @markus2330 also pointed out that it would be also possible to have the spell checker ignore the case for commands like kdb mount/export.

I meant that `kdb mount/export` internally does a tolower so that `kdb export JSON` would work.
