### ISSUE TITLE
remove elektraCopyCallbackMeta

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#4221]
https://github.com/ElektraInitiative/libelektra/blob/0d9ba69aedca7ec8ad706255672867f1aa174e52/src/libs/elektra/keyset.c#L1881-L1905

The key name checks are wrong, they don't take the `meta:/` namespace into account. It also seems this functionality isn't tested anywhere, otherwise we should have noticed it by now.

**Comment by markus2330** [comment]
Thank you for reporting!

I actually think we should remove this functionality.

**Comment by kodebach** [comment]
Which functionality do you mean specifically?

**Comment by kodebach** [comment]
If you a referring to the `meta:/callback` mechanism, see #4222. It isn't really used right now (AFAICT), but it could be really useful for `spec:/` if used correctly and could significantly simplify the `ksLookup` within `libelektra-core`.

**Comment by markus2330** [comment]
I mean removing the whole callback mechanism. Of course it **could** be interesting **if**

1. it has a clean interface
2. is properly documented
3. is properly tested

as 1-3 is not the case we should remove it and introduce it whenever 1-3 is fulfilled.
