### ISSUE TITLE
remove *_NAME from public symbols

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4230]
As discussed in https://github.com/ElektraInitiative/libelektra/pull/4224#discussion_r788018581

remove them from src/libs/elektra/symbols.map and all other occurrences introduced in #4224

**Comment by kodebach** [comment]
I don't see why these symbols exist at all. AFAICT they are just used to set the `description` meta keys of errors/warnings. They are only used within `errors.c` and the new code from #4224.

Add made a quick PR: #4232
