### ISSUE TITLE
INI plugin strips off UTF8 byte order mark

### ISSUE THREAD

**Issue by nikonthethird** [ElektraInitiative/libelektra#424]
I noticed while playing around with the INI plugin and files created with [Notepad++](https://notepad-plus-plus.org/), that files containing a [BOM (byte order mark)](https://en.wikipedia.org/wiki/Byte_order_mark) are stripped of it when using `kdb set`.

## Steps to reproduce:

Create INI file with BOM:

    uconv -f utf-8 -t utf-8 --add-signature << EOF > test.ini
    [test]
    key=uni❤code
    key2=true
    EOF
    
You can verify that the BOM is present with:

    file test.ini
    
Output should be: `test.ini: UTF-8 Unicode (with BOM) text`

Mount the file and change a value:

    sudo kdb mount $(realpath test.ini) system/testing ini
    kdb set system/testing/test/key2 false

    file test.ini

**Expected output**: Same as above. **Actual output**: `test.ini: UTF-8 Unicode text`

Unmount the file with:

    sudo kdb umount system/testing

**Comment by markus2330** [comment]
Thanks for reporting! @tom-wa does #405 handle this already?

**Comment by markus2330** [comment]
Are only the characters related to BOM gone or also other text?

**Comment by tom-wa** [comment]
thats actually the inih library that strips the BOM, but i'll try include a fix for keeping BOMs

**Comment by markus2330** [comment]
I am not sure if we should put too much effort into inih. What it does is not that hard and it fails in many important aspects of ini-parsing. Its not even able to have = in a key. Dont you think that there are much better ini parsers out there?

the ni plugin has quite good parsing code, but unfortunately rips off all comments and destroys ordering.

I did some comparision when I decided for the ni plugin:
```
projectname    portable    lang  db         documentation  licence   deps        -issues,+features
appconf        w32, linux  C     ini,mysql  none(?)        GPL       none
CFL            ansi        C                doxygen, well  GPL       gdsl
simpleXMLconf  *nix,w*     C
OSSP cfg       ansi        C     
varconf        any         C++                                       libsigc++   -flat
ConfigLib                  C++              classref       bsd                   +tutorial
UT_var                                                     bsd
Nickel         C99         C     ini                       zlib                  +speed,-comments
SimpleIni      w32, linux  C++   ini        doxygen        MIT                   +utf8, +lf
rudeConfig
libINI
RudeConfig    b,vc++,lin   C++   ini        java,tut       GPL                   +comments
```

Maybe its time to do a comparision like this again? The requirements are:

- correct handling of every byte sequence
- BSD compatible licence
- keeping order
- keeping comments (+ ideally also whitespaces)

**Comment by tom-wa** [comment]
i'm not sure if keeping the order can actually be done by the ini parser, shouldn't the ini elektra plugin handle the order ? keeping the BOM should be a trivial change to ini/inih and the rest already works (except having a = in a key or preseving whitespaces other than newlines) but i guess looking for an alternative isn't a bad idea

**Comment by markus2330** [comment]
Thanks! With keeping order I mean not discarding it. So you are right, the elektra plugin needs to do its part, too.

If = and BOM are the only problems inih should obviously be fixed. But with such obvious problems present I am afraid that there will be much more problems. In an additional quick test now, it does not seem to support spaces in key names and has a quite short maximum length for key value. (`kdb test system/testing string`).

The #405 is one of the most advanced ini plugins available today and it would be a pity to have such a primitive parsing code underneath it.

**Comment by tom-wa** [comment]
i guess you are right, and it would be really nice to keep formating whitespaces, etc.
but wouldn't the best solution be writing a new ini parser/writer that does exactly what we need and shares a datastructur with the elektra plugin ? that way the only thing passed between the plugin and the parser/writer would be a data structure (+ allocated memory) and some flags and all file operations could be moved to the parser/writer while the elektra plugin handles everything else

**Comment by markus2330** [comment]
Yes, it would be a very good option, but the parser might be more work than you expect.

**Comment by nikonthethird** [comment]
> Are only the characters related to BOM gone or also other text?

As far as the tools I tried are concerned, the BOM is the only piece of information that is lost. I have not tried comments and such.

**Comment by markus2330** [comment]
@tom-wa told me that in the filecheck plugin he checks for 14 different kinds of BOMs.

@nikonthethird is only the UTF-8 BOM relevant or also the others?

**Comment by nikonthethird** [comment]
For Windows (or more specifically, Notepad++), only the UTF-8 BOM is relevant. If it is present, it's an UTF-8 file, if not, it's a ASCII or binary file.

**Comment by markus2330** [comment]
Seems to work now!
