### ISSUE TITLE
[REQ] Alpine APK for aarch64(deprecated)/arm64v8

### ISSUE THREAD

**Issue by Kochise** [ElektraInitiative/libelektra#4247]
Hi, is there any plan to create and maintain an Alpine package for Elektra ?

I see that you already have an "up to date" Docker image based on Alpine : 

https://github.com/ElektraInitiative/libelektra/issues/3908

Yet it is for x86_64 but ARM would be nice as well.

Should I make one and submit it to aports ?

Or someone is on it already ?

Regards.

**Comment by markus2330** [comment]
Hi @Kochise :wave: 

Thank you for reaching out! :sparkling_heart: 

There used to be effort for excellent Alpine packages, which looked very modular (nearly every plugin was in its own package) see #1811, but it looks like its maintenance was stopped. It would be great if you can pick this up! :rocket: 

> ARM would be nice as well.

Interesting to hear, I am currently working on a new project which uses Elektra on ARM.

best regards,
Markus

**Comment by Kochise** [comment]
Ok then.

Seems like someone is on it but also it looks rather hard to get it right : 

https://git.alpinelinux.org/aports/log/?qt=grep&q=elektra

Will see what I can do.

**Comment by mpranj** [comment]
Thank you so much for looking into it!

If it helps, you'll find our current packaging CMake config in [`scripts/packaging/package.sh`](https://github.com/ElektraInitiative/libelektra/blob/a778788ce46dab7bda92bda72e8a28850e521473/scripts/packaging/package.sh).
We're using CPack to build our packages: [`scripts/cmake/ElektraPackaging.cmake`](https://github.com/ElektraInitiative/libelektra/blob/a778788ce46dab7bda92bda72e8a28850e521473/scripts/cmake/ElektraPackaging.cmake).

**Comment by Kochise** [comment]
Obviously it's on track https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/30948

**Comment by Kochise** [comment]
Testing the `armv7` artifact from https://gitlab.alpinelinux.org/oliver/aports/-/pipelines

It is looking promising.

There is a strict dependency on `libgit2` which requires `qsort_r` only available starting `musl-1.2.2-r7` :

https://gitlab.alpinelinux.org/alpine/aports/-/commit/bf5bbfdbf780092f387b7abe401fbfceda90c84d

**Comment by markus2330** [comment]
> strict dependency on `libgit2`

Did you get an compile error? This would be an bug, libgit2 actually should be an optional dependency (plugin gitresolver would be excluded and libelektra-merge would have poorer conflict resolving capabilities on arrays).

**Comment by Kochise** [comment]
No compile error, but `libelektra` install only if `libgit2` is present.

**Comment by markus2330** [comment]
> No compile error, but libelektra install only if libgit2 is present.

If you compile Elektra without having libgit2 on the system, it should also work correctly after installation. Which error did occur?

> Could you provide a clear dependency tree for each package ?

It is documented in the individual READMEs. scripts/cmake/ElektraPackaging.cmake has extensive dependency information. How would you like to have it documented?

**Comment by Kochise** [comment]
Hi, sorry for the delay. It's mostly about why `libelektra-merge` have a dependency to `libgit2` : 

```bash
/workdir # grep libgit2 pkg/.control.*/.PKGINFO
pkg/.control.elektra-gitresolver/.PKGINFO:depend = so:libgit2.so.1.3
pkg/.control.libelektra/.PKGINFO:depend = so:libgit2.so.1.3
```

```bash
libelektra-merge.so.0.9.8
	libgit2.so.1.3 => /usr/lib/libgit2.so.1.3 (0x7ff4e6900000)
```

But you said above that "libgit2 actually should be an optional dependency (plugin gitresolver would be excluded and libelektra-merge would have poorer conflict resolving capabilities on arrays)" so I guess it is still a prerequisite and shouldn't be removed.

Can you confirm ?

**Comment by markus2330** [comment]
I don't think of it as a problem if you remove libgit2 as prerequisite. The missing features without libgit2 are unimportant.

**Comment by Kochise** [comment]
Thank you for your help. Maybe `libgit2` can be left in if it doesn't takes too much space. That way we'll also avoid strange and unplanned behaviors if it is absent. Better keep the expectations and requirements satisfied.

**Comment by markus2330** [comment]
Is there any update on the Alpine packages? As you might have noticed, we released Elektra 0.9.9 https://www.libelektra.org/news/0.9.9-release

**Comment by Kochise** [comment]
Hi, yeah, I noticed the update to 0.9.9, thank for your great job :)

I'm on vacation for a week, will see that on my returning back.

**Comment by Kochise** [comment]
No problem, not part of the project using elektra anymore, idk what's the current status of it.
