### ISSUE TITLE
respect INSTALL_LMOD and INSTALL_CMOD

### ISSUE THREAD

**Issue by Kochise** [ElektraInitiative/libelektra#4248]
## Steps to Reproduce the Problem

```bash
sudo apt install cmake git build-essential
sudo apt install cmake-curses-gui
sudo apt install doxygen graphviz
sudo apt install ruby
sudo gem install ronn-ng -v 0.10.1.pre1

sudo apt install swig
sudo apt install lua5.3

git clone https://github.com/ElektraInitiative/libelektra.git
cd libelektra

mkdir build
cd build

cmake ..
ccmake .. # [c] then [g] then [e] to exit

cd ..

sudo cmake --build build -- -j5
sudo cmake --build build --target run_nokdbtests

cd build
sudo make install && sudo ldconfig

cd ..
cd src/bindings/swig/lua/examples

lua example_key.lua 
```

## Expected Result

Lua example to run

## Actual Result

```bash
lua: example_key.lua:1: module 'kdb' not found:
	no field package.preload['kdb']
	no file '/usr/local/share/lua/5.3/kdb.lua'
	no file '/usr/local/share/lua/5.3/kdb/init.lua'
	no file '/usr/local/lib/lua/5.3/kdb.lua'
	no file '/usr/local/lib/lua/5.3/kdb/init.lua'
	no file '/usr/share/lua/5.3/kdb.lua'
	no file '/usr/share/lua/5.3/kdb/init.lua'
	no file './kdb.lua'
	no file './kdb/init.lua'
	no file '/usr/local/lib/lua/5.3/kdb.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.3/kdb.so'
	no file '/usr/lib/lua/5.3/kdb.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './kdb.so'
stack traceback:
	[C]: in function 'require'
	example_key.lua:1: in main chunk
	[C]: in ?
```

Yet the are some `kdb.so` files in : 

```bash
./libelektra/build/src/bindings/swig/lua/kdb.so
/usr/local/lib/lua/5.2/kdb.so
```

There is no `Lua5.2` installed, only `Lua5.3(.3)`

If I try this, I crash the machine : 

```bash
cd libelektra/build/src/bindings/swig/lua
lua ../../../../../src/bindings/swig/lua/examples/example_key.lua
```

## System Information

- Elektra: master
- Operating System:
`Linux 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

## Further Log Files and Output

If I try to compile the swig file by hand, here's what I get : 

```bash
cd libelektra/src/bindings/swig/lua
swig -lua kdb.i
```

```bash
../common.i:51: Error: Unable to find 'kdb.h'
kdb.i:344: Error: Unable to find 'key.hpp'
kdb.i:435: Error: Unable to find 'keyset.hpp'
kdb.i:449: Error: Unable to find 'kdb.hpp'
```

**Comment by markus2330** [comment]
Thank you for reporting this problem!

I think you need to modify TARGET_LUA_CMOD_FOLDER and TARGET_LUA_LMOD_FOLDER accordingly.

See also scripts/packaging/package.sh how this might be done.

We marked them as advanced, so it is not visible by default in ccmake.

**Comment by Kochise** [comment]
Hi, not much info about what shall be put inside TARGET_LUA_CMOD_FOLDER and TARGET_LUA_LMOD_FOLDER environment variables. Google tells you are the only one on Earth using these. Should it be more appropriate to use Lua's own environment variables ?

**Comment by oliv3r** [comment]
In the alpine package, the following values are used
```sh
/workdir # pkg-config --variable=INSTALL_LMOD lua5.3
/usr/share/lua/5.3
/workdir # pkg-config --variable=INSTALL_CMOD lua5.3
/usr/lib/lua/5.3
```

Hope that helps future googlers!

**Comment by markus2330** [comment]
To clarify the task:

TARGET_LUA_CMOD_FOLDER and TARGET_LUA_LMOD_FOLDER should be made internal: they should fetch the information by `pkg-config --variable=INSTALL_LMOD lua` respective `pkg-config --variable=INSTALL_CMOD lua` by default.

@oliv3r does on your system also work `pkg-config --variable=INSTALL_LMOD lua` or is it necessary to add the version postfix? (On Debian `lua` points to the default lua)

**Comment by oliv3r** [comment]
Hey @markus2330 ,

I'm only updating the alpine package; so my system is not completely relevant maybe :p but on alpine this is how it works.

https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/30948

A quick check in docker shows that yes, the version is not needed, but it depends on how you install lua-dev (e.g. if you install lua5.3-dev, you must supply the version)

```
% docker run --rm -it alpine:edge /bin/sh
/ # apk add lua-dev
/ # find / -iname '*.pc'
/usr/lib/pkgconfig/lua.pc
/usr/lib/pkgconfig/lua5.1.pc
/ # pkg-config --variable=INSTALL_LMOD lua
/usr/share/lua/5.1
```
on an arch container, it also woks
```
% docker run --rm -it archlinux:latest /bin/sh
sh-5.1#
pacman -Sy lua pkgconf
pkg-config --variable=INSTALL_LMOD lua
/usr/share/lua/5.4
```
