### ISSUE TITLE
[FEAT] Array index improvement (natural ordering)

### ISSUE THREAD

**Issue by Kochise** [ElektraInitiative/libelektra#4249]
Hi, following https://www.libelektra.org/tutorials/arrays it looks the array indexing is rather "weird", since it is "sorted alphabetically", why not just use "natural ordering" to always get it right, no mater what ?

I'd like to avoid using underscores and/or doing the ordering myself, by hand.

https://github.com/search?l=C&q=natural+ordering&type=Repositories -> https://github.com/sourcefrog/natsort

http://www.naturalordersort.org/
https://rosettacode.org/wiki/Natural_sorting
https://docs.microsoft.com/en-us/windows/win32/intl/handling-sorting-in-your-applications
https://unicode.org/reports/tr10/

Plus it'll be super easier to retrieve the last "index" that way : simply add a `#last` alias instead of : 

`kdb meta-get <ns>:/<key> array`

**Comment by markus2330** [comment]
Thank you for the idea! :sparkling_heart: 

We already had the idea and also implemented it in #3102, seems like the tutorial is not updated. I created #4250. Afaik the underscores still can be added (@kodebach?). But they are not needed anymore, as the escaping of key names automatically adds them.

The idea to have a `#last` is not yet implemented and probably also not so easy to do so. @kodebach any thoughts about that?

If we want to do something like this I would prefer some non-English way like using `-1` for the last index.

**Comment by Kochise** [comment]
Yeah, I've seen that the tutorials are not really up to date, sometimes referring to example "seen previously" that just aren't there.

Btw, I've not found any "cheat sheet" and I'm creating one, are you interested ? Because getting into libelektra is not the easier.

**Comment by markus2330** [comment]
As the main feature is already implemented and `#last` would only work as extension to currently missing tooling I close this issue. Please open new issues for new questions and feature proposals!

@Kochise Btw. I would find it very nice to have cheat sheets. Please create a PR! :rocket:
