### ISSUE TITLE
cmake fails with unexpected error about list_filter

### ISSUE THREAD

**Issue by nikonthethird** [ElektraInitiative/libelektra#425]
I tried to build the SWIG bindings, but did not have SWIG installed.

Instead of providing the correct error message (below), `ccmake` failed with:

    CMake Error at cmake/Modules/LibAddMacros.cmake:307 (MESSAGE):
      LIST_FILTER: missing list variable.
    Call Stack (most recent call first):
      src/bindings/CMakeLists.txt:21 (list_filter)

The relevant contents of `CMakeLists.txt` is:

        if (SWIG_FOUND)
                add_subdirectory (swig)
        else()
                list_filter(BINDINGS regex)
                remove_binding(swig "neither swig2/3 found. Please install swig3.0 and set -DSWIG_EXECUTABLE=")
        endif()

The offending line is `list_filter(BINDINGS regex)`, and the next line sounds like the error that should have been displayed.

My knowledge of cmake is very limited, but to me it sounds like a syntax error in the `CMakeLists.txt`file or something of that sort.

**Comment by nikonthethird** [comment]
It has nothing to do with SWIG. I get the same error message in another location:

    CMake Error at cmake/Modules/LibAddMacros.cmake:307 (MESSAGE):
      LIST_FILTER: missing list variable.

I just did: `mkdir build && cd build && cmake .. -DBINDINGS=ALL -DTOOLS=ALL -DPLUGINS=ALL` and the error appeared (the SWIG one is now gone since I have installed SWIG).

**Comment by nikonthethird** [comment]
After trying to build all of Elektra on a minimal Ubuntu VM, I now have three instances where `cmake` fails:

* In [`src/bindings/CMakeLists.txt`](https://github.com/ElektraInitiative/libelektra/blob/63d811684e803c735ed8085c08e0e48fc9db30fc/src/bindings/CMakeLists.txt#L21)
* In [`src/bindings/gi/CMakeLists.txt`](https://github.com/ElektraInitiative/libelektra/blob/63d811684e803c735ed8085c08e0e48fc9db30fc/src/bindings/gi/CMakeLists.txt#L70)
* In [`src/bindings/glib/CMakeLists.txt`](https://github.com/ElektraInitiative/libelektra/blob/63d811684e803c735ed8085c08e0e48fc9db30fc/src/bindings/glib/CMakeLists.txt#L8)

So it definitely has to do with `list_filter`.

**Comment by markus2330** [comment]
Thank you for reporting! Which cmake version do you have?

Workaround should be to not specify swig bindings where you do not have installed the dependencies for.
