### ISSUE TITLE
[FLOSS T2] update array tutorial

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4250]
for natural sorting (_ are not needed anymore)

https://www.libelektra.org/tutorials/arrays

see also #4249

**Comment by markus2330** [comment]
For 1.0 we should either update or remove. Before 1.0 it is enough to have issues that say that something is outdated/missing.

**Comment by kodebach** [comment]
> For 1.0 we should either update or remove. 

Of course, but... 

> Before 1.0 it is enough to have issues that say that something is outdated/missing.

... since people are still using Elektra before 1.0, we should probably mark outdated stuff inside the docs themselves and not hope they see the related issue.

**Comment by markus2330** [comment]
Ok, then let us add TODO marker? `[Deprecated]` sounds like that the thing the tutorial is about (like arrays) is out-of-date not that there are issues in the tutorial itself.

**Comment by lukashartl** [comment]
We ( @leothetryhard and @lukashartl ) would like to work on this issue.

* Should we go with `TODO` or `DEPRECATED`?
* What exactly do you mean with marker? Is this something out of Doxygen, or just a prefix in the header?
* Should we work through all the docs or just the mentioned array tutorial?

**Comment by markus2330** [comment]
If you want to work on the issue forget about TODO or DEPRECATED :wink: This was only for the case if nobody wants to update the tutorial.

The proper fix is to update the tutorial to the new array syntax (i.e. without leading underscores) and also explain that these underscores get added for arrays. In doc/KEYNAMES.md you can read about how the syntax currently is.

**Comment by markus2330** [comment]
> Should we work through all the docs or just the mentioned array tutorial?

You probably will not spot what is outdated. Afaik the array tutorial is the only one that has a known problem.

But of course: if you go through some docu and spot a problem, please report.
