### ISSUE TITLE
no new packages

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4255]
I wanted to test mount-java but in `deb https://debs.libelektra.org/bullseye/ bullseye-unstable main` there are no new packages. Maybe the build server did not even pass?

**Comment by markus2330** [comment]
@kodebach: that you check if it was build and possibly fix errors on master

@robaerd: can you maybe spot the problem and fix maybe together with @lukashartl?

**Comment by kodebach** [comment]
There is a basic test for `mount-java` 

https://github.com/ElektraInitiative/libelektra/blob/19dba1b0b3ff194e212cf699e09de590288fc250/tests/shell/external/mount_java.sh#L1-L17

that was executed successfully in at least [this master build](https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/master/686/pipeline/858/#step-998-log-225) (line 225 in the linked log).

**Comment by lukashartl** [comment]
Here is what I found so far:

According to the pipeline log, the package has been built successfully. (Stage `buildPackage/debian/bullseye`)
It has also been uploaded to the Debian repository pool and the metadata for `bullseye-unstable` was also updated (we can see this by taking a look into the timestamp of the files on the server).
But when I list all packages from the repository, I still get the old version.
If we look inside the downloaded package metadata, we can see that there are two version inside
the `bullseye-unstable`, e.g. for package `libelektra5-all`:

```
Package: libelektra5-all
Version: 0.9.8-5.5881
Package: libelektra5-all
Version: 0.9.8-1.6911
```

If you look at the version number, you can see that the newest build has actually a lower number than the older stable version: `0.9.8-1.6911 < 0.9.8-5.5881`.
The opposite should be the case.

The deb repository (pool and metadata) seems to be correct, the upload mechanisms in the pipeline are also working accordingly.
So it seems that the method of calculating the version seems to be incorrect.

**Comment by markus2330** [comment]
Maybe we can simply reset the counter with every release? As we want to do a release soon anyway, the problem will be fixed that way?

**Comment by kodebach** [comment]
To me it seems the problem is that somebody erroneously published the version `0.9.8-5.5881`. This version was published **before** `0.9.8-1` which AFAICT should be the latest release version. We have currently set the `SO_VERSION` to 5, maybe at some point during the release process this version is used instead of the Debian version?

https://github.com/ElektraInitiative/libelektra/blob/master/CMakeLists.txt#L97

**Comment by robaerd** [comment]
The `SO_VERSION` has no influence on the revision version of the packages itself. 

The packages with the version `0.9.8-5.5881` were published on 04.10.2021 at 00:07, shortly before the actual release. So this most likely was published during the build job for the commits that incremented the version numbers without incrementing the `debian/changelog` version. The `debian/changelog` is also populated automatically, so case distinction will be necessary that check if the current version even exists inside the `debian/changelog`.

I think the easiest temporary fix until the release would be to simply add a new `debian/changelog` entry with the revision version `5`. This way  new master built packages will get a version `> 0.9.8-5.5881`

**Comment by markus2330** [comment]
I like the solution with debchange!

**Comment by markus2330** [comment]
Packages have arrived again!

@mpranj maybe we find a way to reset the build counter every release, so that the first master build after publishing 0.9.9 has the version 0.9.9-1.1

**Comment by mpranj** [comment]
> maybe we find a way to reset the build counter every release, so that the first master build after publishing 0.9.9 has the version 0.9.9-1.1

The last part of the package version is derived from the Jenkins `$BUILD_NUMBER` environment variable. With the current naming scheme you can correlate the built package version with the Jenkins build easily.
