### ISSUE TITLE
introduce proper logging system

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#426]
See doc/decisions/logging.md

elektra logs to stdout (compiled with VERBOSE)
should be stderr

**Comment by markus2330** [comment]
requirements: should be completely compiled away by default, only useful for debugging

**Comment by markus2330** [comment]
an assert framework would be useful, too

**Comment by Namoshek** [comment]
Why not provide a way to configure the logger of a configuration library (e.g. target for output)?
Of course this would only work if the logging has not been compiled out of the binary, i.e. ELEKTRA_LOGGING is ON.

From the current description it is unclear to me how severity can be set for individual writes to the log.

**Comment by markus2330** [comment]
The severity can be set by using a different macro, e.g. `ELEKTRA_LOG_DEBUG`.

Then one can filter by modifying the source within `log.c`, e.g. adding `if (severity == ELEKTRA_LOG_DEBUG)` ...

Providing run-time configuration makes the logger much more complicated (except we do some hack with global variables and mutex which would make the logger very slow), we should use an existing logger if we really need this. Something like that could be still added to `log.c`, but why would someone need it? The only thing that might be generally useful (and does not work with plugins) is information about which `ksLookup` an specific application issued. Maybe @KurtMi has an idea for that.

**Comment by Namoshek** [comment]
Ah, now I got the severity point. Makes totally sense to have it like that. :+1: 

About the configuration, I agree that more logic increases the risk of having errors and decreases performance. After thinking about it again, it would also be some sort of circular dependency if we have the logger use the core and the core use the logger, which could be dangerous. Thus compile-time configuration seems not the worst idea. Logging to stderr could still be redirected into files.

In my opinion filtering logs should be possible through setting a severity level in CMake though. I don't like touching source files for such things. Shouldn't be a big deal to use an enum there.

**Comment by markus2330** [comment]
Yes, the bootstrapping of logger is one of the main issues when a logger has run-time configuration (e.g. how to report that the logger config contains errors?).

Enums in CMake unfortunately is a strange thing and only usable in the GUI (not in curses). Maybe we can keep the config as macros directly in `log.c` (similar to what dwm does). And I think most people will rather want to filter for source files and modules, and rather seldom for severity. But maybe I have wrong assumptions here, how do you filter loggers?

**Comment by Namoshek** [comment]
Depends on the use case and the software, but often I run loggers with the lowest severity (DEBUG or TRACE) during development and with WARNING or ERROR in production. As the latter usually introduces new use cases, the information can be useful to find (new) errors in code. Most programs I know let their loggers run in production too, so from my perspective turning logging off entirely is the rare use case here...

**Comment by markus2330** [comment]
Thank you for sharing. In particular it would be interesting which `printf` and so on you (question is directed  to everyone) used in Elektra code up to now. Server code is quite different. In cppcms you can use the cppcms logger.

The severity levels are quite limited in the current proposal, maybe we should make `INFO` as default to have also one level higher than default which is not a warning. Adding too many levels is also not a good choice, though. It makes the decision which level arbitrary.

**Comment by markus2330** [comment]
I added a first quick draft here: #873 

Please give feedback what else you would need to be able to use it productively.

**Comment by markus2330** [comment]
A even simpler version is now in master: I did not add the modules-enum (adds centralization without much benefits, strcmp on file names allows you to do nearly the same).

Assertions are still in the old version, but please do not let this stop you from using it.

Please try it out and report experiences:
1. Make sure ENABLE_LOGGER is turned ON
2. include <kdblogger.h>
3. Add ELEKTRA_LOG statements (see doc/CODING.md)
4. Hack src/libs/elektra/log.c so that they are actually printed (adapt level filter, line 85, and filter by file, line 106)

**Comment by markus2330** [comment]
The assertion macro is now also updated, please try it out and report experiences:
1. Make sure ENABLE_DEBUG is turned ON
2.) include `<kdbassert.h>`
3. Use ELEKTRA_ASSERT statements (see doc/CODING.md)

If you also have the logger turned on, the logger will be used for printing assertions (before failing), otherwise the minimal implementation of src/libs/elektra/nolog.c will be used.

**Comment by petermax2** [comment]
clang on Travis reports build warnings:

    /Users/travis/build/ElektraInitiative/libelektra/src/include/kdbassert.h:34:120: warning: token pasting of ',' and __VA_ARGS__ is a GNU extension [-Wgnu-zero-variadic-macro-arguments]
    #define ELEKTRA_ASSERT(EXPR, ...) ((EXPR)) ? (void)(0) : elektraAbort (STRINGIFY (EXPR), __func__, __FILE__, __LINE__, ##__VA_ARGS__)
                                                                                                                           ^
    /Users/travis/build/ElektraInitiative/libelektra/src/include/kdbassert.h:34:120: warning: token pasting of ',' and __VA_ARGS__ is a GNU extension [-Wgnu-zero-variadic-macro-arguments]
    /Users/travis/build/ElektraInitiative/libelektra/src/include/kdbassert.h:34:120: warning: token pasting of ',' and __VA_ARGS__ is a GNU extension [-Wgnu-zero-variadic-macro-arguments]

**Comment by markus2330** [comment]
Everything should work now! Thanks for your participation in the discussion!
