### ISSUE TITLE
mount_java: needs process plugin?

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#4264]
@kodebach is it possible that the `mount_java` test also relies on the experimental process plugin?

https://github.com/ElektraInitiative/libelektra/blob/631f6492edb13bcc57fa2fa92d4bc04bd93aad63/tests/shell/external/CMakeLists.txt#L42-L46

I get the following when running the release tests:
```
Running check_external_mount_java


ELEKTRA CHECK MOUNT JAVA

The command /home/jenkins/workspace/system/bin/kdb-full mount terminated unsuccessfully with the info:
No plugin that provides process could be found
Please report the issue at https://issues.libelektra.org/
error: mount-java not successful
Mountpoint user:/test/mountjava does not exist
check_external_mount_java RESULTS: 1 test(s) done 1 error(s).
error: check_external_mount_java
``` 
Or is the test exclusion somehow failing for kdb FULL?

**Comment by kodebach** [comment]
Yes, it definitely needs the `process` plugin as well. Although I think, it also doesn't work with `kdb-full`. But in any case, there should be a CMake dependency on `process`. I'll create a PR.

**Comment by mpranj** [comment]
Thank you for working on it @kodebach!

Should we explicitly add this plugin or mark is as non-experimental for the CM LVA people? Or do they not need this in the release?

**Comment by kodebach** [comment]
Good point, I added a commit to the PR.
