### ISSUE TITLE
[CM T0] Remove internal iterator use from SWIG bindings

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#4279]
The SWIG bindings (Lua, Ruby, Python) are based on the C++ binding, so most of the migration from internal to external iterators is covered by #4280. However, there are still some uses of the internal iterator APIs (mostly via their C++ variants) within the SWIG bindings (e.g. in the mapping files `kdb.i`). The full list of functions in the internal iterator API can be found in #3171.

**Comment by markus2330** [comment]
Is the Python binding already done?

**Comment by kodebach** [comment]
It is listed as done in #3171, but I didn't check.

**Comment by markus2330** [comment]
Can you please check for Python and Ruby? We cannot give a task if probably nothing is to do :wink:

**Comment by kodebach** [comment]
I updated, the issue title and description. I combined all the SWIG bindings into one issue, because there seems to be very minimal use of the iterator APIs.
