### ISSUE TITLE
qtgui: keys with wrong content

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#428]
Hello,

With the qtgui version in master I get an error when I try to sync:
```
Error (#84) occurred!
Description: Read only plugin, kdbSet not supported
Ingroup: kdb
Module: 
At: /home/markus/Projekte/Elektra/current/src/libs/elektra/plugin.c:381
Reason: the key system/elektra/version/constants/KDB_VERSION (expected system/elektra/version) was modified to 0.8.14 (expected Below are version information of the Elektra Library you are currently using)
Mountpoint: system/elektra/version
Configfile: 
```

`system/elektra/version` seems to have wrong content (and seems to cause the problem). When I hover it or double click on it, it shows that its value is "1", but it should be "Below are version information of the Elektra Library you are currently using". Using the `kdb` tool I do not have these issues. It does not matter if additional mountpoints are present or not. (There are many other keys, though)

Any ideas?

And can you please check if you are ok with d3f6204dbd8ec97f731989ed7ed63eab0d89129c, it implements #302

thank you, best regards

**Comment by 0003088** [comment]
I do not have any idea about this problem atm, but I will find some time after christmas to look into it. Regarding the commit, in general I have no problem with changes/enhancements, as long as they do not introduce regressions or new bugs.
best regards

**Comment by markus2330** [comment]
This would be quite important to fix for next release, it might be #528

**Comment by markus2330** [comment]
@0003088 any news? It would be great to get a PR today. Something minimal which only fixes these grave bugs would be enough!

**Comment by markus2330** [comment]
Thanks, works perfectly, even in the case of conflicts! Great work! I hope to see some improvments in the next release, too.
