### ISSUE TITLE
Remove internal iterators from C++ API

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#4280]
The internal iterator API (listed in #3171) will be removed from the C API. Corresponding functions need to removed from the C++ API and direct all uses within C++ code need to be replaced appropriately.

- [ ] Remove all functions (`rewind`, `next`, `setCursor`, etc.) that map to the internal iterators API (`keyRewind`, `keyNext`, etc.)
- [ ] Replace all usage of these functions and all direct uses of the C API for the internal iterators with alternatives

**Note:** Fully fixing this issue may require fixing #4279 as well. Some of the SWIG bindings refer to functions that will be removed with this issue.

**Comment by markus2330** [comment]
Can be implemented as small project or big T3 work.

**Comment by kodebach** [comment]
@markus2330 Please check whether the CM points need to adjusted, since this issue may be blocked by #4279.

**Comment by flo91** [comment]
Hello,
@Milangs and I want to work on this issue for our CM-project.
I think it's convenient that we additionally do #4279 and #4281 for the teamwork, because the three issues are related.

**Comment by markus2330** [comment]
Remove internal iterators is an excellent job for project and teamwork. It is probably best to start replacing it in bindings (Ruby etc.), and then C++ iterator to use the external iterator instead; and finally remove the internal iterator from C (rewriting code with the external iterator instead).

**Comment by Milangs** [comment]
_Rationale for the change:_ When the client (i.e. the programmer) controls of the iteration, the iterator is called external iterator. Otherwise, when the iterator controls the iteration, it is called internal iterator. Due to the fact that external iterators are more flexible the internal iterators will be removed completely from Elektra.

**Comment by Milangs** [comment]
Everything finished except following issue: https://github.com/ElektraInitiative/libelektra/pull/4354#discussion_r884688010

**Comment by markus2330** [comment]
@flo91 could this one more project? Or simply as normal issue?

**Comment by flo91** [comment]
> @flo91 could this one more project? Or simply as normal issue?

For a project, the remaining work probably is a bit too small.
I'd suggest to offer it as a big normal issue.
