### ISSUE TITLE
[CM T0] Remove usage of internal iterators API from plugins

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#4281]
Many plugins still use the internal iterators API. In particular, `ksRewind`/`ksNext` as well as `ksGetCursor`/`ksSetCursor` are very common.

The common pattern:
```c
elektraCursor cursor = ksGetCursor (ks);
ksRewind (ks);

Key * cur;
while ((cur = ksNext (returned)) != NULL)
{
    // [loop body]
}

ksSetCursor (ks, cursor);
```

Should be replaced with a `for` loop using an external iterator:

```c
for (elektraCursor it = 0; it < ksGetSize (ks); ++it)
{
    Key * cur = ksAtCursor (ks, it);
    // [loop body]
}
```

Other uses of the internal iterator API (see #3171 for list) should be replaced appropriately. Additionally, if extra `KeySet`s (e.g. via `ksDup`) were used purely to avoid contamination of the internal iterator, these extra `KeySet`s should be removed as well.

**Comment by kodebach** [comment]
Such things are always easiest to answer, by looking at the source for `ksAtCursor`:

https://github.com/ElektraInitiative/libelektra/blob/eac1c6a74cb75bb84ebfae2247b3cc531259ded8/src/libs/elektra/keyset.c#L1801-L1823

Here we see two things: 1) the docs and the source code agree, when `NULL` is returned 2) as long as we actually pass a valid `KeySet *` pointer and the position isn't out of range, we will not get `NULL`.

Additionally we can look at `ksGetSize`:

https://github.com/ElektraInitiative/libelektra/blob/eac1c6a74cb75bb84ebfae2247b3cc531259ded8/src/libs/elektra/keyset.c#L725-L740

Together this means, that the very basic and intuitive `for`-loop

```c
KeySet * ks;
for (elektraCursor it = 0; it < ksGetSize(ks); ++it)
{
    Key * cur = ksAtCursor (ks, it);
    // loop body ...
}
```

will always work. If `ks == NULL` the loop won't be entered, because `ksGetSize (NULL) == -1`. Because we check against `ksGetSize`, the value of `it` will also never be out of range.

Note, however, that this only works if we actually call `ksGetSize (ks)` within the `for`-loop header. If we call it only once and save it in a variable, the code will only work, if the contents of `ks` aren't modified within the loop. So for a `const KeySet *` storing the size in a local variable _should_ be fine.

But I'd say always use the snippet above. It is the safest option and the compiler will probably optimize away the repeated `ksGetSize` calls, if it knows it's safe.

**Comment by flo91** [comment]
Thank you for the detailed explanation!
So I understood most things correctly.
The only thing I wasn't sure about was if `ks->array[pos]`, which gets returned by `ksAtCursor()`, can contain `NULL`.
But if that's not the case, the loop you mentioned should be fine!
