### ISSUE TITLE
[FLOSS H1] Repo file missing for Fedora 35

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#4287]
For Fedora 33 and Fedora 34 we have `.repo` files that can be used with `dnf config-manager --add-repo`.

- https://rpms.libelektra.org/fedora-33/libelektra.repo
- https://rpms.libelektra.org/fedora-34/libelektra.repo

For Fedora 35 (and `fedora-35-unstable`) this file is missing. You can just use `--add-repo https://rpms.libelektra.org/fedora-35/`, but then you don't automatically get the extra metadata. I'm not entirely sure this is the reason, but with this workaround the GPG checks fail and you need to use e.g. `dnf install --nogpgcheck elektra-bin`

**Comment by Eiskasten** [comment]
I am able to fetch it for Fedora 35 with `curl -vL curl -vL https://rpms.libelektra.org/fedora-35/libelektra.repo` and even for Fedora 36: `curl -vL https://rpms.libelektra.org/fedora-36/libelektra.repo`. Same applies for Fedora 35 Unstable but I do not think that's important anymore. It seems to be already resolved.
