### ISSUE TITLE
qtgui: bookmark feature

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#429]
In the kdb utility we will implement a bookmark-like feature, see #302

What about displaying the bookmarks in qtgui, too? Is it possible to navigate the left bar to a specific key or is there a limitation because of the "TreeView"?

Then we should use a common path, and not a specific one for the kdb-tool only.

**Comment by 0003088** [comment]
I'm not 100% sure if I understand you correctly here, but if you want that the view scrolls to a bookmarked key automatically I'm pretty sure that this won't work with the hacked TreeView, I tried something similar when implementing the search feature, it's just not possible to select a key any other way except clicking on it.

**Comment by markus2330** [comment]
Yeah, I was afraid so. Nevertheless, thanks for the quick response.

So I will keep the bookmarks private to kdb.
