### ISSUE TITLE
Arch package: unnecessary deps

### ISSUE THREAD

**Issue by Eiskasten** [ElektraInitiative/libelektra#4302]
## Steps to Reproduce the Problem

Using the package from the Arch User Repository throws an compilation error as of now. This can be reproduced with
```sh
git clone https://aur.archlinux.org/elektra.git
cd elektra
makepkg
```

## Expected Result

A package in the directory where `makepkg` was called.

## Actual Result

A compilation error:
```
[ 27%] Building CXX object src/tools/kdb/CMakeFiles/kdb-objects.dir/command.cpp.o
/home/richi/.cache/yay/elektra/src/libelektra-0.9.3/src/tools/kdb/cmdline.cpp: In constructor 'Cmdline::Cmdline(int, char**, Command*)':
/home/richi/.cache/yay/elektra/src/libelektra-0.9.3/src/tools/kdb/cmdline.cpp:39:99: error: 'numeric_limits' was not declared in this scope
   39 |   debug (), force (), load (), humanReadable (), help (), interactive (), minDepth (0), maxDepth (numeric_limits<int>::max ()),
      |                                                                                                   ^~~~~~~~~~~~~~
/home/richi/.cache/yay/elektra/src/libelektra-0.9.3/src/tools/kdb/cmdline.cpp:39:114: error: expected primary-expression before 'int'
   39 |   debug (), force (), load (), humanReadable (), help (), interactive (), minDepth (0), maxDepth (numeric_limits<int>::max ()),
      |                                                                                                                  ^~~
/home/richi/.cache/yay/elektra/src/libelektra-0.9.3/src/tools/kdb/cmdline.cpp:429:59: error: expected primary-expression before 'int'
  429 |                                 maxDepth = numeric_limits<int>::max ();
      |
```

## System Information

- Elektra: 0.9.3
- Operating System: Arch Linux

## Further Information

The package is flagged out-of-date in the Arch User Repository.

**Comment by kodebach** [comment]
I have now assigned this issue `1p`. This applies, if you just make the packages work, by updating the versions. If you also fix the warnings (Note: not all of them can be fixed), and maybe rework the package (e.g separate packages for docs, experimental plugins, etc.) more points would be awarded. For some ideas, on how the package could be split look at the Debian/Fedora packages.

**Comment by Eiskasten** [comment]
Thank you. I think that the first option is the best one. This would also prevent a failure of a plugin build which does not require any experimental plugins which might not build or work. However, providing binaries would be the last option to my opinion as the AUR is meant to be source based as far as possible.

As for now, the fixed package versions can be found at https://aur.archlinux.org/packages/libelektra and https://aur.archlinux.org/packages/libelektra-docs.

**Comment by Eiskasten** [comment]
It is possible and it is already done this way. The web interfaces just generates separate pages for each package which results into multiple links.

Thank you for mention them, they are removed now.

I wonder how a PR for this issue should look like since the PKGBUILD is committed in the AUR and I prefer not committing it here since it would violate the single source of truth principle.

**Comment by kodebach** [comment]
> I got points deducted because of this.

I think it's just weird formatting in the feedback. The deduction was because of the missing PR for #4001 (you and @bhampl are assigned to this issue).

**Comment by markus2330** [comment]
Yes, it was only confusing because of the formatting. The contrary is true: the group got plus points because of this excellent package update. Great that you found out how to split the package.

I wonder why it is ../LICENSE.md for one package and **../**../LICENSE.md for the other package?

The whole "optdepends" can be removed, the python2 bindings+plugins are already removed, we now have only python3 bindings+plugins. (Only the deprecated pythongen remained using python2 but this is not worth packaging. We will remove it before 1.0, see #2987)

**Comment by Eiskasten** [comment]
I have bumped the version to 0.9.14 and removed the optional dependencies. I think this can be closed.

**Comment by markus2330** [comment]
@Eiskasten Thank you!
