### ISSUE TITLE
[CM T0] Correct the behavior for lineendings plugin

### ISSUE THREAD

**Issue by Milangs** [ElektraInitiative/libelektra#4306]
1. lineendings plugin should run the validation during ...Get() and ...Set().
2. If a validation problem occurs during ...Set(), the plugin should set an error and return -1
3. If a validation problem occurs during ...Get(), the plugin should add a warning and continue validation (finally return 0)
4. lineendings plugin need to have the `placements: pregetstorage` and `postgetstorage` in their metadata. Otherwise ...Get()/...Set() won't be called.

This issue is related to #4059.

**Comment by flo91** [comment]
As mentioned in the issue #4059, the behaviour was already changed in the range-plugin.
In the scope of my FLOSS project from last semester, I looked at that changes and the error/warning handling in general, so I've already some experience with the topic.

Therefore this issue should be well suited for our Teamwork.
