### ISSUE TITLE
[CM T1] Improve docs for mounting of spec

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#4308]
It seems that our current documentation fails to explain the possible issues with mounting a spec from `$PWD`.

```sh
# not good for applications
kdb mount $PWD/my-spec.ini spec:/myapp ni
```

The example above works, but has a problem. Using an absolute path (`$PWD` is always absolute), means Elektra will read/write this file directly. If `$PWD` is the install directory of the application this would be totally fine. But if this is done during installation and `$PWD` is the source directory, the source specification could be modified via `kdb set spec:/myapp/foo bar`. This is not good, because (advanced) users might want to adapt the specification that was originally installed with the application.

The best alternative would be:

```sh
kdb mount myapp-spec.ini spec:/myapp ni
kdb import spec:/myapp ni $PWD/my-spec.ini
```

Because we gave a relative path (not starting with `/`) to Elektra will use a file within the spec directory (`/usr/share/elektra/specification` by default). (*) The `kdb import` command just tells Elektra to load the file `$PWD/my-spec.ini` with the `ni` plugin and write it into `spec:/myapp`. Using a separate `kdb import` also means we could use a different storage plugin for `mount` than what `$PWD/my-spec.ini` uses.

Another alternative is copying the file manually:
```sh
kdb mount myapp-spec.ini spec:/myapp ni
cp $PWD/my-spec.ini $(kdb file spec:/myapp-spec.ini)
```

This works like the previous snippet, except that we directly modify the spec file without going through Elektra. For very big specifications this might be faster, but we get no validation that the file is actually readable and `$PWD/my-spec.ini` has to be readable by the storage plugin used with `kdb mount`.

Finally, in some cases you may want to control where the mounted spec file is stored. In those cases using an absolute path is fine:

```sh
kdb mount /etc/myapp-spec.ini spec:/myapp ni
kdb import spec:/myapp ni $PWD/my-spec.ini

# OR

kdb mount /etc/myapp-spec.ini spec:/myapp ni
cp $PWD/my-spec.ini $(kdb file spec:/myapp-spec.ini)
```

---

(*) Technically, this depends on the resolver being used, but this is the default.

**Comment by flo91** [comment]
In https://www.libelektra.org/tutorials/writing-a-specification-for-your-configuration in Step 1 the command
``sudo kdb mount `pwd`/spec.ni spec:/sw/org/app/\#0/current ni`` is given.
While this is ok for defining the specification via `kdb` in the first place, it should be mentioned that this approach is not recommended for using the specification for installed applications.
Instead, the explanation you gave in your posting should be included in the tutorial.
I'd like to do this for the CM-T1-assignment.
