### ISSUE TITLE
C++ vaarg KeySet constructor error-prone

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#431]
@nikonthethird @manuelm 

`KeySet(Key("user", KEY_END), KS_END);` compiles without any warning because `Key` implicitly casts to bool which implicitly converts to size_t.

A way to fix it is to change the first argument to a new `Alloc` class, which only has an explicit constructor which disallows implicit conversions.

For the `vaarg` constructor this is quite forward to implement (only 3 clients of the constructor), but the `...` (ellipse) constructor is used heavily and the change would have quite an impact. Thus I wanted to ask in advance if you have any objections (especially in respect to effects on bindings) or any other better ideas.

Thanks!

**Comment by markus2330** [comment]
For the easy case see: 2442736f297a59e9c6f0bbdd2a2c150d4b4ce63a

**Comment by manuelm** [comment]
So why do we want to fix something which isn't broken? The constructor is clearly used in a wrong way.

**Comment by manuelm** [comment]
One possibility might be overloading the KeySet constructors with other datatypes and making the `KS(bool, ...)` constructor stop the compilation. We would at least need `KS(int, ...)` as well. But I'm still against fixing this as this approach might have other side effects (or even won't work at all - just did a rough test in a sample file).

**Comment by markus2330** [comment]
@manuelm: The fix is about API usability, you can use it a completely wrong way very easily, that is not a good sign.

Adding a KeySet(bool,...) constructor is not so easy. To let it fail you somehow need SFINAE (to not fail in the good cases), thus templates are involved.
Something like:
```
template <typename T>
inline KeySet::KeySet (T alloc, ...)
{
static_assert(std::is_same<bool, T>::value, "You tried to pass a boolean as first argument");
...
}
```
seems for me to be much more complicated? Wouldn't it also make the bindings more complicated?

**Comment by manuelm** [comment]
This is still not a bug for me. Yes, the API is error prone. The whole varargs API is. I've said this multiple times. You can easily make your code crash by passing any unexpected datatype to the Key constructor.

Instead of fiddling with the vaargs API we should rather think of adding a more modern C++ API and make the vaargs API a C-API only.

And yes, every fix will make bindings more complicated.

**Comment by manuelm** [comment]
What about something like that: https://gist.github.com/manuelm/08d27f271c8102eaf7ac?

**Comment by markus2330** [comment]
@manuelm Thats a nice minimal solution, thanks. We only need some `#ifdef GCC` around it (similar to `ELEKTRA_SENTINEL`). Can you create a PR?

About your concern to create a more modern C++ API, what exactly do you have in mind? Did you already look at `keysetget.hpp`? (Allows you to construct any type from data in a keyset)

For KeySet construction we could create a fluent API with perfect forwarding functions that do the construction similar to:
```
KeySet(4).addKey("user/abc").addValue("cdef")
               .addKey("user/def")
```

I am not sure if this is really better (and not only just different), the best way would be still to write a configuration file and generate code from it (if a hardcoded KeySet is needed in the program at all).

**Comment by manuelm** [comment]
I'm lacking time. Can you do the PR/creating the patch for me please? You're more familiar with the compiler conditionals used already anyway.

**Comment by markus2330** [comment]
Is not so urgent, I will keep the ticket open.
