### ISSUE TITLE
Elektra Packaging

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#433]
Hello @sl1pkn07

Thanks for maintaining the AUR package, we are very grateful for it.

Some comments about the package as pasted here http://sl1pkn07.wtf/paste/view/325631b6:

```
pkgname=elektra-git
```

Ideally, there would be more than one binary package. Elektra is very modular and its core only has dependencies to gcc and cmake. The plugins have all sorts of dependencies, thus it would be good if the user can install the plugins separately.

```
arch=('i686' 'x86_64')
```
It should work on every architecture.

```
url='https://github.com/ElektraInitiative/libelektra'
```

The canonical link is http://libelektra.org, currently it redirects to github, but that might change if we decide not to use github. So we would prefer if everyone uses the canonical link.

```
depends=('qt5-declarative'
         'yajl'
         'augeas'
         'discount'
         )
```

I do not know the differences between depends and makedepends, but some development packages of the packages above are also needed for compilation (maybe with `qt5-declarative` as exception).

```
makedepends=('git'
             'cmake'
             'boost'
             'docbook-xsl'
             'texlive-latexextra'
             'texlive-fontsextra'
             'tcl'
             'swig'
             'python'
             'python2-cheetah'
             'lua52'
             'gobject-introspection'
             'ruby-ronn'
             )
```

I suppose `git` is a dependency the package needs for doing a git-clone?
`docbook-xsl` is not needed anymore, `tcl` was never needed (the tcl plugin only has supports a configuration file with a syntax like tcl, it does not use tcl).
The `texlive*` are only needed if you want to build the pdf of the API (doxygen is prerequisite for this)

The other dependencies look ok.

```
optdepends=('lua52: Lua bindings'
            'python: Python 3 bindings'
            'python2: Python 2 bindings'
            'gobject-introspection: GI bindings'
            )
```

Again, I do not know the difference between optdepends and makedepends, but why are these dependencies duplicated? Actually, every dependency except `gcc` and `cmake` is optional.

Potentially missing are: `doxygen` and `graphviz` for building API doc, `libxml2` for xmltools plugins, `libdbus` for dbus plugin, `libaugeas` for augeas plugin, `libsystemd-journal-dev` for the journald plugin.
 
```
build() {
  cd build
  cmake ../elektra \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DENABLE_TESTING=ON \
    -DBUILD_TESTING=OFF \
    -DBUILD_SHARED=ON \
    -DBUILD_STATIC=OFF \
    -DBUILD_FULL=ON \
    -DTOOLS=ALL \
    -DPLUGINS=ALL \
    -DBINDINGS=ALL \
    -DLUA_INCLUDE_DIR=/usr/include/lua5.2
```

Why are you using `Release`? This implies that you do not have any debug information for crashes. Is this standard for Arch?

Otherwise, its nice that you build everything (all tools, plugins and bindings)!

@mpranj @petermax2 if I remember correctly you are the arch users? Can you take a look at it, too?

Thanks for your efforts!

best regards

**Comment by sl1pkn07** [comment]
>Ideally, there would be more than one binary package. Elektra is very modular and its core only has dependencies to gcc and cmake. The plugins have all sorts of dependencies, thus it would be good if the user can install the plugins separately.

can make a split pkgbuild (one PKGBUILD for build several packages), but i think can use optdepend for this

>It should work on every architecture.

yes, but arch, by default, only support i686 and x86_64 architectures

>The canonical link is http://libelektra.org, currently it redirects to github, but that might change if we decide not to use github. So we would prefer if everyone uses the canonical link.

ok

>I do not know the differences between depends and makedepends, but some development packages of the packages above are also needed for compilation (maybe with qt5-declarative as exception).

in arch, the includes (commonly named '-dev' packages on other distribution) they are included in the packages

a little explanation of diferences between makedepends, depends,optdepends:

makedepends=(): is a dependency only neded when buld the package. when finish, can uninstall it
depends=(): is a dependecy need for run the main programs/libs. usually, the dependencies of plugins/bindings is need set on optdepends=()
optdepends=(): is a dependency for use one of the components (usually plugins) of the build, if the main process can run witout it. for example. libelektra can run without python, but if need use the plugin/binding, then need install it.

>I suppose git is a dependency the package needs for doing a git-clone?

'git'  is for like you say. only need for download the sources, and only when build, therefore it is in makedepends=() (is managed internally by makepkg. can handle between master, any branch, any tag or a commit in particular)

>docbook-xsl is not needed anymore

'docbook-xsl' is not used to build the html documentation?

>The texlive* are only needed if you want to build the pdf of the API (doxygen is prerequisite for this)

same question as docbook-xsl

>tcl was never needed (the tcl plugin only has supports a configuration file with a syntax like tcl, it does not use tcl).

ok, then can move to makedepend (only use for build (searched by CMakeLists.txt) but not for run) . see http://sl1pkn07.wtf/paste/view/e4c210e4#L133

>Again, I do not know the difference between optdepends and makedepends, but why are these dependencies duplicated? Actually, every dependency except gcc and cmake is optional.

all packages in optdepends need set again on makedepends. the only exception is when that package is not need in build, but if is installed is used by a component

in arch for build any AUR package need install (mandatory) the group 'base-devel'. https://www.archlinux.org/groups/x86_64/base-devel/

>Potentially missing are: doxygen and graphviz for building API doc, libxml2 for xmltools plugins, libdbus for dbus plugin, libaugeas for augeas plugin, libsystemd-journal-dev for the journald plugin.

some of these packages is pulled by other dependencies, no need set again. libaugeras is included in the package augeras (is the same package in arch). libdbus in the dbus (again), and libsystemd-journal-dev...., see https://github.com/ElektraInitiative/libelektra/issues/264#issuecomment-155815406

>Why are you using Release? This implies that you do not have any debug information for crashes. Is this standard for Arch?

yes, is a standard (sad, for exaple in my case with KDE/Qt :( ). if the user need the debug then need change Release to Debug and add in the PKGBUILD 'options=('!strip' 'debug')'

>Otherwise, its nice that you build everything (all tools, plugins and bindings)!

nope XD, misisng java plugin/binding. one of the component is missing in arch (by common way) (jna.jar)

>Thanks for your efforts!

tnx bro!


On the other hand, I observer for example this:

           'python2-cheetah'
           'ruby-ronn'

no need any other python/lua/whatever module? (yes. i forget add python-cheetah (python3) on the PKGBUILD)

greetings

**Comment by sl1pkn07** [comment]
ops. i close the issue :S

**Comment by sl1pkn07** [comment]
>>docbook-xsl is not needed anymore

>'docbook-xsl' is not used to build the html documentation?

>>The texlive* are only needed if you want to build the pdf of the API (doxygen is prerequisite for this)

>same question as docbook-xsl

ok. I tried uninstall dockbooc-xsl and texlive-(latexextra,fontsextra) and the documentation (html) is builded without aparently problems. then I'll remove it

**Comment by markus2330** [comment]
Hello,

Luckily we started a new issue, it seems to be a longer discussion ;)

Gustavo Alvarez wrote:
> can make a split pkgbuild (one PKGBUILD for build several packages), but i
> think can use optdepend for this

Seems to be a good option.

> >It should work on every architecture.
>
> yes, but arch, by default, only support i686 and x86_64 architectures

Obviously, you are more experienced in packaging and in the end every 
packaging decision is yours. I do not have experience with arch linux not to 
speak with packaging for it. I only said what I found suspicious. If non-
i686/x86_64 do not matter for arch linux, then its ok ;)

> >docbook-xsl is not needed anymore
> 
> 'docbook-xsl' is not used to build the html documentation?

No, the html documentation is now build with doxygen.

The man pages are build with ruby-ronn.

Both are optional, but highly recommended.

docbook-xsl is not needed in any case.

> >The texlive* are only needed if you want to build the pdf of the API
> >(doxygen is prerequisite for this)
> same question as docbook-xsl

Its only needed when BUILD_PDF is ON. (By default its OFF, it takes long to 
build)

> >tcl was never needed (the tcl plugin only has supports a configuration file
> >with a syntax like tcl, it does not use tcl).
> ok, then can move to makedepend (only use for build (searched by
> CMakeLists.txt) but not for run) . see
> http://sl1pkn07.wtf/paste/view/e4c210e4#L133

Yes, the tcl plugin has nothing to do with the tcl-language. The plugin only 
has a dependency to boost.

> >Potentially missing are: doxygen and graphviz for building API doc, libxml2
> >for xmltools plugins, libdbus for dbus plugin, libaugeas for augeas
> >plugin, libsystemd-journal-dev for the journald plugin.

> libdbus in the dbus (again)

I cannot find any dependency to dbus in your file at 
sl1pkn07.wtf/paste/view/325631b6

But it seems to be present in the CMake run:
http://sl1pkn07.wtf/paste/view/e4c210e4#L130

If you run the package build from an fresh arch installation and cmake finds 
everything, then all necessary deps should be there.

> >Otherwise, its nice that you build everything (all tools, plugins and
> >bindings)!
> nope XD, misisng java plugin/binding. one of the component is missing in
> arch (by common way) (jna.jar)

It even seems to be present multiple times ;)

https://www.archlinux.org/packages/community/x86_64/processing/files/
https://www.archlinux.org/packages/extra/i686/visualvm/files/

Don't know what would be the best option for arch linux option to reuse it 
between packages. Without it, the java binding do not work and the java plugin 
does not make much sense then. Its more of an experimental feature, though.

> On the other hand, I observer for example this:
> 
>            'python2-cheetah'
>            'ruby-ronn'

Yes, they are both needed. ruby-ronn is essential for man pages.
cheetah is needed for code generation with `kdb gen`.

> no need any other python/lua/whatever module? (yes. i forget add
> python-cheetah (python3) on the PKGBUILD)

I think there is no python-cheetah for python3, but Elektra can be build with 
python2 and python3 bindings+plugins at the same time.

Enabling and running the tests would give you more information about what is 
actually working.

Thanks!

best regards,

**Comment by sl1pkn07** [comment]
>I cannot find any dependency to dbus in your file at
sl1pkn07.wtf/paste/view/325631b6

>But it seems to be present in the CMake run:
http://sl1pkn07.wtf/paste/view/e4c210e4#L130

qt5-declarative pull qt5-base, and qt5-base pull dbus.

>Obviously, you are more experienced in packaging and in the end every packaging decision is yours. I do not have experience with arch linux not to speak with packaging for it. I only said what I found suspicious. If non-i686/x86_64 do not matter for arch linux, then its ok ;)

of course is possible add other architectures, for example armv7 and others., only need add the architecture in the arch=() array. AUR is commonly used by arch-based distros accept other architectures. if any user need add these architecture (if don't need make much work for implemented), i can add without problem


>It even seems to be present multiple times ;)

>https://www.archlinux.org/packages/community/x86_64/processing/files/
>https://www.archlinux.org/packages/extra/i686/visualvm/files/

>Don't know what would be the best option for arch linux option to reuse it
between packages. Without it, the java binding do not work and the java plugin
does not make much sense then. Its more of an experimental feature, though.

one question about this. that 'jna.jar' file, works alone?, i mean, if for exaple, i download these file (only) from upstream site, and put into a any java path, can build the elktra java plugin? or that jna.jar need a aditional software depency?

>If you run the package build from an fresh arch installation and cmake finds everything, then all necessary deps should be there.

this is a "little" problem for me. one of the advice in arch for build packagers (if you be maintainer) is build all in chroot (arch have a tools for it). but need a lot of space (same like a install a core distribution). 
I don't have that space, then need build the packages as-is.
Some internal dependencies is passed unnoticed if, is not documented or the scripts don't show it in log

for this i ask if my list of depends is correct :)

>Yes, they are both needed. ruby-ronn is essential for man pages.

for write or for read? i think is for write, but you can confirm it?

>I think there is no python-cheetah for python3, 

yes. I wrong read the pacman output. sorry then

>but Elektra can be build with python2 and python3 bindings+plugins at the same time.

yep. but about this, make me a little mistake:

if python2-cheetah is used by 'kdb gen', then add the python2 to optdepend is useless, because python2-cheetah pull python2, then convert python2 as hard dependency. 

i think is need 100% split the pkgbuild into python(3)-elektra, python2-elektra, lua-elektra and the main elektra (this last include all plugins/programs)

I can install (make install) each component separately? if is yes. how?


everything else is clear (maybe... xd)

Greetings

PS: sorry my english :S

**Comment by markus2330** [comment]
Hi,

Gustavo Alvarez wrote:
> >Obviously, you are more experienced in packaging and in the end every
> >packaging decision is yours. I do not have experience with arch linux not
> >to speak with packaging for it. I only said what I found suspicious. If
> >non-i686/x86_64 do not matter for arch linux, then its ok
> of course is possible add other architectures, for example armv7 and
> others., only need add the architecture in the arch=() array. AUR is
> commonly used by arch-based distros accept other architectures. if any user
> need add these architecture (if don't need make much work for implemented),
> i can add without problem

Of course only if someone can build it.

> one question about this. that 'jna.jar' file, works alone?, i mean, if for
> exaple, i download these file (only) from upstream site, and put into a any
> java path, can build the elktra java plugin? or that jna.jar need a
> aditional software depency?

The jna.jar is self contained, you only need this one file somewhere so that it 
is found.

> >If you run the package build from an fresh arch installation and cmake
> >finds everything, then all necessary deps should be there.
> this is a "little" problem for me. one of the advice in arch for build
> packagers (if you be maintainer) is build all in chroot (arch have a tools
> for it). but need a lot of space (same like a install a core
> distribution).  I don't have that space, then need build the packages
> as-is.
> Some internal dependencies is passed unnoticed if, is not documented or the
> scripts don't show it in log
> 
> for this i ask if my list of depends is correct

Its very easy to miss something, it would be good to test it from a clean 
system from time to time.

> >Yes, they are both needed. ruby-ronn is essential for man pages.
> 
> for write or for read? i think is for write, but you can confirm it?

Yes, it is needed during the build-process.

> i think is need 100% split the pkgbuild into python(3)-elektra,
> python2-elektra, lua-elektra and the main elektra (this last include all
> plugins/programs)

That would be great if you can put everything that has different dependencies 
into different packages.

> I can install (make install) each component separately? if is yes. how?

make install always installs every component, but I am sure that pkgbuild 
easily allows to split up different files to different packages.

best regards,

**Comment by sl1pkn07** [comment]
>That would be great if you can put everything that has different dependencies
into different packages.

all, all, not, only the bindings. (the plugins can live together with the main package)

>make install always installs every component, but I am sure that pkgbuild
easily allows to split up different files to different packages.

yes. with tons of 'rm -fr' XD. No, seriously, I need take a look on this

>The jna.jar is self contained, you only need this one file somewhere so that it is found.

okidoki.

>Yes, it is needed during the build-process.

roger!


Gretings

**Comment by sl1pkn07** [comment]
Splitted PKGBUILD

http://sl1pkn07.wtf/paste/view/2975d3e1

now with java plugin/binding

**Comment by markus2330** [comment]
Thank you, looks much better!

**Comment by markus2330** [comment]
See #435, maybe we can get the rest of it modular, too?

**Comment by markus2330** [comment]
I will close the issue for now, thank you again!

Do not hesitate to reopen if there are any further issues.
