### ISSUE TITLE
build utils: do not always install exportsymbols, exporterrors

### ISSUE THREAD

**Issue by haraldg** [ElektraInitiative/libelektra#434]
When cross compiling the build utils (exportsymbols, exporterrors) need to be installed into the build system, because cmake doesn't (officially) support switching compilers on the fly. However such generic names might easily lead to collisions and very strange build errors.

Renaming them to something like elektra-export-symbols and elektra-export-errors would be safer. (And remembering to rename them once they change in an incompatible way in case multiple versions of elektra are built with the same build system.)

**Comment by markus2330** [comment]
Hello, thanks for reporting the issue!

I pushed this solution to master so that you are not blocked with the work.

When we resolve #435 (so that elektra-export-errors and elektra-export-symbols) are not installed for everybody, I think its a fine solution.

An alternative would be to install exportsymbols and exporterrors (a rename would not be required then) to TARGET_TOOL_EXEC_FOLDER (thats a path where similar to git-functionality external commands can be invoked) and execute it with `kdb exportsymbols`. But I am not sure if this would properly work in cross compiling tool chains. Can you invoke e.g. `kdb test_key` within the tool chain? What do you think?

**Comment by haraldg** [comment]
markus2330 writes:
> I pushed this solution to master so that you are not blocked with the work.

Thanks, actually it wouldn't have been necessary to polute master with
experimental commits. I think the package could fetch any commit as long
as I know the hash.

> An alternative would be to install exportsymbols and exporterrors
> (a rename would not be required then) to TARGET_TOOL_EXEC_FOLDER
> (thats a path where similar to git-functionality external commands
> can be invoked) and execute it with `kdb exportsymbols`. But I am
> not sure if this would properly work in cross compiling tool chains.

kdb should be available during cross compilation. If it isn't, then it
is a bug in my package. I'm rather curious if it will work in host
compilation, when elektra hasn't been installed yet?

> Can you invoke e.g. `kdb test_key` within the tool chain?

I will try to be sure.

> What do you think? 

Might be the cleaner solution if it actually works, but I don't have
strong feelings either way.

**Comment by haraldg** [comment]
Got one step further, but now it is picking up the wrong binary! Which
I quite don't understand. Your commits look very straight forward to me ...

```
make[5]: Entering directory '/home/lambda/olinuxino/openwrt/build_dir/target-arm_arm926ej-s_musl-1.1.11_eabi/elektra-0.8.15dev'
[  1%] Generating exported_symbols.h
cd /home/lambda/olinuxino/openwrt/build_dir/target-arm_arm926ej-s_musl-1.1.11_eabi/elektra-0.8.15dev/src/libs/elektra && /home/lambda/olinuxino/openwrt/staging_dir/host/bin/elektra-export-errors dump resolver sync error template doc ccode fstab csvstorage lineendings hexcode hidden ni null struct tracer counter type constants noresolver wresolver ini list logchange glob hosts iconv network path enum mathcheck conditionals keytometa rename syslog uname timeofday simpleini line validation regexstore filecheck resolver_fm_b_b resolver_fm_hb_b resolver_fm_hp_b resolver_fm_ub_x resolver_fm_xb_x resolver_fm_xp_x resolver_fm_xhp_x resolver_fm_uhb_xb
Usage /home/lambda/olinuxino/openwrt/staging_dir/host/bin/elektra-export-errors
infile [outfile]
src/libs/elektra/CMakeFiles/elektra-core.dir/build.make:65: recipe for target 'src/libs/elektra/exported_symbols.h' failed
```

**Comment by haraldg** [comment]
I think I found the reason for the new error. Looks like a variable scope problem during cross compiling:

```
lambda@huygens:~/olinuxino/openwrt/build_dir$ grep ^EXE_ host/elektra-0.8.15dev/CMakeCache.txt
lambda@huygens:~/olinuxino/openwrt/build_dir$ grep ^EXE_ target-arm_arm926ej-s_musl-1.1.11_eabi/elektra-0.8.15dev/CMakeCache.txt
EXE_LOC:FILEPATH=/home/lambda/olinuxino/openwrt/staging_dir/host/bin/elektra-export-errors
```

So looks like find_util is polluting the cache on cross compiling. If at all there should be EXE_SYM_LOC and EXE_ERR_LOC entries in the cache.

FWIW this is the definition:

```
function(find_util util output_loc output_arg)
        if (CMAKE_CROSSCOMPILING)
                if (WIN32)
                        find_program(EXE_LOC wine)
                        if (EXE_LOC)
                                set (ARG_LOC "${CMAKE_BINARY_DIR}/bin/${util}.exe")
                        else()
                                find_program (EXE_LOC
                                        HINTS
                                                ${CMAKE_BINARY_DIR}
                                        ${util}.exe)
                        endif ()
                else()
                        find_program (EXE_LOC ${util})
                endif ()
        else (CMAKE_CROSSCOMPILING)
                get_target_property (EXE_LOC ${util} LOCATION)
        endif (CMAKE_CROSSCOMPILING)
        set (${output_loc} ${EXE_LOC} PARENT_SCOPE)
        set (${output_arg} ${ARG_LOC} PARENT_SCOPE)
endfunction(find_util util output)
```

**Comment by markus2330** [comment]
Thanks for your investigation, you directly led me to the problem. Should be fixed now. (I only tested if the CMakeCache.txt has correct content, not if cross-compiling actually works)

**Comment by markus2330** [comment]
Depending on the outcome of #435, we might need INSTALL_BUILD_TOOLS or INSTALL_CROSS_COMPILATION to avoid installation of export* tools. @haraldg needs to be notified when we introduce it, because it will break the openwrt build.

**Comment by markus2330** [comment]
@haraldg Warning, you now need to add -DINSTALL_BUILD_TOOLS=ON for the host build.

I set up a [build job](http://community.markus-raab.org:8080/job/elektra-gcc-configure-debian-musl/) that uses scripts/configure-debian-musl:

```
CC=musl-gcc CXX=g++ cmake -DINSTALL_BUILD_TOOLS=ON -DBUILD_TESTING=OFF -DBUILD_FULL=OFF -DBUILD_STATIC=OFF -DPLUGINS="ALL;-yajl;-journald;-crypto;-dbus;-xmltool" -KDB_DEFAULT_STORAGE=ini -DTARGET_PLUGIN_FOLDER="" ~e
```

**Comment by markus2330** [comment]
Does `-DINSTALL_BUILD_TOOLS=ON` work? Can we close the ticket?

**Comment by haraldg** [comment]
Yes, seems to work. Closing.
