### ISSUE TITLE
allow mixing HL and LL

### ISSUE THREAD

**Issue by Kochise** [ElektraInitiative/libelektra#4347]
Hi, mixing high-level with low level, I try to keep/set metadata :

```bash
/workdir # kdb set user:/sw/myorg/toto/#0/current/path/integer 458
Create a new key user:/sw/myorg/toto/#0/current/path/integer with string "458"
```
```bash
/workdir # kdb meta-set user:/sw/myorg/toto/#0/current/path/integer type long
```
```bash
/workdir # kdb meta-set user:/sw/myorg/toto/#0/current/path/integer min 400
```
```bash
/workdir # kdb meta-set user:/sw/myorg/toto/#0/current/path/integer max 500
```
```bash
/workdir # kdb meta-ls user:/sw/myorg/toto/#0/current/path/integer
max
min
type
```

Now I'm using high-level API to update this key

```c
	elektraSetLong(elektra, key, (kdb_long_t)data_long, &error);
```

It works, yet all the previously set metadata are gone, but the type (which might be reset by the function) :

```bash
/workdir # kdb meta-ls user:/sw/myorg/toto/#0/current/path/integer
type
```

So before setting the key's value, I save the metadata using `KeyGetMetadata` with something in the like of :

```c
	key = elektraFindKey(elektra, str_key, NULL);
	if (!key) return NULL;

	builder = g_variant_builder_new(G_VARIANT_TYPE("a{ss}"));

	keyRewindMeta(key);
	while ((meta = keyNextMeta(key)) != 0) {
		const char *key_name = NULL;
		gchar *meta_key = NULL;

		key_name = keyName(meta);
		meta_key = g_utf8_substring(key_name, strlen(META_CONFIG DELIMITER), (glong)strlen(key_name));
		g_variant_builder_add(builder, "{ss}", meta_key, keyString(meta));
		count += 1;

		g_clear_pointer(&meta_key, g_free);
	}

	if (count) {
		metadata = g_variant_new("a{ss}", builder);
	}

	g_variant_builder_unref(builder);
```

Which work pretty well :

```json
{'max': '500', 'min': '400', 'type': 'long'}
```

Then restoring the metadata after setting the key's value it performed by :

```c
	key = elektraFindKey(elektra, str_key, NULL);
	if (!key) return ret_code;

	g_variant_iter_init(&iter, meta);
	while (g_variant_iter_loop(&iter, "{ss}", &name, &value))
	{
		keySetMeta(key, name, value);
	}
```

Which "work" as well because reading back those metadata with the previous code returns the same thing :

```json
{'max': '500', 'min': '400', 'type': 'long'}
```

Yet when trying to list them with `kdb`, I only get :

```bash
/workdir # kdb meta-ls user:/sw/myorg/toto/#0/current/path/integer
type
```

Also when adding a metadata using `KeySetMeta` "works" somehow as I can read it back from the `c` code :

```c
	keySetMeta(key, "titi", "tata");
	keySetMeta(key, "foo", "bar");
```

```json
{'foo': 'bar', 'max': '500', 'min': '400', 'titi': 'tata', 'type': 'long'}
```

But it doesn't appears using `kdb` :

```bash
/workdir # kdb meta-ls user:/sw/myorg/toto/#0/current/path/integer
type
```
```bash
/workdir # kdb file user:/sw/myorg/toto/#0/current/path/integer
/root/.config/default.ecf
```

Any explanation ?

**Comment by markus2330** [comment]
Thank you for reporting! :+1: 

This looks like a bug to me. Setting keys in high-level API unfortunately is buggy: #4337, and there are also usability problems:  #3938. Mixing high-level and low-level is new terrain, I don't think it was tried before.

I would expect that, in general, metadata should be preserved (e.g. think of "comment"). `type` of course needs to be changed if it isn't the type that the program tries to set.

Is there a specific reason why you write the type to `user:`? The purpose of `spec:` is to hold specifications, like validations (min, max).

**Comment by Kochise** [comment]
Thank you for your feedback.

Indeed, currently I'm creating a wrapper around `Elektra` to "simplify" things because as you can see with my many questions, sometimes it is a bit "too much" for storing values.

Hence I set some default values and constants at `system:` level then just open a handle on `user:`.

The main purpose is to store everything in on XML file : path, key, value and also metada (as nodes' attributes)

So I'd like to avoid using another handle to `spec:` or so, but if that's the way it works, then I guess I have to give it a try.

**Comment by markus2330** [comment]
@kodebach can you also take a look here? Would be great to get the problems of the HL API fixed.

**Comment by markus2330** [comment]
> So I'd like to avoid using another handle to spec: or so, but if that's the way it works, then I guess I have to give it a try.

`spec:` also allows you to set defaults, which get returned if the key is neither in user: nor in system:. Metadata in other namespaces than `spec:` are actually only for the situation if the metadata is specific to the key of this namespace (like comments).

@flo91 did you also run into this bug?

**Comment by Kochise** [comment]
@markus2330 Thank for the clarification about `spec:` vs `user:`, it all depends if I could "redirect" those `spec:` metadata to the same mounted XML file. That would be super nice.

**Comment by markus2330** [comment]
`spec:` gets written to its own file, usually in /usr/share/elektra/specification (but can be any file if you use absolute paths). I wouldn't recommend you to use the same file you already mounted somewhere else (it might work if you never write there but it is a call for trouble. If you try it, please report what happened).

**Comment by kodebach** [comment]
From the code snippets above, I'm not sure, if you actually persisted the changes onto disk. Did you call `kdbSet` or for the high-level API `elektraSaveKey` after modifying the metadata?

`keySetMeta` only modifies the in-memory data-structure. A call to `kdbSet` is needed to persist changes (`elektraSaveKey` makes this call and also does some error handling). The `elektraSet*` functions from the high-level API all call `elektraSaveKey`.

Generally, I don't recommend using the high-level API, if you need to frequently modify keys or if you need to modify multiple keys. With the high-level API you can only apply a single change at a time. The low-level API allows you to change many keys at once and then persist everything in one atomic operation.

**Comment by Kochise** [comment]
@kodebach Thank for the clarification, but since I'm using `elektraSetLong` at least the already present metadata should remain. Which is obviously not the case.

**Comment by Kochise** [comment]
Tried to commit metadata this way (not the brightest idea I guess) :

```c
	get = ksNew(0, KS_END);
	kdbGet(*((KDB **)elektra), get, key);
	kdbSet(*((KDB **)elektra), get, key);
	ksDel(get);
```

Got this in return :

```bash
      set_metadata...
        looping...
Item max has value 500
Written 4 bytes
Item min has value 400
Written 4 bytes
Item type has value long
Written 5 bytes
{'error': 'number description  module file line mountpoint configfile reason', 'error/configfile': '/root/.config/default.ecf', 'error/description': 'Interface', 'error/file': '/workdir/src/libelektra-0.9.9/src/libs/elektra/kdb.c', 'error/line': '1800', 'error/module': 'kdb', 'error/mountpoint': 'user:/sw/evbox/toto/#0/current/path/integer', 'error/number': 'C01320', 'error/reason': 'parentKey with read-only name passed', 'foo': 'bar', 'max': '500', 'min': '400', 'titi': 'tata', 'type': 'long'}
{'error': 'number description  module file line mountpoint configfile reason', 'error/configfile': '/root/.config/default.ecf', 'error/description': 'Interface', 'error/file': '/workdir/src/libelektra-0.9.9/src/libs/elektra/kdb.c', 'error/line': '1800', 'error/module': 'kdb', 'error/mountpoint': 'user:/sw/evbox/toto/#0/current/path/integer', 'error/number': 'C01320', 'error/reason': 'parentKey with read-only name passed', 'foo': 'bar', 'max': '500', 'min': '400', 'titi': 'tata', 'type': 'long'}
    ret_code: 0
```

**Comment by markus2330** [comment]
If you need features beyond the HL-API it is probably better that you use the LL-API (low-level, i.e. kdb.h). Mixing them probably only adds complications for you, as you need to understand the inner workings of both HL and LL.

What exactly would you like to do with meta-data? Maybe it is something important we missed to support in the HL-API.

**Comment by Kochise** [comment]
Well, from my understanding, there is no metadata handling from the HL-API anyway :

https://github.com/ElektraInitiative/libelektra/blob/master/src/include/elektra.h

Hence the mixing with the LL-API, which may not be as "user friendly" yet probably more efficient and "exhaustive".

Regarding the use of "metadata", I think there is a misunderstanding due of the common naming.

Obviously some resolver/plugin use some "metadata" for internal use, like automated bound checking or so.

On the other hand, as "user", we also want to provide "metadata" to a value, with a very similar purpose.

Not only for "default", "mix" and "max", but also other arbitrary "companion" data as our needs may see fit.

So I guess we should first check what kind of metadata can rely on `Elektra`'s internal mechanism.

Then keep more "application" oriented metadata on a separate "layer".

However both should be saved in the same configuration file, which **must** be an XML file.

That might explain the collision/confusion of our mutual understanding of each other's goals.

Sorry for that.
