### ISSUE TITLE
KeySet ref counter in Java bindings 

### ISSUE THREAD

**Issue by tucek** [ElektraInitiative/libelektra#4348]
The new reference counting for key sets that was implemented in #3949 still needs to be implemented in multiple bindings. For an overview of all bindings needing changes, see #4129.

This issue tracks the integration of the new key set reference counter for the Java binding only. There has some discussion regarding this change in #4129.

**Comment by flo91** [comment]
@markus2330 Maybe also an issue suited for the FLOSS course, esp. because it involves using Java.

**Comment by markus2330** [comment]
Unfortunately a quite tricky issue. @tucek do you see a way how a beginner may help you here?

**Comment by tucek** [comment]
@markus2330 this issue is already done with #4440 which is still not merged, is see?!
