### ISSUE TITLE
Modular installation

### ISSUE THREAD

**Issue by haraldg** [ElektraInitiative/libelektra#435]
As discussed in Issue #434 the build utils need to be installed into the PATH of the system when preparing for cross compiling. This is currently not supported by the Makefiles.

One possible solution is to provide a new make target install_buildutils ...

**Comment by markus2330** [comment]
The most straight-forward way within CMake seems to be to use the [install COMPONENT](https://cmake.org/cmake/help/v3.0/command/install.html) feature.

With it we could assign every installed file to one of the components. Before I go into details which files go into which components:

1.) Do you think its a good idea?
2.) Could we get rid of every INSTALL_* (i.e. INSTALL_DOCUMENTATION, INSTALL_TESTING and INSTALL_SYSTEM_FILES) that way?
3.) Is it worth the effort? Most of the distribution packages need to be adapted if INSTALL_* is not available anymore.

A concern that I have that it will get difficult to install everything except one component. But exactly this would be very common, e.g. installing everything except system files or everything except cross compilation tools. As I understood it, you either install everything with `make install` or you have to install every single component.

@beku: Would that be problematic for your local installations without system files (/etc/profile.d)?

@pinotree: What do you think? Do you maybe have experience with the COMPONENT feature of cmake?

Thank you!

**Comment by beku** [comment]
As far as I can see Oyranos and Synnefo uses that cmake thing to build OS X frameworks and app bundles correctly. I do not know if that is the correct answere for your here discussed needs.

**Comment by markus2330** [comment]
@beku Thank you, app bundles are indeed an interesting aspect for that discussion. I will look into Oyranos if we decide to implement a install COMPONENT feature.

**Comment by beku** [comment]
@markus2330 https://github.com/oyranos-cms/oyranos/blob/master/src/liboyranos_core/CMakeLists.txt

**Comment by markus2330** [comment]
Because no one really argued that he/she really wants/needs this expensive feature we will simple go for INSTALL_BUILD_TOOLS, see #434.
