### ISSUE TITLE
[CM P2] web-ui 2.0

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4356]
- [x] docu full of errors, e.g. in tutorial:
  - [ ] no folder "client"
  - [x] remove section "Using a Different kdb Executable"
  - [x] kdb run-web not available (run-webd)
- [ ] ip/port config via Elektra
- [ ] publish webui demo #2913
- [ ] automatic test cases that do at least smoke tests
- [x] pump version number to 2.0
- [x] few open items in #4299 (dependabot.yml, open dependabot PRs).

**Comment by lukashartl** [comment]
@markus2330 please clarify what "open items" means 😸

**Comment by markus2330** [comment]
You already fixed those! I fixed/ticked it.

**Comment by leothetryhard** [comment]
> * [ ]  "Getting Started (docker)" which folder do I need to be in?

Since we pull elektra/web:latest from dockerhub, the folder to be in shouldn't relevant, or am I missing something?

**Comment by leothetryhard** [comment]
>  "Using` a Different kdb Executable" does not apply to golang version anymore

Not sure what you mean by that, please clarify.
I ran `run-elektrad`and kdb run-webd like in the example and it worked.
@markus2330

**Comment by markus2330** [comment]
>  Since we pull elektra/web:latest from dockerhub, the current folder shouldn't be relevant, or am I missing something?

You are right, if this docker command works, everything should be fine.

>  Not sure what you mean by that, please clarify.
> Edit: I talked to @kodebach and we agreed on deleting this section due to the lack of applicability.

Yes, exactly, the section "Using a Different `kdb` Executable" is simply outdated and needs to be removed.

I updated the top-post.
