### ISSUE TITLE
Kotlin binding 1.0

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4357]
Follow-up from #4294:

- [x] #4393
- [ ] An example application
- [ ] An example using plugin code (current example covers most functions)
- [ ]  Array handling functions
- [ ]  Plugin error creation (already discussed in https://github.com/ElektraInitiative/libelektra/pull/4365#issuecomment-1140314385)

Maybe sometime in the future:

- [ ] Use Kotlin native to integrate with the C library directly
- [ ] Plugin extensions

Other work:

- [ ] README.md improvements: more explanations, guide through most important features, ...
- [ ] add link to binding: APP.HOME.LABEL.ORIENTATION.2.DETAILS in src/tools/website/public/assets/translations/en.json
- [ ] improvement of tests
- [ ] API docu missing/could be improved
- [ ] Missing full&working examples, ideally a small application and a plugin that uses Kotlin Serialization

**Comment by markus2330** [comment]
Please tick what was done and write here what is still left undone as future work.

**Comment by mandoway** [comment]
We can't tick the options so here is a list of future work:

- Musts:
  - Publishing (config is present)
- Optionals:
  - An example using plugin code (current example covers most functions)
  - Array handling functions (open discussion for the best fitting place for this functionality, see https://github.com/ElektraInitiative/libelektra/pull/4365#issuecomment-1140327073)
  - Plugin error creation (already discussed in https://github.com/ElektraInitiative/libelektra/pull/4365#issuecomment-1140314385)
- Maybe sometime in the future:
  - Use Kotlin native to integrate with the C library directly
  - Plugin extensions

**Comment by markus2330** [comment]
Thank you for summarizing! I updated the top post!
