### ISSUE TITLE
Support in-tree builds

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#436]
In-tree builds are currently possible with FORCE_IN_SOURCE_BUILD, but not really supported. Thus in OpenWRT no clean solution for out-of-tree builds exist we should officially support it, i.e. have a build job that tests it.

**Comment by haraldg** [comment]
Found the first problem with in-tree builds. Recursive inclusion of header
files:

```
Scanning dependencies of target elektra-iconv-objects
[ 16%] Building C object src/plugins/iconv/CMakeFiles/elektra-iconv-objects.dir/iconv.c.o
In file included from /home/lambda/elektra/git/src/plugins/iconv/iconv.h:12:0,
                 from /home/lambda/elektra/git/src/plugins/iconv/iconv.h:12,
.
.
.
                 from /home/lambda/elektra/git/src/plugins/iconv/iconv.h:12,
                 from /home/lambda/elektra/git/src/plugins/iconv/iconv.c:9:
/home/lambda/elektra/git/src/plugins/iconv/iconv.h:9:23: error: #include nested
too deeply
```

Looks like for some reason "#include <inconv.h>" finds the local version of
iconv.h instead of the system version. (This is tested on jessie/i386 to make
sure it is not a problem of the cross toolchain.)

**Comment by markus2330** [comment]
Should be fixed now. I have set up a build job to check for regressions:
http://community.markus-raab.org:8080/job/elektra-gcc-configure-debian-intree/

**Comment by haraldg** [comment]
Yes, works now. Wouldn't it be cleaner to fix the search path for include files than to rename the header files?

**Comment by markus2330** [comment]
Thanks for the remark!
The problem is that the search path is different for in-source and out-source builds (or at least the current working directory is different.) And the search path, especially the handling of `#include ""` is also non-portable. So renaming seemed to be like a robust solution.

**Comment by markus2330** [comment]
Should be fixed now, please reopen on issues.
