### ISSUE TITLE
Debian: get listed in extrepo

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4360]
Debian has a tool "extrepo" in which you can search for and enable external repositories.

Once Elektra's Debian repos are registered there, users could type:

```sh
extrepo search elektra
extrepo enable elektra
```

To search and enable Elektra's Debian repository.

See here on how we get added: https://salsa.debian.org/extrepo-team/extrepo-data

**Comment by flo91** [comment]
@markus2330 Do you think this issue is good for the FLOSS course?

**Comment by markus2330** [comment]
Absolutely! It is basically creating a PR with a YAML file.
