### ISSUE TITLE
CI broken because of elektra-web-base docker build

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#4370]
It seems the Jenkins pipeline is broken right now, because of the job that builds the `elektra-web-base` Docker image. The job fails in all PRs that have recently been built.

**Comment by markus2330** [comment]
Please give more information: error message etc.

**Comment by kodebach** [comment]
Nevermind, I found a recent build where the job succeeded. Either I look at the wrong logs or it was just a coincidence that multiple builds failed with the same issue.
