### ISSUE TITLE
xfconf-binding: cannot read from KDB

### ISSUE THREAD

**Issue by eiskasten** [ElektraInitiative/libelektra#4405]
During the development of the xfconf binding, I encountered a problem where I receive a different key store state.
While the `kdb` tool can read all keys set by the user, the glib binding is only able to read all the default keys in my case.

## Steps to Reproduce the Problem

While

```sh
kdb set user:/tests/hello world
#> Create a new key user:/tests/hello with string "world"

kdb get user:/tests/hello
#> world
```

works as expected,

```c
GElektraKeySet * key_set = gelektra_keyset_new (0, GELEKTRA_KEYSET_END);
GElektraKey * parent_key = gelektra_key_new ("/", GELEKTRA_KEY_END);
gelektra_kdb_get (gElektraKdb, key_set, parent_key);
```
only reads all the default keys and stores them into `key_set`. This is also the case with `system:/` keys.

## Expected Result

`key_set` contains `user:/tests/hello`.

## Actual Result

`key_set` does not contain `user:/tests/hello`.

## System Information

- Elektra: master
- Operating System: Arch Linux

## Infos about xfconf binding

As of now I am developing this binding. My strategy is to implement the c headers of xfconf and use the binding as drop-in replacement for xfconf. Then I start an application which uses xfconf (e.g. thunar) which then calls the functions of the xfconf binding instead of the real xfconf library:

```sh
ldd $(which thunar) | grep -E "(xfconf|elektra)"
	libxfconf-0.so.3 => /usr/lib/libxfconf-0.so.3 (0x00007f97ec8ca000)
	libgelektra-5.0.so => /home/richi/Dokumente/tu/2022-ss/cm/libelektra/cmake-build-debug/lib/libgelektra-5.0.so (0x00007f97eb868000)
	libelektra-kdb.so.5 => /home/richi/Dokumente/tu/2022-ss/cm/libelektra/cmake-build-debug/lib/libelektra-kdb.so.5 (0x00007f97eb84c000)
	libelektra-core.so.5 => /home/richi/Dokumente/tu/2022-ss/cm/libelektra/cmake-build-debug/lib/libelektra-core.so.5 (0x00007f97eb830000)
```

My Cmake flags are:

```sh
-DKDB_DB_HOME="~/.config/kdb/cm/home"
-DKDB_DB_SYSTEM="~/.config/kdb/cm/system"
-DKDB_DB_SPEC="~/.config/kdb/cm/spec"
-DKDB_DB_USER=".config/kdb/cm/user"
-DCMAKE_INSTALL_PREFIX="install"
-DENABLE_DEBUG="ON"
-DENABLE_LOGGER="ON"
-DPLUGINS="ALL"
-DTOOLS="ALL"
-DBINDINGS="ALL"
-DTOOLS="ALL"
```

## Further Log Files and Output

Using `inotifywait` I found out that both `kdb` and `thunar` accessed my `~/.config/kdb/cm/user/default.ecf` which tells me that this is not a problem which consists of reading wrong files from the file system.

**Comment by markus2330** [comment]
Please clarify what you mean with "default keys". Do you have a specification for `user:/tests/hello`?

Your glib code also does not seem to be complete. How did you initialize gElektraKdb etc. Please give a full example so that we can reproduce it.

@mpranj do you have any idea what this could be? Iirc you used the gsettings binding successfully recently?

**Comment by Eiskasten** [comment]
I initialize it with:

```c
gboolean xfconf_init (GError ** error)
{
	trace ();
	GElektraKeySet * empty_set = gelektra_keyset_new (0);
	GElektraKey * elektra_error = gelektra_key_new ("/elektra_error", KEY_END);
	gElektraKdb = gelektra_kdb_open (NULL, elektra_error);
	if (gElektraKdb == NULL)
	{
		g_debug ("unable to open gelektraKdb");
		*error = g_error_new (0, 1, "unable to open kdb: %s", gelektra_key_string (elektra_error));
		return FALSE;
	}
	g_debug ("opened gelektraKdb");
	return TRUE;
}
```

and I retrieve the keys with

```c
gboolean xfconf_channel_get_property (XfconfChannel * channel, const gchar * property, GValue * value)
{
	trace ();
	GElektraKeySet * key_set = gelektra_keyset_new (0, GELEKTRA_KEYSET_END);
	GElektraKey * parent_key = gelektra_key_new ("/", GELEKTRA_KEY_END);
        gelektra_kdb_get (gElektraKdb, key_set, parent_key);
	g_debug ("channel has %zd keys", gelektra_keyset_len (key_set));
	GElektraKey * current;
	for (gssize i = 0; i < gelektra_keyset_len (key_set); i++)
	{
		current = gelektra_keyset_at (key_set, i);
		g_debug ("found key: %s", gelektra_key_name (current));
	}
	return TRUE;
}
```

with default keys I mean the keys:

```
system:/elektra/modules/cache
system:/elektra/modules/cache/exports
system:/elektra/modules/cache/exports/close
system:/elektra/modules/cache/exports/get
system:/elektra/modules/cache/exports/open
system:/elektra/modules/cache/exports/set
system:/elektra/modules/cache/infos
system:/elektra/modules/cache/infos/author
system:/elektra/modules/cache/infos/description
system:/elektra/modules/cache/infos/licence
system:/elektra/modules/cache/infos/metadata
system:/elektra/modules/cache/infos/needs
system:/elektra/modules/cache/infos/placements
system:/elektra/modules/cache/infos/provides
system:/elektra/modules/cache/infos/recommends
system:/elektra/modules/cache/infos/status
system:/elektra/modules/cache/infos/version
system:/elektra/modules/dump
system:/elektra/modules/dump/config/needs/fcrypt/textmode
system:/elektra/modules/dump/exports
system:/elektra/modules/dump/exports/fserialize
system:/elektra/modules/dump/exports/funserialize
system:/elektra/modules/dump/exports/get
system:/elektra/modules/dump/exports/serialize
system:/elektra/modules/dump/exports/set
system:/elektra/modules/dump/exports/unserialize
system:/elektra/modules/dump/infos
system:/elektra/modules/dump/infos/author
system:/elektra/modules/dump/infos/description
system:/elektra/modules/dump/infos/licence
system:/elektra/modules/dump/infos/metadata
system:/elektra/modules/dump/infos/needs
system:/elektra/modules/dump/infos/placements
system:/elektra/modules/dump/infos/provides
system:/elektra/modules/dump/infos/recommends
system:/elektra/modules/dump/infos/status
system:/elektra/modules/dump/infos/version
system:/elektra/modules/list
system:/elektra/modules/list/exports
system:/elektra/modules/list/exports/addPlugin
system:/elektra/modules/list/exports/close
system:/elektra/modules/list/exports/deferredCall
system:/elektra/modules/list/exports/editPlugin
system:/elektra/modules/list/exports/error
system:/elektra/modules/list/exports/findplugin
system:/elektra/modules/list/exports/get
system:/elektra/modules/list/exports/mountplugin
system:/elektra/modules/list/exports/open
system:/elektra/modules/list/exports/set
system:/elektra/modules/list/exports/unmountplugin
system:/elektra/modules/list/infos
system:/elektra/modules/list/infos/author
system:/elektra/modules/list/infos/description
system:/elektra/modules/list/infos/licence
system:/elektra/modules/list/infos/needs
system:/elektra/modules/list/infos/placements
system:/elektra/modules/list/infos/provides
system:/elektra/modules/list/infos/status
system:/elektra/modules/list/infos/version
system:/elektra/modules/resolver_fm_hpu_b
system:/elektra/modules/resolver_fm_hpu_b/constants
system:/elektra/modules/resolver_fm_hpu_b/constants/ELEKTRA_VARIANT_BASE
system:/elektra/modules/resolver_fm_hpu_b/constants/ELEKTRA_VARIANT_SYSTEM
system:/elektra/modules/resolver_fm_hpu_b/constants/ELEKTRA_VARIANT_USER
system:/elektra/modules/resolver_fm_hpu_b/constants/KDB_DB_DIR
system:/elektra/modules/resolver_fm_hpu_b/constants/KDB_DB_HOME
system:/elektra/modules/resolver_fm_hpu_b/constants/KDB_DB_SPEC
system:/elektra/modules/resolver_fm_hpu_b/constants/KDB_DB_SYSTEM
system:/elektra/modules/resolver_fm_hpu_b/constants/KDB_DB_USER
system:/elektra/modules/resolver_fm_hpu_b/exports
system:/elektra/modules/resolver_fm_hpu_b/exports/checkfile
system:/elektra/modules/resolver_fm_hpu_b/exports/close
system:/elektra/modules/resolver_fm_hpu_b/exports/commit
system:/elektra/modules/resolver_fm_hpu_b/exports/error
system:/elektra/modules/resolver_fm_hpu_b/exports/filename
system:/elektra/modules/resolver_fm_hpu_b/exports/freeHandle
system:/elektra/modules/resolver_fm_hpu_b/exports/get
system:/elektra/modules/resolver_fm_hpu_b/exports/open
system:/elektra/modules/resolver_fm_hpu_b/exports/set
system:/elektra/modules/resolver_fm_hpu_b/infos
system:/elektra/modules/resolver_fm_hpu_b/infos/author
system:/elektra/modules/resolver_fm_hpu_b/infos/description
system:/elektra/modules/resolver_fm_hpu_b/infos/licence
system:/elektra/modules/resolver_fm_hpu_b/infos/needs
system:/elektra/modules/resolver_fm_hpu_b/infos/placements
system:/elektra/modules/resolver_fm_hpu_b/infos/provides
system:/elektra/modules/resolver_fm_hpu_b/infos/status
system:/elektra/modules/resolver_fm_hpu_b/infos/version
system:/elektra/version
system:/elektra/version/constants
system:/elektra/version/constants/KDB_VERSION
system:/elektra/version/constants/KDB_VERSION_MAJOR
system:/elektra/version/constants/KDB_VERSION_MINOR
system:/elektra/version/constants/KDB_VERSION_PATCH
system:/elektra/version/constants/SO_VERSION
system:/elektra/version/infos
system:/elektra/version/infos/author
system:/elektra/version/infos/description
system:/elektra/version/infos/licence
system:/elektra/version/infos/version
```

I did not write any specification for `user:/tests/hello`. However, I found out that when I initialize `gElektraKdb` in `xfconf_channel_get_property()` instead of `xfconf_init()` everything works as expected. When running an xfconf application, I receive the line `[New Thread 0x7ffff3144640 (LWP 427936)]` (with different addresses) multiple times which leads me to assume that this issue is caused by multi-threading of xfconfand not caused by glib at all. However I am not aware of another way to get this to work than initialize `gElektraKdb` in every call which is not quite efficient.

**Comment by kodebach** [comment]
> this issue is caused by multi-threading of xfconfand not caused by glib at all. However I am not aware of another way to get this to work than initialize `gElektraKdb` in every call which is not quite efficient.

The `KDB` handle is not thread-safe. So if multi-threading is involved, you need to either do some thread synchronisation (mutex etc.) or use separate handles anyway. However, this is only needed if multiple threads can access the same `KDB` handle at the same time.

However, I doubt a multi-threading problem would look like this. You'd probably get segfaults or corrupt data. The result seems to neat and perfect for a multi-threading problem.

I suspect something different. You showed that `thunar` links against the debug versions of the Elektra libs in `/home/richi/...` and your CMake config overrides `KDB_DB_*`. Did check what `kdb` links against? If this `kdb` is installed from a package or built in the default release config, it will use different `KDB_DB_*` values and therefore access different files.

If this is the problem, the solution would be to simply use `[debug-build-dir]/bin/kdb` or run `make install` for the debug build and use that (from your config it looks like that would be installed as `[debug-build-dir]/install/bin/kdb`).

**Comment by Eiskasten** [comment]
> > this issue is caused by multi-threading of xfconfand not caused by glib at all. However I am not aware of another way to get this to work than initialize `gElektraKdb` in every call which is not quite efficient.
> 
> The `KDB` handle is not thread-safe. So if multi-threading is involved, you need to either do some thread synchronisation (mutex etc.) or use separate handles anyway. However, this is only needed if multiple threads can access the same `KDB` handle at the same time.

I know that it is not thread-safe that lead me come to the conclusion that this is the problem.

> However, I doubt a multi-threading problem would look like this. You'd probably get segfaults or corrupt data. The result seems to neat and perfect for a multi-threading problem.
> 
> I suspect something different. You showed that `thunar` links against the debug versions of the Elektra libs in `/home/richi/...` and your CMake config overrides `KDB_DB_*`. Did check what `kdb` links against? If this `kdb` is installed from a package or built in the default release config, it will use different `KDB_DB_*` values and therefore access different files.
> 
> If this is the problem, the solution would be to simply use `[debug-build-dir]/bin/kdb` or run `make install` for the debug build and use that (from your config it looks like that would be installed as `[debug-build-dir]/install/bin/kdb`).

I have not installed `kdb`on this system and my version links against the correct libraries. As I have written in the issue description, I also check which files were accessed from my disk and they were correct. However, when I initialize `gElektraKdb` in `xfconf_channel_get_property()` instead of `xfconf_init()` everything works as expected (both definitely get called in the correct order, I have checked that via the trace).

**Comment by mpranj** [comment]
> However, when I initialize gElektraKdb in xfconf_channel_get_property() instead of xfconf_init() everything works as expected (both definitely get called in the correct order, I have checked that via the trace).

If this is the case, I don't understand how the problem is located in Elektra's glib bindings and not in the xfconf bindings.

Have you tried enabling [logging in Elektra](https://www.libelektra.org/tutorials/logging#how-to-logging) to see what is happening on that side? (i.e. what parentKey is used on kdbGet and so on..)

Maybe it's just a minor problem or typo somewhere? You could also try just using `user:/` as parentKey and see what changes.

**Comment by Eiskasten** [comment]
> > However, when I initialize gElektraKdb in xfconf_channel_get_property() instead of xfconf_init() everything works as expected (both definitely get called in the correct order, I have checked that via the trace).
> 
> If this is the case, I don't understand how the problem is located in Elektra's glib bindings and not in the xfconf bindings.

It does not. It was my first thought which turned out to be incorrect. I will change the title.

> Have you tried enabling [logging in Elektra](https://www.libelektra.org/tutorials/logging#how-to-logging) to see what is happening on that side? (i.e. what parentKey is used on kdbGet and so on..)
> 
> Maybe it's just a minor problem or typo somewhere? You could also try just using `user:/` as parentKey and see what changes.

I have checked the logs, the correct files get read. The same problem happens using `'/'` as the parent key.

**Comment by kodebach** [comment]
> As I have written in the issue description

Sorry, I missed that... 

---

@mpranj could this be a cache issue?

It still seems very unlikely to me that a threading issue would consistently return the same result.

**Comment by kodebach** [comment]
> > @mpranj could this be a cache issue?
> 
> Afaik the cache is effectively disabled since `procgetstorage` exists, so it's likely not the issue.

I thought that only applies when `gopts` is mounted. Which would require passing a `contract` to `kdbOpen`, since it's not mounted by default.

**Comment by Eiskasten** [comment]
> It still seems very unlikely to me that a threading issue would consistently return the same result.

What would happen if the xfconf application calls `fork()` too early e.g. before `GElektraKdb` was fully initialized?

**Comment by mpranj** [comment]
> I thought that only applies when gopts is mounted. Which would require passing a contract to kdbOpen, since it's not mounted by default.

If I'm not completely mistaken: since the `list` plugin is mounted at every position (by default) the following code is always true:
https://github.com/ElektraInitiative/libelektra/blob/8f43d5debbd4750cab24b33aead340e5dbb769e8/src/libs/elektra/kdb.c#L1292-L1293
Thus, the cache is **never** used.

> EDIT: In any case, it can't hurt if @Eiskasten tries to disable the cache with kdb cache disable.

Yes, this can't hurt right now for development purposes.

**Comment by mpranj** [comment]
> What would happen if the xfconf application calls fork() too early e.g. before GElektraKdb was fully initialized?

It's not clearly defined, but you would likely see some segfault as @kodebach already said. I also highly doubt you would see such neat output.

If you're sure that this is the problem you could always try using a mutex (`GMutex`) around everything just to test it.

**Comment by Eiskasten** [comment]
> Could there be some namespacing/sandboxing involved? What do you get, if you print the file `~/.config/kdb/cm/user/default.ecf` (should be a text file) directly in `xfconf_channel_get_property`?

I have tried it. Using `~/.config/kdb/cm/user/default.ecf` said no such file or directory, but using the absolute path worked. But I think this is only because `fopen()` does not understand `~`. Using the absolute path works and the file permissions are set to `600`.

**Comment by Eiskasten** [comment]
I found out what the issue was. I already silently called `kdbGet` somewhere else in the code before `xfconf_channel_get_property`.
