### ISSUE TITLE
Rust Binding Next Steps

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4411]
I am currently using the Rust binding and must say it is a pleasure to work with it. I published the [0.9.10 version](https://crates.io/crates/elektra). I noticed that following next steps could be worthwhile to pursue:

- [ ] use rustfmt and let CI check if code is formatted correctly
- [ ] type-safe higher-level API using specifications (allow parts of config objects to be passed around)
- [ ] improve concurrent access
- [ ] tokio/async integration
- [ ] allow to store any Rust data structures in a KeySet (using serde.rs)
- [ ] fix cross compilation of rust #3904
- [ ] cmake improvements #4007
- [ ] automatic publish crate on every release
- [ ] remove LookupOption #4222 
- [ ] integrate tooling, 3-way merge and other libraries of Elektra
- [ ] longer tutorial of different features
- [ ] link to API descriptions of libelektra, at least for KDB
- [ ] allow to implement plugins in Rust
- [ ] lookup_by_name should actually use ksLookupByName for performance reasons
- [ ] allow lookup on keyset without mut
- [ ] example pretty printing of KDBError (`KDBError { error_key: StringKey { ptr: 0x658b938, _marker: PhantomData } }` on unwrap etc.)
- [ ] logger integration (allow logger to be configured from Elektra)
- [ ] operator overloading
- [ ] "insert" for both Key and Keyset, see #3978
- [ ] allow callbacks using interneralnotification
- [ ] Implement external iteration of metakeys (src/key.rs line 539)
- [ ] allow changing namespace of keys (should also fix src/key.rs line 593)
- [ ] is_below, is_directly_below etc. should also work with other types (e.g. ReadOnly with StringKey etc.)

**Comment by markus2330** [comment]
@lawli3t Anything else which you found while reimplementing the API?

**Comment by lawli3t** [comment]
Your list already looks pretty good. One thing I found useful was using the bitflags crate for creating the methods, but it depends on whether one would want to add a dependency for that.

also some additional traits such as `FromStr` for Key would be interesting, I am sure there are more.

**Comment by markus2330** [comment]
@PhilippGackstatter if you have some time, maybe you can have a look if there are any missing TODOs/left-overs of the Rust binding (not in the list above). Btw. I don't have your current email address.
