### ISSUE TITLE
Improve length plugin

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4422]
- [ ] implement check/length/min
- [ ] add more unit tests
- [ ] add shell recorder test
- [ ] remove "experimental"
- [ ] improve error message (should be syntactic validation)
- [ ] improve documentation
- [ ] "len plugin" -> "length plugin"

**Comment by flo91** [comment]
@markus2330 Sounds like a good issue for the FLOSS course.

**Comment by markus2330** [comment]
Unfortunately also a C issue...
