### ISSUE TITLE
Rename backend to filebackend

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#4429]
The title says it all. To avoid confusion (*) we should rename the default (file-based) backend plugin `backend` to `filebackend`.

(*) confusion between "a backend plugin" (any of the possible ones) and "the `backend` plugin" (the specific one I want to rename)

**Comment by Eiskasten** [comment]
### Reproduction

Run `grep -rE "^- infos/provides = backend$" ./src/plugins` in the project root.

### Expected Result

Nothing, as there should not exist a plugin named `backend`.

### Actual Result

It prints

```
./src/plugins/backend/README.md:- infos/provides = backend
```

**Comment by markus2330** [comment]
Thank you for taking the issue! The `provides = backend` actually should stay, as the filebackend is one kind of backend.

If anyone has a better name than "filebackend", please say asap :wink:

**Comment by Eiskasten** [comment]
> If anyone has a better name than "filebackend", please say asap wink

Maybe `filesystem`?

**Comment by Eiskasten** [comment]
Sounds reasonable. Then the only alternative I can find is `defaultbackend` but in this case I prefer `filebackend` to be honest.

**Comment by markus2330** [comment]
What about something creative like backfile or fileend? With the same pattern we would then name all (future) backends.

It could be also only one letter like bfile or fileb.

But I have to admit that from all these suggestions, filebackend still is best (by far).

@flo91 how will you call the "sqlbackend"?

**Comment by kodebach** [comment]
Yeah, I still prefer `filebackend`, it is a bit long, but everything shorter like `fileb`, `filebe`, `fileend`, `filebend` etc. is very non-intuitive and makes it harder to find.

The problem really is that our plugin names are all lowercase without any separators. Maybe we should allow `-` (i.e. kebab-case). Then it could be `backend-file`. This would result in the more logical library name `libelektra-backend-file.so` (or `libelektra-plugin-backend-file.so`, when we get round to implementing the `plugin` prefix).

**Comment by flo91** [comment]
I also think that `filebackend` is the best option, because the name makes immediately clear what we are talking about.

> @flo91 how will you call the "sqlbackend"?
I would suggest calling it `odbcbackend` or `odbc-backend` if we allow a separator.

**Comment by markus2330** [comment]
Allowing `-` would be relatively easy (at least compared to allowing `/`). There are a few places that probably would need changes, e.g., scripts/dev/copy-template

I agree with @flo91, with `-` it is probably best to swap the words, i.e. `backend-file` or `backend-odbc` or `backend-nofile` (for noresolver like XFCE etc.) to make it easier to see which backends are there.

This theme should then be used for others, too, e.g. `resolver-git`, `resolver-block`, `resolver-w`.

But this is already a major renaming operation, probably too much for @Eiskasten? @Eiskasten which scope do you see for this issue? (1p definitely would get changed..)

@kodebach could your tooling help there? Or would you also simply do something similar to the script scripts/dev/copy-template?

Another rename would be csvstorage -> csv, unless we also want all storage plugins to be renamed (storage-csv).

**Comment by kodebach** [comment]
Since this mostly involves renaming files/folders and changing strings, I don't think my `tree-surgeon` tool would be useful.

However, there is absolutely no need to do all of this at once. This is issue is only about renaming `backend`. In fact this is a prime example of a decision that can be implemented in parts.

IMO we should do this:
1. Write a decision to allow `-` in plugin names and that plugins should use the naming convention `backend-XXX`, `resolver-XXX`, when using `-`.
2. Change the name of the plugin `backend` to `backend-file`
3. (Optional) add a symlinked plugin `backend` that links to `backend-file` (similar to what we have with resolver)
4. Leave the rest of the remaining for the future. (It should definitely be one PR per renaming to make reviews easier.)

**Comment by markus2330** [comment]
`-` in file names is already allowed, see `scripts/dev/filename-checker`. So it is basically only a naming convention, which imho doesn't need a decision. A few lines in src/plugins/README.md would be enough.

I am against starting any other half thing, we already have more than enough construction work (new-backend,  ...). So either we:

1. only rename backend to filebackend, or
2. we go the full way with using `-` as separator for any backend, resolver, etc. as described in https://github.com/ElektraInitiative/libelektra/issues/4429#issuecomment-1288425360
3. any new suggestion about a naming convention not yet said.

In any case, the result should be a consistent and documented naming schema.

It is @Eiskasten's decision, as he will do the work.
