### ISSUE TITLE
elektraGetOptsHelpMessage docs/examples use 'opt/arg/name' instead of  'opt/arg/help'

### ISSUE THREAD

**Issue by hannes99** [ElektraInitiative/libelektra#4432]
## Steps to Reproduce the Problem

```c
...
(ks, keyNew (baseKeyName "spec:/test/path", KEY_META, "description", "Some description",  \
                                            KEY_META, "opt", "p", \
                                            KEY_META, "opt/arg/name", "path", \
                                            KEY_META, "opt/long", "path", \
                                            KEY_META, "opt/arg", "required", KEY_END));  \
...
... elektraGetOpts (ks, argc, (const char **) argv, (const char **) environ, errorKey);
...
char * help = elektraGetOptsHelpMessage (errorKey, NULL, NULL);
```

The `--help` output ignores the specified `opt/arg/name` and always uses `ARG` instead.

## Expected Result

```
OPTIONS
...
  -p path, --profile=path     Some description.
...

```

## Actual Result

```
OPTIONS
...
  -p ARG, --profile=ARG       Some description.
...

```

**Comment by hannes99** [comment]
Actually, yes. I'll update the `rm` example in the tutorial[1], since `/name` is used there.

[1] https://www.libelektra.org/tutorials/command-line-options#examples

**Comment by hannes99** [comment]
should I change the Issue title and description, or leave it?

**Comment by kodebach** [comment]
> I'll update the rm example in the tutorial

Please also check other docs, like [`examples/opts.c`](https://github.com/ElektraInitiative/libelektra/blob/master/examples/opts.c) and [`examples/gopts.c`](https://github.com/ElektraInitiative/libelektra/blob/master/examples/gopts.c)

> should I change the Issue title and description, or leave it?

I updated it.
