### ISSUE TITLE
opts: potential "free(): invalid pointer" error

### ISSUE THREAD

**Issue by hannes99** [ElektraInitiative/libelektra#4434]
Here 
https://github.com/ElektraInitiative/libelektra/blob/d57703bd1eaff0626fcfa8290773d68832085c4f/src/libs/opts/opts.c#L973-L990
and
https://github.com/ElektraInitiative/libelektra/blob/d57703bd1eaff0626fcfa8290773d68832085c4f/src/libs/opts/opts.c#L892-L904

If `argString` is not overwritten in the following `if`, freeing `argString` later will lead to a `free(): invalid pointer` because `argString` does not point to allocated memory.

**Comment by markus2330** [comment]
Thank you for reporting&fixing, good catch! :heart:
