### ISSUE TITLE
Analyse how to implement notifications for Java binding

### ISSUE THREAD

**Issue by tucek** [ElektraInitiative/libelektra#4441]
Notification are currently only tested with C/C++. Devise an approach how to enable the feature for users of the Java binding. (also see #2786)

**Comment by markus2330** [comment]
Yes, this is an important topic if you need synchronization code whenever config changes. Funnily, yesterday I came across a situation where I need it in one of my projects.

The first step would be to allow to pass a contract to internalnotification that calls a callback whenever config below/of a specific key changes. Once this works, the rest should be easy, as a user could rebuild the other features internalnotification has in Java.

If internalnotification makes more trouble than what it can do, it would also be possible to reimplement the internalnotification plugin in Java. This might, however, create different troubles as the plugin is in a different process as the app. Then you would need some out-of-process communication.

**Comment by markus2330** [comment]
Yes, it is worth a try. The issue is unfortunately not so easy as it looks like. But difficult to say without anyone trying it.
