### ISSUE TITLE
Clarify when/if to use elektraGetOpts

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4443]
> How would using gopts help with making it work properly?

There is already one reason above (externally accessible spec). Other reasons are:
- IIRC `elektraGetOpts` does not consider `meta:/default` at all.
- `elektraGetOpts` definitely doesn't handle any other spec like e.g. `meta:/type`
- AFAIK `kdb`'s profile feature can be used to set default arguments within the KDB. That would automatically be handled correctly with `gopts`, since it would load the `proc:/` keys at the right moment for all spec validation to work correctly (at least on `new-backend` it will) and a cascading lookup would return the correct key for everything.

_Originally posted by @kodebach in https://github.com/ElektraInitiative/libelektra/issues/4438#issuecomment-1222282087_

I think this should be clearly stated in the docu of elektraGetOpts. Otherwise people might use elektraGetOpts "by accident" as they might not know about gopts.

@kodebach can you take this issue?

**Comment by kodebach** [comment]
The tutorial for command line options already recommends `gopts` and only briefly explains how to use `elektraGetOpts`. It also explains the downsides of doing so. The doxygen comment of `elektraGetOpts` does not directly mention `gopts`, but it refers to the tutorial.

What exactly should we improve here? IMO this is again more of a discoverability issue not an issue with actual docs content.

**Comment by markus2330** [comment]
> The doxygen comment of elektraGetOpts does not directly mention gopts

This should be changed. It should recommend to use gopts, with the reasons you outlined.

> IMO this is again more of a discoverability issue not an issue with actual docs content.

Yes, it is a discoverability issue, thus it should be mentioned in elektraGetOpts. We should also mention it in the dev guide for application developers #4436.
