### ISSUE TITLE
[new-backend] highlevel API updates

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#4445]
Just an idea, based on #4442, #4444 and the new mount tooling in C.

When all this is done, the high-level API should by default use the new mountpoint contract and the "symbol" mode of `specload` and we should also generate C code for creating all mountpoints for the application. The goal would be that an app written with the high-level API codegen, runs standalone without installation (at least for command line args). The app should also have a command-line flag for mounting, so that installing is just: move `app` to install dir and run `./app --elektra-mount`

**Comment by markus2330** [comment]
Great idea :rocket: 

@kodebach did you consider to use the high-level API for `kdb`? I mean for its configuration, not for doing its job with KDB (the second part we already discussed earlier). Then this issue would be more important...

An obvious disadvantage would be that `kdb` depends on more libs...

**Comment by kodebach** [comment]
I'm not 100% sure `kdb` is the best candidate for using the high-level API. But it could be worth I try, if @hannes99 wants to invest the time.
