### ISSUE TITLE
rework DESIGN/CODING

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4453]
- no thread-local variables (like errno)
- no global variables
- only work on our non-const data structures (passed as first argument?)
- explain what `const` means in the API (no publicly visible modifications, but internal modification possible) see #4473

**Comment by markus2330** [comment]
@kodebach is this task something you want to do?

**Comment by kodebach** [comment]
No, why would I? Except for the bit about `const` it's not related to the API or anything else I've worked on.
