### ISSUE TITLE
latest latex version fails to produce pdf

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4455]
@lukashartl is it possible that we lack some Doxygen/LaTeX dependency?

Build for master and all PRs where I tried, e.g. #4440 #4448, fail but I cannot reproduce it locally: the pdf (2378 pages) builds successfully.

I tried to disable l1 and restarted a job but it doesn't seem to be specific to l1.

**Comment by atmaxinger** [comment]
That's funny, because it worked yesterday evening after the downtime.

**Comment by atmaxinger** [comment]
Okay, so locally on my system, building the PDF also works.

But if I build it in the same docker image the Jenkins uses, it fails - in that way it's reproducable. 
Somehow while generating the PDF it seems to go into an interactive mode and awaits user input, but Jenkins can't deliver it so it fails.

**Comment by atmaxinger** [comment]
Okay, funny thing ...

The error seems to be located in the generated latex file `group__keyname.tex` on line 853. What's funny is, that the locally generated file (right) has different content than that one generated in the Docker container (left). 

![grafik](https://user-images.githubusercontent.com/5960633/187954990-63eea0a1-0516-43c9-a8af-bf76f088281c.png)

**Comment by markus2330** [comment]
Thank you very much for investigating! :detective: 

Looks very much like that the one version of Doxygen produces a syntax-error in its output.

What are the Doxygen versions locally and in the Docker container?

I have Doxygen 1.9.1 (Debian stable), where the docu builds successfully.

Is the problem already reported upstream (in Doxygen)?

To fix the problem, we shouldn't use base doc.Dockerfile on Debian sid (scripts/docker/debian/sid/doc.Dockerfile) but rather on Debian stable (or something else stable). This makes failures due to dist-upgrades much less likely. I think the reason why the container is based on sid is obsolete long time ago (there was some feature in Doxygen we needed not available in Debian stable at that time.)

**Comment by atmaxinger** [comment]
Yes it works with debian stable in the docker container! I will create a PR for it.

**Comment by markus2330** [comment]
I made a report in https://github.com/doxygen/doxygen/issues/9567 but unfortunately without any minimal example etc.

@atmaxinger if you can provide more info in this issue, please do so directly in the issue. (Some questions above you did not answer, e.g., the local and the sid version of Doxygen)

Not reporting such issues can bite yourself badly: then we might get a broken Doxygen in the next Debian stable release.

**Comment by atmaxinger** [comment]
I'm working on a minimal sample. The Doxygen version is 1.9.4. Currently trying to find out which `.c`-file is responsible for creating `group__keyname.latex` and which Doxygen paramters are used by the build.

**Comment by markus2330** [comment]
@atmaxinger there is actually no urgency the triage (finding a minimal working example) can also be done later by someone doing FLOSS. It is actually a very nice exercise.

Hint for who will do it: group__keyname is probably related with the the group defined in src/libs/elektra/keyname.c

**Comment by atmaxinger** [comment]
I actually already created a sample. You can run `run.sh` to reproduce it on Debian Sid, on Debian Bullseye it works fine. 

HOWEVER it seems more to do with LaTeX than Doxygen, as the files generated by Doxygen on Bullseye also show the same behaviour with `pdflatex` on Debian Sid.

[sample.zip](https://github.com/ElektraInitiative/libelektra/files/9484340/sample.zip)

**Comment by markus2330** [comment]
Great job, please report to https://github.com/doxygen/doxygen/issues/9567

**Comment by markus2330** [comment]
Next points to check are if other LaTeX compilers also fail (XeLaTeX and LuaLaTeX).

Furthermore, we could try to simplify LATEX_CMD_NAME, which probably does not need to be set by us, see also https://github.com/doxygen/doxygen/issues/9567

**Comment by kodebach** [comment]
I suspect this is an issue with one of the `texlive` packages on Debian Sid rather than a `pdflatex` issue. The question is just which of the packages is the problem, so that we can report the problem.

I generated the LaTeX files (for the `elektra-sample.zip` example) with `doxygen` in a `debian:sid` Docker Container. Running `pdflatex` fails in the container, as described above. But if I know run `pdflatex` on my Manjaro host system on the exact same files, everything works fine. Both systems use the same version of `pdflatex`:

```
# debian:sid
pdfTeX 3.141592653-2.6-1.40.24 (TeX Live 2022/Debian)
kpathsea version 6.3.4
Copyright 2022 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.04

# Manjaro host
pdfTeX 3.141592653-2.6-1.40.24 (TeX Live 2022/Arch Linux)
kpathsea version 6.3.4
Copyright 2022 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.12; using zlib 1.2.12
Compiled with xpdf version 4.03
```

The `zlib` and `xpdf` versions are different, but AFAICT that shouldn't matter since the problem is not with the generation of the PDF, but the parsing of LaTeX.

**Comment by markus2330** [comment]
@kodebach you might be right about the cause but it is irrelevant: still it is better to first exclude possibilities that are easy to check (latex compiler) and then continue to investigate possibilities more difficult to check. Your method did not exclude the possibility that it is the fault of the latex compiler. E.g. it is possible that one patch applied by Debian causes the problem, so even exact same version information does not tell the whole story.

Anyway, there is absolutely no urgency in this issue (blockers of new-backend on the other hand is urgent right now) and this issue is nice for FLOSS, so please let us withhold any further investigations or bug triaging :wink:

**Comment by kodebach** [comment]
This issue blocks **all** PRs so I would say it is actually urgent. But yes it's nice for FLOSS so let's leave it.

Maybe we should disable PDF generation for now, or at least move it to a later stage in the Jenkins pipeline so we can ignore the failure and still have all other checks run.

**Comment by atmaxinger** [comment]
> This issue blocks **all** PRs so I would say it is actually urgent.

Strongly disagree here. This issue has been fixed by not using Debian Sid to generate the PDF. PRs into master should work fine now.

**Comment by kodebach** [comment]
Okay sorry, I missed that because the PRs linked in the top post still fail. But it seems they were not rerun after the fix
