### ISSUE TITLE
reconsider installation of useless plugins

### ISSUE THREAD

**Issue by haraldg** [ElektraInitiative/libelektra#447]
According to @markus2330 the plugins doc and template only make sense in the source tree. So maybe they shouldn't be part of ALL or shouldn't be installed in the system?

**Comment by markus2330** [comment]
Yes, we can remove them from installation.
I think, however, they should compile on the buildserver (the build server uses ALL) to be sure that they continue to compile after any changes.

**Comment by markus2330** [comment]
I think we should do that later to prioritize.

**Comment by markus2330** [comment]
So the solution now is that neither doc nor template will be built by default (they were tagged as experimental, which will be excluded by default).
