### ISSUE TITLE
rework key names examples to follow guidelines

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4472]
- [ ] should only use singular (not yet written as rule in doc/help/elektra-key-names.md, please add it there)
- [ ] should only use hierarchy separator for separation

e.g.:

- [ ] doc/help/elektra-key-names.md num_processes -> process/num; hosts -> host

**Comment by kodebach** [comment]
> num_processes -> processes/num

`processes` is definitely plural. With `num_processes` you could argue that it stands for "number of processes" which is singular....

**Comment by markus2330** [comment]
> processes is definitely plural.

Good catch! :1st_place_medal: 

> With num_processes you could argue that it stands for "number of processes" which is singular....

num_process(es) is not allowed as it uses a different separator (other than /).

**Comment by flo91** [comment]
@markus2330 Seems like a good issue for the FLOSS course.

**Comment by markus2330** [comment]
Yes, absolutely!
