### ISSUE TITLE
Have a way to say that all errors in a function should be emitted as a warning

### ISSUE THREAD

**Issue by atmaxinger** [ElektraInitiative/libelektra#4475]
We should have a way to say that all errors in a function should be emitted as a warning. 
This was originally proposed by @kodebach and @markus2330 in this discussion: https://github.com/ElektraInitiative/libelektra/pull/4471#discussion_r974358735

**Comment by kodebach** [comment]
Not necessarily just in a function, but in a section of code, i.e. enabling/disabling a mode where all errors are converted to warnings.

**Comment by flo91** [comment]
@markus2330 Do you think this issue should be offered for the FLOSS course?

**Comment by markus2330** [comment]
No, if the design is not decided yet it doesn't make sense to offer it for FLOSS.

**Comment by markus2330** [comment]
@atmaxinger is this still relevant? Can we close this?

**Comment by atmaxinger** [comment]
I think it is kind of relevant still, yes. But not of very high importance. It's probably enough if we provide a semi-official API to set and remove such a dummy variable, as can be seen in the linked PR.

**Comment by markus2330** [comment]
I don't like semi-official API. Either it is part of the plugin API or not :wink:
