### ISSUE TITLE
introduce new namespace for generic data structures

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4478]
Introduce a new namespace and fix all places where cascading namespaces are used as generic data structure.

> Which places [use cascading keys]?

@kodebach wrote:

---

With a quick search I found:

- `src/libs/opts/opts.c`: Yes, I know I wrote that code, but I didn't have anything else to use. The way `opts` works and passes data between processing steps, it definitely needs a hash map. I'm not 100% certain we need the full hierarchical structure of a `KeySet`. Maybe this use could be replaced with another hash map implementation. It is certainly easier with a `KeySet` since most data in `opts` is based around key names.
- `src/libs/pluginprocess/pluginprocess.c`: Uses `KeySet` as a basic key value structure that can be serialised and transferred to another process. Kind of irrelevant because this lib is obsolete.
- In various places, a cascading key (often `keyNew ("/", KEY_END)`) is used as an `errorKey`. I don't really have a good alternative here apart from randomly choosing another namespace.
- Many plugin tests use cascading keys for config or testdata. In most cases I don't even understand why. For example, there is a `kconfig` test that expects cascading keys to be returned from the plugins `get` function.

_Originally posted by @kodebach in https://github.com/ElektraInitiative/libelektra/issues/4415#issuecomment-1202319672_

**Comment by kodebach** [comment]
I propose `data:/` as the name for this namespace.

Just adding the namespace should be pretty simple, IIRC we only need:
- Add `KEY_NS_DATA` to the enum
- Update `keySetNamespace` and `elektraReadNamespace`
- Add tests to `test_keyname.c`
- Update the various `switch` statements that use the `KEY_NS_*` constants (search for e.g. `ELEKTRA_NS_NONE` to find them)

@markus2330 Might be worth adding this as a FLOSS issue. At least the part about introducing the new namespace. Updating uses of cascading and preventing casacading to be inserted into keysets is probably too much.

**Comment by markus2330** [comment]
For a project also the updates should be doable.
