### ISSUE TITLE
add const to KeySet argument of ksLookup/ksSearch

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4480]
There were 2 reasons why the KeySet was not const:

1. `KDB_O_POP` could remove a key and `KDB_O_CREATE` could create a key
2. We may create a key from `meta:/default`

When all three 3 reasons disappear, we can add const.

For lengthy discussion see  #4473

New signature:

```
    Key * ksLookup (const KeySet * ks, const Key * key, elektraLookupFlags options);
```

**Comment by kodebach** [comment]
Might be worth a separate issue, but the `Key *` argument should also be `const`. It may be temporarily modified, but when `ksLookup` returns the `key` should be identical to before.

Also something along the lines of this should be added to the API docs of `ksLookup`:
"This function will cast the provided `const Keyset * ks` to `Keyset * ks` and `const Key * key` to `Key * key`. Both `ks` and `key` may be modified. Any modification made is purely internal and does not affect the outcome of any public API functions called after this functions returns."

**Comment by flo91** [comment]
@markus2330 Do you think this issue is suited for the FLOSS course?

**Comment by markus2330** [comment]
@flo91 yes, it is fine. But we already have too many C issues. We probably need more in other languages (Java etc.)
