### ISSUE TITLE
[new-backend] kdb mount: remember passed mount-commandline

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4494]
When backends/plugins get upgraded, the same mount command might produce a different result. A very easy approach to allow remounting on backend upgrades would be that we remember in `system:/elektra/mountpoints/\/<name>/plugins/backend/cmd` which command the user typed. On upgrades, `kdb remount-all` is executed, which executes all these commands, then all spec-mounts etc. are up-to-date.

(The alternative would be to deserialize `system:/elektra/mountpoints/\/<name>/definitions/` but then we would need to keep code to deserialize every version we ever might produce.)

@flo91 @kodebach What do you think?

**Comment by markus2330** [comment]
This proposal would also fix #1306

**Comment by kodebach** [comment]
The key should be called `system:/elektra/mountpoints/<name>/kdbcmd` or maybe `system:/elektra/mountpoints/<name>/kdb/cmd`.

It doesn't really have anything to do with the backend plugin. All plugins in `system:/elektra/mountpoints/<name>/plugins/*` are meant to have the same structure.

> The alternative would be to deserialize `system:/elektra/mountpoints/<name>/definitions/` but then we would need to keep code to deserialize every version we ever might produce

A complicated solution to say the least. `definitions` is also specific to the backend plugin, so this would fall under the backend plugins obligation.

It also doesn't cover the case of e.g. `kdb mount .... ini` where a plugin is selected based on `infos/provides`.

I think storing the `kdb mount` command is the best solution for most cases. Of course it doesn't help if a mountpoint was created without `kdb mount`, but we can't really help there.

**Comment by markus2330** [comment]
What about `system:/elektra/mountpoints/<name>/command/create`? I don't think we should mention `kdb` as actually the mount library can be used from other applications too. Maybe we have further commands in future, so I would definitely add a `/` to separate. And I prefer command over cmd.

**Comment by kodebach** [comment]
> I don't think we should mention kdb as actually the mount library can be used from other applications too.

But I thought you wanted to store the `kdb mount` command that was used.

Of course if the new mount tools have an API with input that can be serialized, we can store that input instead. But until the library is done, I'm not sure what name would be best. It might even turn out that we need more than one key to store the input.

So if you want a quick solution, I would maybe store the exact `kdb mount` call (i.e. the full `argv` so it can be passed to e.g. `execv`) in `system:/elektra/mountpoints/<name>/command/kdbmount`. If we find a more general way to store that, we can just add some code to `kdb mount` that removes the existing key and writes the new one. Then the next `kdb remount-all` would migrate to the new format.

**Comment by markus2330** [comment]
Yes, I thought from usability point of view it should be a  `kdb mount` as used on the command-line. Obviously this only works if the API must is very similar to the arguments of `kdb mount`.

If @flo91 has different ideas, a different name might be better suited.

Anyway, the approach also must work for mountpoints mounted by other tools (qt-gui etc.).
