### ISSUE TITLE
lua plugins depends on lua 5.2 but doesn't detect so

### ISSUE THREAD

**Issue by haraldg** [ElektraInitiative/libelektra#450]
lua.cpp uses LUA_OK, which was only defined in 5.2. however cmake will try to build the plugin if an older version of lua is installed.
(No idea why OpenWRT is still stuck with lua 5.1.5 ...)

I'm manually disabling the lua plugin to avoid triggering a build error should lua happen do be selected, so this is no big deal.

**Comment by markus2330** [comment]
Thanks for reporting!

Maybe LUA_OK is the only problem, then we maybe can support lua 5.1?

Otherwise, we should state the dependency correctly in cmake.

**Comment by haraldg** [comment]
Yes, LUA_OK is the only error that is reported. However 5.2 came out 4 years ago, so I wouldn't bother too much.

**Comment by markus2330** [comment]
I think the lua bindings would fit nicely for OpenWRT. Do they have any plans to update?

**Comment by haraldg** [comment]
Yes, it's this odd thing you get when you are forking a project instead of building consensus, that the only scripting language used by OpenWRT aside from shell, will be the only binding we won't be able to use there (just successfully compiled the python plugins, which have been the last ones on my list).

I don't know about their plans, however this mail suggest that they are quite unhappy with 5.2:
https://lists.openwrt.org/pipermail/openwrt-devel/2012-January/013572.html

However at least there appears to be some work towards 5.2:
http://git.openwrt.org/?p=project/uci.git;a=commit;h=b121dd18280895cd57ba2b904acde614e13b6680

**Comment by manuelm** [comment]
If the only thing that's missing adding the `LUA_OK`-macro I'll accept such a PR. However I can and won't test Lua 5.1, nor will I work on related bug reports (of any sort).

**Comment by markus2330** [comment]
Debian stable still has lua5.1 (as option), so I can take a look without too much trouble.
Btw. Directly writing lua code in spec/ (as meta data) sounds like a nice option for some simple tasks.

**Comment by markus2330** [comment]
I will keep it open for LUA_OK-investigation.

**Comment by markus2330** [comment]
Iterators seem to be broken:
```
71: /usr/bin/lua: .../current/src/bindings/swig/lua/tests/test_keyset.lua:59: bad argument #1 to 'ipairs' (table expected, got userdata)
```

Otherwise it compiles and runs with lua 5.1

**Comment by manuelm** [comment]
Lua 5.2 specific feature: http://www.luafaq.org/#T8.2.6

**Comment by haraldg** [comment]
Finally I got an OpenWRT package for the lua plugin compiled.
I think this issue can now be closed.

**Comment by markus2330** [comment]
Thanks for the confirmation!
