### ISSUE TITLE
http -> https links

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4502]
There are still plenty of http links within our repository, they should be replaced with https links. (The link checker will tell if some of these sites are actually not available via https.)

**Comment by kodebach** [comment]
Couldn't we also extend the link checker to check that all links are https links?

**Comment by flo91** [comment]
> Couldn't we also extend the link checker to check that all links are https links?

Sounds like a good idea! 👍🏻 
If some site still needs http, the link could be added to the whitelist.
The issue #4454 could also be interesting for people working on this issue.

**Comment by markus2330** [comment]
Extending the link checker is a separate issue, though.

**Comment by kodebach** [comment]
> Extending the link checker is a separate issue, though.

See #4524

**Comment by kodebach** [comment]
> Run `grep -r --include="*.md" http: . ` in the project root.

Why just markdown files? I also found some code comments with HTTP links (even `http://www.libelektra.org`).

**Comment by Eiskasten** [comment]
There is no particular reason for that, I just assumed that. So for a proper reproduction `grep -r --exclude-dir="cmake-build*" http: .` might be enough in most cases.

**Comment by markus2330** [comment]
@Eiskasten Did you link the PR with this issue? What is open here?

**Comment by Eiskasten** [comment]
I added the link to the PR. If the CI succeeds, it can be merged from my point of view.
