### ISSUE TITLE
l1: too little memory

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4503]
https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-4492/22/pipeline

```
Cannot contact l1: java.lang.InterruptedException

The message received from the daemon indicates that the daemon has disappeared.

Build request sent: Build{id=9b3cc270-65cc-4bab-a612-9b89ee7cbecd, currentDir=/home/jenkins/workspace/libelektra_PR-4492/build/src/bindings/jna}
...
FAILURE: Build failed with an exception.



* What went wrong:

Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
```

@lukashartl is this l1 specific (not enough memory etc.) or some error with Gradle?

**Comment by markus2330** [comment]
Ok, it is quite clear: too little memory on l1. I am taking l1 off.

https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-4492/24/pipeline

```
c++: fatal error: Killed signal terminated program cc1plus
```

**Comment by kodebach** [comment]
Would be interesting to know how much memory we actually need for building.

For `l1` we could try using `make -j1`. Running one thing after another should use less memory.

**Comment by lukashartl** [comment]
I've already increased RAM to 12GB, that should suffice. I'll mark it (l1) online once I've successfully run a test build.

@kodebach I totally agree with having some well documented and sensible system/builder requirements.

**Comment by kodebach** [comment]
I was thinking more about requirements for running compiling. Not just in a build server environment, but for compiling Elektra in general. If that really needs 12GB of RAM (even with `make -j1`) that would be pretty high IMO.

> compilers change constantly, probably only asking for more most of the time

Compiler programmers are smart people. I would hope they only ask for what the really need, but will take anything they can get, if it speeds up compilation, e.g. it works with 1 GB, but if there is more available the compiler uses more for extra caches.

**Comment by markus2330** [comment]
> I was thinking more about requirements for running compiling. Not just in a build server environment, but for compiling Elektra in general. If that really needs 12GB of RAM (even with make -j1) that would be pretty high IMO.

This is unrelated to Elektra. RAM usage of compilers is a requirement for compilers.

**Comment by tucek** [comment]
I think this is due to the gradle daemon leaking over time. I see this from time to time on our build server too...

**Comment by kodebach** [comment]
Hm that would be easy to test. Just add `org.gradle.daemon=false` to `gradle.properties`.
