### ISSUE TITLE
[FLOSS H0] Improve getting started

### ISSUE THREAD

**Issue by stefnotch** [ElektraInitiative/libelektra#4508]
I was checking out the GitHub repository and tried to do the steps in the getting started guide: https://github.com/ElektraInitiative/libelektra/blob/master/doc/GETSTARTED.md

After struggling through it, I figured I'd comment on which parts I'd love to see ever so slightly expanded

> but it's also possible to use Windows which is supported but not yet fully tested.

It'd probably be nice to link to https://www.libelektra.org/tutorials/contributing-with-visual-studio-windows there. And linking to https://www.libelektra.org/tutorials/contributing-with-clion might also make sense.

> kdb run_nokdbtests

I was executing the steps in the WSL, using an Alpine Linux distribution. (SSD space is sadly not infinite, so I figured starting with a lightweight distro would be the easiest way of getting started.)

There, I ran into https://github.com/ElektraInitiative/libelektra/issues/4122
Output:
```
STEFNOTCH-PC:~$ kdb
Usage: kdb <command> [args]

kdb is a program to manage Elektra's key database.
Please run a command with -H or --help as args to show a help text for
a specific command.

Known commands are:
Sorry, I have a severe problem, it seems like I am not installed correctly!
kdbOpen() failed with the info:
 Sorry, 1 warning was issued ;(
 1: Module kdb issued the warning C01200:
        Installation: Dlopen failed. Could not load module libelektra-resolver.so. Reason: Error loading shared library libelektra-resolver.so: No such file or directory
        Mountpoint: /
        Configfile:
        At: /root/libelektra/src/libs/loader/dl.c:90
Sorry, module kdb issued the error C01200:
Installation: Could not open default backend. See other warning or error messages for concrete details
Mountpoint: /
Configfile:
At: /root/libelektra/src/libs/elektra/kdb.c:453

Please report the issue at https://issues.libelektra.org/STEFNOTCH-PC:~$
```

The tutorial on the website does have a fix for this (The troubleshooting section at https://www.libelektra.org/tutorials/contributing-with-clion ). It did take me a while to find that, and I'm not entirely sure how common that issue is. Depending on the answer, it might be useful to either directly note down what to do, or to link to the troubleshooting section.

I'm open to creating a pull request that fixes those issues.

**Comment by markus2330** [comment]
> After struggling through it, I figured I'd comment on which parts I'd love to see ever so slightly expanded

Great idea! This is actually FLOSS H1, though. But as you also asked good questions, we can also count it as FLOSS H0.

> It'd probably be nice to link to https://www.libelektra.org/tutorials/contributing-with-visual-studio-windows there. And linking to https://www.libelektra.org/tutorials/contributing-with-clion might also make sense.

Maybe we can redesign them that general knowledge about Windows/WSL is in its own tutorial? This could be a FLOSS T3 task.

> It did take me a while to find that, and I'm not entirely sure how common that issue is.

If you don't install Elektra (running from build directory), it will actually always be like this. This is also documented in doc/TESTING.md

For installed Elektra it is depending on the distribution and which CMAKE_INSTALL_PREFIX you choose. (Every distribution has a few CMAKE_INSTALL_PREFIX, e.g. / and /usr, sometimes /usr/local and /opt, where it will work out-of-the-box).

Anyway, this troubleshooting should also be somewhere in the getting started (where scripts/dev/run_env should also be mentioned), as it is actually totally unrelated to CLion.
