### ISSUE TITLE
Update clang-format version

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#4518]
clang-format version 15 has been released. We still use version 13 (see `scripts/dev/reformat-c`). At some point we should update. This will probably involve a bigger reformatting PR.

**Comment by mpranj** [comment]
Clang format 14 is not yet on Debian Sid, which we use in the CI for the formatting check…Should we switch to a different container?On 07.10.2022, at 16:18, Klemens Böswirth ***@***.***> wrote:﻿
clang-format version 14 has been released. We still use version 13 (see scripts/dev/reformat-c). At some point we should update. This will probably involve a bigger reformatting PR.

**Comment by kodebach** [comment]
At least the online package search says that the current `clang-format` on Sid is version 14: https://packages.debian.org/sid/clang-format

And there is also a separate package for version 15: https://packages.debian.org/sid/clang-format-15

> Should we switch to a different container?

Might be a good idea to use a separate container for formatting and similar checks that contributors may want to run locally (spelling, release notes, clang-tidy #4517, etc.). Keeping that container small would make that much easier. 

The Alpine Linux Package for clang-format is also already on version 15.0.2 (released this week). I think a small alpine container would be ideal here.

**Comment by markus2330** [comment]
Switching clang-format is a task shortly before a release (to minimize necessary rebasing of PRs), so let us have a look at the situation when it is time.

**Comment by kodebach** [comment]
Could also be done right after merging`new-backend`. But I mainly created the issue so we don't forget to do it, not because it is urgent.

**Comment by markus2330** [comment]
It cannot really be forgotten totally. I don't think we need to create issues as long as there is no depreciation warning or it is getting difficult to install. If we skip some releases, we have less effort.

**Comment by kodebach** [comment]
Honestly please answer this question: "WHY do you hate issues so much?" Having an issue clearly signals there is something to be done. Especially, in a case like this, where it can't be solved immediately.

Waiting until there is a problem is not even a good solution here, because then the change would be urgent and can't just be done when it is convenient.

**Comment by markus2330** [comment]
Like everything, issues can be misused. We are **currently** writing too much text in issues and too little text in our repo. Of course it is also my fault, not having time to create PRs of what others write in issues (as I used to do). What you might misinterpret of me hating issues is me loving a beginner-friendly Elektra. Issues is a terrible way of documentation for beginners (too much to read, get too long/off-topic, unstructured, unclear which statements are outdated/accepted/reviewed and so on), so I urge everyone to write more PRs writing more beginner-friendly documentation. This does not mean that issues don't have their place. If something is wrong, please report an issue. Just that something **could** be updated is imho not needed to be reported.

**Comment by markus2330** [comment]
Btw. an example for a useful issue is that the currently used clang-format formats something incorrectly and clang-format-15 would solve this.

**Comment by kodebach** [comment]
These last two comments and even more so the fact that you renamed the issue, just tell me that you have zero concept of how issue can be used properly. The first comment added zero information to the discussion about clang-format, so don't complain about issues having unrelated information. If you want to change what an issue is about, sure rename it. But only if the new topic is at least somewhat related. Also please update the issue description in the first post. Having an issue "Usage of issues" that then only talks about clang-format in the first post is all but beginner-friendly.

I hid your comments and this one and created #4557.

**Comment by markus2330** [comment]
Updating clang is done regularly by @mpranj before the releases, no issues are needed for this. Release notes are our way to communicate that such a change happened.
