### ISSUE TITLE
testscr_check_formatting stashes staged changes

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#4519]
https://github.com/ElektraInitiative/libelektra/blob/930673f511c864ffd6233b7ab3e1a438c5a9b378/tests/shell/check_formatting.sh#L91-L94

While there is a note, the note is incorrect. Staged changes are also stashed, even if all formatting is correct. I think this check

https://github.com/ElektraInitiative/libelektra/blob/930673f511c864ffd6233b7ab3e1a438c5a9b378/tests/shell/check_formatting.sh#L14-L17

should instead be

```sh
if ! git diff --quiet || ! git diff --cached --quiet; then
	printf >&2 'Source is already modified, aborting test!\n\n'
	exit 0
fi
```

**Comment by markus2330** [comment]
Thank you for reporting this problem!
