### ISSUE TITLE
Issues compiling elektra on OpenBSD 5.8

### ISSUE THREAD

**Issue by tom-wa** [ElektraInitiative/libelektra#452]
* OpenBSD doesn't use/know EBADMSG
```
/home/thomas/libelektra/src/plugins/resolver/resolver.c: In function 'elektraAddErrnoText':
/home/thomas/libelektra/src/plugins/resolver/resolver.c:278:20: error: 'EBADMSG' undeclared (first use in this function)
  else if (errno == EBADMSG)
                    ^
/home/thomas/libelektra/src/plugins/resolver/resolver.c:577:12: error: 'EBADMSG' undeclared (first use in this function)
    errno = EBADMSG;
            ^
```

* OpenBSD doesn't have librt
should be 
```
if (UNIX AND NOT APPLE AND NOT ${CMAKE_SYSTEM_NAME} MATCHES "OpenBSD")
	set(CMAKE_REALTIME_LIBS_INIT rt)
endif()
```
in cmake/ElektraCompiling.cmake

**Comment by markus2330** [comment]
Thanks for reporting! These are really easy fixes then! (EBADMSG was chosen arbitrary, we can take any other value not issued by the syscalls in questions, too)

**Comment by markus2330** [comment]
@petermax2 Do you have OpenBSD installed?

**Comment by petermax2** [comment]
@markus2330 I have an OpenBSD VM somewhere

**Comment by petermax2** [comment]
Found another issue on OpenBSD (tried to compile a67c05505552c57861125c3ed4bf26cda7553fdc )

	[  1%] Building CXX object src/error/CMakeFiles/elektra-export-errors.dir/exporterrors.cpp.o
	cc1plus: warning: -Wuninitialized is not supported without -O
	In file included from /home/pnirschl/elektra/src/error/exporterrors.cpp:9:
	/home/pnirschl/elektra/src/error/parser.hpp:29: error: expected ';' before 'override'
	/home/pnirschl/elektra/src/error/parser.hpp:33: error: expected `;' before '}' token
	/home/pnirschl/elektra/src/error/parser.hpp: In constructor 'parse_error::parse_error(std::string, int)':
	/home/pnirschl/elektra/src/error/parser.hpp:22: error: 'move' is not a member of 'std'
	/home/pnirschl/elektra/src/error/exporterrors.cpp: In function 'int main(int, char**)':
	/home/pnirschl/elektra/src/error/exporterrors.cpp:281: error: 'to_string' was not declared in this scope
	/home/pnirschl/elektra/src/error/exporterrors.cpp:284: error: no matching function for call to 'std::basic_ofstream<char, std::char_traits<char> >::basic_ofstream(std::string&)'
	/usr/include/g++/fstream:594: note: candidates are: std::basic_ofstream<_CharT, _Traits>::basic_ofstream(const char*, std::_Ios_Openmode) [with _CharT = char, _Traits = std::char_traits<char>]
	/usr/include/g++/fstream:578: note:                 std::basic_ofstream<_CharT, _Traits>::basic_ofstream() [with _CharT = char, _Traits = std::char_traits<char>]
	/usr/include/g++/iosfwd:92: note:                 std::basic_ofstream<char, std::char_traits<char> >::basic_ofstream(const std::basic_ofstream<char, std::char_traits<char> >&)

**Comment by markus2330** [comment]
Seems like gcc does not support C++11. Do you use a recent version of gcc and OpenBSD?

**Comment by petermax2** [comment]
Don't use the words "recent" and OpenBSD together. ;) I did a freh install of OpenBSD 5.8 today.

**Comment by tom-wa** [comment]
you have to use egcc/eg++  and libestdc++ on OpenBSD 5.8, the "normal"/non-e-versions are too old.

**Comment by petermax2** [comment]
@tom-wa thx! I'll try

**Comment by petermax2** [comment]
I changed the error number to `EINVAL` which should have better availability.

If we solve the librt problem with

    if (UNIX AND NOT APPLE AND NOT ${CMAKE_SYSTEM_NAME} MATCHES "OpenBSD")
        set(CMAKE_REALTIME_LIBS_INIT rt)
    endif()

what about other systems that do not have a librt? Is there a more general way in CMake to find out if `-lrt` is working on the system?

**Comment by petermax2** [comment]
Maybe we use a `TRY_COMPILE` in conjunction with `LINK LIBRARIES`?

**Comment by petermax2** [comment]
# check if native librt is available
    find_library(HAS_LIBRT "rt")
    if (HAS_LIBRT)
	    set(CMAKE_REALTIME_LIBS_INIT rt)
    endif()

seems to do the trick but I have to test it.

**Comment by markus2330** [comment]
Btw. regarding the earlier question: If you use a FindRT module such problems should already be handled internally.

If no such FindModule is present you can do that manually e.g. as done by @manuelm in cmake/ElektraCompiling.cmake line 39-43 to check if --version-script is a valid linker flag.

**Comment by petermax2** [comment]
@markus2330 do you prefer `check_cxx_compiler_flag` over `find_library`? I am not really sure which solution is better.

**Comment by markus2330** [comment]
I think `find_library` is not used correctly. The name of the library should be stored in the variable you pass. (But the value is not used.) See https://cmake.org/cmake/help/v3.0/command/find_library.html

Used correctly `find_library` would be the better option, because it would not force the `rt` lib to be called `rt`. (when we start to add HINTS and NAMES) Note that the `if` is still necessary, otherwise we would link against `-NOTFOUND`.

Can you take a peak at other projects that need to link against `rt`? Maybe there are even better solutions.

**Comment by petermax2** [comment]
The solutions around all look more or less like [https://github.com/civetweb/civetweb/blob/master/cmake/FindLibRt.cmake](https://github.com/civetweb/civetweb/blob/master/cmake/FindLibRt.cmake).

**Comment by markus2330** [comment]
Yes, it is certainly more elegant to have a dedicated Find module. Thanks for the research!

**Comment by petermax2** [comment]
OK I'll take over a BSD-licensed find-module as soon as I find the time for it.

**Comment by petermax2** [comment]
The FindModule mentioned before does not do much more than we do now. It uses `find_library`:

    find_library(LIBRT_LIBRARIES rt)

We do the same thing in `ElektraCompiling.cmkae`:

    find_library(CMAKE_HAS_LIBRT "rt")

I think there is not much more to it. Do you really think introducing a dedicated find module will be worth the effort?

**Comment by markus2330** [comment]
Yes, it is a clear interface, is expected there and allows us to share it between projects. So even if it is now basically a one liner, its better if its in own file. Once we need more  logic to add support for other systems we already have everything in place. Or asked differently: Why break the convention? There should be a good reason for it.

Btw. you do not have to rewrite it, if you find BSD-licenced module you can copy it from other projects.
