### ISSUE TITLE
[FLOSS H0] CMake Warning: Policy CMP0115

### ISSUE THREAD

**Issue by 0x6178656c** [ElektraInitiative/libelektra#4522]
## Steps to Reproduce the Problem

Preparing the build directory

```shell
mkdir build
cd build
cmake ..
```

prints a warning

```
CMake Warning (dev) at src/libs/pluginprocess/tests/CMakeLists.txt:16 (add_executable):
  Policy CMP0115 is not set: Source file extensions must be explicit.  Run
  "cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  File:

    /home/user/libelektra/src/libs/pluginprocess/tests/testlib_pluginprocess.c
This warning is for project developers.  Use -Wno-dev to suppress it.
```

## Expected Result

The configuration step should run without warning.

## Actual Result

The configuration step issues a warning. Note that deprecated features/syntax can be removed in later versions of CMake.

## System Information

- Elektra: master (930673f511c864ffd6233b7ab3e1a438c5a9b378)
- Operating System: Ubuntu 22.04.1 LTS
- CMake: 3.22.1

## Possible fix

Probably the problem can be fixed by changing

https://github.com/ElektraInitiative/libelektra/blob/930673f511c864ffd6233b7ab3e1a438c5a9b378/src/libs/pluginprocess/tests/CMakeLists.txt#L13

to

```cmake
		list (APPEND TEST_SOURCES ${file})
```

The CMake policy states that source files need to explicitly state their extension: <https://cmake.org/cmake/help/latest/policy/CMP0115.html>

Since I have no experience with CMake I am unsure whether there are other things to consider, though.

**Comment by markus2330** [comment]
Thank you for reporting this issue! The possible fix looks good to me.

**Comment by joni1993** [comment]
I experienced the same warning and the proposed fix makes the error go away - i have no experience with Cmake either though.

**Comment by markus2330** [comment]
> I experienced the same warning and the proposed fix makes the error go away - i have no experience with Cmake either though.

Thank you for doing the triage! (@flo91)

> But besides that there still are some other deprecation warning present (https://github.com/ElektraInitiative/libelektra/issues/3330#issuecomment-789762858)

This is an old post, we upgraded cmake minium version recently. I created #4603. Please create further issues if there you see other/more warnings.
