### ISSUE TITLE
[FLOSS H0] Ubuntu 22.04 Support

### ISSUE THREAD

**Issue by joni1993** [ElektraInitiative/libelektra#4526]
## Steps to Reproduce the Problem
see https://github.com/ElektraInitiative/libelektra/blob/master/doc/INSTALL.md - Ubuntu 20.04 section

## Expected Result
libelektra should install without errors on Ubuntu 22.04

## Actual Result
Using 20.04 repo in 22.04 shows the following dependency problems:
elektra-bin : Hängt ab von: libgit2-28 (>= 0.26.0) ist aber nicht installierbar
libelektra5-gitresolver : Hängt ab von: libgit2-28 (>= 0.26.0) ist aber nicht installierbar
libelektra5-python : Hängt ab von: libpython3.8 (>= 3.8.2) ist aber nicht installierbar
python3-elektra : Hängt ab von: libpython3.8 (>= 3.8.2) ist aber nicht installierbar

Available candidates: libgit2-1.1 and libpython3.9/libpython3.10

## System Information

- Elektra: 0.9.11-2 (Ubuntu 20.04 build)
- Operating System: Ubuntu 22.04

**Comment by markus2330** [comment]
Thank you for reporting this problem!

Afaik we don't have support for Ubuntu 22.04.1 LTS (Jammy Jellyfish) yet (only 18+20).

If you are interested, you can add support, either in T1 (task 3) or also H1/H2. If you want to do it, please assign yourself.

As probably others are interested in installing Elektra in Ubuntu 22.04 it would be great if this can be done asap :1st_place_medal:

**Comment by kodebach** [comment]
I have recently built Elektra myself on a Ubuntu 22.04 system. So the issue is probably only in the package definitions. It seems part of the issue is that we depend on exact versions of the packages. At least it looks that way to me. For example, we don't really need Python 3.8 specifically. Any new enough Python 3 should do.
