### ISSUE TITLE
[FLOSS H0] Integration into other lectures (question)

### ISSUE THREAD

**Issue by LoWesT1337** [ElektraInitiative/libelektra#4527]
Are there any plans to integrate this into other lectures to spread awareness and maybe get more contributions from students?

For example: It could be usefull to integrate it into exercises of Object Oriented Programming, since the weekly tasks are small and include small tasks with elektra could be helpful for students in the future.

**Comment by markus2330** [comment]
This is a great idea! FLOSS in software engineering education is a big topic, e.g. see https://dl.acm.org/doi/abs/10.1145/3266237.3266249

I already use FLOSS development principles for my second course [Configuration Management](https://tiss.tuwien.ac.at/course/courseDetails.xhtml?courseNr=194030). But I don't think there are currently any other courses at the TU Wien planning something like this. With two courses using FLOSS principles, the TU Wien is actually well placed.
