### ISSUE TITLE
update the figure in the api docs 

### ISSUE THREAD

**Issue by Cetzcher** [ElektraInitiative/libelektra#4531]
The figure used at https://doc.libelektra.org/api/master/html/ looks a bit outdated, we could maybe add some text to the logo  found on Github to convey the same information but make the docs look a bit more modern.

This is of course very nit-picky but when something looks nice the users a more likley to adapt certain things.

**Comment by markus2330** [comment]
Great suggestion!

The feature to add logos came with Doxygen 1.8.2 (upgraded 2012 in 3d7ec3c9d4c9ac716fdc5c528c0498c0ffd39679). Seems like we were all blind, nobody noticed it up to now. You are the first to report this!

This is actually a very nice&simple beginner task.  Logos are already in the repo: doc/images/logo/ and they only needed to be listed in PROJECT_LOGO in doc/Doxyfile

If you also want to fix this (H1 or H2), please assign yourself.

If you are interested in Doxygen, see also: #4455 and #4533

**Comment by kodebach** [comment]
I think this issue was more about changing the image weird image with the 3 (technically 4) balls (`doc/images/classes.png`).

**Comment by markus2330** [comment]
Yeah, these images can be updated too if someone has the artistic skills!

**Comment by Cetzcher** [comment]
@markus2330 Yes I would love to update the Image to a more modern look and feel, im no designer but I have some experience with gimp so sure. 

So I should continue using this issue instead of closing it (H0 states that) right? 
Also change the title to [H1 ...] and so on.

**Comment by markus2330** [comment]
For H2 no underlying issues are needed, so if you simply want to redraw this one image, no renaming of the issue needs to be done. You can simply assign yourself to this issue.

If you want to do a triage here (Which other images are used where in the docu and which might need update. It would be also interesting which images are not used at all.), you can continue to do the H1 task also here and later to the (bigger) H3 task.

You can also mix both variants (do the one image in H2, other cleanup tasks or improving of images in H3).

**Comment by Cetzcher** [comment]
looking through images and specifically redrawing the image mentioned by @kodebach

**Comment by Cetzcher** [comment]
So I looked through all of the .png, .svg and .jp(e)g images contained in this Repo. The only one that seemd to be out of date was the one previously mentioned in `doc/images/classes.png`. I will also check for unused images, however, I think un-referenced images are okay since we might want to show them in, for example presentation slides or something simmilar. Should we still create an issue to check these ? @markus2330

**Comment by Cetzcher** [comment]
will unassign myself from this since I sadly cannot participate in the course anymore, up for grabs

**Comment by deoknats861** [comment]
> The feature to add logos came with Doxygen 1.8.2 (upgraded 2012 in [3d7ec3c](https://github.com/ElektraInitiative/libelektra/commit/3d7ec3c9d4c9ac716fdc5c528c0498c0ffd39679)). 
> [...]
> Logos are already in the repo: doc/images/logo/ and they only needed to be listed in PROJECT_LOGO in doc/Doxyfile

I would like to take over this issue and do the quoted part of it (as I tend to do not have the necessary artistic skills for the redesign of the image..).

For me it is not quite sure what the expected outcome of this issue is:
-  The [doxygen doc](https://www.doxygen.nl/manual/config.html#cfg_project_logo) describes that the file will be included in the documentions automatically. Are further manual steps necessary?
- The same doc pages states that the project logo must be smaller than 200x55 pixels
  - Which logo from doc/images/logo/* should be used as project logo?
  - To which file format should the chosen SVG be converted? Should the ratio from logo to background be adapted (f.e. logo_elektra_color.svg would have a huge background in proportion to the writing)?
- Are there further tasks involving doxygen and images/logos for the documentation?

**Comment by markus2330** [comment]
> The same doc pages states that the project logo must be smaller than 200x55 pixels
> Which logo from doc/images/logo/* should be used as project logo?

Probably you need to resize one that matches with the needs of Doxygen. There are also logos in https://blobs.libelektra.org/

>  To which file format should the chosen SVG be converted? Should the ratio from logo to background be adapted (f.e. logo_elektra_color.svg would have a huge background in proportion to the writing)?

I leave this to your artistic skills. If it looks nice, it is perfect.

> Are there further tasks involving doxygen and images/logos for the documentation?

There are a few images which are not used at all, they can be removed (type-*, hp.jpg, link_buttin_1.gif ...)

Some images don't look nice, e.g. overview_libs.png, state.png could be redrawn with mermaid.js

To make mermaid available in Doxygen and our website, integration is needed, in a quick search I found e.g. https://github.com/tttapa/doxygen-mermaid

Doing this should be enough for the whole homework.
