### ISSUE TITLE
[FLOSS H0] Information for total newcomers

### ISSUE THREAD

**Issue by mwoelfer-tuwien** [ElektraInitiative/libelektra#4532]
I am wondering, if it is possible to better convey the gist of Elektra in the README/Homepage/Getting Started Page, as I needed atleast 1-2hours looking through the docs and website to get what Elektra is actually about. 

In my mind is a concrete scenario for better user understandability, something along the lines of "Imagine on your PC Operationg System that you have 3 possible entry points to change the resolution of your screen, and all of those 3 points for the settings change different internal settings (looking at you MS Windows), this would surely be annoying and lead to system failures. Elektra aims to solve this by providing a unified Interface for changing configurations in whole different types of system"

As I am far from an expert concerning FLOSS and especially Elektra, I don't even know if such an example presents the Gist, but I know for a fact, that something along those lines would have helped me a lot :)

**Comment by markus2330** [comment]
> I am wondering, if it is possible to better convey the gist of Elektra in the README/Homepage/Getting Started Page, as I needed atleast 1-2hours looking through the docs and website to get what Elektra is actually about.

For different people there are different views of Elektra, e.g. developers or sys admins. For me https://www.libelektra.org/docgettingstarted/vision is the best summary what Elektra is about but for e.g. Desktop users the picture is very different.

> In my mind is a concrete scenario for better user understandability, something along the lines of "Imagine on your PC Operationg System that you have 3 possible entry points to change the resolution of your screen, and all of those 3 points for the settings change different internal settings (looking at you MS Windows), this would surely be annoying and lead to system failures. Elektra aims to solve this by providing a unified Interface for changing configurations in whole different types of system"

Yes, absolutely. One of Elektra's goal is to provide a specification language where it is possible to unify such 3 different settings. This is part of the Desktop view. To write something like this in the documentation is a very good task for T3.

**Comment by flo91** [comment]
Hello,

thank you for joining the FLOSS course and for the interesting proposal!
As @markus2330 already mentioned, the page "Vision" (https://www.libelektra.org/docgettingstarted/vision) gives an example (Samba config) and presents an overview of some main concepts of Elektra.

For persons who work with Elektra for the first time, the easiest way to get started after installing, is probably using the command line tool `kdb` to set and get some configuration keys and values.

The page https://www.libelektra.org/getstarted/guide#hello-first-steps contains a basic example
for using the `kdb`-tool to handle configuration-files and specifications.

The tutorial https://www.libelektra.org/tutorials/writing-a-specification-for-your-configuration gives a nice example for writing and using a specification.

A quick improvement would be to at least link the page "Vision" and the specification-tutorial on the "Get started" page or homepage.
But surely, there is also potential for improving the existing documentation and creating a more focused tutorial for beginners.
