### ISSUE TITLE
Doxygen LATEX_CMD_NAME

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4533]
we could try to simplify LATEX_CMD_NAME, which probably does not need to be set by us, see also https://github.com/doxygen/doxygen/issues/9567

_Originally posted by @markus2330 in https://github.com/ElektraInitiative/libelektra/issues/4455#issuecomment-1238507234_

**Comment by kodebach** [comment]
I also get these warnings on Doxygen 1.9.3, so there is probably a lot we can do with our Doxyfile.

```
warning: Tag 'OUTPUT_TEXT_DIRECTION' at line 102 of file '/home/klemens/coding/elektra/libelektra/cmake-build-debug/doc/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'LATEX_SOURCE_CODE' at line 1918 of file '/home/klemens/coding/elektra/libelektra/cmake-build-debug/doc/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'RTF_SOURCE_CODE' at line 2008 of file '/home/klemens/coding/elektra/libelektra/cmake-build-debug/doc/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'DOCBOOK_PROGRAMLISTING' at line 2113 of file '/home/klemens/coding/elektra/libelektra/cmake-build-debug/doc/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'CLASS_DIAGRAMS' at line 2300 of file '/home/klemens/coding/elektra/libelektra/cmake-build-debug/doc/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
```

**Comment by markus2330** [comment]
Please don't hesitate to create new issues. We need more smaller issues.

**Comment by 0x6178656c** [comment]
@albert-github in https://github.com/doxygen/doxygen/issues/9567#issuecomment-1236301081_ wrote
> * `cp elektraSpecialCharacters.sty out/latex` is in my opinion not necessary, have a look at `LATEX_EXTRA_FILES`

I realized this suggestion. I am not sure how much is gained by moving the copying from the CMake configuration to the Doxygen configuration.

**Comment by albert-github** [comment]
@0x6178656c 
In my opinion the gain is that doxygen does the work for you and you have everything together that belongs together.
