### ISSUE TITLE
[FLOSS H0] Project Suggestion

### ISSUE THREAD

**Issue by Eiskasten** [ElektraInitiative/libelektra#4536]
I wonder if it is a good idea to finish the implementation of #4350 with @deoknats861 within the project. I do not want it to be less effort than required.

**Comment by markus2330** [comment]
It would be possible, there is always room for more extensions, e.g. make the ldap plugin also work over network.

But: isn't it better if you finish it alone in the homework? It is probably quite some effort to dig into your code? This I cannot answer for you though.
