### ISSUE TITLE
Deleting manpage markdown leave roff behind

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#4542]
Our manpages are written as markdown in `doc/help` and then converted to roff and stored in `doc/man`. Since `doc/man` is also committed to the repo, the folders have to be kept in sync. We have a CI job that checks that all files have been generated. But if a file is deleted from `doc/help` there is nothing that ensures the file is also deleted from `doc/man`.

Ideally, the old file would be deleted from `doc/man` automatically during the build. But there should at least be a CI job that checks that we don't have roff files without markdown sources.

**Comment by kodebach** [comment]
@markus2330 for FLOSS

**Comment by atmaxinger** [comment]
On a related note, why do we have to keep the man pages committed in the repository?

**Comment by kodebach** [comment]
AFAIK it is so Elektra can be built (including full docs) without the somewhat obscure `ronn-ng` tool.

**Comment by atmaxinger** [comment]
@markus2330 If that's the only reason why don't we use [pandoc](https://pandoc.org/) instead, it is much more established. 

My gripe with this approach is that it always leads to stupid build artifacts (the man pages) messing up my git worktree with irrelevant changes every time I build libelektra. Most of those changes are just updating the version number in the "generated with Ronn-NG" header in the documents ....

**Comment by kodebach** [comment]
If you install the same version of `ronn-ng` as the build server you shouldn't see any false changes.

```sh
gem install ronn-ng -v 0.10.1.pre1 
```

But yes, I agree using something like pandoc and removing the roff files entirely would be better.

**Comment by markus2330** [comment]
It is definitely not ideal that we have generated files checked in but we found it to be better than the alternative (requiring to install ronn-ng).

pandoc is relatively useless here, the result generated with `-t man` doesn't looks like a man page at all.

Btw. we already had this discussions many times, we should have written a decision back then.

**Comment by kodebach** [comment]
Seems like you need to call pandoc like this:

```sh
pandoc doc/help/kdb-get.md -s -t man
```

Source: https://jeromebelleman.gitlab.io/posts/publishing/manpages/

To get proper title, author, date, etc. you need to add a YAML frontmatter block. This could be done by a script wrapper around pandoc, i.e. we could keep the files in the repo unchanged.

```markdown
---
title: kdb-get
section: 1
author: Elektra Initiative
date: September 2022
...

# kdb-get(1) -- Get the value of a key stored in the key database
```

If I add this frontmatter to the start of `kdb-get.md`, the result I get with the

```sh
pandoc kdb-get.md -s -t man | man -l -
```

looks very much like a normal man page:

```
kdb-get(1)                                                                                                                                                                                 kdb-get(1)

kdb-get(1) – Get the value of a key stored in the key database
   SYNOPSIS
       kdb get <key name>

       Where key name is the name of the key.

   DESCRIPTION
       This command is used to retrieve the value of a key.

       If  you enter a key name starting with a leading /, then a cascading lookup will be performed in order to attempt to locate the key.  In this case, using the -v option allows the user to see
       the full key name of the key if it is found.

   LIMITATIONS
       Only keys within the mount point or below the <key name> will be considered during a cascading lookup.  A workaround is to pass the -a option.  Use the command kdb get -v <key name>  to  see
       if an override or a fallback was considered by the lookup.

   RETURN VALUES
       This command will return the following values as an exit status:

       • 0: No errors.

       • 1-10: standard exit codes, see kdb(1)

       • 11: No key found.

   OPTIONS
       • -H, --help: Show the man page.

       • -V, --version: Print version info.

       • -p, --profile <profile>: Use a different kdb profile.

       • -C, --color <when>: Print never/auto(default)/always colored output.

       • -a, --all: Consider all of the keys.

       • -n, --no-newline: Suppress the newline at the end of the output.

       • -v, --verbose: Explain what is happening.  Gives a complete trace of all tried keys.  Very useful to debug fallback and overrides.

       • -d, --debug: Give debug information.  Prints additional debug information in case of errors/warnings.

   EXAMPLES
              # Backup-and-Restore: user:/tests/get/examples

              # We use the `dump` plugin, since some storage plugins, e.g. INI,
              # create intermediate keys.
              sudo kdb mount get.ecf user:/tests/get/examples/kdb-get dump
              sudo kdb mount get.ecf spec:/tests/get/examples/kdb-get dump

              # Create the keys we use for the examples
              kdb set user:/tests/get/examples/kdb-get/key myKey
              kdb meta-set spec:/tests/get/examples/kdb-get/anotherKey default defaultValue

              # To get the value of a key:
              kdb get user:/tests/get/examples/kdb-get/key
              #> myKey

              # To get the value of a key using a cascading lookup:
              kdb get /tests/get/examples/kdb-get/key
              #> myKey

              # To get the value of a key without adding a newline to the end of it:
              kdb get -n /tests/get/examples/kdb-get/key
              #> myKey

              # To explain why a specific key was used (for cascading keys):
              kdb get -v /tests/get/examples/kdb-get/key
              #> got 3 keys
              #> searching spec:/tests/get/examples/kdb-get/key, found: <nothing>, options: KDB_O_CALLBACK
              #>     searching proc:/tests/get/examples/kdb-get/key, found: <nothing>
              #>     searching dir:/tests/get/examples/kdb-get/key, found: <nothing>
              #>     searching user:/tests/get/examples/kdb-get/key, found: user:/tests/get/examples/kdb-get/key
              #> The resulting keyname is user:/tests/get/examples/kdb-get/key
              #> The resulting value size is 6
              #> myKey

              # Output if only a default value is set for a key:
              kdb get -v /tests/get/examples/kdb-get/anotherKey
              #> got 3 keys
              #> searching spec:/tests/get/examples/kdb-get/anotherKey, found: spec:/tests/get/examples/kdb-get/anotherKey, options: KDB_O_CALLBACK
              #> The key was not found in any other namespace, taking the default
              #> The resulting keyname is default:/tests/get/examples/kdb-get/anotherKey
              #> The resulting value size is 13
              #> defaultValue

              kdb rm user:/tests/get/examples/kdb-get/key
              kdb rm spec:/tests/get/examples/kdb-get/anotherKey
              sudo kdb umount user:/tests/get/examples/kdb-get
              sudo kdb umount spec:/tests/get/examples/kdb-get

       To use bookmarks: kdb get +kdb/format

       This command will actually get user:/sw/elektra/kdb/#0/current/format if the bookmarks commands from kdb-set(1) man pages are executed before.

   SEE ALSO
       • kdb(1) for how to configure the kdb utility and use the bookmarks.

       • For more about cascading keys see elektra-cascading(7)

       • To get keys in shell scripts, you also can use kdb-sget(1)

       • elektra-key-names(7) for an explanation of key names.

AUTHORS
       Elektra Initiative.

                                                                                            September 2022                                                                                 kdb-get(1)
```

**Comment by markus2330** [comment]
The OPTIONS are not nicely formatted. This is a Markdown extension ronn-ng has. Should look like:

```
OPTIONS
       -H, --help #<-- this in bold
              Show the man page.

       -V, --version
              Print version info.

       -p, --profile <profile>
              Use a different kdb profile.
```

So extra effort for a result that is not so good. And only changing the dep instead of getting rid of a dep. Doesn't sound so good.

A more promising way probably would be if we can convince Doxygen to create these man pages. Then we would have one dependency less.

**Comment by kodebach** [comment]
Hm okay, yeah the markdown files would need to change slightly to get the same result.

Using Doxygen might be possible, but I don't think it would be easy.

Let's get back to the original issue of keeping markdown and roff files in sync. I'll hide the off-topic comments (including this one)

**Comment by markus2330** [comment]
Thank you, yes let us focus on the main point. It is suitable for FLOSS. The same is true for checking if Doxygen might work as alternative. I created #4551.

Let us please avoid such unstructured discussions about "Why?" in the future (now hidden above), as it takes our precious time and, without a decision as result, doesn't lead anywhere. I added the current status as draft decision "manpages.md" in #4528, so that this decision is not lost (again).

**Comment by kodebach** [comment]
> Let us please avoid such unstructured discussions about "Why?" in the future (now hidden above)

I disagree. Creating a new issue to ask this question would also be bad idea. Often the answer is just a single comment. Answering the question and hiding as Off Topic is better IMO. Not asking "why" or not answering such questions at all would of course be the worst option.

> as it takes our precious time and, without a decision as result, doesn't lead anywhere.

**Not everything must be a decision.** Sometimes people are just curious and want to know something. Answering the questions here didn't take long at all.

**Comment by markus2330** [comment]
@kodebach You misunderstood. Curiosity is good. Asking questions is good. That we often **only** answer in issues and not in documentation (like decisions) is what we are doing wrong. We could already be much more beginner friendly. So please use questions more as opportunity to improve Elektra.

**Comment by atmaxinger** [comment]
One final note from me - my question was meant to reevaluate whether the issue brought up here is actually an issue. If we dont check in the man pages there is no Need to keep them in sync.
