### ISSUE TITLE
Optimize CI runtimes

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#4545]
Some of our CIs take quite some time to run and often times it's not because of the time it takes to compile and run the tests. We should try to reduce this overhead.

For example, GitHub Actions macOS runs spend about 10-15 min just in the "Installing Dependencies" step. I'm no macOS expert, but maybe this can be improved somehow (e.g. by caching)

**Comment by markus2330** [comment]
This issue is too general that anything shorter than a bachelor thesis can help here. Such a thesis is already offered.

About speeding up macOS in specific last term someone lost quite some time trying to do this, without any success. #4182
