### ISSUE TITLE
Print memchecker results in Jenkins

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#4548]
I don't know why, but sometimes the `memcheck` results are not printed by `ctest`. However, `ctest` also creates log files with the result. The files can be found in the artifacts of the build, but we should also print those log files in our Jenkins jobs after every `make run_memcheck`.

The files have the format: `${WORKSPACE}/build directory/Testing/Temporary/MemoryChecker.*.log`

**Comment by atmaxinger** [comment]
Could this be an issue for the FLOSS course?

**Comment by markus2330** [comment]
I assume printing them on (memcheck) errors is enough? Otherwise we accumulate huge logs and need to shorten the period how long we can store build logs.

**Comment by kodebach** [comment]
Yes, printing only when `ctest` exits with non-zero should be good enough.
