### ISSUE TITLE
make sure backend plugin is included

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4558]
> AFAICT the last failure was only because some Jenkins builds didn't include the `backend` plugin and then tried to run tests that need it.

_Originally posted by @kodebach in https://github.com/ElektraInitiative/libelektra/issues/4187#issuecomment-1276159434_
      
We should add an CMake check that this gets impossible. See src/plugins/CMakeLists.txt

**Comment by kodebach** [comment]
Other plugins that are required are `modules` and `version`. Maybe also `missing` (not sure actually) and some others.

This should not just be a check of somewhere. Ideally, the `elektra-kdb` target would depend on the hardcoded plugins. Then `make elektra-kdb` would also build them.

**Comment by markus2330** [comment]
Thanks for reminding, yes, modules+version are also essential plugins.

The solution in src/plugins/CMakeLists.txt is not very pretty. What about marking these plugins as "essential" (#666) and then have a check that all essential plugins are present?

About the plugin "missing" we need to do triage: remove a .so of something that is mounted, then missing should be used instead.

Correcting dependencies is nice-to-have but imho a different issue as it doesn't fix this bug nicely: there might be a cmake error because of a missing dependency but we want a nice error message that an essential plugin is missing (which must be added to PLUGINS). IMHO there would be much more to do there before different targets can be used nicely. I don't see this in our scope for 1.0.

**Comment by kodebach** [comment]
I still really dislike the `infos/status` thing. But yes, marking the essential plugins as such in the contract makes sense.

The question is just do we want a real check that raises an error, if an essential plugin is missing, or do we just always include all essential plugins no matter what's in `PLUGINS`? I think we can just always include them, at least if `libelektra-kdb` is included.

**Comment by markus2330** [comment]
I am okay with both (failure or adding), it is up to the implementer. The consequence of auto-adding plugins is that people will at some point also expect that plugins required by other plugins get automatically added.

That said: I wouldn't invest too much time in this, so the easier path is the preferable one.
