### ISSUE TITLE
doc/help/* "see also" links broken

### ISSUE THREAD

**Issue by tom-wa** [ElektraInitiative/libelektra#456]
All the "See also" links in the doc/help files are broken 
e.g.
`https://github.com/ElektraInitiative/libelektra/blob/master/doc/help/elektra-key-names.md`
links to `https://github.com/ElektraInitiative/libelektra/blob/master/doc/help/doc/tutorials/namespaces.md`
but should link to `https://github.com/ElektraInitiative/libelektra/blob/master/doc/help/elektra-key-names.md`
(same goes for all other help docs)

**Comment by markus2330** [comment]
Thank you for reporting! I think I will set up a redirection to have short links to github repository.

**Comment by markus2330** [comment]
Thank you, they seem to work now!
