### ISSUE TITLE
[FLOSS H1] First impressions

### ISSUE THREAD

**Issue by 0x6178656c** [ElektraInitiative/libelektra#4563]
After playing around with Elektra a bit I think I understand some of the key features.

# Clear

* Elektra provides an interface to configuration management and exposes configuration as a key-value store.
* There are different namespaces with different purposes.
  * For instance, for cascading lookups (for keys without the namespace specified) the namespaces are traversed in a specific order.
* Files can be mounted to act as the parent node of a hierarchy.
* Elektra advocates a specific naming convention for naming of keys.

## Resources

The main resource which helped me understand Elektra was reading the first four of the [tutorials](https://www.libelektra.org/tutorials/readme).

# Unclear

## Significance of namespaces

Although I had glimpses of understanding their significance, I still feel that I am missing some concrete examples which highlight the power of the namespace feature.

## Syncing of configuration files

One configuration use case I would be interested in, but could not find any documentation on is keeping configuration files in sync.

Say there are two programs, Program A and Program B, with configuration files `config_a.ini` and `config_b.ini` and that the configuration of some values need to be the same for both programs (e.g. IP addresses, port numbers) .

Is there a way in Elektra to keep those two programs' configuration in sync? Note that I am crucially thinking of the case where Program A and Program B both know nothing about Elektra.

**Comment by markus2330** [comment]
@0x6178656c Thank you, very valuable input!

> Although I had glimpses of understanding their significance, I still feel that I am missing some concrete examples which highlight the power of the namespace feature.

Yes, I agree (more) examples are very welcome. We can keep the issue open for this (or you create a new one) if you want to work on it (later when it becomes more clear what the namespaces are). I would appreciate it.

> One configuration use case I would be interested in, but could not find any documentation on is keeping configuration files in sync.

Are these configuration files on the same computer (nodes) or on different ones?

- If there are on different ones, CM tools or network file systems are ways to do it.
- If it is one computer, you probably don't want to copy but to use override/fallback links.

What doesn't exist at the moment:

- A tool that does a two-way-sync on one computer by copying changes around wouldn't be hard to write. Currently we are doing many changes in the notification system though, see #4554
- Another approach would be providing a `--bind` mount with a plugin that creates override/fallback links on every key for you. Is probably more difficult than it seems as the plugin system is currently not really designed to do this.

**Comment by kodebach** [comment]
> * If it is one computer, you probably don't want to copy but to use override/fallback links.

I think you missed this part of the question:

> Note that I am crucially thinking of the case where Program A and Program B both know nothing about Elektra.

The application(s) not knowing about Elektra makes things significantly more complicated.

> A tool that does a two-way-sync on one computer by copying changes around wouldn't be hard to write. 

I wouldn't say that. Handling conflicts between files and doing merging can always be hard. The notification and recording system deals with some of that, but not all of it.

**Comment by markus2330** [comment]
> know nothing about Elektra.

It still is possible via https://www.libelektra.org/bindings/intercept_fs

> The application(s) not knowing about Elektra makes things significantly more complicated.

:+1: 

> Handling conflicts between files and doing merging can always be hard.

With Elektra it is much easier, as the merging is done on key/values. And we have a 3-way merge:
https://www.libelektra.org/tutorials/merge-configuration
