### ISSUE TITLE
[FLOSS H1] Impressions

### ISSUE THREAD

**Issue by Eiskasten** [ElektraInitiative/libelektra#4564]
As I have already worked with Elektra before during CM and my bachelor thesis, the entry was not hard for me in FLOSS. Please keep that in mind while reading this. This also means that my first steps and impressions are made ling time ago.

### Clear

- Receive a copy of the source code
- Import the project in Clion
- Commit to the project

### Unclear
The biggest topic which is still not fully transparent to me is the build process. This covers the functionality of Cmake itself and which of it is used in Elektra. This does not apply to compile Elektra but how to write new Cmake files, or modules for new plugins or bindings.

I looked for that in

- https://www.libelektra.org/compiling/compile
- https://www.libelektra.org/devdocu/plugins-framework
- https://www.libelektra.org/devdocu/architecture

**Comment by flo91** [comment]
Thanks for your report!

Getting started with CMake could take some time and effort.
I'd suggest to read the following CMake Tutorial which is also linked in the [FLOSS TUWEL course](https://tuwel.tuwien.ac.at/course/view.php?id=49231#section-3) under "M03 Development Tools": https://cmake.org/cmake/help/latest/guide/tutorial/index.html
