### ISSUE TITLE
delete request for openbuildservice

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4565]
Anyone who wants to continue using the openbuildservice? Otherwise I would say we actually can delete it.

Visit https://build.opensuse.org/request/show/1016464

Description:
We have noticed that your project got not touched since more then one year. This is a friendly request to remove your project to free resources on our server. Thank you.

Actions:
- delete project home:elektra

To REVIEW against the previous version:
   osc request show --diff 1016464

To ACCEPT the request:
   osc request accept 1016464 --message="reviewed ok."

To DECLINE the request:
   osc request decline 1016464 --message="declined for reason xyz (see ... for background / policy / ...)."

To REVOKE the request:
   osc request revoke 1016464 --message="retracted because ..., sorry / thx / see better version ..."

**Comment by kodebach** [comment]
We have our own build servers and even repositories for debs and rpms. I don't think we need to use their service. Also was it ever even properly set up? The [description](https://build.opensuse.org/package/show/home:elektra/libelektra) just says "test".

**Comment by markus2330** [comment]
I don't think the setup ever was complete. openbuildservice would be able to build for some distros we currently don't.

**Comment by kodebach** [comment]
> openbuildservice would be able to build for some distros we currently don't.

But I assume we'd still have to write the scripts to build the packages, so we could just do that on our CI couldn't we?

**Comment by markus2330** [comment]
Yes, it probably easier to also add (Open)Suse that way. I accepted the request.
