### ISSUE TITLE
[FLOSS H1] First impressions

### ISSUE THREAD

**Issue by Bujuhu** [ElektraInitiative/libelektra#4566]
Here are my thoughts on Elektra so far. 

Frankly, at first glimpse, I thought it was kind of redundant in a world where tools like Ansible exists. But ansible is still bound to constraints of the configuration management of each individual program; Ansible just mitigates some of it by executing commands or modify plain text files using a single source of truth. Using Elektra it's possible to get rid of complex configuration management within applications altogether, improving flexibility for system administrators and reducing the burden on software developers to include complex configuration management capabilities.

# Clear
The installation, code bindings and simple tasks using the provided command line tools were all very clear to me. Also, the general concepts and philosophy I think I've understood pretty well. The amount of plugins is a bit overwhelming to get into right from the start, but the ones I've looked have generally pretty clear documentation on how they work.

# Unclear
The documentation on mounting I've stumbled upon is at the start is very sparse. This probably the result that most intricacies on mounting are handled by plugins, but I still have difficulties to wrap my head around setups, that more complicated, than just mounting plain config files from the local file system. Especially on how multiple plugins interact with each other. I even found an [empty Documentation Page for mounting](https://www.libelektra.org/tutorials/mount-configuration-files).

# Used Resources
To get started, and learning about the project, I used these documents
- [install](https://www.libelektra.org/installation/installation)
- [tutorials](https://www.libelektra.org/tutorials/readme)
- [why-elektra](https://www.libelektra.org/docgettingstarted/why-elektra)

Information about mounting
- [elektra-mounting(7)](https://www.libelektra.org/manpages/elektra-mounting)
- [kdb-mount(1)](https://www.libelektra.org/manpages/kdb-mount)

Code example I used
- [hello-elektra-in-c-docs](https://www.libelektra.org/tutorials/hello-elektra-in-c)
- [hello-elektra-in-c-example](https://www.libelektra.org/examples/helloelektra)

Plugins I've looked at in more detail
- [csvStorage](https://www.libelektra.org/plugins/csvstorage)
- [fcrypt](https://www.libelektra.org/plugins/fcrypt)
- [constants](https://www.libelektra.org/plugins/constants)

**Comment by markus2330** [comment]
Thank you for this report, these are interesting insights! Probably https://www.libelektra.org/docgettingstarted/vision would have helped to grasp earlier why Ansible (or any other CM tools) aren't the full solution?

> I even found an [empty Documentation Page for mounting](https://www.libelektra.org/tutorials/mount-configuration-files).

Yes, the file was commented out recently because mounting was changed significantly and still changes to also support non-file configuration (like databases). You can still read it by pressing "raw" here: https://master.libelektra.org/doc/tutorials/mount.md

But as it was commented out on purpose, probably some parts won't work. As you are interested in this topic, you could try to reproduce what works and what not in this tutorial. It would be good to have this tutorial back.

**Comment by Bujuhu** [comment]
> Thank you for this report, these are interesting insights! Probably https://www.libelektra.org/docgettingstarted/vision would have helped to grasp earlier why Ansible (or any other CM tools) aren't the full solution?

Yeah, that's probably true, the example helps a lot

> As you are interested in this topic, you could try to reproduce what works and what not in this tutorial. It would be good to have this tutorial back.

Sure!

**Comment by Bujuhu** [comment]
I've only found a single Issue, I've described it #4576
