### ISSUE TITLE
[FLOSS] unify spelling of manpages

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4567]
We currently have at least 3 spellings of manpage(s):

1. man pages
2. manpages
3. man-pages

Use scripts/sed to unify.

Triage is about:

- do we have other spellings?
- which of the options above should we use?

**Comment by stefnotch** [comment]
I can confirm this issue.
Searching for `[mM][aA][nN].{0,3}[pP][aA][gG][eE]` using Visual Studio Code (which uses ripgrep under the hood) yields 260 results.
The vast majority seem to use the first spelling, that is "man pages".

So now to find different ones, we tweak the regex to not search for a space in the middle `[mM][aA][nN][^ ]{0,3}[pP][aA][gG][eE]`. At this point, a lot of results will be things like variables or links.
e.g.
Variables: `generate_manpage`, `${MANPAGE}`, `MAN_PAGE_LOCATION`, `runManPage`, ...
Links: `https://www.libelektra.org/manpages/kdb`, `https://en.wikipedia.org/wiki/Man_page`, ...

**Proposal**
I'd propose unifying the spelling to "man page" with a separator. Although, depending on the context, a different separator can make sense. `generate_manpage` would thus become `generate_man_page`. Meanwhile something like `runManPage` is already fine under that proposal.

Another thing that we should take a look at is file names. There's at least one file containing the words "man page", namely `ElektraManPage.cmake`.

And finally, the tricky part that I'm unsure about:
How does one go about updating the `https://www.libelektra.org/manpages/...` links? According to the [Google guidelines](https://developers.google.com/search/docs/crawling-indexing/url-structure) we could use `https://www.libelektra.org/man-pages/...`. At the same time, we do want to have a redirect from our old `https://www.libelektra.org/manpages/...` URLs to the new ones, after all, a good URL should never break.

**Comment by flo91** [comment]
> Most English sources I found in a quick Google search use "man page". Both "manpage" and "man-page" seem to be more of a German thing...

Your research result squares with the proposal from @stefnotch:

> I'd propose unifying the spelling to "**man page**" with a separator.

So normally, the separator is a space, but in many cases, spaces are not allowed, so either a CamelCase variant `manPage`, or other separators like `-` or `_` must be used.

The file name `ElektraManPage.cmake` looks fine to me.
The man pages on the website refer to files on the GitHub respository available at https://github.com/ElektraInitiative/libelektra/tree/master/doc/help.
But you're right, if we want to change the URLs to contain `man-pages` instead of `manpages`, we should create a redirect or offer the man pages under both URLs.

**Comment by markus2330** [comment]
Nice triage, thank you!

**Comment by stefnotch** [comment]
We'll take a stab at this for T1

**Comment by stefnotch** [comment]
Categories:
bad:
Manpage
manpage
MANPAGE
manpages


good:
man_page
MAN_PAGE
manPage
Man_page

good except in some cases:
man-page (fine in URLs or file names)

**Comment by markus2330** [comment]
> Man_page

Is this for file names? Otherwise you better would say "Man page" (without quotes)?

**Comment by stefnotch** [comment]
For file names or other cases where underscore_case is the way to go.
e.g. `generate_manpage` would become `generate_man_page`
