### ISSUE TITLE
[FLOSS] Leftover package-lock.json

### ISSUE THREAD

**Issue by stefnotch** [ElektraInitiative/libelektra#4569]
## Steps to Reproduce the Problem

There seems to be a stray https://github.com/ElektraInitiative/libelektra/blob/master/src/tools/elektrad/package-lock.json

## Expected Result

I would have expected to not find this file

## Actual Result

This file exists in the repository, and doesn't seem to have a use-case

## System Information

- Elektra: master

**Comment by markus2330** [comment]
Yes, nice find! I agree that this file can be removed. elektrad was rewritten from Javascript to Go.
