### ISSUE TITLE
[FLOSS] Git main branch

### ISSUE THREAD

**Issue by joni1993** [ElektraInitiative/libelektra#4571]
Many communities switch their "primary" branch in git away from `master` to `main`. This is also suggested by the [software freedom conservancy](https://sfconservancy.org/) in 2020 [here](https://sfconservancy.org/news/2020/jun/23/gitbranchname/)

This issue should serve as guideline to track what changes are needed to accomplish this.
# Checklist
- [ ] Check references in build process
- [ ] Update docs 
- [ ] check for other offensive names that may be replaced

**Comment by markus2330** [comment]
Thank you for writing this issue! This is a sensible topic and it seems like nobody dares to write anything here. I'll give two answers:

## FLOSS Answer

Issues should state some problem and not blindly follow what others do.
It is unclear to me if you feel offended by the term in this specific use?

Every person and every initiative has the freedom to go its own way, with all its consequences (which people get attracted etc.).

## Personal Answer

I personally welcome **very much** work in how we can better attract people, no matter of their skin color or whatever other stupid criteria people use to discriminate.

The use of "master" in this case is about the "master of branches", which has nothing to do with any living being.
IMHO it is okay to offend other git branches.
There are also cultures where master is a very positive term (India, Buddhists countries etc.)
So I don't think this rename is an appropriate measure to attract people nor it will avoid discrimination.

## Alternate Proposal

I would agree to avoid the terms whitelist and blacklist.
It is arbitrary (depending on culture) and thus possibly confusing why black would be the rejected and white the allowed.
E.g. the terms blocklist and allowlist are more clear.
Luckily, this change is much easier to do than the `master -> main` rename but still a lot of effort.

**Comment by kodebach** [comment]
It may actually be a different kind of "master". I've read Bitkeeper actually used both "master" and "slave" as terms (which is also common with hardware), but there is also the "master record" in the audio industry. Since `git` doesn't use "slave" this may be the more accurate meaning. So it is not "master" as in "someone who has control", but rather "master" as in "the original, true form" or maybe "master" as in "expert" (e.g. in Master's degree).

[According to Wikipedia](https://en.wikipedia.org/wiki/Blacklisting#Origins_of_the_term) the term blacklist comes from a list of enemies King Charles II kept. Whitelist is simply the opposite, since white and black are opposites (as colors). Before I learned this, my explanation for the terms was always that "black" absorbs all light, so a blacklist blocks/hides things.

That being said, I agree that blocklist and allowlist are fine alternatives. Renaming `master` to `main` is also okay. It's not as complicated as it seems, because many people have done it before. There is even an [official GitHub guide](https://github.com/github/renaming).

**Comment by joni1993** [comment]
## FLOSS answer
Due to the lack of "discussion"-software, i created an issue to start a discussion about it - personally i am not offended by the term but other probably do - the main intend was to start a discussion about it.

## Personal answer
While i do understand that it has nothing to do with any living being, there might be people that could misinterpret the term "master" still. Some could still be offended or traumatized by the term. I think it's better if everyone is happy with a "neutral" term because there are no technical reasons to keep a possibly offending term.

**Comment by markus2330** [comment]
> While i do understand that it has nothing to do with any living being, there might be people that could misinterpret the term "master" still. Some could still be offended or traumatized by the term.

This is possible with nearly any term. People also, e.g., die on main street or drown in the river Main.

> I think it's better if everyone is happy with a "neutral" term because there are no technical reasons to keep a possibly offending term.

There are plenty of technical and other reasons, I add them as you initially wanted to investigate "what changes are needed to accomplish this":

- all our master.libelektra.org links would be broken (not possible for us fix, as we don't have control over all webpages)
- DNS updates would be needed
- the change would be needed on 39 repos to avoid inconsistencies
- nearly all checked-out repos would be on a dead branch (I alone have > 100 clones, virtually all of them on master. This problem also cannot be solved centrally.)
- the term main and master would become more ambiguous. Currently "main" refers nearly exclusively to the C main function, master nearly exclusively to the master branch.

**Comment by kodebach** [comment]
> all our master.libelektra.org links would be broken (not possible for us fix, as we don't have control over all webpages)

But we control `master.libelektra.org` and could redirect that to `main.libelektra.org`. Also I think, if you rename the `master` branch via the GitHub webpage, it automatically redirects `master` links to `main` (as long as you don't create a new `master` branch). So I think we wouldn't even have to do anything.

> I alone have > 100 clones, virtually all of them on master

Uhm, why? Especially if all of them are on master, that seems like quite the waste of disk space.

**Comment by joni1993** [comment]
> This is possible with nearly any term. People also, e.g., die on main street or drown in the river Main.
I think one can not compare accidents of individuals in particular (which are sad too and can lead to traumatization) with the discrimination of whole ethnicities or similar.

> nearly all checked-out repos would be on a dead branch
According to https://github.com/github/renaming, it does automatically redirect.

But i agree in general that the change is rather big one on a project of this size.

**Comment by kodebach** [comment]
> According to https://github.com/github/renaming, it does automatically redirect.

AFAICT it would only redirect _web requests_. I don't think that would include git requests, certainly not those via SSH.
