### ISSUE TITLE
[FLOSS H1] find - SIGSEGV when parameter missing

### ISSUE THREAD

**Issue by joni1993** [ElektraInitiative/libelektra#4572]
## Steps to Reproduce the Problem
`kdb find` (without extra parameters)

## Expected Result
An error should appear that you need to specify a parameter OR default to `/` if no parameter given
## Actual Result
elektra@f2cecfe1dae1:~$ kdb find

Sorry, I crashed by the signal SIGSEGV
This should not have happened!

Please report the issue at https://issues.libelektra.org/
Aborted (core dumped)

## System Information
Happens at least on 

- elektra/elektra:latest (b75e1be6df068612e354a020f1edf173d67e4741ac3daee467117991afdfada2)
- elektra/elektra:0.9.11-2-opensuse-leap-15.3
- elektra/elektra:0.9.11-2-buster

**Comment by joni1993** [comment]
Backtrace:
```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7d37d94 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::data() const () from /lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff7d37d94 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::data() const ()
   from /lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x000055555559cf4c in std::__cxx11::basic_regex<char, std::__cxx11::regex_traits<char> >::basic_regex<std::char_traits<char>, std::allocator<char> > (this=0x7fffffffd260, __s=<Fehler beim Lesen der Variable: Cannot access memory at address 0x8>, 
    __f=(unknown: 0x10)) at /usr/include/c++/11/bits/regex.h:489
#2  0x000055555559ba64 in FindCommand::execute (this=0x555555733a60, cl=...)
    at /home/joni/Development/libelektra/src/tools/kdb/find.cpp:42
#3  0x000055555564ddc7 in main (argc=2, argv=0x7fffffffd758) at /home/joni/Development/libelektra/src/tools/kdb/main.cpp:202
```

**Comment by markus2330** [comment]
Great that you found this bug! I can reproduce the crash:

```
#0  FindCommand::execute (this=<optimized out>, cl=...) at /home/jenkins/workspace/libelektra_master/libelektra/src/tools/kdb/find.cpp:42
#1  0x00005555555847f3 in main (argc=2, argv=0x7fffffffe478) at /home/jenkins/workspace/libelektra_master/libelektra/src/tools/kdb/main.cpp:202
```

Should be quite easy to fix: there is a check for the presence of an argument missing. (The man page of kdb find clearly says via SYNOPSIS that one argument is mandatory.)

Is any further help wanted? I removed the label, please readd as needed.
