### ISSUE TITLE
[FLOSS] Reinstate Documentation on Mounting, Changed RET and Error Codes

### ISSUE THREAD

**Issue by Bujuhu** [ElektraInitiative/libelektra#4576]
As discussed in #4566, I've tested the [documentation on mounting](https://master.libelektra.org/doc/tutorials/mount.md), which is currently commented out to check it there are some issues

## Steps to Reproduce
I've tested it exactly as described in the commented out documentation and checked if the results and explanations match, what the application does. Generally, I found no differences between how the actual application works and the documented behavior. The only discrepancy I found is the following:

Assuming I've understood it correctly, that the RET value is the exit code and ERROR is the printed Error Message, I've got the following discrepancies:

#### Documented behavior
https://github.com/ElektraInitiative/libelektra/blob/d1a8f828fea2ad77c612df62009764beb397d273/doc/tutorials/mount.md?plain=1#L57-L58

#### Actual behavior
```sh
# ping -c 1 mylocalhost > /dev/null
# echo $?
0
```
RET should be 0 instead of 2. 

I'm not quite sure why 2 is supposed to be there in the first place, as the documentation implies, that this step should work without issues. (Maybe some quirk of an older version of ping I'm not aware of?)

#### Documented behavior
https://github.com/ElektraInitiative/libelektra/blob/d1a8f828fea2ad77c612df62009764beb397d273/doc/tutorials/mount.md?plain=1#L64-L69

#### Actual behavior
```sh
# sudo kdb set system:/hosts/ipv4/mylocalhost ::1
Sorry, module network issued the error C03200:
Validation Semantic: name: system:/hosts/ipv4/mylocalhost value: ::1 message: Address family for hostname not supported
echo $?
5
# sudo kdb set system:/hosts/ipv4/mylocalhost 300.0.0.1
Sorry, module network issued the error C03200:
Validation Semantic: name: system:/hosts/ipv4/mylocalhost value: 300.0.0.1 message: Name or service not known
# echo $?
5
```
In this case, RET is fine, but ERROR should be C03200.

## System Information
Operating System:
Arch Linux, Kernel 5.19.13-arch1-1

kdb and plugins version
```sh
# kdb --version
KDB_VERSION: 0.9.11
SO_VERSION: 5
# kdb plugin-check network
# echo $?
0
```

**Comment by markus2330** [comment]
Great triage!

> RET should be 0 instead of 2.

Absolutely, I agree. RET 2 is for "Name or service not known" (German: "Der Name oder der Dienst ist nicht bekannt") which would only be the case if the config file would not have been written.

> In this case, RET is fine, but ERROR should be C03200.

Absolutely, this looks like it was never updated and uses the old error codes.

@kodebach both problems seem unrelated to new-backend. Can you give more specific information why the whole file is commented out?

**Comment by kodebach** [comment]
> Can you give more specific information why the whole file is commented out?

I think I've said it in the PR as well, but it was simply because I didn't have time to check the file. I also expected to see some work on the new mount tooling by now, which would (probably) make the whole file obsolete.

**Comment by markus2330** [comment]
So we can comment it in again in the PR which fixes these two problems.

**Comment by kodebach** [comment]
Yes, but I'd also add a warning to the top (similar to `doc/dev/architecture.md`) that explains that the current `kdb mount` is a temporary solution that will (likely) change. We also need to make clear that it only works for the default file-based backend plugin and no tooling currently exists for other backend plugins.

**Comment by markus2330** [comment]
Yes, a sentence that the tutorial is only about mounting configuration files is a good idea. We shouldn't write, however, that anything (might) change in the future. This is visible in the outlook of release notes, issue tracker and/or PRs and does not need to be duplicated in the documentation.
