### ISSUE TITLE
[FLOSS] kconfig plugin fails silently on meta-set

### ISSUE THREAD

**Issue by Bujuhu** [ElektraInitiative/libelektra#4580]
As discussed in #4555
## Steps to Reproduce the Problem
```sh
$ sudo kdb mount configrc user:/tests/kconfig kconfig
# RET: 0
$ kdb meta-set user:/tests/kconfig blue blah 
# RET: 0  
$ kdb meta-get user:/tests/kconfig blue  
Key not found
# RET: 1
```
## Expected Result

Should either print an error on `kdb meta-set user:/tests/storage/types blue blah ` and return a non 0 exit code or
`kdb meta-get user:/tests/kconfig blue ` should return blah  

## Actual Result
`$ kdb meta-set user:/tests/kconfig blue blah` fails silently and `kdb meta-get user:/tests/kconfig blue`  returns a key not found error

## System Information
Operating System:
Arch Linux, Kernel 5.19.13-arch1-1

kdb and plugins version
```sh
# kdb --version
KDB_VERSION: 0.9.11
SO_VERSION: 5
```

## Relevant Source Code
Similar to #4579 this happens because the kconfig plugin only selectively looks for the "kconfig" meta key. All others are ignored.

https://github.com/ElektraInitiative/libelektra/blob/5702ce0496823fdd12c4e1e6ff9d6d1ca1b71a40/src/plugins/kconfig/kconfig_serializer.cpp#L106

**Comment by Janldeboer** [comment]
I tried to reproduce the issue, but I ran into a following problem when I entered the first command.
My console shows this:
```
sudo kdb mount configrc user:/tests/kconfig kconfig
Password:
The command kdb mount terminated unsuccessfully with the info:
No plugin that provides kconfig could be found
Please report the issue at https://issues.libelektra.org/
```
Is any prior setup (e.g. installing kconfig) required?

**Comment by Bujuhu** [comment]
No, it came with the default installation for me. How did you install elektra? If you compiled it yourself, do you have log files for the compilation?
