### ISSUE TITLE
[FLOSS] simpleini plugin fails silently on meta-set 

### ISSUE THREAD

**Issue by Bujuhu** [ElektraInitiative/libelektra#4583]
As discussed in #4555
## Steps to Reproduce the Problem
```sh
$ sudo kdb mount ini user:/tests/ini ccode simpleini
# RET: 0
$ kdb meta-set user:/tests/ini/key key value
# RET: 0  
$ kdb meta-get user:/tests/ini/key key
Key not found
# RET: 1
```
## Expected Result

Should print an error on `kdb meta-set user:/tests/ini/key value value` and return a non 0 exit code

## Actual Result
`$ kdb meta-set user:/tests/ini/key key value` fails silently and `kdb meta-get user:/tests/ini/key value`  returns Key not found

## System Information
Operating System:
Arch Linux, Kernel 5.19.13-arch1-1

kdb and plugins version
```sh
# kdb --version
KDB_VERSION: 0.9.11
SO_VERSION: 5
```

## Relevant Source Code
Like mini, simpleini states in its documentation that it does not support metadata as well, but still won't reject metadata user input

https://github.com/ElektraInitiative/libelektra/blob/cf4b6f303432dbfdcb9cc222c84f41045962b211/src/plugins/simpleini/simpleini.c#L348

**Comment by kodebach** [comment]
It should be `kdb meta-get user:/tests/ini/key key` in the example.

**Comment by Bujuhu** [comment]
Fixed it. Thank you!
