### ISSUE TITLE
[FLOSS H1] First Impression

### ISSUE THREAD

**Issue by deoknats861** [ElektraInitiative/libelektra#4588]
Hi, my first steps with Elektra were actually straightforward due to the good documentation and tutorials.

## Clear

- The main idea of Elektra 
- Setting up the local development environment with CLion
- Using git and the git workflows of the project

## Unclear

- I am not sure I understood mounting correctly, as the tutorial page is currently outdated
- I understood the main concept of namespaces, but do not know how the spec namespace is used by Elektra (a few more examples would be nice on the tutorial page)
- CMake (load/reload) has some behaviours that I do not fully understand yet

## Used information

- [https://www.libelektra.org/tutorials/contributing-with-clion](https://www.libelektra.org/tutorials/contributing-with-clion)
- [https://www.libelektra.org/devgettingstarted/contributing](https://www.libelektra.org/devgettingstarted/contributing)
- [https://www.libelektra.org/tutorials/readme](https://www.libelektra.org/tutorials/readme)
- [https://raw.githubusercontent.com/ElektraInitiative/libelektra/master/doc/tutorials/mount.md](https://raw.githubusercontent.com/ElektraInitiative/libelektra/master/doc/tutorials/mount.md)

**Comment by markus2330** [comment]
Thank you for describing your experiences!

> I am not sure I understood mounting correctly, as the tutorial page is currently outdated

It looks like most of the tutorial actually works: see #4576 

> I understood the main concept of namespaces, but do not know how the spec namespace is used by Elektra (a few more examples would be nice on the tutorial page)

Good hint! We should have a link from the namespace tutorial to https://www.libelektra.org/tutorials/validate-configuration, where the spec: namespace gets explained. Can you create a PR?

> CMake (load/reload) has some behaviours that I do not fully understand yet

Is probably not important, the build server only tests with clean build directories.
