### ISSUE TITLE
[FLOSS H1] CMake developer warning: package name does not match name of calling package

### ISSUE THREAD

**Issue by deoknats861** [ElektraInitiative/libelektra#4589]
## Steps to Reproduce the Problem

First, [Set up CLion for Elektra](https://www.libelektra.org/tutorials/contributing-with-clion).

Then start the 'Reload CMake Project'  task for `CMakeLists.txt` in CLion. This executes the following command:

```sh
/home/user/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/222.4345.21/bin/cmake/linux/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=/home/user/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/222.4345.21/bin/ninja/linux/ninja -DKDB_DB_HOME=~/.config/kdb/floss/home -DKDB_DB_SYSTEM=~/.config/kdb/floss/system -DKDB_DB_SPEC=~/.config/kdb/floss/spec -DKDB_DB_USER=.config/kdb/floss/user -DCMAKE_INSTALL_PREFIX=install -DENABLE_DEBUG=ON -DENABLE_LOGGER=ON -DBINDINGS=ALL;-DEPRECATED -DPLUGINS=ALL;-DEPRECATED -DTOOLS=ALL -DCOMMON_FLAGS=-Werror -G Ninja -S /home/user/libelektra -B /home/user/libelektra/cmake-build-debug
```

## Expected Result

The cmake step should finish without this warning.

## Actual Result

The execution prints the following project developer warning:

```sh
CMake Warning (dev) at /home/user/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/222.4345.21/bin/cmake/linux/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (DISCOUNT)
  does not match the name of the calling package (Discount).  This can lead
  to problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  scripts/cmake/Modules/FindDiscount.cmake:73 (find_package_handle_standard_args)
  src/tools/qt-gui/CMakeLists.txt:19 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

## System Information

- Elektra:  master([cf4b6f3](https://github.com/deoknats861/libelektra/commit/cf4b6f303432dbfdcb9cc222c84f41045962b211))
- Operating System: Arch Linux 6.0.2-arch1-1 x86-64
- cmake version 3.23.2

## Further Information
- I did not install elektra on my local system, I just followed the CLion tutorial linked above

**Comment by joni1993** [comment]
I can reproduce this issue on master(d1a8f828fea2ad77c612df62009764beb397d273), on Ubuntu 22.04 with Clion 2021.2.1 (with bundled cmake version 3.20.2).

**Comment by flo91** [comment]
Good catch! Looks like an issue with upper- and lowercase spelling in `src/tools/qt-gui/CMakeLists.txt`.
