### ISSUE TITLE
[FLOSS H1] First impression

### ISSUE THREAD

**Issue by joni1993** [ElektraInitiative/libelektra#4591]
Hi, my first experience with Elektra was a bit odd because of #4572. With the size of the project and the fact that it exists for that long i did not expect to find such a trivial error.

While i really like the general idea of unified configuration system offered by elektra - as a system administrator i think it is way to complex and almost needs something like a "wrapper"-tool to make it easier to use. 

A lot of software nowadays uses comments in configuration to explain what each configuration item does - this makes it very easy exploring the possibilities by just using a text editor. With Elekta i first need to dig into how Elektra works and then connect all the bits and pieces together in my head (specs, meta, etc) to get a full overview (instead of reading it in plain text right in front of me)

# Clear

- The main idea of Elektra
- Basic usage of kdb
- Basic understanding of namespaces

# Unclear
Actual usefulness when used for e.g. with SaltStack. Even after reading [this](https://www.libelektra.org/manpages/elektra-faq#why-do-i-need-elektra-if-i-already-use-configuration-management-tools) i am still not convinced. SaltStack for example offers the [pillar system](https://docs.saltproject.io/en/getstarted/config/pillar.html) which is basically also a key-value store for each of the "host-systems". It also gives to possibility to use many different sources for it [(pillar modules)](https://docs.saltproject.io/en/latest/ref/pillar/all/index.html). This even allows usage of "configuration" beyond simple configuration, e.g. using it for logic.

# Used information
- https://www.libelektra.org/getstarted/guide
- https://www.libelektra.org/docgettingstarted/github-main-page
- https://www.libelektra.org/docgettingstarted/goals
- https://www.libelektra.org/docgettingstarted/who
- https://www.libelektra.org/docgettingstarted/why-elektra
- https://www.libelektra.org/docgettingstarted/vision
- https://www.libelektra.org/keynames/keynames
- https://www.libelektra.org/compiling/compile
- https://www.libelektra.org/installation/installation
- https://www.libelektra.org/tutorials/readme (and several subpages)

**Comment by markus2330** [comment]
Thank you for the report!

Did you read https://www.libelektra.org/docgettingstarted/vision? We should put it somewhere more prominently and link from the FAQ there...

The main idea is that applications and different CMs work together to have a unified key/value view. Not that every CM invents its own system.

**Comment by markus2330** [comment]
Or to say it differently: that pillars for new applications are trivial to implement.

**Comment by joni1993** [comment]
> Thank you for the report!
> 
> Did you read https://www.libelektra.org/docgettingstarted/vision? We should put it somewhere more prominently and link from the FAQ there...

Yes, i read it and i agree with it. I think technically elektra is a great solution but the problem i see is getting the vision to reality -   not many applications will be willing to change their own configuration system because a) it's work with no direct benefit for the project themselfes, b) "users" may prefer modifying/reading the file directly. 

I think most software developers don't want to tell their "user"-base "hey you need to learn how to use this [elektra] so you can keep using/configuring us" - especially if it is only "one system" that uses elektra while others may not support elektra. This could easily lead to just another systemd discussion. Some people like(d) their rc-scripts but in the end the benefits where bigger - and they are useful for everyone without the users needing to to anything. 
I think there needs to be a solution for transition so everyone is happy. 

For me it is rather difficult to imagine configuring a system using kdb - i am a visual guy. Lets see the example for e.g. Samba:

### with texteditor
- assume [this sample config](https://git.samba.org/samba.git/?p=samba.git;a=blob_plain;f=examples/smb.conf.default;hb=HEAD)
- i browse the config (e.g. in vim) read through it or search the config option that sounds reasonable to change (for my need)
- edit lines
- save

### with kdb
- find path that is used for samba config (could be different across different distros/systems) (lets call this {path})
- kdb ls {path} - shows probably nothing or only defaults
- for each option (this must be used many times to find all the relevant option, something like kdb meta-tree would be great):
-- kdb meta-ls : to find what option are there
-- kdb meta-show : to find out what they mean
-- use kdb set to set option

#### kdb example for samba (from vision)
`kdb set system:/sw/samba/#0/current/global/workgroup MYGROUP`
It looks very simple but just to get to the point where i know WHAT to do it takes multiple steps (besides knowing how arrays etc work [which i think is not very intuitive once you reach #_11...etc) :
1. find out that i need to use /sw/samba/
2. find out what options are there with meta-ls
3. show the info for the meta with meta-show
4. set it with kdb set
5. go to 2. to find other relevant options

#### texteditor example 
1. open file
2. read 
3. edit
4. save / done

I think using kdb from CLI is just to difficult. What would be very useful for example is a texteditor (vim,emacs whatever) plugin that parses kdb meta / spec automatically or does suggestions based on it while live-editing the file. On save you could do validation and deny if it contains any errors. 

> 
> The main idea is that applications and different CMs work together to have a unified key/value view. Not that every CM invents its own system.

That is true but i think most CMs (Saltstack, Ansible, Puppet) tried to do the best with what they got (different config formats etc) and do not try to "reinvent the wheel" (which forces all applications to adapt) but rather adopt themself to the applications. Also those systems are far beyond a key/value store with what they can accomplish.


> Or to say it differently: that pillars for new applications are trivial to implement.

This is true - but my point here in the end is: As administrator you, at least at some point, need something like Saltstack, Ansible, Puppet to do changes on your system (not only configuration tasks, but installing, updating etc). So every administrator already has some kind of "configuration store" - the benefits with elektra for these people are somewhat limited.

**Comment by markus2330** [comment]
Thank you for this valuable discussion!

> Yes, i read it and i agree with it. I think technically elektra is a great solution but the problem i see is getting the vision to reality - not many applications will be willing to change their own configuration system because a) it's work with no direct benefit for the project themselfes, b) "users" may prefer modifying/reading the file directly.

Yes, it is a big challenge, like with every change of habits.

> I think there needs to be a solution for transition so everyone is happy.

I agree. I created #4616 to make our plans more clear.

> For me it is rather difficult to imagine configuring a system using kdb - i am a visual guy.

I think Elektra is important so that we can offer more visual ways for configuration, especially for applications that do not have the time to write a nice UI for config on their own. Did you already try the Web-UI? https://www.libelektra.org/tutorials/webui

> What would be very useful for example is a texteditor (vim,emacs whatever) plugin that parses kdb meta / spec automatically or does suggestions based on it while live-editing the file.

We have `kdb editor`. But it only does validation, not yet suggestions. Implementing suggestions would be a very nice project.

> As administrator you, at least at some point, need something like Saltstack, Ansible, Puppet to do changes on your system (not only configuration tasks, but installing, updating etc). So every administrator already has some kind of "configuration store" - the benefits with elektra for these people are somewhat limited.

I agree. Nevertheless, the integration in CMs was needed so that we can check if Elektra works and brings the expected benefits. #4616 describes the plan.
