### ISSUE TITLE
[FLOSS H1]  Make example compile without C++

### ISSUE THREAD

**Issue by Dynamichost96** [ElektraInitiative/libelektra#4593]
## Steps to Reproduce the Problem
Steps 1 to 4
-https://www.libelektra.org/tutorials/hello-elektra-in-c

## Expected Result
Output Message as described in step 5

## Actual Result

```console
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error in CMakeLists.txt:
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
```

## System Information

- Elektra: master
- Operating System: Windows 11 with WLS(Ubuntu)

**Comment by Dynamichost96** [comment]
Fixed by installing Ubuntu development package and adding the compiler to the environment variable

**Comment by markus2330** [comment]
Thank you for reporting this problem!

To fix your problem, you probably only need to install `build-essential`.

But yes, actually Elektra should also compile without a C++ compiler.
This would be quite tricky, though, as the `project` statement is already one of the first things in CMakeLists.txt and at that time we do not know yet if any C++ modules are selected...

**Comment by markus2330** [comment]
To only compile the example (not Elektra) without a C++ compiler should be easy.

A `project (hello_elektra C)` in the CMakeLists.txt file should be enough. Can you check if it works and adapt https://www.libelektra.org/tutorials/hello-elektra-in-c ?

See also https://cmake.org/cmake/help/latest/command/project.html

I created #4617 to make also Elektra compile without C++ compiler. But this is probably a large issue and needs much knowledge about CMake.

**Comment by markus2330** [comment]
@Dynamichost96 Can you write which solution you took here?
