### ISSUE TITLE
`LIBCLANG_PATH` must be set for successful build

### ISSUE THREAD

**Issue by flo91** [ElektraInitiative/libelektra#4595]
## Steps to Reproduce the Problem

When executing the following two commands, the build process fails.

```bash
flo@vnpc ~/tu/libelektra_fork/libelektra/cmake-build-debug $ cmake .. \
-DBINDINGS="ALL" \
-DPLUGINS="ALL" \
-DTOOLS="ALL" \
-DENABLE_DEBUG="ON" \
-DKDB_DB_HOME="/home/flo/tu/libelektra_fork/libelektra/cmake-build-debug/.config/kdb/home" \
-DKDB_DB_SYSTEM="/home/flo/tu/libelektra_fork/libelektra/cmake-build-debug/.config/kdb/system" \
-DKDB_DB_SPEC="/home/flo/tu/libelektra_fork/libelektra/cmake-build-debug/.config/kdb/spec" \
-DBUILD_DOCUMENTATION="OFF" \
-DCMAKE_RULE_MESSAGES="OFF" \
-DCMAKE_INSTALL_PREFIX="/home/flo/tu/libelektra_fork/libelektra/elektra-install" \
-DCOMMON_FLAGS="-Werror"

flo@vnpc ~/tu/libelektra_fork/libelektra/cmake-build-debug $ make
```

## Expected Result

The build process should complete successfully.

## Actual Result

The build process fails with the following error:
```bash
[ 56%] Built target benchmark_thread
error: failed to run custom build command for `elektra-sys v0.9.11 (/home/flo/tu/libelektra_fork/libelektra/cmake-build-debug/src/bindings/rust/elektra-sys)`

Caused by:
  process didn't exit successfully: `/home/flo/tu/libelektra_fork/libelektra/cmake-build-debug/src/bindings/rust/target/release/build/elektra-sys-101300da5507266d/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-search=/home/flo/tu/libelektra_fork/libelektra/cmake-build-debug/lib
  cargo:rustc-link-lib=dylib=elektra-core
  cargo:rustc-link-lib=dylib=elektra-meta
  cargo:rustc-link-lib=dylib=elektra-kdb

  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /home/flo/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.50.1/src/lib.rs:1711:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make[2]: *** [src/bindings/rust/CMakeFiles/rust.dir/build.make:70: src/bindings/rust/target/release/libelektra.rlib] Fehler 101
make[1]: *** [CMakeFiles/Makefile2:12608: src/bindings/rust/CMakeFiles/rust.dir/all] Fehler 2
```

## Solution

As the error message indicates, the environment variable `LIBCLANG_PATH` was not set on my system.
```bash
flo@vnpc ~/tu/libelektra_fork/libelektra/cmake-build-debug $ echo $LIBCLANG_PATH
 
```

After setting the variable to the correct folder, the build process succeeded:
```bash
flo@vnpc ~/tu/libelektra_fork/libelektra/cmake-build-debug $ export LIBCLANG_PATH=/usr/lib/llvm/14/lib64
flo@vnpc ~/tu/libelektra_fork/libelektra/cmake-build-debug $ make
```

### Proposed improvement
If the variable is required, it should be mentioned in the documentation.
e.g. 
- https://www.libelektra.org/compiling/compile
- https://www.libelektra.org/tutorials/contributing-with-clion
- ...

## System Information

- Elektra: master
- Operating System: Gentoo Linux with kernel 5.19.11

**Comment by kodebach** [comment]
> As the error message indicates, the environment variable LIBCLANG_PATH was not set on my system.

It's not set on my system either and I can build the rust bindings. It looks like something isn't correctly installed on your system or is in an unexpected location. (Note: On my system `libclang.so` is in `/usr/lib/libclang.so`)

AFAICT the issue comes from [this function](https://github.com/KyleMayes/clang-sys/blob/da1d08897f947302b9351c93c5e445a7b4c3df8e/build/common.rs#L246) from the clang-sys crate. It uses the `LIBCLANG_PATH` env-variable as an override, but it should find the libraries without it too.

If the install location of your `libclang.so` is standard for Gentoo, you might want to report the issue to the [clang-sys repo](https://github.com/KyleMayes/clang-sys).
