### ISSUE TITLE
[FLOSS H1] First impression

### ISSUE THREAD

**Issue by Janldeboer** [ElektraInitiative/libelektra#4596]
It was very easy to install Elektra using homebrew as described in the documents.
I tried to get a GUI working then, but I could find a compiled/runnable one for macOS quickly,
so I just used kdb to set & change some value/key pairs. That worked perfectly as expected.

## System Information

- Elektra: master
- Operating System: macOS

**Comment by markus2330** [comment]
Please elaborate which documents you looked at.
