### ISSUE TITLE
"wrong" order in README.md leads to compile error

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#461]
having a `README.md` like this (with `infos/status` as last key):

	 - infos/author = Peter Nirschl <peter.nirschl@gmail.com>
	 - infos/licence = BSD
	 - infos/needs = 
	 - infos/status = experimental
	 - infos/provides = filefilter
	 - infos/placements = postgetstorage presetstorage
	 - infos/description = Cryptographic operations
	 - infos/status = experimental
    
    ## Introduction ## 

leads to a `readme_*.c` like this:

	keyNew("system/elektra/modules/crypto_openssl/infos",
	KEY_VALUE, "Information about crypto plugin is in keys below", KEY_END),
	keyNew("system/elektra/modules/crypto_openssl/infos/author",
	KEY_VALUE, "Peter Nirschl <peter.nirschl@gmail.com>", KEY_END),
	keyNew("system/elektra/modules/crypto_openssl/infos/licence",
	KEY_VALUE, "BSD", KEY_END),
	keyNew("system/elektra/modules/crypto_openssl/infos/needs",
	KEY_VALUE, "", KEY_END),
	keyNew("system/elektra/modules/crypto_openssl/infos/provides",
	KEY_VALUE, "filefilter", KEY_END),
	keyNew("system/elektra/modules/crypto_openssl/infos/placements",
	KEY_VALUE, "postgetstorage presetstorage", KEY_END),
	keyNew("system/elektra/modules/crypto_openssl/infos/description",
	KEY_VALUE, "Cryptographic operations\n"
	keyNew("system/elektra/modules/crypto_openssl/infos/status",
	KEY_VALUE, "experimental", KEY_END),
	"\n"
	"## Introduction ##\n"
    ...

that throws a compile error like this:

    /root/elektra/src/plugins/crypto/readme_crypto_openssl.c: In function 'libelektra_cryptoopenssl_openssl_LTX_elektraPluginget':
    /root/elektra/src/plugins/crypto/readme_crypto_openssl.c:15:1: error: expected ')' before 'keyNew'
     keyNew("system/elektra/modules/crypto_openssl/infos/status",
     ^

Moving `infos/status` above `infos/description` solves the problem. It is easy to work around but inconvenient. I would expect that the order of the keys at the top of `README.md` does not matter.

**Comment by markus2330** [comment]
The order should not matter, except for `infos/description` which is not a one-liner, but spans over the rest of the file.

**Comment by petermax2** [comment]
Oh okay, I got the idea of `infos/description` wrong then. I thought it was a short description like the `@brief`tag in doxygen. I'm fine with it if you want to close the ticket.

**Comment by markus2330** [comment]
Thanks for reporting, it is a valueable input. I will change the template so that it is clear that description spans over multiple lines. So lets keep the issue open until at least the `template` and `doc`-plugins make that clear. I also need to add `infos/status` there.

**Comment by markus2330** [comment]
Thanks, should be resolved.
