### ISSUE TITLE
add consistency check for contrib

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4618]
Extend ./tests/shell/check_doc.sh to also work for:

- [ ] doc/contrib
- [ ] doc/tutorials

**Comment by joni1993** [comment]
I was unsure about the missing README.md in ´docs/contrib` so i added a file check before executing the tests for each of them.

Also i added brackets the the grep statement because i noticed `docs/tutorials/cmerge.md` was also found for `merge.md`.

**Comment by joni1993** [comment]
The check also reveals 3 errors (which are not part of the PR):

error: Failed to find link to symbol-versioning.md in the file /home/joni/Development/libelektra/doc/dev/README.md
error: Failed to find link to symbol-versioning.md in the file /home/joni/Development/libelektra/doc/dev/README.md
error: Failed to find link to validation.md in the file /home/joni/Development/libelektra/doc/decisions/README.md

**Comment by markus2330** [comment]
> I was unsure about the missing README.md in ´docs/contrib`

Please add the README.md and also the missing links.

**Comment by joni1993** [comment]
I am unsure about the contents of the doc/contrib/README .md so i left that unchanged - the test fails now because the file is missing, but everything else should be good.
