### ISSUE TITLE
Javadoc issue on master

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#4627]
The failing builds are only those using Debian Sid. I assumed the issue is that Sid now includes a new package that causes issues, so I ran the build in docker locally and running Gradle with `--stacktrace` showed that the issue was:

```
Could not start '/usr/lib/jvm/java-17-openjdk-amd64/bin/javadoc'
```

I checked and:

```sh
$ ls '/usr/lib/jvm/java-17-openjdk-amd64/bin/javadoc'
ls: cannot access '/usr/lib/jvm/java-17-openjdk-amd64/bin/javadoc': No such file or directory
```

So **a quick fix for the issue would be**: Install `openjdk-17-jdk-headless` in the docker container.

A more permanent solution would be finding out, why our CMake setup tries to use JDK 17 at all, when only JRE 17 is installed. There is no `javac` for Java 17:

```sh
$ ls '/usr/lib/jvm/java-17-openjdk-amd64/bin/'
java  jpackage  keytool  rmiregistry
```

Possibly the issue is that Debian is set up like this:

```sh
$ realpath /usr/bin/java
/usr/lib/jvm/java-17-openjdk-amd64/bin/java
$ realpath /usr/bin/javac
/usr/lib/jvm/java-11-openjdk-amd64/bin/javac
```

and we only check `java --version` to get the version number and then assume that is correct. If that's the case, we should probably use `javac --version` instead. But AFAICT we use

https://github.com/ElektraInitiative/libelektra/blob/2c8a630bb0ad6cb51342d1d1795f762bd4bfff5c/src/bindings/jna/CMakeLists.txt#L2

which is built into CMake, so a fix might be a bit more complicated and may even needs an upstream bug report.

**Comment by kodebach** [comment]
> Any reason why we don't add this by default?

We could, but I'm not 100% certain where we'd have to add it. I built without CMake, directly calling the failed task `./gradlew --stacktrace :hello:javadoc` to find the error.

**Comment by markus2330** [comment]
@flo91 will you have time today? This is urgent, as without a fix all new PRs (H2 deadline is soon) will fail on the build server.

**Comment by atmaxinger** [comment]
@markus2330 I can do it

**Comment by markus2330** [comment]
Thank you so much! :heart:

**Comment by flo91** [comment]
Thank you for helping out! 🥇 
Unfortunately, I was quite busy the last two days...
