### ISSUE TITLE
lua/python plugins with /module

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#463]
lua/python plugins seem to return too early with /module present.

The idea of /module is to avoid that plugins fail in `kdbOpen()` if we are only interested in their contracts. In the case of lua/python different scripts might modify the contract, thus `kdbOpen()` should try to load the script so that we get the correct contract, also if /module is present.

The behaviour when without `/script` but with `/module`, however, is correct (just return default contract). Only the case with valid `/script` and with `/module` should be different.

Should be an easy fix, you can reassign it to me if you have no time.

**Comment by manuelm** [comment]
I bet you're at least twice as fast as me with fixing this :smiley:

**Comment by markus2330** [comment]
Ok, np.

With the next release it will be possible to load multiple lua/python plugins with different contracts.

**Comment by manuelm** [comment]
While you're at it: I'm for removing technical preview flags.

**Comment by markus2330** [comment]
ok, makes sense
