### ISSUE TITLE
alpine linux: docker hub images not tagged correctly

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#4633]
The [docker hub](https://hub.docker.com/r/elektra/elektra/tags) images are not tagged correctly in the release pipeline.

The last image that was pushed to elektra/elektra is tagged as latest, regardless whether it is alpine linux or not.
Thus it is possible that our minimal "elektra/elektra" image is actually a ubuntu image >500mb.

The release pipeline should only tag the alpine image as latest, s.t. `elektra/elektra:latest` is always the tiny alpine image.

**Comment by markus2330** [comment]
Thank you for reporting this issue!

@robaerd can you maybe point us to the code?

**Comment by mpranj** [comment]
I'm not sure why this happened, maybe docker hub automatically tags latest?

In the release pipeline alpine seems to be the only one setting the tag.
https://github.com/ElektraInitiative/libelektra/blob/2c8a630bb0ad6cb51342d1d1795f762bd4bfff5c/scripts/jenkins/Jenkinsfile.release#L712

**Comment by kodebach** [comment]
> 

AFAIK `latest` is also the default tag, if you don't

**Comment by mpranj** [comment]
Seems like a tag is always set:
https://github.com/ElektraInitiative/libelektra/blob/2c8a630bb0ad6cb51342d1d1795f762bd4bfff5c/scripts/jenkins/Jenkinsfile.release#L1195-L1211
