### ISSUE TITLE
reduce docker images

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4637]
- [ ] scripts/docker/jenkinsnode/Dockerfile see  #4620
- [ ] scripts/docker/fedora/32/Dockerfile
- [ ] remove not used packages (e.g. ninja vs. make)

**Comment by markus2330** [comment]
As [0x6178656c](https://github.com/0x6178656c) wrote in https://github.com/ElektraInitiative/libelektra/pull/4620#issuecomment-1295395453:

- If this image is still relevant this should be documented accordingly
- If this image is no longer used it should be removed from repository

**Comment by markus2330** [comment]
We are regularly running into "no space left" problems because of too many Docker images, so I tagged it as urgent and removed the "probably to be removed".

@mpranj any other suggestions other than the two Docker images above?

**Comment by kodebach** [comment]
One thing I noticed about our images is that they are **very** big. Maybe we can look into making them smaller, that should help with the disk space problems.

**Comment by mpranj** [comment]
> We are regularly running into "no space left" problems because of too many Docker images, so I tagged it as urgent and removed the "probably to be removed".

I think this will not save any space.

AFAIK: removing unused images will do nothing to our disk space usage, as the images are not built by the pipeline. The images are build only when needed.
We are actively using many images, so that is a problem.

> One thing I noticed about our images is that they are very big.

Would be great if we can do something about this.

Maybe we can add the docker build option `--squash` to avoid storing multiple layers of the filesystem.
There are always pros and cons, but it's worth a shot.

**Comment by kodebach** [comment]
> Maybe we can add the docker build option `--squash` to avoid storing multiple layers of the filesystem.

Wouldn't that mean different images can't share a layer and all images would have to be built entirely from scratch, if there is the tiniest difference?

> The images are build only when needed.

So do we actually build new images for every Jenkins run? Is there any kind of auto-cleanup? 

--- 

Also, since I don't have access to the CI servers: Are we sure that the docker images are the problem? Could there be something else that is eating disk space too, e.g. log files with long retention periods, or artifacts of old builds?

**Comment by mpranj** [comment]
> Wouldn't that mean different images can't share a layer and all images would have to be built entirely from scratch, if there is the tiniest difference?

Yes, but I'll test this now to see if there is any difference.
Also, I know this is how it should be true on one machine, but I have a feeling we're not reusing layers anyhow.

> Also, since I don't have access to the CI servers: Are we sure that the docker images are the problem?

Yes, pretty sure it is at least the biggest problem. Most other things are cleaned up.

> So do we actually build new images for every Jenkins run? Is there any kind of auto-cleanup?

Not for every run, but when they are needed. So images are reused once they are build. They are rebuilt monthly s.t. the packages are updated periodically.

**Comment by mpranj** [comment]
> Wouldn't that mean different images can't share a layer and all images would have to be built entirely from scratch, if there is the tiniest difference?

Unfortunately you're right.
I've tested the `--squash` option and for the case of the `build-elektra-fedora-36` images the difference is only 2.16GB vs 2.03GB.

**Comment by kodebach** [comment]
Okay, how exactly is our Fedora 36 Image over 2GB in size, when the base `fedora:36` image is  <60MB (see [Docker Hub](https://hub.docker.com/_/fedora/tags))? There has to be something in there that we don't need...

Another thing we could do: Remove Java from all images except one, maybe even remove it completely from Jenkins and only test on Cirrus. The JVM should be the same everywhere.

**Comment by markus2330** [comment]
> Also, since I don't have access to the CI servers: Are we sure that the docker images are the problem? Could there be something else that is eating disk space too, e.g. log files with long retention periods, or artifacts of old builds?

After running `docker prune -af` the disc space usage goes from 100% to less than 20%.

**Comment by kodebach** [comment]
>  the idea was to suggest which used Docker images (probably the least important ones) to remove or how to make them smaller.

I see we have 4 different Debian Bullseye images? Why? I get the `minimal` image to test without installing dependencies, but the rest are probably wasting space. The same goes for Debian Buster.

Also if `docker image prune -af` (or even `docker system prune`) cleaned up > 1TB auf space, I would really be interested in what exactly was removed. e.g. `docker image ls` before and afterwards would be interesting.

Additionally, we can probably run `docker image prune` (without `-a`) much more often. It should not remove anything we need.

**Comment by markus2330** [comment]
> I see we have 4 different Debian Bullseye images? Why?

To also test cmake exclusion of modules. Probably we should make these images build upon each other to use less space?

> Maybe we should prune -af weekly?

Yes, sounds like the easiest solution for now. Is there some way to only cleanup the images that weren't used for a week?

> What machine are you talking about?

In https://github.com/ElektraInitiative/libelektra/issues/4637#issuecomment-1313475416 I was talking about a7 of the recent incident https://github.com/ElektraInitiative/libelektra/issues/160#issuecomment-1312652971.

**Comment by 4ydan** [comment]
So I did a small investigation on the "scripts/docker/fedora/32/Dockerfile" image.
I analyzed its layers and most of the size comes from all the packages installed.
![image](https://github.com/ElektraInitiative/libelektra/assets/53004139/b192ab69-41ff-4e2e-a163-0bd1692307f9)

As for the package sizes, they are pretty evenly distributed. Here is a table of the top 10 packages by size.
| Package                                          | Size (MB) |
|--------------------------------------------------|-----------|
| golang-bin-1.14.15-3.fc32.x86_64                 | 255.98    |
| java-11-openjdk-headless-11.0.11.0.9-0.fc32.x86_64 | 170.76    |
| java-1.8.0-openjdk-headless-1.8.0.292.b10-0.fc32.x86_64 | 117.47    |
| clang-libs-10.0.1-3.fc32.x86_64                  | 92.07     |
| gcc-10.3.1-1.fc32.x86_64                         | 81.71     |
| llvm-libs-10.0.1-4.fc32.x86_64                   | 78.23     |
| glibc-debuginfo-2.31-6.fc32.x86_64               | 76.42     |
| mesa-dri-drivers-20.2.3-1.fc32.x86_64            | 65.74     |
| glibc-debuginfo-common-2.31-6.fc32.x86_64        | 57.20     |
| python27-2.7.18-8.fc32.x86_64                    | 54.59     |

Adding these options to the dnf install reduced the image size by ~15%
`dnf install --setopt=install_weak_deps=False --setopt=tsflags=nodocs --setopt=clean_requirements_on_remove=True --setopt=installonly_limit=2`

--setopt=install_weak_deps=False: This flag disables the installation of weak dependencies, which can help reduce the number of unnecessary packages installed.

--setopt=tsflags=nodocs: This flag prevents the installation of documentation files, reducing the overall package size. Note that not all packages provide separate documentation packages.

--setopt=clean_requirements_on_remove=True: This flag removes unnecessary dependencies when removing a package. It helps keep the system clean and avoids accumulating unused dependencies.

--setopt=installonly_limit=2: This flag sets the number of package versions to keep during installations. It can help prevent the accumulation of unnecessary package versions, reducing the image size.

![image](https://github.com/ElektraInitiative/libelektra/assets/53004139/88d3bc6d-92f1-40dd-bba1-6649a3778615)
Not sure if this helps.

**Comment by markus2330** [comment]
Thank you for the investigation. Yes, please add this option(s).
