### ISSUE TITLE
qt-gui BackendBuilder

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#465]
There is a new interface to create backends, called BackendBuilder. Its main features are:

1. it reorders plugins if they need a special order (no more OrderViolation exceptions)
2. it automatically adds dependencies (no more missing dependencies exceptions)
3. it allows to remove plugins
4. it allows to automatically add recommends (simply pass a boolean variable to the API)

The usage of the new API should be trivial (See 7022ad47e6003344cb96581592afaaf0509d6c07, basically `s/Backend/MountBackendBuilder/` and additionally call the method `resolveNeeds`). The question is, if you also plan to support 3. and 4. Especially, 3. was something you wanted to have, thus I ask.

**Comment by 0003088** [comment]
I'm a little busy ATM, but I will look into it. It should not be too much work to add a remove button and a radio button. When do you plan to release 0.8.15?

**Comment by markus2330** [comment]
Thanks for your interest to add the buttons!

Release is hopefully quite soon, currently we are only fixing bugs. So it seems better if we just rename Backend to MountBackendBuilder for now?

**Comment by 0003088** [comment]
Yeah, that would be better I suppose. I noticed that the path of the libraries changed to libs/tools instead of libtools. Eventhough I changed that in my qt-gui.pro file I cannot compile the qui with qtCreator because the compiler tells me that there is an undefined reference to kdb::tools::ModulesPluginDatabase. But the file can be found by the editor and the path to the *.hpp is in my INCLUDEPATH. What am I missing?

**Comment by markus2330** [comment]
The ModulesPluginDatabase should be part of libelektratools, maybe you link against an outdated version of libelektratools?

But you do not need to bother for this release, it should be fixed for now.

**Comment by 0003088** [comment]
It was the outdated library and I was missing the new library elektra-ease. It's working now.

**Comment by markus2330** [comment]
Thank you for the update!

**Comment by 0003088** [comment]
Just for clarifiction: backenbuilder.hpp is supposed to completely replace backend.hpp or will they coexist? Is GlobalPluginsBuilder::globalPluginsPath the same as Backends::mountpointsPath?

**Comment by markus2330** [comment]
`BackendBuilder` can write out different backends, e.g. `Backend` or `GlobalBackend`. In future Backend will be legacy and a new `LazyBackend` will be the default.

So yes, `BackendBuilder` has completely replaced `Backend` as new interface to build backends, Backend is only the low level serialization mechanism and should not be used directly (because of the ordering problem and the impossibility to remove plugins there).

Those pathes are different, GlobalPluginsBuilder::globalPluginsPath is only for `GlobalBackendBuilder`.

**Comment by 0003088** [comment]
ok, so backend is not to be supposed to build backends but the class will be still there, so it's possible to further use Backends::mountpointsPath?

**Comment by markus2330** [comment]
I am not sure what you mean, `Backend` and `Backends` are unrelated classes?

**Comment by 0003088** [comment]
Oh, sorry, missed the s. It's been a while since I wrote the code, I need to familiarize myself with the whole stuff again.

**Comment by markus2330** [comment]
No problem, do not hesitate to ask any further question.

**Comment by markus2330** [comment]
@0003088 One more important remark: We are going to completely reformat the C/C++ source. Do you already have a branch you are working on? It would be difficult to merge for you then, unless you also apply clang-format on your branch. Is this possible for you?

**Comment by 0003088** [comment]
Can't I just pull the changes into my branch? Should I wait until you reformatted the source before I begin to include the new class?

**Comment by markus2330** [comment]
Pulling in would conflict with every change you made. So if you haven't started its best to wait. I will reformat today or tomorrow.

**Comment by markus2330** [comment]
removing milestone for adding buttons, better to focus on #528 #603 (which seems like they are duplicates)

**Comment by 0003088** [comment]
Maybe I overlooked it but is there a way to get the already included plugins as a list?

**Comment by markus2330** [comment]
The `begin()`/`end()` interface allows you to iterate over the already added plugins. So you simply can use a `for (auto const & elem : backendbuilder) {}`

**Comment by 0003088** [comment]
For testing purposes: can you name a plugin that pulls in recommended plugins if added to a backend?

**Comment by markus2330** [comment]
augeas, hosts, fstab (see infos/recommends). Note that recommendations are not automatically resolved when plugins are added, you need to call resolveNeeds(true).

Btw. at the command-line it is now also possible to enter provider names and a providing plugin is automatically searched for: e.g. you enter json, but you get yajl (a plugin that provides json). Is it possible to provide text input that filters/searches in the plugins, but also allows you to add arbitrary text to be added as plugin, even if there are no matches?

@sirblackheart What do you think?
