### ISSUE TITLE
Jenkins pipeline not aborting

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#4671]
I don't know when this changed, but [this](https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-4246/18/pipeline) is now at least the third Jenkins run I've seen, where the pipeline does not abort on failure.

Maybe this was an intentional change, but if so I don't understand the reason. Previously, the pipeline stopped when tests failed. Now we waste time by running all the other jobs as well only to in the end report to Github "hey something failed".

The most annoying part is actually, that the individual job in the pipeline that caused the failure **is not** marked as failed. So you have to check all the jobs and all the steps to find the logs of the failure, if the excerpts in the Tests tab are not enough. 

Known examples:
- https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-4246/18/pipeline
- https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-4602/9/pipeline
- https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-4650/4/pipeline
- https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-4724/3/pipeline

PS @markus2330 I didn't label it as such, IMHO this is an "urgent" issue and must be fixed ASAP.

**Comment by markus2330** [comment]
Thank you for bringing it up! :revolving_hearts:  I totally agree it is very annoying.

Maybe it is my fault, as already mentioned briefly it might be a mess-up because of changes with `--rerun-failed` done in #4561. I didn't have a minute of silence to investigate it, though...

**Comment by kodebach** [comment]
Yes, I think that is the issue. See [here](https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-4246/18/pipeline/810/#step-938-log-485). The test failed in the first run, but if you scroll down, it succeeds in the second run. That is what we wanted to achieve with the `--rerun-failed` (avoid flaky tests), but for that the Jenkins failure detection is wrong.

However, in this particular case the test isn't even really flaky. The issue is simply that `testscr_check_spelling` fixes spelling mistakes and then doesn't undo them. For running tests locally, this is actually a good idea.

IMO we should just remove the `--rerun-failed` entirely from everywhere. It was always a bit of a hack. We should at least try removing it for a while to see, if there even are any flaky tests right now. IIRC the issue was with the `dbus` and `zeromq` tests and those aren't even executed on Jenkins AFAICT.

**Comment by markus2330** [comment]
> IMO we should just remove the --rerun-failed entirely from everywhere.

Unfortunately, this is not possible. Hardly any build run would succeed then.

> if there even are any flaky tests right now.

There are plenty, they don't go away by themselves. On most of them there was already work done and no easy solution could be found.  I don't see a realistic way how to fix all of them. There are also much more important things to do.

Probably, we should configure Jenkins not to fail if "only" tests cases failed. I wonder why this behavior changed?

**Comment by kodebach** [comment]
> Hardly any build run would succeed then.

Do have an actual recent example to prove that? I.e. a build log where the first run failed and the automatic rerun succeeded and that is what we wanted?

Ideally the examples are not from Jenkins. If we only see this flakiness on Jenkins, it suggests the problem is with our setup.

> I wonder why this behavior changed?

It did not. AFAICT Jenkins never did do an automatic rerun, at least not in those cases that you changed. I think that is because `dbus` and zeromq`, which are the reason the reruns were added, were excluded already.

> There are also much more important things to do

IMO a working CI that doesn't waste time and annoy developers is very important. I'd much rather have a CI with flaky tests that I have restart manually sometimes than the current situation where you need to wait hours to find out the build failed in one of the first steps.

**Comment by markus2330** [comment]
It happened while working https://github.com/ElektraInitiative/libelektra/pull/4561, maybe you find a build log there. Could be that it also only happened locally.

> which are the reason the reruns were added

There were other flaky tests already much earlier, e.g. threading tests with contextual values.

> IMO a working CI that doesn't waste time and annoy developers is very important.

I absolutely agree. Thus I fixed a "no space left on device" error on Sunday morning.

> I'd much rather have a CI with flaky tests that I have restart manually sometimes than the current situation where you need to wait hours to find out the build failed in one of the first steps.

Constantly retriggering flaky tests is a terrible developer experience. A few month ago we had both: pipeline failed early and flaky tests rerun was working properly.

**Comment by kodebach** [comment]
> There were other flaky tests already much earlier, e.g. threading tests with contextual values.

Emphasis on **were**. Do you have current examples? If not I would try to remove the rerun-failed stuff. If we then need to trigger lots of reruns manually, we can revert the change. But then we would at least now which tests **currently** are flaky. In some cases, there may be ways of changing the tests to avoid the flakiness without having to rerun.

For example, for the `dbus`/`zeromq` I remember that the issue seemed to be very high CPU load. A solution I suggested, which AFAICT was never tested, was to use the CTest option to limit the maximum CPU load.

> Some time ago we had both: pipeline failed early and flaky tests rerun was working properly.

AFAICT this was before you added the extra `--rerun-failed` to the Jenkinsfile.

**Comment by Bujuhu** [comment]
Hi!

I noticed, that the [tests/shell/check_spelling.sh](https://github.com/ElektraInitiative/libelektra/blob/master/tests/shell/check_spelling.sh)
script will only ever return the exit code for the last command (at least if it works like a normal shell script, I'm not too familiar with the particularities with Jenkins)

If the first command fails completely, there won't ever be changes introduced, so the second command will return 0 and the task would be successful. I didn't find any examples of this and I don't think it's the cause of the problem either, but I think it's related to the issue.

**Comment by kodebach** [comment]
See https://github.com/ElektraInitiative/libelektra/pull/4724#issuecomment-1337060681 for a description of what I believe happend in a recent case.

I don't know, if we have any kind of audit tool on the CI server that could tell us, what happened with the `/home/jenkins/workspace/libelektra_PR-4724/config/kdb/system/elektra.ecf` file.

**Comment by markus2330** [comment]
Thank you for adding! There are different issues involved and we should separate them:

1. the issue described here: that the CI passes even though a test case failed
2. some concurrency or leak-of-data event that causes random KDB test cases to fail

I can only discourage from trying to debug 2. directly on the CI system. It makes much more sense to run the tests locally, maybe with strace or similar tools.

**Comment by kodebach** [comment]
> I can only discourage from trying to debug 2. directly on the CI system. It makes much more sense to run the tests locally, maybe with strace or similar tools.

No, unless somebody has actually seen this issue happen in a local test, debugging locally makes no sense. I highly suspect that there is some background process running on the Jenkins system that (for whatever reason) removes the file in question.

IMO what would make sense is to add some kind of auditing tool that watches all `/home/jenkins/workspace/*/config` directories for changes. Then we could look at a log of a failed test and see, if the file actually was created and removed while the test was running.

Also we should find a way to keep the pipeline logs for the problematic pipelines. Right now only the latest one I added today is accessible. The older links just don't load for me.

**Comment by kodebach** [comment]
@markus2330 AFAICT, before #4561 Jenkins did not use `--rerun-failed` at all. Looking at the Jenkinsfile, only the lines use added use `--rerun-failed` directly. The `run_*` scripts that use `--rerun-failed` internally, are also not used on Jenkins AFAICT. There is no e.g. `make run_all`, only `kdb run_all`, but that doesn't do any kind of rerun.

So I propose, we remove `--rerun-failed` from the Jenkinsfile. This should get rid of the "Jenkins doesn't abort" problem. Since we didn't have the flaky tests before #4561 AFAIK, I suspect the tests were only flaky on other CIs (Cirrus, GitHub, Travis), which do use the `run_*` scripts.

**Comment by markus2330** [comment]
Yes, please try it out in a PR.

**Comment by kodebach** [comment]
I created #4778. Let's see what the CI says.

> **Note**: For now I have disabled the `rerun-failed` everywhere, so we can see, if it is still needed at all. It can be enabled on the non-Jenkins CI systems by setting the environment variable `ELEKTRA_AUTO_RERUN=1`.

**Comment by kodebach** [comment]
I think this issue has become more urgent...

It seems the `ctest --rerun-failed` doesn't even necessarily rerun the correct tests. See for example: https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-4811/4/pipeline/810#step-938-log-579

The `testscr_check_spelling` failed in the first run, but then the rerun only runs `testscr_check_resolver`...
