### ISSUE TITLE
kdbGet never returns 0

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#4673]
## Steps to Reproduce the Problem

According to the docs, `kdbGet` should sometimes return 0

https://github.com/ElektraInitiative/libelektra/blob/3df353db3aac89874a5b04ec80d098935e8fafd5/src/libs/elektra/kdb.c#L1690-L1691

## Expected Result

The docs match the real behaviour

## Actual Result

If you look at the code, `kdbGet` definitely never returns 0.

## Further Notes

https://github.com/ElektraInitiative/libelektra/commit/85e8e19edcbfdb41fded4f8204a012cc6c162765 is an attempt to fix this. But the test case fails in the `BUILD_FULL` configuration. See e.g. https://cirrus-ci.com/task/5946551403544576

**Comment by markus2330** [comment]
Thank you for reporting this problem!

Yes, it is important that situations where nothing changed are detected, nothing is done and 0 is returned, so this should be reimplemented.
