### ISSUE TITLE
new-backend: adds useless warnings

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4675]
## Steps to Reproduce the Problem

Make a checker plugin fail, e.g.:

```
kdb mount type.toml user:/tests/type toml type
kdb meta-set user:/tests/type/latitude type double
```

## Expected Result

```
Sorry, module type issued the error C03200:
Validation Semantic: The type 'double' failed to match for 'user:/tests/type/latitude' with string ''
```

## Actual Result

```
 Sorry, 2 warnings were issued ;(
 1: Module kdb issued the warning C01320:
        Interface: Calling the kdbSet function for the backend plugin ('backend') of the mountpoint 'user:/tests/type' has failed during the PRE_STORAGE phase.
 2: Module kdb issued the warning C01320:
        Interface: The PRE_STORAGE phase of kdbSet() has failed. See warnings for details.
Sorry, module type issued the error C03200:
Validation Semantic: The type 'double' failed to match for 'user:/tests/type/latitude' with string ''
```

**Comment by kodebach** [comment]
I don't see the warnings as completely useless, they tell you which backend failed and during which phase it failed. It also covers the case, where a plugin returns an error status, but doesn't set an error.

Maybe we put these warnings behind some kind of debug flag. However, I don't see that as an urgent issue.

**Comment by kodebach** [comment]
Note: I unassigned myself, because I don't see any reason why I specifically have to do this. Anybody should be able to fix this issue. By searching for text fragments from the warning it should be quite obvious where the warnings are produced.

**Comment by markus2330** [comment]
Logging and warnings should not be confused. I agree that logs about what happens in which phase can be useful. Warnings are, however, not designed for logging.

This is simply something that wasn't found in the review of #4187.

**Comment by kodebach** [comment]
I agree that logging and warnings are different, but at least for "the case, where a plugin returns an error status, but doesn't set an error", the warning/error makes sense.

So probably the solution is (when an error status is returned)
1. Check if the plugin set an error
2. If it did, use logging
3. If it did not, add a generic error like the one we have now as a warning

**Comment by markus2330** [comment]
> I agree that logging and warnings are different, but at least for "the case, where a plugin returns an error status, but doesn't set an error", the warning/error makes sense.

I fully agree, I think we can use ELEKTRA_SET_INTERFACE_ERROR here.
