### ISSUE TITLE
Doc: harmonize Git spelling

### ISSUE THREAD

**Issue by joni1993** [ElektraInitiative/libelektra#4679]
As brought up in https://github.com/ElektraInitiative/libelektra/pull/4629#pullrequestreview-1172200219 Git is sometimes spelled as Git and sometimes as GIT.

As it is not an acronym - it should be changed to `Git`.

**Comment by joni1993** [comment]
One questions remains: should we also rename "git" to "Git" ?

**Comment by markus2330** [comment]
Thank you for bringing it up! I agree with everything said here. scripts/sed could even change GIT with any capitalization (except all lowercase) to Git. git -> Git probably only can be done by hand as there is no guarantee that `git` (referring to the command) always is within a code block.
