### ISSUE TITLE
Vote for line length

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#469]
As discussed in #467 and  #459, please vote for the number of characters you want per line. You can give multiple numbers in order of preference.

Everyone that has at least one commit or created at least one issue can vote.

**Comment by sanssecours** [comment]
1. 80
2. 72
3. 100
4. 120
5. 150

**Comment by fberlakovich** [comment]
1. 150
2. 120
3. 100
4. 72
5. 80

Sorry, not meant to troll, but I usally work on large widescreen displays. Therefore I would prefer longer line lengths.

**Comment by petermax2** [comment]
1. 150
2. 140
3. 100
4. 80
5. 72

I don't like it when statements span across several lines. We're not using punchcards anymore.

**Comment by tom-wa** [comment]
1. 140
but anything >=120 && <=145 would work for me

**Comment by KurtMi** [comment]
1. 120
2. 100
3. 80
4. 140
5.150

**Comment by markus2330** [comment]
I prefer values near 130 (that is the value where two columns still work nicely and text readability is nice when 6 tabs are used), so:

1. 130
2. 120 or 140
3. 110 or 150

I would, however, not use 130 characters in a line that is not indented.

**Comment by markus2330** [comment]
Thanks for your participation!

@KurtMi Can you calculate the voting result via https://de.wikipedia.org/wiki/Condorcet-Methode and update the coding style?
@sanssecours Can you update the style file?

**Comment by sanssecours** [comment]
Since I wanted to check out how the Condorcet-Method worked, I tried it out myself:

---

Ranking:

    80 > 72 > 100 > 120 > 150
    150 > 120 > 100 > 72 > 80
    150 > 140 > 100 > 80 > 72
    140 > 130=120 > 72=80=100=150
    120 > 100 > 80 > 140 > 150
    130 > 120=140 > 110=150

Possible Values: 72, 80, 100, 120, 130, 140, 150

    72  vs. 80 : 1  2  (80 won)  
    72  vs. 100: 1  2  (100 won)
    72  vs. 120: 1  1  (72/120 tied)
    72  vs. 130: 0  1  (130 won)
    72  vs. 140: 0  1  (140 won)
    72  vs. 150: 1  1  (72/150 tied)
    
    80  vs. 100: 1  3  (100 won)
    80  vs. 120: 1  3  (120 won)
    80  vs. 130: 0  1  (130 won)
    80  vs. 140: 1  2  (140 won)
    80  vs. 150: 2  2  (80/150 tied)
    
    100 vs. 120: 1  2  (120 won)
    100 vs. 130: 0  1  (130 won)
    100 vs. 140: 1  2  (140 won)
    100 vs. 150: 2  2  (100/150 tied)
    
    120 vs. 130: 0  1  (130 won)
    120 vs. 140: 1  1  (120/140 tied)
    120 vs. 150: 4  1  (120 won)
          
    130 vs. 140: 1  1  (130/140 tied)
    130 vs. 150: 2  0  (130 won)
    
    140 vs. 150: 3  1  (140 won)
    
    ––––––––––––––––––––––––––––––––––––––
    72    80    100   120   130  140   150
    --------------------------------------
     1   1.5    2.5   4     5.5  5     1.5
    6th  5th    4rd   3rd   1st  2nd   5th
    ––––––––––––––––––––––––––––––––––––––

---

Looks like **130** won. Maybe someone else can check if my results are correct.

**Comment by KurtMi** [comment]
@sanssecours how have you calculated the floats?

Since not all participants have ordered all possible values I sorted the non used values at last position and came to this stats:

    	   150	140	130	120	100	80	72
    lost:	3	0	1	2	3	4	4
    win:	0	4	4	2	2	1	0
    tied:	3	2	1	2	1	1	2

I my opinion **140** should win, because it never lost.

**Comment by sanssecours** [comment]
@sanssecours how have you calculated the floats?

I counted ties as 0.5 for both participants. 

> I my opinion 140 should win, because it never lost.

Okay for me too. I changed the value of `ColumnLimit` in #468 accordingly.

BTW: 140 would have lost at least once, if I knew that it was a possible value 😀.

**Comment by KurtMi** [comment]
> BTW: 140 would have lost at least once, if I knew that it was a possible value :grinning:.

You are right! I think it is hard to evaluate the result if not all values are sorted.

**Comment by KurtMi** [comment]
> Okay for me too. I changed the value of ColumnLimit in #468 accordingly.

I think you could stick to 130 :)

**Comment by sanssecours** [comment]
> I think you could stick to 130 :)

Or we could take a vote only between `130` and `140` 🤓. As far as I can tell – looking at the preferences of each participant – this would result in a tie. I will leave it at `140` for now.

**Comment by markus2330** [comment]
Thank you for your participation!
