### ISSUE TITLE
Building of (LaTeX) Reference Manual Fails

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#470]
It looks like somewhere in the build process we add non UTF-8 characters to the LaTeX files produced by Doxygen. According to the output of `find . -name '*.tex' -exec grep -naxv '.*' '{}' /dev/null \;`:

```
./build/doc/latex/doc_GOALS_md.tex:139:{\itshape Trie} or prefix tree is an ordered tree data structure. In Elektra, it provides the information to decide in which backend a key resides. The algorithm, presented in \mbox{[}�����������
./build/doc/latex/md_doc_help_elektra-glossary.tex:32:Already available is the so-\/called X\+DG Base Directory Specification. Perhaps it will define file formats in the future, but currently only the paths are specified. To do so, it introduces some environment variables that help to find the actual configuration. Only if they are unset or empty, a built-\/in fallback should be used. If desired, elektrified applications behave in a X\+DG conforming way. (See the configuration x for \mbox{[}��������������
./build/doc/latex/md_doc_help_elektra-mounting.tex:9:\item everything else \mbox{[}���������
./build/doc/latex/md_doc_help_elektra-plugins-ordering.tex:33:\item \mbox{[}���������������������
./build/doc/latex/md_doc_help_kdb-ls.tex:25:If the user would also like to see the values of the keys below {\ttfamily path} then you should consider the \mbox{[}���������������
./build/doc/latex/md_doc_tutorials_compilation-variants.tex:34:\item \mbox{[}���������������������
./build/doc/latex/md_src_plugins_error_README.tex:107:Also explained \mbox{[}������
./build/doc/latex/md_src_plugins_README.tex:49:\item \mbox{[}�����������
``` 

`markdownlinkconverter` might produce these invalid characters.

Here are steps to reproduce this error:

1. `cmake .. -DBUILD_PDF=ON`
2. `make -j 8`
3. Enter `EOF` (<kbd>^</kbd> + <kbd>D</kbd>) after the CMake output shows a progress value of `[100%]`
4. Output:
```
[100%] Built target testtool_specreader
^D
! Emergency stop.
 ...

l.24 \item \mbox{[}�
                    ���������������������
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on refman.log.
make[2]: *** [doc/latex/refman.pdf] Error 1
make[1]: *** [doc/CMakeFiles/pdf.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by markus2330** [comment]
Cannot reproduce. Seems like doxygen kills your links? Does the markdownlinkconverter work? (@KurtMi: is there a simple way to check if   markdownlinkconverter works?) Which version of doxygen do you have?

Where you get funny characters (E.g. ./build/doc/latex/md_doc_help_elektra-mounting.tex), I have have an hyperlink:
```
  9 \item everything else \hyperlink{md_src_plugins_README_src_plugins_README_md}{plugins} can do.
```

**Comment by KurtMi** [comment]
For me it is also not reproduceable.
There is the possibility to execute the markdownlinkconverter in the commandline:
`bin/markdownlinkconverter /elektra_src/doc/help/elektra-mounting.md`
Execute it from the build dir and the path needs to be absolute.

**Comment by sanssecours** [comment]
> Thank you for reproting!

Thanks for both of your replies!

> But I cannot reproduce. Seems like doxygen kills your links?

Yeah, it looks like it. I tried it again and now it seems that there are less invalid symbols:

```
./doc/latex/doc_CODING_md.tex:88:{\ttfamily doxygen} is used to document the A\+PI and to build the html and pdf output. We also support the import of Markdown pages. Doxygen 1.\+8.\+8 or later is required for this feature (Anyways you can find the \mbox{[}���������
./doc/latex/md_doc_help_elektra-glossary.tex:14:\item \mbox{[}����������
./doc/latex/md_doc_help_elektra-introduction.tex:3:Information on Elektra can be found on the \mbox{[}���������
```

> Does the markdownlinkconverter work? 

Looks like it. The command:

```fish
bin/markdownlinkconverter "$PWD/../doc/CODING.md" > coding.md
```
produces the following output:
```
…/libelektra/build/../doc/CODING.md|81 col 0| warning: invalid link '../src/libelektra/kdb.c'
```
It looks like the resulting file is valid too. At least `grep -naxv '.*' coding.md` does not show anything.

> Which version of doxygen do you have?

According to `doxygen -v` I use version `1.8.11`.

> Where you get funny characters (E.g. ./build/doc/latex/md_doc_help_elektra-mounting.tex), I have have an hyperlink:

I get a valid hyperlink there now too. But the issue somehow persists with varying results:

### Second Run

```
./doc/latex/doc_CODING_md.tex:70:{\bfseries Example\+:} \mbox{[}����������������������
```

### Third Run

```
./doc/latex/doc_decisions_bool_md.tex:79:See \mbox{[}������
./doc/latex/md_doc_help_elektra-contracts.tex:7:The content of the contract is well-\/specified in \mbox{[}��������������
./doc/latex/md_doc_help_elektra-key-names.tex:33:As decided \mbox{[}������
./doc/latex/md_doc_help_kdb-check.tex:53:Please report any output caused by official plugins to \mbox{[}����������������������������������
./doc/latex/md_src_plugins_resolver_README.tex:78:See \mbox{[}������������
```

I guess this is not a bug in `markdownlinkconverter`, since the following [fish](https://fishshell.com) command does not show any invalid characters on my machine:
```fish
for _ in (seq 1000)
  bin/markdownlinkconverter "$PWD/../doc/CODING.md" > coding.md 2> /dev/null
  grep -naxv '.*' coding.md 
end```

**Comment by KurtMi** [comment]
Is it possible that the varying results come from the concurrency by building with `-j`

**Comment by sanssecours** [comment]
> Is it possible that the varying results come from the concurrency by building with `-j` ?

Thank you! Building the documentation with `make` – without specifying any options – works.

**Comment by KurtMi** [comment]
I am curious what component caused the concurrency issue. @sanssecours whats your setup?

**Comment by sanssecours** [comment]
> @sanssecours what distro are you using?

I am afraid the answer to that question is OS X. More specifically OS X 10.11.3:
```
Darwin 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 i386
```

**Comment by KurtMi** [comment]
@markus2330 is this issue really important for the 0.8.15 build?
It looks like this bug only appears on OS X and only when building with `make -j`.
I would say to the mac OS X developers they should try to build the pdf with `make -j` to get more info and then fix it.

**Comment by markus2330** [comment]
No, it is not important.

**Comment by markus2330** [comment]
My build now also failed during building latex:
```
) (./classkdb_1_1KeySetIterator.tex)
! Undefined control sequence.
l.811 \inb
          _1_1tools_1_1Modules}
? 
! Emergency stop.
l.811 \inb
          _1_1tools_1_1Modules}
```

After rerunning the problem was gone. The file `classkdb_1_1KeySetIterator.tex` was not suspicious, at least when I looked at it. Maybe there is a data race that it is read before it is fully written?

The problem seems to be very rare to happen on Linux though.

**Comment by markus2330** [comment]
Seems to happen more often if build from scratch:
```
! LaTeX Error: Lonely \item--perhaps a missing list environment.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.722 \item i
             t documents the keys (including lookup behaviour and default va...

? 
! Emergency stop.
 ...                                              
                                                  
l.722 \item i
             t documents the keys (including lookup behaviour and default va...

!  ==> Fatal error occurred, no output PDF file produced!
```

Is it possible that `make` in the latex folder gets triggered before `doxygen` completed?

Is only one issue described here or are these different issues?

**Comment by KurtMi** [comment]
I can not reproduce this problem on my machine. But I figured  out that for the pdf target a dependency with latex is missing. I hope #476 will fix it.

**Comment by KurtMi** [comment]
Fixed it in #478.

The `.NOTPARALLEL` pseudo target tells make to executes it sequentially. Cmake does not support such targets, so I created a normal one.

In my opinion there is no other way to fix this. Since adding each `*.tex` files in the `doc/latex` folder as dependency for the pdf target is not possible without much effort.

**Comment by markus2330** [comment]
I think I already fixed it in f5576ff, @sanssecours can you confirm? (I tested it 3 times and it seems that pdflatex starts much later.)

@KurtMi for which build systems does .NOTPARALLEL work, what happens for the other ones?

**Comment by sanssecours** [comment]
> I think I already fixed it in f5576ff, @sanssecours can you confirm? (I tested it 3 times and it seems that pdflatex starts much later.)

For now I can confirm that currently, even building Elektra fails (at least on OS X). And sadly I rebased my  current working branch on master quite recently 😱.  So now I have two branches that fail to build at all \o/.

**Comment by KurtMi** [comment]
`.NOTPARALLEL` works for make.
Which other build system do we support?

btw i testet your fix:
```
Runaway argument?
{group__keyset_ga27e5c^^M
! File ended while scanning use of \hyperlink.
<inserted text> 
                \par 
l.803 \input{classkdb_1_1Key}                           
? [100%] Built target html

```
I made a script, to test it:
 ```
#!/bin/bash
    for i in {1..5}
    do
    	mkdir build
    	cd build
    	cmake .. -DBUILD_PDF=1
    	make -j 10000 asd
    	if [ $? -ne 0 ]; then
    		echo "ERRRORORORORORORORORORORORORORORORO"
    	fi
    	cd ..
    	rm -rf build
    done
```

and added a extra traget:
`add_custom_target (asd DEPENDS man3 pdf html latex)`

**Comment by markus2330** [comment]
@KurtMi: hopyfully every build system cmake supports, at least for UNIX.
@sanssecours: Can you check Mac OSX?

**Comment by markus2330** [comment]
@sanssecours and please report an issue for Mac OSX fails. I would be great to have it fixed for the release.

**Comment by sanssecours** [comment]
> @sanssecours: Can you check Mac OSX?

At least `cmake -G Xcode ..` works fine, even after I apply the changes proposed by KurtMi.

> @sanssecours and please report an issue for Mac OSX fails. I would be great to have it fixed for the release.

Okay I will check which commit broke compatibility with [OS X](https://en.wikipedia.org/wiki/OS_X).

**Comment by sanssecours** [comment]
Commit f5576ff does not fix the problem on OS X. Pull request #478 does.

I now also tried `cmake .. -G Xcode -DBUILD_PDF=ON` which works. Building the PDF in Xcode works too.

**Comment by markus2330** [comment]
Perfect! @KurtMi thanks for finding the solution! And thanks for the investigations!

**Comment by markus2330** [comment]
Would be do easy, .NOTPARALLEL, at least in its current form, is not a solution: [it disables parallel-builds completely for the whole makefile](https://www.gnu.org/software/make/manual/html_node/Special-Targets.html). The current solution copies `.NOTPARALLEL` to *every* Makefile, and not only to doc/Makefile (where it would be acceptable). Thus its basically like forcing every build to be with `make -j 1`.

**Comment by markus2330** [comment]
Sorry for the noise, the .NOTPARALLEL in every file has a different reason. It is:
make -j 5  669,46s user 20,98s system 503% cpu 2:17,06 total
make -j 5  681,98s user 22,23s system 500% cpu 2:20,72 total
