### ISSUE TITLE
Invalid links introduced by merging PR #4697

### ISSUE THREAD

**Issue by flo91** [ElektraInitiative/libelektra#4752]
I created the issue for documentation purpose.
I'll promptly fix the links and create a new PR for it.

## Steps to Reproduce the Problem

The CI for the current master branch reports broken links.
These broken links were introduced with renaming of files as a result from a review of the PR #4697.

The following renames are the reason:

- UC_load_config.md -> UC_get_config.md
- UC_store_config.md -> UC_set_config.md

## Expected Result

The CI for the current master branch should pass without errors.

## Actual Result

The following broken links are reported:
```sh
Broken Links:
—————————————
/tmp/cirrus-ci-build/doc/usecases/kdb/UC_modify_config.md:14:0 warning: invalid link 'UC_load_config.md'
/tmp/cirrus-ci-build/doc/usecases/kdb/UC_modify_config.md:16:0 warning: invalid link 'UC_store_config.md'
/tmp/cirrus-ci-build/doc/usecases/kdb/UC_uptodate_config.md:15:0 warning: invalid link 'UC_load_config.md'
/tmp/cirrus-ci-build/doc/usecases/kdb/UC_uptodate_config.md:17:0 warning: invalid link 'UC_load_config.md'
/tmp/cirrus-ci-build/doc/usecases/kdb/UC_uptodate_config.md:19:0 warning: invalid link 'UC_load_config.md'
/tmp/cirrus-ci-build/doc/usecases/kdb/UC_validate_config.md:15:0 warning: invalid link 'UC_load_config.md'
/tmp/cirrus-ci-build/doc/usecases/kdb/UC_validate_config.md:20:0 warning: invalid link 'UC_store_config.md'
/tmp/cirrus-ci-build/doc/usecases/kdb/UC_validate_config.md:24:0 warning: invalid link 'UC_load_config.md'
/tmp/cirrus-ci-build/doc/usecases/kdb/UC_validate_config.md:33:0 warning: invalid link 'UC_load_config.md'
—————————————
```

## System Information

- Elektra: master
- Operating System: Gentoo Linux (custom built kernel 6.0.9)

**Comment by markus2330** [comment]
Thank you so much! Do you know why Jenkins passed?

Seems like an update of a man page is also missing:

https://github.com/ElektraInitiative/libelektra/runs/9864370746

**Comment by flo91** [comment]
You're welcome!
Thanks for pointing out the man page, I've now also updated it. (see commit 00f2168cfa36ae75bf2e0c0029a6964aa463bf45)

It doesn't look like Jenkins passed:
When you scroll to the end of the conversation in the PR #4697, where the merge into master is mentioned, it states `14 of 16 checks passed`.
When you click on `View details` you can see that the two checks (links, man page) also failed there.
