### ISSUE TITLE
Jenkins Image cleanup

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#4779]
Based on the discoveries from the last meeting and the recent troubles with disk space (see #160) I propose we do more immediate cleanup in the Jenkins pipeline.

Currently, we directly build a lot of images in the last stage of the pipeline:

https://github.com/ElektraInitiative/libelektra/blob/90f70811c51a76e758f671f373cace2b98b412ed/scripts/jenkins/Jenkinsfile#L1104-L1169

Each of these `buildPackage` calls does a `dockerUtils.buildImage` call (which executes `docker build`):

https://github.com/ElektraInitiative/libelektra/blob/90f70811c51a76e758f671f373cace2b98b412ed/scripts/jenkins/Jenkinsfile#L1216-L1229

Additionally, there are few `dockerUtils.buildImageStage` (a wrapper around `dockerUtils.buildImage`) calls for the website and web-ui:

https://github.com/ElektraInitiative/libelektra/blob/90f70811c51a76e758f671f373cace2b98b412ed/scripts/jenkins/Jenkinsfile#L749

https://github.com/ElektraInitiative/libelektra/blob/90f70811c51a76e758f671f373cace2b98b412ed/scripts/jenkins/Jenkinsfile#L1334-L1338

https://github.com/ElektraInitiative/libelektra/blob/90f70811c51a76e758f671f373cace2b98b412ed/scripts/jenkins/Jenkinsfile#L1359-L1364

It makes sense to build those images to test, if the build works, but there is no need to keep images around. AFAICT, if the pipeline isn't running on `master` the images aren't even published anywhere.

So I propose we add a `dockerUtils.removeImage` in [ElektraInitiative/jenkins-library](https://github.com/ElektraInitiative/jenkins-library) to execute `docker image rm`. Then we call `dockerUtils.removeImage` either as soon as the images aren't needed anymore, or even better, we add a [`post` section](https://www.jenkins.io/doc/pipeline/tour/post/) to the pipeline for proper cleanup.

**Comment by lukashartl** [comment]
> if you don't produce junk, you don't have to clean it up.

I really like the idea of having a proper post section and cleaning everything up that is produced during the pipeline on the agents.

**Comment by kodebach** [comment]
```diff
diff --git a/scripts/jenkins/Jenkinsfile b/scripts/jenkins/Jenkinsfile
index fbb23a3eb..e5dcf1e53 100644
--- a/scripts/jenkins/Jenkinsfile
+++ b/scripts/jenkins/Jenkinsfile
@@ -207,6 +207,10 @@ Logs: ${currentBuild.rawBuild.getLog(20).join('\n')}
          to: "build@libelektra.org"
   }
   throw e
+} finally {
+  stage("cleanup") {
+    sh "docker image list --format='{{ .Repository }}' '*:${dockerUtils.tagArtifact()}' | xargs docker image rm"
+  }
 }
 
 /*****************************************************************************
```

I think this might actually do the trick. It should add a `cleanup` stage as the last thing before the Pipeline stops (for whatever reason). What I don't know is whether `docker image rm` on the worker node is actually enough to solve our space problem (that's why I didn't make a PR).
