### ISSUE TITLE
macOS jobs broken

### ISSUE THREAD

**Issue by Eiskasten** [ElektraInitiative/libelektra#4789]
Currently, all macOS jobs fail with the same error:

```
==> Pouring python@3.10--3.10.9.big_sur.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.10

To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.10

Possible conflicting files are:
/usr/local/bin/2to3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/2to3
/usr/local/bin/idle3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/idle3
/usr/local/bin/pydoc3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/pydoc3
/usr/local/bin/python3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
```

I am not aware what `2to3` exactly is but from this output I conclude, that multiple packages try to install this binary. As I cannot find any recent changes in the macOS build instruction, I assume that something changed within the brew repositories.

https://github.com/ElektraInitiative/libelektra/actions/runs/3753156602/jobs/6376133446 is a job where this happens.

**Comment by markus2330** [comment]
Thank you for reporting this problem! Can you please link to a broken build run?

We don't need 2to3 but this probably doesn't help to fix the problem.

Is the problem maybe that two python versions are installed in parallel? Maybe we can prevent the second Python version from being installed?

**Comment by kodebach** [comment]
Sounds to me like we install Python 3 via `brew` (directly or indirectly) and the base image was updated to include Python 3 (or at least `2to3`).

Have you tried just removing Python 3 from the `brew install` part? Maybe that's all we need to do

**Comment by Eiskasten** [comment]
> Thank you for reporting this problem! Can you please link to a broken build run?

I have updated the issue and provided a link to a failing job.

> Is the problem maybe that two python versions are installed in parallel? Maybe we can prevent the second Python version from being installed?

This may be the case. Python gets explicitly installed in the version 3.9. Isn't it the case that macOS already ships with a version of python? Does not lead this to any (and maybe this) conflicts?

**Comment by Eiskasten** [comment]
> Have you tried just removing Python 3 from the `brew install` part? Maybe that's all we need to do

I will try that.

**Comment by Eiskasten** [comment]
> > Have you tried just removing Python 3 from the `brew install` part? Maybe that's all we need to do
> 
> I will try that.

That did not help at all. As far as I can tell, python 3.10. stays installed:

```
==> Outdated Formulae
aliyun-cli
aws-sam-cli
colima
composer
curl
gh
imagemagick
libksba
libmpc
libraw
mongodb-community@5.0
python@3.10
xz
yq
```

Brew suggests to run `brew update` but this does not seem to help in this case. May it be that macOS does not rollback the system after running the jobs?

**Comment by mpranj** [comment]
Thank you for reporting, should be fixed now.

I would think this was introduced due to some macOS image changes upstream (having multiple conflicting python installations).

**Comment by markus2330** [comment]
@mpranj thank you so much! :heart:
