### ISSUE TITLE
cirrus: macOS shutdown

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4793]
https://github.com/ElektraInitiative/libelektra/pull/4791/checks?check_run_id=10272562754 says:
"warning [We are sunsetting support for Intel-based macOS instances! Please migrate before January 1st 2023.](https://cirrus-ci.org/guide/macOS/)"

Does this affect us?

**Comment by kodebach** [comment]
AFAICT we need to switch our config from using `osx_instance`

https://github.com/ElektraInitiative/libelektra/blob/cfaee54612856aa41ea1712824aa1ad4347586b9/.cirrus.yml#L95

to using `macos_instance` (https://cirrus-ci.org/guide/macOS/)

**Comment by mpranj** [comment]
I will take a look at this an the other macOS problems.

**Comment by mpranj** [comment]
Thank you for reporting, it's fixed now.
