### ISSUE TITLE
Wrong format used for user namespace specification

### ISSUE THREAD

**Issue by tmakar** [ElektraInitiative/libelektra#4799]
## Steps to Reproduce the Problem

For the key name I have used the following convention:
`/<type>/<org>/<name>/<version>/<profile>`
type: sw
org: organization
name: gateway
version: 0
profile: development

1. `sudo kdb mount "gateway.ni" "spec:/sw/organization/gateway/#0/development" ni`
2. `sudo kdb meta-set "spec:/sw/organization/gateway/#0/development" mountpoint "gateway.ni"`
3. `sudo kdb spec-mount "sw/organization/gateway/#0/development" ni`

After those steps I have added a key to the specification `/sw/organization/gateway/#0/development/security/sso`. After that I have added the key with value `false` for the `user` namespace.

Looking into the file `~/.config/gateway.ni` the wrong format was used.

Data was displayed with the `dump` format.
```dump
------
kdbOpen 2
$key string 12 5
security/sso
false
$meta 7 4
default
true
$end
------
```

## Expected Result

I expected the specification to be in `ni` format.

## Actual Result

The `dump` format was used instead of `ni` format.

## System Information

- Elektra: master
- Operating System: macOS

**Comment by tmakar** [comment]
@markus2330 As discussed, I have created the issue and assigned @flo91.

**Comment by markus2330** [comment]
Thank you!

@flo91 the problem is that the additional parameter of `spec-mount` seems to be ignored. Should be fixed via reimplementation anyway.
