### ISSUE TITLE
invalid signature in debs.libelektra.org

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4813]
```
https://debs.libelektra.org/bullseye bullseye-unstable InRelease [FEHLER]
 Die folgenden Signaturen waren ungültig: EXPKEYSIG 11471BB6E778A9CD Robert Sowula <robert@sowula.at>
```

**Comment by lukashartl** [comment]
Yep, our GPG Keys have expired. (2023-01-03).

We could either:

1. change the expiration date
2. issue a new keypair and resign (release) everything.

In both cases we have to upload the (new) public key to the keyserver.

How did "we" handle these in the past? Couldn't find anything in the infrastructure documentation.

**Comment by markus2330** [comment]
@lukashartl any progress here? Imho this is a release blocker.

**Comment by lukashartl** [comment]
This is still WIP in the "other repo".

I guess you are asking because @robaerd is not going to update his keys and we have to do option 2. correct?

**Comment by markus2330** [comment]
I was asking because I was planning the release. I didn't hear anything from @robaerd about this specific issue. But as said above already, I think we should have our own key with revoke certificate in the longer term anyway. So if you see an easy way to issue a new keypair  for our infrastructure, please go ahead.

**Comment by mpranj** [comment]
I updated the expiration date of the key as a temporary fix.

@markus2330 can you report back whether the apt repo works again?

**Comment by markus2330** [comment]
Thank you! After running `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F26BBE02F3C315A19BF1F791A9A25CC1CC83E839`, `apt update` worked again without this error.
