### ISSUE TITLE
add website manifest, disable auto-PRs

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4821]
- [x] disable [dependabot](https://github.com/ElektraInitiative/libelektra/issues?q=is%3Apr+is%3Aopen+author%3Aapp%2Fdependabot)
- [x] add website manifest to check for every release
- [x] close all [dependabot](https://github.com/ElektraInitiative/libelektra/issues?q=is%3Apr+is%3Aopen+author%3Aapp%2Fdependabot) PRs

> the todo for the release gets a bit longer. But maybe we can now disable these auto-PRs done by GitHub?

I suppose that's fine, but it would probably make sense to add the website manifest to the check as well.

_Originally posted by @mpranj in https://github.com/ElektraInitiative/libelektra/issues/4748#issuecomment-1346396338_

**Comment by markus2330** [comment]
@mpranj can you do this when the next release is done?

Also all the [dependabot](https://github.com/ElektraInitiative/libelektra/issues?q=is%3Apr+is%3Aopen+author%3Aapp%2Fdependabot) PRs should be closed, I added the 3 TODOs in the list above.

**Comment by mpranj** [comment]
Can we target a release in 2-3 weeks? 

Let's give us enough time for the release pipeline, though.
There have been so many changes, so hiccups are likely.

**Comment by mpranj** [comment]
Should be done.
