### ISSUE TITLE
new-backend migration

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4822]
@kodebach wrote in https://github.com/ElektraInitiative/libelektra/issues/4485#issuecomment-1382143144:
> However, there is one thing that might still prevent a release: AFAIK we don't have a migration path from the old system:/elektra/mountpoints layout to the new one yet.

Yes, a script doing this definitely would be a nice-to-have. I personally migrated everything already: simply list mountpoints and remount them afterwards. We also could describe that in the release notes.

**Comment by kodebach** [comment]
I'll see, if I can write a simple Python script to translate the old format to the new format.

**Comment by kodebach** [comment]
See #4824
