### ISSUE TITLE
bash code completion doesn't work when installed from sources on Mac OS X

### ISSUE THREAD

**Issue by tryge** [ElektraInitiative/libelektra#483]
1) the completion script is installed without executable permission
2) the completion script is installed to "/etc/bash_completion.d/" which has no meaning on OS X - and requires root privileges which is actually not necessary.

There's no correct solution for OS X, but one option is to install into "~/.bash_completion.d/" and provide instructions how to enable bash completion at the end of the install.

**Comment by markus2330** [comment]
The bash completion is of rather poor quality, so you should not waste time trying to find OS-specific install-procedures, unless you are also willing to test and fix the bash completion itself.

**Comment by tryge** [comment]
I don't think I will have time for this. 

Another option is to disable INSTALL_SYSTEM_FILES on OS X by default.

**Comment by markus2330** [comment]
Maybe some people have compiled their own bash on Mac OS X, so unless the installation does not completely fail, I would rather prefer to keep CMake settings as same as possible for every supported platform.

**Comment by tryge** [comment]
It doesn't completely fail. It just installs something into a system directory that doesn't do anything.

This might change though, e.g. with El Capitan even root users cannot write into `/usr` anymore (but `/usr/local` is allowed).

**Comment by markus2330** [comment]
Because of the current quality of the bash auto completion I will close the issue for now.
