### ISSUE TITLE
0.9.12 Release

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4835]
Can we target a release in 2-3 weeks? 

Let's give us enough time for the release pipeline, though.
There have been so many changes, so hiccups are likely.

_Originally posted by @mpranj in https://github.com/ElektraInitiative/libelektra/issues/4821#issuecomment-1397351416_

**Comment by markus2330** [comment]
:+1: Yes, is fine. There are a few problems which should be solved before anyway, e.g. #4813. They are all marked with the 0.9.12 milestone.

I originally thought that #4628 doesn't need to be part of the release but it is actually needed to be fixed before the next term starts. If we have 0.9.12 in a few weeks we probably won't have another release within February, will we?

**Comment by mpranj** [comment]
> If we have 0.9.12 in a few weeks we probably won't have another release within February, will we?

I actually prefer a quicker release cycle.
It's worse if an error pops up and we need to debug something that was done months ago.

I do however think, that we should fix signing (#4813) before the release.

**Comment by markus2330** [comment]
I think the major problems are fixed.

**Comment by mpranj** [comment]
Release notes and some formatters/dependency bumps are merged.

Once master is green I will move forward to increment the version number and start the release.
