### ISSUE TITLE
Decisions: mismatched directory structure

### ISSUE THREAD

**Issue by atmaxinger** [ElektraInitiative/libelektra#4839]
As of the last update to the decision process, we have the following steps:

1. Draft
2. Problem Clear
3. Solutions Clear
4. In Review
5. Decided
6. Partially Implemented
7. Implemented
8. Postponed
9. Rejected

However, looking at the directory structure inside of  `doc/decisions`, we have the following:

- 0_drafts
- 0a_delayed
- 0b_rejected
- 1_in_discussion
- 2_in_progress
- 3_decided
- 4_partially_implemented
- 5_implemented

 As a decision author, this is quite confusing. We should restructure the directories so that they are matched up with the agreed upon steps.

**Comment by atmaxinger** [comment]
I'd be willing to do this, but I need some input how the steps now map


| Step | Current Directory Name | New Directory Name |
|------|--------------| --- | 
| Draft | 0_drafts | 0_drafts |
| Problem Clear | ??? | |
| Solutions Clear | ??? | |
| In Review | ??? | |
| Decided | 3_decided | |
| Partially Implemented | 4_partially_implemented | |
| Implemented | 5_implemented | |
| Postponed | 0a_delayed | |
| Rejected | 0b_rejected |  |
| ??? |  1_in_discussion | |
| ??? |  2_in_progress | |

**Comment by kodebach** [comment]
I'd say `1_in_discussion -> 1_problem_clear` and `2_in_progress -> 2_solutions_clear`, and `3_in_review` is empty for now. At least that is what I would've done. If @atmaxinger is quicker, I have no problem with that.

**Comment by atmaxinger** [comment]
Great, working on it ASAP
