### ISSUE TITLE
rename: newly created key not renamed

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#485]
@tom-wa When I mount using `rename tolower=0`, e.g. `kdb mount .../machinekit.ini system/machinekit/cnc ini array= type rename tolower=0 ` then new keys are written out lowercase and are not converted to uppercase.

**Comment by tom-wa** [comment]
thats the expected behaviour using `tolower=0` (all keys below the parent key are converted to lowercase)

**Comment by markus2330** [comment]
It also does not work with `toupper`. New mixed key always stay the same. I thought `tolower` is needed when you want lowercase Elektra names and uppercase persistent configuration? (Documentation should made that more clear, anyway.)

Another bug is that you cannot create new keys when the configuration file does not exist (empty keyset?).

The only thing that works nicely is that on the user side (with `kdb`, not in the configuration file) you see everything upper/lower as requested.

This should be reflected in the docu.

**Comment by tom-wa** [comment]
Oh, now i get what you meant, sorry. 
the changes only apply to the keyset, the keys are written back with their original name (like the original rename plugin has did). 
Do you want a different behaviour ?

**Comment by markus2330** [comment]
No, lets rather concentrate on real bugs. Lets only update the docu.

Where a behavioural change might be useful is to have ranges, e.g. `tolower=1..3` or negative numbers if counted from right. The counting from left and right in its current form is neither intuitive and is nor sufficient in many scenarios. But that is also something for later. (Let us put this to a limitations section in the plugin's docu).

**Comment by markus2330** [comment]
To clarify: I think we also need a two-way renaming for machinekit. So every key the users get should be lowercase, everything passed to the storage uppercase (and vice-verca). It is a different feature, because it loses all case-preserving for the storage. Maybe we can cleverly have two different features that can be combined in every way: One feature that is about how the user sees the keys, the other feature how the storage will get the key? Then the user can combine (or even leave out) the features as desired.

**Comment by markus2330** [comment]
As discussed we need to handle both sides: get-side which produces Elektra (KeySet) and the set-side which writes to the configuration file.

Thus we need two different "tolower" and "toupper" to configure each possibility.

I would suggest:
```
get/case = lower|upper|title|unchanged
set/case = lower|upper|title|unchanged
```

Where unchanged is the default. |title| does not need to be implemented now, it is only for the sake of an argument why we should use an `enum` and not a flag.

@strahlex  is this ok for you or do you want a convenience/backward compatibility options `tolower` and `toupper` which set `lower`, `upper` for both directions?

**Comment by tom-wa** [comment]
@markus2330 
an option to write the new/transformed/whatever keyname from the keyset (the one created by rename applying cut/replace/toupper/tolower) back would be nice too.

so `set/case = lower | upper | newname | unchanged` ?

**Comment by markus2330** [comment]
Yes, there are plenty of other ways how to rename. But I am not sure what you are proposing here. Please elaborate or give an example what this new option should do. (But in a new issue please.) I think the lower|upper|unchanged are the most common ones.

**Comment by markus2330** [comment]
Works now flowless as expected:
```
$ kdb mount caseconversion.ini /rename ini rename get/case=tolower,set/case=toupper
$ kdb set user/rename/section/key valu
$ cat ~/.config/caseconversion.ini
[SECTION]
KEY = value
```
