### ISSUE TITLE
Elektra installation error

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4856]
In the latest version (0.9.11-2.9881 over 0.9.11-2.9881), following error appeared during installation:

```
dpkg: Fehler beim Bearbeiten des Archivs /tmp/apt-dpkg-install-vkkCdu/57-libelektra5_0.9.11-2.9891_amd64.deb (--unpack):
 Versuch, »/usr/lib/elektra5/libelektra-backend.so« zu überschreiben, welches auch in Paket elektra-misc 0.9.11-2.9881 ist

 /tmp/apt-dpkg-install-vkkCdu/57-libelektra5_0.9.11-2.9891_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Distribution: Debian 11.6

**Comment by mpranj** [comment]
Interesting, I had basically the "reverse" issue in  #4849, that `libelektra-backend.so` was missing.

Shouldn't the `backend` plugin be included in the base package?

**Comment by mpranj** [comment]
I don't know how to provide an automated upgrade path here. (The new libelektra5 package is conflicting with the OLD elektra-misc package, according to the output)

Would a fresh install work (i.e. uninstall elektra-misc, upgrade, reinstall elektra-misc as a workaround)?

**Comment by kodebach** [comment]
Yes, `libelektra-backend.so` should definitely be in the base package. I think this can be solved by correctly setting the dependencies and conflicts for our packages (at least for deb packages). [This page](https://wiki.debian.org/PackageTransition) lists some scenarios. I think we have case #10, with A being `elektra-misc` and B being `libelektra5`.

For the RPMs there is probably a similar solution, but I haven't found an easy explanation like for Debian.

**Comment by mpranj** [comment]
Actually I just noticed this should only occur on the unstable repos. If you upgrade from the last stable release you should not run into this problem, since the backend plugin did not exist then.

**Comment by kodebach** [comment]
Can this be closed?

**Comment by markus2330** [comment]
Later updates worked for me.

Btw. Deleting/Moving around files between packages should be documented in release notes, so that maintainers know about it.
