### ISSUE TITLE
crypto_openssl compilation fails for Mac OS X

### ISSUE THREAD

**Issue by tryge** [ElektraInitiative/libelektra#487]
Mac OS X El Capitan (10.11) does not ship with openssl headers (deprecated since 10.7). Therefore the compilation fails. There should be configuration options to specify additional include and library directories without having to edit build files.

Full error message:
```
[ 18%] Building C object src/plugins/crypto/CMakeFiles/elektra-crypto_openssl-objects.dir/openssl_operations.c.o
In file included from /Users/michael/Projects/bachelor/libelektra/src/plugins/crypto/openssl_operations.c:10:
/Users/michael/Projects/bachelor/libelektra/src/plugins/crypto/crypto.h:38:10: fatal error: 'openssl/evp.h' file not found
#include <openssl/evp.h>
         ^
1 error generated.
make[2]: *** [src/plugins/crypto/CMakeFiles/elektra-crypto_openssl-objects.dir/openssl_operations.c.o] Error 1
make[1]: *** [src/plugins/crypto/CMakeFiles/elektra-crypto_openssl-objects.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by markus2330** [comment]
Thanks for reporting! Plugins should check if all build-dependencies are met and disable themselves otherwise. Can you provide the error messages please?

@petermax2 Can you take a look at it?

**Comment by petermax2** [comment]
On my machine (OS X 10.11.3 (15D21)) CMake (version 3.4.1) tells me that it can not find the OpenSSL headers (as you stated earlier). It removes the crypto plugin and does not even try to build it. See the output below:

	Clang detected
	C flags are  -std=gnu99  -Wno-deprecated-declarations  -Wno-long-long -pedantic -Wno-variadic-macros -Wall -Wextra -Wno-overlength-strings -Wsign-compare -Wfloat-equal -Wformat-security -Wshadow -Wcomments -Wtrigraphs -Wundef -Wuninitialized -Winit-self -Wsign-compare -Wfloat-equal -Wformat-security
	CXX flags are  -std=c++11  -Wno-deprecated-declarations  -Wno-missing-field-initializers -Wold-style-cast -Woverloaded-virtual  -Wsign-promo  -Wno-long-long -pedantic -Wno-variadic-macros -Wall -Wextra -Wno-overlength-strings -Wsign-compare -Wfloat-equal -Wformat-security -Wshadow -Wcomments -Wtrigraphs -Wundef -Wuninitialized -Winit-self
	Detected unix-x86_64. Use make package to build packages (PACKAGEMAKER;OSXX11).
	Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
	CMake Warning at doc/CMakeLists.txt:102 (message):
	  Doxygen not found, Reference Manual can't be created even though requested
	  with BUILD_DOCUMENTATION.


	CMake Warning at doc/help/CMakeLists.txt:19 (message):
	  did not find ronn, cannot build man pages even though requested with
	  BUILD_DOCUMENTATION.


	Include Plugin dump
	Include Plugin resolver
	Include Plugin sync
	Include Plugin error
	Include Plugin crypto
	Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
	Checking for one of the modules 'openssl'
	Exclude Plugin crypto_openssl because OpenSSL development files not found
	Exclude Plugin crypto_gcrypt because libgcrypt development files not found
	Include Plugin's build variant crypto_openssl
	Include Plugin's build variant crypto_gcrypt
	Include Binding cpp
	Include Tool kdb
	Configuring done

**Comment by petermax2** [comment]
31f91f8987dbc1f84fe69c2af25c8e7fe6751d1f compiles without any errors.

**Comment by petermax2** [comment]
@tryge how did you generate the build files?

**Comment by markus2330** [comment]
@petermax2 Did you try on Mac OS X El Capitan (10.11)?
@tryge It seems like pkg-config on your system tells that that openssl is present?

**Comment by petermax2** [comment]
> On my machine (OS X 10.11.3 (15D21))

@markus2330 yes ;) I will try to install pkg-config using MacPorts (which should btw. also provide the OpenSSL headers)

**Comment by petermax2** [comment]
I can reproduce it somehow (not with OpenSSL but with Gcrypt). I installed the `pkgconfig` and `libgcrypt` ports (see [https://www.macports.org](https://www.macports.org)). Now pkgconfig finds the library and development files but CMake does not set the include path right. I get something like this:

	/Users/pnirschl/Projekte/libelektra/src/plugins/crypto/crypto.h:30:10: fatal error:
      'gcrypt.h' file not found
	#include <gcrypt.h>

**Comment by markus2330** [comment]
@petermax2 The most robust solution is `try_compile` as it is done in `augeas` plugin.

**Comment by petermax2** [comment]
@markus2330 thx! I will look into that.

**Comment by tryge** [comment]
I'm in Berlin for 2 days and won't be able to respond until Saturday. However, I'd actually like to compile the plugin with my custom openssl, for that I'd like to be able to configure the location when invoking ccmake (or cmake for that matter).

**Comment by petermax2** [comment]
I managed to compile `crypto_gcrypt` using the MacPorts mentioned before.

You can set the CMake variables yourself, like:

    LIBGCRYPT_FOUND : boolean : true
    LIBGCRYPT_INCLUDE_DIR : path : /opt/local/include/
    LIBGCRYPT_LIBRARIES : path: /opt/local/lib

either by using the command line (`-DLIBGCRYPT_FOUND`) or the GUI.

For the `crypto_openssl` variant you should set the following variables

- OPENSSL_FOUND
- OPENSSL_INCLUDE_DIR
- OPENSSL_LIBRARIES

I will try to compile the plugin against a self-compiled version of OpenSSL later on today.

**Comment by petermax2** [comment]
With 5f44f7e0fcf4ca4ba10d288bd8fe354c94b56986 I introduced the following CMake variables

- OPENSSL_MANUAL_CONFIG
- LIBGCRYPT_MANUAL_CONFIG

I downloaded and compiled OpenSSL version 1.0.2f in my Downloads directory.

Now I set the CMake variables for OpenSSL as described in my last post.

	OPENSSL_MANUAL_CONFIG = true
	OPENSSL_INCLUDES = /Users/pnirschl/Downloads/openssl-1.0.2f/include
	OPENSSL_LIBRARIES = /Users/pnirschl/Downloads/openssl-1.0.2f/libcrypto.a;/Users/pnirschl/Downloads/openssl-1.0.2f/libssl.a

And it finally compiles. Even the unit tests run through. :tada:

**Comment by markus2330** [comment]
Great that it works now! (especially the test cases!)

But the manual config seems like a huge workaround for systems where pkgconfig is broken? Isn't it better to fix pkgconfig to not report wrong installations?

Why was it necessary on your system?

**Comment by petermax2** [comment]
The pc-file has been shipped with the MacPorts installation (so I didn't mess with it). pkgconfig usually finds OpenSSL without any further help. Within the CMake file I use

    pkg_search_module (OPENSSL openssl)

On OS X it reports that OpenSSL is available. Well, the libraries actually are available under `/usr/lib` but OS X does not ship with the header files, as @tryge mentioned earlier.

I am not going to provide a custom pkgconfig file just for OS X. A manual configuration would be mandatory anyway, because there are no headers to be found.

**Comment by markus2330** [comment]
If someone specifies options such as `OPENSSL_INCLUDES` this should of course always win. But why give an option to override if openssl is available at all? Removing the plugin is the correct way if someone has a broken openssl installation, I think we should not try to consider every possibility in which systems might be broken, thats CMake's/Pkgconfig's job.

**Comment by markus2330** [comment]
Or stated differently: Isn't *MANUAL_CONFIG the same as *_FOUND?

**Comment by petermax2** [comment]
One could argue that it "is the same thing" and we could certainly have it that way but I think it is an ambiguous or misleading name.

**Comment by markus2330** [comment]
The question is if we do a workaround because we misunderstand pkgconfig and cmake. Manual hints for the auto-detection should be done in the cmake/pkgconfig layer, not by the users of the library.

E.g. on my system *without* this PR: When I *deinstall* openssl, I can still force pkgconfig to detect openssl by using: `cmake -DPLUGINS=ALL -DOPENSSL_FOUND=TRUE ~e `.

So why introduce a `_MANUAL_CONFIG` if you already can override what pkgconfig detects?

**Comment by markus2330** [comment]
(Btw. the try_compile is useful, because it let you check if openssl will work already at cmake stage)

**Comment by petermax2** [comment]
OK, I see what you mean now. I would prefer to not have a *MANUAL_CONFIG then and just check whether or not the user provided *_INCLUDES and *_LIBRARIES. If so pkgconfig won't be triggered at all.

btw *FOUND and *MANUAL_CONFIG are not quite the same thing, because with my PR pkgconfig would not be triggered if you set *MANUAL_CONFIG (so setting the *FOUND variable would not make any difference). Having both *FOUND and *MANUAL_CONFIG seems confusing to me, now that I wrote about it. :smile:

**Comment by petermax2** [comment]
@markus2330 please have a look at 0e1fbd84aff56541a8045132ab056981ede38764. I think this is better.

If the user can supply the path to both include- and library-files then CMake won't trigger pkgconfig. No need for *MANUAL_CONFIG and *FOUND variables to be set.

**Comment by markus2330** [comment]
I am still not convinced that you need any build-logic within CMake.

On my system (again *without* the PR) you can simply specify:
```
cmake -DPLUGINS=ALL -DOPENSSL_FOUND=TRUE -DOPENSSL_INCLUDE_DIR=/some/strange/path ~e 
```
and cmake does the right thing (it adds `-I/some/strange/path`):
```
[ 28%] Building C object src/plugins/crypto/CMakeFiles/elektra-crypto_openssl-objects.dir/openssl_operations.c.o
cd /home/markus/Projekte/Elektra/build-openssl/src/plugins/crypto && /usr/bin/cc  -DELEKTRA_CRYPTO_API_OPENSSL -DELEKTRA_PLUGIN_NAME=\"crypto_openssl\" -DELEKTRA_STATIC -DELEKTRA_VARIANT=openssl -DHAVE_KDBCONFIG_H -DPLUGIN_SHORT_NAME=crypto_openssl -DREADME=readme_crypto_openssl.c -Wall  -std=gnu99  -Wno-deprecated-declarations  -Wno-long-long -pedantic -Wno-variadic-macros -Wall -Wextra -Wno-overlength-strings -Wsign-compare -Wfloat-equal -Wformat-security -Wshadow -Wcomments -Wtrigraphs -Wundef -Wuninitialized -Winit-self -Wmaybe-uninitialized -Wsign-compare -Wfloat-equal -Wformat-security -O2 -g -DNDEBUG -I/home/markus/Projekte/Elektra/build-openssl/src/include -I/home/markus/Projekte/Elektra/current/src/include -I/home/markus/Projekte/Elektra/current/tests/cframework -I/some/strange/path -I/home/markus/Projekte/Elektra/build-openssl/src/plugins/crypto    -fPIC -o CMakeFiles/elektra-crypto_openssl-objects.dir/openssl_operations.c.o   -c /home/markus/Projekte/Elektra/current/src/plugins/crypto/openssl_operations.c
In file included from /home/markus/Projekte/Elektra/current/src/plugins/crypto/openssl_operations.c:10:0:
```

Is the behaviour on Mac OS X different? Which problem do you try to solve in 0e1fbd8?

I also doubt that a logic to automatically set FOUND to true when a INCLUDE_DIR is set is a good idea: a user might got the path wrong.

**Comment by markus2330** [comment]
(Sorry for the many rejections, I hope that we at least learn more about CMake in the process)

**Comment by petermax2** [comment]
> Is the behaviour on Mac OS X different?

I think so. Hm, this is interesting. With 0e1fbd84aff56541a8045132ab056981ede38764 I try to achieve the behavior for OS X that already works fine on Linux.

Without 0e1fbd84aff56541a8045132ab056981ede38764 on OS X CMake (or possibly pkgconfig) messes up the include directories.

**Comment by markus2330** [comment]
Ok, can you rename `OPENSSL_MANUAL_CONFIG` to a name that suggests it is only needed for mac os x (e.g. `OPENSSL_MACOSX_HACK`) and comment that a bit? Try to be as little invasive as possible to not break other systems. Thank you!

**Comment by petermax2** [comment]
Alright, I will rename the variables.

**Comment by petermax2** [comment]
I renamed the variables in aca68c337f875430703cc3512fb155b51f602317 to

- OPENSSL_MANUAL_OSX_HACK
- LIBGCRYPT_MANUAL_OSX_HACK

**Comment by petermax2** [comment]
@tryge @mpranj can you confirm that the following plugins compile with "a little love"?

### crypto
should work out-of-the-box.

### crypto_gcrypt 
try to install the `libgcrypt` port and the `pkgconfig` port from [MacPorts](https://trac.macports.org/). Then manually set the CMake variable `LIBGCRYPT_INCLUDE_DIR` to `/opt/local/include/` and `LIBGCRYPT_LIBRARIES` to `/opt/local/lib/libgcrypt.dylib`.

### crypto_openssl
download and compile the OpenSSL source code from the [project homepage](https://www.openssl.org/source/). Then set `OPENSSL_INCLUDE_DIR` and `OPENSSL_LIBRARIES` correspondingly.

**Comment by markus2330** [comment]
@petermax2 thanks you for that writeup! Can you also include this in the README.md of the plugin?

**Comment by sanssecours** [comment]
I tested the changes under OS X. The variant `crypto` seems to work. At least 

```bash
cmake .. -DPLUGINS='dump;resolver;sync;error;crypto'
```

followed by `make -j 8` works. I then installed `libgcrypt` via [Homebrew](http://brew.sh). After that I tried 

```fish
cmake .. -DPLUGINS='dump;resolver;sync;error;crypto;crypto_gcrypt' -DLIBGCRYPT_INCLUDE_DIR=/usr/local/include -DLIBGCRYPT_LIBRARIES=/usr/local/lib/libgcrypt.dylib; and make -j 8
```

which builds too. I then installed `openssl` via Homebrew. Unfortunately the command

```
cmake .. -DPLUGINS='dump;resolver;sync;error;crypto;crypto_openssl' -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib/libssl.dylib; and make
```

fails with the following error message:

```
[ 19%] Linking CXX shared library ../../../lib/libelektra-full.dylib
Undefined symbols for architecture x86_64:
  "_BIO_ctrl", referenced from:
      _elektraCryptoOpenSSLEncrypt in openssl_operations.c.o
      _elektraCryptoOpenSSLDecrypt in openssl_operations.c.o
  "_BIO_free_all", referenced from:
      _elektraCryptoOpenSSLEncrypt in openssl_operations.c.o
      _elektraCryptoOpenSSLDecrypt in openssl_operations.c.o
  "_BIO_new", referenced from:
      _elektraCryptoOpenSSLEncrypt in openssl_operations.c.o
      _elektraCryptoOpenSSLDecrypt in openssl_operations.c.o
  "_BIO_s_mem", referenced from:
      _elektraCryptoOpenSSLEncrypt in openssl_operations.c.o
      _elektraCryptoOpenSSLDecrypt in openssl_operations.c.o
  "_BIO_write", referenced from:
      _elektraCryptoOpenSSLEncrypt in openssl_operations.c.o
      _elektraCryptoOpenSSLDecrypt in openssl_operations.c.o
  "_CRYPTO_THREADID_set_callback", referenced from:
      _elektraCryptoOpenSSLInit in openssl_operations.c.o
  "_CRYPTO_THREADID_set_numeric", referenced from:
      _internalThreadId in openssl_operations.c.o
  "_CRYPTO_get_locking_callback", referenced from:
      _elektraCryptoOpenSSLInit in openssl_operations.c.o
  "_CRYPTO_num_locks", referenced from:
      _elektraCryptoOpenSSLInit in openssl_operations.c.o
  "_CRYPTO_set_locking_callback", referenced from:
      _elektraCryptoOpenSSLInit in openssl_operations.c.o
      _elektraCryptoOpenSSLTeardown in openssl_operations.c.o
  "_ERR_get_error", referenced from:
      _elektraCryptoOpenSSLInit in openssl_operations.c.o
      _elektraCryptoOpenSSLHandleCreate in openssl_operations.c.o
      _elektraCryptoOpenSSLEncrypt in openssl_operations.c.o
      _elektraCryptoOpenSSLDecrypt in openssl_operations.c.o
  "_ERR_peek_error", referenced from:
      _elektraCryptoOpenSSLInit in openssl_operations.c.o
      _elektraCryptoOpenSSLHandleCreate in openssl_operations.c.o
      _elektraCryptoOpenSSLEncrypt in openssl_operations.c.o
      _elektraCryptoOpenSSLDecrypt in openssl_operations.c.o
  "_EVP_CIPHER_CTX_cleanup", referenced from:
      _elektraCryptoOpenSSLHandleDestroy in openssl_operations.c.o
  "_EVP_DecryptFinal", referenced from:
      _elektraCryptoOpenSSLDecrypt in openssl_operations.c.o
  "_EVP_DecryptInit", referenced from:
      _elektraCryptoOpenSSLHandleCreate in openssl_operations.c.o
  "_EVP_DecryptUpdate", referenced from:
      _elektraCryptoOpenSSLDecrypt in openssl_operations.c.o
  "_EVP_EncryptFinal", referenced from:
      _elektraCryptoOpenSSLEncrypt in openssl_operations.c.o
  "_EVP_EncryptInit", referenced from:
      _elektraCryptoOpenSSLHandleCreate in openssl_operations.c.o
  "_EVP_EncryptUpdate", referenced from:
      _elektraCryptoOpenSSLEncrypt in openssl_operations.c.o
  "_EVP_aes_256_cbc", referenced from:
      _elektraCryptoOpenSSLHandleCreate in openssl_operations.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libelektra-full.0.8.14.dylib] Error 1
make[1]: *** [src/libs/elektra/CMakeFiles/elektra-full.dir/all] Error 2
make: *** [all] Error 2
``` 

@petermax2: Is this the expected outcome? Why do we need to download and build OpenSSL manually, when `libgcrypt` works (more or less) out of the box?

BTW: `cmake .. -DPLUGINS='dump;resolver;sync;error;crypto;crypto_gcrypt'` seems to work too.

**Comment by petermax2** [comment]
@markus2330 ok, I'll update the README.md

@sanssecours thank you for trying it on your system! If you ask me I'd drop the OS X support completely ;) We put much effort into supporting this platform. However, @tryge wants to use the OpenSSL variant and I see no other way than setting up a custom-built OpenSSL library. The reason for having different crypto provider is simple: I need something to compare in my Bachelors Thesis.

**Comment by tryge** [comment]
Everything that follows was done on commit 614772d.

`cmake .. -DPLUGINS='dump;resolver;sync;error;crypto;crypto_openssl'`

results in:

```
Undefined symbols for architecture x86_64:
  "_libelektra_crypto_openssl_LTX_elektraPluginSymbol", referenced from:
      _kdb_exported_syms in exported_symbols.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libelektra-full.0.8.14.dylib] Error 1
make[1]: *** [src/libs/elektra/CMakeFiles/elektra-full.dir/all] Error 2
make: *** [all] Error 2
```

When I specify openssl include and lib dir (also installed via `brew`) using the same command as @sanssecours, I got the same error. (Yeah! consistency!) However, when looking at the executed linker command, the interesting part is that libssl is listed twice in the end of the command.
`...ts.dir/crypto.c.o /usr/local/opt/openssl/lib/libssl.dylib /usr/local/opt/openssl/lib/libssl.dylib`

Shouldn't harm, but probably this means something to anybody...

`file /usr/local/opt/openssl/lib/libssl.dylib` shows 
```
/usr/local/opt/openssl/lib/libssl.dylib: Mach-O 64-bit dynamically linked shared library x86_64
```

and `nm /usr/local/opt/openssl/lib/libssl.dylib` clearly shows that the symbols are included.


I also tried to set the `PKG_CONFIG_PATH` to `/usr/local/opt/openssl/lib/pkgconfig`. There was no observable difference for both commands above. (Do I need to do something in addition to setting the environment variable?)

@petermax2 What do you mean by dropping support for Mac OS X? Only for this plugin, or in general?

Also I just tried to get things running on my system, the first thing I do is trying to build everything. I'm not in special trying to get crypto with openssl running, but it is there, and if it is there, then it should build just fine. Otherwise the plugin needs to be disabled for Mac OS X, so if using `-DPLUGINS=ALL` there's no error.

I can confirm that `crypto_gcrypt` works fine with the brew installed version (I didn't even have to specify include and lib dir).

**Comment by petermax2** [comment]
@tryge thank you for confirming!

> @petermax2 What do you mean by dropping support for Mac OS X? Only for this plugin, or in general?

I mean we should drop non-Linux platform support for plugins with dependencies, that are hard to support. We already had this discussion in our Elektra meetings.

> EDIT: Regarding my comment to disable the plugin, there should be a difference between plugins that won't be supported on a platform and plugins that miss dependencies. 

Agreed. The `try_compile` statement *should* generate a warning if OpenSSL has not been set up properly. I will try to fix the linker error @tryge  and @sanssecours reported. As a workaround for now you can specify your custom-built version of OpenSSL as described in `README.md`.

**Comment by markus2330** [comment]
I think we should support every platform someone is willing to invest time in. Maybe we can reduce the Mac OS X effort by saying that only one way to install dependencies is supported. @tryge wanted to add Elektra to `brew`, so maybe we can agree that all dependencies should be installed by `brew`? Let us discuss this in the next meeting.

I am, however, not in favour of silently remove plugins for some platforms because some ways to install dependencies might not always work. If some plugins make no sense for some platform, the situation would be different, but I do not think this is the case here. For the upcoming release it was already reported that everything works and runs on Mac OS X.

**Comment by tryge** [comment]
After playing with the command a little bit, it is possible to link against `brew`'s openssl with the following command:
```
cmake .. -DPLUGINS="dump;resolver;sync;error;crypto;crypto_openssl" -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib/libcrypto.dylib
```

Regarding the link error for `cmake .. -DPLUGINS='dump;resolver;sync;error;crypto;crypto_openssl'`, is there some code generation involved?

**Comment by markus2330** [comment]
Code generation is involved for the `full` and `static` variants. The `exported_symbols.c file` that contains all symbols of all plugins is generated.
Maybe you only need to cleanly recompile? Otherwise you can also disable the `full` variant, its mainly used for unit tests.

**Comment by markus2330** [comment]
Is this issue now resolved or are there still regressions/problems?

**Comment by tryge** [comment]
To be sure I cloned the repo and used:
`cmake .. -DPLUGINS='dump;resolver;sync;error;crypto;crypto_openssl'`
to build it and this works fine. So you can close it.

**Comment by markus2330** [comment]
Thanks for the confirmation!
