### ISSUE TITLE
0.9.13 release

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#4875]
As discussed in #4859 we will do a minor 0.9.13 release to fix `spec`/`gopts` hook placement and add Ubuntu 22.04 LTS and 22.10 packages.

@atmaxinger @kodebach Is there anything else critical to be merged for this release? Otherwise I'd like to proceed and get the release out quickly.

**Comment by atmaxinger** [comment]
There's nothing from my side for this release.

**Comment by kodebach** [comment]
No, nothing critical I know of.

**Comment by mpranj** [comment]
The release is basically done but the pipeline failed publishing some packages ([see log](https://build.libelektra.org/blue/organizations/jenkins/libelektra-release/detail/libelektra-release/187/pipeline/)).

Not sure what's going on, I'll try to rebuild just a new package revision.
