### ISSUE TITLE
building filecheck and iconv plugins fail on Mac OS X

### ISSUE THREAD

**Issue by tryge** [ElektraInitiative/libelektra#488]
The headers and libraries are in standard locations `/usr/include/iconv.h` and `/usr/lib/libiconv.dylib` so I'm not sure why linking fails.

Full error message:
```
Linking CXX shared library ../../../lib/libelektra-full.dylib
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _kdbbUTF8Engine in iconv.c.o
      _checkFile in filecheck.c.o
     (maybe you meant: _libelektra_iconv_LTX_elektraPluginSymbol)
  "_iconv_close", referenced from:
      _kdbbUTF8Engine in iconv.c.o
      _checkFile in filecheck.c.o
  "_iconv_open", referenced from:
      _kdbbUTF8Engine in iconv.c.o
      _checkFile in filecheck.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libelektra-full.0.8.14.dylib] Error 1
make[1]: *** [src/libs/elektra/CMakeFiles/elektra-full.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by markus2330** [comment]
Thank you for reporting. Please provide all error messages.

**Comment by markus2330** [comment]
I think we have to add detection code for iconv on Mac OS X.

On many systems iconv is directly integrated in libc, thus no additional library needs to be linked.

**Comment by markus2330** [comment]
We could add a try_compile here, too.

Btw. you can easily exclude plugins by using "ALL;-iconv", but that is obviously not a fix. (iconv plugin can be quite useful if you have users still working with different locales)

**Comment by tryge** [comment]
I tried to do that, but ended up with many plugins there (I stopped when I had "ALL;-filecheck;-iconv;-crypto;-crypto_openssl;-crypto_gcrypt" - it still didn't compile) 

The thing is, I want to be able to build everything, so I'm actually not fond of automatically disabling anything if it is missing dependencies.

The minimal confuguration builds fine btw.

**Comment by markus2330** [comment]
Thanks, it would be great if everything builds under Mac OS X.
