### ISSUE TITLE
Docker is sunsetting Free Team organizations

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4880]
We got yesterday following e-mail from docker.com:
> Free Team organizations are a legacy subscription tier that no longer exists. This tier included many of the same features, rates, and functionality as a paid Docker Team subscription.

> After reviewing the list of accounts that are members of legacy Free Team organizations, we’ve identified yours as potentially being one of them.

> If you own a legacy Free Team organization, access to paid features — including private repositories — will be suspended on April 14, 2023 (11:59 pm UTC). Upgrade your subscription before April 14, 2023 to continue accessing your organization.

> If you don’t upgrade to a paid subscription, Docker will retain your organization data for 30 days, after which it will be subject to deletion. During that time, you will maintain access to any images in your public repositories, though rate limitations will apply. At any point during the 30-day period, you can restore access to your organization account if you upgrade to a paid subscription. Visit our [FAQ](https://em.docker.com/NzkwLVNTQi0zNzUAAAGKf9y2h7etX29g28Ueaz2T-NjJcRGzJLc7_KxZJPVtGy9JjgbgHrnj2aplQ1Ve1RYz1EXgLM_BWHMzJH8=) for more information.

Does it affect us?

**Comment by kodebach** [comment]
If we do have problems I'd suggest switching to GitHub's Container Registry, which is [free for public repos](https://docs.github.com/en/billing/managing-billing-for-github-packages/about-billing-for-github-packages), for public images and should be easy to integrate.

For private images we have our own repo AFAIK. We could of course use our own repo for public images too, but IMO using a trusted provider like GitHub gives a better impression.

**Comment by mpranj** [comment]
> We could of course use our own repo for public images too, but IMO using a trusted provider like GitHub gives a better impression.

We also don't really have too much bandwith to spare on the current private registry.

**Comment by markus2330** [comment]
Now they wrote:
> On March 14, 2023, we emailed you about your Free Team subscription, outlining our intention to sunset that plan. After listening to the concerns of the community, we’ve decided to reverse course, and are no longer sunsetting the Free Team plan.

> If you’re currently on the Free Team plan, you no longer have to migrate to another plan by April 14. All customers who upgraded to a paid subscription will automatically receive a full refund for the transaction in the next 30 days, allowing them to use their new paid subscription for free for the duration of the term they purchased.

> We apologize for the alarm our decision caused. For more details, please visit our FAQ. 

So we can close this issue.
