### ISSUE TITLE
kdb export missing plugin

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#4886]
`kdb export` should not segfault, if a plugin cannot be loaded. It is very much an expected failure, that a plugin is missing or broken and a nice error message should be displayed.

See also #4884.

> **Note**: This issue should be fixed in the new C implementation of `kdb`.

**Comment by atmaxinger** [comment]
Interestingly, I cannot reproduce this. For me it just prints out that the plugin cannot be found:

```
$ kdb export system:/elektra nonexisting
The command kdb export terminated unsuccessfully with the info:
No plugin that provides nonexisting could be found
Please report the issue at https://issues.libelektra.org/
```

**Comment by tmakar** [comment]
> Interestingly, I cannot reproduce this. For me it just prints out that the plugin cannot be found:
> 
> ```
> $ kdb export system:/elektra nonexisting
> The command kdb export terminated unsuccessfully with the info:
> No plugin that provides nonexisting could be found
> Please report the issue at https://issues.libelektra.org/
> ```

Have you maybe tried with the steps I put into this issue https://github.com/ElektraInitiative/libelektra/issues/4884? 🤔

**Comment by atmaxinger** [comment]
Yes, I also tried the command that is listed in the logs, same result

```
kdb export "user:/sw/elektra/web/#0/current/instances" yajl "/tmp/elektra-web.1679136074943.buffer.json"
```
```
The command kdb export terminated unsuccessfully with the info:
No plugin that provides yajl could be found, got errors: Was not able to load such a plugin!

Maybe you misspelled it, there is no such plugin or the loader has problems.
You might want to try to set LD_LIBRARY_PATH, use kdb-full or kdb-static.
Errors/Warnings during loading were:
 Sorry, 1 warning was issued ;(
 1: Module kdb issued the warning C01200:
        Installation: Dlopen failed. Could not load module libelektra-yajl.so. Reason: libelektra-yajl.so: cannot open shared object file: No such file or directory
        Mountpoint: /
        Configfile: 
        At: /home/maximilianirlinger/src/libelektra/src/libs/loader/dl.c:90
,
Please report the issue at https://issues.libelektra.org/
```

Whatever causes the issue, it's not something that I can reproduce on Fedora.
