### ISSUE TITLE
cmake fails with static build only

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#489]
Configuring cmake with `-DBUILD_SHARED=OFF -DBUILD_STATIC=ON` fails with following error:

> CMake Error at cmake/Modules/LibAddLib.cmake:28 (target_link_libraries):
  Cannot specify link libraries for target "elektra-ease" which is not built
  by this project.

**Comment by markus2330** [comment]
This issue also causes some dynamic elektra libraries unnecessarily to be linked against static variants.

Unfortunately, the default cmake message is not helpful at all. Does someone know how cmake can output the callstack on errors? (Something less verbose then --debug-output)

**Comment by markus2330** [comment]
@mpranj can you please confirm that it works now?

**Comment by mpranj** [comment]
Indeed it works (as of revision 315c6169c4d112b2070fc6c9d32c917818c3e19b)  with eg:
`cmake -DBUILD_DOCUMENTATION=OFF -DBUILD_FULL=OFF -DBUILD_PDF=OFF -DBUILD_SHARED=OFF -DBUILD_STATIC=ON ..`

all tests pass on OS X

**Comment by markus2330** [comment]
Thank you!
