### ISSUE TITLE
`/elektra` hierarchy

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4894]
`/elektra/record/session` was my first thought as well, but: that would mean we'd have to load the whole recording session every time something from `/elektra` is requested. Which is every `kdbOpen`. I want to avoid this for two reasons:

- memory consumption: If the session is paused we don't need the overhead of reading the existing session. Which is potentially massive.
- concurrency: I want to avoid that multiple processes potentially having the (outdated) session loaded.

_Originally posted by @atmaxinger in https://github.com/ElektraInitiative/libelektra/pull/4892#discussion_r1154524698_

**Comment by atmaxinger** [comment]
Upon further investigation, `kdbOpen` really only reads `elektra.cfg` so there's no problem with bootstrapping. However, that was only a simple example. If something tries to read `/elektra`, we'd still have to load the recording session into memory. Personally, I don't have a problem with that.  After all, it could also just read `/record`. However, I just think it's more likely that something is going to read `/elektra` than `/record`.

> We also should do proper major versioning of these Elektra core parts so that they could be upgraded later. 

Sound good, but will require some work. @flo91 will also have to adjust to the new key structure.
