### ISSUE TITLE
Plugin Status documentation

### ISSUE THREAD

**Issue by atmaxinger** [ElektraInitiative/libelektra#4921]
Is there any documentation/overview of the plugin `info/status` field? When one is creating a new plugin it automatically defaults  to 

```
- infos/status = recommended productive maintained reviewed conformant compatible coverage specific unittest shelltest tested nodep libc configurable final preview memleak experimental difficult unfinished old nodoc concept orphan obsolete discouraged -1000000
```

As a plugin author, it is very hard to determine which ones are appropriate for the plugin and which ones are not.

**Comment by flo91** [comment]
In `/doc/CONTRACT.ini` is a description of the infos/status field:

https://github.com/ElektraInitiative/libelektra/blob/6fe533566ec14d170f1cbfcad1e25921152efb2a/doc/CONTRACT.ini#L285-L330

The `CONTRACT.ini` file is already mentioned in the `README.md` of the template plugin:
https://github.com/ElektraInitiative/libelektra/blob/6fe533566ec14d170f1cbfcad1e25921152efb2a/src/plugins/template/README.md?plain=1#L36-L37

**Comment by markus2330** [comment]
@flo91 thx for helping out! :heart: 

In #666 there are some suggestions for improvements for infos/status. Better don't use the ones we want to remove there. (There is also a half-done PR for this #4758.)

Btw. in case of doubt it is better if we tag it negatively/experimental/..., it is very disadvantageous for Elektra or even FLOSS in general if someone expects it should work and it does not. 

In doc/tutorials/xfconf.md we also should add a disclaimer (for me some parts still did not work).
