### ISSUE TITLE
Use correct `pkgconf`

### ISSUE THREAD

**Issue by tmakar** [ElektraInitiative/libelektra#4924]
With this PR (https://github.com/ElektraInitiative/libelektra/pull/4895) we have introduced the go binding into our main repo. It seems that some of our distros use `pkg-config` but the newer version is `pkgconf`. `pkg-config` seems to not work when there are whitespaces in the `ldflags` or `cflags`. Therefore we changed the build directory name of jenkins to use no whitespaces.

As @kodebach wrote in [Go to Repo PR](https://github.com/ElektraInitiative/libelektra/pull/4895) it needs to be distinguished between distros and based on it choose correct `pkg config`. See _Originally posted by @kodebach in https://github.com/ElektraInitiative/libelektra/issues/4895#issuecomment-1546666800_

**Comment by markus2330** [comment]
@tmakar can you please create a list in the top post on which distributions we have which problems? Maybe removing some old versions of some distros already solves the problem.

**Comment by kodebach** [comment]
I originally thought OpenSUSE Leap doesn't ship a package for `pkgconf`. But that seems to be incorrect, there is a package, but I missed it.

However, we couldn't get Debian Stable working even with the `pkgconf` package in the PR, so this probably requires more debugging and error finding work.

AFAIK the main purpose of using `"build directory"` was finding error ins CMake and Shell scripts. For that purpose it might be enough to have a single build job that builds everything (all plugins, bindings, tools, etc. in shared, full and static) using `"build directory"` on a single distro where we know `pkg-config` works with spaces. The other jobs could just use a build dir without spaces.

**Comment by markus2330** [comment]
> AFAIK the main purpose of using "build directory" was finding error ins CMake and Shell scripts.

Yes, this is the main purpose (and probably the only purpose).

> The other jobs could just use a build dir without spaces.

Originally it was implemented like this. I have no objections going back to that.
