### ISSUE TITLE
release pipeline fails

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4928]
>> ```
>>         Start 191: testscr_check_shellcheck
>>
>> 226/264 Test #191: testscr_check_shellcheck 
>> ......................***Failed    0.06 sec
>>
>>
>> ELEKTRA SCRIPTS SHELLCHECK TEST
>>
>>
>> awk: cmd. line:1: fatal: cannot open file 
>> `benchmarks/changetracking.c' for reading: No such file or directory
>> ```
>>
>> https://build.libelektra.org/blue/organizations/jenkins/libelektra-release/detail/libelektra-release/193/pipeline

**Comment by atmaxinger** [comment]
Can you trigger the build again? The file is obviously there in the repository.
Also, there are multiple failed tasks. The other tasks fail because they can't find the go bindings.

```
go: go.libelektra.org@v0.0.0-20220529165759-8d7288960e91: invalid version: git ls-remote -q origin in /home/jenkins/go/pkg/mod/cache/vcs/9ed703782fbdafb96cff2d51c59917379db36dbde15ad723449805aba92f1c40: exit status 128:
	remote: Not Found
	fatal: repository 'https://github.com/ElektraInitiative/libelektra/go-elektra/' not found
go: downloading go.libelektra.org v0.0.0-20220529165759-8d7288960e91
[ 80%] Building C object src/plugins_tests/CMakeFiles/testmod_base64.dir/base64/testmod_base64.c.o
go: go.libelektra.org@v0.0.0-20220529165759-8d7288960e91: invalid version: git ls-remote -q origin in /home/jenkins/go/pkg/mod/cache/vcs/9ed703782fbdafb96cff2d51c59917379db36dbde15ad723449805aba92f1c40: exit status 128:
	remote: Not Found
	fatal: repository 'https://github.com/ElektraInitiative/libelektra/go-elektra/' not found
make[2]: *** [src/tools/elektrad/CMakeFiles/elektrad.dir/build.make:78: src/tools/elektrad/elektrad/elektrad] Error 1
make[1]: *** [CMakeFiles/Makefile2:13434: src/tools/elektrad/CMakeFiles/elektrad.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by tmakar** [comment]
Yes, as I assumed, there is no such version on Go packages anymore (latest from the archived repo is [latest-go-elektra-binding)(https://deps.dev/go/go.libelektra.org/v0.0.0-20230321081411-7a7dc1493aee)).

**Comment by tmakar** [comment]
I would suggest the following steps:

1. Change the url for metakey `go-import` to `goelektra.libelektra.org`
2. Merge https://github.com/ElektraInitiative/libelektra/pull/4929
3. Then I will create a PR which uses the correct version of go binding in `elektrad`

**Comment by tmakar** [comment]
Besides the steps above, we could clear the cache of go on our release build servers somehow  and then rerun the build again. If that’s not possible let’s do the above steps first.

**Comment by markus2330** [comment]
I started it https://build.libelektra.org/job/libelektra-release/194/ (you should also get access, ask Lukas if you didn't receive anything yet).

> Can the go cache be deleted somehow?

@tmakar Can you help out here?

**Comment by tmakar** [comment]
> I started it https://build.libelektra.org/job/libelektra-release/194/ (you should also get access, ask Lukas if you didn't receive anything yet).
> 
> > Can the go cache be deleted somehow?
> 
> @tmakar Can you help out here?

Maybe manually deleting `/home/jenkins/go/pkg/mod/cache/vcs`, assuming we have access to the servers / nodes.

**Comment by markus2330** [comment]
/home/jenkins/go doesn't seem to exist (checked on v2, a7 and i7). Do you know on which agent? Or can this cache be also somewhere else?

Maybe @lukashartl knows something about it?

**Comment by tmakar** [comment]
> /home/jenkins/go doesn't seem to exist (checked on v2, a7 and i7). Do you know on which agent? Or can this cache be also somewhere else?
> 
> Maybe @lukashartl knows something about it?

Hmm, well, that was my first guess we the cache folder. I‘m not very familiar with our agents etc. 😕

**Comment by lukashartl** [comment]
Since we are building everything inside containers, there shouldn't be a cache on the Jenkins agent node.
Or am I missing something here?

**Comment by tmakar** [comment]
Fedora fails on release pipeline because of this, maybe rerun helps here.

```ah
ZEROMQSEND TESTS
================

zeromq version is 4.3.4
test commit notification
test connect timeout
/home/jenkins/workspace/libelektra-release@3/placeholder/placeholder/placeholder/placeholder/libelektra/src/plugins/zeromqsend/testmod_zeromqsend.c:245: error in test_timeoutConnect: warning meta key was not set
/home/jenkins/workspace/libelektra-release@3/placeholder/placeholder/placeholder/placeholder/libelektra/src/plugins/zeromqsend/testmod_zeromqsend.c:246: error in test_timeoutConnect: right hand side is null pointer
test subscribe message timeout

testmod_zeromqsend Results: 25 Tests done — 2 errors.
```

**Comment by tmakar** [comment]
Seems that I missed to adapt the version somewhere 

```sh
DCMAKE_INSTALL_PREFIX=/home/jenkins/workspace/libelektra-release@2/system ../elektra-0.10.0
CMake Error: The source directory "/home/jenkins/workspace/libelektra-release@2/libelektra/build/elektra-0.10.0" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
script returned exit code 1
```

**Comment by markus2330** [comment]
I love your responsiveness and I am waiting for a PR :rocket:

**Comment by tmakar** [comment]
> I love your responsiveness and I am waiting for a PR rocket

PR is ready here https://github.com/ElektraInitiative/libelektra/pull/4933 (still running) :smiley:

**Comment by tmakar** [comment]
@markus2330 Do you think we can already merge this https://github.com/ElektraInitiative/libelektra/pull/4933?

Btw, rerun the master build 😉

**Comment by markus2330** [comment]
I updated the VERSION in Jenkins to 0.10.0.

Let us see if the master build runs through.

It would be best if @atmaxinger could trigger the release builds, I won't be available today.

"Increment version in Wikipedia pages:" in doc/todo/RELEASE.md is still not removed on master?

**Comment by markus2330** [comment]
I started https://build.libelektra.org/job/libelektra-release/196/

**Comment by tmakar** [comment]
> I updated the VERSION in Jenkins to 0.10.0.
> 
> Let us see if the master build runs through.
> 
> It would be best if @atmaxinger could trigger the release builds, I won't be available today.
> 
> "Increment version in Wikipedia pages:" in doc/todo/RELEASE.md is still not removed on master?

Thank you! Ohhh, will immediately create a PR for that removal!!

**Comment by tmakar** [comment]
@markus2330 Here is the removal of wikipedia in release todos. https://github.com/ElektraInitiative/libelektra/pull/4935 :smiley:

**Comment by tmakar** [comment]
> I started https://build.libelektra.org/job/libelektra-release/196/

I see that there is again this error message for the release build:

```sh
+ cmake -DPLUGINS=ALL -DTOOLS=ALL -DENABLE_DEBUG=OFF -DENABLE_LOGGER=OFF -DBUILD_SHARED=ON -DBUILD_FULL=ON -DBUILD_STATIC=ON -DKDB_DB_SYSTEM=/home/jenkins/workspace/libelektra-release/config/kdb/system -DKDB_DB_SPEC=/home/jenkins/workspace/libelektra-release/config/kdb/spec -DKDB_DB_HOME=/home/jenkins/workspace/libelektra-release/config/kdb/home -DCMAKE_INSTALL_PREFIX=/home/jenkins/workspace/libelektra-release/system ../elektra-0.10.0
CMake Error: The source directory "/home/jenkins/workspace/libelektra-release/libelektra/build/elektra-0.10.0" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```

**Comment by tmakar** [comment]
@markus2330 Where is the src directory created? I can't find any `mkdir ...../elektra-$VERSION` in the `scripts/release/release.sh` file :thinking:

**Comment by markus2330** [comment]
> Where is the src directory created? I can't find any mkdir ...../elektra-$VERSION in the scripts/release/release.sh file thinking

@robaerd do you maybe know that?

**Comment by robaerd** [comment]
> > Where is the src directory created? I can't find any mkdir ...../elektra-$VERSION in the scripts/release/release.sh file thinking
> 
> @robaerd do you maybe know that?

The src dir should be created here https://github.com/ElektraInitiative/libelektra/blob/5ba10355823d7776a99bdff2c1c8762ba044c1b6/scripts/release/release.sh#LL192C2-L192C36

I think the quotation marks added to the version variable (commit: https://github.com/ElektraInitiative/libelektra/commit/ae089ea2edf08f0b022acb2c2a99a7e6df5d6d64) changed how the expanded archive is named, and thus the src dir cannot be found

**Comment by tmakar** [comment]
> > > Where is the src directory created? I can't find any mkdir ...../elektra-$VERSION in the scripts/release/release.sh file thinking
> > 
> > 
> > @robaerd do you maybe know that?
> 
> The src dir should be created here https://github.com/ElektraInitiative/libelektra/blob/5ba10355823d7776a99bdff2c1c8762ba044c1b6/scripts/release/release.sh#LL192C2-L192C36
> 
> I think the quotation marks added to the version variable (commit: [ae089ea](https://github.com/ElektraInitiative/libelektra/commit/ae089ea2edf08f0b022acb2c2a99a7e6df5d6d64)) changed how the expanded archive is named, and thus the src dir cannot be found

Thanks, I will try!

**Comment by tmakar** [comment]
After we merge this https://github.com/ElektraInitiative/libelektra/pull/4936, we can trigger the release again!

**Comment by markus2330** [comment]
https://build.libelektra.org/job/libelektra-release/197/

**Comment by markus2330** [comment]
https://build.libelektra.org/job/libelektra-release/198/

**Comment by tmakar** [comment]
> https://build.libelektra.org/job/libelektra-release/198/

It’s again the source directory problem. 😕

**Comment by tmakar** [comment]
```sh
source-package
Make a elektra source package by using git
fatal: not a valid object name: 0.10.0
Built target source-package
```

this is happening before the `tar …..` command.

**Comment by robaerd** [comment]
I think I spotted the issue now.
The version tag was prefixed with a "v" recently and thus the `make-source` command can't find the given tag as the "v" prefix is missing.

**Comment by markus2330** [comment]
@robaerd Thank you so much!

@tmakar Please make sure that it will also work from v0.10.0 -> v0.10.1 (where then also the old version will have a v in the beginning).

**Comment by tmakar** [comment]
> 

thank you!!!!! Do you mean `make source-package`? I couldn't find `make-source` :thinking:

**Comment by tmakar** [comment]
> @robaerd Thank you so much!
> 
> @tmakar Please make sure that it will also work from v0.10.0 -> v0.10.1 (where then also the old version will have a v in the beginning).

Will do!! But I actually only used the `v` prefix when `git tag` is explicitly run and when we fetch the tag I exclude the prefix `v`. Maybe I missed a file where we are using `git tag -l`.

**Comment by robaerd** [comment]
> @robaerd thank you!!!!! Do you mean `make source-package`? I couldn't find `make-source` 🤔

Yes, sorry, I meant `make source-package`.

**Comment by tmakar** [comment]
> > @robaerd thank you!!!!! Do you mean `make source-package`? I couldn't find `make-source` thinking
> 
> Yes, sorry, I meant `make source-package`.

No problem, thanks!!

**Comment by tmakar** [comment]
@markus2330 Here is the PR for the fix https://github.com/ElektraInitiative/libelektra/pull/4937 :smiley:

**Comment by markus2330** [comment]
https://build.libelektra.org/job/libelektra-release/199/

**Comment by tmakar** [comment]
> https://build.libelektra.org/job/libelektra-release/199/

@markus2330 Unfortunately there was an issue with `git-release-stats` script which I needed to adapt as well. I fixed it already here https://github.com/ElektraInitiative/libelektra/pull/4938.

**Comment by markus2330** [comment]
Thx, ping me when it is ready.

**Comment by markus2330** [comment]
https://build.libelektra.org/job/libelektra-release/200/ also failed, various temporary failures (they seem to be not excluded in the release pipeline)

https://build.libelektra.org/job/libelektra-release/202/

**Comment by tmakar** [comment]
> https://build.libelektra.org/job/libelektra-release/200/ also failed, various temporary failures (they seem to be not excluded in the release pipeline)
> 
> https://build.libelektra.org/job/libelektra-release/202/

What do you mean by „temporary release failures“? 🤔

**Comment by markus2330** [comment]
There are some unit tests that sporadically fail, there used to be a `rerun-failed` but it was removed recently, so I am afraid we need to restart manually until it succeeds unless someone has a better idea.

**Comment by tmakar** [comment]
@markus2330 did not pass again….

**Comment by markus2330** [comment]
https://build.libelektra.org/job/libelektra-release/203/

**Comment by lukashartl** [comment]
The pipeline is waiting for interactive input now 😄

**Comment by tmakar** [comment]
> The pipeline is waiting for interactive input now 😄

Hmm, what kind of input? I don’t have access so I think only @markus2330 or you can do this 😅

**Comment by tmakar** [comment]
Ah now I see it, „Publish, Yes or Abort“ 😅I think you can click on „Yes“ or input „Yes“ don’t know exactly 😬

**Comment by lukashartl** [comment]
It is asking the following question: `Publish Release?`.

Possible answers:
* `Yes`
* `Abbrechen`

I think this is a question that @markus2330 should answer 😅

**Comment by tmakar** [comment]
> It is asking the following question: `Publish Release?`.
> 
> Possible answers:
> 
> * `Yes`
> * `Abbrechen`
> 
> I think this is a question that @markus2330 should answer 😅

Yes, have seen it couple of minutes before. Alright, I thought you can also answer this 😅

**Comment by tmakar** [comment]
How does it usually behave? How long does it wait for input?

**Comment by tmakar** [comment]
@markus2330 Release pipeline is green 😬

**Comment by markus2330** [comment]
There are still some bugs:

- the tag was not created (can easily be manually done if all the other things are fixed but should fixed in release pipeline nevertheless)
- the news site is `0.9.0` instead of `0.10.0`: https://www.libelektra.org/news/
- many of the links/versions in 2023-05-22_0.10.0.md are `0.9.`.

Please do proper fixes that will also work with `0.11` or `1.0`.

**Comment by tmakar** [comment]
> There are still some bugs:
> 
> * the tag was not created (can easily be manually done if all the other things are fixed but should fixed in release pipeline nevertheless)
> * the news site is `0.9.0` instead of `0.10.0`: https://www.libelektra.org/news/
> * many of the links/versions in 2023-05-22_0.10.0.md are `0.9.`.
> 
> Please do proper fixes that will also work with `0.11` or `1.0`.

Well, that’s what I asked in the beginning in a PR were I made changes. I asked if I need to change the files again….

**Comment by markus2330** [comment]
But other than that it looks really good¹, so only the last few steps.

¹ The link check as described in doc/todo/release.md worked and kdb --version of the debs print 0.10.0. I didn't test the rpms, though.

**Comment by tmakar** [comment]
And yes, this will also work with other versions. Is there any other place then `release.sh` were tags are created? Because there I adapted everything….

**Comment by markus2330** [comment]
> Well, that’s what I asked in the beginning in a PR were I made changes. I asked if I need to change the files again….

Ok, seems like there was a misunderstanding. At least following files still need fixes:

- doc/todo/NEWS.md
- doc/news/_preparation_next_release.md
- doc/news/2023-05-22_0.10.0.md (should also be renamed to 05-23 as the release happens today)

**Comment by mpranj** [comment]
> - the tag was not created (can easily be manually done if all the other things are fixed but should fixed in release pipeline nevertheless)

Not sure how it is done now, but the tags were never automatically pushed.
For the 0.9 series you had to download the git bundle from the jenkins artifacts and push the tag manually. (Intentionally, as a last verofication step)

**Comment by markus2330** [comment]
> Not sure how it is done now, but the tags were never automatically pushed.
> For the 0.9 series you had to download the git bundle from the jenkins artifacts and push the tag manually. (Intentionally, as a last verofication step)

Thanks for the notice! :heart: Seems like this is forgotten to be written in doc/todo/RELEASE.md
Can you write some text what exactly you normally did?

**Comment by tmakar** [comment]
> > Well, that’s what I asked in the beginning in a PR were I made changes. I asked if I need to change the files again….
> 
> Ok, seems like there was a misunderstanding. At least following files still need fixes:
> 
> * doc/todo/NEWS.md
> * doc/news/_preparation_next_release.md
> * doc/news/2023-05-22_0.10.0.md (should also be renamed to 05-23 as the release happens today)

PR is on the way!

**Comment by tmakar** [comment]
@markus2330 @mpranj 

> doc/news/2023-05-22_0.10.0.md (should also be renamed to 05-23 as the release happens today)

AFAIK, this file was created automatically, should I also change the content and adapt it to contain the correct description?


> doc/news/_preparation_next_release.md

this file should also contain everything from the `0.10.0` version, right?

> doc/todo/NEWS.md

what should the contents of this file be?

**Comment by mpranj** [comment]
> Thanks for the notice! :heart: Seems like this is forgotten to be written in doc/todo/RELEASE.md
> 
> Can you write some text what exactly you normally did?

I can document it later, but if it needs to be done quickly: you can `git checkout` a bundle or `git remote add bundle some.bundle` and then just push the tag(s).

**Comment by markus2330** [comment]
Yes please, and also fix the scripts so that they will get added next time.

**Comment by tmakar** [comment]
> Yes please, and also fix the scripts so that they will get added next time.

@markus2330 Ready now https://github.com/ElektraInitiative/libelektra/pull/4942!!

**Comment by markus2330** [comment]
Great, let us see if the master build goes through, which will update the website.

Let us close this, as release pipeline succeeded!
