### ISSUE TITLE
document release

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4945]
> Thanks for the notice! :heart: Seems like this is forgotten to be written in doc/todo/RELEASE.md
> 
> Can you write some text what exactly you normally did?

I can document it later, but if it needs to be done quickly: you can `git checkout` a bundle or `git remote add bundle some.bundle` and then just push the tag(s).

_Originally posted by @mpranj in https://github.com/ElektraInitiative/libelektra/issues/4928#issuecomment-1558623849_

**Comment by markus2330** [comment]
If possible, please also do it for 0.10.0 release.

**Comment by mpranj** [comment]
I added the docu, seems that the tag was already pushed before.

The github release needs to be done though. (copying the website news basically..)

Great job with the release @tmakar! :rocket:

**Comment by tmakar** [comment]
@markus2330 https://www.libelektra.org/news/0.10.0-release is now also available!

**Comment by tmakar** [comment]
> I added the docu, seems that the tag was already pushed before.
> 
> The github release needs to be done though. (copying the website news basically..)
> 
> Great job with the release @tmakar! 🚀

I created the release on Github :) https://github.com/ElektraInitiative/libelektra/releases/tag/v0.10.0
