### ISSUE TITLE
spec plugin does not remove added meta data on arrays

### ISSUE THREAD

**Issue by atmaxinger** [ElektraInitiative/libelektra#4961]
The metadata added to arrays by the spec plugin is not being removed.
This issue needs to be addressed in the next release, as it poses a significant obstacle for applications that rely on storage plugins that lack support for custom metadata, like TOML.
This also blocks progress on Opensesame.

Here is a reproducible example, you can add this function to `testmod_spec`:
```c
static void test_hook_remove_spec_keys_from_array_should_succeed (void)
{
	printf ("test %s\n", __func__);

	TEST_BEGIN
	{
		KeySet * ks = ksNew (0, KS_END);

		ksAppendKey (ks, keyNew ("spec:/sw/libelektra/opensesame/#0/current/sensors/#/loc", KEY_META, "description", "location of the sensor", KEY_END));
		ksAppendKey (ks, keyNew ("system:/sw/libelektra/opensesame/#0/current/sensors/#0/loc", KEY_VALUE, "guests", KEY_END));

		int resultCopy = elektraSpecCopy (NULL, ks, parentKey, true);

		// check if meta keys were copied
		Key * realKey = ksLookupByName (ks, "system:/sw/libelektra/opensesame/#0/current/sensors/#0/loc", 0);
		succeed_if (realKey != NULL, "key must exist");
		succeed_if (keyGetMeta (realKey, "meta:/description") != NULL, "meta must exist after copying");

		int resultRemove = elektraSpecRemove (NULL, ks, parentKey);

		// check if meta keys were removed
		ksLookupByName (ks, "system:/sw/libelektra/opensesame/#0/current/sensors/#0/loc", 0);
		succeed_if (realKey != NULL, "key must exist");
		succeed_if (keyGetMeta (realKey, "meta:/description") == NULL, "meta must NOT exist after copying");

		TEST_CHECK (resultCopy == ELEKTRA_PLUGIN_STATUS_SUCCESS, "plugin should have succeeded");
		TEST_CHECK (resultRemove == ELEKTRA_PLUGIN_STATUS_SUCCESS, "plugin should have succeeded");

		ksDel (ks);
	}
	TEST_END
}
```

**Comment by tmakar** [comment]
> Thanks for reporting this problem! I agree this is important.
> 
> @tmakar can you maybe give an hint how/where to fix the problem?
> 
> Any volunteers to fix it?

Whoever fixes this, the only place responsible for removal of metakeys is `elektraSpecRemove`. All the code resides in this function.

**Comment by tmakar** [comment]
@atmaxinger @markus2330 

I did the bugfix by myself now :grin: 
https://github.com/ElektraInitiative/libelektra/pull/4963

**Comment by markus2330** [comment]
@tmakar thank you so much! :heart: Looks very good, only one small memory bug that should be easy to fix.
