### ISSUE TITLE
master build fails

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4973]
https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/master/1072/pipeline

```
Starting build/hub.libelektra.org/build-elektra-openwrt-sdk:202307-03ce68c0892bdd01df99381d46d1e68062936286e7cfda33ec88dcf8f2e8beb2/ on h1
...
docker build -t "$JD_IMAGE" --pull --build-arg JENKINS_GROUPID=47110 --build-arg JENKINS_USERID=47110 --build-arg PARALLEL=12 --build-arg PIPELINE_TAG=libelektra_master_1072 -f ./scripts/docker/openwrt/sdk/Dockerfile ./scripts/docker/openwrt/sdk
...
#6 [3/5] RUN sudo groupadd     -g 47110     -f     jenkins
#6 0.310 /bin/sh: 1: sudo: not found
#6 ERROR: process "/bin/sh -c sudo groupadd     -g ${JENKINS_GROUPID}     -f     jenkins" did not complete successfully: exit code: 127
```

**Comment by atmaxinger** [comment]
Hmm it seems like the [openwrt/sdk](https://hub.docker.com/r/openwrt/sdk/tags?page=1&name=latest) docker image was updated recently, maybe they don't include `sudo` by default anymore.

**Comment by 4ydan** [comment]
Ok so I tried various openwrt/sdk images (build 20days ago, 2month ago) and they all fail. I really wonder how the pipeline worked one month ago when it got merged. Could it be something else then?
Also maybe there should be an tag for the target-subtarget atleast, I dont know what :latest is/was building.

**Comment by markus2330** [comment]
@Eiskasten do you know something about this?

**Comment by atmaxinger** [comment]
Can we disable OpenWRT just for this release?

**Comment by markus2330** [comment]
Yes, definitely. We can also permanently disable it, afaik we don't have a OpenWRT maintainer anymore.

Much more interesting than OpenWRT would be a arm/Olimex build... Maybe you can do it manually for this release?

**Comment by Eiskasten** [comment]
No, I do not know anything about this. However, I wonder why this happens. `sudo` actually gets installed: `#5 78.30 Installing package 'sudo' from packages`

**Comment by 4ydan** [comment]
So this can be closed, since the pipeline fixed itself?
