### ISSUE TITLE
upgrade Opensesame to libelektra 0.11.0

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4986]
@markus2330 for some reason I still get [this](https://github.com/ElektraInitiative/opensesame/issues/45) conflict. I changed the elektra version to `elektra = { version = "0.10.0", features = ["pkg-config"] }`, but the error message still says: ```... which satisfies dependency `bindgen = "^0.50.0"``` of package `elektra-sys v0.9.1`. I don't know why `elektra-sys v0.9.1` is still in use?

_Originally posted by @fel115 in https://github.com/ElektraInitiative/libelektra/issues/4983#issuecomment-1663449368_

**Comment by markus2330** [comment]
@atmaxinger do you maybe know something about this? Can you try to compile opensesame with the latest version of Elektra?

@fel115 do not hesitate to create new issues, old PRs are not a good idea to report that something (still) doesn't work.

**Comment by atmaxinger** [comment]
Seems like the published version of the rust bindings [still depend on elektra-sys 0.9.1](https://crates.io/crates/elektra/0.10.0/dependencies).

**Comment by atmaxinger** [comment]
They are already updated in the release PR

**Comment by markus2330** [comment]
Perfect, let us do the release then. :rocket:
