### ISSUE TITLE
Can't set value, `Did not find key ...`

### ISSUE THREAD

**Issue by fel115** [ElektraInitiative/libelektra#4987]
After setting a new key/value to the database, elektra can't find the new created key.

```bash
kdb set -v user:/sw/libelektra/opensesame/#0/current/sensors/#0/loc "Weatherstation"; 
kdb get -v user:/sw/libelektra/opensesame/#0/current/sensors/#0/loc; 

opensesame: no process found
Create a new key user:/sw/libelektra/opensesame/#0/current/sensors/#0/loc with string "Weatherstation"
got 49 keys
searching user:/sw/libelektra/opensesame/#0/current/sensors/#0/loc, found: <nothing>
Did not find key 'user:/sw/libelektra/opensesame/#0/current/sensors/#0/loc'
```

With other values, it worked well. Could this be caused by the second `#0`? 

I also described this issue in this [issue](https://github.com/ElektraInitiative/opensesame/issues/51) of opensesame.

**Comment by markus2330** [comment]
Thank you for reporting this problem!

`#0` are the first entry for arrays, so they have a special meaning.

To make this issue reproducible we probably need a longer example, including the mounting of TOML (probably the bug is related to this).

@atmaxinger do you maybe have an idea?

**Comment by fel115** [comment]
For some reason, it worked today. But then I tried to remove one entry in the array and it removed the whole array. I used `kdb rm user:/sw/libelektra/opensesame/#0/current/sensors/loc`to remove the loc entry. 
But mounting works without an error
```bash
root@messstation:/home/olimex/opensesame/debian# kdb mount -vv /home/olimex/opensesame/files/opensesame.spec spec:/sw/libelektra/opensesame/#0/current ni
root@messstation:/home/olimex/opensesame/debian# kdb spec-mount -vv /sw/libelektra/opensesame/#0/current
Got mountpoint from spec:/sw/libelektra/opensesame/#0/current with 24 nodes, configfile: opensesame.toml and mountpoint: /sw/libelektra/opensesame/#0/current
root@messstation:/home/olimex/opensesame/debian# kdb mount -vv /home/olimex/opensesame/files/opensesame.state.spec spec:/state/libelektra/opensesame/#0/current ni
root@messstation:/home/olimex/opensesame/debian# kdb spec-mount -vv /state/libelektra/opensesame/#0/current ni
Got mountpoint from spec:/state/libelektra/opensesame/#0/current with 3 nodes, configfile: opensesame.state and mountpoint: /state/libelektra/opensesame/#0/current
```

TOML files used [opensesame.spec](https://github.com/ElektraInitiative/opensesame/blob/master/files/opensesame.spec) and [opensesame.stat.spec](https://github.com/ElektraInitiative/opensesame/blob/master/files/opensesame.state.spec)

**Comment by fel115** [comment]
@atmaxinger how can I add an array with `kdb editor ...`, I don't understand the syntax in this file. Is there any documentation about it? I wasn't able to find one.

**Comment by markus2330** [comment]
@fel115 you can choose your own syntax, but better use toml to not run into conversation issues. `man kdb editor` should work, is this missing in our armhf Debian packages?

Btw. As last resort you can also directly edit ~/.config/opensesame.toml

**Comment by fel115** [comment]
@markus2330 Thx, now I was able to open the editor with the toml-format. `man kdb editor` is working.

I tried to add the array by adding `sensors.#0.loc = "weatherstation" to the ~/.config/opensesame.toml file, but I get this error message:

```
Validation Syntactic: Line 1~(11:8-11:32): syntax error, unexpected COMMENT, expecting BARE_STRING or LITERAL_STRING or BASIC_STRING
```

**Comment by markus2330** [comment]
I think you need to quote `"#0"`, e.g. `sensors."#0".loc = "Gaestezimmer"`. Use `git checkout` if you messed up the config to start again.

**Comment by fel115** [comment]
> I think you need to quote `"#0"`, e.g. `sensors."#0".loc = "Gaestezimmer"`. Use `git checkout` if you messed up the config to start again.

Perfect, now its working. Thx :relaxed:
