### ISSUE TITLE
building plugin doc fails on Mac OS X

### ISSUE THREAD

**Issue by tryge** [ElektraInitiative/libelektra#509]
When running the command `cmake .. -DPLUGINS='dump;resolver;sync;error;doc'`, `make` fails with the following message:

```
[ 19%] Linking C shared module ../../../lib/libelektra-doc.so
Undefined symbols for architecture x86_64:
  "_kdbSet", referenced from:
      _elektraUsercodeUselessSymbol in doc.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libelektra-doc.so] Error 1
make[1]: *** [src/plugins/doc/CMakeFiles/elektra-doc.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by markus2330** [comment]
Actually, you can safely omit the "doc" plugin, it does not really do something useful for itself. Otherwise, it might be an easy fix by adding `LINK_ELEKTRA elektra-kdb` in the CMakeLists.txt. Unfortunately, I cannot reproduce the problem, gcc seems to not care about the unused code.
