### ISSUE TITLE
some tests failing on OS X

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#515]
steps to reproduce:
```
cd build && cmake -DPLUGINS=NODEP -DTOOLS=NODEP -DBINDINGS=cpp .. && make
sudo make run_all
```

testmod_conditionals:
```
testmod_conditionals.c:29: error in test_ifthenelseint: error
testmod_conditionals.c:47: error in test_ifthenint: error
testmod_conditionals.c:65: error in test_ifthenltint: error
testmod_conditionals.c:102: error in test_ifthenkey: error
testmod_conditionals.c:122: error in test_emptyisempty: error
testmod_conditionals.c:142: error in test_notempty: error
testmod_conditionals.c:161: error in test_ifsetthenval: error
testmod_conditionals.c:163: error in test_ifsetthenval: error setting then value
testmod_conditionals.c:181: error in test_ifsetthenkey: error
testmod_conditionals.c:183: error in test_ifsetthenkey: error setting then value
testmod_conditionals.c:197: error in test_assignThen: error
testmod_conditionals.c:199: error in test_assignThen: error setting then value
testmod_conditionals.c:214: error in test_assignElse: error
testmod_conditionals.c:216: error in test_assignElse: error setting then value
```

The following tests FAILED:
```
20 - testmod_conditionals (Failed)
58 - testscr_check_get_set (Failed)
59 - testscr_check_import (Failed)
61 - testscr_check_kdb_internal_suite (Failed)
66 - testscr_check_real_world (Failed)
67 - testscr_check_resolver (Failed)
```

It seems that lots of the errors occur in `simpleini`:
```
error: could not rm system/test/script/apps/next/x/a/b (having value y)
The command set failed while accessing the key database with the info:
Error (#60) occurred!
Description: Invalid Line encountered
Ingroup: plugin
Module: simpleini
At: /Users/mpranj/workspace/libelektra/src/plugins/simpleini/simpleini.c:102
Reason: not at the end of file
Mountpoint: user/test/script/apps
Configfile: /Users/mpranj/.config/test_real_world_apps.ini
```

Output from the failing tests:
[testscr_check_resolver.txt](https://github.com/ElektraInitiative/libelektra/files/130360/testscr_check_resolver.txt)
[testscr_check_real_world.txt](https://github.com/ElektraInitiative/libelektra/files/130364/testscr_check_real_world.txt)
[testscr_check_kdb_internal_suite.txt](https://github.com/ElektraInitiative/libelektra/files/130361/testscr_check_kdb_internal_suite.txt)
[testscr_check_import.txt](https://github.com/ElektraInitiative/libelektra/files/130363/testscr_check_import.txt)
[testscr_check_get_set.txt](https://github.com/ElektraInitiative/libelektra/files/130362/testscr_check_get_set.txt)

**Comment by markus2330** [comment]
Thank you for reporting!

Can you also add the output of the other failed test cases?
Does the `list` plugin now work? How did you fix it?
Is it possible that PLUGIN_OPEN already fails? (Then nearly every testmod_* testcase should fail)

**Comment by mpranj** [comment]
Sorry I think I mixed up the options, this was with `-DPLUGINS=NODEP -DTOOLS=NODEP -DBINDINGS=cpp` I guess. Have to check it again.

The `list` plugin is still failing yes.

**Comment by mpranj** [comment]
Indeed this was when I tested with `NODEP` plugins&tools.

**Comment by mpranj** [comment]
Most testmod_* tests are passing here.

**Comment by tryge** [comment]
For me the commands:
```
cmake .. -DPLUGINS=ALL -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib/libcrypto.dylib
make -j12
make run_all
```

where the following plugins were excluded:
```
fstab
dbus
jni
python
```

resulted in the following failing tests:
```
	 20 - testmod_conditionals (Failed)
	 58 - testscr_check_distribution (Failed)
	 59 - testscr_check_error (Failed)
	 61 - testscr_check_external (Failed)
	 62 - testscr_check_get_set (Failed)
	 63 - testscr_check_import (Failed)
	 65 - testscr_check_kdb_internal_suite (Failed)
	 67 - testscr_check_mount (Failed)
	 70 - testscr_check_real_world (Failed)
	 71 - testscr_check_resolver (Failed)
	 72 - testscr_check_spec (Failed)
	 99 - testkdb_nested (Failed)
	100 - testkdb_simple (Failed)
```

**Comment by markus2330** [comment]
testmod_conditionals is strange, that should be completely portable C code.

The others seem like that `kdb` cannot write to `system`? (i.e. /etc/kdb)
(Or not using dump as default backend, but this seems to be not the case)

**Comment by tryge** [comment]
Why do the tests need to write to `/etc` ? For me this means I need to run the tests with `sudo`, do I?

**Comment by mpranj** [comment]
Indeed you need root access.

**Comment by tryge** [comment]
Ok, that changed the output, but is still not consistent with the tests that failed for @mpranj :

```
	 20 - testmod_conditionals (Failed)
	 62 - testscr_check_get_set (Failed)
	 63 - testscr_check_import (Failed)
	 65 - testscr_check_kdb_internal_suite (Failed)
	 70 - testscr_check_real_world (Failed)
	 71 - testscr_check_resolver (Failed)
```

**Comment by markus2330** [comment]
Thank you!

You do not necessarily need root access, you also can reconfigure `KDB_DB_SYSTEM` or chown `KDB_DB_SYSTEM` to your user.
(By default /etc/kdb)

Can you give the output of the tests. Only the testnames alone do not really help.

Can someone look into the `testmod_conditionals`? It seems like there is undefined behaviour triggered and it works with gcc just by chance.

**Comment by tryge** [comment]
Here is the output:
[testmod_conditionals.txt](https://github.com/ElektraInitiative/libelektra/files/131264/testmod_conditionals.txt)
[testscr_check_get_set.txt](https://github.com/ElektraInitiative/libelektra/files/131265/testscr_check_get_set.txt)
[testscr_check_import.txt](https://github.com/ElektraInitiative/libelektra/files/131266/testscr_check_import.txt)
[testscr_check_kdb_internal_suite.txt](https://github.com/ElektraInitiative/libelektra/files/131267/testscr_check_kdb_internal_suite.txt)
[testscr_check_real_world.txt](https://github.com/ElektraInitiative/libelektra/files/131268/testscr_check_real_world.txt)
[testscr_check_resolver.txt](https://github.com/ElektraInitiative/libelektra/files/131269/testscr_check_resolver.txt)

**Comment by mpranj** [comment]
@tryge you obviously get different output if you don't use the steps to reproduce which were mentioned in the description

**Comment by mpranj** [comment]
@markus2330 ok I'll look into `testmod_conditionals` first

**Comment by tryge** [comment]
Well obviously, however, I didn't try to reproduce anything. I just tried the tests for the build I'm interested in and thought my input might be valuable... 

I'm not sure if my input helps, but I learned something, so for me it was valuable :-)

**Comment by mpranj** [comment]
Sure it helps. I was just thinking it might make sense to separate into new issues since this one is already a huge "things are a bit broken on OS X" issue.

**Comment by markus2330** [comment]
Btw. to run as non-root you also need to take care for KDB_DB_SPEC. But actually it is good if we also test it as root, because from this release on, `kdb` behaves different as root. (`system` is default namespace).

About conditionals: The most likely source of unportable behaviour is the regex: `(\\(([^\\)]*)\\))\\s*(\\?)\\s*(\\(([^\\)]*)\\))\\s*(:\\s*(\\(([^\\)]*)\\))){0,1}`. @mpranj Can you check if this regex only contains portable constructs?
@KurtMi You might be interested in this problem, too.

For simpleini the problem is most likely the fscanf format specifier `ms`. The portable workaround is quite long and basically a reimplementation of the parser, thus I would say for now its best to disable `simpleini` for Mac OS X. All the Error (#60) seem to be caused by it. In a quick look I did not find any other error except this one. @mpranj Can you retry with `-DPLUGINS=all;-simpleini`?

**Comment by mpranj** [comment]
@markus2330 currently I cannot build ALL plugins. But yes `-simpleini` fixes lots of the fails, remaining is:
```
20 - testmod_conditionals (Failed)
67 - testscr_check_resolver (Failed)
```

the check_resolver thing can be quicky fixed I guess (it's the /tmp vs /private/tmp path thing..)

**Comment by mpranj** [comment]
#520 fixes testscr_check_resolver

**Comment by mpranj** [comment]
@markus2330 thanks. It was indeed the regex that was not portable.
