### ISSUE TITLE
spec/conditionals: error message wrong

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#523]
```
$ kdb rm -r user/example/highlevel/
$ kdb set /example/highlevel/device smartphone
$ kdb get /example/highlevel/powersaving/gps
Did not find key
$ kdb set /example/highlevel/powersaving/gps
Using name user/example/highlevel/powersaving/gps
Create a new key user/example/highlevel/powersaving/gps with null value
$ kdb get /example/highlevel/powersaving/gps
```

Only when I assign a non-null key, it will work:

```
$ kdb set /example/highlevel/powersaving/gps s
Using name user/example/highlevel/powersaving/gps
Set string to s
$ kdb get /example/highlevel/powersaving/gps
empty
```

**Comment by markus2330** [comment]
Some clarification: I think that assign/* already states that a key should be created if missing. So the issue is not only about null keys, but also for missing keys.

**Comment by tom-wa** [comment]
should that also work for kdb get if the key doesn't exist ?
because i'm having some issues there (conditionals getting called before spec)
we should probably have 2 postgetstorage global placements (1 directly after getstorage and one directly after the last postget)

**Comment by markus2330** [comment]
Yes, as second step (not in the same PR), it should also work without the key. (See proposal with `default` calculation #533) And yes, new hooks might be needed then. Maybe we can remove other hooks though, the ones executed in the loop would be quite different to use.

**Comment by markus2330** [comment]
Seems to be completely broken now.

```
$ kdb global-mount 
$ kdb get /example/highlevel/powersaving/gps
s
```

expected: `empty`.

@tom-wa Seems like spec does not work at all anymore? Do you have some test cases where it works properly?

**Comment by tom-wa** [comment]
fixed in #661, mixed some lines up when i've added the missing initialization of the globalplugins array

**Comment by markus2330** [comment]
It seems to be again broken?
```
kdb set /example/highlevel/powersaving/gps
Using name user/example/highlevel/powersaving/gps
Create a new key user/example/highlevel/powersaving/gps with null value
The command set failed while accessing the key database with the info:
Error (#134) occurred!
Description: Syntax error
Ingroup: plugin
Module: conditionals
At: /home/jenkins/workspace/workspace/elektra-git-buildpackage-wheezy/libelektra/src/plugins/conditionals/conditionals.c:636
Reason: Invalid syntax: "(battery/level". Check kdb info conditionals for additional information
```
Can you record this with shellrecorder to avoid such regressions?

**Comment by tom-wa** [comment]
works fine for me, what exaclty is the issue ?  
https://github.com/ElektraInitiative/libelektra/blob/master/examples/spec/locationtracker.ini has an issue with the linebreak at line 37, but it you remove the newline it works fine too

**Comment by markus2330** [comment]
The issue (executing code above) now is an invalid syntax error:

```
kdb get /example/highlevel/powersaving/gps
The command get failed while accessing the key database with the info:
Error (#134) occurred!
Description: Syntax error
Ingroup: plugin
Module: conditionals
At: /home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/conditionals/conditionals.c:636
Reason: Invalid syntax: "(battery/level". Check kdb info conditionals for additional information

Mountpoint: user/example/highlevel
Configfile: /home/markus/.config/highlevel.ini
```

Seems like only values and not variables are allowed in the then?

**Comment by markus2330** [comment]
If I change it:
```
diff --git a/examples/spec/highlevel.ini b/examples/spec/highlevel.ini
index 03c17c0..19a832a 100644
--- a/examples/spec/highlevel.ini
+++ b/examples/spec/highlevel.ini
@@ -5,7 +5,7 @@ mountpoint = highlevel.ini
 check/enum = 'wearable','smartphone','vehicle'
 
 [powersaving/gps]
-assign/condition = (device != 'vehicle') ? (battery/level) : ('full')
+assign/condition = (device != 'vehicle') ? ('low') : ('full')
 
 [gps/status]
 assign/condition = (powersaving/gps > 'low') ? ('active') : ('inactive')
```

it works (without prior set of /example/highlevel/powersaving/gps), thus the original issue is solved.

**Comment by tom-wa** [comment]
sorry, the error message is wrong. it works for me after setting the key /examples/highlevel/battery/level.
i've already revised spec and conditionals to use the new syntax for absolute and relative keys and wanted to make the PR after the 0.8.16 release.

**Comment by markus2330** [comment]
Ok thank you, then the error message should be updated.
