### ISSUE TITLE
range plugin

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#524]
type check min/max be replaced by arbitrary ranges + should yield better error messages

**Comment by tom-wa** [comment]
what datatypes other than unsigned integers should be supported ?
signed integers, floating point numbers, chars ? 

is posix regex as a dependency fine ?

**Comment by markus2330** [comment]
> what datatypes other than unsigned integers should be supported ?

See discussion in #1324.

> signed integers, floating point numbers, chars ?

Yes.

> is posix regex as a dependency fine ?

Yes, see #388

**Comment by tom-wa** [comment]
what about string ranges like "aaaa-azzz" ?

**Comment by markus2330** [comment]
No, please do not support that. A regex like `a[a-z]{3}` sounds to me more natural to specify something like that. I am not even sure what the semantics of  "aaaa-azzz" would be.

**Comment by tom-wa** [comment]
not sure where i've seen it, but i remember seeing alpha ranges like that somewhere.

**Comment by markus2330** [comment]
They somehow seem complementary but they really are not.

Stick to the list definition of `cut`, for me it seems to be quite intuitive.

They also support the complement definition so you write 1-10, but you get -∞-0,11-∞. But sounds to be not really important to me?

Did you already solve the issue how to specify negative numbers? It collides with `-` as range operator.

**Comment by tom-wa** [comment]
>Did you already solve the issue how to specify negative numbers? It collides with - as range operator.


```
	testInt ("2", 1, " - 1 - 10");
	testInt ("-2", 1, "-3 --1");

	testInt ("-2", 1, "-3 --  1");
	testInt ("-2", 1, "-3 - -  1");
	testInt ("-2", 1, "-3--  1");

	testInt ("-2", -1, "-31");
	testInt ("-2", -1, "--3--1");
	testInt ("-2", -1, "-3---1");
```
all work fine

**Comment by markus2330** [comment]
I mean regarding the list definition of `cut` which allows `-M` to be from first to Mth field.

But you are right, lets rather not allow this shortcut.

Are you sure you want to accept `-3---1` shouldn't it be wrong syntax?

Btw. please also implement checkconf

**Comment by tom-wa** [comment]
>Are you sure you want to accept -3---1 shouldn't it be wrong syntax?

it's wrong syntax and gets rejected

**Comment by tom-wa** [comment]
(the second parameter is the expected return value)

**Comment by markus2330** [comment]
Please also add a check in the test cases which error was thrown (syntax error or outside of range).

**Comment by tom-wa** [comment]
are there any macros / functions for testing errors i'm missing or should i implement them ?

**Comment by markus2330** [comment]
You can create a key with the error meta data and do `compare_key`. But you are right: a convenience functionality for checking errors would be nice.
