### ISSUE TITLE
libsplit benchmark script is bash dependent

### ISSUE THREAD

**Issue by fberlakovich** [ElektraInitiative/libelektra#530]
The benchmark script introduced in 15657e4d seems to be dependent on bash. When executed with the shebang provided it throws the following error on my development system (Debian 7.9):

```libelektra/scripts/benchmark_libsplit.sh: 18: libelektra/scripts/benchmark_libsplit.sh: Syntax error: Missing '))'```

The issue seems to be rooted in the line ```WALLTIME=$((time -p $BENCHMARK) 2>&1)```.
Can anyone confirm this issue?

**Comment by markus2330** [comment]
Thank you for reporting!

I think its ok to use `#!/bin/bash` for such very specific scripts. The script also depends on existance of doc/benchmark/logs and the build folder within the source.

For elektra-merge, however, it would be nice to actually be POSIX conformant and state that with `#/bin/sh`.

**Comment by mpranj** [comment]
Thanks for reporting. Will fix it later. The main purpose of the script was to show how the benchmark was done, so I skipped all sanity checks.
