### ISSUE TITLE
Add Logo to ElektraInitiative Organization on GitHub 

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#541]
I am not a fan of the current – randomly generated – picture. Can we please change the logo to something less generic. I think the [circle](https://github.com/ElektraInitiative/libelektra/blob/master/doc/images/circle.svg) image in the folder `doc` looks nice. By the way: Is it supposed to look like as if it was drawn by hand? First I assumed it was only available in bitmap form and made a vector copy of it myself: [Elektra Logo.zip](https://github.com/ElektraInitiative/libelektra/files/145106/Elektra.Logo.zip).

**Comment by markus2330** [comment]
Thank you, I changed the avatar of the organization, is the logo now everywhere it should be?

The Studio-HB did the logo and they are mentioned in the AUTHORS file. I think they are the only ones who know how they did it.

in the `doc/image` folder there is also an svg, was something wrong with it? If you have a better version, please send a PR.

**Comment by sanssecours** [comment]
> Thank you, I changed the avatar of the organization, is the logo now everywhere it should be?

As far as I can tell, yes. Thank you for adding the logo.

> in the doc/image folder there is also an svg, was something wrong with it? If you have a better version, please send a PR.

No, nothing is wrong with it. The small version of the logo (`circle.jpg`) contains some artifacts though. Personally I would prefer `circle.svg` – maybe converted to `png` – as logo for that reason. Below is a comparison between the copy of the logo I made, the current logo and a scaled down version of `circle.svg`.

![comparison small](https://cloud.githubusercontent.com/assets/691989/13296769/76e3bdaa-db2f-11e5-949c-652d71671fa5.png)

Here is a comparison of a larger version of the current logo (on the left) and my copy:

![comparison](https://cloud.githubusercontent.com/assets/691989/13297251/b026beb2-db31-11e5-8514-59a4c124e88c.png)

As you can see, the one of the left looks like as if it was drawn per hand. Since I really do not know which one I prefer, I think we should just leave the logo as it is today. Just for reference: The `zip` file below contains the vector version of my copy of the logo.

[Elektra Logo.zip](https://github.com/ElektraInitiative/libelektra/files/145278/Elektra.Logo.zip)

**Comment by markus2330** [comment]
Yes, its a pro/con, the jpg has ugly artifacts when scaled but has a nice gray background (which the svgs do not have).

**Comment by markus2330** [comment]
If you want you can create a PR, but I am not sure where your svg and the one below `doc/images` differ.

**Comment by sanssecours** [comment]
> …the jpg has ugly artifacts when scaled but has a nice gray background (which the svgs do not have).

Here is a version of my copy of the icon, with additional gradient and shadows:

![elektra new](https://cloud.githubusercontent.com/assets/691989/13628484/b4b94d72-e5d2-11e5-98b5-924480b03f76.png)

Maybe we could use this icon for the ElektraInitiative Organization. Unlike the current one, it contains no artifacts. Below is a comparison of the two icons at the same size:

![circle](https://cloud.githubusercontent.com/assets/691989/13628472/976356a0-e5d2-11e5-93e4-67443f5fd207.jpg) ![circle new](https://cloud.githubusercontent.com/assets/691989/13628473/97cdaabe-e5d2-11e5-8a24-dbf7a3c9a7d1.png)

**Comment by markus2330** [comment]
Wow great, looks like we get a new logo ;)
Lets look at it tommorrow together.

**Comment by sanssecours** [comment]
Markus, can you please also update the logo here on GitHub? The current version contains some compression artifacts:

![elektrainitiative](https://cloud.githubusercontent.com/assets/691989/14309237/6783cfae-fbdb-11e5-8caf-77e9db52b23e.png)

**Comment by markus2330** [comment]
@sanssecours seems like that my conversion of your svg had no better quality than the previous one. I now used your png you linked above and also added it to doc/images.
