### ISSUE TITLE
crypto tests

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#544]
The crypto tests now expect both variants to be present. It would be good to have a clever method so that the test cases run only against the variant actually included.

I also changed the add_plugin heavily, I hope I did not introduce a problem in the crypto plugin, please report if the behaviour changed. See the commit 3121a8ad1fb05eceeed313cbae511069eeb2b0e0 and especially doc/decisions/cmake_plugins.md.

**Comment by petermax2** [comment]
The tests were almost doing fine, because the plugins are loaded dynamically

    plugin = elektraPluginOpen ("crypto_gcrypt", modules, newWorkingConfiguration (), 0);
    if (plugin) { /* ...test magic... */ }

the test cases do not fail when the plugin is not present.

**Comment by petermax2** [comment]
@markus2330 does 76392daeb4293a4a29dda3f916b55e2c2787d112 work for you?

**Comment by markus2330** [comment]
add_plugintest (crypto) should only happen if the plugin was actually added in second phase.
