### ISSUE TITLE
CMake can't find OpenSSL development files for crypto_openssl

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#548]
On Fedora CMake can't find the OpenSSL development files altough the packages are installed properly.

**Comment by markus2330** [comment]
On Debian I had the same problem. Maybe its a regression I introduced when introducing the two-phase add_plugin.

**Comment by petermax2** [comment]
@markus2330 why did you introduce `FIND_PACKAGES` to `src/plugins/crypto/CMakeLists.txt`?

The following change works fine for me (on Debian 8):

	--- a/src/plugins/crypto/CMakeLists.txt
	+++ b/src/plugins/crypto/CMakeLists.txt
	@@ -31,7 +31,7 @@ if (DEPENDENCY_PHASE)
		endif ()
	
		set (plugin crypto_openssl)
	-       if (FIND_PACKAGES AND NOT OPENSSL_MANUAL_OSX_HACK)
	+       if (NOT OPENSSL_MANUAL_OSX_HACK)
			include (FindPkgConfig)
			pkg_search_module (OPENSSL openssl)
		endif ()--- a/src/plugins/crypto/CMakeLists.txt
	+++ b/src/plugins/crypto/CMakeLists.txt
	@@ -31,7 +31,7 @@ if (DEPENDENCY_PHASE)
		endif ()
	
		set (plugin crypto_openssl)
	-       if (FIND_PACKAGES AND NOT OPENSSL_MANUAL_OSX_HACK)
	+       if (NOT OPENSSL_MANUAL_OSX_HACK)
			include (FindPkgConfig)
			pkg_search_module (OPENSSL openssl)
		endif ()

You can see the complete file in 78debc1a5471d7f89d511adbf463e2b3293c00d8 .

**Comment by petermax2** [comment]
@markus2330 please clarify the meaning of `FIND_PACKAGES` in `doc/decisions/cmake_plugins.md`. I have no idea what it is supposed to do (and I could only find it in this decisions file).

    		FIND_PACKAGES -> not only packages are subject to this phase

Is this a feature, that has not been implemented yes? Because at the moment it is never defined, so CMake does not even try to test for the OpenSSL development files.

**Comment by markus2330** [comment]
Sorry, my fault:  FIND_PACKAGES was a previous name of DEPENDENCY_PHASE, it is not used anymore and was forgotten at this place.

Thanks for finding the bug!
