### ISSUE TITLE
mathcheck: error when compiled with icc

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#550]
See http://community.markus-raab.org:8080/job/elektra-icc/lastFailedBuild/console, mathcheck seems to have issues when compiled with icc?

```
 22/106 Test  #22: testmod_mathcheck ..................***Failed    0.50 sec
elektraFtoA: val: 1,5, ret: 1.5
elektraEFtoF: string: 1.5, ret: 1,5
MATHCHECK	   TESTS
==================

/home/jenkins/workspace/workspace/elektra-icc/src/plugins/mathcheck/testmod_mathcheck.c:73: error in main: error
/home/jenkins/workspace/workspace/elektra-icc/src/plugins/mathcheck/testmod_mathcheck.c:77: error in main: error
/home/jenkins/workspace/workspace/elektra-icc/src/plugins/mathcheck/testmod_mathcheck.c:81: error in main: error
/home/jenkins/workspace/workspace/elektra-icc/src/plugins/mathcheck/testmod_mathcheck.c:85: error in main: error
/home/jenkins/workspace/workspace/elektra-icc/src/plugins/mathcheck/testmod_mathcheck.c:89: error in main: error

testmod_mathcheck RESULTS: 60 test(s) done. 5 error(s).
```

**Comment by markus2330** [comment]
not checked if problem actually is fixed.

**Comment by markus2330** [comment]
The problem is still open, can you improve the testcase so that the test output is helpful?

**Comment by tom-wa** [comment]
no idea what to do here. seems like icc is trying to do some memory optimizations which breaks the prefix stack.

**Comment by markus2330** [comment]
There are at least two things you can do here:

1) Improve the test case, so that more information is given about what happens
2) Minimalize the code and find out when it stops to break

Its likely that there is some undefined behaviour somewhere hidden and that gcc and clang currently only work by chance. If its really an icc problem only, we can ignore it. Btw. I can also try to upgrade icc, maybe it will fix the problem.

Did you try to run valgrind on what icc produced?

**Comment by markus2330** [comment]
I fixed the issue by excluding the plugin for icc. Improving the testcases would be useful nevertheless.
