### ISSUE TITLE
conditionals: assignment does not work on new keys

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#554]
```
kdb set user/example/highlevel/battery/level low
kdb set user/example/highlevel/device smartphone 
#kdb set user/example/highlevel/powersaving/gps
kdb get /example/highlevel/powersaving/gps
BLUBBERBLASEN!
```

Expected: low

**Comment by tom-wa** [comment]
ok, thats an embarrassing mistake... missed that one somehow while trying to figure out why the key doesn't get set...

**Comment by tom-wa** [comment]
otherwise the issue seems to be the same as #523
I'll try to change the hook placement to get it working.
