### ISSUE TITLE
Metadata in hosts and ini inconsistent

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#597]
On the one hand, hosts interprets order as "int", while ini already allows arbitrary strings (which are very useful to put a new entry at any place). libmeta should be used if possible.

On the other hand, hosts already supports new-style comments, while ini still seems to use the old ones. Also libmeta should be used for this feature. (hosts already has some functions to be moved to libmeta)

@fberlakovich is there another inconsistency I forgot?

**Comment by fberlakovich** [comment]
> @fberlakovich is there another inconsistency I forgot?

Nothing I am aware of.
