### ISSUE TITLE
Allow user to specify which elektra version to use

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#600]
Currently, on recompilation automatically the latest version of Elektra is used. This might be undesired:

1. Apps might want to be compatible to a wider range of Elektra versions and be sure that they did not use a function that was introduced later.
2. with symbol versioning, apps want to be linked against older versions (to be binary compatible to older Elektra versions)

Additionally, this proposal is also:

1. a preparation for a later header-file renaming. (`include <elektra/kdb.h>`).
2. would allow to remove/change macros/enums or other non-ABI stuff

Proposal:
The user can define with (`#define ELEKTRA_USE_VERSION 816`) that version 0.8.16 should be used. Even when compiling against Elektra 0.8.17, the user still would see the old interface (without what was added for 0.8.17).

When the user does not set ELEKTRA_USE_VERSION the latest version is used except for API-breaking parts. (e.g. for header file renaming and renames of enums the user must explicitely define ELEKTRA_USE_VERSION).

The main disadvantage is that it needs a lot of macro magic which is difficult to test.

What do you think?

(Especially @manuelm you proposed a macro for header file renaming, do you think this proposal fulfils what you wanted, too?)

For 0.8.16 we would only communicate to the users, that they should set this macro if they want to be frozen to the specific version. The API did not change in this release, so its a good time now.

**Comment by markus2330** [comment]
@edy What specifically do you dislike?

**Comment by manuelm** [comment]
I'm definitely against this version specific macro. It will lead to code cluttering and a lot of unnecessary ifdefs. Just think of an additional setmeta type, an enum or whatever which gets introduced in a new version.

And there's simple no need for this. If an application developers want to use an older version he has to link against and ship this specific version. Simple as that.

Don't introduce something way more horrible than ubuntu snappy.

**Comment by manuelm** [comment]
I'm really looking forward to things like this:
```
#if ELEKTRA_USE_VERSION >= 816
int betterElektraFoo() { ... }
#endif

#if ELEKTRA_USE_VERSION >= 810
int oldElektraFoo() { betterElektraFoo(some_stuff) }
#endif
```

**Comment by markus2330** [comment]
I also do not find it appealing from implementation side of view. It might, however, solve an important binary-portability problem:

Think of (non-statically) programs linking against glibc. They only run on systems where the same or a newer glibc version is running. When you want a portable binary, you need to compile against a really old glibc.

With the approach described above, I could set a macro and do not have to install a Fedora 7 or similar just to create a portable binary.

The code you showed is already present in code *using* Elektra. I think it is more important that client code is pretty, and not the library code.

**Comment by manuelm** [comment]
If you want a portable binary you either link statically or ship the library. End of story.

**Comment by markus2330** [comment]
Yeah, thats is the solution because every other way currently is not supported. But you are right, there is a good reason why nobody (incl. glibc) supports it: It is really a huge effort. Its much simpler to be compatible in one direction only.

If you want we can discuss it tomorrow.

**Comment by markus2330** [comment]
Closed because effort is too high.
