### ISSUE TITLE
longlock plugin

### ISSUE THREAD

**Issue by KurtMi** [ElektraInitiative/libelektra#605]
Implement new lock, out of pre state of semlock (see #578).

Btw. I think we found a use case for this kind of plugin: When we do not have or should not (NFS) rely on timestamps this could be useful.

Your strategy would already work if only the `kdb` tool is used, but it would not handle long-living processes that do multiple kdbSet?

So following tasks would be required to make a plugin for NFS-conflict detections out of it:
- [ ] rename it to something less generic, unless you plan to have multiple locking features combined in this plugin (including the global lock proposed)
- [ ] hold lock from first kdbGet() until kdbClose() (for multiple kdbSet())
- [ ] release lock when pid behind the lock is already gone
- [ ] avoid the busy loop

**Comment by markus2330** [comment]
thanks for creating the ticket! Can you do it for 0.8.16? (Let us discuss tomorrow)

**Comment by markus2330** [comment]
Can we close this ticket? I think we should focus on semlock.

**Comment by KurtMi** [comment]
Alright
