### ISSUE TITLE
support nfs in resolver

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#606]
```
bool_t xdr_nfstime (XDR *, nfstime*);
```

**Comment by markus2330** [comment]
Strange, actually the resolver only compares stat with stat timestamps, they should always have correct nfs time (and not care about local time).

Is it possible that a conflict actually happened or is there only one process executing the `kdb set`?

**Comment by tom-wa** [comment]
there is only one process executing `kdb set` and the problem only occured when there was a networking issue. 
i'll do some more debugging on friday.

**Comment by markus2330** [comment]
Ok, thank you.

**Comment by markus2330** [comment]
I think we can close this, please reopen if you find further NFS issues.
