### ISSUE TITLE
spec: copies meta data to wrong places

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#621]
Not having spec mounted, everything works nice, e.g. `kdb ls /`. After it is mounted I suddenly get the error:
```
$ kdb global-mount
$ kdb ls /
The command ls failed while accessing the key database with the info:
Error (#135) occurred!
Description: Validation failed
Ingroup: plugin
Module: conditionals
At: /home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/conditionals/conditionals.c:679
Reason: Validation of (test?/kontrolle == 'ab') ? ((test?/points >= '0') && (test?/points <= '50')) : (test?/points != '') failed. ((test?/points != '') failed)
Mountpoint: user/example/highlevel
Configfile: /home/markus/.config/highlevel.ini
```

Highlevel, however, does not even contain such a condition. Instead it seems like metadata from a different mountpoint is wrongly copied there.

**Comment by tom-wa** [comment]
i can't reproduce the problem, do you have any additional informations ?

**Comment by markus2330** [comment]
I'll send you `kdb export system` by e-mail. I have quite many mountpoints and data between them seems to get messed up with the spec plugin between them now.

**Comment by tom-wa** [comment]
seems like i've screwed up elektraGetDoUpdateWithGlobalHooks. i'm honestly out of ideas on how to do the globalplugins as hooks. Any suggestions ?

**Comment by markus2330** [comment]
@mpranj can you take a look at the global plugins? You would need them for the mmap storage.

The currently best way is to have a global plugin per position that is only executed once with the full keyset (all namespaces) as argument.

The only exception is one additional hook after storage plugin which is needed to inject meta-data for validation plugins in postget.

Later we will add AOP-like directives to add global plugins at any place before and after every action: also per-plugin and once. For example `postgetstorage/before@foreach` could be the specifier for a hook before postgetstorage which is executed for each plugin.

@KurtMi if you have some ideas with @tom-wa problem, please also help out.

**Comment by mpranj** [comment]
@markus2330: I can take a look at it, but can you specify what you mean. Just this meta-data issue or global plugins in general?

**Comment by markus2330** [comment]
@mpranj Yes, doing a code review of the hooks. Ideally you find issue(s).

**Comment by markus2330** [comment]
@mpranj and it would also be interesting why the performance degraded so strongly after #622, that should be fixed, too.

**Comment by mpranj** [comment]
Quick update: it might take a while because I have to read up on the implementation details. The `elektraGetDoUpdateWithGlobalHooks` isn't straightforward to me and the approach isn't really documented, so I'm not sure how it _should_ work.

@markus2330 on a side note, I also can't reproduce the initial problem, which makes it a bit harder to try any fixes.

**Comment by markus2330** [comment]
Thanks for the update. Did you find out why it slowed down by a factor of 3?

**Comment by mpranj** [comment]
Didn't look into that yet, but I can look into that this evening. Maybe it helps me understand the global hooks as it's the same code anyway.
