### ISSUE TITLE
ini: moving section fails

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#626]
Given the ini file:
```
$ cat profile.ini
[current]
key = value
```
when we move the `current` section:
```
$ kdb mv -r user/sw/org/myapp/#0/current/ user/sw/org/myapp/#0/default
```

we do not get:
```
$ cat profile.ini
[default]
key = value
$ kdb get user/sw/org/myapp/#0/default/key
value
```
but we get:

```
$ cat profile.ini
[default]
[current]
default/key = value
$ kdb get user/sw/org/myapp/#0/default/key
Did not find key
```

**Comment by tom-wa** [comment]
this issue is fixed in the revised version in #599 . i've forgot about kdb mv though, will add a few testcases.

**Comment by tom-wa** [comment]
fixed in the last PR. can be closed now

**Comment by markus2330** [comment]
Thank you, but there is a problem with debian packaging, and I would like to test it with an installed version.

**Comment by markus2330** [comment]
Works now perfectly, thank you!
