### ISSUE TITLE
ini: no = in value

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#646]
```
$ head machinekit.ini
[PRUCONF]
DRIVER=hal_pru_generic
CONFIG=pru=0 num_stepgens=5 num_pwmgens=0
PRUBIN=xenomai/pru_generic.bin
$ kdb set system/machinekit/cnc/pruconf/driver some_other
head machinekit.ini
[PRUCONF]
DRIVER = some_other
"CONFIG=PRU=0 NUM_STEPGENS=5 NUM_PWMGENS=0"
PRUBIN = xenomai/pru_generic.bin
```

expected: leave `CONFIG` unchanged (and `PRU=0 NUM_STEPGENS=5 NUM_PWMGENS=0` should be its value)

(Please only fix for 0.8.16 if you are sure it won't break something else)

**Comment by tom-wa** [comment]
Oh, yeah, if there are multiple "=" in a line, the ini plugin tries to search for " = " in order to find the right delimiter because the "=" could belong both to the name, or the value otherwise. if you add a space in front an after the "=" it would work, or if you do `CONFIG="PRU=0 NUM_STEPGENS=5 NUM_PWMGENS=0"`

**Comment by tom-wa** [comment]
changing it wouldn't break anything, but thats actually a scenario where you should switch the delimiter to something else like `:`. there's no good approach to find out which "=" is actually the delimiter

**Comment by markus2330** [comment]
Thanks for the explanation, can you please add it to README.md?

(This would also close the issue unless @strahlex has objections)

**Comment by tom-wa** [comment]
i don't really want to implement a workaround for that case because, even though there isn't a real ini standard, this definitely isn't. if that's ok with everyone.

**Comment by markus2330** [comment]
Yes, I already said from my point no workaround is needed. The problem was only the missing documentation. It must only be clear to the user which = will be part of the key and which will be part of the value.
