### ISSUE TITLE
tcl plugin: Boost headers not included

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#648]
I get
```
libelektra/src/plugins/tcl/tcl.cpp:18:10: fatal error: 'boost/spirit/include/qi_expect.hpp' file not found
#include <boost/spirit/include/qi_expect.hpp>
         ^
```
on OS X 10.11.4 as well as FreeBSD 10.3-RELEASE.

**Comment by markus2330** [comment]
You need to download the files from http://www.boost.org/

Strange that cmake could find the cmake package? (It does not specifically check for `boost/spirit/include/qi_expect.hpp`, but usually the header files are all in one package and libraries are not needed for the `tcl` plugin).

**Comment by markus2330** [comment]
The PR #649 looked so innocent but broke the mingw build. The problem is that the include_directories is in global scale (for all plugins). On Linux /usr/include was added in the search path, which is not a good idea for a mingw build.

**Comment by mpranj** [comment]
Sorry for the breakage and thanks for fixing it!
