### ISSUE TITLE
OpenBSD: testmod_conditionals fails

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#651]
2/104 Test   #2: testmod_conditionals ...............***Failed    0.02 sec
	CONDITIONALS     TESTS
	==================

	/root/Projekte/libelektra/src/plugins/conditionals/testmod_conditionals.c:28: error in test_ifthenelseint: error
	/root/Projekte/libelektra/src/plugins/conditionals/testmod_conditionals.c:76: error in test_ifthengtint: error
	/root/Projekte/libelektra/src/plugins/conditionals/testmod_conditionals.c:93: error in test_ifthenkey: error
	/root/Projekte/libelektra/src/plugins/conditionals/testmod_conditionals.c:111: error in test_emptyisempty: error
	/root/Projekte/libelektra/src/plugins/conditionals/testmod_conditionals.c:129: error in test_notempty: error
	/root/Projekte/libelektra/src/plugins/conditionals/testmod_conditionals.c:199: error in test_assignElse: error setting then value
	/root/Projekte/libelektra/src/plugins/conditionals/testmod_conditionals.c:235: error in test_assignKeyElse: error setting then value

	testmod_conditionals RESULTS: 90 test(s) done. 7 error(s).

**Comment by mpranj** [comment]
Fails the same way on FreeBSD 10.3, clang versions:
- (**default**) FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
- clang version 3.7.1 (tags/RELEASE_371/final)

**Comment by markus2330** [comment]
Thanks for reporting. The error messages could be better, too.

**Comment by markus2330** [comment]
Will be solved together with other improvements in conditionals.
