### ISSUE TITLE
OpenBSD: testmod_ini fails

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#652]
13/104 Test  #13: testmod_ini ........................***Failed    0.02 sec
	INI	   TESTS
	==================

	Compare <[section1]
	>, with <section1/key1 = value1
	>
	in file /root/Projekte/libelektra/src/plugins/ini/ini/plainini, line 2.
	/root/Projekte/libelektra/tests/cframework/tests.c:174: error in compare_line_files: comparing lines failed
	/root/Projekte/libelektra/src/plugins/ini/testmod_ini.c:78: error in test_plainIniWrite: files do not match as expected
	Compare <[section1]
	>, with <section1/key1 = value1
	>
	in file /root/Projekte/libelektra/src/plugins/ini/ini/emptyval, line 2.
	/root/Projekte/libelektra/tests/cframework/tests.c:174: error in compare_line_files: comparing lines failed
	/root/Projekte/libelektra/src/plugins/ini/testmod_ini.c:106: error in test_plainIniEmptyWrite: files do not match as expected
	Compare <key1 = value1
	>, with <[section1]
	>
	in file /root/Projekte/libelektra/src/plugins/ini/ini/sectionini, line 5.
	/root/Projekte/libelektra/tests/cframework/tests.c:174: error in compare_line_files: comparing lines failed
	/root/Projekte/libelektra/src/plugins/ini/testmod_ini.c:347: error in test_sectionWrite: files do not match as expected
	Compare <[section1]
	>, with <section1/key1 = val1
	>
	in file /root/Projekte/libelektra/src/plugins/ini/ini/sectionmerge.output, line 1.
	/root/Projekte/libelektra/tests/cframework/tests.c:174: error in compare_line_files: comparing lines failed
	/root/Projekte/libelektra/src/plugins/ini/testmod_ini.c:386: error in test_sectionMerge: files do not match as expected
	Compare <[Section1]
	>, with <Section1/testkey0 = testval0
	>
	in file /root/Projekte/libelektra/src/plugins/ini/ini/insertTest.output.ini, line 1.
	/root/Projekte/libelektra/tests/cframework/tests.c:174: error in compare_line_files: comparing lines failed
	/root/Projekte/libelektra/src/plugins/ini/testmod_ini.c:444: error in test_insertOrder: files do not match as expected
	Compare <array = 0
	>, with <array = 2
	>
	in file /root/Projekte/libelektra/src/plugins/ini/ini/arrayInsertOut.ini, line 4.
	/root/Projekte/libelektra/tests/cframework/tests.c:174: error in compare_line_files: comparing lines failed
	/root/Projekte/libelektra/src/plugins/ini/testmod_ini.c:492: error in test_arrayInsert: files do not match as expected

	test_ini RESULTS: 191 test(s) done. 12 error(s).

**Comment by markus2330** [comment]
Seems to be the same as on Mac OS X #645

**Comment by mpranj** [comment]
I think this should be already fixed as of d18fe57bb55aa26ca2e1451610b9b39da86017de

**Comment by markus2330** [comment]
Can someone recheck on OpenBSD? A build job would be great ;)

**Comment by petermax2** [comment]
Confirmed! 7cad757d7c63419128135c6a85c92377a1331360 passes!

	# bin/testmod_ini                                                                                                  
	INI         TESTS
	==================


	test_ini RESULTS: 185 test(s) done. 0 error(s).
