### ISSUE TITLE
OpenBSD: testmod_mathcheck fails

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#653]
19/104 Test  #19: testmod_mathcheck ..................***Failed    0.01 sec
	elektraFtoA: val: 1.5, ret: 1.5
	elektraEFtoF: string: 1.5, ret: 1.5
	MATHCHECK	   TESTS
	==================

	/root/Projekte/libelektra/src/plugins/mathcheck/testmod_mathcheck.c:73: error in main: error
	/root/Projekte/libelektra/src/plugins/mathcheck/testmod_mathcheck.c:77: error in main: error
	/root/Projekte/libelektra/src/plugins/mathcheck/testmod_mathcheck.c:81: error in main: error
	/root/Projekte/libelektra/src/plugins/mathcheck/testmod_mathcheck.c:84: error in main: error
	/root/Projekte/libelektra/src/plugins/mathcheck/testmod_mathcheck.c:87: error in main: error

	testmod_mathcheck RESULTS: 60 test(s) done. 5 error(s).

**Comment by markus2330** [comment]
@tom-wa Nr. 3, so its definitely not an `icc` bug.

**Comment by markus2330** [comment]
@tom-wa should we exclude it for 0.8.16? (tag as experimental?)

**Comment by markus2330** [comment]
Also happened again on debian: http://community.markus-raab.org:8080/job/elektra-multiconfig-gcc-unstable/build_type=Debug,gcc_version=5,plugins=ALL/68/console

There are also
```
Memory checking results:
Uninitialized Memory Conditional - 79
Uninitialized Memory Read - 71
```
which is a clear indiciation of the underlying issues. Did you try to run valgrind on gcc5 debug?

**Comment by tom-wa** [comment]
yeah, please tag it as experimental, the plugin will get some rework anyway together with spec and conditionals for the next release (new syntax for relative and absolute keys + some cleanup and refactoring because it became quite messy after adding some of the newer features)

**Comment by tom-wa** [comment]
just ran it with valgrind gcc5 and debug build, no isses or memleaks. can you try to reproduce some of the issues locally on your boxes ?

**Comment by markus2330** [comment]
I think openbsd is the easiest way to reproduce it. On debian unstable it is non-deterministic.

**Comment by petermax2** [comment]
It also happens on Fedora.

	MATHCHECK	   TESTS
	==================

	src/plugins/mathcheck/testmod_mathcheck.c:73: error in main: error
	src/plugins/mathcheck/testmod_mathcheck.c:77: error in main: error
	src/plugins/mathcheck/testmod_mathcheck.c:81: error in main: error
	src/plugins/mathcheck/testmod_mathcheck.c:84: error in main: error
	src/plugins/mathcheck/testmod_mathcheck.c:87: error in main: error

	testmod_mathcheck RESULTS: 60 test(s) done. 5 error(s).
	elektraFtoA: val: 1,5, ret: 1.5
	elektraEFtoF: string: 1.5, ret: 1,5

**Comment by markus2330** [comment]
Thanks for reporting!

**Comment by markus2330** [comment]
Will be solved later with other improvements in mathcheck.

**Comment by markus2330** [comment]
As discussed, check if its works with compilation variants for other data types (float, int, unsigned int, maybe even fixed point). If it works, its a floating point related problem.
