### ISSUE TITLE
OpenBSD: testscr_check_get_set fails

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#656]
64/104 Test  #64: testscr_check_get_set ..............***Failed    5.50 sec

	ELEKTRA BASIC COMMAND SCRIPTS TESTS

	Check if script tests the correct version
	ccode not a read-write storage
	conditionals not a read-write storage
	constants not a read-write storage
	counter not a read-write storage
	csvstorage not a read-write storage
	curlget not a read-write storage
	dpkg not a read-write storage

	-- Testing dump
	find: -quit: unknown option
	find: -quit: unknown option
	testing ls command
	testing rm command
	Did not find keyDid not find keytesting array
	/root/Projekte/libelektra/build/tests/shell/testscr_check_get_set.sh: seq: not found
	testing ls command
	testing rm command
	Did not find keyDid not find keytesting array
	/root/Projekte/libelektra/build/tests/shell/testscr_check_get_set.sh: seq: not found
	enum not a read-write storage
	error not a read-write storage
	filecheck not a read-write storage
	glob not a read-write storage
	hexcode not a read-write storage
	hidden not a read-write storage
	hosts not a read-write storage
	iconv not a read-write storage

	-- Testing ini
	find: -quit: unknown option
	find: -quit: unknown option
	testing ls command
	testing rm command
	Did not find keyDid not find keytesting array
	/root/Projekte/libelektra/build/tests/shell/testscr_check_get_set.sh: seq: not found
	testing ls command
	testing rm command
	Did not find keyDid not find keytesting array
	/root/Projekte/libelektra/build/tests/shell/testscr_check_get_set.sh: seq: not found
	iterate not a read-write storage
	keytometa not a read-write storage
	line not a read-write storage
	lineendings not a read-write storage
	list not a read-write storage
	logchange not a read-write storage
	mathcheck not a read-write storage
	network not a read-write storage

	-- Testing ni
	find: -quit: unknown option
	find: -quit: unknown option
	testing ls command
	testing rm command
	Did not find keyDid not find keytesting array
	/root/Projekte/libelektra/build/tests/shell/testscr_check_get_set.sh: seq: not found
	testing ls command
	testing rm command
	Did not find keyDid not find keytesting array
	/root/Projekte/libelektra/build/tests/shell/testscr_check_get_set.sh: seq: not found
	noresolver not a read-write storage
	null not a read-write storage
	path not a read-write storage
	regexstore not a read-write storage
	rename not a read-write storage
	resolver_fm_hpu_b not a read-write storage
	resolver_fm_b_b not a read-write storage
	resolver_fm_pb_b not a read-write storage
	resolver_fm_hb_b not a read-write storage
	resolver_fm_hp_b not a read-write storage
	resolver_fm_ub_x not a read-write storage
	resolver_fm_xb_x not a read-write storage
	resolver_fm_xp_x not a read-write storage
	resolver_fm_xhp_x not a read-write storage
	resolver_fm_uhb_xb not a read-write storage
	shell not a read-write storage

	-- Testing simpleini
	find: -quit: unknown option
	find: -quit: unknown option
	error: could not get root
	error: could not shell get root
	The command set failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: user/tests/script
	Configfile: /root/.config/test.simpleini

	error: could not set value
	error: cant get user/tests/script/value
	error: cant shell get user/tests/script/value
	testing ls command
	error: cant ls user/tests/script (may mean that user/tests/script folder is not clean)
	testing rm command
	The command rm failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: user/tests/script
	Configfile: /root/.config/test.simpleini

	error: could not remove user/test/value
	The command get failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: user/tests/script
	Configfile: /root/.config/test.simpleini

	The command rm failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: user/tests/script
	Configfile: /root/.config/test.simpleini

	error: could not remove user/test/value
	The command get failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: user/tests/script
	Configfile: /root/.config/test.simpleini

	The command set failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: user/tests/script
	Configfile: /root/.config/test.simpleini

	error: could not set user/tests/script/value with other_value
	error: cant get user/tests/script/value (expected other_value)
	The command rm failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: user/tests/script
	Configfile: /root/.config/test.simpleini

	error: could not rm user/tests/script/value (having value other_value)
	testing array
	The command set failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: user/tests/script
	Configfile: /root/.config/test.simpleini

	error: could not set key user/tests/script/hello/a/key
	The command get failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: user/tests/script
	Configfile: /root/.config/test.simpleini

	error: user/tests/script/hello/a/key is not value
	/root/Projekte/libelektra/build/tests/shell/testscr_check_get_set.sh: seq: not found
	The command rm failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: user/tests/script
	Configfile: /root/.config/test.simpleini

	error: could not remove all keys
	error: user file was not removed
	error: could not get root
	error: could not shell get root
	The command set failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: system/tests/script
	Configfile: /etc/kdb/test.simpleini

	error: could not set value
	error: cant get system/tests/script/value
	error: cant shell get system/tests/script/value
	testing ls command
	error: cant ls system/tests/script (may mean that system/tests/script folder is not clean)
	testing rm command
	The command rm failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: system/tests/script
	Configfile: /etc/kdb/test.simpleini

	error: could not remove user/test/value
	The command get failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: system/tests/script
	Configfile: /etc/kdb/test.simpleini

	The command rm failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: system/tests/script
	Configfile: /etc/kdb/test.simpleini

	error: could not remove user/test/value
	The command get failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: system/tests/script
	Configfile: /etc/kdb/test.simpleini

	The command set failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: system/tests/script
	Configfile: /etc/kdb/test.simpleini

	error: could not set system/tests/script/value with other_value
	error: cant get system/tests/script/value (expected other_value)
	The command rm failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: system/tests/script
	Configfile: /etc/kdb/test.simpleini

	error: could not rm system/tests/script/value (having value other_value)
	testing array
	The command set failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: system/tests/script
	Configfile: /etc/kdb/test.simpleini

	error: could not set key system/tests/script/hello/a/key
	The command get failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: system/tests/script
	Configfile: /etc/kdb/test.simpleini

	error: system/tests/script/hello/a/key is not value
	/root/Projekte/libelektra/build/tests/shell/testscr_check_get_set.sh: seq: not found
	The command rm failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: system/tests/script
	Configfile: /etc/kdb/test.simpleini

	error: could not remove all keys
	error: user file was not removed
	error: system file was not removed
	spec not a read-write storage
	struct not a read-write storage
	sync not a read-write storage
	syslog not a read-write storage
	timeofday not a read-write storage
	tracer not a read-write storage
	type not a read-write storage
	uname not a read-write storage
	validation not a read-write storage
	wresolver not a read-write storage

	-- Testing xmltool
	find: -quit: unknown option
	find: -quit: unknown option
	testing ls command
	testing rm command
	Did not find keyDid not find keytesting array
	/root/Projekte/libelektra/build/tests/shell/testscr_check_get_set.sh: seq: not found
	testing ls command
	testing rm command
	Did not find keyDid not find keytesting array
	/root/Projekte/libelektra/build/tests/shell/testscr_check_get_set.sh: seq: not found
	profile not a read-write storage
	testscr_check_get_set.sh RESULTS: 252 test(s) done 31 error(s).

**Comment by markus2330** [comment]
There is no `seq` on OpenBSD? Isn't it possible to install it?

**Comment by petermax2** [comment]
It is possible. One has to install `coreutils` and the symlink `gseq` to `seq`

    pkg_add coreutils
    ln -s /usr/local/bin/gseq /usr/local/bin/seq

But the test still fails:

	 64/104 Test  #64: testscr_check_get_set ..............***Failed    0.27 sec

	ELEKTRA BASIC COMMAND SCRIPTS TESTS

	Check if script tests the correct version
	ccode not a read-write storage
	conditionals not a read-write storage
	constants not a read-write storage
	counter not a read-write storage
	csvstorage not a read-write storage
	curlget not a read-write storage
	dpkg not a read-write storage

	-- Testing dump
	find: -quit: unknown option
	find: -quit: unknown option
	The command mount terminated unsuccessfully with the info:
	Cascading mountpoint /tests/script not possible, because dir mountpoint already exists
	fatal (no cleanup): could not mount test.dump at /tests/script using dump

**Comment by markus2330** [comment]
Thats an influence of the previous test run, you need to umount the left-overs manually. The cleanup procedure was not called in this unexpected event. `-quit` of find seems to be a problem, too. Let us discuss this today, the shellrecorder seems to be a much more robust solution.

**Comment by markus2330** [comment]
There is no more `seq`, please recheck if this is fixed.

**Comment by petermax2** [comment]
Confirmed working `testscr_check_get_set` on OpenBSD 6.0 compiled with clang 3.8 and `sync;dump;resolver_fm_hpu_b;base64` plugin set.

Thank you for fixing!

**Comment by markus2330** [comment]
@petermax2 thanks for confirmation
@mpranj thanks for fixing
