### ISSUE TITLE
OpenBSD: testscr_check_import fails

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#657]
66/104 Test  #66: testscr_check_import ...............***Failed    5.80 sec

	ELEKTRA IMPORT SCRIPTS TESTS

	Check if script tests the correct version
	-- ccode not a read-write storage
	-- conditionals not a read-write storage
	-- constants not a read-write storage
	-- counter not a read-write storage
	-- csvstorage not a read-write storage
	-- curlget not a read-write storage
	-- dpkg not a read-write storage
	-------- dump -----------
	Import with existing root
	Import with empty root
	Import as stream (using cat)
	Import with wrong root (overwrite)
	Create a new key user/tests/side_val with string val
	Import two values
	Import one value (cut two values from previous test case)
	Create a new key user/tests/side_val with string val
	Import one value (cut previous value)
	Set string to wrong_root
	Create a new key user/tests/script/val with string wrong_val
	Create a new key user/tests/side_val with string val
	-- enum not a read-write storage
	-- error not a read-write storage
	-- filecheck not a read-write storage
	-- glob not a read-write storage
	-- hexcode not a read-write storage
	-- hidden not a read-write storage
	-- hosts not a read-write storage
	-- iconv not a read-write storage
	-------- ini -----------
	Import with existing root
	Import with empty root
	Import as stream (using cat)
	Import with wrong root (overwrite)
	Create a new key user/tests/side_val with string val
	Import two values
	Import one value (cut two values from previous test case)
	Create a new key user/tests/side_val with string val
	Import one value (cut previous value)
	Set string to wrong_root
	Create a new key user/tests/script/val with string wrong_val
	Create a new key user/tests/side_val with string val
	-- iterate not a read-write storage
	-- keytometa not a read-write storage
	-- line not a read-write storage
	-- lineendings not a read-write storage
	-- list not a read-write storage
	-- logchange not a read-write storage
	-- mathcheck not a read-write storage
	-- network not a read-write storage
	-------- ni -----------
	Import with existing root
	Import with empty root
	Import as stream (using cat)
	Import with wrong root (overwrite)
	Create a new key user/tests/side_val with string val
	Import two values
	Import one value (cut two values from previous test case)
	Create a new key user/tests/side_val with string val
	Import one value (cut previous value)
	Set string to wrong_root
	Create a new key user/tests/script/val with string wrong_val
	Create a new key user/tests/side_val with string val
	-- noresolver not a read-write storage
	-- null not a read-write storage
	-- path not a read-write storage
	-- regexstore not a read-write storage
	-- rename not a read-write storage
	-- resolver_fm_hpu_b not a read-write storage
	-- resolver_fm_b_b not a read-write storage
	-- resolver_fm_pb_b not a read-write storage
	-- resolver_fm_hb_b not a read-write storage
	-- resolver_fm_hp_b not a read-write storage
	-- resolver_fm_ub_x not a read-write storage
	-- resolver_fm_xb_x not a read-write storage
	-- resolver_fm_xp_x not a read-write storage
	-- resolver_fm_xhp_x not a read-write storage
	-- resolver_fm_uhb_xb not a read-write storage
	-- shell not a read-write storage
	-------- simpleini -----------
	Import with existing root
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: user/tests/script
	Configfile: /dev/stdin
	error: key name not correct one_value
	Did not find keyerror: root value not correct
	1d0
	< user/tests/script = root
	error: Export file one_value.simpleini was not equal
	Did not find any key
	error: Could not remove root
	Import with empty root
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: user/tests/script
	Configfile: /dev/stdin
	error: key name not correct one_value empty root
	Did not find keyerror: root value not correct
	1d0
	< user/tests/script = root
	error: Export file one_value.simpleini was not equal
	Did not find any key
	error: Could not remove root
	Import as stream (using cat)
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: user/tests/script
	Configfile: /dev/stdin
	error: key name not correct one_value empty root
	Did not find keyerror: root value not correct
	1d0
	< user/tests/script = root
	error: Export file one_value.simpleini was not equal
	Did not find any key
	error: Could not remove root
	Import with wrong root (overwrite)
	Create a new key user/tests/side_val with string val
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: user/tests/script
	Configfile: /dev/stdin
	1 conflicts were detected that could not be resolved automatically:
	user/tests/script
	ours: CONFLICT_SAME, theirs: CONFLICT_DELETE

	Merge unsuccessful.
	error: Could not run kdb import
	error: root value not correct
	1c1
	< user/tests/script = root
	---
	> user/tests/script = wrong_root
	error: Export file one_value.simpleini was not equal
	Import two values
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: user/tests/script
	Configfile: /dev/stdin
	error: key name not correct
	Did not find keyerror: root value not correct
	Did not find keyerror: key value not correct
	1,2d0
	< user/tests/script = root
	< user/tests/script/key = value
	error: Export file two_value.simpleini was not equal
	Import one value (cut two values from previous test case)
	Create a new key user/tests/side_val with string val
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: user/tests/script
	Configfile: /dev/stdin
	error: key name not correct
	Did not find keyerror: root value not correct
	1d0
	< user/tests/script = root
	error: Export file one_value.simpleini was not equal
	Import one value (cut previous value)
	Create a new key user/tests/script with string wrong_root
	Create a new key user/tests/script/val with string wrong_val
	Create a new key user/tests/side_val with string val
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: user/tests/script
	Configfile: /dev/stdin
	error: key name not correct
	Did not find keyerror: root value not correct
	1d0
	< user/tests/script = root
	error: Export file one_value.simpleini was not equal
	Did not find any key
	error: Could not remove user/tests/script
	-- spec not a read-write storage
	-- struct not a read-write storage
	-- sync not a read-write storage
	-- syslog not a read-write storage
	-- timeofday not a read-write storage
	-- tracer not a read-write storage
	-- type not a read-write storage
	-- uname not a read-write storage
	-- validation not a read-write storage
	-- wresolver not a read-write storage
	-------- xmltool -----------
	Import with existing root
	Import with empty root
	Import as stream (using cat)
	Import with wrong root (overwrite)
	Create a new key user/tests/side_val with string val
	Import two values
	Import one value (cut two values from previous test case)
	Create a new key user/tests/side_val with string val
	Import one value (cut previous value)
	Set string to wrong_root
	Create a new key user/tests/script/val with string wrong_val
	Create a new key user/tests/side_val with string val
	-- profile not a read-write storage
	testscr_check_import.sh RESULTS: 279 test(s) done 26 error(s).

**Comment by markus2330** [comment]
Strange that simpleini fails, isn't it also a glibc system?

**Comment by nd2s** [comment]
glibc = GNU; OpenBSD has nothing to do with GNU and uses the BSD libc.

**Comment by markus2330** [comment]
Yes, I know now. I thought initially that it was even required to have glibc so that Elektra works on OpenBSD, but now its clear: you only need to install gcc, not glibc.

@nd2s 03fb2c770eb2c4eda4d380b76b2f54bd3febefe8 should disable the simpleini plugin and fix the test (and maybe even others), can you verify that?

**Comment by nd2s** [comment]
@markus2330 If you tell me how...

**Comment by markus2330** [comment]
git pull && make && make run_all

**Comment by nd2s** [comment]
I copied the whole output because there is a lot going on (22 tests failing!). This one seems to be ok, though:

https://gist.github.com/nd2s/49e281d3b9e3fc24557e06a3ef733a8a

**Comment by markus2330** [comment]
@nd2s In your case most tests fail because Elektra tries to write to /etc/kdb. Either give access to it for your development user or run as root.

**Comment by nd2s** [comment]
Certainly not giving it root access. ;) Shouldn't it write to a tmp dir?

Anyway, down to 12 failed: https://gist.github.com/nd2s/b4a6b0899914230040a501bb8a24258b

**Comment by markus2330** [comment]
No, the tests are realistic. To have good default security, all `system` keys go to `/etc` which cannot be manipulated via environment. Thus `kdb mount` writes to `system`, the tests write to `/etc`. You can configure Elektra to be more insecure at compiletime if you want (XDG resolver allow to manipulate `system` configuration per environment variable) or simply set default pathes to what suits you best.

**Comment by markus2330** [comment]
Simpleini should now be excluded on openbsd, please recheck if this problem is still present.

**Comment by petermax2** [comment]
Confirmed working `testscr_check_import` on OpenBSD 6.0 compiled with clang 3.8 and `sync;dump;resolver_fm_hpu_b;base64;simpleini` plugin set.

The exclusion is working. Thank you!

**Comment by markus2330** [comment]
Mercy! We are closing really a lot of issues tonight ;)
