### ISSUE TITLE
OpenBSD: testscr_check_real_world fails

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#658]
71/104 Test  #71: testscr_check_real_world ...........***Failed    2.37 sec

	ELEKTRA CHECK REAL WORLD SUITE

	Check if script tests the correct version
	find: -quit: unknown option
	find: -quit: unknown option
	system/test/script/sys/uname/machine
	system/test/script/sys/uname/nodename
	system/test/script/sys/uname/release
	system/test/script/sys/uname/sysname
	system/test/script/sys/uname/version
	amd64
	test_real_world_root.ecf on /test/script with name /test/script
	test_real_world_sys.ni on /test/script/sys with name /test/script/sys
	test_real_world_hosts on /test/script/sys/hosts with name /test/script/sys/hosts
	test_real_world_apps.ini on /test/script/apps with name /test/script/apps
	error: cant get system/test/script/apps/next/x (expected y)
	The command rm failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: system/test/script/apps
	Configfile: /etc/kdb/test_real_world_apps.ini

	error: could not rm system/test/script/apps/next/x (having value y)
	error: cant get user/test/script/apps/next/x (expected y)
	The command rm failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: user/test/script/apps
	Configfile: /root/.config/test_real_world_apps.ini

	error: could not rm user/test/script/apps/next/x (having value y)
	The command set failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: user/test/script/apps
	Configfile: /root/.config/test_real_world_apps.ini

	error: could not set user/test/script/apps/next/x/x/y with 127.0.0.1
	error: cant get user/test/script/apps/next/x/x/y (expected 127.0.0.1)
	The command mv failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: user/test/script/apps
	Configfile: /root/.config/test_real_world_apps.ini

	error: could not mv user/test/script/apps/next/x/x/y to system/test/script/sys/hosts/ipv4/localhost
	error: cant get system/test/script/sys/hosts/ipv4/localhost (expected 127.0.0.1)
	Did not find the key
	error: could not rm system/test/script/sys/hosts/ipv4/localhost (having value 127.0.0.1)
	The command set failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: system/test/script/apps
	Configfile: /etc/kdb/test_real_world_apps.ini

	error: could not set system/test/script/apps/next/x/a/b with y
	error: cant get system/test/script/apps/next/x/a/b (expected y)
	The command rm failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: system/test/script/apps
	Configfile: /etc/kdb/test_real_world_apps.ini

	error: could not rm system/test/script/apps/next/x/a/b (having value y)
	The command set failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: user/test/script/apps
	Configfile: /root/.config/test_real_world_apps.ini

	error: could not set user/test/script/apps/next/x/x/y with y
	error: cant get user/test/script/apps/next/x/x/y (expected y)
	The command rm failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: user/test/script/apps
	Configfile: /root/.config/test_real_world_apps.ini

	error: could not rm user/test/script/apps/next/x/x/y (having value y)
	test_real_world_hosts on /test/script/sys/hosts with name /test/script/sys/hosts
	testscr_check_real_world.sh RESULTS: 102 test(s) done 15 error(s).

**Comment by markus2330** [comment]
Should also be fixed now.

**Comment by petermax2** [comment]
Confirmed working `testscr_check_real_world` on OpenBSD 6.0 compiled with clang 3.8 and `sync;dump;resolver_fm_hpu_b;base64` plugin set.

Thank you for fixing!
