### ISSUE TITLE
OpenBSD: testscr_check_kdb_internal_suite fails

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#659]
69/104 Test  #69: testscr_check_kdb_internal_suite ...***Failed    7.14 sec

	ELEKTRA KDB INTERNAL TEST SUITE

	Check if script tests the correct version
	ccode not a read-write storage
	conditionals not a read-write storage
	constants not a read-write storage
	counter not a read-write storage
	csvstorage not a read-write storage
	curlget not a read-write storage
	dpkg not a read-write storage
	find: -quit: unknown option
	find: -quit: unknown option
	Running tests for dump
	Doing basic tests
	Doing string tests
	Doing umlauts tests
	Doing binary tests
	Doing naming tests
	We got 0 errors in 1839 testcases.
	Test suite is now finished.
	Now restoring the original keyset.
	Doing basic tests
	Doing string tests
	Doing umlauts tests
	Doing binary tests
	Doing naming tests
	We got 0 errors in 1839 testcases.
	Test suite is now finished.
	Now restoring the original keyset.
	Cleanup for dump
	enum not a read-write storage
	error not a read-write storage
	filecheck not a read-write storage
	glob not a read-write storage
	hexcode not a read-write storage
	hidden not a read-write storage
	hosts not a read-write storage
	iconv not a read-write storage
	find: -quit: unknown option
	find: -quit: unknown option
	Running tests for ini
	Doing basic tests
	Doing string tests
	Doing umlauts tests
	Doing naming tests
	We got 0 errors in 1053 testcases.
	Test suite is now finished.
	Now restoring the original keyset.
	Doing basic tests
	Doing string tests
	Doing umlauts tests
	Doing naming tests
	We got 0 errors in 1053 testcases.
	Test suite is now finished.
	Now restoring the original keyset.
	Cleanup for ini
	iterate not a read-write storage
	keytometa not a read-write storage
	line not a read-write storage
	lineendings not a read-write storage
	list not a read-write storage
	logchange not a read-write storage
	mathcheck not a read-write storage
	network not a read-write storage
	find: -quit: unknown option
	find: -quit: unknown option
	Running tests for ni
	Doing basic tests
	Doing string tests
	We got 0 errors in 9 testcases.
	Test suite is now finished.
	Now restoring the original keyset.
	Doing basic tests
	Doing string tests
	We got 0 errors in 9 testcases.
	Test suite is now finished.
	Now restoring the original keyset.
	Cleanup for ni
	noresolver not a read-write storage
	null not a read-write storage
	path not a read-write storage
	regexstore not a read-write storage
	rename not a read-write storage
	resolver_fm_hpu_b not a read-write storage
	resolver_fm_b_b not a read-write storage
	resolver_fm_pb_b not a read-write storage
	resolver_fm_hb_b not a read-write storage
	resolver_fm_hp_b not a read-write storage
	resolver_fm_ub_x not a read-write storage
	resolver_fm_xb_x not a read-write storage
	resolver_fm_xp_x not a read-write storage
	resolver_fm_xhp_x not a read-write storage
	resolver_fm_uhb_xb not a read-write storage
	shell not a read-write storage
	find: -quit: unknown option
	find: -quit: unknown option
	Running tests for simpleini
	Doing basic tests
	The command test failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: user/tests/script
	Configfile: /root/.config/test.simpleini

	error: could not run test suite
	Doing basic tests
	The command test failed while accessing the key database with the info:
	Error (#60) occurred!
	Description: Invalid Line encountered
	Ingroup: plugin
	Module: simpleini
	At: /root/Projekte/libelektra/src/plugins/simpleini/simpleini.c:89
	Reason: not at the end of file
	Mountpoint: system/tests/script
	Configfile: /etc/kdb/test.simpleini

	error: could not run test suite
	Cleanup for simpleini
	spec not a read-write storage
	struct not a read-write storage
	sync not a read-write storage
	syslog not a read-write storage
	timeofday not a read-write storage
	tracer not a read-write storage
	type not a read-write storage
	uname not a read-write storage
	validation not a read-write storage
	wresolver not a read-write storage
	find: -quit: unknown option
	find: -quit: unknown option
	Running tests for xmltool
	Doing basic tests
	Doing string tests
	We got 0 errors in 9 testcases.
	Test suite is now finished.
	Now restoring the original keyset.
	Doing basic tests
	Doing string tests
	We got 0 errors in 9 testcases.
	Test suite is now finished.
	Now restoring the original keyset.
	Cleanup for xmltool
	profile not a read-write storage
	testscr_check_kdb_internal_suite.sh RESULTS: 42 test(s) done 2 error(s).

**Comment by markus2330** [comment]
Should also be fixed now.

**Comment by petermax2** [comment]
Confirmed working `testscr_check_kdb_internal_suite` on OpenBSD 6.0 compiled with clang 3.8 and `sync;dump;resolver_fm_hpu_b;base64;simpleini` plugin set.

Problem solved. Thank you!
