### ISSUE TITLE
Fix build warnings

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#668]
- [ ] unused variable f (gcc)
- [ ] hash non-template (gcc)

**Comment by mpranj** [comment]
seems like an empty duplicate of #681, close?

**Comment by markus2330** [comment]
Thanks for alerting me, I changed it to another issue in this context.

**Comment by markus2330** [comment]
You are right, its better to close this issue. The vague description is not beginner friendly.
