### ISSUE TITLE
spec: metadata is not cleaned up

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#670]
The spec is positioned at `postgetstorage presetstorage`. Are you sure we should change that positioning for this release?

What is not working because of the missing positioning?

**Comment by tom-wa** [comment]
it should work without those placements, it just wont clean up.

**Comment by markus2330** [comment]
With cleanup you mean removal of meta data?

**Comment by tom-wa** [comment]
yes.

**Comment by markus2330** [comment]
Ok, thank you. Lets better keep it the way as is for the current release and in next release @KurtMi  and you rethink the global plugin positioning.

**Comment by markus2330** [comment]
For me "1.0.0" was only for major goals, for the actual realization I used the "0.9.*" milestone. So I would have put this issue here to "0.9.*".
