### ISSUE TITLE
topology sort in mounting

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#673]
```
kdb mount --with-recommends hosts /hosts hosts validation
The command mount terminated unsuccessfully with the info:
Ordering Violation!
You tried to add a plugin which requests another plugin to be positioned first.
Please position the other plugin first and try again.
```

Workaround:

```
bin/kdb mount --with-recommends hosts /hosts hosts glob network validation
```

**Comment by tom-wa** [comment]
i don't quite get it, 
```
0:/resolver
1:/sync
2:/hosts
3:/validation
4:/glob
5:/network
```
thats the array returned by the topological sort. where exactly is the issue ?

**Comment by markus2330** [comment]
glob must be before validation+network, otherwise the globbed metakeys won't reach their destination. (ordering is against check, both validation and network are check)

**Comment by tom-wa** [comment]
glob doesn't have any dependencies added in the keyset

**Comment by markus2330** [comment]
ahh, there is a TODO that this is not yet implemented. That clears that up.

**Comment by markus2330** [comment]
Can you look at the TODO in src/libs/tools/src/backendbuilder.cpp

How can you specify dependencies to virtual nodes for elektraSortTopology without conflict with yourself? If you struggle with C++, can you create a testcase in C where such a dependency is specified? (e.g. the "hosts validation" case with the providers as specified in the contracts (README.md))

**Comment by tom-wa** [comment]
not sure if i'm getting this right: plugins having "provide" should be added as dependency to every other plugin ?

**Comment by markus2330** [comment]
That is the question: How can you handle the situation with "virtual dependencies" in  elektraSortTopology? Simply think through above example with mounting "hosts validation".

**Comment by markus2330** [comment]
Does this work well enough for next release? Otherwise simply remove "0.8.19" tag.

**Comment by tom-wa** [comment]
sorry, i still have no idea how to approach this issue
i'm removing the milestone tag
