### ISSUE TITLE
Ninja: Warning About Multiple Rules Generating `kdberrors.h` 

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#674]
## Steps To Reproduce

1. Change directory to the root directory of the cloned repository
2. Execute the following commands:

    ```sh
    mkdir -p build
    cd build
    cmake .. -GNinja -DPLUGINS="dump;resolver;yajl;resolver_fm_hpu_b"
    ninja
    ```

## Result

Ninja prints the following warning multiple times:

```
ninja: warning: multiple rules generate src/include/kdberrors.h. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
```

---

This might be related to the CMake macro `add_headers`, since adding plugins also increases the number of warnings `ninja` prints. ~~If I comment the lines~~
```cmake
add_custom_command (
		OUTPUT ${BINARY_INCLUDE_DIR}/kdberrors.h
		DEPENDS elektra-export-errors
		COMMAND ${EXE_ERR_LOC}
		ARGS ${EXE_ERR_ARG} ${CMAKE_SOURCE_DIR}/src/error/specification ${BINARY_INCLUDE_DIR}/kdberrors.h
		)
```
~~in the macro, then `ninja` does not print the warning messages any more.~~

**Comment by markus2330** [comment]
Thank you for reporting. The issue is well-known, see very long discussion in #258.
