### ISSUE TITLE
create full-automatic shell recorder test cases

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#678]
- [x] update docu for shell recorder
- [x] create more testcases
- [x] should be executed (add_test)
- [x] tag shell test cases different
- [x] complete `sh` compatibility

@KurtMi you you please write down what you learned during the review. I think the docu is still not like it should be.

**Comment by KurtMi** [comment]
@markus2330 I peeked in the shell and shell recorder test suite and I can not find any check if `bash` or `sh` is present. How is the behaviour on systems that do not have a `sh` or `bash`?

**Comment by markus2330** [comment]
For now: simply assume a shell is present. Other unit tests are written in shell too.

The shell recorder itself is written in shell, so a check would not be useful?

The shell recorder should avoid bash dependencies, it should be plain POSIX.

**Comment by KurtMi** [comment]
> The shell recorder itself is written in shell, so a check would not be useful?

I thought a cmake check or so.

> The shell recorder should avoid bash dependencies, it should be plain POSIX.

Well, the shell recorder works with `bash`, I can try to change it to `sh`

**Comment by markus2330** [comment]
> I thought a cmake check or so.

Do you have any system to test it?
It would only be useful if you also disable the other shell tests.
But I think its not worth the effort.

A better solution might be to tag every shell test and shell recorder test, then everyone can easily select the tests he/she wants to run.
(Currently the shell tests are tagged with kdbtests, but later also kdbtests were added that are not implemented in shell. So this tag cannot be used anymore to distinguish between shell and other tests.)

> Well, the shell recorder works with bash, I can try to change it to sh

Yes, that would be useful for some systems.

**Comment by KurtMi** [comment]
> Do you have any system to test it?

No, I thought it would be nice, I can have a look.
If I do not find a proper solution I rearrange the tags.

**Comment by KurtMi** [comment]
@tom-wa can you pls have a short look at the `shell_recorder.sh` if there is a different behaviour with `sh`? I am not so the shell guru :)

**Comment by sirblackheart** [comment]
@KurtMi you can use [checkbashims](https://aur.archlinux.org/packages/checkbashisms/) to check if any bash specific code was used.

**Comment by KurtMi** [comment]
@sirblackheart thx for the hint.

#806 should do `should be executed (add_test)`

For the transformation from `bash` to `sh` I did my best but some points are open,
I also `shellcheck`ed the shell recorder, #807 contains both.

**Comment by markus2330** [comment]
Thanks to @sanssecours we fixed the problems with the shell recorder.
