### ISSUE TITLE
Fix OpenBSD warnings

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#681]
As @nd2s  reported we should fix all OpenBSD warnings.

Afterwards, as discussed we should create an OpenBSD build agent to avoid regressions. If there is someone who can donate an OpenBSD build agent: this would be highly appreciated.

If possible we should also do the same for one of the solaris distributions.

@petermax2 @nd2s You are of course welcome to also contribute fixes for this issue.

**Comment by tom-wa** [comment]
anyone managed to get elektra working on openbsd 5.9 ? egcc and eg++ (+ libs) aren't available on 5.9, and -std=c++ failes

**Comment by nd2s** [comment]
They are, read doc/COMPILE.md.

**Comment by tom-wa** [comment]
thanks, but i still get `Your compiler does no know the flag: -std=c++11` using eg++ on 5.9 
```
# eg++ --version
eg++ (GCC) 4.9.3
```
worked fine for me on 5.8

**Comment by nd2s** [comment]
And you ran that with both the CC/CXX vars as described? `cmake` as well?

**Comment by markus2330** [comment]
Btw. I would recommend `-DCMAKE_C_COMPILER=egcc -DCMAKE_CXX_COMPILER=eg++`. Can you post `CMakeFiles/CMakeError.log` and similar files which show the exact output of the flag detection (check_cxx_compiler_flag)?

Are you sure there is a spelling error in `does no know`? The text in cmake/ElektraCompiling.cmake is different.

Also make sure that you really build from a completely empty build directory.

**Comment by tom-wa** [comment]
thats a typo i made, nexted tmux sessions + clipboards are annoying so i just typed the message instead of copying it. 

works now with -DCMAKE_CXX_COMPILER, thanks

**Comment by markus2330** [comment]
Ok, can you create a PR for `doc/COMPILE.md` with the minimal working cmake commandline?

@nd2s thanks for helping out!
