### ISSUE TITLE
Translation of qt-gui

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#682]
Currently we only have a german translation:
`src/tools/qt-gui/qml/i18n/lang_de_DE.ts`
It would be great to have other languages, too.

**Comment by sirblackheart** [comment]
Probably we should use [zanata](https://translate.zanata.org/) once it [supports](https://zanata.atlassian.net/browse/ZNTA-689) ts files.

**Comment by markus2330** [comment]
Do you think it could attract currently uninvolved people? Then lets go for it ;) 

Otherwise, there are many offline tools for translation tasks.

**Comment by sirblackheart** [comment]
I do not think that it will get more developers directly involved with elektra, but i do think that the barrier of offline translation tools will keep possible translators away. Here comes the question if we assume that a possible translator of the project would do more then translate and get involved in other ways with the project and if we want to keep the offline tool barrier for that reason. On the other hand offering a web interface for simple translation does lower the barrier for people with basic technical skills but good translation skill to translate the application.
Zanata is just one proposal for going that way and it sill does not support ts files yet. [Transifex](https://www.transifex.com/) for example would also be free for open source projects and already would support [qt .ts](http://docs.transifex.com/formats/qt-ts/).

**Comment by markus2330** [comment]
I mean involvement in any way, such as translating it or also using it. If it lowers the barrier, it would be good to have it!

**Comment by markus2330** [comment]
We now have some translations. It is low priority to add more translations.
