### ISSUE TITLE
list: addPlugin and shell recorder tests

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#684]
Extensions for list plugin:
- [ ] export a function that allows to add a further plugin in the list at runtime
- [ ] add shell recorder tests, in specific one that shows how to do a lazy mountpoint

**Comment by markus2330** [comment]
Implementation hints: the exporting of the `addPlugin` should already be a prototype of how the new way of exporting should work.

It should be easy to call an exported function and it should be possible to dynamically detect which functions are exported and which signatures they have.

For the simplification part: I think about something like `elektraModulesGetFunction (elektraPluginFactory, functionName)`

**Comment by markus2330** [comment]
Here it would be important to have a shell recorder test for lazy mountpoints. It would be great help for a kdb implementation to have such a template.

**Comment by tom-wa** [comment]
i'm currently a little bit lost here.

>elektraModulesGetFunction (elektraPluginFactory, functionName)

isn't elektraPluginFactory just a pointer to the Plugin (handle) ? i don't really get how to add them at runtime other than adding a pointer to it to the _Plugin structure 

or can i assume the caller of elektraModulesGetFunction already has the handle and the modules keyset with all loaded modules ?

**Comment by markus2330** [comment]
#828 also tries to export the pointer, but I am not sure if this will work well. The problem is that the plugin mounted below `system/elektra/modules` is a different one than the one actually doing the work.

@waht can simply work around by linking the plugin against the application and remembering his stuff in the `kdb` handle.

In your situation, I think, the problem does not need to be solved, too. When @waht wants to add his plugin to the list plugin (looking into the global plugins), he already has the plugin handle in his hands. So you can take it for granted that someone executing the function has the plugin handle at hand.

If it is unclear, its best we discuss it next time together.

**Comment by markus2330** [comment]
Based on the discussion in #885

@tom-wa writes:
> i'll improve the addPlugin/editPlugin functionality in list (after i'm done with the firefox thingy) to make it a little bit more useable

Yes, it is an interesting thought to use addPlugin/editPlugin functionality also for`kdb global-mount` and not only for `kdbEnsure` (see #868).

But to make addPlugin useful for `kdb global-mount` we would also need a serializer, so given the kdb->globalPlugins, create a KeySet that contains configuration suitable for `system/elektra/globalplugins`.

Btw. the addPlugin/delPlugin functionality is quite complicated, because you would need to read the contract and honor `infos/ordering` and `infos/stacking` (maybe even do a topological sort so that the constraint get fulfilled if addPlugin was executed in the wrong order?).

**Comment by markus2330** [comment]
We will implement a new approach as suggested by Vid.
