### ISSUE TITLE
KDB_DB_SPEC and KDB_DB_SYSTEM with ~ does not work

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#691]
SPEC Expected behaviour: Should resolve to `~/.config/kdb/spec/default.ini`
SPEC Actual behaviour: Resolves to `/usr/local/~/.config/kdb/spec/default.ini`

SYSTEM Expected behaviour: Should resolve to `/home/me/...`
SYSTEM actual behaviour: resolves to `~/...`

KDB_DB_SYSTEM also needs to be STRING, otherwise it is impossible to start string with `~`.

**Comment by markus2330** [comment]
Please update docu in `doc/TESTING.md` see 007169b6a6bf1f16e2c470446bc9946444dc28d6

**Comment by markus2330** [comment]
I think we need to debug the resolver why the default-resolver works differently than mounted resolvers.

**Comment by tom-wa** [comment]
for SPEC there is still an issue with cmake setting CMAKE_INSTALL_PREFIX in src/include/CMakeLists.txt
is there a reason for setting it just for KDB_DB_SPEC ?

**Comment by markus2330** [comment]
Yes, only spec is usually installed on the system (in CMAKE_INSTALL_PREFIX).
I think we need a special cases for `~` pathes to not prefix it with CMAKE_INSTALL_PREFIX.

Did you also found out why it does not work for system-pathes?
