### ISSUE TITLE
openwrt build of 0.8.16

### ISSUE THREAD

**Issue by haraldg** [ElektraInitiative/libelektra#698]
Hi,

I'm configuring elektra with -DPLUGINS="ALL;-crypto_gcrypt" like I did with 0.8.15,
but this time I get an errror. (See below.)

I tried to look at src/plugins/crypto/CMakeLists.txt but the comments confused me. Maybe somebody can make sense of this:

(cd /home/lambda/olinuxino/openwrt/build_dir/target-arm_arm926ej-s_musl-1.1.11_e
abi/elektra-0.8.16; CFLAGS="-Os -pipe -march=armv5te -mtune=arm926ej-s -fno-call
er-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-res
ult -mfloat-abi=soft " CXXFLAGS="-Os -pipe -march=armv5te -mtune=arm926ej-s -fno
-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unuse
d-result -mfloat-abi=soft " LDFLAGS="-L/home/lambda/olinuxino/openwrt/staging_di
r/target-arm_arm926ej-s_musl-1.1.11_eabi/usr/lib -L/home/lambda/olinuxino/openwr
t/staging_dir/target-arm_arm926ej-s_musl-1.1.11_eabi/lib -L/home/lambda/olinuxin
o/openwrt/staging_dir/toolchain-arm_arm926ej-s_gcc-5.2.0_musl-1.1.11_eabi/usr/li
b -L/home/lambda/olinuxino/openwrt/staging_dir/toolchain-arm_arm926ej-s_gcc-5.2.
0_musl-1.1.11_eabi/lib " cmake -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_VERSION=
1 -DCMAKE_SYSTEM_PROCESSOR=arm -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS_RELEAS
E="-DNDEBUG" -DCMAKE_CXX_FLAGS_RELEASE="-DNDEBUG" -DCMAKE_C_COMPILER="/home/lamb
da/olinuxino/openwrt/staging_dir/toolchain-arm_arm926ej-s_gcc-5.2.0_musl-1.1.11_eabi/bin/arm-openwrt-linux-muslgnueabi-gcc" -DCMAKE_C_COMPILER_ARG1="" -DCMAKE_CXX_COMPILER="/home/lambda/olinuxino/openwrt/staging_dir/toolchain-arm_arm926ej-s_gcc-5.2.0_musl-1.1.11_eabi/bin/arm-openwrt-linux-muslgnueabi-g++" -DCMAKE_CXX_COMPILER_ARG1="" -DCMAKE_ASM_COMPILER="/home/lambda/olinuxino/openwrt/staging_dir/toolchain-arm_arm926ej-s_gcc-5.2.0_musl-1.1.11_eabi/bin/arm-openwrt-linux-muslgnueabi-gcc" -DCMAKE_ASM_COMPILER_ARG1="" -DCMAKE_EXE_LINKER_FLAGS:STRING="-L/home/lambda/olinuxino/openwrt/staging_dir/target-arm_arm926ej-s_musl-1.1.11_eabi/usr/lib -L/home/lambda/olinuxino/openwrt/staging_dir/target-arm_arm926ej-s_musl-1.1.11_eabi/lib -L/home/lambda/olinuxino/openwrt/staging_dir/toolchain-arm_arm926ej-s_gcc-5.2.0_musl-1.1.11_eabi/usr/lib -L/home/lambda/olinuxino/openwrt/staging_dir/toolchain-arm_arm926ej-s_gcc-5.2.0_musl-1.1.11_eabi/lib" -DCMAKE_MODULE_LINKER_FLAGS:STRING="-L/home/lambda/olinuxino/openwrt/staging_dir/target-arm_arm926ej-s_musl-1.1.11_eabi/usr/lib -L/home/lambda/olinuxino/openwrt/staging_dir/target-arm_arm926ej-s_musl-1.1.11_eabi/lib -L/home/lambda/olinuxino/openwrt/staging_dir/toolchain-arm_arm926ej-s_gcc-5.2.0_musl-1.1.11_eabi/usr/lib -L/home/lambda/olinuxino/openwrt/staging_dir/toolchain-arm_arm926ej-s_gcc-5.2.0_musl-1.1.11_eabi/lib -Wl,-Bsymbolic-functions" -DCMAKE_SHARED_LINKER_FLAGS:STRING="-L/home/lambda/olinuxino/openwrt/staging_dir/target-arm_arm926ej-s_musl-1.1.11_eabi/usr/lib -L/home/lambda/olinuxino/openwrt/staging_dir/target-arm_arm926ej-s_musl-1.1.11_eabi/lib -L/home/lambda/olinuxino/openwrt/staging_dir/toolchain-arm_arm926ej-s_gcc-5.2.0_musl-1.1.11_eabi/usr/lib -L/home/lambda/olinuxino/openwrt/staging_dir/toolchain-arm_arm926ej-s_gcc-5.2.0_musl-1.1.11_eabi/lib -Wl,-Bsymbolic-functions" -DCMAKE_AR="/home/lambda/olinuxino/openwrt/staging_dir/toolchain-arm_arm926ej-s_gcc-5.2.0_musl-1.1.11_eabi/bin/arm-openwrt-linux-muslgnueabi-gcc-ar" -DCMAKE_NM="/home/lambda/olinuxino/openwrt/staging_dir/toolchain-arm_arm926ej-s_gcc-5.2.0_musl-1.1.11_eabi/bin/arm-openwrt-linux-muslgnueabi-gcc-nm" -DCMAKE_RANLIB="/home/lambda/olinuxino/openwrt/staging_dir/toolchain-arm_arm926ej-s_gcc-5.2.0_musl-1.1.11_eabi/bin/arm-openwrt-linux-muslgnueabi-gcc-ranlib" -DCMAKE_FIND_ROOT_PATH="/home/lambda/olinuxino/openwrt/staging_dir/target-arm_arm926ej-s_musl-1.1.11_eabi;/home/lambda/olinuxino/openwrt/staging_dir/toolchain-arm_arm926ej-s_gcc-5.2.0_musl-1.1.11_eabi/bin/arm-openwrt-linux-muslgnueabi-gcc-nm" -DCMAKE_RANLIB="/home/lambda/olinuxino/openwrt/staging_dir/toolchain-arm_arm926ej-s_gcc-5.2.0_musl-1.1.11_eabi/bin/arm-openwrt-linux-muslgnueabi-gcc-ranlib" -DCMAKE_FIND_ROOT_PATH="/home/lambda/olinuxino/openwrt/staging_dir/target-arm_arm926ej-s_musl-1.1.11_eabi;/home/lambda/olinuxino/openwrt/staging_dir/toolchain-arm_arm926ej-s_gcc-5.2.0_musl-1.1.11_eabi" -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=BOTH -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_STRIP=: -DCMAKE_INSTALL_PREFIX=/usr -DDL_LIBRARY=/home/lambda/olinuxino/openwrt/staging_dir/target-arm_arm926ej-s_musl-1.1.11_eabi -DCMAKE_PREFIX_PATH=/home/lambda/olinuxino/openwrt/staging_dir/target-arm_arm926ej-s_musl-1.1.11_eabi -DCMAKE_SKIP_RPATH=TRUE -DTARGET_PLUGIN_FOLDER="" -DBUILD_FULL=OFF -DBUILD_STATIC=OFF -DBUILD_DOCUMENTATION=OFF -DFORCE_IN_SOURCE_BUILD=ON -DBUILD_TESTING=OFF -DKDB_DEFAULT_RESOLVER=resolver_fm_pb_b -DKDB_DEFAULT_STORAGE=ini -DPLUGINS="ALL;-crypto_gcrypt" . )
-- GCC detected
-- C flags are -Os -pipe -march=armv5te -mtune=arm926ej-s -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=soft   -std=gnu99  -Wno-deprecated-declarations  -Wno-long-long -pedantic -Wno-variadic-macros -Wall -Wextra -Wno-overlength-strings -Wsign-compare -Wfloat-equal -Wformat-security -Wshadow -Wcomments -Wtrigraphs -Wundef -Wuninitialized -Winit-self -Wmaybe-uninitialized -Wsign-compare -Wfloat-equal -Wformat-security
-- CXX flags are -Os -pipe -march=armv5te -mtune=arm926ej-s -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=soft   -std=c++11  -Wno-deprecated-declarations  -Wold-style-cast -Wstrict-null-sentinel -D_GLIBCXX_USE_NANOSLEEP -Wno-missing-field-initializers -Woverloaded-virtual  -Wsign-promo  -Wno-long-long -pedantic -Wno-variadic-macros -Wall -Wextra -Wno-overlength-strings -Wsign-compare -Wfloat-equal -Wformat-security -Wshadow -Wcomments -Wtrigraphs -Wundef -Wuninitialized -Winit-self -Wmaybe-uninitialized
-- Detected Debian8.4-amd64. Use make package to build packages (DEB).
-- Exclude crypto_gcrypt
-- Exclude Plugin augeas because augeas not found
-- Include Plugin ccode
-- Include Plugin conditionals
-- Include Plugin constants
-- Include Plugin counter
-- Found libgcrypt: -L/home/lambda/olinuxino/openwrt/staging_dir/target-arm_arm926ej-s_musl-1.1.11_eabi/usr/lib -lgcrypt -lgpg-error
CMake Error at cmake/Modules/LibAddPlugin.cmake:108 (message):
  Internally inconsistency, plugin is not there, but was not removed
Call Stack (most recent call first):
  src/plugins/crypto/CMakeLists.txt:95 (add_plugin)

**Comment by markus2330** [comment]
Thank you, there is a bug in plugin inclusion logic for variants.

I would recommend to fully disable the crypto plugin for 0.8.16, using `-DPLUGINS="ALL;-crypto_gcrypt;-crypto_openssl"` (it also causes problems at runtime #675), or even all experimental plugins using `-DPLUGINS=ALL;-EXPERIMENTAL` which is the default now (if no PLUGINS given -- it would additionally exclude doc, jni, semlock, template and iterate).

**Comment by markus2330** [comment]
Your initial PLUGINS commandline should now work again (in master, for 0.8.16 it is unfortunately too late). I also updated the documentation. Thanks for reporting, do not hesitate to reopen if there are any further issues or questions.
