### ISSUE TITLE
C-KeySet persistency

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#702]
Write a plugin that persists the KeySet using the `ksNew` and `keyNew` syntax. It should be possible to include such a configuration file as header file.

For the beginning it is enough if only the writing-direction is supported.

@tom-wa: can you write this plugin?

**Comment by tom-wa** [comment]
sounds fun, i'll do it.

**Comment by markus2330** [comment]
change priority of issue
