### ISSUE TITLE
specifiy with metadata/plugins might depend on other keys in METADATA.ini

### ISSUE THREAD

**Issue by tom-wa** [ElektraInitiative/libelektra#704]
since there's currently no way of knowing if a plugin might depend on other keys (like conditionals/mathchckeck) i think we should add an entry to METADATA.ini

**Comment by markus2330** [comment]
Currently, you can only open every plugin and query for `infos/metadata` (`kdb mount` is doing so). We would need consistency checks if we add this data to METADATA.ini, too.

Alternatively we could generate a METADATA.ini enriched with more information from the plugins.

Which information exactly do you need to know? Only which metadata is provided by which plugin?

**Comment by tom-wa** [comment]
i need to know which plugin/metadata might depend on other keys for dependency resolving (validation tool)

**Comment by markus2330** [comment]
Dependency can be an ambigious term, can you give an example?

I am not aware that we have meta data that needs more than one plugin to work.

**Comment by tom-wa** [comment]
i meant dependencies like in 
```
[powersaving/gps]
assign/condition = (device != 'vehicle') ? ('low') : ('full')

[gps/status]
assign/condition = (powersaving/gps > 'low') ? ('active') : ('inactive')
```
here gps/status' assign/condition depends on powersaving/gps

**Comment by markus2330** [comment]
Ok, so you only want to mark that such dependencies might exist in METADATA.ini.

For example:
```
[assign/condition]
has/dependencies=yes
```

But I think such a depencency should be resolved internally in the plugin (using topological sorting), and no external tool using the plugin should be bothered with it.

**Comment by tom-wa** [comment]
ok, then i'll write a function for it since i'm sure it'll be usefull for other plugins too.
but i'm not sure which library it would add it to because i want to use posix regex as dependency

**Comment by markus2330** [comment]
I think its not ideal to make assumptions on the syntax and how a key name is encoded across different plugins. The topological sorting is already quite highlevel. At the moment it only affects `mathcheck` and `conditionals`, doesn't it?

**Comment by markus2330** [comment]
Btw. there is not one order of processing. It is possible that the required ordered for different plugins contradict each other. Thus its not useful to have one plugin that does the ordering for all other plugins.

**Comment by tom-wa** [comment]
hmm, i guess you are right, i thought having each plugin implement it on its own would lead to a ton of redundant code.

**Comment by markus2330** [comment]
This was rather a question, so I close it. If any issue exists (e.g. inconsistencies between METADATA.ini and metadata declared by plugins), please open a new issue.
