### ISSUE TITLE
[FLOSS] Update Sources where Elektra is mentioned

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#705]
There are some editable sources like wikipedia which have outdated information about Elektra:
- [ ] https://en.wikipedia.org/wiki/Freedesktop.org
- [ ] https://de.wikipedia.org/wiki/Elektra_%28Software%29
- [ ] https://nl.wikipedia.org/wiki/Configuratiebestand
- [ ] https://fr.wikipedia.org/wiki/Elektra_%28registre_linux%29
- [x] https://gitlab.com/elektra-initiative/libelektra
- [x] https://gitorious.org/elektra-initiative/libelektra
- [x] https://www.freedesktop.org/wiki/Software/Elektra/

If you find some editable information somewhere, please mention them here.

At other places we should add information Elektra:

- [x] https://directory.fsf.org/wiki/Main_Page

**Comment by mpranj** [comment]
This repositories should be updated, removed, or link to the correct repository:
- [ ] https://gitlab.com/elektra-initiative/libelektra
- [ ] https://gitorious.org/elektra-initiative/libelektra


Editable media:
- [ ] https://www.freedesktop.org/wiki/Software/Elektra/

**Comment by markus2330** [comment]
I created https://bugs.freedesktop.org/show_bug.cgi?id=98827 to hopefully fix the outdated info at https://www.freedesktop.org/wiki/Software/Elektra/

**Comment by markus2330** [comment]
Thanks to @tanuk I got a wiki account and could change the links + set a redirection page on Freedesktop.org!

**Comment by nastiaulian** [comment]
Will add new entry to https://directory.fsf.org

**Comment by markus2330** [comment]
Thank you, I assigned you the ticket!

**Comment by nastiaulian** [comment]
Will update the list of plugins on https://de.wikipedia.org/wiki/Elektra_%28Software%29

**Comment by markus2330** [comment]
Thank you!

Please also post here the results. (is https://directory.fsf.org done already?)

**Comment by nastiaulian** [comment]
I finished both, waiting for the changes to be approved (currently not visible on Wikipedia). @markus2330 Should I mark them as done already? 
Please also have a look at https://directory.fsf.org/wiki/Elektra.

**Comment by markus2330** [comment]
Looks very nice, thank you for the improvements!

Please also add that it works under Windows and BSD.

user:$USER/ is not supported anymore, please remove.

Otherwise this task is finished.

**Comment by nastiaulian** [comment]
Added Windows and BSD; removed user:$USER/.

**Comment by markus2330** [comment]
Thank you! The wiki site is already visible. Consider the issue as done, I unassigned you.

Btw. user:root/ is also obsolete, I fixed it.

**Comment by JakobWonisch** [comment]
I'm not sure what I am supposed to do with this issue for FLOSS H3, can you maybe point me in the right direction @markus2330 ? Thanks!

**Comment by markus2330** [comment]
This issue does not involve changes in Elektra's repository. Instead it is about changing wikipedia articles: bringing the articles up-to-date, or preferably¹ changing it in a way that it cannot get outdated anytime soon: i.e. only having general information+link, removing information about specific plugins and irrelevant details.

After you did the updates, you make a summary here in which articles you did which changes.

¹ If it is not possible to update it "permanently", e.g. because the changes would be too invasive or are not accepted by wikipedia-admins, please create a new issue which lists which pages need to be updated periodically.

**Comment by markus2330** [comment]
Small correction: it is better if you create a PR (adding the links where Elektra is mentioned) instead of creating an issue. Then other can review this PR like other PRs.

**Comment by stefnotch** [comment]
As far as I can tell, there's almost no outdated information about Elektra that's easily available anymore. I searched for "libelekta" or "libelektra wiki" and "elektra configuration" on Google.

Searching for other things, like "elektra" by itself mostly yields unrelated results.

Regarding Wikipedia, the only thing that will quickly get out of date is the version number on the page https://de.wikipedia.org/wiki/Elektra_%28Software%29

Another relevant page is Wikidata, where I'm not entirely sure how that works or what one would have to do https://www.wikidata.org/wiki/Q1170170

**Comment by kodebach** [comment]
> Another relevant page is Wikidata, where I'm not entirely sure how that works or what one would have to do

Judging by the [history](https://www.wikidata.org/w/index.php?title=Q1170170&action=history), it automatically extracts data from GitHub

**Comment by markus2330** [comment]
> Regarding Wikipedia, the only thing that will quickly get out of date is the version number on the page

So to fix this issue for a longer time, we could include the always-up-to-date data from Wikidata in the Wikipedia articles.

**Comment by stefnotch** [comment]
Okay, after a bit of playing around, it turns out that the Wikipedia article was already set up for that. I just removed the manually entered entries and it automatically started pulling the info from Wikidata

https://de.wikipedia.org/w/index.php?title=Elektra_(Software)&stable=0&redirect=no

**Comment by stefnotch** [comment]
@markus2330 Would it be possible to use this, despite it not being a PR, for FLOSS H2 or H3?

**Comment by markus2330** [comment]
Yes, of course. Simply link to the diffs of what you did on Wikipedia etc.

**Comment by stefnotch** [comment]
https://de.wikipedia.org/w/index.php?title=Elektra_%28Software%29&type=revision&diff=227717175&oldid=218344188

**Comment by markus2330** [comment]
Seems like Wikidata is outdated, in your version (the latest one not yet reviewed) it shows version 0.9.10?

Operating System MacOSX and Windows should be added. Can you also store the other information in Wikidata?

**Comment by stefnotch** [comment]
Yes, I'm not sure how to get the GitHub bot to update that. I think it'll simply take a while until Wikidata automatically pulls the latest info.

I've added the other info and moved more to Wikidata
https://de.wikipedia.org/w/index.php?title=Elektra_(Software)&stable=0&shownotice=1

**Comment by stefnotch** [comment]
> I suppose the issue can be closed once the changes make it through and go live.


The changes made it through, so I can happily close this issues
