### ISSUE TITLE
Review Decision Global Plugins

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#708]
Decision how to realize unlock semantics (hooks that are executed even on unsuccessful kdbGet/kdbSet calls)

1. init/fini
1. Introduce new dimension
  -   always (for locking semantics)
  -  success (usual way)
1. init/deinit
1. lock/unlock (too specific?)
1. constr/deconstr (not better?)
1. constructor/deconstructor (too long?)
1. open/close (confusing with other use)
1. pre/post (too generic, unclear how it differs with before/after)
1. attach/detach (confusing?)

@tom-wa @KurtMi @Namoshek 
Could you please review doc/decisions/global_plugins.md?

I added a proposal how all positions could be named.

@tom-wa would the spec plugin work with these position? Do you see a problem to implement some of these positions?

**Comment by KurtMi** [comment]
/before/init
    /after/deinit

seem to me a no so intuitive, since all other "hooks" are {before,after}/{once,forall}.
But right now I do not have a appropriate name for those hooks in mind.

**Comment by markus2330** [comment]
@KurtMi yes, I am also not very happy with the names, alternatives are:

- init/fini
- lock/unlock (too specific?)
- constr/deconstr (not better?)
- constructor/deconstructor (too long?)
- open/close (confusing with other use)
- pre/post (too generic, unclear how it differs with before/after)
- attach/detach (confusing?)

**Comment by markus2330** [comment]
Alternatively we could add a third dimension which describes when a hook should be executed:

- always (for locking semantics)
- success (usual way)

Then we would have, e.g.

`/before/once/always`

**Comment by Namoshek** [comment]
I don't really think that
    /before/init
    /after/deinit
is confusing. Using `init` and `fini` is even worse, because the information, when exactly the execution takes place, is missing.

Maybe it would be less confusing to use `init/deinit` if we rename `once` to `first/last`. From the current explanation, I cannot really differentiate `init/deinit` from `once`. Is there even a point to differentiate between them?

**Comment by tom-wa** [comment]
using the current placements, would deinit or after be the cleanup placement ? cleanup is a mandatory placement for spec e.g., but deinit sounds kinda odd for the placement
the placements are fine to me. but i'd rather have some more placement-_names_ with strict rules (like init must have the same plugin mounted as deinit, plugins that need cleanup must be mounted after whatever too, etc)

**Comment by tom-wa** [comment]
the rest also seems fine to me, i think we should split kdbGet into 2 different funktions (on with and one without global plugins) ? the way i'm currently doing it is ugly anyway.

**Comment by markus2330** [comment]
Isn't the cleanup position postgetstorage/after/once?

init/fini would be before/after once.

**Comment by tom-wa** [comment]
i'd say cleanup is mandatory and should have a placement name that clearly states that too ?

**Comment by markus2330** [comment]
@mpranj will do it. Duplicating the function should not be necessary, the overhead of these 6 ifs per function should be neglectable.

**Comment by markus2330** [comment]
Its kind of a different approach: name the hooks after what they are used for and not where they are. The current schema only encodes where they are (and the semantics in before/after/once/foreach/always/success)

**Comment by tom-wa** [comment]
i meant, cleanup could be postget/deinit too which makes more sense since it's mandatory

**Comment by tom-wa** [comment]
i'm fine with both as long as the placements exist, i just thought that it might be easier to use/understand from an endusers point of view

**Comment by markus2330** [comment]
Yes, it is easier from endusers point of view *as long as* they use it in exactly the way as we think about it now. But in other cases it would be even more confusing. But if you want you can formulate an alternative proposal. (But it should include all hooks)

Also for all others: Which of the above ways do you like best?

**Comment by tom-wa** [comment]
i haven't really thought that through yet, but internally we could use just before/after and externaly have different names with strict rules tied to it.
a init/deinit would also be translated to a before and a check for a deinit would be force and an error thrown if no deinit is given, a foreach/before translated to multiple befores, etc

**Comment by markus2330** [comment]
@mpranj seems to do a good job here, will close this discussion. Please do not hesitate to open a new issue.
