### ISSUE TITLE
globbing flag

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#709]
The name of globbing flags `flags` is too generic (it should be `glob/flags`), is not documented in `doc/METADATA.ini` and should take arguments by name (otherwise every plugin setting flags needs to include fnmatch.h and convert the number to a string).

As a test if it works, please extend the host validation so that it should fail if noninvolved keys are being changed.

E.g. if you set invalid keys such as:

```
kdb mount --with-recommends /etc/hosts system/hosts hosts
kdb set system/hosts/something abc
kdb set system/hosts/something/else abc
```

They are not rejected but discared silently.

To solve this issue the hosts contract `src/plugins/hosts/contract.h` should be extended to use `trigger/errors` for every key that is not matched by rule `#0` and `#1`. (Which needs globbing with arbitrary path depth, hence not using `FNM_PATHNAME`).

**Comment by markus2330** [comment]
Any progress here?

**Comment by fberlakovich** [comment]
No, not yet. I am away for the weekend, but I can have a look at it next week.

**Comment by markus2330** [comment]
Ok, thank you!

**Comment by fberlakovich** [comment]
I looked over the glob code and I have some questions regarding your proposal.

> The name of globbing flags flags is too generic (it should be glob/flags), is not documented in doc/METADATA.ini

Should be easy.

> should take arguments by name (otherwise every plugin setting flags needs to include fnmatch.h and convert the number to a string).

This is a bit problematic because multiple flags can be combined. I think that can be solved in different ways:

- Allow only a single flag at a time
- Use a list of strings, e.g. ```"path_name, period, leading_dir"``` to combine the flags ```FNM_PATH_NAME```, ```FNM_PERIOD``` and ```FNM_LEADING_DIR```
- Copy the flag name defs to glob.h

Which one do you prefer?

> As a test if it works, please extend the host validation so that it should fail if noninvolved keys are being changed.

Should be doable, but we will need another option in the glob plugin settings to invert the match as glob does not offer exclusion by itself.

**Comment by markus2330** [comment]
Thanks for picking up the task!

> because multiple flags can be combined.

A space separated list should do.

> will need another option in the glob plugin

What about applying some other metadata that marks which keys should fail? The error plugin should be suitable, except that it currently does not yield a good error text (should be a configurable error text, not "from error plugin in kdbSet").

**Comment by fberlakovich** [comment]
> What about applying some other metadata that marks which keys should fail? The error plugin should be suitable, except that it currently does not yield a good error text (should be a configurable error text, not "from error plugin in kdbSet").

error can be used for triggering the error, but how to identify the keys that should receive error metadata. As there is an infinite number of invalid keys and only a finite number of valid keys for the host plugin we would need to do something like "match alls key that do not match <valid host keys glob> and apply an error metadata to it". But fnmatch does not support the "do not match" part. Therefore we will need an extra flag to invert the glob rule.

**Comment by markus2330** [comment]
I was thinking about the predefined order of glob config (the array). So if the error is later than the successful cases most use cases should work. In case of hosts it would be only "ipv4/*" "ipv6/*" (both successful cases) and "*" (all other cases -> error).

Which use case do you have in mind which needs the inverted glob flag? I also see no issue in adding flags which are not directly fnmatch parameters, so you can add the inverted glob, too.

**Comment by fberlakovich** [comment]
> I was thinking about the predefined order of glob config (the array). So if the error is later than the successful cases most use cases should work. In case of hosts it would be only "ipv4/" "ipv6/" (both successful cases) and "*" (all other cases -> error).

Ok, now it makes sense. That is why I asked before implementing it :).

> Which use case do you have in mind which needs the inverted glob flag? I also see no issue in adding flags which are not directly fnmatch parameters, so you can add the inverted glob, too.

I had an error in reasoning while thinking about glob.

**Comment by markus2330** [comment]
I think this is fixed now!

Thanks you!
