### ISSUE TITLE
Support for xdg icon themes in qt-gui

### ISSUE THREAD

**Issue by sirblackheart** [ElektraInitiative/libelektra#720]
So i looked into getting xdg icon theme support into the qt-gui and would like to hear the opinion of the rest of the team in regard of mapping icons that are not straight mappable to the [KDE](https://techbase.kde.org/Projects/Oxygen/namingSpec)/[GNOME](https://developer.gnome.org/icon-naming-spec/)/[XDG](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html) icon theme specifications.

Getting xdg icon theme support into the qt-gui allows people with impaired vision to use a icon set that works better for them. e.g. HighContrast Icon set

The current approach would look first if a theme icon is available, if not it would fallback to the icon shipped with the application.

fallback Icon | icon for | proposed icon name | Breeze | Oxygen Icon | Adwaita Icon | HC Icon | notes
-----------------|------------|-----------------|-------------------|-------------------|----------------|---------|-----
![document-close](https://cloud.githubusercontent.com/assets/1131371/15273874/10a0770c-1aa6-11e6-9311-302b137c243a.png) | deleting key/array | edit-delete | ![edit-delete](https://cloud.githubusercontent.com/assets/1131371/15274973/f8f83bb6-1abf-11e6-9800-dd901f31b14d.png) | ![edit-delete](https://cloud.githubusercontent.com/assets/1131371/15273991/1cb4b7c6-1aa9-11e6-941d-8f40b51ccf86.png) | ![edit-delete](https://cloud.githubusercontent.com/assets/1131371/15274089/57d5b1a0-1aab-11e6-841a-eb35ad4c4a98.png) | ![edit-delete](https://cloud.githubusercontent.com/assets/1131371/15274273/75408a82-1aae-11e6-8bdc-63df8bb75149.png) | original icon document-close is kde specific, edit-delete is part of xdg spec
|| _alternative_ | user-trash | ![user-trash](https://cloud.githubusercontent.com/assets/1131371/15275197/ff416ba0-1ac4-11e6-8ba0-b8cf568e66e1.png) | ![user-trash](https://cloud.githubusercontent.com/assets/1131371/15275201/2388ca12-1ac5-11e6-9ef5-b83e2972d5c5.png) | ![user-trash](https://cloud.githubusercontent.com/assets/1131371/15275212/64e74088-1ac5-11e6-9d35-1cace75ab945.png) | ![user-trash](https://cloud.githubusercontent.com/assets/1131371/15275214/747274dc-1ac5-11e6-91cc-e6775a97b566.png) | 
|| _alternative_ | edit-clear | ![edit-clear](https://cloud.githubusercontent.com/assets/1131371/15275228/c2362614-1ac5-11e6-91b6-f6bcad08e34d.png) | ![edit-clear](https://cloud.githubusercontent.com/assets/1131371/15275233/e264a6f4-1ac5-11e6-96dc-ebbecab3de51.png) | ![edit-clear](https://cloud.githubusercontent.com/assets/1131371/15275235/f18d82e0-1ac5-11e6-8237-353ea1bc5b40.png) | ![edit-clear](https://cloud.githubusercontent.com/assets/1131371/15275236/13bd296a-1ac6-11e6-89ee-1d7a184d7957.png)
![import](https://cloud.githubusercontent.com/assets/1131371/15273894/9c7ddf80-1aa6-11e6-9a24-ab014c30a45b.png) | Import Configuration | document-open | ![document-open](https://cloud.githubusercontent.com/assets/1131371/15274991/5df6535e-1ac0-11e6-8bec-22706c08e38d.png) | ![document-open](https://cloud.githubusercontent.com/assets/1131371/15273994/470d75bc-1aa9-11e6-8562-47ff55eed11a.png) | ![document-open] (https://cloud.githubusercontent.com/assets/1131371/15274093/6881679c-1aab-11e6-8d61-a3338e013da9.png) | ![document-open](https://cloud.githubusercontent.com/assets/1131371/15274282/9b8b7904-1aae-11e6-9f67-f02c1c672402.png) | original icon document-import kde specific, document-open is part of xdg spec
![export](https://cloud.githubusercontent.com/assets/1131371/15273895/a60c8bf0-1aa6-11e6-9b9e-b1dcba0906c8.png) | Export Configuration | document-save | ![document-save](https://cloud.githubusercontent.com/assets/1131371/15275009/cf3d5b2a-1ac0-11e6-87be-70f88c388605.png) | ![document-save](https://cloud.githubusercontent.com/assets/1131371/15273997/551cf402-1aa9-11e6-8b4a-fbfcf552d99e.png) | ![document-save](https://cloud.githubusercontent.com/assets/1131371/15274097/8255d2b6-1aab-11e6-8ab6-d7d8e7887702.png) | ![document-save](https://cloud.githubusercontent.com/assets/1131371/15274291/b7bbb9ae-1aae-11e6-898e-e86f5968ded4.png) | original icon document-export is kde specific, document-save is part of xdg spec
|| _alternative_ | document-save-as | ![document-save-as](https://cloud.githubusercontent.com/assets/1131371/15275014/e7f3da54-1ac0-11e6-89d1-6e85c74593fd.png) | ![document-save-as](https://cloud.githubusercontent.com/assets/1131371/15274522/4e028e24-1ab4-11e6-8d35-e364013220b0.png) | ![document-save-as](https://cloud.githubusercontent.com/assets/1131371/15274524/60615c08-1ab4-11e6-86df-67f9446e8399.png) | ![document-save-as](https://cloud.githubusercontent.com/assets/1131371/15274526/74a8bed6-1ab4-11e6-8930-6577211dd2eb.png) | maybe save-as is a better representation for export then save? 
![mount](https://cloud.githubusercontent.com/assets/1131371/15273898/af392daa-1aa6-11e6-87eb-f2e0530602c2.png) | Mount Backend | list-add | ![list-add](https://cloud.githubusercontent.com/assets/1131371/15275053/f8a44efa-1ac1-11e6-9c69-86f63b864b0e.png) | ![list-add](https://cloud.githubusercontent.com/assets/1131371/15274028/6c760d64-1aa9-11e6-9b8d-8f4b0c69c4f0.png) | ![list-add](https://cloud.githubusercontent.com/assets/1131371/15274099/8b57c4aa-1aab-11e6-8a0c-84d563244a9d.png) | ![list-add](https://cloud.githubusercontent.com/assets/1131371/15274294/c390538e-1aae-11e6-8533-5b1db2536f52.png) | This is the best i could find in the xdg spec for mount and unmount, they should be clear as long as they are shown in context.
![unmount](https://cloud.githubusercontent.com/assets/1131371/15273899/b4e86806-1aa6-11e6-9b7e-75fb3d651f38.png) | Unmount Backend | list-remove | ![list-remove](https://cloud.githubusercontent.com/assets/1131371/15275057/0c014728-1ac2-11e6-9989-ceabcdd4943e.png) | ![list-remove](https://cloud.githubusercontent.com/assets/1131371/15274051/54921020-1aaa-11e6-85da-132e4d9aa8bd.png) | ![list-remove](https://cloud.githubusercontent.com/assets/1131371/15274101/97db25aa-1aab-11e6-83c1-3d1a3c9c69f2.png) | ![list-remove](https://cloud.githubusercontent.com/assets/1131371/15274298/d49e962c-1aae-11e6-9e84-1ffd0921f989.png)
![new-array](https://cloud.githubusercontent.com/assets/1131371/15273924/3cde9370-1aa7-11e6-9509-ace7a8fa5370.png) | New Array | view-grid | ![view-grid](https://cloud.githubusercontent.com/assets/1131371/15275073/4321baa8-1ac2-11e6-91ca-c4da9b9b63ef.png) | ![view-grid](https://cloud.githubusercontent.com/assets/1131371/15274053/67d42196-1aaa-11e6-9432-6c674e2fc2a7.png) | | ![view-grid](https://cloud.githubusercontent.com/assets/1131371/15274300/e0cf4f36-1aae-11e6-9115-d2909f830ddf.png) | Grid as abstract visualisation of array. Is this to much of a stretch?
![color](https://cloud.githubusercontent.com/assets/1131371/15273915/08c69416-1aa7-11e6-9d09-487c92af82d7.png) | Color Settings | preferences-desktop-color | ![preferences-desktop-color](https://cloud.githubusercontent.com/assets/1131371/15275106/e794161c-1ac2-11e6-9490-ca1eb6b62aa6.png) | ![preferences-desktop-color](https://cloud.githubusercontent.com/assets/1131371/15274183/e77a2902-1aac-11e6-9eff-671b6fbe37af.png) ||| kde specific
|| _alternative_ | preferences-color ||| ![preferences-color](https://cloud.githubusercontent.com/assets/1131371/15274192/f9156a50-1aac-11e6-853f-51ba80cb577f.png) | ![preferences-color](https://cloud.githubusercontent.com/assets/1131371/15274310/06514a16-1aaf-11e6-81cc-cc5299127bd5.png) | gnome specific. Maybe find a solution to give the image provider more then one icon name
|| _alternative_ | applications-system | ![applications-system](https://cloud.githubusercontent.com/assets/1131371/15275492/c176e134-1acd-11e6-9475-fdaca9594b82.png) | ![applications-system](https://cloud.githubusercontent.com/assets/1131371/15275499/f262de6a-1acd-11e6-9d79-3706f272a356.png) | ![applications-system](https://cloud.githubusercontent.com/assets/1131371/15275509/399c054a-1ace-11e6-839b-2a3f69a1cc75.png) | ![preferences-system](https://cloud.githubusercontent.com/assets/1131371/15275503/160bd2d6-1ace-11e6-8aca-63f309786936.png)
![edit-rename](https://cloud.githubusercontent.com/assets/1131371/15273918/143e23d6-1aa7-11e6-8e38-329f3c97ac76.png) | edit key/array | edit-rename | ![edit-rename](https://cloud.githubusercontent.com/assets/1131371/15275119/2428d36a-1ac3-11e6-8a67-e5e1653bfcde.png) | ![edit-rename](https://cloud.githubusercontent.com/assets/1131371/15274216/5180991c-1aad-11e6-9e4d-72cb722f8952.png) ||| kde specific
|| _alternative_ | accessories-text-editor | ![accessories-text-editor](https://cloud.githubusercontent.com/assets/1131371/15275133/7632be5a-1ac3-11e6-85ee-451ab547ec20.png) | ![accessories-text-editor](https://cloud.githubusercontent.com/assets/1131371/15274204/17c2cf4c-1aad-11e6-8d24-58ceb22e89af.png) | ![accessories-text-editor](https://cloud.githubusercontent.com/assets/1131371/15274209/37645726-1aad-11e6-98a2-9f8bc1cfce2c.png) | ![accessories-text-editor](https://cloud.githubusercontent.com/assets/1131371/15274313/1752b35e-1aaf-11e6-865d-9f74e9d7117c.png)
|| _alternative_ | document-properties | ![document-properties](https://cloud.githubusercontent.com/assets/1131371/15275142/ac906cd6-1ac3-11e6-9615-a06d71331c4e.png) | ![document-properties](https://cloud.githubusercontent.com/assets/1131371/15274376/4ab45a94-1ab0-11e6-9bfa-2d835ac91e8d.png) | ![document-properties](https://cloud.githubusercontent.com/assets/1131371/15274385/6cb14620-1ab0-11e6-9b89-2cbc721d6fe1.png) | ![document-properties](https://cloud.githubusercontent.com/assets/1131371/15274465/63e14b7e-1ab2-11e6-9add-08e37b10b6af.png)
![whats_this](https://cloud.githubusercontent.com/assets/1131371/15273929/5db89406-1aa7-11e6-83a4-a73f88664fe3.png) | contextual help | help-contextual | ![help-contextual](https://cloud.githubusercontent.com/assets/1131371/15275149/d534cf4c-1ac3-11e6-9742-87cf43dcdd1e.png) | ![help-contextual](https://cloud.githubusercontent.com/assets/1131371/15274245/e0b64faa-1aad-11e6-9559-462b9a9da3de.png) | ![help-contents](https://cloud.githubusercontent.com/assets/1131371/15274253/0e23931c-1aae-11e6-97e1-54722c16e493.png) |  ![help-contents](https://cloud.githubusercontent.com/assets/1131371/15274253/0e23931c-1aae-11e6-97e1-54722c16e493.png) | help-contextual is kde specific it automaticly falls back to default help icon on gnome

**Comment by markus2330** [comment]
Nicely done comparision! We should discuss it in the next meeting.

Some initial ideas from my side:
Is oxygen a relevant set anymore? I thought kde migrates to breeze.
edit-delete looks more like "aborting an action", especially in Oxygen (maybe use trash can or list-remove?)
Isn't there an import/export icon? Open/Close is something quite different? (Wouldn't open/close rather be "mounting a file"?)
Color settings: maybe we simply use a general "settings" icon. Its rather by chance that currently colors are the only configurable item.
document-save-as: Is this needed? Maybe we should reduce the set if possible.
accessories-text-editor: that would be nice for a `kdb editor` feature

**Comment by markus2330** [comment]
@0003088 @beku @Namoshek @omnidan can you take a look, too?

**Comment by sirblackheart** [comment]
@markus2330 

> Is oxygen a relevant set anymore? I thought kde migrates to breeze.

That is just me not being up to date on the kde side of things, i updated the table with the corresponding breeze icons.
> edit-delete looks more like "aborting an action", especially in Oxygen (maybe use trash can or list-remove?)

true, i added user-trash and edit clear as alternatives

> Isn't there an import/export icon? Open/Close is something quite different? (Wouldn't open/close rather be "mounting a file"?)

Sadly no, but we could stay with document-import document-export icon name. Both breeze and oxygen have those.

> document-save-as: Is this needed? Maybe we should reduce the set if possible.

I just added it as alternative icon-name choice for document exporting, as it probably is more similar to export then just save. I updated the table so it should now be clearer which icons are meant to be alternatives.

![screenshot from 2016-05-15 19-08-09](https://cloud.githubusercontent.com/assets/1131371/15275619/c6d72b2c-1ad0-11e6-8f4c-4d1fd17061a3.png)

**Comment by markus2330** [comment]
Wow, qt-gui is hardly recogniceable with the new icons!

**Comment by markus2330** [comment]
@Namoshek please open an issue about build-issues with qt-gui.
Export: it is about generating configuration files that are completely independent of the key database. Importing modifies the key database.

**Comment by sirblackheart** [comment]
> not sure about the advantage of a black-white icon for someone with color blindness, as he will have trouble seeing colors anyway...
Think of other visual impairments like impairment on the clarity of vision. The high contrast icons for this come with strong white outlines so they always are recognizable independent of the background they are drawn on. High contrast is one of the accessibility features most desktops have.

For the rest I think we best show the qt-gui at the meeting so people see in which context the icons appear.

**Comment by Namoshek** [comment]
> @Namoshek please open an issue about build-issues with qt-gui.
I don't think it's an issue with Elektra, but more with me not configuring the build correctly... :sweat_smile: 

> Export: it is about generating configuration files that are completely independent of the key database. Importing modifies the key database.
That's what I thought. So the open/save icon doesn't really fit, because in my opinion it suggests that you can (only) load and store the state of the tool.

**Comment by markus2330** [comment]
The issue tracker is not only for issues, simply use the tags "questions" and "help wanted". Better to have some issues about  trivialities than time-consuming searches by different people over and over again.

**Comment by 0003088** [comment]
Looks good, it sure will integrate nicely into the breeze theme. If there's no stock icon that fits the purpose 100%, it's still possible to create a custom one  (like the current new array, mount/unmount backend icons)

**Comment by markus2330** [comment]
@0003088 Are you interested in creating icons?

**Comment by 0003088** [comment]
Maybe, if there is an agreement on the style and place of the new icons and a definite answer to the question which icons need to be created.
