### ISSUE TITLE
mathcheck: variable operations

### ISSUE THREAD

**Issue by KurtMi** [ElektraInitiative/libelektra#721]
There is a bug in the mathcheck plugin, with:
`kdb mount matcheck.dump /test dump mathcheck`

and

```
kdb rm -r /test
kdb set user/test/asd/test0/points 5.9
kdb set user/test/asd/test1/points 4.5

kdb set user/test/asd/gp
kdb setmeta user/test/asd/gp check/math ":= + test0/points test1/points"
kdb get user/test/asd/gp
kdb set user/test/asd/gp
```

It seems that the mathcheck plugin looks in `user/test/test0/points` and `user/test/test1/points` and not in `user/test/asd/test1/points`. The error is in line 303, but I do not understand your logic completely and you are surely fast in fixing it.

**Comment by markus2330** [comment]
Thank you for reporting! The title is amusing.

Please create a reproduceable test case (e.g. with shell recorder).

**Comment by markus2330** [comment]
@KurtMi Please add shell recorder test.

I unassigned tom-wa because he had too many issues.

**Comment by markus2330** [comment]
[undefinied behavior sanitizer](http://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) reports:
```
/home/markus/Projekte/Elektra/current/src/libs/elektra/internal.c:569:13: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'size_t' (aka 'unsigned long')
/home/markus/Projekte/Elektra/current/src/libs/elektra/keyset.c:689:27: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'unsigned long'
```

**Comment by markus2330** [comment]
@tom-wa as said, please push the shell recorder test to master.

**Comment by markus2330** [comment]
(or create PR if you are not sure if all build servers can run the test successfully)

**Comment by tom-wa** [comment]
already done

**Comment by KurtMi** [comment]
checked and declared as good

**Comment by markus2330** [comment]
Thanks!
