### ISSUE TITLE
zsh auto completion

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#726]
- [ ] slash at end also for leaves
- [ ] needs a tab for every level, even if there is only one possibility for the whole path
- [ ] not every character properly escaped or escaped slashes do not work
- [ ] where to install?
- [ ] no support for cascading keys (starting with `/`)
- [ ] if pressed with empty string: `_values:compvalues:10: not enough arguments`

**Comment by reox** [comment]
note for later: the folder for those files in debian is /usr/share/zsh/vendor-completions

**Comment by sirblackheart** [comment]
looking forward to this one. would be nice to get it into oh my zsh.

**Comment by markus2330** [comment]
@reox could you create the PR as discussed (even if not everything works smoothly at the moment)

**Comment by markus2330** [comment]
Thank you for creating the PR. The debian packages now contain /usr/share/zsh/vendor-completions/_kdb

For me the completion does not work ;( Is there anything needed for the tab completion other than having this file installed?

I started a new zsh, `which kdb` says `/usr/bin/kdb`. (I also tried with `nocorrect noglob kdb`) but `kdb get <tab>` only completes to the files in the current folder.

My system is debian jessie with zsh 5.0.7.

**Comment by sirblackheart** [comment]
@markus2330 could you try to move 
`/usr/share/zsh/vendor-completions/_kdb` to `/usr/share/zsh/site-functions/_kdb`
this worked for me.

**Comment by reox** [comment]
@sirblackheart as far as i read the vendor path should be correct.
Idk if it is in $fpath automatically but for me it is:
```
reox@cebalrai ~ % zsh -f
cebalrai% print $fpath
/usr/local/share/zsh/site-functions /usr/share/zsh/vendor-functions /usr/share/zsh/vendor-completions /usr/share/zsh/functions/Calendar /usr/share/zsh/functions/Chpwd /usr/share/zsh/functions/Completion /usr/share/zsh/functions/Completion/AIX /usr/share/zsh/functions/Completion/BSD /usr/share/zsh/functions/Completion/Base /usr/share/zsh/functions/Completion/Cygwin /usr/share/zsh/functions/Completion/Darwin /usr/share/zsh/functions/Completion/Debian /usr/share/zsh/functions/Completion/Linux /usr/share/zsh/functions/Completion/Mandriva /usr/share/zsh/functions/Completion/Redhat /usr/share/zsh/functions/Completion/Solaris /usr/share/zsh/functions/Completion/Unix /usr/share/zsh/functions/Completion/X /usr/share/zsh/functions/Completion/Zsh /usr/share/zsh/functions/Completion/openSUSE /usr/share/zsh/functions/Exceptions /usr/share/zsh/functions/MIME /usr/share/zsh/functions/Misc /usr/share/zsh/functions/Newuser /usr/share/zsh/functions/Prompts /usr/share/zsh/functions/TCP /usr/share/zsh/functions/VCS_Info /usr/share/zsh/functions/VCS_Info/Backends /usr/share/zsh/functions/Zftp /usr/share/zsh/functions/Zle
```

I think you need to initilize the compsystem by using:
```
autoload -U compinit                                                                                          
compinit
```
in the zshrc.
For me it worked, after running those commands in a `zsh -f`.

**Comment by sirblackheart** [comment]
@reox maybe `vendor-functions` is debian specific or zsh version specific?
```
$ zsh -f                                       
Kali% print $fpath
/usr/local/share/zsh/site-functions
/usr/share/zsh/site-functions
/usr/share/zsh/functions/Calendar
/usr/share/zsh/functions/Chpwd
/usr/share/zsh/functions/Completion
/usr/share/zsh/functions/Completion/Base
/usr/share/zsh/functions/Completion/Linux
/usr/share/zsh/functions/Completion/Unix
/usr/share/zsh/functions/Completion/X
/usr/share/zsh/functions/Completion/Zsh
/usr/share/zsh/functions/Exceptions
/usr/share/zsh/functions/MIME
/usr/share/zsh/functions/Misc
/usr/share/zsh/functions/Newuser
/usr/share/zsh/functions/Prompts
/usr/share/zsh/functions/TCP
/usr/share/zsh/functions/VCS_Info
/usr/share/zsh/functions/VCS_Info/Backends
/usr/share/zsh/functions/Zftp
/usr/share/zsh/functions/Zle

Kali% zsh --version
zsh 5.2 (x86_64-unknown-linux-gnu)

Kali% uname -a
Linux Kali 4.6.3-1-ARCH #1 SMP PREEMPT Fri Jun 24 21:19:13 CEST 2016 x86_64 GNU/Linux

```

**Comment by reox** [comment]
@sirblackheart the vendor-completion is the place on debian. (as far as i read...)
For other distributions I have no idea. Maybe the `/usr/share/zsh/site-functions` is the best choice then, like you said before.

**Comment by markus2330** [comment]
`/usr/share/zsh/site-functions` did not exist and when I mv `_kdb` in a newly created directory of that name I get `(eval):1: _kdb: function definition file not found`.

Maybe another folder is better suitable across distros?
```
markusbyte% print $fpath
/usr/local/share/zsh/site-functions /usr/share/zsh/vendor-functions /usr/share/zsh/vendor-completions /usr/share/zsh/functions/Calendar /usr/share/zsh/functions/Chpwd /usr/share/zsh/functions/Completion /usr/share/zsh/functions/Completion/AIX /usr/share/zsh/functions/Completion/BSD /usr/share/zsh/functions/Completion/Base /usr/share/zsh/functions/Completion/Cygwin /usr/share/zsh/functions/Completion/Darwin /usr/share/zsh/functions/Completion/Debian /usr/share/zsh/functions/Completion/Linux /usr/share/zsh/functions/Completion/Mandriva /usr/share/zsh/functions/Completion/Redhat /usr/share/zsh/functions/Completion/Solaris /usr/share/zsh/functions/Completion/Unix /usr/share/zsh/functions/Completion/X /usr/share/zsh/functions/Completion/Zsh /usr/share/zsh/functions/Completion/openSUSE /usr/share/zsh/functions/Exceptions /usr/share/zsh/functions/MIME /usr/share/zsh/functions/Misc /usr/share/zsh/functions/Newuser /usr/share/zsh/functions/Prompts /usr/share/zsh/functions/TCP /usr/share/zsh/functions/VCS_Info /usr/share/zsh/functions/VCS_Info/Backends /usr/share/zsh/functions/
```
What about `/usr/share/zsh/functions/Completion/Unix`?

compinit works for me, but should multiple completion work? So when I press `kdb ls <tab>` I get the namespaces, but when I try to complete a second time I get:

```
_kdb_paths:33: = not found
```

**Comment by sirblackheart** [comment]
> Maybe another folder is better suitable across distros?
What about /usr/share/zsh/functions/Completion/Unix?

I am having a hard time finding good documentation sources for this topic.
The only relevant one is a discussion on zshs mailing list about adding `/usr/local/share/zsh/site-functions` in addition to `/usr/share/zsh/site-functions` as default to `$fpath`.
http://www.zsh.org/mla/workers/2014/msg00901.html
one reply explicitly explains debians approach with `/usr/share/zsh/vendor-functions`
http://www.zsh.org/mla/workers/2014/msg00902.html

As far as i can tell both Arch Linux and homebrew on macOS use either `/usr/share/zsh/site-functions` and `/usr/local/share/zsh/site-functions`

I will try to do some further investigation on the possibility to install into one of the `/usr/share/zsh/functions/Completion/*` folders.

```kdb_paths:33: = not found```

I am also getting this error.

**Comment by reox** [comment]
> kdb_paths:33: = not found

I see, in zsh -f this does not work: `if [ $foo == "/" ]; then`... You have to use `if [[ $foo == "/" ]]; then` (see line 41)
I fixed that right now

**Comment by markus2330** [comment]
Thank you, it is much better now!

I also noticed that sometimes slashes at the end do not make sense. And it seems like you need to press tabs multiple times for every key-name part even though there is only one match anyway.

Completing crazy names does not work. Given:
```
user/shelltests/crazynames/!"§$%&/(()=?``´\\/abc
```
and then pressing `tab`:
```
$ kdb get user/shelltests/crazynames/\!\"§\$%\&/<tab>
_values:compvalues:10: not enough arguments
```

**Comment by reox** [comment]
You should get something like this:
```
kdb get system/sdfjdslf
completing Could not find system/sdfjdslf as a valid path
```
I know you can correct the user input, but I did not look into that feature...

The trailing slash is an issue I also know but I'm not able to fix right now. Maybe there is a better function or i have to tell the compsys that it should finish with completion then. (I thought that a return at the point would do that but thats not the case)

**Comment by markus2330** [comment]
I do not get `completing Could not find system/sdfjdslf as a valid path`, the reason might be different configuration of auto-completion. Can you share yours so that I can reproduce the intended behaviour?

I have in my `.zshrc`:
```
zstyle ':completion:*' completer _expand_alias _complete _ignored
zstyle ':completion:*:cd:*' ignore-parents parent pwd
setopt glob_complete
autoload -U compinit
compinit -C
zmodload -i zsh/complist
```

I updated the things I found so far in the beginning of this issue. But they are all together only very minor, the auto completion is really great and helps a lot!

**Comment by markus2330** [comment]
should be irrelevant, thus zsh completion will be reimplemented with `kdb complete`
