### ISSUE TITLE
multi-file resolver

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#728]
- [x] multi-file resolver (every tree direct below the mountpoint gets its own file)
- [x] curl resolver
- [x] block resolver (begin+end marker)
- [x] git resolver
- multi-file resolver (with redundant config files as "backup")

**Comment by markus2330** [comment]
block resolver something like:
```
### elektra configuration start
### elektra configuration stop
```

**Comment by tom-wa** [comment]
wouldn't somemthing like 
```
### elektra configuration CONFIGNAME start
### elektra configuration CONFIGNAME stop
```
be better ?

**Comment by markus2330** [comment]
Yes, if you want to support multiple blocks there should be an additional marker.

But its better to keep it simple and extend if needed. But you can already add some marker from the start to be compatible to later versions. (If you have a good idea what `CONFIGNAME` should be).

**Comment by tom-wa** [comment]
can you explain to me what exactly these two multi-file resolvers should do ?

**Comment by markus2330** [comment]
The backup resolver is what you described last meeting: Writing the same config out multiple times.

Imho more important is the other one: Support for the `.d` directories. For example I want to mount the whole directory `/etc/sysctl.d` with whatever `.conf` files are placed within it. This resolver would also be useful for the stud repo.

**Comment by tom-wa** [comment]
about the multifile resolver (the `.d`-directory one): want me to try to implement a backend as a plugin, an abstraction over the `list` plugin or, ... actually there are many ways to do it, any preferences ?

**Comment by markus2330** [comment]
I think we should not complicate the list plugin even further. Backends as Plugins would be a step forward..

**Comment by markus2330** [comment]
The multi-file resolver is the next important thing (the one that treats many files as individual subtrees without mounting each of it individually). Some infos about it:

The plugin basically is a resolver for directories that creates a list of resolved files       by dispatching the list of files to individual resolvers/storage plugins. It is a kind of a lazy "resolver and storage dispatcher".

it works the following way for kdbGet():
1.) first invocation:
 - do kdbOpen() and kdbGet() using a "fake" resolver kdbOpen() with a /path (/path is in this case a directory not a configuration file), e.g. "ld.so.conf.d" -> "/etc/ld.so.conf.d"
 - using this real directory, either use the configuration "/glob" or simply add an "*" at the end of the directory, e.g.: "/etc/ld.so.conf.d" -> "/etc/ld.so.conf.d/*"
 - do a glob(3) to get all real configuration files, e.g. "/etc/ld.so.conf.d/*" -> "/etc/ld.so.conf.d/elektra.conf" "/etc/ld.so.conf.d/libc.conf"
 - For every globbed file create a new resolver and run kdbOpen() on it (with faked /path), e.g. Plugin *p =  elektraPluginFactory(), p->config = ksNew{keyNew("system/path", KEY_VALUE, "/etc/ld.so.conf.d/libc.conf", KEY_END}
 - For every globbed file create a new storage plugin
 - For every globbed file run kdbGet() on its resolver
2.) (later invocations)
  - Check for new files, create new resolvers+storages for them (as above)
 - If file is removed, remove all of its keys, and kdbClose() resolver+storage
 - For every globbed file run kdbGet() on its resolver
 - If every storage returned 0 (nothing to do), then the overall multi-file plugin returns 0, too (then the plugin will not be invoked for 2.))
   3.) Then, with the stored names, on the next kdbGet() invocation, it runs all storage plugins

The kdbSet() invocation is a bit more involved (has more states):
 1.) Run kdbSet() for every resolver, store the resolved path name (string of parent key)
 2.) Then, run all storage plugins with the correct path names (again with string of parent key)
 3.) Then run kdbSet() again for every resolver (to commit)
  OR, if kdbError() is invoked:
  3.) Run kdbError() for every resolver

Key Names, e.g. for /etc/ld.so.conf.d/elektra.conf /etc/ld.so.conf.d/libc.conf and are:
                user/mountpoint/elektra.conf/key
                user/mountpoint/libc.conf/key

**Comment by tom-wa** [comment]
>"ld.so.conf.d" -> "/etc/ld.so.conf.d"

just to get this right: the mount argument is "ld.so.conf.d" and not "/etc/ld.so.conf.d" ?

also, why glob and not reddir ? dirent->d_type could be used to check if it's a directory or not

**Comment by markus2330** [comment]
> just to get this right: the mount argument is "ld.so.conf.d" and not "/etc/ld.so.conf.d" ?

Both might work depending on the KDB_DB_SYSTEM setting. Please try to resemble the `resolver` behavior, but for directories.

> also, why glob and not reddir ? dirent->d_type could be used to check if it's a directory or not

Do you mean readdir? It has thread-safety problems, so it would be better to use `readdir_r`. That would be okay too (if you find it easier).

**Comment by tom-wa** [comment]
@markus2330 
is there a way to get a list of plugins a mountpoint is mounted with from within a plugin ?

**Comment by markus2330** [comment]
No, currently there is no way. Where do you need it?

The multi-file resolver plugin should work as resolver+storage. You can assume for now that no other plugin doing bad things is mounted on the same mountpoint.

**Comment by tom-wa** [comment]
i was thinking about the case `kdb export system/ld.so.conf.d` which i imagine would only work if all plugins are controlled by the multifile resolver

**Comment by tom-wa** [comment]
how should calles to individual subtrees/files be handled ? e.g. should a call to `system/ld.so.conf.d/local.conf` be forwarded to the resolver+storage for the file `local.conf` or call each resolver and storage plugin
both would be possible, and could be implemented alongside each other, but i'm not sure if theres any need for it

**Comment by markus2330** [comment]
Sounds like an optimization, so as first Version it should be enough to always return everything.

Btw. there might be a misunderstanding of the pathes. So you would do:

```
kdb mount --resolver multifile --plugins-config pattern='*.conf' /etc/ld.so.conf.d system/ld ...
kdb ls system/ld/local
```
To query `/etc/ld.so.conf.d/local.conf `. So neither `ld.so.conf.d` nor the full path name of the file might be present in Elektra's paths.

**Comment by tom-wa** [comment]
>Sounds like an optimization, so as first Version it should be enough to always return everything.

it would be "real" laziness, only calling the resolver + storage on a file if it's really needed. synchonization of everything could get quite complicated though. 

using the paths from your example:
`kdb ls system/ld` would call all resolvers + storage plugins for all files, but
`kdb ls system/ld/local` would only call the resolver + storage plugin for `ld.so.conf.d/local.conf`

even if the feature wouldn't be present now, it would be easier to add it later if i keep it in mind while writing the first version


about paths: i just used the full names because i thought `system/ld/local` might be confusing as an example.

**Comment by tom-wa** [comment]
i think theres an issue with how you described the kdbGet process:
- on the first invocation (getresolver) kdbGet is called for every file/resolver
-on every succeeding call to kdbGet will be called on the resolvers again and would return 0 (no update needed) in most cases so it's impossible to tell if there any need to read the file. 

is there actually any need to call kdbGet on the resolvers on the first invocation ? if i'm not wrong the result would be the same.

**Comment by markus2330** [comment]
> is there actually any need to call kdbGet on the resolvers on the first invocation

Yes, the resolver needs to initalize itself with the timestamp of the file(s).

But as we plan to release soon, we should focus now on 0.8.19 issues, especially the many remaining shell recorder issues in  #944.
