### ISSUE TITLE
XDG variables

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#734]
Currently, XDG basically only has support for what is the `user` namespace in Elektra. (The specification works on files, the current implementation with per-key override of `system` already took quite some interpretation of [the standard](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html), e.g. because it does not specify what "importance" means.)

For the other namespaces, we are currently lacking environment variables:

- system
- system/elektra/mountpoints (if we want to handle it separately)
- spec
- dir

Should we add them, should we concentrate our XDG efforts on `user`, or should we discuss it on the XDG list?

**Comment by beku** [comment]
XDG list discussion appears the best thing to clarify XDG spec intention and side effects beyond a few use cases. Whether it helps getting admin comments is a different question.

**Comment by markus2330** [comment]
Btw. on the mailing list there was no interest to extend the standard: https://www.mail-archive.com/xdg@lists.freedesktop.org/msg07921.html
