### ISSUE TITLE
qt-gui reset to default colors is not saved

### ISSUE THREAD

**Issue by raetiacorvus** [ElektraInitiative/libelektra#735]
If previously custom colors in the gui have been set, clicking on reset to default only resets them temporarily. Synchronizing or restarting the app sets them back to the previously saved colors.

**Comment by 0003088** [comment]
the guisettings.cpp looks a little different from I remember it. Could you elaborate on fallback and legacy profiles in getKDB()?

**Comment by markus2330** [comment]
Seems like I implemented reset() wrongly, but that seems to be unrelated to profiles. The needed change is trivial.

Please reopen if it is not fixed properly.

**Comment by markus2330** [comment]
The fix in 8a5eb45 is not ideal: It writes the conf to the user-namespace even if the user never changed anything (only pressed "reset") and it does not honor system settings (but only the build-in settings we provide).

So an alterative solution would be to remove the user-keys. Obviously this might remove some legacy conf, that the user actually did not want to remove. What do you think?

**Comment by 0003088** [comment]
My original solution, afair, was that the class would return the standard colours (they do honour system settings since they are derived from the current system colours?) and only save some config if the user made any changes. What's wrong with that approach?

**Comment by markus2330** [comment]
What you also should consider is if an admin sets:
```
kdb set system/sw/elektra/qtgui/#0/current/color/frame "#6f6e6c"
```

and someone presses reset, the qui should still not set the color, even though its not equal to the built-in color.

Another issue is that setKDB might remove unrelated keys (dummySet might contain keys outside of m_base), we should cut them at m_base and append them.

**Comment by markus2330** [comment]
Initial issue is fixed, please open a new issue if you think parts of this discussion are relevant to be fixed.
