### ISSUE TITLE
mingw64 build

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#738]
@waht @sirblackheart the http://community.markus-raab.org:8080/job/elektra-gcc-configure-mingw-w64/ build job now contains an archive that contains an installed Elektra. Such zips are kept for the latest 3 builds. The last one always is: http://community.markus-raab.org:8080/job/elektra-gcc-configure-mingw-w64/lastSuccessfulBuild/artifact/build/elektra.zip

Please check if the content of the zip works. Does also the shared variant work? Can you mount something? Can you even link another program against libelektra.dll? Can you write a short tutorial how to use it?

Do not hesitate to ask for any changes in the build. (E.g. other prefix, remove shared variant, or not installing bash completion?)

@sirblackheart btw. the visual c++ build might produce much less errors if you tell cmake to interpret every .c file as c++ code. Maybe something like (pseudocode):
```
if (visualcpp AND w32)
file (glob every_c_file */*.c)
SET_SOURCE_FILES_PROPERTIES(${every_c_file} PROPERTIES LANGUAGE CXX )
```

Fixes for compilation errors where C code does not compile as C++ code is accepted upstream. I am unsure if this is worth the effort, mingw seems like a better solution.

@mpranj Could you please add mingw64 for PRs?

**Comment by sirblackheart** [comment]
@markus2330 i gave it a try. As prelude my setup is [msys2](https://sourceforge.net/projects/msys2/) with mingw64 and mintty. In addition I also tested in the windows command line.

I was not able to use kdb shared. First i was missing libdl.dll. I gave both the binary [package ](https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-dlfcn)from msys2 mingw64 package as well as a self compiled [library ](https://github.com/dlfcn-win32/dlfcn-win32)version a try.

In addition i had to rename libelektra-wresolver.gll to libelektra-resolver.dll and libelektra-dump.dll to libelektra-storage.dll. Elektra uses symlinks for this on linux, but no such thing on windows. I still got the following error:
```shell
1 Warning was issued:
 Warning number: 1
        Description: could not load module, dlopen failed
        Ingroup: modules
        Module: dl
        At: /home/jenkins/workspace/workspace/elektra-gcc-configure-mingw-w64/src/libs/loader/dl.c:82
        Reason: of module: libelektra-storage.dll, because: "libelektra-storage.dll": The specified module could not be found.
        Mountpoint:
        Configfile:
Error (#40) occurred!
```

I tried to get all the needed dependencies trough [dependency walker](http://www.dependencywalker.com) but at some point gave up.

Boht static and full seem to work fine with basic commands like `set get info ls`.
I have not tried mounting yet as i wanted to export something before that so i could mount it. But exporting resulted in the following error:
```shell
$ ./kdb-static ls user/usr
user/usr/bla

$ ./kdb-static export user/usr
Error (#75) occurred!
Description: Could not open file for writing.
Ingroup: plugin
Module: storage
At: /home/jenkins/workspace/workspace/elektra-gcc-configure-mingw-w64/src/plugins/dump/dump.cpp:233
Reason: No such file or directory
Mountpoint: user/usr
Configfile: /dev/stdout
```

**Comment by markus2330** [comment]
Thank you for testing!

libdl.dll is part of the build directory (./build/src/libs/loader/dlfcn-win32/bin/libdl.dll) I can copy it into the zip if you want.  Or should we disable the shared build and lets call it unsupported for now on mingw?

Yes, the symlink does not easily work on w32, we will have to copy it.
Did you set `PATH` to where the libraries are? Which dependencies were missing?

Yes, export/import needs an `#ifdef` for w32, writing to /dev/stdout obviously won't work. I do not know, however, which file would represent stdout on w32? We can also add a commandline-option to directly write to a specified file? (Would be useful for other systems, too)

Mounting would still be interesting.

**Comment by sirblackheart** [comment]
> Did you set PATH to where the libraries are? Which dependencies were missing?

I did copy everything into the same folder. As far as i can remember `libstdc++-6.dll` and `libgcc_s_sjlj-1.dll` where the ones missing.

>  I do not know, however, which file would represent stdout on w32?

[CON ](http://superuser.com/questions/241272/windows-how-to-redirect-file-parameter-to-stdout-windows-equivalent-of-dev-s)looks promising.

> Mounting would still be interesting.
kdb-full mount segfault regardless of file and  plugin string.
kdb-static behaves the same but prints the following:

````
terminate called after throwing an instance of 'kdb::tools::NoPlugin'
  what():  No plugin that provides sync could be found
````

**Comment by markus2330** [comment]
Ok, I'll try to rebuild with sync plugin enabled. (I am not sure if it will work)

As workaround you can set `/sw/elektra/kdb/#0/current/plugins` to empty string.

**Comment by markus2330** [comment]
Ok, I tried to use CON in 5e868657359185a23aa40067c20f6cba8fd1800d (export might work now), but there seems to be no equivalent for /dev/stdin (so import won't work).

**Comment by markus2330** [comment]
Ok, so no sync plugin for mingw. Simply use workaround as suggested.

**Comment by sirblackheart** [comment]
Ok after 

> As workaround you can set /sw/elektra/kdb/#0/current/plugins to empty string.

and creating `C:/ProgramData/home/jenkins/workspace/workspace/elektra-gcc-configure-mingw-w64/system/elektra.ecf` mounting works. Sys mounts are stored in `C:/ProgramData/home/jenkins/workspace/workspace/elektra-gcc-configure-mingw-w64/system/` but user mount are stored correctly in the user folder `C:/User/Username/storagefile`

CON works for output windows command line but does not allow to pipe and i do not get any output in the mintty terminal so sadly it is not a full equivalent for stdout.

There seem to be some utf8 problems when using `kdb info` but that is just a minor detail.

**Comment by markus2330** [comment]
What should the default place for the system configuration be? (User conf is done by environment variable).

> CON limitations

Ok, so providing some option to write to a file is then an leftover (not related to mingw). Additionally, we also could write to a temporary file and output it afterwards. It might also be useful for Linux, /dev is not always mounted.

Thank you for all the investigations, I think its now quite good documented what works and what not, except: Is if it is possible to link a vc++ program against the dll from mingw.

**Comment by sirblackheart** [comment]
> What should the default place for the system configuration be? (User conf is done by environment variable).

I think we should user `%ALLUSERSPROFILE%/kdb/` for system configuration and  for user mounts and configuration we should probably use `%LOCALAPPDATA%/kdb/` and use `%USERPROFILE%` only as fallback.

> If it is possible to link a vc++ program against the dll from mingw.

I will give it a try.

**Comment by sirblackheart** [comment]
As far as i can tell it is not possible to link against mingw64 compiled libraries from a visual studio project.

**Comment by markus2330** [comment]
ALLUSERSPROFILE is already honored, but it seems to be not set on your system?

USERPROFILE seems to be consistent with ALLUSERSPROFILE, is there something like ALLLOCALAPPDATA?

**Comment by sirblackheart** [comment]
No it is correctly set:
```bash
C:\Users\Gabriel>echo %ALLUSERSPROFILE%
C:\ProgramData
```
 i wonder why kdb-full is using this long path:
```bash
C:\elektra\usr\local\bin>kdb-full.exe file system
C:/ProgramData/home/jenkins/workspace/workspace/elektra-gcc-configure-mingw-w64/system/default.ecf
```

**Comment by markus2330** [comment]
I see, because it is an relative path the KDB_DB_SYSTEM gets appended after ALLUSERSPROFILE.

That KDB_DB_SYSTEM is such a long path comes from the jenkins build, I changed it now (see e5561871b191dad4692993bac000388caa5520ec), jenkins build is starting soon.With the change we would have:

C:\ProgramData\spec\configfile   for relative "configfile" in spec
C:\ProgramData\kdb\configfile   for relative "configfile" in system
C:\ProgramData\configfile   for absolute "/configfile" (both system and spec)

**Comment by sirblackheart** [comment]
Ok i am now also able to build on my system but i had to change
`-DKDB_DB_SYSTEM=kdb` to `-DKDB_DB_SYSTEM=/kdb`.
Spec seems still to have a path problem and so does dir:
```bash
$ bin/kdb-full.exe file spec
C:/ProgramDataC:/Program Files (x86)/Elektra/spec/default.ecf

$ bin/kdb-full.exe file dir
C:/msys64/home/sirblackheart/Documents/libelektra/build/default.ecf

```

**Comment by markus2330** [comment]
Good that you can build it now!

Can you reproduce the problem also outside of msys64? dir should be current working directory + configfile. (KDB_DB_DIR is not implemented)

for spec: is not using ALLUSERSPROFILE (would be C:/Program Files (x86)/Elektra/spec/default.ecf then) also an option?

Maybe its the easiest if you create a PR for wresolver with the behaviour you expect? 
src/plugins/resolver/README.md explains how it works for Linux.
There is currently hardly any documentation in src/plugins/wresolver/README.md
but there are some wresolver tests in tests/shell/check_resolver.sh

**Comment by markus2330** [comment]
Seems to be quite complete now. @raetiacorvus Thanks for your effort!
