### ISSUE TITLE
Proposal: Enable merge squashing for pull requests

### ISSUE THREAD

**Issue by raetiacorvus** [ElektraInitiative/libelektra#743]
As trough the workflow of the pull requests we often add small commits with only marginal changes. It would be nice if such pull requests would be [squash merged ](https://help.github.com/articles/about-pull-request-merge-squashing/#) to keep the upstream repo commit history cleaner.

**Comment by markus2330** [comment]
I agree that we should care about rebasing, but I am sceptical to make such a reduction of information as default, especially not when a PR adds a new non-trivial feature.

Here are some more thoughts about that: https://mjg59.dreamwidth.org/42759.html

But I can enable the feature if we use it carefully: there are also obvious reasons when to use it (e.g. squash code change and reformatting).

**Comment by markus2330** [comment]
The feature is disabled, please reopen the issue if someone think it should be discussed further.
