### ISSUE TITLE
Intercept open

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#747]
Using `/preload/open/<filename> = <other filename>` one should be able to specifiy which configuration files are used instead of other files in the intercepted |open| call.

For example:
```
/preload/open/~\/.vimrc =~/.vimrc-other
```

would intercept open syscalls to `~/.vimrc` and return a file descriptor to ~/.vimrc-other instead.

Together with contextual-lookups this is very useful, e.g.:

```
[spec/preload/open/~\/.vimrc]
  context = /sw/vimrc/%profile%/file
user/sw/vimrc/latex/file = ~/.vimrc-latex
user/sw/vimrc/dev/file = ~/.vimrc-dev
user/sw/vimrc/NOT_HERE/file =
...
```

Another useful feature shown above is pretending the configuration file is not here.
An error should be returned if the file is an empty string.

(contextual-lookup does not need to implemented for this issue)

**Comment by tom-wa** [comment]
any suggestions on how to handle relative paths ? 
e.g. if the cwd would be `/home/user` , the file `/home/user/test` could be either `./test`, `test`, `/home/user/test` or `~/test` or if you are in `/home/user/dir` `../test` could also refer to the same file, so there would be tons of possible keynames for the same file. 

one way would be trying to get the absolute pathname, and then try to remove the cwd from the pathname, replace it with `./`, replace the home directory with `~`, etc until a matching key is found. 

do you have a better idea ?

**Comment by markus2330** [comment]
Absolute pathes (starting with /) and home-directory-pathes (starting with ~) should be clear: the cwd is irrelevant in these cases.

A relativ path can be resolved from the cwd, but this feature is not as important.

**Comment by tom-wa** [comment]
i don't think the feature would be very useable without resolving relative paths. 
calling `cat .vimrc` inside your home directory would result in open(".vimrc",...) (and `cat ./.vimrc` in open("./.vimrc",..)
to only way to get the `/preload/open/~\/.vimrc`-key would be using getcwd to get the full path, and then replacing the path of your home directory with `~`

**Comment by markus2330** [comment]
We talked past each other, I was thinking about how the user will configure the open-interception, not about the implementation.

In the implementation you need to concatinate cwd+parameter of open.
realpath (3) or canonicalize_file_name (3) would not really help, the symlink handling would be weird. E.g. when `.vimrc` is a symlink to `.vimrc-symlink` the user would need to configure `.vimrc-symlink` for redirection.

Together with the expansion of the user-provided path a simple strcmp should do.

For the open-parameter you do not need to handle ~, the shell would already resolve it for you earlier.

So, if the user configures ~/.vimrc to be redirected to ~/.vimrc-other (as obove) it should resolve to /home/markus/.vimrc and /home/markus/.vimrc-other.

When the user executes `cat .vimrc`, it would resolve to `pwd+/.vimrc`, yielding the configured path.

**Comment by tom-wa** [comment]
realpath would also fail for non-existing files, so it wouldn't be very useful anyway

i think there would still be some issues though. 
let's say i call `cat ~/.vimrc`, it would result in `open("/home/user/.vimrc",..)` and the keyname could be either `/preload/open/~\/.vimrc` or `/preload/open/\/home\/user\/.vimrc`. 
assuming we allow something like `/preload/open/.\/filename` too, when calling `cat filename` inside your home directly `filename`, `.\/filename`, `~\/filename` and `\/home\/user\/filename` could be all valid key basenames refering to this file. ignoring this case for now would only cause more trouble later i think.
so if i'm not wrong here, i think we need to specify an order in which the keynames will be resolved.

**Comment by markus2330** [comment]
I would not allow `/preload/open/.\/filename`. Next to the problem you mentioned, it will force you to recreate all pathes of the configuration all the time (because cwd might change).

Do you have a valid use-case to use relative pathes in the configuration?

An order need to be specified anyway (you could specify to intercept both `~/.vimrc` and `/home/markus/.vimrc`), so I do not think it will cause troubles later.

**Comment by tom-wa** [comment]
i was thinking of local / per directory vim configs or .gitignore files. that way e.g. setting an alias could quickly provide such a config overriding the default one just once.

**Comment by markus2330** [comment]
Features like this can be better implemented by generating the config-files on the fly. With cascading, `dir/` keys (and thus files from `pwd`) would be preferred. The lookup "if a file is a config file" should be minimal, because it has to be paid for every `open`.

**Comment by tom-wa** [comment]
theres currently an issue with the "read-only" feature: 
when trying to write to the file using nano, vim, etc they all return some sort of error (can't write, read only, etc) but they all seem to remove the contents of the original file afterwards

i could (instead of removing the O_WRONLY oflag) just reject the open call on read-only files when the O_WRONLY flag is set, but i don't like that solution.

any other ideas/suggestions ?

**Comment by markus2330** [comment]
The read-only feature is not so important, you can leave it for now. I think its also not so useful unless you also handle `unlink` cases. But these features are more a user-space rootkit than configuration related.

Generation of config files would be more interesting.

**Comment by tom-wa** [comment]
i've already removed the unlink cases, at first i thought the editors might just unlink the file, but then i figured out they all use mmap

i've also implemented a way to generate configurations from elektra keysets (not finished, currently just testing)
currently when a key as the metakey `open/create` the value of the key is treated as elektra key, and the metakey value is the format

**Comment by markus2330** [comment]
Sounds good, should I merge current version and you add config option later?
I would prefer metakey `content` or `generate` though, `open/create` sounds confusing.

**Comment by tom-wa** [comment]
yeah, i'll remove the generating part for now and make an other PR with it once it's done 
open/generate or just generate ?

**Comment by markus2330** [comment]
Maybe a non-meta based configuration will be better after all, so something like:

```
/preload/open/~\/.vimrc =~/.vimrc-other
/preload/open/~\/.vimrc/readonly = 1
/preload/open/~\/.vimrc/generate = /other/key
/preload/open/~\/.vimrc/generate/plugins = ini
```

**Comment by tom-wa** [comment]
yeah, seems cleaner that way. i'll change it

**Comment by markus2330** [comment]
Do you already have a draft how to generate configuration files?

**Comment by tom-wa** [comment]
@markus2330 any comment on the current state ? is there anything that should be changed or can we close this issue ?

**Comment by markus2330** [comment]
Thank you I think its well done! Let us open new issues for further enhancements.
