### ISSUE TITLE
Elektra Qt Editor: color chooser dialog sets wrong color

### ISSUE THREAD

**Issue by sirblackheart** [ElektraInitiative/libelektra#758]
This bug is maybe platform dependent (GNOME vs KDE).
When using the color chooser to select a color and press ok to apply the color to a specific option (e.g. highlight), this option does not get the color i choose but the color i choose before that. And if i have not chosen a color before, black gets applied.

Example:
I have set everything to system color defaults. I want to choose the highlight color. Open the choose colors window. I click on the color on the right side of highlight. I select green as color. I press Ok. I expect highlight to have now green as color, but it shows black to its right side and black is also the highlight color in the application. I click again on the color to the right side of highlight and now select red in the color chooser dialog. The highlight is now the green i choose in the dialog before.

![peek 2016-05-29 18-13](https://cloud.githubusercontent.com/assets/1131371/15634639/10de308c-25c9-11e6-8bcc-4d0b87024eda.gif)

Using `colorDialog.currentColor` instead of `colorDialog.color` fixes this for me, but that is wrong according to the [qml documentation](http://doc.qt.io/qt-5/qml-qtquick-dialogs-colordialog.html#currentColor-prop) which states

> For the color that is set when the dialog is accepted, use the color property.

So maybe this is a platform specific bug?

**Comment by markus2330** [comment]
The gif is done really nicely, can you create something like this to show how a bit qt-gui works?

With KDE you have a complete different color chooser. It also has some unexpected behaviour: the color chosen last is presented, and not the one you try to change currently.

Can you create a PR for your fix, we can test if it still works with KDE.

@0003088 Do you have some ideas here?

**Comment by 0003088** [comment]
I can remember that I ran into this bug but I'm not sure what I did to get around it (is it [this](https://bugreports.qt.io/browse/QTBUG-35792) one?) What Qt version are you using anyway?

**Comment by sirblackheart** [comment]
@0003088 yes this seems to be the bug, i wonder why they closed it... running Qt5.6
switching to `currentColor` seems to work fine so far. I tested it on OS X, GNOME and KDE.

**Comment by sirblackheart** [comment]
Well they even [rewrite their own examples](https://bugreports.qt.io/browse/QTBUG-36593?jql=text%20~%20%22ColorDialog.color%22) to work around it, so that is probably the best path to take for now.
