### ISSUE TITLE
Question: kdbGets update behavior.

### ISSUE THREAD

**Issue by raetiacorvus** [ElektraInitiative/libelektra#760]
The [docu](http://doc.libelektra.org/api/0.8.16/html/group__kdb.html#ga28e385fd9cb7ccfe0b2f1ed2f62453a1) states:
> Updates:
> In the first run of `kdbGet` all requested (or more) keys are retrieved. On subsequent calls only the keys are retrieved where something was changed inside the key database. The other keys stay unchanged in the keyset, even if they were manipulated.

This made me assume that multiple calls would no overwrite changes to key values in the ks, that have not changed in the kdb. But calling kdbGet before kdbSet will reset any changes i made to the keyset. Is this specific behavior to the glib bindings?

But the docu also states:
> The new retrieved keys will be appended using `ksAppendKey().`

and the docu says to `ksAppendKey()`
> If the keyname already existed in the keyset, it will be replaced with the new key.

Which would explain the reset behavior of `kdbGet()` and i am probably misunderstanding the update statement from the docu. Does it mean the keys will not get changed, but their values will?

**Comment by markus2330** [comment]
#706 improves the behaviour to something you would expect (@Namoshek and @KurtMi  for details there)

Without the globalcache, kdbGet() will not manipulate the keys *at all* if no update is needed. So if you pass modified values, the values will stay modified, if you pass an empty keyset, the keyset will stay empty.

After you changed KDB using kdbSet(), it is similar to the situation where an update is needed, so the previous statement is irrelevant.

This behaviour is identical for every binding, it should only be influenced by plugins, and  not by bindings.

I will update the docu to reflect this more clearly, please keep the issue open.

In the longer term, I think the globalcache should be default (see #690). Its behaviour is what you would expect. (And if it is not, we should discuss the globalcache behaviour.)

**Comment by markus2330** [comment]
The initial description is unclear. Which keyset was used for `kdbGet` and then `kdbSet`? Please reopen if the issue is still relevant.
