### ISSUE TITLE
GNOME Integration: ElektraSettings (GSettingsBackend)

### ISSUE THREAD

**Issue by raetiacorvus** [ElektraInitiative/libelektra#762]
# ElektraSettings (GSettingsBackend)

I will use this ticket to track the state of the GSettingsBackend implementation:
## Interface Implemenation
- [x] read () method to read a key's value
- [x]  read_user_value () virtual method to read user's key value
- [x]  get_writable () method to get if a key is writable
- [x]  write () method to change key's value
- [x]  write_tree ()  method to change a tree of keys
- [x]  reset () virtual method to reset state -- _#761_ --
- [x]  subscribe () method to subscribe to key changes
- [x]  unsubscribe () method to unsubscribe to key changes
- [ ]  sync () virtual method to sync state -- _needs to handly conflicts and errors_ --
- [x]  get_permission ()  method to get permission of a key -- _not implemented_ --
## Code Quality
- [ ]  cleaner cmake code
- [ ]  comments -- _partially_ --
- [ ]  error handling
- [ ]  peer reviews
- [x] pass gsettings own unit tests
## Research
- [ ] which applications actually use g_settings_new_with_backend ()
## Note

Currently the backend is developed [outside](https://github.com/sirblackheart/elektrasettings) of the Elektra Source Tree to grant flexibility during early development cycles. It will be integrated once it reaches a mature and stable state.
## Discussion
- Specific behaviors relating getKDB, setKDB and append Key
  - those are only bugs in the gsettingsbackend, probably related to threading
- dbus as global plugin?
  - offenes issue #404 
- convenience plugin (bool 'true', 'false')

**Comment by markus2330** [comment]
Nice overview, well done!

Did you already try to run the gsettings unit tests?

**Comment by sirblackheart** [comment]
Just did and it looks rather good for the current state of the code.
The first two errors turn up in tests where ElektraSettings is still missing the implementation (`writeTree`). The others seem to come from calling the single test directly. But that is the only way to run all tests currently, as the glib tests segfaults on any error.

```
/gsettings/basic: OK
/gsettings/basic-types: OK
/gsettings/complex-types: OK
/gsettings/changes: OK
/gsettings/l10n: warning: translation is not working... skipping test. OK
/gsettings/l10n-context: warning: translation is not working... skipping test.  OK
/gsettings/delay-apply: **
GLib-GIO:ERROR:gsettings.c:492:test_delay_apply: assertion failed: (!changed_cb_called)
/gsettings/delay-revert: OK
/gsettings/delay-child: OK
/gsettings/atomic: **
GLib-GIO:ERROR:gsettings.c:664:test_atomic: assertion failed (str == "greetings from test_atomic"): ("top o' the morning" == "greetings from test_atomic")
/gsettings/simple-binding: OK
/gsettings/directional-binding: OK
/gsettings/custom-binding: OK
/gsettings/no-change-binding: OK
/gsettings/unbinding: OK
/gsettings/writable-binding: OK
/gsettings/keyfile: OK
/gsettings/child-schema: OK
/gsettings/strinfo: OK
/gsettings/enums: OK
/gsettings/flags: OK
/gsettings/range: OK
/gsettings/list-items: OK
/gsettings/list-schemas: OK
/gsettings/mapped: OK
/gsettings/get-range: OK
/gsettings/schema-source: OK
/gsettings/schema-list-keys: 
(/home/sirblackheart/Documents/glib/gio/tests/.libs/lt-gsettings:4318): GLib-GIO-ERROR **: g_settings_schema_source_unref() called too many times on the default schema source
/gsettings/actions: OK
/gsettings/null-backend: 
(/home/sirblackheart/Documents/glib/gio/tests/.libs/lt-gsettings:4412): GLib-GIO-WARNING **: Tried to implement non-registered extension point gsettings-backend
/gsettings/memory-backend: 
(/home/sirblackheart/Documents/glib/gio/tests/.libs/lt-gsettings:4457): GLib-GIO-WARNING **: Tried to implement non-registered extension point gsettings-backend
/gsettings/read-descriptions: OK
/gsettings/test-extended-schema: OK
/gsettings/default-value: OK
```

**Comment by sirblackheart** [comment]
All tests are running fine now.
Also using Elektra as GSettings backend on both my computers right now and neither did blow up yet.
As a side note i did notice a slightly elevated cpu usage on my notebook where i use an ini mount for GSettings, but i am not sure if that is related or not.

```shell
/gsettings/basic: OK
/gsettings/basic-types: OK
/gsettings/complex-types: OK
/gsettings/changes: OK
/gsettings/l10n: warning: translation is not working... skipping test. OK
/gsettings/l10n-context: warning: translation is not working... skipping test.  OK
/gsettings/delay-apply: OK
/gsettings/delay-revert: OK
/gsettings/delay-child: OK
/gsettings/atomic: OK
/gsettings/simple-binding: OK
/gsettings/directional-binding: OK
/gsettings/custom-binding: OK
/gsettings/no-change-binding: OK
/gsettings/unbinding: OK
/gsettings/writable-binding: OK
/gsettings/keyfile: OK
/gsettings/child-schema: OK
/gsettings/strinfo: OK
/gsettings/enums: OK
/gsettings/flags: OK
/gsettings/range: OK
/gsettings/list-items: OK
/gsettings/list-schemas: OK
/gsettings/mapped: OK
/gsettings/get-range: OK
/gsettings/schema-source: OK
/gsettings/schema-list-keys: OK
/gsettings/actions: OK
/gsettings/null-backend: OK
/gsettings/memory-backend: OK
/gsettings/read-descriptions: OK
/gsettings/test-extended-schema: OK
/gsettings/default-value: OK
```

**Comment by markus2330** [comment]
Great! This was really fast!

Yes, ini tends to be slow (and dump too). ni is quite fast, but it discards comments.

**Comment by sanssecours** [comment]
> @sanssecours do you plan to compare the storage plugins for performance?

Yes.

**Comment by markus2330** [comment]
Ok, then we can expect to learn much more about performance characteristics with @sanssecours work. Maybe the gsettings are even a way to get realistic data.

**Comment by sirblackheart** [comment]
Ok a short update regarding the application startup elektra vs dconf.
The difference of almost 3 seconds i was talking about at the meeting 09.06.16 was due to a bug on my side.
In general the difference after fixing it is now down to about ~0.1 s when starting gnome-tweak-tool.
Used plugins: `ni` `dbus` `journald`

**Comment by markus2330** [comment]
Great to hear, will be exciting if it gets even faster with @mpranj and @KurtMi work.

Do you want to mention your current work in the upcoming release? Or do you even want to merge it as experimental?

**Comment by sirblackheart** [comment]
I honestly do not feel comfortable to merge the code in the current state. I will try to polish it, but not sure if i get it into an `experimental` state before 0.8.17 release.

**Comment by markus2330** [comment]
If we put a proper disclaimer people will know what they get.

And do you want your repo to be mentioned? Or that you are working on it and that a benchmark looks promising?

**Comment by sirblackheart** [comment]
Ok, i will prepare a pr.
But first the question where should it reside in the current Elektra source?
Should it go into libs or rather into bindings?

**Comment by markus2330** [comment]
Bindings, should be fairly easy to add. You only have to make sure glib is selected when your binding gets added. (See how gi does it.) Per default it should be disabled.

Please try to keep the version history.

**Comment by markus2330** [comment]
@raetiacorvus A nearly fixed issue, would love to see it completed!

**Comment by markus2330** [comment]
Closed because of lack of man power, will be reevaluated after 1.0.
