### ISSUE TITLE
FreeBSD: JNA bindings - CMake can not find jar

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#763]
The Java Native Access jar installed from the ports (`devel/jna`) is not found.

It should be just a matter of directories. FreeBSD installs it to `/usr/local/share/java/classes`, but we don't want to add platform specific paths.

On OS X there is also no clean way to do this. Homebrew doesn't have JNA, macports does but outdated/unmaintained. Just dropping jars to a directory/(the classpath) may work but is usually discouraged.

(low priority, just for future reference)

**Comment by markus2330** [comment]
Of course you can add platform specific paths, but they should be part of the CMake Find modules.

I am afraid we have to fork the FindJava.cmake anyway, it seems like we need to patch it so that jars get included.

**Comment by markus2330** [comment]
I think we can claim its cmake's fault (FindJava.cmake is not maintained by us).

But if someone needs this urgently, please reopen.
