### ISSUE TITLE
Devhelp(doc) generation for (g)elektra

### ISSUE THREAD

**Issue by raetiacorvus** [ElektraInitiative/libelektra#766]
This would be a nice to have for developing on Elektra in GNOME.
As far as i can tell this could be possible possible for the whole elektra api trough doxygen xml generation and XSLT transformation. Here is an example [xsl](https://cgit.freedesktop.org/dbus/dbus/tree/doc/doxygen_to_devhelp.xsl).
- [Devhelp](https://wiki.gnome.org/Apps/Devhelp)

TODO:
- [ ] doxygen xslt to devhelp for `libelektra`
- [ ] gtk-doc generation for `libgelektra`

**Comment by markus2330** [comment]
This is a good idea! Is devhelp integrated in your IDE? Aren't there standard tools to convert doxygen to devhelp?

**Comment by sirblackheart** [comment]
> This is a good idea! Is devhelp integrated in your IDE? 

Yes devhelp is integrated in [gnome-builder](https://wiki.gnome.org/Apps/Builder)

> Aren't there standard tools to convert doxygen to devhelp?

As far as i can tell the described way seems the default for doxygen projects. Doxygen already brings an xml generator we only need to provide the xsl and the [right commands.](https://www.slac.stanford.edu/grp/eg/minos/dist/dist_aux4/sigc++/libsigc++-2.2.4.2/build/doc-reference.am)

**Comment by markus2330** [comment]
Seems like a piece of cake, maybe you even find the commands implemented in CMake.

**Comment by sirblackheart** [comment]
Yes i just have to figure out how to get the xsl right, then we can use the existing doxygen html output. We also need to output xml but that is just a simple switch.

**Comment by markus2330** [comment]
Closed because of low priority, will be reevaluated after 1.0.
