### ISSUE TITLE
Building Elektra Qt Editor broken with: -DENABLE_DEBUG=ON

### ISSUE THREAD

**Issue by sirblackheart** [ElektraInitiative/libelektra#771]
```shell
/home/sirblackheart/build/aur/elektra-git/src/elektra/src/tools/qt-gui/src/treeviewmodel.cpp:653:14: error: use of undeclared identifier
      'theirs'; did you mean 'this'?
                printKeys (theirs, result, ours);
                           ^~~~~~
                           this
/home/sirblackheart/build/aur/elektra-git/src/elektra/src/tools/qt-gui/src/treeviewmodel.cpp:653:22: error: use of undeclared identifier
      'result'
                printKeys (theirs, result, ours);
                                   ^
```

**Comment by sirblackheart** [comment]
the debug functions here seem to be a leftover before "Update the qt-gui to use the merging kdb wrapper" bc38023e583636b39c0ec852d8ad1c181833f6d8

@markus2330 do you can think they can be dropped? Does the merging kdb wrapper handle them?  or should they be rewritten?

**Comment by markus2330** [comment]
Seems to be a leftover of #604. It should have been moved to kdbmerge.

Is it the only place where compiling with ENABLE_DEBUG fails? If yes please remove it. Otherwise we should fix ENABLE_DEBUG properly with a new logging system and leave ENABLE_DEBUG as unsupported for now.
