### ISSUE TITLE
Gnome Integration: GSettings keyname lack #version and profile

### ISSUE THREAD

**Issue by raetiacorvus** [ElektraInitiative/libelektra#775]
We should probably discuss possible solution for the lack of version and profile parts in GSettings keys.
Two possible solutions could be:
 * Assume that the first three subelements of a `GSettings` (e.g. `/org/gnome/gedit`) key will always name the application, where as keys bellow will be options. Then just add the /#0/current/ between both.
  * We would get keys conform to the `Elektra` convention
  * This will only works correctly if out assumption of the `GSettings` key names is met.
  * More complex string operation needed for conversion between `GSettings` and Elektra
  * No real benefit for GSettings as it does not really get any support of versions or profiles

* Use cascading on #version and profile. E.g. a `kdb set /org/gnome/gedit/preferences/editor/scheme "classic"` should automatically write to `/org/gnome/gedit/#current/current/editor/scheme` and the corresponding read should read from that name. #version should always point to the highest version number. current to the default profile.
  * We still would have to assume which parts of the keyname are application name and which are setting names.
  * Rather complex solution
  * GSettings would get version support trough the Elektra backend.

**Comment by markus2330** [comment]
profiles can be added by the profile plugin, i.e. as long as you honor the naming conventions, you automatically have profiles.

I think the version information would also be interesting for upgrading gsettings-binding itself.

**Comment by markus2330** [comment]
The first solution seems to be better. Please reopen if there is any further open question or you find any new important details.
