### ISSUE TITLE
Elektra Qt Editor: error on using menu `E_dit -> Edit ...` twice on same element

### ISSUE THREAD

**Issue by sirblackheart** [ElektraInitiative/libelektra#777]
`qrc:/qml/EditKeyWindow.qml:11: TypeError: Cannot read property 'metaValue' of null`

![peek 2016-06-11 15-31](https://cloud.githubusercontent.com/assets/1131371/15985329/9ea0f77c-2fe9-11e6-9363-96d0e36a5bb8.gif)

**Comment by 0003088** [comment]
When cancelling the window the selected node was set to 'null'. I changed that in fe18fbf22be675b1f3abb47c72c1f3e62b816b21. I cannot remember the exact reason for unselecting the node, so maybe this causes issues (I cannot think of one atm, but it's not out of the question)

**Comment by markus2330** [comment]
@sirblackheart can you confirm that fe18fbf fixes the problem? Sounds like an easy fix.

**Comment by sirblackheart** [comment]
Yes this fixes this specific issue. Thanks @0003088

**Comment by markus2330** [comment]
@sirblackheart What do you mean with "specific issue". Are there related issues?

@0003088 do you want to create a PR or should I simply comment out the line?

**Comment by sirblackheart** [comment]
There are some error messages i noticed while testing the fix but they are not related. I will open a issue after i had time to investigated it further. It seems to be related to metadata in the gsettings import.

`qrc:/qml/NewMetaKey.qml:58: ReferenceError: user is not defined`

**Comment by 0003088** [comment]
@markus2330 I'll create a pull request for the sake of traceability
