### ISSUE TITLE
Create meta data for every script

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#792]
With 0.8.17 we have a way to create meta data for scripts in order to find scripts more easily. https://github.com/elektrainitiative/libelektra/tree/scripts/README.md

Not every script currently has meta data though, please add it. As an example you can see scripts/configure-debian

**Comment by iandonnelly** [comment]
Few questions:

1. The brief should be short enough to fit in the normal terminal width on one line, correct?
2. For scripts with descriptions in the comments (like convert-fstab) should we leave these comments after the metadata?
3. What is the correct date format (DD.MM.YYYY or MM.DD.YYYY)?
4. What should I do when missing information?
5. For some I see the date is just Month and Year, how should I convert these? I can just use the first of the month so we have a consistent date format.

**Comment by markus2330** [comment]
Thank you for working on it!

1. Yes: brief should be a short sentence only, it should be printable within a line.
2. I think most comments can be some part of the metadata (as last resort some detail description), @KurtMi can help you with the decision where it should be, simply write here for questions.
3. in the example it looks like DD.MM.YYY (because the script was created in June), should be clarified by @KurtMi in the README.md though
4. Try to investigate in the git history, looking at the script or simply try it out. You can also ask here.
5. Yes, first of the month should be ok. The git history might have the exact day, too.

**Comment by markus2330** [comment]
Were my answers too brief or is everything clear now?

**Comment by markus2330** [comment]
Closed because of low priority.
