### ISSUE TITLE
svg module not added to COMPONENTS

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#796]
Did you try to compile Elektra if the svg component is not installed?
(I did not find a way to install it on Debian, but it might be possible at other systems and is certainly is possible if you compile Qt yourself because it is an add-on).

I think it might need to be listed in QCOMPONENTS, what do you think?

**Comment by sirblackheart** [comment]
We probably should make it optional, so if the module is not available you just can not use svg icon themes.

**Comment by sirblackheart** [comment]
and i think this is the svg module on debian: https://packages.debian.org/search?keywords=libqt5svg5

**Comment by sirblackheart** [comment]
and also dev: https://packages.debian.org/jessie/libqt5svg5-dev
