### ISSUE TITLE
Provide an OSX build?

### ISSUE THREAD

**Issue by thedrow** [ElektraInitiative/libelektra#810]
Does libelektra compile under OSX?
If it does, it'd be nice to be able to install it from Homebrew.

**Comment by markus2330** [comment]
Hi!

Thanks for asking. Elektra fully compiles and works under Mac OS X. Several developers are using Mac OS X themselves. Build Server see: https://travis-ci.org/ElektraInitiative/libelektra/branches

For Homebrew only a very basic formula is available here: https://github.com/fish2000/homebrew-praxa/blob/master/elektra.rb Unfortunately no further work was done, help would be very welcome, see #531

best regards,
Markus

**Comment by thedrow** [comment]
Thanks. I think this is a duplicate so I'll close this one.

**Comment by markus2330** [comment]
Elektra is now officially in homebrew, see #531
