### ISSUE TITLE
proposal: update AUTHORS

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#818]
Please bring AUTHORS to a better state:
- [ ] add yourself there
- [ ] add github user names there
- [ ] devel/test on (which systems you have)
- [ ] mark inactive people as such (1 year without any activity?)

**Comment by markus2330** [comment]
Please add yourself in AUTHORS!

**Comment by Namoshek** [comment]
Do we need a PR for this or can it be done directly?

**Comment by markus2330** [comment]
If you do not want to participate in the Hacktoberfest, then directly is also ok ;)

Btw. please also add "Github User" like Peter Nirschl already did.

**Comment by markus2330** [comment]
Done very nicely by @Namoshek, issue no longer needed.
