### ISSUE TITLE
API doc: keyIsUser & keyIsSystem are private

### ISSUE THREAD

**Issue by sirblackheart** [ElektraInitiative/libelektra#824]
The [current api](http://doc.libelektra.org/api/current/html/group__keytest.html) lists both `keyIsUser` and `keyIsSystem` as part of the functions that should be available as key test functions.

Using them in code results in a:
```
implicit declaration of function 'keyIsSystem' is invalid in C99
```

A short look at elektras header files shows that both are located in `kdbprivate.h` and therefore not included trough `kdb.h` as stated by libelektras [doc](http://doc.libelektra.org/api/current/html/group__keytest.html#details).

**Comment by markus2330** [comment]
Thank you, good catch!
