### ISSUE TITLE
remove elektraenv.sh

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#833]
While setting environment based on Elektra configuration sound like a good idea some time ago, I think it has become useless.

I think one can argue it got obsolete by `src/libs/getenv/`. Furthermore I have the impression it was never used by anyone.

Any opinions?

**Comment by sirblackheart** [comment]
Do i understand it correctly that it should be possible to achieve similar results with `src/libs/getenv/`. If so would it make sense to distribute a service file that can be enabled to use `elektrify-getenv` at boot or login as replacement for `elektraenv.sh`?

**Comment by markus2330** [comment]
Yes, you understand it correctly. At the moment `elektrify-getenv` only works for programs that use `getenv` and do not directly access into `environment`. But this can be changed (by also manipulating `environment`), together with @petermax2 work we would finally have secure ways to globally set the environment.

There are many ways to activate elektrify-getenv (elektrify-getenv wrapper, setting environment variable or permanently, securely and globally by changing /etc/ld.so.preload). Let us discuss tomorrow what exactly we could achieve with a service file.
