### ISSUE TITLE
gitresolver.so: undefined symbol: git_libgit2_shutdown

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#846]
On debian wheezy libgit2 seems to not have the symbol git_libgit2_shutdown

http://community.markus-raab.org:8080/job/elektra-gcc47-all/lastFailedBuild/consoleFull

```
libelektra-gitresolver.so: undefined symbol: git_libgit2_shutdown
```

Is there a easy fix (e.g. not doing a shutdown when libgit2 is old), or should we enforce some minimal libgit2 to be present?

**Comment by markus2330** [comment]
There are more, even on jessie:
```
src/plugins/gitresolver/gitresolver.c:139:2: warning: implicit declaration of function ‘git_libgit2_init’ [-Wimplicit-function-declaration]
  git_libgit2_init ();
  ^
Building C object src/plugins/hexcode/CMakeFiles/elektra-hexcode-objects.dir/hexcode.c.o
src/plugins/gitresolver/gitresolver.c: In function ‘elektraGitresolverGet’:                                                           
src/plugins/gitresolver/gitresolver.c:259:3: warning: implicit declaration of function ‘git_libgit2_shutdown’ [-Wimplicit-function-declaration]
   git_libgit2_shutdown ();
   ^
src/plugins/gitresolver/gitresolver.c: In function ‘addFileToIndex’:
src/plugins/gitresolver/gitresolver.c:369:2: warning: implicit declaration of function ‘git_index_add_frombuffer’ [-Wimplicit-function-declaration]
  git_index_add_frombuffer (index, &ie, git_blob_rawcontent (blob), git_blob_rawsize (blob));
  ^
```

**Comment by tom-wa** [comment]
i've had some linking problems too, seems like it's some issue with the library. i've used libgit2 from the debian unstable repositories, building it with your cmake script i had to run ldconfig manually again before it got it working. 
but i don't got those warnings at all. can you try to check out my old cmake script and try compiling it that way?

**Comment by tom-wa** [comment]
i'm using 
```
ii  libgit2-24:amd64                      0.24.1-2                          amd64        low-level Git library
ii  libgit2-dev:amd64                     0.24.1-2                          amd64        low-level Git library (development files)
```
but as i'm already said, the api is a mess. so i guess forcing a version would be the best options, because really doubt that the api is stable

**Comment by markus2330** [comment]
The warnings refer to header file where these functions are not found, this won't be fixed with a different linker invocation.

> so i guess forcing a version

Which version? Can we use the one from jessie, would be really nice to have support for current debian stable.

**Comment by tom-wa** [comment]
i'll try to get it running on my debian stable box (with `libgit-21`) but `git_index_add_frombuffer` is actually essential for this plugin to work. maybe i can find a workaround

**Comment by markus2330** [comment]
If `git_index_add_frombuffer` is essential functionality, we will simply require the version where it was introduced. If you find a workaround without much effort it would be nice though ;)

**Comment by tom-wa** [comment]
`git_index_add_frombuffer` allows you to add a blob. the other functions can only add files to the index (and those have to be inside the git repository). this is needed to add the temporary file without touching the actual files in the repository
the only workaround i could find was reimplementing that part.

seems like `git_index_add_frombuffer` was introduced in v0.24.1

**Comment by markus2330** [comment]
Ok, lets enforce this version then.

Can you check for the version or check for the symbol with a try_compile? (e.g. see augeas for usage)

**Comment by markus2330** [comment]
Update: most build jobs are affected by this problem:
http://community.markus-raab.org:8080/

would be great to have a try_compile which contains some minimal program which tests if libgit has everything needed.

**Comment by tom-wa** [comment]
i guess we can close this one ?

**Comment by markus2330** [comment]
Yes, thank you for the fix!

**Comment by IronicallySerious** [comment]
I am not sure how this was fixed after reading the comments above. Could someone brief a little on how this was fixed?

**Comment by markus2330** [comment]
@IronicallySerious sorry, I did not see this comment as it was written in an old and closed issue.

Iirc the fix is only about building on the build server. If you see the same error, it most likely means that your libgit is too old and we do not correctly detect that. Please open a new issue with more information so that we can help you.

**Comment by IronicallySerious** [comment]
Oh thanks I will try building with a newer version. If this persists then I will start a new issue thread with more info

**Comment by markus2330** [comment]
@IronicallySerious did it work for you? We also love to hear success stories :smiley:

**Comment by IronicallySerious** [comment]
I used the latest master and this issue hasn't appeared yet :)

**Comment by IronicallySerious** [comment]
I had shifted to building a static lib instead of a shared one because of my project requirements so this bug couldn't possibly appear in a setup like this

**Comment by markus2330** [comment]
Thank you for the update! Good to know that the static lib is still used.
