### ISSUE TITLE
renaming intercept open and getenv

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#849]
The configs, directories and naming of open and getenv should be unified:

- [x] make subdirectory intercept in bindings with subdirectories open and getenv
- [x] getenv should also be binding/intercept and not in libs

Please discussion first, no PR at current stage for:

- [x] rename config of open to /elektra/intercept/open and config of getenv /elektra/intercept/getenv (but still read `/env` for backwards compatibility)
- [ ] rename libelektraintercept.so to libelektraintercept-open.so and rename libelektragetenv to libelektraintercept-getenv.so (and create symlink libelektragetenv for compatibility)

**Comment by tom-wa** [comment]
>rename libelektraintercept.so to libelektrapreload-open.so and rename libelektragetenv to libelektrapreload-getenv.so

my only issue with those names is: they are way too long (not that libelektraintercept.so is any better)

>rename config of open to /intercept/open and config of getenv /intercept/getenv? (must be consistent to library names though)

sounds fine to me

>make subdirectory intercept in bindings which subdirectories open and getenv?

i'm fine with that too, it's also nice to have if we plan on making other syscall interception libraries later.

**Comment by markus2330** [comment]
Ok, then lets go for the name `intercept`, tasks see above. Can you start with the tasks for moving the `open` in the subdirectory `intercept`?

I also added `/elektra` as part of the configuration, I think we should prefix all our tools. Actually we should even prefix it with version and profiles, so it would be: `/elektra/intercept/open/#0/current`. What do you think?

> names are way too long

Yes, but they should both prefix `elektra` and `intercept` to not collide with others. We could go for `libelektraopen`: its unlikely that a elektra lib will be called that way and then we would not need to rename `libelektragetenv`.

**Comment by tom-wa** [comment]
since `intercept`/`open` also intercepts access and stat, should we change the name of `libelektraopen` to something else ?

**Comment by markus2330** [comment]
Yes, we could rename it to libelektrainterceptfs or libelektrainterceptfilesystem, ....
