### ISSUE TITLE
keyRel2 API robustness

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#856]
In keyRel2 the third argument (`which`) should be checked more. It is possible to set multiple bits in combination with bits that are not yet defined (leading to a lot of implementation defined behaviour problematic for further API evolution). Please check these cases (in particular more than one bit set) and return with `-1`.

Btw. you also mentioned that the elektraModules API can be improved, can you elaborate?

**Comment by tom-wa** [comment]
is #877 enough to close this issue ?
