### ISSUE TITLE
Clang compile errror in backendparser.cpp

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#860]
/home/peter/elektra-clang/src/libs/tools/src/backendparser.cpp:100:89: error: use of undeclared identifier 'c'
		    if (std::all_of (argument.begin (), argument.end (), [](char c) { return std::isspace (c) || c == ...
		                                                                                           ^
	/home/peter/elektra-clang/src/libs/tools/src/backendparser.cpp:100:95: error: use of undeclared identifier 'c'
		    if (std::all_of (argument.begin (), argument.end (), [](char c) { return std::isspace (c) || c == ...
		                                                                                                 ^
There seems so be a problem with clang. I ran the following commands directly on the build server:

    cmake -DPLUGINS="cachefilter;ccode;conditionals;constants;counter;crypto_botan;crypto_gcrypt;crypto_openssl;csvstorage;doc;dpkg;dump;enum;error;filecheck;fstab;glob;hexcode;hidden;hosts;iconv;ini;iterate;keytometa;line;lineendings;list;logchange;mathcheck;network;ni;noresolver;null;path;profile;regexstore;rename;resolver_fm_b_b;resolver_fm_hb_b;resolver_fm_hp_b;resolver_fm_hpu_b;resolver_fm_pb_b;resolver_fm_ub_x;resolver_fm_uhb_xb;resolver_fm_xb_x;resolver_fm_xhp_x;resolver_fm_xp_x;semlock;shell;simpleini;spec;struct;sync;syslog;template;timeofday;tracer;type;uname;validation;wresolver" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DKDB_DB_SYSTEM=/home/peter/elektra-clang/system -DCMAKE_INSTALL_PREFIX=/home/peter/elektra-clang -DBUILD_DOCUMENTATION=OFF ..
	run-make

**Comment by petermax2** [comment]
NOTE: no problem in my VM, no problem in the Jenkins build job.

**Comment by markus2330** [comment]
Can you post the clang version? Seems like lambdas are not fully supported here.

**Comment by petermax2** [comment]
peter@community:~$ clang --version
    Debian clang version 3.0-6.2 (tags/RELEASE_30/final) (based on LLVM 3.0)
    Target: x86_64-pc-linux-gnu
    Thread model: posix

**Comment by markus2330** [comment]
Yes, I think its simply too old. I would recommend 3.8, which we use for formatting, too. I think nobody has tested so far which is the oldest clang version that still works.

**Comment by petermax2** [comment]
It is the only available version on `build.libelektra.org` or am I mistaking? Anyway I wrote the suppression I needed by hand, so we can close the ticket.

**Comment by markus2330** [comment]
Yes, it currently is the only one. We can add further versions if someone tries which is the oldest, still-working version. Please add such information to #160.
