### ISSUE TITLE
proposal: kdbLookup

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#867]
As discussed with @KurtMi the main purpose of run-time logging would be to inspect which `ksLookup` an application is doing. To avoid all the issues a more general logging framework in the library would have, we could extend the API with `kdbLookup` where lookup-plugins (similar to global Plugins) can intercept every lookup call.

This way we could implement the current ksLookup printer that `kdb get`, and the context-awareness features in a way accessible to every application.

The proposed API is:
`Key * kdbLookup (KDB *kdb, KeySet *haystack, Key *needle);`

What do you think?

**Comment by KurtMi** [comment]
So you propose to not implement a logger and instead to add a hook to the lookup?

If the hook acts like a gobal hook, meaning that we only add one or two new positions for the globalhooks like `prelookup` and `postlookup` it would be fine.

I do not understand why we need a new Api for that? And what is context-awareness?

**Comment by markus2330** [comment]
Hi! There is no plan change for the static logger. The new API and hooks is for run-time logging (and more) of `ksLookup`. Maybe we even only need a single position `lookup` (no pre/post) with the hook already present, see keyset.c line 1896. The current (internal) ksLookup plugin API is:
```
Key * elektraLookupHook (KeySet * ks, Key * key, Key * found, option_t options)
```
For examples see src/tools/kdb/get.cpp. Or do you think we can achieve more with `pre/post`?

> I do not understand why we need a new Api for that?

The API is needed because from `ksLookup` you cannot get references to plugins which live in `kdb`.

> And what is context-awareness?

Context awareness is (very briefly) explained in src/libs/getenv/README.md, section CONTEXT. More info, e.g. in ["Unanticipated Context Awareness for Software Configuration"](http://www.libelektra.org/ftp/papers/icis2016unanticipated.pdf)

**Comment by markus2330** [comment]
Additionally to the main hook, pre/post lookup hooks might be useful so that is clear for a plugin which lookup hook was the first/last (e.g. to do preparations/finalizations within the plugin).

The pre/post hooks might also be useful as locking solution when applications exclusively use kdb* functions (or work with the same lock while tampering with the data structures, i.e. ks* key* methods).

**Comment by markus2330** [comment]
Maybe for Elektra 2.0, I close it for now.
