### ISSUE TITLE
proposal: kdbValidate

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#869]
Currently, applications can only write out configuration without any way to influence the behaviour of `kdbSet`. Two valid use cases are not possible:
1. only checking if the KeySet is valid
2. only checking if the user could write out the config (permission check)

For 2. there is a workaround by reading `system/elektra/mountpoints` and then run `kdbGet` for each mountpoint to get the file name and do `access (2)` on it.

For 1. no workaround exists, thus a solution would be more urgent.

One way to implement the feature would be to add metadata to the `parentKey` in `kdbSet` and influence the `kdbSet` behaviour in a way that `kdbSet` only executes `validation` plugins (e.g. by checking if their contract states that the provide `validation`). @tom-wa Can you benchmark the overhead? (This would be an interesting research question)

Another way would be additional API, e.g. `int kdbValidate (KDB *kdb, KeySet *ks, Key *parentKey);`.

**Comment by Namoshek** [comment]
I'm clearly a fan of the latter, as this is the more explicit way of offering functionality. How this function is implemented behind the scenes, e.g. by adding meta-data and leaving the job to the `kdbSet` function as already mentioned by you, could probably discussed further. But if someone needs such functionality, it is a lot easier to look for a proper function than stumbling across an option concerning meta data and (dirty) workarounds by accident. Looking for such meta-features is really time consuming in the end.

**Comment by markus2330** [comment]
Yes, based on previous discussions with `KDB_O_POP` in `ksLookup` you are certainly right.

The question is more if this should be in a core API or if we add such syntactic sugar (like ksPopByName) to `libease`. If we also provide `kdbIsWritable`, `kdbHasChange`,... the API might blow up very quickly. This is no issue for `libease`, but can be a big issue for the core libraries which also should be small and efficient (the linker has a lot to do if many symbols are present in a library).

**Comment by markus2330** [comment]
I'll close the issue as it as a better practice to write out configs early. (And especially it is not a good idea to write it out when the application quits.)
