### ISSUE TITLE
kdb global-mount: overwrites mounted plugins

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#886]
Mounting multiple plugins globally with `kdb global-mount` results in only the most recently mounted plugin being executed.

I expected multiple global mounts not to overwrite previous mounts.

When I run:

```
kdb global-mount dbus
kdb global-mount tracer
```

the dbus plugin is lost/overwritten by tracer.
- Elektra Version: master

**Comment by markus2330** [comment]
Thanks for reporting! Can you also report expected behavior? (maybe also in a non-trivial setup when you have 2 plugins and want add 2 others)

**Comment by tom-wa** [comment]
the issue is probably the global-mount tools description running `kdb global-mount dbus tracer` instead seems to work fine

**Comment by markus2330** [comment]
The docu doc/help/kdb-global-mount.md says "Note that previous calls of `kdb global-mount` will be overwritten.". Any suggestions how it can be improved?

But I would like to discuss what @mpranj expected, I agree that the overwrite semantics are maybe not what a user expects.

**Comment by markus2330** [comment]
Btw. and it seems like even @tom-wa runned in the trap that `kdb global-mount` will overwrite plugins, so there is definitely a gap in user expectations here.
