### ISSUE TITLE
The Order Preserving Minimal Perfect Hash Map Build Integration

### ISSUE THREAD

**Issue by KurtMi** [ElektraInitiative/libelektra#887]
The Order Preserving Minimal Perfect Hash Map (`OPMPHM`) is a very special kind of hash map. In Order to make a KeySet ready for lookups a build process is need. This build process in mainly divided in three steps. This Issue describes the needed tasks to Integrate the `OPMPHM` build process in Elektra.

### General
- [x] think about reusability of code

### Mapping
- [x] add ratio param
- [ ] add ksLookup flag for explicit hash build
- [x] add random function
- [x] add hash function
- [x] add graph debug tool graphviz as soft dept
- [ ] init a fast and nice bipartite graph data structure
- [ ] test cases
- [x] check heap function typdef
- [ ] try to find a more platform independent random function
- [ ] try to find a more platform independent seed init function
- [ ] fix  endian at hashfunction
### Order
- [ ] how to bring data to searching phase without malloc
- [ ] add points here!
### Searching
- [ ] how to bring data to searching phase without malloc
- [ ] add points here!

**Comment by markus2330** [comment]
Thank you, very nice explanation! I am looking forward to the visualizations of the mappings!

Btw. please do not add any configuration for `OPMPHM` to cmake, it only confuses package maintainers and people with the needs to modify such internals, will patch the source anyway. Simply add it as constant to the beginning of kdbprivate.h.

**Comment by KurtMi** [comment]
> Thank you, very nice explanation! I am looking forward to the visualizations of the mappings!

The visualization is more for debug purpose later on in the ordering and searching. The mapping constructs only this bipartite graph and I found out that drawing a bipartite graph with 16+ vertices over and over is very annoying.

**Comment by KurtMi** [comment]
Due to plan change, this issue will be closed. The new one is #1487.
