### ISSUE TITLE
global plugins: plugin configuration

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#888]
Here's a snippet of how the configuration of global plugins currently works.
```
< set system/elektra/globalplugins/postcommit list
< set system/elektra/globalplugins/postcommit/user list
< set system/elektra/globalplugins/postcommit/user/placements ""
< set system/elektra/globalplugins/postcommit/user/placements/set "presetstorage presetcleanup precommit postcommit"
...
```

The first key means that we want to mount the list plugin at position postcommit globally. The other keys are the plugin configuration.

While this looks nice when configuring one plugin for one position, it can be confusing to mount it to other positions. For instance, adding the key:
```
< set system/elektra/globalplugins/precommit list
```
would now hook the same list plugin with the same configuration from above to a new point. Any new/additional plugin configuration of the list plugin is ignored, because the list plugin is already loaded.

I propose the following:
Separate plugin configuration from global placements configuration. (e.g. `system/elektra/globalconfig/<pluginname>/config_below`)

[NB: this is **just** an idea, I thought I'd throw it in the proposals pot in case someone cares]

**Comment by markus2330** [comment]
> Here's a snippet of how the configuration of global plugins currently works

I think there is more to it, this is the way the mount tool configures the list plugin. @tom-wa Can you describe (please in a form suitable for documentation) how the globalplugins and list plugin can be configured? (How does the "system" config work? Shouldn't it be like @mpranj proposes?)

**Comment by mpranj** [comment]
I'm not sure if this answers your question, but the "system" config is also below ` system/elektra/globalplugins/postcommit/`. At least according to the implementation.

I took the same semantics - from the implementation - and adapted it to be able to mount subpositions like `postcommit/init` and such. This is the point where the plugin configuration gets really weird.

In other words you need to place the `list` plugin config exactly at the first key that the mount tool will hit upon iteration. Otherwise the config is ignored. That's why `globaltest.esr` looks the way it looks.

**Comment by tom-wa** [comment]
the whole configuration thing stems from how the `list` plugin works.
currently it's just the `list` configuration as described in `list/README.md` appended to `system/elektra/globalplugins` at the first placement.

but imho the list plugin should be split into a global and a normal version anyway, because the global plugin has/needs different placements than the list plugin and probably some other changes as well.

>In other words you need to place the list plugin config exactly at the first key that the mount tool will hit upon iteration. 

isn't that the same for all plugins / how it works generally ?

**Comment by markus2330** [comment]
> isn't that the same for all plugins / how it works generally ?

For backends there is explicit syntax that "constructs" new plugins and refers to already constructed plugins.

**Comment by tom-wa** [comment]
ok, so how exactly should the key layout look like ? just move the config from the first placement to `system/elektra/globalconfig/pluginname` and copy it  back in elektraMountGlobals ?

**Comment by markus2330** [comment]
@mpranj Can you make a proposal how it should look like?

**Comment by mpranj** [comment]
I'm trying to finish a draft for my PR based on how it works already, so please don't change anything now. I especially revamped `elektraMountGlobals `. This was more of a question / proposal I could then implement myself if anyone is interested.

I already made a rought proposal above which preserves the same functionality that is possible now.
> Separate plugin configuration from global placements configuration. (e.g. system/elektra/globalconfig/<pluginname>/config_below)

I would just move config to this separate place, and place only instances in `system/elektra/globalplugins`. This would make it more clear that it's only possible to have one configuration per plugin at a time.

A better way to implement this might be a multi-config solution.
Example: use multiple configs
```
system/elektra/globalconfig/list
system/elektra/globalconfig/list/config1
system/elektra/globalconfig/list/config1/user ...
...
system/elektra/globalconfig/list/config2
system/elektra/globalconfig/list/config2/user ...
...
```

Then instantiate whichever configuration you need at a placement:
```
system/elektra/globalplugins/precommit list
system/elektra/globalplugins/precommit/list "config1"
system/elektra/globalplugins/postcommit list
system/elektra/globalplugins/postcommit/list "config2"
```

I'd very much like to finish the draft for my PR first. You can then take a look and we can discuss this proposal.

**Comment by markus2330** [comment]
Seems to be fixed now. Please reopen if there are any further issues.
