### ISSUE TITLE
crypto plugin: gpgme plugin variant

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#896]
# Feature

The `gpgme` plugin is created to solely uses the `gpgme` library for crypto operations.

**Comment by petermax2** [comment]
This is a follow-up task to #892 .

**Comment by petermax2** [comment]
We have two options here:

1. We use the master password and call the gpg binary to perform symmetric encryption with the regular master password.
2. We do not generate and use a master password for crypto_gpg but instead we call the "default" --encrypt / --decrypt option of gpg.

I would prefer number 1 because of better comparability to the other compilation variants. However, number 2 might be cleaner and more secure (no passwords are written over the pipes).

@markus2330 What is your opinion on this matter?

**Comment by markus2330** [comment]
You are right that a plugin variant `crypto_gpg` doing something completely different than the other variants would be strange. Do you really need yet another comparison? 3 variants should be enough? I do not think that we need a benchmark to show us that executing processes takes longer than library calls. Describing a full setup (case study) with getenv would be much more interesting!

What about having a separate plugin `gpg` that uses `--encrypt` and `--decrypt` or even `--sign`?

**Comment by petermax2** [comment]
> I do not think that we need a benchmark to show us that executing processes takes longer than library calls.

Agreed.

> What about having a separate plugin gpg that uses --encrypt and --decrypt or even --sign?

I was thinking about separate plugins for encryption/decryption and signing. Like having sign_gcrypt, fsign (or fverify, not sure about the name yet). I would prefer to implement the signature operations outside the scope of my Bachelor's Thesis.
