### ISSUE TITLE
Base64 Filter Plugin

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#897]
# Situation / Problem

The crypto plugin stores encrypted data as-is in binary format. This is not useful when working with text-based configurations like ini.

# Expected Behaviour (Proposal)

A configuration option controls wheter or not the encrypted content will be encoded in Base64.

# Solution

A filter plugin that encodes binary data to Base64 format during `kdb set`. The plugin decodes those values back to its original form at `kdb get`.

**Comment by petermax2** [comment]
This is a follow-up task to #892 .

**Comment by markus2330** [comment]
Btw. this should be a separate plugin with separate meta data. base64 encoding is useful in many other cases, too.
