### ISSUE TITLE
crypto plugin: security levels

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#899]
# Situation / Problem

At the moment the configuration of the crypto plugin exposes internal details about cryptographic operations like:
- PBKDF2 iteration count
- length of the master password
# Expected Behaviour (Proposal)

Instead of exposing those details we provide built-in security levels:
- low (sufficiently secure?)
- medium
- high
# Questions
- Do you want that? Is this useful to anybody?
- What is sufficiently secure? 

Maybe we need another security role model. I am open for input.

**Comment by petermax2** [comment]
This is a follow-up task to #892 .

**Comment by markus2330** [comment]
What about give some numbers of how secure it is, e.g. money https://joeyh.name/code/keysafe/ or years to break it?

Or alternatively, what about deriving the security level from the gpg key? If it only has a small number of bits more iterations and a longer master password would be useless anyway, wouldn't it?

**Comment by markus2330** [comment]
I set it to low priority because people are unlikely to use something else than the default. So please choose the default carefully to make it as secure as possible with acceptable performance impact.
