### ISSUE TITLE
"Resolved" label ?

### ISSUE THREAD

**Issue by tom-wa** [ElektraInitiative/libelektra#901]
since some issues are broad or evolved into broader issues over time closing them via commit messages isn't always the best option. 
so i propose adding a `Resolved` label to tag those.

**Comment by markus2330** [comment]
While I think we should avoid issues becoming broader (but split them), I like the idea to have labels instead of immediately close them.

But is it possible to set labels from commit messages? Or can we reconfigure github so that `fix #123` will add the resolved label to `#123`?

**Comment by markus2330** [comment]
Thanks for reporting! The outcome is that we split issues and track larger issues with subissues (with the `- [ ]` feature). Furthermore we added labels "work in progress" and "ready to review" which basically achieves the same as "resolved".
