### ISSUE TITLE
Test Internal functions not starting with elektra, kdb, ks

### ISSUE THREAD

**Issue by KurtMi** [ElektraInitiative/libelektra#909]
- [ ] check if other functions need this feature (except `elektraMount`)
- [ ] add tests for the found functions

**Comment by markus2330** [comment]
Thank you!

**Comment by KurtMi** [comment]
@markus2330 I found a way to solve this:

* the function that should be tested can not be `static` or `inline`
This is very bad because internal things mostly start with `static`
(But this point was clear from the beginning)

* the function that should be tested needs to be declared in the test file.
I think the declaration will be removed from the header files also, so I need to add it.

* the c file in which the function that should be tested is defined must be added.

What do you think?

**Comment by markus2330** [comment]
> the function that should be tested can not be static or inline

You can also test static/inline functions if you include the C file (e.g. with `#include <../abc.c>` in the beginning of the test driver).

> the function that should be tested needs to be declared in the test file.

Please use a separate header file for functions that are declared for the sole purpose of being tested.

> the c file in which the function that should be tested is defined must be added.

Yes, except for the `#include` case.

**Comment by KurtMi** [comment]
```
int elektraMountOpen (KDB * kdb, KeySet * config, KeySet * modules, Key * errorKey);
int elektraMountDefault (KDB * kdb, KeySet * modules, int inFallback, Key * errorKey);
int elektraMountModules (KDB * kdb, KeySet * modules, Key * errorKey);
int elektraMountVersion (KDB * kdb, Key * errorKey);
int elektraMountGlobals (KDB * kdb, KeySet * keys, KeySet * modules, Key * errorKey);
int elektraMountBackend (KDB * kdb, Backend * backend, Key * errorKey);

Key * elektraMountGetMountpoint (KDB * handle, const Key * where);
Backend * elektraMountGetBackend (KDB * handle, const Key * key);
```
Are all those those functions `elektraMount` ?

**Comment by markus2330** [comment]
I do not understand your question.

But all of them are internal only, so you can hide them if you find a way.

**Comment by KurtMi** [comment]
Ok, then the work in #1061 should be fine, more commits coming soon.

**Comment by KurtMi** [comment]
Should not be all function in `src/include/kdbprivate.h` only internal?

**Comment by KurtMi** [comment]
I found a passage with a lot (elektra|ks|kdb) functions in it in the kdbprivate.h:444 with the title:
```
/***************************************
 *
 * Not exported functions, for internal use only
 *
 **************************************/
```
I hope not all of these need to be made internal?

**Comment by markus2330** [comment]
I am afraid nearly all of them actually are. I did not find an exception in a quick look-through.

Actually you do not really rename them, you can also list them in src/libs/elektra/libelektra-symbols.map

**Comment by KurtMi** [comment]
I decided to make the job right and started renaming some core data structs (in #1062 , #1063, #1064).
We should merge those and then continue, otherwise this operation gets messy.

**Comment by KurtMi** [comment]
Are the functions in `kdbhelper.h` also only internal?

**Comment by markus2330** [comment]
> I decided to make the job right

Thanks, that is great. Can you check if your work reduces the size of the binary?

Btw. if possible also add static (if only called within same file) or even remove the function (if not called at all).

> Are the functions in kdbhelper.h also only internal?

No, they are used by plugins and other libs.

**Comment by KurtMi** [comment]
> Thanks, that is great. Can you check if your work reduces the size of the binary?

Which binary, the test binarys?
When yes, they got bigger, a little bit.

```
Before rename:
-rwxr-xr-x  1 root root  89K Nov  3 12:51 test_backend
-rwxr-xr-x  1 root root 288K Nov  3 12:51 test_mount
-rwxr-xr-x  1 root root 266K Nov  3 12:51 test_mountsplit
-rwxr-xr-x  1 root root  64K Nov  3 12:51 test_split
-rwxr-xr-x  1 root root 215K Nov  3 12:51 test_splitget
-rwxr-xr-x  1 root root 340K Nov  3 12:51 test_splitset
-rwxr-xr-x  1 root root 269K Nov  3 12:51 test_trie

After rename:
-rwxr-xr-x  1 root root 122K Nov  3 12:56 test_backend
-rwxr-xr-x  1 root root 388K Nov  3 12:56 test_mount
-rwxr-xr-x  1 root root 366K Nov  3 12:56 test_mountsplit
-rwxr-xr-x  1 root root 165K Nov  3 12:56 test_split
-rwxr-xr-x  1 root root 315K Nov  3 12:56 test_splitget
-rwxr-xr-x  1 root root 444K Nov  3 12:56 test_splitset
-rwxr-xr-x  1 root root 306K Nov  3 12:56 test_trie
```
> Btw. if possible also add static (if only called within same file) or even remove the function (if not called at all).

I will see if we can make some functions static or delete them.

**Comment by markus2330** [comment]
>  Which binary, the test binarys?

Sorry, no the library libelektra. The tests obviously got larger (c code is included) but nobody cares about their size.

> I will see if we can make some functions static or delete them.

Thank you!

**Comment by KurtMi** [comment]
> Sorry, no the library libelektra. The tests obviously got larger (c code is included) but nobody cares about their size.

Ok, the following files got smaller (output of `ls -s`)

```
from  260 libelektra-kdb.so.0.8.18
to  256 libelektra-kdb.so.0.8.18
from 452 libelektra.so.0.8.18
to 448 libelektra.so.0.8.18
```

**Comment by markus2330** [comment]
This is great, thanks for this! @haraldg was looking forward to such a cleanup!

**Comment by haraldg** [comment]
Indeed. Thanks from me too!

**Comment by KurtMi** [comment]
> I will see if we can make some functions static or delete them.

Done in #1066, I noticed some where untested, documented here #1067.

**Comment by markus2330** [comment]
Thank you, great work!
