### ISSUE TITLE
warnings in passwd plugin with musl

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#911]
@tom-wa Can you check if the passwd plugin works with musl?

Background: On cross compilation the detection might find that the symbols exist, but on the target system they might not exist. See https://github.com/openwrt/packages/pull/3120

**Comment by haraldg** [comment]
I think if the symbols don't exist the target build would fail.

The openwrt issue was my bad caused by an unfortunate combination of two bugs.

**Comment by tom-wa** [comment]
can't build it with musl, i'm stuck at
```
Linking CXX executable ../../bin/testabi_key
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
collect2: error: ld returned 1 exit status
tests/abi/CMakeFiles/testabi_key.dir/build.make:92: recipe for target 'bin/testabi_key' failed
```

**Comment by markus2330** [comment]
What did you try? musl on debian or openwrt? If on debian, see scripts/configure-debian-musl

**Comment by tom-wa** [comment]
building works with scripts/configure-debian-musl, but i get some warnings
```
/home/thomas/Dev/libelektra/src/plugins/passwd/passwd.c: In function 'elektraPasswdGet':
/home/thomas/Dev/libelektra/src/plugins/passwd/passwd.c:138:16: warning: implicit declaration of function 'fgetpwent' [-Wimplicit-function-declaration]
  while ((pwd = fgetpwent (pwfile)) != NULL)
                ^~~~~~~~~
/home/thomas/Dev/libelektra/src/plugins/passwd/passwd.c:138:14: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  while ((pwd = fgetpwent (pwfile)) != NULL)
              ^
/home/thomas/Dev/libelektra/src/plugins/passwd/passwd.c: In function 'writeKS':
/home/thomas/Dev/libelektra/src/plugins/passwd/passwd.c:248:4: warning: implicit declaration of function 'putpwent' [-Wimplicit-function-declaration]
    putpwent (pwd, pwfile);
    ^~~~~~~~
```

**Comment by tom-wa** [comment]
```
 % grep fgetpwent /usr/include/x86_64-linux-musl/pwd.h
struct passwd *fgetpwent(FILE *);
```

**Comment by markus2330** [comment]
Would be interesting if the plugin works. It is, however, not release critical (is an experimental plugin anyway).

**Comment by tom-wa** [comment]
@markus2330 do you mind if i just turn off the warnings ? it's _SVID_SOURCE (some older freebsd), __USE_MISC (linux) , _GNU_SOURCE (musl), ... depending on the system.

**Comment by tom-wa** [comment]
i'm sure it works, the functions are present in musl. but i can't really test it because the musl build is not working for me:
```
% kdb
kdb: error while loading shared libraries: /usr/lib/x86_64-linux-gnu/libc.so: invalid ELF header
```

**Comment by markus2330** [comment]
Ok, I keep the ticket open for fixing the warnings...

**Comment by ingwinlu** [comment]
It segfaults on musl. The functions exist but they do not get auto feature enabled as with glibc. see #2075 .

**Comment by markus2330** [comment]
We now have regressions test with musl (Alpine Linux).
