### ISSUE TITLE
fcrypt Plugin - encryption of whole files

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#914]
# Goal

A plugin that encrypts entire configuration files using GPG.

**Comment by petermax2** [comment]
@markus2330 The placement for this plugin would be `postcommit` (encryption of the whole file after it has been written) and `pregetstorage` (decryption before any storage plugin reads from the file). Is that correct?

How do I get the filename (mount-point) for the current backend within the plugin?

**Comment by petermax2** [comment]
The path to the file seems to be stored directly in `parentKey`.

**Comment by petermax2** [comment]
The placement `pregetstorage postcommit` seems to be good. Please confirm my summary, just to be sure.

**Comment by petermax2** [comment]
First prototype d5f4a028da86b990351685eeb19a0aac3f61a99e .

The encryption works but `kdb get` is failing.

**Comment by markus2330** [comment]
pregetstorage is ok, but postcommit is too late, it should be after setstorage, but before commit (when encryption fails, the commit should fail).

Yes, filename should be in parentKey, but please please check if it is really there. There were several bugs where in some positions the file name was not there. @mpranj will write regression tests for this (global plugins easily interfere with the file name and might break things).

**Comment by petermax2** [comment]
Speaking of error messages: could you explain what `kdb` is trying to tell me? :) 

    pnirschl@elektrabuild:/usr/src/libelektra/build$ ./bin/kdb mount test.ini system/t fcrypt /gpg/key=$KEY 
    The command mount terminated unsuccessfully with the info:
    Too many plugins!
    The plugin fcrypt can't be positioned to position precommit anymore.
    Try to reduce the number of plugins!

    Failed because precommit with 7 is larger than 6

**Comment by markus2330** [comment]
The mount tool currently has a limitation on how many plugins it can place per position (I am afraid this cannot be fixed within next release, but hopefully in the release after that). So you need to avoid that the sync plugin is added (which is not recommended!) by setting an empty string to `/sw/elektra/kdb/#0/current/plugins`.

**Comment by petermax2** [comment]
Thank you for the information! Mounting still does not work.

    ./bin/kdb set /sw/elektra/kdb/#0/current/plugins "" 
    Using name user/sw/elektra/kdb/#0/current/plugins
    Create a new key user/sw/elektra/kdb/#0/current/plugins with string 
    ./bin/kdb set system/sw/elektra/kdb/#0/current/plugins "" 
    Create a new key system/sw/elektra/kdb/#0/current/plugins with string 
    ./bin/kdb mount test.ecf system/t fcrypt /gpg/key=$KEY
    The command mount terminated unsuccessfully with the info:
    Too many plugins!
    The plugin fcrypt can't be positioned to position commit anymore.
    Try to reduce the number of plugins!

    Failed because commit with 8 is larger than 7

**Comment by petermax2** [comment]
Ah, but it works as `precommit` plugin now.

**Comment by petermax2** [comment]
Is a placement like `pregetstorage postgetstorage precommit` viable? I have to re-encrypt the file after `getstorage` is done. Otherwise the file stays decrypted after each `kdb get` call. It is only encrypted after calling `kdb set`.

How do I distinguish between `pregestorage` call and `postgestorage` call?

**Comment by markus2330** [comment]
> pregetstorage postgetstorage precommit

Yes, perfect. (commit, as I read in your second error message, does not make sense: commit is done by the resolver)

>  have to re-encrypt the file after getstorage is done.

You could also keep the encrypted file (e.g. renamed with .gpg) and rename it back on success/error.

From security point of view it would be even better to unlink the file within pregestorage and use something like `/dev/fd/<num>` instead, but I am afraid this needs changes in resolver and kdb plugin execution logic.

> How do I distinguish between pregestorage call and postgestorage call?

You need to track the state (simple counter is enough, see wresolver pk->state) with a variable in the plugin data. Do not forget to reset the state in case of errors.

**Comment by petermax2** [comment]
> From security point of view it would be even better to unlink the file within pregestorage and use something like /dev/fd/<num> instead, but I am afraid this needs changes in resolver and kdb plugin execution logic.

Very interesting concept! It would, however, only run on systems providing the `dev` filesystem (thinking of OpenBSD and so on). For Linux it would be a great thing. I do not want to touch neither the resolver nor the `kdb get` logic. :)

**Comment by markus2330** [comment]
Yeah, for now it is enough if we mention it as security consideration in the README.md.
