### ISSUE TITLE
HTTP API documentation

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#917]
## Constraints

- human readable (Markus, Marvin)
- free software (Markus)
- separation of data modeling and API description (Marvin)

## Considered Alternatives

- Swagger (to Java centered?)
- [apiary](https://apiary.io/) before, it looks nice and uses a [markdown based syntax for writing api blueprints](https://apiblueprint.org/). There's also a [CLI tool](https://github.com/apiaryio/apiary-client) if we don't want to use their service.
- api blueprint standard called [RAML](http://raml.org/).

## Notes

@omnidan @Namoshek #829

**Comment by Namoshek** [comment]
I think we already got rid of swagger as option in our previous discussion. The other two options look quite similar, although I personally like the syntax of API blueprints a bit more (especially after looking at their [examples](https://github.com/apiaryio/api-blueprint/tree/master/examples)) and it also looks more similar to our current documentation style. I also like the option to define request and response schemata and not only plain examples (or I simply didn't find this option for RAML, not sure). It also supports separation of data objects from the API description (i.e. reusable descriptions).

**Comment by omnidan** [comment]
I agree with everything @Namoshek said and wanted to add that apiblueprint is also MIT licensed (open source constraint) and there is a lot of [tooling available](https://apiblueprint.org/tools.html), which for example makes it possible to [run automatic tests](https://dredd.readthedocs.io/en/latest/) (the same tool also supports swagger, though). Swagger seems to use YAML. I would prefer markdown as it fits our current documentation more.

**Comment by markus2330** [comment]
Yes, agreed! Thank you for summing up everything here. @Namoshek Can you make a PR for having this content in doc/decisions?

@omnidan So you can start rewriting #912 then, please also work in the feedback you got there.

**Comment by Namoshek** [comment]
Should be ok now. If further questions arise, issue can be reopened!
