### ISSUE TITLE
helper function to get exported plugin symbol

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#922]
As @petermax2 proposed we should have a helper function in libease that returns a function pointer from an exported plugin symbol.

API could be:
`func_t elektraModulesGetFunction(Plugin * plugin, const char * name)`

for get/set and so on there could be an optimization to get the function without getting the contract before.

**Comment by petermax2** [comment]
@markus2330 hasn't this ticket been closed by #1548 ?

**Comment by markus2330** [comment]
Yes, there was even an update on this API already. (Errors are now passed to caller).

Thanks for reminding me to close the ticket!
