### ISSUE TITLE
cmake issues compiling passwd

### ISSUE THREAD

**Issue by tom-wa** [ElektraInitiative/libelektra#924]
seems like my approach for detecting if fgetpwent and putpwent are present doesn't work
```
try_compile(HAS_FGETPWENT "${CMAKE_BINARY_DIR}" "${PROJECT_SOURCE_DIR}/src/plugins/passwd/hasfgetpwent.c")
try_compile(HAS_PUTPWENT "${CMAKE_BINARY_DIR}" "${PROJECT_SOURCE_DIR}/src/plugins/passwd/hasputpwent.c")

add_plugin (passwd
	SOURCES
		passwd.h
		passwd.c
	COMPILE_DEFINITIONS
		HAS_FGETPWENT;HAS_PUTPWENT
```
@markus2330 any idea whats wrong here ?

**Comment by markus2330** [comment]
try_compile would be executed 3 times, try to only do it within DEPENDENCY_PHASE.

What are you trying to solve here?

Is this different to  #911?

Btw. the label "bug" suggests you describe a problem in Elektra, but it seems more like you have a question about cmake?

**Comment by tom-wa** [comment]
it actually screwed up the build process on OpenBSD and NetBSD for me. 

i'm trying to test if `fgetpwent` and `putpwent` are present. musl seems to support both.

**Comment by markus2330** [comment]
> it actually screwed up the build process on OpenBSD and NetBSD for me. 

What do you mean by "it", do you mean the change described in this issue's top post?

I think its better to discuss about code changes in PRs.

**Comment by tom-wa** [comment]
tried building the `passwd` plugin with `fgetpwent` and `putpwent` on systems not supporting those functions and (obviously) failed linking.

**Comment by tom-wa** [comment]
@markus2330 any idea what to do here ?

**Comment by markus2330** [comment]
Why is this obvious? In case of `fgetpwent` and `putpwent` missing the symbols should not be used? What was the linker error? Is HAS_FGETPWENT set incorrectly?

**Comment by tom-wa** [comment]
> In case of fgetpwent and putpwent missing the symbols should not be used?

yes.

> Is HAS_FGETPWENT set incorrectly?

seems so, but i'm not sure what exactly is wrong here.

**Comment by markus2330** [comment]
Seems like COMPILE_DEFINITIONS sets HAS_FGETPWENT;HAS_PUTPWENT without their value being dependent of the success of try_compile. HAS_FGETPWENT is TRUE or FALSE and can be accessed by ${HAS_FGETPWENT} in CMakeLists.txt.
