### ISSUE TITLE
Testing of REST APIs

### ISSUE THREAD

**Issue by Namoshek** [ElektraInitiative/libelektra#931]
Elektra is currently getting two REST APIs from projects, which of course can be unit tested in the background (internal services & functions). But to provide more stable software it would probably be a good idea to test the services also through their real REST APIs by making real HTTP calls.

So we should make a decision:
- Test services also through their public API?
- What software to use (testing suite)?
- When to use (automatically or not)?

Supportive questions:
- Do we have already something in use that could be used for such tasks?
- If not, any experience with software that could be used for it?
- Specific software that uses API Blueprints?

@markus2330 @omnidan

**Comment by Namoshek** [comment]
I tried installing [Dredd](https://github.com/apiaryio/dredd) on my debian VM, but I had no success so far. I'll investigate it further because it sounds very promising.

**Comment by omnidan** [comment]
The most interesting scenario would be spinning up an instance of the API and testing that in the CI pipeline (so that every time we send a PR for the project, an instance of the updated API is started and tested). I haven't used any tools for testing APIs yet, but dredd seems nice and works well with api blueprints (which we've already decided to use).

> I tried installing Dredd on my debian VM, but I had no success so far. I'll investigate it further because it sounds very promising.

Make sure you're running the latest nodejs version (at least v6.x.x). Then simply doing `npm install -g dredd` should work. If it doesn't, let me know the error output and I'll see what I can do :wink:

**Comment by Namoshek** [comment]
I got it installed now. The reason was that I only installed `npm` via `apt-get install npm`, but not nodejs. I removed it and installed `nodejs` as explained on their website, that worked well. :+1:

Your idea about CI sounds good, but we should not create CI dependent tests in my opinion (CI can change). Of course these servers should run the tests when building the services, but it would be better if we could arrange the tests via CMake or other test scripts so that we can run them locally the same way. I don't know what software/framework you'll be using for your REST service, but for CppCMS which I'm using it would be quite easy to use a second test-configuration with special ports and stuff that would allow for testing via dredd easily (only a guess, that is no actual experience yet).

**Comment by markus2330** [comment]
Thanks for the proposal: yes we should run API tests against the started instances.

If we do not find a more appropriate tool, I would suggest we use the shellrecorder and curl to do the tests. So we simply execute curl and run regressions tests that the next version of the API still delievers the same curl output (inclusive the http headers with `-i`). 

But a tool that directly works with the specification would be preferable.

**Comment by omnidan** [comment]
this is actually very simple with the `dredd` tool: `dredd <path to apib file> <url of api>`

e.g. `dredd ./snippet-sharing.apib https://restapi.libelektra.org/`

**Comment by Namoshek** [comment]
It didn't turn out that easy if you have to consider authorization, etc. Very basic tests like verifying the output of the version resource worked fine, but more complex tests failed at my end. And the effort to make them work would have been too much (and adapting the blueprint for a test doesn't seem very good either).

**Comment by omnidan** [comment]
@Namoshek you can specify an authorization header (or any other header) to the dredd tool, so we would probably have to make a script that logs in with a test user and then specifies the authorization token via the `--headers` flag: https://dredd.readthedocs.io/en/latest/how-to-guides/#authenticated-apis

**Comment by markus2330** [comment]
@omnidan Can we close this issue? Can you maybe give some input how you finally tested the REST API?

**Comment by omnidan** [comment]
@markus2330 I used `dredd` to test the REST API and specified headers in the documentation
