### ISSUE TITLE
Object Libraries for builds

### ISSUE THREAD

**Issue by Namoshek** [ElektraInitiative/libelektra#934]
I'd suggest to use [Object Libraries](https://cmake.org/Wiki/CMake/Tutorials/Object_Library) in more places as they increase build speed a lot. An example where it should work without any problem would be the KDB tool.

The shared and full build are pretty much the same, except for the linking. So why compile the sources two times?

```
file (GLOB SRC_FILES *.cpp)
set (SOURCES ${SRC_FILES} ${HDR_FILES})

if (BUILD_SHARED)
	add_executable (kdb ${SOURCES})
	add_dependencies (kdb kdberrors_generated)

	target_link_libraries (kdb elektra-core elektra-kdb elektratools)

	install (TARGETS kdb DESTINATION bin)
endif (BUILD_SHARED)

if (BUILD_FULL)
	add_executable (kdb-full ${SOURCES})
	add_dependencies (kdb-full kdberrors_generated)

	target_link_libraries (kdb-full elektra-full elektratools-full)

	install (TARGETS kdb-full DESTINATION bin)
endif (BUILD_FULL)
```
should also work as
```
file (GLOB SRC_FILES *.cpp)
set (SOURCES ${SRC_FILES} ${HDR_FILES})

if (BUILD_SHARED OR BUILD_FULL)
	add_library (kdb-tmp OBJECT ${SOURCES})
endif (BUILD_SHARED OR BUILD_FULL)

if (BUILD_SHARED)
	add_executable (kdb $<TARGET_OBJECTS:kdb-tmp>)
	add_dependencies (kdb kdberrors_generated)

	target_link_libraries (kdb elektra-core elektra-kdb elektratools)

	install (TARGETS kdb DESTINATION bin)
endif (BUILD_SHARED)

if (BUILD_FULL)
	add_executable (kdb-full $<TARGET_OBJECTS:kdb-tmp>)
	add_dependencies (kdb-full kdberrors_generated)

	target_link_libraries (kdb-full elektra-full elektratools-full)

	install (TARGETS kdb-full DESTINATION bin)
endif (BUILD_FULL)
```

@markus2330 mentioned something about plugins, but when I search the repository with `add_library OBJECT` I only get two results that don't look like they were related to our CMake code. Or is there also another syntax to generate such object libraries?

**Comment by Namoshek** [comment]
> Your suggestions nearly is a PR already: I would only suggest to use the name -objects instead of -tmp for consistency reasons. Can you wrap it up in a PR so that the build server can check it?

Will do so! I just wrote down my idea, it is untested so far (I had another build running anyway). I'll run it locally and then make a PR.

> No, there is no other syntax, but the usage in cmake/Modules/LibAddPlugin.cmake makes an object library for every plugin (in the same way you suggested for the kdb tool), so indirectly we use it intensively already. 

Ok, got it.

> The object libraries do not work for the static variant, because in this case `-fPIC` is needed.

Yes, I saw it while writing the example for KDB, but I think even the other change saves some seconds (I think KDB is the tool that takes the longest to compile on my machine).

> Btw. you can also avoid compiling every variant by unselecting BUILD_FULL or BUILD_SHARED.

Absolutely! It was primarily meant for the build servers that have to check everything.

**Comment by markus2330** [comment]
Seems to be difficult to gain here something worth the effort. Please reopen if you have further ideas.
