### ISSUE TITLE
Mount system fails

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#953]
# Describe what you wanted to do

Mount backend to system

# Describe what you expected

It should mount to system

# Describe what actually happened

```
$ kdb mount system.dump system
The command mount terminated unsuccessfully with the info:
Given mountpoint is not a valid keyname, will abort
Examples: system/hosts or user/sw/app
```

# System Information

- Elektra Version: master

**Comment by KurtMi** [comment]
The error comes from a exception thrown here:

    src/libs/tools/src/backend.cpp:410
```
Key restrictedPath ("system/elektra", KEY_END);
...
if (restrictedPath.isBelow (k)) throw MountpointInvalidException ();
```
It seems `keyIsBelow` is broken. `system` is not below `system/elektra`.

**Comment by KurtMi** [comment]
No bullshit the cpp bindings are wrong.
```
inline bool Key::isBelow (const Key & k) const
{
	int ret = ckdb::keyIsBelow (k.getKey (), key);
	if (ret == -1) return false;
	return ret;
}
```

Doc of keyIsBelow:
```
* @retval 1 if check is below key
* @retval 0 if it is not below or if it is the same key
```
checking for -1 is wrong.

**Comment by KurtMi** [comment]
@markus2330 I have to leave now, i hope this helps :)
I tried the `ret == 0` but it does not worked

**Comment by markus2330** [comment]
Thanks, should be easy to fix!

**Comment by tom-wa** [comment]
thats a documentation error. `keyIsBelow` returns -1 if an argument is NULL. (i'll create a PR with a fix + updated comments)

`restrictedPath.isBelow (k)` can only be true for `system` anyway

is there a reason why `system` is forbidden here ?

**Comment by markus2330** [comment]
No, its a bug, it should be the other way round, mountpoints below system/elektra should be forbidden.

**Comment by markus2330** [comment]
Strange that the checks are distributed among setMountpoint and serialize

**Comment by markus2330** [comment]
Thanks for the hints! I removed the left-over check which was wrong and was not needed.
