### ISSUE TITLE
make run_all might remove keys

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#958]
# Describe what you wanted to do

Run `make run_all`
# Describe what you expected

That the key database is unmodified.
# Describe what actually happened

Some keys are removed (e.g. `user/sw/dfc/`).

It happens somewhere around

```
115/148 Test #115: testshell_hosts ....................   Passed    9.13 sec
        Start 116: testshell_db_changes
116/148 Test #116: testshell_db_changes ...............   Passed    5.25 sec
        Start 117: testshell_mathcheck
```
# System Information
- Elektra Version: master

**Comment by KurtMi** [comment]
@markus2330 I created some keys starting with `user/sw/dfc/` but i can not reproduce it. Do you have more information?

**Comment by markus2330** [comment]
Seems to be related to some mountpoints...

**Comment by markus2330** [comment]
Thanks for checking!

**Comment by tom-wa** [comment]
shell_recorder does:
```
"$KDBCOMMAND" export $Mountpoint > "$TMPFILE" 2>/dev/null
"$KDBCOMMAND" rm -r $Mountpoint 2>/dev/null
```
and
```
"$KDBCOMMAND" rm -r "$Mountpoint" 2>/dev/null
"$KDBCOMMAND" import "$Mountpoint" 2>/dev/null < "$TMPFILE"
```

is there any chance that a key is lost here ?

**Comment by markus2330** [comment]
Depends on the Mountpoint and the export format, but yes, could be.

**Comment by tom-wa** [comment]
`dump` should be safe i guess ? 
i don't think there would be an other way to do it, but i guess we should split the shell_recorder testcases into `internal_only` and normal testcases.

**Comment by markus2330** [comment]
What means internal_only? So are there test cases that remove data?

We also can mention it in the release notes, without fixing it.

**Comment by tom-wa** [comment]
>What means internal_only?

Testcases that could tamper with existing data / mountpoints. there might be some use cases where you would want to write such a testcase but for internal testing only

>So are there test cases that remove data?

currently checking

**Comment by tom-wa** [comment]
can't reproduce. `db_changes.esr` seems like the only test that might cause some problems because it works directly under the `user` mountpoint

**Comment by markus2330** [comment]
Ok, let us fix it in the next release

**Comment by markus2330** [comment]
It seems also to add new keys, e.g. add a tracer to global plugins

**Comment by markus2330** [comment]
The issue is quite annoying, it wipes out quite many keys.

Please try to create some mountpoints and keys below `user`.
