### ISSUE TITLE
warn: unrecognized inline tag: "img"

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#960]
The build process (most likely the docu) outputs:

```
warn: unrecognized inline tag: "img"
warn: unrecognized inline tag: "img"
```

Any ideas?

**Comment by KurtMi** [comment]
is this while the latex build?

**Comment by KurtMi** [comment]
I found out that `make man` produces this output

**Comment by KurtMi** [comment]
It seems that `ronn` can not do anything with markdown images , tables and to small headlines.
Btw I fixed the to small headline in the master bba764c819844eb29b0c2ebea180b9df07a7bdfb

**Comment by markus2330** [comment]
Thank you! But where are these img tags? Not in doc?

**Comment by KurtMi** [comment]
It can be that there is a html step between markdown to man generation. But I am not sure.

**Comment by markus2330** [comment]
I do not see these warnings anymore.
