### ISSUE TITLE
open intercept tutorial

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#966]
open intercept tutorial only outputs `testfile`, did the rename break something?

**Comment by markus2330** [comment]
@tom-wa Or is some relevant parent key missing (I am using dump)

**Comment by tom-wa** [comment]
for me it always outputs `testreplacement`, so seems like it's a missing key in your case and i'm going to investigate why it doesn't generate the config for me

**Comment by markus2330** [comment]
Thanks!

**Comment by tom-wa** [comment]
there was a typo in the example, but otherwise it works fine for me with `dump`

**Comment by markus2330** [comment]
Which typo?

**Comment by markus2330** [comment]
Thanks!
