### ISSUE TITLE
Lookup should not modify KeySet

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#972]
Currently, ksLookup modifies the KeySet when a not-present default is returned. This would be harmful with a hashmap present, so we need alternative solutions:

1.) Already add the default keys during `kdbGet` and only calculate the values during `ksLookup`.
2.) Put the default keys at the end/beginning of the keyset and exclude them from the hashmap.

**Comment by markus2330** [comment]
Should be fixed via default value calculation.

**Comment by markus2330** [comment]
Now we only need to remove the code creating the keys within ksLookup to complete this proposal.

**Comment by markus2330** [comment]
Now we only need to remove the code creating the keys within ksLookup to complete this proposal.

**Comment by KurtMi** [comment]
> Now we only need to remove the code creating the keys within ksLookup to complete this proposal.

I assume code creating the keys refers to the `elektraLookupBySpecDefault (...)` function.
Does the default value creation needs to be switched on in some way? Because removing the function leads to failing test cases.

**Comment by markus2330** [comment]
The spec plugin needs to be present (which should be the case by default). Maybe the spec plugin is buggy and does not always create default keys or it creates them by looking them up. Seems like we need a change in the spec plugin, too.

Is it possible for you to invalidate the hash map during ksLookup? Such a feature seems to be necessary anyway (for KDB_O_POP) and might also be interesting for user-supplied hooks. For performance reasons users obviously should always avoid changes of KeySets in ksLookup hooks but it seems to be expensive to guarantee that a hook did not modify the KeySet (at least if we would use run-time checks).
