### ISSUE TITLE
clang build warnings

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#978]
# Problem

clang reports build warnings:

    /Users/travis/build/ElektraInitiative/build/src/include/kdberrors.h:42:138: warning: token pasting of ',' and __VA_ARGS__ is a GNU extension [-Wgnu-zero-variadic-macro-arguments]

The warnings occur on multiple occasions:

- kdberrors.h:42:138
- kdbassert.h:34:120

Also there is a missing header-include:

    In file included from /Users/travis/build/ElektraInitiative/libelektra/src/libs/elektra/keyset.c:32:
    /Users/travis/build/ElektraInitiative/libelektra/src/include/kdbassert.h:34:120: warning: token pasting of ',' and __VA_ARGS__ is a GNU extension [-Wgnu-zero-variadic-macro-arguments]
    #define ELEKTRA_ASSERT(EXPR, ...) ((EXPR)) ? (void)(0) : elektraAbort (STRINGIFY (EXPR), __func__, __FILE__, __LINE__, ##__VA_ARGS__)
                                                                                                                           ^
    /Users/travis/build/ElektraInitiative/libelektra/src/libs/elektra/keyset.c:1531:6: warning: implicitly declaring library function 'snprintf' with type 'int (char *, unsigned long, const char *, ...)' [-Wimplicit-function-declaration]
            if (snprintf (&newName[index], ELEKTRA_MAX_ARRAY_SIZE, ELEKTRA_LONG_LONG_F, newIndex) < 0)
                ^
    /Users/travis/build/ElektraInitiative/libelektra/src/libs/elektra/keyset.c:1531:6: note: include the header <stdio.h> or explicitly provide a declaration for 'snprintf'
    2 warnings generated.

**Comment by markus2330** [comment]
Thanks for reporting! Is a (very) easy fix, but only if you know how kdberrors.h is generated ;)
