### ISSUE TITLE
key/values in latex comments

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#982]
I have here some files where key/values are in special comments (`%:`), e.g.

```
\section{foo}
Text of document.
% irrelevant comment
%:key value
Some text
%:key muli value
Further text
```

What do you think is the best way to support such special cases without creating yet another special plugin?

**Comment by sanssecours** [comment]
> What do you think is the best way to support such special cases without creating yet another special plugin?

I do not know about best, but these are the current options I can think of:

1. Write an Augeas lens for the specified format
2. Convert the file to a format that Elektra understands; For example, the following Ruby program converts the string `text` to the INI file format:

  ```ruby
  require 'inifile'

  text = '\section{foo}
  Text of document.
  % irrelevant comment
  %:key value
  Some text
  %:key muli value
  Further text'

  KEY_MARKER = '%:'.freeze

  ini_file = IniFile.new

  lines = text.lines.select { |line| line.start_with?(KEY_MARKER) }.map(&:rstrip)
  keys_values = lines.map do |line| 
    line.scan(/#{KEY_MARKER}([\w]+)\s+(.+)/) 
  end.flatten

  ini_file['user/latex'] = Hash[keys_values.each_slice(2).to_a]
  print(ini_file)
  ```
  
  Below is the output of the command:

  ```
  [user/latex]
  key = muli value
  ```

3. Write a “general purpose” storage plugin; This plugin could for example use the arguments (regular expressions) listed below.
  
  1. `Marker`: This regular expression specifies a special token that marks the line that contains a key. In our example this would be `%:`
  2. `Key`: This value specifies the key. In our example this would be `\w+`
  3. `Separator`: This value specifies the part between key and value. In our example this would be `\s+`
  4. `Value`: This regex specifies the value of the key. The key starts right after the separator. In our example we could use the regex `[^\n]+` or `.+`.

**Comment by markus2330** [comment]
Thanks for the input!

1. To have a nice abstraction, the lenses usually would need some post-processing, specifically some transformations from augeas-arrays to well-named keys.

2. That would only work in one direction? And why not directly write the storage plugin in ruby? (Except that the binding is not ready) Currently this seems to be the easiest option for such simple formats.

3. That is an interested idea, it would be kind of a restricted lens for key/value data. Would be great to have it and see if it really can do better than lenses for such cases.

Further options are:

4. Change grammar of tcl plugin.

5. Modify simpleini plugin to work with different strings. (Would need some additional logic to ignore lines not starting with `%:`)

6. regexstore (is read-only, however)

**Comment by sanssecours** [comment]
> That would only work in one direction?

Yes.

>  And why not directly write the storage plugin in ruby?

I did not know that this was possible. Also I don’t know that much about writing a storage plugin yet. I just wrote the Ruby code, since parsing the LaTeX document above seemed to be a simple and interesting task.

**Comment by markus2330** [comment]
> I did not know that this was possible.

Only something like the [lua plugin](https://github.com/ElektraInitiative/libelektra/tree/master/src/plugins/lua) or [python plugin](https://github.com/ElektraInitiative/libelektra/tree/master/src/plugins/python) is missing, then it should work together with @BernhardDenner binding.

> above seemed to be a simple and interesting task.

Running your code as pregetstorage plugin would be a possibility but I am afraid a simple way for doing so is also missing: The shell plugin can execute external processes (like `ruby yourscript`) but it does not pass the file name of the config file.

Having a wrapper that implements the ruby-`inifile` API with Elektra (writing to a KeySet) would make your ruby code a storage plugin, too.

**Comment by markus2330** [comment]
I added support for configurable formats in simpleini. With `format=%%:% %` now (46c584facbe026db24411eae1b882f35934656d8) such files can be parsed but there are many restrictions in simpleini.
