### ISSUE TITLE
test cases fail with ENABLE_DEBUG

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#988]
A lot of problems to fix:
http://community.markus-raab.org:8080/job/elektra-incremental/1157/console

**Comment by markus2330** [comment]
@tom-wa Seems like ini plugin allocates zero bytes, do you really need this? (The behavior is implementation defined, you might get a pointer or NULL).

**Comment by tom-wa** [comment]
what exactly is the issue here / whats left to do ?

**Comment by markus2330** [comment]
Check if ENABLE_DEBUG works on other systems (clang, OpenBSD, ...).

**Comment by tom-wa** [comment]
works fine on OpenBSD and Linux, can't run any other tests atm because my hdd with my VMs/BuildEnvs died.
