### ISSUE TITLE
Rename license file to `LICENSE`

### ISSUE THREAD

**Issue by eschnett** [ElektraInitiative/libelektra#995]
The license file is currently called `COPYING`. This is confusing, as this is usually only the case when using the GPL as license, not for a BSD license. Also, several automated tools that expect the file name `LICENSE` or `LICENSE.md`.

**Comment by markus2330** [comment]
Thanks for reporting! You are right, it is confusing and it might be an old artifact caused by changing the licence in the beginning of Elektra.
